### ISSUE TITLE
Automapping follow-ups (error message and documentation)

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1001]
Follow up of #60:

- [x] create a dotted path notation for error messages where nested properties can't be mapped automatically
- [x] Adapt reference documentation
- [ ] Add entry to migration notes to note that there won't be an error message in case nested properties can be mapped automatically
- [x] ~~Make sure that configuration from prototype methods in `@MapperConfig` classes are applied to forged methods (I think that's currently not the case and never has been -- but we should tackle that soon as it becomes more important now).~~ This is now #1086
- [x] Align ForgedMethods with current ForgeMethod approach. ForgedMethods should not be properties on BeanMapping and PropertyMapping. The name should be generated based on the uniqueness of the method. See also discussions in #1011. A testcase should be added to verify this truly works (e.g. forcing the same name, with different property mappings). This could be done for instance by taking a DTO with the same name from different packages. 
- [x] `TestMultipleForgedMethodsTest` needs to do some assertions: create proper input data and assert the results. Rename the test class itself (`Test*Test`) and rename the classes `Bar`, `BarDto`, `Dto`... :)
- [x] Should work for update methods too

**Comment by navpil** [comment]
How should we continue on this?
I already have some changes, which work, but they break some tests, which assume another format of the error message. But before I fix those tests I'd better know that the format I chose is the correct one. Should I do the PR with some tests failing so you can look at the current implementation (I have a dedicated test for these error messages)? Should we discuss it in the google group? Should we discuss it here?

**Comment by agudian** [comment]
I'd say open a new PR right away and we can discuss it there directly with the modified code and the failing tests visible to all of us... :)

**Comment by gunnarmorling** [comment]
>
> I'd say open a new PR right away and we can discuss it there directly with
> the modified code and the failing tests visible to all of us... :)
>
+1

**Comment by agudian** [comment]
I've added another point about the test class `TestMultipleForgedMethodsTest` that I just stumbled upon... It looks a bit unfinished... 😉

**Comment by sjaakd** [comment]
> Make sure that configuration from prototype methods in @MapperConfig classes are applied to forged methods (I think that's currently not the case and never has been -- but we should tackle that soon as it becomes more important now

I really like this idea. I'm more and more moving to a `SharedConfig` pattern. Form that I refer from my mappers. E.g. a merge mapper, from dto -> entity, a create mapper, from dto -> entity, a reverse mapper from entity -> dto. In principle, all I need than is an object-graph top level method in my mapper and `MapStruct` with the shared config will generate the stuff with automapping. PR #1046 introduces `MappingConfig` in forged methods, so this should after this one be low-hanging-fruit.

**Comment by gunnarmorling** [comment]
Closing to have the milestone clean for the announcement. @sjaakd could you add something to the migration notes?

**Comment by brabenetz** [comment]
I played a little with 1.2.0-Beta1 feature Automapping-generation. And found two test-cases which doesn't work:

1. Recursive Mappings can produce a compiler crash "Internal error in the mapping processor: java.lang.StackOverflowError":
[MapStructRecursionMapper.java.txt](https://github.com/mapstruct/mapstruct/files/801300/MapStructRecursionMapper.java.txt)

2. enums are not Mapped (Error "Consider to declare/implement a mapping method: ..."):
[MapStructEnumMapper.java.txt](https://github.com/mapstruct/mapstruct/files/801301/MapStructEnumMapper.java.txt)

**Comment by gunnarmorling** [comment]
@brabenetz Thanks for the report. Could you open two new issues for these problems? Thanks!

**Comment by brabenetz** [comment]
Sure, I created #1102, #1103, #1104
