### ISSUE TITLE
Cleanup the code duplication between the Stream and Iterable support

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1012]
- [x] In `MapperCreationProcessor` creation of `IterableMappingMethod` and `StreamMappingMethod` are really similar. Extract a common Builder for the mapping methods and reuse as much as possible the code
- [x] The `StreamMappingMethod` and the `IterableMappingMethod` are almost identical, extract some common class between the two

**Comment by gunnarmorling** [comment]
Done.
