### ISSUE TITLE
Map to entry which has more fields

### ISSUE THREAD

**Issue by Volodymyr128** [mapstruct/mapstruct#1030]
I have:

```
public class MyEntity {
  private Long id;
  private String value;
}

public class MyDTO {
  private Long id;
  private String value;
  private AnotherObject anotherObject;
}
```

Question: how to map MyDTO (with null anotherObject prop) from MyEntity?

**Comment by agudian** [comment]
```java
@Mapper
public interface MyMapper {
    MyDTO toMyDTO( MyEntity entity );
}
```

By default, MapStruct will then give you a warning that the property `anotherObject` remains unmapped. You can either shut that warning off via `Mapper#unmappedTargetPolicy`, or explicitly ignore the property for the mapping (and thus documenting for yourself that the property won't be populated by that mapping method):

```java
@Mapper
public interface MyMapper {
    @Mapping( target="anotherObject", ignore = true )
    MyDTO toMyDTO( MyEntity entity );
}
```

Closing this, as it's a question. Feel free to comment if that doesn't help you.
