### ISSUE TITLE
un-mapped field

### ISSUE THREAD

**Issue by PFStruct** [mapstruct/mapstruct#1035]
I have a dto that has two fields. account and date opened. Using the mapper, I mapped only account and not the date opened. However the implementation is adding unmapped field as well. I apologize if this has been addresses before. Any input would be greatly appreciated.

**Comment by gunnarmorling** [comment]
Can you share your mapper definition and mapper types? Have you tried to
use @Mapping#ignore()?

**Comment by filiphr** [comment]
@PFStruct are the name of the date opened field same in the dto and the other object? If they are then MapStruct automatically maps them. If you don't want to map fields that have the same name you have to explicitly ignore them via `@Mapping#ignore()` like @gunnarmorling suggested.

**Comment by PFStruct** [comment]
I have not tried setting to ignore. I was thinking if it is not mapped, it will not map and we do not have to specifically ignore. here is the sample. 

public class LoanDTO extends TransactionList{
	protected String accountId;
	protected XMLGregorianCalendar payoffDate;

	 public String getAccountId() {
		return accountId;
	}
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}
	public XMLGregorianCalendar getPayoffDate() {
		return payoffDate;
	}
	public void setPayoffDate(XMLGregorianCalendar payoffDate) {
		this.payoffDate = payoffDate;
	}
}

	@Mappings({ 
		
		  
		  @Mapping(source = "accountNumber", target = "accountId")
		  
		})
	
	public abstract LoanDTO TranToAccount(Response pi);
		

 @Override
  public LoanDTO TranToAccount(Response pi) {
        if ( pi == null ) {
            return null;
        }

        LoanDTO  loanDTO = new LoanDTO();

        loanDTO.setAccountId( String.valueOf( pi.getAccountNumber() ) );
        loanDTO.setPayoffDate( stringToXmlGregorianCalendar( pi.getPayoffDate(), null ) );

        return loanDTO;
    }

**Comment by filiphr** [comment]
@PFStruct our replies were almost in the same time 😄.

For more information you can have a look at [Basic Mappings](http://mapstruct.org/documentation/1.1/reference/html/index.html#basic-mappings) from our documentation. 

This paragraph explains how the mapping is done:

>In the generated method implementations all readable properties from the source type (e.g. Car) will be copied into the corresponding property in the target type (e.g. CarDto). If a property has a different name in the target entity, its name can be specified via the @Mapping annotation.

If it is OK for you I will close the issue

**Comment by PFStruct** [comment]
Absolutely! Thank you for quick response.
