### ISSUE TITLE
Nested objects, when mapped, don't first `get` the existing object

### ISSUE THREAD

**Issue by snowe2010** [mapstruct/mapstruct#1036]
https://github.com/snowe2010/ExampleOfErasingNestedParameters

Example of a secondary, untouched, object being overridden because a new instance is generated instead of retrieved from the currently existing object.

**Comment by snowe2010** [comment]
duplicate #1011

**Comment by sjaakd** [comment]
Lets track this as part of #1011 . Thanks.
