### ISSUE TITLE
@Mapping generates compilation errors on Maven/Netbeans

### ISSUE THREAD

**Issue by olabomba** [mapstruct/mapstruct#1040]
Hi,
I'm using jhipster, which generates mapstruct mappings.
I've errors on certain fields (not all of them), if they have multiple @Mapping annotation. Only in the EDI. All building process, by maven, is OK.
The error is : "Incompatible types: int cannot be converted to boolean".
Have you any idea ?
Thanks,
Regards.

**Comment by filiphr** [comment]
@olabomba can you please give us examples and/or screenshots from Netbeans that are displaying the error. 

As @gunnarmorling said: Can you also add the definition of the mapper interface (or maybe a
screenshot indeed if it only happens within NetBeans). Thanks!

**Comment by olabomba** [comment]
Hi,
Here it is: 
![capture d ecran du 2017-01-09 18 32 14](https://cloud.githubusercontent.com/assets/1215055/21776268/0970e664-d69a-11e6-9efa-b12dd38dd322.png)

I haven't the issue in Eclipse.

**Comment by filiphr** [comment]
@olabomba can you check which Java 8 version NetBeans uses compile your code? I don't think that this issue is related to MapStruct

**Comment by olabomba** [comment]
NetBeans uses openjdk version "1.8.0_111".

Some methods are good, as you can see in the previous capture (productToProductDTO).

**Comment by gunnarmorling** [comment]
Do you have some kind of error view or log file in NetBeans where you could see the full stack trace? @sjaakd, mabe you have a pointer where to find that in NetBeans?

**Comment by agudian** [comment]
Does `Product` by any chance have more than one  setter for `pictures`?

**Comment by olabomba** [comment]
@filiphr : I've switched to Oracle's one (java version "1.8.0_111") : same issue.

@gunnarmorling, No trace in View > IDE log. I don't know where I could find a better trace.

**Comment by agudian** [comment]
Or is there another property with more than one setter?

**Comment by olabomba** [comment]
@agudian only one setter by property ; all these properties are generated by jhipster, which is very clean.

I've just saw this strange behaviour:

![capture d ecran du 2017-01-09 19 02 53](https://cloud.githubusercontent.com/assets/1215055/21777298/82d71f2e-d69e-11e6-8eb8-3f67c2261281.png)
=> OK

![capture d ecran du 2017-01-09 19 03 12](https://cloud.githubusercontent.com/assets/1215055/21777303/8a856abe-d69e-11e6-9042-46f6d7b5ef93.png)
=> OK

![capture d ecran du 2017-01-09 19 03 26](https://cloud.githubusercontent.com/assets/1215055/21777313/91dfc188-d69e-11e6-8731-ac4b799fc598.png)
=> KO

Maybe not a strict MapStruct issue (I don't know), but I appreciate your help :)

**Comment by filiphr** [comment]
Can you try
```java
@Mappings({
//here your 2 mappings
})
```
And tell us which artifacts from mapstruct are you depending on?

**Comment by sjaakd** [comment]
Have you tried in NB, menu source, scan-for-external-changes?

**Comment by sjaakd** [comment]
Another option is to clean your netbeans cache. I usually rename it to cache.old.

**Comment by olabomba** [comment]
@sjaakd : no result for your proposals

@filiphr, OK, it works !

![capture d ecran du 2017-01-09 19 33 29](https://cloud.githubusercontent.com/assets/1215055/21778182/ac119e60-d6a2-11e6-8007-7d6c4529040b.png)

**Comment by olabomba** [comment]
I don't know why it is needed for the mapping of productDTOToProduct, and not for productsToProductDTOs, but thanks !

**Comment by filiphr** [comment]
@olabomba the problem is that you most probably have a dependency on [core mapstruct](http://mvnrepository.com/artifact/org.mapstruct/mapstruct) and not on [jdk-8 mapstruct](http://mvnrepository.com/artifact/org.mapstruct/mapstruct-jdk8). The core mapstruct does not have support for Java 8 `@Repeteable` mappings.

It is indeed strange why it works for one and not for the other. Can you just tell use which mapstruct artifact are you using?

**Comment by olabomba** [comment]
The maven dependencies I use are: mapstruct, mapstruct-jdk8, mapstruct-processor (in 1.1.0.Final)

**Comment by filiphr** [comment]
You shouldn't be using mapstruct and mapstruct-jdk8 in the same time. Either mapstruct or mapstruct-jdk8.  Can you try excluding mapstruct and see if your initial configuration works?

**Comment by olabomba** [comment]
Hi, sorry, I made a "grep".
The mapstruct is already excluded (the entry I found was an exclusion).
So, the maven dependencies I use are only: mapstruct-jdk8, and mapstruct-processor (in 1.1.0.Final)
It's not the explanation we are looking for..

**Comment by agudian** [comment]
NetBeans runs the compilation using `mvn`, right? Is there a way to configure it to pass `-X` to the build, which enables the maven debug output?

**Comment by sjaakd** [comment]
> @sjaakd, mabe you have a pointer where to find that in NetBeans?

http://wiki.netbeans.org/FaqLogMessagesFile

In the IDE itself:
window >> IDE Tools >> Exception Reporter 
window >> IDE Tools >> Notifications

**Comment by sjaakd** [comment]
> NetBeans runs the compilation using mvn, right? Is there a way to configure it to pass -X to the build, which enables the maven debug output?

Only if its indeed a maven project. Not when its a NB project (believe it uses ant under water).

**Comment by olabomba** [comment]
@sjaakd both (Exception Reporter, Notifications) are empty

**Comment by sjaakd** [comment]
@olabomba : is it indeed a maven project, or a native netbeans project?

**Comment by olabomba** [comment]
@sjaakd it's a maven project.
