### ISSUE TITLE
boolean  conversion 

### ISSUE THREAD

**Issue by plzeng** [mapstruct/mapstruct#1041]
When i conversion boolean it  default use Boolean.valueOf, If value is null i still got false . I hope when i use 
Boolean with type of packaging, can return a null value.

**Comment by filiphr** [comment]
I don't quite understand what the problem is. Where do we use `Boolean#valueOf()`? Can you show us an example of your mapper?

**Comment by sjaakd** [comment]
@plzeng : can you provide an example so that we can reproduce it? I'll proceed to close this issue later this week when we lack a reproducer.

**Comment by plzeng** [comment]
Sorry this is my problem, I do not have the correct use.I have resolved .Thanks for your help.
