### ISSUE TITLE
Can't map nested properties inside a dependency jar

### ISSUE THREAD

**Issue by jianyuz** [mapstruct/mapstruct#1043]
I have a wrapper class that wraps the hibernate entity class which in turn holds other entity objects. The hibernate entity class is in a dependency jar
When I tried to map the tested property from the wrapper class, the following error is reported.

"The type of parameter "xxxwrapper" has no property named "xxa.xxb.xxc"."
Mapping the nested property from the top of the entity class, however, works fine.

**Comment by agudian** [comment]
Can you provide an actual example of the mapper definition and the related classes, please?
The fact that the entity classes come from another jar shouldn't be of any concern here.

**Comment by sjaakd** [comment]
@jianyuz : is it possibly to provide an example as @agudian requests? Otherwise I'll proceed to to close this issue

**Comment by sjaakd** [comment]
@jianyuz , I'll close this issue. We don't have sufficient info. You can always re-open and provide feedback.
