### ISSUE TITLE
Mapstruct doesn't work when either the DTO or the model is generated code.

### ISSUE THREAD

**Issue by andrei-taras** [mapstruct/mapstruct#1045]
My DTOs are generated. 
Whenever I perform a clean in Eclipse (i.e. my generated DTOs get deleted), and MapStruct processor kick in first, then it sees that my DTOs don't exist yet, and it fails via  org.mapstruct.ap.internal.model.common.TypeFactory, line 141 (in release 1.1.0.Final)

`    
public Type getType(TypeMirror mirror) {
        if ( mirror.getKind() == TypeKind.ERROR ) {
            throw new AnnotationProcessingException( "Encountered erroneous type " + mirror );
        }
        ...
}
`

If I copy/paste the code in org.mapstruct.ap.MappingProcessor, and do the following changes (the catch clause : don't signal error, but throw a softer exception), it works (i.e. ignore all AnnotationProcessingException 's and leave the erroneous annotated code to be processed in the next round)
`    private void processMapperTypeElement(ProcessorContext context, TypeElement mapperTypeElement) {
        Object model = null;

        for ( ModelElementProcessor<?, ?> processor : getProcessors() ) {
            try {
                model = process( context, processor, mapperTypeElement, model );
            }
            catch ( AnnotationProcessingException e ) {
            	// Don't throw any more errors. Just delegate to the next round
            	throw new TypeHierarchyErroneousException(mapperTypeElement); 
            }
        }
    }`

**Comment by agudian** [comment]
How are your DTOs generated and what does your pom look like?

**Comment by andrei-taras** [comment]
My DTOs are generated through custom-written annotation processors.
The mapstruct dependencies that I use are:
`
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.1.0.Final</version>
        </dependency>
        
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>1.1.0.Final</version>
            <scope>provided</scope>
        </dependency>
`

Please note that this problem reproduces ONLY when generating "from scratch" (i.e. after during a clean in Eclipse). If my DTOs already exist (for example when mapstruct processor runs as a result of a file modification, and not during Eclipse/clean), it works as expected.

**Comment by gunnarmorling** [comment]
I'll take a look; I think I can provide a fix with my work for #510.

**Comment by gunnarmorling** [comment]
Hey @andrei-taras, this should be fixed by my PR #1042. Any chance you check out that PR's branch, build the MapStruct processor (`mvn clean install -pl processor -am`) and test it with your own annotation processor?

**Comment by andrei-taras** [comment]
Hey, @gunnarmorling , thanks for the fix.
I tested it, and it works.

**Comment by andrei-taras** [comment]
Sorry, perhaps not the best place to ask this question (but don't know of other more suited for this).
But do you know if/when this fix gets released ?

**Comment by gunnarmorling** [comment]
@andrei-taras, this is planned for the Beta1 of MapStruct 1.2 which is due in the next few days.

**Comment by gunnarmorling** [comment]
Fix is merged to master.
