### ISSUE TITLE
MappingMethods refactoring

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1050]
We need to extract as much as possible up to the `MappingMethod`. Candidates here are the equals and hashcode methods.

We also need to make sure that the `BeanMappingMethod` does not extend the `ContainerMappingMethod` (the idea of this method is to be used for `MappingMethods` similar to the `IterableMappingMethod` and `StreamMappingMethod`. Methods that are wrapping some underlying type in generics) introduced in #1046

**Comment by sjaakd** [comment]
Perhaps change the name as well. `ContainerMappingMethod` . A bean mapping method can also take and return generic parameterized types.

**Comment by sjaakd** [comment]
@filiphr .. I think this one can be closed, right?

**Comment by filiphr** [comment]
Well we still need to make sure that the `BeanMappingMethod` does not extend the `ContainerMappingMethod`. I just saw that your last merge had it still in. I will make a PR for it

**Comment by filiphr** [comment]
Done
