### ISSUE TITLE
Automapping should work for nested generics

### ISSUE THREAD

**Issue by navpil** [mapstruct/mapstruct#1051]
Suppose we have `User `and `UserDto` which can be automapped.
Automapping can handle the `List<User>` to `List<UserDto>` conversion.
But `List<List<User>>` to `List<List<UserDto>>` will not be mapped and an error will be shown.

Automapping should be able to handle nested generics.

The likely reason behind it is that we forge iterable/stream/map mappings only in the `PropertyMapping` class, but not in the `MapMappingMethod` or `IterableMappingMethod`.

**Comment by navpil** [comment]
#1001

**Comment by filiphr** [comment]
I think that this is similar as #922 . If we add general support for collections within collections and/or collections as keys / values in maps, then this will work. 

If we generate forged methods for such generics within the `MapMappingMethods` and / or the `IterableMappingMethod` then it should work.

**Comment by navpil** [comment]
@filiphr yes, you're right. I think this issue may be considered a duplicate.

**Comment by filiphr** [comment]
Great. I am marking it as duplicate, it is already linked with the duplicate and I have added the duplicate to the Future Planning milestone.
