### ISSUE TITLE
(componentModel = "spring") and @autowired

### ISSUE THREAD

**Issue by PFStruct** [mapstruct/mapstruct#1055]
I apologize in advance as I am fairly new to using mapstruct. I have a mapper class with (componentModel = "spring") . When I run in eclipse MVN or STS plugin, application initailized correctly. When I try to deploy it to the external tomcat, I get "Consider defining a bean in your configuration." So @Autowired is not working. So what am I missing? Appreciate any help.

**Comment by filiphr** [comment]
Is your war correctly packaged? Is the error occurring during the generation of the implementation mappers, or some of your classes?

**Comment by gunnarmorling** [comment]
Hey @PFStruct, I'm going to close this one as there is hardly anything we can do to help without knowing further issues. If the problem still isn't fixed, please send a mail to the [mapstruct-users](https://groups.google.com/forum/#!forum/mapstruct-users) list with a complete reproducer of the issue. Thanks!
