### ISSUE TITLE
Provide a switch to turn off CheckStyle on generated sources

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1064]
The CheckStyle run for the generated sources consumes a considerable amount of time. Disabling it in the code (`CompilingStatement`) cuts down build time from 2 minutes to 1 minute for the processor module for me. Hence having an option to turn it off would be highly desirable, ideally it'd be just controlled via the existing option `-Dcheckstyle.skip=true`.

**Comment by Captain1653** [comment]
@gunnarmorling It can be little late :), but.. Maybe I will say something stupid, but did you try the standart configuration parameters of checkstyle? https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#skip 

I mean: skip, resourceexcludes, excludes and ext. I think it can be done with these parameter, but maybe I'm wrong.

**Comment by gunnarmorling** [comment]
Hey, I don't quite remember the details, as it's long time ago :) I think
CheckStyle is invoked programmatically by the MapStruct testing harness, so
the existing options of the CS Maven plug-in won't be applied.

>

**Comment by filiphr** [comment]
Yes the checkstyle is invoked as part of the [`CompilingStatement`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingStatement.java). There is `assertCheckstyleRules` method that does the job.

We added an annotation for disabling the check as well. [`@DisableCheckstyle`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/testutil/compilation/annotation/DisableCheckstyle.java). In theory we could check for a system property.

Btw, @Captain1653 if you are interested in more contributions let me know and we can have a chat. There are some issues assigned to the 1.4.0 milestone, some marked as [up-for-grabs](https://github.com/mapstruct/mapstruct/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs), [good first issue](https://github.com/mapstruct/mapstruct/issues?q=is%3Aopen+is%3Aissue+label%3A"good+first+issue") or just any issue in our tracker. Feel free to pick something that peaks your interest, or if something is not there and you think that it would be a good addition create an issue and work on it 😄

**Comment by Captain1653** [comment]
@filiphr Yes, I interest. We can have chat, my email is in my profile.
