### ISSUE TITLE
Extract functionality from ContainerMappingMethod and NormalTypeMappingMethod into composition

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1066]
As a follow up on #1058 in order to reduce the inheritance chain we can extract the functionality in the 2 mentioned methods into a composition.

**Comment by Obolrom** [comment]
@filiphr, it seems this issue can be closed

**Comment by filiphr** [comment]
Good point @Obolrom. There is something more that could be done for this, but let's tackle that at some other itme
