### ISSUE TITLE
Add parameter for pre- and post-processing of a mapped object

### ISSUE THREAD

**Issue by twothe** [mapstruct/mapstruct#1067]
It would be great if there was a functionality to allow for pre-processing or post-processing of an object that is mapped to apply certain functionality to the input or result.

As an example take an incomplete object that is related to a database entity and requires fetching information from that database to complete the input object. Vice versa you could create a database entity from an (incomplete) source that afterwards requires fetching additional data from that database to be complete.

Currently that requires additional code to be written like:

    MyEntity entity = XMLToEntityMapper.INSTANCE.mapXMLToEntity(myXML);
    EntityService.fetchAdditionalData(entity);

**Comment by sjaakd** [comment]
You mean as in our [ref-guide](http://mapstruct.org/documentation/stable/reference/pdf/mapstruct-reference-guide.pdf) ch 11.2?

**Comment by twothe** [comment]
Indeed. Sorry for not finding that beforehand.
