### ISSUE TITLE
Add parameter for back-reference to parent

### ISSUE THREAD

**Issue by twothe** [mapstruct/mapstruct#1068]
Sometimes when converting classes you want  back-reference to the parent in a child class (double-linked). This is (to my knowledge) currently not possible wth MapStruct.

Example:

    class A {
      String myAValue;
      B child;
    }

    class B {
      int myBValue;
      A parent;
    }

A simple notation would be:

    B mapTOToB(BTO bTO, @ParentReference A parent);

In this case MapStruct could use the additional paremeter to pass the parent to this function. 
Downside would be that in case of complex structures, a lot of parents would have to be passed around. Maybe there is a better way to do that.

**Comment by sjaakd** [comment]
For code generation by Dali (Eclipse JPA code gen), we have collection strategies. Checkout our [ref-guide](http://mapstruct.org/documentation/stable/reference/pdf/mapstruct-reference-guide.pdf), ch 6.2

**Comment by twothe** [comment]
I see. However that leaves all non-collection sitiuations unhandles. Also deeper nesting wouldn't work, like: `A.B.C.parent = A`

**Comment by filiphr** [comment]
@twothe I am not sure I understand the problem. Are you talking about passing the parent reference to the mapping or converting it and avoiding cycles?

If it is the latter have a look at [this](https://github.com/mapstruct/mapstruct-examples/pull/16) pending PR in our examples repository.

Thanks to our new [`@Context`](https://github.com/mapstruct/mapstruct/blob/master/core-common/src/main/java/org/mapstruct/Context.java), I think that you can do something in the direction of `@ParentReference` annotation with the help of `@AfterMapping`, `@BeforeMapping` methods.

**Comment by twothe** [comment]
If I have a complex structure of objects I sometimes need a back-reference to the parent that holds that structure (or any parent in between). Double-linked lists are one exampled (which is covered if I understand you correctly) but you could easily construct a relation between objects of much higher complexity where that simple system will no longer work (A->B->C and then C should link to A as well).

Essentially to properly link such "more complex" constructs I would have to have a back-reference parameter during mapping. But since the mapping is generated I cannot just address an individual "parent" in between, therefore an option to pass parents of my choosing down to children would be nice to have to properly back-reference in such structures.

**Comment by sjaakd** [comment]
I believe @filiphr  is right. You could make an @Context object and add a parent object to it by means of `@AfterMapping` You could later fetch this parent object and use an `@AfterMapping` to fetch it and set your grand-parent -  grand-child relation. WDYT?

**Comment by twothe** [comment]
After reading through that Context thing I think that would solve the problem. Honestly I did miss that the first time I read your post, sorry for that.

I will give that a try and see if it solves my problem at hand.

**Comment by sjaakd** [comment]
@twothe . let us know. For questions we do also have a (user-group)[https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users]

**Comment by sjaakd** [comment]
@twothe . I close this issue in the mean while.

**Comment by twothe** [comment]
Sounds good. I have not yet had the time to test it, but I am confident it will work.

**Comment by twothe** [comment]
Turns out this is not yet released. I am eagerly awaiting 1.2 ;)

**Comment by remmeier** [comment]
is there maybe a chance to get this feature after all? having parent/child bi-directional references seems a  common use case. In our case we have a larger object graph with a single  root and all the other elements point to their parent.  Implementing it with `@Context` is possible, but involves quite a bit of boiler-plate. As alternative we also considered changing the getter/setters, but one still needs to ignores of the mapping target to pass verification and we would prefer to keep getters/setters simple.
