### ISSUE TITLE
Provide option to not add @Generated annotation

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1080]
When running on Java 9, using the `@Generated` annotation requires the addition of a separate module (_--add-modules java.xml.ws.annotation_). As that can be invonvinient, there should be a processor option to not add the `@Generated` annotation to generated mapper classes.

**Comment by agudian** [comment]
We currently leave it out automatically if the annotation is not available, for exactly that reason. Do we really want to add another option to control that manually as well?

**Comment by gunnarmorling** [comment]
Ah, I wasn't aware of this. That seems good enough then.

Btw. a new `@Generated` annotation may be added in Java 9 as per
discussions on jigsaw-dev this week. But nothing to act on yet.

**Comment by gunnarmorling** [comment]
Going to close this one for the time being.
