### ISSUE TITLE
Investigate why there are no property entries in the source reference

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1085]
In #1072 there is a TODO in the `NestedTargetPropertyMappingHolder`. It seems that it is possible that the property entries of a non-`null` valid `SourceReference` can be empty. Investigate why is that the case

**Comment by filiphr** [comment]
If the mapping is ignore, constant and/or expression then the `SourceReference` is `null`

**Comment by sjaakd** [comment]
and add meaningful comment why :smile:

**Comment by filiphr** [comment]
I know why they are empty. When we map the source parameter to some property then we have a valid `SourceReference` but no property entries 😄. See also PR #1248.


I'll close this one.
