### ISSUE TITLE
Improve test framework to support adding classes per package

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1089]
@agudian had a nice idea to add support for adding all classes to the compiler with the exception of *Test classes.

Additionally it might be interesting to thing in the direction to automatically add all classes recursively to the Test class. Maybe exclude **Erroneous** classes from the inclusion.

**Comment by sjaakd** [comment]
and perhaps add objects in sub-packages as well (such as `source` and `_target`).

**Comment by filiphr** [comment]
Closing since the current approach is acceptable for now
