### ISSUE TITLE
Nested target properties issue

### ISSUE THREAD

**Issue by JohnHoward9** [mapstruct/mapstruct#1090]
I have a mapping that consists of:
```
            @Mapping(source = "productDetail", target = "contents"),
            @Mapping(source = "allergens", target = "contents.allergens"),
```
Where productDetail is a class which has it's own mapping defined
`
    CatalogProduct.ContentsData toObject(CatalogProductDBO.DetailsData detailsData);`

I was hoping that the allergens mapping would use the ContentsData object created for the productDetail->contents mapping, but what is happening is that the generated code is creating two ContentsData objects, which results in the allergens not being mapped to the target object.

I have fix using decorator.  It would be good if this could be achieved through a mapping definition, but not sure there are many use cases other than our crazy data model

Great product BTW, just wish I'd discovered it 6 months ago

**Comment by sjaakd** [comment]
@JohnHoward9 , I'm a bit struggling with your example. 

> Where productDetail is a class which has it's own mapping defined

Do you mean there is a mapping inside productDetail taking care of some mappings? If that's the case, you should add it to your uses. 

There are 'ignore' options as well. It might be that you need to 'ignore' `allergens` in the `productDetail to content` mapping.. 

BTW: personally I like to flip source / target around in `@Mapping`. Reads easier because the method also starts with the return type (target). 

The upcoming MapStruct (tomorrow night beta) improved the nested targets quite considerably.

It would be good if you could provide a more complete  (if required anonymized) example as gist or in this issue.


> Great product BTW, just wish I'd discovered it 6 months ago

Thanks!

**Comment by JohnHoward9** [comment]
Thanks for guidance.  I've just started working with mapStruct this weekend, so any input is most welcome.

The attached a a simple case that demonstrates the issue.  There is a junit test SimpleMapperTest that when run results in 'C' not being mapped to the target.

I'll grab the beta when it is available and check if that works with our model.

Thanks,

John

[test.zip](https://github.com/mapstruct/mapstruct/files/786150/test.zip)

**Comment by sjaakd** [comment]
@JohnHoward9 

try:
```java
@Mapper
public interface SimpleMapper {

    @Mapping(target = "subClassTarget", source = "source")
    Target toObject(Source source);


    @Mappings({
            @Mapping(target = "a", source = "subClassSource.a"),
            @Mapping(target = "b", source = "subClassSource.b"),
            @Mapping(target = "c", source = "c"),
    })
    Target.SubClass toSubClass(Source source);
}
```

The first mapping method is a parameter mapping. It simply takes the name `source` from the source parameter name and maps it into the property `subClassTarget`.  You could of course do that also with your own handwritten method. I reckon that the second mapping method speaks for itself.

As a tip: try to keep the target non nested. This improves readability and eases mappings. Let me know if this addresses your problem.

**Comment by sjaakd** [comment]
@JohnHoward9 .. were my tips useful?

**Comment by JohnHoward9** [comment]
Only just got a chance to pick this up again - Works perfectly

I tried a few other mappings as our model was slightly more complicated.  As well as the subClass we had a list of alternate subClasses where field C wasn't set, plus the field names were different in the two subClasses.

This is how I solved that.  Hope this is the right approach!

```
@Mapper
public interface SimpleMapper {
    @Mappings({
        @Mapping(target = "subClassTarget", source = "source"),
        @Mapping(target = "targetAltSubClasses", source = "sourceAltSubClasses")
    })
    Target toObject(Source source);


    @Mappings({
            @Mapping(target = "a", source = "subClassSource.a1"),
            @Mapping(target = "b", source = "subClassSource.b1"),
            @Mapping(target = "c", source = "c"),
    })
    Target.SubClass toSubClass(Source source);

    @Mappings({
            @Mapping(target = "a", source = "a1"),
            @Mapping(target = "b", source = "b1"),
            @Mapping(target = "c", ignore = true)
    })
    Target.SubClass toSubClass(Source.SubClass sourceSubClass);
}

```

Plan now is to use MapStruct on the microservices we are developing.  This will greatly simplify our mapping code, of which we have quite a lot. 

Many thanks for all your help.  

John

**Comment by sjaakd** [comment]
@JohnHoward9 .. nice to hear.

One small thing: if you're on Java8 you can even skip the `@Mappings` annotation and apply a list of `@Mapping` directly to the method. Just include `<artifactId>mapstruct-jdk8</artifactId>` iso the `<artifactId>mapstruct</artifactId>`

We just released the beta, and if you look at the issues, there are some spin offs of your issue wrt the beta. So thank you as well :smile:.
