### ISSUE TITLE
MappingConstants ANY_REMAINING and NULL not playing well together

### ISSUE THREAD

**Issue by idkw** [mapstruct/mapstruct#1091]
I have an enum `FirstEnum` which looks like :

- START
- STOP
- REPORT

and an enum `SecondEnum` which looks like : 
- START
- STOP

I want to map the values of the `FirstEnum` to the `SecondEnum` and output `null` when the value of `FirstEnum` doesn't exist in `SecondEnum`. It should map the values as follow: 
- null -> null
- START -> START
- STOP -> STOP
- REPORT -> null

I tried : 

```
    @ValueMappings({
        @ValueMapping(source = MappingConstants.ANY_REMAINING, target = MappingConstants.NULL),
    })
    SecondEnum toSecondEnum(FirstEnum firstEnum);
```

It generates the code: 

```

    @Override
    public SecondEnum toSecondEnum(FirstEnum firstEnum) {
        if ( firstEnum == null ) {
            return null;
        }

        SecondEnum secondEnum;

        switch ( firstEnum ) {
            case START: secondEnum = SecondEnum.START;
            break;
            case STOP: secondEnum = SecondEnum.STOP;
            break;
            default: secondEnum = SecondEnum.<NULL>;
        }

        return secondEnum;
    }

```

As you can see, the generated code contains `default: secondEnum = SecondEnum.<NULL>` which doesn't compile.
I would have expect to output ` default: secondEnum = null;` instead

**Comment by filiphr** [comment]
This indeed seems to be a bug on our side. The only thing if you use this then you cannot Inherit a Reverse mapping from this one.

It is not allowed to have a `ValueMapping` like:
```java
@ValueMapping(source = MappingConstants.NULL, target = MappingConstants.ANY_REMAINING)
```

**Comment by idkw** [comment]
OK thank you for the warning.
I intended to use this mapping as a one way converter.

**Comment by filiphr** [comment]
@idkw this one is now fixed and on our master it will be part of the next release (Beta or CR) for 1.2

**Comment by idkw** [comment]
Thank you for the fast answer and fix ! As a workaround, for the released version, for now, I will manually map the "remaining" values to null.

**Comment by gunnarmorling** [comment]
You also can fetch 1.2.0-SNAPSHOT with this fix from the Sonatype repo: https://oss.sonatype.org/content/repositories/snapshots/org/mapstruct/mapstruct-processor/1.2.0-SNAPSHOT/
