### ISSUE TITLE
Introduce decision helper API

### ISSUE THREAD

**Issue by manosbatsis** [mapstruct/mapstruct#1099]
Allow mappers to apply their strategy selectively to properties with null or other alternatives according to provided helper

**Comment by gunnarmorling** [comment]
Hi Manos, that request is a bit vague. Could you elaborate a bit how such
helper would look like and how you'd envision it to be used?

**Comment by manosbatsis** [comment]
Basically I would like to have a mapper consult my custom helper to allow overriding default behavior at runtime, for example to map a non-null value to null or even conditionally add a collection entry instead of setting a property to the target bean. The usecase is HTTP requests with parameters that dynamically instruct for a subset of the target model's properties and/or inclusion of relations as links or "included" resources per JSON-API 1.x

**Comment by gunnarmorling** [comment]
Seems like this could be solved using decorators and/or
@BeforeMapping/@AfterMapping methods. Have you tried out those?

**Comment by manosbatsis** [comment]
Happily guilty of missing that. Thanks for pointing me in the right direction.

**Comment by sjaakd** [comment]
FAQ issue?

**Comment by gunnarmorling** [comment]
Sure, feel free to add one :)
