### ISSUE TITLE
Couldn't retrieve @Mapper annotation while using Swagger2

### ISSUE THREAD

**Issue by prathapjayaraj** [mapstruct/mapstruct#1100]
I'm not able to compile when I use along with the Swagger2. My pom configuration file is attached.  When I enable swagger 2. I'm not able to compile it. I'm getting below exception.

`
[ERROR] diagnostic: C:\Prathap\STS-Workspace\GIT\directory\src\main\java\app\prathaplabs\or
gman\mapper\AddressMapper.java:13: error: Couldn't retrieve @Mapper annotation
@Mapper(componentModel = "spring", uses = {})
^
[ERROR] diagnostic: C:\Prathap\STS-Workspace\GIT\directory\src\main\java\app\prathaplabs\or
gman\mapper\OrganizationMapper.java:13: error: Couldn't retrieve @Mapper annotation
@Mapper(componentModel = "spring", uses = {})
^
[ERROR] diagnostic: C:\Prathap\STS-Workspace\GIT\directory\src\main\java\app\prathaplabs\or
gman\mapper\MemberMapper.java:13: error: Couldn't retrieve @Mapper annotation
@Mapper(componentModel = "spring", uses = {})
^
[ERROR] diagnostic: C:\Prathap\STS-Workspace\GIT\directory\src\main\java\app\prathaplabs\or
gman\mapper\ContactMapper.java:13: error: Couldn't retrieve @Mapper annotation
@Mapper(componentModel = "spring", uses = {})
^
[ERROR] error on execute: error during compilation
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.015 s
[INFO] Finished at: 2017-02-25T19:19:44+05:30
[INFO] Final Memory: 31M/268M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bsc.maven:maven-processor-plugin:2.2.4:process (process)
 on project directory: Error executing: error during compilation -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the follo
wing articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

[pom.txt](https://github.com/mapstruct/mapstruct/files/801239/pom.txt)

**Comment by gunnarmorling** [comment]
You've got groupId and artifactId for your dependency exclusion from Swagger to MapStruct 1.0.0.Final mixed up. It should be

    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger2</artifactId>
        <version>${swagger2.version}</version>
        <scope>compile</scope>
        <exclusions>
            <exclusion>
		<groupId>org.mapstruct</groupId>
		<artifactId>mapstruct</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

Just seeing that i's wrong in our FAQ, I'll fix it there.

Btw. you probably want to use "spring" instead of "cdi" as the `defaultComponentModel`, given you are working with Spring Boot ;)
