### ISSUE TITLE
Confusing method name in test mapper

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1101]
`shouldMapIntegerSetToNumberSet()` -> `shouldMapIntegerStreamToNumberSet()`

**Comment by gunnarmorling** [comment]
Done.

**Comment by filiphr** [comment]
@gunnarmorling this is already in master right? Shall we close this one?

**Comment by gunnarmorling** [comment]
Ah, yes. Thanks!
