### ISSUE TITLE
1.2.0-Beta1 Automapping Feature: doesn't work with enums

### ISSUE THREAD

**Issue by brabenetz** [mapstruct/mapstruct#1102]
enums are not Mapped (Error "Consider to declare/implement a mapping method: ..."):
[MapStructEnumMapper.java.txt](https://github.com/mapstruct/mapstruct/files/801846/MapStructEnumMapper.java.txt)

The Docu "mapstruct-reference-guide.asciidoc" says:

	MapStruct will only create a new mapping method if and only if the source and target property
	are  properties of a Bean and they themselves are Beans or simple properties.
	i.e. they are not Collection or Map type properties.

Maybe enums doesn't fall under "simple properties"?

**Comment by sjaakd** [comment]
@brabenetz .. In principle this is a missing feature.. The problem concerns enum mappings (which are not yet automatically generated). That's why we mentioned `Bean` in the text above. 

But having said that, its a good idea to add this as well.

**Comment by gunnarmorling** [comment]
Makes sense.

Thanks a lot for testing the Beta and filing these reports/feature request, @brabenetz. Keep them coming :)

**Comment by brabenetz** [comment]
Thanks for the greate MapStruct Library! I'm sure I will use it more often in the future.

**Comment by agudian** [comment]
Just pushed @filiphr's fix for this to master... Thanks Filip, and thanks @brabenetz for reporing this 👍
