### ISSUE TITLE
1.2.0-Beta1 Automapping Feature: cycle tree let the compiler crash with StackOverflowError.

### ISSUE THREAD

**Issue by brabenetz** [mapstruct/mapstruct#1103]
Recursive Mappings can produce a compiler crash "Internal error in the mapping processor: java.lang.StackOverflowError":
[MapStructRecursionMapper.java.txt](https://github.com/mapstruct/mapstruct/files/801850/MapStructRecursionMapper.java.txt)

**Comment by navpil** [comment]
@brabenetz Thanks for finding this bug.

I have added the PR which fixes this particular issue. Probably some other recursive cases should be handled.

**Comment by agudian** [comment]
Merged the fix by @navpil. Thanks @brabenetz for reporting the issue!
