### ISSUE TITLE
List<List<Bean>> generate method error

### ISSUE THREAD

**Issue by johnwatsondev** [mapstruct/mapstruct#1111]
#### ENV
MacOS 10.12.3

Android Studio 2.2.3
Build #AI-145.3537739, built on December 2, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

lombokVersion = '1.16.14'
mapstructVersion = '1.2.0.Beta1'

#### Mapper class
```
@Mapper public interface MaintainSetAndDetailEntity2MaintainSetAndDetailBeanMapper
    extends MaintainItemInfoEntity2MaintainItemInfoBeanMapper {
  MaintainSetAndDetailEntity2MaintainSetAndDetailBeanMapper MAPPER =
      Mappers.getMapper(MaintainSetAndDetailEntity2MaintainSetAndDetailBeanMapper.class);

  List<MaintainItemInfoBean> maintainItemInfoEntityListCast(
      List<MaintainItemInfoEntity> maintainItemInfoEntityList);

  List<List<MaintainItemInfoBean>> listList(
      List<List<MaintainItemInfoEntity>> maintainItemInfoEntityListList);
}
```

#### Generated class
```
  @Override

  public List<List<MaintainItemInfoBean>> listList(
      List<List<MaintainItemInfoEntity>> maintainItemInfoEntityListList) {

    if (maintainItemInfoEntityListList == null) {

      return null;
    }

    List<List<MaintainItemInfoBean>> list = new ArrayList<List<MaintainItemInfoBean>>();

    for (List<MaintainItemInfoEntity> list : maintainItemInfoEntityListList) {

      list.add(maintainItemInfoEntityListCast(list));
    }

    return list;
  }
```

#### Solution
Please change the local variable name `list` to `some_prefix_list` in for-loop criteria.

Thanks for hard work.

**Comment by gunnarmorling** [comment]
@sjaakd We could even consider to forge the middle (List -> List) method. Not sure though whether it's worth the efforts. Probably better to avoid the nested collections and model it using proper classes.

**Comment by sjaakd** [comment]
> We could even consider to forge the middle (List -> List) method.

That doesn't work.. I think forging only works when a bean mapping method refers to an iterable. Here an iterable requires another iterable mapping. That's not implemented. Perhaps an issue?

**Comment by gunnarmorling** [comment]
Yes, that's what I meant, should we support it? We can open an issue, but
it wouldn't be very high on my prio list :)

**Comment by sjaakd** [comment]
> Yes, that's what I meant, should we support it? We can open an issue, but
> it wouldn't be very high on my prio list :)

Done.. See #1118

**Comment by sjaakd** [comment]
@johnwatsondev .. Problem is solved. You can try our latest 1.2.0-SNAPSHOT build if you want  to try. Thanks for reporting this issue.

**Comment by johnwatsondev** [comment]
@sjaakd @gunnarmorling Thanks again. 
I will try it later. But how can I use the 1.2.0-SNAPSHOT version by gradle? Please add it to README. 😅

**Comment by filiphr** [comment]
@johnwatsondev you'll have to build MapStruct from source (it is already in the README), then you will have to tell gradle to use your local maven repository and then you can try it out 😀

**Comment by johnwatsondev** [comment]
@filiphr OK. Thanks. 👍
