### ISSUE TITLE
Support for Lomboks @Builder and @Value annotations.

### ISSUE THREAD

**Issue by LucasAndersson** [mapstruct/mapstruct#1116]
Hi

I would like to generate objects using builder and immutable patterns with Lomboks @Builder and @Value annotations and then map between these using mapstruct. I have managed to do this in a hackish way by using version 1.1.0.Final of mapstruct, build steps that I found in issue #510 and an old experimental version of Lomboks @Builder annotation which includes a "fluent" flag which turns the builders methods into setX(...) instead of x(...). 

I have uploaded an example here: https://github.com/LucasAndersson/mapstruct-lombok

If I use version 1.2.0.Beta1 of mapstruct and replace the build steps with the one in your installation documentation, CarFactory in my example complains that CarDto.CarDtoBuilder and Car.CarBuilder doesn't exist. It also seems like mapstruct is unable to find the methods of my builder if they aren't prefixed with "set", therefore I have to use the old experimental version of @Builder and set fluent to false.

I would love to come up with a "real" solution for this problem. I'm sorry if this is a duplicate issue. I highly appreciate any help I can get to do this in a better way or if you can at least point me in the right direction.

Br
Lucas

**Comment by filiphr** [comment]
@LucasAndersson to solve the issue with the builder and use it without `set` you will have to extend the `AccessorNamingStrategy` SPI. You can find more information in our [reference guide](http://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy). 

I just tried your example and it works with 1.2.0.Beta1. Did you have a look at our [mapstruct-lombok](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-lombok) example?

Btw. Your `CarFactory` doesn't need to have the `@Mapper` annotation, it just needs to have a default constructor. If you use injection, MapStruct can use any service that you have.

**Comment by LucasAndersson** [comment]
@filiphr 

Thank you for you response. I tried my example again with 1.2.0.Beta1 and it didn't work (with or without the special build steps).

Here is my pom file:

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>mapstruct-lombok</groupId>
    <artifactId>mapstruct-lombok</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <org.mapstruct.version>1.2.0.Beta1</org.mapstruct.version>
        <org.projectlombok.version>1.16.14</org.projectlombok.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${org.projectlombok.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-jdk8</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`

And here is the error I get:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project mapstruct-lombok: Compilation failure: Compilation failure:
[ERROR] /Users/lucasan/mapstruct-lombok/src/main/java/se/hiq/andersson/lucas/mapstruct/lombok/CarFactory.java:[8,18] cannot find symbol
[ERROR] symbol:   class CarDtoBuilder
[ERROR] location: class se.hiq.andersson.lucas.mapstruct.lombok.CarDto
[ERROR] /Users/lucasan/mapstruct-lombok/src/main/java/se/hiq/andersson/lucas/mapstruct/lombok/CarFactory.java:[13,15] cannot find symbol
[ERROR] symbol:   class CarBuilder
[ERROR] location: class se.hiq.andersson.lucas.mapstruct.lombok.Car
[ERROR] /Users/lucasan/mapstruct-lombok/src/main/java/se/hiq/andersson/lucas/mapstruct/lombok/CarMapper.java:[19,20] cannot find symbol
[ERROR] symbol:   class CarDtoBuilder
[ERROR] location: class se.hiq.andersson.lucas.mapstruct.lombok.CarDto
`

I have looked at your example but your target is mutable and not generated by Lombok. My target is immutable, using builder pattern and generated by Lombok. Actually, as my code is written now, my target is mutable as well since I'm mapping to CarDtoBuilder and not CarDto directly.

So perhaps the issue is that mapstruct can't find the builder without the special build steps where you delombok first? If it was able to find the builder then all I would have to do is extend the AccessorNamingStrategy like you mentioned and it should work.

**Comment by filiphr** [comment]
@LucasAndersson you have configured the maven compiler to only see the MapStruct annotation processor, and not the Lombok one. Either add the lombok dependency via the `annotationProcessorPaths` or add the MapStruct processor as a provided dependency and remove the `annotationProcessorPaths` from the compiler configuration. 

For our example I meant to look at the configuration in the `pom.xml`, not the java classes 😀

**Comment by LucasAndersson** [comment]
@filiphr 

Nice, it works! Thank you very much for your support. I will look into extending `AccessorNamingStrategy` so I don't have to use the old experimental version of Lomboks `@Builder` annotation.

**Comment by filiphr** [comment]
@LucasAndersson great. For the custom naming strategy you can have a look at our implementation (`DefaultAccessorNamingStrategy`), you can extend it and just override the needed methods. 

I am going to close the issue. You can reopen it if you think it is required.

**Comment by agudian** [comment]
That said, we have an issue open for explicitly supporting builders, which might be what you need in the long run: #782
