### ISSUE TITLE
MapStruct seems to mix Prototype method with mapping method signature

### ISSUE THREAD

**Issue by iersel** [mapstruct/mapstruct#1120]
Shared configuration:

```java
    /* DeliveredLocation */
    @Mapping( target = "deliveredLocationDbk", ignore = true )
    @Mapping( target = "boreholeResearchEntities", ignore = true )
    @Mapping( target = "XOrLon", expression = "java(BroLocationMapper.getX(v.getLocation()))" )
    @Mapping( target = "YOrLat", expression = "java(BroLocationMapper.getY(v.getLocation()))" )
    @Mapping( target = "crsCd", expression = "java(v.getLocation().getCrs())" )
    @Mapping( target = "horPosDate", source = "horizontalPositioningDate" )
    @Mapping( target = "horPosDateCd", source = "horizontalPositioningDate" )
    @Mapping( target = "horPosMethodCd", source = "horizontalPositioningMethod" )
    @Mapping( target = "horPosOperator", source = "horizontalPositioningOperator" )
    DeliveredLocationEntity toEntity( DeliveredLocation v );
```
Call site:
```java
   /* DeliveredLocation */
    @InheritConfiguration
    abstract void toEntity( DeliveredLocation dto, @MappingTarget DeliveredLocationEntity entity );
```
generated class:

```java
   @Override
    void toEntity(DeliveredLocation dto, DeliveredLocationEntity entity) {
        if ( dto == null ) {
            return;
        }

        if ( dto.getHorizontalPositioningDate() != null ) {
            entity.setHorPosDateCd( broDateMapper.toFormat( dto.getHorizontalPositioningDate() ) );
        }
        if ( dto.getHorizontalPositioningMethod() != null ) {
            entity.setHorPosMethodCd( dto.getHorizontalPositioningMethod() );
        }
        if ( dto.getHorizontalPositioningOperator() != null ) {
            entity.setHorPosOperator( dto.getHorizontalPositioningOperator() );
        }
        if ( dto.getHorizontalPositioningDate() != null ) {
            entity.setHorPosDate( broDateMapper.toDate( dto.getHorizontalPositioningDate() ) );
        }

        entity.setXOrLon( BroLocationMapper.getX(v.getLocation()) );
        entity.setCrsCd( v.getLocation().getCrs() );
        entity.setYOrLat( BroLocationMapper.getY(v.getLocation()) );
    }

```
`[ERROR] /C:/nathan/workspace/bhr_common/bhr_dao/target/generated-sources/annotations/nl/bro/dao/ss/bhr/impl/DtoToEntityMergeMapperImpl.java:[462,26] cannot find symbol symbol:   variable v`

Note: `v` is argument in the prototype method, `dto` is the corresponding method in the generated implementation. Using 1.1.0.final.

The problem only occurs for 1 of the , say 20 other methods.

**Comment by iersel** [comment]
problem also occurs with 1.2.0.Beta1

**Comment by filiphr** [comment]
@iersel, what MapStruct is doing is correct. Have a look at the [documentation] (http://mapstruct.org/documentation/stable/reference/html/#expressions) for the expressions. MapStruct is taking the expression as is, without doing anything else. 

Why don't you use nested source expression for your `v.getLocation().getCrs()` and `@Mapper(uses = BroLocationMapper.class)` for the other expressions? 

Theoretically we can create an issue to have an enhancement that we can add to MapStruct that will allow the users to use something like `<SOURCE>` in expressions / constants. Then MapStruct can insert the source parameter, of course we'll have to handle multiple source parameters.

**Comment by sjaakd** [comment]
@filiphr .. thanks. @iersel : we will close the issue...
