### ISSUE TITLE
TypeConversion seems to fail when going to 1.2.0.Beta1

### ISSUE THREAD

**Issue by iersel** [mapstruct/mapstruct#1121]
When going to MapStruct 1.2.0.Beta1 we get the following errors:

`[ERROR] Can't map property "java.math.BigInteger numberOfLayerComponents" to "java.lang.Integer numberOfLayerComponents". Consider to declare/implement a mapping method: "java.lang.Integer map(java.math.BigInteger value)".`

Seems that typeconversion no longer works between `Integer` and `BigDecimal`

While it compiled on 1.1.0.Final without a problem.

**Comment by iersel** [comment]
Note: MapStruct used to generate:

```java
        if ( sources.getNumberOfLayerComponents() != null ) {
            targets.setNumberConstituents( BigDecimal.valueOf( sources.getNumberOfLayerComponents() ) );
        }
```

**Comment by iersel** [comment]
We are using an update method (with `@MappingTarget`)

**Comment by agudian** [comment]
Great, thanks for reporting! We'll need to look into it for the next release.

**Comment by sjaakd** [comment]
@iersel I can't reproduce it. Lets have a better look on tuesday.

**Comment by sjaakd** [comment]
I've managed to reproduce it. It seems to happen when source and target are in a different jar than the mapper. Need to check how to set this up in unit test.Perhaps using bean-style objects in the java lib (and hope it works)? Candidates?

**Comment by sjaakd** [comment]
problem is most likely in `Type#hashCode` which uses `TypeMirror#hashCode`. JavaDoc `TypeMirror`:  `Types should be compared using the utility methods in Types. There is no guarantee that any particular type will always be represented by the same object. `

Ergo: if they are in different jar's these are most likely not the same objects.. Verifying now..

**Comment by sjaakd** [comment]
Should be solved..
