### ISSUE TITLE
Pass original source parameter as context

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1123]
See the discussion in #809. 

In an object graph, It would be nice to pass a source parameter (which is not a context) as context to a subordinate mapping method. 

To control this, this could be done by adding an attribute to an `@IterableMapping`, `@MapMapping`, `@BeanMapping` or `@ValueMapping` method.

A typical use case would be to retain for instance a collection for use in the element mapping (or deeper down the object graph).

**Comment by agudian** [comment]
I not so sure that we should treat any non-context parameters or other values or properties as contxt parameters...
But didn't we already have an issue to allow passing the source param down to another property or element property method? I vaguely remember that we discussed that for the same kind of problem... ?

**Comment by sjaakd** [comment]
> I not so sure that we should treat any non-context parameters or other values or properties as contxt parameters...

I'm not so sure either. You can do it quite easily with a hand written method. Not sure how big the problem actually is. Also: it would be more clear if context remains context (and thus untouched by MapStruct).

**Comment by gunnarmorling** [comment]
Couldn't one simply set this source object to a property of the context object manually before invoking the mapping method?

**Comment by sjaakd** [comment]
> Couldn't one simply set this source object to a property of the context object manually before invoking the mapping method?

I based this issue on the discussion in #809. Yes, you are right (or even pass a complete collection as context as is the case in #809). However, it seems to occur often. Hence automation would help.
