### ISSUE TITLE
Mapping nested property to simple property does not work when used with context

### ISSUE THREAD

**Issue by 44past4** [mapstruct/mapstruct#1124]
In 1.2.0-Beta1 when I am passing a context to a mapper using @Context annotation and I am applying a custom mapping from nested property like "entity.id" to "entityId" property (@Mapping(source = "entity.id", target = "id")) generated code does not compile as the invocation of method which extracts "entity.id" value expects context to be passed but it does not get any.

[TestMapper.java.txt](https://github.com/mapstruct/mapstruct/files/821703/TestMapper.java.txt)
[TestMapperImpl.java.txt](https://github.com/mapstruct/mapstruct/files/821708/TestMapperImpl.java.txt)

**Comment by agudian** [comment]
Thanks for reporting, I'll look into it... :+1:
