### ISSUE TITLE
MappingTarget and immutable collections

### ISSUE THREAD

**Issue by zelark** [mapstruct/mapstruct#1126]
I am trying to apply MapStruct to our project, but I run into a problem. We use our own ORM. If a property is a list, It returns either an emptyList() or an immutable list of values (unfortunately it works this way). The problem is the following generated code for update methods won't work in such case:
```java
        if ( entity.getFilePaths() != null ) {
            List<String> list = dto.getStorageFilePaths();
            if ( list != null ) {
                entity.getFilePaths().clear(); // this throws an exception
                entity.getFilePaths().addAll( list );
            }
            else {
                entity.setFilePaths( null );
            }
        }
        else {
            List<String> list = dto.getStorageFilePaths();
            if ( list != null ) {
                entity.setFilePaths(       new ArrayList<String>( list )
                );
            }
        }
```

The question is how can we tell MapStruct just to generate code like in the else block for update methods?

Also I found #153 where clear and addAll came from. And it seems in #728 describing the same feature which I'd like to get.

**Comment by zelark** [comment]
Hi guys, can you help, please?

**Comment by sjaakd** [comment]
@zelark .. I'll try to have a look later this weekend.

**Comment by sjaakd** [comment]
@zelark .. for the current setup I don't have a definite solution.. However, you might want to try to define a hand written method for all `List<X>` to `List<Y>` you need along this line:

```java
@Mapper
public abstract class ExampleMapper {


    @Mapping(target = "integer", source = "bigDecimal")
    abstract void map(Source source, @MappingTarget Target target);


    List<String> map(List<String> source ) {
        if ( source != null && !source.isEmpty() ) {
            return new ArrayList();
        }
        return Collections.emptyList();
    }
}
```

That will generate the following code

```java
public class ExampleMapperImpl extends ExampleMapper {

    @Override
    void map(Source source, Target target) {
        if ( source == null ) {
            return;
        }

        if ( source.getBigDecimal() != null ) {
            target.setInteger( source.getBigDecimal().intValue() );
        }
        if ( target.getList() != null ) {
            List<String> list = map( source.getList() );
            if ( list != null ) {
                target.getList().clear();
                target.getList().addAll( list );
            }
            else {
                target.setList( null );
            }
        }
        else {
            List<String> list = map( source.getList() );
            if ( list != null ) {
                target.setList( list );
            }
        }
    }
}
```

Alternatively you might want to have a look at `@BeforeMapping` , initializing all collection types that have a non-empty, non-null source.

**Comment by sjaakd** [comment]
However, I realize that this circumvents the problem. Perhaps we should have some setting (along the lines of `NullValueCheckStrategy` / `NullValueMappingStrategy`) indicating to leave out the: 
```java
            if ( list != null ) {
                target.getList().clear();
                target.getList().addAll( list );
            }
```
part.

@gunnarmorling : WDYT? Feels that an additional value to `NullValueCheckStrategy` leads to combinations of values..

**Comment by zelark** [comment]
Thanks for reply, @sjaakd!
For our entities we can't invoke clear() or/and addAll() on any getters returning a collection. That's why we want to somehow eliminate this block:
```java
            if ( list != null ) {
                target.getList().clear();
                target.getList().addAll( list );
            }
```

@BeforeMapping works perfect, but not for this case. If we have some non-trivial type we have to map it as well. It may an enum or an nested entity. So, first, we have to ignore the all collection types and then put those mapping into @BeforeMapping methods, where manually invoke mappers for each of them. It seems tedious.

As you fairly noted there need some option to choose what we want, either just set-get or clear-addAll.

**Comment by sjaakd** [comment]
> Thanks for reply, @sjaakd!

No problem. Now a decent solution :smile: 

I've been thinking a bit more on this. I'm starting to run into problems on generated method when I use an additional parameter on `@MappingTarget`. However, I almost forgot: we also have a `CollectionMappingStrategy`. At the moment this is probably the most obvious candidate to extend. I'll try to prepare a PR for this one..

**Comment by sjaakd** [comment]
@zelark .. the solution is merged to the main branch.. Please feel free to check.

**Comment by zelark** [comment]
@sjaakd, sounds perfect! Thank you. I'll check it tomorrow.

**Comment by riaprocoumai** [comment]
can set CollectionMappingStrategy just for special target ?
