### ISSUE TITLE
Don't use equals and hashCode from TypeMirror

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1129]
This is connected to the fix to #1127. There is [this](https://bugs.openjdk.java.net/browse/JDK-7159498) JDK bug report that might be causing java lang `ClassType` that are actually same to be different. 

According to the javadoc of [`TypeMirror#equals()`](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/type/TypeMirror.html#equals-java.lang.Object-) one should use [`Types#isSameType()`](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/util/Types.html#isSameType-javax.lang.model.type.TypeMirror-javax.lang.model.type.TypeMirror-) for semantic comparison.

There is one more place where we use `TypeMirror#hashCode()`:
 * [SelectionParameters#L72](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java#L72)

There are other places where we use `TypeMirror#equals`:

* [SelectionParameters#L97](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java#L97)
* [Type#L570](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java#L570)
* [MethodMatcher#L398](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java#L398)

**Comment by gunnarmorling** [comment]
Great analysis. We should call `isSameType()` in all these cases. The JDK bug you linked to looks indeed as it could be the cause for the problem and it matches Sjaak's description, too.

**Comment by agudian** [comment]
Agreed for the isSameType for equals, and for hashCode we can do it as Sjaak did it in the other PR.... 🙂
Great findings, Filip!

**Comment by filiphr** [comment]
I will make the changes then. 

Additionally what do you think about sonar? They allow free usage of sonarqube for open source projects (more [here](https://about.sonarqube.com/news/2016/09/01/sonarqubedotcom-open-to-aynone.html)). This can theoretically be used to identify new issues like the current one. We can create a rule that will fail if someone uses `equals` / `hashCode` of a TypeMirror. If you think that there is an easier way to enforce this automatically let me know :)
