### ISSUE TITLE
Reverse mapping for several targets

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#113]
In unit test: 
`org.mapstruct.ap.test.severaltargets.SourcePropertyMapSeveralTimesTest.java` tests how 1 source can be mapped to two targets by means of a custom mapper `TimeAndFormatMapper`.  I would expect that if the `TimeAndFormatMapper` is extended with a new method `public TimeAndFormat getTimeAndFormat(Date time, String format)`  like this:

``` java
package org.mapstruct.ap.test.severaltargets;

import java.util.Date;

public class TimeAndFormatMapper {

    public String getFormat(TimeAndFormat t) {
        return t != null ? t.getTfFormat() : null;
    }

    public Date getTime(TimeAndFormat t) {
        return t != null ? t.getTfTime() : null;
    }

    public TimeAndFormat getTimeAndFormat(Date time, String format) {
        TimeAndFormat tf = new TimeAndFormat();
        tf.setTfFormat( format );
        tf.setTfTime( time );
        return tf;
    }

}
```

and the main SourceTargetMapper is extended with a new method `Source targetToSource(Target s)` like this:

``` java
@Mapper(uses = TimeAndFormatMapper.class)
public interface SourceTargetMapper {
    SourceTargetMapper INSTANCE = Mappers.getMapper( SourceTargetMapper.class );

    @Mappings(
        {
            @Mapping(source = "name", target = "name1"),
            @Mapping(source = "name", target = "name2"),
            @Mapping(source = "timeAndFormat", target = "time"),
            @Mapping(source = "timeAndFormat", target = "format")
        })
    Target sourceToTarget(Source s);

    Source targetToSource(Target s);
}
```

mapping would work out of the box by means of what is described in 'ch 3.2  Mapping methods with several source parameters' of the documentation.

Unfortunately the result is a compilation error.

**Comment by stajne** [comment]
can i get help, how is this to be resolved with expression?
