### ISSUE TITLE
Variable name already defined (Name variable in source and in target identical)

### ISSUE THREAD

**Issue by Azork** [mapstruct/mapstruct#1138]
The naming convention produces some unwanted bevahior: 

For Object source:

```
@Data
public class Source {

   private String test;

   private SourceCollection sources;

}
```
```
public class SourceCollection {

    List<Source> target;

    public List<Source> getTarget() {
        return target;
    }

    public SourceCollection withTarget(List<Source> target) {
        this.target = target;
        return this;
    }
}
```

```
public class Target {

    private Long testing;

    private List<Target> targets;

    public Long getTesting() {
        return testing;
    }

    public void setTesting( Long testing ) {
        this.testing = testing;
    }

    public List<Target> getTargets() {
        return targets;
    }

    public Target withTargets(List<Target> targets) {
        this.targets = targets;
        return this;
    }
}
```
```
@Mapper
public interface SourceTargetMapper {

    SourceTargetMapper MAPPER = Mappers.getMapper( SourceTargetMapper.class );
    @Mappings({
            @Mapping(source = "test", target = "testing"),
            @Mapping(target = "targets", source = "sources.target")
    })
    Target toTarget( Source s );
}
```

Result:
```
 @Override
    public Target toTarget(Source s) {
        if ( s == null ) {
            return null;
        }
        Target target = new Target();

        List<Source> target = sSourcesTarget( s );
        if ( target.getTargets() != null ) {
            List<Target> list = sourceListToTargetList( target );
            if ( list != null ) {
                target.getTargets().addAll( list );
            }
        }
        if ( s.getTest() != null ) {
            target.setTesting( Long.parseLong( s.getTest() ) );
        }

        return target;
    }
```

[ERROR] /C:/Projects/test/mapstruct-examples-master/mapstruct-lombok/target/generated-sources/annotations/com/mycompany/mapper/SourceTargetMapperImpl.java:[25,22] variable **target** is already defined in method toTarget(com.mycompany.dto.Source)
[ERROR] /C:/Projects/test/mapstruct-examples-master/mapstruct-lombok/target/generated-sources/annotations/com/mycompany/mapper/SourceTargetMapperImpl.java:[27,57] incompatible types: com.mycompany.entities.Target cannot be converted to java.util.List<com.mycompany.dto.Source>

The version 1.1.0.Final didn't have this problem.

[mapstruct-lombok.zip](https://github.com/mapstruct/mapstruct/files/838181/mapstruct-lombok.zip)

**Comment by agudian** [comment]
Just tried to recreate it, and it turns out that this is already fixed in master... I'd like to close it. We're planning to do a new Beta release in the next days, and it would be great if you could verify it then with your real-life setup...

**Comment by Azork** [comment]
It's working with the master branch.
Isn't it great to have caught a bug before it was reported?
Thanks for the quick response!

**Comment by agudian** [comment]
> Isn't it great to have caught a bug before it was reported?
> Thanks for the quick response!

Haha, right, it is! Thanks to you for filing the issue and re-testing it! Very much appreciated.
