### ISSUE TITLE
Fails to generate impl class from abstract class when abstract uses collections and non abstract methods

### ISSUE THREAD

**Issue by carstencogos** [mapstruct/mapstruct#114]
When an abstract class has a non abstract method, no new abstract methods can be added  and generated ind the Impl class.

Ex.

    @Mapper()
    public abstract class AandBMapper {

        static final public AandBMapper INSTANCE = Mappers.getMapper(AandBMapper.class);

        // example that converts to instance variables with different names and types
        @Mappings({
                @Mapping(source="a", target="b"),
        })
        abstract protected ClassB AtoB(ClassA a);
        @Mappings({
    }) 

        abstract ClassA BtoA(ClassB b); 

        public ClassB AtoBCustom(ClassA a){
            ClassB b = AtoB(a);
            b.b = b.b + 1;
            return b;
        }
    }

This works perfect, now adding a new abstract method with Collections
    abstract List<ClassB> AsToBs(List<ClassA> as);  

So we have 

    @Mapper()
    public abstract class AandBMapper {

        static final public AandBMapper INSTANCE = Mappers.getMapper(AandBMapper.class);

        // example that converts to instance variables with different names and types
        @Mappings({
                @Mapping(source="a", target="b"),
        })
        abstract protected ClassB AtoB(ClassA a);
        @Mappings({
    }) 

        abstract ClassA BtoA(ClassB b); 

        abstract List<ClassB> AsToBs(List<ClassA> as);  

        public ClassB AtoBCustom(ClassA a){
            ClassB b = AtoB(a);
            b.b = b.b + 1;
            return b;
        }
    }

The Impl class now fails because of the missing AsToBs, implementation.

If we remove the public methos so we have all abstract methods - really making it an interface, the impl class is now generated again.

i.e.

    @Mapper()
    public abstract class AandBMapper {

        static final public AandBMapper INSTANCE = Mappers.getMapper(AandBMapper.class);
        
        // example that converts to instance variables with different names and types
        @Mappings({
                @Mapping(source="a", target="b"),
        })
        abstract protected ClassB AtoB(ClassA a);
        @Mappings({
    }) 

        abstract ClassA BtoA(ClassB b); 

        abstract List<ClassB> AsToBs(List<ClassA> as);  

    }

And just to wrap it up with a work around, we can now add the public method again so we have (same as the one not working but the sequence of adding the methods when actually typing the code is different) 

    @Mapper()
    public abstract class AandBMapper {

        static final public AandBMapper INSTANCE = Mappers.getMapper(AandBMapper.class);
        
        // example that converts to instance variables with different names and types
        @Mappings({
                @Mapping(source="a", target="b"),
        })
        abstract protected ClassB AtoB(ClassA a);
        @Mappings({
    }) 

        abstract ClassA BtoA(ClassB b); 

        abstract List<ClassB> AsToBs(List<ClassA> as);  

        public ClassB AtoBCustom(ClassA a){
            ClassB b = AtoB(a);
            b.b = b.b + 1;
            return b;
        }
    }

And everything is again working. If you found the above cumbersom to follow just take the last code, uncomment the public method, all is OK. now add in the method again, all is still OK. Now uncomment the  abstract List<ClassB> AsToBs(List<ClassA> as);  all is OK, Now add in the the  abstract List<ClassB> AsToBs(List<ClassA> as); and the build fails.

**Comment by gunnarmorling** [comment]
Going to close this one as I think it's not an issue really anymore. Since then, [qualifiers](http://mapstruct.org/documentation/#section-15) have been introduced to resolve any ambiguities in the course of mapping method resolution. If there is anything left, feel free to open up a new issue. Thx!
