### ISSUE TITLE
Inconsistent use of clearing collections in case of update methods.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1142]
when using `ADDER_PREFERRED`  the following update method is generated:

```java
    @Override
    public Car updateCar(CarDto dto, Car car) {
        ...
        if ( dto.getPersons() != null ) {
            for ( PersonDto person : dto.getPersons() ) {
                car.addPerson( dtoToPerson( person ) );
            }
        }
       ...

```

It doesn't clear the collection. This is not consistent with other `CollectionMappingStrategie`'s
icw update methods.

**Comment by jklapwijk** [comment]
Will the collection.clear() be added to the generated update method implementation for the ADDER_PREFERRED strategy?

**Comment by sjaakd** [comment]
I'm reiterating some issues.. I see there's a difference. Although I am thinking whether we should access a getter when handling an adder method... @filiphr : WDYT?

**Comment by filiphr** [comment]
This is a tough one @sjaakd. I also had the same question last week. I would say if you are using an adder strategy we should not touch the getter. It might even be possible that the adder returns an immutable collection that will throw an exception if we clear it, so I wouldn't go there 😄

**Comment by sjaakd** [comment]
Ok.. I'll close this one.. But we clear collections also in the regular case. Should we leave that as is?

**Comment by filiphr** [comment]
I think that in the regular case it is OK. The reason is that we are using the getter to add to the collection, so we can clear it. If we can't clear it we also can't add to it (at least that is my reasoning)

**Comment by sjaakd** [comment]
Agreed. But do we add this reasoning somewhere..? FAQ?

**Comment by filiphr** [comment]
Perhaps in the documentation?

**Comment by sjaakd** [comment]
Good idea..  I'll open op a pr for that..

**Comment by filiphr** [comment]
In [Update existing bean instances](http://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances)

we currently have 

>Collection- or map-typed properties of the target bean to be updated will be cleared and then populated with the values from the corresponding source collection or map.

Maybe we need to add about the adders here

**Comment by sjaakd** [comment]
> Maybe we need to add about the adders here

Hmmm. Immutable? I don't think we have adders for maps..
