### ISSUE TITLE
1.2.0-Beta2 Automapping Feature: doesn't work with enums when field names are different

### ISSUE THREAD

**Issue by adalgrim** [mapstruct/mapstruct#1143]
` */
public class AddressDTO {

    private LocationDTO locationType;

    private String location;

    public LocationDTO getLocationType() {
        return locationType;
    }

    public void setLocationType(LocationDTO locationType) {
        this.locationType = locationType;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}

public class AddressEntity {

    private Location locationEnum;

    private String location;

    public AddressEntity(String location, Location locationEnum) {
        this.location = location;
        this.locationEnum = locationEnum;
    }

    public Location getLocationEnum() {
        return locationEnum;
    }

    public void setLocationEnum(Location locationEnum) {
        this.locationEnum = locationEnum;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface UserMapper {

    @Mappings({
            @Mapping(target = "address.locationType", source = "address.locationEnum")
    })
    List<UserDTO> mapToUsers(List<UserEntity> userEntityList);
}`

error during compilation: No property named "address.locationEnum" exists in source parameter(s).

When two fields have exactly the same name everything works as expected.

**Comment by filiphr** [comment]
@adalgrim your mapping definition is wrong. When you use `@Mapping` it applies to the objects that you are mapping. In this case the `source` / `target` types are `List<UserEntity>` / `List<UserDTO` respectively.

What you need to do is:

```java
@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface UserMapper {

    @Mappings({
            @Mapping(target = "address.locationType", source = "address.locationEnum")
    })
    UserDTO mapToUser(UserEntity user);

    List<UserDTO> mapToUsers(List<UserEntity> userEntityList);
}
```

The generated method will then call the `mapToUser` method.

>When two fields have exactly the same name everything works as expected.

It works because MapStruct does not try to find the `source` in the `List`.

If you agree I will continue and close this issue.

**Comment by adalgrim** [comment]
@filiphr I think we can close. I found the same solution after some investigation. 

However, it seems to me that one custom field stops us from using auto sub-mappings :(

**Comment by filiphr** [comment]
@adalgrim what do you mean by one custom field stop you from using auto sub-mappings? You don't want to have a mapping method between the `UserEntity` and `UserDto`?

You can create a feature request to support `@Mapping` to apply on the element type of an `Iterable` if that is what you need.

**Comment by adalgrim** [comment]
@filiphr that's exactly what I'd like to have :) creating sub-mapping only for such extra custom mapping is a "waste of lines"..
