### ISSUE TITLE
ReportingPolicy sometimes missing mapper class in error message

### ISSUE THREAD

**Issue by stengvac** [mapstruct/mapstruct#1144]
Techs:
Java: 1.8
MapStructVersion: 1.2.0.Beta1 (mapstruct-jdk8)
And maven plugin configured as is described in http://mapstruct.org/documentation/installation/

Hello, 
i have following problem. When i use ReportingPolicy.ERROR/WARN and target object have more fields than source (so some field in target are unmapped) then warn/error output message say only "somewhere in project is unmapped property" -> missing where this error occured.

See example:

i use  following "global config":
```
@MapperConfig(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface Converter<S, T> {
    T convert(S source);
}
```
Source object
```
public class Source {
    private String name;
   //get and set methods
}
```
Target object to convert.
```
public class Target {
    private String name;
    private String surname;
    //get and set methods
}
```
and mappers are constructed like:
```
@Mapper(config = Converter.class)
public interface Source2TargetConverter extends Converter<Source, Target> {
  //empty
}.
```
When i run mvn clean install: output for this case is:
[ERROR] unmapped target property "surname". 
So there is no info which mapper is source of this error.

V

**Comment by filiphr** [comment]
@stengvac The error should be displayed on the place of the method that does the mapping. In your case ` T convert(S source);`.

The error looks something like:

```
[ERROR] Converter.java:[29,7] Unmapped target property: "surname".
``` 

Are you saying that this is not the case for you? I know that this would not be helpful to you as your `Converter` is generic. If you have some other suggestion to make this message helpful for generic methods please let us know.

**Comment by stengvac** [comment]
With project structure like [here](https://github.com/stengvac/mapstruct-err-msg) when i run build with 

`mvn clean install`

then output is

`[ERROR] unmapped target property "surnamee".` 

Sry i have tried to add project as zip archive but github had problem with file type (zip is allowed -_-).

**Comment by filiphr** [comment]
@stengvac that most probably happens because the method that the Annotation processor is using is in another jar (module).

@agudian, @gunnarmorling, @sjaakd, Do you think that we could / should do something for this use case?

**Comment by filiphr** [comment]
I just found out that #598 addresses the exact same thing. Therefore I am going to close this issue. Please watch #598 for more information.
