### ISSUE TITLE
Vote on IntelliJ fix for annotation-processor sources in gradle projects

### ISSUE THREAD

**Issue by tkruse** [mapstruct/mapstruct#1145]
Sorry if this is spam.
IntelliJ IDEA has a bug when trying to import gradle projects using annotation-processor generated sources. I think that may cause users to avoid using MapStruct.

Please vote for this to be fixed:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-124090

Close this ticket without further comment if you like.

**Comment by filiphr** [comment]
Thanks for pointing out the IntelliJ ticket. I will close this issue as it is not directly linked to MapStruct. Maybe we can add this to the FAQ on the website, if you think that it happens frequently to gradle users.

**Comment by tkruse** [comment]
Already with a few votes added it seems IntelliJ takes the issue more seriously. I believe all Gradle+IntelliJ+Mapstruct users are affected to the point of dropping one of those 3 tools out of frustration.

**Comment by filiphr** [comment]
If you are on IDEA 2016.3 or newer you can always use the possibility IntelliJ to delegate the build to Gradle. Have a look at the IntelliJ [blog post](https://blog.jetbrains.com/idea/2016/10/intellij-idea-2016-3-eap-refactorings-to-java-8-vcs-integration-and-gradle/)
