### ISSUE TITLE
Updating existing bean instances - of the target bean to be updated will be cleared

### ISSUE THREAD

**Issue by amitwaves** [mapstruct/mapstruct#1147]
Sorry if this is spam.
The documented behavior is when updating existing beans is Collection- or map-typed properties of the target bean to be updated will be cleared and then populated with the values.   I expected the ignored property values in target bean to be left alone and not cleared.  Should this be the correct behavior for an update operation ?

**Comment by filiphr** [comment]
@amitwaves what exactly do you mean by the ignored property values in the target bean? Do you mean the bean in the `Collection` or `Map` type or you mean the property in the bean you are trying to map?

If a property is ignored via `@Mapping` then MapStruct will not generate a mapping code for that, it is simply ignored. 

Are you having some problems with something? Is something not working as expected?

**Comment by amitwaves** [comment]
Looking at the generated code, I understand why it is working the way it is, but it was not what I was expecting when I read the doc.

```java
@Mapper(componentModel = "spring")
public interface Test {
    @Mapping(target = "prop2", ignore = true)
    public Bar FooToBar(Foo Foo);

    @Mapping(target = "prop2", ignore = true)
    public Bar updateData(Foo Foo, @MappingTarget Bar Bar);

    @IterableMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
    public List<Bar> updateDataList(List<Foo> FooList,
                                    @MappingTarget List<Bar> BarList);
}

@Override
    public Bar FooToBar(Foo Foo) {
        if ( Foo == null ) {
            return null;
        }
        Bar Bar = new Bar();
        Bar.setProp1( Foo.getProp1() );
        return Bar;
    }

    @Override
    public Bar updateData(Foo Foo, Bar Bar) {
        if ( Foo == null ) {
            return null;
        }
        Bar.setProp1( Foo.getProp1() );
        return Bar;
    }

    @Override
    public List<Bar> updateDataList(List<Foo> FooList, List<Bar> BarList) {
        if ( FooList == null ) {
            BarList.clear();
            return BarList;
        }
        BarList.clear();
        for ( Foo Foo : FooList ) {
            BarList.add( FooToBar( Foo ) );
        }
        return BarList;
    }
```
I was expecting the implementation to of updateDataList() to call updateData() instead of calling FooToBar(). That way my original populated value in target BarList remains intact. 

I got around this by creating abstract class but it didn't work as what I was thinking an Update operation is supposed to do.

Thanks.

**Comment by filiphr** [comment]
How do you expect the `List<Bar>` to be updated? In order to call the `updateData()` we need to have a mapping target, what would the mapping target be in this case?

**Comment by amitwaves** [comment]
I get your point. Would need a Criteria for comparison before calling updateData(). I will close the comment.
Thanks.
