### ISSUE TITLE
Confusing error messages, nesting levels not considered.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1150]
```java
public class MyDate {

    private Date date;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

}
```

```java
public class Entity {

    private MyDate date;

    public MyDate getDate() {
        return date;
    }

    public void setDate(MyDate date) {
        this.date = date;
    }
    
}
```

```java
public class Dto {

    private Date date;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

}
```

```java
@Mapper
public interface MyMapper {

    MyMapper INSTANCE = Mappers.getMapper( MyMapper.class );

    Entity map( Dto dto);

}
```

Leads to error message:

`ERROR MyMapper.java:30 Can't map property "int date" to "java.util.Date date". Consider to declare/implement a mapping method: "java.util.Date map(int value)".`

Took me a while to figure out that MapStruct actually tries to map the deprecated `getDate()` method the Java `Date` class.. 

The errror should have been:

`ERROR MyMapper.java:30 Can't map property "int date.date" to "java.util.Date date.date". Consider to declare/implement a mapping method: "java.util.Date map(int value)".`

**Comment by filiphr** [comment]
Maybe we shouldn't be trying to forge mappings for objects that we have conversions (or objects in the Java package)?

**Comment by sjaakd** [comment]
> Maybe we shouldn't be trying to forge mappings for objects that we have conversions (or objects in the Java package)?

?? We don't have a conversion from `Date` to `MyDate`.. 

The problem is that MapStruct maps all stuff and it gives no clue on which nesting level the problem is.  

Let alone that we probably should exclude deprecated marked getters / setters and perhaps even have a means to indicate that MapStruct should ignore getters / setters on the DTO themselves.. (e.g. MyDate).

**Comment by sjaakd** [comment]
I'll issue some separate issues for that..

**Comment by filiphr** [comment]
>?? We don't have a conversion from Date to MyDate..

What I meant is that we have a conversion to create a `Date`, so we shouldn't go into `Date` during forging. I think that we can at least block recursive calls into the objects in the `java` package.

**Comment by sjaakd** [comment]
That's a good idea. Can you open an issue for that ? (Perhaps it belongs to #1151). 

Nonetheless we should have clear errors.

**Comment by filiphr** [comment]
You are right this is more about the error. I created #1154 for that.
