### ISSUE TITLE
Do not try to create mappings for objects in the java package

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1154]
When we generate missing mappings we shouldn't try to go into objects from the java package.

For example if we have:

```java
public class MyDate {

    private String someProperty;

    //getters and setters omitted for brevity
}
```
```java
public class Entity {
    
    private MyDate date;

    //getters and setters omitted for brevity
}
```

```java
public class EntityDto {
    
    private Date date;

    //getters and setters omitted for brevity
}
```

```java
@Mapper
public interface MyMapper {

    EntityDto map(Entity entity);
}
```

We are going to generate:

```java
protected Date myDateToDate(MyDate myDate) {
        if ( myDate == null ) {
            return null;
        }

        Date date = new Date();

        return date;
}
````

In my opinion we shouldn't try to instantiate and create objects from the java package. We also then continue and try to see if there are properties that can be mapped between `Date` and `MyDate`.

**Comment by agudian** [comment]
Makes sense! I'm trying to come up with examples of classes in java.* where treating them as beans would be okay, but I can't find any... 😁
How about limiting this to known full package names, such as java.lang, java.util, java.time, ...? That gives us a little bit more control.

**Comment by filiphr** [comment]
Just as information, I already have a 90% ready implementation for this. I am waiting for #1146 to be resolved/merged to create a PR. The reason is that I am using something from there to ignore the java packages :)
