### ISSUE TITLE
Dto to Entity OneToMany orphanRemoval

### ISSUE THREAD

**Issue by alexandrepetrillo** [mapstruct/mapstruct#1161]
Hello, i'm trying to map PersonDto To PersonJpa. 
PersonJpa have a adresses collection with orphanRemoval, for working my mapping doesnt create new Instance of JpaEntity but realize a loadById from entityManager. 
But mapping set the collection and replace the hibernate's persistentSet by a traditionnal java.util.TreeSet and after.. orhpanRemoval can't working. 
Do you know, how can i do for not set collection but use adresses.clear() and adresses.addAll(..) in my mapper ?
Tkx

**Comment by filiphr** [comment]
MapStruct will use `collection.clear()`, `collection.addAll` if you are doing an update method (`@MappingTarget`), or if there are not setters on your bean. Have a look at the [collection mapping strategies](http://mapstruct.org/documentation/stable/reference/html/#collection-mapping-strategies) from our documentation.

**Comment by filiphr** [comment]
@alexandrepetrillo Let me know if we need to reopen the issue.

**Comment by alexandrepetrillo** [comment]
For sure,
Thanks for your response.I can try tomorrow.

Thanks

2017-03-29 19:08 GMT+02:00 Filip Hrisafov <notifications@github.com>:
