### ISSUE TITLE
not mapping the subclass during compile

### ISSUE THREAD

**Issue by chandra0651** [mapstruct/mapstruct#1173]
Hi i am new to mapstruct and i am trying to use it to convert the entity to dto and viceversa. i am using the 1.2.0.Beta1 version.

i have entity which extends other entity like
public entity extends abstract entity{
 String name;
String version;
}

abstract Entity{
String id,
String  createdTime;
}

public EntityDto{
String name;
String version;
String id,
String  createdTime;
}

When i write some thing like below and compile the project only the fields in the abstract class are getting converted first and i need to recompile again for the fields in sub class to get converted in impl class of ma[struct.
@Mapper
public interface DtoConversion {

    DtoConversion INSTANCE = Mappers.getMapper(DtoConversion.class);

 EntityDto convert(Entity entity);

    }

**Comment by agudian** [comment]
How is your build set up? How does your pom/gradle file look like?

How do you compile?

Are any of the used entities/dtos generated/extended through some other tool during the build? (xjc, Lombok, Protobuf, ...)

**Comment by chandra0651** [comment]
i am using lombok and my gradle file looks like 

plugins{
   id 'java'
    id 'net.ltgt.apt' version '0.9'
}

  dependencies {
            dependency 'org.mapstruct:mapstruct-processor:1.2.0.Beta1'
            dependency 'org.mapstruct:mapstruct-jdk8:1.2.0.Beta1'
            dependency 'org.mapstruct:mapstruct:1.2.0.Beta1'

        }

**Comment by filiphr** [comment]
Which lombok version are you using? Lombok 1.16.4 is compatible with MapStruct, earlier versions will not work correctly. 

By the way you don't need mapstruct and mapstruct-jdk8 in the same time. The only difference between the two is the possibility to use Java 8 repeatable annotations

**Comment by filiphr** [comment]
Sorry lombok 1.16.14 not 1.16.4

**Comment by chandra0651** [comment]
i am using below dependencies and now i couldnt able to generate the mapstruct impl class itself 

  compile "org.mapstruct:mapstruct-jdk8:1.2.0.Beta1"
    apt "org.mapstruct:mapstruct-processor:1.2.0.Beta1"

    compile "org.projectlombok:lombok:1.16.14"

**Comment by agudian** [comment]
If you add `org.mapstruct:mapstruct-processor` to the `apt` path, then you'll also need to add `org.projectlombok:lombok` to the `apt` path (in addtion to `org.projectlombok:lombok` on the `compile` path, as for Lombok, the annotations and the processor are in the same jar).

Reason: `javac` picks up annotation processors either from the `-processorpath` (`apt` in gradle) if it is specified, OR, if it's not specified, from the classpath - but never from both sources...

**Comment by chandra0651** [comment]
When i use my dependencies like below the impl class is getting generated and working fine 

compile "org.mapstruct:mapstruct-jdk8:1.2.0.Beta1","org.projectlombok:lombok:1.16.14"
compile "org.mapstruct:mapstruct-processor:1.2.0.Beta1","org.projectlombok:lombok:1.16.14"

but not working with apt() method for processor like below 

compile "org.mapstruct:mapstruct-jdk8:1.2.0.Beta1","org.projectlombok:lombok:1.16.14"
apt "org.mapstruct:mapstruct-processor:1.2.0.Beta1","org.projectlombok:lombok:1.16.14"

**Comment by filiphr** [comment]
@chandra0651 did you resolve your problem? 

I am going to close this issue as we have multiple reportings that everything works ok with gradle. If you are using IntelliJ make sure that you delegate the build to gradle instead of the default IntelliJ one
