### ISSUE TITLE
@Context not working for collections

### ISSUE THREAD

**Issue by mpachucki-decerto** [mapstruct/mapstruct#1176]
Hi,
I have two classes A and B. A keeps a collection of B's. I want to map A to ADTO, but for that I need additional @Context argument which I use in @AfterMapping method. I can pass it fine to the A mapper, but when A mapper calls B mapper it does not pass the @Context argument.

As far as I know the annotations are correct, mapstruct just creates invalid code as it tries to call B mapper methods without @Context parameter, but those do not exist (so it generates code that does not compile).

**Comment by filiphr** [comment]
I guess the solution is the same as the one you wrote in the gitter:

>Eh, it seems some IDE problem. Invalidating caches in Intellij fixed this problem 

Just posting it here, so others can see what the "solution" was :)
