### ISSUE TITLE
nested target mappings not working properly

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1178]
```java
    @Mapping( target = "wellData.groundLevelPosition", source = "deliveredVerticalPosition.groundLevelPosition.value" )
    @Mapping( target = "wellData.groundLevelPositioningMethod", source = "deliveredVerticalPosition.groundLevelPositioningMethod" )
    @Mapping( target = "wellData.owner", source = "owner" )
    @Mapping( target = "wellData.maintenanceResponsibleParty", source = "maintenanceResponsibleParty" )
```

does not map `owner` and `maintenanceResponsibleParty`.. Need to investigate futher.

**Comment by chris922** [comment]
Hey @sjaakd 

do you have more information in which cases the mentioned properties will not be mapped ? 
I tried to set up a testcase just with the information from this ticket and - at least with current version from `master` - everything works fine.

Best regards

**Comment by sjaakd** [comment]
@chris922 ..this is some while ago.. I guess its solved by now (new nested property mapping). Forgot to close this one. Sorry.
