### ISSUE TITLE
Non iterable to iterable mapping 

### ISSUE THREAD

**Issue by nnvnaveen** [mapstruct/mapstruct#1179]
Hi,

I have a requirement to convert non iterable mapping to iterable ..

class Car{
  String parent; 
  String name;
 String price;
}

class CarDto {
 String name;
 String price;
}

I've a mapper class like this 

@Mappings(@Mapping(target = "parent", source="company")
public abstract Car CarDtotoCar(String company, CarDto cardto );

this is working fine when converting from one to one. But if I want to covnert list of cardtos where all the list of car dtos has belongs to same company i am getting exception

public abstract Car **CarsDtotoCars**(String company, List<CarDto >cardto ); for this throwing 

**[47,49] Can't generate mapping method from non-iterable type to iterable type.**

**Comment by sjaakd** [comment]
Have you tried out [this](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-iterable-to-non-iterable) example?

**Comment by sjaakd** [comment]
@nnvnaveen .. Did the example solve your problem? Can we close this issue?

**Comment by gunnarmorling** [comment]
@nnvnaveen it isn't quite clear to me what behavior you'd like to achieve here. What's the semantics of mapping multiple `CarDto`s to one `Car`?

**Comment by filiphr** [comment]
@nnvnaveen I am going to close this issue as the example that @sjaakd pointed should be able to solve your problem. Please reopen if that is not the case
