### ISSUE TITLE
Adding partially custom methods 

### ISSUE THREAD

**Issue by avk2** [mapstruct/mapstruct#1181]
I would want to implement the mapping just for one of the fields of my pojo and let MapStruct do the rest, is that possible?

```
	default FooDto toDto(FooEntity e) {
		FooDto dto = new FooDto();
		dto.setField(someEncoding(e.getField));

		//MapStruct do the rest
	}
```

**Comment by filiphr** [comment]
Yes you can do this there are multiple ways it could be done:

* [Decorators](http://mapstruct.org/documentation/stable/reference/html/#customizing-mappers-using-decorators)
* With `@BeforeMapping` or `@AfterMapping` more [here](http://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after).

I would personally go for the `@BeforeMapping` or `@AfterMapping`

You can have mapper that looks like:

```java
@Mapper
public interface MyMapper {
    @Mapping(target = "field", ignore = "true")
    FooDto toDto(FooEntity e);

    @BeforeMapping
    default void beforeMapping(FooEntity e, @MappingTarget FooDto result) {
        result.setField(someEncoding(e.getField());
    }

    //Or with @AfterMapping
    @BeforeMapping
    default void afterMapping(FooEntity e, @MappingTarget FooDto result) {
        result.setField(someEncoding(e.getField());
    }
}
```

**Comment by filiphr** [comment]
I am going to close this as the question is answered. If you think that it should be reopened please reopen it
