### ISSUE TITLE
new surefire argline breaks debugging in netbeans

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1196]
The following change (but then commented in) makes in-IDE-debugging impossible in netbeans..

```java
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
<!--                <configuration>
                     to get jacoco report we need to set argLine in surefire,
                        without this snippet the jacoco argLine is lost
                    <argLine>@{argLine} -Xms1024m -Xmx3072m</argLine>
                </configuration>-->
            </plugin>
```

I know this was added for jacocco., but I think we should tweak the configuration a  little bit (lifecycle?). Don't know how Eclipse behaves.

**Comment by filiphr** [comment]
I noticed the same problem with IntelliJ as well. And they already have some bug reports: [IDEA-143187](https://youtrack.jetbrains.com/issue/IDEA-143187), [IDEA-172542](https://youtrack.jetbrains.com/issue/IDEA-172542) and [IDEA-167838](https://youtrack.jetbrains.com/issue/IDEA-167838). In IntelliJ there is a way to not use the surefire `argLine`. Is there something like this for Netbeans?

In any case, we can replace `@{argLine}` with `${argLine}` Jacoco is OK with that as well, the only thing is that the line is red in IntelliJ, but I think we can live with that :).

**Comment by sjaakd** [comment]
My debug console sais:
```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-cli) on project mapstruct-processor: Execution default-cli of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /Users/sjaak/Development/java/mapstruct/mapstruct/processor && /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java '@{argLine}' -Xms1024m -Xmx3072m -Xdebug -Xrunjdwp:transport=dt_socket,server=n,address=64531 -jar /Users/sjaak/Development/java/mapstruct/mapstruct/processor/target/surefire/surefirebooter5006881702416687555.jar /Users/sjaak/Development/java/mapstruct/mapstruct/processor/target/surefire/surefire7791156374175045809tmp /Users/sjaak/Development/java/mapstruct/mapstruct/processor/target/surefire/surefire_0766536464562516942tmp
-> [Help 1]
```

**Comment by filiphr** [comment]
Looks similar to the output of IntelliJ. Can you try with `${argLine} `? We can change it to that.

**Comment by sjaakd** [comment]
First thing I tried.. sorry.. no result..

**Comment by sjaakd** [comment]
checkout [this](http://stackoverflow.com/questions/12269558/maven-jacoco-plugin-error).  For now I call it a day..

**Comment by agudian** [comment]
Just define an empty argLine default in the properties-section of the pom - that should do it., shouldn't it?

**Comment by filiphr** [comment]
Just to note, defining an empty `argLine` in the properties does not work. Maven just evaluates it before jacoco has picked it up (I think). In any case, with that config jacoco didn't run

**Comment by gunnarmorling** [comment]
Done.
