### ISSUE TITLE
Custom component models for generated mappers

### ISSUE THREAD

**Issue by davidyee** [mapstruct/mapstruct#1206]
While MapStruct supports several common component models (`default`, `cdi`, `spring`, and `jsr330`), is it possible to allow custom component models to be implemented? 

For example, in the Dolphin Platform, they define a [custom scope called `ClientScope`](https://canoo.github.io/dolphin-platform/#_definition_of_the_client_scope). This annotation would be needed on a MapStruct mapper if it needs access to Dolphin Platform specific services such as its [bean manager](https://canoo.github.io/dolphin-platform/#_the_bean_manager). In this case, none of the existing MapStruct component models will work as the mapper needs to exist at a lifecycle "lower" than the session scope.

**Comment by filiphr** [comment]
I think that you can achieve what you need by implementing your own  [`ModelElementProcessor`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/ModelElementProcessor.java). I would suggest you to extend the [`AnnotationBasedComponentModelProcessor`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/AnnotationBasedComponentModelProcessor.java) and implement the abstract methods.

This is a service so you will need to define a file `META-INF/services/org.mapstruct.ap.internal.processor.ModelElementProcessor` with content the reference to your custom `ModelELementProcessor`. 

DISCLAIMER: This is not a public facing API, and is also used for some other internal steps, so be careful when changing the the priority. The API can also change between releases (although I doubt it 😄).
