### ISSUE TITLE
Component model default only works when uses are @Mapper

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1210]
If we have a class that we want to use in the mapper and we use the default component model then we search for it's implementation even though we can instantiate it like we need it.

e.g.

```java
public class MapperHelper {
//methods
}

@Mapper(uses = {MapperHelper.class})
public interface MyMapper {
//methods
}

//Generated mapper

public class MyMapperImpl implements MyMapper {

    private MapperHelper helper = Mappers.getMapper(MapperHelper.class);
//methods
}
```

If we improve the `Mappers#getMapper` do try and load the class actually passed as a last resort then one doesn't need to annotate the `MapperHelper` with `@Mapper`

**Comment by gunnarmorling** [comment]
Hum, that's weird. I'm pretty sure it works for using the JAXB factory classes and such.

**Comment by filiphr** [comment]
I'll do a better check for this. @cornzy said that he had to annotate a Mapper with `@Mapper` in the #1209 PR.

**Comment by filiphr** [comment]
This works OK. I don't know why @cornzy had problems.
