### ISSUE TITLE
Ambiguous mapping method but there is a most specific mapping

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1216]
I have a util class that has the following methods:

```java
public static java.util.Date toUtilDate(String strDate);
public static java.sql.TimeStamp toTimeStamp(String strDate);
public static java.sql.TimeStamp toTimeStamp2(String strDate);
public static java.sql.Date toSqlDate(String strDate);
```

I want to map from `String` to `java.util.Date`. I am getting an Ambiguous mapping error. I think that if an explicit mapping between `String` to `java.util.Date` exists then we should select that method. If the `toUtilDate` method didn't exists then we should throw the error.

WDYT?

**Comment by andresmontoyat** [comment]
H!, 

I have the following problem, this is my example: 

this is a model object:
```java
 public class CurriculumViewModel extends CurriculumModel
 ...
```

this is my mapper methods: 
```java
public CurriculumModel toCurriculumModel(Curriculum domain);

@Mappings({
            @Mapping(source = "id", target = "id"),
            @Mapping(source = "headLine", target = "headLine"),
            @Mapping(source = "summary", target = "summary"),
            @Mapping(source = "location", target = "location")
 })
public CurriculumViewModel toCurriculumViewModel(Curriculum domain);
```
this is my error message:
```
Ambiguous mapping methods found for mapping collection element to
```

**Comment by filiphr** [comment]
As discussed in the gitter [chat](https://gitter.im/mapstruct/mapstruct-users). We need some more information for the error in order to help you out. You might need to specify on which method exactly does the error occur and in which mapper.

**Comment by csxiaoshang** [comment]
> H!,
> 
> I have the following problem, this is my example:
> 
> this is a model object:
> 
> ```java
>  public class CurriculumViewModel extends CurriculumModel
>  ...
> ```
> 
> this is my mapper methods:
> 
> ```java
> public CurriculumModel toCurriculumModel(Curriculum domain);
> 
> @Mappings({
>             @Mapping(source = "id", target = "id"),
>             @Mapping(source = "headLine", target = "headLine"),
>             @Mapping(source = "summary", target = "summary"),
>             @Mapping(source = "location", target = "location")
>  })
> public CurriculumViewModel toCurriculumViewModel(Curriculum domain);
> ```
> 
> this is my error message:
> 
> ```
> Ambiguous mapping methods found for mapping collection element to
> ```
hi, do you slove this error? i found the same error.
