### ISSUE TITLE
[Feature] Pattern to match enum constants

### ISSUE THREAD

**Issue by doctor-zoidberg** [mapstruct/mapstruct#1220]
I need to map various enums, manually written and generated from WSDL:
```java
    public enum DomAttribute {

        CONSTANT_1,

        CONSTANT_2,

        CONSTANT_3,

        CONSTANT_4,

        // ...
    }
```
```java
    @XmlEnum
    public enum ToAttribute {

        @XmlEnumValue("TO:CONSTANT_1")
        TO_CONSTANT_1("TO:CONSTANT_1"),

        @XmlEnumValue("TO:CONSTANT_2")
        TO_CONSTANT_2("TO:CONSTANT_2"),

        @XmlEnumValue("TO:CONSTANT_3")
        TO_CONSTANT_3("TO:CONSTANT_3"),

        @XmlEnumValue("TO:CONSTANT_4")
        TO_CONSTANT_4("TO:CONSTANT_4"),

        // ...
    }
```
The problem is that the generated enums always have a prefix on their constant names. My current workaround is a custom mapper. However, I don’t like this solution that much. Of course, I could use a large list of `@ValueMappings` / `@ValueMapping` but this is quite tedious.

So I would really appreciate a solution where I could specify some sort of pattern (regex!?) to generate a mapper automatically. Is it possible? Thank you.

**Comment by filiphr** [comment]
There other issues similar to this one. Such as:

* #796 - Which is similar (if not the same as this one). As a solution it proposes using an SPI for matching `Enums`
* #1076 - Which proposes an SPI for general name matching strategies

Will a solution to one of those issues work for you? We are not big fans of wild card matching, but something in the direction of the 2 linked tickets is something interesting for us.

**Comment by doctor-zoidberg** [comment]
I can understand your concerns about wildcard patterns. So, I will look at your proposal for using an SPI and then report back. Thank you.

**Comment by doctor-zoidberg** [comment]
After reading issues #796 and #1076 I would say that an SPI as you prefer would do the trick for me.

Nonetheless, this solution feels a bit odd to me. You have to put a piece of your custom mapping in an external JAR module making it less understandable for another person reading the code. That is why I would prefer an annotation way like @twothe proposed in https://github.com/mapstruct/mapstruct/issues/1076#issuecomment-279988449.

However, as I said, a SPI would do the trick.

**Comment by filiphr** [comment]
Making it an SPI is not a must, it was a start that was proposed by others. And I agree with you I also prefer the approach in the comment as it makes your mappers and your mapping strategy much more flexible and makes it more understandable for a person reading the code. 

Would you be interested in helping out with the implementation of such feature?

**Comment by doctor-zoidberg** [comment]
At the moment I’m trying to understand the basic functionality of the mapstruct processor. Maybe a good idea comes along. But I can’t promise anything, because my time is rather limited. Anyway, who knows…

**Comment by filiphr** [comment]
Let us know if you need some help. There are multiple `ModelElementProcessor` that are responsible for multiple things. The core is the `MapperCreationProcessor`, more specifically the `MapperCreationProcessor#getMappingMethods` from there the entire creation of mapping methods starts

**Comment by doctor-zoidberg** [comment]
Now that I have a very basic understanding of how the mapstruct processor works, I managed to write a simple (for now unfortunately hard coded) enum pattern mapper that would fit my needs:

`ValueMappingMethod.Builder.enumToEnumMapping(Method method)`:
```java
...
            // Is inverse mapping? Maybe needed in the future...
            final boolean isInverse = ( InheritInverseConfigurationPrism
                    .getInstanceOn( method.getExecutable() ) != null ) ? true : false;

            // Start to fill the mappings with the defined valuemappings
            for ( ValueMapping valueMapping : trueValueMappings ) {
                String target =
                    MappingConstantsPrism.NULL.equals( valueMapping.getTarget() ) ? null : valueMapping.getTarget();
                mappings.add( new MappingEntry( valueMapping.getSource(), target ) );
                unmappedSourceConstants.remove( valueMapping.getSource() );
            }


            // add mappings based on name
            if ( applyNamebasedMappings ) {
                final PatternMatcher patternMatcher = new DefaultPatternMatcher();

                System.err.println( "MET: <" + method + ">" );
                System.err.println( "INV: <" + isInverse + ">" );
                // get all target constants
                List<String> targetConstants = method.getReturnType().getEnumConstants();
                for ( String sourceConstant : new ArrayList<String>( unmappedSourceConstants ) ) {
                    final String targetConstant;
                    if ("de.deutscherv.aufgabenverwaltung.dom.util.DOMDescriber.AufgabeAttribute"
                            .equals( method.getSourceParameters().get( 0 ).getType().getFullyQualifiedName() )) {
                        targetConstant = patternMatcher.toTarget( sourceConstant );
                    }
                    else if ("de.deutscherv.aufgabenverwaltung.ws.dom.AufgabeAttribute"
                            .equals( method.getSourceParameters().get( 0 ).getType().getFullyQualifiedName() )) {
                        targetConstant = patternMatcher.toInverseTarget( sourceConstant );
                    }
                    else {
                        targetConstant = sourceConstant;
                    }
                    if (targetConstants.contains( targetConstant )) {
                        mappings.add( new MappingEntry( sourceConstant, targetConstant ) );
                        unmappedSourceConstants.remove( sourceConstant );
                    }
                }
...
```

This way I found out, that there would be at least two problem areas in a generalized solution to talk about:

- functionality of @InheritInverseConfiguration
- Is the custom pattern class compiled and ready for execution during the mapstruct processing?

At the moment, I’m just focusing on the enum pattern mapping. I introduced a preliminary interface:
```java
public interface PatternMatcher {

    String toTarget( String source );

    String toInverseTarget( String source );
}
```
The implementing class just delivers the target name based on the source name. What way would you propose to get this class declared in an enum mapper?

**Comment by filiphr** [comment]
I was thinking something in the direction of:

```
public interface EnumMatchingStrategy {

    boolean matches(VariableElement source, VariableElement target);
}
```

Or as an alternative:

```
public interface EnumMatchingStrategy {

    String transform(VariableElement source);
}
```

Maybe the first one is more appropriate as it allows easier use of multiple strategies.

Where `VariableElement` is `javax.lang.model.element.VariableElement`. Or maybe wrap it in our type.

When you have access to the `VariableElement` then you can get the declaring class, i.e. the `enum` this means that you won't need to know whether you are doing a direct or inverse mapping. You can find that out based on the declaring class in your `EnumMatchingStrategy`.

All of this means that we will need to adapt the `Type#getEnumConstants()` to return a list of `VariableElement` (or our Type) instead of `String`.  This also means that there is no special logic for `@InheritInverseConfiguration` as the matching strategy is responsible for doing that.

Regarding:

>Is the custom pattern class available, compiled and ready for execution during the mapstruct processing?

The custom pattern will need to be loaded in some way and then just instantiated, we can create a util class that can do that. The processor has access to all the classes that you have on compile time, i.e. if you can write `@Mapper(matchingStrategy = MyMatchingStrategy.class)`, then MapStruct will have access to the class. Most probably we will require to have a public default constructor though.

>What way would you propose to get this class declared on an enum mapping method in a mapper?

I think that it needs to be declared as part of the `@Mapper` and `@MapperConfig` somehow. We don't have a special configuration annotation for enum mappings (like we have for the rest: `@BeanMapping`, `@IterableMapping`, `@MapMapping`).

**Comment by filiphr** [comment]
After some more thought about this, I think that it is better to go with the second option with `String` and not `VariableElement`. 

I think that the matching strategy should not have such in depth access to the element. If one needs such granular control one can always define a manual method. 

Your matching strategy should be removing a `TO_` prefix from the enums. Or remove all `_` like from the other issue.

What do you think?

**Comment by doctor-zoidberg** [comment]
Hmm, if I think a bit further and we want to have pattern matching not just limited to enums, then the `VariableElement` might be the more flexible way. Are there enough feature requests to consider this?

There is another problem regarding any of my changes. I just can contribute to mapstruct in some spare time while I’m at work. The problem is, besides being a git newbie; I can’t access github directly because of network restrictions. I can use the web interface, but that’s it. :-( I could send in patch sets. Or do you have another suggestion?

**Comment by filiphr** [comment]
For me it is the other way around, I can usually work on MapStruct during the evenings 😄.

I think that there are enough feature requests to consider adding a general name matching strategy. I am only not sure whether we need one for name matching and one for enums. Using `VariableElement` is not appropriate on other places, maybe `Element`.  MapStruct actually uses the `getter` and `setter` methods to extract the property names via the `AccessorNamingStrategy`. 

Regarding your contribution I would suggest to you to download the source code as zip, you can do that via the web interface. Then create a git repository locally on your disk (git doesn't need a server), have a look [here](https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/) until and with step 6. You can then create patch sets and send them here, I can use them to create a branch in my repository and commit those patches (with you as an author of course 😄).

In any case patches will be OK whatever you do.

**Comment by doctor-zoidberg** [comment]
Fine, that was the way I went to understand the mapstruct fundamentals. In my local repository, I then created a branch and wrote the very first example how the design in principle could be.

Okay, now I take a closer look on `AccessorNamingStrategy` to create a more general solution.

**Comment by doctor-zoidberg** [comment]
You are right; bean mapping is a different story. So let’s focus on enums.

I find it very useful to define forward and reverse mapping in one custom mapper. Therefore, you always need to know what your source is and what your target type is. This way you can also map a source enum to different target enums with maybe different prefixes quite easily. Moreover, you don’t need to know explicitly if it’s inverse mapping. Am I right?

My proposals are:
```java
public interface EnumMatchingStrategy {

    boolean matches( VariableElement source, VariableElement target );

    // or
    boolean matches( String sourceEnum, Class<? extends Enum<?>> source, Class<? extends Enum<?>> target );

    // or
    String transform( VariableElement source, VariableElement target );

    // or
    String transform( String sourceEnum, Class<? extends Enum<?>> source, Class<? extends Enum<?>> target );

}
```
What do you think?

**Comment by filiphr** [comment]
What does the transform return?

I think that the ones with the `VariableElement` are more appropriate, during compilation time you don't need to uses `Class`. 

I am still not sure if we need to know what is source what is target. The strategy will be used on mapper level, and if you need to map a source enum to a target enum with different prefixes, I don't think you need to know what is what.  If your mappings to different targets are in different mappers then you can use other strategies that strip the prefix. Additionally it will be easier to test the strategies and they would not know about source target.

What you are saying you can always achieve with a custom mapping method like:

```java
public TargetEnum map(Source source) {
    if (source == null) {
         return null;
    }

    String sourceValue = source.name();
    try {
        return TargetEnum.valueOf("PREFIX_" + sourceValue);
    } catch (IllegalArgumentException ex) {
        return null; //Or default
    }
}
```

I would also like to hear what the others @gunnarmorling, @agudian and @sjaakd think about this.

**Comment by doctor-zoidberg** [comment]
What do you exactly mean with “mapper level”? Is it the whole `@Mapper` class (class level) or mapping method (method level) within?

To your question: The `transform()` method returns the constants name `String` for the `MappingEnty`.

**Comment by filiphr** [comment]
>What do you exactly mean with “mapper level”? Is it the whole `@Mapper` class (class level) or mapping method (method level) within?

Yes I mean the class / interface level.

The `MappingEntry` must stay like it is. The `source` in the `MappingEntry` must be the actual name of the `enum` as that is used in the generated code. 

What I meant with the question about the transform, is does it return the name for comparison of the `source` or the `target`?

**Comment by doctor-zoidberg** [comment]
It returns the String representation of the target constant modified with the desired (prefix) pattern. This method transforms all source enum constants not already mapped by a `@ValueMapping`.

I used this idea in my playground example: https://github.com/mapstruct/mapstruct/issues/1220#issuecomment-308103621

**Comment by doctor-zoidberg** [comment]
I really don’t want to urge anybody. Nevertheless, are there any news regarding a possible API design?

**Comment by sjaakd** [comment]
related to #1076

**Comment by filiphr** [comment]
Recently we added new `EnumNamingStrategy` and `EnumTransformationStrategy` that would enable the use case in the issue.

For the given example the following mapper can be written:

```
@Mapper
public interface AttributeMapper {

    @EnumMapping(nameTransformationStrategy = "prefix", configuration = "TO_")
    ToAttribute map(DomAttribute attribute);

    @InheritInverseConfiguration
    DomAttribute map(ToAttribute attribute);
}
```

Instead of `@InheritInverseConfiguration` it is also possible to do:

```
@Mapper
public interface AttributeMapper {

    @EnumMapping(nameTransformationStrategy = "prefix", configuration = "TO_")
    ToAttribute map(DomAttribute attribute);

    @EnumMapping(nameTransformationStrategy = "stripPrefix", configuration = "TO_")
    DomAttribute map(ToAttribute attribute);
}
```

There are 4 out of the box strategies:

* **prefix**
* **stripPrefix**
* **suffix**
* **stripSuffix**

All of this are in the `org.mapstruct.MappingConstants` as constants.
