### ISSUE TITLE
A feature request?

### ISSUE THREAD

**Issue by egervari** [mapstruct/mapstruct#1226]
I've read over all of the documentation, and there is one feature I'm wondering if it's currently supported, and if not, I am wondering if it could be added?

# Inheritance Mappings

Let's say I have a `UserActivity` class, and it has 5 sub-classes. Is there a way to specify mappings for the base class, such as `List<UserActivityDto> userActivitiesToUserActivityDtos(List<UserActivity> userActivities)` and have it be smart enough to map the sub-classes for each type of `UserActivity`? This would be super handy to have.

I've tried to use decorators to implement the above functionality, and no luck. I've also tried to use `@BeanMapping` and factories, but I couldn't get it to work.

So, I've basically resorted to writing a switch statement manually, and I'm just calling the specific mappers for each type of `UserActivity`. This works, but was wondering if there was a more automated approach:

```
default UserActivityDto toUserActivityDto(UserActivity userActivity) {
    switch (userActivity.getType()) {
      case "CreatedCourseOfferingUserActivity":
        return toUserActivityDto(
          (CreatedCourseOfferingUserActivity) userActivity
        );
      case "CreatedCourseUserActivity":
        return toUserActivityDto(
          (CreatedCourseUserActivity) userActivity
        );
      case "CreatedDiscussionTopicUserActivity":
        return toUserActivityDto(
          (CreatedDiscussionTopicUserActivity) userActivity
        );
      case "EnrollmentStateChangedUserActivity":
        return toUserActivityDto(
          (EnrollmentStateChangedUserActivity) userActivity
        );
      case "PublishedCourseVersionUserActivity":
        return toUserActivityDto(
          (PublishedCourseVersionUserActivity) userActivity
        );
      default:
        return null;
    }
  }
```

I'm really hoping it's possible right now, and this was not documented. Crossing fingers.

Thank you!

Katie

**Comment by egervari** [comment]
Yep, I didn't realize that @MappingTarget would work in my case - but I tried it and updating the existing instance seems to be working now ;)

It's too bad the library can't see the hierarchies and infer them. As you can see from my code above, I did eventually arrive to your simplified second code snippet. I'm glad I was on the right track at least. That's super helpful to know your answers so I don't go digging for other possible solutions, thank you ;)

This is a really cool library btw. I was using ModelMapper before, but I like this one much better. Thanks for writing it!!

**Comment by sjaakd** [comment]
@egervari , it will find the hierarchy.. But once you use update methods MapStruct starts looking for property mappings (prefeer) to call which are also update methods.

**Comment by filiphr** [comment]
It's really awesome that you like it 😄.

Regarding the hierarchy, you meant about the mapping inheritance right? The thing is MapStruct generates code and during compile time it only knows that you are mapping `UserActivity` to `UserActivityDto`. The more specific type of the object in the list will only be known during runtime and we don't do anything on runtime. There is no reflection in the generated code and we don't want any 😄 

The only thing that we can do as a feature is to create those `instanceof` calls if there is a method that can map the more specific class. However, I think that this might lead to unexpected outcome for some people, as sometimes you just want to map the base classes. I am not sure how I personally feel about having MapStruct generate the `instanceof` checks.

Should we close this issue or you want to keep it is a feature request (if there is some way for us to do this).

**Comment by agudian** [comment]
Btw, we have an issue describing that second feature as well: #131 Support for Type-Refinement mapping (or Downcast Mapping). It discusses two alternative approaches on how MapStruct could collect the information about the available sub-types.
So I'd suggest we close this issue here...

@egervari if you feel we need something else as described in #131, just reopen... 😃
