### ISSUE TITLE
Support for flattening of nested collections

### ISSUE THREAD

**Issue by shobhitsahay** [mapstruct/mapstruct#1228]
Let's say we have

    class ClassA {
     String aId;
     List<ClassB> bList;
    }

    class ClassB {
     String bId;
     List<ClassC> cList;
    }

    class ClassC {
     String cId;
    }

and we want to flatten it to following class

    class ClassD {
     List<ClassE> eList;
    }

    class ClassE {
     String aId;
     String bId;
     String cId;
    }

Can we flatten it without writing a custom method?

**Comment by filiphr** [comment]
For the sake of argument. How will a custom method look like?

Do you want to have per nested `ClassC` one `ClassE`. For example if we have:
 
1 `ClassA` with 2 `ClassB` each having 3 `ClassC` you will end up with one `ClassD` with 6 `ClassE`?

**Comment by shobhitsahay** [comment]
I was able to do this using custom method.
This usecase looks like a pattern to me, same as you mentioned. I have 1 ClassA with x ClassB each having y ClassC and I want to map it to 1 ClassD with (x*y) ClassE. Moreover, all fields of ClassE can be mapped to that of ClassB and ClassC.

Is there someway already or something planned to solve the above pattern. Custom methods are certainly an option but is there a way to solve it the MapStruct way?

**Comment by gunnarmorling** [comment]
Nope, there's no support for this in MapStruct atm, i.e. you'll need to resort to a custom mapping method. It seems quite special to me, so I'm not sure whether we should add support for this to MapStruct.

**Comment by filiphr** [comment]
This can be theoretically done using `@Context` with `@AfterMapping` and `@ObjectFactory`. However, it is much more complicated than writing it by hand. Therefore, I would say go for the hand mapping for this use case.

**Comment by filiphr** [comment]
@shobhitsahay I will close this issue, if you think that it needs to be reopened please let us know.
