### ISSUE TITLE
Set up japicmp on the API module to track API changes

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1231]
See https://github.com/siom79/japicmp

**Comment by filiphr** [comment]
I've played around with this a bit.

What exactly do we want to do with the plugin. Do we want to have build failures or just use the report for publishing?

Which packages do we want to include?

In my opinion we need this:
* Entire mapstruct and mapstruct-jdk8 modules
* exclude everything from `org.mapstruct.ap.internal` and `org.mapstruct.shaded` for the processor module

Do we maybe want to include `org.mapstruct.ap.internal.processor`?

BTW. It is a nice tool 😄

**Comment by gunnarmorling** [comment]
> In my opinion we need this

What you suggest is the same I had in mind. I wouldn't include anything from `internal`.

> Do we want to have build failures or just use the report for publishing?

I've used it for informational purposes only so far, but we can try and have it fail the build if it detects any breakages. Always easy to turn that off in case it comes up with false reports.
