### ISSUE TITLE
Encoding problem when compiler is Eclipse JDT (IDE)

### ISSUE THREAD

**Issue by glauberferreira** [mapstruct/mapstruct#1238]
Hi all.

I am using MapStruct (1.1.0.Final) in a Maven (3.5.0) based project with Java 1.8. My OS is Windows 10 and I am using Eclipse Neon with the most recent version of m2e-apt plugin. My POM file has been configured according to MapStruct [documentation](http://mapstruct.org/documentation/stable/reference/html/#_apache_maven) plus _project.build.sourceEncoding = UTF-8_.

My project has a Mapper with a Mapping that has a _constant_ parameter that use an acute accent in a portuguese word (e.g salário = salary in english).

	@Mapping(target = "tipo", constant = "salário")

When I am using Eclipse for editing and compiling, the generated MapperImpl class produces an incorrect character: sal�rio. This is the _comments_ attribute in the Generated annotation, indicating that Eclipse has been used.

    comments = "version: 1.1.0.Final, compiler: Eclipse JDT (IDE) 1.2.100.v20160418-1457, environment: Java 1.8.0_131 (Oracle Corporation)"

On the other hand, when I execute _mvn clean compile_ on the command line, the code is generated correctly, with the word salário. This is the _comments_ attribute in the Generated annotation...

    comments = "version: 1.1.0.Final, compiler: javac, environment: Java 1.8.0_131 (Oracle Corporation)"

Is it possible to configure Eclipse to use maven/javac to generate MapStruct code? Or how can I solve this encoding problem and continue to use Eclipse for generating MapStruct code?

Thanks in advance.

**Comment by shalugin** [comment]
Is it related to #883 ?

**Comment by filiphr** [comment]
I don't think that is the problem. If #883 was the problem then the maven compilation should not work. 

@glauberferreira maybe you need to configure the locale for the Eclipse compilation. I am not using Eclipse, so I can't help here. @agudian do you know more about this problem?

**Comment by sjaakd** [comment]
@glauberferreira : it seems that the [JDT Batch compiler](https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm)  also has an encoding option. Don't know how to get Eclipse to use this. But I reckon there should be a config file somewhere.

**Comment by glauberferreira** [comment]
I have made many searches but no success.  Some additional information that I identified...

- my _platform encoding_ when I execute _mvn -v_  is _Cp1252_. But since _project.build.sourceEncoding = UTF-8_ everything is fine with Maven. I think this is reason.
- the generated MapperImpl .java file has text file encoding equals to UTF-8. Is is inherited from Maven pom.xml

@agudian can you help me with some tip related to Eclipse compiler configuration?

**Comment by gunnarmorling** [comment]
You could try "Properties" (of your project) -> "Maven" -> "Annotation Processing" -> "Delegate annotation processing to maven plug-ins".

**Comment by glauberferreira** [comment]
@gunnarmorling My Eclipse is already configured in this way. But even so the Generated code are compiled with Eclipse JDT (IDE).

**Comment by gunnarmorling** [comment]
I see. What's the encoding for your project in Eclipse (or,
"target/generated-sources", for that matter)? Is it "UTF-8"? (right-click
the source directory in your project, then "Resource").

**Comment by glauberferreira** [comment]
Project is UTF-8. Source folder and *MapperImpl.java files are also UTF-8.

**Comment by filiphr** [comment]
@glauberferreira Did you resolve your problem? Can you share more information with use, do we need to do something on our side?

**Comment by filiphr** [comment]
It seems this is no longer a problem. Closing the issue. Please let us know if we need to reopen
