### ISSUE TITLE
Ambiguous factory method for @ObjectFactory with and without parameters

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1242]
In the javadoc of the new `@ObjectFactory` we state:

> If there are two factory methods, both serving the same type, one with no parameters and one taking sources as input, then the one with the source parameters is favored. If there are multiple such factories, an ambiguity error is shown.

However, when that situation actually occurs. Currently we have compile error ambiguous factory methods. Should we update the implementation or the Javadoc?

**Comment by agudian** [comment]
I double checked. That was part of the original PR and a result of the discussions about that feature. I missed that the case was not covered in the tests and during the refactoring done in 79f87e8833e53b232eb93985c1555378abb52db3, I broke that feature. Let me add it back again... 😁

**Comment by filiphr** [comment]
It looks like we also missed in the review as well :smile:. Sure let's add it back and add a test for it :smile:
