### ISSUE TITLE
Access to Types and Elements in AccessorNamingStrategy

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1253]
Looking at the implementation of the example for the Protobuf `AccessorNamingStrategy` I think that it could benefit if it could have used `javax.lang.model.util.Types` and `javax.lang.model.util.Elements`.

If we had those than instead of:

```java
@Override
public String getElementName(ExecutableElement adderMethod) {

    String methodName = super.getElementName(adderMethod);
    Element receiver = adderMethod.getEnclosingElement();
    if (receiver != null && receiver.getKind() == ElementKind.CLASS) {
        TypeElement type = (TypeElement) receiver;
        TypeMirror superType = type.getSuperclass();
        if (superType != null && PROTOBUF_GENERATED_MESSAGE_V3.equals(superType.toString())) {
            methodName += LIST_SUFFIX;
        }
    }
    return methodName;
}
```

We could have had:
```java
@Override
public String getElementName(ExecutableElement adderMethod) {

    String methodName = super.getElementName(adderMethod);
    Element receiver = adderMethod.getEnclosingElement();
    TypeElement protoGenMessageV3 = elements.getTypeElement(PROTOBUF_GENERATED_MESSAGE_V3);
    if (receiver != null && types.isAssignable(receiver.asType(), protoGenMessage.asType())) {
        methodName += LIST_SUFFIX;        
    }
    return methodName;
}
```

Of course the implementation can be even more optimized by storing the `protoGenMessageV3` in the class.

I see two ways of achieving this:

* Add a new method to the `AccessorNamingStrategy` with which we can set the `Types` and `Elements` 
* Pass the `Types` and `Elements` to the current methods

**Comment by sjaakd** [comment]
Now with Java8 only it becomes more easy. Just add an default `init` method doing nothing. The user can override when the need arises to use `TypeUtils` and `ElementUtils`. The code remains downward compatible.

 I considered having passed the complete `javax.annotation.processing.ProcesssingEnvironment` but perhaps its better to only take `TypeUtils` and `ElementUtils` as argument of the `init` method.
