### ISSUE TITLE
Report ambiguous factory methods at call site

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#126]
Currently ambiguous factory methods are reported at their declaration site, but they should be reported at the call site (i.e. at a method which makes use of a factory methods and it's not clear which one should be chosen), because that's the place where the ambiguity is to be resolved (once we provide support for that using "qualifiers" or similar).

**Comment by gunnarmorling** [comment]
@sjaakd, Do you know whether that's actually still an issue?

**Comment by filiphr** [comment]
I think that we can close this one. It should be already resolved. @gunnarmorling [this](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/InheritanceSelectionTest.java#L66) test method what you meant?

**Comment by gunnarmorling** [comment]
Already closed.
