### ISSUE TITLE
CDI injection problem

### ISSUE THREAD

**Issue by bolosq** [mapstruct/mapstruct#1262]
Hi.
I just started playing with MapStruct and I like it so far, but I can't get CDI to work.
Weld is complaining about unsatisfied dependency:

`Unsatisfied dependencies for type MessageMapper with qualifiers @Default`

Here is my mapper interface:
```
@Mapper(
    componentModel = "cdi"
)
@Local
public interface MessageMapper {
    // some stuff
}
```
Generated mapper implementation:
```
@ApplicationScoped
public class MessageMapperImpl implements MessageMapper {
    // some generated stuff
}
```
My injection point:
```
@Inject private MessageMapper messageMapper;
```

Shouldn't generated mapper have annotation `@Local` like this?:
```
@ApplicationScoped
@Local(MessageMapper.class)
public class MessageMapperImpl implements MessageMapper {
    // some generated stuff
}
```
As I'm new to MapStruct maybe I'm missing something?

**Comment by gunnarmorling** [comment]
What annotation is `@Local`? Is it a custom qualifier annotation of your's? Or `@Local` from EJB`? In case of the latter I'm sure we don't have any special support for that.

**Comment by filiphr** [comment]
@bolosq I am going to close this issue due to inactivity on your side. When you provide us with more info we can reopen it.
