### ISSUE TITLE
Conflicts while obfuscation.

### ISSUE THREAD

**Issue by Hamzaaton** [mapstruct/mapstruct#1264]
Hi, 

I am trying to obfuscate my source code, the project use (the very fancy) mapstruct to generate mappers' implementations. 

As the  Component-annoted mapper implementation refers to the mapper with an Autowired annotation. And with both of them taking similar classnames ("a" for example, after obfuscation) it causes a conflict due the missing name attribute of the Component. 

> If such an annotation contains no name value or for any other detected component (such as those discovered by custom filters), the default bean name generator returns the uncapitalized non-qualified class name.

Is it possible to add a name attribute to the Mapper and in the Implementation with the Autowired we add another Qualifer annotation with the Mapper's name?

**Comment by filiphr** [comment]
I am not sure I understand completely. You want the `@Component` annotation that is written on top of the class to contain the name of the pre-obfuscated class?

The only benefit of what you are looking for is for obfuscated code. Therefore, I am not sure if this is something that we would be interested in having.

In any case, there is an unofficial way with which you can achieve what you are looking for. There is `ModelElementProcessor` which is implemented as an SPI and if you provide your own implementation of `AnnotationBasedComponentModelProcessor` then you might be able to make it work. The `SpringComponentProcessor` is the processor that does the work for the spring `componentModel`. You will need to make sure that your implementation runs after the MapStruct one.

If you do what you need then the obfuscation of that particular part will not make a difference. For example, you are going to expose the names of the `Mapper`(s) and all your components.

**Comment by sjaakd** [comment]
@Hamzaaton I'm cleaning up open issues. I see there's no reaction on the remarks of @filiphr .. Can you comment? In case of no response,  I'll proceed to close the issue soon.

**Comment by filiphr** [comment]
There is actually a really neat way to achieve this with Spring. One needs to use [`ComponentScan#nameGenerator`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/ComponentScan.html#nameGenerator--)

**Comment by chris922** [comment]
Additionally #1427 would give you the possibility to chose an own name for the spring bean. But it is not yet clear whether, and if so in which release, the PR will be integrated.
