### ISSUE TITLE
CR1 still broken packages support

### ISSUE THREAD

**Issue by Guchman** [mapstruct/mapstruct#1265]
Hi! Still have same issue as in beta with loombok support.
```
package ru.home.api.goods.converters;

import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface GoodsConverter {
    ru.home.api.goods.model.Goods convert(ru.home.thrift.goods.entity.Goods source);
}
```
Generates 
```
package ru.home.api.goods.converters;
import javax.annotation.Generated;
import org.springframework.stereotype.Component;
import ru.goods.thrift.goods.entity.Goods;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2017-08-05T20:10:26+0300",
    comments = "version: 1.2.0.CR1, compiler: javac, environment: Java 1.8.0_112 (OracleCorporation)")
@Component
public class GoodsConverterImpl implements GoodsConverter {

    @Override
    public ru.home.api.goods.model.Goods convert(Goods source) {
        if ( source == null ) {
            return null;
        }
        ru.home.api.goods.model.Goods goods = new ru.home.api.goods.model.Goods();
        return goods;
    }
}
```
Line
**ru.home.api.goods.model.Goods goods = new ru.home.api.goods.model.Goods();**
Is very wrong as you see.

**Comment by filiphr** [comment]
@Guchman what exactly is wrong with the generated code? The packages are correct.

Is it some problem with Lombok? How does your setup look like and which version of Lombok you are using?

**Comment by filiphr** [comment]
>Line
**ru.home.api.goods.model.Goods goods = new ru.home.api.goods.model.Goods();**
Is very wrong as you see.

The line is not wrong, your target class is `ru.home.api.goods.model.Goods` and MapStruct is creating `ru.home.api.goods.model.Goods goods` so it can map it from `ru.goods.thrift.goods.entity.Goods`.

There are no setters in `ru.home.api.goods.model.Goods` and that is why nothing is mapped. If you are using Lombok, make sure that you are using Lombok that supports MapStruct and your setup is like the one from the [mapstruct-lombok](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok) example.

**Comment by Guchman** [comment]
Sorry, you're right. I'd use wrong lombok version. Please delete this stupid issue)

**Comment by filiphr** [comment]
Thanks for clearing this up. Closing the issue is enough. You can't delete issues in Github

**Comment by filiphr** [comment]
Thanks for clearing this up. Closing the issue is enough. You can't delete issues in Github
