### ISSUE TITLE
Control creation of nested objects

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1275]
Consider the following class:

```java
NestedSource{ 
  String propA;
  String propB;
}
```
and:

```java
Target{
   NestedTarget nestedTarget;
}
```

With `NestedTarget`:

```java
NestedTarget{ 
  String propA;
  String propB;
}
```

With `SourceTargetMapper`:

```java
SourceTargetMapper{

   @Mapping( target = "nestedTarget.propA" source = "propA" )
   @Mapping( target = "nestedTarget.propB" source = "propB" )
   Target map( Source source )
}
```
It would be nice to have some control if the `NestedTarget` class is actually instantiated if both source props (`propA` and `propB` ) are `null`. 

Especially when one considers that the reverse case works like that. Ergo: if the `nestedTarget=null` then  the source `propA` and `propB` are `null` as well (could not be otherwise).

**Comment by filiphr** [comment]
I think that this one is exactly the same as #1166.

Currently this can be achieved, by writing a `@AfterMapping` which will set the `nestedTarget` to `null` if both properties inside are `null.

Reverse case is easier as we have one entry point, in this case the number of possibilities is arbitrary

**Comment by sjaakd** [comment]
> I think that this one is exactly the same as #1166.

I think you are right... :smile:
