### ISSUE TITLE
Don't depend on Sonatype OSS Parent POM any longer

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1281]
As per [this guide](http://central.sonatype.org/pages/apache-maven.html#deprecated-oss-parent) this parent POM is deprecated and not maintained anymore. Instead, we should pull all the required configuration into our own parent POM. The required changes can be taken from ModiTect, where I just [applied them](https://github.com/moditect/moditect/compare/69e20d236231a3156233418069aa823183e4f003...a02ec309f7d9b9192bc3fa2bd4307c1fe55e453a).

**Comment by filiphr** [comment]
@gunnarmorling Do you deploy snapshots via Travis? Did you do something for that in ModiText?
