### ISSUE TITLE
How to add constans string to target field?

### ISSUE THREAD

**Issue by 234424169** [mapstruct/mapstruct#1284]
for example,I have a field "filename" and its value is "xxx.jpg".I want to convert this String to another DTO "completeFileName".I want to add a constant String before the orgin value like "c:\\abc\xxx.jpg".Then how do i complete this work?

**Comment by filiphr** [comment]
@234424169 This is a question meant for StackOverflow, our [Google Group](https://groups.google.com/forum/#!forum/mapstruct-users) or our [gitter chat](https://gitter.im/mapstruct/mapstruct-users).

In any case there are multiple ways to achieve what you want. You can do it via custom mapping only specific for this, or you can do it by using `@AfterMapping`. 

It would also be beneficial if you share with us what you have done.
