### ISSUE TITLE
Enum .toString() instead of .name()

### ISSUE THREAD

**Issue by dentych** [mapstruct/mapstruct#1286]
Hello.

I am aware that there has been an issue + PR that changed enum.toString() to enum.name() because it's safer to use. However, I am now in a position where I need MapStruct to call enum.toString(). So before I'm doing a whole lot of things, is there any option to change it back to toString()

**Comment by filiphr** [comment]
@dentych It was done within #540. I think that this is more "correct" as we are trying to do mappings and maintain the state of the enum.

Why do you think that you need to do a lot of things?

You would need to have your place where you can do the mapping:

```java
public class EnumConverter {

    public static String convert(Enum<?> source) {
        return source == null ? null : source.toString();
    }

    public static <E extends Enum<E>> E convert(String source, @MappingTarget Class<E> enumType) {
        // You probably need something else here as the methods are not symmetrical
        return source == null ? null : Enum.valueOf( enumType, source );
    }
}
```

You then need to make sure that you use this in your mappers by `@Mapper(uses = {EnumConverter.class})`. Or add it to a config that you use in your mappers.

**Comment by dentych** [comment]
Hello @filiphr 

Thank you for your reply.

I agree that it is the more correct approach, to use the enum name. However, I need the toString solution. I did figure out a solution that looks much like your example, so I will close this issue as it isn't an issue anyway.

Have a nice day :)

**Comment by filiphr** [comment]
Thanks for the tip @mistic100. I have also updated my reply so someone else doesn't have the same issues 😄
