### ISSUE TITLE
Mapstruct [Gradle]: Doesn't generate using of @Named methods

### ISSUE THREAD

**Issue by xxMikhailx** [mapstruct/mapstruct#1289]
I'm trying to specify the method for mapping using the qualifiedByName+@Named. It works using maven but doesn't work while I'm using gradle. Mapstruct vesion: 1.1.0.Final. Gradle version: 4.1

Mapper implementation differs from Maven to Gradle.

**Comment by filiphr** [comment]
The only difference between Maven and Gradle is the setup for invoking our Annotation Processor. Therefore it is really strange why this is happening. Is something even generated with Gradle? Can you provide us with a reproducing project?

And just to be sure, you are using the `@Named` from the MapStruct package right? Not the `javax` one?

**Comment by xxMikhailx** [comment]
> And just to be sure, you are using the @Named from the MapStruct package right? Not the javax one?
Yes, I am using @Named from the MapStruct, I've checked this several times.

Secondly, I used this example to setup annotation processor: [mapstruct-on-gradle](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-on-gradle/build.gradle)

I can only give this example to you:

```
@Mapper(componentModel = "spring", uses = { ObjectFactory.class })
public abstract class Mapper
{
    @Mapping(target = "query", source = "model", qualifiedByName = "switchByType")
    @Mapping(target = "loginCredentials.pin", source = "password")
    abstract public LoginRequestType map(LoginRequest model);

    @Named("switchByType")
    protected QueryType mapToQuery(LoginRequest model)
    {
        CredentialType credentialType = CredentialTypeResolver.resolveByUserName(model.getUserName());
        if (credentialType == PROGRAM)
        {
            return mapToMembershipKey(model);
        }
        else if (credentialType == EMAIL)
        {
            return mapToEmail(model);
        }

        return null;
    }

    @Named("mapToKey")
    @Mapping(target = "id", source = "userName")
    @Mapping(target = "code", constant = "PC")
    abstract protected ProgramKeyType mapToKey(LoginRequest model);

    @Named("mapToEmail")
    @Mapping(target = "email", source = "userName")
    abstract protected EmailEntryType mapToEmail(LoginRequest model);
}
```

So, when the implementation is generated by Maven the method "mapToQuery" is used, but when the impl is generated by Gradle it uses the "mapToKey" somehow...

**Comment by filiphr** [comment]
@xxMikhailx This is really strange. I would try to create an example of this. It should work, especially because it is working with maven.

Can you share your gradle config?

I didn't mean you to provide us your source code, but if you can provide us with a toy example where you can reproduce the error than it would be much easier for us to fix this.

**Comment by xxMikhailx** [comment]
So, a kind of workaround for this is to divide this interface to three interfaces. One for `mapToQuery` and `map` methods, another for `mapToKey`, and the last one for `mapToEmail`.

Then, MapStruct generated implementation uses the right method for switching mappings.

**Comment by sjaakd** [comment]
@xxMikhailx .. Is this still an issue?

**Comment by xxMikhailx** [comment]
No, I think you can close the issue. We've used the workaround described by me earlier and we don't have this logic at all for now.
Thank you.

**Comment by sjaakd** [comment]
@xxMikhailx It still sounds strange. 

Note: You can also use a defined qualifier (`@Qualifier`) . Checkout this [example](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-rounding/src/main/java/org/mapstruct/example/mapper/util/RoundingUtil.java).
