### ISSUE TITLE
( Sbt build tool) Impl class is not  generated for abstract mapper class while testing with JUnit 4.4

### ISSUE THREAD

**Issue by SATHEESHREDDY559** [mapstruct/mapstruct#1291]
Hi,

I'm new to MapStruct. When I run JUnit test cases for Mapper class, I got errors Caused by: java.lang.ClassNotFoundException: Cannot find implementation for SomeMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:93)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:76)

Please help me out.

Regards,
Satheesh

**Comment by filiphr** [comment]
@SATHEESHREDDY559 Are you using MapStruct with Scala?

How does your setup look like? How are you running your JUnit tests, via IDE (which one), via build tool? We need more information in order to help you out

**Comment by SATHEESHREDDY559** [comment]
Thank you for the quick reply.

I'm using MapStruct with Java. using eclipse IDE, SBT build tool and trying to run JUnit test cases. Test cases are failed either way. 
I have abstract mapper class (ProductMapper.java), other java class(ProuductAdapter.java) which invokes mapper abstract mapper class. In my test class, I'm using ProductAdapter class object.

**Comment by filiphr** [comment]
Until now we haven't had an example with the SBT build tool, so unless I see your build config I won't be able to help you. I have never used SBT qith Java before as well. 

For the processor to work in Eclipse you'll need to somehow configure it to invoke the Annotation Processor.

If you share an example project that I can play with it would be great 😀

**Comment by SATHEESHREDDY559** [comment]
How do I configure the processor to work in Eclipse?

**Comment by filiphr** [comment]
[here] (http://mapstruct.org/documentation/ide-support/), you can find how 😀. I am not sure how it works with SBT though

**Comment by SATHEESHREDDY559** [comment]
You know what It's working in real time like testing with RestClient. But, in eclipse IDE my test cases are not getting passed.

**Comment by filiphr** [comment]
I am an IntelliJ user. Make sure that Annotation processing is configured correctly in your IDE. I don't know exactly how to do it in Eclipse

**Comment by FBHPLUS** [comment]
you can find how to configure here

https://stackoverflow.com/questions/45518161/how-to-get-eclipse-to-generate-mapstruct-mappers-using-gradle
