### ISSUE TITLE
Update examples to GenericMapper base interface

### ISSUE THREAD

**Issue by slavb18** [mapstruct/mapstruct#1292]
Examples  can include GenericMapper base interface usage
E.g.
```java
public interface GenericMapper<E,D> {
    
    D createFromEntity(E entity);

    E createFromDto(D dto);

    void updateEntity(@MappingTarget E entity, D dto);

    List<D> createFromEntities(List<E> entities);

    List<E> createFromDtos(List<D> dtos);
    
}
```
and specific mapper
```java
@Mapper(componentModel = "spring")
public interface DocfileMapper extends GenericMapper<SomeEntityClass,SomeDtoClass>{

}
```

**Comment by filiphr** [comment]
@slavb18 I don't quite understand what this issue is for? Are you talking about adding something like that to: https://github.com/mapstruct/mapstruct-examples?

**Comment by slavb18** [comment]
Why not introduce generic mapper as core mapstruct concept, as it done in spring data jpa, for example? This will simplify make more standard mapper definitions.
E.g. basic mapper functionality could be described by only extending generic interface.

Please see https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.core-concepts 

```java
public interface CrudRepository<T, ID extends Serializable>
    extends Repository<T, ID> {

    <S extends T> S save(S entity); 

    T findOne(ID primaryKey);       

    Iterable<T> findAll();          

    Long count();                   

    void delete(T entity);          

    boolean exists(ID primaryKey);  

    // … more functionality omitted.
}
```

**Comment by filiphr** [comment]
@slavb18 now I understand what you mean. In my opinion this is something which really easily can be achieved by each project on their own. I don't see the benefit of having such an interface within MapStruct. The only functionality that you are going to get with the generic mapper are predefined methods that MapStruct needs to implement. However, there are a lot of cases where mapping needs to be done one way, or one needs to customize the mapping (use `@Mapping`) between particular objects. With a generic mapper such things are more difficult. 

Maybe we can add such an example in the examples, but not in core.

Also in case you want some more standardisation I think that JHipster had a generic interface. However, I cannot find it right now. You can see their writeup about dtos [here](http://www.jhipster.tech/using-dtos/)

Btw. you can extend any interface and MapStruct will generate the mappings. For example you can extend [`Converter`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/convert/converter/Converter.html) from Spring and MapStruct will generate the convert implementation.

**Comment by filiphr** [comment]
I am going to close this now. We can continue the discussion for sure, but for now this isn't something that belongs in MapStruct.

**Comment by slavb18** [comment]
thanks!
