### ISSUE TITLE
in a mapper i can't dependency inject a service in spring

### ISSUE THREAD

**Issue by 234424169** [mapstruct/mapstruct#1294]
`@Mapper
public abstract class SquareEntranceMapper {
    @Autowired
    ApplicationTypeService applicationTypeService;
`
I define a mapper like this because i want to use the function of this service.But I found the dependency injection of spring is failed, the "applicationTypeService" is null in my code and cause a null pointer exception.I use this in a wrong way? Or how can i finish this with another way

**Comment by filiphr** [comment]
From what I can see you are not using the spring `componentModel`. 

You will need to define your mapper like:

```
@Mapper(componentModel = "spring")
public abstract class SquareEntranceMapper {
...
}
```

You also **must not** use `Mapper.getMapper(SquareEntranceMapper.class)` if you don't use the default component model. You will need to inject the mapper as a normal spring bean.
