### ISSUE TITLE
Explicit only mode

### ISSUE THREAD

**Issue by rpost** [mapstruct/mapstruct#1295]
It would be nice to have possibility to config mapper so that only explicitly listed `@Mapping`-s are used. Or maybe there is such thing but I can't find it?

**Comment by filiphr** [comment]
@rpost Why would you want to do that? You can easily define a smaller POJO that you would map to, it would make things much easier and smaller for you.

Currently there is no way to do this. However, we are doing it for some nested mappings (internally it is possible)

**Comment by rpost** [comment]
My use case is that I'm doing mapping between two classes coming from wsdl that I got from external source. I simply don't want to accidentally map something when wsdl changes without explicit telling to do  so.

**Comment by filiphr** [comment]
Closing this in favor of #1392 and the open PR #1403
