### ISSUE TITLE
Can't generate code with kotlin All-open and No-arg plugin

### ISSUE THREAD

**Issue by lonelyleaf** [mapstruct/mapstruct#1298]
I am using mapstruct build a spring-boot app with kotlin and mapstuct.
I read your kotlin [demo](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-kotlin/pom.xml) and works fine.
Then I noticed kotlin has [plugins](https://kotlinlang.org/docs/reference/compiler-plugins.html) to let class open by default and has no-arg constructor by default.But it seems mapstuct can't work with kotlin-app-open and kotlin-allopen plugin.
My pom.xml like this

```
            <!--kotlin-->
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>kapt</id>
                        <goals>
                            <goal>kapt</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>src/main/kotlin</sourceDir>
                                <sourceDir>src/main/java</sourceDir>
                            </sourceDirs>
                            <annotationProcessorPaths>
                                <annotationProcessorPath>
                                    <groupId>org.mapstruct</groupId>
                                    <artifactId>mapstruct-processor</artifactId>
                                    <version>${org.mapstruct.version}</version>
                                </annotationProcessorPath>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <compilerPlugins>
                        <!--<plugin>all-open</plugin>-->
                        <plugin>spring</plugin>
                        <!--<plugin>no-arg</plugin>-->
                        <plugin>jpa</plugin>
                    </compilerPlugins>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-noarg</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by filiphr** [comment]
What is the error that you are getting with MapStruct? How exactly it doesn't work?

Does Kotlin create public no arg constructors? It is also really important when those plugins are executed before kapt is invoked. I don't know how they are implemented and how the logic is within Kotlin to help you out more.

**Comment by lonelyleaf** [comment]
My former post has some inaccuracy.

When I disable those plugins,it generated source in `target/generated-sources/kapt/compile` successfully.

And if I am only using `no-arg` and `all-open` plugin,also works fins.

The plugin is not working is `jpa` and `spring` plugin for spring application,I cheked the class  file,the dto
classes have no-arg construcor.And the maven  output has no error with map-struct

**Comment by filiphr** [comment]
If everything is working OK for MapStruct and the kotlin plugins `jpa` and `spring` are not working. I really don't see why this issue is for us and what we need to do.

Therefore, I am going to close this one. Feel free to comment and reopen if you think that something is on our side.

**Comment by imberda** [comment]
@lonelyleaf I also ran into the same issue. In case you still need help or anyone else runs into this see below for how I solved it. Perhaps it will help you as well....

You just need to move the configuration for `<compilerPlugins>` from a top-level plugin `<configuration>`, to being nested within the compile execution itself. Also make sure you set the compile execution to phase `process-sources`.

```
<execution>
    <id>compile</id>
    <phase>compile</phase>
    <goals>
        <goal>process-sources</goal>
    </goals>
    <configuration>
        <compilerPlugins>
            <plugin>spring</plugin>
            <plugin>jpa</plugin>
        </compilerPlugins>
    </configuration>
</execution>
```

A couple of other things to be aware of:

- The generated mapper will be a Java class that will be compiled by the java compiler (as opposed to the Kotlin compiler). So make sure you set the `<phase>` of the `kotlin-maven-plugin` compile  execution to `process-sources` otherwise the Kotlin domain objects / DTOs referenced by the generated Java mapper will not be available and you'll get `cannot find symbol` errors.

- In my particular project I also ran into an issue where I had Lombok on the class path which interfered with generating the mapper. I needed to exclude it as a dependency. Actually having it in my Kotlin project made no sense anyhow (what with data classes, named arguments, etc.).

Hope this helps!

**Comment by filiphr** [comment]
Thanks @imberda for the detailed explanation. I think that this can indeed help other people when they stumble on to this :)

**Comment by energister** [comment]
I'm trying to use no-arg plugin to get rid of default constructors in code introduced specially for MapStruct (see [source code](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-kotlin/src/main/kotlin/org/mapstruct/example/kotlin/dto/PersonDto.kt)). To do so I've added custom annotation to the [test project](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-kotlin):
```
package org.mapstruct.example.kotlin

@Target(AnnotationTarget.CLASS)
annotation class DefaultConstructor
```


First of all there was a bug in kotlin-maven-plugin: [KT-18022 kotlin maven plugin - adding dependencies overwrites arguments.pluginClassPath preventing kapt goal from running](https://youtrack.jetbrains.com/issue/KT-18022). So I switched to Kotlin 1.2
```
    <properties>
        <!--- .... --->
        <kotlin.version>1.2.0</kotlin.version>
        <!--- .... --->
    </properties>

```
But I've stuck. When I add option for no-arg plugin tests break.
So this configuration won't work:
```
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <configuration>
                    <compilerPlugins>
                        <plugin>no-arg</plugin>
                    </compilerPlugins>

                    <pluginOptions>
                        <!-- this option breaks build -->
                        <option>no-arg:annotation=org.mapstruct.example.kotlin.DefaultConstructor</option>
                    </pluginOptions>
                </configuration>
                <executions>
                    <execution>
                        <id>kapt</id>
                        <goals>
                            <goal>kapt</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>src/main/kotlin</sourceDir>
                            </sourceDirs>
                            <annotationProcessorPaths>
                                <annotationProcessorPath>
                                    <groupId>org.mapstruct</groupId>
                                    <artifactId>mapstruct-processor</artifactId>
                                    <version>${mapstruct.version}</version>
                                </annotationProcessorPath>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-noarg</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

I've tried approach suggested by @imberda and move `configuration` section under `execution/compile` + set `goal` to `process-sources`:
```
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>kapt</id>
                        <goals>
                            <goal>kapt</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>src/main/kotlin</sourceDir>
                            </sourceDirs>
                            <annotationProcessorPaths>
                                <annotationProcessorPath>
                                    <groupId>org.mapstruct</groupId>
                                    <artifactId>mapstruct-processor</artifactId>
                                    <version>${mapstruct.version}</version>
                                </annotationProcessorPath>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>process-sources</goal>
                        </goals>
                        <configuration>
                            <compilerPlugins>
                                <plugin>no-arg</plugin>
                            </compilerPlugins>

                            <pluginOptions>
                                <option>no-arg:annotation=org.mapstruct.example.kotlin.DefaultConstructor</option>
                            </pluginOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-noarg</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```
But it doesn't work either: build fails with 
```
Could not find goal `process-sources` in plugin org.jetbrains.kotlin:kotlin-maven-plugin:1.2.0 among available goals compile, js, kapt, metadata, script, test-compile, test-js, test-kapt, test-metadata
```
Any ideas how to make `@DefaultConstructor` work on `PersonDto` and `Person` classes instead of writing defalut constructors and make properties nullable?

**Comment by filiphr** [comment]
I don't know that much about kotlin and it's configurations. However, from the perspective of Maven I think that the snippet from @imberda is wrong. I think it should be:

```
<execution>
    <id>compile-cotlin</id>
    <phase>process-sources</phase>
    <goals>
        <goal>compile</goal>
    </goals>
    <configuration>
        <compilerPlugins>
            <plugin>spring</plugin>
            <plugin>jpa</plugin>
        </compilerPlugins>
    </configuration>
```

The `phase` and `goal` are swapped. However, I am not entirely sure what is the correct way to do it.

**Comment by thePhil** [comment]
@energister have you been able to solve the problem?

My guess is, that the default constructor via the no-args plugin is just being generated in bytecode and not available to the generated classes or because the annotation processor runs before the no-args plugin.

BTW I'm using gradle.
Any help would be greatly appreciated.

**Comment by lppedd** [comment]
@thePhil I still have this problem, have you been able to solve?

**Comment by nilotpal1981** [comment]
I am also trying to use a custom annotation to be used by all-open. However, it is not working for me as well. I tend to agree with @thePhil . I believe the all-open is coming into picture only during compilation and not in annotation processor code generation phase. Need to figure out how to configure all-open with code generation phase for Mapstruct annotation processor. Any pointers in this regard will be appreciated.

**Comment by filiphr** [comment]
@nilotpal1981 @thePhil have you seen the [mapstruct-kotlin](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-kotlin) example in our examples repository? There it uses something else

**Comment by lppedd** [comment]
In my case I was using data classes with MapStruct, so for the true (non synthetic) empty constructor to be generated I had to annotate with `JvmOverloads` and provide default arguments.

**Comment by nilotpal1981** [comment]
@filiphr my model data class is a final class (with properties as val). I have annotated it and included that annotation as plugin option for all-open plugin. I need all-open to make my data class open during Mapstruct annotation processing so that the mapper implementation is done properly by Mapstruct.  However, this is not working.

**Comment by lppedd** [comment]
@nilotpal1981 This cannot work. MapStruct generate SOURCES. There is no magic. I don't understand why MapStruct should care about the class being final/non-final. Could you post the model and the error?

**Comment by lppedd** [comment]
@nilotpal1981 data classes are final by language constraint, I think even the all open plugin can't work.

**Comment by filiphr** [comment]
I don't know how the noArgs plugin works like. If it just creates a private no argument constructor then it won't work. MapStruct needs a public no argument constructor, as it generates Java code that invokes the constructor. There is no reflection going on

**Comment by lppedd** [comment]
@filiphr do you think it is somehow possible to generate Kotlin code instead of Java code? Or is the whole framework too tied up to Java?

**Comment by filiphr** [comment]
Reading the comments from all of you I think that none of the plugins are needed for MapStruct.

MapStruct only needs a public default constructor. @lppedd already explained how to do that. The kotlin example in our examples repo does the same

**Comment by lppedd** [comment]
@filiphr Exactly. For MapStruct usage you cannot rely on the no-args plugin.-

**Comment by wadid** [comment]
is this issue still existing?

**Comment by filiphr** [comment]
@wadid have a look at my comment (https://github.com/mapstruct/mapstruct/issues/1298#issuecomment-414638010). I don't think that the plugins are needed for MapStruct. If you need them for some other reason and you are having problems, then please provide a minimal example and create a new issue
