### ISSUE TITLE
Documentation : Nested Objects

### ISSUE THREAD

**Issue by bigalnz** [mapstruct/mapstruct#1300]
Hello,

I am a complete newbie and terrible at reading doc's - if I can understand them anyone can. Some feedback about the MapStruct Docs having used MapStruct for the first time.

If I have object Car, which is made up of:

class Car {
    private String carName;
    private Wheel wheel;

To me Wheel inside Car is a 'Nested Class' and when I went through the docs - this is where I looked (in error) for help in this situation and went on a path of trying to follow[ 5.3 Nested Bean Mappings](http://mapstruct.org/documentation/dev/reference/html/#controlling-nested-bean-mappings)

What I really needed was [Invoking Other Mappers ](http://mapstruct.org/documentation/dev/reference/html/#invoking-other-mappers)

Its also worth mentioning that even after using the Other Mappers I still have to make sure that my DTO's were mapping to DTOs. ie:

public class CarDTO {
    private String carName;
    private WheelDTO wheel;

etc

My problem also involved a Nested Mapping of a List. A example of this would be helpful too.

HTH

Al

**Comment by sjaakd** [comment]
@bigalnz Is still an issue?

**Comment by filiphr** [comment]
Closing due to no response
