### ISSUE TITLE
Exceptions are not being declared to be thrown

### ISSUE THREAD

**Issue by xyzst** [mapstruct/mapstruct#1304]
At the request of @filiphr, I have created a barebones project to reproduce the issue I was having with the generated mapping files not declaring exceptions to be thrown.

Please refer to the following repository/project: https://github.com/xyzst/unwrapped-exceptions

**Comment by filiphr** [comment]
Thanks a lot for your example project @xyzst. It helped me a lot. I've created a PR #1305 that fixes this issue. 

The reproducal passes the new fix.

Will you have the time to test it against your codebase? You can use jitpack to build it. [Here](https://jitpack.io/#filiphr/mapstruct/1304_nested_mappings_with_exceptions-SNAPSHOT) is the link to the branch that you can use.

Btw. Really good job on the repository, I liked your thoroughness :). There were minor issues with the structure, but all in all it was good :)

**Comment by xyzst** [comment]
@filiphr tested it against the codebase and mapstruct is now properly adding the throws clause for nested mapping methods in the generated mapping files (no more compile errors!)

thanks for the quick fix, look forward to undoing the workaround that is currently in place for when 1.2.0-FINAL is released!

And thank you 😁
