### ISSUE TITLE
When source is null target should  NOT be set to null 

### ISSUE THREAD

**Issue by msundari** [mapstruct/mapstruct#1306]
Hi, I am trying to map nested properties using mapstruct 1.2.0.CR2. (Example map customer.address.houseNumber to userDTO.homeDTO.addressDTO.houseNo ).

Expectation : I do not want to set the addressDTO to null when customer.address is null. Since addressDTO contains "countyname" and other properties which are already set from other different sources

Please advice if there is property/setting that I could set so that the target it not set to null when source is null.

This is the mapping  I am using.

@Mapper( nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS )
public interface CustomerUserMapperNullCheck {

    @Mapping(source="address", target="homeDTO.addressDTO" )
    void mapCustomer(Customer customer, @MappingTarget  UserDTO userDTO)  ;
    
    @Mapping(source="houseNumber", target="houseNo" )
    void mapCustomerHouse(Address address, @MappingTarget  AddressDTO addrDTO)  ;
    
}

I initially tried in single mapping like below
 @Mapping(target="homeDTO.addressDTO.houseNo", source="address.houseNumber")
   abstract void mapCustomerHouse(Customer customer, @MappingTarget  UserDTO userDTO)  ; Then tried splitting up the mapping,  based on https://github.com/mapstruct/mapstruct/issues/649. 

Both  approaches does not produce the expected generated code.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**The generated code**

public class CustomerUserMapperNullCheckImpl implements CustomerUserMapperNullCheck {

    @Override
    public void mapCustomer(Customer customer, UserDTO userDTO) {
        if ( customer == null ) {
            return;
        }

        if ( userDTO.getHomeDTO() == null ) {
            userDTO.setHomeDTO( new HomeDTO() );
        }
        customerToHomeDTO( customer, userDTO.getHomeDTO() );
    }

    @Override
    public void mapCustomerHouse(Address address, AddressDTO addrDTO) {
        if ( address == null ) {
            return;
        }

        if ( address.getHouseNumber() != null ) {
            addrDTO.setHouseNo( address.getHouseNumber() );
        }
    }

    protected void customerToHomeDTO(Customer customer, HomeDTO mappingTarget) {
        if ( customer == null ) {
            return;
        }

        if ( customer.getAddress() != null ) {
            if ( mappingTarget.getAddressDTO() == null ) {
                mappingTarget.setAddressDTO( new AddressDTO() );
            }
            mapCustomerHouse( customer.getAddress(), mappingTarget.getAddressDTO() );
        }
        **else {
            mappingTarget.setAddressDTO( null );   // I dont want to else where addressDTO is set to null.
        }**
    }
}

**Comment by kevcodez** [comment]
Have you tried the `NullValueMappingStrategy`?

**Comment by sjaakd** [comment]
@msundari : did the suggestion of @kevcodez solve your problem..?

**Comment by msundari** [comment]
@sjaakd , I tried but it dint not work as expected. 

  BeanMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
  void mapCustomer(Customer customer, @MappingTarget UserDTO userDTO);
Still  it was setting target to null

**Comment by filiphr** [comment]
@msundari I think that this is the same as my first point in https://github.com/mapstruct/mapstruct/issues/879#issuecomment-304787805. Currently, we set this to `null` explicitly. Maybe we should change this and not set it to `null` in update methods.

**Comment by luispereira** [comment]
Any news about this? I'm having the same issue where I set a default in kotlin arrayListOf() and is defining it as null

**Comment by ngbalk** [comment]
Is this related to #954 ? Was there a proposed work around?

**Comment by luispereira** [comment]
The only way that I could fix this, was doing manually, where I see the DTO and then put its results on the UI Object

**Comment by ngbalk** [comment]
@luispereira interesting... could you provide a small example?

**Comment by sjaakd** [comment]
I'm a bit afraid to break existing functionality. Out of curiosity: have you tried the current master with the `defaultExpression("java(new AddressDTO())");`? There's an `import` on the `@Mapper` annotation to import `AddresDTO` in the generated code, so you don't have to use the fully qualified names.

**Comment by sjaakd** [comment]
you can use plain java. Checkout [10.2. Expressions](http://mapstruct.org/documentation/stable/reference/pdf/mapstruct-reference-guide.pdf) . The defaultExpression will do the same.

**Comment by ngbalk** [comment]
@sjaakd Thanks so much, I think **defaultExpression** will eventually serve as a reasonable workaround.  Out of curiosity, is this something that you think is worth fixing, or something that is better suited for working around?

**Comment by sjaakd** [comment]
> Out of curiosity, is this something that you think is worth fixing, or something that is better suited for working around?

You mean in MapStruct? .. I'm not sure what the repercussions will be if we fix this in MapStruct. However: personally I do see expressions as a mean to solve things that we don't have a proper other solution for.

**Comment by ngbalk** [comment]
@sjaakd Sorry I should have been more clear - yes fixing this in MapStruct.  Fair enough! Thanks for the guidance!

**Comment by sjaakd** [comment]
@msundari , @luispereira , @ngbalk .. Issue has been resolved and merged to the master.. We introduced a new strategy.. Have a look at the javadoc / documentation in the commits above and check if it fits your needs.

**Comment by ngbalk** [comment]
@sjaakd That looks like exactly what we want! Can't wait to start using this!

**Comment by sjaakd** [comment]
my pleasure.

**Comment by lkrnac** [comment]
Is there any ETA when 1.3.0.Beta2 will be released?

BTW, thanks for great library!

**Comment by filiphr** [comment]
Thanks for the nice words.

1.3.0.Beta2 should be out by next Monday

**Comment by bakasura11** [comment]
Do you have an ETA for release version of this changes?

**Comment by filiphr** [comment]
@bakasura11 I already gave the ETA in https://github.com/mapstruct/mapstruct/issues/1306#issuecomment-435847515. It should be out on Monday

**Comment by anergys** [comment]
@filiphr Hello there. I am using 1.3.0.Beta2. But it's still not generating code I want.
I have following mapping method:
`@Mappings({
            @Mapping(target = "grantee.nickname", source = "dto.granteeName"),
            @Mapping(target = "grantee.id", source = "dto.granteeId"),
    })
User map(UserDto dto);`
And it's generating next: 
```java
public User map(UserDto dto) {
        if ( dto == null ) {
            return null;
        }

        User user = new User();

        user.setGrantee( userDtoToGrantee( dto ) );
        if ( dto.getId() != null ) {
            user.setId( dto.getId() );
        }
        ...
}
protected Grantee userDtoToGrantee(UserDto userDto) {
        if ( userDto == null ) {
            return null;
        }

        Grantee grantee = new Grantee();

        if ( userDto.getGranteeId() != null ) {
            grantee.setId( userDto.getGranteeId() );
        }
        if ( userDto.getGranteeName() != null ) {
            grantee.setNickname( userDto.getGranteeName() );
        }

        return grantee;
    }
```
But I want something like: 
```java
protected Grantee userDtoToGrantee(UserDto userDto) {
        if ( userDto == null ) {
            return null;
        }
        
        // or something like that
        if (userDto.getGranteeId() != null && userDto.getGranteeName() != null) {
            return null;
        }

        Grantee grantee = new Grantee();

        if ( userDto.getGranteeId() != null ) {
            grantee.setId( userDto.getGranteeId() );
        }
        if ( userDto.getGranteeName() != null ) {
            grantee.setNickname( userDto.getGranteeName() );
        }

        return grantee;
    }
```

What should I do?

**Comment by filiphr** [comment]
@anergys I think that your issue is linked with https://github.com/mapstruct/mapstruct/issues/1166 and not with this one

**Comment by doanthai** [comment]
@msundari This code working with me: 
`@Mapper(
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)`

**Comment by atigm** [comment]
Strategies don't solve the problem, you have to use AfterMapping.

    ```
@Mapping(source = "id", target = "object.id")
    Target toModel(Source source);

    @AfterMapping
    default void after(final @MappingTarget Target target, final Source source) {
        if(source.getId() == null) {
            target.setObject(null);
        }
    }
```

**Comment by pulsarix** [comment]
This is expected to create your empty object.
```
@BeanMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
```
