### ISSUE TITLE
should be possible to use gradle default annotation processor

### ISSUE THREAD

**Issue by mozinrat** [mapstruct/mapstruct#1309]
With gradle apt support inbuild, should be possible to get rid of plugin  'net.ltgt.apt' version '0.8'
and use gradle's default apt for annotation processing.

**Comment by filiphr** [comment]
Is this something new? Can you send us some links that we can have a look at?

Searching gives me the `net.ltgt.apt` plugin. And you can use the latest version of it 😀

**Comment by mozinrat** [comment]
With Gradle 4, it's recommended that a plugin use compiler classpath (annotation processors, in general, do this) https://blog.gradle.org/incremental-compiler-avoidance, there is a way to clear specification. I didn't use the source code separation as mentioned, still explicitly stating the apt is still the good way.  Here is my working build.gradle without using apt plugin

apply plugin: 'java'
configurations {
    apt
}
dependencies {
    apt "org.projectlombok:lombok:${lombokVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    apt "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    compileOnly "org.mapstruct:mapstruct-jdk8:${mapstructVersion}"
}
tasks.withType(JavaCompile) {
    options.compilerArgs = ['-Amapstruct.suppressGeneratorTimestamp=true', '-Amapstruct.defaultComponentModel=spring']
}

It works fine with gradle bootrun or delegate to ide in IntelliJ. But to make it work in ide I have to add generated java to src. By default, it will be generated in the classes directory. 

As I mentioned in above forum, you can generate an src path, and this will support incremental build also. But yeah, using above configuration you no longer need the apt plugin.

Until I am using Lombok it's not so advantageous as separated annotation source will not work with lombok, but projects without lombok can go further and create configuration aptCompile for generated java and add them to sourcePath. This way they have full incremental build supported.
I really love that you have created the separate process and lib modules.
Cheers!!

**Comment by kevcodez** [comment]
@mozinrat Do you want the current README section regarding gradle integration to be changed?

**Comment by filiphr** [comment]
@mozinrat I think what you are saying is great. Improving the APT support and so on. However, I think that the apt-plugin already supports the compiler avoidance and works OK with gradle in that regard. Your snippet is actually what the plugin does (I think). Have a look at https://github.com/tbroyer/gradle-apt-plugin/issues/45#issuecomment-301676326. I would more go in the direction of improving the plugin instead of doing things by hand.

**Comment by mozinrat** [comment]
@filiphr When I posted this question, I just want to avoid extra plugins and make incremental compilation works. After some research found a way to do that for mapstruct so posted here. I think this can be closed.

**Comment by mohamnag** [comment]
not sure about the outcome here, but lombok somehow makes it to use default gradle settings. So basically it is enough to add this in gradle.build and everything compiles & runs fine:
```
dependencies {
        compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.16.18'
}
```
it would be nice to be able to do the same here too.

**Comment by filiphr** [comment]
If you look at https://github.com/mapstruct/mapstruct/issues/1309#issuecomment-338129989 you will see how you can make this work. 

You can se the same configuration for mapstruct. The reason why we are recommending `apt` for the `mapstruct-processor` is in order not to leak those dependency to your compile path
