### ISSUE TITLE
Support for Type-Refinement mapping (or Downcast Mapping)

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#131]
Suppose we have the following types: `MotorizedVehicle`, `Car extends MotorizedVehicle`, `MotorCycle extends MotorziedVehicle`, and their complementary types `MotorizedVehicleDto`, `CarDto extends MotorizedVehicleDto`, `MotorCycleDto extends MotorziedVehicleDto`.

We also have defined a MotorCycleMapper, a CarMapper and a MotorizedVehicleMapper, each containing methods to map from the entity type to the DTO type.

What I now have in my hand is just a list of MotorizedVehicle instances and I want to map them all to DTOs. But not just to MotorizedVehicleDtos, but to what resembles the most concrete type. 

With the current state, I would have to "instanceof" my way through and call the right mapper with the downcasted object myself. Other mapping frameworks allow to define that the actually returned type may be something more special based on the runtime-type of the object to map (in dozer you have to specify such type pairs in the global config).

I wonder if we should support something like that as well. For exampe:

``` java
@Mapper( uses = { CarMapper.class, MotorCycleMapper.class } )
public MotorizedVehicleMapper {
    @Mapping( withDowncastMapping=true )
    public MotorizedVehicleDto vehicleToDto(MotorizedVehicle vehicle);
}
```

would generate to:

``` java
public MotorizedVehicleMapperImpl {
    private CarMapper carMapper = ...;

    @Override
    public MotorizedVehicleDto vehicleToDto(MotorizedVehicle vehicle) {
        if ( vehicle instanceof Car ) {
            return carMapper.carToCarDto( (Car) vehicle );
        }

        if ( vehicle instanceof MotorCycle ) {
            return ...;
        }

        MotorizedVehicleDto motorizedVehicleDto = new ...
        // the usual mapping stuff
    }
}
```

I know, usually one could nicely handle such stuff in an object-oriented way by upsmarting the entity types, but, well... you know how it is... ;-)

WDYT?

**Comment by agudian** [comment]
The idea here is that we generate a method that selects the refining mapping method at runtime using instanceof checks and downcasts of the source parameter (as in the example above). The possible options are collected from the current mapper's methods and the used mappers.

That way, if a user has an object containing a property of type ```MotorizedVehicle```, then that property mapping can be done with the best downcasted fit automatically. We might need to enforce that the user specifies the behaviour in case none of the "known" options fits.

**Comment by gunnarmorling** [comment]
A possible alternative solution for this issue is presented in #923.

**Comment by agudian** [comment]
An alternative to just collecting all possible specializations from the used mappers / declared methods is suggested in #923: the variants to consider could be declared specifically using an annotation, e.g. `@PolymorphismMapping`.

**Comment by gunnarmorling** [comment]
Ahaha, great minds think alike :)

**Comment by rwalkerands** [comment]
+1

Having just hand-coded two methods of the instanceof/cast variety to do this (e.g., https://github.com/au-research/ANDS-Vocabs-Toolkit/commit/087c32e89a4d515e61e4d4fe0b093f277d407315#diff-28ded5bdcc0bbe659e4da1ae67530d37R104), I await a better way.

**Comment by foxbaucia** [comment]
Hi, is there an extended example of can I use this? 
If most of my attributes are in MotorizedVehicle. Is there any way to create a simple CarMapper and simple MotorCycleMapper that extends their Mappings from MotorizedVehicleMapper or should I repeat always all the mappings?

**Comment by filiphr** [comment]
@foxbaucia I think what you are looking for is [Mapping configuration inheritance](http://mapstruct.org/documentation/stable/reference/html/#mapping-configuration-inheritance). It is not really linked with this issue

**Comment by sebastianhaberey** [comment]
:+1:  I also have this long hand-written method with instanceof case distinctions that feels like it could be generated.

On an unrelated note I just wanted to say that I _love_ what you guys have done with MapStruct. We have a rather complicated scenario and we thought we'd probably have to write our own custom mappers from scratch. But so far we've always been able to find a MapStruct feature to help with our specific requirements. Well done!

**Comment by hugoo10** [comment]
I needed something like that in my own project so I created a CommonMapper class that can be used to handle this:  https://github.com/hugoo10/MapStructInheritance hope it'll help

**Comment by paullarionov** [comment]
Hi guys, any updates? Issue started in 2014, but today is 2020!

**Comment by filiphr** [comment]
Hey @paullarionov, as you can see there aren't many updates. We have been busy working on other issues. This is an open source project and every help is appreciated. If this feature is so important to you, perhaps you can find the time to add support for it and provide a PR. 

The entire MapStruct team is working on this project in their free time and the time we have is limited.

**Comment by Zegveld** [comment]
Hey, I'm also running into this issue. 

I've started on creating a way to support this, but I am running into knowledge issues.
I've chosen for an additional annotation to mention which sourceSubClass maps on which targetSubClass.
Now I've arrived at the point where I need to get a call in to map the sourceSubClass to the targetSubClass, for this I need to know:
1. how and where currently is determined which mapping methods are going to be generated.
this because I might need to add additional mappings to be generated.
2. how to get the mapping method called.
this to have it return that result instead of the default behaviour.

See https://github.com/rigd-loxia/mapstruct/tree/feature/Issue_131 for the current state of my progress.

Also I'm currently using the term subclasses to refer to the classes that extend the parentclass which is for example mentioned in a collection.

**Comment by Zegveld** [comment]
Update: I've got it working when you also manually define the mapping methods to which you refer.

Example:
`
    org.mapstruct.ap.test.bugs._131.dto.Car map(org.mapstruct.ap.test.bugs._131.domain.Car car);

    org.mapstruct.ap.test.bugs._131.dto.Bike map(org.mapstruct.ap.test.bugs._131.domain.Bike bike);

    @SubClassMapping( sourceClass = org.mapstruct.ap.test.bugs._131.domain.Car.class, targetClass = org.mapstruct.ap.test.bugs._131.dto.Car.class )
    @SubClassMapping( sourceClass = org.mapstruct.ap.test.bugs._131.domain.Bike.class, targetClass = org.mapstruct.ap.test.bugs._131.dto.Bike.class )
    org.mapstruct.ap.test.bugs._131.dto.Vehicle map(org.mapstruct.ap.test.bugs._131.domain.Vehicle vehicle);
`
results in 
`
    @Override
    public org.mapstruct.ap.test.bugs._131.dto.Car map(Car car) { /* skipped because unchanged */ }

    @Override
    public org.mapstruct.ap.test.bugs._131.dto.Bike map(Bike bike) { /* skipped because unchanged */ }

    @Override
    public Vehicle map(org.mapstruct.ap.test.bugs._131.domain.Vehicle vehicle) {
        if ( vehicle == null ) {
            return null;
        }

        Vehicle vehicle1;
        if (vehicle instanceof Car) {
            vehicle1 = map( (Car) vehicle );
        }
        else if (vehicle instanceof Bike) {
            vehicle1 = map( (Bike) vehicle );
        }
        else {

            vehicle1 = new Vehicle();

            vehicle1.setName( vehicle.getName() );
        }

        return vehicle1;
    }
`

But I'm not that happy with the implementation route that I took to add this.

**Comment by filiphr** [comment]
Thanks for the initiative @Zegveld.

I haven't looked into the code, and I would propose that you create a draft PR so we can discuss it in there.

For not defining the methods before I would suggest looking into [`forgeMapping`](https://github.com/mapstruct/mapstruct/blob/a95d1c59c3f531fc90b62c60092dd9c16bc93b66/processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java#L769). We are already creating mappings between different objects when properties are being mapped. However, if a user manually defines a mapping then we should indeed use that one.

For the implementation, I would look at a PR before commenting

**Comment by lambrosx77** [comment]
Hi,

I can't help unfortunately but I'm in front of this issue because I need to implement [graphql Global Object Identification](https://graphql.org/learn/global-object-identification/). I'm working with [Relay](https://relay.dev/) and new [DGS project](https://netflix.github.io/dgs/). 
Graphql objects need to extends Node superclass. 
And I have to switch between JPA autoincrement identifier and graphql identifier in base64.

Mapstruct seems to be the solution and a good solution. I hope we can have a way to this issue.

**Comment by sebastianhaberey** [comment]
Yaaay amazing! Well done all 😎
