### ISSUE TITLE
Not generating setter methods for all constants

### ISSUE THREAD

**Issue by saikumar-a** [mapstruct/mapstruct#1320]
MapStruct not generating setter methods for all constants. For the below mapper, code was generated only for `myState`. This is happening only for third level parameters.
```java
public interface MyMapper {
	@Mapping(target = "address.country.cityName", constant="myCity")
	@Mapping(target = "address.country.stateName", constant ="myState")
    Target map(Integer dummy);	
}
```

**Comment by filiphr** [comment]
@saikumar-a can you tell us which version you are using? 

I just tried it out as well and indeed up to third level it is working.

Thanks for reporting this.

**Comment by filiphr** [comment]
@saikumar-a this should be fixed with #1322. In case you want to try it out, you can use jitpack with the top of my branch.

**Comment by saikumar-a** [comment]
Thanks @filiphr. I am new to github and open source projects. Can you please tell me what dependencies I have to add in `pom.xml` to test your changes.

**Comment by filiphr** [comment]
Of course. Have a look [here](https://jitpack.io/#Filiphr/mapstruct/1320-bug-fix-SNAPSHOT) there are instructions how you can setup my branch and try it out in maven

**Comment by filiphr** [comment]
Adapted the milestone to 1.3.0.Beta1 as there won't be a 1.2.1 release
