### ISSUE TITLE
Error when entity class extends a base class

### ISSUE THREAD

**Issue by danjee** [mapstruct/mapstruct#1328]
Hello and nice job in the first place.
I have a situation when my entity class extends an abstract base class. 
The error is something like this:
_The return type ro.oss.niinoo.domain.model.base.Attribute is an abstract class or interface. Provide a non abstract / non interface result type or a factory method._
I've setup a minimal working project to reproduce this on:

[Github Project](https://github.com/danjee/mapstructexample)

**Comment by danjee** [comment]
Can the method name be outputted in the error message? It's somehow not enough to have only the method return type. I haven't used compile time annotation before. Is there a way to debug this ?
Thank you

**Comment by danjee** [comment]
Found a different approach for my generics and it worked. I've made a push on the sample project as well. Also I saw I can debug in Intellij on Maven lifecycle install and put breakpoints in the BeanMappingMethod class.

**Comment by filiphr** [comment]
@danjee great that you resolved the issue. As you figured it out, you can debug the maven compile goal and put breakpoints in the MapStruct code.

As for the error output, there should have been a line number of the class that was having the error. What was actually happening is that the automatic generation of mapping methods for MapStruct was kicking in and it couldn't map the

**Comment by danjee** [comment]
Thanks @filiphr
