### ISSUE TITLE
Use flatten-maven-plugin to publish simplify POMs

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1330]
Just learned about this useful plug-in: http://www.mojohaus.org/flatten-maven-plugin/usage.html

It should allow us to publish POM files just with the sole information needed for _using_ MapStruct but without all the info for _building_ it (i.e. plug-ins, test dependencies, build profiles etc.). I tried it quickly, but one issue was that the created POM contained the FreeMarker dependency, i.e. it doesn't play together nicely with the shading plug-in.

**Comment by filiphr** [comment]
This was done as part of #1857
