### ISSUE TITLE
Mapstruct is ignoring `NullValueCheckStrategy.ALWAYS` when `@MappingTarget` is used

### ISSUE THREAD

**Issue by jackmatt2** [mapstruct/mapstruct#1331]
```java
@Mapper(componentModel = "spring", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface PersonMapper {
    void copy(PersonPatchDto dto, @MappingTarget Person person);

   void copy(AddressPatchDto dto, @MappingTarget Address address);
}
```

Address is a hibernate entity connected to a Person, the DTOs are mapped in the same fashion.  Even though `NullValueCheckStrategy.ALWAYS` is specified, the following code is generated

```java
        if ( dto.getAddress() != null ) {
            if ( person.getAddress() == null ) {
                person.setAddress( new Address() );
            }
            addressMapper.copy( dto.getAddress(), person.getAddress() );
        } else {
            person.setAddress( null );   <------------ This "else" should not be here right????
        }
```

All other properties - the ones not using `@MappingTarget` are like this:

```java
        if ( dto.getDob() != null ) {
            person.setDob( dto.getDob() );
        }
```

thus ignoring null values

**Comment by filiphr** [comment]
@jackmatt2 the explicit sett to `null` is done on purpose for Update methods. However, I agree with you we should have an option to disable the setting of null. I think that this is related to https://github.com/mapstruct/mapstruct/issues/879#issuecomment-304787805

**Comment by filiphr** [comment]
Closing in favor of #879
