### ISSUE TITLE
Exceptions in nested beanmapping is not declared in generated code

### ISSUE THREAD

**Issue by chigix** [mapstruct/mapstruct#1332]
I have meet a problem when my getters in bean declaration is with exceptions thrown. For a nested bean mapping for just only 2 layers, this problem is not appeared because all the possible exceptions have been declared explicitly by user. But for a deeper mapping, such exception is not generated with generated private methods by mapstruct. For describing this problem,  I have also pushed a branch in my fork: https://github.com/chigix/mapstruct/tree/Exception_in_nested_mapping

I'm not sure is it a design originally to not cover exceptions thrown around getters or setters in pure mapping. However, I think it would not establish negative effect.

**Comment by filiphr** [comment]
@chigix I think it is a major antipattern to throw checked exceptions from getters / setters. What you are doing in your getter is something that should be done in a service. This will also allow you to test your code better.

The issue occurs when you have nested source mappings. Theoretically we could do something about it, but it would add some complexity to the code and I am not sure if it is really worthwhile

**Comment by chigix** [comment]
@filiphr Well, exactly as you said, it breaks right design pattern, however, I'm not doing pattern design code, it is a part of implementation for a repository, where the bean is also not domain model, which is directly a rich model proxy from domain model,  for usage restricted in dao ( or repository ) implementation layer, rather than the pattern usage across the whole project or any consideration about reusability or visibility. 

Actually, I think it is no need for me to create a service only used in implementation layer or pass another service object with the model where nested information has been cached and included.

So I really hope this support could be provided from mapstruct build.

**Comment by filiphr** [comment]
@chigix you are right maybe we need to take this into consideration as well. 

Would you like to submit a PR for this? I can of course guide you through the process.

In this particular example the `NestedPropertyMappingMethod` and NestedPropertyMappingMethod.ftl` need to be modified, so exceptions are taken into consideration.

**Comment by chigix** [comment]
@filiphr  OK, I'll have a try in this weekend. Any problem, however, if appeared I'll email you directly for potential instruction and guide.

**Comment by filiphr** [comment]
@chigix no problem. You can also reach me on our [gitter chat](https://gitter.im/mapstruct/mapstruct-users)

**Comment by filiphr** [comment]
Fixed via #1335 thanks @chigix for the PR
