### ISSUE TITLE
Inconsistent ADDER_PREFERRED

### ISSUE THREAD

**Issue by wenerme** [mapstruct/mapstruct#1336]
```java
if ( builder.getBrandsList() != null ) {
    /* Expected output
    for (MyDTO term : s.getBrands()) {
        builder.addBrands(mapParseTerm(term));
    }
    */
    // But got this
    List<NeoMyDTO> list = parseTermListToParseTermList( s.getBrands() );
    if ( list != null ) {
        builder.getBrandsList().addAll( list );
    }
}
```

Why use `addAll` if there is `addBrands`, I also create a demo project, but always use `addBrands`, how can I control this ?

**Comment by filiphr** [comment]
@wenerme are you using Protobuf? Your builder looks a lot like protobuf. Have you tried using something like we have in the [mapstruct-protobuf3](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-protobuf3) example?

The reason why your adder is taken into consideration is because MapStruct checks for `addBrandsList` method. As your target property is `brandsList`

Can you share a demo project, so I can help you a bit more?

**Comment by wenerme** [comment]
Yes, it's pb3, may target property is `brands`, because I removed `List` from pb's property name, so, I don't have to add Mapping for every collections.

```
    private boolean isMessageOrBuilder(ExecutableElement element) {
        Element e = element.getEnclosingElement();
        if (e != null && e.getKind() == ElementKind.CLASS) {
            if (((TypeElement) e).getSuperclass().toString().startsWith(PROTOBUF_GENERATED_MESSAGE_V3)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String getPropertyName(ExecutableElement element) {
        String name = super.getPropertyName(element);
        if (isMessageOrBuilder(element)) {
            if (name.endsWith("List")) {
                name = name.substring(0, name.length() - 4);
            }
        }
        return name;
    }
```

**Comment by wenerme** [comment]
I found why this failed, the example not failed, because there only one candidate for adders

```java
        if ( candidates.isEmpty() ) {
            return null;
        }
        else if ( candidates.size() == 1 ) {
            return candidates.get( 0 );
        }
        else {
            for ( Accessor candidate : candidates ) {
                String elementName = Executables.getElementNameForAdder( candidate );
                if ( elementName != null && elementName.equals( Nouns.singularize( pluralPropertyName ) ) ) {
                    return candidate;
                }
            }
        }
```

If there is multi candidates, the `Nouns.singularize( pluralPropertyName ) ` will breaks protos, because protobuf use property name for add, the actual adder is `addBrands`, so `elementName` is `brands`, but `Nouns.singularize( pluralPropertyName )` is `brand`, may be mapstruct should check `pluralPropertyName == elementName` first.

**Comment by wenerme** [comment]
My workaround

```
    @Override
    public String getElementName(ExecutableElement element) {
        // https://github.com/mapstruct/mapstruct/issues/1336
        String name = super.getElementName(element);
        if (isMessageOrBuilder(element)) {
            name = Nouns.singularize(name);
        }
        return name;
    }
```

**Comment by filiphr** [comment]
@wenerme I would say that MapStruct is doing the check correctly. I don't think that we need to check for `pluralPropertyName.equals(elementName)`. In my opinion the method generated by protobuf is not intuitive, in terms of english language.

`addBrands` implies that multiple brands can be added. However, the method accepts only a single parameter of type `Brand`.

Your "workaround" is not a workaround for MapStruct, it is just making MapStruct and Protobuf work together.

Therefore, I am inclined to close this issue. 

Maybe you can contribute your protobuf extensions to the MapStruct [examples](https://github.com/mapstruct/mapstruct-examples) repository.

**Comment by wenerme** [comment]
Thanks, I will improve my protobuf integration, pr to examples when it's proved.
