### ISSUE TITLE
In protobuf3, how to mapping a ProtocolStringList

### ISSUE THREAD

**Issue by wenerme** [mapstruct/mapstruct#1338]
`ProtocolStringList` is `List<String>` in protobuf, mapstruct will not think this is a collection, because no type parameter.

```java
// this is a collection, so this can be done always
if ( !collectionProperty.getTypeParameters().isEmpty() ) {}
```
I need to tell mapstruct to call `addPropertyName` method, not `getPropertyNameList().addAll()`, so , add a mapping from `ProtocolStringList` to `List<String>` will not work.

Maybe mapstruct should support property based addAll method, like `addProperty`, so, mapstruct should use `addAllPropertyName( java.lang.Iterable<java.lang.String> values)`. Then all list in protobuf3 will just works.

**Comment by filiphr** [comment]
@wenerme I think that we can remove that line and instead of:

```java
// there's only one type arg to a collection
TypeMirror typeArg = collectionProperty.getTypeParameters().get( 0 ).getTypeBound().getTypeMirror();
```

We can do:

```
TypeMirror typeArg = first( collectionProperty.determineTypeArguments( Iterable.class ) ).getTypeBound().getTypeMirror();
```

We actually do that kind of call on other places. Changing that would work for your use case. Would you like to provide a PR for that?

Maybe we should add `addAllPropertyName(Iterable<String>)`. However, that is a bit more complex, as it has impact on how we determine which adder to use. And in theory it might clash with the single adder method.

**Comment by filiphr** [comment]
The 1.3.x milestone and the `bug` label are for the first part of my comment.

**Comment by wenerme** [comment]
For long term, I think `addAllPropertyName` is better, because even mapstruct know how to addAll for extended Collection, still can not create it, an extra mapping is required.

**Comment by filiphr** [comment]
@wenerme can you create another feature request for `addAllProperty` name with a collection. I agree that it might be better, but it might also be more specific to Protobuf, in any case it would be good if we can track that separately :).

**Comment by wenerme** [comment]
@filiphr I create https://github.com/mapstruct/mapstruct/issues/1343 to add `addAllProperty` support.

**Comment by vrudikov** [comment]
Reproduced an issue with multiple sets fields. Skeleton project is here
https://github.com/vrudikov/protobuf3-mapstruct-mapping-issue

**Comment by vrudikov** [comment]
@filiphr do i need to open a new issue or this can be reopened?

**Comment by donbeave** [comment]
I have the same issue and this project solved this problem: https://github.com/entur/mapstruct-spi-protobuf

**Comment by alexey-plotnikoff** [comment]
> I have the same issue and this project solved this problem: https://github.com/entur/mapstruct-spi-protobuf

Thank you @donbeave ❤️

**Comment by donbeave** [comment]
@alexey-plotnikoff or you can try this module https://github.com/tailrocks/jambalaya/tree/main/jambalaya-mapstruct-processor, but sorry I didn't add any documentation to it.
