### ISSUE TITLE
Context annotation on primitive types with AfterMapping throws exception on compile

### ISSUE THREAD

**Issue by aflatt** [mapstruct/mapstruct#1339]
The `@Context` feature in 1.2.0 seems to generate a compile time NullPointerExceptions when used on primitives (for example boolean). I'm not sure if this is intended behavior, and I couldn't find anything in the documentation suggesting that it was intentional. Similar code seems to work in 1.1.0 without the Context annotation.

For example, I think the following use of `@Context` will reproduce the issue:

```
@Mapping(target = "field1", source = "src.field1")
@Mapping(target = "primitiveField1", source = "primitive1")
@Mapping(target = "someField", ignore = true)
public abstract TestTarget map(TestSource src, boolean primitive1, @Context boolean primitive2);

@AfterMapping
public void afterMap(@MappingTarget TestTarget target, @Context boolean primitive2)
{
    //do some complicated mapping logic involving primitive2
    int result = someComplicatedFunction(primitive2);
    target.setSomeField(result);
} 
```

When I try to compile the above example with map-struct I get the following exception:
```
[ERROR] diagnostic: <filename> error: Internal error in the mapping processor: java.lang.NullPointerException       at 
org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:112)     at 
org.mapstruct.ap.internal.util.Executables.getAllEnclosedAccessors(Executables.java:208)     at 
org.mapstruct.ap.internal.util.Executables.getAllEnclosedExecutableElements(Executables.java:188)
...
```

Just removing the `@Context` parameter does not seem to work because mapstruct generates the following code (substituting in the wrong parameter)
```
afterMap(testTarget, primitive1);
```

Using 1.1.0 (without the `@Context` annotation) my example works fine, and generates the following mapping, as I would expect.
```
afterMap(testTarget, primitive2);
```

**Comment by filiphr** [comment]
Thanks for reporting this. It is indeed a bug, we never indeed to throw NPEs :).

If you are interested I can help you out in providing a PR for the fix ;)

**Comment by aflatt** [comment]
@filiphr thx for the quick response - I'd love to help with a fix, but I'm not sure I have the time.

If I do find some time, I will try to take a look though.

**Comment by filiphr** [comment]
@aflatt no problem at all. I already provided PR #1342, the change was really easy (3 lines of code ;)).

You can give the PR a spin if you want to test it with your codebase (you can use jitpack.io) to get it.
