### ISSUE TITLE
Enum mapper generates mapping method with wrong signature. Wrong amount of parameters

### ISSUE THREAD

**Issue by syanukov** [mapstruct/mapstruct#1340]
Considering that `Quote` and `QuoteDTO` are just enums

`@Mapper
public interface QuoteMapper {
    QuoteDTO mapToDto(@Context MappingContext context, Quote source);
}`

generates the following

`public class QuoteMapperImpl implements QuoteMapper {
    @Override
    public QuoteDTO mapToDto(MappingContext context) {
        ...
    }
}`

As you can see only `context` parameter is passed. `source` is missed.
If order of parameters in mapper interface is changed, so 

`QuoteDTO mapToDto(Quote source, @Context MappingContext context);`

then generated method looks like:

`public QuoteDTO mapToDto(Quote source) {...}`

So, in this case `context` is missing. 
Well, all the time the second argument.

With regular classes, not enums, everything works as expected

**Comment by filiphr** [comment]
Thanks a lot for reporting this @syanukov. The enums are handled in a different method which has different functionality.

**Comment by filiphr** [comment]
Just for info this would not have worked even before `1.2.0` :).

You can try it out with the PR #1341
