### ISSUE TITLE
Ignore doesn't works for readonly properties

### ISSUE THREAD

**Issue by lujop** [mapstruct/mapstruct#1345]
If we map a readonly property(only getter) there's no way to use inverse configuration. 
The problem is that mapstruct give an error that there isn't a write method for the inverse and you can't use @Mapping(ignore) to solve it

**Comment by sjaakd** [comment]
@lujop can you add an example (e.g. as gist)?

**Comment by lujop** [comment]
Of course. Here is the [Gist](https://gist.github.com/lujop/e53d46eeaca432c444ec1c7fa4110827).
When you compile you get this error: 
`a Property "readOnlyProperty" has no write accessor in cat.joanpujol.A.`

And there is no way to get rid of it. Although you use a target ignore you get the error.
And this is very tedious because if you have a big mapping where you can use the InverseConfig and you have only one read-only property you have to manually do all the inverse configuration.

**Comment by sjaakd** [comment]
@lujop : Thanks.. I'm able to reproduce your problem. Now finding a solution.

**Comment by lujop** [comment]
Thanks, I think the same, it's better if Mapstruct detects it's a readonly property.
But a least ignore should work ;)

**Comment by sjaakd** [comment]
@lujop : took a while.. But there's a fix PR #1369 pending. If you want, you can check it out and build it locally.

**Comment by sjaakd** [comment]
fixed.
