### ISSUE TITLE
when I use maven build project ,something went wrong

### ISSUE THREAD

**Issue by qianlei6148** [mapstruct/mapstruct#1349]
![default](https://user-images.githubusercontent.com/17400459/33329670-f8818dc0-d497-11e7-91fe-664913efcbae.png)
![default](https://user-images.githubusercontent.com/17400459/33329770-31b0bee0-d498-11e7-8bc6-da3541d95fac.png)
I do not know why .
Please tell me how to solve,Thank you .

**Comment by filiphr** [comment]
@qianlei6148 what was the issue for the error?
