### ISSUE TITLE
Mapping between interfaces

### ISSUE THREAD

**Issue by kpsharath** [mapstruct/mapstruct#1351]
Hi as of now i'm able to do the mapping between simple classes. Now i have to map between interfaces.
Consider i have 2 interfaces where many classes implements these interfaces. Since i didn't get to know how to do, i have mapped to specific type of interface A. Now i need to do reverse mapping, where attributes may be in subclasses, how to do inverse mapping in  this case. I tried @InheritInverseConfiguratioin tag it didn't work. 
instead of reading descriptions, it will be really helpful if i get some code snippet in answer to understand

**Comment by filiphr** [comment]
Please provide some examples with what you have been trying so we can help out. You can also use our [forum](https://groups.google.com/forum/#!forum/mapstruct-users) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) with the `mapstruct` tag for questions
