### ISSUE TITLE
@Mapping arguments should be trimmed

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1353]
I've noticed that if you add a space in front of a mapping, you get an error. However, the error is not related to a property but to the complete method which makes it hard to debug (see #1354). Its questionable whether this should be seen as an error or just been ignored.

**Comment by filiphr** [comment]
I am not entirely sure that we should trim... Having leading spaces looks strange in code, so I would say that we show an error if the arguments have spaces.

**Comment by sjaakd** [comment]
> I am not entirely sure that we should trim... Having leading spaces looks strange in code, so I would say that we show an error if the arguments have spaces.

What do you mean with "Having leading spaces looks strange in code"? If you have loads of [mappings](https://github.com/sjaakd/CPT_GEF_CONVERTER/blob/master/gef_impl/src/main/java/nl/bro/cpt/gef/transform/GefToBroMapperImbro.java), they are easy to overlook :smile:

**Comment by filiphr** [comment]
Well allowing something like `@Mapping( target = " myProperty", source = " mySource")` seems strange to me. I didn't mean that it is strange to do it, yes you can easily overlook it I agree. Therefore, I think that we should output an error if there are leading or trailing spaces in a `@Mapping`.

**Comment by sjaakd** [comment]
> Therefore, I think that we should output an error if there are leading or trailing spaces in a @Mapping.

Perhaps in this case we could do a trim and warn instead of error. I think the intention is clear and we don't want to be pedantic.

**Comment by gunnarmorling** [comment]
+1 for just trimming (warn if you like) and processing the property. Let's
try and not annoy people more than necessary :)

**Comment by filiphr** [comment]
Then it's fine for me 😄. Trimming and warning should suffice

**Comment by filiphr** [comment]
Of course, if it is not too complex to perform the warning, if it is, then we should not really go out of our way to do it 😄
