### ISSUE TITLE
Suggestion: Add implicit conversion String <-> java.util.Currency

### ISSUE THREAD

**Issue by tkruse** [mapstruct/mapstruct#1355]
Title says it all, not sure what further detail would be needed.

**Comment by gunnarmorling** [comment]
Sounds good. Would you like to send a PR? Happy to include it. Thanks!

**Comment by tkruse** [comment]
no promise. Do you have a pointer which files should be touched for this?

**Comment by filiphr** [comment]
I think that you can do this via conversions. Have a look at [`Conversions`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java) and how they are registered.

Some conversions for inspiration: `CharToStringConversion`, `CharWrapperToStringConversion`, `EnumStringConversion`, `BigDecimalToBigIntegerConversion`, `DateToSqlTimeConversion`, `DateToSqlDateConversion`, `DateToSqlTimestampConversion`.

The final part would be adding the new supported implicit conversion in the reference documentation under [Implicit type conversions](http://mapstruct.org/documentation/stable/reference/html/#implicit-type-conversions)

**Comment by xyzst** [comment]
I'll try to implement this, should have something to review before next week

**Comment by filiphr** [comment]
Support for this has been added in #1381. Thanks for the PR @xyzst

**Comment by tkruse** [comment]
thx
