### ISSUE TITLE
Mapstruct LocalDateTime to Instant

### ISSUE THREAD

**Issue by batuhancaglayan** [mapstruct/mapstruct#1357]
Hello,

I am new in Mapstruct. I have a model object which includes LocalDateTime type field. DTO includes Instant type field. I want to map LocalDateTime type field to Instant type field. I have **TimeZone** instance of incomming requests. 

Manually field setting like that;
set( LocalDateTime.ofInstant(x.getStartDate(), timeZone.toZoneId()) )

How can i map these fields using with Mapstruct.
Thanks.

**Comment by filiphr** [comment]
I've already answered this question on StackOverflow, [here](https://stackoverflow.com/a/47948158/1115491) is the link.

The answer here as well:

You have 2 options to achieve what you are looking for.

First option:

Use the new `@Context` annotation from 1.2.0.Final for the `timeZone` property and define your own method that would perform the mapping. Something like:

```java
public interface MyMapper {

    @Mapping(target = "start", source = "startDate")
    Target map(Source source, @Context TimeZone timeZone);

    default LocalDateTime fromInstant(Instant instant, @Context TimeZone timeZone) {
        return instant == null ? null : LocalDateTime.ofInstant(instant, timeZone.toZoneId());
    }
}
```

MapStruct will then use the provided method to perform mapping between Instant and LocalDateTime.

The second option:

```java
public interface MyMapper {

    @Mapping(target = "start", expression = "java(LocalDateTime.ofInstant(source.getStartDate(), timezone.toZoneId()))")
    Target map(Source source, TimeZone timeZone);
}
```

My personal option would be to use the first one

**Comment by batuhancaglayan** [comment]
Thanks for your attention Filip, StackOverflow question is mine:(
I created a class which includes first option methods (fromInstant and toInstant). I referenced this class to my mapper (@Mapper(uses=LocalTimeMapper.class)). Thanks again.

**Comment by filiphr** [comment]
I knew that it is yours @batuhancaglayan, I forgot to mention that in my previous comment.

Your appro
