### ISSUE TITLE
Multiple source objects to single target list

### ISSUE THREAD

**Issue by Swaraj-Bharti** [mapstruct/mapstruct#1358]
We  have scenario to map multiple object of similar nature into single target list . is there a way to achieve that using mapstruct ?
*************************************
Source Object structure 
*********************************
```
Class CustomerAddresses{
    PermanentAddress  p;
   CommunicationAddress c;
    POBoxAddress po;
    ShippingAddress s;
}
Class PermanentAddress {
    String addrLine1;
    String addrLine2;
    String city;
    String state;
    String country;
    String zip;
}
Class CommunicationAddress {
    String houseNo;
    String StreetNo;
    String city;
    String province;
    String country;
    String postalCode;
}

Class POBoxAddress{
   String boxNo;
   String city;
   String state;
   String country
   String zip;
}
Class ShippingAddress{
    String flatNo;
    String apartmentName;
    String street;
    String block;
    String state;
    String country;
    String zip;
}
```

*************************************
Target Object structure 
*********************************
```
Class ClientAddresses{
  List<Address>  addresses;
}
Class Address {
    List<CodeValue>  details;
}
Class CodeValue{
  String code;
  String value;
}
```

For mapping of each SourceAddress type  to Address objects , idea was to use a util class and mappedBy Qualifier for each specific conversion ; however i am not able to get a single list of Address Objects. , as it does not allow multiple mapping to same target property "addresses" .

**Comment by filiphr** [comment]
I can't thing of a way to achieve what you are looking for at the moment, I think that it is currently not possible to do it with MapStruct at the moment. You would need to perform your logic in an `@AfterMapping` or `@BeforeMapping` and set the `addresses` by yourself
