### ISSUE TITLE
@Mapping(uses=)

### ISSUE THREAD

**Issue by spoerri** [mapstruct/mapstruct#1360]
Would you accept a patch to support “uses” as a parameter to `@Mapping`?

It’d work just like ”uses” on `@Mapper` accepting a class etc, though of course it’d apply just for the one target field. We currently use “expression” to achieve something similar, but this would be better.

**Comment by filiphr** [comment]
Why do you need to do something like that? You can use the `Qualifier` annotation and `Mapping#qualifiedByName` to perform something like that

**Comment by spoerri** [comment]
Yes, qualifiedByName is another way to do it. It's less obvious, and the IDE support for it is less good. And it also requires editing two different places in the file, the `@Mapping` line and the `@Mapper` line.

E.g. when I see `qualifiedByName = { "TitleTranslator" }`, I have to be pretty familiar with mapstruct to know that it's going to run the `@Named("TitleTranslator")` mapper. And to be really sure, I have to consult the "uses" parameter of the class and, potentially all of the super-classes/interfaces and the shared configuration via `@MapperConfig`.

With the proposed syntax, I could navigate directly to the logic with a ctrl-click.

**Comment by gunnarmorling** [comment]
How would the code generated for this look like? `@Mapper#uses()` causes the generation of fields within the mapper implementation, it's not clear to me how this would look like when giving used mappers within `@Mapping`.

Also, can you provide a complete example of your use case? So far I'd agree with @filiphr that using qualified mapping methods is the way to go here.

**Comment by sjaakd** [comment]
The qualifier (qualifiedByName or defining your own qualifier) approach is copied from other frameworks (e.g. CDI). So for many developers its a familiar concept.

Having said this, perhaps we can enhance IDE (Intellij, Eclipse) support (e.g. linking as you describe or even having a context option to generate a qualifer + method signature in the current mapper. We could reuse MapStruct code for that perhaps.

**Comment by spoerri** [comment]
Instead of:
```
@Named("TitleTranslator")
public class Titles {
    @Named("EnglishToGerman")
    public String translateTitleEG(String title) {
        // some mapping logic
    }
}
@Mapper( uses = Titles.class )
public interface MovieMapper {
     @Mapping( target = "title", qualifiedByName = { "TitleTranslator", "EnglishToGerman" } )
     GermanRelease toGerman( OriginalRelease movies );
}
```

We’d use:
```
public class Titles {
    public static class EnglishToGerman {
        public String translateTitleEG(String title) {
            // some mapping logic
        }
    }
}
@Mapper
public interface MovieMapper {
     @Mapping( target = "title", uses = TitleTranslator.EnglishToGerman.class )
     GermanRelease toGerman( OriginalRelease movies );
}
```
And it would generate pretty much the same code as the above currently does.

IMHO it’s much nicer, so much nicer that if we’re worried about having two different ways of doing the same thing, we could deprecate qualifiers!

**Comment by gunnarmorling** [comment]
Thanks for providing the example, that helps a lot.

This would change the meaning of `uses()` significantly, though. Currently it's purpose just to make other mappers known to the one at hand (and inject references to those mappers into it), whereas here you're suggesting to widen the purpose of `uses()` to address needs of method selection, too.

Personally I'm not a big fan of using one construct (`uses()`) for two different purposes in that way. Also this proposal does not - unlike qualifiers - provide a way to resolve ambiguities amongst multiple methods of one mapper class (say you'd have two matching methods on `EnglishToGerman`).

I think you're better off to use qualifier annotations for your use case:

     @Mapping( target = "title", qualifiedBy = { TitleTranslator.class, EnglishToGerman.class } )
     GermanRelease toGerman( OriginalRelease movies );

**Comment by spoerri** [comment]
Full disclosure: I cribbed my example from the mapstruct documentation itself.

 To avoid changing the meaning of “uses”, we could name the parameter something different, e.g. “explicitMapper” or just “explicit”.

 Unlike the mapped objects, which the application developers may not own or maintain manually, we can change the mapper code and organize it in the best way.  Appdevs can always use an inner class instead of having ambiguous methods in the same level of a single class.

To be clear: this has become a proposal to eventually *change* the API of the qualifier feature altogether. IMHO if we were to support both APIs, the explicit one would become much more widely used.

**Comment by thunderhook** [comment]
> Yes, qualifiedByName is another way to do it. It's less obvious, **and the IDE support for it is less good.**

It has become really good in the meantime. So I would no longer use that as an argument.
IMHO the qualifiers do a great job of defining what mapping should actually be used. So I wouldn't add an extra option to point to a different mapping. It makes the API more complex and users need to think about which of these options are prioritised by MapStruct.

**Comment by filiphr** [comment]
Since this is a really old issue and there hasn't been a lot of interest in this I am going to go ahead and close it. We can always reopen it if we need to.
