### ISSUE TITLE
Smarter configuration reuse

### ISSUE THREAD

**Issue by svpace** [mapstruct/mapstruct#1362]
Hi,

I have a class "AbstractEntity" with the field "user" and a subclass AbstractAuditingEntity with the fields "createdAt" and "updatedAt". None of those fields would generally be mapped to DTOs. Therefore I create a shared configuration as follows

```java
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    AbstractAuditingEntity mapAuditingEntity(@MappingTarget AbstractAuditingEntity entity, Object source);

    @Mapping(target = "user", ignore = true)
    AbstractEntity mapEntity(@MappingTarget AbstractEntity entity, Object source);
```

MapStruct is giving me a "More than one configuration prototype method is applicable" error for every method mapping a subclass of AbstractAuditingEntity. Since AbstractAuditingEntity inherits from AbstractEntity, I would expect that both sets of configurations to be applied.

**Comment by filiphr** [comment]
@svpace that is not how the configuration inheritance works in the moment. Currently you would have to add `@Mapping(target = "user", ignore = true)` to the `mapAuditingEntity` as well and explicitly specify with `@InheritConfiguration("mapAudingEntity")` the method from which you need to inherit the configuration.

**Comment by svpace** [comment]
Indeed, and that is exactly the point of this issue. I believe that MapStruct could be made smarter about configuration inheritance to take into account the classes inheritance. 

IMHO would be a gain in reducing repetition, verbosity and "least surprise".

**Comment by sjaakd** [comment]
The configuration use has been modified. Checkout our latest branch. Inheritance is still not applied as proposed above. What has been done is aligning explicit and implicit `InheritConfiguration`. It is now possible to:
* Inherit a configuration and reverse configuration simultaneously. 
* Also there's a PR pending on ignoring all properties in a bean. Checkout: #1392.

Although this still would not allow inheritance, does this cover your requirements sufficiently?

**Comment by sjaakd** [comment]
@svpace can you indicate if you can continue with the provided solution..? I'll continue later this week to close this issue.

**Comment by sjaakd** [comment]
@svpace .. to be precise. You would like MapStruct to match the method that is (inheritance wise ) closest to the object that you try to match.. ?

**Comment by svpace** [comment]
Yes, you're correct, it should prefer to implement the "closest" method declaration.

But not only that. It shouls also inherit the @Mapping annotations of all the other compatible declarations.

I would like that ConcreteEntity mapper to use the AbstractAuditEntity mapper but also ignore the "user" field as configured in the AbstractEntity mapper, without having to repeat that in the AbstractAuditEntity mapper.

**Comment by sjaakd** [comment]
@svpace .. I don't think we are going to implement this in the short run. We've not had any more feedback on this issue. .

Furthermore: I think that the solution will be hard to explain. 

So I'll continue to close this issue.
