### ISSUE TITLE
Allow defaultValue to be an expression

### ISSUE THREAD

**Issue by smythie86** [mapstruct/mapstruct#1363]
It would be great to be able to make an expression a default value, like this:

```java
    @Mappings({
      @Mapping(target="Id", source="obj.SourceId", defaultValue = "java(UUID.randomUUID().toString())")
    })
    MyObject myObjToMyObject(MyObj obj);
```

**Comment by filiphr** [comment]
That's an interesting proposal @smythie86. I am not sure if we should reuse `defaultValue` or add a new `defaultExpression` for this. The advantage of adding a new `defaultExpression` would be in the fact that it would be much clearer to the person looking at the code

**Comment by sjaakd** [comment]
What about reusing the current defaultvalue and allow the expression syntax: Java()

Verstuurd vanaf mijn iPhone

**Comment by gunnarmorling** [comment]
Why is it that not simply the existing `expression()` could be used? Is it related to the case where the source property is null?

**Comment by filiphr** [comment]
@sjaakd that was the proposal of @smythie86.

@gunnarmorling yes this is when the source is null, we can't use the current expression as that is for the actual mapping of the property. That is why I suggested the `defaultExpression`. However, we could reuse the `defaultValue` as well.

**Comment by gunnarmorling** [comment]
Got it. Re-using `defaultValue` would be nice, although it poses a problem
with backwards-compatability: there's the - unlikely - case that someone
wanted to set their target property to the literal value
"java(someexpression)". Having a new attribute deafultExpression would
avoid that issue, but I'm unsure whether it's worth it. What do you folks
think?

**Comment by filiphr** [comment]
I personally am split, I have no particular preference between reusing `defaultValue` and adding a new one.

@smythie86 if you are interested you can provide a PR for this functionality, we can of course help you out with it ;)

**Comment by smythie86** [comment]
I will try to take a look at this and see what I can do

**Comment by filiphr** [comment]
Support for this has been added in #1372 thanks for the PR @smythie86, sorry that it took so long to merge it
