### ISSUE TITLE
Show warning probably 

### ISSUE THREAD

**Issue by mohammedhammouri** [mapstruct/mapstruct#1371]
I have the following class 
public interface TwoWayMapper<From,To>{
    To map(From from);
    From mapTo(To to);
}
where each mapper extends from it
Example : 

@Mapper(uses = {IdEntityToIdMapper.class})
public interface PlanEntityToPlanMapper extends TwoWayMapper<PlanEntity,Plan>{
}

I have a lot of mappers whenever I got a warning it shows to me like this ; 
C:\jpc\src\main\java\com\zunbarak\common\TwoWayMapper.java:5: warning: Unmapped target properties: "forUserId, createdTimeStamp, updatedTimeStamp, id, type, keyValue, name".
    To map(From from);
       ^

The problem is that it shows me that the problem in TwoWayMapper interface (superclass)
Not the real class which implement/extends it

**Comment by filiphr** [comment]
This is a duplicate of #598. Therefore I am going to close this one. Please watch the linked issue
