### ISSUE TITLE
Have control if intermediate objects are created when doing nested mappings.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1377]
Currently its not possible to determine whether or not to create interstitual target objects when the source is null. This should be controllable by means of a strategy.

**Comment by MarkRobbo** [comment]
The implementation of this would allow us to switch over to Mapstruct from Dozer in a large system without tons of boilerplate code in @AfterMapping annotated methods, so is of a lot of interest to me.

If you also know of a good workaround for doing this in the meantime I would also be very interested to hear.

**Comment by filiphr** [comment]
@sjaakd is this similar / same as #1166?

**Comment by sjaakd** [comment]
Similar. #1166 mentiones reverse mappings. This is more general

Verstuurd vanaf mijn iPhone
