### ISSUE TITLE
Extremily low mapstruct-processor performance on Java 9

### ISSUE THREAD

**Issue by vladimir-novoseltsev** [mapstruct/mapstruct#1378]
Project build on Java 9 with mapstruct-processor is extremely slow.
Project is around 5200 classes including arond 400 mappers. On java 8 the whole project builds in 50-60 seconds on mine development machine under Linux (i7-3720qm laptop, 16gb ram). I've sampled CPU usage with VisualVM and attached screenshot for reference. It seem like the main culprit for performance regression is com.sun.tools.javac.model.JavaElements.getTypeElement(), but I'm not familiar with this subject enough to solve problem myself.
![2018-02-12 16 18 39](https://user-images.githubusercontent.com/1718526/36099152-aadaad70-1012-11e8-8d63-47635d56b547.png)

**Comment by filiphr** [comment]
@vladimir-novoseltsev thanks a lot for the screenshot. We will investigate this and try to provide a fix. Can you tell us which Java 9 version are you using?

**Comment by vladimir-novoseltsev** [comment]
@filiphr 
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by filiphr** [comment]
@vladimir-novoseltsev by looking at your screenshot I managed to do #1379. However, I am not 100% sure that it would fix the problem. Do you perhaps have some time to run your code base with my fix from the PR? You can use jitpack.io to build the project 

Thanks,
Filip

**Comment by vladimir-novoseltsev** [comment]
Hello, sorry for delay. I'd like to try processor with new pull request but I'm not sure how should I write version string in project in a way jitpack will accept it. It is pretty straightforward with branches/commits but I have find nothing on pull requests in documentation.

**Comment by filiphr** [comment]
You would need to reference the branch / commit from my repo. Have a look at https://jitpack.io/#Filiphr/mapstruct/1378-SNAPSHOT

**Comment by vladimir-novoseltsev** [comment]
Doesn't seem to work, build failed with a bunch of "error: Couldn't retrieve @Mapper annotation" errors.

**Comment by filiphr** [comment]
@vladimir-novoseltsev that is strange. Did you manage to download the dependencies?

I just tried with:

```
<dependency>
    <groupId>com.github.filiphr.mapstruct</groupId>
    <artifactId>mapstruct-jdk8</artifactId>
    <version>1378-SNAPSHOT</version>
</dependency>
```

Of course the others as well. And it worked. Can you make sure that you have the jitpack repo in `<repositories>` and the you are not using the processor plugin (I've had issues with that one when using custom repos).

**Comment by vladimir-novoseltsev** [comment]
@filiphr I've tried only with 1378-SNAPSHOT mapstruct-processor, not other dependencies have been updated.

**Comment by filiphr** [comment]
I was mostly referring to the groupId. Make sure that is like the one from my previous message

**Comment by vladimir-novoseltsev** [comment]
@filiphr Tried with all dependencies references the way you've provided. Java 9 build have run a lot faster on Win10 on the same laptop I've referenced before, it finished in 2:35 min. Build on Linux would probably be noticeably faster.

**Comment by filiphr** [comment]
Thanks for checking it out. We will merge the PR then.

It would be interesting to know how long was the build on Win10 on Java 8? I understood it took 50-60 seconds on Java 8 on Linux. If you can share that with us it would be great.

**Comment by vladimir-novoseltsev** [comment]
On Win 10, Java 8 build takes around 1:30min.

**Comment by filiphr** [comment]
So on Java 9 is 1 min slower. If you find more places where we are slowing down the build please share them with us, we would be more than happy to fix it :)

**Comment by sjaakd** [comment]
> 2:35 min.

For all intends and purposes: do you mean 2 hours and 35 minutes..? or 2 minutes and 35 seconds?

**Comment by vladimir-novoseltsev** [comment]
2 minutes 35 seconds on Java 9 and 1 minute 30 seconds on Java 8.

**Comment by keemcode** [comment]
Mapper Struct Build Time  .......................................... SUCCESS [05:19 min]

JDK Version 
----------------------------------------------------------------------------------------------------------------------------------------------
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)



Machine 
----------------------------------------------------------------------------------------------------------------------------------------------
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by filiphr** [comment]
@keemcode please do not comment on closed issues. If you think that there is some kind of problem please create a new issue with the same information that were provided by @vladimir-novoseltsev when he created this issue. Otherwise we can't do much.
