### ISSUE TITLE
Java 9: java.annotations.common has been renamed to java.xml.ws.annotation

### ISSUE THREAD

**Issue by davidyee** [mapstruct/mapstruct#1382]
According to the documentation regarding [Using MapStruct on Java 9](http://mapstruct.org/documentation/stable/reference/html/#_using_mapstruct_on_java_9), `MAVEN_OPTS` should be set as followed:

```bash
export MAVEN_OPTS="--add-modules java.annotations.common"
```

However, at least in the latest public JDK 9.0.4+11, the above setting results in an error with Maven (I am using latest Maven v3.5.2 with Java 9.0.4):

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.annotations.common not found
```

According to [JDK-8173604](https://bugs.openjdk.java.net/browse/JDK-8173604), the `java.annotations.common` module has been renamed to `java.xml.ws.annotation`. Therefore, the correct setting is now:

```bash
export MAVEN_OPTS="--add-modules java.xml.ws.annotation"
```

**Comment by filiphr** [comment]
Thanks for the tip @davidyee. We are going to fix this for the next release

**Comment by gunnarmorling** [comment]
Another fact to consider is that there is a new `@java.annotation.processing.Generated` annotation as of Java 9. That - unlike the old one - is considered as a general purpose annotation for any code generators. So ideally on Java 9 we'd use this annotation.

FWIW, other processors such as JBoss Logging added a processor option for supressing the addition of any `@Generated` annotation which might be the simplest avoid any hazzle with that. We could do the same, e.g. add "-Amapstruct. suppressGeneratedAnnotation".
