### ISSUE TITLE
One to many conversion JPA / Spring Data

### ISSUE THREAD

**Issue by klearchos** [mapstruct/mapstruct#1385]
Hello,

I am trying to convert and save a one to many association with mapstruct.
I can see from the generated code that the keys (birectional) are being assigned but since this is a new entity basically null values are set. The actual object references are not being set.

You can find more information here:
https://stackoverflow.com/questions/48967181/spring-data-and-jpa-one-to-many-with-mapstruct

I found a workaround but I believe that this is not the correct MapStruct way of doing the conversion.
For me it seems that I simply use the library in the wrong way and I miss something basic.
Could you please help ?

Thank you in advance

**Comment by filiphr** [comment]
@klearchos I have just answered the SO question

**Comment by sjaakd** [comment]
There's another possibility... checkout https://github.com/mapstruct/mapstruct-examples/pull/37

**Comment by klearchos** [comment]
Thank you a lot both! Really useful comments at SO.
