### ISSUE TITLE
Map Abstract Class and Inheritance

### ISSUE THREAD

**Issue by melalgi-acensi** [mapstruct/mapstruct#1388]
I have a serous problem with mapstruct to do the transformation of my Entity Objects to DTO object so i can use theme in UI and other part of my application.

This is my objects 

public abstract class Item implements Serializable {
    private Long id;
    private String itemNumber;
    private String name;
    private ObjectStatus status;
    private String description;
    private String tags;
}

and it's mapper : 
@Mapper(componentModel = "spring")
public interface ItemMapper {

    default <T extends ItemDTO> Optional<Item> toEntity(T t) {
        if (t instanceof CarDTO) {
            return Optional.of(toCar((CarDTO) t));
        } else if (t instanceof PaintingDTO) {
            return Optional.of(toPainting((PaintingDTO) t));
        }
        return Optional.empty();
    }

    default <T extends Item> Optional<ItemDTO> toDto(T t) {
        if (t instanceof Car) {
            return Optional.of(toCarDto((Car) t));
        } else if (t instanceof Painting) {
            return Optional.of(toPaintingDto((Painting) t));
        }
        return Optional.empty();
    }

    Car toCar(CarDTO carDTO);
    CarDTO toCarDto(Car car);
    Painting toPainting(PaintingDTO paintingDTO);
    PaintingDTO toPaintingDto(Painting painting);
}

public class Car extends Item implements Serializable {
    private String title;
    private String serialNumber;
    private String reference;
    private String creator;
    private String period;
}

and it's mapper 
@Mapper(componentModel = "spring")
public interface CarMapper extends EntityMapper<CarDTO, Car> {
    Car toEntity(CarDTO carDTO);
    CarDTO toDto(Car car);
}

public class Painting extends Item implements Serializable {
    private String title;
    private String artist;
    private String origin;
    private String technic;
}
and PaintingMapper : 
@Mapper(componentModel = "spring")
public interface PaintingMapper extends EntityMapper<PaintingDTO, Painting> {
    Painting toEntity(PaintingDTO paintingDTO);
    PaintingDTO toDto(Painting painting);
}

The problem that i get when building my project is : 
Error:(16, 9) java: The return type com.artcurial.backoffice.data.domain.objects.Item is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.

Error:(17, 9) java: The return type com.artcurial.backoffice.data.domain.objects.Item is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.

Error:(14, 14) java: The return type com.artcurial.backoffice.data.domain.objects.Item is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.

So i'm confused and really need some help.

**Comment by sjaakd** [comment]
@melalgi-acensi .. MapStruct somewhere wants to create an object to return. It is not capable of doing so right now. Please take a look at the [reference guide](http://mapstruct.org/documentation/stable/reference/pdf/mapstruct-reference-guide.pdf), chapter 5.5 `@MappingTarget`.  Try to add a `@MappingTarget` argument to `default <T extends ItemDTO> Optional<Item> toEntity(T t)`, so something along the lines of `default <T extends ItemDTO> Optional<Item> toEntity(T t, @MappingTarget Class<T> clz)`

@saw303 is right.. It would help if you would issue your question on Stackoveflow.com or on our user group (see our website). You will help other users with similar questions as well :smile:
