### ISSUE TITLE
Can MapStruct be told to not perform automatic mappings?

### ISSUE THREAD

**Issue by saikumar-a** [mapstruct/mapstruct#1389]
Followup on the two year old question from stackoverflow [here](https://stackoverflow.com/questions/34629563/can-mapstruct-be-told-to-not-perform-automatic-mappings), is mapper level switch implemented in 1.2.0 Final? If yes, how can I do that ?

**Comment by filiphr** [comment]
@saikumar-a the answer on that question is still valid. Currently, there is no way to not perform automatic mappings. You would need to explicitly use `@Mapping(target = "property", ignore = true)` to ignore the mapping.
