### ISSUE TITLE
How can I map properties conditionally with MapStruct 1.2?

### ISSUE THREAD

**Issue by du-it** [mapstruct/mapstruct#1390]
Is it possible with MapStruct 1.2 to map a source property with a specific value to a specific different value in the target?

I think about something like this:

```java
@Mapper(componentModel = "spring", uses = MyCustomMapper.class)
public interface MyMapper {
    @Mappings({
    @Mapping(source = "mySource.propA", target = "myTarget.propX")
    })
@ValueMappings({
            @ValueMapping(source = "ABC", target = "XYZ"),
            @ValueMapping(source = "123", target = "789")
        })
        MyTarget source2Target(final MySource mySource);
}
```

So that when MapStruct sees during the mapping that when mySource.propA has the value "ABC" myTarget.propX needs to be set to value "XYZ" and so forth.

(Sorry for the code, I didn't get it to let the code being displayed properly although marking the text as code using the <>.)

To be  more precisely, I even want something more elaborated:
The target should be a class haven three properties in which the resulting target value must be split into.
For instance, if mySource.propA has the value "ABC" the target myTarget should get a value like "V01.123.456.AB". This value in turn shall be split up in a preValue, a middleValue and an endValue:
preValue = "V01"
middleValue = "123.456"
endValue = "AB". 

That's why I already wrote a custom mapper and I tell the MyMapper to use it via 
`@Mapper(componentModel = "spring", uses = MyCustomMapper.class)`

This works so far but I can't achieve it to tell the MyCustomMapper to put "V01.123.456.AB" into the target when the souzrce comes with "ABC".

**Comment by du-it** [comment]
I think I can't really do that with MapStruct. The @ValueMapping annotation is for mapping of Enum(s).

In order to achieve what I am looking for I would need to do that in @BeforeMapping or @AfterMapping.

For example I can do something like:

@Mapper
public interface JiraKpmMapper {

    @BeforeMapping
    default void beforeMapping(@MappingTarget MyTarget target, MySource source) {
        if (source.getPropY().equals("ABC") {
            target.setPropX("V01.123.456.AB");
        }
    }

    @Mapping(target = "propX", ignore = true) // This is now mapped in beforeMapping
    MyTarget source2Target(final MySource mySource);
}
The custom mapper then should have an @AfterMapping. Where I would convert the propX into my class. I can even do this as part of the @BeforeMapping and directly create my class (or invoke the method that does the conversion from String into a class).

**Comment by filiphr** [comment]
@du-it thanks for updating the issue. I am the one answering the question on [SO](https://stackoverflow.com/questions/49067870/how-can-i-map-properties-conditionally-with-mapstruct-1-2/) :). 

I am going to close this issue. If you think that we need to reopen please say so

**Comment by du-it** [comment]
I don't  think that we we have to reopen the question (by now). It was a good and helpful answer. Since I didn't get an answer until I updated the issue here I wanted to let the rest of the world know how to handle such an issue (if I am not the only on who had this problem). ;-)
