### ISSUE TITLE
Generate ERROR in case of @Nullable source property mapped to @NonNull target property

### ISSUE THREAD

**Issue by ondrejlerch** [mapstruct/mapstruct#1391]
Let's assume we have Person:
```
import javax.annotation.Nullable;
public class Person {
  @Nullable
  private String middleName;

  @Nullable
  public String getMiddleName() {
    return middleName;
  }
}
```
PersonDto:
```
import javax.annotation.NonNull;
public class PersonDto {
  @NonNull
  private String middleName;

  public void setMiddleName(@NonNull middleName) {
    this.middleName = middleName;
  }
}
```
and PersonMapper:
```
@Mapper
public interface PersonMapper {
  PersonDto personToPersonDto(Person person);
}
```
Since ```middleName``` is ```@Nullable``` in source but ```@NonNull``` in target object such mapping may lead to situation where ```personDto.getMiddleName() == null``` which is bad.

It would be great if MapStruct would detect such NPE issues and would produce ERROR or at least WARNING.

In 95% of use cases we would welcome such ERROR. In 5% of use cases we would like to explicitly tell MapStruct to ignore possible NPE for this particular property via some annotation parameter.

Btw instead of ```@NonNull``` annotation polluting our code base we are using Spring 5 ```@NonNullApi``` and ```@NonNullFields``` applied via ```package-info.java```.

Notice that if we would write mapper manually we would be warned by IntellijIDEA on line: 
```
personDto.setMiddleName(person.getMiddleName())
```
but we get no such warning when using MapStruct since IntellijIDEA does not analyze generated code.

Many thanks.

**Comment by filiphr** [comment]
@ondrejlerch would #1243 cover your use case? That one actually proposes to have support for the Spring 5 `@NonNullApi`. 

In your particular use case it would look like:

```
if (person.getMiddleName() != null) {
    personDto.setMiddleName(person.getMiddleName());
} 
```

I am going to close this one. However, if you feel that it is different, than I can reopen it.

Btw, if you are interested in helping out for this functionality we would be more than happy to help you out 😄

**Comment by ondrejlerch** [comment]
@filiphr 
I think those 2 issues are different.

I am not interested in:
```
if (person.getMiddleName() != null) {
    personDto.setMiddleName(person.getMiddleName());
} 
```
Rather I would like to configure MapStruct in a way so that it would fail to generate `PersonMapperImpl` or at least give meaningful warning that `personDto.middleName` may be null even though it is annotated as `@Nonnull`.

Does it make sense?

Thanks.
