### ISSUE TITLE
SpringBoot/MapStruct/Lombok - ImplClasses not created

### ISSUE THREAD

**Issue by ppfeifer77** [mapstruct/mapstruct#1393]
Hello there,

I'm really desperate in the meanwhile, because I can't get my maven build working with the above mentioned configuration. In my EclipseIDE the annotation processing works fine and I can build the project there. But with maven on the command line I can't get it to work. The Impl-classes are not generated, I don't even have a "generated-sources" folder in my target folder. Somehow it seems that the mapping interfaces don't get picked up for generation.

I appreciate any help and any  tips how I can get this thing to work...

Thank you very much.

Peter

This is my pom.xml (I have to say that my Lombok enabled classes are in dependent projects (dbmodel, dto)):

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>at.bfzgruenbach.shop</groupId>
		<artifactId>shop</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../bfz.shop</relativePath>
	</parent>
	<groupId>at.bfz-gruenbach.shop.standalone</groupId>

	<artifactId>standalone</artifactId>
	<version>1.0-SNAPSHOT</version>

	<name>bfz.standalone</name>

	<properties>
		<org.mapstruct.version>1.2.0.Final</org.mapstruct.version>
		<!--m2e.apt.activation>jdt_apt</m2e.apt.activation -->
	</properties>

	<dependencies>

		<dependency>
			<groupId>at.bfzgruenbach.shop.commons</groupId>
			<artifactId>dbmodel</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>at.bfzgruenbach.shop.commons</groupId>
			<artifactId>dto</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>at.bfzgruenbach.shop.commons</groupId>
			<artifactId>ui</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-jdk8</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/main/js</directory>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<excludeDevtools>true</excludeDevtools>
					<excludeArtifactIds>scout-boot-ui-dev</excludeArtifactIds>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by sjaakd** [comment]
have a look at the [examples](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-rounding)..  You've included the processor as dependency. That's not the intention (you don't want the processor classes on your runtime class path). Try including it as something that the compiler plugin should call . Like this:

```
   <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by ppfeifer77** [comment]
Hi there,

I already tried to do it as you show above. But without any luck. So I ressorted to the method shown in the mapsruct/lombok [example](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-lombok/pom.xml).

The only difference I can spot is, that I have my lombok classes in another maven project (2 in fact) and that I'm using JDK8.

That's why I'm so lost...

Peter

**Comment by filiphr** [comment]
@ppfeifer77 it is really strange what you are experiencing. Can you perhaps try to exclude the transitive dependencies from Lombok (It might be due to the way Lombok has implemented the hook).

Can you confirm that the version of the `maven-compiler-plugin` is `3.6.2` and that you are not inheritting the one from `spring-boot-parent`?

**Comment by sjaakd** [comment]
> The only difference I can spot is, that I have my lombok classes in another maven project (2 in fact) and that I'm using JDK8.

If the Lombok classes are in another maven project you should not have any issues with lombok at all. Can you try building on the command line?

**Comment by ppfeifer77** [comment]
Hi,
> Can you confirm that the version of the maven-compiler-plugin is 3.6.2 and that you are not inheritting the one from spring-boot-parent?

Good question, at least Eclipse tells me, that I'm using a different version of the maven-compiler-plugin as it is defined in the parent pom.

`Overriding managed version 3.1 for maven-compiler-plugin`

> Can you try building on the command line?
That's what I'm doing all the time :) Because I want to get it to work on the command line in order to setting up a build pipeline in jenkins then....

Thanks a lot for your help.

Peter

**Comment by sjaakd** [comment]
@ppfeifer77 : any progress on your side?

**Comment by sjaakd** [comment]
I'm not an Eclipse expert, but the (perhaps) obvious things are:
* Lombok comes with its own installer for eclipse, you need to use that one otherwise it won't work.
* Annotation processing is a bit messy: in the past you needed to get apt from the marketplace
* the update-maven-project thingy (if you generate your Lombok stuff in a separate library). 
* you can actually print the effective pom in eclipse. That takes into corporation the minimum required versions. Perhaps you use some kind of old Lombok / Eclipse combi.

Anyway .. just guessing.. It sounds perhaps a bit pedantic, but usually its not MapStruct (since it uses (mostly) standard annotation processing capabilities of java).

**Comment by ppfeifer77** [comment]
Well it may have nothing to do with Eclipse itself, because from within Eclipse everything works fine. The source is generated and is running flawlessly.

It's just when moving to the command line and trying to compile the source manually with maven there. Then the problems start.

**Comment by sjaakd** [comment]
> I already tried to do it as you show above. But without any luck. So I ressorted to the method shown in the mapsruct/lombok example.

I updated the example (filed a PR). Check [here](https://github.com/mapstruct/mapstruct-examples/pull/41). I would go for the `annotationProcessorPaths` in combination with `maven-compiler-plugin` 3.6.2 or later.

You might want to get the `maven-compiler-plugin` version with following command (command line) `mvn help:effective-pom`

**Comment by filiphr** [comment]
Thanks for the feedback. Glad that it works. Since it seems this is resolved I will close this issue.

**Comment by davidvasquezr** [comment]
Try adding this dependency 
```
<dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.3.2</version>
                <type>jar</type>
</dependency>
```
