### ISSUE TITLE
Question :  automatic mapping from b-> a when a -> b has been implemented

### ISSUE THREAD

**Issue by GreenUtil** [mapstruct/mapstruct#1402]
Hello all,

I am wondering, is it possible to automatically let generate the b -> a mapper, when a -> b has been built like 

```
@Mapper
public interface CarMapper {

    CarMapper INSTANCE = Mappers.getMapper( CarMapper.class );

    @Mapping(source = "numberOfSeats", target = "seatCount")
    CarDto carToCarDto(Car car);
}
```

The result should look like this

```
@Mapper
public interface CarMapperReverse {

    CarMapperReverse INSTANCE = Mappers.getMapper( CarMapperReverse.class );

    @Mapping(source = "seatCount", target = "numberOfSeats")
    Car carDtoToCar(CarDto carDto);
}
```

**Comment by sjaakd** [comment]
@GreenUtil : check [this](http://mapstruct.org/documentation/reference-guide). You probably need to define a `SharedConfig`. So: move the definitions to `SharedConfig` and refer in the forward mapper and in the reverse mapper to each method  in the shared config (so `InheritConfiguration( name = xyz )` and `InheritInverseConfiguration( name = xyz )`  with `xyz` the method name in the shared config.

**Comment by GreenUtil** [comment]
Thanks Sjaak, great reference guide. I am convinced MapStruct will solve the inverse mapping.
