### ISSUE TITLE
[Improvement] DateTimeParseException on dateFormat when String is empty

### ISSUE THREAD

**Issue by ZoraBoris** [mapstruct/mapstruct#1405]
Hi team,
Could you, please, make improvement for dateFormat functionality, ignore when String is empty

```
@Mapping(source = "agingdate", target = "agingDate", dateFormat = "MM/dd/yyyy"),
```

this code generates to code that have no check on empty String:

```
if ( agingdetailsType.getAgingdate() != null ) {
    agingDetails.setAgingDate( java.time.LocalDate.parse( agingdetailsType.getAgingdate(), DateTimeFormatter.ofPattern( "MM/dd/yyyy" ) ) );
}
```

throws exception when date is empty String (e.g. it is possible when xml tag is empty)

```
java.time.format.DateTimeParseException: Text \"\" could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1849)
        at java.time.LocalDate.parse(LocalDate.java:400)
```

workaround exists, but improvement appreciated

```
@Mapping(expression = "java(convertDate(agingdetailsType.getAgingdate()))", target = "agingDate")

default LocalDate convertDate(String agingDate) {
        if (StringUtils.isNotBlank(agingDate)) {
            return LocalDate.parse(agingDate, DateTimeFormatter.ofPattern("MM/dd/yyyy"));
        }
        return null;
   }
```

**Comment by filiphr** [comment]
There is already #879 which proposes ignoring mapping of target property when the target is `null` or empty. Which would cover your use case. 

Currently, we have some other things which we are focused on for the 1.3.0 Release. However, if someone wants to provide PR for that funcationality we are more than happy to help out.

As for the workaround. You don't have to use an `expression`. Just by having that default  method there MapStruct will pick it up for mapping all `String` to `LocalData`
