### ISSUE TITLE
Inverse mapping

### ISSUE THREAD

**Issue by GreenUtil** [mapstruct/mapstruct#1408]
I have this mapping : 

```
@Mapping( target = "additionalInvestigation", source = "survey" )
    @Mapping( target = "additionalInvestigationPerformed", source = "survey.gefCptFile.measurementText111" )
    @Mapping( target = "conePenetrometerSurvey", source = "survey" )
    @Mapping( target = "deliveredLocation", source = "survey" )
    @Mapping( target = "deliveredVerticalPosition", source = "survey" )
    @Mapping( target = "deliveryContext", source = "survey.gefCptFile.measurementText102" )
    @Mapping( target = "objectIdAccountableParty", source = "survey.gefCptFile" )
    @Mapping( target = "researchOperator", source = "survey.gefCptFile.companyId" )
    @Mapping( target = "researchReportDate", source = "survey.gefCptFile.measurementText112" )
    @Mapping( target = "cptStandard", source = "survey.gefCptFile.measurementText6sondeernorm" )
    @Mapping( target = "surveyPurpose", source = "survey.gefCptFile.measurementText103" )
    protected abstract GeotechnicalCPTSurveyType createSurvey(GefCptSurvey survey);
```

where GefCptSurvey type is 

```
public class GefCptSurvey implements Serializable {

    private static final long serialVersionUID = 1L;

    private String cptFileName;
    private String objectName;

    private String qualityRegime;
    private boolean orphanaged;

    private IfcCptFile gefCptFile = new GefCptFile();
    private List<IfcDisFile> gefDisFiles = new ArrayList<IfcDisFile>();

    public IfcCptFile getGefCptFile() {
        return gefCptFile;
    }

    public List<IfcDisFile> getGefDisFiles() {
        if ( gefDisFiles == null ) {
            gefDisFiles = new ArrayList<IfcDisFile>();
        }
        return gefDisFiles;
    }

    public String getCptFileName() {
        return cptFileName;
    }

    public void setGefCptFile(IfcCptFile gefCptFile) {
        this.gefCptFile = gefCptFile;
    }

    public String getObjectName() {
        return objectName;
    }

    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    public void setGefDisFiles(List<IfcDisFile> getDisFiles) {
        this.gefDisFiles = getDisFiles;
    }

    public void setCptFileName(String cptFileName) {
        this.cptFileName = cptFileName;
    }

    @Override
    public String toString() {
        return "GefCptSurvey [fileName=" + cptFileName + "]";
    }

    public String getQualityRegime() {
        return qualityRegime;
    }

    public void setQualityRegime(String qualityRegime) {
        this.qualityRegime = qualityRegime;
    }

    public boolean isOrphanaged() {
        return orphanaged;
    }

    public void setOrphanaged(boolean orphanaged) {
        this.orphanaged = orphanaged;
    }
```
When I perform the inverse mapping like

```
@InheritInverseConfiguration
    protected abstract GefCptSurvey createGefSurvey(GeotechnicalCPTSurveyType bro_gcpt);
```
I get this compilation error : 

```[ERROR] /C:/Users/baren/git/Gef Converter/gef_impl/src/main/java/nl/bro/cpt/gef/transform/GefToBroMapperImbro.java:[295,5] Unknown property "survey" in result type nl.bro.cpt.gef.dto.GefCptSurvey. Did you mean "gefDisFiles"?```

Indeed, "survey" isn't a property of GefCptSurvey.
I am wondering why "survey" can act as a source for the forward mapping. 

`

**Comment by filiphr** [comment]
In your first mapping you have `@Mapping( target = "additionalInvestigation", source = "survey" )` which then with `@InheritInverseConfiguration` is translated into `@Mapping( target = "survey", source = "additionalInvestigation" )`. And in your case `survey` is the name of the source parameter in your first method.

I think that your issue is really similar to #1406.

When we do reverse we probably need to exclude source parameter mappings.

There is a workaround that you can do to achieve this. Your mapper can look like:

```
@Mapper
public interface MyMapper {

    @Mapping( target = "additionalInvestigation", ignore = true)
    GeotechnicalCPTSurveyType createSurvey(GefCptSurvey survey);

    AdditionaInvestigation mapAdditional(GefCptSurvey survey);

    @AfterMapping
    default void afterMapping(@MappingTarget  GeotechnicalCPTSurveyType type, GefCptSurvey survey) {
        type.setAdditionalInvestigation(mapAdditional(survey));
    }


    @InheritInverseConfiguration
    GefCptSurvey createGefSurvey(GeotechnicalCPTSurveyType bro_gcpt);
}
```

I know that it might not be optimal, but I think this is the only way at this moment.

**Comment by GreenUtil** [comment]
@sjaakd :  dear Sjaak, when I read your comments in #1406, I think the inverse mapping of a "complete source-parameter" mapping is not going to work. That's a pitty, because re-using the forward mapping seemed to be an elegant way for generating the inverse mapping, while reducing extra coding etc. etc.
And for the future, when classes are changing, only on one spot revision has to be done, in the forward mapping.
I think the only option now is setting up the inverse mapping from scratch.
Or is there another solution ?

**Comment by sjaakd** [comment]
> when I read your comments in #1406, I think the inverse mapping of a "complete source-parameter" mapping is not going to work.

@GreenUtil .. I did not claim that, right? Quote from #1406 : `However, you cannot make a reverse mapping for such mappings.`

How would the generated code look have to like in such a case?

> I think the only option now is setting up the inverse mapping from scratch.

Although I have an understanding what you are trying to achieve, remember this is a general MapStruct site. You probably can reuse many of the forward mappings, but there are always some adaptations to do. Perhaps the suggestion of @filiphr  helps.
