### ISSUE TITLE
Follow-up improvements around #120

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#141]
* `ListOfJaxbElemToListOfValue()` shouldn't be required anymore once #3 is implemented
* Unify algorithms for finding suitable mapping methods used for normal "source methods" and "built-in methods"

**Comment by gunnarmorling** [comment]
@sjaakd, thanks for taking up that one!

> Unify algorithms for finding suitable mapping methods used for normal "source methods" and "built-in methods"

Do you know whether this is still an issue? If so we should create a separate ticket for it so we can close this one for the JAXB improval.

**Comment by sjaakd** [comment]
> Do you know whether this is still an issue?

Reading this, haven't got the faintest idea what I meant back then with: "Unify algorithms" :smile:

**Comment by sjaakd** [comment]
done
