### ISSUE TITLE
Change license header to 2018

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1411]
We can probably move from the `/**` to `/*` style of license header as well. With the second one IntelliJ does not format the header, with the first one it does

**Comment by sjaakd** [comment]
Verstuurd vanaf mijn iPhone

> Op 2 apr. 2018 om 11:30 heeft Filip Hrisafov <notifications@github.com> het volgende geschreven:
> 
> We can probably move from the /** to /* style of license header as well. With the second one IntelliJ does not format the header, with the first one it does
> 
Noticed that as well. Very annoying,.

Would wait though until just before release, after all pr's are merged...

**Comment by filiphr** [comment]
>Would wait though until just before release, after all pr's are merged...

Definitely :). I just created it so we don't forget about it ;)

**Comment by gunnarmorling** [comment]
At this occasion we should also move to a simpler header without any year info, e.g. like so: https://github.com/debezium/debezium/blob/master/debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/CollectionId.java#L1-L5

**Comment by filiphr** [comment]
As agreed the new simpler header would be:

```
/*
 *  Copyright MapStruct Authors.
 *
 *  Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
```
