### ISSUE TITLE
Mapping hierarchical beans

### ISSUE THREAD

**Issue by mnreddy7** [mapstruct/mapstruct#1416]
This is an extension to [this ](https://stackoverflow.com/questions/49570864/how-to-map-jaxb-elements-annotated-with-xmlseealso-using-mapstruct) question. 

```
class Customer{
  // distinct properties
}
class RetailCustomer extends Customer{
  // distinct properties
}

class WholeSaleCustomer extends Customer{
 // distinct properties
}

class CustomerDO {
 // String custType ; // flag used to determine if Customer is wholeSale or Retail
 //few properties same as Customer/WholeSaleCustomer/RetailCustomer
 // few distinct properties
}

@Mapper
public interface CustomerMapper{
           
           default Customer toCustomer(CustomerDO customerDO) {
                 String custType = customerDO.getCustType();
                if("W".equalsIgnoreCase(custType)){
                   return toWholeSaleCustomer(customerDO);
                  }
                 else {
                  return toRetailCustomer(CustomerDO);
                   }
           }
        @Mappings({
              @Mapping(source="a", target="b"),
               @Mapping(source="c", target="d"),
               @Mapping(source="m", target="m")
            })
         WholeSaleCustomer toWholeSaleCustomer(CustomerDO customerDO);

       @Mappings({
              @Mapping(source="e", target="f"),
               @Mapping(source="g", target="h"),
               @Mapping(source="n", target="n")
            })
         RetailCustomer toRetailCustomer(CustomerDO customerDO);
}
```
I need a one way mapping. I need to map from CustomerDO to WholeSaleCustomer/RetailCustomer based on **custType** flag in CustomerDO.  But this doesn't work. It gives me  "Ambiguous mapping methods found for mapping property " while compiling.  But if I change default method parameter to Object and remove either of toWholeSaleCustomer/toRetailCustomer, it works. But I want both. I've similar case for Service Bean. There are serveral child Services. I should be able to map them all whenever they are required

**Comment by filiphr** [comment]
@mnreddy7 I am going to say again please if you have question post them on StackOverflow or our forum. The issue tracker is not a place for questions.

I already answered this question in https://github.com/mapstruct/mapstruct.org/issues/75. You didn't provide any info more

**Comment by mnreddy7** [comment]
@filiphr I posted the question in detail [here](https://stackoverflow.com/questions/49657216/mapping-hierrachical-beans-using-mapstruct). I will be using stackover flow from now on. Your forum is blocked in our network.  Apologies for the inconvenience.

**Comment by filiphr** [comment]
No problem @mnreddy7 thanks for the understanding. I will answer your question in more detailed there. And I am sorry that you are having connection issues for our forum.
