### ISSUE TITLE
Update documentation about the latest gradle apt plugin

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1419]
Our current documentation uses the 0.8 version of the https://github.com/tbroyer/gradle-apt-plugin. However there are changes in how it should be used. We need to update our documentation and examples.

Additionally IntelliJ or Eclipse support does not come out of the box now. You have to apply the appropriate plugins for it.

**Comment by yokotaso** [comment]
@filiphr I made PR.If you will have free time, cloud you review it? 

https://github.com/mapstruct/mapstruct/pull/1518

**Comment by filiphr** [comment]
The PR has been merged. Thanks for the contribution @yokotaso
