### ISSUE TITLE
Support Gradle's upcoming incremental annotation processing feature 

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1420]
Gradle has added support for incremental compilation for annotation processors.  See https://github.com/gradle/gradle/issues/1320 and the [documentation](https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing) about it.

#1414 is just one step. With this issue the idea is to add the required bits in `META-INF` that Gradle needs to consider our annotation processor as capable of incremental compilation.

The only thing that we could cause a full rebuild is when the SPI files are generated. However, I think that this is rarely used. If there are some people that explicitly enable this via the property or are using a customized package or a custom name for the mappers with the default `componentModel` please let us know.

**Comment by oehme** [comment]
There is a workaround for people who use resource generation (until we support it) - disable incremental compilation.

**Comment by filiphr** [comment]
Thanks for the information. We should document this in our reference guide so our users know what to do in case they are triggering the resource generation. @oehme just for info at this moment Gradle will fail when a resource generation is tried right? You mentioned that you might relax this and trigger a full rebuild if resource is created through the `Filler` API. Is there an issue that we can track for this?

**Comment by oehme** [comment]
Yes, there is https://github.com/gradle/gradle/issues/4960

**Comment by eximius313** [comment]
Gradle 4.7 with support for `Incremental annotation processing` is going to be released tomorrow.
Can Mapstruct support it?

**Comment by filiphr** [comment]
@eximius313 we are in the process of adding this support. The only thing if that it would be a bit difficult for us to test this. Does someone know the best way to test it out? 

I am fairly certain that we would have this support in 1.3.0.Beta2 (latest)

**Comment by oehme** [comment]
@filiphr You can use the [Tooling API](https://docs.gradle.org/current/userguide/embedding.html#sec:embedding_quickstart) to run Gradle builds. You could then write a few tests where build an example project, make incremental changes and assert that the class file timestamps changed as expected.

**Comment by oehme** [comment]
Please note that the registration mechanism will change in 4.8 to be more flexible, as suggested by the AutoValue team. The META-INF based registration will be supported till 5.0, but be ignored after. See [this](https://github.com/gradle/gradle/pull/5255) PR to see the new mechanism in action.

Also, Gradle will no longer fail when you try to generate resources. Instead it'll just do a full recompile.

Is there anything else I can help with?

**Comment by filiphr** [comment]
Take https://github.com/gradle/gradle/issues/4915 and https://github.com/gradle/gradle/pull/5255 into consideration

**Comment by oehme** [comment]
Actually we backed out the change to registration, so the META-INF based way will stay for the long term. The documentation for 4.7 and 4.8-rc-2 are correct, disregard 4.8-rc-1.

**Comment by autonomousapps** [comment]
Any update on this?

**Comment by gunnarmorling** [comment]
Hey @filiphr, just learned about incremental annotation processing and was about to file an issue for it :) Did you have a chance already to look into this?

**Comment by filiphr** [comment]
> was about to file an issue for it :) 

Did you perhaps noticed it via the new GitHub features 😉?

> Did you have a chance already to look into this?

I had a small look. I think the most "heavy lifting" was done with #1414. The only thing left is to actually add that file so Gradle can pick it up. I haven't had time to look into that though (more from the perspective of testing that it works properly).

**Comment by oehme** [comment]
For testing you could use Gradle's tooling API to run a build, then change a file, run again and then assert which files were recompiled. That's how we do end to end testing for our incremental compiler at Gradle.

**Comment by gunnarmorling** [comment]
> Did you perhaps noticed it via the new GitHub features 😉?

Haha, yes, indeed. Very useful!

@oehme, thanks a lot for chiming in! Great advice. The challenge is to fully discover all files that impact a generated mapper. @filiphr I saw that in the linked PR you pass the mapper interface as originating element. I don't think that's enough, also base interface(s), config types and mapped source/target types (and their base types) impact a generated mapper, so I think we must pass all of them in order to ensure a mapper is recreated after any of these fails.

**Comment by gunnarmorling** [comment]
> I don't think that's enough, also base interface(s), config types and mapped source/target types (and their base types) impact a generated mapper

Ha, seems that's actually not needed, as Gradle takes care of all that as per its docs.

**Comment by oehme** [comment]
Yes, you only need to pass the causal element, i.e. the element that made you go "Oh, I need to generate a new file here". Everything reachable through that element's AST is already tracked by Gradle.

**Comment by gunnarmorling** [comment]
Gotcha. I was wondering though about the fact that passing multiple originating files will ause a ful re-build. Why is this? It seems that it might be the cause for problems should an AP wish to decide all originating files explicitly so to work in other environments that don't do that calculation automatically as Gradle does.

**Comment by oehme** [comment]
> It seems that it might be the cause for problems should an AP wish to decide all originating files explicitly so to work in other environments that don't do that calculation automatically as Gradle does.

That's a violation of the contract of `Filer`, which says in its JavaDoc that you should pass the "causal originating element", not other elements.

> I was wondering though about the fact that passing multiple originating files will ause a ful re-build. 

The "isolating" mode is a 1:1 mapping. Passing multiple elements would be a clear violation of this, as that would be a n:1 mapping. If there really are multiple causal element, the processor has to be "aggregating".

**Comment by gunnarmorling** [comment]
Ok, I understand your reasoning. It seems "package or module elements causally associated with the creation of this file" from the `Filer` docs is to be interpreted very strict in the sense, that only the element carrying the annotation triggering the file generation (`@Mapper`-annotated types in our case) are to be considered as "causally related". Makes sense I suppose. Thanks!

**Comment by oehme** [comment]
The JavaDoc is very succinct indeed. It wouldn't hurt if it contained some additional explanation. I find the following easier to understand: Ask yourself "If I remove this element, would I still generate the output file?" If the answer is yes, then this is not a causal element, but just some transitive dependency.

**Comment by remmeier** [comment]
not direclty this ticket, but related for incremental compilation & caching: it would still be good to address https://github.com/mapstruct/mapstruct/issues/1682 because any kind of versions and timestamps in the generated resources breaks the Gradle up-to-date mechanisms: same source should result in same output.

**Comment by imeszaros** [comment]
I added the metadata to my locally cached processor JAR (as isolating processor) and the first tests are promising. Incremental compilation works, and if I change a mapping file, the corresponding source file is regenerated and recompiled.

Is there an ETA on this? The latest IDEA version delegates build actions to Gradle by default, and causing a full rebuild even because of a single character change in a string is a bit annoying.

**Comment by ttzn** [comment]
Is anybody working on this ? This feature would be very nice to have. I managed to get a rudimentary Gradle test setup working for this but I need some guidance on where to

**Comment by ttzn** [comment]
Is anybody working on this ? I managed to get a rudimentary Gradle test setup working, but I need some guidance on how to organize the tests.

**Comment by filiphr** [comment]
That's some really good news @ttzn. Would be really good to have this in MapStruct.

* Not sure what the options for gradle are here. Is it somehow possible to point to the jar relatively? If needed I can help out with setting up the CI pipeline.
* Having a dedicated module might be the best approach here. Especially if it is a more complex setup

Anyways I would suggest that you push something to a branch of yours that we can have a look and then we can come up with ideas.

**Comment by ttzn** [comment]
Hey @filiphr, I just pushed https://github.com/ttzn/mapstruct/tree/1420-gradle-incremental, that should give us a start. I left some printlns to see what's going.
- it is indeed possible to point relatively, but right now I'm using a temp dir to run the Gradle build, so what I do is inject the absolute root mapstruct path from the test code into the build and lookup the jars in the Gradle script. This is all very file tree dependent, but so are the rest of the integration tests, so I'm not too worried about this.
- imho the setup needn't be too complex if all we need is to test this specific feature. When other Gradle-specific issues start to pile up I'll be more than happy to refactor this into something more generic.

**Comment by filiphr** [comment]
Just had a look at the branch @ttzn, looks really promising.

* That is completely OK for me
* Having a simple test setup from the start is fine

I have some questions:

*. Won't it make more sense to have actual getters and setters in the `Source` and `Target` classes? So that they can be valid in the MapStruct way?
* Maybe add another test when you change the `UnrelatedComponent` and verify that only that one is compiled

Would you like to create a PR with your branch, we can continue the discussion on the branch and eventually merge it

**Comment by ttzn** [comment]
I just made a pull request.

- Indeed it's a bit more realistic to have actual fields with getters and setters, even though it doesn't really make a difference for the incremental compiler. I added them to the test classes.
- I added that test case and some others.

**Comment by filiphr** [comment]
We now support the Gradle incremental annotation processing.

Thanks a lot to @ttzn for doing this as part of PR https://github.com/mapstruct/mapstruct/pull/1971
