### ISSUE TITLE
org.joda.time.LocalDate to java.time.LocalDate generated code has compilation error

### ISSUE THREAD

**Issue by abhijitkottur** [mapstruct/mapstruct#1425]
There is a compilation error on highlighted line as the object **dt** is being referred as a java.timeLocalDate whereas it should have been a org.joda.time.LocalDate. The import statement is incorrectly generated. 

Please let me know if there is another way of mapping between these dates or if I am missing something.

The generated code:

```
dto.setRequestedDeliveryDate( xmlGregorianCalendarToLocalDate( jodaLocalDateToXmlGregorianCalendar( entity.getRequestedDeliveryDate() ) ) );



private XMLGregorianCalendar jodaLocalDateToXmlGregorianCalendar( LocalDate dt ) {
        if ( dt == null ) {
            return null;
        }

        try {
            return DatatypeFactory.newInstance().newXMLGregorianCalendarDate(
                dt.getYear(),
                **dt.getMonthOfYear(),**
                dt.getDayOfMonth(),
                DatatypeConstants.FIELD_UNDEFINED );
        }
        catch ( DatatypeConfigurationException ex ) {
            throw new RuntimeException( ex );
        }
    }

private static java.time.LocalDate xmlGregorianCalendarToLocalDate( XMLGregorianCalendar xcal ) {
        if ( xcal == null ) {
            return null;
        }

        return java.time.LocalDate.of( xcal.getYear(), xcal.getMonth(), xcal.getDay() );
    }
```

**Comment by filiphr** [comment]
This has been fixed in PR #1442 on top of that all our templates now would generate a FQN or a simple name based on the type themselve (at the moment they were handwritten by us). Issues like this should no longer occur.

Thanks a lot to @chris922 for doing the fix and in general improving our entire built in template support
