### ISSUE TITLE
Any conflicts between aspectj-maven-plugin and mapstruct?

### ISSUE THREAD

**Issue by QigangZhong** [mapstruct/mapstruct#1426]
I bump into this problem that  I can't generate mapstruct impl classes and the aspect join point classes at build time in the same module. This drives me crazy, I don't know what happens inside, so I hope you  guys can give me some hints. 

I use aspectj-marven-plugin by following this sample:
https://github.com/yabqiu/maven-weave-aspectj

Appreciate for any help, thank you guys!

**Comment by sjaakd** [comment]
@QigangZhong .. can you check out closed issue:  #1257? Is it the same?

**Comment by QigangZhong** [comment]
Not exactly the same issue, I've searched a lot and tried the OP's solution, not working for me. I'll make a project to reproduce this problem when I got some time. Thank you @sjaakd , I'll be back soon.

**Comment by filiphr** [comment]
@QigangZhong is it not working from maven or IDEA? When you do like in the linked issue does maven work?

**Comment by sjaakd** [comment]
@QigangZhong .. is still an issue? Did you find a solution? I'm sure whether this is a MapStruct or aspectj problem
