### ISSUE TITLE
@Mapper(componentModel = "spring") doesn't support custom name for Spring Service Annotation

### ISSUE THREAD

**Issue by zurbergram** [mapstruct/mapstruct#1427]
Can't specify a name for the Spring Service annotation
If the interface definition something like

    @Mapper(componentModel = "spring", componentModelName = "cakeMapperV2")
     public interface CakeMapper{
         Cake map(Cupcake cupcake);
     }

     @Service("cakeMapperV2")
     public class CakeMapperImpl {
     }

**Comment by filiphr** [comment]
@zurbergram yes this is not possible in the moment out of the box.

However, there is a way for you to achieve what you are looking for with some internal customizations. We have an internal SPI [ModelElementProcessor](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/ModelElementProcessor.java) that adds the spring `@Component` annotation. The one for Spring is the [SpringComponentProcessor](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/SpringComponentProcessor.java).

What you can do is to define your own `ModelElementProcessor` that would be of a custom component model, provide your own marker annotation for the name of the component and you would be able to do what you are looking for.

Just keep in mind that this is an internal SPI, which means that we cannot guarantee backwards compatibility between versions. However, it is rarely changed.

**Comment by chris922** [comment]
Oups, sorry! I wasn't aware about the fact that changes in my forked mapstruct repo will directly be linked to this issue. Hopefully I haven't spammed you with too much notification mails.

@filiphr as my changes are now linked here maybe you could already take a look or should I create a PR? _(this is my more or less first 'real' OS contribution; right now I am waiting that the built finishs locally including all tests)_

I tried to add the possibility to have an extra annotation (`@MapperSpringConfig` / `@MapperJsr330Config`) to be able to have more component model specific configurations, e. g. if `@Service` or `@Component` should be used and - as requested in this ticket - to define an own bean name.

Maybe its better to extend the `@Mapper` configuration with a new property like `componentName`, but my idea was that there are maybe also other configuration things that only belongs to a special `componentModel` and having a special annotation for this could be helpful for those usecases.

**Comment by i-telligence-af** [comment]
> @zurbergram yes this is not possible in the moment out of the box.
> 
> However, there is a way for you to achieve what you are looking for with some internal customizations. We have an internal SPI [ModelElementProcessor](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/ModelElementProcessor.java) that adds the spring `@Component` annotation. The one for Spring is the [SpringComponentProcessor](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/SpringComponentProcessor.java).
> 
> What you can do is to define your own `ModelElementProcessor` that would be of a custom component model, provide your own marker annotation for the name of the component and you would be able to do what you are looking for.
> 
> Just keep in mind that this is an internal SPI, which means that we cannot guarantee backwards compatibility between versions. However, it is rarely changed.

I've tried your suggestion, but the Processor is not picked up by org.mapstruct.ap.MappingProcessor in method getProcessors() (v1.3.1.Final):
```
/**
     * Retrieves all model element processors, ordered by their priority value
     * (with the method retrieval processor having the lowest priority value (1)
     * and the code generation processor the highest priority value.
     *
     * @return A list with all model element processors.
     */
    private Iterable<ModelElementProcessor<?, ?>> getProcessors() {
        // TODO Re-consider which class loader to use in case processors are
        // loaded from other modules, too
        @SuppressWarnings("rawtypes")
        Iterator<ModelElementProcessor> processorIterator = ServiceLoader.load(
            ModelElementProcessor.class,
            MappingProcessor.class.getClassLoader()
        )
            .iterator();
        List<ModelElementProcessor<?, ?>> processors = new ArrayList<>();

        while ( processorIterator.hasNext() ) {
            processors.add( processorIterator.next() );
        }

        Collections.sort( processors, new ProcessorComparator() );

        return processors;
    }
```

I assume it's because my `ModelElementProcessor` is not in the same classloader as MappingProcessor. Am I doing something wrong?

**Comment by filiphr** [comment]
Just to share some info about how this can be done with some custom Spring `@ComponentScan`.

Let's say that we have the following:

```
package com.example.mapper.v1;

@Mapper
public interface CakeMapper {
}

package com.example.mapper.v2;

@Mapper
public interface CakeMapper {
}
```

Then your configuration can look like the following:

```
package com.example.mapper;

@Configuration
public class MapperConfig {

    @Configuration
    @ComponentScan(basePackages = "com.example.mapper.v1", nameGenerator = V1NameGenerator.class)
    public static class V1MapperConfig {
    
    }

    @Configuration
    @ComponentScan(basePackages = "com.example.mapper.v2", nameGenerator = V2NameGenerator.class)
    public static class V2MapperConfig {
    
    }

    protected static class V1NameGenerator extends PackageVersionNameGenerator {
        protected V1NameGenerator() {
            super("V1");
        }
    }

    protected static class V2NameGenerator extends PackageVersionNameGenerator {
        protected V2NameGenerator() {
            super("V2");
        }
    }

    protected static class PackageVersionNameGenerator extends AnnotationBeanNameGenerator {

        protected final String suffix;

        protected PackageVersionNameGenerator(String suffix) {
            this.suffix = suffix;
        }
            
        @Override
        protected String buildDefaultBeanName(BeanDefinition definition) {
            return super.buildDefaultBeanName(definition) + suffix;
        }
    }
}
```

**Comment by javanerd** [comment]
Hey @filiphr , i appreciate your solution because that's exactly what i was looking for....but, did you ever get this working?
In Spring Boot i get a ConflictingBeanDefinitionException although i followed your code parts. 

If you need further information what i was trying, please let me know. Perhaps my problem has something to do with order resolving or component scan issues?

**Comment by filiphr** [comment]
Hey @javanerd, yes I've used this solution in different projects and it works. 

For it to work you have to add `componentModel = "spring"` to your mappers, otherwise it there will be no components.

Most likely you have the `ConflictingBeanDefinitionException` problem because your mappers share a package with your Spring Boot Application. If that is the case then you have 2 options:

* Move your mappers to a different package that is not shared with your Spring Boot Application
* Play with `TypeExcludeFilter` so that you can exclude the mappers

**Comment by javanerd** [comment]
Finally, i got i working. As you said, @filiphr , i added `componentModel = "spring"` to my mappers and used a filter to exclude all of my mapper classes (the interface all of my mappers are implementing: MapperInterface.class) within the Spring Boot application. To my application class i added:

`@ComponentScan(basePackages = { "com.application.spring_boot_class" }, excludeFilters = {
		@ComponentScan.Filter(value = { MapperInterface.class }, type = FilterType.ASSIGNABLE_TYPE) })`

Hopefully, all of my remaining code is still working with this configuration.  ;-)

**Comment by dreameral** [comment]
Hello, is this issue for take?

**Comment by filiphr** [comment]
Adding this to 1.6 in order to be able to think of a solution that would work correctly with #1574

**Comment by jccampanero** [comment]
> Adding this to 1.6 in order to be able to think of a solution that would work correctly with #1574

@filiphr Please, could you elaborate the idea?

**Comment by filiphr** [comment]
With #1574 one can now write a mapper that looks like:

```java
@Mapper(componentModel = "spring")
@AnnotateWith(value = Component.class, elements = @Element(strings = "myCustomMapperName"))
public interface MyCustomMapper {

}
```

This will now generate

```java
@Component("myCustomMapperName")
@Component
public interface MyCustomMapper {

}
```

This is of course invalid.

What we need to do is to make sure that we are properly handling this, i.e. not adding the `@Component` in `AnnotationBasedComponentModelProcessor`.

We'll need to make sure that the following things work:

* Works properly with delegator
* Works properly when a different specialization of `@Component` is used. e.g. if `@Service` is used with `@AnnotateWith`

**Comment by jccampanero** [comment]
Thank you very much for your explanation @filiphr.

So, basically, it is necessary to finish the work already started on [this commit](https://github.com/Zegveld/mapstruct/commit/a1fcfd272c3327743a6a4a86414684729d9b4800), making sure it works properly with delegator and with other Spring related annotations, is that correct?

I will be glad to work in the issue if you wish.

**Comment by jccampanero** [comment]
Hi @filiphr.

It's nice talking to you again.

I have been working on the issue, I have provided a possible implementation mainly based on the code that you and @Zegveld developed.

I tried performing some initial testing of the decorator related stuff and it seems to work properly.

One question came to mind though: when using a decorator, if we have a component where we have a custom name, shouldn't be that name the one used in the generated `@Qualifier` annotation instead of the default `delegate`? In the present code, it works properly because of the precedence of the `@Qualifier` annotation but it is a common practice in Spring to qualify by the custom name provided when annotating the component or service.

I created a PR with the changes performed: please, feel free to ask me to change anything you think is appropriate.

Thank you very much.

**Comment by filiphr** [comment]
This was implemented using the new `@AnnotateWith`.

This means that the one can do:

```java
@AnnotateWith(value = Service.class, elements = @Element(strings = "cakeMapperV2"))
@Mapper(componentModel = "spring")
public interface CakeMapper{
     Cake map(Cupcake cupcake);
 }
```

And that will generate:

```java

 @Service("cakeMapperV2")
 public class CakeMapperImpl {
 }
```

**Comment by Factualdicky18** [comment]
@filiphr https://stackdev.space/questions/using-the-component-annotation-in-conjunction-with-a-qualifier
