### ISSUE TITLE
Disable Implicit Type Conversions

### ISSUE THREAD

**Issue by FatihErdem** [mapstruct/mapstruct#1428]
Hi,

I want to disable implicit type conversion. For example:

```
class MyDto {
    private String rate;
}
```

```
class MyResponse {
    private Float rate;
}
```

When I try to convert these two classes, MapStruct doesn't show any error and make automatic conversion between types even if field types are different. Is there any option to get build failure when field types doesn't match?

**Comment by sjaakd** [comment]
There is an old issue (still) that states that we should issue a warning in case of precision loss. Not solved yet. 

In order to circumvent this you can provide your own mapping method. 

Verstuurd vanaf mijn iPhone

**Comment by FatihErdem** [comment]
@sjaakd is there any easy way to do that? I have tens of classes which will use that mapper. Can you give me a little example?

**Comment by FatihErdem** [comment]
But I don't want to map if types are different. This isn't about only precision lost. In Selma mapper, if objects types are different then you can not compile the project. I am looking for this feature in MapStruct.

**Comment by filiphr** [comment]
@FatihErdem if you are referring to [Implicit type conversions](http://mapstruct.org/documentation/stable/reference/html/#implicit-type-conversions) that cannot be disabled at the moment. Why would you even want to do that? 

If you are talking about the automatic sub-mapping functionality where MapStruct automatically maps custom types as well. You can disable it by setting `@Mapper(disableSubMappingMethodsGeneration = true)`. Have a look at [Mapping object references](http://mapstruct.org/documentation/stable/reference/html/#mapping-object-references)

**Comment by filiphr** [comment]
I forgot to add until now no one has requested explicit disabling of the implicit type conversions. We have only received requests to add more stuff to it. The reason is that people don't want to define the boring method for mapping between `Integer` and `String` and rely on MapStruct to do that for them.

**Comment by FatihErdem** [comment]
@filiphr Yes, I am referring to implicit type conversion. I need these because :

For example I have a field "commissionRate". And this fields is BigDecimal in my entity. If I want to use "commissionRate", it must BigDecimal in all classes includes dtos, outputs and http responses. And developers make mistakes.  They sometimes forgets to make "commissionRate" to BigDecimal. Thus break my models. And I have hundreds of field like this. 

> people don't want to define the boring method for mapping between Integer and String

I don't want neither. In the project same fields must have same type. This decision made by the team.

I want to limit developer for object mapping. That's why I need to disable or workaround about implicit type conversion.

**Comment by filiphr** [comment]
@FatihErdem thanks for the clarification. I understand your requirement.

I have marked this with `up-for-grabs` in case someone from the community wants to do it. This is a low priority for us at the moment. In case you (@FatihErdem) or someone else wants to contribute this we can help you out

**Comment by filiphr** [comment]
The [`MappingResolverImpl`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java) is the place where the resolving is being done. More precisely the `getTargetAssignment` method.

There are 2 options to do this:
* Via the compiler options. See [`Options`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/option/Options.java). Which would be passed to the resolver. Then do a check (exclude of `buildInMethods`) in the appropriate `resolveViaXXX` methods.
* Add a property to the `@Mapper` and then pass this somehow to the `MappingResolver`

Not sure what the best approach for this would be to be honest.

**Comment by FatihErdem** [comment]
IMHO add property to the `@Mapper` would much easier to use. For example `disableImplicitTypeConversion` property better for documenting and using comparing to compiler option.

**Comment by zeeshan58** [comment]
Hi, what is the update on this issue? can I start working on it?

**Comment by filiphr** [comment]
Hey @zeeshan58,

I think that the consensus is to add this functionality as proposed by @sjaakd in https://github.com/mapstruct/mapstruct/issues/1428#issuecomment-381325860.

**Comment by filiphr** [comment]
Forgot to add, I think that you can work on it if you want to. Let us know if you need help on this.

**Comment by sjaakd** [comment]
Perhaps we should have more fine grained control by means of a strategy. Like no 2 step mapping, no type conversion/built-in

**Comment by PratikStar** [comment]
I found this thread searching for disabling troublesome implicit type conversions. Is this in development yet?

**Comment by filiphr** [comment]
Closing this since it can be done with the new `MappingControl` added in 1.4 as part of #695.

For this particular case it can be done by creating your own interface:

e.g.

```
@Retention(RetentionPolicy.CLASS)
@Experimental
@MappingControl( MappingControl.Use.DIRECT )
@MappingControl( MappingControl.Use.MAPPING_METHOD )
@MappingControl( MappingControl.Use.COMPLEX_MAPPING )
public @interface NoConversationMapping {
}
```

and then add that to the `mappingControl` in `@Mapping`, `@BeanMapping`, `@Mapper` or `@MapperConfig`.
