### ISSUE TITLE
Identify and remove performance bottlenecks

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#143]

**Comment by filiphr** [comment]
One performance bottleneck is #777, because we are using the default constructor to create a collection a lot is lost during the add operation to the collection.

**Comment by gunnarmorling** [comment]
Get in touch with the folks publishing perf numbers, suggesting to try out the new version.

**Comment by filiphr** [comment]
Another performance improvement is https://github.com/mapstruct/mapstruct/issues/1532

**Comment by sjaakd** [comment]
Shall we close this one and handle each improvement in its own merits? We have so many issues open its sometimes hard to prioritize. Also: performance measurement frameworks cover the performance of generated code. Thinking our loud: perhaps it's withering to have a separate module to run our unit test code and measure it.. setup threshold

**Comment by filiphr** [comment]
Agreed. We can close this one.

There is already https://github.com/arey/java-object-mapper-benchmark/ that contains benchmarks for multiple mapping frameworks, we are also in there.

**Comment by sjaakd** [comment]
Only point is that this is a very limited set. If we would somehow use our unit test for that purpose and control it ourselves....

**Comment by filiphr** [comment]
It is a bit difficult tobuse the unit test. Especially if we want to do it properly qith JMH and warmups and all the rest of the possibilities. We can do it in our own repo or a bew module that would be similar to the one I linked, but with much more tests
