### ISSUE TITLE
Add imports to @MapperConfig

### ISSUE THREAD

**Issue by andye2004** [mapstruct/mapstruct#1435]
I have a scenario where I am using an expression in a MapperConfig mapping and I am having to add an imports for the Mapper annotation of the interfaces using it (see below for an example). Without adding the imports to the actual mapper the import is not there and the code doesn't compile. This is despite the fact the expression is on the config.

I'd really like to see a feature added that means we can have an imports directly in the MapperConfig declaration. If there were positive feedback on the request I'd be happy to implement it.

Cheers, Andy.

Example

```java
@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG)
public interface Config {
    @Mapping(expression = "java( StringUtil.left(source.getText, 5) )", target = "text")
    OutObject map(final InObject source);
}

@Mapper(config = Config.class, imports = StringUtil.class)
public interface TextMapper {
    @Mapping(constant = "sometext", target = "outText")
    OutObject map(final InObject source);
}

@Mapper(config = Config.class, imports = StringUtil.class)
public interface TextMapper2 {
    OutObject map(final InObject source);
}

@Mapper(config = Config.class, imports = StringUtil.class)
public interface TextMapper3 {
    OutObject map(final InObject source);
}
```

**Comment by sjaakd** [comment]
@andye2004 : I don't think its good practice to use expressions in a `@MapperConfig`. You often end up referring to a parameter in a method in the class you annotated as `@Mapper` and troubleshooting why your code does not compile. Is there a reason you want to use expressions?

**Comment by sjaakd** [comment]
BTW: you know there's an `imports` on the mapper?

**Comment by andye2004** [comment]
@sjaakd Thanks for the response. There is a actually a business reason for wanting do what I've described but tbh it's pretty complicated to explain in detail. In essence I am trying map multiple third party entities onto internal representations. Pretty much all of the entities (third party and internal) extend off of a base class and as part of the mapping we need to truncate a string value so it has a maximum length and it is the truncate that is being called in the expression.

I do know that I can add an imports into the mapper, I actually put that in my example BUT to me there are three issues with this:

1. The imports keyword is now removed from the code where it is actually being used.
2. If anyone else starts to use the Config and forgets to add the import to the mapper then there will be a compile error. Not a biggy as it can be fixed of course.
3. I need to add the imports keyword to every mapper that uses the MapperConfig, even though they will have no further use for it themselves. It's the DRY principle I'm highlighting here and I have updated my example to hopefully better illustrate this.

**Comment by andye2004** [comment]
I'll watch this to see if it does come "up-for-grabs" / "good-first-issue". I'd be happy to look at it.

**Comment by filiphr** [comment]
Yes, @sjaakd it seems easy to implement.

@andye2004 feel free to have a look at it.

**Comment by sjaakd** [comment]
@andye2004  in principle you can take the `XYZStrategies` as an example how to do this.

**Comment by shoaib4330** [comment]
Is anyone working on this issue currently? if not, I'll like to be working on this.

**Comment by sjaakd** [comment]
nope go ahead..

**Comment by filiphr** [comment]
This issue has been implemented by @Zomzog and merged into master

**Comment by andye2004** [comment]
So sorry guys, I've been posted missing for a couple of months. @Zomzog many thanks for picking this up, much appreciated!
