### ISSUE TITLE
MapStruct not working in simple Entity -> DTO

### ISSUE THREAD

**Issue by MSChristian** [mapstruct/mapstruct#1441]
Hi, im new to MapStruct. In an effort to use it i tried to build a simple conversion from Entity to DTO:

CocheEntity.clas:

![image](https://user-images.githubusercontent.com/22235940/39017500-c08e62ca-4423-11e8-839f-0e0756e3bc9a.png)

CocheDTO.class:

![image](https://user-images.githubusercontent.com/22235940/39017538-d2acb556-4423-11e8-8c17-95c89fd4dbcb.png)

CocheMapper:

![image](https://user-images.githubusercontent.com/22235940/39017581-e995ac64-4423-11e8-8f5a-798083c22126.png)

After compiling i went to the compiled files and this is what i found:

![image](https://user-images.githubusercontent.com/22235940/39017645-1b59acf0-4424-11e8-951a-7bf7de0b52da.png)

Maybe i missing something, if someone need more information in order to help , ill provide it. Thanks

**Comment by filiphr** [comment]
How does your maven or gradle setup looks like? Which version of MapStruct and Lombok are you using?

**Comment by MSChristian** [comment]
Hi @filiphr 
Solved the problem changing the maven-compiler version. Im using Java 9 , upgrading the  maven-compiler to 3.7.0 solved the problem.

Thank you.
