### ISSUE TITLE
Cyclic Graph Mapping not working

### ISSUE THREAD

**Issue by elapp** [mapstruct/mapstruct#1444]
Hi,

I am trying to use mapstuct for my Entity to DTO conversions, and stuck at cyclic mapping of attributes.

Error: Caused by: java.lang.StackOverflowError

My entity has a @ManyToOne mapping.

I tried using the solution mentioned @ [Cyclic Issue](https://github.com/mapstruct/mapstruct/pull/911)

Can somebody help in identifying where am I going wrong? 

As suggested I have created CycleAvoidingMappingContext

```
public class CycleAvoidingMappingContext {
    private Map<Object, Object> knownInstances = new IdentityHashMap<Object, Object>();

    @SuppressWarnings("unchecked")
	@BeforeMapping
    public <T> T getMappedInstance(Object source, @TargetType Class<T> targetType) {
        return (T) knownInstances.get( source );
    }

    @BeforeMapping
    public void storeMappedInstance(Object source, @MappingTarget Object target) {
        knownInstances.put( source, target );
    }

}
```
My Parent Entity Looks like

```
@Entity
public class PEntity extends BaseEntity implements Serializable {

	private static final long serialVersionUID = 6377548296743868678L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	.
	.
	.
	attributes
	.
	.
	.
	
	
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	private CEntity centity;

}

```
and Child Entity Looks like

```
@Entity
public class CEntity extends BaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5716282847063008562L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	.
	.
	.
	attributes
	.
	.
	.
	
	@OneToMany(mappedBy="centity")
	private List<PEntity> pEntityList;
	

}
```

The DTO attributes looks exactly the same as in entity
The mapper being used is 
```
@Mapper(config = MapConfig.class, uses = CycleAvoidingMappingContext.class)
public interface EntityToDaoMapper extends CommonMapper {

	PDto map(PEntity obj);

	CDto map(CEntity obj);

}
```

**Comment by filiphr** [comment]
Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/mapstruct) or [gitter](https://gitter.im/mapstruct/mapstruct-users) channel for questions.

In any case have a look at [mapstruct-mapping-with-cycles](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-mapping-with-cycles) in our examples repo that does exactly what you are looking for.


For your case you need to use `@Context` to pass the context.

```java
@Mapper(config = MapConfig.class)
public interface EntityToDaoMapper extends CommonMapper {

	PDto map(PEntity obj, @Context CycleAvoidingMappingContext context);

	CDto map(CEntity obj, @Context CycleAvoidingMappingContext context);

}
```
