### ISSUE TITLE
Support for lifecycle methods on type being build with builders

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1454]
Currently we only support lifecycle methods on for a single type.

This issue is to expand that so the lifecycles are invoked for the type being build.

Example. We have `Person` with `PersonBuilder`.

The following lifecycle methods are / should be invoked:

- [x] `@BeforeMapping` with no parameters
- [ ] `@BeforeMapping` with `@TargetType` `Person`
- [x] `@BeforeMapping` with `@TargetType` `PersonBuilder`
- [x] `@BeforeMapping` with `@MappingTarget` `PersonBuilder`
- [x] `@AfterMapping` with no parameters
- [ ] `@AfterMapping` with `@TargetType` `Person`
- [x] `@AfterMapping` with `@TargetType` `PersonBuilder`
- [ ] `@AfterMapping` with `@MappingTarget` `Person`
- [x] `@AfterMapping` with `@MappingTarget` `PersonBuilder`
- [x] `@AfterMapping` with `@MappingTarget` `PersonBuilder` and returning `Person`

**Comment by andrei-ivanov** [comment]
Any chance to get this one completed? 😩
