### ISSUE TITLE
source presence tracking for a list

### ISSUE THREAD

**Issue by birdfriend** [mapstruct/mapstruct#1455]
Hi, 

We want to use source presence tracking when mapping a list. For example:

//source object
```
public class Source {
  private String name;
  private List<String> urls;
  //getters and setters....
}
```

//destination object
```
public class Target {
  private String name;
  private List<String> domains;
  private Set<String> hasFieldSet = new HashSet<>();
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
    hasFieldSet.add("name");
  }
  public List<String> getDomains() {
    return domains;
  }
  public void setDomains(List<String> domains) {
    this.domains = domains;
  }
  public Boolean hasName() {
    return hasFieldSet.contains("name");
  }
  public Boolean hasDomains() {
    return hasFieldSet.contains("domains");
  }
}
```

//mapper
```
@Mapper(
  nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS
)
public interface TestMapper {
  @Mapping(source = "urls",target = "domains")
  Target testMap(Source var1);
}
```

When mapping a source object to a target object, we don't want to call the setter if the field is not present in the source object. However, it looks like the setter for `domains` in the target object is always called.

The generated code is:
```
public Target testMap(Source source) {
    if(source == null) {
      return null;
    } else {
      Target target = new Target();
      if(source.hasUrls().booleanValue()) {
        List<String> list = source.getUrls();
        target.setDomains(new ArrayList(list));
      } else {
        target.setDomains((List)null); //can we not call the setter if urls are not present in the source?
      }
      if(source.hasName().booleanValue()) {
        target.setName(source.getName());
      }
      return target;
    }
  }
```
Why do we have different behaviors for a list and primitive type here? For a list, such as `domains` field, can we not call the setter if the source is not present? Thanks!

**Comment by filiphr** [comment]
Sorry for not responding earlier @birdfriend. What you are looking for is https://github.com/mapstruct/mapstruct/issues/1306. It has nothing to do with the fact that you are using presence checking. Once the linked issue is fixed this would work properly for you as well, therefore I am closing this as a duplicate
