### ISSUE TITLE
Introduce mechanism to report error from MappingResolver

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1458]
Is needed for

- [x] The solution for #1401
- [ ] The solution for #5

**Comment by filiphr** [comment]
@sjaakd now that we merged #1466 should we close this?

**Comment by sjaakd** [comment]
> @sjaakd now that we merged #1466 should we close this?

No.. #5 also requires such mechanism.. its not fully implemented yet.

**Comment by filiphr** [comment]
>No.. #5 also requires such mechanism.. its not fully implemented yet.

Good was not sure. I updated the the original message with checkpoints so we can track it better 😄

**Comment by sjaakd** [comment]
done.. position hint is available in `MapperResolverImpl`, partial message as well. Used in #5
