### ISSUE TITLE
String to enum conversion: Compile error in generated mapper

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct#1460]
Today we found a new bug in MapStruct 1.2.0:

We had a bean with a String property which was mapped to a different bean where the same property is an enum.
String to enum is totally fine, but: The enum (E1) had the same class name as a different enum (E2) that was referenced in the same mapper.

The generated class imported the E2, but is using the simple name of E1 in the String to E1 mapping.

A bit complicated to describe, but I already analyzed this and will provide a PR as soon as possible. 

I guess it is the correct way to first create an issue and then a PR with the fix or would it be okay to do this without an issue?

Best regards,
Christian

**Comment by sjaakd** [comment]
Hi Christian,

Just add a good reproducer as unit test to your pr. There are examples in unit test how to do this: reference this issue number in the package name and in issue key annotation. That is sufficient.

Good luck,
Sjaak

**Comment by chris922** [comment]
Hi Sjaak,

I guess you are referring to the `@IssueKey` annotation? I already saw and used it. But what is this exactly doing? When creating the release notes? reports? Or where is it used?


PS: Will be a bit more effort than expected. Issue was again that a simple name and not FQN was used; I will not only fix exactly this issue but also other similar issues that could occur for nearly all of those `SimpleConversion` classes.

**Comment by soberich** [comment]
@chris922  not only enum to enum.
If any other class has the same SimpleName as another enum/class used in same mapper it will use E1.
I've experienced that, had to rename one of the classes.

**Comment by filiphr** [comment]
@soberich this would be fixed by the #1461 PR from @chris922
