### ISSUE TITLE
[IMPROVEMENT] Generate collection elements mapping (e.g. Nested<->NestedDTO) automatically when ADDER_PREFFERED same way as now when ACCESSOR_ONLY picked

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1472]
Hi, 
I just want to emphasize this one, as it happens that when `ACCESSOR_ONLY`, for example, is used then this mapping method(s) generated automatically with no problem.
But when `ADDER_PREFFERED` it requires this to be (at least) declared with an error
```
Can't map property "java.util.List<com.example.Entity> entities" to "com.example.DTO dtos". 
Consider to declare/implement a mapping method:
"com.example.DTO map(java.util.List<com.example.Entity> value)"

```
BTW, notice it asks for mapping from plural (iterable) to singular (non-iterable) while, nevertheless declaring singular to singular mapping satisfies this requirement and compilation passes fine.

I emphasize because even when switching between the two during development should be transparent and now it fails (moving config to ADDER_PREFFERED from other config property).
If this issue redundant close, or whatever.
Thanks.

**Comment by soberich** [comment]
Duplicate https://github.com/mapstruct/mapstruct/issues/1477

**Comment by filiphr** [comment]
@soberich sorry for not picking this up. This issue was newer then the one I created, but I missed this one.
