### ISSUE TITLE
Nullptr.. Need to investigate..

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1476]
nl/bro/dao/ep/epl/impl/DtoToEntityCreateMapper.java:[31,17] Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.model.source.SourceReference.copyForInheritanceTo(SourceReference.java:333)  	at org.mapstruct.ap.internal.model.source.Mapping.copyForInheritanceTo(Mapping.java:456)  	at org.mapstruct.ap.internal.model.source.MappingOptions.applyInheritedOptions(MappingOptions.java:279)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.mergeInheritedOptions(MapperCreationProcessor.java:452)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:274)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:80)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:158)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	at com.sun.tools.javac.main.Main.compile(Main.java:523)  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)  	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)  
2 errors

**Comment by filiphr** [comment]
@sjaakd it's not your first time 😄. Isn't this a duplicate of #1180?

**Comment by sjaakd** [comment]
Ah.. but I got a reproducer now. I stopped immediately when I found out and went home.. could also be that the weather played a certain part there 😉. Anyway, tonight I'll try on the snapshot tonight..

**Comment by filiphr** [comment]
>Ah.. but I got a reproducer now.

Hahaha, that's awesome. I think you can update both and close one once you know more :)

**Comment by sjaakd** [comment]
hmm. I tried it.. but problem disappeared somehow.. But you're right.. I'll close this one. Tomorrow I'll unpack the 1.2 code to see which line it is..

**Comment by filiphr** [comment]
>hmm. I tried it.. but problem disappeared somehow..

Magic
