### ISSUE TITLE
Adder wrapper should use singular from the source for the iterable element

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1478]
Currently generated code:

```

 if ( ptacObject.getCustomers() != null ) {
    for ( CustomerInfo customersList : ptacObject.getCustomers() ) {
        builder.addCustomers( map( customersList ) );
    }
}

if ( ptacObject.getBrokers() != null ) {
    for ( String brokersList : ptacObject.getBrokers() ) {
        builder.addBrokers( brokersList );
    }
}
```
Example code can be found [here](https://github.com/pascalwhoop/grpc-adapter)

**Comment by sivviswa22** [comment]
Hi, I would like to try this one. 
So is the fix here renaming of the for loop object names from
customersList --> customer and brokersList --> broker ?

**Comment by sjaakd** [comment]
@sivviswa22 not sure.. @filiphr : could you enlighten us?

**Comment by filiphr** [comment]
@sivviswa22 yes the "fix" would be to have such rename. I have something locally for this though. It needed something more to be added and I am not 100% certain in the solution. I can push it if you want to have a look

**Comment by filiphr** [comment]
@sivviswa22 the example is in this PR https://github.com/mapstruct/mapstruct/pull/1634
