### ISSUE TITLE
Wrong builder method is selected when Protobuf is used

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1479]
Protobuf has mutliple public parameterless methods that create the type in the builder:

* `getDefaultInstanceForType`
* `build`
* `buildPartial`

Currently we pick `getDefaultInstanceForType` without any error. This is clearly a mistake and we should either:

* not pick any and error out so the user can define a custom SPI that would pick the correct
* provide a custom SPI for Protobuf that would pick the `build` method.

An example code can be found [here](https://github.com/pascalwhoop/grpc-adapter). The `CompetitionMapper` can be adjusted to map into `PBCompetition` instead of `PBCompetition.Builder`

**Comment by chris922** [comment]
What if a custom SPI would be provided for Protobuf and this will be selected? Maybe other builders will not work anymore except this SPI still supports those things?

I would like to throw in two other ideas:
1. Add a possibility that the user can configure which method should be used based on annotations? e. g. defining a new annotation `@Builder(buildMethod = "build")` that can be placed at the mapping method or a new attribute in `@Mapper` / `@MapperConfig`
2. In case a method within the mapper or mapperconfig was defined that accepts the builder as an input and is returning the the object this one will be called.
    
    Example:
    ```java
    public Message buildMessage(Message.Builder builder) {
      return builder.build();
    }
    ```
    Generated code:
    ```java
    public Message map(Source source) {
      // ... create builder, set values ...
    
      return buildMessage(sourceBuilder);
    }
    ```

**Comment by filiphr** [comment]
>What if a custom SPI would be provided for Protobuf and this will be selected?

That is doable. We are already doing that with Immutables. There are some other Protobuf specifics that we can support ootb. Also it is not that complex to check if the type is a protobuf type and use something special there.

For the other ideas:

1.  This one is a bit complex due to the way the things are wired within MapStruct. The creation of types (where the Builder is searched for) is separated of the mappers. If you have an idea how this can be achieved please share it 😄 
1. This actually is a really nice idea. Maybe it can be done with `@AfterMapping` in #1454. Currently it is possible to return do a return from `@AfterMapping` or `@BeforeMapping`. So in your example it would be something like:

```
@AfterMapping
public Message buildMessage(Message.Builder builder) {
  return builder.build();
}
```

And then the generated code would be:

```
public Message map(Source source) {
  // ... create builder, set values ...

  Message target = builderMessage(sourceBuilder);
  if (target != null) {
    return target;
  }
  return sourceBuilder.finish();
}
```

**Comment by wenerme** [comment]
Also working on this, https://github.com/wenerme/mapstruct-extras 

For protobuf, I hope mapstruct just ignore them , allowed using the spi to handle them.

This is how I add the builder ObjectFactory
https://github.com/wenerme/mapstruct-extras/blob/master/proto-processor/src/main/java/com/github/wenerme/mapstruct/ProtobufMethodCreationProcessor.java#L59

**Comment by chris922** [comment]
@filiphr so what about implementing your first idea (error message) with a hint about the possible solution (`@AfterMapping` that calls `build`)? And, if not already available, things like this should be available in the reference documentation.

**Comment by filiphr** [comment]
The `@AfterMapping` that calls `build` is not supported yet. 

I think we need both. Do you want to give it a go @chris922? 

For the first one I think that we could add something to the `BuilderInfo` or throw an exception and handle it somewhere.
For the second one something similar like the Immutables support should be sufficient.

@wenerme just for info, that what you are doing there is using an internal API from MapStruct and might break in any version (just a small precaution)

**Comment by wenerme** [comment]
@filiphr I hope mapstruct expose more internal stable spi, can't find another way around, but have to solve the problem.

**Comment by pascalwhoop** [comment]
@wenerme well I think it's pretty clear right now. Return a `ProtobufType.Builder` and then write either an `@AfterMapping` or a `default ProtobufType build(OriginalType t){return map(t).build();}`

Long term, yes, MapStruct should offer to Map to a built protobuf message and choose the right return type. but it *can* work today, just a bit more hand-written boilerplate.

**Comment by chris922** [comment]
@filiphr I enhanced the `MappingContext` for the builder lifecycle tests with this `@AfterMapping`

```java
@AfterMapping
public Order afterWithBuilderTargetReturningTarget(OrderDto source, @MappingTarget Order.Builder orderBuilder) {
    invokedMethods.add( "afterWithBuilderTargetReturningTarget" );

    return orderBuilder.create();
}
```

And it works. So is there really something missing to support creating an `@AfterMapping` annotated method that calls the correct `build` method like your example?
Looks for me like we only need to provide the error message in case multiple build methods are available?

Generated code:
```java
Order target = context.afterWithBuilderTargetReturningTarget( source, order );
if ( target != null ) {
    return target;
}

return order.create();
```

**Comment by filiphr** [comment]
I think that with #1498 this should be resolved. I went for throwing an exception in case there are multiple builder creation or build methods. 

However, in case of multiple build methods then they are filtered for a method called `build` if such method exists, that one would be used, otherwise the exception is thrown.

**Comment by filiphr** [comment]
PR has been finally merged. Sorry that it took some time.

The final solution allows builders to have multiple build method and if such case is found then we are going to look for a method named `build` and use it. In case no method is named `build` than there will be an error. 

One can use `@Builder(buildMethod = "create")` from within `@BeanMapping`, `@Mapper` or `@MapperConfig` to configure this. If `@Builder` is defined and no method that matched the `buildMethod` is found than there will be a compilation error.
