### ISSUE TITLE
In 2.0 we should support `Default` as qualifier

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1483]
Because now non annotated methods will also be selected, even though `qualifiedBy` is specified.

**Comment by filiphr** [comment]
Is this adding some new annotation or something else? I don't quite understand the issue 😄

**Comment by sjaakd** [comment]
well.. I need to check myself still what I conjured up in the past. Its some time ago, but it seems that 
1) if you add a method, 
2) and also a method with qualifier, 
3) specify the `qualifiedBy` with said qualifier..
both methods qualify. 

CDI has the concept of `Default` to resolve this.. But again.. I need to add a reproducer. Perhaps I'm mistaken. So I'll assign it to myself.

**Comment by filiphr** [comment]
I'm not familiar with CDI (more of a Spring guy myself 😀). If it makes sense in that regard than its fine.

In any case methods that are annotated woth qualify (should) never be candidates without `qualifiedBy`, and if you use qualifiedBy we should not pick another method.

An important thing is the qualifier to be from MapStruct (I inow that there is one in CDI and that might cause an issue)

**Comment by sjaakd** [comment]
I tried one of the examples. Can't reproduce it..  Will re-open when I can..
