### ISSUE TITLE
How can I customize conversion ?

### ISSUE THREAD

**Issue by wenerme** [mapstruct/mapstruct#1484]
The Conversions is not extendable, I want to add conversion for Immutable to Builder or Builder to Immutable.

**Comment by wenerme** [comment]
It's very annoying that the creation context is unable to extend, between the SourceMethod and Mapper, should contain one more process the add extra extensions. Current spi is very limited, even add a ModelElementProcessor can only do a litter things, can not add extra generated method or assignment.

**Comment by wenerme** [comment]
Maybe this can fix the problem https://github.com/mapstruct/mapstruct/issues/782 but have to wait 1.3.0 beta

**Comment by filiphr** [comment]
@wenerme why do you need to extend the `Conversions`. You can easily add a [Custom mapping method](http://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods) and MapStruct will use that method. Keep in mind that the method can be in a different class. See [Invoking other mappers](http://mapstruct.org/documentation/stable/reference/html/#invoking-other-mappers).


I am going to close this as I think that one can easily add custom methods via other mappers. If you think this is not the case we can reopen this

**Comment by wenerme** [comment]
I was writing a plugin for mapstruct, https://github.com/wenerme/mapstruct-extras ,to support the builder <-> message convert, I want to extend the internal `Conversions` , that's the most convenient way.
