### ISSUE TITLE
Edge-Case: private inner Enum issue

### ISSUE THREAD

**Issue by pascalwhoop** [mapstruct/mapstruct#1485]
Sample repo: [here](https://github.com/pascalwhoop/grpc-adapter)

When Class A is mapped to class B and class A has an enum property where the enum is privately owned by class A, the generated code is not compilable:

```java
public class PowerType
{
  private enum TypeLabel {
  CONSUMPTION,
  //...
  ELECTRIC_VEHICLE
  }

  //...
  private TypeLabel label;

  @Override
  public String toString ()
  {
    return label.toString();
  }
```

with the following mapper:

```java
@Mapper(uses = BuilderFactory.class,
    collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED,
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface PowerTypeMapper
{
  PowerTypeMapper INSTANCE = Mappers.getMapper(PowerTypeMapper.class);

  @Mappings({
      @Mapping(target = "label", ignore = true)
  })
  PBPowerType map(PowerType in);


  @Mappings({
  })
  PowerType map(PBPowerType in);


  class BuilderFactory
  {
    @ObjectFactory
    PowerType build(PBPowerType in)
    {
      return PowerType.valueOf(in.getLabel());
    }

    @ObjectFactory
    PBPowerType build(PowerType in)
    {
      return PBPowerType.newBuilder().setLabel(in.toString()).build();
    }
  }
}
```

all is well. Notice the "label ignore". If this is skipped, the generated code is faulty:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-05-08T12:45:51+0200",
    comments = "version: 1.3.0-SNAPSHOT, compiler: javac, environment: Java 1.8.0_162 (Oracle Corporation)"
)
public class PowerTypeMapperImpl implements PowerTypeMapper {

    private final BuilderFactory builderFactory = new BuilderFactory();

    @Override
    public PBPowerType map(PowerType in) {
        if ( in == null ) {
            return null;
        }

        Builder pBPowerType = PBPowerType.newBuilder();

        if ( in.getLabel() != null ) {
            // EEEEEEEEEERRGGGH
            pBPowerType.setLabel( in.getLabel().name() );
        }

        return pBPowerType.getDefaultInstanceForType();
    }

    @Override
    public PowerType map(PBPowerType in) {
        if ( in == null ) {
            return null;
        }

        PowerType powerType = builderFactory.build( in );

        return powerType;
    }
}
```

the `in.getLabel().name()` causes an access error.

**Comment by pascalwhoop** [comment]
There's something wrong with my example (it's still calling `getDefaultInstanceForType` at the end which is obviously wrong and relates to #1479 . I'm investigating and will update once I have a workaround so we can discuss what's the best approach here.

**Comment by filiphr** [comment]
Good catch @pascalwhoop.

In any case if `PowerType` is [this](https://github.com/powertac/powertac-core/blob/master/common/src/main/java/org/powertac/common/enumerations/PowerType.java) then there is no public getter for `label`, so I am a bit confused how MapStruct even creates that getter.

I am also not entirely sure how this can be fixed by us. As MapStruct performs mappings for public getters. And if you have a private getter / setter you should not return that private type as anyone calling that method will have problems.

**Comment by pascalwhoop** [comment]
sorry I should have mentioned that. I added that getter manually on my local machine but because I have no control over the snapshot release cycle of the simulation it's WOMM for now ...

**Comment by filiphr** [comment]
Thinking a bit more about this I think that this is not really a bug in MapStruct as if you expose a private class into a public method you can't do anything with it (and you really shouldn't).

```
public class Dummy {

    private Me me;

    public Me getMe() {
        return me;
    }

    public void setMe(Me me) {
        this.me = me;
    }

    private enum Me {
        TEST,
        SOME
    }
}
```

You can't do anything with `getMet()` not even call `toString()` on it from outside of `Dummy`. I would say that methods exposing some type should have the same visibility as the type being exposed,

**Comment by filiphr** [comment]
Closing this since in my opinion classes that are exposed via `public` methods should be accessible to the callers.
