### ISSUE TITLE
Mapstruct 1.20 generating classes based on interface created but not able to Use it

### ISSUE THREAD

**Issue by msaifally** [mapstruct/mapstruct#1487]
Hello Friends i am new to spring boot and have searched for almost 3 days , but did not find a concrete solution. i am trying to implement mapstruct 1.20 in my spring boot project but the problem is that i can't access the classes that have been generated after i perform **MVN CLEAN INSTAL**L 

This is  the and plugin and dependency that i have added based on its documentation at
 http://mapstruct.org/documentation/installation/
**<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-jdk8</artifactId>
			<version>1.2.0.Final</version>
</dependency>**
 but when i use @Autowired of my MapperInterface in my service class i get the following error
@Service
public class UserService {
	

	
@Autowired
UserMapper userMapper;
UserService(){
	
}

}
![image](https://user-images.githubusercontent.com/19793302/39879713-a4d03828-548c-11e8-9018-f3965861041d.png)

This image below show the structure of my project with my interface being generated

![image](https://user-images.githubusercontent.com/19793302/39879934-3909750e-548d-11e8-97e7-cb4659a6e6e8.png)

And finally the solution that i came across tells me to  make sure that "target/generated-sources" is linked as a source folder in Eclipse.But this does not work
link: https://stackoverflow.com/questions/32609755/mapstruct-generated-class-not-being-injected-by-spring-in-jhipster-web-app
 
Thanks in advance  :D

**Comment by filiphr** [comment]
Just to be sure you are using the `spring` `componentModel` in your `@Mapper`?

I am not an Eclipse user, but from your screenshots it seems that the the generated sources are not in `target/`

**Comment by filiphr** [comment]
Have you read http://mapstruct.org/documentation/ide-support/#maven-integration as well? You need to set 

```xml
<properties>
  <!-- automatically run annotation processors within the incremental compilation -->
  <m2e.apt.activation>jdt_apt</m2e.apt.activation>
</properties>
```

in your `pom.xml` so Eclipse can pick the annotation processors from maven

**Comment by msaifally** [comment]
Hello @filiphr
The generated sources is in the target/ as well. it appears like this in the screenshot because i have link the generated sources to the source folder . 
I did not  this part of the documentation, After adding it to my **pom,xml** now it's working fine.
Thank you a lot .

**Comment by msaifally** [comment]
Hello @filiphr
The generated sources is in the target/ as well. it appears like this in the screenshot because i have link the generated sources to the source folder .
I did not this part of the documentation, After adding it to my pom,xml now it's working fine.
Thank you a lot .
