### ISSUE TITLE
version 1.2.0.Final did not generate source properly

### ISSUE THREAD

**Issue by namson0482** [mapstruct/mapstruct#1491]
Hi All,

I use mapstruct 1.2.0.Final but it did not generate source properly. But if i use version 1.1.0.Final then it is ok. Who can tell me root cause. My configuration are as per below

![image](https://user-images.githubusercontent.com/2830607/39972816-bcfa1afc-5740-11e8-92be-c53ab6ba32da.png)

**Comment by filiphr** [comment]
What do you mean it didn't generate source properly? Can you share your mappers and the generated code?

**Comment by namson0482** [comment]
If i use mapsruct version 1.1.0.Final then it can generate source like image below
![image](https://user-images.githubusercontent.com/2830607/39996372-72d4353e-57a9-11e8-8bf0-233c537faff5.png)


But if i use version 1.1.2.Final in pom.xml then it cannot generate source like above
![image](https://user-images.githubusercontent.com/2830607/39996422-9dc9e504-57a9-11e8-8243-cbb6403d0d81.png)

**Comment by filiphr** [comment]
`1.1.2.Final` does not exist. Are you sure you are using `1.2.0.Final`. There is no reason why it should not work, this are basic maven configurations

**Comment by namson0482** [comment]
Yes, I use 1.1.2.0.Final version. Do you have any advices for me?

**Comment by filiphr** [comment]
Again such version (1.1.2.0.Final) does not exist. Can you share with us the pom?

**Comment by namson0482** [comment]
My pom file as per below

<?xml version="1.0" encoding="UTF-8"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.panasonic.healthcare</groupId>
	<artifactId>pfm-service-device</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.1.RELEASE</version>
		<relativePath /> 
	</parent>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<docker.registryHost>base-docker-registry:5000</docker.registryHost>
		<docker.currentTag>dev-01172016-1200</docker.currentTag>
		<common-utility.version>0.0.1-SNAPSHOT</common-utility.version>
		<common-domain.version>0.0.1-SNAPSHOT</common-domain.version>
		<mapstruct.version>1.2.0.Final</mapstruct.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-ldap</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-security-core</artifactId>
					<groupId>org.springframework.security</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.panasonic.healthcare</groupId>
			<artifactId>pfm-common-lib-utility</artifactId>
			<version>${common-utility.version}</version>
		</dependency>
		<dependency>
			<groupId>com.panasonic.healthcare</groupId>
			<artifactId>pfm-common-lib-domain</artifactId>
			<version>${common-domain.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.4.13</version>
				<configuration>
					<imageName>${docker.registryHost}/${project.artifactId}</imageName>
					<dockerDirectory>src/main/docker</dockerDirectory>
					<dockerHost>http://20.203.133.155:4444</dockerHost>
					<resources>
						<resource>
							<targetPath>/</targetPath>
							<directory>${project.build.directory}</directory>
							<include>${project.build.finalName}.jar</include>
						</resource>
					</resources>
					<imageTags>
						<imageTag>${docker.currentTag}</imageTag>
					</imageTags>
					<pushImage>true</pushImage>
				</configuration>
			</plugin>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-compiler-plugin</artifactId>
			    <version>3.7.0</version>
			    <configuration>
			        <source>1.8</source>
			    	<target>1.8</target>
			        <annotationProcessorPaths>
			            <path>
			                <groupId>org.mapstruct</groupId>
			                <artifactId>mapstruct-processor</artifactId>
			                <version>${mapstruct.version}</version>
			            </path>
			        </annotationProcessorPaths>
			    </configuration>
			</plugin>
		</plugins>
	</build>
</project>

Above file is main project. we also get 2 dependence projects. In those, we put 


<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>${mapstruct.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-jdk8</artifactId>
			<version>${mapstruct.version}</version>
		</dependency>

**Comment by filiphr** [comment]
Have you read the [Eclipse Maven integration](http://mapstruct.org/documentation/ide-support/#maven-integration) on our website? I don't see ` <m2e.apt.activation>jdt_apt</m2e.apt.activation>`

**Comment by namson0482** [comment]
Even i put m2e.api.activation property but it still not generate source code. Do you have any other advices to give me?

**Comment by filiphr** [comment]
@namson0482 it is `m2e.apt.activation` property. In any case I don't have any other advice to give to you. I personally am an IntelliJ user. 

There are other Eclipse users and no one has had a problem with this for now. Therefore, I am going to close this one. In case you think that there is something that we need to do on our side we can reopen it
