### ISSUE TITLE
Map Enum with toString() and not name()

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1492]
I stumbled upon that mapstruct uses `name()` instead `toString()`
I understand that in may be one way but not the reverse if to use `toString()`, but this is exactly why this method was put there by Josh Bloch or other JDK developers to allow that to become on developer's responsibility to handle custom conversion if he want's to do so. Also regarding that in a very rare cases projects has lots of `Enum::toString()` methods overridden, unless they have a very good reason for that (and otherwise non-overridden method would produce exact same output), I believe `toString()` is the only method should be used, so that if the team wants to use that it becomes its responsibility to handle reverse mapping or any other consequences. That said `toString()` should be used in MapStruct.

**Comment by chris922** [comment]
According to the javadoc `toString()` should return a user-friendly string. Thus something that can be displayed to the user. This is often not something that will be stored in internal objects (except they will be exposed to the user in the GUI)

Using `name()` will ensure that a reverse mapping will not cause troubles, because `valueOf(..)` requires exactly the value that `name()` returns. So I think as a default it is correct to use `name()`.

In case you need to use `toString()` you can define an extra mapping method that will call `toString()` and not `name()`.


Maybe you could also define a `@MapperConfig` with a more generic mapping that could be used for all enums, but I don't know if this is really possible... just some untested example code:

```java
@MapperConfig
public class EnumMappings {
  protected String mapEnum(Enum<?> enum) {
    if(enum == null) return null;
    return enum.toString(); 
  }
}

@Mapper(uses = MapperConfig.class)
public interface OtherMapper {
  String toString(FooEnum fe);
}
```

**Comment by soberich** [comment]
@chris922 

> Using name() will ensure that a reverse mapping will not cause troubles, because valueOf(..) requires exactly the value that name() returns. So I think as a default it is correct to use name()

This is the opposite to what my point to this issue was, so it doesn't make sence because the opposite possibility is obvious and not the solution , but rather is the problem itself.

Library is the **product** and not the (Java) specification. Library is already the **client** side and should (and does) use the specification rather than follow. 

Library using `name()` ->  is a blocker for the library user
Library using `toString()` -> is a convention over configuration

@chris922 Not a holywar. @gunnarmorling , @filiphr  - I think should just look at this one, quickly react from their experience and close this with wither one solution or the other to follow.

**Comment by sjaakd** [comment]
@soberich, you might be right, but I see a downward compatibility problem if we change this at this point in time. Note: JAXB generation circumvents this problem by defining its own `value` and `fromValue`, leaving `name` and `toString` untouched (had problems myself here).

@chris922 you are right as well. I used the occasional `toString` as well to hook in I18n. By the way, I adapter the `org.mapstruct.ap.test.complex.CarMapper` unit test. `@MapperConfig` is only allowed as configuration and must be interface (we have an issue somewhere I believe to enforce this). The proper way is to just define a used mapper. So:

```java
@Mapper(uses = { DateMapper.class, EnumMapper.class } )
public interface CarMapper1 {
...
}
```

```java
public class EnumMapper {

    protected String mapEnum(Enum<?> e) {
        if ( e == null ) {
            return null;
        }
        return e.toString();
    }
}
```

Unfortunately that will not work due to #1482. Could use some help in that one though :smile: ..

**Comment by filiphr** [comment]
This is exactly the same as https://github.com/mapstruct/mapstruct/issues/1286

I still stand by [my](https://github.com/mapstruct/mapstruct/issues/1286#issuecomment-326629008) opinion there that using `name()` is "more correct".

One problem that I see when using `toString()` is that the mappings are not symmetrical, so one would always had to write a custom method to make the reverse work (in case of an overriden `toString()`.

And it is already really easy to change this by using a custom mapper:

```
public class EnumConverter {

    public static String convert(Enum<?> source) {
        return source == null ? null : source.toString();
    }

    public static <E extends Enum<E>> E convert(String source, @TargetType Class<E> enumType) {
        // You probably need something else here as the methods are not symmetrical
        return source == null ? null : Enum.valueOf( enumType, source );
    }
}
```

**Comment by soberich** [comment]
Let it be

**Comment by soberich** [comment]
@sjaakd 

> @soberich would the above approach fulfil your criteria as well (so with a working #1482). We could (perhaps) discuss your proposed change as part of going to 2.0 (were users can expect such change). There's an issue( #1307 )for that..
I'll then say post such things in that #1307 if there will be some. Thnks for pointing out.

**Comment by soberich** [comment]
@filiphr 

> I still stand by my opinion there that using name() is "more correct".

Jackson at 3.x release is going to do enums with `toString()` and not `name()`
I still believe this is the right approach.
see https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson3-Changes#changes-to-defaults

**Comment by filiphr** [comment]
>Jackson at 3.x release is going to do enums with toString() and not name()

That page as not been actively updated as of 24th of September 2017. The only active place where I could find where issues for the Jackson 3.x release are being talked is https://github.com/FasterXML/jackson-databind/issues?q=is%3Aopen+is%3Aissue+label%3A3.x. And in there there is nothing about the enums, the default value is also still not changed on the Jackson master (the base for the 3.x release).

**Comment by govindrk** [comment]
am using mapstruct 1.3.1Final, have more than 50 enums different types (string, int) generated from XSD (50 java classes). There are more than 600 fields of enum type within different objects.

JAXB Enum has fromValue which returns the name (VALUE_01) for given value("01"), this is set and mapped to JPA entity as EnumType. 

The name (VALUE_01) is stored in the database. I want to store the value (01) in the backend repository (database) and reverse it back to value (01) in JAXB from JPA via mapstruct.

Tried the suggestion provided here by have custom mapping but not successful. Would like to implement generic EnumMapper at class level and not at field level.

I want to store the value("01") in database as-is from XML after enum validation. Currently its storing enum name(VALUE_01). I would like to reverse the same back to XML.

Would be nice if you could share code sample that be used, am sure will help others

**Comment by govindrk** [comment]
XML - input
      `Gender="_**Female**_"`

XSD - 
`  <xs:simpleType name="genderList">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Female"/>
      <xs:enumeration value="Male"/>
      <xs:enumeration value="Other"/>
    </xs:restriction>`

JAXB - declaration

`                @XmlAttribute(name = "Gender")
                protected GenderList gender;`

Enum -

`@XmlType(name = "genderList")
@XmlEnum
public enum GenderList {

    @XmlEnumValue("Female")
    FEMALE("Female"),
    @XmlEnumValue("Male")
    MALE("Male"),
    @XmlEnumValue("Other")
    UNDISCLOSED("Other");
    private final String value;

    GenderList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GenderList fromValue(String v) {
        for (GenderList c: GenderList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}`

JPA - entity
`    @Enumerated(EnumType.STRING)
    @Column(length = 10)
    protected GenderList gender;`


- no custom mappings

record stored in database is name - FEMALE  (upper case).  My requirement is to store the value "Female" as-is from XML.

Vice-versa - get the value, use mapstruct to get the name FEMALE and then set it to JAXB to get the value back ("Female")

Thanks.

**Comment by govindrk** [comment]
> This is exactly the same as #1286
> 
> I still stand by [my](https://github.com/mapstruct/mapstruct/issues/1286#issuecomment-326629008) opinion there that using `name()` is "more correct".
> 
> One problem that I see when using `toString()` is that the mappings are not symmetrical, so one would always had to write a custom method to make the reverse work (in case of an overriden `toString()`.
> 
> And it is already really easy to change this by using a custom mapper:
> 
> ```
> public class EnumConverter {
> 
>     public static String convert(Enum<?> source) {
>         return source == null ? null : source.toString();
>     }
> 
>     public static <E extends Enum<E>> E convert(String source, @TargetType Class<E> enumType) {
>         // You probably need something else here as the methods are not symmetrical
>         return source == null ? null : Enum.valueOf( enumType, source );
>     }
> }
> ```

Hi Filip,
do you have any guide to create custom mapping for Enum. I know how to create mapping by annotation for methods and apply at property level (attribute). I have ton of classes with enums (900), i want to convert Enum to String (value) and reverse. Can you please a guide with sample code.

Thanks

**Comment by filiphr** [comment]
Hey @govindrk,

I am not quite following what you want to do? There is https://github.com/mapstruct/mapstruct/pull/2045 which is for enhancing the `@ValueMappig`.

If you are looking for something else then have a look at the comment you quoted (https://github.com/mapstruct/mapstruct/issues/1492#issuecomment-389667590). Not sure what you more you are looking for. Perhaps show what you have tried so far so we can help you out

**Comment by govindrk** [comment]
Hi Filip,

Thanks, am using Mapstruct for the first time. Usually i write my own mappers, a colleague of mine referred Mapstruct.

I have 441 class files and in total 900+ enumeration attributes.  I have taken your EnumConverter  logic and modified to get the value.

Please let me know if i can just call this class from an Mapper interface, have attached the example file.






Thanks & Regards

==========================

Govind

+61 410 851 608 (c)

==========================

________________________________

**Comment by govindrk** [comment]
Hey @filiphr,

what is the best way to get the enum constant value for generic type. Your code works good both ways, but am not able to extract value to String.

eg: RED("red"),  need the constant value = "red" and not the constant name = RED to be passed to the string.

Your help is much appreciated.
Thank you.

**Comment by filiphr** [comment]
Well you have the class and the source right? You can write your own reflection logic. 


```
public class EnumConverter {

    public static String convert(Enum<?> source) {
        if (source == null) {
            return null;
        }

        return (String) source.getClass().getDeclaredMethod("value").invoke(source);
    }

    public static <E extends Enum<E>> E convert(String source, @TargetType Class<E> enumType) {
        // You probably need something else here as the methods are not symmetrical
        if (source == null) {
            return null;
        }

        return (E) enumType.getDeclaredMethod("fromValue").invoke(null, source);
    }
}
```

**Comment by seime** [comment]
@govindrk If #2045 is accepted you would in your SPI implementation of the proposed SPI define a generic enum transformation function such that mapstruct is able to generate readable and compilable mapping code between the JAXB enums and your JPA enums. The benefits would be (and some of the reasons why mapstruct is great - thanks @filiphr & @sjaakd):

- no slow runtime reflection
- no unhandled mapping cases going undetected and showing/blowing up in production instead
- where your general pattern ("Xyz" <-> "XYZ") isn't followed you may handle each case by adding `@ValueMapping(source="XYZ" target="xYZ")` or similar
- handling of `null` values mapping to other enum constants
- handling of enum constants that does not exist on your JPA side but on the JAXB side - or vice versa

Here is an SPI implementation example. This one is for protobuf, but a JAXB type as you need would probably be smaller. https://github.com/entur/mapstruct-spi-protobuf/blob/valuemapping_accessor_spi/spi-impl/src/main/java/no/entur/mapstruct/example/protobuf/ProtobufEnumConstantNamingStrategy.java

How the SPI mechanism work; https://mapstruct.org/documentation/stable/reference/html/#using-spi

**Comment by govindrk** [comment]
> Well you have the class and the source right? You can write your own reflection logic.
> 
> ```
> public class EnumConverter {
> 
>     public static String convert(Enum<?> source) {
>         if (source == null) {
>             return null;
>         }
> 
>         return (String) source.getClass().getDeclaredMethod("value").invoke(source);
>     }
> 
>     public static <E extends Enum<E>> E convert(String source, @TargetType Class<E> enumType) {
>         // You probably need something else here as the methods are not symmetrical
>         if (source == null) {
>             return null;
>         }
> 
>         return (E) enumType.getDeclaredMethod("fromValue", String.class).invoke(null, source);
>     }
> }
> ```
Hey @filiphr,
The reflection worked thank you very much.  We need to specify the parameterType - String.class in the String -> Enum return.

thanks again.
govind

**Comment by govindrk** [comment]
> @govindrk If #2045 is accepted you would in your SPI implementation of the proposed SPI define a generic enum transformation function such that mapstruct is able to generate readable and compilable mapping code between the JAXB enums and your JPA enums. The benefits would be (and some of the reasons why mapstruct is great - thanks @filiphr & @sjaakd):
> 
> * no slow runtime reflection
> * no unhandled mapping cases going undetected and showing/blowing up in production instead
> * where your general pattern ("Xyz" <-> "XYZ") isn't followed you may handle each case by adding `@ValueMapping(source="XYZ" target="xYZ")` or similar
> * handling of `null` values mapping to other enum constants
> * handling of enum constants that does not exist on your JPA side but on the JAXB side - or vice versa
> 
> Here is an SPI implementation example. This one is for protobuf, but a JAXB type as you need would probably be smaller. https://github.com/entur/mapstruct-spi-protobuf/blob/valuemapping_accessor_spi/spi-impl/src/main/java/no/entur/mapstruct/example/protobuf/ProtobufEnumConstantNamingStrategy.java
> 
> How the SPI mechanism work; https://mapstruct.org/documentation/stable/reference/html/#using-spi

Hey @seime,
Thank you, would you be merging these into 1.4.0 release.
