### ISSUE TITLE
Set defaultValue when RETURN_DEFAULT is used

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct#1493]
When `NullValueMappingStrategy.RETURN_DEFAULT` is used the `expression` and `constant` values will be set to the newly instantiated bean. I would expect that also the `defaultValue` would be set, but this is not the case.

WDYT? In case this will be added the new `defaultExpression` should be considered in the same way.
I think this is also a (minor) breaking change, so it should be mentioned in the release notes. Don't know if it is safe to include this in a minor release or if this is something for the next major release.

If you like this I would try to create a PR for this.

**Comment by filiphr** [comment]
I need to see an example for what exactly you mean.

Such breaking change is fine in our release version cycles. 

Usually `defaultValue` and `defaultExpression` are used when the source property is `null` or not present. Whereas the `expression` and `constant` are always set, i.e. they don't depend on source properties. Do we have some test that I can have a look at?

**Comment by chris922** [comment]
Just a quick example from memory:

```java
@BeanMapping(nullValueMappingStrategy = RETURN_DEFAULT)
@Mapping(target = "foo", defaultValue = "bar")
public Target toTarget(Source source);

// generated:
public Target toTarget(Source source) {
  Target target = new Target();
  
  if(source != null) {
    if(source.getFoo() != null) target.setFoo(source.getFoo());
    else target.setFoo("bar");
  }
 
  return target;
}

// should generate:
public Target toTarget(Source source) {
  Target target = new Target();
  
  if(source != null) {
    if(source.getFoo() != null) target.setFoo(source.getFoo());
    else target.setFoo("bar");
  } else {
    // new: ensure the default value will be set
    target.setFoo("bar");
  }
 
  return target;
}
```

I think the test for issue 913 with the `DomainDtoWithNvmsDefaultMapper` should fit. In case `create(Dto)` will be called with `null` the returned `Domain` will not have a value for `stringsWithDefault` even though there is a default value (`3`) configured.

**Comment by sjaakd** [comment]
ah.. you're the first one combining those two previously unrelated features. It was originally not intended like this. RETURN_DEFAULT was to indicate a default type. So, an empty list, map or just a new Object, 0 or false. That's what the documentation states in chapter 10.4.

**Comment by chris922** [comment]
But it will set constants or expressions if defined. So not just an empty object in this case. It is a bit strange that default values will not be considered here when I want to return a default object. 

Do you think it should stay as it is or would it be a good idea to add this feature? Maybe a new `nullValueMappingStrategy` that combines everything?

**Comment by sjaakd** [comment]
I think your proposal is fine. Its even stated in our current documentation:

"• Bean mappings: an 'empty' target bean will be returned, with the exception of constants and expressions, they will be populated when present." 

Somehow this dropped from our solution.. Reading this.. it must have been there in the past.

**Comment by sjaakd** [comment]
@chris922  Should we reconsider this one in the light of `@NulvaluePropertyMappingStrategy`.. ? I realise now that the `NulvalueMappingStrategy ` was not intended to act on properties, but on beans. The `defaultValue` `defaultExpression` are supposed to act only when a property is null, not the entire bean. 

So I propose to close this one.

**Comment by chris922** [comment]
Sounds like the `NullValuePropertyMappingStrategy` is doing the same. So yes, we can go on with this new annotation instead of extending the regular `nullValueMappingStrategy`.

I will close this issue.

**Comment by tiagozc** [comment]
Hi, was this ever implemented and if it was is there any example where I can see how to do it? I was expecting the same, that a `RETURN_DEFAULT` bean would be populated with the `defaultValue` as well.

**Comment by filiphr** [comment]
@tiagozc please create a new discussion for asking questions. This issue has been closed for almost 5 years.
