### ISSUE TITLE
Enhancement function parameters as object mapping

### ISSUE THREAD

**Issue by luispereira** [mapstruct/mapstruct#1495]
I would like to suggest something like this, in order to prevent the creation a new CustomClass just to create our own transformation manually

```
    @Mappings({
            @Mapping(source = "deviceID", target = "{deviceId}")
    })
    Device fromDeviceDTO(DeviceDTO dto, String deviceId);
```
In this example we are telling the mapper that Device will have it field deviceID filled with the parameter deviceId

Or is there any change to do this kinda of custom mapping?

**Comment by filiphr** [comment]
Is the `Device#deviceID` a `String` as well?

Have you tried with:

```
    @Mappings({
            @Mapping(source = "deviceId", target = "deviceID")
    })
    Device fromDeviceDTO(DeviceDTO dto, String deviceId);
```

This should work. Have you read [Mapping methods with several source parameters](http://mapstruct.org/documentation/stable/reference/html/#mappings-with-several-source-parameters)? 

If I understood you correctly, then this is already possible. Therefore, I am closing this issue. In case I misunderstood, I am sorry and we can reopen it.
