### ISSUE TITLE
Update don't set null value if conversion exist

### ISSUE THREAD

**Issue by necmettincetincift** [mapstruct/mapstruct#1496]
Hi using mapstruct 1.2.0.Final. I want to update entity with given dto and some values are null. Mapstruct not update this null values if there is type conversion. In given code if b is null in source, update method don't set null to b in target. Is this behaver configurable? Help please
```
public class Dto {
    private Long a;
    private BigDecimal b;
}
```

```
public  class Entity {
    private Long a;
    private Double b;
}
```

```
public abstract void updateEntity(Dto source, @MappingTarget Entity target);
```
```
//Generated
@Override
public void updateEntity(Dto source, Entity target) {

    if ( source != null ) {
        target.setA( source.getA() );
        if ( source.getB() != null ) {
            target.setB( source.getB().doubleValue() );
        }
    }
}
```

**Comment by sjaakd** [comment]
have you checked out our [refguide)[http://mapstruct.org/documentation/stable/reference/pdf/mapstruct-reference-guide.pdf] chapter 10.5: `NullValueCheckStrategy`?

**Comment by filiphr** [comment]
@necmettincetincift I think the link @sjaakd referenced answers this question. I am going to close this issues. If you think we need to reopen it please say so

**Comment by michal-filip** [comment]
To me this behavior was also confusing and no value of NullValueMappingStrategy or NullValueCheckStrategy allows me to change the behavior to generate code like this:
```
@Override
public void updateEntity(Dto source, Entity target) {

    if ( source != null ) {
        target.setA( source.getA() );
        if ( source.getB() != null ) {
            target.setB( source.getB().doubleValue() );
        } else {
            target.setB(null);
        }
    }
}
```

A workaround is to add manual mapping eg.
```
@Mapping(
   target = "B",
   expression = "java(source.getB() == null ? null : source.getB().doubleValue())"
)
```
which is quite lengthy. Is there some other configuration option I'm missing?

**Comment by sjaakd** [comment]
have you tried using a create mapping for the mappings you don't want to override.?

e.g. : `double create( Double source );`
