### ISSUE TITLE
Generate no argument object factory

### ISSUE THREAD

**Issue by svpace** [mapstruct/mapstruct#1500]
When implementing base mappers, specially generics, it would be useful to have access to the objects constructors.

Therefore I would like to suggest a feature to generate non-implemented object factories using constructors.

```java
@ObjectFactory
public abstract Foo create();
```
Generates
```java
public Foo create() {
    return new Foo();
}
```

**Comment by filiphr** [comment]
`@ObjectFactory` is meant to be used for complex object creations. Creating a default constructor is already the case. 

For example:

```
public interface GenericMapper<S, T> {

    T map(S source);
}

@Mapper
public interface SpecificMapper extends GenericMapper<Process, ProcessDto> {
}
``

Will generate the following code:

```
public class SpecificMapperImpl implements SpecificMapper {

    public ProcessDto map(Process source) {
        if (source == null) {
            return null;
        }

        ProcessDto target = new ProcessDto();
        // do the mappings
        return target
    }
}
```

Therefore, I don't see a big benefit in MapStruct implementing `@ObjectFactory`. I personally don't see why you would need something like that.

Please share some more information about why the current way is not OK for you and we can reopen the issue

**Comment by svpace** [comment]
I should've had lead with that. A pattern that I see frequently with mapstruct is the mapper-resolver where there is an object factory like this
```java
@ObjectFactory
public T resolve (AbstractDto dto) {
    return dto.getId() !=null ? repo.load(stop.getId()) : create ();
}
```
Where create is some abstract method that must be implement or some reflection.

**Comment by filiphr** [comment]
You need reflection to get the type of `T`?

You know that you can use `@TargetType` and MapStruct will pass in the class of `T` in your method. Have a look at the example in the [Object factories](http://mapstruct.org/documentation/stable/reference/html/#object-factories) in the documentation.

You can do something like:

```
@ObjectFactory
public T resolve (AbstractDto dto, Class<T> clazz) {
    return dto.getId() !=null ? repo.load(dto.getId()) : create (clazz);
}

protected T create(Class<T> clazz) {
    try {
        return clazz.newInstance();
    } catch ( InstantiationException | IllegalAccessException e ) {
        throw new RuntimeException( e );
    }
}
```

Does something like this work for you?

**Comment by svpace** [comment]
Thanks, I've must have missed that. Currently I have to jump through a few hoops to get T's class. This will make things a lot easier.

Nonetheless, I was looking for a way to avoid using reflection since a missing default constructor will not be detected at compile-time.

**Comment by filiphr** [comment]
>Nonetheless, I was looking for a way to avoid using reflection since a missing default constructor will not be detected at compile-time.

Using `Class#newInstance()` is not that bad, compared to the hoops you need to do to get the generics 😄. Nevertheless, I understand you. However, I am not entirely sure that we need to do something like this on our side.

However, there is an unofficial way for you to achieve this 😄. You would need to register a custom `ModelElementProcessor` that would add an implementation of that method. You would need to do multiple things to achieve that. 

* You would have to make that method non abstract (if it is abstract MapStruct will try to create an implementation and would perform its checks in `MethodRetrievalProcessor`). 
* Create a custom `ModelElementProcessor` that would look for your method (you can mark it with your own annotation as well) and make it go before the `MapperRenderingProcessor`. In your implementation you would need to add a method to the `Mapper#getMethods`. You can use the `VirtualMappingMethod` and a custom implementation of `HelperMethod`.

**NB** I must stress out that by doing this you would be using an internal API of MapStruct which has no guarantees of staying stable even in a patch release

**Comment by svpace** [comment]
Thanks! Great tip. I will try it and let you know. Best regards
