### ISSUE TITLE
[IMPROVEMENT] Make Mapper configuration properties all enums

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1508]
Hi,
```java
@Mapper/*Config*/(
        componentModel             = "cdi",  // <= He wants to be Enum too =(
        injectionStrategy          = CONSTRUCTOR,
        collectionMappingStrategy  = TARGET_IMMUTABLE,
        unmappedTargetPolicy       = ERROR,
        unmappedSourcePolicy       = WARN,
        mappingInheritanceStrategy = AUTO_INHERIT_ALL_FROM_CONFIG)

```
))

**Comment by chris922** [comment]
I also like enums to prevent mistakes, but when I remember correctly it is possible to extend the (right now more or less only internal) SPI with own component models and using an enum wouldn't allow this as this must be extended.

**Comment by soberich** [comment]
@chris922 I didn't look to those possibilities, more precisely, I didn't know that it is possible.

**Comment by filiphr** [comment]
Thanks for the reply @chris922. Yes that being a string is on purpose with the actual possibility of plugging an own component model through the internal SPI
