### ISSUE TITLE
Is it possible to assign value using setter with different non-standard name?

### ISSUE THREAD

**Issue by agilob** [mapstruct/mapstruct#1512]
I have the following class:
```
   private Event keyEvent;

    public Event getKeyEvent() {
        return keyEvent;
    }

    private void setKeyEvent(Event keyEvent {
        this.keyEvent = keyEvent;
    }

    public void assignKeyEvent(Event keyEvent) {
        setKeyEvent(keyEvent);
        addEvent(keyEvent);
    }

    public void addEvent(Event event) {
      // validation and hierarchy of events setup
    }
```

and I would like to tell MapStruct to use `assignKeyEvent` setter. It it possible to setup mapper to use this setter by name? The setter it's trying to find is private, MapStruct can't see it and complains it doesnt exist.

**Comment by sjaakd** [comment]
checkout [chapter 13, SPI](http://mapstruct.org/documentation/stable/reference/pdf/mapstruct-reference-guide.pdf). You can also find examples [here](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-spi-accessor-naming)
