### ISSUE TITLE
Concat primary key of another entity (Loop AfterMapping)

### ISSUE THREAD

**Issue by luispereira** [mapstruct/mapstruct#1513]
I'm trying to concat something to a primary key of other entity, like:

EntityA
```
open class EntityA(
      @PrimaryKey
       var primaryKey: String? = "",
       var entityB : List<EntityB>? = emptyList(),
      (...)
)
```

EntityB 
```
open class EntityB(
      @PrimaryKey
       var primaryKey: String? = "",
      (...)
)
```

EntityMapperA
```
interface EntityMapperA{
          @Mappings(
            Mapping(source = "primaryKey", target = "entityB .primaryKey"))
    fun fromEntityADTOToEntityA(dto: EntityADTO): EntityA?
}

```

Problem with this EntityMapperA is that I cannot concat a string to the `entityB .primaryKey`
Therefore, what I tried was to concat something using @AfterMap

EntityMapperB
```
interface EntityMapperB{

    fun fromEntityBDTOToEntityB(dto: EntityBDTO): EntityB?

    @AfterMapping
    fun afterMapping(dto: EntityBDTO, @MappingTarget target: EntityB) {
        val pk = target.primaryKey
        target.primaryKey = pk + "_app"
    }
}

```

However this creates an infinite looping on the generated implementation:

```
    @Override
    public void afterMapping(EntityB target, EntityBDTO dto) {
        if ( dto == null ) {
            return;
        }

        afterMapping( target, dto );
    }
```

Is there something wrong with my implementation?

**Comment by sjaakd** [comment]
are you sure this is the code that is generated? I'm not so familiar with Kotlin, but it seems strange to me that the `afterMapping` method is somehow overriden? I assume its `fromEntityBDTOToEntity` that is generated.

Anyway.. Its more an implementation question iso a problem or feature request. This is intended for problems in MapStruct. Can you post this one on StackOverflow?

**Comment by filiphr** [comment]
The problem might actually be in the way the kotlin compiler generates the bytecode for the interface. We are going to create an implementation only if the method is not default or static see [here](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java#L208).
