### ISSUE TITLE
Cannot convert from java.time.LocalDate to java.time.LocalDate

### ISSUE THREAD

**Issue by jaas0301** [mapstruct/mapstruct#1515]
`public class ClassA {
     private OffsetDateTime updateBy;
}`

`public class ClassB {
     private LocalDate timestamp;
}`

public interface ClassABMapper {
@Mapping(target = "updateBy", source = "classB.timestamp")
ClassA map(ClassB classB);
}

> Can't map property "java.time.LocalDate timestamp" to "java.time.OffsetDateTime updateBy". Consider to declare/implement a mapping method: "java.time.OffsetDateTime map(java.time.LocalDate value)".
      
I tried declaring the following method in mapper.
`java.time.LocalDate map(java.time.OffsetDateTime value);`

And I am getting error:

>  error: java.time.LocalDate does not have an accessible empty constructor.
        java.time.LocalDate map(java.time.OffsetDateTime value);

Can someone please explain what I am missing?

**Comment by jaas0301** [comment]
I created my own custom mapper as explained in the documentation section 5.4. Invoking other mappers. That solved this issue for me.

**Comment by filiphr** [comment]
Glad that you managed to work it out

**Comment by yahitesh** [comment]
@jaas0301 can you provide the link for that?
Thanks!

**Comment by filiphr** [comment]
I think that the link should be [this](https://mapstruct.org/documentation/stable/reference/html/#invoking-other-mappers)
