### ISSUE TITLE
IMPROVEMENT: Annotated Ignore Mappers

### ISSUE THREAD

**Issue by ldolbir** [mapstruct/mapstruct#1517]
Here is the use case: 
Most of the enterprise schema entities we are mapping have some sort of the superclasses defining additional behavior. 
Example: Enrollment class would  extend TemporalObject class, while Amendment class extends TransactionHistory, etc. Most of the inherited attributes don't need to be mapped as they represent immutable history. Since there are only several of those superclasses, but many more Entities it would be advantages to provide generic approach of ignoring these attributes. 

Approach:
The Mappers are defined at the method level. Therefore when a single Mapper provides several methods all common ignore attributes must be repeated at the @Mapping level. It would be great if we could re-use the Mappers that must be ignored by all other Mappers instead. It would be consistent with the main constructs of the framework and allow to avoid many pains in my case.
Example: 
`@IgnoreMapper 
public Interface TemporalMapper{
com.company.a.Temporal temporalToTemporal(com.company.b.Temporal source);
}
@Mapper
public @interface IgnoreMapper {
/* Not sure what type of settings it would need since the Mapper implementation is not really required.*/
}`

This approach would allow a single with multiple types or multiple with single type mapping to be ignored generically.

Thanks !!!

There is a chance you already thought of this and I'm just being ignorant. If this is the case,  please point me to the right direction :-)

**Comment by filiphr** [comment]
Have you looked into [Reusing mapping configurations](http://mapstruct.org/documentation/stable/reference/html/#_reusing_mapping_configurations). I think that is what you are looking for.

In the upcoming 1.3.0.Beta1 there will be a way to ignore all properties and only do mappings for specific ones. Have a look at https://github.com/mapstruct/mapstruct/issues/1392.

Feel free to reopen if this is not what you are looking for

**Comment by ldolbir** [comment]
This solution doesn't appear to be working for inherited attributes. I've attempted to add the superclass to the configuration->uses attribute and it made no impact.
Only when I ignore the attribute at the subclass level are the attributes actually ignored. 

So you may be right from the stand point of feature existence, but it is not working

**Comment by filiphr** [comment]
>This solution doesn't appear to be working for inherited attributes

Which one? The reusing mapping configurations or the other one? 

I've reopened the issue. Can you create a small example showing what does not work, os inheritance and ignoring properties there should work correctly.

**Comment by ldolbir** [comment]
I've added some classes to the Mapstruct Examples fork https://github.com/ldolbir/mapstruct/commit/18811d3131d79f95036274b17f864fec114c41f3

**Comment by filiphr** [comment]
Your mapper looks like:

```
@Mapper(uses = {HistoricalDataMapper.class})
public interface PolicyMapper {
    Policy policyDtoToPolicy(PolicyDto source);
}
```

Do you need to use the `HistoricalDataMapper` or is it just for the ignoring? If it is for configuration it needs to look a bit different. Look at [Shared configurations](http://mapstruct.org/documentation/stable/reference/html/#shared-configurations).

Also you would need to annotated your method with `@InheritConfiguration` in order for the configuration to be inherited. Or use `MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG`. If you use the latter you would need to do `@Mapper(config = HistoricalDataMapper.class)` as well.

**Comment by ldolbir** [comment]
I've attempted every permutation I could think of to test it. Please check here https://github.com/ldolbir/mapstruct/commit/5b684264a48e59bb29784fe7c91a7a1add979fba. I've also tried many variations and couldn't achieve desired result

**Comment by ldolbir** [comment]
I wanted to pass along some feedback from my project: The new transformation logic using MapStruct cut down the transformation time from 514 milliseconds to 7.5 milliseconds and discovered some bugs in the process. So, thank you very much!!!

**Comment by filiphr** [comment]
>I've attempted every permutation I could think of to test it.

I'll have a look your permutation and try to figure out an example to achieve what you are looking for. I am fairly certain that you can do something 😄.

Thanks for passing a long the feedback. It is really nice to get positive feedback from users. Glad that you like it. 

>The new transformation logic using MapStruct cut down the transformation time from 514 milliseconds to 7.5 milliseconds and discovered some bugs in the process.
If you don't mind me asking. Can you share from what you are converting to MapStruct?

**Comment by ldolbir** [comment]
The current approach is implemented with Apache Commons (Bean Utils, Property Utils, etc...). However, I did consider a couple of other mapping frameworks before settling on MapStruct.  I did a prototype with Dozer and ModelMapper and only MapStruct got x10 improvement.

**Comment by sjaakd** [comment]
@ldolbir .. what's your status on this one?
