### ISSUE TITLE
Support several component model at the same time for generated mappers

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1521]
We have a generic app which support deployment with spring container or without.
So, if internally it is possible, please provide ability to pass several values to component model property
```java
@Mapper/*Config*/(
        componentModel             = {"cdi", "spring"} // <= HERE
        collectionMappingStrategy  = TARGET_IMMUTABLE,
        unmappedTargetPolicy       = ERROR,
        unmappedSourcePolicy       = WARN,
        mappingInheritanceStrategy = AUTO_INHERIT_ALL_FROM_CONFIG)
```
The retention of those `@Component` and `@ApplicationScopped` is `RUNTIME` and even if it is there and not in use, it just hangs like no-op, so the generated mapper would be 
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-06-14T03:53:14+0300",
    comments = "version: 1.3.0-SNAPSHOT, compiler: javac, environment: Java 1.8.0_172 (Oracle Corporation)"
)
@Component
@ApplicationScopped
public class ProspectMapperImpl implements ProspectMapper {

    //@Autowired  // Even this could be ommited as Spring support @Inject
    @Inject
    private SellerMapper sellerMapper;
    ...
}
```
constructor injection seems to be no problem as well.

**Comment by soberich** [comment]
There is no DIRECT benefit, but INDIRECT.
Now the chosen implementation restricts library user for no reason while it can stop doing so just allowing an array of component models and generating a couple of annotations.
So, the benifit here has the from of not adding some plus but rather stop having a minus - not to restict use case for no reason.

**Comment by filiphr** [comment]
If we add support for array in the `componentModel` it would mean that we would need to have support for multiple component models within the processor itself and have extra checks and everything as it is not allowed to use `default` with others as it won't make sense. There might even be more issues from such implementation.

I really don't understand why it is a problem for you to implement a custom extension of the `AnnotationBasedComponentModelProcessor` and provide your implementation with your own component model? The reason why `componentModel` is a `String` is the fact that it can be customized by extension points.

Additionally, it is even possible to implement an extension that would take a comma separated value of the `componentModel` and create everything you need. This can be implemented as part of an extension to MapStruct.

I personally don't see big value (compared to what it needs to be done to implement this) for MapStruct. Therefore I am going to close this issue. In case the team has some other opinion we can reopen it.

**Comment by soberich** [comment]
@filiphr 

> I really don't understand why it is a problem 

It's not a problem, I am looking for simpler and more generic solution for such case.
Here is an idea.
Why not just use `@javax.inject.Named` it is supported by Spring framework so the generated mapper for both `spring` and `cdi` could always look like.
```java
import javax.inject.Named;
...
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-06-14T03:53:14+0300",
    comments = "version: 1.3.0-SNAPSHOT, compiler: javac, environment: Java 1.8.0_172 (Oracle Corporation)"
)
@Named
@ApplicationScopped
public class ProspectMapperImpl implements ProspectMapper {

    @Inject
    private SellerMapper sellerMapper;
    ...
}
```

I think this is great and simple.

**Comment by filiphr** [comment]
@chris922 I think there has been another issue that request passing annotations to the mappers. However, I am going to say again implementing a custom `ModelElementProcessor` that extends `AnnotationBasedComponentModelProcessor` is the easiest and fastest way to solve such problem. The `componentModel` is a `String` so users can different things with it.
