### ISSUE TITLE
Cache DatatypeFactory

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1532]
I came across this (German) post which shares some experiences with MapStruct: https://blog.doubleslash.de/welcher-javabean-mapper-die-qual-der-wahl/

It is positive in general, but there's one performance issue being pointed out: when converting a `Date` into an `XmlGregorianCalendar`, the mapping method calls `DatatypeFactory#newInstance()` each single time (see [template](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/DateToXmlGregorianCalendar.ftl#L30), might affect other built-in mappings, too). This call is expansive (service loader usage), so we should do it only once.

The easiest would be, if the template contained the field as well (it'd result in somewhat unclean code as it'd add the field not at the beginning of the class but somewhere in the middle, which I think is alright). We'd have to take care though to avoid naming collisions.

**Comment by sjaakd** [comment]
I guess its not to difficult to extend the current solution to include also a new mechanism to declare instance variable definitions along the same lines the template for this conversion is added. That could not be to difficult to make.

**Comment by sjaakd** [comment]
Done.. need to add unit test for CDI though.

**Comment by filiphr** [comment]
@sjaakd should we close this one and open a new one for the CDI unit test?

**Comment by sjaakd** [comment]
Most certainly. Initially I thought that this could be resolved quick. Now I realize that we need more time to fix UT first. Although it does not feel comfortable CDI is not properly tested.
