### ISSUE TITLE
Support for AutoValue builders

### ISSUE THREAD

**Issue by jorgebo10** [mapstruct/mapstruct#1536]
It would be nice to have support for AutoValue builders. Is there any workaround so far?
Thanks,
Jorge

**Comment by sjaakd** [comment]
@jorgebo10 . Have you tried our latest master? There's support for `AutoValue` builders. We are going to release a beta soon. But  by all means, feel free to try :smile: . I'm going to close this issue as support is on its way.

**Comment by filiphr** [comment]
See also https://github.com/mapstruct/mapstruct/issues/802
