### ISSUE TITLE
Converting float to int and double to long with usage of Math.round 

### ISSUE THREAD

**Issue by gauee** [mapstruct/mapstruct#1542]
Hi, 
today I mapped classes when I have to convert the float to int. I saw that generated mapping is using simple type casting.
`distance.setLength( (int) distanceType.getLength() );`

Would you be interested in pr with changes about usage of `Math.round()` ?

**Comment by sjaakd** [comment]
@gauee : did you use our latest master? You are aware that you can always implement your own handwritten method. A default method for java8 or an abstract class for other java version?

**Comment by gunnarmorling** [comment]
Indeed I think that's better handled with a custom mapping method which will take precedence over the built-in mappings. Esp. as your preferences in regard to rounding may differ between projects.

**Comment by filiphr** [comment]
@gauee I also think that using some form of `Math.round()` might not be the right approach as there are different ways one can do that. I would suggest to you to have a look at [Adding custom methods to mapper](http://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods) and [Invoking other mappers](http://mapstruct.org/documentation/stable/reference/html/#invoking-other-mappers) in order for you to solve this on your side.

I am going to close this issue

**Comment by gauee** [comment]
Ok, it was only an idea. Thanks for took it into consideration.
