### ISSUE TITLE
Mapstruct doesn't work correct with java 10 

### ISSUE THREAD

**Issue by Pryanic** [mapstruct/mapstruct#1543]
Hi all, I changed java version in my project from 8 to 10.  And saw that mapstruct doesn't work correct with mapping from @Data(annotation from lombok library) to @Value entity via Builder. 
I looked in ObjectMapperImpl and saw the following changes 

 @Override
    public ValueObject toValueObjectBuilder(String parA, DataObject data) {
        if ( parA== null && data== null ) {
            return null;
        }

        ValueObjectBuilder builder= createValueObjectBuilder();
       /*
              the following code was in JAVA 8
      */
     //    builder.setA(data.getA());
    //     builder.setB(data.getB());
   //      builder.setC(data.getC());
//===========================
        return equipmentBuilder;
    }

Can you help me fix this problem?

**Comment by gunnarmorling** [comment]
Hey, the formatting of the question is a bit broken. Can you provide properly formatted snippets of the mapper interface and the generated code with Java 8 and with Java 10? Thanks!

**Comment by filiphr** [comment]
I just tried Java 10 with [mapstruct-lombok](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok) and the generated builders were working. The problem you are facing might actually be similar as https://github.com/rzwitserloot/lombok/issues/1538.

Can you also try to split the MapStruct mappers and Lombok classes into separate modules just to test if it is going to work like that?

**Comment by Pryanic** [comment]
@filiphr  HI, we discussed with you yesterday in StackOverflow(https://stackoverflow.com/questions/51284296/mapstruct-and-java10)
I fixed my problem can you help me with problem and say why my spring boot application doesn't see mapstruct mapper as bean. Code example you can find here https://github.com/Pryanic/MACHINE

**Comment by Pryanic** [comment]
@filiphr Is it expected that after change java version from 8 to 10 location of generated

**Comment by chris922** [comment]
@Pryanic don't annotate your Mapper interface with `@Component`. You need to set the `componentModel` that MapStruct will use when generating the implementation to `spring`, e. g. like this: `@Mapper(componentModel = "spring")`.
Alternativly you can create a `@MapperConfig` that you use in all your mapper or - the as it looks like deprecated (but in my opinion prefered) way - as a processing option in your maven configuration:

http://mapstruct.org/documentation/stable/reference/html/#configuration-options

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.5.1</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
		<annotationProcessorPaths>
			<path>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>${org.mapstruct.version}</version>
			</path>
		</annotationProcessorPaths>
		<compilerArgs>
			<compilerArg>
				-Amapstruct.defaultComponentModel=spring
			</compilerArg>
		</compilerArgs>
	</configuration>
</plugin>
```

**Comment by filiphr** [comment]
@Pryanic yes I thought it was the same person :).

Regarding the `@Generated`. Have a look at [Using MapStruct on Java 9](http://mapstruct.org/documentation/stable/reference/html/#_using_mapstruct_on_java_9) we need to change our documentation to reflect the latest changes see https://github.com/mapstruct/mapstruct/issues/1382. Currently the `@Generated` annotation is commented it out when the appropriate module is not exposed.
