### ISSUE TITLE
Inherit MapperConfig

### ISSUE THREAD

**Issue by mistic100** [mapstruct/mapstruct#1546]
I would like to be able to combine `@MapperConfig` annotated classes.

The goal is to have a global configuration for the whole application :

```java
@MapperConfig(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        uses = MappingUtils.class
)
public interface MappingConfig {

}
```

And dedicated configurations for some bricks :

```java
@MapperConfig
public interface ApiMappingConfig extends MappingConfig {

    @Mapping(/** common mapping config for abstracts **/)
    AbstractModel abstractMap(AbstractApiDTO apiDTO);

}
```

Then in the API mappers I could use :

```java
@Mapper(config = ApiMappingConfig.class)
```
And have both MapperConfig applied.

The syntax proposed here is similar the Spring's  `@Configuration` inheritance.

**Comment by filiphr** [comment]
@mistic100 is this one similar to #807. Both are talking about composition (meta annotations). We have been thinking on adding support for meta annotations to MapStruct for 2.0. So I suppose something like what you are proposing will work.

Maybe cleaner with be your `MappingConfig` to be an annotation and then `ApiMappingConfig` will be annotated with `@MappingConfig`. Or even better we can have something like:

```
@Mapper(componentModel = "spring")
public interface @SpringMapper {}
```

And you will then use `@SpringMapper` on your class. Something in that direction.

**Comment by sjaakd** [comment]
@filiphr could we mark this as duplicate than? I think such a request #1362 and #807 all come down to similar functionality.. That is: how to compose inheritance in mappings.

**Comment by filiphr** [comment]
@sjaakd I think yes, we can mark it as duplicate and close it. The 3 linked issues are quite similar to each other.
