### ISSUE TITLE
relieve rules for String->enum mapping

### ISSUE THREAD

**Issue by tomaszalusky** [mapstruct/mapstruct#1557]
Suppose we convert object of type `Foo` to `FooDto`, both classes have `fruit` field of enum type, respectively: (reasoning: `Fruit` might change and `FooDto` is used in frontend whose development is not tightly coupled with backend, so we want frontend not to crash when say `Fruit.ORANGE` constant is added to backend.)

    public enum Fruit {APPLE, BANANA, COCONUT}
    public enum FruitDto {APPLE, BANANA, COCONUT, FALLBACK}

This works great thanks to abstract conversion method `FruitDto m(Fruit)` annotated with `@ValueMapping(source = MappingConstants.ANY_REMAINING, target = "FALLBACK")`, generated method contains switch with common constants and default branch for `FALLBACK`. 

What's an issue: in some cases the `Foo.fruit` property is of type `String` (not `Fruit`) with literally same content. In such case conversion method `Fruit m(String)` either must not exist (which renders automatic conversion without fallback) or must be written manually with body. Abstract method with annotation above leads to `Can't generate mapping method from non-enum type to enum type` error.

Proposal: allow `@ValueMapping` on String->enum methods. Instead switching on `Fruit`s, generated code could switch on Strings. Case statements' constant values would be taken from target enum. IMHO it wouldn't mind since currently generator can render only intersection of two enum sets anyway (in `ANY_REMAINING` mode; `ANY_UNMAPPED` mode would behave same way).

**Comment by sjaakd** [comment]
What about a regular mapping here? `@ValueMapping` was introduced for mapping enum-to-enum. There was discussion for extending this to other types. However it was not deemed use full at the time, since immutable maps are just as efficient.

**Comment by tomaszalusky** [comment]
Could you please provide an example for my case or more elaborate on what you mean by "regular mapping"?
I cannot think out how would @Mapping annotation apply, multiple repeating annotations AFAIK serve for more fields of single mapping rather then more values of single field. I want to avoid enumerating constants manually, one at a time.

**Comment by sjaakd** [comment]
> Could you please provide an example for my case or more elaborate on what you mean by "regular mapping"?

Implement a method (so manually) with uses a map to do the mapping. If fields can be mapped based on name, you could possibly shortcut by only mapping the (non matching names) in the map.

**Comment by filiphr** [comment]
@tomaszalusky what @sjaakd  is referring to looks something like:

```
@Mapper
public interface MyMapper {

    BasketDto map(Basket source);

    default FruitDto map(String fruit) {
        if (fruit == null) {
            return null;
        }

        switch(fruit) {
            case "APPLE":
                return FruitDto.APPLE;
            ....
        }
    }
}
```

However, what @tomaszalusky is proposing might be interesting. I don't see that it would be too difficult to relax the `@ValueMapping` to accept strings. However, I am not sure if it is a right approach for MapStruct.

**Comment by sjaakd** [comment]
I proposed it even myself in the beginning when I implemented valuemappings. But wee did not agree at that time. But wee can re-evaluate. Let's discuss in a hang out

**Comment by chris922** [comment]
Just reviewed a PR on work and a teammate had the same issue and implemented an own mapping method... 

@filiphr and @sjaakd: I don't see something that needs to be discussed here except "should we allow `@ValueMapping` for this or not?".
@filiphr what are the reasons you are not sure if this is the right approach for MapStruct?

In case you both agree this approach I can give it a try.

So the solution would allow things like this:

```java
@ValueMapping(source = MappingConstants.ANY_REMAINING, target = "FALLBACK")
FruitDto map(String source);
```

And I would also like to consider this:

```java
@ValueMapping(source = "FALLBACK", target = MappingConstants.NULL)
String map(FruitDto source);
```

So it is possible to use this in both ways: Enum -> String and String -> Enum

**Comment by artem-emelin** [comment]
Hi all, 
it would be really helpful to have a `String->Enum` mapper out of the box, instead of doing manual mappings

**Comment by IDoCodingStuffs** [comment]
I ran into this issue. Would like to start a pull request for this one unless someone is already working on it.

**Comment by Ryaryu** [comment]
I'm also running into this issue. It would be really helpful if it was implemented.

**Comment by sjaakd** [comment]
@Ryaryu I can take a look.

**Comment by sjaakd** [comment]
Resolved and merged to the master
