### ISSUE TITLE
Cannot use Enum convertor with Context

### ISSUE THREAD

**Issue by Kalich** [mapstruct/mapstruct#1564]
When I have any enum in source/target and use @Context, got compilation error: *method sourceEnumToDtoEnum in class DtoMapperImpl cannot be applied to given types;*

Problem is, that not generate _sourceEnumToDtoEnum_ methot with @Context parameter, but called.

I use MapStruct in version 1.2.0.Final.

Here is tests:

Source class:
`package maptest;
public enum SourceEnum {
	ONUS;
}
`

`package maptest;
public class Source {
	private SourceEnum sourceEnum;
	public SourceEnum getSourceEnum() {
		return sourceEnum;
	}
	public void setSourceEnum(SourceEnum sourceEnum) {
		this.sourceEnum = sourceEnum;
	}
}`

Target class:
`package maptest;
public enum DtoEnum {
	ONUS;
}
`

`package maptest; public class Dto {
	private DtoEnum dtoEnum;
	public DtoEnum getDtoEnum() {
		return dtoEnum;
	}
	public void setDtoEnum(DtoEnum dtoEnum) {
		this.dtoEnum = dtoEnum;
	}
}`

And mapper with @Context:
`package maptest;
import org.mapstruct.*;
@Mapper
public abstract class DtoMapper {
	@Mappings({
			@Mapping(source = "sourceEnum", target = "dtoEnum")
	})
	public abstract Dto fromSource(Source source, @Context Void theTypeDoesNotMatter);
}`

The generated implementation: 
`public class DtoMapperImpl extends DtoMapper {
    @Override
    public Dto fromSource(Source source, Void theTypeDoesNotMatter) {
        /* ... */
        dto.setDtoEnum( sourceEnumToDtoEnum( source.getSourceEnum(), theTypeDoesNotMatter ) );
        return dto;
    }
    protected DtoEnum sourceEnumToDtoEnum(SourceEnum sourceEnum) {
        /* ... */
    }
}`

**Comment by Kalich** [comment]
Workaround for this is implement own convertor with @Context as param. For the test case added to DtoMapper: `public DtoEnum convertEnum(SourceEnum source, @Context Void theTypeDoesNotMatter)`

**Comment by sjaakd** [comment]
Try 1.3beta. I fixed an issue wrt enumerations

**Comment by Kalich** [comment]
Thanks. 1.3.0.Beta1 work fine.
