### ISSUE TITLE
support mapper to convert Flux and Mono interfaces

### ISSUE THREAD

**Issue by mohsen-mahmoudi** [mapstruct/mapstruct#1565]
I use `spring boot-2` and `spring-webflux` in my project. Is there any support for `Flux<>` and `Mono<>` mapping in MapStruct now?

**Comment by mohsen-mahmoudi** [comment]
Yes. In **spring-data v2.0.7** we can use `ReactiveCrudRepository` that whole of methods returns `Mono<T>` or `Flux<T>`. on the other hand, we can use **sprint-webflux** reactive features in our rest controllers. we can return `Flux<T>` of `Mono<T>`.

For example, suppose that you have `Post` and `PostComments` entities and you wanna to get all comments. when you call findAll() method from `PostCommentsRepository`, we will have collection of `Flux<PostComments>`. And then you consider that you want to send `Flux<PostCommentsViewModel>` in response to the client. at now:

> **mapstruct** can not map `Flux<PostComments>` to `Flux<PostCommentsViewModel>` .
> for solving this problem, we must **create default method and implement mapping.**

**codes:**

```
@Entity
public class Post {
    @Column
    private String title;

    // other attributes
}
```

```
@Entity
public class PostComments {
    @Column
    private Post post;

    @Column
    private String comment;

    // other attributes
}
```

```
@Repository
public interface PostCommentsRepository extends ReactiveCrudRepository {
}
```

```
public class PostCommentsViewModel {
    private String postTitle;
    private String comment;
}
```

```
@Mapper(componentModel = "spring")
public interface PostMapper {

    PostMapper INSTANCE = Mappers.getMapper(PostMapper.class);

    @Override
    @Mapping(source = "postTitle", target = "post.title")
    Post mapToModel(PostViewModel viewModel);

    @Override
    @Mapping(source = "post.title", target = "postTitle")
    PostViewModel mapToViewModel(Post model);

    List<Post> mapListToModel(List<PostViewModel> viewModels);

    List<PostViewModel> mapListToViewModel(List<Post> models);

    default Mono<Post> mapMonoToModel(Mono<PostViewModel> viewModel) {
        return Mono.just(mapToModel(viewModel.block()));
    }

    default Mono<PostViewModel> mapMonoToViewModel(Mono<Post> model) {
        return Mono.just(mapToViewModel(model.block()));
    }

    default Flux<Post> mapFluxToModel(Flux<PostViewModel> viewModels) {
        return Flux.fromIterable(mapListToModel(viewModels.collectList().block()));
    }

    default Flux<PostViewModel> mapFluxToViewModel(Flux<Post> models) {
        return Flux.fromIterable(mapListToViewModel(models.collectList().block()));
    }
}
```

```
@Controller
public Class PostCommentsController {

    @Autowired
    private PostCommentsRepository iPostCommentsRepository;
    
    @Autowired
    private PostCommentsMapper postCommentsMapper;

    @GETMapping("/getAll")
    public Flux<PostCommentsViewModel> findAll() {
        return postCommentsMapper.mapFluxToViewModel(iPostCommentsRepository.findAll());
    }
}
```

If we don't  implement these methods: `mapFluxToViewModel`, `mapFluxToModel`, `mapMonoToViewModel` and `mapMonoToModel`, **mapstruct** can not automatically create mapping method and this error has been raised.!

```
[ERROR] The return type reactor.core.publisher.Mono<org.test.PostComments> is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
[ERROR] The return type reactor.core.publisher.Mono<org.test.PostCommentsViewModel> is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
[ERROR] The return type reactor.core.publisher.Flux<org.test.PostComments> is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
[ERROR] The return type reactor.core.publisher.Flux<org.test.PostCommentsViewModel> is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
```

If implementation for these reactive interfaces `Flux<T>` and `Mono<T>` in **mapstruct** is created, then we will not need to implement those.
thanks a lot.

**Comment by filiphr** [comment]
In my opinion it would be interesting if we have a way to plug custom logic like this into MapStruct. As the only thing that we should do is to create a mapping between `PostViewModel` and `Post` and do the mapping.

The current example is wrong from the point of view of react based programming as you are doing blocking calls. I think that one should use [`Flux#map`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#map-java.util.function.Function-) and [`Mono#map`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#map-java.util.function.Function-) instead. 

Having said that you can easily write something like:


```
@Controller
public Class PostCommentsController {

    @Autowired
    private PostCommentsRepository iPostCommentsRepository;
    
    @Autowired
    private PostCommentsMapper postCommentsMapper;

    @GETMapping("/findAll")
    public Flux<PostCommentsViewModel> findAll() {
        return iPostCommentsRepository.findAll().map(postCommentsMapper::mapToViewModel)
    }
}
```

Looking at this (how easy it is to invoke the current mapper methods) I am inclined to close this one. Would you agree @mohsen-mahmoudi?

**Comment by sjaakd** [comment]
I think you can provide the return type. Checkout the possibilities in @Mapping. You could implement an object factory method, as the error message says..

**Comment by mohsen-mahmoudi** [comment]
Hi @filiphr, this is very nice and i agreed. It seems i made mistake, thanks you. but in some case like below, we use `Pageable<PosComments>` and `Pageable<PosCommentsViewModel>`. Let me show you the code:

```
@Getter
@Setter
public class Pageable<T> {
    private int pageNumber;
    private int totalRecords;
    private int pageSize;
    private Flux<T> entityList;
}
```
With this class, we can create paging result of data. We must create a method in `PostCommentsMapper` for map `Pageable<PosComments>` to`Pageable<PosCommentsViewModel>` and i can not access to [Flux#map](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#map-java.util.function.Function-) function.! How we can map these cases?

**Comment by filiphr** [comment]
I would argue that what you are trying to do with the `Pageable` is against the notion of non blocking reactive programming. As in order to get the total records you have to execute a total count which is thus blocking. Have a look at [this](https://stackoverflow.com/questions/46384618/how-apply-pagination-in-reactive-spring-data) Stackoverflow question and the comments on the answer itself. The questions has been answered Mark Paluch from the Spring Data team.

In theory it is easy to provide what you are looking for by providing of a default mapping between your different Flux like:

```
@Mapper
public interface PostCommentsMapper {

    default Flux<PostCommentsViewModel> fromFlux(Flux<PostComments> flux) {
        return flux.map(this::map);
    }

    PostCommentsViewModel map(PostComments source);
}
```

How are you even creating the paging results without doing extra non blocking calls?
