### ISSUE TITLE
Setters on a Builder super class are not called

### ISSUE THREAD

**Issue by kaweston** [mapstruct/mapstruct#1566]
As per the following example if my Builder extends AbstractBuilder then the 'id' setter will not be called

```java
@SuppressWarnings("unchecked")
    static abstract class AbstractBuilder<T extends AbstractBuilder<T>> {
        String id;

        public T id(final String id) {
            this.id = id;
            return (T) this;
        }
    }
```

**Comment by filiphr** [comment]
@kaweston thanks for reporting it. It seems that it has something to do with the generics. We are going to have a look at it

**Comment by kaweston** [comment]
@filiphr Thanks for getting on to it, I certainly count as one that has been waiting for solid builder support and am happy to help out.

On a separate issue; is there any plans to implement a decorator that passes the builder as the delegate?  I have experimented a bit using the Mapping annotation to perform a many to one attribute transformation which worked quite nicely using builders but would like to have the option of using a decorator.

**Comment by filiphr** [comment]
@kaweston regarding your separate issue can you please open a new issue for that?

In any case have you tried using `@AfterMapping` or `@BeforeMapping`, maybe you can solve your problem via that
