### ISSUE TITLE
Converting Object to List of Object

### ISSUE THREAD

**Issue by saravanan77** [mapstruct/mapstruct#1568]
**Source Object:**

```
class Source {
   Field1 field1;
   String field2;
   String field3;
}

class Field1 {
   String value;
}
```

**Target Object:**

```
class Target {
   List<IndexValue> values;
}

class IndexValue {
   int index;
   String value;
}

```

**Expected code to be generated:**

```
Target target = new Target();
target.values = new ArrayList<>();

if (null checks) {
     target.values.add(new IndexValue(1, source.getField1().getValue()) ; 
}
if (null checks) {
     target.values.add(new IndexValue(2, source.getField2()) ; 
}
if (null checks) {
     target.values.add(new IndexValue(3, source.getField3()) ; 
}

```
One solution i found in https://github.com/mapstruct/mapstruct/issues/506
@AsList - Write all code ourself.  I like to avoid writing null check codes.

Is it possible to do something like

```
@Mapping(source="field1.value", target="values", mappingFunction="createIndexValue(1, $source)")
@Mapping(source="field2", target="values", mappingFunction="createIndexValue(2, $source)")

IndexValue createIndexValue(int index, String fieldValue) {
   return new IndexValue(index, fieldValue)
}
```

Please let me know if there is any other way to do this mapping better

**Comment by filiphr** [comment]
@saravanan77 I think that what you are proposing is overly complex for MapStruct at the moment. If you really need something like this it is not that difficult to do it in a generic way on your own. Therefore I am going to close this issue. If someone has a better to way to achieve this please do let us know.
