### ISSUE TITLE
Couldn't retrieve @Mapper annotation with uses = {GeneratedMapper.class}

### ISSUE THREAD

**Issue by emanuel1993** [mapstruct/mapstruct#1570]
Hello, we have the following example: class AMapper which is annotated with @Mapper(uses={BMapper.class}) and we have the class B, which is annotated with @MyMapperAnnotation, which in turn generates the BMapper class annotated with @Mapper, in the same package as AMapper (using my custom processor).

When doing an Eclipse build, everything works fine, but when doing a command line build (like 'mvn compile'), it throws an exception on AMapper with the message 'Couldn't retrieve @Mapper annotation'.

On a closer look in the mapper source code, upon entering AMapper (in which it enters before BMapper is created), it goes up to MethodRetrievalProcessor, and there it creates a MapperConfiguration with uses = {\<error\>}, thus rendering the corresponding mapper prism invalid.

My suggestion is when it detects an Error Type class inside of @Mapper.uses, it should throw an exception like TypeHierarchyErroneousException which in turn causes the current element to be added to the set of deferredMappers.

**Comment by filiphr** [comment]
Closing this since it has been fixed by #2056
