### ISSUE TITLE
Allow nullValueCheckStrategy on @BeanMapping t not have twice more classes/interfaces

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1571]
This one I could raise the very first simply because this limitation once brought me to Mapstruct tracker and it is quite big limitation. Not only you have to declare aka "Creators" and "Updaters" to do both operations, but also you need to inject those additionally into you services. Updaters with `nullValueCheckStrategy = ALWAYS` does magic with `patch`ing persistent entities. There is a wonderfully suitable "@BeanMapping" annotation - that would be great if able to specify it there.

**Comment by sjaakd** [comment]
Should not be too difficult. I thought it was already in '@BeanMapping'.  Or perhaps there is already an issue for it.

**Comment by sjaakd** [comment]
strangest thing.. the javadoc states that its also possible to specify on mapping level.. however that has never been implemented.

**Comment by sjaakd** [comment]
@soberich .. give it a shot.. Its on the master. The option is now on `BeanMapping` level and on `Mapping` level.
