### ISSUE TITLE
Deadlock while initializing Mappers

### ISSUE THREAD

**Issue by DerKanzler** [mapstruct/mapstruct#1572]
I have several Classes which inherit from a common parent Linkable which has several objects I need to map. Therefore I created a MetaMapper which is used by every other mapper.
Also another mapper (AddressMapper) which uses MetaMapper is used by some other mappers which also uses MetaMapper.

Now the problem is sometimes (too often) the initialization of the mappers causes a deadlock in the threads. After that the JVM (application) has to be restarted.

The chain of the used mappers in the "uses" annotation causes the problem in the clinit of these referenced mappers.

![image](https://user-images.githubusercontent.com/877040/43501939-6937ac12-9558-11e8-9ea8-07fd0a9584e5.png)
![image](https://user-images.githubusercontent.com/877040/43501951-798447e2-9558-11e8-93ec-9e61909fc9ee.png)
![image](https://user-images.githubusercontent.com/877040/43501963-89f8fb04-9558-11e8-9651-fb85f91501e8.png)

I attached a small project to reproduce the error. It doesn't always occur the first time. Just retry it then.
Run it in debug mode in our IDE and when it hangs take a look at the threads.

I hope you can find and resolve this issue.
Thank you!

[uses-deadlock.zip](https://github.com/mapstruct/mapstruct/files/2248062/uses-deadlock.zip)

**Comment by sjaakd** [comment]
@DerKanzler .. Sorry. it took along time to look at this.. But one observation: you do use both the BSC plugin and the Maven-Compiler-Plugin.. Thats 2 plugins generating the same code. Please use one.

**Comment by sjaakd** [comment]
My best guess this is related to #1163 (there's some cyclic dependency). Can you check this?

**Comment by sjaakd** [comment]
Why did you put the `@Mapper` annotation on `MetaMapper`? There's nothing to be generated there by MapStruct..
