### ISSUE TITLE
Add annotations to Generated code

### ISSUE THREAD

**Issue by vadim-shb** [mapstruct/mapstruct#1574]
I just want to share an idea... I think it would be great to be able to add any annotations you want to generated classes/methods.
Something like this:
```
@Annotated({
  @Component,
  @Qualifier("fooMapper")
})
@Mapper
public interface FooMapper {
  @Annotated({
    @Cacheable(value = "cache", key = "mappedFoo #foo.id" )
  })
  Foo map(Foo foo);
}
```

So, the content of `@Annotated` would be added to generated code like this:
```
@Component,
@Qualifier("fooMapper")
public class FooMapperImpl implements FooMapper {
  @Cacheable(value = "cache", key = "mappedFoo #foo.id" )
  Foo map(Foo foo) {
  ...
  }
}
```
With this functionality we wouldn't need @Mapper(componentModel = "spring") for example, and many annotation-based issues would gone.

**Comment by sjaakd** [comment]
Interesting. I'm not an expert on Spring but to my understanding some of the annotations end up on a referenced mapper instance. Like '@Inject' for CDI. How would that work with your idea?

**Comment by vadim-shb** [comment]
I'm not sure if I've understood your question correctly, so please rephrase it then, or add an example...

In context of Spring `@Inject` would work just fine with the example above (if package with FooMapper.java is scanned for beans by Spring):

```
@Component
public class SomeBean {
  @Inject
  @Qualifier("fooMapper")
  FooMapper mapper

  ...
}
```

**Comment by sjaakd** [comment]
When you use a mapper, ('@Mapper#use') MapStruct will generate that code when the component model is Spring. Don't know if it also evaluates the annotations on the used mapper

**Comment by vadim-shb** [comment]
Ok, I've never used `@Mapper#use`, and after quick pick I still not see where I would like to use it, but it was probably a mistake to talk that 

> we wouldn't need @Mapper(componentModel = "spring")

But it still might be useful in different situations... Leave it here to discuss...

**Comment by filiphr** [comment]
@vadim-shb the request is interesting. 

Regarding:

>With this functionality we wouldn't need @Mapper(componentModel = "spring") for example, and many annotation-based issues would gone.

This is wrong. If you use the default `componentModel` than when you use other mappers with `Mapper#uses` MapStruct will use the `Mappers` factory to create the used mapper or invoke it's default constructor. This is wrong.

Having said that, the other part for annotating the methods might be interesting. However, I am not entirely sure about it. Your example doesn't really make sense to me, why would you want to cache the DTOs? Are you seeing a performance hit when the mapping is invoked?

**Comment by vadim-shb** [comment]
>Your example doesn't really make sense to me

It makes no sense for me either. I made it up quickly just to show that this functionality should be implemented for method annotations as well as for class annotations.

It's general functionality and it may be used in lot's of ways by different frameworks.

Let's made up a better example with Spring:
```
public interface FooMapper {
  Foo map(Foo foo);
}
```

```
@Annotated({
  @Component,
  @Lazy,
  @Profile("prod")
})
@Mapper
public interface FooMapperQa extends FooMapper {
  Foo map(Foo foo);
}
```

```
@Annotated({
  @Component,
  @Profile("qa")
})
@Mapper
public interface FooMapperQa extends FooMapper {
  @Annotated({
    @Loggable
  })
  Foo map(Foo foo);
}
```

```
@Service
public class SomeBean {
  @Inject
  FooMapper mapper;

  ...
}
```
I don't know an easy way to do such configuration now.

**Comment by LinkedList** [comment]
I am too vouching for this, as now there is no way to add logical name to generated mapper.
My problem could be also solved if there was a parameter on `@Mapper` that would provide value for `@Component` - see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/stereotype/Component.html#value--

However provided example: 
```
@Annotated({
    @Component("foo")
})
```
would work as well..

**Comment by c9pr3** [comment]
Would need something like this as well for @Transactional

**Comment by mjustin** [comment]
I just ran across a completely non-Spring situation where this could be useful.  I marked one of my mapper methods as `@Deprecated`, since I hope to remove it in a future release, and want it documented in the code.  However, since the generated method is neither `@Deprecated` nor has `@SuppressWarnings("deprecation")`, I get a compilation warning for the deprecation:

```
/path/to/project/build/generated/sources/annotationProcessor/java/main/com/example/ExampleMapperImpl.java:90: warning: [deprecation] map(ExampleTarget) in ExampleMapper has been deprecated
    public ExampleTarget map(ExampleSource source) {
```

Granted, this could (and perhaps should) be solved by a deprecation-specific MapStruct feature.  However, it could also be solved by being able to specify that I want to add either of these annotations to the generated method.

**Comment by famod** [comment]
Me team just ran into this "missing feature": We use `componentModel=cdi` and mostly mapping interfaces.
We now wanted to add cdi interceptor binding annotations to the generated MapperImpl classes, but there is no way to do that.

As a workaround, we'll have to migrate to abstract mapping classes.

**Comment by payne911** [comment]
My team would love such a feature as well.
We are trying to exclude the generated classes from the unit-test code coverage in our pipeline via a custom annotation. It would be great to be able to propage that annotation to the implementation of the mappers.

**Comment by Zegveld** [comment]
@Payne911, why not have the generated classes live in a second source-folder which is not analyzed for coverage? 
[Let's continue discussing this here, not to sidetrack this issue.](https://github.com/mapstruct/mapstruct/discussions/2769)

**Comment by Zegveld** [comment]
I've been looking into a way to implement this.

I did not find a way to create an annotation that would allow the following notation:
```
@AnnotateWith( {
    @Deprecated,
    @AnnotationWithParameters( param1="value", param2="otherValue" )
} )
```

What I did find that might work is the following, although the autocomplete behavior of the IDE would be lost:
```
@AnnotateWith( Deprecated.class )
@AnnotateWith( type=AnnotationWithParameters.class, parameters = {
    @AnnotateWith.Parameter ( key = "param1", value = "value" ),
    @AnnotateWith.Parameter ( key = "param2", value = "otherValue" )
} )
```

wdyt, @sjaakd and @filiphr ? Would this be the way to go, or is there perhaps a better way to support the initial idea?

**Comment by filiphr** [comment]
I've missed the comment about the `@Deprecated` from @mjustin:

>I  just ran across a completely non-Spring situation where this could be useful. I marked one of my mapper methods as `@Deprecated`, since I hope to remove it in a future release, and want it documented in the code. 

I've created #2773 for this.

Regarding the `@Generated` from @payne911:

>But maybe another way to approach this would be for MapStruct to have its own `@Generated` class and to change the Retention Policy from `SOURCE` to either `RUNTIME` or `CLASS`, as explained [there](https://www.baeldung.com/jacoco-report-exclude#excluding-with-custom-annotation). That is how Lombok does it.

I do not agree with this because I do not agree that the code generated by MapStruct should not be tested and be unverified. We strive for generating code that looks like it has been written by a person, which means that it shouldn't have warnings. The generated code usually is simple, but there can be complex things due to the different configuration options we have, you should most definitely test that the mappings that are generated are mapping your data as you would expect.

Regarding the proposal from @Zegveld.

>```java
>@AnnotateWith( {
>    @Deprecated,
>    @AnnotationWithParameters( param1="value", param2="otherValue" )
>} )
>```

That would be ideal, unfortunately Java doesn't allow doing that. Lombok has their experimental [onX](https://projectlombok.org/features/experimental/onX) for supporting that, but that only works for them since they are changing the byte code of the class itself.

>What I did find that might work is the following, although the autocomplete behavior of the IDE would be lost:

>```java
>@AnnotateWith( Deprecated.class )
>@AnnotateWith( type=AnnotationWithParameters.class, parameters = {
>    @AnnotateWith.Parameter ( key = "param1", value = "value" ),
>    @AnnotateWith.Parameter ( key = "param2", value = "otherValue" )
>} )
>```

This is actually not that bad of an idea. We will need to provide parameters for the different parameter types of an annotation but I think it can work. People can also use their own composed meta annotations and use use `@AnnotateWith( MyCustomAnnotation.class )`. We will need to be a bit careful with the component model annotations that we are already adding, but it is doable.

**Comment by Zegveld** [comment]
> We will need to be a bit careful with the component model annotations that we are already adding, but it is doable.

Concerning that, I was thinking that perhaps the `@Named` annotation on the mapper could be transferred over as the name for the mapper in the annotation of the component model.
For example:
```
@Named( "MyOwnMapper" )
@Mapper( componentModel = "spring" )
interface Mapper {
```
would result in:
```
@Component( "MyOwnMapper" )
class MapperImpl implements Mapper {
```
Perhaps the above could be an issue by itself.


Concerning the `@AnnotateWith` and `@AnnotateWith.Parameter` I think that we will get the following classes:
```
@Repeatable( AnnotateWiths.class )
@Retention( SOURCE )
@Target( { TYPE, METHOD } )
public @interface AnnotateWith {
    Class<? extends Annotation> value();

    Parameter[] parameters() default {};

    @interface Parameter {
        String key();

        String stringValue() default ""; // used for having the value as a string.
        String objectValue() default ""; // used when the value is not a string.
    }
}
```

Example:
```
@AnnotateWith( MyCustomAnnotation.class )
@AnnotateWith( value=MyCustomAnnotationWithParameters.class, parameters = {
   @AnnotateWith.Parameter ( key = "stringParam", stringValue = "value" ),
   @AnnotateWith.Parameter ( key = "classParam", objectValue = "java.lang.String.class" ),
   @AnnotateWith.Parameter ( key = "intParam", objectValue = "1234" )
} )
```
would result in:
```
@MyCustomAnnotation
@MyCustomAnnotationWithParameters( stringParam = "value", classParam = java.lang.String.class, intParam = 1234 )
```

How extended to we want to protect the user against mistakes with `@AnnotateWith` usage?
There are several things that can go wrong, that cause the generated mapper code to not compile:
1. The annotation is not allowed at that location.
2. The parameter does not exist on the annotation.
3. The parameter value is of the wrong type.

**Comment by filiphr** [comment]
>Concerning that, I was thinking that perhaps the `@Named` annotation on the mapper could be transferred over as the name for the mapper in the annotation of the component model.

We can't do that, because `@Named` is used for qualifying methods / mappers. If a mapper is annotated with `@Named` then it won't be automatically used for mapping custom types.

>Concerning the `@AnnotateWith` and `@AnnotateWith.Parameter` I think that we will get the following classes:

I don't like the `stringValue` and `objectValue`, I think that we need to have the actual values that are supported for an annotation.

e.g.

```java
@Repeatable( AnnotateWiths.class )
@Retention( CLASS )
@Target( { TYPE, METHOD, ANNOTATION_TYPE } )
public @interface AnnotateWith {
    Class<? extends Annotation> value();

    Parameter[] parameters() default {};

    @interface Parameter {
        String key();

        short[] shorts() default {};

        byte[] bytes() default {};

        int[] ints() default {};

        long[] longs() default {};

        float[] floats() default {};

        double[] doubles() default {};

        char[] chars() default {};

        boolean[] booleans() default {};

        String[] strings() default {};

        Class<?>[] classes() default {};
    }
}
```

This makes it easy to use statics and so on. This is similar to the JUnit 5 [`ValueSource`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/provider/ValueSource.html). An annotation also allows having enums, but for those we will have to use the `strings` and determine the enum value on our own. 

Also the `ElementType` should be:

* `TYPE`
* `METHOD`
* `ANNOTATION_TYPE` - in order to allow meta annotations

With the the example would look like:

```java
@AnnotateWith( MyCustomAnnotation.class )
@AnnotateWith( value=MyCustomAnnotationWithParameters.class, parameters = {
   @AnnotateWith.Parameter ( key = "stringParam", strings = "value" ),
   @AnnotateWith.Parameter ( key = "classParam", classes = String.class ),
   @AnnotateWith.Parameter ( key = "intParam", ints = 1234 )
} )
```

>How extended to we want to protect the user against mistakes with `@AnnotateWith` usage?

We want to provide as much information to the user as possible. We can easily detect certain things so we can easily

>There are several things that can go wrong, that cause the generated mapper code to not compile:
> 1. The annotation is not allowed at that location.

We can have a compile error pointing out the mistake.

> 2. The parameter does not exist on the annotation.

Again, compile error pointing out the mistake.


>3. The parameter value is of the wrong type.

Also a compile error pointing out that that it isn't supported.

**Comment by Zegveld** [comment]
I'm going to give this a go. I'm quite interested in seeing how much information we can get from the custom annotations and such. Also curious as to what we can achieve for the enums.

**Comment by filiphr** [comment]
>I'm going to give this a go.

Awesome, looking forward to it.

>I'm quite interested in seeing how much information we can get from the custom annotations and such. Also curious as to what we can achieve for the enums.

You should be able to get a lot of information through the `TypeElement` and its method.

**Comment by Zegveld** [comment]
I'm pretty far, now to see if I can add the location check and meta-annotation stuff.

**Comment by Zegveld** [comment]
@filiphr, what do you mean with the following?
> ANNOTATION_TYPE - in order to allow meta annotations

That people can use the `@AnnotateWith` inside their own meta annotations?
But MapStruct doesn't support meta annotations yet, does it?

**Comment by Zegveld** [comment]
Just noticed that we have support for meta annotations for `@Mapping` and `@SubclassMapping` already. 
So I'll be changing the current implementation to match that one.

**Comment by NadChel** [comment]
Can I ask what is the rationale behind this design decision involving class literals? As opposed to what the OP suggested
```java
  @Annotated(@Cacheable(value="cache", key="mappedFoo #foo.id" ))
```
It appears more straightforward and flexible than
```java
  @AnnotatedWith(value=Cacheable.class, elements={@Element(strings="cache"), @Element(name=key, strings="mappedFoo #foo.id")})
```
I'm sure there was reasoning behind it that I don't yet realize
