### ISSUE TITLE
FQN of LocalDateTime is used when a simple name is possible

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1576]
When using the `JavaLocalDateToDateConversion` we generate a code that looks like:

```
if ( as.getPromotionDate() != null ) {
    article.setPromotionDate( java.time.LocalDateTime.ofInstant( as.getPromotionDate().toInstant(), ZoneOffset.UTC ).toLocalDate() );
}
```

The code should look like:

```
if ( as.getPromotionDate() != null ) {
    article.setPromotionDate( LocalDateTime.ofInstant( as.getPromotionDate().toInstant(), ZoneOffset.UTC ).toLocalDate() );
}
```

The `java.time.LocalDateTime` is not necessary to be FQN, as it is the only `LocalDateTime`. The actual problem is that when Joda time is present than the Joda types are loaded in the `Conversion` which leads to them being part of the `importedQualifiedTypesBySimpleName` in our `TypeFactory`. Seems that we use the `Type` in the Conversion [`Key`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java#L305). However, looking into that code it seems that we can easily use the FQN of the types (without the need to load the `Type`).

I see 2 ways to solve this:

* Add a flag to the `TypeFactory` to load a type without marking it as imported
* Use `String` in the Conversion `Key`

**Comment by jwcarman** [comment]
Is readability of the generated code a design goal of MapStruct?

**Comment by filiphr** [comment]
@jwcarman yes readability is one of the design goals of MapStruct. We try to have a code that reads and debugs as nice as possible. Have you noticed something that we need to address?

**Comment by jwcarman** [comment]
No, not at all.  I was asking in the context of this issue.  I will say that the generated code is certainly very readable, so that’s a nice feature!  If readability isn’t a concern, then I’d just use FQNs everywhere.  It would certainly make the process simpler.  But, it is really nice to have tidy code to view.  Thanks for the reply and thanks for all the hard work on this library!

**Comment by filiphr** [comment]
Thanks for the nice words. It is really appreciated to see that people are enjoying using the library.

Yes using FQNs everywhere will certain make it much easier, but then it will be really difficult to read it 😉.

**Comment by jwcarman** [comment]
No problem.  Open source folks don’t get thanked enough for their countless hours of coding for the greater good.  Looking forward to beta2!

**Comment by sjaakd** [comment]
The solution is not as simple as it initially looks like.. There's interference between the java `LocalDateTime` and the joda `LocalDateTime`. A `getType()` marks it also as imported.
