### ISSUE TITLE
Control initial destination collection size

### ISSUE THREAD

**Issue by Matv1989** [mapstruct/mapstruct#1579]
HI all,
Regarding https://github.com/mapstruct/mapstruct/issues/777
I have a collection which does not support size() method and I didn't find a way to control if this method should or shouldn't be invoked during destination collection creation.
Hence, my mapping is failing with UnsupportedOperationException. Is there a way to generate destination collection with a default constructor, e.g. ArrayList, and do not provide initial capacity?
If no - I believe that it is a good point for enhancement.

**Comment by sjaakd** [comment]
You might want to try including a factory method. Otherwise you implement your own mapping. Have a look at the documentation.

**Comment by Matv1989** [comment]
Hi @sjaakd ,
I got your point. But I think that something like annotation would be more convenient.
For now I've just created a custom mapper

**Comment by sjaakd** [comment]
Did you also try a factory method? That's the intended way for this use case.,

**Comment by Matv1989** [comment]
Hi @sjaakd ,
Thanks for you reply. I've managed to create collection without initial size, by mapping an Iterable object. This is the most convenient way I suppose.
I'm new to mapstruct, so sorry for bothering you :)

**Comment by sjaakd** [comment]
No problem.

I still think you should try factory methods. This way you only leave the construction of the arraylist to the method. Have a look at the doc.

BTW: For direct support/questions we usually use gitter. Give it a try 😀
