### ISSUE TITLE
Removing joda time?

### ISSUE THREAD

**Issue by almothafar** [mapstruct/mapstruct#1580]
I think there are many new features from Java 8 to 10, and one of the best improvement around this is DateTime things for sure, I was able to remove all joda times references from all projects that I worked in, but this library seems to bring it back to my dependances.

As many benchmarks seem Java DateTime as better than Joda, so I think it maybe the time to move from it?

http://java-performance.info/jsr-310-java-8-datetime-library-performance-well-joda-time-2-3-j-u-calendar/

http://java-performance.info/joda-time-performance/

**Comment by filiphr** [comment]
Can you please show the `mvn dependencies:tree` and the dependency on joda from MapStruct.

MapStruct does not have a direct dependency on Joda time. However, if Joda time is present during the annotation processing, MapStruct will be able to recognize it and allow out of the box support for mapping those types.

**Comment by almothafar** [comment]
@filiphr oh! I'm using sbt, but nevermind, it is my fault, it as Jackson who uses it not mapstruct.
