### ISSUE TITLE
@AfterMapping not working for mapping methods with multiple source parameters

### ISSUE THREAD

**Issue by anticlockwise** [mapstruct/mapstruct#1584]
I have the following mapper:

```java
@Mapper
public interface DomainMapper {
  DomainObjDTO convert(final DomainObjA objA, final DomainObjB objB,
        @Context final Locale locale);

  @AfterMapping
  default void fillInProperties(final DomainObjA objA, final DomainObjB objB,
        @MappingTarget final DomainObjDTO output, @Context final Locale locale) {
    ...
  }
}
```

In the generated implementation, the `@AfterMapping` method was not called.

**Comment by anticlockwise** [comment]
OK, nvm, figured it out, I'm using Lombok builder, so the targetType is determined to be the builder class of the `DomainObjDTO`. Changing `@MappingTarget` to `DomainObjDTO.DomainObjDTOBuilder` worked.

**Comment by filiphr** [comment]
Glad that it was resolved. Thanks for letting us know

**Comment by filiphr** [comment]
You can also follow https://github.com/mapstruct/mapstruct/issues/1454. One of the points is to expose the type being build `DomainObjDTO`  in `@AfterMapping` methods

**Comment by benjvoigt** [comment]
I just stumbled upon this issue using builders. Can this information be added to the docs at http://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after?

**Comment by sjaakd** [comment]
> I just stumbled upon this issue using builders. Can this information be added to the docs at http://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after?

Sure: just issue a PR. The documentation is generated from: https://github.com/mapstruct/mapstruct/tree/master/documentation/src/main/asciidoc

**Comment by imochurad** [comment]
I am seeing the same issue...
So, how do I force @AfterMapping to use a DTO default constructor instead of a Lombok builder? Is there a way?

**Comment by filiphr** [comment]
`@AfterMapping` doesn't use any constructors. Have a look at https://github.com/mapstruct/mapstruct/issues/1584#issuecomment-413975774 to see how to use the builder in the `@AfterMapping`. 

In case you don't want to use builders, you can disable them. This is explained in [Using builders](https://mapstruct.org/documentation/stable/reference/html/#mapping-with-builders)

**Comment by imochurad** [comment]
It's interesting that you say that. I have 2 mappers for 2 different DTO/BO pairs. Both pf those mappers have @AfterMapping annotated methods. The target objects in both cases use Lombok @Builder. And in one case, mapper implementation is using setters to construct an object and then invokes the method with @AfterMapping, whereas in the other case, implementation relies on a builder and it doesn't invoke @AfterMapping method.
It seems that the strategy for picking builder vs setters is random. Is it a bug?

**Comment by filiphr** [comment]
That could be linked to https://github.com/rzwitserloot/lombok/issues/1538. By default MapStruct uses the builder if it is there (and it can see it)
