### ISSUE TITLE
Possibility to map immutable objects using AllArgsConstructors

### ISSUE THREAD

**Issue by eximius313** [mapstruct/mapstruct#1589]
I see that version `1.3.0` of Mapstruct focuses on immutable objects, wich is great. 
Unfortunately, currently only builders are supported. 
But what about objects that have all-argument constructors (or created by Lombok's `@AllArgsConstructors`) ? Can you please support that?

**Comment by sjaakd** [comment]
duplicate of #73

**Comment by filiphr** [comment]
@eximius313 this is also one big requested feature of MapStruct. This release we tackled the builder support and hopefully we can tackle the constructor support in the release after 1.3 😄

**Comment by eximius313** [comment]
@filiphr, thank you for the information ;)
