### ISSUE TITLE
Inherit configuration for sub classes using @InheritConfiguration?

### ISSUE THREAD

**Issue by rroehrig** [mapstruct/mapstruct#1593]
Either I don't know how to write or It's a feature request.

I have the following setup:

**Sources**:
ObjectA
ObjectB

**Targets**:
Base
Sub (which inherits from Base)

I was assuming that I can do the following:
```
@Mapper
public interface ObjectMapper {
  @Mapping(source = "a", target = "aa")
  Base mapBase(ObjectA objectA); 

  @InheritConfiguration
  @Mapping(source= "objectB.b", target = "bb")
  Sub mapSub(ObjectA objectA, ObjectB objectB); 
}
```

However, mapstruct prints the warning: `Unmapped target properties: "bb".` for method mapSub.

**Comment by sjaakd** [comment]
@rroehrig .. any news on this? I created [this PR.](https://github.com/mapstruct/mapstruct/pull/1630) But I can't reproduce.

**Comment by rroehrig** [comment]
Sorry, will let you know once I'm back to this project. May take a few more days.
