### ISSUE TITLE
Support for conversion between java.time.Instant and java.util.Date

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1595]

**Comment by JaquelineP** [comment]
Can anyone give a hint on how to start with this issue? Do I have to extend the NormalTypeMappingMethod?

**Comment by sjaakd** [comment]
@JaquelineP ..Depends a bit what code you want to generate. For one-lines we typically use type conversion. Have a look [here](https://github.com/mapstruct/mapstruct/tree/master/processor/src/main/java/org/mapstruct/ap/internal/conversion). For multi line mapping methods there are [built-in methods](https://github.com/mapstruct/mapstruct/tree/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin).

**Comment by sjaakd** [comment]
Nice that you want to help out..

**Comment by gunnarmorling** [comment]
Yeah, a conversion should suffice, it's just one method call on Date. The
other thing to do (besides testing) would be to add the new built-in
conversion to the dcos (see the "documentation" module)

Thanks, @JaquelineP!

**Comment by filiphr** [comment]
A good example is [`JavaLocalDateToDateConversion`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateToDateConversion.java).

Thanks for having a look @JaquelineP

**Comment by filiphr** [comment]
@JaquelineP did you look into this? If you haven't then some of us can implement this without a problem.

**Comment by sivviswa22** [comment]
I would like to attempt to make this change.

**Comment by filiphr** [comment]
Hey @sivviswa22 if you ask me no problem. Just not sure whether @JaquelineP did something. We want to do it as soon as possible so we can release the next beta, so if you can do it it would be great 😀
