### ISSUE TITLE
Missing imports for Immutables

### ISSUE THREAD

**Issue by danielsonjh** [mapstruct/mapstruct#1596]
I'm trying to use Immutables 2.6.3 with mapstruct 1.3.0.Beta1, and ran into an issue with a missing import statement after generating the MapperImpl.

I have an Immutable object set up as such
```java
package com.example.items

@Value.Immutable
public abstract class Item {
    public abstract UUID id();
    public abstract UUID itemType();
}
```

The generated MapperImpl does contain usages of `ImmutableItem.builder()` as expected:
```java
import com.example.items.ImmutableItem.Builder

Builder item= ImmutableItem.builder();
```

But the statement `import com.example.items.ImmutableItem` is missing, which prevents the project from` compiling. Weirdly enough, there is a `import com.example.items.ImmutableItem.Builder` 

I've also tried modifying the mapper like this to no success: `@Mapper(imports = {ImmutableItem.class})`

Is this a known issue? Or have I set something up incorrectly?

**Comment by filiphr** [comment]
This looks strange. We actually have integrations tests with Immutables and they are working properly. Can you please share a project that this can be reproduced so we can have a look at it?

Using `@Mapper(imports = {ImmutableItem.class})` should work in any case. Maybe there is . some bug

**Comment by danielsonjh** [comment]
Sorry for the delay here it is https://github.com/danielsonjh/mapstruct-immutables

While creating the example repo I think I realized what the issue might be. It was working initially when I had the Item and ItemDTO classes in the same package, but not after.

**Comment by danielsonjh** [comment]
Also somewhat unrelated, and possibly more of a stylistic choice than a bug, but mapstruct can't find properties for Immutables properties created without `get` prefixes. This is the recommended style for Immutables it seems:
```Java
@Value.Immutable
public abstract class Item {
    public abstract UUID id();
    public abstract UUID itemType();
}
```

If this is considered a problem, I can open a new issue.

**Comment by sjaakd** [comment]
You can use the naming strategy  SPI to fix that. Normally MapStruct adheres to the bean convention. another v user was working on a complete example with protobuf I remember. Take care about standard methods as toString and getClass

**Comment by talbx** [comment]
I had the same problem regarding the missing import statements in the generated classes.
The comment by @filiphr 

> Using @Mapper(imports = {ImmutableItem.class}) should work in any case.

solved it. Thank you!

**Comment by danielsonjh** [comment]
`@Mapper(imports = {ImmutableItem.class, ImmutableItemDTO.class})` does work with some effort, but the process feels pretty bad.

There are 2 problems:
1. The project must be built first with the mapper annotation commented out since the line contains classes that don't exist yet. This is a pain to deal with whenever `clean` is run on the project.
2. Even after the ImmutableItem.class and ImmutableItemDTO.class was created in the first build, since it is a generated source, the following line needs to be added to allow the gradle project to build:
`sourceSets.main.java.srcDirs = ['build/generated/source/apt/main','src/main/java']`

This could easily deter people from using this feature, which feels like a shame.

Possible solutions:
1. If there was an option for the `imports` parameter to take `String` instead, then this might solve both problems
```Java
@Mapper(imports = {"com.example.domain.ImmutableItem", "com.example.dto.ImmutableItemDTO"})
```
It would allow compilation even if the Immutables annotation processor did not run, and because the generated classes are not being referenced in the main source, the sourceSets will not have to be modified in gradle projects.

Let me know if there are other solutions. Thanks!

**Comment by sjaakd** [comment]
> @Mapper(imports = {ImmutableItem.class, ImmutableItemDTO.class}) does work with some effort, but the process feels pretty bad.

Mapper imports is a feature that is 
1. used in combination with the expression feature
2. used when there are shortcommings in MapStruct

As @filiphr indicated, its probably 2. We need to analyse and solve problems in the next beta (hence we have beta's  :smile: )



> @Mapper(imports = {"com.example.domain.ImmutableItem", "com.example.dto.ImmutableItemDTO"})

The problem occurs when there are 2 code generating framework active at the same time.  The solution above is not type-safe on other cases.

**Comment by filiphr** [comment]
@danielsonjh first thanks a lot for the example project. Will have a look and try to fix this.

I have some multiple questions in regard some of your comments.

For https://github.com/mapstruct/mapstruct/issues/1596#issuecomment-416804582

>Also somewhat unrelated, and possibly more of a stylistic choice than a bug, but mapstruct can't find properties for Immutables properties created without get prefixes. This is the recommended style for Immutables it seems:

Can you please open a new issue (I thought I've seen it in another issue, but I couldn't find it). For sure someone in the [Gitter room](https://gitter.im/mapstruct/mapstruct-users) posted something for that. The only thing is that it is not that easy to have this ootb, as you really need to know that your classes are in such way, otherwise every method will get matched.

For https://github.com/mapstruct/mapstruct/issues/1596#issuecomment-417573509

>`@Mapper(imports = {ImmutableItem.class, ImmutableItemDTO.class})` does work with some effort, but the process feels pretty bad.

Which IDE are you using? With Annotation processors this should compile fine on every run, independent of the clean. And the IDE should correctly pick up the sources.

**Comment by danielsonjh** [comment]
Can do, I've made a new issue here https://github.com/mapstruct/mapstruct/issues/1601

I'm using IntelliJ IDEA, and the IDE does show that it is recognizing the sources.
The problem is with the gradle CLI. It will only pick up the sources with the following line in `build.gradle`
```
sourceSets.main.java.srcDirs = ['build/generated/source/apt/main','src/main/java']
```
And even with that line, after a `clean`, the first `gradlew build` will fail since `ImmutableItem.class` and `ImmutableItemDTO.class` do not exist.
I've found out that the second `gradlew build` will succeed however, which makes this not as bad as I initially thought.
I've made an update to the example project where this can be verified.

**Comment by filiphr** [comment]
Thanks for opening the issue.

>And even with that line, after a `clean`, the first `gradlew build` will fail since `ImmutableItem.class` and `ImmutableItemDTO.class` do not exist.

This is weird, I will look into gradle to see how it should work ootb. The thing is that you should use `Immutable.builder()` in your own code if you want to build your item, so it should work on the first try. Something must be off

**Comment by sjaakd** [comment]
Problem with reproducer also happens with maven.. do don't think it a gradle issue

**Comment by sjaakd** [comment]
Reproducer added. Issue resolved
