### ISSUE TITLE
Mapping object to JAXBElement<different object>

### ISSUE THREAD

**Issue by mateop5** [mapstruct/mapstruct#1603]
Hi, I have a small issue and need some help with it. 
Let's say I have object1 of package1 and object2 of package2. Now that's an easy case for mapstruck to map object1 to object2 (by default mapping, those object are almost equal just different packages).
The problem is when I want to map object1 to JAXBElement\<object2\> . I get Can't map property error with custom mapping suggestion. Of course I am using generated ObjectFactory and including it with 'uses'.
Is there any solution to this problem without the need to create custom mapper?

**Comment by mateop5** [comment]
Found a solution in creating an explict mapping from object1 to object2.

**Comment by avmohan** [comment]
@mateop5 Could you detail the solution a bit?
