### ISSUE TITLE
Issue with super type of object model A mapped to sub types of object model B

### ISSUE THREAD

**Issue by wwang2016** [mapstruct/mapstruct#1611]
Hi

I have two object model: A and B
model A: 
It has an instance variable that is a super type. At runtime, different sub types can be instantiated as the super type.
model B:
It has all sub types listed as instance variables.

I want to map the super type of A to sub types of B, and it does allow me to map it however, it will always use the first mapping. So it will be mapped to one sub type.

On another scenario,

sub types of B will need to mapped to super A, and the mapping is not allowed
error message:
Target property \"%s\" must not be mapped more than once

Is there a solution? or I have to change object design to make both the same.

I also found that even if I have the same object design, the super type used in object design will require me to hand-write code to map sub types in two object models. It can be a lot of code. Is there any better solution?

Thanks,

Wayne

**Comment by sjaakd** [comment]
Have a look at the documentation of `@BeanMapping`. from the top of my head: you can specify the result type.. Is that what you are looking for?

**Comment by filiphr** [comment]
@wwang2016 I presume that https://groups.google.com/forum/#!topic/mapstruct-users/KvUZ_-TgIdg is also from you?

**Comment by sjaakd** [comment]
@wwang2016: I'm trying to decode what you are saying. But without a concrete example (e.g. provide a gist) it is hard to understand what you try to achieve.

**Comment by wwang2016** [comment]
@sjaakd 

The following is an example:
Object model A:

public class ContainerA
{
    SuperTypeA superType;
   ... other objects
}

public class ContainerB
{
    SubTypeB1 b1;
    SubTypeB2 b2;

   ... other objects
}

When I try to map SuperTypeA ( which on run-time will be assigned with concreted types SubTypeA1, SubTypeA2 etc) to SubTypeB1, SubTypeB2 etc. I will have a problem of one-to-many mapping. 
@Mappings({
    Mapping( target = "b1", source = "superType"),
    Mapping( target = "b2", source = "superType")
})

If I need to do a reverse mapping, then different sources (sub types of B) will be mapped to the same super type (A), and that is not allowed.

I will need both object model to map either super to super or sub to sub.

Let me know if the concern is clear in this example. 

Thanks

**Comment by sjaakd** [comment]
Ah.. It has nothing to do with super / subtypes. You try to map the same source to 2 targets.. That's not allowed. 

What I would do is ignore b1 and b2 and fix this in an `@AfterMapping`. Checkout the [documentation](http://mapstruct.org/documentation/reference-guide/) on how to do this.

**Comment by wwang2016** [comment]
@sjaakd 
I removed the mapping, and write abstract mapping methods to map between sub types of two object models. In the @AfterMapping method, I detect the object type of the source super type of object model A and call the methods to map it to corresponding sub types of object model B. However, the method was not invoked.

Is there something missing?

Thanks

**Comment by sjaakd** [comment]
can you show me the signature of your mapping an of your `@AfterMapping` annotated method?

**Comment by wwang2016** [comment]
AudioMessageB mapAudioMessage( AudioMessageA message );
    FileMessageB mapFileMessage( FileMessageB message );

    @AfterMapping default SuperTypeB mapMessages( SuperTypeA source )
    {
        SuperTypeB target = null;
        System.out.println("invoked");
        if ( source instanceof AudioMessageA )
        {
            target = mapAudioMessage( (AudioMessageA)source );

        }
        else if ( source instanceof FileMessageA )
        {
            target = mapFileMessage( (FileMessageA)source );
        }
        return target;
    }

**Comment by wwang2016** [comment]
Thanks a lot!
I got the forward mapping and reverse mapping all figured out

Please feel free to close it

Thanks

Wayne

**Comment by sjaakd** [comment]
No problem. Good to  hear..
