### ISSUE TITLE
HashMap key conversion using mapStruct

### ISSUE THREAD

**Issue by sharadborhade** [mapstruct/mapstruct#1614]
Does MapStruct allow conversion of Source Map containing source column names as keys to Target Map containing target column names as keys. 

Like below:
`@KeyMapping(source="a", target="b")` 
`public HashMap<String, String> dtoMapToDoMap(Map<String, String> dtoMap);`

**Comment by sjaakd** [comment]
I see the question also has been posted on SO. I'm closing it here.. its not an issue
