### ISSUE TITLE
SpecificCompilerWorkarounds.replaceTypeElementIfNecessary NPE

### ISSUE THREAD

**Issue by Riscue** [mapstruct/mapstruct#1619]
- [x] Is this an issue (and hence not a question)?
This is a bug, i think.

If i use `@Context` annotation with primitive `boolean` in abstract method's parameters this Exception is thrown. If i use with Object `Boolean` works fine.

Mapstruct version in project is 1.2.0.Final.

SpecificCompilerWorkarounds.java:112 is ( 1.2.0.Snapshot )
`        if ( element.getEnclosedElements().isEmpty() ) {`

That line is at SpecificCompilerWorkarounds.java:99 nowadays.

Exception and StackTrace:
`Error:(28, 17) java: *******.java 28: Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:112)  	at org.mapstruct.ap.internal.util.Executables.getAllEnclosedAccessors(Executables.java:208)  	at org.mapstruct.ap.internal.util.Executables.getAllEnclosedExecutableElements(Executables.java:188)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetrievalProcessor.java:153)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrieveLifecycleMethodsFromContext(MethodRetrievalProcessor.java:279)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.getMethodRequiringImplementation(MethodRetrievalProcessor.java:245)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.getMethod(MethodRetrievalProcessor.java:199)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetrievalProcessor.java:154)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:96)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:72)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:627)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:556)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:701)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:987)  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)  	at com.sun.tools.javac.main.Main.compile(Main.java:353)  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:113)  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:199)  	at org.jetbrains.jps.javac.ExternalJavacProcess.compile(ExternalJavacProcess.java:196)  	at org.jetbrains.jps.javac.ExternalJavacProcess.access$400(ExternalJavacProcess.java:48)  	at org.jetbrains.jps.javac.ExternalJavacProcess$CompilationRequestsHandler$1.run(ExternalJavacProcess.java:263)  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)  	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)  	at java.util.concurrent.FutureTask.run(FutureTask.java:138)  	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)  	at java.lang.Thread.run(Thread.java:662) `

**Comment by chris922** [comment]
Is it possible for you to retest this issue with the version 1.3.0.Beta1?

I just tried to create a test that covers this and it seems to work. Maybe you could also provide a short code snippet how your method looks like? (incl. annotations)

**Comment by sjaakd** [comment]
could you include java version? This particular class is there for handling all kinds of problems in specific JDK versions..

**Comment by Riscue** [comment]
> Is it possible for you to retest this issue with the version 1.3.0.Beta1?
> 
> I just tried to create a test that covers this and it seems to work. Maybe you could also provide a short code snippet how your method looks like? (incl. annotations)

I will retest mate as soon as possible. I am busy foradays.


> could you include java version? This particular class is there for handling all kinds of problems in specific JDK versions..

We use in my company JDK 1.6 but i will try this issue with mapstruct 1.3.0.Beta1 and java 8 or 10. I must create dummy project for this and share with you code snippets also.

**Comment by sjaakd** [comment]
> We use in my company JDK 1.6

That might very well be the origin of the exception (and the reason @chris922  can't reproduce it).  

Please note: we are discussing to drop support for Java6 and Java7 in the upcoming releases (1.4, 2.0?)

**Comment by sjaakd** [comment]
> We use in my company JDK 1.6 but i will try this issue with mapstruct 1.3.0.Beta1 and java 8 or 10. I must create dummy project for this and share with you code snippets also.

The current plan is actually to drop support for JDK 1.6 and JDK 1.8 in one of the next beta versions. We drag along a lot of legacy code. So I think you could even retry on JDK 1.8 on earlier versions. (e.g MapStruct 1.2.0.Final).

**Comment by sjaakd** [comment]
@Riscue .. any news on this?

**Comment by Riscue** [comment]
Hi mate, sorry for delay.

I saw your response and remember thanks.

I made my demo enviroment and saw that 1.3.0.Beta1 version fixes the issue. 1.2.0.Final has that bug then it's official.

This topic can be closed. 

You wanna see my codes down belown. Thanks again.

Mapper
`
@Mapper(componentModel = "spring")
public abstract class OwnerMapper {

    @Mappings({
            @Mapping(target = "something", expression = "java(something)"),
    })
    public abstract OwnerDTO mapToDTO(Owner owner, @Context boolean something);
}
`

Rest
`
@Controller
public class PetClinicRestController {
    private PetClinicService petClinicService;
    private OwnerMapper ownerMapper;

    @Autowired
    public PetClinicRestController(PetClinicService petClinicService,
                                   OwnerMapper ownerMapper) {
        this.petClinicService = petClinicService;
        this.ownerMapper = ownerMapper;
    }

    @RequestMapping(value = "/owner/{id}", method = RequestMethod.GET)
    @ResponseBody
    public OwnerDTO getOwner(@PathVariable @NotNull Long id) {
        Owner owner = petClinicService.findOwner(id);
        return ownerMapper.mapToDTO(owner, false);
    }
}
`

OwnerDTO
`
@Getter
@Setter
public class OwnerDTO {

    private String firstName;

    private String lastName;

    private String email;

    private boolean something;
}
`

pom.xml dependencies
`
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>1.2.0.Final</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>1.2.0.Final</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.2</version>
			<scope>provided</scope>
		</dependency>
`
