### ISSUE TITLE
custome generator with annotation

### ISSUE THREAD

**Issue by unknowedNp** [mapstruct/mapstruct#1631]
Is there avaialable any annotation to use in genreate only selecte field somthing like @JsonView in Jackson

any annotation use somewhere in DTO class like and genreate just field that have same key

**Comment by sjaakd** [comment]
@riaprocoumai .. is this a duplicate of #1574 ?

**Comment by riaprocoumai** [comment]
thats not equals 

i mean like this :
 
@Mapper
interface FooMapper {

@NewAnno(View.Public.class)
FooDTO toDTO(Foo foo);

@NewAnno(View.Summray.class)
FooDTO toSummrayDTO(Foo foo);

}

class FooDTO {


@NewAnno(View.Summray.class)
string name;


@NewAnno(View.Summray.class)
string sureName;


@NewAnno(View.Public.class)
string other;

}

and in Impl mapper just generate field setter with same annotation.

**Comment by sjaakd** [comment]
> and in Impl mapper just generate field setter with same annotation.

But we don't generate the setters.. We call the setters.. Are you implying that we select only the setters with an annotation? In that case we have a facility.. You can influence what we consider a target accessor (setter) based on an SPI.. Checkout our documentation .
