### ISSUE TITLE
Annotation processor arguments not recognized during `mvn test-compile`

### ISSUE THREAD

**Issue by hemeroc** [mapstruct/mapstruct#1638]
**What I tried:**

Configure mapstruct annotation processor arguments as follows:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>1.3.0.Beta1</version>
            </path>
        </annotationProcessorPaths>
        <compilerArgs>
            <compilerArg>-Amapstruct.suppressGeneratorTimestamp=true</compilerArg>
        </compilerArgs>
    </configuration>
</plugin>
```
Run maven with the following command:
```bash
mvn clean test-compile
```

**What I expected:**

The annotation processor picks the `-Amapstruct.suppressGeneratorTimestamp=true` argument and compiles the project without warnings.

**What happened:**

It seems that during the `test-compile` step the annotation processor does not pick the `-Amapstruct.suppressGeneratorTimestamp=true` argument which leads to following warning message:
```bash
[WARNING] The following options were not recognized by any processor: '[mapstruct.suppressGeneratorTimestamp]'
```

**Additional information:**

The arguments are picked properly in the `compile` step. But that still leads to the problem that the project can't be compiled treating warnings as errors.

**Comment by filiphr** [comment]
This has nothing to do with the MapStruct annotation processor.

The reason why this is happening is because those arguments are not passed to the test compiler. Can you please try with [`testCompilerArguments`](https://maven.apache.org/plugins/maven-compiler-plugin/testCompile-mojo.html#testCompilerArguments)?

Maybe if `testCompilerArguments` are not set the `maven-compiler-plugin` should use the `compilerArgs`. However, for this best would be to open an issue in the [Maven compiler](https://issues.apache.org/jira/projects/MCOMPILER/) issue tracker

**Comment by hemeroc** [comment]
Sorry maybe I didn't get something but the problem is exactly the other way arround.
The warning:
```
[WARNING] The following options were not recognized by any processor: '[mapstruct.suppressGeneratorTimestamp]'
```
tells me that the arguments are passed but there is no processor to pick them up!

**Comment by filiphr** [comment]
@hemeroc I re-read your comment and I have better understanding now. I will try to investigate why the options are not recognized. 

Can you try to add a mapper in your test sources? Maybe the processor is not invoked and thus can't consume the properties.

**Comment by hemeroc** [comment]
I tried your suggestion as soon as I added a mapper to the test sources the warning is gone.

**Comment by filiphr** [comment]
That is what I suspected. MapStruct is not invoked as there are no types that MapStruct can consume. I don't think that there is anything that MapStruct could do in such case.

Options would be:

* Add a dummy mapper in your tests so you don't get the warning.
* Try adding `testCompilerArguments` and see if the `compilerArgs` are not passed to javac.

Should we close this issue or do you think that we can do something?

**Comment by RutgerDOW** [comment]
I ran into simular problem:

`                    <compilerArgs>
                        <arg>
							-Amapstruct.defaultComponentModel=cdi
						</arg>
                        <arg>
							-Amapstruct.unmappedTargetPolicy=IGNORE
						</arg>
                    </compilerArgs>`

The mapstruct.unmappedTargetPolicy=IGNORE arg is working because unmapped warnings are not in the log anymore, but I still get this:
`[WARNING] The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.defaultComponentModel]'`

**Comment by filiphr** [comment]
@RutgerDOW, this is not coming from MapStruct, but rather from javac itself. It seems like the maven-compiler-plugin is passing the `compilerArgs` both to the production and test compilation. Seems like the maven-compiler-plugin also passes those arguments to the test compile phase as well.

**Comment by RutgerDOW** [comment]
You are right. I fixed it by adding execution goals to the maven compiler plugin:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.mapstruct-processor.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amapstruct.defaultComponentModel=cdi</arg>
                        <arg>-Amapstruct.unmappedTargetPolicy=IGNORE</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
