### ISSUE TITLE
Field name capitalized in @Mapping

### ISSUE THREAD

**Issue by jaagupkymmel** [mapstruct/mapstruct#1643]
Given a POJO with a field called `sFooBar` (which in turn has getter `getSFooBar` and setter `setSFooBar`), if I want to refer to that field in `@Mapping` annotation, I need to capitalize its name and use `SFooBar` instead. As discussed on Gitter, this probably happens due to `MapStruct` treating my POJO as a Java Bean, in which case the Java Bean property name extracted from the getter and setter will in fact be `SFooBar` (capitalized), as defined in [Java Beans spec 1.01](https://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf) chapter 8.8 and is thus working as intendid. However, since my POJO is not a Java Bean, I'd argue I shouldn't have to know Java Beans spec in order to use MapStruct to map it. My use of lombok to generate getters and setters only adds to the confusion.

My proposal is to support both `SFooBar` and `sFooBar` when referring to the field/property/whatever in the `@Mapping` annotation.

```java
@lombok.Getter @lombok.Setter
class Source {
    private String sFooBar;
}

@lombok.Getter @lombok.Setter
class Target {
    private String fooBar;
}

@Mapper
public interface MyMapper {
    @Mapping(source = "sFooBar", target = "fooBar") // This is what I want to do, since `sFooBar` is what's written in "Source" class
    @Mapping(source = "SFooBar", target = "fooBar") // This is what I have to do, since the Java Bean property name extracted from "getSFooBar" and "setSFooBar" will be "SFooBar"
    Target toTarget(Source source);
}
`

**Comment by sjaakd** [comment]
@jaagupkymmel . I tend to disagree. MapStruct is a bean mapper by default (out of the box). I cannot really gauge the consequences if we change this. 

NB, its not so easy to change this. There's the option to add a custom naming strategy as SPI.  Checkout our reference guide.

**Comment by filiphr** [comment]
I also agree with @sjaakd about this one. On top of that IntelliJ would generate `getsFooBar` and `setsFooBar` as getter and setter for the `Source` class. Therefore, we can't change this. 

If Lombok generates `getSFooBar` then MapStruct uses `SFooBar`.

**Comment by thunderhook** [comment]
Just for reference, lombok can be configured to use the Java Bean spec getter/setter generation, see https://github.com/mapstruct/mapstruct/issues/3374#issuecomment-1722216448
