### ISSUE TITLE
does not detect getter method when method is equal to field name

### ISSUE THREAD

**Issue by sahareh** [mapstruct/mapstruct#1647]
Im using lombok and when u use lombok boolean fields have getter method equal to the field if your field starts with `is`.
but mapstruct does not detect this fields

**Comment by chris922** [comment]
If the getter is named `isAvailable()` you must use the name `available` together with MapStruct and not `isAvailable`.

MapStruct doesn't know the field names, it just knows the getters/setters.

**Comment by filiphr** [comment]
As @chris922 mentioned, MapStruct know about getters / setters and detects the names of the properties from there. 

I am closing this issue, as it works as expected.
