### ISSUE TITLE
unmappedSourcePolicy ERROR may lead to false positives

### ISSUE THREAD

**Issue by afwlehmann** [mapstruct/mapstruct#1648]
When mapping properties with different names in source and target, `unmappedSourcePolicy = ReportingPolicy.ERROR` may lead to false positives. For this, see the following example:

```
@Mapping(target = "foo", source = "bar")
protected abstract TargetType fromSourceType(SourceType sourceType)
```

Even though the field `bar` is explicitly mapped, the source policy will produce a warning/error unless `@BeanMapping` is used to ignore the source property, such as

```
@Mapping(target = "foo", source = "bar")
@BeanMapping(ignoreUnmappedSourceProperties = { "bar" })
protected abstract TargetType fromSourceType(SourceType sourceType)
```

In fact this may lead to real errors once the line that contains the actual mapping were removed by accident. What I would expect to see instead is that the analysis of the `unmappedSourcePolicy` takes the actual `@Mapping`s into account.

**Comment by filiphr** [comment]
Thanks for reporting this @afwlehmann. I have just opened a PR for fixing this. The fix will be there in the next release

**Comment by afwlehmann** [comment]
@filiphr Thanks a lot for your prompt reaction (as well as for fixing the issue :+1: )
