### ISSUE TITLE
[Feature request] Mapping diagram generation

### ISSUE THREAD

**Issue by broyda** [mapstruct/mapstruct#1652]
[Feature request] 
A requirement that we felt in our projects is the generation of a visual mapping diagram (similar to a feature in Altova Mapforce) as an (optional) secondary artifact in the build step. Not sure if such a feature is present in the roadmap - if not I'd request for such a feature. Thanks.

**Comment by filiphr** [comment]
I had a quick look at Altova Mapforce and it is something interesting, much different to our goals though.

We haven't thought about such feature within MapStruct. In my opinion such feature is out of scope of the current MapStruct project. However, there is a way to do it within a community project by hooking with a `ModelElementProcessor` with this you can get access to the model that is used to generate the mappings.

I think that this one is similar to https://github.com/mapstruct/mapstruct/issues/702. Therefore I am going to go and close this issue
