### ISSUE TITLE
[protobuf] mapstruct fails to honour ADDER_PREFERRED when target class has 2 collections of same type

### ISSUE THREAD

**Issue by seime** [mapstruct/mapstruct#1655]
When the target protobuf class has 2 or more collections of the same type, ie

```
private List<Department> mainDepartments = new ArrayList<>();
private List<Department> departments = new ArrayList<>();
```

mapstruct fails to honour the ADDER_PREFERRED collection strategy and generates code like this:

```
        if ( userDTO.getDepartmentsList() != null ) {
            List<DepartmentDTO> list = departmentListToDepartmentDTOList( user.getDepartments() );
            if ( list != null ) {
                userDTO.getDepartmentsList().addAll( list );
            }
        }
        if ( userDTO.getMainDepartmentsList() != null ) {
            List<DepartmentDTO> list1 = departmentListToDepartmentDTOList( user.getMainDepartments() );
            if ( list1 != null ) {
                userDTO.getMainDepartmentsList().addAll( list1 );
            }
        }
```

This causes the protobuf collections to be initialized as UnmodifiableCollection causing exception:
```
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1065)
	at org.mapstruct.example.mapper.UserMapperImpl.map(UserMapperImpl.java:37)
```

A PR demonstrating the issue will be submitted shortly to https://github.com/mapstruct/mapstruct-examples

**Comment by seime** [comment]
See PR here: https://github.com/mapstruct/mapstruct-examples/pull/50 

Unit tests will fail the mapstruct/mapstruct-examples build due to this error.

**Comment by filiphr** [comment]
Closing this as the example problem has been resolved. See https://github.com/mapstruct/mapstruct-examples/commit/8dd8efc38d12b29c1a43e840ca091597d8960b5b.

Just FYI the problems was due to the fact that we were checking against the builders and those are not extending the `GeneratedMessageV3` and thus there was no adder being found. For some reason this worked properly with 1 collection of the same type.

**Comment by RaAleks** [comment]
Hi. Now the same problem with Map. I tried to map Map<String, Double> to protobuf map<string, double> and get 

java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.putAll(Collections.java:1463);


Here is example of Mapper.

`@Mapper(collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface UserMapper {

    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);


    @Mapping(source = "permissions", target = "permissionsList")
    @Mapping(source = "mainDepartments", target = "mainDepartmentsList")
    @Mapping(source = "departments", target = "departmentsList")
    UserDTO map(User user);

}`

Below example of mapper implementation.
`if ( userDTO.getTest() != null ) {
            Map<String, Double> map = user.getTest();
            if ( map != null ) {
                userDTO.getTest().putAll( map );
            }
        }`

**Comment by RaAleks** [comment]
Any updates for this?

**Comment by filiphr** [comment]
@RaAleks have a look at https://github.com/mapstruct/mapstruct/issues/1343 and https://github.com/mapstruct/mapstruct/issues/2279. If you are interested in helping out we are more than happy to accept the help ;)

**Comment by Jungle666** [comment]
Any updates for this?

**Comment by Jungle666** [comment]
> 

I got same problem,is there any sulation?

**Comment by GaniduAsh** [comment]
Guys any update on this ? getting same issue when trying to add in to a list

**Comment by chankwpj** [comment]
Adding `collectionMappingStrategy = CollectionMappingStrategy.SETTER_PREFERRED` to `@Mapper` annotation resolved it.

**Comment by Arslan1596** [comment]
@chankwpj This did not resolve it for me.

**Comment by dtrunk90** [comment]
This is still an issue with version 1.5.5. Why is this closed? Do we really need a custom naming strategy just to make this work? Imho this is a bug and should be re-opened.

**Comment by filiphr** [comment]
@dtrunk90 I think that a better support for things like this could be provided via the custom community [mapstruct-spi-protobuf](https://github.com/entur/mapstruct-spi-protobuf) extension.
