### ISSUE TITLE
Add Mappers.getMapperClass for getting the class of a Mapper

### ISSUE THREAD

**Issue by sgdesmet** [mapstruct/mapstruct#1657]
When using a mapper with componentModel jsr330 and injectionstrategy `InjectionStrategy.CONSTRUCTOR`, calling `Mappers.getMapper(...)` will fail if the Mapper has dependencies. This is because no default constructor is generated in this case, which is required for `doGetMapper` in `Mappers`.

Always adding a default constructor will solve the issue, but as a result this will probably also require `@Inject` annotated setters for the dependencies, so Guice (or similar DI frameworks) can perform injection on the instance.

**Comment by filiphr** [comment]
Using `Mapper.getMappers` with the non default `componentModel` makes no sense. The reason for this is that most probably the mapper you are using is going to be in an invalid state as the mappers it needs will need to have them injected.

**Comment by sgdesmet** [comment]
It allows you tot do something like this: 

    bind( SomeMapper.class ).toInstance( Mappers.getMapper( SomeMapper.class ) );

That way it is not necessary to bind to the generated class itself, which may not have been generated yet.
Guice takes care of the injection on the instance.

**Comment by filiphr** [comment]
Can't Guice create the instance for you? Having a constructor injection would defeat its purpose, especially as we won't add `@Inject` or `@Autowired` on the fields. So I am not entirely sure that what you are trying to do would even work.

**Comment by sgdesmet** [comment]
Yes, Guice can create the instance. I'm trying to avoid binding directly to the autogenerated implementation like this: 

    bind( SomeMapper.class ).to( SomeMapperImpl.class );

Mainly just so it doesn't look like a compilation error in the IDE before the mapper implementation has been generated.

But I agree that using constructor injection in this particular case makes less sense.

**Comment by sgdesmet** [comment]
That would certainly work, and the performance hit would probably even be minimal (only once on application startup, when guice does the bindings).

I agree that a properly configured IDE is the best option, but I've yet to find out how to properly configure everything in gradle so no manual IDE configuration is required for other team members.

**Comment by filiphr** [comment]
I'll rename this issue to match the proposed enhancement

>I agree that a properly configured IDE is the best option, but I've yet to find out how to properly configure everything in gradle so no manual IDE configuration is required for other team members.

Have you tried adding the following:
```
plugins {
    id "net.ltgt.apt-eclipse" version "0.18"
    id "net.ltgt.apt-idea" version "0.18"
}
```

those plugins will configure your IDE properly.

**Comment by filiphr** [comment]
This has been added in https://github.com/mapstruct/mapstruct/pull/1669.

Thanks @chris922 for adding this. @sgdesmet this will be part of the next 1.3.0.Final release
