### ISSUE TITLE
Calling method on @MappingTarget object

### ISSUE THREAD

**Issue by bojanv55** [mapstruct/mapstruct#1658]
So, I'm using protobuff and want to preserve `unknownFields`.

I found a way to do this mapping using:

```
//mapper
MainDto mapInplace2(Main main, @MappingTarget MainDto.Builder mainDto);
//usage
MainDto serAgainBack = MainMapper.INSTANCE.mapInplace2(back, deser.toBuilder()); //OK
```

the only problem here is that I always have to call this `.toBuilder()` - repeating call in every line I use mapper.

Is it possible to have something like this?

```
@MappingFromTarget(source = "java(mainDto.toBuilder())", target="<SELF>");
MainDto mapInplace3(Main main, @MappingTarget MainDto mainDto);
```

**Comment by bojanv55** [comment]
only problem here is that I will have to write mapInplace method per DTO that I have. Anyway this is also possible workaround as me calling `mainDto.toBuilder()` manually when calling method...

**Comment by sjaakd** [comment]
Isn't this also a duplicate of #1686?
