### ISSUE TITLE
MapStruct (1_3_0_Beta2) NullValuePropertyMappingStrategy with IGNORE doesn't work as expected

### ISSUE THREAD

**Issue by Cepr0** [mapstruct/mapstruct#1659]
MapStruct (1_3_0_Beta2) **NullValuePropertyMappingStrategy** with `IGNORE` doesn't work as expected.

**Target**

```java
@Data
//@Builder
public class FooBar {

	private int foo;

//	@Builder.Default
	private String bar = "default value";
}
```

**Source**

```java
@Value
public class FooBarDto {
	private int foo;
	private String bar;
}
```

**Mapper**

```java
@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface FoobarMapper {
	FooBar fromDto(FooBarDto fooBarDto);
}
```
**Generated Mapper implementation**

```java
public class FoobarMapperImpl implements FoobarMapper {

    @Override
    public FooBar fromDto(FooBarDto fooBarDto) {
        if ( fooBarDto == null ) {
            return null;
        }

        FooBar fooBar = new FooBar();

        fooBar.setFoo( fooBarDto.getFoo() );
        fooBar.setBar( fooBarDto.getBar() );

        return fooBar;
    }
}
```
Here we can see that mapper doesn't perform the check of `fooBarDto.getBar()` result for `null` values;
If the 'target' has a 'Bulder' - the mapper doesn't do the check as well.

[Demo](https://github.com/Cepr0/mapstruct-nullvaluepropstrategy-issue).

**Comment by sjaakd** [comment]
The new strategy is developed for update methods only. 
.
Reason:  If source bar is null than the target bar will also be null. In update methods the target bar might have had a value that you don't want to override..

**Comment by sjaakd** [comment]
You are probably looking for the 'NullvalueCheckStrategy' icw an object factory

**Comment by Cepr0** [comment]
Thank you @sjaakd for `NullvalueCheckStrategy` - it works.
