### ISSUE TITLE
Add code-examples to Javadoc of org.mapstruct.* annotations

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#166]
If find it always very helpful to see some usage-examples directly in the javadoc of a framework or an API. 

See for example here: http://docs.oracle.com/javaee/7/api/javax/persistence/Embeddable.html

**Comment by gunnarmorling** [comment]
Ok, would be nice-to-have for 1.0 but it's no strict blocker IMO.

**Comment by sjaakd** [comment]
ack.

**Comment by agudian** [comment]
ack ack.

**Comment by Captain1653** [comment]
@agudian  @gunnarmorling @sjaakd I can do it. Assign this isssue on me if we still are going to do it. I can add examples to javadoc  for each annotation in package org.mapstruct. Should I do it like one PR or better to split up on two or three?

**Comment by sjaakd** [comment]
@Captain1653 .. I there are already some examples in the java doc.. Look at `Context.java` for instance.

Some time ago I investigated some plugin to directly include java code into the java doc. We could then(re-) our use unit test code. Did not work out then (do not remember why not).

**Comment by Captain1653** [comment]
@sjaakd  I was thinking about some plugin, but it seems little harder (maybe I'm wrong). But if we use plugin we should mark some place in javadoc, and we sholud find some way to add some code in javadoc, add only relevent code from a generated mapper (it seems not so easy also. Maybe I'm wrong again :)). 
And I have some investigate about javadoc examples in other project: Spring, Hibernate. I have found, the javadoc is handwritten. There are some commits:
[Spring](https://github.com/spring-projects/spring-framework/commit/effb762558f152ed60f5bd6aedb4c7b5ea65db4a#diff-b02fe34df0cc342d11d2e89c73334240) and [Hibernate](https://github.com/hibernate/hibernate-orm/commit/a8a3f9b11287ff2350aef9bc976ae990918a6f91#diff-2d1c7579dd3f96a0e0a9085a984fb70c) . 

Should I also to do our examples this way? Or I should try to find some plugin or workaround?

**Comment by filiphr** [comment]
@Captain1653 I think adding handwritten examples in the Javadoc is OK. AssertJ does it like that as well.
