### ISSUE TITLE
Avoid explicit Unrecognized mapping while working with Java Enum & proto buff

### ISSUE THREAD

**Issue by Kavyamanjanatha** [mapstruct/mapstruct#1667]
If the proto has enum then the generated file has Unregognized option added.However in the Java enum Dto we dont add this.
Due to this need to add explicit mapping of unrecoginzed while translation from java enum to proto enum.

@ValueMapping(source = "UNRECOGNIZED", target = MappingConstants.NULL)
Permission map(PermissionDTO permissionDTO);

Need a way to avoid this mapping either via config files.

**Comment by chris922** [comment]
Do you have an example? Maybe a short extract from `Permission` and `PermissionDTO`?

I think MapStruct already supports what you are searching for or maybe I misunderstood your issue. Have you tried this?

```java
@ValueMapping(source = MappingConstants.ANY_REMAINING, target = MappingConstants.NULL)
Permission map(PermissionDTO permissionDTO);
```

**Comment by Kavyamanjanatha** [comment]
Hi
In your approach developer has to explicitly map for every enum  conversion above lines.
Instead we should have an option to specify these configuration via config file so that  it can be globally applied without developer need to the specify @ValueMapping for every mapping conversion

**Comment by chris922** [comment]
Ah ok, understood.

@filiphr / @sjaakd : WDYT? Useful and where should we add this? I think the right place would be `@Mapper` and `@MapperConfig` on the usual way.. any suggestions for the property name?
```java
@Mapper( defaultValueMapping = @ValueMapping(source = MappingConstants.ANY_REMAINING, target = MappingConstants.NULL) )

@Mapper( valueMappingPolicy = ValueMappingPolicy.ANY_REMAINING_TO_NULL )

...
```

Or is it already possible together with `@InheritConfiguration`? Something like:

```java
@ValueMapping( source = MappingConstants.ANY_REMAINING, target = MappingConstants.NULL )
Enum<?> defaultEnumMapping( Enum<?> source );

@InheritConfiguration
Permission map( PermissionDTO permissionDTO );
```

But in this case you still have to configure it for each enum.

**Comment by filiphr** [comment]
Recently we added new `EnumNamingStrategy` and `EnumTransformationStrategy` that would enable the use case in the issue.

There is no out of the box support for this. However, it is possible to implement new custom `EnumNamingStrategy` and implement the `getDefaultNullEnumConstant` to handle the default value for protobuf enums.
