### ISSUE TITLE
not support map?

### ISSUE THREAD

**Issue by xiejin90314** [mapstruct/mapstruct#1668]
i have a problem.

when i coding 
```
default Map<String,String> toMetadata(String metadataJson) {
        if (StringUtils.isBlank(metadataJson)) {
            return null;
        }
        return JSON.parseObject(metadataJson, Map.class);
    }
````

then this interface  impl class was
```
 if ( map != null ) {
                taskVM.setMetadata( map );
            }
            else {
                taskVM.setMetadata( new HashMap<String, String>() );
            }
```
but impl class not  import java.util.HashMap.
so this class has a error?

**Comment by filiphr** [comment]
I also tried to reproduce this on master but couldn't. We can reopen the issue once you provide the entire mapper that we could use to reproduce the problem.

**Comment by xiejin90314** [comment]
> Which version of MapStruct are you using?
> 
> I think I know what the error might be, but in any case it would help if you can share your mapper interface.
> 
> Until we fix this you can use `@Mapper(imports = HashMap.class)` in order to force that import.

thanks for you~
