### ISSUE TITLE
How recursively update embedded objects on mapping into existed object instead of rewrite it?

### ISSUE THREAD

**Issue by human453453467** [mapstruct/mapstruct#1673]
I'll show you an example:

valueToUpdate: 
```java
class Person{
    public  String name;      //"Bob"
    public  Address address;
}

class Address{
    public  String street;    //"Abbey Road"
    public  Integer home;     //!!! there is no 'home' value !!!
}
```
target: 
```java
class Person{
    public  String name;      //"Michael"
    public  Address address;
}

class Address{
    public  String street;    //"Kitano"
    public  Integer home;     //5
}
```
and as a result i want get:
```java
class Person{
    public  String name;      //"Bob"
    public  Address address;
}

class Address{
    public  String street;    //"Abbey Road"
    public  Integer home;     //5 - !!! the value remains the same !!!
}
```

Can I get similar functionality using MapStruct? What do I need to use? I can close this issue by myself. I only need clues for find needed objects.

**Comment by sjaakd** [comment]
Checkout or documentary.. you should use @MappingTarget to update existing objects. You can use the dot notation to address nesting. Our unit tests also provide ample examples

**Comment by human453453467** [comment]
> Checkout our documentation: http://mapstruct.org/documentation/installation/. you should use @MappingTarget to update existing objects. You can use the dot notation to address nesting. Our unit tests also provide ample examples

Thanks a lot for your reply. I know this feature (@MappingTarget), but my question is about how to do recursively update for embedded objects, while mapstruct by default update only first level objects, at next level it simply rewrite it. You can see my test, it shows what i want to achieve.

I can't manually point to each field by annotations because structure is deep nested with many fields.

```java
    @Test
    public void mapStruct(){

        Address addressValueToUpdate = new Address();
        addressValueToUpdate.street= "Abbey Road";
        //!!! there is no "home" value, so it is NULL !!!
        Person personValueToUpdate = new Person();
        personValueToUpdate.address = addressValueToUpdate;
        personValueToUpdate.name = "Bob";

        Address addressTarget = new Address();
        addressTarget.street= "Kitano";
        addressTarget.home = 5;
        Person personTarget = new Person();
        personTarget.address = addressTarget;
        personTarget.name = "Michael";

        PersonMapper mapper = Mappers.getMapper(PersonMapper.class );
        mapper.updatePersonFromPerson(personValueToUpdate, personTarget);

        assertEquals("Bob", personTarget.name);
        assertEquals("Abbey Road", personTarget.address.street);
        assertEquals(Integer.valueOf(5), personTarget.address.home); //ERROR Expected :5 Actual :null
    }
```

```java
@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface PersonMapper {
    void updatePersonFromPerson(Person valueToUpdate, @MappingTarget Person target);
}
```

**Comment by sjaakd** [comment]
You can force it by defining sub mapping method signatures (also with @MappingTarget) however I would expect mapstruct to do this automatically.. however, I'm currently not in the position to check your example (mobile only). Perhaps @filiphr can take a look.. otherwise you have to wait a while 🙁

**Comment by filiphr** [comment]
I've answered this question on StackOverflow already. The answer is [here](https://stackoverflow.com/a/54019501/1115491).

The mapper you are looking for is:

```
@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE, nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface PersonMapper {

    void update(@MappingTarget Person toUpdate, Person person);

    void update(@MappingTarget Address toUpdate, Address address);
}
```

When you are updating same object types you would have to add an explicit method for it, otherwise it would use implicit mapping and won't create a mapping method. We only generate mappings when the source and target type are different.

Closing this as it has been answered
