### ISSUE TITLE
Add ability to globally configure @Mapping for properties in reused super classes

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#168]
With #72 being resolved now, we need some means to allow ignoring certain properties from being mapped / reported as unmapped on a global scope.

I could think of something along the following lines (with much room for improvement for the naming):

```java
@GlobalMapping(
   sourceType=BaseEntity.class, 
    targetType=BaseDto.class, 
    mappings={ 
      @Mapping(target="uuid", ignore=true),
      @Mapping(source="id", target="technicalId") 
   }
)
```
That annotation (or a multiple of it) would be allowed at mapper level (e.g. in ```@Mapper```) and in the ```@MapperConfig``` annotation.

```sourceType``` and ```targetType``` would be optional, and the specified ```@Mapping``` configuration would be applied for each mapping method that has source / target types that fit (as in "assignable from").

**Comment by gunnarmorling** [comment]
@agudian, I've been thinking a bit more about this. There is basically two things I'm concerned about with the proposed approach:

* The irregularity of global definitions: source and target types need to be specified within the annotations rather then method parameters / return types as with the existing means of mapping definitions; It also doesn't work for parameterized types (I don't think that's supported yet in general, but any solution we come up with should leave the door open)
* When looking at a mapping method definition, not all its property mappings are easily visible; You need to take global definitions possibly defined somewhere else into account

So what would you think about re-using `@InheritConfiguration` alternatively:

    @Mapping(source = "id", target = "primaryKey")
    BaseEntity dtoToEntity(BaseDto dto);

    @InheritConfiguration(name="dtoToEntity")
    CarEntity toCarEntity(CarDto carDto);

This would address the concerns above:

* "Global" (or basic) mappings would just be defined as any other mappings, it works for parameterized types.
* When looking at a specific method such as `toCarEntity()` there is a link to the method with the basic mappings, making things much easier to grasp

We'd also re-use an existing construct rather than defining a new one. Now some downsides:

* It doesn't allow for the definition of mappings where source or target is "any type". Personally I don't think it's a huge issue.
* It doesn't work if the target base type (e.g. `BaseDto`) is an abstract class as we cannot generate an implementation of the base mapping method then. That's a problem indeed. One solution I can think of is to define the base method on another mapper and have a flag in `@Mapper` which marks that mapper as not to be implemented, i.e. it's only supposed to serve as base mapping source. That'd require the inherit configuration mechanism to work across mappers. Maybe you have another, better idea for that?

All in all, that approach seems beneficial to me due to its regularity, explicitness and re-use of existing constructs. WDYT?

**Comment by gunnarmorling** [comment]
> It doesn't allow for the definition of mappings where source or target is "any type"

I guess that can be done by using `Object` as source/target type.

Another advantage of the inheritance approach is that it avoids any mismatches between conflicting global mappings for the same types as a method can only its configuration from exactly one other method.

**Comment by gunnarmorling** [comment]
> One solution I can think of is to define the base method on another mapper and have a flag in @Mapper...

Or, we take methods defined on the conflig class into account for this purpose. The nice thing about that is that it doesn't really change the scope of `@InheritConfiguration` (I find inheriting from methods from the config class less invasive than from other mappers) and the base mapping method is not exposed to clients (which is a good thing if the return type is abstract as its not useful anyways). And if you want to expose the base method, just define it in the mapper interface itself.

**Comment by sjaakd** [comment]
Hi Gunnar. I think you have valid points above. I feel like we're progressing on this one. Small remark: I was a bit looking through the whole thread and its a bit scattered now (some stuff in the PR, some stuff here).  

1. Now some stuff that we need to tackle. We should be very careful in re-using the `@InheritConfiguration`. I put some limits on the usage, and they need to be studied (like you can't refer to another method with `@InheritConfiguration` or `@InheritReverseConfiguration`) thoroughly.

2. Therefore, it might be better to extend the family with `@InheritBaseConfiguration`. We can even do some neat tricks, by specifying more (like multiple inheritance if  `BaseDto` and `BaseEntity` are interfaces iso abstract classes :smile: ). Order becomes important then.

3. I'm indeed also a bit reluctant to take the `@InheritConfiguration` outside the scope of the class. For one thing, how would you address such a method? Javadoc style? So having the config class as a 'global' parent might be a good way around this. Perhaps we can even agree that we do not generate implementations for *all* methods in this class.

4. Alternatively, we could also use the new `BeanMapping` and make a new parameter on that one. E.g. `BeanMapping#abstract` or `BeanMapping#doNotImplement`.

5. If you use `@InheritConfiguration` for this purpose, what are you going to do with the `@InheritReverseConfiguration` ?

**Comment by agudian** [comment]
One alternative would also be to annotate the method within the config class with something like ```@MappingPrototype(inheritsConfiguration=WHEN_ALL_TYPES_ARE_APPLICABLE)``` or ```@MappingPrototype(inheritsConfiguration=WHEN_EXPLICITLY_INHERITED)``` (just with some more sophisticated wording, but I guess you get the idea)...

**Comment by sjaakd** [comment]
Lets combine some ideas:

A. I think that we all agree that its a good idea having a real method signature to refer to like (to give it a home whas the expression @agudian used above :+1:  :
```java
@Mapping(source = "id", target = "primaryKey")
BaseEntity dtoToEntity(BaseDto dto);
````

B.  Making use of the config class for these signatures, I sense, is also a good idea. So like this:
```java
@Mapper(config = CentralConfig.class )
public class MyMapper {
....
}

@MapperConfig
public class CentralConfig {
}
```

C. New: why don't we demand that this class is in fact an interface and not marked as `@Mapper` (we should enforce this). Then no method bodies will be generated. Like this:
```java
@MapperConfig
public interface CentralConfig {

@Mapping(source = "id", target = "primaryKey")
BaseEntity dtoToEntity(BaseDto dto);

}
```

D. I like the idea that Andreas posed above. Only now you can make it an element of `@MapperConfig`. Like this:
```java
@MapperConfig( inheritsConfiguration=WHEN_ALL_TYPES_ARE_APPLICABLE )
public interface CentralConfig {

@Mapping(source = "id", target = "primaryKey")
BaseEntity dtoToEntity(BaseDto dto);

}
```
Note: I would use `WHEN_EXPLICITLY_INHERITED` as default option. Also we could consider marking this feature as 'experimental', just to overcome the problems that Gunnar sees.

E. Finally, some piece of my solution:
```java
@InheritBaseConfiguration
CarEntity toCarEntity(CarDto carDto);
```
Note: this annotation would only consider methods in the `@MapperConfig` class. No name needs to be specified. Also it can be referred to from an `@InheritConfiguration` or an `@InheritReverseConfiguration`. 

So the whole solution would look like this (default modus):

```java
@MapperConfig
public interface CentralConfig {

    @Mapping(source = "id", target = "primaryKey")
    BaseEntity dtoToEntity(BaseDto dto);
}

@Mapper(config = CentralConfig.class )
public interface MyMapper {

    @InheritBaseConfiguration
    @Mapping(target="fordSpecificEngineType", source="fordSpecificEngineTypeYYY")
    CarEntity toCarEntity(CarDto carDto);

    @InheritConfiguration
    FordEntity toFordEntity(FordDto carDto);

}
```

Or in Andreas his case:

```java
@MapperConfig(inheritsConfiguration=WHEN_ALL_TYPES_ARE_APPLICABLE)
public interface CentralConfig {

    @Mapping(source = "id", target = "primaryKey")
    BaseEntity dtoToEntity(BaseDto dto);
}

@Mapper(config = CentralConfig.class )
public interface MyMapper {

    @Mapping(target="fordSpecificEngineType", source="fordSpecificEngineTypeYYY")
    CarEntity toCarEntity(CarDto carDto);

    @InheritConfiguration
    FordEntity toFordEntity(FordDto carDto);

}
```

So: WDYT?

**Comment by agudian** [comment]
Oh, I like it! :+1:
Although I would not put "inheritsConfiguration" int MappingConfig, as it might suggest that it applies to everything that is configured there. Or could that be fixed with a more precise wording?

**Comment by gunnarmorling** [comment]
Yes, I think we're getting somewhere :)

I'll answer in more detail later, but I understand Andreas' point about too
many places where @Inherit(Base)Configuration needs to be put. So it also
came to my mind that this can be circumvented by having this sort of "auto
application" but require to explicitly opt into this once, quite similar to
what Sjaak suggests.

I would only have put it to @Mapper rather than @MapperConfig so to make it
a per-mapper setting and also more apparent in individual mapper classes.
Now don't tell me you have hundreds of mappers and its not feasible for
you, Andreas ;)

Seems we agree on putting base configs into methods sigs in config classes.
That's very nice. I also like the idea of demanding those to be interfaces.
I'm not quite sure whether we'd really need a separate annotation other
than @InheritsConfiguration.

**Comment by sjaakd** [comment]
> Or could that be fixed with a more precise wording?

Make  a suggestion :smile: .. 

------------------

Perhaps a bit farfetched, but we could also have a hierarchical mechanisms, like we have for `unmappedTargetPolicy` and use the `@PrototypeMapping`like this:

```java
@MapperConfig(inheritsConfiguration=WHEN_ALL_TYPES_ARE_APPLICABLE)
public interface CentralConfig {

    @PrototypeMapping(inheritsConfiguration=WHEN_EXPLICITLY_INHERITED) // overrides @MapperConfig
    @Mapping(source = "id", target = "primaryKey")
    BaseEntity dtoToEntity(BaseDto dto);
}
```

Or,  use the new `@BeanMapping` iso the  `@PrototypeMapping` (optionally making also use of the other elements in `@BeanMapping` like `@BeanMapping#qualifiedBy` or `@BeanMapping#resultType`) if that makes sense, like this:
```java
@MapperConfig(inheritsConfiguration=WHEN_ALL_TYPES_ARE_APPLICABLE)
public interface CentralConfig {

    @BeanMapping(inheritsConfiguration=WHEN_EXPLICITLY_INHERITED) // overrides @MapperConfig
    @Mapping(source = "id", target = "primaryKey")
    BaseEntity dtoToEntity(BaseDto dto);
}
```

Anyway.. choices, choices and more options :smile:

**Comment by sjaakd** [comment]
> I would only have put it to @Mapper rather than @MapperConfig so to make it a per-mapper setting and also more apparent in individual mapper classes. Now don't tell me you have hundreds of mappers and its not feasible for you, Andreas ;)

I leave that one to @agudian :smile:, say for the fact that we do have the `@MapperConfig` in place to do central configuration. So 'both' (in `@Mapper` and `@MapperConfig`, hierarchical override) would be a logical choice as well for me. After all: the user has his own responsibillity as well. 


> I'm not quite sure whether we'd really need a separate annotation other than @InheritsConfiguration.

There's quite some rules you can / should define to avoid circular/cyclic behaviour. That's always lurking around the corner in these scenarios: Like you can't `@InheritConfiguration` from a mapping-method that already carries the `@InheritConfiguration`but it makes sense that you could from a mapping-method that carries `@InheritBaseConfiguration` (as with my example above).

Having separate annotations gives you more flexibility!  I'm not sure whether it gives more clarity having this ruling on elements in `@InheritConfiguration`.

**Comment by agudian** [comment]
>> I would only have put it to ```@Mapper``` rather than ```@MapperConfig``` so to make it a per-mapper setting and also more apparent in individual mapper classes. Now don't tell me you have hundreds of mappers and its not feasible for you, Andreas ;)
> 
> I leave that one to @agudian :smile:, say for the fact that we do have the ```@MapperConfig``` in place to do central configuration. So 'both' (in ```@Mapper``` and ```@MapperConfig```, hierarchical override) would be a logical choice as well for me. After all: the user has his own responsibillity as well.

Just counted: 406 types annotated with ```@Mapper``` in three of the four projects... :grin: - But I'll have to reg-exp about 95% of them anyway to add the ```config=``` attribute (which is not yet used), so that would be no show stopper for me.

But I agree with Sjaak, that until now we mirrored all the options of ```@Mapper``` in ```@MapperConfig```, so I'd also find it logical to do the same thing here.

Once we're all on the same spot with where and where not to put that flag (Mapper, MapperConfig, BeanMapping, or a new method-level MapperPrototype annotation), we can take some time to think about naming the property and the different enum instances.

What I had in mind initially was to express something like "I am configured in some special way and I hereby state that this configuration shall be inherited to bean mapping methods where (all types match | I am explicitly referenced)".

My favourites:
* Not in ```@Mapper``` (because I it does not carry the configuration, but only references the config interface, saying "I order whatever the config interface choses")
* Not in ```@MapperConfig``` (because until now it only carries ```@Mapper```-level options and those are _always_ applied to the mappers that reference this config interface [unless overruled by the mapper itself])
* Not in ```@BeanMapping``` (because then you could state the same option also on a real bean mapping method
* In a new ```@MappingPrototype``` annotation on the dummy mapping method declaration (because it clearly denotes the purpose of that method, being a prototype/template/base that is not supposed to end up being generated; the inheritence-setting would be clearly limited to what's inheritable from _mapping-method_ to _mapping-method_; I can't imagine having too many different methods of that kind in a config-interface, so it shouldn't turn out to become an annotation nightmare) - I don't know if that might be too verbose, though.

**Comment by sjaakd** [comment]
> And thus, my favourites are:

Drums.. TADA.. You've got a strange form of favorites :smile:..

Anyway. To list the remaining topics to be solved:

1. Place of the flag (I don't have a strong preference, so I guess you guys need to settle that one).  

2. The annotations `@InheritConfiguraiton`, `@InheritBaseConfiguration` and I guess also the `@InheritReverseConfiguration`. Personally: I'm concerned on these ones. I've seen what happens in the automated case (cyclic relations, unpredictable behavior). I added checks to circumvent those. @gunnarmorling : could it be that a matter of taste, whether you add elements to one annotation or you have multiple of them? @agudian : what's your take on this?

3. .. any more?

**Comment by agudian** [comment]
> Place of the flag (I don't have a strong preference, so I guess you guys need to settle that one).

Ok then, I've placed my bet. Let the BDOL decide... :wink:

On 2. I'm kind of out - I also have a feeling that re-using InheritConfiguraiton and InheritReverseConfiguration could cause some trouble/inconsistencies and that we might better add some new and specific annotation there. But that's really just a feeling based on no hands-on experience with that stuff. You two are much deeper into that, so you decide, I'll implement :grinning: 

3. would be to reconsider the namings, but we need to pin down 1 and 2 first, I'd say.

Something else missing?

**Comment by gunnarmorling** [comment]
> But I agree with Sjaak, that until now we mirrored all the options of @Mapper in @MapperConfig, so I'd also find it logical to do the same thing here.

Yes, ok, that make sense. Have an option on `@Mapper` and `@MapperConfig`, and giving the former precedence.

**Comment by gunnarmorling** [comment]
> In a new @MappingPrototype annotation on the dummy mapping method declaration

Where would one use that? As I see it, all the method definitions on the `@MapperConfig` class are "mapping prototypes", so there is no need to mark them again as such via the annotation. Or where did you mean to use it?

There are two cases:

* You want to be the "mapping prototype" method be usable itself -> declare it on an actual mapper interface
* You don't want to be it usable (e.g. because it declares an abstract return type) -> declare it on a `@MapperConfig`-annotated interface

**Comment by gunnarmorling** [comment]
Regaring having a specific `@InheritBaseConfiguration`, I do not yet understand in which way it would differ from `@InheritConfiguration`. In both cases it's an advice to apply the configuration from one other method to the annotated method. I don't think it makes a difference whether the parameter/return types are exactly the same or super types. They must be the same or super-types, but in both cases the configuration can be inherited. Thus I don't think a new annotation is needed for that.

**Comment by gunnarmorling** [comment]
> could it be that a matter of taste, whether you add elements to one annotation or you have multiple of them?

Generally I prefer to re-use (and possibly enhance/generify) existing annotations and constructs rather than adding new ones. But if a construct is too generic, it often gets too verbose to use it. Thus I think it's fine to have the explicit `@InheritReverseConfiguration` instead of `@InheritConfiguration(reverse=true)`.

But for the case of inheriting base configurations re-using `@InheritConfiguration` seems good to me as it can be use as is, there is no need to parameterize it.

**Comment by sjaakd** [comment]
> But for the case of inheriting base configurations re-using @InheritConfiguration seems good to me as it can be use as is, there is no need to parameterize it.

Ok. Lets go ahead and try. I do think we need to think a bit more on ruling. Examples:

I want to avoid relations as A -> B -> A . So 'A' inherits from 'B' inherits from 'A' again. I avoided this by simply not allowing A to inherit its configuration from B if B itself inherits also from something. I think we need to fine-tune that.

1. `InheritConfiguration` is not allowed on the `@MapperConfig` interface (prototype methods)

2. `InheritConfiguraiton` is allowed from A to be, as long as B `InheritConfiguration` from a method in the `@MapperConfig` annotated class.

3. But then, how do we resolve conflicts in the mapper class with methods in the class with the one marked with `@MapperConfig`? We need to indicate somehow a class as well in the `@MapperConfig#name` ..

If we can work the above out, then we're there. 

> Generally I prefer to re-use (and possibly enhance/generify) existing annotations and constructs rather than adding new ones. But if a construct is too generic, it often gets too verbose to use it. Thus I think it's fine to have the explicit @InheritReverseConfiguration instead of @InheritConfiguration(reverse=true).

That's good. I think we can close that discussion (in my mind this was still an open end somewhere :smile: ) ).

**Comment by gunnarmorling** [comment]
> I want to avoid relations as A -> B -> A . So 'A' inherits from 'B' inherits from 'A' again. I avoided this by simply not allowing A to inherit its configuration from B if B itself inherits also from something. I think we need to fine-tune that.

+1 This situation must be detected and prohibited. It's easy when `@InheritConfiguration` is given explicitly, but when mapping methods for super-types may be inherited automatically, it may become more tricky.

Also some ordering must be applied (in case there is a mapping method for super-types and another one for super-super types).

> InheritConfiguration is not allowed on the @MapperConfig interface (prototype methods)

Why would that be needed? Couldn't one base configuration method inherit the config from another one?

> But then, how do we resolve conflicts in the mapper class with methods in the class with the one marked with @MapperConfig?

Could you give an example for the situation you have in mind?

**Comment by gunnarmorling** [comment]
Regarding the referencing of methods in the mapper config via `@InheritConfiguration`, we may add an optional member `Class<?> declaring class` for that purpose. By default, the named method would be searched on the "local" class.

**Comment by sjaakd** [comment]
> Regarding the referencing of methods in the mapper config via @InheritConfiguration, we may add an optional member Class<?> declaring class for that purpose. By default, the named method would be searched on the "local" class.

Ah.. I think you already know what situation i have in mind :smile: .  But this is why I had a special annotation `@InheritBaseConfiguration` in mind (this is only searched in the `@MapperConfig` class) whereas `@InheritConfiguration` is only searched in the mapper class itself.

**Comment by sjaakd** [comment]
> By default, the named method would be searched on the "local" class.

You mean prefer the "local" class over the `@MapperConfig` class? There could be conflict in the `@MapperConfig` class as well. If there's no matching class in the "local" class, it still could be resolved with `@InheritConfiguration#name` only.

> we may add an optional member Class<?> declaring class for that purpose.

Isn't that overkill? There are only 2 options, right "local" or `@MapperConfig`? I think we are making this over complicated.

**Comment by sjaakd** [comment]
> we may add an optional member Class<?> declaring class for that purpose.

I've been thinking a bit more on this. Perhaps we should use an enum iso the class. Or do you want to open up the possibility as well to refer to entirely different mappers? 

So:

```java
@Target( ElementType.METHOD )
@Retention( RetentionPolicy.SOURCE )
public @interface InheritConfiguration {

    public enum Scope { LOCAL, MAPPER_CONFIG, BOTH }

    String name() default "";

    boolean inverse() default false;

    Scope scope() default Scope.BOTH;
}
```
Note:
*. You can't combine inheritance from prototype (mapper config) methods and local methods on one method

*. `WHEN_ALL_TYPES_ARE_APPLICABLE / WHEN_EXPLICITLY_INHERITED` . Perhaps obvious, but defining an `@InheritConfiguration` overrules 'WHEN_ALL_TYPES_ARE_APPLICABLE`

*. @agudian: Have you thought about update / create methods (in the `@MapperConfig`), or do we both match up with one signature? I think we should.

**Comment by gunnarmorling** [comment]
> Or do you want to open up the possibility as well to refer to entirely different mappers? 

Yes, I think some flexibility may be beneficial here. Not necessarily for mapper classes (at least for now), but I could imagine cascades of global config classes (i.e. one global config class extending another one).

**Comment by gunnarmorling** [comment]
> boolean inverse() default false;

Ah, do you prefer that flag now? Didn't we agree on the separate annotation being nicer to read?

**Comment by sjaakd** [comment]
> Ah, do you prefer that flag now? Didn't we agree on the separate annotation being nicer to read?

I was exploring the possibility :smile: ..  Actually, the same arguments as you apply to having separate annotations for `InheritBaseConfiguration` and `InheritConfiguration`. So perhaps we should..  That opens up the possibility to inherit reverse configurations as well from base. I'm still worried that we open up a can of worms. 

Anyway.. Perhaps we should leave it up to @agudian  at this point. We have discussed it sufficiently (at least I think), and perhaps we should see what implementation yields. WDYT?

**Comment by gunnarmorling** [comment]
Yes, I think the general direction is clear, so I think we can can continue (or just finish ;) ) the discussion once Andreas has updated the PR based on our latest line of thought. Being able to specify base mapping methods in config classes is the key piece which was missing before.

**Comment by gunnarmorling** [comment]
@agudian The PR is merged. I'll leave the issue open until the doc update is there. Thx!

**Comment by agudian** [comment]
Doc update pushed.
