### ISSUE TITLE
Make suppressGeneratorTimestamp and suppressGeneratorVersionInfoComment enabled by default

### ISSUE THREAD

**Issue by remmeier** [mapstruct/mapstruct#1682]
Without those two flags enabled (which is not the default), it will break the reproducablity/cachablity of Gradle builds. There is not much value in those two constants and they should be removed. If timestamp and version should be tracked, JARs can make an entry in the META-INF.

**Comment by filiphr** [comment]
@remmeier are you sure that the timestamp and info comments are the problem? If we do https://github.com/mapstruct/mapstruct/issues/1420 won't that solve the problem for gradle? 

I am not that familiar with gradle and its API. 

Also you know that you can disable them via a compiler option right?

See [Configuration options](http://mapstruct.org/documentation/stable/reference/html/#configuration-options) in the documentation.

Closing this in favour of the compiler configuration options.

**Comment by remmeier** [comment]
i thing those are two orthogonal concerns. gradle has fairly extensive caching mechanisms based on hashing tash inputs. similarly for example docker images adress images by image id (a content hash). adding versions and timestamps to files goes against these approaches.

i managed to disable their generation, but i think it would be worthwhile to have as default.
