### ISSUE TITLE
Conversion list without type

### ISSUE THREAD

**Issue by jabraojos** [mapstruct/mapstruct#1687]
How can I convert list without type?

- Example

Source:
```
public class ClassSource {
  private String attribute;
  private List sourceList;
}
```

Target:
```
public class ClassTarget {
  private String attribute;
  private List<MyObject> targetList;
}
```

Mapper:
```
@Mappings({
  @Mapping(source = "sourceList", target = "targetList")
})
ClassTarget sourceToTarget(ClassSource classSource )
```

Generated code:
```
...
        List list = classSource .getSourceList();
        if ( list != null ) {
            classTarget.setTargetList( new ArrayList<MyObject>( list ) );
        }
        else {
             classTarget.setTargetList( null );
        }
...
```

The line 
> classTarget.setTargetList( new ArrayList<MyObject>( list ) 

produce "ClassCastException".

**Comment by jabraojos** [comment]
Solution

```
@Mappings({
  @Mapping(source = "sourceList", target = "targetList", qualifiedByName = "myTransformation")
})
ClassTarget sourceToTarget(ClassSource classSource )

@SuppressWarnings("unchecked")
	@Named("myTransformation")
    default List<MyObject> myTransformation(List source) {
        return (List<MyObject>) source.stream().map(s-> transformSourceToTarget((ObjectSource)s)).collect(Collectors.toList());
    }

MyObject transformSourceToTarget(ObjectSource objectSource);
```

**Comment by chris922** [comment]
When I understood it correctly the issue for MapStruct is that it does not know the source type and thus it skips the mapping. That is probably possible because it will be assumed that the source list contains the same type of elements like the target like.

@filiphr, @sjaakd: WDYT? If this is the case it might be an idea to support something like @IterableMapping(elementSourceType=...) ?

**Comment by sjaakd** [comment]
Don't know what @jabraojos is after.. Normally you only have to provide an element mapping from `Object` to `MyObject`.. MapStruct will generate the list mapping for you..

So if the mapper would specify the following mapping:

```java

 MyObject map(Object source)

```

in the generated code MapStruct would generate the list mapping for you. No need to provide `myTransformation`..

**Comment by chris922** [comment]
But from `Object` to `MyObject` you have to write your mapper yourself. It looks here like a `List` will be used that always contain the same type of element, but doesn't use generics.

Hmm.. but maybe something like this is working and also not really complex:

```java
default MyObject transformSourceToTarget(Object objectSource) {
  if( objectSource instanceof ObjectSource ) {
    return transformSourceToTarget( (ObjectSource) objectSource );
  }
  
  return null; // or throw an exception or what ever ...
}

MyObject transformSourceToTarget(ObjectSource objectSource);
```

**Comment by sjaakd** [comment]
> But from `Object` to `MyObject` you have to write your mapper yourself.

Yes..
