### ISSUE TITLE
Ignoring source property without defining target

### ISSUE THREAD

**Issue by dainiusfigoras** [mapstruct/mapstruct#1688]
At the moment "target" in @Mapping is required, but sometimes source data model contains properties that doesn't have equivalent in target. And would be helpful to allow to ignore properties based not just  on target (that's possible today) but also on source.

For example:

Target {
string name;
}

Source {
string name;
string id;
}

@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR, unmappedTargetPolicy = ReportingPolicy.ERROR)
interface Mapper {

@Mapping(source = "id", ignore = true)
Target map(Source source);

}

**Comment by filiphr** [comment]
This can be done via `BeanMapping#ignoreUnmappedSourceProperties`. This was done as part of https://github.com/mapstruct/mapstruct/issues/1317
