### ISSUE TITLE
Changes to domain/dto objects do not trigger code regeneration

### ISSUE THREAD

**Issue by vali-m** [mapstruct/mapstruct#1690]
Good day!

How to reproduce bug (tested in an existing Spring Boot project):
1. Add field **with the same name** to both entity and DTO object of same mapper
2. Add getters and setters 
3. Do not add Mapping to Mapper interface
4. Re run project

Mapstruct does not detect changes in these objects and thus does not regenerate the mapper classes. The consequence is that the implicit mapping (between the 2 fields with the same name) does not happen unless the generated class is deleted or some change is made in the mapper interface.

In fact, you can even remove a method that is used in the generated class (a getter/setter on domain or dto object) and it will try to call said method.

**Comment by filiphr** [comment]
When you say that regeneration does not happen you mean within IntelliJ IDEA, as with Maven, Gradle and Eclipse this works properly. Unfortunately (as I have already said in https://github.com/mapstruct/mapstruct-idea/issues/13#issuecomment-346439554 there is nothing that we can do here. The compilation (and which classes will get compiled) is done by the IDE. 

My comment in the linked issues was:

>IDEA Only compiles the classes that have been changed since the last build, and when you change Source or Target only then SourceTargetMapper won't be compiled. Maybe we need to raise an issue with Jetbrains.

>I as well am not that well knowledgeable of the internals of IDEA and if someone has an idea or is willing to help out with this I am more than happy to tag along. I've asked on [twitter](https://twitter.com/filiphr/status/933405067939631128), let's see if we get some more info

**Comment by abdul0214** [comment]
I am facing the same issue.

**Comment by filiphr** [comment]
@abdul0214 are you using the latest IntelliJ (2020.3)?

**Comment by abdul0214** [comment]
Hi, yes I was using the latest IntelliJ (2020.3).

**Comment by nettadhp** [comment]
@filiphr I have stumbled across this issue as well (Intelli 2022.1.1). I'm not an expert on how intellij works but I'm wondering if this issue stems from the fact that mapstruct (as opposed to lombok for example) has a mapping file that separate from the objects being mapped. What if you were to add a helper annotation that we could add to the objects being mapped. Could something like that potentially trigger a code regeneration in intellij?

**Comment by neverkah** [comment]
do not use eclipse compiler ,use javac complier

**Comment by luchuanbaker** [comment]
@filiphr You can refer to the implementation of lombok，we can add -javaagent:{absolute path of lombok jar} to the config of intellij idea，the config path is "build, execetion  -> Compiler -> Shared build process vm options".
The entry class in lombok is lombok.launch.Agent，that means the class method will be called each time when intellij idea start to compile java files. Lombok add an patch for ecj by this way.
You can read the source code of lombok for more details.
And the mapstruct will not regenerate code when using ecj even if modify the mapper code，the only way is rebuild the whole project which will waste a lot of time.

**Comment by filiphr** [comment]
@luchuanbaker the reason why Lombok needs an agent is because it is not a proper annotation processor, it modifies the existing class. MapStruct is an annotation processor and generates new classes. If something is not working then you need to take this up with Eclipse or IntelliJ.
