### ISSUE TITLE
update gradle installation

### ISSUE THREAD

**Issue by stianrincon** [mapstruct/mapstruct#1695]
It would be greate to update the documentation about installing mapstruct with gradle. With the latest version of net.ltgt.apt the installing proccess should be like this:

  ```
  implementation "org.mapstruct:mapstruct:${mapstruct}"
  annotationProcessor "org.mapstruct:mapstruct-processor:${mapstruct}"
```

If you do not mind I can help with that

**Comment by filiphr** [comment]
>If you do not mind I can help with that

Of course we don't mind. The documentation file is https://github.com/mapstruct/mapstruct/blob/master/documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, feel free create a PR for us to merge it
