### ISSUE TITLE
Make possible to reference `@MappingTarget` in `@Mapping` parameter by name

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1705]
I think its possible to link to the source, by referencing the parameter name. Not sure whether this is also the case for the `@MappingTarget` annotated target parameter. Anyway..Stuff should be consistent (also when inheriting such method in a regular mapping method or doing inverses ).

**Comment by sjaakd** [comment]
I'm not sure wether or not this is already supported..

**Comment by thunderhook** [comment]
Just stumbled accross this by accident.

Just did a quick test, it is possible to reference it via `"."` but not with the parameter name:

```java
@Mapper
interface Issue1705Mapper {

    PersonDto map(Person source);

    @Mapping( source = "owner", target = ".")
    // @Mapping( source = "owner", target = "target") // does not work
    void update(Company source, @MappingTarget PersonDto target);
}

class Person {
    public String name;
}

class PersonDto {
    public String name;
}

class Company {
    public Person owner;
}
```

**Comment by filiphr** [comment]
I'm not sure that we need to be consistent here. We do support `target = "."`. Supporting the source parameter name would add extra complexity with almost no benefit.

**Comment by filiphr** [comment]
Therefore, I would say we should close this issue and not support this.

**Comment by thunderhook** [comment]
Okay for me.
