### ISSUE TITLE
Generate Chain Style Value Setting For Builder

### ISSUE THREAD

**Issue by ardenwong** [mapstruct/mapstruct#1706]
I am using the builder of latest 1.3.0.Beta2. 

Can we generate the code of the mapper with chain style value setting for builder, like: 
```
builder.name(dto.getName()).id(dto.getId()).build();
```
Currently, I can only genreate code with the value setting like:
```
builder.name( dto.getName() );
builder.id( dto.getId());
```

Thanks.

**Comment by sjaakd** [comment]
Fluent style is currently not supported.. could be there's already an issue on that

**Comment by sjaakd** [comment]
Not sure whether to support this though. It adds a lot of complexity to the current MapStruct solution without bringing something real in return apart from syntactic sugar in generated code..

**Comment by sjaakd** [comment]
@filiphr .. what's your take on this?

**Comment by filiphr** [comment]
With the current way we are doing the mapping it would be too complex to support chained builders.

There are a lot of different variables involved in this. There are null checks, lifecycle methods. I don't see spending time from the MapStruct team on this issue. If someone from the community wants to jump in and add such support we would review it of course.

@ardenwong what's the reason for the chained builder? Apart from the obvious that it looks a bit better in the default setting (without null checks and lifecycle hooks).

**Comment by chris922** [comment]
Fully agree with @filiphr . Of course one of the goals of MapStruct is to provide good readable code, but fluent style/chaining will not improve the readability so much and I would also expect that it is a high effort to implement this still considering all the `null`-checks and other stuff that is done right now.
