### ISSUE TITLE
CDI Injection problem when using a mapper into an another

### ISSUE THREAD

**Issue by GregoryDeclerck** [mapstruct/mapstruct#1711]
Hi all, 

I have an issue when I use the "uses" attribute of the @Mapper annotation. The mapper that I want to use into an another mapper is always null. 
The injection seems doesn't be applied.
The mapper works well when it was injected in my other classes. 
I tried to used the "injectionStrategy = InjectionStrategy.CONSTRUCTOR" but nothing changes.
I have the same problems with the last stable version and the last beta version of Mapstruct. My environnement is a Standard JEE with CDI and jdk8 on wildfly .
Have you ever encountered this problem?

**Comment by GregoryDeclerck** [comment]
Some code  to explain my problem : 

I get the parent mapper like this
```
@Inject
ParentMapper parent;
```
The parent mapper definition
```
@Mapper(componentModel = "cdi", uses = ChildMapper.class,injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface ParentMapper  {
@Mappings({
            ....
            @Mapping(target="childs",source="childs") //we need here the ChildMapper to map this object
    })
    DtoParent mapTo(Parent entity, @Context SomeContext context);
}
```
The child mapper definition
```
@Mapper(componentModel = "cdi",injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface ChildMapper{
             @Mappings({
            @Mapping(target="name",source="name"),
    })
    DtoChild mapTo(Child entity);
}
```
The generated class
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-01-15T10:55:00+0100",
    comments = "version: 1.3.0.Beta2, compiler: javac, environment: Java 1.8.0_181 (Oracle Corporation)"
)
@ApplicationScoped
public class ParentMapperImpl implements ParentMapper {
    private ChildMapper childMapper;
    public ParentMapperImpl() {    }
    @Inject
    public ParentMapperImpl (ChildMapper childMapper) {
        this.childMapper= childMapper;
    }
    @Override
    public DtoParent mapTo(Parent entity, SomeContext context) {
        if ( entity == null ) {            return null;        }
        DtoParent dtoParent = new DtoParent();
        context.completeData( entity, dtoParent );
        dtoParent .setChilds(childMapper.mapTo( entity.getChilds() ) ); //childMapper is null, so throw nullpointer
        return dtoParent ;
    }
```
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-01-15T10:54:59+0100",
    comments = "version: 1.3.0.Beta2, compiler: javac, environment: Java 1.8.0_181 (Oracle Corporation)"
)
@ApplicationScoped
public class ChildMapperImpl implements ChildMapper {
    @Override
    public DtoChild mapTo(Child entity) {
        if ( entity == null ) {            return null;        }
        DtoChild dtoChild = new DtoChild ();
        dtoChild .setId( entity.getId() );
        return dtoChild ;
    }
 @Override
    public List<DtoChild > mapTo(List<Child > list) {
        if ( list == null ) {            return null;        }
        List<DtoChild > list1 = new ArrayList<DtoChild >( list.size() );
        for ( Child child: list ) {
            list1.add( mapTo( child) );
        }
        return list1;
    }
```

**Comment by sjaakd** [comment]
the generated code looks ok. So I reckon its a problem with CDI.. 

* Perhaps a trivial question, but did you include the `beans.xml` to trigger CDI in your META-INF? 
* Can you see whether weld is starting? 
* What is your entry point? Bean? Servlet?

**Comment by GregoryDeclerck** [comment]
Hi @sjaakd , Yes I have my beans.xml into the META-INF...
It looks like that : 
```
<?xml version="1.0"?>
<beans bean-discovery-mode="annotated" version="1.1"
 xmlns="http://xmlns.jcp.org/xml/ns/javaee"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd">
</beans>
```
Weld is started, I have no problem to use it mapstruct with it in my application except in this case.

I used it into a jaxrs API.

**Comment by sjaakd** [comment]
Ok. So, how do you call your `ParentMapper`? Do you inject this somewhere?

**Comment by GregoryDeclerck** [comment]
Yes like that into my ,
```
@RequestScoped
public class MyJaxRsApiImpl implements MyJaxRsApi {
@Inject
ParentMapper parent;
...
```

 and it works for him but not for his child

**Comment by sjaakd** [comment]
Just to try.. can you remove the `@RequestScoped`??

**Comment by sjaakd** [comment]
From the generated code I cannot see what MapStruct is doing wrong.. You could try it yourself to make a few simple classes to follow this pattern. Perhaps try to leave out the empty constructor in `ParentMapperImpl` to see whether this is causing any problem. But I understood that even without constructor injection there was a problem, right?

Could it be that your child mapper (or implement) is not on the classpath? Check the .ear / .war file..

**Comment by GregoryDeclerck** [comment]
> Just to try.. can you remove the `@RequestScoped`??
It doesn't work too if I remove the `@RequestScoped`

> Perhaps try to leave out the empty constructor in `ParentMapperImpl` to see whether this is causing any problem. But I understood that even without constructor injection there was a problem, right?
yes I have the same issue InjectionStrategy.CONSTRUCTOR

> Could it be that your child mapper (or implement) is not on the classpath? Check the .ear / .war file..
The ChildMapper +  ChildMapperImpl class are into my war file. 

> From the generated code I cannot see what MapStruct is doing wrong.. You could try it yourself to make a few simple classes to follow this pattern.
I think the problem comes from my application but I don't understand what's wrong. It looks like the ParentMapper was loaded by Weld before ChildMapper, something like that ... I'm not very familiar with Weld ... i'm digging into that direction

**Comment by sjaakd** [comment]
> I think the problem comes from my application but I don't understand what's wrong. It looks like the ParentMapper was loaded by Weld before ChildMapper, something like that ... I'm not very familiar with Weld ... i'm digging into that direction

Normally Weld does constructor injection first and I think it even makes a pool of `ParentMapperImpl`.. 

I myself use Intelij, and it shows by means of Icons what is injected and produced. That helps to discover problems before  you deploy. 

Anyway.. I don't think this is  a MapStruct problem.  Can I close this one?

**Comment by GregoryDeclerck** [comment]
I use Intellij too, and I can see the parent and child mapper into the Java Enterprise Panel ->CDI.

If you are sure that not mapstruct the problem, you can close this issue. 
I will come back later with a solution, if I find something.
