### ISSUE TITLE
Compilation fails when using static method imports for non-static methods from @UtilityClass

### ISSUE THREAD

**Issue by SimSonic** [mapstruct/mapstruct#1717]
- [x] Is this an issue (and hence not a question)? 

When I use statically imported methods from lombok's @UtilityClass compilation fails.
The case is applicable to that methods of utility class that are not explicitly marked as static.

Example:
```java
import static ru.simsonic.experiments.lombokmapstruct.CustomUtils.makeCustom;

public class MapStructIssue1717Example {

    @Data
    public static class Source {
        private String text;
    }

    @Data
    public static class Target {
        private String text;
        private boolean custom;
    }

    @Mapper
    public abstract static class SourceTargetConverter {

        public abstract Target toTarget(Source source);

        @AfterMapping
        public void after(@MappingTarget Target target) {
            makeCustom(target);
        }
    }

    public static void main(String[] args) {
        Source source = new Source();
        source.setText("String value");
        System.out.println("Source: " + source);

        SourceTargetConverter sourceTargetConverter = Mappers.getMapper(SourceTargetConverter.class);

        Target target = sourceTargetConverter.toTarget(source);
        System.out.println("Target: " + target);
    }
}
```

```java
@UtilityClass
public class CustomUtils {

    public void makeCustom(MapStructIssueExample.Target target) {
        target.setCustom(true);
    }
}
```

First hotfix: add `static` keyword to CustomUtils#makeCustom definition.
Second hotfix: Do not use static import, import CustomUtils class instead and call `CustomUtils.makeCustom(...)`.

**Comment by filiphr** [comment]
@SimSonic sorry but I am not exactly following. What exactly is the problem? Does MapStruct fail to generate some code or is it something else?

From what I can see you are using the `CustomUtils` in an `@AfterMapping` method and MapStruct is not using hat class.

**Comment by SimSonic** [comment]
@filiphr I really don't know where is the problem — in mapstruct or in lombok.
Definitely the whole stage of annotation processors fails (mapstruct skips generating .java mapper implementations and lombok skips generation of his .class files).
In maven log even with -X option I see only javac's errors around unknown classes/methods.

This error is raises when:
- there is some utility class with lombok's **`@UtilityClass`** annotation
- there is method in this utility class which **has no explicit `static` keyword** added (lombok do it in his phase).
- mapstruct mapper imports this method **statically**: `import some.demo.pkg.SomeUtils.someMethod;` 

If replace static import to import of class and invoke method like `... = SomeClass.someMethod(...);`, the error goes away.
If add `static` keyword to the someMethod, error goes away too.

**Comment by filiphr** [comment]
@SimSonic this sounds like a configuration problem. How does your pom look like? Where is the `mapstruct-processor` defined? In the `maven-compiler` `annotationProcessorPaths` or as a provided dependency?

**Comment by SimSonic** [comment]
@filiphr Don't think so. I've pushed minimal example here: https://github.com/SimSonic/lombok-mapstruct-builders-example/tree/issue1717
Tested with maven 3.5.3 and 3.6.0.

**Comment by Captain1653** [comment]
I'm not sure, but I think you can't use static  import not for static member. Some quote from documentation "The static import construct **allows unqualified access to static members without inheriting** from the type containing the static members. Instead, the program imports the members, either individually:" .  [Full documentation about it](https://docs.oracle.com/javase/7/docs/technotes/guides/language/static-import.html)   . I think you should make your method static.

**Comment by filiphr** [comment]
This has nothing to do with MapStruct. Reading about the Lombok [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass) it clearly says 

>Due to a peculiar way javac processes static imports, trying to do a non-star static import of any of the members of a `@UtilityClass` won't work. Either use a star static import: `import static TypeMarkedWithUtilityClass.*;` or don't statically import any of the members.
