### ISSUE TITLE
MapStruct 1.3.0.Final doesn't ignore public non-static valueN methods of JOOQ Records

### ISSUE THREAD

**Issue by jmorozov** [mapstruct/mapstruct#1726]
Hello. I use Mapstruct and JOOQ for mapping between record-class (generated implementation of  [Record](https://www.jooq.org/javadoc/3.10.7/org/jooq/Record.html)) and POJO. I tried to switch from Mapstruct 1.2.0.Final to 1.3.0.Final. But I get compilation errors like this - `Unmapped target properties: "value1, value2, value3, value4"`.

JOOQ generate record-class with usual setters/getters and some public non-static methods with a name like `valueN`. `valueN` methods generates for each setter/getter. `valueN` methods declared in subinterfaces of Record ([example of subinterface](https://www.jooq.org/javadoc/3.10.7/org/jooq/Record1.html#value1-T1-)). I want to use only the usual setters/getters in mappers because `valueN` methods have a different purpose.

With Mapstruct 1.2.0.Final it works perfectly fine. `valueN` methods ignored in generated mappers. Generated mappers use only getters-setters. I didn't set ignore for `valueN` explicitly.

Could you consider this case and perhaps not determine these `valueN` methods as fluent-setters-getters like in 1.2.0.Final version? 
And also if you could add a simple option to disable fluent setters, it will be great too. Thank you.

P.S. I created this issue after asking the question on [StackOverflow](https://stackoverflow.com/questions/54744468/mapstruct-1-3-0-final-dont-ignore-non-getter-setter-methods)

**Comment by sjaakd** [comment]
I saw you accepted the answer on SO.. I added another alternative there. I'm continuing to close the issue here.

**Comment by filiphr** [comment]
@sjaakd I still think that we need to have an option that would disable fluent setter over a compiler option or something like that. I say we keep this open in order to implement that.

**Comment by filiphr** [comment]
Closing this in favour of #3211 where we've discussed into more detail about what we can do about the different accessor strategies
