### ISSUE TITLE
NullValuePropertyMappingStrategy.SET_TO_DEFAULT on @Mapper does not work as expected

### ISSUE THREAD

**Issue by srdanb** [mapstruct/mapstruct#1727]
```
@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT)
public interface oMapper {
@Mapping(target = "prop2", source = "prop1")
Obj2 o2o(Obj1 o1);

```
does not generate 
`if (o1.prop1 != null) { o2.prop2 = o1.prop1; } else { o2.prop2 = "";  }`
prop1 and prop2 are String-s, using 1.3.0.Final

**Comment by sjaakd** [comment]
NullValuePropertyMappingStrategy only applies to update method (with `@MappingTarget`).

@filiphr ..the question has come up before..  perhaps we should deprecate this one in favour of `NullValuePropertyMergeStrategy` or  something like that..

**Comment by filiphr** [comment]
@sjaakd I don't think we should deprecate it, we just added it in 1.3 😄. Maybe we need to document it, but I even think that it already is documented enough

**Comment by sjaakd** [comment]
> we just added it in 1.3

I know... But lets keep an eye out for this one.. If the name is confusing..

**Comment by srdanb** [comment]
@sjaakd and @filiphr 
Thank you for the reply. May I ask why was NullValuePropertyMappingStrategy implemented only on update methods? I have an null-agnostic source and would like to avoid writing Mapping annotations for all properties, let alone repeating defaultValue.

**Comment by sjaakd** [comment]
At the moment of implementing the code we decided this scenario would be handled as following: 

1. You should use the `NullValueCheckStrategy` ICW an object factory (annotated with `@ObjectFactory`)  that returns the object you want as default..  

Later I added some  pre-defined defaults (mainly for primitive types + their respective boxed types) , which I realize are handy in regular methods as well. Problem being: the `NullValueCheckStrategy` starts to overlap with the `NullValuePropertyMapping` strategy.. 

If only I could redesign this from the start :smile: .. Perhaps something to consider for 2.0..  @filiphr : WDYT?

Please let us know if this is a doable scenario.
