### ISSUE TITLE
Inverse mapping does not working well on default functions 

### ISSUE THREAD

**Issue by makahleh** [mapstruct/mapstruct#1729]
**Hello,
Sorry but i'm new to mapstruct,
lets say we have Door, Car classes & DoorDTO, CarDTO as shown below,

Do i have to write the inverse function of doorsToDoorsDTO to get carDTOToCar works correctly??

Note: i added @InheritInverseConfiguration on doorsToDoorsDTO but still the generated code is not right !**

```java
public class Door{
Long id;
String name;
String color;
..
..
}
public class DoorDTO {
Long id;
String name;
}

public class Car {
List<Door> doors;
}

public class CarDTO {
List<DoorDTO> doorDTOs;
}

@Mapper
public interface MyMapper {
    CarDTO carToCarDTO(Car car);

    @InheritInverseConfiguration
    Car carDTOToCar(CarDTO carDTO);

List<Door> doorsToDoorsDTO(List<Door> doors){
List<DoorDTO> doorDTOs = new ArrayList<>();
doors.foreach(door -> {
DoorDTO doorDTO = new DoorDTO();
doorDTO.setId(door.getId());
doorDTO.setName(door.getName());
doorDTOs .add(doorDTO);
});

return doorDTOs;
}
}
```

**Comment by sjaakd** [comment]
@makahleh .. this is a question and belongs on SO..

However: you only need to provide an additional mapping method `DoorDTO toDoor(Door door)` in your Mapper.. (and its inverse)  MapStruct will generate the list for you..
