### ISSUE TITLE
nullValuePropertyMappingStrategy is not applicable with @BeanMapping

### ISSUE THREAD

**Issue by mdoskoc** [mapstruct/mapstruct#1733]
We want to upgrade from Mapstruct 1.3.0.Beta2 to 1.3.0.Final version but we found out that there is no nullValuePropertyMappingStrategy for @BeanMapping
as 1.3.0.Final reference guide stated

> By specifying nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE on @Mapping, @BeanMapping, @Mapper or @MappingConfig, the mapping result will be equal to the original value of the @MappingTarget annotated target.

Sadly there is no such option for @BeanMapping. We want to ignore all null values from source. Any suggestion how to achieve such behavior ?

**Comment by sjaakd** [comment]
?? Are you sure? What about [here](https://github.com/mapstruct/mapstruct/blob/master/core/src/main/java/org/mapstruct/BeanMapping.java)? 

Or is it not working? I'll proceed to close this issue.. Feel free to re-open, if you find there' s an issue.

**Comment by filiphr** [comment]
>Sadly there is no such option for `@BeanMapping`. We want to ignore all null values from source. Any suggestion how to achieve such behavior ?

As @sjaakd pointed out there is an option for setting `NullValuePropertyMappingStrategy` in `@BeanMapping`. It is [here](http://mapstruct.org/documentation/dev/api/org/mapstruct/BeanMapping.html#nullValuePropertyMappingStrategy--) in the Javadoc as well.

When you say you want to ignore all null values, not sure if you are talking about update mappings or not. For update mappings you need to use `NullValuePropertyMappingStrategy` you would need set that to ignore. For normal mappings you just need to use `NullValueCheckStrategy.ALWAYS` as in normal mappings if it is null it is always ignored.
