### ISSUE TITLE
Use sub-mapping for mapping two args

### ISSUE THREAD

**Issue by paxmus** [mapstruct/mapstruct#1734]
This is my example.

```
public class Company {
	....
	private String companyName;
	....
}

public class Employee {
	....
	private String name;
	....
}

public class EmployeeDto {
	....
	private String name;
	private String companyName;
	....
}

@Mapper(componentModel = "spring")
public interface EmployeeDtoMapper {

	@Mapping(target = "name", source = "source1.name")
	@Mapping(target = "companyName", source = "source2.companyName")
	EmployeeDto toDto(Employee source1, Company source2);

	List<EmployeeDto> toDtos(List<Employee> sources, @Context Company source2);
	
}
```

I want that the method toDtos use toDto to map Employee to EmployeeDto but mapstruct generate a employeeDtoToEmployeeDto method.
How can I fix it ?

thanks

**Comment by sjaakd** [comment]
please use stackoverflow for questions..

MapStruct does not select mapping methods based on multiple source args. It only can map source to target. Hence the `@Context` annotation.. It means the parameter source2 is not used in the mapping as source or target.

**Comment by paxmus** [comment]
Ok thanks
