### ISSUE TITLE
AUTO_INHERIT_ALL_FROM_CONFIG not used in forging methods.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1736]
Sometimes its handy to have a MapperConfig and let MapStruct generate the implementation. e.g. I've got a merge mapper from DTO to entity and a regular mapper sharing a common config.

Nothing forged is inherited from the mapper config.

**Comment by filiphr** [comment]
@sjaakd is this one same as https://github.com/mapstruct/mapstruct/issues/1086?

**Comment by sjaakd** [comment]
yes it is. I'll close this one..
