### ISSUE TITLE
MapStruct producing uncompilable code when using bounded wildcard

### ISSUE THREAD

**Issue by DanielArthurUK** [mapstruct/mapstruct#1738]
Hello there :wave: 

As a bit of context, I am using JAXB as a way to convert XML messages to Java POJOs, and then using MapStruct to map those objects onto domain objects that my application uses. I have come across an issue in the way that MapStruct generates code when I use a bounded wildcard (e.g. `B<? extends C>`) in a source field. Here's an example:

```java
public class A {
  private B<? extends C> someField;
}
```
Let's say that `B` has a field `anotherField`. If I try to access any fields of `B` in a MapStruct `source` parameter, like this:

```java
@Mapping(source = "b.anotherField")
```

Then the generated code doesn't compile. I get something like this:

```java
private ? extends C mappingMethod(A mappingInput) {
  ? extends C someField = b.getSomeField();
  ...
}
```

This Java code obviously does not compile. The reason that I mention JAXB is that some of the source POJO's fields have a type of `JAXBElement<? extends SomeType>` which we can't really change.

Sorry for the abstract example, I can't display the actual code I am working on as it's part of a work project. If needed I can produce a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).

I am using `mapstruct-jdk8` version **1.3.0.Final**

Many thanks :smile:

**Comment by sjaakd** [comment]
@DanielArthurUK thanks for your feedback.. An minimal working example would be appreciated (saves me time :smile: ), and I usually use them as unit test reproducer.

**Comment by filiphr** [comment]
I've managed to reproduce this. Working on a fix now.

Btw @DanielArthurUK `mapstruct-jdk8` is now deprecated and you can use `mapstruct` instead.

**Comment by filiphr** [comment]
I've found a fix, thanks for reporting this @DanielArthurUK. Fix will be shortly merged into master

**Comment by filiphr** [comment]
This has been fixed on master. Thanks for reporting it @DanielArthurUK

**Comment by DanielArthurUK** [comment]
Sorry guys, I never found the time to reproduce this. Thanks for doing that and fixing @filiphr!

Also I didn't realise we could just use `mapstruct` instead now, much appreciated! 😄
