### ISSUE TITLE
MapStruct should return the target object(which marking with @MappingTarget) when the source object is null

### ISSUE THREAD

**Issue by snfdf** [mapstruct/mapstruct#1752]
The generated code as follow:

    public TbsSpecification yjlGoodsAttribute2Spec(YjlGoodsAttribute yjlGoodsAttribute, TbsSpecification tbsSpecification) {
        if ( yjlGoodsAttribute == null ) {
            return null;
        }

        tbsSpecification.setModifiedTime( java.time.LocalDateTime.now() );

        return tbsSpecification;
    }

when yjlGoodsAttribute is null, the method should be return tbsSpecification.

**Comment by sjaakd** [comment]
I think we have the `NullValueMappingStrategy`.. Have a look. But I don't think it takes this scenario into account.  The scenario where you have a 
1. And a mapping target
2. And a return type.

You might want to try the `@BeforeMapping` to overcome this, but I'm not entirely sure where the code is inserted.

Do you need this feature? For the time being I'll add it as a feature request to extend the `NullValueMappingStrategy`..

**Comment by filiphr** [comment]
@sjaakd I am not sure if this is a feature or just an enhancement. I think that in the [BeanMapingMethod#L23](https://github.com/mapstruct/mapstruct/blob/63c5fc8effdd5cbf7e3aac96d5149235fd3dcba6/processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl#L23) we should check for an existing instance mapping and return that instead of `null`. 

I think that this is quite easy to do. @snfdf will you be willing do provide a PR for this change?

**Comment by Captain1653** [comment]
@sjaakd @filiphr  I have tried to implement this feature. My naive implementation you can see on the pictures. I understand, it isn't complete, but I worry about Issue 374 (I have attached the picture). 
Next question about builders. Should the feature work for them or not?

Correct my mistakes, please :)

![@MappingTarget with strateg RETURN_NULL](https://user-images.githubusercontent.com/4740207/63213805-51aac500-c119-11e9-8f9c-0ed3162dacd9.png)
![naive implementation](https://user-images.githubusercontent.com/4740207/63213806-51aac500-c119-11e9-8928-dba33983b749.png)

**Comment by filiphr** [comment]
@Captain1653 that is an interesting observation. Perhaps we should completely ignore `NullValueMappingStrategy` for update methods, or maybe only use it to decide whether to do apply constants or not, but not whether to return `null` or not. Looking in our documentation for [Updating existing bean instances](http://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances) we say

>The generated code of the updateCarFromDto() method will update the passed Car instance with the properties from the given CarDto object. There may be only one parameter marked as mapping target. Instead of void you may also set the method’s return type to the type of the target parameter, which will cause the generated implementation to update the passed mapping target and return it as well. This allows for fluent invocations of mapping methods.

We say that we return the passed mapping target. So I would say that this is even a bug in relation to what we say in our documentation.

**Comment by Captain1653** [comment]
@filiphr I have read documentation again:
10.1. Default values and constants
10.2. Expressions
10.3. Default Expressions

I didn't find there any information about using nullCheckPolicies with constant, defaultValue, defaultExpression. We say about "null value" but, not for nullCheckPolicies. 
What are we going to do:

1. Should we  apply defaultValue, defaultExpression and others if all parameters except @MappingTarget are null? (I think no, if all parameters are null - we should return @MappingTarget without changing)
2. Should we do  transformations defaultValue, defaultExpression, constant if all parameters are null? (Or maybe some additional transformations?)

Maybe we should more clearly to write about it in our documentation.

Maybe I'm wrong ))
