### ISSUE TITLE
Explicit decorator override for collections.

### ISSUE THREAD

**Issue by nnsns** [mapstruct/mapstruct#1753]
Simple is example:
```
@Mapper
@DecoratedWith(CardMapperDecorator.class)
public interface CardMapper {
    CardDto convert(CardEntity entity);
    List<CardDto> convert(List<CardEntity> list);
}
```
And decorator:
```
public abstract class CardMapperDecorator implements CardMapper {
    @Autowired
    @Qualifier("delegate")
    private CardMapper delegate;

    @Override
    public CardDto convert(CardEntity entity) {
        CardDto dto = delegate.convert(entity);
        // something
        return dto;
    }
}
```

It would be reasonable to assume that there is no need for explicit override for collection mapping. 
However, the overridden method works as expected, the collection method with same object ignores decorator method. So it is necessary to create and convert the collection manually:

```
    @Override
    public List<CardDto> convert(List<CardEntity> entities) {
        List<CardDto> dtos = new ArrayList<>();
        entities.forEach(x -> dtos.add(convert(x)));
        return dtos;
    }
```

Not sure that this is by design.

**Comment by chris922** [comment]
Please take a look at #1750. I think there is nothing that we really can do, for me it "works like designed"... even if it is definitely confusing! 😕 

I will close this one as this looks for me like a duplicate. If this is not the case just let me know and we can re-open it.

**Comment by nnsns** [comment]
> I will close this one as this looks for me like a duplicate. If this is not the case just let me know and we can re-open it.

I think, this can be labeled as for team discussion.
