### ISSUE TITLE
Deprecate decorators?

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct#1754]
Sometimes there are questions coming up regarding decorators so it seems for me that they are widely used.

Nevertheless I think with the availability of `@BeforeMapping`, `@AfterMapping` and everything else that we have to hook into the generated methods we might not need decorators anymore.

Or am I missing a point that could only be solved using decorators?

So my proposal is:
1. Deprecate decorators
2. Or highlight for example in the reference guide "decorators" section what things can be done in a different ways and also show some constraints/possible issues using decorators (for example #1750)

**Comment by gunnarmorling** [comment]
I don't think deprecating is a good idea; decorators and the before/after hooks service different purposes: the former are attached to a specific interface/method, whereas the latter are generic interceptors dealing with different method signatures. It's comparable to decorators and interceptors in CDI, which also both have their different purposes.

**Comment by sjaakd** [comment]
I remember there was somewhere an issue that MapStruct did not call back on the decorator when handling nested mappings (e.g. inside a bean mapping), rendering the usage of the decorator a bit unexpected (I just looked for the issue: I thought that I wrote it a couple of years ago, but could not find it. I'm also not sure whether this was only for the standard component model. If so, we should probably warn for that situation, or perhaps even deprecate that specific usage (if thats is possible at all).

**Comment by sjaakd** [comment]
related to  #1307

**Comment by filiphr** [comment]
I also don't think that we should deprecate them. I agree with @chris922 that perhaps some usages of the decorators can be replaced with `@BeforeMapping` or `@AfterMapping`. However, there are certainly usages (that I might as well not be aware of) where decorators make a lot more sense. One usage would be to wrap the objects being mapped with some kind of proxy that would perform validation on the input or do something else.

Therefore I would propose that we leave this as is and close this issue. 

If there are some issues with the decorators we should fix them, we can also point people into using `@BeforeMapping` or `@AfterMapping` if in that situation that fits better.

**Comment by nnsns** [comment]
I propose to consider the need to add a new parameter/annotation
```
@EMapping(use_decorator=true/false)
@BeanMapping(use_decorator=true/false)
```
 discussed here: https://github.com/mapstruct/mapstruct/issues/1750#issuecomment-473978982

**Comment by baurchanu** [comment]
Hi, is it possible now to add a validation like [this](https://stackoverflow.com/questions/43391995/mapstruct-mapping-return-null-object-if-all-source-parameters-properties-are-n) without using a decorator?

**Comment by filiphr** [comment]
@nnsns this issue is not about adding a new parameter / annotation. Please continue that discussion in the other issue.

@baurchanu no something like that it is not possible without a decorator.

**Comment by sjaakd** [comment]
I guess this discussion has been around long enough. Any objections? Otherwise I'll close this issue and we remove the `@Experimental` annotation from the decorators and make them fully available.
