### ISSUE TITLE
Vague message when handling nested property mapping.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1756]
When creating an empty bean (nested), MapStruct cannot (in the absence of properties) create a mapping. Therefore it stops and suggest to implement a hand written method. The error message however does not really point to the case.

**Comment by sjaakd** [comment]
solved by PR #1757

**Comment by filiphr** [comment]
Reopening as the current changes need to be reworked. See my comment in the PR

**Comment by filiphr** [comment]
I shouldn't be commenting when I am tired it seems 😄. I was looking in the wrong place.

**Comment by sjaakd** [comment]
> I shouldn't be commenting when I am tired it seems

I'm in need of some sleept too :smile:.. Have a nice evening!
