### ISSUE TITLE
what would be the configuration for mapStruct to stop mapping a DTO's super class's fields?

### ISSUE THREAD

**Issue by Puspendert** [mapstruct/mapstruct#1768]
I am having a DTOs class which is extending `spring-hateoas`'s `ResourceSupport` class. The `UserMinimalDto` is a DTO for `User` entity.

So, for generating the mapper classes, I am using **mapStruct**.

```
@Data //from lambok
@EqualsAndHashCode(callSuper=false)
public class UserMinimalDto extends ResourceSupport {

    String firstName;
    String lastName;
    String email;
    String uniqueId;
    String profilePicUrl;

}
```

I am using `ResourceSupport` to add Hateoas links to the response from the controller.

The Mapper interface

```
@Mapper
public interface UserMinimalMapper {

    UserMinimalMapper INSTANCE = Mappers.getMapper(UserMinimalMapper.class) ;

    UserMinimalDto entityToDto(User user);

    User dtoToEntity(UserMinimalDto userMinimalDto);
}

```
But when I run mvn clean install on the project, I am facing compilation error

> Can't map property "org.springframework.hateoas.Link id" to "java.lang.Integer id". Consider to declare/implement a mapping method: "java.lang.Integer map(org.springframework.hateoas.Link value)".

This is because the **mapStruct** is trying the map some fields of `User` entity with `ResourceSupport`. Which I ofcourse don't want.

Its works if:

1. I remove `extends ResourceSupport` from `UserMinimalDto`

2. I remove `dtoToEntity(UserMinimalDto userMinimalDto);` from mapper interface

What would be the configuration to tell **mapStruct** to not map the super class(`ResourceSupport` here) fields?

**Comment by filiphr** [comment]
Please do not crosspost questions. I see that you have already posted your [question](https://stackoverflow.com/questions/55321500/what-would-be-the-configuration-for-mapstruct-to-stop-mapping-a-dtos-super-clas/55322804) on StackOverflow. I've already answered it there.
