### ISSUE TITLE
Can't reuse other mapper when component is Spring

### ISSUE THREAD

**Issue by trungdoviet** [mapstruct/mapstruct#1771]
I have three classes (model <-> DTO)
- **Student** come with **StudentMapper**
- **Teacher** come with **TeacherMapper**
- Now i have class **School** that contain student and teacher, i want to reuse the StudentMapper and TeacherMapper so i define my mapper like this:
```java
@Mapper(componentModel="spring", uses={StudentMapper.java, TeacherMapper.java})
public interface SchoolMapper {
   TeacherDTO toDTO(Teacher teacher);
}
```
but in generated class, it only create new instance of TeacherDTO then return, not invoke any mapper that i mentioned on _uses_ attribute.
```java
public class SchoolMapperImpl implement SchoolMapper {
   public TeacherDTO toDTO(Teacher teacher){
       if(teacher == null){
         return null;
       }
      TeacherDTO dto = new TeacherDTO();
       return dto;
  }
}
```
Note: StudentMapper and TeacherMapper are also Spring component

Any hint for that?
I'm using version mapstruct 1.3 with SpringBoot , Inteliji IDEA

**Comment by chris922** [comment]
What is your expectation? Should the method just call `teacherMapper.toDTO(teacher)`?

**Comment by filiphr** [comment]
@trungdoviet please use [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) for asking questions about MapStruct.

@chris922 already replied, I am not sure what you expect MapStruct to do when you are creating a mapping method between `Teacher` and `TeacherDTO`
