### ISSUE TITLE
Documentation Update: jsr330/@DecoratedWith

### ISSUE THREAD

**Issue by jengelhart0** [mapstruct/mapstruct#1773]
The following section of the documentation claims Decorators are experimental with jsr330, but references an old version of the documentation:

> @DecoratedWith in combination with component model jsr330 is considered experimental as of the 1.0.0.CR2 release. The way the original mapper is referenced in the decorator or the way the decorated mapper is injected in the application code might still change.

Wondering if this documentation section can be updated to indicate that the feature is still experimental as of the latest release or be changed so it is no longer listed as experimental.

- [x] Is this an issue (and hence not a question)?

**Comment by Captain1653** [comment]
@filiphr @sjaakd  I have found some tests for it in the package org.mapstruct.ap.test.decorator.jsr330 . It seems it is no longer listed as experimental.  (Am I wrong?) Should I remove these lines from  documentation?

**Comment by sjaakd** [comment]
@Captain1653 its has been a discussion for some while. I think the way decorators work in the CDI / Spring context is fine. The standard component type has some drawbacks. A lot of this functionality can also be achieved with `@AfterMapping` and `@BeforeMapping`.. I guess there's even a complete discussion on it somewhere..

To make a long story short, I think we have to decide and as far as I'm concerned we remove the experimental label.

**Comment by sjaakd** [comment]
See also: https://github.com/mapstruct/mapstruct/issues/1307

**Comment by sjaakd** [comment]
And also: https://github.com/mapstruct/mapstruct/issues/1754

**Comment by filiphr** [comment]
We have the decorators for a while now and we haven't really changed anything in there. I would say if we have tests with jsr330 and Decorators then we remove the experimental
