### ISSUE TITLE
Compilation error: duplicate class with MapStruct in IntelliJ IDEA 2019.1

### ISSUE THREAD

**Issue by neerajjain92** [mapstruct/mapstruct#1774]
I am using Mapstruct for mapping between different Java Beans, but after installing the latest IntelliJ update, Compilation is getting failed with error:

```
Compilation error: duplicate class
```
Here are the version details of IntelliJ
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

**Comment by filiphr** [comment]
Where are the duplicate classes created? This error is quite strange, I am also on 2019.1 and I haven't noticed any problems

**Comment by neerajjain92** [comment]
Duplicate classes were getting created inside `.out` folder. Deleting that folder fixed the issue.

**Comment by filiphr** [comment]
Thanks for letting us know. This usually means that IntelliJ was not properly setup. It either picked up the maven properties wrong, or the gradle ones.

**Comment by feanor777** [comment]
I had the same issue, and it's really tricky.
Need to do next magic every time, after any changes in Mapstruct classes:
1. ./gradlew clean
2. remove `out` folder
2. Idea build project (cmd+F9)
3. ./gradlew clean build

Delegating IDE build to the Gradle solve the issue, but it brings others.
Like the wrong message during error in compilation time, bug with allowing to run the application in case of compilation error.
So, as for me, this issue is still opened.

**Comment by neerajjain92** [comment]
@filiphr IntelliJ is set up correctly and was working fine before this upgrade. I have to do the following steps.

Follow this process, whenever I have to rebuild the project.
1. `mvn clean`
2. Run the application from IntelliJ.

**Comment by edwincabezas7** [comment]
> I had the same issue, and it's really tricky.
> Need to do next magic every time, after any changes in Mapstruct classes:
> 
> 1. ./gradlew clean
> 2. remove `out` folder
> 3. Idea build project (cmd+F9)
> 4. ./gradlew clean build
> 
> Delegating IDE build to the Gradle solve the issue, but it brings others.
> Like the wrong message during error in compilation time, bug with allowing to run the application in case of compilation error.
> So, as for me, this issue is still opened.

This works for me, thanks

**Comment by filiphr** [comment]
@feanor777 the reason why this is marked as invalid is that it has nothing to do with MapStruct. MapStruct is an annotation processor. This means that the build tools java compilers are doing the compilation and invoking MapStruct and creating the generated classes. MapStruct itself does nothing for the integration with IntelliJ (in the sense of generating the mappers).

Perhaps it is a bug in IntelliJ or a misconfiguration of Gradle / Maven.

**Comment by feanor777** [comment]
@filiphr make sense.
I think, need to create a bug in IntelliJ bug tracker.

**Comment by joern** [comment]
Hi @feanor777 : could you resolve this with IDEA? Could you provide a link to youTrack?
Thanks!
