### ISSUE TITLE
nullValueMappingStrategy = DONT_CHECK

### ISSUE THREAD

**Issue by nnsns** [mapstruct/mapstruct#1775]
Mapstruct always check passed object for null. 
How about disable this functionality for cases where:

- the object is already checked in advance
- generating an exception is not a problem or even desirable
- minor performance improvement

I did not find the parameter to disable checking completely.
I suggest something like this:
`@BeanMapping(nullValueMappingStrategy = DONT_CHECK)`

**Comment by filiphr** [comment]
@nnsns I think that https://github.com/mapstruct/mapstruct/issues/1243 will cover your use case as well. I am closing it in favor of the initial issue. If you think that we need to reopen please do let us know

**Comment by nnsns** [comment]
@filiphr not sure that we talking about same. 
Here is an example of generated code by Mapstruct:

```
    @Override
    public CardDto convert(CardEntity entity) {
        if ( entity == null ) {
            return null;
        }

        CardDto cardDto = new CardDto();
        cardDto.setId( entity.getId() );
        cardDto.setOwnerName( entity.getOwnerName() );
        cardDto.setCardYear( entity.getCardYear() );
        cardDto.setCardMonth( entity.getCardMonth() );

        return cardDto;
    }
```

I have to constantly manually delete the first lines:

```
        if ( entity == null ) {
            return null;
        }
```
