### ISSUE TITLE
Inverted presence checker (absence checker)

### ISSUE THREAD

**Issue by baurchanu** [mapstruct/mapstruct#1776]
Hello. We use your framework in our project and face some limitations of using a presence checker feature. Now  it's impossible to check absence of a property using a custom method (hasNoX / isNullX), isn't it? So we need write something like @Mapping(target="X", expression="java(src.isNullX() ? null : src.getX())"). If absence checker functionality is interesting not only for us, I would implement this enhancement and submit PR.

**Comment by sjaakd** [comment]
Is already implemented. Checkout documentation

**Comment by baurchanu** [comment]
@sjaakd Could you please specify in which article of the documentation I can find example with a custom absence checker? I mean a checker with logic different than simple not null check ( `return X == null` ). Sorry for wasting your time, if I missed something.

**Comment by sjaakd** [comment]
http://mapstruct.org/documentation/stable/reference/html/#source-presence-check

**Comment by sjaakd** [comment]
Custom via spi

**Comment by sjaakd** [comment]
You can change the `hasX` into `isNull` in the SPI but you can't negate. So, the first thing that comes to my mind is to extend the SPI with some kind of boolean check (downward compatible), with default false; E.g. negate.

**Comment by filiphr** [comment]
@baurchanu, you don't have control over the objects with the `isNullX()` method?

@sjaakd I am not certain whether it is worthwhile to introduce such complexity. To me currently it sounds really specific and would really be interested what is generating those `isNullX()` methods (if it is not in the control of the OP)

**Comment by baurchanu** [comment]
@filiphr, yes, the objects are generated sources, and I have no opportunity to customize the process of the generation.
