### ISSUE TITLE
Inconssistence in support of containers (enum vs non enum type)

### ISSUE THREAD

**Issue by kwasny2** [mapstruct/mapstruct#1788]
Watch examples:

    public class Container {
        public Integer aInteger
    }

    @ Mapper
    public interface ContainerMapper {
        Container toContainer(Integer aInteger); //works ok
    } 

The same works for Long/Short/Boolean, but not works for enums!

    public class Container {
        public enum Type {
            ONE, TWO
        }

        public Type type;
    }

    @ Mapper
    public interface ContainerMapper {
        Container toContainer(Container.Type type); // does not work, why?
    } 

I expect to have working container creation and assignment. In real life I expect also to have possibility to use here mapping from one enum to another.

**Comment by filiphr** [comment]
There is an error message saying why it does not work.

>Can't generate mapping method from enum type to non-enum type.

> In real life I expect also to have possibility to use here mapping from one enum to another.

This is supported in MapStruct. Please have a look at [Values Mapping](http://mapstruct.org/documentation/stable/reference/html/#mapping-enum-types) in the MapStruct documentation.

Perhaps it would make sense to allow the mapping from enum to non enum by resorting to source parameter name mapping (which is what happens in the first case)

**Comment by kwasny2** [comment]
Indeed. Just allow the mapping from enum to non enum by resorting to source parameter name mapping (which is what happens in the first case). It will solve all my problems.

**Comment by sjaakd** [comment]
Is this related to #1557

**Comment by sjaakd** [comment]
solved on master.. @kwasny2 .. thanks for reporting.
