### ISSUE TITLE
New functionality: Expression support in @ValueMapping

### ISSUE THREAD

**Issue by seime** [mapstruct/mapstruct#1789]
Think of it as doing search/replace in your text editor with regex support.

The order of processing would be like

- exact matches between source and target
- `@ValueMapping` with exact source and target (inc `NULL`)
- `@ValueMappings` with expressions
- at the end `ANY_REMAINING` or `ANY_UNMAPPED`

Other considerations could be

- expression marker regex () could be omitted - but makes it difficult to later on include a different rule syntax?
- if either source or target is an expression then both should be treated as expressions?

A more or less complete example:

```
package org.mapstruct.ap.test.value;

import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ValueMapping;

@Mapper
public interface ValueExpressionMapper {

    @ValueMapping( source = "SPECIAL", target = "SPESIAL") // Exact mapping
    @ValueMapping( source = "regex( .* ) ", target = "regex ( PREFIX_$1 )") // Will match for RETAIL and map to PREFIX_RETAIL 
    @ValueMapping( source = "regex( .* ) ", target = "regex ( $1_POSTFIX )") // Will match for EXTRA and map to EXTRA_POSTFIX
    @ValueMapping( source = "regex( TRIM_THIS_AWAY_(.*) ) ", target = "regex ( $1 )") // Will match for TRIM_THIS_AWAY_EXPRESS and TRIM_THIS_AWAY_AIR and map to EXPRESS and AIR
    @ValueMapping( source = MappingConstants.NULL, target = "UNSPECIFIED") // Handle non existing source values
    @ValueMapping( source = MappingConstants.ANY_REMAINING, target = "UNSPECIFIED" ) // Handle non existing target values, source will match UNMAPPED
    ExternalExpressionOrderType map(OrderType source);

    // Source types
    public enum OrderType {

        RETAIL,  STANDARD, NORMAL, UNMAPPED, SPECIAL, TRIM_THIS_AWAY_EXPRESS, TRIM_THIS_AWAY_AIR
    }

    // Destination types
    public enum ExternalExpressionOrderType {

        PREFIX_RETAIL, STANDARD_POSTFIX, NORMAL, SPESIAL, UNSPECIFIED, EXPRESS, AIR
    }

}
```

- Initially only a SINGLE `@ValueMapping` with expression would be supported for each mapping method
- Initially no support for nested expressions
- Initially only support for REGEX expressions
- Unmapped source/target property checking would occur if either side is an enum, but not if they both are Strings/Numbers

See discussion at gitter (all message links copied, but they do all appear within a few sessions of discussion from March 8th 19 at 14:01 to March 27th 19 at 11:09)

- https://gitter.im/mapstruct/mapstruct-users?at=5c8259851fae6423ca4fc55a
- https://gitter.im/mapstruct/mapstruct-users?at=5c839455ac408e11922e5b66
- https://gitter.im/mapstruct/mapstruct-users?at=5c83ad84d1e7281f09fe1089
- https://gitter.im/mapstruct/mapstruct-users?at=5c83e0acd1e7281f09ff515e
- https://gitter.im/mapstruct/mapstruct-users?at=5c840e608f294b134a15ea73
- https://gitter.im/mapstruct/mapstruct-users?at=5c993f648aa66959b66e6275
- https://gitter.im/mapstruct/mapstruct-users?at=5c9aad522fb6800d80878659
- https://gitter.im/mapstruct/mapstruct-users?at=5c9b319e1f74fc4d4ca5b105
- https://gitter.im/mapstruct/mapstruct-users?at=5c9b4825e820b6470b6f9937
- https://gitter.im/mapstruct/mapstruct-users?at=5c9b4b2a81b15c5e4b942945
- https://gitter.im/mapstruct/mapstruct-users?at=5c9b4bc340b32b4c4fa3065f

This issue covers both #1220 and #796

**Comment by seime** [comment]
@sjaakd @filiphr We are starting to work on a PR for this one - anything we should be aware of?

**Comment by filiphr** [comment]
@seime I think that with the new additions (`EnumNamingStrategy` and `EnumTransformationStrategy`) a lot of the requested functionality can be achieved.

Do you agree with this? Shall we close this as resolved?

**Comment by seime** [comment]
@filiphr yes #2100 solves this one. Thanks
