### ISSUE TITLE
1.3.0.Final Regression in nullValuePropertyMappingStrategy when inherited

### ISSUE THREAD

**Issue by mnembrini** [mapstruct/mapstruct#1790]
On version 1.3.0.Final: 

When using `nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS` in a MapperConfig
and `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE` on the Mapper,
the generated code is not what the docs is specifying:

Mapper:
```
@Mapper(
        config = MappingConfig.class,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface BuggedMapper {


    CarDto toCarDto(CarModel carModel);


    void toExistingCar(@MappingTarget CarDto carDto, CarModel carModel);

}
```

MappingConfig:
```
@MapperConfig(
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS
)
public class MappingConfig {

}
```

Generated BuggedMapperImpl: (comment is mine)
```
@Override
    public void toExistingCar(CarDto carDto, CarModel carModel) {
        if ( carModel == null ) {
            return;
        }

        if ( carModel.getBrandName() != null ) {
            carDto.setBrandName( carModel.getBrandName() );
        }
// this else branch should not be here
        else {
            carDto.setBrandName( null );
        }
    }
```

Adding ` nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS` to the Mapper fixes it, as well as reverting to mapstruct 1.3.0.Beta2

I have attached a sample project that reproduces the issue
[mapstructBugs.zip](https://github.com/mapstruct/mapstruct/files/3062936/mapstructBugs.zip)

**Comment by filiphr** [comment]
Thanks for reporting this @mnembrini. The branch should not be there indeed. We are going to look into this.

**Comment by saw303** [comment]
@filiphr any ETA on this issue yet available? Do you play to do a small bugfix release or will this be stuck until the release of 1.4.0?

**Comment by saw303** [comment]
@filiphr I have added a Git repo that describes and reproduces the bug at https://github.com/saw303/mapstruct-nullValue-Bug

The issue is actually provoked on the [class level](https://github.com/saw303/mapstruct-nullValue-Bug/blob/master/src/main/java/ch/silviowangler/mapstruct/BuggedMapper.java#L13) annotation `Mapper#nullValuePropertyMappingStrategy`. When setting `nullValuePropertyMappingStrategy` to `NullValuePropertyMappingStrategy.IGNORE` Mapstruct generates wrong code.

When setting `nullValuePropertyMappingStrategy` to `NullValuePropertyMappingStrategy.IGNORE` on [method level](https://github.com/saw303/mapstruct-nullValue-Bug/blob/master/src/main/java/ch/silviowangler/mapstruct/BuggedMapper.java#L20) using `Mapping#nullValuePropertyMappingStrategy` everything works as expected.

```java
@Mapper(
        config = MappingConfig.class,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface BuggedMapper {

    CarDto toCarDto(CarModel carModel);

    // remove this annotation to trigger the bug described in https://github.com/mapstruct/mapstruct/issues/1790
    @Mapping(target = "name", source = "name", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void toExistingCar(@MappingTarget CarDto carDto, CarModel carModel);

    void toExistingCarWithBug(@MappingTarget CarDto carDto, CarModel carModel);
}
```

I hope this clarifies things.

Regarding fixing the bug. Do you at Mapstruct plan a bugfix release such as 1.3.1? This bug is very annoying and we would be happy if there would be something like a maintenance release to fix this. We are happy to help and provide a PR if wanted.

**Comment by filiphr** [comment]
Thanks for the reproducal @saw303. It is a silly typo 😄. Just created a PR for the fix.

>Do you at Mapstruct plan a bugfix release such as 1.3.1?

We haven't really decided about this yet.

>We are happy to help and provide a PR if wanted.

PRs and help is always appreciated. No need to ask to do it 😉

**Comment by saw303** [comment]
@filiphr Thank you for releasing the 1.3.1.Final bugfix release. I'm sorry to report that this fix does not affect the bug reported in this ticket and I would like to ask you to reopen this issue.

As mentioned in the [link](https://github.com/mapstruct/mapstruct/issues/1790#issuecomment-530711091) above setting the `nullValuePropertyMappingStrategy` to `NullValuePropertyMappingStrategy.IGNORE` has not the expected effect when mapping to an existing target bean.

```java
@Mapper(
        config = MappingConfig.class,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface BuggedMapper {
     void toExistingCarWithBug(@MappingTarget CarDto carDto, CarModel carModel);
}
```

Mapstruct 1.3.1 still sets the target property value to `null` when the corresponding source property is `null`. This seems to be wrong when choosing `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE`.  It still generates the `else` branch.

```java
   @Override
    public void toExistingCar(CarDto carDto, CarModel carModel) {
        if ( carModel == null ) {
            return;
        }

        if ( carModel.getBrandName() != null ) {
            carDto.setBrandName( carModel.getBrandName() );
        }
        // this else branch should not be here
        else {
            carDto.setBrandName( null );
        }
    }
```

I have updated my Git repository which simulates the problem https://github.com/saw303/mapstruct-nullValue-Bug/blob/master/src/test/groovy/ch/silviowangler/mapstruct/BuggedMapperSpec.groovy#L33

**Comment by saw303** [comment]
@filiphr  Yes I'm the thing is that a set a Spock `@PendingFeature` annotation to the test that simulates the bug. PendingFeature ignores test failures but breaks the test when all test assertions are back to green. Sorry, that was my fault :(

But I just realized that I can solve the problem when setting my global `MapperConfig` (org.mapstruct.MapperConfig#nullValuePropertyMappingStrategy) to `org.mapstruct.NullValuePropertyMappingStrategy#IGNORE`. I suspect this default value is responsible for the additional null setting else branch. And I think that makes sense then.

As for now there is no need to reopen this issue. My bad.

**Comment by filiphr** [comment]
@saw303 what I meant is that you didn't upgrade the `mapstruct-processor` dependency to 1.3.1.Final [here](https://github.com/saw303/mapstruct-nullValue-Bug/blob/master/build.gradle#L38). Which means you are still running 1.3.0.Final for that repository

**Comment by saw303** [comment]
OMG....🤦‍♂ I need holidays. @filiphr thanks anyway
