### ISSUE TITLE
Support for conversion between java.time.LocalDateTime and javax.xml.datatype.XMLGregorianCalendar

### ISSUE THREAD

**Issue by avmohan** [mapstruct/mapstruct#1791]
When mapping `LocalDate` to `XmlGregorianCalendar`, timezone is set to DatatypeConstants.FIELD_UNDEFINED. But when converting `LocalDateTime` to `XmlGregorianCalendar`, the timezone is currently set to system default.

**Comment by filiphr** [comment]
@avmohan can you please paste the generated code? Looking in our repository I don't see a mapping from `java.time.LocalDateTime` to `XmlGregorianCalendar`

**Comment by avmohan** [comment]
@filiphr 
The issue is reproed here - https://github.com/avmohan/mapstruct-issue-1791-sample
The generated code is below (for both LocalDate & LocalDateTime)
```java
public class SourceTargetMapperImpl implements SourceTargetMapper {

    private final DatatypeFactory datatypeFactory;

    public SourceTargetMapperImpl() {
        try {
            datatypeFactory = DatatypeFactory.newInstance();
        }
        catch ( DatatypeConfigurationException ex ) {
            throw new RuntimeException( ex );
        }
    }

    @Override
    public Target mapSource(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        if ( source.getLocalDateTime() != null ) {
            target.setLocalDateTime( dateToXmlGregorianCalendar( Date.from( source.getLocalDateTime().toInstant( ZoneOffset.UTC ) ) ) );
        }
        target.setLocalDate( localDateToXmlGregorianCalendar( source.getLocalDate() ) );

        return target;
    }

    private XMLGregorianCalendar dateToXmlGregorianCalendar( Date date ) {
        if ( date == null ) {
            return null;
        }

        GregorianCalendar c = new GregorianCalendar();
        c.setTime( date );
        return datatypeFactory.newXMLGregorianCalendar( c );
    }

    private XMLGregorianCalendar localDateToXmlGregorianCalendar( LocalDate localDate ) {
        if ( localDate == null ) {
            return null;
        }

        return datatypeFactory.newXMLGregorianCalendarDate(
            localDate.getYear(),
            localDate.getMonthValue(),
            localDate.getDayOfMonth(),
            DatatypeConstants.FIELD_UNDEFINED );
    }
}
```

**Comment by filiphr** [comment]
Thanks for the reproducal @avmohan, as I suspected there is no implicit conversion between `LocalDateTime` and `XMLGregorianCalendar` and the conversion from `LocalDateTime` to `Date` and then from `Date` to `XMLGregorianCalendar` is used.

Will you be interested in submitting a PR for adding this support?

**Comment by avmohan** [comment]
Sure. I can give it a try.

**Comment by filiphr** [comment]
Awesome let us know if you need some help.

Some pointers, for one-lines we typically use type conversion. Have a look [here](https://github.com/mapstruct/mapstruct/tree/master/processor/src/main/java/org/mapstruct/ap/internal/conversion). For multi line mapping methods there are [built-in methods](https://github.com/mapstruct/mapstruct/tree/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin). I think that for this you would need built-in method. Similar to [JodaLocalDateTimeToXmlGregorianCalendar](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/JodaLocalDateTimeToXmlGregorianCalendar.java) it's template is [here](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/JodaLocalDateTimeToXmlGregorianCalendar.ftl)
