### ISSUE TITLE
[Feature Request] Support return boolean type when  updating existing bean instances

### ISSUE THREAD

**Issue by dcy10000** [mapstruct/mapstruct#1794]
In some case. We need to know if the target bean changes or not.
So, maybe need to support return boolean type when updating existing bean instances.
Like this.
```
// return true  if some fields changes in the target entity
// return false if nothing changes in the target entity
boolean toTarget( MammalDto source, @MappingTarget MammalEntity target );
```
Thanks

**Comment by sjaakd** [comment]
I don't think this is something we would like to support. It conflicts with current functionality (it is possible to use a return type in combination with an `@MappingTarget`.. Out of curiosity: why don't you implement hashcode/equals on the target object?  You can process it in an `@AfterMapping` method if you want..

**Comment by dcy10000** [comment]
```
@Mapper
public abstract class CarMapper {


    private CarDto oldDto;

    @Mapping(source = "numberOfSeats", target = "seatCount")
   public  abstract CarDto  carToCarDto(Car car,@MappingTarget CarDto oldDto);


    public void setOldDto(CarDto oldDto) {
        this.oldDto = oldDto;
    }

    @AfterMapping
    protected void after(Car car, @MappingTarget CarDto newDto) {
        if (oldDto.equals(newDto)){
            //...
        }
    }


}
```

Do you mean this code above? no, it doesn't work. because `oldDto` changed too.
Unless I have to implement Copy Constructor, then create a new copy of `oldDto`. 
I think this is a bad way.

**Comment by sjaakd** [comment]
more like this:

```java
@Mapper
public abstract class CarMapper {

    private CarDto oldDto;

    @Mapping(source = "numberOfSeats", target = "seatCount")
   public  abstract CarDto  carToCarDto(Car car,@MappingTarget CarDto dto, @Context  CarDto origDto);



    @AfterMapping
    protected void after(Car car, @MappingTarget CarDto newDto, @Context CarDto orgiDto) {
        if (oldDto.equals(origDto)){
            //...
        }
    }


}
```

Note: currently (recently solved) there could be a mixup between old/new dto. Perhaps better to wrap the oldDto in a holder.

**Comment by sjaakd** [comment]
Note.. as an afterthought. You probably need to clone the origDTO into the newDTO.. You can also do that with MapStruct..

**Comment by dcy10000** [comment]
Thanks. You are right!
