### ISSUE TITLE
Links to reference Guide for Version 1.2 are wrong

### ISSUE THREAD

**Issue by bjoernb94** [mapstruct/mapstruct#1796]
Hey guys,
I found out that the links on your website to the reference guide for the version 1.2 are wrong. They are linking to stable and not 1.2. It's for all links, except the migration notes. 

Thanks for the great tool and keep up the good work! :-)

**Comment by chris922** [comment]
Thank you very much, Björn!

There is already a ticket (and fix) in the mapstruct.org repository (mapstruct/mapstruct.org#89), but the page itself was not yet updated. Probably @filiphr can do this.

**Comment by chris922** [comment]
@bjoernb94 fyi, I just updated the webpage 😃 Links should be fine now.

**Comment by bjoernb94** [comment]
@chris922 Great. Thank you! 👍
