### ISSUE TITLE
Using an expression moves the generated code outside of the null check

### ISSUE THREAD

**Issue by perogi** [mapstruct/mapstruct#1798]
Searched for this issue but I was unable to find it.

Mapping one object to another using NullValueMappingStrategy.RETURN_DEFAULT with a field that uses an expression will result in a NullPointerException because the field that uses the expression will be generated outside of the check for null block.
```Java
@Override
public ReturnObject inputObjectToReturnObject(InputObject inputObject) {
    ReturnObject returnObject = new ReturnObject();
    if (inputObject != null) {
      if (inputObject.getFieldOne() != null) {
        returnObject.setFieldOne(inputObject.getFieldOne());
      }
      ... map more fields  ...
    }
    returnObject.setFieldTen(MyJavaExpression.formatIt(inputObject.getField10));

  return returnObject;
}
```
If inputObject is null, it will bypass the non-expression fields but will still continue to process fields outside of the `inputObject != null` block.

~One work-around would be to add a null check in the expression but that seems like overkill.~ edit: just tried this and no go.

Thoughts?
Thank you!

**Comment by filiphr** [comment]
This works as designed. I know that in your case it doesn't work as expected. However, in `expression` you can use any java code. This means that someone might be doing something that doesn't touch the source parameters and would expect exactly what you are saying to happen (for example `new Date()`).

I would suggest that you either use `@AfterMapping`, `@BeforeMapping` or use a qualification. In your example that would fit perfectly.

For example:

```java
@Mapper
public interface TestMapper {

    @Mapping(target = "fieldTen", source = "field10", qualifiedByName = "formatIt")
    ReturnObject inputObjectToReturnObject(InputObject inputObject);

    @Named("formatIt")
    default String formatIt(String value) {
        return MyJavaExpression.formatIt(value);
    }
}
```

You can read more about [Mapping method selection based on qualifiers](http://mapstruct.org/documentation/stable/reference/html/#selection-based-on-qualifiers) in the documentation.

Just FYI you can also put the `@Named` or any custom `@Qualifier` on the `MyJavaExpressioN#formatIt` method as well.

**Comment by perogi** [comment]
Thank you very much for the solution and reply!!
