### ISSUE TITLE
Fluent setters on fields with names starting with set are not working

### ISSUE THREAD

**Issue by OhDearMoshe** [mapstruct/mapstruct#1799]
It seems in version MapStruct 1.3.0-Final theres an issue with builders and fields that begin with the word set such as settlement or setup.

Example (with lombok)

Source: 
```
@Builder
public class Foo {
    private String setup;
    private LocalDate settlement;

}
```

Target: 
```
@Builder
public class Bar {
    private String setup;
    private LocalDate settlement;

}
```

Neither of these fields are mapped. But I did get it to work by adding

```
@Mapping(source = "settlement", target = "tlement")
@Mapping(source = "setup", target = "up")
```

**Comment by filiphr** [comment]
Thanks for raising this issue @OhDearMoshe. This is certainly a bug and we would try to fix it asap.

In case you have some time and are wiling to play a bit with the MapStruct codebase you could help out with a contribution 😉. We would of course guide you

**Comment by msymonov** [comment]
Hi guys. Could you please review https://github.com/mapstruct/mapstruct/pull/1810.
Hopefully it fixes everything, however side effects are expected as for existing methods which are expected to be used as getters/setters, but not following Oracle's specification the code will be broken. For instance i noticed such cases in MapStruct tests: "getaName", "setaName" for a field named "aName".
Thanks in advance for review and comments.

**Comment by msymonov** [comment]
@filiphr Could you please comment on this item? No pushing, just want to close my internal gestalt :). Thanks

**Comment by msymonov** [comment]
any news, gentlemen?

**Comment by msymonov** [comment]
guys, could someone comment on this item please.

**Comment by filiphr** [comment]
I reviewed the PR @msymonov, sorry for taking such a long time.

**Comment by choudharylakshyaveer** [comment]
Use the below config, it worked fine in my case:
                 <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>1.4.2.Final</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.24</version>
						</path>
						<dependency>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</dependency>
						<path>
	                        <groupId>org.mapstruct</groupId>
	                        <artifactId>mapstruct-processor</artifactId>
	                        <version>1.5.2.Final</version>
                    	</path>
					</annotationProcessorPaths>
					<compilerArgs>
						<compilerArg>
                       -Amapstruct.defaultComponentModel=spring
                </compilerArg>
					</compilerArgs>
				</configuration>
			</plugin>
			
-----
<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>1.5.2.Final</version>
		</dependency>

**Comment by choudharylakshyaveer** [comment]
Below config worked fine for me
`<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>1.5.2.Final</version>
		</dependency>`

`<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>1.4.2.Final</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.24</version>
						</path>
						<dependency>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</dependency>
						<path>
	                        <groupId>org.mapstruct</groupId>
	                        <artifactId>mapstruct-processor</artifactId>
	                        <version>1.5.2.Final</version>
                    	</path>
					</annotationProcessorPaths>
					<compilerArgs>
						<compilerArg>
                       -Amapstruct.defaultComponentModel=spring
                </compilerArg>
					</compilerArgs>
				</configuration>
			</plugin>`
