### ISSUE TITLE
Map<> mapping generates method with invalid parameter name

### ISSUE THREAD

**Issue by IDoCodingStuffs** [mapstruct/mapstruct#1802]
Also refer to:
https://stackoverflow.com/questions/55959943/mapstruct-expression-mappings-using-multiple-source-parameters

This is version 1.3.0.Final

```
@Mapping(target = "myWrapperObject.myListObject",
        expression = "java(myListMap.get(keyParent.getKey()))")
    @Mapping(target = "myOtherObject", expression = "java(myOtherClassList.add(myOtherObject))")
    MyFinalClass mapStuff(Map<String, List<MyClass>> myListMap, MyOtherClass keyParent);
```

Using this code generates code that looks like this under impl:
```
 protected void stringListMapToMyWrapperClass(Map<String, List<MyClass>> map, MyWrapperClass mappingTarget) {
        if ( map == null ) {
            return;
        }

        mappingTarget.setMyListObject = myListMap.get(keyParent.getPropertyKey()) );
    }
```

There are actually two issues in the code above but this one is the most glaring one. See how method parameter is passed as **map** but then the name I specified "**myListMap**" is called. Either one or the other should be the case.

**Comment by filiphr** [comment]
As I mentioned in https://github.com/mapstruct/mapstruct/issues/1803#issuecomment-489223286 please refrain from asking on multiple channels.

As I said in the other issue this works as designed. All names in the non public generated methods of the mapper implementation are implementation detail for MapStruct. There is no guarentee that we are going to preserve the same name as in the original method.

I would advise you to use `@AfterMapping` or a custom method to achieve more complex mappings like in your case.

**Comment by tb-kubra** [comment]
A bug or a too loose contract for expressions. Maybe expressions should resolve a placeholder for whatever mapstruct decides to name it.

**Comment by filiphr** [comment]
@tb-kubra have a look at #2559, a solution for that might achieve what you want with the placeholder. However, I'll say again, relying on the fact that something is passed down in generated methods is not the way to use expressions.
