### ISSUE TITLE
NullValuePropertyMappingStrategy.SET_TO_DEFAULT generates invalid constructors for java.time

### ISSUE THREAD

**Issue by joe380** [mapstruct/mapstruct#1815]
- [X] Is this an issue (and hence not a question)? 
Version: 1.3.0.Final
Enviroment: Spring boot 2.1.4.RELEASE + lombok + jpamodelgen

Bug:
- using nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT
- problem types: Instant, BigDecimal, (maybe also other types from java.time and java.math)
- it creates ...else { instance.setField(new Instant()) } which is not correct => Instant.now() is the proper initiation
- and this applies also for BigDecimal probably "new BigDecimal()" could by new BigDecimal("0") as oppose to default value for cases like int, double ...

**Comment by sjaakd** [comment]
@joe380 . MapStruct can't possibly know all the ways to instantiate objects. For some types ( primitive + primitive-wrappers, lists, maps) we do this. For others we just use the empty constructor. Checkout our [documentation](http://mapstruct.org/documentation/stable/reference/html/#mapping-result-for-null-properties) on that.  As the documentation states, please use `@Mapper#defaultValue` or `@Mapper#defaultExpression`..

**Comment by chris922** [comment]
Hmmm... @sjaakd do you think it would be too complicated to try to support at least everything from the JDK? `Instant` and `BigDecimal` is at least in the JDK and could be supported.. this might not be a high prio topic, but maybe someone from the community would like to contribute ?

Of course we can't support everything and for this - as you said - we've got `defaultValue`/`defaultExpression`...

**Comment by sjaakd** [comment]
> Hmmm... @sjaakd do you think it would be too complicated to try to support at least everything from the JDK? `Instant` and `BigDecimal` is at least in the JDK and could be supported.. this might not be a high prio topic, but maybe someone from the community would like to contribute ?

That's perhaps possible.. But its for sure not a bug but a feature request.. Anyway, perhaps @joe380 can contribute a PR 😄 .

**Comment by sjaakd** [comment]
> * and this applies also for BigDecimal probably "new BigDecimal()" could by new BigDecimal("0")

I would say: `BigDecimal.ZERO`

**Comment by chris922** [comment]
> > Hmmm... @sjaakd do you think it would be too complicated to try to support at least everything from the JDK? `Instant` and `BigDecimal` is at least in the JDK and could be supported.. this might not be a high prio topic, but maybe someone from the community would like to contribute ?
> 
> That's perhaps possible.. But its for sure not a bug but a feature request.. Anyway, perhaps @joe380 can contribute a PR 😄 .

Yes, definitely not a bug.. but as a feature request it is imho fine.
