### ISSUE TITLE
Mapstruct fails to create a mapper when using lombok @FieldNameConstant instead of string literals

### ISSUE THREAD

**Issue by rtisma** [mapstruct/mapstruct#1816]
## Issue
When using the constants defined by the [@FieldNameConstant](https://projectlombok.org/features/experimental/FieldNameConstants) annotation in mapstruct mapping definitions, an error results. 

## Replication
The following `PASSING_MAP_METHOD` example compiles successfully and passes the test when using string literals. If the `PASSING_MAP_METHOD` block is commented out, and the `FAILING_MAP_METHOD` is uncommented, the above issue will result.

```java
  @Test
  public void testMapStructFail(){
    val myMapper = Mappers.getMapper(MyMapper.class);
    val p = new Person();
    p.setAge(4423);
    p.setFirstName("john");
    p.setLastName("does");
    val p2 = myMapper.map(p);
    assertThat(p2.getA()).isEqualTo(p.getAge());
    assertThat(p2.getFName()).isEqualTo(p.getFirstName());
    assertThat(p2.getLName()).isEqualTo(p.getLastName());
  }


  @Mapper(componentModel = "default")
  public interface MyMapper {

//    FAILING_MAP_METHOD
//    @Mapping(source = "p.firstName", target = Person2.Fields.fName)
//    @Mapping(source = "p.lastName", target = Person2.Fields.lName)
//    @Mapping(source = "p.age", target = Person2.Fields.a)
//    Person2 map(Person p);

    // PASSING_MAP_METHOD
    @Mapping(source = "p.firstName", target = "FName")
    @Mapping(source = "p.lastName", target = "LName")
    @Mapping(source = "p.age", target = "a")
    Person2 map(Person p);

  }
  
  @Data
  @FieldNameConstants
  public static class Person {
    private String firstName;
    private String lastName;
    private Integer age;
  }

  @Data
  @FieldNameConstants
  public static class Person2 {
    private String fName;
    private String lName;
    private Integer a;
  }

```
My pom.xml has the following dependency
```xml
<dependency>
	<groupId>org.mapstruct</groupId>
	<artifactId>mapstruct</artifactId>
	<version>1.3.0.Final</version>
</dependency>
```

and the following maven-compiler-plugin config
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
        <source>11</source> 
        <target>11</target> 
        <annotationProcessorPaths>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>1.3.0.Final</version>
            </path>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.8</version>
            </path>
        </annotationProcessorPaths>
        <compilerArgs>
            <compilerArg>
                -Amapstruct.suppressGeneratorTimestamp=false
            </compilerArg>
            <compilerArg>
                -Amapstruct.suppressGeneratorVersionInfoComment=false
            </compilerArg>
            <compilerArg>
                -Amapstruct.unmappedTargetPolicy=ERROR
            </compilerArg>
            <compilerArg>
                -Amapstruct.defaultComponentModel=spring
            </compilerArg>
        </compilerArgs>
    </configuration>
</plugin>

```

**Comment by sjaakd** [comment]
Lombok violates JSR269 by adapting existing classes (making use of internal JDK / EclipseCompiler API's).  To deal with that, when MapStruct and Lombok run in the same annotation cycle we implemented an SPI that Lombok calls when it has generated a (getter / setter) method.

I guess with this new experimental feature, Lombok needs to delay its call to the SPI until also the corresponding fieldnameconstants are generated.

Please report this issue on the Lombok repo. I don't think there's anything that we can do for you here.

Note: you could try to fix this by putting the lombok classes in a different maven project (lib) and use that as a dependency in the maven project that runs MapStruct.

**Comment by FlorianCousin** [comment]
@rtisma Have you reported this issue on the Lombok repo ?
If so, could you please provide a link here to the Lombok repo issue ?

**Comment by filiphr** [comment]
@FlorianCousin have a look at #2609 and https://github.com/projectlombok/lombok/issues/2991. Especially check the discussion in the Lombok project to understand why this is not working as you would expect. There is nothing that MapStruct nor Lombok can do about this particular problem.

**Comment by FlorianCousin** [comment]
Thank you very much for your time @filiphr

**Comment by genglongsir** [comment]
试试这个
https://github.com/mapstruct/mapstruct/issues/2951#issuecomment-2613805761
