### ISSUE TITLE
Feature Request : support multiple arguments in source of @Mapping

### ISSUE THREAD

**Issue by deslauriersp** [mapstruct/mapstruct#1817]
Mapstruct nicely calls other mapper implicitly when source arguments type needs to be converted to the target type.

My problem is that I want to call implicitly a mapper that takes multiple source arguments.

Someting that looks like this :

```
@Mapper(uses= {MyTargetObjectMapper.class})
public interface MyComplexTargetObjectMapper {
  @Mapping(target="myTargetObject", source="one.src1, two.src2") // FEATURE REQUEST
  public MyComplexTargetObject convert(MySourceOne one, MySourceTwo two);
}
```

Given the other Mapper 

```
@Mapper
public interface MyTargetObjectMapper {
  @Mapping(target="prop1", source="a")
  @Mapping(target="prop2", source="b")
  public MyTargetObject mapMyObject(String a, String b);
}
```

Maybe there is another way... I am fairly new to MapStruct

 **I am trying to avoid an explicit call to a mapper**, and benefit from the Mapper(uses={ [my mappers] }).

see also:

https://stackoverflow.com/questions/56149402/mapstruct-invoking-implicitly-other-mapper-with-multiple-parameter

**Comment by sjaakd** [comment]
The problem of selection methods of multiple sources has been raised before so this is possibly be duplicate. I don't think it can be solved. We have a stack of selectors that resolves the proper method. They are based on the premise of findings the best match between one source and target. Especially selection inheritance becomes cumbersome. I'm going to close this one and I'll come back asap in your SO question on possible alternatives
