### ISSUE TITLE
Use non-bean-objects or primitives map to a bean

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#182]
I've come acros a number of occasions were I've got some simple types that should create a bean in the mapping process. For example, there's a type called MeasureType (JAXB generated) which carries a unit-of-measurement (uom) and a value (measure). It maps from an 'BigDecimal'. There's a whole set of specializations from this `MeasureType`. E.g. Temperature (uom="degrees C"), Length(uom="m"), Speed(uom="m/s"), etc. ObjectFactories are used to create the measure type specializations in the proper spot.

Now, I would like to have something like this:

```
@Mapping( source="m", isSourceConstant=true,  target="uom" )
PreDrilledDepth toPreDrilledDepth(BigDecimal value)
```

or

```
@Mapping( source="m2", isSourceConstant=true,  target="uom" )
ConeSurfaceArea toConeSurfaceArea(Integer value)
```

with `PreDrilledDepth extends MeasureType` and `ConeSurfaceArea extends MeasureType`

Now I've to write my own custom mappers to do this, while MapStruct knows how to resolve the factory.

Note1: the 'default' names are derived from the argument names (and would not require mappings)

These are actually 2 features: introduction of constants (which could be relevant in bean mappings as well) and 'wrapping' a simple object into a bean.

Any thoughts on this?

**Comment by vitaliy-kuzmich** [comment]
I was need to map "nested bean collection"  -> "primitive collection", here it is approach with jdk8 instead of abstract classes : 
```
class A {
	public Integer value;

}

@Mapper
interface ADomainAdapter {

	default Collection<Integer> map(Collection<A> value) {
		return value
				.stream()
				.map(v -> v.value)
				.collect(Collectors.toList());

	}

}
```
