### ISSUE TITLE
NullValueCheck in Expressions

### ISSUE THREAD

**Issue by RuslanSafa** [mapstruct/mapstruct#1824]
When performing Expressions, I would like to check the source for null.
@Mapping(target = "timeAndFormat", expression = "java( new org.sample.TimeAndFormat( s.getDate().getTime(), s.getDate().getFormat() )
Target sourceToTarget(Source s);

Is verification possible that s.getDate () did not return a Null?

**Comment by sjaakd** [comment]
`expressions` and `defaults` are never null checked because we don't know if the user acts on a `null value`.  You could add a default method (if the mapper is an interface) or regular method if the mapper is an abstract class.

But if your case actually reflects reality, its perhaps better not to use an expression at all.. Just implement a method:

```java
public interface MyMapper{
  
  @Mapping( target = "timeAndFormat", source = "date" )
  Target sourceToTarget(Source s);

   // and implement a method which MapStruct can select:
   default TimeAndFormat mapTimeAndFormat(Date in) {
         if ( in != null ) {
                return new TimeAndFormat( in.getTime(), in.getFormat() );
         }
        return null; // or whatever default you like
   }
}
```

**Comment by RuslanSafa** [comment]
Thank. We use the following solution:
``
public interface MyMapper{
  
  @Mapping( target = "timeAndFormat", source = "date", qualifiedByName="mapTimeAndFormat" )
  Target sourceToTarget(Source s);

   @Named("mapTimeAndFormat")
   default TimeAndFormat mapTimeAndFormat(Date in) {
                return new TimeAndFormat( in.getTime(), in.getFormat() );
   }
}
``

**Comment by sjaakd** [comment]
No problem. If this is the only method with the signature: `TimeAndFormat mapTimeAndFormat(Date in)` you don't even need a qualifier. Without the `qualifiedByName` and `@Named` annotation should also work. These are there if you have multiple possibilities.

**Comment by sjaakd** [comment]
I'm going to proceed to close this issue.. If you feel that there's something to add, let me know.

**Comment by RuslanSafa** [comment]
Thanks for the quick response. Can close. I expressed the idea.
