### ISSUE TITLE
Null pointer exception in nested property mapping method with presence check

### ISSUE THREAD

**Issue by jakraska** [mapstruct/mapstruct#1826]
Given the following object structures:
```
SourceParent                        Target
    |_ SourceChild                       |_Content
         |_ Content 
```
If you try to map `SourceParent->SourceChild->Content` to `Target->Content` and also are using presence tracking you will get a null pointer if `SourceChild` is present but null.  

The NestedPropertyMappingMethod.ftl is missing a null check before checking presence.  I have fixed this and will open a PR shortly.

**Comment by jakraska** [comment]
opened #1827

**Comment by sjaakd** [comment]
Hey @jakraska .. Thanks a lot for your contribution. At first chance it looks very complete. I'll have a more detailed look tomorrow.

**Comment by sjaakd** [comment]
@jakraska . I just looked at your PR..


I spotted that you explicitly call `sourceParent.setSourceChild( null )`. Now there are 2 ways to look at presence check:

1. As alternative to null check (should it adhere to `NullValueCheckStrategy` in that case)
2. As complementary to null check, e.g. dealing with fresh (non initialised) beans. Initialising with null could then be considered as initialised as well.

I don't know enough about the "general use case out there" to make a clear verdict. So I looked at our documentation and unfortunately I can't make a real strong case for an explicit choice for 1. or 2. either.

I finally looked at our generated code (non nested). There are cases that incline to 2.. Check out for instance: `org.mapstruct.ap.test.source.presencecheck.spi.SoccerTeamMapperNestedObjects`. There a null check  is generated like this:
```java
      if ( in.hasGoalKeeper() && in.getGoalKeeper() != null && in.getGoalKeeper().hasName() ) {
            soccerTeamTargetWithPresenceCheck.setGoalKeeperName( inGoalKeeperName( in ) );
        }
```
which would plea for your case 2.

@filiphr : what do you think about this? I'm in favour of 2.

**Comment by jakraska** [comment]
hey @sjaakd, thanks for taking the time to look at this.  To give you a little more background on my usecase: 

We have a Json based API that calls a separate, legacy, downstream api that has a very similar structure.  Our legacy API doesn't treat nulls consistently - sometimes they are ignored and sometimes they unset things.   Since our API supports partial updates (ie just updating the name field of our object) we need to be able to track which fields a user provided as we translate to our legacy pojo.  

```
User Json Input  --> Our java API  --> Our legacy API
```


Our object is very complicated (around 200+ nested fields) but Mapstruct has worked great for this. With the exception of this null pointer on subfields.   While i agree that mapstruct uses the `hasX` methods instead of null checks for determining when to map, i think the underlying code still needs (and already does) null checks.  

If we look at the code that is already being generated:
```
 @Override
    public Target sourceAToTarget(SourceParent sourceParent) {
        if ( sourceParent == null ) {
            return null;
        }

        Target target = new Target();

        String content = sourceParentSourceChildContent( sourceParent );
        if ( sourceParent.hasSourceChild() && sourceParent.getSourceChild() != null && sourceParent.getSourceChild().hasContent() ) {
            target.setContent( content );
        }

        return target;
    }
```
the logic  that determines when to set already factors in both null checks and `has` fields.  The null pointer error occurs when determining the value to set `sourceParentSourceChildContent( sourceParent );`

**Comment by sjaakd** [comment]
> With the exception of this null pointer on subfields

There's a reason this null check is added. If you look in the explanation, [null check](http://mapstruct.org/documentation/stable/reference/html/#checking-source-property-for-null-arguments) is always added in case we call a generated method. 

However. This being a generated (forged) method.. I think we have a choice.. Perhaps you're right.. 

@filiphr .. What's your opinion on this?

**Comment by filiphr** [comment]
I think that the PR makes sense, especially if used in update mappings when there is different logic for what `hasValue`. `hasValue` doesn't need to mean that `value` is not `null`. 

In JSON you can easily show this with explicitly adding a value of `null` (which means it has value and the value is null).
