### ISSUE TITLE
MapStruct 1.3.0.Final generates invalid implementation when nested property of target is populated with multiple nested properties of source

### ISSUE THREAD

**Issue by mabilalmirza** [mapstruct/mapstruct#1828]
MapStruct v1.3.0.Final generates invalid mapper implementation when nested object property of target is populated from multiple nested object propertiese of source. MapStruct v1.1.0.Final works fine in this scenario.

```
@Mapper
public interface FirstMapper {

    @Mapping(target = "name", source = "name")
    @Mapping(target = "completeAddress.lineOne", source = "specialAddress.line1")
    @Mapping(target = "completeAddress.lineTwo", source = "specialAddress.line2")
    @Mapping(target = "completeAddress.city", source = "generalAddress.city")
    @Mapping(target = "completeAddress.country", source = "generalAddress.country")
    public Person mapPerson(Employee employee);
}
```
Where structure of target (Person) and person(Employee) is as below
```
class Person { String name; CompleteAddress completeAddress; }

class Employee { String name; GeneralAddress generalAddress,  SpecialAddress specialAddress; }
```

Generated Mapper is as below
```
public class FirstMapperImpl implements FirstMapper {

    @Override
    public Person mapPerson(Employee employee) {
        if ( employee == null ) {
            return null;
        }

        Person person = new Person();

        person.setCompleteAddress( generalAddressToCompleteAddress( employee.getGeneralAddress() ) );
        person.setCompleteAddress( specialAddressToCompleteAddress( employee.getSpecialAddress() ) );
        person.setName( employee.getName() );

        return person;
    }

    protected CompleteAddress generalAddressToCompleteAddress(GeneralAddress generalAddress) {
        if ( generalAddress == null ) {
            return null;
        }

        CompleteAddress completeAddress = new CompleteAddress();

        completeAddress.setCountry( generalAddress.getCountry() );
        completeAddress.setCity( generalAddress.getCity() );

        return completeAddress;
    }

    protected CompleteAddress specialAddressToCompleteAddress(SpecialAddress specialAddress) {
        if ( specialAddress == null ) {
            return null;
        }

        CompleteAddress completeAddress = new CompleteAddress();

        completeAddress.setLineOne( specialAddress.getLine1() );
        completeAddress.setLineTwo( specialAddress.getLine2() );

        return completeAddress;
    }
}
```

Here generated methods `generalAddressToCompleteAddress` and `specialAddressToCompleteAddress` are both returning new instance of `CompleteAddress`. Overridden method `mapPerson` is calling `person.setCompleteAddress` with output of these two generated methods so one instance is thrown away in the process.So, with v1.3.0.Final, mapper is not correctly implemented as per defined mapping.

Please see [this repo](https://github.com/mabilalmirza/mapstruct-multiple-nested-objects) created to demostrate this issue.
- Branch [mapstruct-1.1.0.Final](https://github.com/mabilalmirza/mapstruct-multiple-nested-objects/tree/mapstruct-1.1.0.Final) is passing all unit tests.
- Branch [mapstruct-1.3.0.Final](https://github.com/mabilalmirza/mapstruct-multiple-nested-objects/tree/mapstruct-1.3.0.Final) fails to pass the tests.

**Comment by serghei-ilin** [comment]
I faced the same issue.

**Comment by filiphr** [comment]
Thias has somehow slipped. Thanks for reporting it and the good reproducal @mabilalmirza. We will have a look at it and try to fix it

**Comment by filiphr** [comment]
Thanks for the reproducer @mabilalmirza, it really helped us locate the problem. We have found the problem and we have a PR with a fix.
