### ISSUE TITLE
It should be possible to list the Decorator itself as used Mapper

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#183]
When changing a mapping inside a nested structure using a decorator, we have to override all methods, selecting each branch in the direction of the change, until we reach the method that we actually want to change.

If it were to be possible to include the Decorator itself as 'used' mapper, this would not be needed. All methods would first be resolved on the Decorator, before falling back to the Mapper.

**Comment by geertvanheusden** [comment]
Hi @gunnarmorling, just came across this issue as well with. I have a mapper with `List<Foo> foosToFooDtos(List<Foo> foo)` and `FooDto fooToFooDto(Foo foo)`. 
If I add a decorator and do some additional mapping on `fooToFooDto` it will never get called.
The generated code for the `foosToFooDtos` method in **FooMapperImpl_.java** will call the `fooToFooDto` directly. Not the new one in the decorator.

Currently this issue is labeled as an **enhancement** shouldn't it be labeled as a bug?

**Comment by gunnarmorling** [comment]
Hey @geertvanheusden, yes I guess we can label it as bug, too :)

Question is, how should the generated code look like in this case. So far we didn't find a really good solution. If you have some ideas around this, I'd be eager to learn about them.

**Comment by sjaakd** [comment]
@gunnarmorling .. we could generate for each method we implement on the decorated, a method in the decorated class in which we pass the decorator. Iso calling the class itself, we call the decorator. The methods could be package-scoped.

**Comment by gunnarmorling** [comment]
Hey @sjaakd, could you paste an example of how you imagine the generated code to look like?

**Comment by gunnarmorling** [comment]
One idea I have been contemplating lately is that we'd have to make sure that there only is a single class being generated. This would make sure that all references between decorated methods would be resolved properly. That'd require though that the *actual* methods (i.e. the undecorated ones) are renamed to avoid the conflict with the decorating method. Also we'd have to adapt references from the decorating method to the decorated one to this new name, i.e. we'd have to examine the source code of decorator methods, override them and adapt the reference to the decorated method. All in all rather tricky, but it might ensure proper working eventually.

**Comment by sjaakd** [comment]
What I meant is giving the user the choice. Its perhaps a bit more verbose, but we could allow something like this:

```java
@Mapper
@DecoratedWith(PersonMapperDecorator.class)
public interface PersonMapper {

    PersonMapper INSTANCE = Mappers.getMapper( PersonMapper.class );

    @Mapping( target = "name", ignore = true )
    PersonDto personToPersonDto(Person person);

    AddressDto addressToAddressDto(Address address);
    
    //@InheritConfiguration
    PersonDto personToPersonDto(Person person, PersonMapper decorator);
    
}
```
The mapping configuration would automatically be inherited. The generated code would perform callbacks on the decorator iso the mapper itself itself.

```java
    PersonDto personToPersonDto(Person person, PersonMapper decorator) {
        if ( person == null ) {
            return null;
        }

        PersonDto personDto = new PersonDto();

        personDto.setDateOfBirth( person.getDateOfBirth() );
        personDto.setAddress( decorator.addressToAddressDto( person.getAddress() ) );

        return personDto;
    }
```

The user would have the choice now of calling the 'normal' method in the decorator or the method with callback. 

I'm not sure how the other component models would handle callbacks on the decorator. Do we have testcases for that? Would the standard component model start to deviate too much?

**Comment by hukacode** [comment]
Hi guys,

Is it implementing?

**Comment by filiphr** [comment]
@hukacode I think that no one is working on this. You are free to try and work on it if you want to ;)

**Comment by ghostd** [comment]
I work around the bug/missing enhancement by creating a dedicating Mapper for the nested type.

**Comment by sjaakd** [comment]
I think there's no easy solution for this in the standard component model.. So lets close this until there's a clear view on how to do this.
