### ISSUE TITLE
Support "with" as an alias to "set"

### ISSUE THREAD

**Issue by ben-manes** [mapstruct/mapstruct#1834]
[JsonSchema2Pojo](http://www.jsonschema2pojo.org/) generates builder methods inlined on the mutable object. These are chained setters, e.g.
```java
return new Foo()
    .withBar(...)
    .withBaz(...);
```

The set'ers return `void` whereas the with'ers return the object instance. When mapping into those generated classes, MapStruct reports them as unmapped target properties.

Rather than setting to ignoring unmapped, it would be nice if either (a) this aliasing was supported or (b) if an inlined `BuilderProvider` could be written. I'm not sure about (b) or if there is an alternative (c) that I didn't consider.

Ideally js2p might be supported like AutoValue is. There is `additionalProperties` in jsonSchema for unmapped values, which could be automatically ignored.

**Comment by sjaakd** [comment]
To be honest: I don't see any added value in generating fluent setters. It does not offer  (as far as I know) any faster code and due to the complexity of eg null checking and other features it is just not worthwhile the effort. Remember: it is after all generated code. Wrt to a): you can provide your own priority of setters in an SPI. Checkout out accessor naming SPI in our documentation.

**Comment by ben-manes** [comment]
I would agree if I wrote that generator or all the usage code was similarly generated. It is nice in application code when building a nested json object to then serialize, as it offers indentation of nests. In my case, I am mapping EDI schema generated classes to/from jsonSchema generated for integration with legacy systems.

My issue isn’t priority, as the bean setters are used wonderfully. MapStruct thinks the with’er methods are additional attributes (uses setFoo, warns that withFoo is unmapped). I have to configure to ignore all unmapped, whereas I’d rather not ignore so broadly if a future property was added.

**Comment by sjaakd** [comment]
Ok. Out of curiosity, can you share an example of what it is you try to achieve? I associate "setXYZ" with mutable attributes and "withXYZ" with immutable attributes. The latter ones are usually constructed with a builder. MapStruct will prefer builder over setter (don't think you can mix within one method). On our current master you can switch off builders per method

**Comment by ben-manes** [comment]
I'm sorry for the confusion. Attached is an example for mapping an EDI 990 stop. This is a 1-to-1 mapping, to allow the application to manipulate through a json-based pipeline, where the EDI serialized form is relegated a source/sink step. EDI is an old line delimited format that is annoying to work with. MapStruct works great quickly map objects and then use more modern toolchains.

I am ignoring unmapped properties, but ideally I wouldn't (except for jsonSchema's default `additionalProperties`). This maps correctly but warns on the `with` methods,

>Edi990Mapper.java:55: warning: Unmapped target properties: "withStopOffDetails, withReferenceIdentifications, withDateTimes, withRemarks, additionalProperties".

I agree that `with` is usually on builder classes that produce an instance, but that is not how the JsonSchema2Pojo code generator evolved. A simple solution in my case might be if I could ignore properties based regex patterns.

Since all of this works it's not a blocking issue for me, just an observation when learning MapStruct to assist in this scenario.

**Comment by filiphr** [comment]
@ben-manes I think we had the same problem as with `Immutables`. They have `from` in there. I think that this can easily be resolve by using a custom `AccessorNamingStrategy` that would ignore the methods starting with `with`. Have a look at the [`ImmutablesAccessorNamingStrategy`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/spi/ImmutablesAccessorNamingStrategy.java) for a possible way of resolving this.

I am not sure that we need to do something special in MapStruct about this. I am even contemplating to close this issue. I don't think that we can go and say that everything starting with `with` is an alias to `set`.

**Comment by ben-manes** [comment]
Thanks, that’s a good reference to look into the next time I do a mapping.
