### ISSUE TITLE
MapStruct using different approaches to get Bean property name for beans in libraries

### ISSUE THREAD

**Issue by daniel-shuy** [mapstruct/mapstruct#1836]
When mapping a source Bean to a target Bean with the same property name, if the target Bean is in a library, MapStruct fails to automatically map them.

Eg.
```java
public class Source {
    private String sField;

    public String getSField() {
        return sField;
    }

    public void setSField(String sField) {
        return this.sField = sField;
    }
}
```

```java
public class Target {
    private String sField;

    public String getSField() {
        return sField;
    }

    public void setSField(String sField) {
        return this.sField = sField;
    }
}
```
Assuming `Target` is from a library dependency, when attempting to map this in MapStruct, eg.
```java
@Mapper(
    unmappedSourcePolicy = ReportingPolicy.ERROR,
    unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface MyMapper {
    Target toTarget(Source source);
}
```
it fails with:
`Unmapped target properties: "sField".`
`Unmapped source properties: "SField".`

So it seems like MapStruct is following the Java Beans spec when getting the property name for the source, but using the actual field name as the property name for the target, if it is in a library (if `Target` is copied locally to the project, MapStruct behaves as normal).

**Comment by daniel-shuy** [comment]
After some extensive testing, it seems like it only occurs in Intellij IDEA

**Comment by filiphr** [comment]
@daniel-shuy thanks for letting us know. MapStruct is never looking into the field. The check for the element name is happening in [`DefaultAccessorNamingStrategy#getElementName`](https://github.com/mapstruct/mapstruct/blob/119826982ab7a8d7d5a995ca80319992acca150f/processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java#L188). Would you be able to debug this in IntelliJ to see why it is not working as expected?
