### ISSUE TITLE
AfterMapping Doesn't Appear To Get Called When A Qualifier Annotation Is Applied To It

### ISSUE THREAD

**Issue by nestharus** [mapstruct/mapstruct#1837]
We use ToEntity both for readability and as a qualifier.

```
@Mapper
public abstract class ConnectMapper2 {
	public static class From {
		public String a;
	}

	public static class To {
		public String a;
	}

	public abstract To convert(final From source);

	@ToEntity
	@AfterMapping
	protected void after(final From source, @MappingTarget final To target) {

	}

	@IterableMapping(qualifiedByName = "fromto")
	public abstract List<To> from(final Collection<From> source);
}
```

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-06-04T08:15:58-0700",
    comments = "version: 1.3.0.Final, compiler: javac, environment: Java 1.8.0_201 (Oracle Corporation)"
)
public class ConnectMapper2Impl extends ConnectMapper2 {

    @Override
    public To convert(From source) {
        if ( source == null ) {
            return null;
        }

        To to = new To();

        to.a = source.a;

        return to;
    }

    @Override
    public List<To> from(Collection<From> source) {
        if ( source == null ) {
            return null;
        }

        List<To> list = new ArrayList<To>( source.size() );
        for ( From from : source ) {
            list.add( convert( from ) );
        }

        return list;
    }
}
```

```
@Qualifier
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.METHOD)
public @interface ToEntity {
}
```

**Comment by chris922** [comment]
Should your `after` method be invoked in the generated `a1` method? 
If yes you mixed up the types, `source` should be of type `A2` and `target` of type `A1` in your `after` method

**Comment by chris922** [comment]
@nestharus .. you don't need to communicate with us by changing the title 😆 you can just create a comment here... have you found your issue and we can close this here or what do you expect?

**Comment by nestharus** [comment]
@chris922 nah, I saw that the bug happens in our specific mapper. When I fixed the AfterMapping in my quick example that worked. Our mapper still doesn't. I put in our code instead.

**Comment by nestharus** [comment]
I figured out the problem. As a workaround, removing the annotation from all of the after mappings.

**Comment by filiphr** [comment]
@nestharus the fact that the after mapping is not picked up is correct and works as designed. In order for it to be picked up you would need to use [`BeanMapping#qualifiedBy`](http://mapstruct.org/documentation/stable/api/org/mapstruct/BeanMapping.html#qualifiedBy--) on your mapping methods.

The entire idea with the `@Qualifier` annotation is to be picked up only if you explicitly request it.
