### ISSUE TITLE
CollectionMappingStrategy.ADDER_PREFERRED overrides qualifiedByName

### ISSUE THREAD

**Issue by TeoDimitrov** [mapstruct/mapstruct#1838]
When I have **CollectionMappingStrategy.ADDER_PREFERRED**, **qualifiedByName** is ignored. I believe the priority should be in favor of the method. When I remove the collection strategy it works.

Here is the example:
```java
@Mapper(componentModel = "spring", uses = {AttachmentMapper.class}, collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED)
public abstract class AttachmentCategoryMapper {

    @Mapping(source = "attachments", target = "attachments", qualifiedByName = "toSortedAttachments")
    public abstract AttachmentCategoryViewModel toViewModel(AttachmentCategory attachmentCategory);

    @Named("toSortedAttachments")
    protected List<AttachmentConsumerDTO> toSortedAttachments(List<Attachment> attachments) {
        // Sort
    }
}

**Comment by filiphr** [comment]
Thanks for reporting this one @TeoDimitrov.

This would be a tricky one to solve. The reason for that is that the `collectionMappingStrategy` is applied when the accessor is picked. This means that when `CollectionMappingStrategy.ADDER_PREFERRED` is used then the `qualifiedByName` would be applied on the mapping of the element.

Looking at your example you could solve this by using `@AfterMapping`.

For example

```
@Mapper(componentModel = "spring", uses = {AttachmentMapper.class}, collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED)
public abstract class AttachmentCategoryMapper {

    public abstract AttachmentCategoryViewModel toViewModel(AttachmentCategory attachmentCategory);

    @AfterMapping
    protected void toSortedAttachments(@MappingTarget AttachmentCategoryViewModel viewModel) {
        // Sort
        if (viewModel.getAttachments() != null) {
            Collections.sort(viewModel.getAttachments());
        }
    }
}
```

@sjaakd should we close this one as won't fix? Or perhaps we should update the javadoc for `CollectionMappingStrategy#ADDER_PREFERRED` to say that the `qualifiedBy` is applied on the mapping between the element type?

**Comment by sjaakd** [comment]
> @sjaakd should we close this one as won't fix? Or perhaps we should update the javadoc for `CollectionMappingStrategy#ADDER_PREFERRED` to say that the `qualifiedBy` is applied on the mapping between the element type?

Agreed. This might be a can of worms and a solution is available.
