### ISSUE TITLE
Unknown property error, but property is present

### ISSUE THREAD

**Issue by dchkoniya** [mapstruct/mapstruct#1839]
https://stackoverflow.com/questions/56559136/mapstruct-problem-unknown-property-error-but-property-is-present

**Comment by harshil-nori12** [comment]
Do update this once you get the cause for this

**Comment by filiphr** [comment]
This is a known problem. See https://github.com/mapstruct/mapstruct/issues/1799. Fluent setters starting with `set` have the starting `set` removed so `settlementDate` becomes `tlementDate`

**Comment by dchkoniya** [comment]
thank you.
