### ISSUE TITLE
Lombok's @SuperBuilder prevents MapStruct from calling @AfterMapping

### ISSUE THREAD

**Issue by tschmidt01** [mapstruct/mapstruct#1841]
Given
Source.java

```
@Data
public class Source {

    private String parentField;

    private String childField;

}
```

TargetParent.java
```
@Getter
@SuperBuilder
public abstract class TargetParent {

    private String parentField;

}
```

TargetChild.java
```
@Getter
@SuperBuilder
public class TargetChild extends TargetParent {

    private String childField;

    private String afterMappingField;

}
```

SourceTargetChildMapper.java
```
@Mapper
public abstract class SourceTargetChildMapper {

    public static final SourceTargetChildMapper MAPPER = Mappers.getMapper(SourceTargetChildMapper.class);

    public static final String AFTER_MAPPING_FIELD_VAL = "some-random-val";

    public abstract TargetChild toTarget(Source s);

    @AfterMapping
    public TargetChild afterMapping(Source s, @MappingTarget TargetChild.TargetChildBuilder target) {
        target.afterMappingField(AFTER_MAPPING_FIELD_VAL);
        return target.build();
    }
}
```

Generating the `SourceTargetChildMapperImpl.java` results in
```
public class SourceTargetChildMapperImpl extends SourceTargetChildMapper {

    @Override
    public TargetChild toTarget(Source s) {
        if ( s == null ) {
            return null;
        }

        TargetChildBuilder<?, ?> targetChild = TargetChild.builder();

        targetChild.parentField( s.getParentField() );
        targetChild.childField( s.getChildField() );

        return targetChild.build();
    }
}
```

As you can see the method `toTarget` does not invoke the `afterMapping` method defined in `SourceTargetChildMapper`

Link to the repository demonstrating the problem, unit test included: [tschmidt01/mapstruct-lombok-supermapper](https://github.com/tschmidt01/mapstruct-lombok-supermapper)

**Comment by filiphr** [comment]
@tschmidt01 I see that your `afterMapping` returns `TargetChild`. Is there a reason for that? If you change the return into `void` it should be picked up.

**Comment by tschmidt01** [comment]
Thanks for the reply @filiphr. I've updated the example project, changing the method return from `TargetChild` to `void` didn't fix it though.

**Comment by Arnaud-J** [comment]
Hi!
Just created a pull request: https://github.com/tschmidt01/mapstruct-lombok-supermapper/pull/1
Please read the description for details and tell me if that fixes your issue :slightly_smiling_face:

**Comment by tschmidt01** [comment]
@Arnaud-J Awesome, works now! Thanks a lot.
