### ISSUE TITLE
Allow Package-Private Field-Access

### ISSUE THREAD

**Issue by lostiniceland** [mapstruct/mapstruct#1842]
The field-access support was already a big step forward, but it would be great if it would not be mandatory to make fields public and instead use package-private visibility.

When following a hexagonal layering, we usually have all classes for a certain technology-adapter in one package. This includes the MapStruct interface (and hence the generated impl) as well as the necessary DTO(s).
In this case it is just not necessary to make fields puplic, since the generated mapper-impl can access those fields.

I would be enough to check if the mapper and target class reside in the same package. Use Bean-Convention if possible but fall-back to package-private fields if possible and as a last resort public fields.

**Comment by filiphr** [comment]
@lostiniceland isn't #1689 the same as this one?

**Comment by lostiniceland** [comment]
Yes, that would be the same. As the discussion already suggested, if the type is in the same package, default visibility should suffice.
