### ISSUE TITLE
Using (uses) with other beans spring

### ISSUE THREAD

**Issue by RuslanSafa** [mapstruct/mapstruct#1843]
The problem is in using the utility for mapping and another beans @ Component.
In this case:
We get an abstract class with a manual @Autowired (should not be private to use in the generated class) and an implementation in which @Autowired is a utility.
The idea is to expand @Mapping annotation, with the configuration injected = {Bean. Class, Bean 2. Class}, which allows using the expression for the beans.
```java
@Mapper(uses = MapperUtils.class, componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR, injected = Bean.class)
public interface TestMapper {

   @Mapping(target = "name", sourse = "name", qualidiedByName = "test") //Use MapperUtils
   @Mapping(target = "name", expression = "java(bean.getTestUid())") //Use Bean
   One map(OneDto dto);
```
Generated implementation
```java
@Component
public class TestMapperImpl implements TestMapper {

   private final MapperUtils mapperUtils;
   private final Bean bean;

   @Autowired
   public TestMapperImpl(MapperUtils mapperUtils, Bean bean) {
        this.mapperUtils=mapperUtils;
        this.bean=bean;
   }
   
   public One map(OneDto dto) {
     // Mapping
   }
}
```
Improve reading and support of mappers
Allows to use expressions for other beans without a class in abstract.

**Comment by chris922** [comment]
I am not sure if I can follow you.

What you want to achieve is, that you can use an injected instance of `Bean` in an `expression`?

If yes you should try to add `Bean.class` to `uses` (switch to an array).. I am not completely sure if `bean` will be available, because MapStruct will not be able to detect that `bean` is used somewhere

**Comment by RuslanSafa** [comment]
In my cure there are utilities that are spring bean, so I need to inject it for use.

And also add `Bean.class` to `uses`, then if there is a method in this bean that accepts String and returns String, he will apply it to all sources and targets, as he perceives it as a mapper.

I think you can check for the presence of expression using the name of the bean.

An alternative option is the ability to configure auto-applying methods from classes to `uses`.
For example:
UsesStrategy = AUTO, ONLY_QUALIFIER...

**Comment by RuslanSafa** [comment]
Another alternative use `qualidiedByName`  without source
```java
@Mapping(target = "name", qualidiedByName = "TestUid")
   One map(OneDto dto);

    @Named("TestUid")
    public String getId() {}
```

**Comment by chris922** [comment]
Aahh, so you can't add `Bean.class` to `uses` because `Bean` provides some methods that would then mistakenly be chosen for some mappings, because the method signature fits?

And your idea is to have some possibility to prevent this? Either by having a new attribute similar to `uses`, but for which the given classes will not be used for mapping or by forcing the usage of qualifiers and prevent any auto-mappings?

**Comment by RuslanSafa** [comment]
> Aahh, so you can't add `Bean.class` to `uses` because `Bean` provides some methods that would then mistakenly be chosen for some mappings, because the method signature fits?
Exactly
> And your idea is to have some possibility to prevent this? Either by having a new attribute similar to `uses`, but for which the given classes will not be used for mapping or by forcing the usage of qualifiers and prevent any auto-mappings?
That is what I meant. And suggested various ideas on this.

**Comment by filiphr** [comment]
@RuslanSafa with what you explained you could do it with a manual inject and an abstract class.

For example:

```java
@Mapper(uses = MapperUtils.class, componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public abstract TestMapper {

    protected Bean bean;

   @Mapping(target = "name", sourse = "name", qualidiedByName = "test") //Use MapperUtils
   @Mapping(target = "name", expression = "java(bean.getTestUid())") //Use Bean
   One map(OneDto dto);

    @Autowired
    public void setBean(Bean bean) {
        this.bean = bean;
    }
}
```

**Comment by filiphr** [comment]
Closing this since this is possible to be done with an `abstract` class and field or setter injection.

**Comment by RuslanSafa** [comment]
This is how I use it. This issues was proposed as an idea.
