### ISSUE TITLE
give better location information for failing nested list methods.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1846]
When MapStruct cannot make a (nested mapping) for a list, the error message leaves you clueless:

Ambiguous mapping methods found for mapping collection element to java.lang.Object: java.lang.String nl.bro.transform.common.BroCodeWithAuthorityTypeMapper.getCode(net.opengis.gml.v_3_2_1.CodeWithAuthorityType type), nl.bro.dto.common.BroRefCode nl.bro.transform.common.BroCodeWithAuthorityTypeMapper.toBroRefCode(net.opengis.gml.v_3_2_1.CodeWithAuthorityType type).

**Comment by sjaakd** [comment]
done by PR #2156

**Comment by WilliamShoww** [comment]
1.3.1.final how to handler this problems?
```java 
Error:(26, 27) java: Ambiguous mapping methods found for mapping collection element to java.lang.Object: com.leixing.bbs.model.RoleBriefModel toRoleBriefModel(com.leixing.bbs.data.pojo.UserRole userRole), com.leixing.bbs.model.RoleFansModel toRoleFansModel(com.leixing.bbs.data.pojo.UserRole userRole).
```

**Comment by sjaakd** [comment]
please do not report on closed issues. Use StackOverflow for questions.
