### ISSUE TITLE
Mapping request to two entities with one to many relationship

### ISSUE THREAD

**Issue by abajric1** [mapstruct/mapstruct#1849]
Hi, I wan't to use let say property 'x'  (String type) from incoming request and update two entities which are in one to many relationship. Parent entity will have property 'x' as one field. Any ideas how to implement this? Preferably i would want to use mapstruct for this. Thank you.

**Comment by filiphr** [comment]
@abajric1 please use StackOverflow our [gitter room](https://gitter.im/mapstruct/mapstruct-users) for questions.

RIght now I can't really help you as I don't quite understand your question. Can you give some better examples please?
