### ISSUE TITLE
No way to ignore source fields with unmappedSourcePolicy = ERROR

### ISSUE THREAD

**Issue by TroyMass** [mapstruct/mapstruct#1882]
I'm trying to enforce strict mapping on all of my mappers so that all fields on the source and target are explicitly ignored if not mapped. To do this I configured my mappers with:

`@Mapper( unmappedSourcePolicy = ReportingPolicy.ERROR,
         unmappedTargetPolicy = ReportingPolicy.ERROR )`

When there is a field in the source object that does not exist in the target, there is not a way to mark it explicitly as ignored.

`@Mapping( source = "foo", ignore = true )`

The above line does not work because of the error `'target' missing though required`

Either `@Mapping` needs to have a default value for the target field, or there needs to be another annotation like `@MappingIgnore( source = "foo" )`

**Comment by sjaakd** [comment]
Have you tried our latest master? I think I solved an issue a while ago on this one.

**Comment by filiphr** [comment]
@TroyMass have you tried with [`BeanMapping#ignoreUnmappedSourceProperties`](https://mapstruct.org/documentation/stable/api/org/mapstruct/BeanMapping.html#ignoreUnmappedSourceProperties--)

**Comment by nettadhp** [comment]
@filiphr - From what I can tell, it isn't possible to use ignoreUnmappedSourceProperties more than once. Also, since there is the constant limitation for annotations there is no way to extend it. What if you want to hardcode a list of properties to be ignored from the source (for protobuf for example) and then add onto them on a case by case basis? Is there a way to do this?

**Comment by filiphr** [comment]
@nettadhp I am not sure what you mean with use it more than once. 

If we are talking about things like protobuf than this needs to be resolved on a different level. Those methods should not even be considered as properties. Have a look at an SPI extension from the community around protobuf (https://github.com/entur/mapstruct-spi-protobuf).

**Comment by nettadhp** [comment]
@filiphr thanks for responding. I'm referring to some config option that would allow me to define "ignoreUnmappedSourceProperties", use it in multiple mappings, and add onto it on a case by case basis
