### ISSUE TITLE
Mapstruct with Eclipse/JDK12/Lombok/Gradle/Spring gen code issue

### ISSUE THREAD

**Issue by niclarcipretti** [mapstruct/mapstruct#1891]
Hi,

I'm experimenting with mapstruct (Eclipse/JDK12/Lombok/Gradle/Spring) and despite my best efforts, it is not generating the mappers within apt_generated nor apt_generated_test folders.

I'm quite sure my configurations are ok, cause I use QueryDSL too and it generates the classes just fine.

Any tips?

Cheers

Nikao

**Comment by filiphr** [comment]
Is it possible for you to share an example project where you have the problem?

**Comment by niclarcipretti** [comment]
Hi Filip,

I guess any project using the stack above mentioned would have the same results I'm having. I'll try to provide an example tomorrow though.

Cheers

**Comment by AnakinPt** [comment]
I have this same problem. I created a small converter and the unit test. If I run using gradle it passes, but in Eclipse it won't find the compiled classes.

You can see the code in https://github.com/AnakinPt/taebox-backend

**Comment by AnakinPt** [comment]
I found I had the issue, because I was using the lombok plugin instead of the annotationProcessor. Removing the plugin and adding the annotationProcessor in the dependencies fixed the problem.

**Comment by sjaakd** [comment]
> I found I had the issue, because I was using the lombok plugin instead of the annotationProcessor. Removing the plugin and adding the annotationProcessor in the dependencies fixed the problem.

@AnakinPt thanks for reporting the solution.. @niclarcipretti : is this causing the issue for you as well?
