### ISSUE TITLE
Keep the collection/map original type during mapping the collection.

### ISSUE THREAD

**Issue by gr4ve** [mapstruct/mapstruct#1893]
map struct will use [collection type](https://mapstruct.org/documentation/stable/reference/html/#implementation-types-for-collection-mappings) to wrap the source collection. This strategy is sufficient in most scenarios, but sometimes we want to use specific collection type, such as linkedhashmap, for example we use linkedhashmap to keep the add order of a hashmap, but when we use map struct to do some convert things, the  information will be lost.

**Comment by sjaakd** [comment]
can't you use a factory?

**Comment by filiphr** [comment]
@gr4ve MapStruct is an annotation processing so it doesn't know the collection type during the generation of the mappers. You would need to use an `@ObjectFactory` in order to change this.
