### ISSUE TITLE
Mapstruct ADDER_PREFERRED with more than one field that can use adder not working properly

### ISSUE THREAD

**Issue by DNAlchemist** [mapstruct/mapstruct#1899]
- [x] Is this an issue (and hence not a question)? 

If there is only one adder method, the name of the adder is not will be compared with property.

Below is a snippet with **two collections** and **ADDER_PREFERRED** option on the mapper and only **one adder method**

```
class Source {
    List<String> elements;
    List<String> secondElements;

    // ... standard getters and setters
}

class Target {
    List<String> elements;
    List<String> secondElements;

    public void addSecondElement(String element) {
        secondElements.add( element );
    }

    // ... standard getters and setters 
}
```
Elements from both collections will be in a secondElements collection after mapping.

**Also when I fixed this, I found that the previously written functionality was broken** (testShouldFallBackToDaliSingularInAbsenseOfHumanSingular test failed). The bug I fixed hid the problem.
So I fixed this problem also in accordance with the test.

**Comment by DNAlchemist** [comment]
I see that this behavior is described in the documentation.
```To find the appropriate adder, MapStruct will try to make a match between the generic parameter type of the underlying collection and the single argument of a candidate adder.```
But, in my opinion, the adder should always match the name.

**Comment by sjaakd** [comment]
> But, in my opinion, the adder should always match the name. This behavior looks ambiguous.

That's kind of dangerous.. It breaks existing functionality which has been there for quite some time. The name match (even with doing some plural /singular matching) is a fallback for when there's a conflict.

**Comment by DNAlchemist** [comment]
@sjaakd It may be worthwhile to isolate the situation if more than one field can use adder. Despite backward compatibility, this is more looks like a bug. My snippet about it.

**Comment by filiphr** [comment]
@sjaakd I would say that the fact that we are using the single type matching adder is a bit unexpected (even though it is mentioned in the documentation).


I also looked into `testShouldFallBackToDaliSingularInAbsenseOfHumanSingular` it refers to fallbacking to Dali Singular in absense of Human Singular. However, according to the dali rules in `TargetDali` `teeth` should not match. So that test doesn't really test what it says that it tests.

I couldn't find where the dali rules are coming. I saw the link to https://www.eclipse.org/webtools/dali/. However, I couldn't find their rules. What I found is a blog post by Grammarly (https://www.grammarly.com/blog/plural-nouns/).

Perhaps we should output a warning when a single adder was found and it didn't match the rules (although that can be incorrect as well)

**Comment by filiphr** [comment]
@sjaakd something that I just thought about. We could introduce an SPI for the singularization. This way people can write their own rules if they want (need) to

**Comment by sjaakd** [comment]
@filiphr I need to get into this a bit more. It's long time ago.

**Comment by sjaakd** [comment]
> I couldn't find where the dali rules are coming. I saw the link to https://www.eclipse.org/webtools/dali/. However, I couldn't find their rules. What I found is a blog post by Grammarly (https://www.grammarly.com/blog/plural-nouns/).

Like said.. its long time ago.. But the Dali rules (at that time I think it was the entity generation plugin in Eclipse) is pretty simple. It does not handle the conversion from singular to plural very well. I remember I found some rules somewhere that I used to make nice conversions. Like tooth-teeth, sheep-sheep, foot-feet, etc.. There implemented in the class `org.mapstruct.ap.internal.util.Nouns`

**Comment by DNAlchemist** [comment]
So how can I help with this issue @filiphr?

**Comment by sjaakd** [comment]
> @sjaakd Maybe we need to isolate the situation if more than one field can use single adder. Despite backward compatibility, this is more looks like a bug.
> My snippet about it. Two fields must not be allowed to use the same adder. I can't imagine a case when such behavior is necessary.

You are right here. I think this would be the solution. So to get it clear. 

The current situation:

1. The add method would be selected on type.
2. In case there are multiple candidates, select based on name (note: there are 2 mechanisms, a simple name base selection and a true one that makes the distinction between tooth, teeth).

The desired solution:

1. The add method would be selected on type.
2a. In case one candidate `add method` is applicable to multiple properties: resolve by name.
2b. (as in current 2), In case  multiple `add methods` apply: resolve by name



> So how can I help with this issue @filiphr?

Can you provide a PR for that?

@filiphr : regarding your remark, perhaps some of the utils should be part of the SPI (as util) so they can be overridden. Although I'm not too excited putting much stuff there. Feels a bit risky as well.

**Comment by filiphr** [comment]
@shaike41 the issue was closed because there exists a community lead [MapStruct Protobuf Extension](https://github.com/entur/mapstruct-spi-protobuf) and we believe that it s better to implement such a functionality in that extension
