### ISSUE TITLE
Error trying ignore target

### ISSUE THREAD

**Issue by cjgmj** [mapstruct/mapstruct#1913]
I am trying to ignore an attribute when mapping the entity but I'm getting the followin error:
`No property named "teams" exists in source parameter(s). Did you mean "empty"?`

I'm using Lombok so I put it on annotationProcessorPaths
> 
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<configuration>
			<source>1.8</source>
			<target>1.8</target>
			<annotationProcessorPaths>
				<path>
					<groupId>org.mapstruct</groupId>
					<artifactId>mapstruct-processor</artifactId>
					<version>1.3.0.Final</version>
				</path>
				<path>
					<groupId>org.projectlombok</groupId>
					<artifactId>lombok</artifactId>
					<version>1.18.8</version>
				</path>
			</annotationProcessorPaths>
		</configuration>
	</plugin>

I create this mapper
> 
	@Mapper(componentModel = "spring")
	public interface LeagueMapper {

		@Mapping(target = "teams", ignore = true)
		List<League> leaguesEntityToLeagues(List<LeagueEntity> league);

	}

And these are the classes
> 
	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	public class LeagueEntity {
		...
		private Set<TeamEntity> teams;
		...
	}
> 
	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	public class League {
		...
		private Set<Team> teams;
		...
	}

Where is the problem?

**Comment by Captain1653** [comment]
Dou you have property "id" in target? Maybe you should ignore property "id"?

**Comment by cjgmj** [comment]
> Dou you have property "id" in target? Maybe you should ignore property "id"? Maybe mapper try to fill target.id, but you don't have property "id" in source

Sorry, it was the error from other test, I just update the post

**Comment by Captain1653** [comment]
Can you try to change return value your mapper from  List<League> to Set<Legague> ?  You target entity contains Set, right?

**Comment by cjgmj** [comment]
> Can you try to change return value your mapper from List to Set ? You target entity contains Set, right?

Id was Long and I got same error, anyway I will try

**Comment by Captain1653** [comment]
No, sorry. Can you publish your full example on gitgub? I'll check

**Comment by cjgmj** [comment]
Of course.
LeagueEntity: https://github.com/cjgmj/testGraphQL/blob/master/src/main/java/com/cjgmj/testGraphQL/entity/LeagueEntity.java
LeagueMapper: https://github.com/cjgmj/testGraphQL/blob/master/src/main/java/com/cjgmj/testGraphQL/mapper/LeagueMapper.java
League: https://github.com/cjgmj/testGraphQL/blob/master/src/main/java/com/cjgmj/testGraphQL/objects/type/League.java
POM: https://github.com/cjgmj/testGraphQL/blob/master/pom.xml

**Comment by Captain1653** [comment]
Firstly, you should create method in your mapper method. See mapping collection in our documentation [link](https://mapstruct.org/documentation/stable/reference/html/#mapping-collections)

`@Mapping(target = "teams", ignore = true)
    League map(LeagueEntity leagueEntity);`

Next. Do you want to call contructor with all arguments? Is it necessary?

**Comment by cjgmj** [comment]
Thank you, that was the error. Can I be able to call a sub attribute concatenated it with "."?

**Comment by Captain1653** [comment]
You may use [this](https://mapstruct.org/documentation/stable/reference/html/#controlling-nested-bean-mappings)

**Comment by cjgmj** [comment]
I try to do 
> 
	@Mapping(target = "teams.league", ignore = true)
	League leagueEntityToLeague(LeagueEntity leagueEntity);

But I got 
`Unknown property "teams.league" in result type com.cjgmj.testGraphQL.objects.type.League. Did you mean "teams.empty"?`

**Comment by Captain1653** [comment]
Ignore fields works something like that @Mapping(target="teams", ignore=true). It means ignore field "teams" in target object (League for you)

**Comment by cjgmj** [comment]
But I just want ignore league from teams to avoid circular references

**Comment by Captain1653** [comment]
Is it what do you need?
![Снимок экрана от 2019-09-21 16-04-02](https://user-images.githubusercontent.com/4740207/65373714-831f2f00-dc89-11e9-95de-ed694e306561.png)

**Comment by cjgmj** [comment]
No, I want to map Teams but avoid Leagues
![image](https://user-images.githubusercontent.com/16681783/65373761-f7ee6b00-dc81-11e9-8eab-085fc1a1d907.png)


Something like this

**Comment by Captain1653** [comment]
Then you should write additional map method for convert TeamEntity to Team and ignore field league.

```
@Mapping(target="league", ignore=true)
Team map(TeamEntity teamEntity)
```  
like with League and league entity

**Comment by cjgmj** [comment]
Then, I can't do like [this](https://mapstruct.org/documentation/stable/reference/html/#controlling-nested-bean-mappings)?

**Comment by Captain1653** [comment]
I'm not sure, but I think no. Because you should say how mapstruct should map your entities. When you write @Mapping(target="team.league" ignore=true) you can try to find field "league" in collection, but not in the entity. I home my last answer will work for you. Isn't it?

**Comment by cjgmj** [comment]
Yes, it work. Thank you
