### ISSUE TITLE
Bugfix Release 1.3.1

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1916]
I've created a milestone [1.3.1](https://github.com/mapstruct/mapstruct/milestone/29). I've also created a branch https://github.com/mapstruct/mapstruct/commits/1.3.x that contains the commits and issues that I think we should include in the release.

Some of the bugs that were assigned to 1.4.0 are already moved to 1.3.1. 

I think that we should also include the fixes for the following issues:

- [x] #1742 fixed in https://github.com/mapstruct/mapstruct/commit/33710584d33856495992c7cab511b4a16643f53e
- [x] #1801 fixed in https://github.com/mapstruct/mapstruct/commit/7e0327767f1a375a59b76ef2458a6394d8a5786e

If there are some other issues that we should add then then please comment here

**Comment by sjaakd** [comment]
what kind of criterium are you using? 

* Bugs in new functionality? 
* Or.. perhaps we should add regression as well.

**Comment by filiphr** [comment]
Regressions and bugs in functionality that were added up to 1.3.0.Final. Not bugs in functionality added after 1.3.0.Final

**Comment by filiphr** [comment]
I think that we have ported most of the issues.

Currently there are 2 more bugs in the 1.4.0 milestone:

- [x] #1821 fixed in ade4f4d7e2ab87b2e0f113221d3fc9a6729f78cc - I think that the fix relies on the new refactoring and that it is not a major issue so we don't have to port it
- [ ] #1828 - This one has not been fixed nor analyzed yet. I'll have a look to try and determine what the problem is.

Is there something else pending for the 1.3.1 release?
