### ISSUE TITLE
Only generate field / imports for a referenced mapper if it is actually used

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#194]

**Comment by sjaakd** [comment]
Partially done.. The import remains. The field is only included if a non-static method is actually called. 

I'm wondering here wether we should do anything more. The user has a certain responsibility as well. WDYT?

**Comment by agudian** [comment]
Getting rid of the import as well would be great, but we can tackle that in a separate issue later on in case we see the need for it.
Generally, such unused referenced mappers could lurk in from general mapper-config classes where maybe not every "used" mapper is required in all the mappers. So it might become tideous for users to get rid of them by creating another mapper-config or something like that.

@sjaakd: it's in beta4, right?

**Comment by sjaakd** [comment]
> @sjaakd: it's in beta4, right?

Yep..

What I can do is make a fix for imports as well. Its a quite easy effort.. Now we set a primitive `boolean` used depending if its a static method / or not.. We might decide to make this is a wrapper `Boolean`. Not initialized means: not used at all and can be taken from the imports. WDYT?

We can keep this one open and if we agree, I'll make a fix today.

Btw: I think its better to move the check in the templates to an outer level (so to GeneratedType). Now sometimes an empty line is inserted for instance variables when MapStruct decides its not used.

**Comment by sjaakd** [comment]
Sorry. Could not leave it like this :smile: lets fix it completely.

**Comment by sjaakd** [comment]
ok now really done..

**Comment by gunnarmorling** [comment]
Cool, thanks!
