### ISSUE TITLE
MapStruct does not map boolean properties 

### ISSUE THREAD

**Issue by dantheperson** [mapstruct/mapstruct#1943]
I have two lombok DTO with identical 'isActive' pimative boolean properties.

mapstruct does not map them.  Works fine for string etc.

```
package test;
import lombok.Builder;
import lombok.Value;

@Value
@Builder
public class ProductOne {
	boolean isActive;
}

-------------
package test;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class ProductTwo {

	boolean isActive;

}
--------------
package test;
import org.mapstruct.Mapper;

@Mapper
public interface ProductMapper {

	ProductTwo map(ProductOne one);

}
---------------
package test;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

public class MyTest {


	ProductMapper mapper = Mappers.getMapper(ProductMapper.class);

	@Test
	void test() {


		ProductOne one = ProductOne.builder().isActive(true).build();
		ProductTwo two = mapper.map(one);

		assertThat(two.isActive()).isTrue();

	}
}
```

**Comment by dantheperson** [comment]
If i try to force it

@Mapping(source = "isActive", target = "isActive")
ProductTwo map(ProductOne one);

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dcarter/dev/platform-services/catalog-index/catalog-index/src/test/java/test/ProductMapper.java:[8,9] No property named "isActive" exists in source parameter(s). Did you mean "active"?


@Mapping(source = "active", target = "active")
ProductTwo map(ProductOne one);
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dcarter/dev/platform-services/catalog-index/catalog-index/src/test/java/test/ProductMapper.java:[8,9] Unknown property "active" in result type test.ProductTwo. Did you mean "null"?


Finally, this one works
	@Mapping(source = "active", target = "isActive")
	ProductTwo map(ProductOne one);

But why two different property names when both DTOs have the same property name?

**Comment by dantheperson** [comment]
Hi,

Both have boolean isActive()  (and the @Data also has  void setActive(boolean))

But i think it's the builder that's more relevant?
Both builders have isActive(boolean)

Here's a full project with the trivial demonstration.
https://github.com/dantheperson/demo/tree/master/mapstruct-1943

**Comment by dantheperson** [comment]
Also, if i make both Objects the same, either both @Data or both @Value, same issue.

Thanks for an otherwise great tool BTW!

**Comment by sjaakd** [comment]
one question: `isActive` leads to a read accessor (getter) `isIsActive` right? That explains your fault message. Just name your property `active` I guess.


> Thanks for an otherwise great tool BTW!

Thanks :smile: .. always nice to hear.

**Comment by Omkar-Halikar** [comment]
> one question: `isActive` leads to a read accessor (getter) `isIsActive` right? That explains your fault message. Just name your property `active` I guess.
> 
> > Thanks for an otherwise great tool BTW!
> 
> Thanks  .. always nice to hear.

Yep. The general convention for naming a boolean property is **active** and its respective getter is **isActive**. However in lombok, having a prop as **isActive** still gives a getter as **isActive** and not **isIsActive**.
 [For boolean fields that start with is immediately followed by a title-case letter, nothing is prefixed to generate the getter name.](https://projectlombok.org/features/GetterSetter)
https://www.baeldung.com/lombok-getter-boolean

I further dug into the problem. When mapping entity **A**(ProductEntity) to entity **B**(ProductDao), having **isActive** as a prop in **A** and **active** in **B** works fine, mapstruct constructs the mapper class , however same is not the case when prop name is **isActive** in **B**. Following the generated code.

When prop name is **active** in B(ProductDao):
`public class ProductMapperImpl implements ProductMapper {

    @Override
    public ProductDao map(ProductEntity one) {
        if ( one == null ) {
            return null;
        }

        ProductDaoBuilder productDao = ProductDao.builder();

        productDao.active( one.isActive() );

        return productDao.build();
    }
}`

When prop name is **isActive** in B(ProductDao):

`public class ProductMapperImpl implements ProductMapper {

    @Override
    public ProductDao map(ProductEntity one) {
        if ( one == null ) {
            return null;
        }

        ProductDaoBuilder productDao = ProductDao.builder();

        return productDao.build();
    }
}`

**productDao.active( one.isActive() );** is missing

Can someone point out where booleans are processed so I can see the underlying implementation.

**Comment by sjaakd** [comment]
> Yep. The general convention for naming a boolean property is **active** and its respective getter is **isActive**. However in lombok, having a prop as **isActive** still gives a getter as **isActive** and not **isIsActive**.

The problem is: we want to work via convention. Lombok has introduced an exception. That's a bit unfortunate. For MapStruct we try to adhere to the bean convention. For instance, take a property that starts with `is` by its natural name. Like `isoCompliant`. (iso like the international standards organisation). 

I guess that Lombok would make this `isOCompliant()` which is wrong. But I'd like to be proven wrong on this.

**Comment by Omkar-Halikar** [comment]
[For boolean fields that start with is immediately followed by a title-case letter, nothing is prefixed to generate the getter name.](https://projectlombok.org/features/GetterSetter)

If you look closely, in case of **isActive**, "is" is immediately followed by Active and hence it is left as **isActive**. In case of isoCompliant, the above case is not true because of the extra "o" and falls back to the default case of converting the very first char to title case, hence the getter becomes **isIsoCompliant**. I tried it in the code and the previous statement holds true.

**Comment by sjaakd** [comment]
> If you look closely, in case of **isActive**, "is" is immediately followed by Active and hence it is left as **isActive**. In case of isoCompliant, the above case is not true because of the extra "o" and falls back to the default case of converting the very first char to title case, hence the getter becomes **isIsoCompliant**. I tried it in the code and the previous statement holds true.

Good they (Lombok) covered this case. But I still see no reason to include such functionality in MapStruct.

By the way: how does the setter look like? I guess Lombok has adapted that as well.

Anyway:  Can't you rename the property? That seems (to me) the proper thing to do and  in line with the bean convention.

**Comment by dantheperson** [comment]
> Yep. The general convention for naming a boolean property is active and its respective getter is isActive.

Disagree, there is no general convention for naming a boolean, it's one of those contested areas with good arguments on either side, all that really matters is you pick one convention and stick with it. E.g. see the top two answers here:
https://stackoverflow.com/questions/5322648/for-a-boolean-field-what-is-the-naming-convention-for-its-getter-setter

Many years ago those before me chose to follow the convention used by Sun/Oracle in the JDK classes, which is to prefix boolean field names with the prefix 'is'.  I don't fancy changing our coding standard and refactoring a huge body of POJO, JPA, and Jackson DTO classes just to use MapStruct.  

> The problem is: we want to work via convention. Lombok has introduced an exception. 

According to lombok, they are just following the existing convention from the Javabeans spec that eclipse,netbeans,hibernate,etc are following
https://github.com/rzwitserloot/lombok/issues/221

Whatever your perspective on what boolean fields should be named (active/isActive) it seems to me if you do encounter one, the convention for primitive booleans is to name the getter with an 'is' prefix, discarding any is prefix that may exist on the field name itself.  The setter remains setActive(boolean isActive), and out of our various toolchains and frameworks it's only MapStruct that is not following this convention.

**Comment by sjaakd** [comment]
> Disagree, there is no general convention for naming a boolean, it's one of those contested areas with good arguments on either side, all that really matters is you pick one convention and stick with it. E.g. see the top two answers here:
> https://stackoverflow.com/questions/5322648/for-a-boolean-field-what-is-the-naming-convention-for-its-getter-setter

I guess the real top answer is the first :smile:  (225).. 

> Many years ago those before me chose to follow the convention used by Sun/Oracle in the JDK classes, which is to prefix boolean field names with the prefix 'is'.

True.. the Java code convention sais:

![jsr_beans](https://user-images.githubusercontent.com/6173283/68577220-eea6a100-046f-11ea-81a3-88aa7bbfc162.PNG)

----
But.. what's more import for you. There's a way you can customize the way MapStruct handles properties inside your organization. The SPI offers this function by a custom naming access strategy. See [here](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy). I guess you could adapt the behavior here to anything you desire.

Wrt to the standard MapStruct, I can discuss the issue with the other main contributors. @filiphr : what's your opinion?. But for myself, I'm still not convinced.

**Comment by sjaakd** [comment]
> But.. what's more import for you. There's a way you can customize the way MapStruct handles properties inside your organization. The SPI offers this function by a custom naming access strategy. See [here](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy). I guess you could adapt the behavior here to anything you desire.

@Omkar-Halikar @dantheperson .. is this a viable solution for you guys?

@filiphr What is your take on this?

**Comment by greifegerste** [comment]
You can do something like 
`@Mapping(target = "active", source = "source.isActive")`
 don't ya ?

**Comment by dantheperson** [comment]
Yes as mentioned it can be done with a manual mapping, when source and target both have the same property "isInActive" then you can force MapStruct to map them with
`@Mapping(source = "inActive", target = "isInActive")``

but of course, why?  It is not obvious with Mapstruct that you need to manually map boolean fields that start with the 'is' prefix, and leads to lots of subtle bugs, and it seems to keep changing with Mapstruct/lombok versions, some versions Mapstract will use the lombok builder, other times it will just create the target object and call setters, and this seems to change if it needs the manual mapping or not.

In the end I have to write a unit test for every mapstruct mapper that tests the boolean fields so that when i bump the spring boot version i can see which Mappers are breaking.

**Comment by jakoss** [comment]
I'm going back to the topic - the same thing is breaking the mappers using kotlin classes. 

```kotlin
data class Test(
  val isActive: Boolean
)
```
This code generates a getter is is called `isActive`. The same thing is for properties starting with "has". I'm trying to bypass this using custom accessor naming strategy, but i'm not sure what i'm doing wrong. 

This:

```kotlin
    override fun getPropertyName(getterOrSetterMethod: ExecutableElement): String {
        val methodName = getterOrSetterMethod.simpleName.toString()
        return if (methodName.startsWith("get") || methodName.startsWith("set")) {
            methodName.substring(3).replaceFirstChar { it.lowercase(Locale.getDefault()) }
        } else {
            // scenario with "is" and "has" - do not change the name here
            methodName
        }
    }
```

Does not fix the issue, i think have error `Unmapped target property: "isActive"`. It seems to me like the resolving of the property name is done somewhere outside the accessor naming? Or maybe i don't understand what i'm doing here

**Comment by CoffeSweetMilk** [comment]
Still not fixed, not convenient for kotlin

**Comment by jakoss** [comment]
@CoffeSweetMilk and for all interested - the alternative showed up: https://github.com/s0nicyouth/kmapper

Please test it out and contribute if you can

**Comment by fresh-fx59** [comment]
As I can see from my JAVA code, the **Lombok + Mapstruct can't deal with primitive _boolean isValid_**. However Object _Boolean isValid_ works fine. See example below.

I'll try to explain:
While _isValid_ is an Object - _Boolean_, Lombok generates `setIsValid` as Setter and `getIsValid` as Getter. Mapstruct is OK with this.
While _isValid_ is a primitive - _boolean_, Lombok generates `setValid` as setter and `isValid` for getter. Mapstruct can't handle these setter and getter.


Working example
```
@Builder
@With
@Data
@EqualsAndHashCode(callSuper=true)
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "XmlFile dto for CRUD operations")
public class XmlFileDTO extends BaseEntityDTO implements Serializable {

    @NotNull
    @Schema(description = "Is file valid.")
    private Boolean isValid;

}


@With
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "xml_file")
public class XmlFile extends BaseEntity implements Serializable {

    @NotNull
    @Column(name = "is_valid", nullable = false)
    private Boolean isValid;

}


@Named("XmlFileMapper")
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.WARN)
public abstract class XmlFileMapper implements EntityMapper<XmlFileDTO, XmlFile> { }

```

**Comment by JainavAgarwal** [comment]
As on Today
The following code of mine worked without using 'is' in the domain model

Domain Entity :
```
package com.amazon.ardatasourceproviderservice.component.domainmodel;


import lombok.Builder;
import lombok.Value;

/**
 * Domain object corresponding to Vendor Contract.
 */

@Builder
@Value
public class AllowanceDataForVendor {

    boolean overstockAllowance;
    boolean damageAllowance;

}
```

Conversion Entity in Smithy :
```
structure GetVendorContractForVendorCodeResponse {
    isOverstockAllowance: Boolean
    isDamageAllowance: Boolean
}
```

Map Struct Mapper code :

```
    @Mappings({
            @Mapping(source = "allowanceDataForVendor.damageAllowance", target = "withIsDamageAllowance"),
            @Mapping(source = "allowanceDataForVendor.overstockAllowance", target = "withIsOverstockAllowance"),
    })
    GetVendorContractForVendorCodeResponse getVendorContractForVendorCodeResponse(
            AllowanceDataForVendor allowanceDataForVendor);
```

And it worked 👍

**Comment by nstdspace** [comment]
I think this issue should be reopened. This problems makes mapstruct very weird to use with kotlin 
when you follow the is* naming convention.

**Comment by filiphr** [comment]
Unfortunately reopening this is a big can of worms @nstdspace. Perhaps this can be resolved in a kotlin specific way when we address the kotlin data classes (#2281)

**Comment by agitrubard** [comment]
@filiphr It's not a Kotlin issue. It's a MapStruct issue. 

I can explain our scnerio: Our table has `IS_SUPER` column. JPA can converting `IS_SUPER` column to `boolean isSuper` variable when reading record from database. But MapStruct cannot mapping `boolean isSuper` to `boolean isSuper`. I can adding `permission.isSuper(source.isSuper());` line to MapStruct implementation class manually. 

Why MapStruct can't do this, if I can?

**Comment by filiphr** [comment]
@agitrubard it is not a MapStruct issue. The getter is `isSuper` which according to the Java Bean specification means that the name of the property in your `source` is called `super`. The setter is a fluent setter `isSuper` and because it is a fluent setter the name of the property there is `isSuper`. 

You should not look at it from the perspective of the properties, but rather from the perspective of the public methods that MapStruct uses.

The reason why I said that this needs to be tackled with the data classes is due to the fact that when viewed from the perspective of a data class the name of the property is `isSuper`. This works properly if a Java record is used. If the name of the property there is `isSuper` then MapStruct is going to see it properly.

**Comment by filiphr** [comment]
I see now that @thunderhook explained in detail in the other issues you opened (https://github.com/mapstruct/mapstruct/issues/3702#issuecomment-2336819938)

**Comment by Grantismo** [comment]
@filiphr Would it not be possible to allow overriding or extending the existing convention to support such use-cases? It appears to be a common issue and the current workaround of renaming your variables or manually mapping fields reduces the value of this library in such real world cases.

**Comment by filiphr** [comment]
@Grantismo this is already possible. Have a look at [Custom Accessor Naming Strategy](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy) in our documentation

**Comment by Symfony-messenger-unques** [comment]
@Iamhomkar https://stackdev.space/questions/in-java-a-gettersetter-is-a-single-method-used-to-access-a-field-within-a-class
