### ISSUE TITLE
How to reusing mapping configurations when the transformation relationship is many to one?

### ISSUE THREAD

**Issue by liudaomanbu** [mapstruct/mapstruct#1962]
For example:
```java
public interface MyConverter{
@Mapping(target = "field1", source = "fieldA")
 MyDO1 myDTOToMyDO1 (MyDTO dto);
@Mapping(target = "field2", source = "fieldB")
 MyDO2 myDTOToMyDO2 (MyDTO dto);
@InheritConfiguration
 MyBO myDTOToMyBO(MyDTO dto);
}
public class MyDO1{
 String field1;
}
public class MyDO2{
 String field2;
}
public class MyBO{
 MyDO1 myDo1;
 MyDO2 myDo2;
}
public class MyDTO{
 String fieldA;
 String fieldB;
}
```
But the myDTOToMyBO  method is empty.
It not reusing the configuration for myDTOToMyDO1 method and myDTOToMyDO2 method.

In case that I don't find it in the document, I can make the mapping method from dto to two DOS reuse the configuration of the mapping method from dto to Bo, or make the mapping method from dto to Bo reuse the configuration of the mapping method from dto to two DOS

**Comment by sjaakd** [comment]
This is not the way it is supposed to work. If `@InheritConfiguration` is used, there needs to be an inheritance relation between `MyBO` and and either `MyDO1` or `MyDO2` on the target side. The same is valid on the source side.

BTW this works:
```java
    @Mapping(target = "myDo1.field1", source = "fieldA")
    @Mapping(target = "myDo2.field2", source = "fieldB")
    MyBO myDTOToMyBO(MyDTO dto);
```

Our [documentation](https://mapstruct.org/documentation/stable/reference/html/#_reusing_mapping_configurations) is not so very clear on that I realise (after reading it again). 

What you require is more in line what is requested [here](https://github.com/mapstruct/mapstruct/issues/807) as well. 

I'll proceed to close this issue. Upvote #807 to put some more focus on this.

**Comment by liudaomanbu** [comment]
> This is not the way it is supposed to work. If `@InheritConfiguration` is used, there needs to be an inheritance relation between `MyBO` and and either `MyDO1` or `MyDO2` on the target side. The same is valid on the source side.
> 
> BTW this works:
> 
> ```java
>     @Mapping(target = "myDo1.field1", source = "fieldA")
>     @Mapping(target = "myDo2.field2", source = "fieldB")
>     MyBO myDTOToMyBO(MyDTO dto);
> ```
> 
> Our [documentation](https://mapstruct.org/documentation/stable/reference/html/#_reusing_mapping_configurations) is not so very clear on that I realise (after reading it again).
> 
> What you require is more in line what is requested [here](https://github.com/mapstruct/mapstruct/issues/807) as well.
> 
> I'll proceed to close this issue. Upvote #807 to put some more focus on this.

Thanks.
