### ISSUE TITLE
Option to disable automatic mapping-method resolution

### ISSUE THREAD

**Issue by imeszaros** [mapstruct/mapstruct#1963]
This is a feature propsal based on https://groups.google.com/forum/#!topic/mapstruct-users/dtQUD6hYzy8

Automatic discovery and application of mapping methods sometimes yields undesired outcome. Consider the following Mapper:

```java
@Mapper
public interface SomeMapper {

	class SomeDto {

		public String foo;
		public String bar;
	}

	class SomeEntity {

		public String foo;
		public String bar;
	}

	@Mapping(target = "bar", expression = "java(magic(entity.bar))")
	SomeDto toDto(SomeEntity entity);

	default String magic(String input) {
		return input.toUpperCase();
	}
}
```

In the above code, the intent of the author was to apply some magic on the value of the "bar" field. Field "foo" has an implicit mapping added by MapStruct. The "problem" is that MapStruct resolves magic() as a mapping method and also applies it when mapping the "foo" field:

```java
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-10-25T12:38:35+0200",
    comments = "version: 1.3.0.Final, compiler: Eclipse JDT (IDE) 3.16.0.xx-201812291959-e2018-12-RELEASE, environment: Java 11.0.1 (Oracle Corporation)"
)
public class SomeMapperImpl implements SomeMapper {

    @Override
    public SomeDto toDto(SomeEntity entity) {
        if ( entity == null ) {
            return null;
        }

        SomeDto someDto = new SomeDto();

        someDto.foo = magic( entity.foo );

        someDto.bar = magic(entity.bar);

        return someDto;
    }
}
```

Of course this is very convenient in most of the situations, but brakes to above use-case. I know currently two workarounds, neither of them is elegant:

- put the helper method to an inner interface:

```java
@Mapper
public interface SomeMapper {

	...

	@Mapping(target = "bar", expression = "java(Helpers.magic(entity.bar))")
	SomeDto toDto(SomeEntity entity);

	interface Helpers {

		static String magic(String input) {
			return input.toUpperCase();
		}
	}
}
```

- annotate the method with `@Named("...")`:

```java
@Mapper
public interface SomeMapper {

	...

	@Mapping(target = "bar", expression = "java(magic(entity.bar))")
	SomeDto toDto(SomeEntity entity);

	@Named("workaround")
	default String magic(String input) {
		return input.toUpperCase();
	}
}
```

**My proposal would be to introduce a new configuration field called** `mappingMethodResolution`:

```java
/**
 * Configures how mapping method resolution works.
 */
public enum MappingMethodResolution {

	/**
	 * Mapping methods defined in mapper interfaces / abstract classes are
	 * discovered automatically based on their argument and return types.
	 * <p>
	 * A method can be ignored by using the {@link NonMappingMethod} annotation, which
	 * cannot be put on methods implemented by the MapStruct annotation processor.
	 */
	AUTOMATIC,

	/**
	 * Mapping methods are only discovered if they are explicitly annotated with the
	 * {@link MappingMethod} annotation.
	 * <p>
	 * This restriction does not apply for mapping methods generated by MapStruct.
	 */
	MANUAL
}

/**
 * Ignores a method from usage as mapping method for mapping method resolution. Only useful
 * if mapping method resolution is set to {@link MappingMethodResolution#AUTOMATIC}.
 * <p>
 * Cannot be put on methods implemented by the MapStruct annotation processor.
 */
@Retention(CLASS)
@Target(METHOD)
public @interface NonMappingMethod {}

/**
 * Annotates a method eligible for mapping method resolution. Only useful if mapping method
 * resolution is set to {@link MappingMethodResolution#MANUAL}.
 * <p>
 * Cannot be put on methods implemented by the MapStruct annotation processor.
 */
@Retention(CLASS)
@Target(METHOD)
public @interface MappingMethod {}
```

Which could be defined per-mapper class or inherited from `@MapperConfig` (defaults to `AUTOMATIC` to preserve backwards compatibility):

```java
@Mapper(mappingMethodResolution = MappingMethodResolution.MANUAL)
@MapperConfig(mappingMethodResolution = MappingMethodResolution.MANUAL)
```

With the above features, a fix for the initial problem would be either:

```java
@Mapper
public interface SomeMapper {

	class SomeDto {

		public String foo;
		public String bar;
	}

	class SomeEntity {

		public String foo;
		public String bar;
	}

	@Mapping(target = "bar", expression = "java(magic(entity.bar))")
	SomeDto toDto(SomeEntity entity);

	@NonMappingMethod
	default String magic(String input) {
		return input.toUpperCase();
	}
}
```

or:

```java
@Mapper(mappingMethodResolution = MappingMethodResolution.MANUAL)
public interface SomeMapper {

	class SomeDto {

		public String foo;
		public String bar;
	}

	class SomeEntity {

		public String foo;
		public String bar;
	}

	@Mapping(target = "bar", expression = "java(magic(entity.bar))")
	SomeDto toDto(SomeEntity entity);

	default String magic(String input) {
		return input.toUpperCase();
	}
}
```

What do you think about this? I'd be happy to contribute if you like the idea.

**Comment by sjaakd** [comment]
I was thinking to have a more granular control what mapstruct does.. selecting methods is one thing, but we also have type conversion en combinations of both.. all in all three are 8 combinations / options possible. There's also the desire to have deep cloning, which is also related to this.

By the way: I come around undesired method selection by putting a DoNotSelect qualifier in the method.. I guess I could document that in our FAQ .

**Comment by chris922** [comment]
> By the way: I come around undesired method selection by putting a DoNotSelect qualifier in the method.. I guess I could document that in our FAQ .

Great idea! So you can create your `@NonMappingMethod` annotation yourself.. Just "abuse" the qualifier functionality as documented here https://mapstruct.org/documentation/stable/reference/html/#selection-based-on-qualifiers (see example 40)

@imeszaros : Could you please give it a try and report back if this is working sufficient for you? 

Nevertheless you often notice that a method was mistakenly selected just because the mapper does some undesired stuff. So it could easily be overseen. Therefore I like to rethink the automatic selection of methods. Having a more granular control over this would be great and maaaybe we could even change the default behavior in 2.0.. 

On the one hand side I love this feature because you can spin up mappings really fast without the need to always specify what "sub-mapping" method should be chosen on the other hand side it could lead to unforeseen behavior that may lead to bugs.

**Comment by imeszaros** [comment]
The custom qualifier annotation is indeed a very good idea. Though it's still a workaround, it's a much more elegant than ones I mentioned.

On the long run however I would prefer MapStruct to support this out of the box.

**Comment by sjaakd** [comment]
I think that the answer of #695 covers a similar approach of having a possibility to switch on/off certain type of mappings.. I just should find the time to implement it :smile: . If you don't mind, I'll proceed to close this issue. Let me know if I missed something.

**Comment by djechelon** [comment]
@sjaakd I wish you could kindly reopen the issue or provide additional explanation. I am facing the exact issue but haven't understood how #695 helps

Can anyone provide a working example?

**Comment by djechelon** [comment]
Fixed by annotating `@Named` on method to disable.

Working example:

```
@Mapper
public interface SomeMapper {

	class SomeDto {

		public String foo;
		public String bar;
	}

	class SomeEntity {

		public String foo;
		public String bar;
	}

	@Mapping(target = "bar", qualifiedByName = "magic")
	SomeDto toDto(SomeEntity entity);

        @Named("magic")
	default String magic(String input) {
		return input.toUpperCase();
	}
}
```
