### ISSUE TITLE
Mapper Implementations not being generating during Maven install

### ISSUE THREAD

**Issue by chadmalla-ff** [mapstruct/mapstruct#1964]
- [Yes] Is this an issue (and hence not a question)? 

So I have looked at the docs and the `mapstruct-lombok` example and wrote my `pom` file the way it suggested. 

```xml
<dependency>
    <groupId>org.mapstruct</groupId>
   <artifactId>mapstruct</artifactId>
   <version>${mapstruct.version}</version>
</dependency>
<dependency>
     <groupId>org.projectlombok</groupId>
     <artifactId>lombok</artifactId>
     <version>${projectlombok.version}</version>
     <scope>provided</scope>
</dependency>
...
<build>
   <pluginManagement>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${maven-compiler-plugin.version}</version>
            <configuration combine.self="override">
               <source>${maven.compiler.source}</source>
               <target>${maven.compiler.target}</target>
               <release>${java.version}</release>
                <annotationProcessorPaths>
                 <path>
                   <groupId>org.mapstruct</groupId>
                   <artifactId>mapstruct-processor</artifactId>
                   <version>${mapstruct.version}</version>
                  </path>
                  <path>
                     <groupId>org.projectlombok</groupId>
                     <artifactId>lombok</artifactId>
                     <version>${projectlombok.version}</version>
                  </path>
                </annotationProcessorPaths>
             </configuration>
         </plugin>
    </pluginManagement>
</build>
```

When I do `mvn clean` then `mvn install` my unit tests that use my mappers during the `test` phase fail because they can't find the implementations for the mappers. But I can go to the unit test and run the test through `Intellij` and the tests pass as well as the mapper implementations get generated into `generated-resources`. Now if I go to `mvn test` then my unit tests will pass. 

This really puzzles me as this is the same configuration that is in the example and I am able to run that example using `mvn install` and it passes the test successfully. 

Can anyone please help me out on this?

Thanks!

BTW, these are the versions:

```pom
<maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
<mapstruct.version>1.3.1.Final</mapstruct.version>
<projectlombok.version>1.18.8</projectlombok.version>
Java 11
```

**Comment by chadmalla-ff** [comment]
Okay so I just tried the `mapstruct lombok` example with `Java version 11` and it doesn't work. So is `mapstruct` limited to `Java 9` ?

**Comment by chadmalla-ff** [comment]
I have it fixed now. I had to add the `processor` as a dependency and have it in the `annotatorPath`. Should the docs be updated for that? Anyways, closing for now.

**Comment by twilks18** [comment]
Could you show an example please?
