### ISSUE TITLE
Where to place META-INF/services/org.mapstruct.ap.spi.BuilderProvider

### ISSUE THREAD

**Issue by smac89** [mapstruct/mapstruct#1972]
```kotlin
/**
 * A [org.mapstruct.ap.spi.BuilderProvider] implementation which ignores
 * test builder methods
 */
class BuilderProviderWithTestBuilderAware: DefaultBuilderProvider() {
    override fun isPossibleBuilderCreationMethod(method: ExecutableElement, typeElement: TypeElement): Boolean {
        return !method.simpleName.contains(TEST_BUILDER_PATTERN) &&
               super.isPossibleBuilderCreationMethod(method, typeElement)
    }

    companion object {
        private val TEST_BUILDER_PATTERN = Regex("forTests?$", RegexOption.IGNORE_CASE)
    }
}
```

I am trying to use a custom `BuilderProvider` so that I can ignore certain builder methods and thus not have to deal with `MoreThanOneBuilderCreationMethodException` error. The above class is in a different gradle project, and I have a dependency on it. However, I am finding that mapstruct is ignoring the entry in my `META-INF/services/org.mapstruct.ap.spi.BuilderProvider`.
I have also tried just putting `org.mapstruct.ap.spi.NoOpBuilderProvider` in that file, but this does not seem to affect mapstruct.

What I am trying to understand is, where do I place the `META-INF/services/org.mapstruct.ap.spi.BuilderProvider` file so that mapstruct is able to see and use it?

**Comment by sjaakd** [comment]
In my experience you need to put it in a dependent jar. Checkout the [example](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-spi-accessor-naming) on the SPI interface.
