### ISSUE TITLE
Poor performance with  Kotlin classes

### ISSUE THREAD

**Issue by eiswind** [mapstruct/mapstruct#1976]
I see very very poor performance when mapping java to kotlin classes.
The model is around 500classes and we have quite a bunch of predefined mappings.
Generating the mapper takes around *40minutes* on a i78559U.

One guess I have is it may be the constructors from the Kotlin side?

Any ideas what I can do to improve this?

Just to give an example:

```
open class OAddresseeIdentifier (   
    @get:NotNull  
    var addresseeIDType : List44 = List44.C01 ,   
    var idTypeName : String? = null ,
    @get:NotNull  
    var idValue : String = "" 
)

@XmlRootElement(name = "AddresseeIdentifier")
public class AddresseeIdentifier {

    @XmlElement(name = "AddresseeIDType", required = true)
    protected AddresseeIDType addresseeIDType;
    @XmlElement(name = "IDTypeName")
    protected IDTypeName idTypeName;
    @XmlElement(name = "IDValue", required = true)
    protected IDValue idValue;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected SourceTypeCode sourcetype;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;
   // getters/setters

// manual mappings added in external class
 public AddresseeIDType mapAddresseeIDType(List44 o){
        if(o == null){
            return null;
        } 
        AddresseeIDType v = new AddresseeIDType();
        v.setValue(o);
        return v;
    }
    public List44 map(AddresseeIDType o){
        return o.getValue();
    }

**Comment by eiswind** [comment]
Is there any chance I can launch the generator with an agent attached? Then I could do a profiling session.

**Comment by filiphr** [comment]
40 minutes? That is slow no matter the CPU that you have.

Usually the number of classes doesn't really matter, but the number of methods that are there involved for a mapper.

Have you tried with different versions? For example 1.2 and 1.3?

As for profiling, I see that you found a way. I was trying to figure out how to do this. Would it be possible to share how yo did it?

**Comment by filiphr** [comment]
The function (`findCandidateBindingsForParameter`) that takes the most time is quite simple:

https://github.com/mapstruct/mapstruct/blob/071e5dc6b2ba2b03dcee4a85d7768eda6337e543/processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/TypeSelector.java#L291-L304

Looking at the code it seems like there are a lot of parameter bindings, which could be coming from the Kotlin constructors. I imagine that Kotilin creates multiple overloaded constructors for the properties.

**Comment by eiswind** [comment]
I tried with 1.2,1,3,1.3.1. It feels even slower with 1.3.1 then it has been with 1.2 but this is just what I remember.
I just attached a JProfiler to the running maven process. My project is not open source, but it's really small (everything gets generated from an xsd), so I can share it with you some other way if you'd like to see it.

And yes the Kotlin constructors are what I have been thinking of.

**Comment by filiphr** [comment]
Even 25 minutes is too slow. If you don't mind please share the project privately with me. You can find my email in the commits. I'd have a look at it and see if we can do something about it

**Comment by eiswind** [comment]
Its in your inbox.

**Comment by filiphr** [comment]
Yup I got it. I'll have a look at it over the weekend

**Comment by filiphr** [comment]
Had a look at the code. And to add some more context. From my current analysis the Kotlin classes are not the problem.

The accompanied code has a util class with a lot (700+ methods). The mapping has a lot of properties as well, and this leads to a lot of calls to `MappingResolver#getTargetAssignment`. This is done for every possible property in order to determine if there is a method for the mapping. This is also done for lists, and for properties for which automatic mapping would be generated (due to `MappingResolver#getTargetAssignment` returning `null`).

This leads to a lot of calls to:

* resolveViaMethod
* resolveViaMethodAndMethod
* resolveViaConversionAndMethod
* resolveViaMethodAndConversion 

And down that call tree the 2 hot spot methods are invoked a lot. Those methods are hot because they are invoked a lot of times, not because they are slow.

**Comment by sjaakd** [comment]
I guess we should make method resolving configurable.. there's already an issue for that. I'll prioritize this one..

**Comment by sjaakd** [comment]
@eiswind, @filiphr .. is this still an issue?

**Comment by filiphr** [comment]
We managed to reduce the number of methods to around ~100 with the use of `@TargetType` and some generics. Once we did that the compilation went down to 1 minute.

Not sure if it is worth adding some caching that could improve the performance

**Comment by sjaakd** [comment]
> We managed to reduce the number of methods to around ~100 with the use of `@TargetType` and some generics. Once we did that the compilation went down to 1 minute.
> 
> Not sure if it is worth adding some caching that could improve the performance

I am pretty confident that if we gave an option to switch 2 step resolving off, we'll gain a lot of performance. Remember, for each method in the used mapper change you try each other method.
