### ISSUE TITLE
Cannot inherit a custom mapping function for mapping a DTO to primitive

### ISSUE THREAD

**Issue by Norbo11** [mapstruct/mapstruct#1977]
I have a MapperConfig and a Mapper which inherits from that.

The docs state that any functions I declare in the MapperConfig will be used by inheriting mappers, if the types are assignable.

Here is the base mapper:

```kotlin
@MapperConfig(
  unmappedSourcePolicy = ReportingPolicy.IGNORE,
  unmappedTargetPolicy = ReportingPolicy.IGNORE,
  typeConversionPolicy = ReportingPolicy.ERROR,

  collectionMappingStrategy = CollectionMappingStrategy.SETTER_PREFERRED,
  mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG,
  nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
  nullValueMappingStrategy = NullValueMappingStrategy.RETURN_NULL,
  nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_NULL,

  implementationName = "Default<CLASS_NAME>",
  implementationPackage = "<PACKAGE_NAME>",

  componentModel = "jsr330" // Allows us to inject the implementations using Guice
)
public abstract class MapStructConfig {

  fun idToLong(id: Id): Long {
    return id.get()
  }
}
```

And here is the child mapper:

```kotlin
@Mapper(config = MapStructConfig::class)
public abstract class EntityMapper {

  companion object {
    val INSTANCE: EntityMapper = Mappers.getMapper(EntityMapper::class.java)
  }

  @Mappings(
    Mapping(source = "entity.legalName", target = "legalName"),
    Mapping(source = "entityId", target = "entityId")
  )
  abstract fun createNewEntityLogRecord(entityId: EntityId, entity: NewEntity): EntityLogRecord
}
```

The EntityId object implements the Id interface. So I would expect that when MapStruct wants to map an EntityId to a Long it will use the custom mapper declared in the MapStructConfig class. Instead I get the message:

`error: Can't generate mapping method with primitive return type.`

Using the `@InheritConfiguration` annotation does not help.

It only works if I move the `idToLong` function to the EntityMapper class.

**Comment by filiphr** [comment]
`@MappingConfig` is used to inherit configuration (i.e. ignore certain properties, provide default `@Mapping`, etc.), it is not meant for reusing methods for mapping.

In order to achieve what you are doing you should use `MapperConfig#uses` or `Mapper#uses` and put a util class there. So in your case:

```
@MapperConfig(
  uses = IdMappingUtil::class.java
  unmappedSourcePolicy = ReportingPolicy.IGNORE,
  unmappedTargetPolicy = ReportingPolicy.IGNORE,
  typeConversionPolicy = ReportingPolicy.ERROR,

  collectionMappingStrategy = CollectionMappingStrategy.SETTER_PREFERRED,
  mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG,
  nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
  nullValueMappingStrategy = NullValueMappingStrategy.RETURN_NULL,
  nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_NULL,

  implementationName = "Default<CLASS_NAME>",
  implementationPackage = "<PACKAGE_NAME>",

  componentModel = "jsr330" // Allows us to inject the implementations using Guice
)
public abstract class MapStructConfig {

  fun idToLong(id: Id): Long {
    return id.get()
  }
}

public class IdMappingUtil {

  public static Long idToLong(Id id) {
    return id.get();
  }
}
```

One other note, I see that you are using `Mappers.getMapper` with the `jsr330` component model. I would strongly advise doing this, since the generated mappers won't have the dependent mappers initialized. You should always use a dependency injection if you don't use the default component model.

Closing this since it is a question
