### ISSUE TITLE
MapStruct annotations as meta-annotations

### ISSUE THREAD

**Issue by Master-Killer** [mapstruct/mapstruct#1978]
Hello.
I think that it would be helpful to have the MapStruct annotations as meta-annotations.
In particular `Mapping`.
I have a use case like this:
I have a lot of similar classes, all with different class names but their fields have mostly the same name and types (for example when working with WSDL generated classes).
Most of the mappings from the same initial object to all those slightly different classes are going to be identical. 
In this case I believe that InheritConfiguration cannot be used because it looks for exact same input and output types.
But a meta-annotation would be very helpful to avoid mapping duplication.

**Comment by filiphr** [comment]
@Master-Killer thanks for opening the issue. 

We already have https://github.com/mapstruct/mapstruct/issues/807. I'd say that this is exactly the same as that one. Therefore, I am going to close this one in favour of #807
