### ISSUE TITLE
Support for avro builders

### ISSUE THREAD

**Issue by Rajh** [mapstruct/mapstruct#1981]
Hello,

I'm using mapstruct to map avro objects.
To prevent missing mapping I was using : unmappedTargetPolicy = ReportingPolicy.ERROR

I switched from 1.2.0.Final to 1.3.1.Final, and now I've got an error for a lot of field.

This seems to be caused by the fact that avro object has Builder and in those builder you can set the value directly or set a builder for the value.

Exemple :
```
@org.apache.avro.specific.AvroGenerated
public class ClassA ... {
    @Deprecated public ClassB classB;
    public static class Builder .... {
         public ClassA.Builder setClassB(ClassB value) { ... }
         public ClassA.Builder setClassBBuilder(ClassB.Builder builder) { ... }
    }
}

```

**Comment by sjaakd** [comment]
In 1.3.1 there's an option to disable the builder.

```java
@Mapper( builder = @Builder( disableBuilder = true )  ) {
...
}
```

Which would allow you to return to the old (1.2) situation.. Is that what you mean?

**Comment by Rajh** [comment]
Thanks it's working for switching, still it would be great to be able to use builder with avro.

**Comment by sjaakd** [comment]
> Thanks it's working for switching, still it would be great to be able to use builder with avro.

We have an extension mechanism by means of SPI.. Checkout the way other builder types are supported.  I'm not sure whether  we would take this up on the standard builders.. @filiphr .. WDYT?

In the mean time I'll close this issue. Thanks for your feedback
