### ISSUE TITLE
Allow missing targets on mapper prototypes

### ISSUE THREAD

**Issue by chrylis** [mapstruct/mapstruct#1985]
I'm writing a mapper prototype as described in section 11.3 of the documentation for updating database entities. I want the concrete mappers to always ignore some properties like `id` and `lastModified`, but my entities are top-level classes and don't inherit from a common `BaseEntity` parent.

Since this is a prototype method, I expected the `@Mapping` metadata to be stored but not acted on, and for the mappings to be applied to the concrete mapper. Instead, the annotation processor reports an error at the method declaration saying:

```
BaseMapperConfig.java:[31,24] Unknown property "lastModified" in result type org.springframework.hateoas.Identifiable<java.util.UUID>. Did you mean "id"?
```

There doesn't appear to be any way to tell MapStruct not to validate the presence of targets in a prototype, which should be at least an option if not the default.

Oddly enough, MapStruct _didn't_ complain about the fact that on the `Identifiable` interface, `id` is a read-only property.

I'm using MapStruct 1.3.1.Final.

**Comment by sjaakd** [comment]
Recently added: #1979 . It's up for the next release. Download our latest snapshot and give it a spin

**Comment by sjaakd** [comment]
@chrylis .. did you try?
