### ISSUE TITLE
Bug: Mapping doesn't catch IS prefix of boolean source

### ISSUE THREAD

**Issue by Vynnytska** [mapstruct/mapstruct#1990]
[BUG] 
There are **isChannel** as a **source**  and **isChannel** as a **target** fields for mapping.
When add: 
`@Mapping(target = "isChannel", source = "isChannel")`
get an error: 
>error: No property named "isChannel" exists in source parameter(s). Did you mean "channel"?
>
It works if write  
  `@Mapping(target = "isChannel", source = "channel")`

However, it is expected to be working with **isChannel**, which is a valid source name.

**Comment by sjaakd** [comment]
Have you checked #1943 ?
