### ISSUE TITLE
question: Is there anyway to ignore by default and set null to others?

### ISSUE THREAD

**Issue by ahyakamil** [mapstruct/mapstruct#1994]
I want to mapping entity to dto using @BeanMapping(ignoreByDefault = true) and @Mapping, its work great. But I need to set null to the others field that not defined on @Mapping, is there anyway to achieve this?

**Comment by sjaakd** [comment]
Try `@Mapping( target="x", constant="null" )`.. 

But please use SO or the other means to ask questions..
