### ISSUE TITLE
small mistakes in writing ：[mapstruct-reference-guid]

### ISSUE THREAD

**Issue by DerekDebug** [mapstruct/mapstruct#1995]
5. Data type conversions page: 26
Example  33. Referencing another mapper class

`@Mapper(uses=DateMapper.class)
public class CarMapper {
 CarDto carToCarDto(Car car);
}`

should be:

`@Mapper(uses=DateMapper.class)
public interface CarMapper {
 CarDto carToCarDto(Car car);
}`

APOLOGY to bother u guys for such a little thing

**Comment by sjaakd** [comment]
> APOLOGY to bother u guys for such a little thing

Not a problem.. will fix asap.

**Comment by sjaakd** [comment]
Thanks!

**Comment by sjaakd** [comment]
done! thanks for reporting
