### ISSUE TITLE
MapStruct does not always use builders in target-object

### ISSUE THREAD

**Issue by mfriess2** [mapstruct/mapstruct#1997]
Hi,

we try to use MapStruct with Lombok builders but MapStruct does **not always** seem to recognize and use the builders. Our particular problematic case is when the **target** object has a field which only has a builder.

Used MapStruct version: 1.3.1.FINAL
Used Lombok version: 1.18.10

It would be very helpful for us if you could let us know if this is considered a bug or not.
Looking forward to your feedback!

**Here is an example:**

Source POJO:
```
package example.model.source;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Car {
	private String model;
}
```

Target POJOs:
```
package example.model.target;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class CarInsurance {
	private CarDetail carDetail;   // this is the problematic case
}

@Data
@Builder
public class CarDetail {
	private String model;
}
```

Mapper:
```
package example.mapper;

import example.model.source.Car;
import example.model.target.CarInsurance;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper
public interface CarInsuranceMapper {
	@Mapping(source = "model", target = "carDetail.model")
	void map(Car source, @MappingTarget CarInsurance target);
}
```

MapStruct generates this mapper:
```
package example.mapper;

import example.model.source.Car;
import example.model.target.CarDetail;
import example.model.target.CarInsurance;
import javax.annotation.Generated;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor"
)
@Component
public class CarInsuranceMapperImpl implements CarInsuranceMapper {

    @Override
    public void map(Car source, CarInsurance target) {
        if ( source == null ) {
            return;
        }

        if ( target.getCarDetail() == null ) {
            target.setCarDetail( new CarDetail() );  // THIS CREATES A COMPILE ERROR
        }
        carToCarDetail( source, target.getCarDetail() );
    }

    protected void carToCarDetail(Car car, CarDetail mappingTarget) {
        if ( car == null ) {
            return;
        }

        mappingTarget.setModel( car.getModel() );
    }
}
```

And the compiler fails with:
```
CarInsuranceMapperImpl.java:22: error: constructor CarDetail in class CarDetail cannot be applied to given types;
            target.setCarDetail( new CarDetail() );

```

It would work if MapStruct would generate:
```
if ( target.getCarDetail() == null ) {
    target.setCarDetail( CarDetail.builder().build() );
}
```

The annotation processor ordering in the Gradle build:
```
	implementation 'org.mapstruct:mapstruct'
	implementation 'org.projectlombok:lombok'
	annotationProcessor 'org.mapstruct:mapstruct-processor'
	annotationProcessor 'org.projectlombok:lombok'
```

**Comment by filiphr** [comment]
@mfriess2 I think that this is the same as #1581 and is caused by rzwitserloot/lombok#1538.

**Comment by mfriess2** [comment]
Thanks for taking the time to answer but I'm also a bit sad that you closed this issue so fast.

1 ) I **am** using the proposed solution from #1581 : lombok **is after** mapstruct (written in the gradle file; I think at execution time it is run reversed: first lombok then mapstruct)

To be double-sure, I tried out:
```
annotationProcessor 'org.mapstruct:mapstruct-processor', 'org.projectlombok:lombok'
```
similar to your example https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-lombok/build.gradle (but I am using the newer "annotationProcessor" instead of "apt")

2 ) but most important: I de-lomboked the class "CarDetail" just to take Lombok out of the equation and the problem stays the same: the builder is not recognized/used by mapstruct and an uncompilable Mapper is generated

Here is the non-lombok class which provokes the same error:

```
package example.model.to;

public class CarDetail {
	private String model;

	private CarDetail(String model) {
		this.model = model;
	}

	public static CarDetailBuilder builder() {
		return new CarDetailBuilder();
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public static class CarDetailBuilder {
		private String model;

		CarDetailBuilder() {
		}

		public CarDetail.CarDetailBuilder model(String model) {
			this.model = model;
			return this;
		}

		public CarDetail build() {
			return new CarDetail(model);
		}

		public String toString() {
			return "CarDetail.CarDetailBuilder(model=" + this.model + ")";
		}
	}
}
```

**Comment by filiphr** [comment]
Sorry I didn't see that you are using update mapping. In this case we can't use the builder and we would use the setters only.

I understand the problem now. Can you try with 1.4.0-SNAPSHOT? I think that there was a similar problem and we have fixed it on master.

**Comment by mfriess2** [comment]
Thanks & sure. Can you give me a hint how to get the 1.4.0-SNAPSHOT? Do I have to clone and build the master or is it available for download somewhere? I could not find anything promising with Google.

**Comment by mfriess2** [comment]
I tried it out with 076f3ba839f0872b4d431e5f471a2bc83023dcae and unfortunately it did not work.
I uploaded the full example to: https://github.com/mfriess2/mapstruct-issue-1997

**Comment by drenda** [comment]
@filiphr Could my question [here ](https://stackoverflow.com/questions/61524229/mapstruct-different-implementations-mvn-install-vs-run) be related to this issue? Any possible workaround? Thanks

**Comment by cedricwalter** [comment]
I can confirm the issue is still in version 1.4.1.Final

Any workaround?

**Comment by aalnaw2s** [comment]
I am also confirming the same bug with the last version 1.4.1.Final.
the proposed solutions above are not working.

**Comment by aalnaw2s** [comment]
I can confirm it is working right with the version 1.4.1.Final. ( with the following configuration from StackOverflow thread ...)

<plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct-processor.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId> lombok-mapstruct-binding</artifactId>
                            <version>0.1.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

**Comment by thunderhook** [comment]
@filiphr I can confirm that the problem starts appearing with lombok `1.18.14`.

To reproduce this, adapt the [`mapstruct-lombok` module in `mapstruct-examples`](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok) the following way:
Add `@Builder` on class `Target` and build the module. You will see that the mapper uses the builder.

Now, set `<org.projectlombok.version>` to `1.18.14` and rebuild the module. I have see randomly two issues
- `java: No property named "test" exists in source parameter(s). Did you mean "null"?` ... that alone may be a symptom that mapstruct can't read the source property from a `@Data` annotated class
- the mapper tries to use a no-arg-constructor and does not use the builder

I hope this helps investigating the underlying problem.

BTW: `lombok-mapstruct-binding` did not solve the problem, neither as dependency, nor as annotation processor path.

**Comment by filiphr** [comment]
@thunderhook is the problem there with 1.18.16? According to the Lombok changelog 1.18.14 is broken and shouldn't be used

**Comment by thunderhook** [comment]
Ah sorry, yes, this is reproducable with 1.18.16 as well.

**Comment by aalnaw2s** [comment]
i am using mapstruct ( 1.4.1.Final ) , with lombok (1.18.16). having entities annotated just with @Data then @Builder
with the mapstruct-processor, lombok and the lombok-mapstruct-binding configured in the maven compiler plugin within
annotationProcessorPaths ; and everything is working right. the generated classes is using the builder to create
 mapped entities

**Comment by filiphr** [comment]
@thunderhook are you by any chance using Java 8 to do the compilation?

`lombok-mapstruct-binding` does not work on Java 8 have a look at https://github.com/rzwitserloot/lombok/issues/2616. We have an open PR (https://github.com/mapstruct/mapstruct-examples/pull/111) to update our examples to use the latest Lombok and the CI is green for Java 9+

**Comment by thunderhook** [comment]
> @thunderhook are you by any chance using Java 8 to do the compilation?
> 
> `lombok-mapstruct-binding` does not work on Java 8 have a look at [rzwitserloot/lombok#2616](https://github.com/rzwitserloot/lombok/issues/2616). We have an open PR ([mapstruct/mapstruct-examples#111](https://github.com/mapstruct/mapstruct-examples/pull/111)) to update our examples to use the latest Lombok and the CI is green for Java 9+

Thanks for clarification. Yes I am using Java 8. You are right, choosing a higher Java version works at least with maven.

Changing to 9 (or 11, or 15, that's what i've tried) also shows `java: No property named "test" exists in source parameter(s). Did you mean "null"?` **but only in IntelliJ**.

From my own test-project using Java 15 this is also reproducable (that was easier than adapting the mapstruct-examples project).

with something like 

```java
@Builder
@Value
public class CustomerDTO {

    int customerNumber;
    String name;
}
```

**IntelliJ generated mapper:**
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-11-21T17:47:56+0100",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 15.0.1 (Oracle Corporation)"
)
public class CustomerMapperImpl implements CustomerMapper {

    @Override
    public CustomerDTO map(CustomerEntity source) {
        if ( source == null ) {
            return null;
        }

        CustomerDTO customerDTO = new CustomerDTO();
        // <- compile error java: constructor CustomerDTO in class bug.mapstruct.CustomerDTO cannot be applied to given types;
        //    required: int,java.lang.String
        //    found:    no arguments

        return customerDTO;
    }
}
```

**Maven generated mapper:**

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-11-21T17:51:38+0100",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 15.0.1 (Oracle Corporation)"
)
public class CustomerMapperImpl implements CustomerMapper {

    @Override
    public CustomerDTO map(CustomerEntity source) {
        if ( source == null ) {
            return null;
        }

        CustomerDTOBuilder customerDTO = CustomerDTO.builder();

        customerDTO.customerNumber( (int) source.getCustomerNumber() );
        customerDTO.name( source.getName() );

        return customerDTO.build();
    }
}
```

If I can provide any more info (mvn/idea log), or if this should be an own ticket, please let me know!

**Comment by hongji3354** [comment]
Hi.
Mapping code is treated as a constructor only when using @builder in lombok.

Just in case, the builder is used normally when testing after writing the builder pattern.

The dependencies I currently use are as follows.
lombok 1.18.16, mapStruct 1.14.Final

```
dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.16'
    annotationProcessor 'org.projectlombok:lombok:1.18.16'
    compileOnly 'org.mapstruct:mapstruct:1.4.1.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.1.Final'
}
```

The mapper file is defined as follows and you want to map CarDto to Car.

```
@Mapper
public interface CarMapper {

    Car carDtoToCar(CarDto carDto);
}
```

Car only uses Builder.

```
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
public class Car {

    @Id
    private String vehicleIdentificationNumber;
    private String manufacturer;
    private String color;
    private int numberOfSeat;

    @Builder
    public Car(String vehicleIdentificationNumber, String manufacturer, String color, int numberOfSeat) {
        this.vehicleIdentificationNumber = vehicleIdentificationNumber;
        this.manufacturer = manufacturer;
        this.color = color;
        this.numberOfSeat = numberOfSeat;
    }
}
```

The actual mapped code uses a non-builder constructor as shown below.

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-01-03T22:26:56+0900",
    comments = "version: 1.4.1.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-6.7.1.jar, environment: Java 11.0.9 (AdoptOpenJDK)"
)
@Component
public class CarMapperImpl implements CarMapper {

    @Override
    public Car carDtoToCar(CarDto carDto) {
        if ( carDto == null ) {
            return null;
        }

        String manufacturer = null;
        String color = null;
        int numberOfSeat = 0;

        manufacturer = carDto.getManufacturer();
        color = carDto.getColor();
        numberOfSeat = carDto.getNumberOfSeat();

        String vehicleIdentificationNumber = null;

        Car car = new Car( vehicleIdentificationNumber, manufacturer, color, numberOfSeat );

        return car;
    }
}
```

**Comment by metao1** [comment]
I still have this problem

Model:

```
@Value
@Builder
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class Student {
    String name;
    int id;
}
``````
Mapper Class:

``````
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.WARN)
public interface DTOMapper {
    Student map(Student student);
}
```
```

 error: LogConfigDTO does not have an accessible constructor.
    LogConfigDTO mapLogConfigToDTO(ConfigModel configModel);
                 ^
```

**Comment by filiphr** [comment]
@metao1 seems like you have cross posted this here and in the Lombok issue tracker https://github.com/rzwitserloot/lombok/issues/2804. MapStruct by default uses builders (if it can see them), see https://github.com/rzwitserloot/lombok/issues/1538 for more information

**Comment by FARHANE** [comment]
Same problem
java 15
lombok 1.18.20
mapstruct 1.4.2.Final
`
 <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok-mapstruct-binding</artifactId>
              <version>${lombok-mapstruct-binding.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${org.mapstruct.version}</version>
            </path>
          </annotationProcessorPaths>

        </configuration>
      </plugin>
    </plugins>
  </build>
`

`
@Value
@Builder(toBuilder = true)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Jacksonized
public class MyClass implements MyInterface{

}
`
