### ISSUE TITLE
Mapstruct multiple source null pointer exception

### ISSUE THREAD

**Issue by Pragat** [mapstruct/mapstruct#2004]
Trying to mapped the multiple sources to single target object.
Everything works fine, except for java expression null check is not available.

Wherever there is java expression, nested object throwing null pointer exception.

**Comment by filiphr** [comment]
@Pragat can you provide an example?

When using expressions there is no null check happening. The expression is used as is, without any null checks

**Comment by filiphr** [comment]
Closing due to lack of feedback. If more feedback is provided are going to reopen the issue
