### ISSUE TITLE
Only one of multiple @AfterMapping methods is executed

### ISSUE THREAD

**Issue by ckosmowski** [mapstruct/mapstruct#2006]
- [X] Is this an issue

**Steps to reproduce:**
- Create a simple bean mapper
- Add at least two custom methods each with the same return type and parameters (including MappingTarget)
- Annotate them with @AfterMapping

**Current Behaviour**
- Only one of the above methods is executed when the mapping method runs
- No waring or error is raised during compile time
- The generated code contains one return statement for each of the generated afterMapping segments so after the first one, the mapping methods returns

**Expected Behaviour**
- Either raise a warning / error at compile time that the above scenario is not supported or:
- Only add a return statement to the last afterMapping method block generated in the mapper

I would really like to contribute to the project and fix this issue and i am new to annotation processing.

I guess that the issue can be solved around here:

https://github.com/mapstruct/mapstruct/blob/076f3ba839f0872b4d431e5f471a2bc83023dcae/processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl#L64-L69

But i wasn't able to figure out what exactly the @includeModel directive does or especially where to find the code that actually generates the code for the AfterMapping method.

If someone could point me to that place i will try my best to file a merge request

**Comment by filiphr** [comment]
Thanks for raising this @ckosmowski.

This works as designed and is also written in our documentation [Mapping customization with before-mapping and after-mapping methods](https://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after). This particularly was done to implement the solution for cyclic mappings.

Why do you have multiple after mappings that return an object?

**Comment by ckosmowski** [comment]
We tried to use multiple after mappings just for a better overview. However it is easy to have one after mapping method and split the needed steps in nested methods.

What i do not like about this, is that if you use multiple after mappings for whatever reason that there is no warning at all but only one single method will be called in the mapping process and you will first notice in debugging.

Or is this actually the wanted behaviour?

**Comment by qannoufoualid** [comment]
Nested methods resolve the issue.
Should the issue open ?

**Comment by chhavish** [comment]
@ckosmowski Did you have multiple @MappingTarget in @AfterMapping method?

**Comment by filiphr** [comment]
Seems like I forgot to respond this.

>What i do not like about this, is that if you use multiple after mappings for whatever reason that there is no warning at all >but only one single method will be called in the mapping process and you will first notice in debugging.
>
>Or is this actually the wanted behaviour?

Yes this is the wanted behaviour. Otherwise, cyclic mapping cannot work.
