### ISSUE TITLE
Unable to generate the implementation files for Mapper class.

### ISSUE THREAD

**Issue by Ruch12** [mapstruct/mapstruct#2009]
Is there any way apart from setting all those intellij dependencies . I need to deploy my changes for which I need to use mapstruct but there is only one runtime Exception being thrown that the class is not found.  I have to inject the bean in one class. All this is being done in kotlin.

**Comment by filiphr** [comment]
What do you mean with setting all those IntelliJ dependencies?

MapStruct is an annotation processor. All you need to do is to make sure that the processor is present during compilation.

Can you provide an example of what is not working?

**Comment by filiphr** [comment]
Closing due to lack of feedback. If more feedback is provided we will reopen the issue
