### ISSUE TITLE
Introduce gem as replacement of hickory:prism

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#2011]
hickory:prism is no longer maintained, but is a useful framework to handle annotations in an annotation processor such as MapStruct. Hence, a tool has  been created to replace hickory on the MapStruct organisation: org.mapstruct.tools.gem. This issue handles the introduction of this tool.

**Comment by filiphr** [comment]
For traceability, the tool is located at https://github.com/mapstruct/tools-gem

**Comment by gunnarmorling** [comment]
Ha, that's interesting. Is gem derived from Hickory, or is it a complete
new implementation? Nice job in any case!

>

**Comment by sjaakd** [comment]
> Ha, that's interesting. Is gem derived from Hickory, or is it a complete new implementation? Nice job in any case!

Its a new implementation.. We optimised stuff, but it derives its ideas from Hickory ..

**Comment by gunnarmorling** [comment]
Really cool! Perhaps do a quick blog post about it? It's quite a niche
topic for sure, but still might find its readers :)

**Comment by sjaakd** [comment]
I believe that @filiphr was going to write something :smile: .. But I'll help out of course

**Comment by sjaakd** [comment]
(I'm not a good blogger)...

**Comment by gunnarmorling** [comment]
Haha, I was waiting for you to say this ;)

>

**Comment by sjaakd** [comment]
> Haha, I was waiting for you to say this ;)

becoming predictable..

**Comment by filiphr** [comment]
Yup I was about to write something this weekend. 

Prepared a blog post https://github.com/filiphr/mapstruct.org/commit/ad70799b88bb749c5d3de8eaa85f54235ba327cd. Let me know what you think
