### ISSUE TITLE
Wrong decorator class name used when Decorator class is nested inside mapper interface

### ISSUE THREAD

**Issue by xak2000** [mapstruct/mapstruct#2021]
Example:

```java
@Mapper
@DecoratedWith(MyMapper.Decorator.class)
public interface MyMapper {
    abstract class Decorator implements MyMapper {}
}
```

Generated implementation example:

```java
public class MyMapperImpl extends Decorator implements MyMapper {
...
}
```

Here class `Decorator` is not imported and not qualified by it's outer class name (like `MyMapper.Decorator`), so implementation just doesn't compile.

The right implementation should be:

```java
public class MyMapperImpl extends MyMapper.Decorator implements MyMapper {
...
}
```

**Comment by filiphr** [comment]
Thanks for the bug report @xak2000.

We'll fix this for the next release. In the meantime you can move out the decorator from your class to a top level location. That should work
