### ISSUE TITLE
Multiple source properties with defaultExpression lead to unnecessary null checks and unexpected code

### ISSUE THREAD

**Issue by turing85** [mapstruct/mapstruct#2023]
- [✓] Is this an issue (and hence not a question)? 

This mapper definition:
```
package com.turing;

import java.util.UUID;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
public interface PersonDtoMapper {
  @Mapping(
      source = "correlationId",
      target = "correlationId",
      defaultExpression = "java(UUID.randomUUID())")
  CreateNewPersonRequest toRequest(final PersonDto person, final UUID correlationId);
}
```
Leads to the following mapper being generated:
```
package com.turing;

import com.turing.CreateNewPersonRequest.Builder;
import java.util.UUID;
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-02-06T20:16:29+0100",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 13 (AdoptOpenJDK)"
)
public class PersonDtoMapperImpl implements PersonDtoMapper {

    @Override
    public CreateNewPersonRequest toRequest(PersonDto person, UUID correlationId) {
        [...]
        if ( correlationId != null ) {
            if ( correlationId != null ) {
                createNewPersonRequest.setCorrelationId( correlationId );
            }
            else {
                createNewPersonRequest.setCorrelationId( UUID.randomUUID() );
            }
        }

        return createNewPersonRequest.build();
    }
}
```
There is a double `null`-check on `correlationId`. What is worse is that the `else` of the inner `if` can never be reached.

---
Expected behaviour:
The outer `if`-block should be absent:
```
package com.turing;

import com.turing.CreateNewPersonRequest.Builder;
import java.util.UUID;
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-02-06T20:16:29+0100",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 13 (AdoptOpenJDK)"
)
public class PersonDtoMapperImpl implements PersonDtoMapper {

    @Override
    public CreateNewPersonRequest toRequest(PersonDto person, UUID correlationId) {
        [...]
        if ( correlationId != null ) {
            createNewPersonRequest.setCorrelationId( correlationId );
        }
        else {
            createNewPersonRequest.setCorrelationId( UUID.randomUUID() );
        }

        return createNewPersonRequest.build();
    }
}
```
---
The full code to reproduce this behaviour can be found on [GitHub][GitHub].

[GitHub]: https://github.com/turing85/mapstruct-bug

**Comment by filiphr** [comment]
Thanks for the reproducal @turing85.

This one is a tricky one. Currently we are applying the `defaultExpression` in the property mappings. When using multiple source parameters we explicitly check for nullability before continuing to map them. This makes sense for object mappings when both source parameters have properties.

I can understand why this doesn't make sense for your use case. We should probably treat mappings like your specially in the multi source parameters case.

As a current workaround you can wrap the correlation id in an object. For example:

```
public class CorrelationIdProvider {

    private final UUID correlationId
    private CorrelationIdProvider(UUID uuid);

}
```

**Comment by filiphr** [comment]
I closed the issue by mistake and also posted a comment which was not complete. I edited the comment and reopened the issue.

**Comment by filiphr** [comment]
Btw can we use the code you linked as a test case?

**Comment by turing85** [comment]
@filiphr of course =) feel free!

**Comment by fml2** [comment]
May I add something to the mix? I noticed something that is related to this issue.

Say, I have these two classes:

    class Person {
        Address address;
    }

    class PersonDto {
        Address address;
    }

And then I create the mapping as follows:

    @Mapper
    public interface PersonDtoMapper {
      @Mapping(
          // Note that the source attribute is not set because the source field has the same name
          target = "address",
          defaultExpression = "java(new Address())")
      PartnerDto toDto(Person person);
    }

The result of the generation is weird. The method for mapping of address starts with

        if ( address == null ) {
            return null;
        }

I'd expect that if the value of the source property (i.e. the source address) is NULL then the default expression is used.

If I specify the source property in the mapping (source="address") then the result is as expected. But since the source and target fields have the same name, it should not be necessary to specify the name of the source field.

**Comment by ntinnemeier** [comment]
I also stumbled upon this same problem. I found the following two work-arounds for this issue. For the first workaround I resort to using an expression, instead of a default expression:
```
  @Mapping(
      source = "correlationId",
      target = "correlationId",
      expression = "java(mapCorrelationId(correlationId)")
  CreateNewPersonRequest toRequest(final PersonDto person, final UUID correlationId);

    default UUID map(final UUID correlationId) {
        return correlationId != null? correlationId : UUID.randomUUID();
    }
```

The second workaround boils down to using the after mapping construct, for this case something like:

```
@AfterMapping
default CreateNewPersonRequest afterMap(@MappingTarget CreateNewPersonRequest t) {
    if (t.getCorrelationId() == null) {
        t.setCorrelationId(UUID.randomUUID());
    }
    return t;
}

@Mapping(
      source = "correlationId",
      target = "correlationId")
CreateNewPersonRequest toRequest(final PersonDto person, final UUID correlationId);
```

Hope it helps.
