### ISSUE TITLE
Eclipse 2019-12 - incremental compilation fails with APT

### ISSUE THREAD

**Issue by hocine68** [mapstruct/mapstruct#2025]
**Each time there is a change in any of a mapped class or a mapping interface the interface gets error marker** 

This seems related to ecj compiler since we have the same issue with intellij when using ecj compiler instead of the javac compiler.
**This issue is really annoying since we have to rebuild the whole project each time that we have a new mapping with mapstruct.**
We're using Eclipse 2019-12 and Mapstruct 1.3.1.Final.
(Same issue as #43 and #45)
See the stack trace below that appears when there is a change in a mapping :

Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Source file already exists : test.mapstruct.TestMapperImpl at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:71) at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:52) at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:42) at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:37) at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280) at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260) at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226) at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162) at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142) at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124) at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:174) at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138) at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940) at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450) at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426) at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386) at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:371) at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318) at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:186) at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:143) at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:281) at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:202) at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263) at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319) at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371) at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392) at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154) at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) Caused by: javax.annotation.processing.FilerException: Source file already exists : test.mapstruct.TestMapperImpl at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.createSourceFile(IdeFilerImpl.java:177) at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:68) ... 33 more

**Comment by filiphr** [comment]
I've been looking into this and I could easily reproduce it with IntelliJ and the Eclipse compiler, with maven and the eclipse compiler.

However, if I use jdt (also from eclipse) it is working fine.

Have you followed the [Eclipse Maven Integration](https://mapstruct.org/documentation/ide-support/#maven-integration) from our website?

Do you have

```
<m2e.apt.activation>jdt_apt</m2e.apt.activation>
```

in your poms? and do you have the [m2e-apt](https://marketplace.eclipse.org/content/m2e-apt) plugin installed?

**Comment by hocine68** [comment]
Hi Filiphr,
we don't use maven, just the mapstruct library.
We had to stop using mapstruct because of this issue.
I'd like to use it again but this issue should be solved.
We can not allow the rebuild of the complete project each time we have a new mapping.
Please look into it.
Thanks

**Comment by filiphr** [comment]
I am sorry that this caused you to stop using MapStruct. However, if you are not using Maven or Gradle then you should configure the JDT APT manually. I am not an Eclipse user myself so I can't really help a lot. How does your Java Compiler -> Annotation Processing look like.

Is your project properly setup with generated sources directory and the likes.

I don't think that there is anything that we can do about this.

**Comment by filiphr** [comment]
Closing because I think that there is nothing that we can do about this. When using Eclipse the jdt_apt incremental should be used in order for the compilation to work properly
