### ISSUE TITLE
Improve builder to allow to build from super class object

### ISSUE THREAD

**Issue by TehBakker** [mapstruct/mapstruct#2029]
Would be great to be able to instantiate a builder from super class Object.

I've my class like this for now

```
@Getter
@Setter
@SuperBuilder
@EqualsAndHashCode
@ToString
public class PetData {
    private String name;
}
```

```
@Getter
@Setter
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DogData extends PetData {
    private String dogRace;
}
```

If I've an object Pet that is alrady built, I would like to be able to initiate a Dog builder from that Pet object

```
private Dog buildDogFromPet(Pet myPet) {
   return  Dog.builder(myPet).dogRace("Auggie").build();
}
```

Or through a "super" setter.

**Comment by filiphr** [comment]
@TehBakker can you please share some examples with MapStruct about this?

I am not familiar with the `@SuperBuilder` from Lombok, so would need some more examples about it? What is currently not possible to be done?

**Comment by TehBakker** [comment]
@filiphr thanks for the quick response.
To be honest, not sure how i messed this up, this was supposed to go on lombok not on mapstruct ...

Sorry for wasting your time

**Comment by filiphr** [comment]
No problem, it happens 😄.
