### ISSUE TITLE
Incremental annotation android

### ISSUE THREAD

**Issue by jrcacd** [mapstruct/mapstruct#2032]
Incremental annotation processing requested, but support is disabled because the following processors are not incremental: org.mapstruct.ap.MappingProcessor (NON_INCREMENTAL).

**Comment by filiphr** [comment]
With the next release (1.4) MapStruct would be an incremental processor according to Gradle's rules. See https://github.com/mapstruct/mapstruct/issues/1420

**Comment by jrcacd** [comment]
How can I use the 1.4.0-SNAPSHOT in android?

Gradle result:
Failed to resolve: org.mapstruct:mapstruct:1.4.0-SNAPSHOT

**Comment by filiphr** [comment]
One way to use the snapshot is to use jitpack.io. Example can be found [here](https://jitpack.io/#mapstruct/mapstruct/master-SNAPSHOT). You can also use a specific commit.

**Comment by jrcacd** [comment]
ok, thanks
