### ISSUE TITLE
1.3.1.Final does not use method of injected class

### ISSUE THREAD

**Issue by Koocka44** [mapstruct/mapstruct#2033]
Consider the following case :

```
public class EntityA {
    private EntityB b;
}

public class EntityB {
    private List<EntityA> as;
}

public class A {
    private B b;
}

public class B {
    private List<A> as;
}
```
And the following mapper setup : 

```
@Mapper(componentModel = "spring", uses = {MapperB.class})
public interface MapperA {
    A entityAToA(EntityA entityB);
}
```

In this scenario, if i don't add @Mapping(target="b"  qualifiedByName="xyz") to the `entityAToA` method, MapStruct doesn't resolve the method from the injected class, but start creating its own protected methods which leads to compilation errors in our case. 

The documentation states that : 
> When mapping a property from one type to another, MapStruct looks for the most specific method which maps the source type into the target type. The method may either be declared on the same mapper interface or on another mapper which is registered via @Mapper#uses()

MapperB is an abstract @Mapper class if that counts, because we need explicit autowiring in it.

**Comment by Koocka44** [comment]
Update : 

This only happens when the method in MapperB is @named. if i remove that annotation, it works well.

**Comment by filiphr** [comment]
This is expected behaviour. Have a look at [Mapping method selection based on qualifiers](https://mapstruct.org/documentation/stable/reference/html/#selection-based-on-qualifiers).

More precisely 

>A class / method annotated with a qualifier will not qualify anymore for mappings that do not have the qualifiedBy element.

**Comment by Koocka44** [comment]
Thank you very much @filiphr, i slipped through that part in the docs, sorry!
