### ISSUE TITLE
Can't generate mapping method from non-iterable type to iterable type.

### ISSUE THREAD

**Issue by wangjia2016** [mapstruct/mapstruct#2037]
Can't generate mapping method from non-iterable type to iterable type.
Can't generate mapping method from non-iterable type to iterable type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method from non-iterable type to iterable type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with primitive return type.
Can't generate mapping method with no input arguments.
Can't generate mapping method from non-iterable type to iterable type.
com.xxx does not have an accessible empty constructor.
com.xxx does not have an accessible empty constructor.
com.xxx does not have an accessible empty constructor.

**Comment by filiphr** [comment]
Those are valid error messages saying why the mapping cannot be done. Why do you create an issue
