### ISSUE TITLE
Request to add @Profile supporting features for spring integration

### ISSUE THREAD

**Issue by JokerSun** [mapstruct/mapstruct#2041]
I have some case that needs add @Profile annotation on mapper, but when I annotate it directly, it doesn't work. 
I guess it hasn't been supported yet.
```
e.g.

@Profile(Constants.PROFILE)
@Mapper(componentModel = "spring")
public interface SomeConverter {
    ...
}
```

**Comment by filiphr** [comment]
`@Profile` is a Spring annotation and we don't have any particular support for those. This is really similar with #1427.

However, this is quite easy to be done with a custom `@ComponentScan` that would only scan the `SomeConverter` package when the profile is active.

I am leaning towards closing this as wontfix. Not sure what the team thinks.

**Comment by JokerSun** [comment]
Well, That sounds reasonable, and does the team have a plan to develop the spring integration? I mean the spring-boot-starter-mapstruct will be useful.

**Comment by Chessray** [comment]
On a more abstract level, this reminds me strongly of the discussion in #990 about a possibility to add _any_ annotation to a Mapper. We seem to have a common topic here.

**Comment by JokerSun** [comment]
@Chessray 
That's it. I think I should close the issue, and thanks for your reply.
