### ISSUE TITLE
Using mapping target a null source should return target (not null)

### ISSUE THREAD

**Issue by tibistibi** [mapstruct/mapstruct#2043]
This is my mapping:

	Team toEntity(TeamDTOMine teamDTO, @MappingTarget Team team);

and this is generated:

    @Override
    public Team toEntity(TeamDTOMine teamDTO, Team team) {
        if ( teamDTO == null ) {
            return null;
        }

        team.setId( teamDTO.getId() );
       ....
        return team;
    }

I would suggest not returning null but the team because you want to update the team. If there is nothing to update than the team should stay the same.

**Comment by filiphr** [comment]
Thanks for the issue @tibistibi. I think that this is the same as #1752. I am closing this as a duplicate and will move the original issue to 1.4.0 so we can talk about it with the team.
