### ISSUE TITLE
Is there a way to ignore mapping all fields except one field in Mapstruct ?

### ISSUE THREAD

**Issue by ER-GAIBI** [mapstruct/mapstruct#2044]
Hi, 
 As mentionned in the title, is there a way to avoid ignoring all fileds (> 20) of the target class without using `ignore = true`

**I am asking this question because I have to map just the Id field and not all of them.**

for example : 

```
    @Mapping(target = "opportunity", ignore = true )
    @Mapping(target = "updateDate", ignore = true)
    @Mapping(target = "simpleVarsRemaining", ignore = true)
    @Mapping(target = "ficheEmmiesRemaining", ignore = true)
    @Mapping(target = "creationDate", ignore = true)
    @Mapping(target = "editionDate", ignore = true)
    @Mapping(target = "ficheCalcul", ignore = true)
    @Mapping(target = "institution", ignore = true)
    @Mapping(target = "verificateur1", ignore = true)
    @Mapping(target = "verificateur2", ignore = true)
    @Mapping(target = "installateur", ignore = true)
    @Mapping(target = "soustraitant", ignore = true)
    @Mapping(target = "fiche", ignore = true)
    @Mapping(target = "instutitionName", ignore = true)
    @Mapping(target = "inFolder", ignore = true)
    @Mapping(target = "isCpe", ignore = true)
    @Mapping(target = "cpe", ignore = true)
    @Mapping(target = "forfait", ignore = true)
    @Mapping(target = "folderId", ignore = true)
    @Mapping(target = "folderName", ignore = true)
    @Named(value = "filterMapperForDocument")
    OperationDTO toOperationDTOForDocumentFilter(Operation operation);
```

**Comment by chris922** [comment]
Hi @ER-GAIBI ,

two possible ways:

1. Set `@BeanMapping(ignoreByDefault = true)` and then just add the mapping you would like to have
2. You should be able to create a custom mapping, if it is just one field this should be fine. (see https://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods)


Nevertheless questions should be raised in one of the appropriate channels (e. g. stackoverflow or gitter; https://mapstruct.org/community/getting-help/) and therefore I will close this.

If you found for example a bug or want to raise a feature request feel free to create a new ticket :smiley:

**Comment by BohdanM-AVISPL** [comment]
Ironically this is first result in google search on query "mapstruct ignore all field except one", and, actually, only one useful at first page of google :D

**Comment by filiphr** [comment]
@BohdanM-AVISPL I've added #2930, which I hope can fix the Google Search

**Comment by foal** [comment]
Unfortunately, `@BeanMapping(ignoreByDefault = true)` ignores both target as well as source properties, so lose the control if source will have new attribute that I have to map or add it to the `ignoreUnmappedSourceProperties` list.

**Comment by foal** [comment]
@filiphr Maybe change the type of `ignoreByDefault` from `boolean` to the Enum - `SOURCE|TARGET|BOTH`?

**Comment by filiphr** [comment]
@foal the idea is on the right path. Can you please create a separate issue for that?

We can't change the `ignoreByDefault`. However, we can new `ignoreByDefaultStrategy` that would have `SOURCE | TARGET | BOTH`

**Comment by igr** [comment]
That would make sense

**Comment by foal** [comment]
Created #3391
