### ISSUE TITLE
Wrong mapper impl generated when defaultExpression is used and no "source" explicitly specified

### ISSUE THREAD

**Issue by fml2** [mapstruct/mapstruct#2047]
- [x] Is this an issue (and hence not a question)? 

**The issue happens with the latest stable release 1.3.1.**

I have two identical (just the names differ) classes `SourcePerson` and `TargetPerson` like this:
```
public class SourcePerson {
    private String name;
    public String getName() { return name; }
    public void setName(String name) {this.name = name;}
}
```

and a mapper that uses the `defaultExpression` attribute:
```
@Mapper
public interface TheMapper {
    @Mapping(target = "name", defaultExpression = "java(\"DEFAULT\")")
//    @Mapping(target = "name", defaultValue = "DEFAULT")
//    @Mapping(target = "name", source = "name", defaultExpression = "java(\"DEFAULT\")")
    TargetPerson map(SourcePerson source);
}
```
The mapper should assign a default value to the field `name` in the target object if the field in the source object is `null`.

Since the field name in the source and the target objects is the same, I only specify the target name and do not specify the source name.

When I use `defaultExpression`, a wrong code for the mapper impl is generated:

```
@Override
public TargetPerson map(SourcePerson source) {
	if ( source == null ) {
		return null;
	}

	TargetPerson targetPerson = new TargetPerson();

	targetPerson.setName( source.getName() );

	return targetPerson;
}
```

If I either use `defaultValue` or specify the `source` attribute (i.e. do the mapping in either of the commented ways) the code is generated correctly. Here is the example for the case `defaultExpression` with an explicitly specified `source`:
```
@Override
public TargetPerson map(SourcePerson source) {
	if ( source == null ) {
		return null;
	}

	TargetPerson targetPerson = new TargetPerson();

	if ( source.getName() != null ) {
		targetPerson.setName( source.getName() );
	}
	else {
		targetPerson.setName( "DEFAULT" );
	}

	return targetPerson;
}
```

Could you please provide a fix for the issue? I'll provide a (failing) test case shortly.

PS. The bug does not occur in the current master branch. So it seems to have been fixed. But then could you please backport it to the 1.3.x branch. Or release the current state. Thanks!

**Comment by filiphr** [comment]
Thanks for the analysis @fml2. As you have seen it doesn't occur on current master branch because it has been fixed there. I don't remember which issue did the fix so I can link it.

We are not planning to do another release from the 1.3.x branch. We are working towards a 1.4 release. We know that it is going a bit slow, but we are doing our best

**Comment by fml2** [comment]
Is there something like a "Known Bugs" page? So that pepople do not have to spend time?

**Comment by chris922** [comment]
As far as I know there is no dedicated page. Before opening an issue you can do a quick search in the GitHub issue overview or have a look at the issues planned and/or already implemented for the next version by selecting the milestone filter, e. g. for the upcoming 1.4.0: https://github.com/mapstruct/mapstruct/issues?q=milestone%3A1.4.0
