### ISSUE TITLE
[Feature] Conditional mapping

### ISSUE THREAD

**Issue by pherklotz** [mapstruct/mapstruct#2051]
### Feature proposal 
Specify a condition (similar to the expression) for a target. If the condition evaluates to true the mapping will be done. Otherwise nothing happens or the default will be used if specified.

### Motivation 
Whether a null check nor a presence checker method are sometimes mighty enough to express whether a property should be mapped or not. We use MapStruct to map Protobuf v3 Messages. These can contain oneof fields which can contain only exact one or zero values. If one of the specified values is a primitive datatype like int or long there is no hasXYZ method generated and the default value will be returned from the getter (e.g. zero) this is also the case if another value type is the in the oneof! You have to check the case-Field of the protobuf message to find out which of the oneofs is set. See protobuf documentation about that: 

- https://developers.google.com/protocol-buffers/docs/proto3#oneof-features
- https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof

**Example**

Protobuf:
```protobuf
...
oneof foo {
  uint32 bar = 1;
  uint32 baz = 2;
}
...
```

Generated mapper code for this:
```java
o1.setBar( o.getBar() );
o1.setBaz( o.getBaz() );
```

But only one should be set. With the proposed conditional mapping I could write a condition to check the case-Field of the source to find out which property should be set.

### Example for the usage of the proposed feature
Mapper interface
```java
@Mapping(target="baz", condition="java( bar.getBaz()==42 )")
Foo mapFoo(Bar bar);
```

Generated mapping code for property "baz"
```java
if(bar.getBaz()==42) {
  foo.setBaz( bar.getBaz() );
}
```

If you are open to adopt this feature I would provide a PR.

**Comment by filiphr** [comment]
Thanks for the suggestion @pherklotz. We also just received the same request in #2107. Their **Option 1** is identical to yours.

I like the proposal here, with one difference instead of using `condition`, I think that `conditionExpression` makes more sense.

If you are still interested in providing a PR can you please sync with @Desislav-Petrov?

Looking at this I got an idea that could be something interesting is as well. We can add a new annotation named `@Condition` which we can then use in `condition`. That way you can use some utils for it.

e.g.

```
@Condition("is42")
default boolean is42(int value) {
    return value == 42;
}

@Condition
default boolean isNotEmpty(String value) {
    return value != null && value.length() > 0;
}

@Mapping(target = "baz", condition = "is42")
@Mapping(target = "someString", condition = "isNotEmpty")
For mapFoo(Bar bar);
```

We can even look for a single `@Condition` method which has the source type as input and has a `boolean` as output, or allow specifying on the `@Condition` whether it applies to all or not. 

This might even solve #2084

**Comment by Desislav-Petrov** [comment]
Hi @filiphr,

I think I like your proposal more because in addition to what you said, this way we will have proper java code versus "java as a string" as in condition.

Thanks,
Des

**Comment by filiphr** [comment]
I don't mind having both options (`conditionExpression` and `condition`). I personally am always more for java code vs an expression (java as string).

**Comment by ivangsa** [comment]
Yes, I think the `@Condition` proposal would be an even better solution for #2084 (when it can be applied to all properties of type)

**Comment by filiphr** [comment]
For #2084 it can even work out of the box by defining some method like:

```
default <T> boolean isPresent(Optional<T> optional) {
    return optional.isPresent();
}
```

In theory if we add the support for `condition` we can have some out of the box conditions that we'll be automatically reused, similar to how it is done for the mapping methods

**Comment by Desislav-Petrov** [comment]
Thanks for the good ideas, I've just started working on a PR and would have an initial impl shortly.

**Comment by filiphr** [comment]
That's great. Looking forward to reviewing it.

**Comment by pherklotz** [comment]
Thanks for all your comments. I really like your idea @filiphr. This allows more complex checks with good readability. @Desislav-Petrov can I help you with the implementation?

**Comment by Desislav-Petrov** [comment]
@pherklotz why not divide and conq on this one - I'm working on introducing the condition = method name bit. Once i'm done with this you can finish off the second part about introducing the @Condition ?

**Comment by filiphr** [comment]
Thanks for the work on this @pherklotz and @Desislav-Petrov. Let us know if you need some help. 

One a side note something like this might help us with the presence check for #1075. We'll need a containsKey check as a presence check there.

**Comment by Desislav-Petrov** [comment]
Hi,

PR: https://github.com/mapstruct/mapstruct/pull/2148 

Haven't implemented the @Condition bit as I haven't heard if @pherklotz is interested to finish it off. I'm happy to do it as an extension if I don't hear back.

Thanks,
Des

**Comment by kevinprotoss** [comment]
Hi,

Cool, if this feature could be done. We require this feature for our use case as well and I also like this solution. 

Bg,

**Comment by kevinprotoss** [comment]
Hi, 

the solution part from @Desislav-Petrov works already for me. How about the part for @condition annotation? Will it still be implemented. 

If not, I'd like to have a try. @filiphr Which parts should I change, if I wanna implement this new @condition annotation?

Bg,
Kevin

**Comment by Desislav-Petrov** [comment]
I'm doing the @condition bit too, was waiting to hear if @pherklotz still wants to do part of the work or not. Since I haven't heard from him for a while I will continue with adding it.

**Comment by keltharan** [comment]
Hi,
is it possible to use multiple parameters for the given condition. I would like to use protobuf oneof and this condition annotation in combination with a Map<String, String> mapping. So that i can create a generic mapper referring to the required fields in the provided map.

BR

**Comment by filiphr** [comment]
This has now been implemented in the same style as the other functionality of MapStruct.

The new `@Condition` annotation can be used to mark that a method is a condition check method. There are 2 new options in the `@Mapping`: `conditionQualifiedBy` and `conditionQualifiedByName` which are the qualifiers for a condition.

Methods annotated with `@Condition` can have similar parameters as the lifecycle `@AfterMapping` and `@BeforeMapping` injected.

**Comment by d-tchmnt** [comment]
Hello filiphr, 
when should we expect the new functionality to be used?
thanks for all the good work :)

**Comment by HemalathaGowdar** [comment]
@filiphr : Could you please help me , I have been using @condition method as suggested below link
https://mapstruct.org/documentation/dev/reference/html/#conditional-mapping

But am not seeing this method has been used/invoked in the generated impl class. Could you please assist.

**Comment by filiphr** [comment]
@HemalathaGowdar you created #2688, there is no need to ping people and comment the some things in multiple issues. I've replied to you in #2688
