### ISSUE TITLE
"uses" entries ignored when used class is generated during annotation processing

### ISSUE THREAD

**Issue by Chessray** [mapstruct/mapstruct#2056]
Tested with current master (1.4.0-SNAPSHOT): https://github.com/Chessray/mapstruct-spring-additions/tree/specifyNameForGeneratedBridgeClass

Version 1.3.1.Final throws a NullPointerExsception in this setup. The latest master just behaves as if the `uses` attribute weren't there:
- By default, it just generates a meaningless helper mapping method:

       protected SeatConfigurationDto seatConfigurationToSeatConfigurationDto(SeatConfiguration seatConfiguration) {
        if ( seatConfiguration == null ) {
            return null;
        }

        SeatConfigurationDto seatConfigurationDto = new SeatConfigurationDto();

        return seatConfigurationDto;
       }
- With `unmappedTargetPolicy = ERROR`, annotation processing fails, because there are no mappings for the child attributes in the parent mapper.

**Comment by Chessray** [comment]
_Gitter conversation copied for reference_:

Raimund Klein
@Chessray
08:34
I'm currently digging a bit into the details. It feels like the `MapperConfigGem` should not be valid during the first run. But take this opinion with a grain of salt - I'm looking through the Gem code for the first time. ;-)
The content of `uses` is simply the String `(<error>)` which makes sense before the class to use has been generated.
Filip Hrisafov
@filiphr
10:40
You are looking into the correct place
We should probably throw the type hierarchy erroneous exception
Raimund Klein
@Chessray
10:48
IDKWTM. :-) I've got to attend my day job for the next few hours, but I might be able to look at it tonight or over the weekend. Unless you could spend some time?
Filip Hrisafov
@filiphr
10:54
I have no problems you fiddling with the MapStruct internals. You'll get to know more about it :)
During the day it is difficult for me, and not sure if I would be able to do it over this weekend as well
Raimund Klein
@Chessray
10:57

OK, I'll try. Just looking at the exception now. The class comment seems to indicate this would be a bit of an abuse, but if the project lead says so...

`Indicates a type was visited whose hierarchy was erroneous, because it has a non-existing super-type.`
Filip Hrisafov
@filiphr
10:58
Yes that was how it was meant to be initially
But it makes sense to use it in other places where we use certain types
We throw it from the Immutables builder SPI as well
To indicate that the type is not ready yet
Raimund Klein
@Chessray
10:59
In that case...
Filip Hrisafov
@filiphr
10:59
Which is what you want in order to be good processor citizen and postpone your processing to the next round
Raimund Klein
@Chessray
11:00
Makes sense, I'll see if I can come up with something. So you're saying the presence of this `<error>` would be sufficient for throwing it?
(As this seems to come back directly from the environment, if I'm not missing anything.)
Filip Hrisafov
@filiphr
13:58
Don't we have `TypeMirror` there?
I think that there should be a collection of those and they should be of kind `ERROR`
Raimund Klein
@Chessray
15:08
I'm currently inside GemValue.extractListValues - in this portion, the definedValue is rcognised as a List:

        Object definedValue = annotationValue.getValue();
        if ( definedValue instanceof List ) {
            value = toStream( (List) definedValue, valueClass ).map( mapper ).collect( Collectors.toList() );
        }
        else {
            value = null;
        }

Raimund Klein
@Chessray
15:22
However, `value` becomes an _empty_ `List`.
[Type HIerachy](https://files.gitter.im/mapstruct/mapstruct-users/bLrq/Bildschirmfoto-2020-04-03-um-15.25.34.png)
Raimund Klein
@Chessray
15:28
`definedValue` contains something of type` Attribute$UnresolvedClass` which apparently is not a `TypeMirror`, so `toStream` just discards it silently. Not sure where to go from here.
Filip Hrisafov
@filiphr
15:33
Interesting
That is certainly a bug in the tools gem then
Looking at the `Attribute$UnresolvedClass` it seems like the value it returns is not the `Type` but a String with `<error>` in it
Raimund Klein
@Chessray
16:02
That's what I figured.
Raimund Klein
@Chessray
17:08
SO do you wish to give this some deeper thought?
Filip Hrisafov
@filiphr
17:16
Yup, I'll think about how we can solve this
Thanks for the analysis
Raimund Klein
@Chessray
17:16
No problem. Thank for the help. :-)

**Comment by filiphr** [comment]
Thanks a lot for the great analysis @Chessray. We actually have 2 problems:

* `tools-gem` silently ignores this problem (i.e. MapStruct will never see what was in `uses` or `imports`). Already have a fix for this for there
* mapstruct will throw an NPE once `tools-gem` is fixed to properly return `null` for missing `TypeMirror`. Also have a fix for this in mapstruct.

One important note, this is actually a bug in javac. See [JDK-8229535](https://bugs.openjdk.java.net/browse/JDK-8229535). Eclipse will correctly return a `TypeMirror` with `TypeKind#ERROR` and MapStruct will gracefully handle that by postponing the mapper to the next round.

**Comment by Chessray** [comment]
> One important note, this is actually a bug in javac. See [JDK-8229535](https://bugs.openjdk.java.net/browse/JDK-8229535). Eclipse will correctly return a `TypeMirror` with `TypeKind#ERROR` and MapStruct will gracefully handle that by postponing the mapper to the next round.

I was wondering whether this should be considered a JDK bug. Rereading the Javadocs for `TypeMirror.ERROR`, I tend to agree. Looks like I'll have to switch to the Eclipse compiler then for the time being - another reason to wash my hands...
