### ISSUE TITLE
Map List in source inner property to List in target

### ISSUE THREAD

**Issue by trixobird** [mapstruct/mapstruct#2064]
Hi, first of all thank you very much for this lib :) here is my question - I have:
```
class Dto {
    private List<InnerDto> innerDto;
}

class InnerDto {
    private MyEnum myEnum;
}

enum MyEnum { }

class Model {
    private List<MyEnum> myEnum;
}
```
Is there a way to have a toDto Mapper that will map myEnum in the innerDto list to a List of MyEnum in the target?

**Comment by chris922** [comment]
Hey @trixobird , sorry for the late reply. But as this is just a question please don't create an issue for this.
You can find information where to ask questions on the [MapStruct web site](https://mapstruct.org/community/getting-help/), e. g. use Stackoverflow and tag the question with `mapstruct`.

Anyway, have you tried to create an own mapping method?

For example the mapper could look like this:

```java
@Mapper
public interface TestMapper {

    @Mapping(target = "innerDto", source = "myEnum")
    Dto toDto(Model model);

    default InnerDto toInnerDto(MyEnum myEnum) {
        InnerDto innerDto = new InnerDto();
        innerDto.setMyEnum(myEnum);
        return innerDto;
    }
}
```
