### ISSUE TITLE
Mapping List<Object[]> to List<Employee> Object Using mapstruct

### ISSUE THREAD

**Issue by Blessing1988** [mapstruct/mapstruct#2065]
Hi,

I need to map a List<Object[]> to  List<Employee>. How can I do this.

Object [] = {test1,40}

Employee = {name,age}

Regards,
Blessing.

**Comment by filiphr** [comment]
Hey,

Please use StackOverflow or our [Gitter Room](https://gitter.im/mapstruct/mapstruct-users) to ask questions.

In a nutshell MapStruct is an annotation processor so it doesn't know about the type of the object during runtime. You'll have to provide your own mapping method.
