### ISSUE TITLE
Copy one attribute from a deep nested and complex JPA entity to another JPA entity.

### ISSUE THREAD

**Issue by govindrk** [mapstruct/mapstruct#2066]
- [ ] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

Hey @filiphr 

I have a complex nested object which is mapped to JPA entities. The maximum level of hierarchy for any element is 5 with many (one-to-one, one-to-many and many-to-one) relationship.

I would like to copy the ID attribute of every object with the deep nested entity. Each entity has average 8 properties and some with more than 40 properties. I only want to get the ID attribute of all elements copied to another Entity of same structure.

The JPA entity has many one-to-one, one-to-many, many-to-one relationship.  The purpose of me getting the ID attribute is to update the Entity.

The hibernate JPA automatically deletes record and inserts new record for Update. This happens if you don't specify the ID in the entity.  The first option for me to query the database to check if record exists, get the record, then copy only the ID value and set it to the to-be-updated entity.

have tried 
update(@MappingTarget PersonEntity base, PersonEntity modified);
update(@MappingTarget AddressEntity base, AddressEntity modified);
update(@MappingTarget PersonNameEntity base, PersonNameEntity modified);
etc...
in total have 372 entities with Ids.

Thanks

**Comment by filiphr** [comment]
Hey @govindrk,

please do not use the issue tracker for asking questions. Use either StackOverflow or our [GItter room](https://gitter.im/mapstruct/mapstruct-users) for asking questions.
