### ISSUE TITLE
NullValuePropertyMappingStrategy.SET_TO_DEFAULT on value null

### ISSUE THREAD

**Issue by john182** [mapstruct/mapstruct#2076]
@InheritInverseConfiguration doesn't apply null value mapping

Example:
User.java
`
@Getter
@Setter
public class User {

    private Integer id;
    private String name;
    private Profile profile;
}
`
Example:
Profile.java
`
@Getter
@Setter
public class Profile {

    private Integer id;
    private String name;
}

`
Example:
Mapper.java

`
@Mapper(componentModel = "spring")
public interface UserMapper {

    @Mappings({
            @Mapping(source = "profile.id", target = "idprofile"),
    })
    UserDTO toModel(User user);

    @InheritInverseConfiguration
    User toDomainObject(UserDTO dto);
}
`

Result:

`
@Component
public class UserMapperImpl implements UserMapper {
    public UserMapperImpl() {
    }

    public UserDTO toModel(User user) {
        if (user == null) {
            return null;
        } else {
            UserDTO userDTO = new UserDTO();
            userDTO.setIdprofile(this.userProfileId(user));
            userDTO.setId(user.getId());
            userDTO.setName(user.getName());
            return userDTO;
        }
    }

    public User toDomainObject(UserDTO dto) {
        if (dto == null) {
            return null;
        } else {
            User user = new User();
            user.setProfile(this.userDTOToProfile(dto));
            user.setId(dto.getId());
            user.setName(dto.getName());
            return user;
        }
    }

    private Integer userProfileId(User user) {
        if (user == null) {
            return null;
        } else {
            Profile profile = user.getProfile();
            if (profile == null) {
                return null;
            } else {
                Integer id = profile.getId();
                return id == null ? null : id;
            }
        }
    }

    protected Profile userDTOToProfile(UserDTO userDTO) {
        if (userDTO == null) {
            return null;
        } else {
            Profile profile = new Profile();
            profile.setId(userDTO.getIdprofile());
            return profile;
        }
    }
}
`
Expert:

`
  protected Profile userDTOToProfile(UserDTO userDTO) {
        if (userDTO == null  || userDTO.getIdprofile()== null) {
            return null;
        } else {
            Profile profile = new Profile();
            profile.setId(userDTO.getIdprofile());
            return profile;
        }
    }

`

**Comment by sjaakd** [comment]
Problem is that `NullValuePropertyMappingStrategy` only applies to update methods. `NullValueCheckStrategy` (relevant to regular methods) does not offer to return a default. In 2.0 we want to revise these and make them more logical. They evolved this way historically. 

So `NullValuePropertyMappingStrategy` works as designed.
