### ISSUE TITLE
Mapping error for non-iterable type to iterable type with Builder

### ISSUE THREAD

**Issue by cmdjulian** [mapstruct/mapstruct#2079]
Hello, 

Not quiet sure if it's a bug or if I doing something wrong. I'm having trouble while mapping an entity.
My entity is just a normal java class, no extended interfaces, just plain java, imagine it like so:

```
public class Entity {
    @Id
    Long id;

    String name;

    String description

    @OneToMany
    List<SomeOtherEntity> someOtherEntities;
}
```
I'm using [HAL](https://docs.spring.io/spring-hateoas/docs/current/reference/html/) and want to generate the corresponding links in the constructor  of the dto, so I'm using a builder construct for that, for having accesses to the entities attribute.

My dto looks like that:

```
public class EntityDto extends CollectionModel<SomeOtherEntity> {
    Long id;
    String name;
    String description;

    @Builder
    public EntityDto(Long id, String name, String description, List<SomeOtherEntity> someOtherEntities) {
        super(someOtherEntity);
        this.id = id;
        this.name = name;
        this.description = description;

        final Link selfRef = new Link("/Entity/" + id);
        add(selfRef);

        if (CollectionUtils.isNotEmpty(someOtherEntity)) {
            final Link someOtherEntityRef = new Link("/Entity/" + id + "/someOtherEntity/");
            add(someOtherEntityRef);
        }
    }
}
```

`CollectionModel` is a class of Spring Hal and implements `Iterable`. And there is the problem. When I try to map the classes in a mapper like so:

```
@Mapper(uses = SomeOtherEntityMapper.class, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface EntityMapper {
    EntityDto map(Entity entity);
}
```

I get the following error: `error: Can't generate mapping method from non-iterable type to iterable type`.
I would expect when using a builder that map struct just uses the builder. You can see from my code there is no problem, the only problem is the map struct check for looking into this Iterable and non-Iterable thing.
Am I using mapstruct in the wrong way or should that work?
Thanks in advance.

**Comment by filiphr** [comment]
Closing this in favour of #607 and PR #2210
