### ISSUE TITLE
Is it possible to assign expressions clause to target property only when the source property is not NULL?

### ISSUE THREAD

**Issue by shivamkhosla** [mapstruct/mapstruct#2082]
I want to convert a source property's datatype Timestamp to the target property's datatype LocalDateTime.
For this, I call the _.toLocalDateTime_ property of the timestamp object in the expression clause like below.
`@Mapping(target = "targetDate", expression ="java(someSqlDTO.getSourceDate().toLocalDateTime())")`
But now I want to assign the target _targetDate_ only when my source property _sourceDate_ is not null else ignore.
`nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_NULL`
I've enabled but of them but they don't seem to work with expressions and most likely the reason is that when using expressions, we cannot use _source_ in _@Mapping_.
Is there a solution to this problem?

**Comment by filiphr** [comment]
`Mapping#expression` is there to be used as is, there is no source concept here. Whatever is written in the expression it will be written in the generated code.

I would suggest that you rethink why you need to use `expression`. You can always write your own custom method for mapping between `Timestamp` and `LocalDateTime`. MapStruct will then correctly invoke the custom mapping method.
