### ISSUE TITLE
Generated Impl has common method that is reference to two fields with similar names. 

### ISSUE THREAD

**Issue by nadeemfarooqui** [mapstruct/mapstruct#2083]
- [Yes] Is this an issue (and hence not a question)? 
Generated Impl has common method that is reference to two fields with similar names. This is causing wrong value mapped to multiple fields. Here is what I have 

			@Mapping(source = "treatmentRefProducts.abcNeedleId", target = "abcTreatmentNeedle.id"),
			@Mapping(source = "treatmentRefProducts.xyzNeedleId", target = "xyzTreatmentNeedle.id"),
			@Mapping(source = "treatmentRefProducts.thridId", target = "third.id"),
			@Mapping(source = "treatmentRefProducts.fourthId", target = "fourth.id"),
			@Mapping(source = "treatmentRefProducts.fifthId", target = "fifth.id"),

The problem is with first two elements. This is what is generated in Impl 
         
           if (input.getTreatmentRefProducts() != null) {
           treatmentOrderHemo.setAbcTreatmentNeedle(this.treatmentRefProductsToTreatmentNeedle(input.getTreatmentRefProducts()));
            }   
           if (input.getTreatmentRefProducts() != null) {
                treatmentOrderHemo.setXyzTreatmentNeedle(this.treatmentRefProductsToTreatmentNeedle(input.getTreatmentRefProducts()));
            }

As you can see they both call this.treatmentRefProductsToTreatmentNeedle(input.getTreatmentRefProducts()
and obviously get the same value populated. I would have expected two methods generated, one for abc and second for xyz. However it seems like it truncates the first word from abcTreatmentNeedle i.e abc and first word from xyzTreatmentNeedle i.e and generates one method treatmentRefProductsToTreatmentNeedle. Is this expected?

**Comment by filiphr** [comment]
@nadeemfarooqui can you please share your models so we can have a better look at this.

**Comment by filiphr** [comment]
Closing to the lack of response. We can reopen when more details are provided.
