### ISSUE TITLE
Support custom source presence checker expressions for mappings and custom method mappings

### ISSUE THREAD

**Issue by ivangsa** [mapstruct/mapstruct#2084]
Currently mapstruct only allows presence checker methods on the owning source object.

Some types (like java.util.Options, guava Optional, JsonNullable, ...) have presence checker method on the property itself.

With a custom presence checker expression configuration we could write a mapper like:

```
@Mapper
public interface OptionalMapper {

    @SourcePresenceCheckerConfig(
            expression = "java( <SOURCE>.<READ_ACCESSOR>() != null && <SOURCE>.<READ_ACCESSOR>().isPresent() )")
    default <T> T fromOptional(final Optional<T> optional) {
        return optional.orElse(null);
    }

    // nulls are handled inside method
    @SourcePresenceCheckerConfig(nullValueCheckStrategy = NullValueCheckStrategy.NEVER)
    default <T> Optional<T> asOptional(final T optional) {
        return optional != null ? Optional.of(optional) : Optional.empty();
    }

}
```

or a mapping like:
```
@Mapping(target = "prop1", source ="prop1", sourcePresenceCheckerExpression = "java( source != null && source.getProp1().isPresent() )")
TargetWithPlainValues asPlain(SourceWithOptional source);
```

This may address this question:
https://stackoverflow.com/questions/61371019/custom-source-presence-checking-method-name-in-mapstruct

and this issue in a general manner:
https://github.com/mapstruct/mapstruct/issues/674

**Comment by sjaakd** [comment]
@ivangsa thanks for raising the issue here. 

My thinking would be to expand the SPI (checkout `AccessorNamingStrategy`) for this. Did you check that one out already?

**Comment by ivangsa** [comment]
Hi,

yes I had a look at AccessorNamingStrategy,

I've also been doing a quick'n'dirty test here https://github.com/ivangsa/mapstruct/commit/6646b813c8ef37006468cc7e160cefcb91c2bcc9

registering a new JavaOptionalConverter and a hardcoded "source presence checker" for it... 
(that obviously will only for java Optional, it will require more converters for guava, jsonnullable...) 

still with that approach there is a missing piece: the "null check strategy" when converting from 'plain' to 'optional':

- if source is null I'd still want the mapper to be invoked so it can set an Optional.empty or at least be able to configure it.. but because is an implicit conversions it will never be invoked if source is null..

I will have another look at expand the SPI

**Comment by ivangsa** [comment]
Hi

I believe I got it extending `AccessorNamingStrategy` interface, its simple and it seems to works fine

https://github.com/ivangsa/mapstruct/commits/features/customPresenceCheckerRef

I think this solution could solve most use cases for mapping java.util.Optional, JsonNullable...

It would still be usefull to have something like NullValueCheckStrategy.NEVER so null mapping can be handled inside the custom mapper:

```
if(source.getPlainProperty() != null) { // <-- avoid this check
	// null could be handled inside mapper
	target.setOptionalProperty(optionalMapper.asOptional(source.getPlainProperty()));
}
```
but we can leave this for now..

If you think this is OK I can do a PR..

**Comment by norrs** [comment]
@ivangsa : I would love to see this getting supported, make a PR and have the discussion int the PR! <3

I found this issue via comments in https://github.com/mapstruct/mapstruct/issues/674 . 

Then poke sjaakd again after the PR is created :-)

**Comment by ivangsa** [comment]
hi @sjaakd I hace created this PR #2097 
it builds fine but in jdk15 which seems to be an unrelated problem..

**Comment by filiphr** [comment]
This can now be achieved with the new `@Condition` annotation.

Have a look at https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/conditional/basic/OptionalLikeConditionalMapper.java for an example. The example is actually inspired by the example in the issue provided by @ivangsa
