### ISSUE TITLE
Need a feature to implement custom presense checker

### ISSUE THREAD

**Issue by kevinprotoss** [mapstruct/mapstruct#2090]
Hi,

I have a problem while using mapstruct. I have also seen some similar existing issues here, such as. 
[https://github.com/mapstruct/mapstruct/issues/2084](https://github.com/mapstruct/mapstruct/issues/2084)

I know some one suggested to extend the spi of mapstruct. However, as I understand, I can only decide which checker function should be used by extending spi. There is a precondition, that the checker function must be available on the source class. Did I understand correctly? If not, please give me more hints about how to use that. 

Currenty, I want to define a custom checker function which is not existing on the Source Class. I need to check whether the property of source object is a NULL char: `\u0000`. It's certainly not null reference. 

Otherwise, is there any possibility to define an additional checker after Qualifier before setting target. I used custom Qualifier to map this char to enum value. If the char is a NULL char, the qualifier will return null reference. If check of qualifier result is possible, the target property setting can be avoided. 

Best regard and great thanks.
Kevin

**Comment by filiphr** [comment]
Hey Kevin,

thanks for creating this issue. I think that with the proposal I did in #2051 it would be possible to achieve what you are looking for here. Therefore I am closing this in favour of #2051. Let me know if you don't agree and we can discuss it more.
