### ISSUE TITLE
Set-property with null-value is not set to null, when mapping bean to new object

### ISSUE THREAD

**Issue by runenielsen** [mapstruct/mapstruct#2094]
- [x] Is this an issue (and hence not a question)? 

Set-property with null-value is not set to null, when mapping bean to new object.

The generated code is:

```java
if ( set != null ) {
    newBean.setNewSet( new HashSet<Integer>( set ) );
}
```

It should be:

```java
if ( set != null ) {
    newBean.setNewSet( new HashSet<Integer>( set ) );
} else {
    newBean.setNewSet( null );
}
```

Otherwise any default value is not overwritten.

The problem only occurs for new objects, when updating an existing object, it works correctly.

This worked in Mapstruct 1.2.0.Final, but doesn't work in 1.3.1.Final.

**Comment by chris922** [comment]
Thanks for reporting this, @runenielsen 

Could you please give a short outline of the mapper that you defined? Maybe also the relevant structure of the source/target objects?

**Comment by runenielsen** [comment]
Hi.

Example mapper, from- and to-beans:

```
package org.test;

import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;

@Mapper
public interface TestMapper {
    ToBean mapToBean(FromBean fromBean);
    void updateToBean(FromBean fromBean, @MappingTarget ToBean toBean);
}
```

```
package org.test;

import lombok.Data;
import java.util.Set;

@Data
public class FromBean {
    private Set<Integer> integerSet;
}
```

```
package org.test;

import lombok.Data;

import java.util.HashSet;
import java.util.Set;

@Data
public class ToBean {
    private Set<Integer> integerSet = new HashSet<Integer>();
}
```

The resulting generated code is:

```
package org.test;

import java.util.HashSet;
import java.util.Set;
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-05-11T14:20:12+0200",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 1.8.0_181 (Oracle Corporation)"
)
public class TestMapperImpl implements TestMapper {

    @Override
    public ToBean mapToBean(FromBean fromBean) {
        if ( fromBean == null ) {
            return null;
        }

        ToBean toBean = new ToBean();

// PROBLEMATIC CODE HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        Set<Integer> set = fromBean.getIntegerSet();
        if ( set != null ) {
            toBean.setIntegerSet( new HashSet<Integer>( set ) );
        }
// PROBLEMATIC CODE ENDS HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        return toBean;
    }

    @Override
    public void updateToBean(FromBean fromBean, ToBean toBean) {
        if ( fromBean == null ) {
            return;
        }

        if ( toBean.getIntegerSet() != null ) {
            Set<Integer> set = fromBean.getIntegerSet();
            if ( set != null ) {
                toBean.getIntegerSet().clear();
                toBean.getIntegerSet().addAll( set );
            }
            else {
                toBean.setIntegerSet( null );
            }
        }
        else {
            Set<Integer> set = fromBean.getIntegerSet();
            if ( set != null ) {
                toBean.setIntegerSet( new HashSet<Integer>( set ) );
            }
        }
    }
}
```

Note that the target integerSet property is not set to null, if the source integerSet property is null in mapToBean. This means the default value is still set, so integerSet in toBean is still an empty set rather than null as expected. In version 1.2.0.Final, the set was set to null in this case.

It is however correctly set to null in updateToBean, if the set is null in fromBean, but not null in toBean.

**Comment by chris922** [comment]
@sjaakd You worked on these null-value property strategy stuff? Is this somehow related to it?

This issue sounds really familar to me.. but I can't find a related one.

**Comment by filiphr** [comment]
This was done in 1.3.0.Beta2. Have a look at "Handling null or missing source properties" in https://github.com/mapstruct/mapstruct/releases/tag/1.3.0.Beta2.

It was an explicit reason to remove the setting to `null` for mapping into target objects. The reason for that is that usually you have control over the default value in your object, so if the value is not set in the source object it won't be set in the target as well.

If you want to explicitly set the default value you can use `Mapping#defaultValue` or `Mapping#defaultValueExpression`

**Comment by runenielsen** [comment]
Ok, thanks.
