### ISSUE TITLE
Any ability to define global mapper and use it implicitly?

### ISSUE THREAD

**Issue by linarkou** [mapstruct/mapstruct#2102]
- [ ] Is this an issue (and hence not a question)? 

Hi! I'm new to MapStruct, before I've used ModelMapper, and it has ability to register global converter between types (ex. `LocalDate` -> `Date`). Then in any other converter it will implicitly use this converter for converting `LocalDate` to `Date`.

In MapStruct I only found `@Mapper#uses()` for reusing converter, but I need to add it explicitly into all converters. So does there any way to add global converter and use it implicitly?

Actually I want to write converter from java DateTime API to google.protobuf.Timestamp [timestamp.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto). And then implicitly reuse it in mappings between date/time fields.

**Comment by chris922** [comment]
Hey @linarkou ,

questions shouldn't be asked here in issues, take a look at the [MapStruct webpage](https://mapstruct.org/community/getting-help/) to see how you can get help, e. g. stackoverflow with the `mapstruct` tag.

Anyway regarding your question: You can find the global configuration options here: https://mapstruct.org/documentation/stable/reference/html/#configuration-options
Unfortunately there is no way to define a global mapper, what you could do is defining a shared mapper configuration (see [here](https://mapstruct.org/documentation/stable/reference/html/#shared-configurations)) and reference this in your mappers

**Comment by linarkou** [comment]
Excuse me, @chris922 , and thanks!
