### ISSUE TITLE
Issue mapping List<T> from source to target object instance variable List<T> if first parameter

### ISSUE THREAD

**Issue by dfiorin** [mapstruct/mapstruct#2105]
Hi,

Let's take as example this class:

```
public class ShoppingBasket{
    private List<Fruit> fruits;
    private List<Vegetable> vegetables;
}
```
with getters and setters.
If I want to create a Mapper class like that

```
@Mapper
public class ShoppingBasketMapper {
    ShoppingBasket toTarget(List<Fruit> fruits, List<Vegetable> vegetables);
}
```

I'm expecting that these elements would be mapped easily. The issue is that the processor goes in error because he thinks that I want to map an Iterable to a target object.
Ok, at this point I'm expecting the sentence "use a constructor not mapstruct". Let me finish :) 
If I had a new parameter on the class:

`private Double amount;`

I'd like the mapper to change like this: 

```
@Mapper
public class ShoppingBasketMapper {
    ShoppingBasket toTarget(Integer amount, List<Fruit> fruits, List<Vegetable> vegetables);
}
```
Now I'd expect that the processor returns an error as before but it doesn't. Actually, it works because there isn't any List as first parameter, it maps Integer to Double and then it assigns the 2 lists to the target lists since they have same name and type.

The checks expected on the first parameter should change in order to evaluate first if the target object has a List as instance variable, applying the same logic of mapping between simple objects. 
1) same name and same type should be free mappings
2) different name but same type -> specify mapping names with @Mapping 
3) if the 2 lists have different types:
  a) do nothing it is already provided as in the case from Integer to Double).
  b) it is needed to specify a mapping between the source object type and the target object type 

What do you think?

**Comment by mcapacch** [comment]
Happened the same to us, but the other way around: we didn't have an issue because we had a first argument not a list and we didn't realize that we hit this ~~bug~~ feature.

**Comment by filiphr** [comment]
Thanks for the detailed issue @dfiorin. I think that this is same as #2005. We are only checking the first source parameter when doing the check. Perhaps we need to relax that and only do the check if there is a single source parameter.
