### ISSUE TITLE
Test mappers ignoring @Mapping annotation when method is defined in src/main/ directory

### ISSUE THREAD

**Issue by sabflik** [mapstruct/mapstruct#2113]
### Description
I've got a generic interface with common mappings defined that my mapper interfaces extend.
I've also written test mappers that extend this same generic interface.
The problem I'm facing is that the MapperImpl classes being generated for mappers in the main directory are different than those generated for the tests, even though they both extend the same generic interface. 
The test MockMapperImpl seems to be ignoring the `@Mapper` annotation. However, when I copy over the same generic interface into the test directory, then the test MockMapperImpl class is being generated correctly.

**build.gradle**
```
dependencies {
    implementation("org.mapstruct:mapstruct:1.3.1.Final")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.3.1.Final")
    testAnnotationProcessor("org.mapstruct:mapstruct-processor:1.3.1.Final")
}
```

**Generic interface**
```
public interface GenericMapper<T extends Base> {
    @Mapping(target = "uuid")
    T map(UUID uuid);
}
```

**Concrete Mapper in test dir**
```
@Mapper
public interface MockMapper extends GenericMapper<Mock> {
}
```

**Generated test MapperImpl when GenericMapper is in src/main/ dir (wrong)**
```
@Generated
public class MockMapperImpl implements MockMapper {
    @Override
    public Mock map(UUID arg0) {
        if ( arg0 == null ) {
            return null;
        }
        Mock mock = new Mock();
        return mock;
    }
```

**Generated test MapperImpl when GenericMapper is in src/test/ dir (correct)**
```
@Generated
public class MockMapperImpl implements MockMapper {
    @Override
    public Mock map(UUID uuid) {
        if ( uuid == null ) {
            return null;
        }
        Mock mock = new Mock();
        mock.setUuid( uuid );
        return mock;
    }
```

**Comment by filiphr** [comment]
This is not a bug and it works correctly. Your main classes are compiled without `--parameters` which means that Java will replace the names of the method parameters with `arg0`, `arg1`, etc. 

The classes from the `src/main` dir are like classes in a different jar to the compiler. MapStruct sees what the compiler sees.

**Comment by sabflik** [comment]
Oh I see.. thank you, I'll fix my build gradle!
