### ISSUE TITLE
Recommended solution for avoiding Cyclic mappings does not work with Protobuf (Builder pattern)

### ISSUE THREAD

**Issue by TriXXeD** [mapstruct/mapstruct#2114]
Hi, the below issue is based on the example for context in the documentation for avoiding cyclic references using @Context, https://mapstruct.org/documentation/stable/api/org/mapstruct/Context.html (Similar example exists in the mapstruct example repo).

Issue arises if the target entity, happens to enforce the builder pattern, which protocol buffers do, as a result, the generated code, picks up the wrong class using `@TargetType Class<T>` - and picks up the builder instead.

This is the @BeforeMapping function as per the documentation:
`@BeforeMapping
    public <T> T getMappedInstance(Object source, @TargetType Class<T> targetType) {
        return (T) knownInstances.get(source);
    }`

And here is the generated code, for checking the identity map:
`TranslationPB target = context.getMappedInstance( translation, Builder.class );
        if ( target != null ) {
            return target;
        }`
N.B `Builder.Class` references `TranslationPB.Builder.Class`

This code cannot actually compile, due to incompatiable types, in order for it to work, the following should have been generated instead:
`TranslationPB target = context.getMappedInstance( translation, TranslationPB.class );
        if ( target != null ) {
            return target;
        }`

**Comment by filiphr** [comment]
This is the same as https://github.com/mapstruct/mapstruct/issues/1454. `@BeforeMapping` with `@TargetType` the original class is still not done.
