### ISSUE TITLE
Cannot map enum argument to target enum property with same type

### ISSUE THREAD

**Issue by v1nc3n4** [mapstruct/mapstruct#2117]
Hello,
I'm not sure it is an issue or an unsupported use case.
It seems it is not possible to map an enum argument to a target object property, with the same enum type. The code below produces error `Can't generate mapping method from enum type to non-enum type.`
```java
import java.nio.file.AccessMode;

public class Target {
    public AccessMode accessMode;
    // other properties
}

@Mapper
public CustomMapper {
    @Mapping(target = "accessMode", source = "accessMode)
    // ... other mapping annotations for 'source' object properties.
    Target toTarget(AccessMode accessMode, Source source);
}
```
When I comment the `@Mapping(...)` line and remove the `accessMode` argument, the mapper is successfully generated. I can also map the enum value if I wrap it in a class and replace the argument with an instance of this class.
What is the correct way to map enum arguments into target objects?
Thanks in advance for your help!
BR,
Vincent

**Comment by filiphr** [comment]
Which version of MapStruct are you using? I think that we relaxed this error in 3.4.0.Beta1. 

If you switch the parameters in the method it should work without a problem as well.

**Comment by filiphr** [comment]
I've added a test case for this and it works as expected on 1.4.0.Beta1.

**Comment by v1nc3n4** [comment]
Hi @filiphr,
Sorry for the late answer, I finally didn't have to do such mapping because our need changed, so the issue I was facing is not blocking anymore, for me. I was using release 1.3.1.Final.
Thank you for your quick answer, solution, and help!
BR,
Vincent
