### ISSUE TITLE
@AfterMapping not invoked when mapping from abstract classes

### ISSUE THREAD

**Issue by mjarosie** [mapstruct/mapstruct#2118]
### Issue descripition
When mapping from a base class extending an abstract class, I'm trying to use `@AfterMapping` to put a parent "back-reference" in the nested object contained within the target object.

Having the following classes (to see the full code reproducing the issue, see [this repository](https://github.com/mjarosie/mapstruct-abstract-aftermapping-issue)):

#### Dto classes
```
public abstract class AnimalDto {
    private Long id;
}
```

```
public class DogDto extends AnimalDto {
    private Long weight;
    private Set<String> owners;
}
```

#### Database entities
```
public class Animal {
    private Long id;
    private Long weight;
    private String name;
    private Set<OwnersPair> owners;
}
```

```
public class OwnersPair {
    Animal animal;  // Back-references the "parent" class.
    String name;
}
```

I want to map `DogDto` to `Animal` and put the "back-reference" after the mapping is performed.
As abstract mapping is not yet supported out of the box (https://github.com/mapstruct/mapstruct/issues/366), [I'm calling `instanceof`](https://github.com/mjarosie/mapstruct-abstract-aftermapping-issue/blob/master/src/main/java/com/example/demo/mapper/AnimalMapper.java#L17) to determine which base mapper should be used:

```
@Mapper
public abstract class AnimalMapper {
    public Animal toDbEntity(AnimalDto animalDto) {
        if (animalDto instanceof DogDto) {
            return toDbEntity((DogDto) animalDto);
        }

        return null;
    }

    public abstract Animal toDbEntity(DogDto animalDto);

    protected Set<OwnersPair> mapOwners(Set<String> owners) {
        return owners
                .stream()
                .map(o -> OwnersPair
                        .builder()
                        .animal(null) // Set null for now to set it later in @AfterMapping
                        .name(o)
                        .build()
                )
                .collect(Collectors.toSet());
    }

    @AfterMapping
    protected void afterAnimalMapping(@MappingTarget Animal animal) {
        // Put a "back-reference" to the animal.
        animal.getOwners().forEach(o -> o.setAnimal(animal));
    }
}
```

### Current behaviour
Unfortunately, [`afterAnimalMapping`](https://github.com/mjarosie/mapstruct-abstract-aftermapping-issue/blob/master/src/main/java/com/example/demo/mapper/AnimalMapper.java#L39) is not used in the mapping from `DogDto` to `Animal` generated by mapstruct.

### Expected behaviour
I'd expect it to be called at the end of mapping from `DogDto` to `Animal`.

**Comment by filiphr** [comment]
Thanks for the reproducal.

I see that you are using Lombok and your classes have builders. 

When using builders lifecycle methods don't yet work when the `@MappingTarget` is the generated type. See https://github.com/mapstruct/mapstruct/issues/1454.

Can you try removing the Lombok builder and see if it works? Closing this as it would be fixed once #1454 is done
