### ISSUE TITLE
Enum to String mapping generated code cause build failure

### ISSUE THREAD

**Issue by luisfigomisk** [mapstruct/mapstruct#2121]
Hi,
I'm using the Mapstruct version 1.4.0.Beta1 because I need immutable type mapping with constructors, and I exprerienced the following issue.
I have an enum field, what I want to map into String, for example:
```java
public enum Enum { 
	VALUE1, 
	VALUE2 
}

public class ObjectA {  

	private Enum enumProp;

	public Enum getEnumProp() {
		return enumProp;
	}
}

public class ObjectB {

	private String enumString;

	public ObjectB(String enumString) {
		this.enumString = enumString;
	}
}
```

I defined a mapping from ObjectA to ObjectB:
```java
@Mapper
public interface AToBMapper {

	@Mapping(source = "enumProp", target = "enumString")
	ObjectB aToB(ObjectA objectA);
}
````
and the generated code:
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor"
)
public class AToBMapperImpl implements AToBMapper {

    @Override
    public ObjectB aToB(ObjectA objectA) {
        if ( objectA == null ) {
            return null;
        }

        String enumString;

        if ( objectA.getEnumProp() != null ) {
            enumString = objectA.getEnumProp().name();
        }

        ObjectB objectB = new ObjectB( enumString );

        return objectB;
    }
}
```
This means I get an build error: 
`Error:(22,40) java: variable enumString might not have been initialized`
I experienced same behavior if the source field type is `Integer`, but the target is just `int`, the object which injected into the constructor is not initialized.

I found workaround but should be better, if the generating always generate compiling code.

Thanks in advanced!

Best Regard,
G

**Comment by filiphr** [comment]
Thanks a lot for the feedback. It is extremely valuable to us so we can iron out the small details before the final release. Please let us know if you experience other issues as well.

I am 99% sure that this is fixed on master via https://github.com/mapstruct/mapstruct/commit/da37d401520ee32889f706cf06308a9ac95338e2. I am leaving this issue open so we can add a test case with your example.
