### ISSUE TITLE
Mapping a value wrapped in a list generates invalid code (stringToXmlGregorianCalender will be added)

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct#2122]
I really don't know how to title this issue.. but I found a strange error similar to a really old issue that we had in the past (#328).

Was testing with 1.4.0.Beta1, had a quick test and it also exists in 1.3.1.Final

Code:

```java
@Mapper
public interface TestMapper {
    @Mapping(target = "embeddedTarget", source = "value")
    Target toTarget(Source source);

    EmbeddedTarget toEmbeddedTarget(String value);
    
    default <T> List<T> singleEntry(T entry) {
        return List.of(entry);
    }

    @Data
    class Source {
        String value;
    }

    @Data
    class Target {
        List<EmbeddedTarget> embeddedTarget;
    }

    @Data
    class EmbeddedTarget {
        String value;
    }
}
```

The generated method looks like this:

```java
    @Override
    public Target toTarget(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        target.setEmbeddedTarget( singleEntry( stringToXmlGregorianCalendar( source.getValue(), null ) ) );

        return target;
    }
```

_(+ the usual `DatatypeFactory` stuff and `stringToXmlGregorianCalender` built-in method)_

In case such a (crazy) mapping is possible I would expect the `toEmbeddedTarget(String)` method will be used. At least this method was generated correctly... and if the mapping is not possible.. as always an appropriate error message and no invalid code :)

**Comment by sjaakd** [comment]
This definitely does not seem right? @chris922, did you investigate the 2 step mapping mechanism?

**Comment by sjaakd** [comment]
Perhaps you can make a reproducer en put that in a PR so that we can look together if you want..

**Comment by chris922** [comment]
Good idea! PR for a reproducer is there.

 I haven't yet investigated where the issue starts... but interesting to see that the stringToXmlGregorianCalender was also used for #328, maybe somewhere is a list from which the first item will be used?!

**Comment by sjaakd** [comment]
I'll try to have a good look at it tomorrow. I have included code to avoid A -> Object, Object -> B the last time (if I remember correctly) in 2 step mappings. Today I've got other appointments 😄

**Comment by sjaakd** [comment]
@chris922 .. @filiphr did a review.. So I merged in our joint code (want to make a new release later and need to fix some other stuff)

**Comment by sjaakd** [comment]
find by PR #2122 @filiphr .. thanks for reviewing
