### ISSUE TITLE
How to generate mapping source/target in txt file at buildtime ?

### ISSUE THREAD

**Issue by jaadlani** [mapstruct/mapstruct#2126]
Hello guys,

I need to generate somewhere (maybe in directory "target/generated/annotations/..../ MyMapper.txt at buildtime) all the sources/target by mapper.

to then be able to read the txt files at runtime

example : 

```
@Mapper
public interface MyMapper {
        @Mapping(target = "a", source = "source.x.y.z")
        @Mapping(target = "b", source = "source.r.s.t")
        @Mapping(target = "c", source = "source.o.p.q")
	MyObject map(MySource source);
}
```
Content of the generated file : target/generated/annotations/MyMapper.txt

```
mypackage.MyObject.a=mypackage.MySource.x.y.z
mypackage.MyObject.b=mypackage.MySource.r.s.t
mypackage.MyObject.c=mypackage.MySource.o.p.q
```

how can i do that?

thank you in advance for your help

stackoverflow : https://stackoverflow.com/questions/62519032/mapstruct-how-to-generate-mapping-source-target-in-txt-file-at-build-time

**Comment by filiphr** [comment]
@jaadlani please do not cross post questions here and StackOverflow. We are monitoring both places and answering accordingly. I've already answered on StackOverflow
