### ISSUE TITLE
Allow the generation of package-private fields for Inject when using Quarkus

### ISSUE THREAD

**Issue by hguerrero** [mapstruct/mapstruct#2127]
When using Quarkus 1.4 the generated code for mapstruct is throwing the following message: 

`Found unrecommended usage of private members (use package-private instead) in application beans:`

This is because the `@Inject` field for the Mappers is using `private` fields, this is discouraged in Quarkus according to the CDI guide[1].

So, there should be a way to make it default to use package-private fields or allow a configuration to chose this option.

[1] https://quarkus.io/guides/cdi-reference#native-executables-and-private-members

**Comment by filiphr** [comment]
I saw that Quarkus can work with [Constructor Injection](https://quarkus.io/guides/cdi-reference#simplified-constructor-injection) as well. Can you please try `@Mapper(injectionStrategy = InjectionStrategy.CONSTRUCTOR)`?

**Comment by hguerrero** [comment]
Yes that worked!

**Comment by filiphr** [comment]
Is it ok if we close this now? If the constructor injection is not enough and there is something more specific that we can do about Quarkus we can always add a new `componentModel` or maybe even create a new extension repo similar to the [mapstruct-spring-extensions](https://github.com/mapstruct/mapstruct-spring-extensions)

**Comment by hguerrero** [comment]
Agreed @filiphr I'll close this and keep watching for any other issue.
