### ISSUE TITLE
Question: is it possible to change the naming of variables in the generated code?

### ISSUE THREAD

**Issue by otbe** [mapstruct/mapstruct#2142]
Hi.

We currently try to map our data classes to some external generated classes.
The target classes look like this:
```java
@Builder //lombok builder
@Getter
class Contact {
   _PhoneNumber phone;

  @Builder
  @Getter
  class _PhoneNumber {
    // ....
  }
}
```

in a mapper like this
```java
abstract Contact map(InternalContact contact)
```
mapstruct will generate code like this
```java
_PhoneNumberBuilder _PhoneNumber = _PhoneNumber.builder();
```

We assume that the variable name "_PhoneNumber" is generated by lowercasing the first letter of the class name. Is there a way to configure this behavior somehow? We know `_` is not a good convention but thats what we have right now 🙃

Thanks!

We tried the following versions 1.3.1.Final and 1.4.0.Beta1

**Comment by sjaakd** [comment]
You can't configure that. However, MapStruct should select non conflicting names. I guess, that having a class named like this was never on our radar..

Having said that.. perhaps we should offer a way to configure the `_`

**Comment by filiphr** [comment]
I don't think that we need to configure this. However, I think that we can remove leading `_` from names. It wouldn't be too difficult. I think it needs to be done [here](https://github.com/mapstruct/mapstruct/blob/b323c363935ba61cb8073eae72587ffd8b724031/processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java#L168). 

Just out of curiosity, why do you need to change the name of the generated variable name? Event though it is the same as the class it is still a valid name 😄.

**Comment by otbe** [comment]
Hi @filiphr 

I dont know If I get you right, but in the generated mapper code this leads to build errors like:

```
Error:(164, 56) java: cannot find symbol
  symbol:   method builder()
  location: variable _PhoneNumber of type Contact._PhoneNumber._PhoneNumberBuilder
```
and also my IDE shows something there
<img width="747" alt="Screenshot 2020-07-07 at 23 30 16" src="https://user-images.githubusercontent.com/3391052/86845888-6e8e1500-c0aa-11ea-9c7c-842af84f6545.png">

**Comment by filiphr** [comment]
You are right. We are going to remove all leading `_` before decapitalizing to create the name.
