### ISSUE TITLE
Mapping warning when using @Singular and @Builder with lombok

### ISSUE THREAD

**Issue by Tiller** [mapstruct/mapstruct#2147]
Hello, I am not entirely sure whether this is a "real" issue or not, but I haven't found anything related in the backlog so I'll just add it

Let's consider the following class:
```java
@Builder
class Car {
  @Singular
  List<Wheel> wheels;
}
```
It'll generate a builder looking like:
```java
class CarBuilder {
    List<Wheel> wheels = new ArrayList<>();

    CarBuilder wheels(List<Wheel> wheels) {
        this.wheels.clear();
        this.wheels.addAll(wheels);
        return this;
    }
    
    CarBuilder wheel(Wheel wheel) {
        this.wheels.add(wheel);
        return this;
    }
}
```

Then, when trying to map this class to another bean having the same `wheels` attribute, using for example:
```java
@Mapper
interface CarMapper {
    OtherBean map(Car car);
}
```

It'll result in the map method giving the following warning: `Unmapped target property: "wheel".` and we need to add `@Mapping(target = "wheel", ignore = true)` to disable the warning message.

So, I don't know how much of it is an "issue" and maybe it's just the way it is and nothing can be done about it. But I wanted to report it in case it was an easy fix :)

**Comment by filiphr** [comment]
I think that this would be extremely difficult to solve.

MapStruct has the concept of adders. And can use them properly. However, those methods have to be prefixed with `add`. So in your case if the method is named `addWheel` then it will work correctly.

We also don't look at the non public fields of the class and rely on public methods only to determine property names. In your case `wheel` can very much be a single property and just by looking at the method name it is not clear whether there is a property named `wheel` or whether this will add a wheel to the `wheels`.

If you have some idea for how we can improve this feel free to share it with us. Is the `wheel` method annotated with something in the Lombok generated bytecode? A Lombok specific `AccessorNamingStrategy` might be able to use that.

**Comment by Tiller** [comment]
Lombok does not add any particular annotation on the generated method unfortunaly.

One workaround is then to use `@Singular("addWheel")` to force the method name and adhere to the mapstruct convention.

Regarding having any idea on how to solve this... Not really :D One thing that *might* be possible, is to scan the getter of the bean (not of its builder) and then only consider (or raise warning) builder method that match a bean's method name. But I think that'd be very wobbly

**Comment by filiphr** [comment]
Something like this can probably go into some kind of a Lombok extension where we can do some more inspections based on the lombok annotations on the fields. 

We are currently spread really thin, so if there is someone from the community willing to take up the lead for a Lombok extension we are more than willing to help out.

I will close this in the meantime, because in my opinion the benefits of this are not that big.

Thanks for the understanding @Tiller
