### ISSUE TITLE
Compilation fails for mappers extending an interface based on generics (MapStruct 1.4.0.Beta2)

### ISSUE THREAD

**Issue by berryh** [mapstruct/mapstruct#2153]
Hello,

I am trying out the new beta version of MapStruct (1.4.0.Beta2) and I'm running into what seems like a bug to me. I am using an interface which serves as a base definition for converting types and their list forms using generics. This used to work just fine in MapStruct 1.3.1.Final, but doesn't compile in neither of the new beta versions.

See the following project for a simple demo: https://github.com/berryh/Mapstruct140Beta2ListMapperInterfaceTest

**Comment by filiphr** [comment]
Thanks for raising this @berryh. I was trying out your example and I realised that the reason why it doesn't work is in purpose.

You are using `IterableMapping#qualifiedByName`, but there are no methods qualified for that. Have a look at the behaviour changes in https://github.com/mapstruct/mapstruct/releases/tag/1.4.0.Beta1. From 1.4 the qualifiers are more strict and if you have defined a qualifier, but nothing exist, there will be an error.

You should either:

* remove `qualifiedByName`
* Annotated the single mapping methods (both in `ListConverter` and the places where they are overridden) with the appropriate `@Named` qualifier.

**Comment by berryh** [comment]
Thanks for the response. I think the qualifier changes make sense and it explains why the example project breaks. I've also played around with your suggestions and they seem to work.
