### ISSUE TITLE
customize thrown Exception when Enum Mapping fails

### ISSUE THREAD

**Issue by mickroll** [mapstruct/mapstruct#2169]
It would be nice to be able to configure the Mapper to throw a custom Exception for an unknown enum value, instead of an `IllegalArgumentException`.

Possible solution:
@filiphr:
> We've added EnumNamingStrategy in 1.4. Perhaps we can rename that to EnumMapingStrategy and add a method that would return the TypeElement of the exception that it should be thrown.

For now we manipulated `ValueMappingMethod.ftl` in the classpath, but this is an internal file, hence not the way to go: mapstruct might switch away from using freemarker templates in the near future.

**Comment by filiphr** [comment]
Another alternative (giving more control) is to also expose this on the `@EnumMapping`

e.g.

```
@EnumMapping(defaultArgumentException = RuntimeException.class)
```

the `defaultArgumentException` doesn't have to have that name :). 

Another alternative could also be to do it via `@ValueMapping` by exposing a new option (`targetException`) and reuse the `MappingConstants.ANY_REMAINING` and `MappingConstants.ANY_UNMAPPED`. With this someone can even throw an exception.

Not sure which one is better. Most likely my first idea works best together with the `@EnumMapping`

**Comment by mickroll** [comment]
I like where this is going. Way better than overriding a whole template!

Is there a way to configure this behaviour at a central point? Like a `@MapperConfig`? That would be neat. Write one line and have all the mappers behave the same way, throw the same "UnknownEnumMappingException".

**Comment by filiphr** [comment]
There will be 4 ways you can override this (from highest to lowest priority):

* Via `@EnumMapping` for a single value mapping method
* Via `@Mapper` for all value mapping methods in a mapper
* Via `@MapperConfig` 
* Via an SPI
