### ISSUE TITLE
Missing import in generated mapping class when using generic mapper interface

### ISSUE THREAD

**Issue by myatmin** [mapstruct/mapstruct#2170]
When using generic mapper interface (eg: `EntityMapper` in below) is causing missing import.

### Entity & DTO
```java
@Setter
@Getter
@AllArgsConstructor
class Address{ 
    private String zipCode;
    List<Person> person;
}

@Setter
@Getter
@AllArgsConstructor
class Person { 
    String name;
}

@Data
class AddressDto {
    private String zipCode;
    List<PersonDto> person;
}

@Data
class PersonDto {
   String name;
}

```
### Mappers
```java
public interface EntityMapper<D, E> {
    E toEntity(D dto);
    D toDto(E entity);
    List<E> toEntity(List<D> dtoList);
    List<D> toDto(List<E> entityList);
}

@Mapper(uses = {PersonMapper.class})
public interface AddressMapper extends EntityMapper<AddressDto, Address> {
}

@Mapper
public interface PersonMapper extends EntityMapper<PersonDto, Person> {
}

```
### Result
Generated implementation mapper class `AddressMapperImpl` has no import of `Person` class.

**Comment by sjaakd** [comment]
Thanks for reporting! I did some redesign in this area. Could be I missed a scenario. Will fix in next beta

**Comment by filiphr** [comment]
The problem is actually due to the constructor mapping and not because of the generic mapper interface.  Anyways, we've created PR #2172 to fix this.

In the meantime you can always use `@Mapper(imports = { Person.class, PersonDto.class })` to circumvent the compilation problem.
