### ISSUE TITLE
NoClassDefFoundError: org/mapstruct/factory/Mappers

### ISSUE THREAD

**Issue by j782282271** [mapstruct/mapstruct#2171]
I try to use mapstruct 1.4.0.Beta1，but I got this error:NoClassDefFoundError: org/mapstruct/factory/Mappers

![image](https://user-images.githubusercontent.com/26477120/88802922-4e033780-d1de-11ea-990e-b1bd8fe1c64a.png)

And this is my pom:
![image](https://user-images.githubusercontent.com/26477120/88805159-66288600-d1e1-11ea-9784-450dde5476ba.png)

**Comment by j782282271** [comment]
And this is my pom:
![image](https://user-images.githubusercontent.com/26477120/88804941-29f52580-d1e1-11ea-8ead-9f6d407be323.png)

**Comment by j782282271** [comment]
And this my pom:
![image](https://user-images.githubusercontent.com/26477120/88804973-34afba80-d1e1-11ea-834f-1650b910ef6e.png)

**Comment by filiphr** [comment]
How does your dependency tree look like? Is there by any chance some other mapstruct version? Or is there `mapstruct-jdk8` there perhaps?

**Comment by j782282271** [comment]
> How does your dependency tree look like? Is there by any chance some other mapstruct version? Or is there `mapstruct-jdk8` there perhaps?

I have excluded all mapstruct-jdk8 specially. It is strange

**Comment by filiphr** [comment]
Yes it is strange. However, we can't help if we can't reproduce it. Can you please try to create a repository where this can be reproduced?
