### ISSUE TITLE
Redundant exception wrapping in nested generated method

### ISSUE THREAD

**Issue by yoniwg** [mapstruct/mapstruct#2174]
- [V] Is this an issue (and hence not a question)? 

Hi All,
I am using MapStruct v1.3.1.Final

The guide [says](https://mapstruct.org/documentation/stable/reference/html/#exceptions) that you can make the generated method to throw a checked exception by simply adding a `throws` declaration.

But in a nested generated method it doesn't seem to work.

For example, let say I have the following (All persistence and Spring annotations are just for the sake of the example):

```
public class User
{
    @Id
    UUID id;
    @OneToOne
    private Address address;
    
    // getters & setters
}

public class Address
{
    @Id
    UUID id;
    @OneToMany
    private City city;
    private String street;

   // getters & setters

}

public class City
{
    @Id
    UUID id;   
    String name;

   // getters & setters
}
```
And a DTO:
```
public class UserDto
{
    private String name;

    private String city;

    private String street;

    // getters & setters
}
```

The Mapper:
```
@Mapper
public abstract class UserMapper
{

    @Autowired
    private CityRepository cityRepository;

    @Mappings(
        @Mapping(source = "city", target = "address.city")
    )
    protected abstract User map(UserDto userDto) throws CityNotFoundException;

    protected City map(String city) throws CityNotFoundException {
        return cityRepository.findByName(city); // throws CityNotFoundException
    }
}
```

Now, the generated mapper implementation is:
```
public class UserMapperImpl extends UserMapper {

    @Override
    protected User map(UserDto userDto) throws CityNotFoundException {
        if ( userDto == null ) {
            return null;
        }

        User user = new User();

        user.setAddress( userDtoToAddress( userDto ) );

        return user;
    }

    protected Address userDtoToAddress(UserDto userDto) {
        if ( userDto == null ) {
            return null;
        }

        Address address = new Address();

        try {
            address.setCity( map( userDto.getCity() ) );
        }
        catch ( CityNotFoundException e ) {
            throw new RuntimeException( e );  // This warpping is redundant
        }

        return address;
    }
}
```

As you can see it wraps the `CityNotFoundException` with a `RuntimeException` even though I explicitly declared both of the mappers with `throws CityNotFoundException`

Expected behavior:
Add a `throws CityNotFoundException` declaration to the `userDtoToAddress` method, and don't wrap the exception.

**Comment by filiphr** [comment]
What should we do in this case @sjaakd? Should we propagate the exception to all the generated methods?

**Comment by sjaakd** [comment]
> What should we do in this case @sjaakd? Should we propagate the exception to all the generated methods?

I guess so.. that would make sense. So if you if you've got an object tree 2 levels deep (level 1 and 2 generated) I would expect a method throwing an exception on level 3 used by level 2 is propagated all the way up. Its of course to the user to handle this on level0 (the defined mapping method)
