### ISSUE TITLE
Mapping to generic class via constructor does not work (1.4.0.Beta3)

### ISSUE THREAD

**Issue by ruedigerk** [mapstruct/mapstruct#2177]
When using the current MapStruct 1.4.0.Beta3 and trying to map to a generic class via its constructor, I get an error message. See here for a code example that reproduces the error:

```
import org.mapstruct.Mapper;

@Mapper
interface MapstructGenericsTest {

  Generic<String> doesNotWork(NonGeneric nonGeneric);

  class NonGeneric {
    public String value;
    public String getValue() {
      return value;
    }
  }

  class Generic<T> {
    private final T value;
    public Generic(T value) {
      this.value = value;
    }
    public T getValue() {
      return value;
    }
  }
}
```

MapStruct raises the following error: 

> Error: Can't map property "java.lang.String value" to "T value". Consider to declare/implement a mapping method: "T map(java.lang.String value)".

Mapping to an equivalent class that has a setter method, works. So only the new "constructor mapping" feature seems to be affected, example:

```
@Mapper
interface MapstructGenericsTest {

  GenericBySetter<String> doesWork(NonGeneric nonGeneric);

  class NonGeneric {
    public String value;
    public String getValue() {
      return value;
    }
  }

  class GenericBySetter<T> {
    private T value;
    public void setValue(T value) {
      this.value = value;
    }
    public T getValue() {
      return value;
    }
  }
}
```

**Comment by filiphr** [comment]
Thanks for raising the issue @ruedigerk. I moved it to the mapstruct repository. I agree with you that this should work.

We are going to fix this for the next release. However, can you please try putting the `Generic<T>` in another wrapper class instead of as a return type, maybe it will work

**Comment by ruedigerk** [comment]
Thanks a lot for looking into this. I worked around the issue for now by changing the problematic class to not use generics.
