### ISSUE TITLE
Some suggestions on idea plugins

### ISSUE THREAD

**Issue by zfavourite99** [mapstruct/mapstruct#2179]
I use MapStruct in Intellij IDEA. And installed the plugin. 
Although it is already great, I think it can be used better. Can you improve it?

issues:
some properties not mapping,but there has no warning.
![image](https://user-images.githubusercontent.com/2630290/90214671-da8f3600-de2b-11ea-8d8d-e874f7cf7de6.png)

some idea:
1.properties show not with `string`. like spring `cacheable` annotation.

![image](https://user-images.githubusercontent.com/2630290/90214029-e8dc5280-de29-11ea-9de2-68f85a35bbf9.png)
![image](https://user-images.githubusercontent.com/2630290/90214074-03163080-de2a-11ea-8cbe-268cbd1e8d73.png)

2.Is it possible not to generate source files? like lombok (Data  annotation). or generated source files's path can set (like querydsl).And querydsl can just run the plugin but not need complie all project.

![image](https://user-images.githubusercontent.com/2630290/90214867-74ef7980-de2c-11ea-9444-0e38faa0976e.png)
![image](https://user-images.githubusercontent.com/2630290/90214534-62287500-de2b-11ea-8d25-af37af5bdc55.png)

3.if source property's name equals target property's name. Can it be mapped automatically?

Just personal suggestions. Expect mapstruct to get better and better.

**Comment by filiphr** [comment]
Thanks for raising this issue @zfavourite99.

I'll answer your points one my one

Issues:

>some properties not mapping,but there has no warning.

Please raise a bug with your example code in the [mapstruct/mapstruct-idea](https://github.com/mapstruct/mapstruct-idea) repository

Ideas:

>1.properties show not with string. like spring cacheable annotation.

This is also about the IntelliJ plugin, so please create a separate issue in [mapstruct/mapstruct-idea](https://github.com/mapstruct/mapstruct-idea). I am not sure I understand this though.

>2.Is it possible not to generate source files? like lombok (Data annotation). or generated source files's path can set (like querydsl).And querydsl can just run the plugin but not need complie all project.

MapStruct is an annotation processor, so it is invoked as part of the Java compilation of the project. We are not going to develop plugins that are working outside of the Java compilation. You can control the directory with via the maven compiler plugin though. See https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#generatedSourcesDirectory

>3.if source property's name equals target property's name. Can it be mapped automatically?

This is already the case. Please create a separate issue if you have problems with this.
