### ISSUE TITLE
Suppress warnings functionality

### ISSUE THREAD

**Issue by edekovacsgalambos** [mapstruct/mapstruct#2180]
If the mapper has any collection and uses a @Context which holds already converted objects, maptsruct generates code something like this:
 `Set<T> target = context.getMappedInstance( set, Set.class );` 
this unfortunately leads to "warning: [unchecked] unchecked conversion" compiler warnings. Which in non generated code could be easily suppressed with : `@SuppressWarnings("unchecked")`, but using maptsruct I can't find any way to do this.
So would be nice somehow to suppress these compiler warnings in the generated code too.
Despite of this maptsruct is very powerful :)

**Comment by edekovacsgalambos** [comment]
Adding those additional parameters to @BeforeMapping @AfterMapping` sounds good to me!
If it helps here is the code which I used:https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-mapping-with-cycles/src/main/java/org/mapstruct/example/mapper/CycleAvoidingMappingContext.java
actually its from mapstruct examples :)
So the problem comes up when  `getMappedInstance` is called with T where T is substiuated with some Set<K> (where K is whatever class). So basically when mapping properties of type Set and using the @Context feature.

**Comment by sjaakd** [comment]
@edekovacsgalambos lets check out the opinion of @filiphr .. If he agrees, would you be willing to help out by means of PR?

**Comment by filiphr** [comment]
I have mixed feelings about suppressing any potential warnings in the generated code.

In this particular case it is because of the `@Context`, but there might be other reasons why something like this is happening and adding the suppressions arbitrary by MapStruct in the generated code might lead to unexpected errors.

To fix your particular problem, you might think in limiting the generic parameter in the `CycleAvoidingMappingContext`. Do you really need to apply the cycle check for collections? Do you need to do it for all objects? 

e.g. you can do something like:
```
public class CycleAvoidingMappingContext {
    private Map<Object, Object> knownInstances = new IdentityHashMap<Object, Object>();

    @BeforeMapping
    public <T extends BaseEntity> T getMappedInstance(Object source, @TargetType Class<T> targetType) {
        return (T) knownInstances.get( source );
    }

    @BeforeMapping
    public <T extends BaseEntity> void storeMappedInstance(Object source, @MappingTarget T target) {
        knownInstances.put( source, target );
    }
}
```

You can limit the objects that you support for cycles by doing this.

**Comment by sjaakd** [comment]
I agree with @filiphr. We discussed this and I guess it's a can of wormes. More scenarios will pop up, while it indicates there is an (in this case, probably, avoidable) issue.

**Comment by feczkob** [comment]
> e.g. you can do something like:

Just to be clear, do you recommend to create a class hierarchy to overcome this issue?
To apply this approach, it assumes that your entity and business classes (assuming that you map in both directions) either implement a common interface or share a common ancestor. This allows you to define a generic type parameter <T> that represents any class derived from or implementing that common interface/ancestor. By doing so, the `getMappedInstance` function could be used for all such classes, excluding collections.

Do I understand correctly?

**Comment by filiphr** [comment]
@feczkob how you implement this is entirely up to you. The approach I proposed is using an `Object` so it doesn't assume that you need to have common interfaces.
