### ISSUE TITLE
Mapstruct breaks Gradle task caching functionality

### ISSUE THREAD

**Issue by remal** [mapstruct/mapstruct#2194]
**Mapstruct version: 1.4.0.CR1**

I have a quite simple Gradle project with mapstruct.

Mapstruct adds `@Generated` annotation with `date` attribute. The attribute's value changes on each build, so Gradle doesn't mark `compileJava` task as `UP-TO-DATE` and recompiles sources on each build.

Generated class by Mapstruct:
```java
package pkg;

/*
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-09-03T20:04:20+0300", // <- this line changes during each build
    comments = "version: 1.4.0.CR1, compiler: IncrementalProcessingEnvironment from gradle-language-java-6.6.1.jar, environment: Java 11.0.2 (Oracle Corporation)"
)
*/
class ConverterImpl implements Converter {
    // ...
}
```

 

When I added `doLast` Gradle step that removes `date` attribute, Gradle started caching `compileJava` task and marking as `UP-TO-DATE`:
```groovy
tasks.withType(JavaCompile) {
    doLast {
        options.annotationProcessorGeneratedSourcesDirectory?.traverse { File file ->
            if (!file.isFile() || !file.name.endsWith('.java')) {
                return;
            }

            String originalContent = file.text
            String content = originalContent
                .replaceAll(/(@Generated\([^)]*?)\s*date\s*=\s*"[^"]*",?/, '$1')
            if (content != originalContent) {
                file.text = content
            }
        }
    }
}
```

 

I see two options here:
1. Stop generating `date` attribute at all
1. Add an annotation processor option, that allows to disable `date` attribute generation

**Comment by filiphr** [comment]
There is an annotation processor option. That is `mapstruct suppressGeneratorTimestamp`. You can find all options [here](https://mapstruct.org/documentation/stable/reference/html/#configuration-options) in the documentation.

Another question, why is the processor even invoked a second time if nothing has changed? I thought that Gradle will not invoke the processor if there are no changes needed.

**Comment by remal** [comment]
`mapstruct.suppressGeneratorVersionInfoComment` helped, thanks!

I think Gradle invocation the processor a second time is a part of Gradle incremental compilation feature. I'm not totally sure, so I'll investigate it in the nearest future.

I'm closing this issue.
