### ISSUE TITLE
Invalid code generated for enum mapping when field name starts with underscore '_'

### ISSUE THREAD

**Issue by ogerardin** [mapstruct/mapstruct#2197]
I'm trying to map to a class where field names that start with an underscore. Some of these fields are enums and their type is an inner enum with the same name, e.g.:
```java
    ...
    private Emtv3Item._06040PortfolioManagement _06040PortfolioManagement;
    ...
    public enum _06040PortfolioManagement {
        R("R"),
    ...
```

> (Background: this class is generated by jsonschema2pojo from a JSON schema where field names start with a digit, hence the leading underscore. While this might not be good practice, it's legal and we have a use case for it)

The mapping code generated by mapstruct 1.4.0.RC1 for these enums is invalid: it uses a variable with the same name as the original field, but without the leading underscore, hence it starts with a digit:
```java
    protected _06040PortfolioManagement m06040PortfolioManagementEnumTo_06040PortfolioManagement(M06040PortfolioManagementEnum m06040PortfolioManagementEnum) {
        if ( m06040PortfolioManagementEnum == null ) {
            return null;
        }
        _06040PortfolioManagement 06040PortfolioManagement;
```

If I try to use mapstruct 1.3.1.Final, the generated enum mapping code is also invalid but for a different reason: the variable has the same name as the enum, which causes problems later: 
```java
   protected _06040PortfolioManagement m06040PortfolioManagementEnumTo_06040PortfolioManagement(M06040PortfolioManagementEnum m06040PortfolioManagementEnum) {
        if ( m06040PortfolioManagementEnum == null ) {
            return null;
        }
        _06040PortfolioManagement _06040PortfolioManagement;
        switch ( m06040PortfolioManagementEnum ) {
            case R: _06040PortfolioManagement = _06040PortfolioManagement.R;

```
-->  `variable _06040PortfolioManagement might not have been initialized`

A solution here is to name the variable anything legal and different from the enum class, e.g.:
```java
        _06040PortfolioManagement _06040PortfolioManagement_var;
        switch ( m06040PortfolioManagementEnum ) {
            case R: _06040PortfolioManagement_var = _06040PortfolioManagement.R;
```

**Comment by filiphr** [comment]
This is an interesting one. We did some fixes in this area with #2142, but we haven't thought about this use case as well.

Most likely we will go with the approach with removing the underscore and digit prefixes from the generated variables.

**Comment by ogerardin** [comment]
> Most likely we will go with the approach with removing the underscore and digit prefixes from the generated variables.

I would suggest **adding** a prefix instead, because otherwise if you have a field named "_0" what do you do then ??

**Comment by filiphr** [comment]
You are right @ogerardin, this is pushing it to the max :). Maybe if we have no more elements, we start with a variable named `a` and try to generate a safe name from there.

What kind of prefix will you suggest?

**Comment by ogerardin** [comment]
> What kind of prefix will you suggest?
Literally anything, but make it configurable !

**Comment by filiphr** [comment]
@ogerardin, we are now stripping both underscores and digits when sanitizing a name. In case the name is only consisted of underscores and digits, then we leave it as is. I would rather wait for an issue about that before going down a path that would make this too complex.

I wouldn't make this configurable, since it is such a low level thing in the code generation, that in my opinion it is not worth it.

**Comment by ogerardin** [comment]
> @ogerardin, we are now stripping both underscores and digits when sanitizing a name. In case the name is only consisted of underscores and digits, then we leave it as is.
My concern is that you need to make sure you address both cases: invalid variable name (1.4.0.RC1) and collision with the enum class name (1.3.1). 
In my experience with generators, it's always better to have a config parameter if you can't make sure you're generating 100% compilable and correct code. For instance, if there had been a param, I wouldn't be stuck right now :)
