### ISSUE TITLE
Provide ability to have a not null check prior to applying an expression

### ISSUE THREAD

**Issue by edougliu** [mapstruct/mapstruct#2200]
It doesn't seem that any of the options for null checking work along with providing an expression.  I'm using 1.3.1-FINAL

@Mapper(componentModel="spring")
public interface RecurringScheduleMapper {
    @Mappings({
            @Mapping(target="adhocDates", expression="java(java.util.stream.Stream.of(recurringSchedule.getAdhocDates().split(\",\", 0)).collect(java.util.stream.Collectors.toList()))")
    })
    RecurringScheduleDto entityToDto(RecurringSchedule recurringSchedule);

}

produces:

        recurringScheduleDto.setAdhocDates( java.util.stream.Stream.of(recurringSchedule.getAdhocDates().split(",", 0)).collect(java.util.stream.Collectors.toList()) );

I need

        if (recurringScheduleDto.getAdhocDates() != null) {
            recurringScheduleDto.setAdhocDates(java.util.stream.Stream.of(recurringSchedule.getAdhocDates().split(",", 0)).collect(java.util.stream.Collectors.toList()));
        }

All the null check strategies either ignore the property with the expression or give an error on generation advising that it can't be used in conjunction with an expression.

Is there some other way of accomplishing this?

**Comment by filiphr** [comment]
This is not possible. When using `expression` we are using the expression as is. There is no way for us to know on what to do a null check.

However, you can achieve the mapping you want with some custom methods.

e.g.

```
@Mapper
public interface CustomMapper {

    RecurringScheduleDto entityToDto(RecurringSchedule recurringSchedule);

    @Named("stringToList")
    List<String> stringToList(String value) {
        if (value != null) {
            Stream.of(value.split(",", 0)).collect(Collectors.toList());
        }

        return null;
    }
}
```

You can achieve the `null` check in the generated code by using `NullValueCheckStrategy` on the mapper (`@Mapper`) or method (`@BeanMapping`) level
