### ISSUE TITLE
How to manage variable shadowing in JAVA with Mapstruct

### ISSUE THREAD

**Issue by Hard-system** [mapstruct/mapstruct#2202]
I did not find a way how to manage this, because I cannot add in Mapstruct variable with the same name as a target which make sense but there is no workaround or at least I did not find any. 
My code:

```
public abstract class CaseDTOBase{

       private Integer version;

       public static void mapFromCaseToCaseDTO(Fall fall, CaseDTOBase caseDTOBase) {
        caseDTOBase.setVersion(fall.getVersion());}
       }
    }
```

```
public class AufCaseDTO extends CaseDTOBase{

  private Integer version;

  public static AufCaseDTO from(AufFall aufFall, Fall fallGemeldetAnPKR) {

  AufCaseDTO aufCaseDTO = AufCaseDTO.builder().version(aufFall.getVersion()).build();

  CaseDTOBase.mapFromCaseToCaseDTO(aufFall.getFall(), aufCaseDTO);

  return aufCaseDTO;
 }
}
```

**As you can see the one variable "version from AufCaseDTO" uses aufFall.getVersion() and the another version from CaseDTOBase variable uses aufFall.getFall().getVersion(), I cannot add both inside of Mapstruct because it says that it does not allow duplicates. How can I make this in MapStruct?**

```
    @Mapping(target = "version", source = "aufFall.version")  
    @Mapping(target = "version", source = "aufFall.fall.version")
    AufCaseDTO from(AufFall aufFall, Fall fallGemeldetAnPKR);
```

**Comment by filiphr** [comment]
I see that you have cross posted this from StackOverflow (https://stackoverflow.com/q/63957233/1115491). Please do not use this issue tracker for asking questions, and do not cross post.

The question has been answered on StackOverflow.
