### ISSUE TITLE
Mapstruct 1.4.0CR: using the „.“ as target property

### ISSUE THREAD

**Issue by javanerd** [mapstruct/mapstruct#2203]
I tried to get the "." operator as target property working, but i get an error during the build process as follows under this configuration:

Spring Boot 2.1.2 (but not important i think)
Lombok 1.18.4
MapStruct 1.4.0.CR1
Java 1.8.0_92
Intellij 2019.3 Ultimate (but not important i think)

Bank class

```
@Data
public class BankEntity {

    private CustomerEntity customer;
}
```

Customer class

```
@Data
public class CustomerEntity {

    private String id;
    private String name;
}
```
CustomerDto class

```
@Data
public class CustomerDto {

    private String id;
    private String name;
}

```

Mapper class

```
public interface CustomerMapper {

    @Mapping(target = ".", source = "bank.customer")
    CustomerDto toDto(BankEntity bank);

}

```

SIMPLE TestCase

```
    @Test
    public void bankToCustomerDtoTest() {
        BankEntity bank = new BankEntity();
        CustomerEntity customer = new CustomerEntity();
        customer.setId("123");
        customer.setName("Smith");
        bank.setCustomer(customer);
        CustomerMapper customerMapper = Mappers.getMapper(CustomerMapper.class);
        CustomerDto dto = customerMapper.toDto(bank);
        System.out.println(dto);
    }

```

Error:(7, 8) java: Internal error in the mapping processor: java.util.NoSuchElementException at java.util.ArrayList$Itr.next(ArrayList.java:854) at org.mapstruct.ap.internal.util.Collections.first(Collections.java:50) at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.handleDefinedMappings(BeanMappingMethod.java:477) at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:184) at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:376) at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:151) at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:122) at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76) at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:283) at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:263) at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:221) at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:156) at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794) at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705) at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91) at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035) at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176) at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170) at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856) at com.sun.tools.javac.main.Main.compile(Main.java:523) at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129) at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138) at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:207) at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:486) at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:338) at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:263) at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:216) at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1328) at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1006) at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1073) at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:967) at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:796) at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:378) at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178) at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:140) at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297) at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130) at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by filiphr** [comment]
I just tried this in our examples with Lombok 1.18.12 and it works correctly. How does your maven or gradle config looks like?

**Comment by filiphr** [comment]
Can you try removing the lombok annotations? If it works without them, then most likely it is a build configuration problem

**Comment by javanerd** [comment]
Will try it without Lombok annos. But will not take place before Monday ;)

**Comment by javanerd** [comment]
Hey. I did remove the Lombok annotations and added normal getter/setter but no changes. I am still getting the error above....

**Comment by filiphr** [comment]
That is really weird. What happens when you try to compile with Maven or Gradle?

**Comment by javanerd** [comment]
Ohhh.... Good advice. I will give it a try....

**Comment by javanerd** [comment]
Well, it's compiling with maven directly. Now i am confused. What could be the reason for that? Intellij?

**Comment by filiphr** [comment]
It seems like IntelliJ is not using the correct version.

Can you please check what does the "Processor path" in "Build, Execution, Deployment" -> Compiler -> "Annotation Processors" and in your module there has? This is in the Settings.

**Comment by javanerd** [comment]
I checked it: This is the entry:

C:\tmp\maven\local-repository\org\mapstruct\mapstruct-processor\1.4.0.CR1\mapstruct-processor-1.4.0.CR1.jar;C:\tmp\maven\local-repository\org\projectlombok\lombok\1.18.4\lombok-1.18.4.jar

**Comment by filiphr** [comment]
So IntelliJ uses the correct version of MapStruct. I really can't explain this. 

Is it possible for you to create a small repository where this can be reproduced? That way I can download IJ 2019.3 and try it out.

**Comment by javanerd** [comment]
Hmmm, I don’t know. It’s our company‘s code base. I only produced some simple sample within our code (customer/bank entity). 

What i found out is that the error also takes place in version 1.3.1FINAL. It’s all about the „.“ operator. If I remove it it works.

What I can offer you immediately is some Remote Desktop session like WebEx etc....to show it to you. To create a repository will take me some time I think.

**Comment by javanerd** [comment]
@filiphr : After the second reboot of my laptop finally i got it working! Yes! Perhaps there was a process hanging or some IntelliJ refresh problem. I suggest to close this issue. Sorry, for stealing your time.

**Comment by filiphr** [comment]
No problem @javanerd, I am glad that the problem got resolved. It indeed felt like IntelliJ using the wrong version of MapStruct.
