### ISSUE TITLE
Where is 'MapperGem'

### ISSUE THREAD

**Issue by BernyGao** [mapstruct/mapstruct#2207]
import org.mapstruct.ap.internal.gem.MapperGem
is not found

**Comment by filiphr** [comment]
Please use the [Gitter room](https://gitter.im/mapstruct/mapstruct-users) for asking such questions.

`MapperGem` is a generated class during compilation with the [mapstruct/tools-gem](https://github.com/mapstruct/tools-gem). It is used to access the annotation elements in a type safe manner.

**Comment by lcx45** [comment]
https://github.com/mapstruct/tools-gem mvn-compile gem-processor 模块后未找到 MapperGem 文件
