### ISSUE TITLE
Support for "qualifiedByName" with multiple parameters possibility 

### ISSUE THREAD

**Issue by gerasimovv88** [mapstruct/mapstruct#2212]
Hi!
I would like to use **qualifiedByName** feature with multiple parameters without `@Context`. 
I have a simple mapper like this
```
@Mapper
public abstract class SimpleMapper {

  @Mapping(target = "field", source = "field")
  public Output map(Input input)
}
```

But I want to do some logic, when map field
```
@Mapping(target = "logic", expression = "java(input.getA() + input.getB())")
public Output map(Input input)
```

I can do it with a **qualifiedByName**, then
```
@Mapping(target = "logic", source = "a", qualifiedByName = "fieldCalculation")
public Output map(Input input)
```
And in the method "fieldCalculation" I get only "a" field, but I want to do it with **multiple parameters** like this:
```
@Mapping(target = "logic", source = "a", source = "b", qualifiedByName = "fieldCalculation")
public Output map(Input input)
```

Same behaviour I can get with a Context annotation, but it add new argument to mapper. It might be ugly)

Thank you!)

**Comment by sjaakd** [comment]
Selecting methods that map several sources to one target is not supported. That's the underlying cause.

**Comment by gerasimovv88** [comment]
Okay, the last code fragment show my suggested solution.
Is there a way to use qualifiedByName with multiple parameters (multiple fields from source object)?

**Comment by filiphr** [comment]
>Is there a way to use qualifiedByName with multiple parameters (multiple fields from one source object)?

That is what @sjaakd answered in his previous comment. Currently it is not supported to select a method from multiple sources. Multiple fields from one source object is still multiple sources, since you need to pass multiple mapping parameters to the mapping method.

The feature you are requesting is #1315. If and when that is done then what you are asking will be possible.
