### ISSUE TITLE
@Mapping needs to define source parameter with defaultValue if you have two arguments in 1.4.0.Final

### ISSUE THREAD

**Issue by Saljack** [mapstruct/mapstruct#2214]
I found a regression in the new version 1.4.0.Final. If you have a mapper method with two arguments and define a `@Mapping` annotation with a `defaultValue` parameter then you have to define `source` parameter. It is a regression. See the example which works in 1.3.1.Final but it doesn't work in the new 1.4.0.Final.
```java
@Mapper
public interface MapperWithoutSource {

  class Tenant {
    public String id;
    public String type;
    public String parentTenantId;
  }

  class TenantDTO {
    public String id;
    public String type;
  }

  @Mapping(target="type", defaultValue = "STANDARD")
  Tenant map(TenantDTO tenant, String parentTenantId);

}
```
The error is `No property named "type" exists in source parameter(s). Please define the source explicitly.`
As workaround you have to define `source` argument with the method parameter name as: `@Mapping(target="type", defaultValue = "STANDARD", source="tenant.type")`

**Comment by filiphr** [comment]
Thanks for raising this issue @Saljack. We did some changes in this area and something slipped. I think that this issue is the same as #2206. At that time we were not aware about other possible regressions. We are going to look into it and fix this regression.

**Comment by Saljack** [comment]
@filiphr Yes it is the same. These issues types are good because you can write a simply unit test and it will never happen again. Good thing is that thanks to this issue I found an error in my mappers with `defaultValue`. I think that you can close it in favor of #2206 .

**Comment by filiphr** [comment]
Thanks for confirming @Saljack. I will keep this one open as it is slightly different. It will help us with writing the tests for the fix
