### ISSUE TITLE
Expose suppressGeneratorTimestamp in @Mapper annotation

### ISSUE THREAD

**Issue by whut** [mapstruct/mapstruct#2225]
Right now to enable reproducible build timestamp generation must be disabled. This can be done only via compiler argument. But this generates below warning if some project do not declare any MapStruct mappers.

```raw
The following options were not recognized by any processor: '[mapstruct.suppressGeneratorTimestamp]'
```

This can easily happen if having MapStruct configuration done once for many projects, like when using parent pom in Maven multi-module project. Typically then all projects use the same parent pom, but not all declare MapStruct mappers. In such case `javac` generates above warning, and it can't be suppressed.

So to avoid this either:

- generation of timestamp should be disabled by default

  Such approach was already suggested in #1682, but this was closed. IMHO timestamp does not bring any value, but only introduce issues: like with reproducible builds, Gradle build caching (#2194) or in any other case when there is no mapper declared (like in #1638), so disabling it by default will make better user experience.

- add ability to set `suppressGeneratorTimestamp` this on `@Mapper` annotation - then it will not be possible to set it globally once, like in the Maven parent pom, but at least this warning, will go away

**Comment by filiphr** [comment]
Thanks for the issue @whut. Thinking more about this and going through the issues it might make sense to disable the date generation by this and only activate it with an option (i.e. the reverse of the current `suppressGeneratorTimestamp`). This however cannot be done in a patch release. So it can only be done in the next release.

What do you think about this @sjaakd?
