### ISSUE TITLE
InheritConfiguration with qualifiedByName

### ISSUE THREAD

**Issue by toaster33** [mapstruct/mapstruct#2235]
Getting multiple errors: The type of parameter "from" has no property named "main".

@Mapper(disableSubMappingMethodsGeneration = true)
public abstract class HelperMapper {

	public class Frombject {

		List<Object> main = Arrays.asList(new FromNestedObject());
	}

	public class FromNestedObject {
		String one = "1";
		String two = "2";
	}

	public class Tobject {

		List<String> main;
	}

	@Named("qualified")
	public static List<String> qualified(List<Object> main) {

		List<String> ids = main.parallelStream().map(obj -> obj.toString()).collect(Collectors.toList());
		return ids;
	}

	@InheritConfiguration
	public abstract Tobject to2(Frombject from);

	@Mapping(source = "from.main", target = "main", qualifiedByName = "qualified")
	public abstract Tobject to1(Frombject from);
	
}

**Comment by filiphr** [comment]
MapStruct only looks at public getters / setters and fields to find a property.

Have a look at #1689 for fields / properties with default visibility
