### ISSUE TITLE
Dependency Injection generated code is not working in version 1.4.1.Final

### ISSUE THREAD

**Issue by ivangfr** [mapstruct/mapstruct#2237]
- [x] Is this an issue

Hi guys!

I am trying to update Mapstruct version in my app (https://github.com/ivangfr/springboot-neo4j-caffeine), from `1.3.1.Final` to `1.4.1.Final`. With the new version, I am getting the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project restaurant-api: Compilation failure: Compilation failure:
[ERROR] /springboot-neo4j-caffeine/restaurant-api/target/generated-sources/annotations/com/mycompany/restaurantapi/mapper/RestaurantMapperImpl.java:[49,29] cityService has private access in com.mycompany.restaurantapi.mapper.RestaurantMapper
[ERROR] /springboot-neo4j-caffeine/restaurant-api/target/generated-sources/annotations/com/mycompany/restaurantapi/mapper/RestaurantMapperImpl.java:[64,94] cityService has private access in com.mycompany.restaurantapi.mapper.RestaurantMapper
```

Checking the `RestaurantMapperImpl.java` generated class, I realized that `cityService` is not being injected

Code generated using version `1.3.1.Final`
```
...
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-10-17T09:46:29+0200",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 11.0.7 (Oracle Corporation)"
)
@Component
public class RestaurantMapperImpl extends RestaurantMapper {

    @Autowired
    private CityService cityService;
    ...

    @Override
    public Restaurant toRestaurant(CreateRestaurantDto createRestaurantDto) {
        if ( createRestaurantDto == null ) {
            return null;
        }

        Restaurant restaurant = new Restaurant();
        restaurant.setName( createRestaurantDto.getName() );
        restaurant.setCity( cityService.validateAndGetCity(createRestaurantDto.getCityId()) );
        return restaurant;
    }

    @Override
    public void updateRestaurantFromDto(UpdateRestaurantDto updateRestaurantDto, Restaurant restaurant) {
        if ( updateRestaurantDto == null ) {
            return;
        }

        if ( updateRestaurantDto.getName() != null ) {
            restaurant.setName( updateRestaurantDto.getName() );
        }

        restaurant.setCity( updateRestaurantDto.getCityId() == null ? restaurant.getCity() : cityService.validateAndGetCity(updateRestaurantDto.getCityId()) );
    }
    ...
}

```

Code generated using version `1.4.1.Final`
```
...
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-10-17T09:34:32+0200",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 11.0.7 (Oracle Corporation)"
)
@Component
public class RestaurantMapperImpl extends RestaurantMapper {
    ...
    @Override
    public Restaurant toRestaurant(CreateRestaurantDto createRestaurantDto) {
        if ( createRestaurantDto == null ) {
            return null;
        }

        Restaurant restaurant = new Restaurant();
        restaurant.setName( createRestaurantDto.getName() );
        restaurant.setCity( cityService.validateAndGetCity(createRestaurantDto.getCityId()) );
        return restaurant;
    }

    @Override
    public void updateRestaurantFromDto(UpdateRestaurantDto updateRestaurantDto, Restaurant restaurant) {
        if ( updateRestaurantDto == null ) {
            return;
        }

        if ( updateRestaurantDto.getName() != null ) {
            restaurant.setName( updateRestaurantDto.getName() );
        }

        restaurant.setCity( updateRestaurantDto.getCityId() == null ? restaurant.getCity() : cityService.validateAndGetCity(updateRestaurantDto.getCityId()) );
    }
    ...
}
```

Here is how `RestaurantMapper` is configured
```
@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = CityService.class
)
public abstract class RestaurantMapper {

    @Autowired
    private CityService cityService;

    public abstract RestaurantDto toRestaurantDto(Restaurant restaurant);

    @Mapping(target = "city", expression = "java(cityService.validateAndGetCity(createRestaurantDto.getCityId()))")
    public abstract Restaurant toRestaurant(CreateRestaurantDto createRestaurantDto);

    @Mapping(target = "city", expression = "java(updateRestaurantDto.getCityId() == null ? restaurant.getCity() : cityService.validateAndGetCity(updateRestaurantDto.getCityId()))")
    public abstract void updateRestaurantFromDto(UpdateRestaurantDto updateRestaurantDto, @MappingTarget Restaurant restaurant);

}
```

Best regards!

**Comment by filiphr** [comment]
The fact the `cityService` is not injected is per design. When the components defined in `uses` are not used, then no fields are created for them. I would even say that it was a bug that it was injected before.

You should not rely on the `cityService` being present.

What you can do though is to make your field `protected` instead of `private` and then everything will work fine.

Another option is that you don't even need to use expression and just use `@Mapper(..., uses = CityService.class)`. MapStruct will automatically detect the `validateAndGetCity` method and use it for mapping between `String` and `City`. I usually try to avoid using `expression`.

e.g.

```
@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = CityService.class
)
public interface RestaurantMapper {

    RestaurantDto toRestaurantDto(Restaurant restaurant);

    @Mapping(target = "city", source = "cityId")
    Restaurant toRestaurant(CreateRestaurantDto createRestaurantDto);

    @Mapping(target = "city", source = "cityId")
    void updateRestaurantFromDto(UpdateRestaurantDto updateRestaurantDto, @MappingTarget Restaurant restaurant);
```

**Comment by ivangfr** [comment]
Thanks @filiphr 

I applied the changes you suggested and worked perfectly.

Indeed, I don't need to use the `expression` inside the `Mapping` annotations.

Now, the configuration inside the `RestaurantMapper` is simpler.

**Comment by filiphr** [comment]
Great that it worked.

Btw I had a brief look at your project and I saw that you have the mapstruct-processor in the dependencies as provided scope. This means that the processor is still on your classpath, especially with the spring-boot-maven-plugin generating the fat jar. 

I would suggest that you add it as part of the `annotationProcessorPaths` of the `maven-compiler-plugin` (you'll need to add lombok as well there, and any other annotation processor you might have). By doing this your fat jar will be smaller, at least smaller by 1.7 MB (the size of the mapstruct-processor).

**Comment by ivangfr** [comment]
Hey @filiphr 

So, I changed the `RestaurantMapper.java` as you suggested; plus, I am using `InjectionStrategy.CONSTRUCTOR`. The class is like
```
@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = CityService.class,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR
)
public interface RestaurantMapper {

    RestaurantDto toRestaurantDto(Restaurant restaurant);

    @Mapping(target = "city", source = "cityId")
    Restaurant toRestaurant(CreateRestaurantDto createRestaurantDto);

    @Mapping(target = "city", source = "cityId")
    void updateRestaurantFromDto(UpdateRestaurantDto updateRestaurantDto, @MappingTarget Restaurant restaurant);

}
```

Now, I removed the `mapstruct-processor` in the dependencies as provided scope and add it as part of the `annotationProcessorPaths` of the `maven-compiler-plugin` (together with `lombok`). Here is the code
```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${maven-compiler-plugin.version}</version>
            <configuration>
                <source>${java.version}</source>
                <target>${java.version}</target>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>${org.mapstruct.version}</version>
                    </path>
                    <path>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>${lombok.version}</version>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
```

However, now I am getting the following exception
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project restaurant-api: Compilation failure: Compilation failure:
[ERROR] /github-projects/springboot-neo4j-caffeine/restaurant-api/src/main/java/com/mycompany/restaurantapi/mapper/RestaurantMapper.java:[24,40] No property named "cityId" exists in source parameter(s). Did you mean "null"?
[ERROR] /github-projects/springboot-neo4j-caffeine/restaurant-api/src/main/java/com/mycompany/restaurantapi/mapper/RestaurantMapper.java:[27,40] No property named "cityId" exists in source parameter(s). Did you mean "null"?
```

**Comment by filiphr** [comment]
All of that looks good. I also cloned your code and did the same steps and it works correctly via Maven and via IntelliJ.

Which command did you run so this happenned?

**Comment by ivangfr** [comment]
I've run `./mvnw clean package -DskipTests`

I added the `maven-compiler-plugin` in the `pom.xml` of `restaurant-api`, not the main `pom.xml`

**Comment by filiphr** [comment]
That is what I did as well.

**Comment by ivangfr** [comment]
Thanks @filiphr I will have a look. I have other projects that also use mapstruct and, for sure, I am not configuring it using `maven-compiler-plugin`. I will try on them and see if I face the same problem.

**Comment by ivangfr** [comment]
Hey @filiphr I've found the reason why it was not working here... I was using the latest version of `Lombok`, `1.18.16`. With the version `1.18.12` (default version used currently by spring-boot 2.3.4.Final) it works perfectly.

**Comment by ivangfr** [comment]
@filiphr one question: I have some Quarkus applications. Should I use `mapstruct-processor` in the dependencies as explained in the article https://mapstruct.org/news/2019-12-06-mapstruct-and-quarkus/#one-small-disadvantage-still-left ? Thanks in advance!

**Comment by filiphr** [comment]
> I was using the latest version of `Lombok`, `1.18.16`. With the version `1.18.12` (default version used currently by spring-boot 2.3.4.Final) it works perfectly.

There is a breaking change there. You'll need to add `lombok-mapstruct-binding` for it to work with MapStruct correctly. Additionally, that binding only works on JDK 1.8. I've raised https://github.com/rzwitserloot/lombok/issues/2616 with the Lombok team, not sure if that is intended or not.

**Comment by filiphr** [comment]
As for the Quarkus question, yes it seems that https://github.com/quarkusio/quarkus/issues/1502, the issue for Quarkus using `annotationProcessorPaths` correctly is still open. So indeed you'll have to use the `provided` scope.
