### ISSUE TITLE
@Mapping nullValuePropertyMappingStrategy not generate default value for nested class value

### ISSUE THREAD

**Issue by idrissov** [mapstruct/mapstruct#2240]
Hello!
While migrating from 1.3.1 to 1.4.1 I faced with a problem that nullValuePropertyMappingStrategy is not generating code for the default value set. Previously I saw **if** statement that checks for null, now it generates only if attribute defaultValue explicitly set to empty string. 

I personally think that it is a bug.

```java
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring")
public interface TestMapper {
    class Tenant {
        public String id;
    }
    class Inner {
        public String id;
    }

    class TenantDTO {
        public Inner inner;
    }

    @Mapping(target="id", source = "inner.id",
            nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT)
    Tenant map(TenantDTO tenant);

}
```

**Comment by filiphr** [comment]
Are you sure that `nullValuePropertyMappingStrategy` worked in 1.3.1.Final? `NullValuePropertyMappingStrategy` is only used for update methods.

From the javadoc:

>The enum **only applies to update methods**: methods that update a pre-existing target (annotated with `@MappingTarget`).

Can you please share the generated code in 1.3.1.Final and 1.4.1.Final?

**Comment by idrissov** [comment]
Hi @filiphr,
The issue happened when we migrated to 1.4.1. To fix the issue we removed `nullValuePropertyMappingStrategy ` and added explicitly `defaultValue=""`. So, maybe you are right and the issue is with defaultValue that has changed default behaviour.

Following the code generated by 1.3.1 and 1.4.1:
```java
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-10-20T09:44:07+0600",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 11.0.4 (Oracle Corporation)"
)
@Component
public class TestMapperImpl implements TestMapper {

    @Override
    public Tenant map(TenantDTO tenant) {
        if ( tenant == null ) {
            return null;
        }

        Tenant tenant1 = new Tenant();

        String id = tenantInnerId( tenant );
        if ( id != null ) {
            tenant1.id = id;
        }
        else {
            tenant1.id = "";
        }

        return tenant1;
    }

    private String tenantInnerId(TenantDTO tenantDTO) {
        if ( tenantDTO == null ) {
            return null;
        }
        Inner inner = tenantDTO.inner;
        if ( inner == null ) {
            return null;
        }
        String id = inner.id;
        if ( id == null ) {
            return null;
        }
        return id;
    }
}
```
```java
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-10-20T09:46:26+0600",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 11.0.4 (Oracle Corporation)"
)
@Component
public class TestMapperImpl implements TestMapper {

    @Override
    public Tenant map(TenantDTO tenant) {
        if ( tenant == null ) {
            return null;
        }

        Tenant tenant1 = new Tenant();

        tenant1.id = tenantInnerId( tenant );

        return tenant1;
    }

    private String tenantInnerId(TenantDTO tenantDTO) {
        if ( tenantDTO == null ) {
            return null;
        }
        Inner inner = tenantDTO.inner;
        if ( inner == null ) {
            return null;
        }
        String id = inner.id;
        if ( id == null ) {
            return null;
        }
        return id;
    }
}
```

**Comment by filiphr** [comment]
@idrissov I just checked `@Mapping(target="id", source = "inner.id", defaultValue = "")` with 1.4.1.Final and the following is generated

```
if ( tenantInnerId( tenant ) != null ) {
    tenant1.id = tenantInnerId( tenant );
}
else {
    tenant1.id = "";
}
```

which is not ideal (it is missing an intermediate variable) and for this I created #2245. However, there is a null check. You can also add `nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS` to the `@Mapping` and then there will be an intermediate variable check as well (even if you don't have a `defaultValue` set).

**Comment by idrissov** [comment]
@filiphr yes we now use this approach `@Mapping(target="id", source = "inner.id", defaultValue = "")`.

But my question is about changing behavior of `@Mapping(target="id", source = "inner.id", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT)` it's changed from 1.3.1 to 1.4.1. Is it by design or is a bug?

**Comment by filiphr** [comment]
Just checked what you said and indeed it was working like you said in 1.3.1. However, the fact that it is working there is a bug. If you put it on the `@Mapper` then it creating the empty string. Therefore, I would say that the behaviour in 1.4.1 is the correct one. The `NullValuePropertyMappingStrategy` is only applicable to update methods and not to normal mapping methods.
