### ISSUE TITLE
Error / warn messages should include the class annotated with @Mapper, not the class that defines the mapping method

### ISSUE THREAD

**Issue by sniffertine** [mapstruct/mapstruct#2243]
We have an interface that defines common mapping for JPA entities to DTOs. 

```
public interface EntityMapper<D, E> {

    E toEntity(D dto);

    List<E> toEntity(List<D> dtos);

    Set<E> toEntity(Set<D> dtos);

    D toDto(E entity);

    List<D> toDto(List<E> entities);

    Set<D> toDto(Set<E> entities);

}
```

Our mapper extend this interface to inherit the default mapping methods:

```
@Mapper
public interface MyMapper extends EntityMapper<MyDTO, MyEntity> {

}
```

Warnings about unmapped properties will look like this:

> EntityMapper.java:14: warning: Unmapped target properties: "createdBy, createdDate

It is not clear, which mapper produces this error because `MyMapper` is not mentioned at all.

**Comment by filiphr** [comment]
@sniffertine I think that this is the same as #598. Therefore closing this in favour of that one. Please let us know if you think that there is a difference between the 2 issues.
