### ISSUE TITLE
Using proper methods with @Context parameter through collections and other mappers

### ISSUE THREAD

**Issue by trevize8** [mapstruct/mapstruct#2246]
I am having a hard time trying to have my @Context param getting through another mapper the main mapper class is using. It always ends up calling the other mappers method without the desired context param.
A scenario replicating the issue I'm having:

Company and CompanyDTO classes:
```
public class Company {
    private String name;
    private List<Employee> employees;
    // getters and setters
}

public class CompanyDTO {
    private String name;
    private List<EmployeeDTO> employees;
    // getters and setters
}
```
Then Employee and EmployeeDTO both having a single name attribute:
```public class Employee {
    private String name;
    //getters and setters
}
public class EmployeeDTO {
    private String name;
    //getters and setters
}
```
And for the mappers, a BaseMapper class defining some common map methods, some having an extra parameter, which must be name to fix ambiguation issues:
BaseMapper
```
public interface BaseMapper<T, E> {
    T toDto (E entity);

    E toEntity (T dto);

    @Named("toDtoLocale")
    T toDto(E entity, @Context Locale locale);

    @Named("toEntityLocale")
    E toEntity(T dto, @Context Locale locale);

    @Named("toDtoListLocale")
    List<T> toDto(List<E> entities, @Context Locale locale);

    @Named("toEntityListLocale")
    List<E> toEntity(List<T> dtos, @Context Locale locale);
```
Finally the classes for the Employee and Company Mappers:
```
@Mapper (componentModel = "spring", uses = {EmployeeMapper.class})
public interface CompanyMapper extends BaseMapper<CompanyDTO, Company>{
}

@Mapper(componentModel = "spring")
public interface EmployeeMapper extends BaseMapper<EmployeeDTO, Employee>{
}
```

Now, Mapstruct will generate a method `List<EmployeeDTO> employeeListToEmployeeDTOList1(List<Employee> list, Locale locale)` as I was expecting, including the @Context param. However in the method implementation, it will use the `EmployeeDTO toDto (Employee entity)` from the Employee mapper to map each of the collection items.

 I've tried different things and can't get that working. Not sure I'm missing anything. 

I event tried to use some expressions to make sure the right employeeMapper method is being used:
```
    @Named("toDtoLocale")
    @Mapping(target="employees", expression = "java(employeeMapper.toDto( company.getEmployees(), locale ))")
    CompanyDTO toDto(Company company, @Context Locale locale);
```

But even in that case, in the EmployeeMapperImpl that converts the collection, it will internally use the toEntity(Employee employee) for each item, so not using the @Context param.

Thanks!

**Comment by filiphr** [comment]
You are using MapStruct's `@Named` which by design means that those methods are special methods and should only be used when the mappings are used with the appropriate qualifier.

As you saw, without `@Named` you will start getting compilation errors saying that there are multiple methods that match the mapping.

I would suggest reading up on [Mapping method selection based on qualifiers](https://mapstruct.org/documentation/stable/reference/html/#selection-based-on-qualifiers).

In order to fix it you will have to do something like:

```
    @Named("toDtoLocale")
    @Mapping(target="employees", qualifiedByName = "toDtoListLocale")
    CompanyDTO toDto(Company company, @Context Locale locale);
```

This will make sure that mapping `employees` will use the correct mapping method with the `@Context` for the mapping of the employees.

You might also need to change your `EmployeeMapper` and do 

```
    @Named("toDtoListLocale")
    @IterableMapping(qualifiedByName = "toDtoLocale")
    List<EmployeeDto> toDto(List<Employee> entities, @Context Locale locale);
```

I am not sure that there is something that we can do about this

**Comment by trevize8** [comment]
Awesome thanks! Applied your suggestions and it is now doing what I wanted.

The key was that `@IterableMapping` annotation I did not know about. Without it it still uses the method without the `@Context`.

Thanks again for the support!
