### ISSUE TITLE
Wrong reporting for unmapped source properties when source source is implicitly mapped

### ISSUE THREAD

**Issue by incaseoftrouble** [mapstruct/mapstruct#2253]
This is an issue / feature request. I hope I didn't miss this but after reading the reference a few times I didn't find anything along those lines. I do hope that I can get across the point well, but I feel like my explanation isn't that good :| Let's try anyway.

Basically, I have the following situation:
```java
@Mapping(target = "string", source = "string")
Entity map(Dto dto, String string)
```
where `Entity` has a property `String string`. `dto` is my "primary" source for parameters (yes, "primary" is a bit vague), `string` is a property / mapped to a property of `Entity`. Nevertheless, mapstruct scans `String` for additional properties (even though the object itself is already mapped as a property). Moreover, generic `@ObjectFactories` and `@BeforeMapping`s / `@AfterMapping`s match both objects (which is desired in general but might not be in this case).

My suggestion: Similar to `@Context`, introduce a `@Parameter` annotation (or `@Property` / `@Mapped`), which excludes the marked argument from *any* consideration except as a source propery. Maybe one could even the "target" argument to directly assign the argument to a property. So, for example, the above then would be:
```java
Entity map(Dto dto, @Property("string") String string)
```

I guess that #1280 and #1315 are somewhat related.

Why I don't want to "work around" with `@Context`: The additional arguments (the `string` in the above example) typically are database ids which are resolved to database entities using a generic `T object(UUID id, @TargetType Class<T> clazz)` method. If I used `@Context` I would basically need to replicate this generated mapping by hand, except I am missing a trick of `@Context`.

**Comment by filiphr** [comment]
I think that I understand the problem you are having. However, to make sure that I don't misunderstand, can you please share a small reproducible example?

All of this boils down to the fact that when you use

```
@Mapping(target = "string", source = "string")
Entity map(Dto dto, String string)
```

It will treat `String` as a Bean and will try to look for properties inside of it.

I don't think that we need to add a new annotation, the current mapping definition should work.

**Comment by incaseoftrouble** [comment]
Example:

```java
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
public interface TestMapper {
  Entity map(Dto dto, String string);

  class Entity {
    public int integer;
    public String string;
  }

  class Dto {
    public int integer;
  }
}
```
This yields `error: Unmapped source properties: "empty, bytes, blank".` with 1.4.1.Final (String has `isEmpty`, `isBlank`, `getBytes` methods), doesn't matter if I add an `@Mapping` method or setters/getters. With `ReportingPolicy.WARN`, the mapping is correctly generated (`Entity`'s `string` field is correctly set) but warnings still are emitted:
```java
    @Override
    public Entity map(Dto dto, String string) {
        if ( dto == null && string == null ) {
            return null;
        }

        Entity entity = new Entity();

        if ( dto != null ) {
            entity.integer = dto.integer;
        }
        if ( string != null ) {
            entity.string = string;
        }

        return entity;
    }
```
plus: `warning: Unmapped source properties: "empty, bytes, blank".`

**Comment by filiphr** [comment]
@incaseoftrouble we are going to treat this as a bug as it should work without any interaction from your side. 

There is a PR fixing this

**Comment by incaseoftrouble** [comment]
Great! Thanks!

**Comment by mitasov-ra** [comment]
@filiphr Hi! I've noticed that PR above explicitly skips parameters with array types. Does it affect Lists? Asking because I've just got an error

```
Unmapped source properties: "empty"
```

While using `List` as second method parameter:

```
record Foo() {}

record Bar() {}

record ComplexDto(
  Foo foo,
  List<Bar> bars
) {}

@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
interface ComplexMapper {
  @Mapping(source = "foo", target = "foo")
  @Mapping(source = "bars", target = "bars")
  ComplexDto toComplex(Foo foo, List<Bar> bars);
}
```

**Comment by filiphr** [comment]
@mitasov-ra, I think that the best solution for your problem would be #2559. It gives more control over the mapping of the source parameters and whether they need to be treated as beans or mapped directly
