### ISSUE TITLE
Add constants for componentModel

### ISSUE THREAD

**Issue by Saljack** [mapstruct/mapstruct#2255]
`@Mapper` has an attribute `componentModel` where you can define what component model will be generated but unfortunately there are no constants for it. I checked the `SpringComponentProcessor` and there is string too. So my proposal is to create a new class with constants which can be used there and then you can use it as `@Mapper(componentModel=ComponentModel.SPRING)`.
```java
public class ComponentModel {

  /**
   * the mapper uses no component model, instances are typically retrieved via
   * Mappers.getMapper(Class)
   */
  public static final String DEFAULT = "default";

  /**
   * The generated mapper is an application-scoped CDI bean and can be retrieved
   * via @Inject
   */
  public static final String CDI = "cdi";

  /**
   * The generated mapper is a Spring bean and can be retrieved via @Autowired
   */
  public static final String SPRING = "spring";

  /**
   * The generated mapper is annotated with @javax.inject.Named and @Singleton,
   * and can be retrieved via @Inject
   */
  public static final String JSR330 = "jsr330";

  private ComponentModel() {
  }

}
```

**Comment by filiphr** [comment]
I don't know why we don't have constants for the component model.

The [IntellIj MapStruct](https://plugins.jetbrains.com/plugin/10036-mapstruct-support) plugin has auto completion for it though.

In any case I think that your proposal is OK. However, instead of creating a new class, why not use the existing [`MappingConstants`](https://github.com/mapstruct/mapstruct/blob/master/core/src/main/java/org/mapstruct/MappingConstants.java).

Are you interested in providing a PR for this?

**Comment by Nikolas-Charalambidis** [comment]
@filiphr As proposed, I would rather create a separate class `ComponentModel` for these reasons:
- As far as I see `MappingConstants` are exclusively associated with the mapping feature itself (i.e. `@ValueMapping` annotation as the reference documentation states). This would lead wrongly users to constructs such as `@ValueMapping(source = MappingConstants.DEFAULT, target = "DEFAULT" ),`
- The component model is that specific this shall be restricted throught the class this way. Again, something like `@Mapper(componentModel = MappingConstants.ANY_UNMAPPED)` can happen, which would be misleading to the users.

I am also open to take care of that and submit a PR, however, I'd rather leave this task to @Saljack if he is interested as I don't want to *steal* this idea.

**Comment by Saljack** [comment]
I will try to provide a PR. My opinion is that a separate class is better and I think that enum isn't good because it means a lot of refactoring. And I think that the `componentModel` can be extendable. So my proposal is:

```java
@Mapper(componentModel = ComponentModel.SPRING)
```

**Comment by chris922** [comment]
+1 for using a String instead of an enum. Using an enumeration means MapStruct must be updated in case Spring introduces a new component-model.
