### ISSUE TITLE
[feature suggestion] Map from iterable parameter to iterable field of non-iterable target

### ISSUE THREAD

**Issue by ba3a** [mapstruct/mapstruct#2259]
It's sometimes needed to build object from iterable variable and some other stuff. E.g.
```class DesiredDro{
    String param1;
    List<String> params2;
    //getters, setters and so on
}
```
Now I have to define mapper that consumes wrapping class containing only that one Iterable:
```
class ListWrapper {
    List<String> params;
}

@Mapping(target = "params2", source = "listWrapper.params")
DesiredDto map(ListWrapper listWrapper, String param1)
```

But it would be more convenient to write like this:
`DesiredDto map(List<String> params2, String param1)`

Current version of mupstruct fails to generate such a mapper because of  `Can't generate mapping method from iterable type to non-iterable type.`

**Comment by filiphr** [comment]
Hey @ba3a,

I think that this is identical to #607 which was recently implemented by a contributor and it will be part of the next 1.5 release.

By the way what you are trying to do will work even now if you swap the parameters of the method.

e.g.
```
DesiredDto map(String param1, List<String> params2)
```
