### ISSUE TITLE
Incorrect implementation with spring-boot 2.3.5

### ISSUE THREAD

**Issue by wpater** [mapstruct/mapstruct#2267]
- [x] Is this an issue (and hence not a question)? 

I am using Mapstruct (1.4.1.Final) with Spring Boot. Started with 2.3.2.RELEASE (and same result with 2.3.4.RELEASE) and it is working:
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-11-05T07:05:05+0100",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 13.0.2 (Oracle Corporation)"
)
@Component
public class UserMapperImpl implements UserMapper {

    @Autowired
    private GroupToIdMapper groupToIdMapper;
    @Autowired
    private TodoListToIdMapper todoListToIdMapper;

    @Override
    public UserDto userToUserDto(User user) {
        if ( user == null ) {
            return null;
        }

        UserDto userDto = new UserDto();

        userDto.setId( user.getId() );
        userDto.setUsername( user.getUsername() );
        userDto.setEmail( user.getEmail() );
        ...

        return userDto;
    }
    ...
```
With Spring Boot 2.3.5.RELEASE:
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-11-05T07:12:09+0100",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 13.0.2 (Oracle Corporation)"
)
@Component
public class UserMapperImpl implements UserMapper {

    @Override
    public UserDto userToUserDto(User user) {
        if ( user == null ) {
            return null;
        }

        UserDto userDto = new UserDto();

        return userDto;
    }
}
```

Only version is changed, same host, same OS, same JDK (tested with docker `maven:3-jdk-13-alpine` too - same results).

**Comment by filiphr** [comment]
Spring Boot updated Lombok to 1.18.16 in 2.3.5 and there is a breaking change with MapStruct there. Have a look at https://projectlombok.org/changelog.

You need to add `lombok-mapstruct-binding` as a dependency now as well.

**Comment by wpater** [comment]
Yes, I saw that and I have this dependency already added. That's why I am reporting this :(.
I found another issue about this, but reported in lombok project: https://github.com/rzwitserloot/lombok/issues/2626

**Comment by wpater** [comment]
https://github.com/rzwitserloot/lombok/issues/2626#issuecomment-722231483

Not as dependency but in `annotationProcessorPaths` node in plugins. Now it is working.

Thank you for your help! 👍
