### ISSUE TITLE
建议：抽象出一个父级接口，通用场景集成更为简化

### ISSUE THREAD

**Issue by chendailong** [mapstruct/mapstruct#2273]
```
public interface SuperConverter<T, D> {
    D tb2dto(T tbStore);

    T dto2tb(D dto);
}
```

```
@Mapper
public interface StoreConverter extends SuperConverter<TbStore,StoreDto> {
    StoreConverter INSTANCE = Mappers.getMapper(StoreConverter.class);
}
```

这样如果有很多场景并没有复杂的属性映射问题，可以省去开发者申明两个pojo互相转换的方法

**Comment by filiphr** [comment]
I tried using Google Translate to translate this:

Title: "Suggestion: Abstract a parent interface and simplify the integration of common scenarios"

Content: "In this way, if there are many scenarios that do not have complex attribute mapping problems, you can save the developer to declare the method of two pojo conversion"

**Comment by filiphr** [comment]
If I understood correctly you would like MapStruct to provide the `SuperConverter` interface for you?

If that is the case I am against it since it is extremely easy for users to define their own common super interfaces that they can use to inherit from.
