### ISSUE TITLE
MappingTarget member cannot be set to null

### ISSUE THREAD

**Issue by mickroll** [mapstruct/mapstruct#2274]
**Expected**
Given a mapper:
```java
@Mapper
public interface ExampleMapper {
  void update(@MappingTarget ExampleTarget target, ExampleSourceVO source, ExampleMember member);
}
```
...and calling it with a `null`-parameter for `member`:
```java
mapper.update(target, source, null);
```
will lead to `target.setMember(null)`.

**Actual**
The mapper implementation is generated as follows:
```java
    [...]
    if ( member != null ) {
      exampleTarget.setMember( member );
    }
    [...]
```
So the member will never be set to `null`.

I tried to work around this using `defaultExpression = "java(null)"`, but this leads to a completely confused implementation:
```java
    if ( member != null ) {
      if ( member != null ) {
        target.setMember( member );
      }
      else {
        target.setMember( null );
      }
    }
```
This weird double check without a chance to reach the else-branch was also mentioned in #2023

Demonstrator:
https://github.com/mickroll/demonstrator/tree/mapstruct-mappingtarget-set-member-to-null
1. `git clone -b mapstruct-mappingtarget-set-member-to-null https://github.com/mickroll/demonstrator.git`
2. `cd demonstrator`
3. `mvn clean install`

Feel free to integrate the included tests as wanted.

**Workaround**
```java
  @AfterMapping
  default void fixNullMember(@MappingTarget ExampleTarget target, ExampleMember member) {
    if (member == null) {
      target.setMember(null);
    }
  }
```
See demonstrator for reference. This workaround fixes the included tests.

**Comment by filiphr** [comment]
Thanks for the demonstrator and pointing to #2023. The root cause of the problem for this issue is actually the same as in #2023.

I think that I have found a good solution for the fix.
