### ISSUE TITLE
Runtime dependency on mapstruct.jar with default component model

### ISSUE THREAD

**Issue by dmngb** [mapstruct/mapstruct#2277]
When using the default component model, other mapper types used by a mapper are instantiated using Mappers.getMapper(UsedMapper.class).

The unfortunate side effect is that mapsctruct.jar then becomes a mandatory runtime transitive dependency because of the Mappers class.

I haven't found a way to get the code generation use direct instantiation (private final UsedMapper usedMapper = new UsedMapperImpl()) or any other work around.

**Comment by dmngb** [comment]
Just to give some context on my use case: we develop a library which uses mapstruct internally (it's so convenient!). 

This library tries to avoid any transitive dependency, as it will be embedded in many applications with very different frameworks and very different versions.

The use of Mappers.getMapper() in generated code breaks the "compile time only" feature of mapstruct that was so appealing to us.

**Comment by filiphr** [comment]
When using the `default` component model there is no other way to instantiate the mappers. The `Mappers` factory is there for this exact purpose.

It is possible to create your own component model and replace the fields, or you can replace the ones for the current default one. Have a look at `AnnotationBasedComponentModelProcessor` as an inspiration.

Additionally we have a request #2211 to use constructor injection with the default model. Thus leading to you having to create the wiring and instantiation of the mappers on your own.

**Comment by dmngb** [comment]
Yes, #2211 could be an acceptable work-around.

In practice, this would probably allow do something like that, I guess:
```
@Mapper(InjectionStrategy=CONSTRUCTOR, uses = {UsedMapper.class}) 
interface MyMapper {
   MyMapper INSTANCE = new MyMapperImpl(UsedMapper.INSTANCE);
}
@Mapper
interface UsedMapper {
  UsedMapper INSTANCE = new UsedMapperImpl();
}
```

Another solution may be for the default code generation to use the conventional INSTANCE field (if it exists and has the expected type) instead of a "factory" implemented by Mappers.

That is, generated code could be like:
```
class MyMapperImpl {
   private final UsedMapper usedMapper = UsedMapper.INSTANCE;
}
```
instead of:
```
class MyMapperImpl {
   private final UsedMapper usedMapper = Mapper.getMapper(UsedMapper.class);
}
```

This would allow us to do something like this to avoid the use of Mappers.getMapper at runtime:
```
@Mapper(uses = {UsedMapper.class}) 
interface MyMapper {
}
@Mapper(uses = {UsedMapper.class}) 
interface UsedMapper {
  UsedMapper INSTANCE = new UsedMapperImpl();
}
```

As an added bonus, this would to allocate mappers only once, even when still using the Mappers class. And it would in practice be backward compatible in almost all cases, I hope:
```
@Mapper(uses = {UsedMapper.class}) 
interface MyMapper {
}
@Mapper(uses = {UsedMapper.class}) 
interface UsedMapper {
  UsedMapper INSTANCE = Mappers.getMapper(UsedMapper.class);
}
```

Just for my understanding, why do you say that there is no other way to instantiate the mappers besides using Mappers.getMapper ? Directly instantianting the generated implementation classes seems to work OK for us. So, I guess there are some use cases where it can not work.
