### ISSUE TITLE
Can support protobuf3 with map

### ISSUE THREAD

**Issue by foresx** [mapstruct/mapstruct#2279]
- [x] Is this an issue (and hence not a question)? 
```java
  private Map<String, String> customAttributes = new ConcurrentHashMap<>();
```
If we have one parameter above, we want to map this to protobuf.
Mapstruct will map this parameter using method getCustomAttributes().putAll() to set this value.
But in protobuf3 this is a immutable map.So this can't work out. Protobuf3 support method is this putAllCustomAttributes().
Can protobuf3 using the same method like list, give a @Mapping annotation to manual assign.
Now my way to fix this is to using decorator to manual set the value.
It's nice to have a annotation to quick assign.

**Comment by filiphr** [comment]
I think that this is more or less similar to #1343. In the issue there is talk about supporting `putAll` variant as well. Can you please verify that @foresx?

**Comment by foresx** [comment]
Yes, I think this is the same probelm. Thanks a lot. Maybe I should close this issue and watching #1343

**Comment by filiphr** [comment]
Thanks for checking. Closing this in favor of #1343
