### ISSUE TITLE
Collection Mapping should have a way to filter what to convert

### ISSUE THREAD

**Issue by AnakinPt** [mapstruct/mapstruct#2291]
I have a special need. I have a source collection, let's say FooList and I want to convert to BarList, but I don't want to convert all objects from FooList, just a subset based on some Business Logic

I know, I can do a BefforeMapping method to remove from the source the objects I'm not interested, but I would prefer to walk through the List only once and not twice.

I would like to suggest to have some configuration in the mappers to allow me to call a method to filter the objects to add in the collection

`class Mapper {
  @Mapping(target="bar", source="foo")
  Bar mapBarFromFoo(Foo fooObject);

 @CollectionMapping(filterMethod="someFilterMethod")
 List<Bar> mapBarsFromFoos(List<Foo> foos);
`

**Comment by filiphr** [comment]
This is one of those use cases which are extremely easy to be done manually and quite complex to be done on our side. Perhaps the pending conditional mapping could be used here as wel.

In any case in your example it can look like:

```
interface CustomMapper {
    @Mapping(target="bar", source="foo")
    Bar mapBarFromFoo(Foo fooObject);

    List<Bar> mapBarsFromFoos(List<Foo> foos) {
        return foos.stream()
                    .filter(this::someFilterMethod)
                    .collect(Collectors.toList());
    }

    default boolean someFilterMethod(Foo foo) {
         // Custom filter check
    }
}
```
