### ISSUE TITLE
@Mapper(uses = ...) is not mapping all of the fields

### ISSUE THREAD

**Issue by rj93** [mapstruct/mapstruct#2292]
I am having an issue where some `@Mapping`'s are not being applied when using `uses` on a `@Mapper`.

Full source code and test are available at https://github.com/rj93/mapstruct-error.

In summary, I have an abstract entity class, where other entity classes extend:

```java
@NoArgsConstructor
@Data
@SuperBuilder
public abstract class AbstractEvent {
    private long id;
    private long requestorId;

    public abstract boolean supportsDraft();
}
```

```java
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
public class MyEvent extends AbstractEvent {
    private String eventName;

    @Override
    public boolean supportsDraft() {
        return true;
    }
}
```

Furthermore, I have a base DTO class that all other DTO classes extend:

```java
@NoArgsConstructor
@Data
@SuperBuilder
public class EventDto {
    private long eventId;
    private long requestorId;
    private boolean draftSupported;
}
```

```java
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
public class MyEventDto extends EventDto {
    private String eventName;
}
```

I then have two mappers, one for the abstract/base class and the other being for the child classes:

```java
@Mapper
public interface EventMapper {

    @Mappings({
            @Mapping(target = "eventId", source = "id"),
            @Mapping(target = "requestorId", source = "requestorId"),
            @Mapping(target = "draftSupported", source = "event", qualifiedByName = "supportsDraft"),
    })
    EventDto map(AbstractEvent event);

    @Named("supportsDraft")
    default boolean supportsDraft(AbstractEvent event) {
        return event.supportsDraft();
    }

}
```

```java
@Mapper(uses = EventMapper.class)
public interface MyEventMapper {

    @Mappings({
            @Mapping(target = "eventName", source = "eventName"),
    })
    MyEventDto map(MyEvent event);
}
```

The issue I am having is that `@Mapping(target = "eventId", source = "id")` and `@Mapping(target = "draftSupported", source = "event", qualifiedByName = "supportsDraft")` aren't being applied for some reason. The `requestorId` and `eventName` mappings are working correctly.

If I duplicate the `@Mapping`'s to a different `Mapper` it works:

```java
@Mapper(uses = EventMapper.class)
public interface MyEventExplicitMapper {

    @Mappings({
            @Mapping(target = "eventId", source = "id"),
            @Mapping(target = "draftSupported", source = "event", qualifiedByName = "supportsDraft"),
            @Mapping(target = "eventName", source = "eventName"),
    })
    MyEventDto map(MyEvent event);
}
```

The generated Mappers are:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-12-02T12:03:43+0000",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 11.0.8 (AdoptOpenJDK)"
)
public class EventMapperImpl implements EventMapper {

    @Override
    public EventDto map(AbstractEvent event) {
        if ( event == null ) {
            return null;
        }

        EventDtoBuilder<?, ?> eventDto = EventDto.builder();

        eventDto.eventId( event.getId() );
        eventDto.requestorId( event.getRequestorId() );
        eventDto.draftSupported( supportsDraft( event ) );

        return eventDto.build();
    }
}
```

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-12-02T12:03:43+0000",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 11.0.8 (AdoptOpenJDK)"
)
public class MyEventMapperImpl implements MyEventMapper {

    @Override
    public MyEventDto map(MyEvent event) {
        if ( event == null ) {
            return null;
        }

        MyEventDtoBuilder<?, ?> myEventDto = MyEventDto.builder();

        myEventDto.eventName( event.getEventName() );
        myEventDto.requestorId( event.getRequestorId() );

        return myEventDto.build();
    }
}
```

As you can see, the `EventMapperImpl` is setting the `eventId` and `draftSupported` correctly:
*  `eventDto.eventId( event.getId() );`
* `eventDto.draftSupported( supportsDraft( event ) );`

But this logic does not make it into the `MyEventMapperImpl` class, which is strange as `myEventDto.requestorId( event.getRequestorId() );` is available in both of them.

**Comment by filiphr** [comment]
The reason why it doesn't work is because you are mixing `MapperConfig` and `Mapper`.

Currently `EventMapper` is a `@Mapper` which means that the mappers that have it in `uses` will use it to perform mappings, but not to inherit mappings. 

What you need is something like:

```
@MapperConfig
public interface EventMapperConfig {

    @Mappings({
        @Mapping(target = "eventId", source = "id"),
        @Mapping(target = "requestorId", source = "requestorId"),
        @Mapping(target = "draftSupported", source = "event", qualifiedByName = "supportsDraft"),
    })
    EventDto map(AbstractEvent event);
}
```

And then your `EventMapper` needs to look like:

```
@Mapper(uses = EventMapper.class, config = EventMapperConfig.class)
public interface MyEventMapper {

    @InheritConfiguration
    MyEventDto map(MyEvent event);
}
```

The important part is `@InheritConfiguration`. I removed the obsolete `@Mapping` as both `source` and `target` were the same.

**Comment by rj93** [comment]
Hi @filiphr, thank you for you reply. I appreciate it. I can now see how I am supposed to use this. I however am now running into a second issue. 

If I overload the `MyEventDto map(MyEvent event);` method for example, with some computed integer value that is computed externally then the tests for the `id` and `supportsDraft` are no longer mapped. 

An example with tests can be found [here](https://github.com/rj93/mapstruct-error/commit/d56780acd200bf4a0e0ae62a0cae4c26bcb7fb7d).

**Comment by rj93** [comment]
Ignore this. I found #1720 where you mention that is it [not supported](https://github.com/mapstruct/mapstruct/issues/1720#issuecomment-500403504).
