### ISSUE TITLE
Where is the @MappingConfig annotation

### ISSUE THREAD

**Issue by AnakinPt** [mapstruct/mapstruct#2293]
The documentation referes to an annotation @MappingConfig, but I don't find it in the code or any dependencies as I presumed it should be in the same package as the other annotations. Was this deleted and you forgot to update the documentation or it was deleted by mistake.

**Comment by filiphr** [comment]
That is a typo. The name of the annotation is `@MapperConfig`. We'll fix the documentation

**Comment by AnakinPt** [comment]
I thought it could be a way to add configuration to a method. I need that feature.

**Comment by filiphr** [comment]
Depends what you need to do, but there is `@BeanMapping` for methods.

**Comment by filiphr** [comment]
That particular request is identical to #2291, which I already explained how you can achieve it.
