### ISSUE TITLE
[QUESTION] haveField method

### ISSUE THREAD

**Issue by lex-em** [mapstruct/mapstruct#2299]
Hello!

I forgot some mapstruct feature - the `haveFeild` method, now I can't find it in documentation, but I remember using it. Can you explain it to me or give link? Now I can't reproduce it

```java
interface SomeMapper {
  Entity map(Dto dto);
}

class SomeMapperImpl implements SomeMapper {
  Entity map(Dto dto) {
    ...
    if (dto.haveData()) {
      entity.setData(dto.getData);
    }
    ...
  }
}
```

**Comment by filiphr** [comment]
Please do not use the issue tracker for asking questions. Please use the [Gitter room](https://gitter.im/mapstruct/mapstruct-users) for that instead.

What you are looking for is called [Source presence checking](https://mapstruct.org/documentation/stable/reference/html/#source-presence-check).

In your example the method needs to be called `hasData`.

**Comment by lex-em** [comment]
Thnx. I will use gitter in the future
