### ISSUE TITLE
Why does mapstruct compile slowly after using mapstruct.Is there any good solution?

### ISSUE THREAD

**Issue by wangfuguo** [mapstruct/mapstruct#2300]
It takes 5 minutes to compile the application before using mapstruct, and 20 minutes to compile after using mapstruct.Is there any good solution?

**Comment by filiphr** [comment]
Can you please provide some more information? Which version of MapStruct are you using? How many mappers do you have? How many methods per mapper do you have? How many mappers do you have in `Mapper#uses`?

Without such information we can't do much

**Comment by wangfuguo** [comment]
Version:1.3.0.Final    
There are about 250 mappers.
There are about 4 methods per mapper.

**Comment by wangfuguo** [comment]
> Can you please provide some more information? Which version of MapStruct are you using? How many mappers do you have? How many methods per mapper do you have? How many mappers do you have in `Mapper#uses`?
> 
> Without such information we can't do much

Version:1.3.0.Final
There are about 250 mappers.
There are about 4 methods per mapper.

**Comment by filiphr** [comment]
We did some performance improvements in 1.4. Can you please try that release out?

If it is still slow with 1.4, then I would suggest you to provide us with some profiling information or provide us with access to the project so we can have a look at it. Have a look at https://github.com/mapstruct/mapstruct/issues/1976 for some ideas for how to provide some profiling information.

**Comment by filiphr** [comment]
Closing this due to lack of feedback. We can reopen it if we get some more feedback

**Comment by passedbylove** [comment]
mapstruct 1.5.2.Final
it's too slow to compile mapping implements of Mapstruct, Convertor;
8 mapper class and about 20 methods.

9 class has no default constructor,  so i annonationed  with 

```java
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
 
@Target(ElementType.CONSTRUCTOR)
@Retention(RetentionPolicy.CLASS)
public @interface Default {
}
```

pom.xml realted plugins as bellow:
```xml
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.5.2.Final</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.22</version>
                        </path>
                        <!-- additional annotation processor required as of Lombok 1.18.16 -->
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                    <showWarnings>true</showWarnings>
                    <compilerArgs>
                        <arg>
                            -Amapstruct.suppressGeneratorTimestamp=true
                        </arg>
                        <arg>
                            -Amapstruct.suppressGeneratorVersionInfoComment=true
                        </arg>
                        <arg>
                            -Amapstruct.verbose=true
                        </arg>
                    </compilerArgs>
                </configuration>
            </plugin>
```

**Comment by passedbylove** [comment]
Once i increase the [Build,Execution->Deployment->Compiler] --Shared build process heap size(Mbytes) to larger, the problem sloved.

**Comment by filiphr** [comment]
@passedbylove if you would like us to have a look at performance problems we'll have to have access to the mappers you have. Otherwise, it is difficult for us to benchmark it. Feel free to reach out directly to me if you need to.
