### ISSUE TITLE
Getting either "Unknown property" or "Unmapped target property"

### ISSUE THREAD

**Issue by janinko** [mapstruct/mapstruct#2301]
I updated mapstruct from 1.3.1 to 1.4.1 and now I'm having problems mapping one class:
Having:
```java
    @Override
    @Mapping(target = "dependantBuildRecords", ignore = true)
    /*
     * Builder that MapStruct uses when generating mapper has method dependantBuildRecord() which confuses MapStruct as
     * he thinks it is a new property
     */
    @Mapping(target = "dependantBuildRecord", ignore = true)
    Artifact toEntity(org.jboss.pnc.dto.Artifact dtoEntity);
```
I'm getting following error:
```
ArtifactMapper.java:[68,14] Unknown property "dependantBuildRecord" in result type Artifact. Did you mean "dependantBuildRecords"?
```
And after removing the `@Mapping`
```java
    @Override
    @Mapping(target = "dependantBuildRecords", ignore = true)
    /*
     * Builder that MapStruct uses when generating mapper has method dependantBuildRecord() which confuses MapStruct as
     * he thinks it is a new property
     */
    // @Mapping(target = "dependantBuildRecord", ignore = true)
    Artifact toEntity(org.jboss.pnc.dto.Artifact dtoEntity);
```
I'm getting this error instead:
```
ArtifactMapper.java:[68,14] Unmapped target property: "dependantBuildRecord".
```
It seems that mapstruct is now confused more then before.
This is the Artifact class (stripped of unrelated stuff):
```
public class Artifact implements GenericEntity<Integer> {

    @ManyToMany(mappedBy = "dependencies")
    private Set<BuildRecord> dependantBuildRecords;

    public Set<BuildRecord> getDependantBuildRecords() {
        return dependantBuildRecords;
    }

    public void setDependantBuildRecords(Set<BuildRecord> buildRecords) {
        this.dependantBuildRecords = buildRecords;
    }

    public void addDependantBuildRecord(BuildRecord buildRecord) {
        dependantBuildRecords.add(buildRecord);
        buildRecord.getDependencies().add(this);
    }

    public void removeDependantBuildRecord(BuildRecord buildRecord) {
        dependantBuildRecords.remove(buildRecord);
        buildRecord.getDependencies().remove(this);
    }

    public static class Builder {

        private Set<BuildRecord> dependantBuildRecords = new HashSet<>();

        public Builder dependantBuildRecord(BuildRecord dependantBuildRecord) {
            this.dependantBuildRecords.add(dependantBuildRecord);
            return this;
        }

        public Builder dependantBuildRecords(Set<BuildRecord> dependantBuildRecords) {
            this.dependantBuildRecords = dependantBuildRecords;
            return this;
        }

    }
}
```

**Comment by filiphr** [comment]
Can you please share a git repository where this problem is easily reproducible. I tried the example you provided and it works correctly. The `Builder` is not used though, as MapStruct doesn't know about it.

However if you map into the `Builder` then for MapStruct there are 2 properties `dependantBuildRecord` and `dependantBuildRecords`. There is no way that we can determine that `dependantBuildRecord` is an adder.

**Comment by janinko** [comment]
The repositori is at https://github.com/project-ncl/pnc

I think that the problem is that buidler has `dependantBuildRecord` and `dependantBuildRecords` but the entity has only `setDependantBuildRecords`. 
Adding this to the entity removes the error, but that is obviously not a solution.
```
    public void setDependantBuildRecord(BuildRecord buildRecords) {
        throw new UnsupportedOperationException("This method needs to exists, just so we can ignore it.");
    }
```

**Comment by filiphr** [comment]
That's a big project 😄. I'll try to have a look at it, and isolate the problem to understand why it is happening. 

Perhaps there is some regression.

**Comment by filiphr** [comment]
I did some debugging and it turns out that the error message is happening for the `updateEntity` method in the `ArtifactMapper` which is correct as the `Artifact` does not have such a setter, but the `ArtifactBuilder` does have it.

I'll look into why it was working in 1.3.1 and try to see if we can somehow keep this behaviour.

**Comment by filiphr** [comment]
I managed to reproduce this and to fix the problem. Thanks a lot for reporting this @janinko
