### ISSUE TITLE
Support JSR 303

### ISSUE THREAD

**Issue by Sam-Kruglov** [mapstruct/mapstruct#2304]
This is a minor feature request to support `javax.validation` annotations like `@NotEmpty`, `@NotNull` etc.
So, if I map a DTO to an Entity, and the DTO has all the validation defined, I wish mapstruct would assume the validation is already done and skip the null checks (or other checks if applicable) for these fields but I still want it to check the fields without these annotations. 

So, it doesn't make much of a difference to check for null or not but I thought maybe it would be reasonable to do.

**Comment by filiphr** [comment]
@Sam-Kruglov I think that this is the same as #1243. Therefore I am closing this in favour of that one. In case you think that it isn't, please let me know and we'll reopen it.
