### ISSUE TITLE
qualifiedByName with Collection stopped working in 1.4

### ISSUE THREAD

**Issue by wicksim** [mapstruct/mapstruct#2311]
- [x] Is this an issue (and hence not a question)? 

This worked in 1.3.1.Final, and I couldn't find anything about this in the 1.4 release notes.

I've a mapping for an object with a collection as a property:

`@Mapping(source = "set", target = "list", qualifiedByName = "namedMapping")
  A map(B b);`

My `@Named`-Mapping ist only for single object, and not for set-to-list:

`@Named("namedMapping")
C map(D);`

Compiler now states:
`java: Qualifier error. No method found annotated with @Named#value: [ namedMapping]. See https://mapstruct.org/faq/#qualifier for more info.`
`java: Can't map property "Set<C> set" to "List<D> list". Consider to declare/implement a mapping method: "Set<C> map(List<D> value)".`

It still seems to work in cases when source and target have the same collection-type, but I'm no really sure about that.

**Comment by filiphr** [comment]
@wicksim this looks identical to https://github.com/mapstruct/mapstruct/issues/2250.

Have a look at https://github.com/mapstruct/mapstruct/issues/2250#issuecomment-719910576.

In a nutshell, the qualifiers are stricter not so you need to add a qualified mapping between `List<D>` and `Set<C>` for it to be picked up.
