### ISSUE TITLE
【big bug】Invalid generation result when use lombok 1.18.16

### ISSUE THREAD

**Issue by spyvip** [mapstruct/mapstruct#2313]
java: 8
lombok: 1.18.16
mapstruct: 1.4.1.final

example

source

````
@Data
public class ADTO implements Serializable {

    private Integer reasonCode;

}

@Data
public class InParams implements Serializable {

    private Integer reasonCode;

}
````

generation

````
@Override
    public ADTO toDTO(InParams inParams) {
        if ( inParams == null ) {
            return null;
        }

        ADTO aDTO = new ADTO();

        return aDTO;
    }

````

**Comment by junwangit** [comment]
I also have this big problem

**Comment by filiphr** [comment]
Please have a look at the [Lombok Changelog](https://projectlombok.org/changelog).

Lombok has a breaking change in 1.18.6 and you should add the [lombok-mapstruct-binding](https://search.maven.org/artifact/org.projectlombok/lombok-mapstruct-binding) to the `annotationProcessorPaths`.

**Comment by junwangit** [comment]
> Please have a look at the [Lombok Changelog](https://projectlombok.org/changelog).
> 
> Lombok has a breaking change in 1.18.6 and you should add the [lombok-mapstruct-binding](https://search.maven.org/artifact/org.projectlombok/lombok-mapstruct-binding) to the `annotationProcessorPaths`.

Ok, it has been resolved, thank you
