### ISSUE TITLE
Getting "variable is already defined" error

### ISSUE THREAD

**Issue by jkstrauss** [mapstruct/mapstruct#2316]
I am using trying to map an input parameter into my output object. In my example below I keep it simple to illustrate my problem, but I am suing to input parameters, one of them being a complex object, and the other a simple field, and the output combines them both.

In order to rule out any chance that this a problem with Lombok, I stripped my pom.xml to only include map-struct.

I get the following error when compiling.

`variable field1 is already defined in method test(java.lang.String)`

Workarounds exist such as explicitly mapping the field like this `@Mapping(target = "field", source = "field")`; making the field non-final and adding a setter; or using the `@Builder` annotation from Lombok.

This is the generated source code (with some blank lines removed):

    package com.temp;

    import javax.annotation.Generated;

    @Generated(
        value = "org.mapstruct.ap.MappingProcessor",
        date = "2020-12-27T14:45:43-0500",
       comments = "version: 1.4.1.Final, compiler: javac, environment: Java 1.8.0_181 (Oracle Corporation)"
    )
    public class TestMapperImpl implements TestMapper {
        @Override
        public Test test(String field) {
            if ( field == null ) {
                return null;
            }

            String field1 = null;
            field1 = field;
            String field1 = null;
            Test test = new Test( field1 );
            return test;
        }
    }

Here are my source files:

**TestMapper.java**
    package com.temp;

    import org.mapstruct.Mapper;

    @Mapper
    public interface TestMapper {
        Test test(String field);
    }

**Test.java**

    package com.temp;
    public class Test {
      private final String field;
      public Test(String field) {
        this.field = field;
      }
    }

**pom.xml**

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>

        <groupId>com.test</groupId>
        <artifactId>teset</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <packaging>jar</packaging>

        <name>test</name>
        <description>Test</description>

        <properties>
            <snapshot.version>${project.version}</snapshot.version>
            <java.version>1.8</java.version>
            <org.mapstruct.version>1.4.1.Final</org.mapstruct.version>
        </properties>

        <dependencies>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>
            
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.13.1</version>
                <scope>test</scope>
            </dependency>
        </dependencies>

        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.6.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${org.mapstruct.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </project>

**Comment by piteron** [comment]
Having exact same issue with the simplest configuration possible:

`fun map(id: String): UserId`

and the result is:
```
@Override
public UserId map(String id) {
    if ( id == null ) {
        return null;
    }

    String id1 = null;

    id1 = id;

    String id1 = null;

    UserId userId = new UserId( id1 );

    return userId;
}
```

on the other hand, when I change name to:
`fun map(userId: String): UserId`

it looks like this which is also wrong because of the null and lack of assignment:
```
@Override
public UserId map(String userId) {
    if ( userId == null ) {
        return null;
    }

    String id = null;

    UserId userId1 = new UserId( id );

    return userId1;
}
```

the UserId class is:
`data class UserId(val id: String)`

The interesting thing for me is that it worked with `fun map(userId: String): UserId` before I cleaned the project, right now it won't

**Comment by filiphr** [comment]
Thanks for the issue @jkstrauss. This looks like the same issue in #2251. You can try out the latest snapshot release or wait for 1.4.2.Final to be released.

**Comment by scss-mixins** [comment]
I experienced that problem and managed to resolve it https://stackdev.space/questions/can-you-please-explain-the-significance-of-a-string-identifier-in-java
