### ISSUE TITLE
Allow disabling an individual mapper's component model when a defaultComponentModel is specified

### ISSUE THREAD

**Issue by mjustin** [mapstruct/mapstruct#2325]
MapStruct allows overriding the default component model using the `componentModel` property of `@Mapper`.  However, I do not see a way of disabling the component model altogether if a non-`default` component model is set (per the [`mapstruct.defaultComponentModel`](https://mapstruct.org/documentation/stable/reference/html/#configuration-options) configuration option).  It appears that the existing "default" option for `@Mapper(componentModel = "default")` defers to whatever the configuration option is set to.

It seems a "none" option would be a useful addition, for instances where the developer wants to have a particular mapper opt out of using a component model.

```java
@Mapper(componentModel = "none")
```

**Comment by filiphr** [comment]
Can you explain the actual use case for this?

If you are using the configuration option you are basically overwriting everything that is defined in the annotations. That has the highest priority.

Why don't you instantiate the mapper manually instead of using the `Mappers` factory?

**Comment by mjustin** [comment]
> Can you explain the actual use case for this?

Sure. I have a number of mappers in the application I'm currently working on, most of which I want available as Spring Beans.  There are a few that are only used outside a Spring context (in my case, they're called within static methods of non-Spring managed data objects).  If an object is never going to be used as a Spring bean, I'd rather it not be included in the Spring context, so as to not confuse the issue.  In this case, I want to use the `Mappers` factory.  Granted, this is definitely not a blocker issue (it's not a big deal if a small mapper object gets added to the Spring context), but it is slightly less than ideal.

> If you are using the configuration option you are basically overwriting everything that is defined in the annotations. That has the highest priority.

This is literally the opposite of what [the documentation](https://mapstruct.org/documentation/stable/reference/html/#configuration-options) states:

> If a policy is given for a specific mapper via `@Mapper#unmappedTargetPolicy()`, the value from the annotation takes precedence.

**Comment by mjustin** [comment]
I have done some manual testing of this issue, and it turns out I was mistaken.

When I set the default component model compiler property per `-Amapstruct.defaultComponentModel=spring`, there is a difference between using `@Mapper` and `@Mapper(componentModel = "default")`.  When I use `@Mapper` without a `componentModel`, the Spring component model is used (that is to say, I see the `@Component` annotation added to the generated mapper Impl class).  When I specify `@Mapper(componentModel = "default")`, the Spring component model is not used (the generated class is not annotated with `@Component`).

That is all to say, I made the false assumption that `@Mapper` and `@Mapper(componentModel = "default")` would be equivalent, because the default component model declared in the annotation is `"default"`:

```java
public @interface Mapper {
    ...
    String componentModel() default "default";
    ....
}
```

I find this behavior highly surprising, since the `default` keyword implies that omitting the element means that default value is used instead.  However, this is not the observed behavior.  It seems like the annotation processor AST code must be distinguishing between explicitly setting the component model to "default" and omitting the component model from `@Mapper`.

With this in mind, my actual issue as reported is invalid.  Though it feels like there's instead another issue here: "Confusing nonstandard use of default annotation value in `@Mapper` componentModel".

**Comment by filiphr** [comment]
>I find this behavior highly surprising, since the `default` keyword implies that omitting the element means that default value is used instead. However, this is not the observed behavior. It seems like the annotation processor AST code must be distinguishing between explicitly setting the component model to "default" and omitting the component model from `@Mapper`.

The annotation processor AST is able to distinguish between explicitly setting a value or not for an annotation value. This is indeed a bit different to how the runtime processing of annotation works. If you know this difference then it should be fine.
This allows MapStruct to have simpler structure in elements such as `@Mapper` and allow using things like `@MapperConfig` or the compiler property. If you don't explicitly define it then you allow using the defaults provided via `@MapperConfig` or via the compiler property.

If you look at the Javadoc you will see

>The method overrides a componentModel set in a central configuration set by {@link #config() }


---- 

>With this in mind, my actual issue as reported is invalid. Though it feels like there's instead another issue here: "Confusing nonstandard use of default annotation value in `@Mapper` componentModel".


Do you perhaps have a suggestion how we can improve this? Would it help if we mention something in the documentation next to the compiler properties?

**Comment by mjustin** [comment]
> Do you perhaps have a suggestion how we can improve this? Would it help if we mention something in the documentation next to the compiler properties?

Looking at the documentation, that appears to be a great place to call it out:

> If a component model is given for a specific mapper via `@Mapper#componentModel()`, the value from the annotation takes precedence. Note that MapStruct differentiates between `@Mapper(componentModel = "default")` and `@Mapper()`, with the former using no component model, and the latter using the configured default.

I don't know how extensive this declared vs. default annotation usage is.  If it's used in quite a few places, it might make more sense to declare it once in the documentation, rather than in the documentation for each affected element.

In either case, it would also probably be helpful to call it out in the element's Javadocs, since that will often be what people are looking at:

> ```java
> * The method overrides a componentModel set in a central configuration set
> * by {@link #config() }.  Note that MapStruct differentiates between
> * `@Mapper(componentModel = "default")` and `@Mapper()`, with the former using no
> * component model, and the latter using the configured default.
> ```

As an aside, I just noticed that the [Javadoc for this element](https://javadoc.io/static/org.mapstruct/mapstruct/1.4.1.Final/org/mapstruct/Mapper.html#componentModel--) is wrong due to probably a bad copy/paste, as it refers to "unmappedTargetPolicy" and not "componentModel".

---

That all being said, my own personal preference would be to dodge the issue, and change the annotation so that it better matched the semantics of the Java default elements — where omitting it was exactly identical to specifying a value with the default.  If you chose to go that route, you could add a "none" option to the `componentModel` choices, and leave the default as "default".

Downside is that it would be a change in behavior for anyone currently explicitly using `@Mapper(componentModel = "default")`, though not one that is _likely_ to break code in practice, unless having an additional bean in the context breaks some careful config workarounds.  It would also be a higher effort change than updating the documentation.

> Specifies the component model to which the generated mapper should adhere. Supported values are
> * `default`: the mapper uses the default component model for the mapper as set by any central configuration
> * `none`: the mapper uses no component model, instances are typically retrieved via `Mappers.getMapper(Class)`
> * [...]

**Comment by filiphr** [comment]
I was checking the documentation and in the [Configuration options](https://mapstruct.org/documentation/stable/reference/html/#configuration-options) for `mapstruct.defaultComponentModel` we do say

>If a component model is given for a specific mapper via `@Mapper#componentModel()`, the value from the annotation takes precedence.

I think that this is enough.
>As an aside, I just noticed that the Javadoc for this element is wrong due to probably a bad copy/paste, as it refers to "unmappedTargetPolicy" and not "componentModel".

Yes I also realised this while checking it out. We'll fix that for the next release.

-----

Omitting the value or going with something else, would be a big effort on our side, as it is not just the `componentModel` that uses this approach, but every single configuration property for MapStruct. Therefore, I am going to close this issue.
