### ISSUE TITLE
java: Can't generate mapping method from iterable type to non-iterable type.

### ISSUE THREAD

**Issue by mambablack** [mapstruct/mapstruct#2326]
Hi~

this code compile failed, error message is 'java: Can't generate mapping method from iterable type to non-iterable type.'

I want to get the max score from a integer list.

also try [this](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-iterable-to-non-iterable) can not 
be resoled

mapstruct 1.4.1.Final

```
@Data
public class MaxScore {
    Integer maxScore;
    List<Integer> detail;
}
```

```
@Mapper
public interface ScoreConvert {

    @Mapping(target = "maxScore",expression = "java(detail.get(0))")
    @Mapping(target = "detail",source = "detail")
    MaxScore to(List<Integer> detail);
}
```

**Comment by filiphr** [comment]
With #607 we added support for mapping from non java iterable to a bean.

I think that we explicitly decided not to support such a case as it makes things more complex. Correct me if I am wrong @sjaakd 

I would suggest to do the following:

```
@Mapper
public interface ScoreConvert {

    default MaxScore to(List<Integer> detail) {
        return to(detail.get(0), detail);
    }

    MaxScore to(Integer maxScore, List<Integer> detail);
}
```

**Comment by mambablack** [comment]
> With #607 we added support for mapping from non java iterable to a bean.
> 
> I think that we explicitly decided not to support such a case as it makes things more complex. Correct me if I am wrong @sjaakd
> 
> I would suggest to do the following:
> 
> ```
> @Mapper
> public interface ScoreConvert {
> 
>     default MaxScore to(List<Integer> detail) {
>         return to(detail.get(0), detail);
>     }
> 
>     MaxScore to(Integer maxScore, List<Integer> detail);
> }
> ```

fixed  .  thank you very much .

**Comment by sjaakd** [comment]
> I think that we explicitly decided not to support such a case as it makes things more complex. Correct me if I am wrong @sjaakd

That is correct.. Checkout [this ](https://mapstruct.org/faq/#why-is-it-not-possible-for-mapstruct-to-generate-implementations-for-iterable-stream-and-map-types-from-update-mappingtarget-methods)for a more detailed explanation.

**Comment by alabotski** [comment]
I have the similar problem
```
@Data
public class GetProfileRq {
  private String id;
  private List<EmployeeIdDto> params;
}
```

And mapper
```
  @Mapping(target = "params", expression = "java((list != null) ? list : Collections.emptyList())")
  GetProfileRq toRq(List<EmployeeIdDto> list);

and

  @Mapping(target = "params", source= "list")
  GetProfileRq toRq(List<EmployeeIdDto> list);
```

And have error

[30,16] Can't generate mapping method from iterable type from java stdlib to non-it
erable type.


I change mapper to
```
  default GetProfileRq toRq(List<EmployeeIdDto> list) {
    return GetProfileRq.builder()
        .params((list != null) ? list : Collections.emptyList())
        .build();
  }

```

All works except one method from mapper
```
  @BeforeMapping
  default <T extends EmployeeRq> void setCommonInfo(@MappingTarget T rq) {
    rq.setId(getUUID());
  }
```
