### ISSUE TITLE
Better support for builder pattern entities 

### ISSUE THREAD

**Issue by mheidt** [mapstruct/mapstruct#2330]
If the class contains a static Builder inner class, the generated implementation only contains the line
```
Builder foo = FooClass.builder();
return foo.build();
```

I have to add 
`@Mapping(target="withId")
`
to get mapstruct add a line like
`foo.withId(dto.getId());`

It would be nice, if not only fields with get/set are considered but those that only have with-methods as well.

**Comment by filiphr** [comment]
This can easily be achieved by adding your custom `AccessorNamingStrategy`. Have a look at [this](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy) from our documentation for more information.

**Comment by mheidt** [comment]
Thanks Filip for the hint.
I took the time to read other chapters and found, that this generates the correct implementation

```
    @EnumMapping(nameTransformationStrategy = "with")
    LocationMM toMM(LocationDTO dto);
```

When I read chapter 3.8 Using builders and see the list of supported builder frameworks, I wonder why it's not done automatically.

It is this framework you could add to that list if you would:

https://github.com/graphql-java-generator

**Comment by mheidt** [comment]
Thanks Filip,
from your documentation:
`To use a custom SPI implementation, it must be located in a separate JAR file together with the file META-INF/services/org.mapstruct.ap.spi.AccessorNamingStrategy with the fully qualified name of your custom implementation as content (e.g. org.mapstruct.example.CustomAccessorNamingStrategy). This JAR file needs to be added to the annotation processor classpath (i.e. add it next to the place where you added the mapstruct-processor jar).`

Don't you think, that this a little much for something the user expects to be done automatically?
Using "with" in the Builder-Pattern is not that unusual.
By the way, I am not talking about a class I defined, but that is generated by 
https://github.com/graphql-java-generator

Or if you would deploy that CustomAccessorNamingStrategy in your plugin (after being renamed) and having a plugin maven config parameter.
I just need that!

**Comment by mheidt** [comment]
Actually that sample didn't work for GraphQL-Java generated classes
This one does:
```
public class GraphQLAccessorNamingStrategy extends DefaultAccessorNamingStrategy implements AccessorNamingStrategy {

    @Override
    public boolean isSetterMethod(ExecutableElement method) {
        if (super.isSetterMethod(method)){
            return true;
        }
        String methodName = method.getSimpleName().toString();
        return methodName.startsWith( "with" ) && methodName.length() > 4;
    }


    @Override
    public String getPropertyName(ExecutableElement getterOrSetterMethod) {
        String methodName = getterOrSetterMethod.getSimpleName().toString();
        String result = null;
        return methodName.startsWith( "with" ) ? IntrospectorUtils.decapitalize(methodName.substring( 4 )) : super.getPropertyName(getterOrSetterMethod);
    }

}
```
