### ISSUE TITLE
Flatten list in list

### ISSUE THREAD

**Issue by zacikpetr** [mapstruct/mapstruct#2336]
Hi,
I would need to simplify my code, so it would be possible to flatten list in list like this:
@Mapping(target = "targetList", source = "sourceList1.sourceList2")

My current solution is very dirty and it does not support `unmappedSourcePolicy = ReportingPolicy.ERROR`. I also need to support `@Context ` in mapping functions.

Thank you,
Petr

**Comment by filiphr** [comment]
I don't know how your solution looks like, but there are easy solutions that you could use to provide such flat mapping through default methods.

e.g.

```
@Mapper 
public interface MyMapper {


    @Mapping(target = "targetList", source = "sourceList1", qualifiedByName = "flatMapSourceList2")
    Target map(Source source, @Context MyContext context);

    @Named("flatMapSourceList2")
    default List<Target.Value> map(List<Source.Value> sourceList, @Context MyContext context) {
        // Here you can do the flat mapping, call another mapping method that would provide the single element mapping
        // and also use the `@Context` in the mapping functions.
    }
}
```

I think that providing such a support will come with a big maintenance burden and it will not be worth it.

If you have some ideas how we can easily implement this then please provide a PR for it so we can look into it, in the meantime I am going to close this issue.
