### ISSUE TITLE
MapStruct processor as maven provided dependency vs as a maven-compiler-plugin annotationProcessor

### ISSUE THREAD

**Issue by mhewedy** [mapstruct/mapstruct#2338]
I find the examples to install mapstruct is via the `maven-compiler-plugin` as an annotationProcessor.
Like the instructions here https://mapstruct.org/documentation/installation/

So I want to ask, how far it is prefered - if at all - over the other way of adding the processor as a provided dpenedency like:

```xml
<dependencies>
	<dependency>
		<groupId>org.mapstruct</groupId>
		<artifactId>mapstruct</artifactId>
		<version>${mapstruct.version}</version>
	</dependency>

	<dependency>  <!-- this one here -->
		<groupId>org.mapstruct</groupId>
		<artifactId>mapstruct-processor</artifactId>
		<version>${mapstruct.version}</version>
		<scope>provided</scope>
	</dependency>
</dependencies>
```

**Comment by filiphr** [comment]
Hey @mhewedy,

This is a good question for StackOverflow or our [Gitter Room](https://gitter.im/mapstruct/mapstruct-users). We try to keep the issues for feature requests and bug reports.

I think that the best answer for this is the documentation from the Maven Compiler Plugin about [`annotationProcessorPaths`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths).

>Classpath elements to supply as annotation processor path. If specified, the compiler will detect annotation processors only in those classpath elements. If omitted, the default classpath is used to detect annotation processors

This basically means that you won't use any internals of the mapstruct-processor by chance in your production code.

**Comment by mhewedy** [comment]
Thanks for clarifications and next time I will try to ask questions in the proper place 😊
