### ISSUE TITLE
Enum mapping. Throw exception for unexpected input

### ISSUE THREAD

**Issue by Chaos-UA** [mapstruct/mapstruct#2339]
For example we have

```
class EnumA {
       VALUE1,
       VALUE2
}
```

and 

```
class EnumB {
       VALUE1,
       VALUE2,
       VALUE3
}
```

It would be very helpfull to add posibility to throw exception when "VALUE3" will be as an input value instead of failing compilation. Something like this:
```
@ValueMapping(target = MappingConstants.THROW_EXCEPTION, source = "VALUE3")
EnumA toEnumA(EnumB source)
```

At the moment it is only possible to set it to null or to another existing value, but not to throw some IllegalArgumentException etc.

**Comment by filiphr** [comment]
This sounds like a reasonable improvement.

What would the exception message contain? Currently, for the default exception throwing it is "Unexpected enum constant: XXX". Does it make sense to throw this exception as well?

In addition for enum mappings this can also be used to remove the missing Any Unmapped or Any Remaining warning for String to Enum mappings.

I think that this issue is relatively easy to implement. @Chaos-UA would you me interested in providing a PR for it? Otherwise, is someone else from the community interested in adding this functionality? The MapStruct team is of course always here to help out.

**Comment by filiphr** [comment]
Some discussions from PR https://github.com/mapstruct/mapstruct/pull/2354.

We need to think what we should do when inversing something like 

```
@ValueMapping(target = MappingConstants.THROW_EXCEPTION, source = "VALUE3")
```

most likely we should ignore them, as they don't make much sense. Having said that `MappingConstants.THROW_EXCEPTION` should also be only applicable to `ValueMapping#target()` and not `ValueMapping#source()` since we can't map from exceptions.

**Comment by JudeNiroshan** [comment]
@filiphr  I'd like to give a try. This would be my first contribution to mapstruct.

**Comment by filiphr** [comment]
Thanks for the initiative @JudeNiroshan. I've assigned this one to you. Please let us know if you have any questions

**Comment by JudeNiroshan** [comment]
@filiphr can you help me with running the unit tests in IntelliJ IDEA?

Whenever I try to run a test class(entire class), I get this error. 

```
Process finished with exit code 1
Class not found: "org.mapstruct.ap.test.value.enum2enum.EnumToEnumMappingTest"
```

I believe there is something that needs to be changed in my run configurations. This is how it looks:
<img width="1067" alt="Screenshot 2021-02-16 at 10 25 13" src="https://user-images.githubusercontent.com/16539159/108043313-43f13b00-7041-11eb-8520-37d4d9c89eb9.png">

**Comment by filiphr** [comment]
I have Java 11 locally. What I usually do is to run the test from the IDE directly. Did you manually create this or did you run it from the IDE?

I also have a slightly newer version of IntelliJ. For me it looks like:

![image](https://user-images.githubusercontent.com/6012094/108112284-2a2e1300-7096-11eb-9463-763173c3c8d5.png)

**Comment by JudeNiroshan** [comment]
>Did you manually create this or did you run it from the IDE?


I simply tried to run through IDEA. I tried now by selecting jdk11 but still no success. 

<img width="1067" alt="Screenshot 2021-02-16 at 21 01 46" src="https://user-images.githubusercontent.com/16539159/108115291-3025f300-709a-11eb-8ac4-15ae9f1bf2bd.png">

**Comment by JudeNiroshan** [comment]
@filiphr Thanks, It was an Intellij IDEA problem. This answer helped me to fix it -> https://stackoverflow.com/a/33760645/4506140

Now I can run unit tests 😄 
<img width="1487" alt="Screenshot 2021-02-16 at 21 09 03" src="https://user-images.githubusercontent.com/16539159/108116152-6dd74b80-709b-11eb-87ea-9ed11f11d51f.png">

**Comment by JudeNiroshan** [comment]
@filiphr can you help me to understand the flow of execution for unit tests that resides under `processor` sub-module?

I can see there is a resources folder resides there. I have created a new Test Enum by myself just to start with. It seems like I should have manually put the generated source for any new interface that I create. For e.g:

```
@Mapper
public interface BrokenOrderMapper {

    BrokenOrderMapper INSTANCE = Mappers.getMapper( BrokenOrderMapper.class );

    @ValueMappings({
            @ValueMapping(source = "MONDAY", target = "MONDAY")
    })
    JudeTarget orderTypeToExternalOrderTypeWithThrownException(JudeSrc orderType);
}
```

Above interface needs to have the impl class. I see that already existing interfaces, impl classes are located under the `processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/enum2enum`. How do I generate the impl class for my newly added `BrokenOrderMapper` interface?

**Comment by filiphr** [comment]
This is a really good question @JudeNiroshan. We didn't have anything, but you inspired me and I wrote something. Have a look at [this](https://mapstruct.org/development/testing-mapstruct/) on our website. I hope that it is clear.

In a nutshell

1. This is usually located in `target/compilation-test/<fullTestName>`
2. No you don't need to put the impl class anywhere
3. Our tests are kinda like parametrized tests. One tests is run using the javac compiler and another one the ecj compiler from Eclipse.

You don't need to add test fixtures and implementation classes. We do that sometimes when we want to validate that the code we generate is OK.

I hope that the link I shared will help you. If not please let me know and I can try to improve it. You can of course add suggestions for it as well.

**Comment by JudeNiroshan** [comment]
Thanks for your informative reply.🙇🏾‍♂️  I guess everything that I was looking for is in that link. Now I understand the test structure.

**Comment by JudeNiroshan** [comment]
@filiphr As I mentioned in a previous comment, I was playing around with tests. So I created a new Mapper interface(`BrokenOrderMapper`). I put this into Unit test classes level annotation. But now I get this error:

`java.lang.AssertionError: No reference file could be found for Mapper org.mapstruct.ap.test.value.enum2enum.BrokenOrderMapper. You should create a file fixtures/org/mapstruct/ap/test/value/enum2enum/BrokenOrderMapperImpl.java`

**Comment by JudeNiroshan** [comment]
@filiphr here is my first PR 😊 -> https://github.com/mapstruct/mapstruct/pull/2362

**Comment by filiphr** [comment]
Awesome @JudeNiroshan 🎉 . We'll review it shortly

**Comment by filiphr** [comment]
Closing this since the PR has been integrated. Thanks @JudeNiroshan for your work on it.
