### ISSUE TITLE
Sponsoring MapStruct

### ISSUE THREAD

**Issue by Tiller** [mapstruct/mapstruct#2340]
Hi,
Just a quick question: have you ever considered creating a Patreon, or a Github Sponsors?

I'd love to help / thanks mapstruct's developers. Even if it's not much, with time it can be a good small addition. For example, Lombok has a patreon and is making $140+ per month with 46 patreons

**Comment by filiphr** [comment]
Hey @Tiller,

To be honest we haven't really thought about doing something like this. However, the fact that you are raising such an issue means that there might be interest in the community in providing such support for the MapStruct team. I will talk with the team and see if we can come up with some plan for this. We will keep you updated.

**Comment by donaldpipowitch** [comment]
We'd also like to consider this project for our yearly sponsoring. (Next round would be in January.)

**Comment by filiphr** [comment]
Thanks for letting us know @donaldpipowitch. We are looking into this and how we can enable and use sponsoring for MapStruct. We'll provide more information soon.

**Comment by yellelieder** [comment]
Just for the record as we have already spoken @filiphr. We from adesso SE are also looking for a way to support mapstruct financially.

**Comment by filiphr** [comment]
Hey everyone, we would like to thank you for asking us for how to be able to sponsor us. We've been working on this a bit and we have create a [MapStruct Open Collective](https://opencollective.com/mapstruct) that you can use. We are also in the process of having this linked directly with GitHub sponsors.

We'll add this information to our README as well
