### ISSUE TITLE
Different DTOs are mapped in the same Mapper class

### ISSUE THREAD

**Issue by EinBlatt** [mapstruct/mapstruct#2344]
Hello author for mapperstruct

I tried to write two methods entityTransformDto and entityTransformDtoList in a mapper for mapping entity to DTO, List<entity> to List<ListDTO>

The target DTO of the two methods are different
But after the project is compiled

The for loop in the entityTransformDtoList method calls the entityTransformDto method
This doesn't solve my problem

I think the entityTransformDtoList method can generate a method to convert to ListDTO during the compilation process.
Then it would be better to call this generated method in the for loop of entityTransformDtoList

**Comment by EinBlatt** [comment]
This shouldn't be a problem

**Comment by filiphr** [comment]
Hey @EinBlatt, I am not sure if I understood you correctly. If you don't want your entityTransformDto method to be considered for the entityTransformDtoList you need to mark it with `@Named`, basically saying that this method is a special method and that it should only be used if explicitly picked up via `qualifiedByName` or `qualifiedBy`.

If I am wrong please let me know and we can reopen the issue. Please provide some example code as well, so I can better understand your problem.
