### ISSUE TITLE
如何解决jpa的同一张表里面，有子数据的情况，即 表里面有parent_id

### ISSUE THREAD

**Issue by roneywei** [mapstruct/mapstruct#2345]
- [ ] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by xiejin90314** [comment]
这个问题跟MapStruct啥关系? 去jpa,哪怕是hibernate提问也好呀

**Comment by filiphr** [comment]
From my awesome Google Translate skills I think that this has nothing to do with MapStruct.

Therefore, I am closing this issue. Please reopen it, if you think otherwise.
