### ISSUE TITLE
Compilation failure when mapper interface is a private nested interface

### ISSUE THREAD

**Issue by mjustin** [mapstruct/mapstruct#2347]
When a private nested interface is declared as a `@Mapper`, three compilation warnings are emitted in the generated class.  It's not completely communicated to the user _why_ this error is happening (though the private warnings are a big hint), nor have I encountered documentation stating that this usage should not be allowed.

It feels like this scenario should be handled better — either by allowing it; or by disallowing it, documenting it, and making the error messaging indicate the restriction against private nested interface mappers.

Note that changing the interface to non-private resolves the compilation issue, so a workaround is to have it be the default package private visibility.  That said, if the mapper is only used internally to a single class, it is natural to want to make it private in this manner.  

## Class:

```java
public class ClassWithPrivateMapper {
    public TargetType doSomething(SourceType source) {
        return Mappers.getMapper(PrivateMapper.class).map(source);
    }

    @Mapper
    private interface PrivateMapper {
        TargetType map(SourceType source);
    }
}
```

## Output:

```
/path/to/ClassWithPrivateMapper$PrivateMapperImpl.java:11: error: modifier private not allowed here
private class ClassWithPrivateMapper$PrivateMapperImpl implements PrivateMapper {
        ^
/path/to/ClassWithPrivateMapper$PrivateMapperImpl.java:3: error: PrivateMapper has private access in ClassWithPrivateMapper
import com.example.ClassWithPrivateMapper.PrivateMapper;
                                         ^
/path/to/ClassWithPrivateMapper$PrivateMapperImpl.java:11: error: PrivateMapper has private access in ClassWithPrivateMapper
private class ClassWithPrivateMapper$PrivateMapperImpl implements PrivateMapper {
                                                                  ^
3 errors
```

**Comment by filiphr** [comment]
Yes we should disallow such a generation of a mapper.

However, one can also argue that there is no point in defining private interface. If you define a private interface then there is no way for MapStruct to generate the mapping code as a private class is not accessible from anywhere.

**Comment by mjustin** [comment]
> If you define a private interface then there is no way for MapStruct to generate the mapping code as a private class is not accessible from anywhere.

I think that's true given MapStruct's model of creating its classes in their own separate class files.  If the generated mapper code were instead created as a nested static class of the interface's enclosing class, then it would work, since two private nested classes of the same parent source can reference each other.

That said, I highly suspect that such a workaround for this sort of niche case is not at all worth the return on investment, unless this solution was being used elsewhere as well.

**Comment by filiphr** [comment]
>I think that's true given MapStruct's model of creating its classes in their own separate class files. If the generated mapper code were instead created as a nested static class of the interface's enclosing class, then it would work, since two private nested classes of the same parent source can reference each other.

Your `PrivateMapper` is only accessible from `ClassWithPrivateMapper` and MapStruct cannot generate code in the `ClassWithPrivateMapper`.Annotation processors should only generate classes in separate class files. Generating classes in existing class files is not supported by the Java annotation processing API and internal APIs need to be used, this is extremely brittle and doesn't work well with other annotation processors.

I'll keep this here to generate an error in case the class trying to be generated is private.
