### ISSUE TITLE
Passing of mapping method argument to a property and using @InheritInverseConfiguration

### ISSUE THREAD

**Issue by neowin35** [mapstruct/mapstruct#2356]
```java
import org.mapstruct.*;

@Mapper
public interface CarMapper {
    class Car {
        public String brand;
        public String model;
        public String modelInternational;
    }
    class CarDTO {
        public String brand;
        public String modelName;
    }

    @Mapping(target = "modelName", source = "in")
    CarDTO map(Car in);

    default String mapToModel(Car in){
        return in.modelInternational==null? in.model : in.modelInternational;
    }

    @InheritInverseConfiguration
    @Mapping(target = "model", source = "modelName")
    @Mapping(target = "modelInternational", ignore = true)
    Car map(CarDTO in);
}
```

This code is compiling fine in 1.3.1.FINAL but in 1.4.2.FINAL gives following compile error: 
`Unknown property "in" in result type CarMapper.Car. Did you mean "brand"?`

Is that change of behavior on purpose?

**Comment by neowin35** [comment]
I found out that using "." instead of the argument name works fine. 

```java
@Mapping(target = "modelName", source = ".")
CarDTO map(Car in);
```

**Comment by wangfengqi2010** [comment]
@neowin35 
`Mapping(target = "modelName", source = "in")  `
"in" is not a property of Car

**Comment by filiphr** [comment]
@wangfengqi2010  the `@Mapping(target = "modelName", source = "in")` is valid since it matches the method parameters, so it will call the custom `String mapToModel(Car)` 

@neowin35 thanks for reporting this, this is indeed a bug. We should ignore the reversing of this `@Mapping`
