### ISSUE TITLE
mapstruct can't work with resteasy reactive in quarkus

### ISSUE THREAD

**Issue by yuhaibohotmail** [mapstruct/mapstruct#2357]
Can't inject a maaper  when  I use  with resteasy reactive in quarkus,  but it worked fine with  resteasy  in quarkus 
The quarus version is 12.0.0.CR1.

**Comment by filiphr** [comment]
Can you please provide some more information?

What doesn't work? MapStruct has nothing to do with those 2 frameworks. If you can't inject it it means that for whatever reason your configuration is not entirely correct, or the injection in quarkus works differently with reactive resteasy

**Comment by yuhaibohotmail** [comment]
Thank you for your reply.
I verified that this is a quarkus's bug.
[](https://github.com/quarkusio/quarkus/issues/15028)
