### ISSUE TITLE
qualifiedByName不存在时，会使用上一个方法

### ISSUE THREAD

**Issue by yukai3804** [mapstruct/mapstruct#2364]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/7309823/108825504-133f7180-75fe-11eb-8632-2ca1563b7165.png">

该类没有写divideMillion，只写了divideHundred
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/7309823/108825597-31a56d00-75fe-11eb-8091-d60b59f8f04b.png">

**Comment by filiphr** [comment]
@yukai3804 this looks really similar to #2288. In order to better help you we need to see the `CompetitionProjectFacadeAssembler`. 

I am also not sure what you are showing. You don't have a `divideMillion` method, so not sure how you expect we to use one?
