### ISSUE TITLE
Update documentation in regards to Java version

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#2366]
The docs still state there's experimental support for Java 9, but I think by now we're pretty sure it just works fine?

**Comment by filiphr** [comment]
You are right @gunnarmorling. The support is no longer experimental and the add modules is also not needed.

**Comment by JudeNiroshan** [comment]
@filiphr can you point to the places where it needs to be corrected exactly? I guess I can make those changes ☺️

**Comment by filiphr** [comment]
That would be great @JudeNiroshan. Have a look at https://github.com/mapstruct/mapstruct/blob/master/documentation/src/main/asciidoc/chapter-2-set-up.asciidoc. Search for "Using MapStruct on Java 9"

**Comment by JudeNiroshan** [comment]
Pr opened -> https://github.com/mapstruct/mapstruct/pull/2371 
Any possible modifications are most welcomed!
