### ISSUE TITLE
Make target the first parameter in all the uses of @Mapping

### ISSUE THREAD

**Issue by jvwilge** [mapstruct/mapstruct#2368]
There are some inconsistencies  in the documentation (md, asciidoc, javadoc) and the unit tests with the order of the parameters (`target` is not always before `source`) in the `@Mapping` annotations.

I asked a question about this : https://groups.google.com/d/msgid/mapstruct-users/977d0938-0781-4531-83c2-5c5832a88109n%40googlegroups.com?utm_medium=email&utm_source=footer

I already started on fixing all the docs, will start on the unit tests and create a PR afterwards.

**Comment by filiphr** [comment]
Thanks for aligning everything @jvwilge. Closing this issue since we merged your PR (#2369)
