### ISSUE TITLE
可以修改默认的构造方法吗

### ISSUE THREAD

**Issue by yukai3804** [mapstruct/mapstruct#2379]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/7309823/110885341-a4625800-8321-11eb-86d0-00178122405e.png">

请问大佬，这种自定义构造创建目标对象可以实现吗

**Comment by filiphr** [comment]
Hey @yukai3804,

Unfortunately, I cannot really understand what you are trying to ask. I tried using Google Translate, but I still do not understand the question.

I would suggest using StackOverflow for asking questions.
