### ISSUE TITLE
Document markdown syntax issues

### ISSUE THREAD

**Issue by BakaRice** [mapstruct/mapstruct#2385]
- [x] Is this an issue (and hence not a question)? 

I was looking through the documentation and found some minor markdown syntax errors in section 5.1 of the article, and while they don't affect the reading, I thought I'd raise this little issue.

> https://mapstruct.org/documentation/stable/reference/html/#implicit-type-conversions

From the article：Due to backward compatibility reasons the default value is 'ReportingPolicy.IGNORE`.

I think it should be like this：Due to backward compatibility reasons the default value is `ReportingPolicy.IGNORE`.

**Comment by filiphr** [comment]
Thanks for the issue. You are right there was a typo there.

Just pushed a fix for this
