### ISSUE TITLE
Error when upgrading 1.3.1.Final -> 1.4.x

### ISSUE THREAD

**Issue by merzbird** [mapstruct/mapstruct#2387]
I have troubles migrating my codebase to newer version of MapStruct.

```java
class TestNoSource {
    public static class TestDTO {
        public String foo;
        public String bar;
    }
    public static class TestModel {
        public String foo;
    }
    @Mapper
    interface TestMapper {
        @Mapping(target = "bar", defaultValue = "baz")
        TestDTO toDto(TestModel model);
    }
    @Test
    void shouldMap() {
        var model = new TestModel();
        model.foo = "42";
        var dto = Mappers.getMapper(TestMapper.class).toDto(model);
        assertEquals("42", dto.foo);
        assertNull(dto.bar);
    }
}
```

The code above works fine with `1.3.1.Final`, but any version `1.4.x` emits this error:
>java: The type of parameter "model" has no property named "bar". Please define the source property explicitly.

Is it expected (maybe I am relying on some erroneous behavior here and it was fixed) or some kind of a regression?

**Comment by filiphr** [comment]
Can you share how does the generated code look like in 1.3?

I don't know what your intention was, but the mapping which is there is incorrect. The behaviour in 1.4 is correct.

Basically when you write `@Mapping(target = "bar", defaultValue = "baz")` it is the same as writing `@Mapping(target = "bar", source = "bar", defaultValue = "baz")`. You are telling MapStruct to map `bar` and if `bar` in the source is `null` then use the default value `baz`.

Most likely you are looking for  `@Mapping(target = "bar", constant = "baz")`. This mapping means that the target `bar` has a fixed value of `baz` always.

**Comment by merzbird** [comment]
I agree that mapping itself doesn't make a lot of sense (but it was in our codebase), just wanted to check if change in the library behavior was intentional and not some unknown bug. 
Thanks for clarification.
