### ISSUE TITLE
Kotlin Data Class with Boolean property with `is` prefix

### ISSUE THREAD

**Issue by molokoka** [mapstruct/mapstruct#2388]
- [ ] Is this an issue (and hence not a question)? 

Whenever I'm trying to map Java(Protobuf) class to Kotlin data class with Boolean property that starts with `is`:
```kotlin
data class Foobar(
  val isFoobarBooleanFlag: Boolean
)
```
Kotlin generates next accessor method: `isFoobarBooleanFlag()` and MapStruct reads property name as `foobarBooleanFlag`. And fails to map from Java's accessor method`public boolean getIsFoobarBooleanFlag()`.
Is this correct behaviour?

**Comment by aerisnju** [comment]
It seems that we can use the annotation as a workaround:
```kotlin
@Mapping(target = "isFoobarBooleanFlag", source = "foobarBooleanFlag")
```

**Comment by filiphr** [comment]
This is not a problem of MapStruct. We do not look into the names of the fields, but we look into the accessors.


The Kotlin data class:

```
data class Foobar(
  val isFoobarBooleanFlag: Boolean
)
```
exposes a method `isFoobarBooleanFlag`. Which means that the property is `foobarBooleanFlag`.

If you have a Java access method `public boolean getIsFoobarBooleanFlag()` them MapStruct will treat this property as `isFoobarBooleanFlag`. There is already a `get` in front of the method, there is no way for us to know that we need to also remove the `is`.

I would suggest into looking why your Java accessor is created with a `get` and perhaps you need to tweak your code generation and analyse whether it makes sense for you to have a field starting with `is`.

What @aerisnju proposed is the workaround you need for the problem with your accessor.

Closing this as there is nothing that we can do about this from MapStruct side
