### ISSUE TITLE
Nested mapping results in empty object

### ISSUE THREAD

**Issue by gregory-j-baker** [mapstruct/mapstruct#2394]
The following mapping configuration generates an empty, non-null target object when the source is null:

```
@Mapping(source = "applicationStatusId", target = "applicationStatus.id")
ApplicationDto toDto(Application application);
```

The implemented method ends up being this:

```
protected ApplicationStatusDto applicationToApplicationStatusDto(Application application) {
	if ( application == null ) {
		return null;
	}

	ca.blablabla.dto.ImmutableApplicationStatusDto.Builder applicationStatusDto = ImmutableApplicationStatusDto.builder();

	if ( application.getApplicationStatusId() != null ) {
		applicationStatusDto.id( application.getApplicationStatusId() );
	}

	return applicationStatusDto.build();
}
```

Is there a way to have the implementation return null if the source is null?

**Comment by antonvovk** [comment]
Hi @gregory-j-baker
But the source code of the implemented method you have provided returns null if the source is null
```java
if (application == null) {
        return null;
}
```

**Comment by gregory-j-baker** [comment]
The problem is the nested field is instantiated and then not populated.

I fixed the problem with an @AfterMapping after finding another issue that discussed this exact problem. Sorry I can't link to it because I'm on mobile right now.

I'll close this issue.
