### ISSUE TITLE
TARGET_IMMUTABLE treated as ACCESSOR_ONLY instead of SETTER_PREFERRED

### ISSUE THREAD

**Issue by Sirttas** [mapstruct/mapstruct#2395]
Basically the title, the annotation processor doesn't want to use `addAll` and ask me to create a setter for the collection, but the javadoc says otherwise.

**Comment by filiphr** [comment]
The Javadoc says:

>Identical to {@link #SETTER_PREFERRED}, however the target collection will not be cleared and accessed via
> addAll in case of updating existing bean instances, see: {@link MappingTarget}.
>
> Instead the target accessor (e.g. set) will be used on the target bean to set the collection.

Which means that it will use a setter on the target bean to set the collection and will not be cleared and accessed via `addAll`.

The sheer definition of `TARGET_IMMUTABLE` means that the target collection is immutable, i.e. updating it by clearing it or using `addAll` means that there will be a runtime exception if the collection is immutable or unmodifiable.
