### ISSUE TITLE
Mapstruct not working with vscode

### ISSUE THREAD

**Issue by PandaGeek1024** [mapstruct/mapstruct#2396]
This is mygradle setup:
```
	implementation 'org.mapstruct:mapstruct:1.4.2.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'
```
My mapper file:
```
@Mapper(componentModel = "spring")
public interface SafetyPlanMapper {
    @BeanMapping(nullValuePropertyMappingStrategy  = NullValuePropertyMappingStrategy.IGNORE)
    void updateSafetyPlanEntityFromDto(SafetyPlan dto, @MappingTarget SafetyPlanEntity entity);
}
```
And obviously the files are generated:
![image](https://user-images.githubusercontent.com/3827781/112737859-97e92b00-8fc2-11eb-8845-c8f4cd88a419.png)

Then I reference it by:
```
@Autowired
SafetyPlanMapper safetyPlanMapper;
```
But when I run it, it gets this error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field safetyPlanMapper in com.ahurufoundation.management.domain.service.SafetyPlanService required a bean of type 'com.ahurufoundation.management.data.mysql.entity.mapper.SafetyPlanMapper' that could not be found.

```

**Comment by filiphr** [comment]
This has nothing to do with MapStruct. You need to make sure that the MapStruct mappers are component scanned by Spring.

**Comment by ad798** [comment]
Hi @filiphr ! I am facing almost the same problem with vscode, but I can't see the generated implementation of the mapper. So, here is the repo so you can check it (the problem is in the "teacher" branch). Thank you in advance!
[Repo](https://github.com/ad798/demo-spring/tree/teacher)
