### ISSUE TITLE
How to control the sequence of values

### ISSUE THREAD

**Issue by penweizgx** [mapstruct/mapstruct#2414]
![image](https://user-images.githubusercontent.com/6983487/114653655-18c25980-9d1b-11eb-91c8-766e98c3a5fc.png)

**Comment by filiphr** [comment]
I don't know what you are expecting MapStruct to do here?

In the [Using Constructors](https://mapstruct.org/documentation/stable/reference/html/#mapping-with-constructors) section of our documentation we document how the constructors are detected.

It seems like you have a bean which is in another jar. The bean constructor is not annotated with `@ConstructorProperties` (from any package) nor the jar is compiled with Java 8 `--parameters` flag.
