### ISSUE TITLE
"uses" is ignored when at least one related properties is ignored

### ISSUE THREAD

**Issue by gcorsaro** [mapstruct/mapstruct#2415]
I have an issue that I think it's a bug.

I have a mapper which uses another mapper
```
@Mapper(unmappedTargetPolicy = ReportingPolicy.WARN, uses = {SecondMapper.class}, imports = {UUID.class, Collectors.class})
public abstract class FirstMapper
```
In this mapper I have some methods that use `SecondMapper` in java expression like
```
@Mappings({
	@Mapping(target = "myColl", expression="java(secondMapper.collDTOToColl(aDTO.getMyColl))"),
})
public abstract A mapperMethod1(ADTO aDTO);
```

Everything works well until _secondMapper_ is used by other methods, but if I ignore the properties where it is used, then the _secondMapper_ variable is removed from the implementation, leading to have a compilation error in the java expression.
I think it's a sort of optimization done by the processor when **used** mappers aren't detected.
Just for information, I'm using mapstruct with spring (which means that _secondMapper_ is autowired)

**Comment by filiphr** [comment]
This works as designed. MapStruct will only inject other services if they are used in known mappings. If you want to use it in expressions then you should inject it yourself in your abstract class.
