### ISSUE TITLE
defaultExpression incorrectly generated when applied on a root source objects

### ISSUE THREAD

**Issue by patrykwoj** [mapstruct/mapstruct#2418]
Hello,
So I have prepared the following mapper:

```java
@Mapping(target = "requestId", source = "nullableParam", defaultExpression= "java(UUID.randomUUID().toString())")
@Mapping(target = "anotherProperty", source = "anotherParam") 
@Mapping(target = "yetAnotherProperty", source = "yetAnotherParam")
MyPojo mapMyPojo(String nullableParam, String anotherParam, String yetAnotherParam)
```

and this causes following code to be generated:

```java
@Override
public MyPojo mapMyPojo(String nullableParam, String anotherParam, String yetAnotherParam) {
   if ( nullableParam == null && anotherParam == null && yetAnotherParam == null) {
      return null;
   }
   MyPojo myPojo = new MyPojo();
   
   if (nullableParam != null) {
      if (nullableParam != null) {
         myPojo.setRequestId(nullableParam);
      } else {
         myPojo.setRequestId(UUID.randomUUID().toString());
      }
   }
   (...)
}
```

due to this double nested null check on `nullableParam` the `else` statement that actually does the `defaultExpression` logic is never reached. 

Im not sure if that is a bug or done like this by design, but imagine nullableParam being HTTP request header value that is optional and when is not provided some additional logic is called. In this case i cannot properly map this and have to place this defaultExpression logic in some different layer.

I've checked that on both 1.4.0.Final and 1.4.2.Final ,
Hope I described everything in simple understandable way.

Best Regards,

**Comment by filiphr** [comment]
Thanks for the detailed issue @patrykwoj. This has already been fixed and will be part of the 1.5 release. See #2023
