### ISSUE TITLE
Mapstruct mappers diamond inheritance, method is already defined

### ISSUE THREAD

**Issue by bladekp** [mapstruct/mapstruct#2437]
I have following situation, I simplified my actual case and I created minimum example showing my case:

![inheritance (1)](https://user-images.githubusercontent.com/5969699/117512495-02ad5f00-af90-11eb-987b-05b17bb665b8.png)

Two empty, not relevant in this example, classess `Phone` and `PhoneDto`, and mappers inheritance structure, `TestSuperMapper` with one method declaration to map `PhoneDto` to `Phone`, two empty interfaces `TestParent1Mapper` and `TestParent2Mapper` both extending `TestSuperMapper`, one actual mapper interface `TestMapper` annotated with `@Mapper` extending both `TestParent1Mapper` and `TestParent2Mapper`, and `TestMapperImpl` class implementing `TestMapper` generated by mapstruct. Problem with this setup is that mapstruct generates `TestMapperImpl` with following content:
```
import javax.annotation.processing.Generated;

@Generated(...)
public class TestMapperImpl implements TestMapper {

    @Override
    public Phone map(PhoneDto phoneDto) {
        if ( phoneDto == null ) {
            return null;
        }

        Phone phone = new Phone();

        return phone;
    }

    @Override
    public Phone map(PhoneDto phoneDto) {
        if ( phoneDto == null ) {
            return null;
        }

        Phone phone = new Phone();

        return phone;
    }
}
```
So it won't comple, as method `Phone map(PhoneDto)` is declared twice, one is coming via `TestParent1Mapper` inheritance path, second via `TestParent2Mapper`. Mapstruct version 1.4.1.Final, jdk 11. Actual javac exception is `java: method map(PhoneDto) is already defined in class TestMapperImpl.`

**Comment by filiphr** [comment]
Thanks for the good analysis @bladekp. This is indeed a problem and we have a fixing upcoming for this.

In the meantime you will have to override the problematic methods in the `PhoneMapper`
