### ISSUE TITLE
DependsOn is poor documented

### ISSUE THREAD

**Issue by Nashev** [mapstruct/mapstruct#2441]
At the present time, it refers to "result type properties", while the rest of the mapping code refers to "source" or "target" rather than "result". And the description of this property does not contain an example. And in the description mentioned some "Returns", but this is an argument of annotation and not a function!

> One or more properties of the result type on which the mapped property depends. The generated method implementation will invoke the setters of the result type ordered so that the given dependency relationship(s) are satisfied. Useful in case one property setter depends on the state of another property of the result type.
> An error will be raised in case a cycle in the dependency relationships is detected.
> Returns:
> the dependencies of the mapped property

**Comment by Nashev** [comment]
And when I have (maybe) something wrong, it produces an error "java: "docCode" is no property of the method return type." which is nonsenses for me, because I can not understand what is a "return type" in a context of a mapper, and I definitely have a field with lombok-generated getter and setter in a source class.

**Comment by filiphr** [comment]
Can you perhaps provide us with an example that will make this documentation clearer?

>And in the description mentioned some "Returns", but this is an argument of annotation and not a function!

Annotations contains element-value pairs where the element is a method. You can read more about that [here](https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.7) in the Java Specification.

>And when I have (maybe) something wrong, it produces an error "java: "docCode" is no property of the method return type." which is nonsenses for me, because I can not understand what is a "return type" in a context of a mapper, and I definitely have a field with lombok-generated getter and setter in a source class.

I would guess that the line of the error is the `@Mapping` annotation. And the "return type" then is not in a context of a mapper, but in a context of the method. I guess "return type" for a method is clear to you?

If you have problems with Lombok I would first try to use delombok and see if the problem persists or not. Sometimes when the mapper and your lombok classes are in the same compilation round there are problems.

**Comment by jovial-snyder** [comment]
Where is it even documented? It's not mentioned once in the official reference (https://mapstruct.org/documentation/stable/reference/html/).
I tried to access the JavaDoc (https://mapstruct.ci.cloudbees.com/job/mapstruct-javadoc/javadoc/) but the site seems to be offline at the moment.

**Comment by filiphr** [comment]
>Where is it even documented? It's not mentioned once in the official reference

There is really no point in being rude. If you go to the documentation section and then reference (https://mapstruct.org/documentation/reference-guide/) of our website you will see a link to the Javadoc. The direct link is (https://mapstruct.org/documentation/stable/api/). On top of that, every decent IDE can download the Javadoc and show it to you while you are developing.


> I tried to access the JavaDoc (https://mapstruct.ci.cloudbees.com/job/mapstruct-javadoc/javadoc/) but the site seems to be offline at the moment.

Where did you find the cloudbees link? That used to be for the SNAPSHOT, but we are not using cloudbees for a while.

**Comment by Nashev** [comment]
As I wrote in the first message here, I would like to see there
1) an example of usage, with what can be declared and what be generated
2) Clarify by note "source" or "target" around "properties", or something even clearer. I do not understand still how it works, and can't provide a more correct description.
