### ISSUE TITLE
Mapping not working if the source class has a parent class

### ISSUE THREAD

**Issue by vrangana** [mapstruct/mapstruct#2442]
Example: Let's say we Source class Kid and Target class Student, also class Kid extends class Person. Following are the definition of the relevant class, then the mapping doesn't work because of the generated Implementation code. The generated implementation code has a mapping function for both the Source superclass (Person) and the Source class (Kid). 

When the mapping function is called it is always directed to the mapping function with superclass implementation, due to this reason mapping is not happening. How do prevent Mapstruct to generate a mapper method without superclass-based implementation?

```
public class Person {
  private String name;
  private int age;
}

public class Kid extends Person {
  private String hobby;
}

public class Student {
  private String hobbies;
}

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface StudentMapper {
    @Mappings({
        @Mapping(target = "hobby", source = "hobbies")
    })
    Student getStudent(Kid kid);
}
```
Mapstruct generated code:
```
public class StudentMapperImpl implements StudentMapper {
    public StudentMapperImpl() {
    }

    public Student getStudent(Person person) {
        if (person == null) {
            return null;
        } else {
            Student student= new Student();
            return student;
        }
    }

    public Student getStudent(Kid kid) {
        if (kid == null) {
            return null;
        } else {
            Student student= new Student();
            String hobbies = this.kidHobbies(kid);
            if (code != null) {
                student.setHobbies(code);
            }
            return student;
        }
    }
}
```

**Comment by filiphr** [comment]
Are you sure that your `StudentMapper` leads to the `StudentMapperImpl`? I don't see `Student getStudent(Person person)` in the `StudentMapper`.

>When the mapping function is called it is always directed to the mapping function with superclass implementation, due to this reason mapping is not happening.

If we take the assumption that there is `Student getStudent(Person person)` in `StudentMapper` and you are invoking the mapping function with a type `Person` then this is expected. MapStruct doesn't do any special casting to check for child classes. If you are looking for that I would suggest looking watching #131.
