### ISSUE TITLE
Mappers are injected as private when they are used by other mappers

### ISSUE THREAD

**Issue by draccagni** [mapstruct/mapstruct#2443]
Mappers are injected as private when used by other mappers via the ```uses``` parameter of the ```@Mapper``` annotation. By using Quarkus framework, this choice rises the following warning message:

```
Found unrecommended usage of private members (use package-private instead) in application beans:
```

Would be possible to inject them as package-private instead (as suggested)?

**Comment by filiphr** [comment]
Which component model are you using?

I think that if you use `@Mapper(injectionStrategy = InjectionStrategy#CONSTRUCTOR)` there will be no warnings.
