### ISSUE TITLE
Can't create a Mapper TO a Builder Object

### ISSUE THREAD

**Issue by lucianogreiner** [mapstruct/mapstruct#2460]
Guys, I am trying to create a mapper from an Object to a Builder. It's not about using the builder, but mapping TO a builder:

  ```
@Mapping(source = "user", target = "author")
  MyModel toMyModel(MyModelInput input, User user);

  MyModel.MyModelBuilder toMyModel2(MyModelInput input, User user);
```

The first mapper works just fine (generated):
```
  MyModelBuilder myModel = MyModelBuilder.builder();

   if ( user != null ) {
       myModel.author( userToUserInfo( user ) );
   }

   return myModel.build();
```

Now the second fails to use the builder() method:

```
  MyModelBuilder myModel = new MyModelBuilder();
```

And then that fails to compile:
**error: MyModelBuilder() is not public in MyModelBuilder; cannot be accessed from outside package
        MyModelBuilder myModel = new myModel();**

Thoughts?

Using:
Mapstruct: 1.4.2.Final
Mapstruct Lombok Bindings 0.2
Lombok 1.18.20

**Comment by filiphr** [comment]
The problem with the second one is that MapStruct will treat it as a normal bean to bean mapping.
 Imagine that your `MyModel` has a method called `MyModel.newInstance()` that would create the instance. We do not have a mechanism for detecting that.

What I would suggest is to add an `@ObjectFactory` method for the `MyModelBuilder`.

e.g.

```
@Mapping(source = "user", target = "author")
MyModel toMyModel(MyModelInput input, User user);

MyModel.MyModelBuilder toMyModel2(MyModelInput input, User user);

@ObjectFactory
default MyModel.MyModelBuilder myModelBuilder() {
    return MyModelBuilder.builder();
}
```

**Comment by C0mbatwombat** [comment]
I know this issue has been closed forever, but I was wondering if it is possible to use a single method for multiple types? I have a lot of different proto types and would like to have a general 'BuilderObjectFactory'. Something along the lines of:
```
    public static <Builder extends Message.Builder> Builder createProtoBuilder(Builder builder) {
        @SuppressWarnings("unchecked")
        Builder result = (Builder) builder.getDefaultInstanceForType().newBuilderForType();
        return result;
    }
```
I don't see how I could get something like this to work, and want to verify if it is indeed impossible. Thanks for the great software!!

**Comment by filiphr** [comment]
@C0mbatwombat I would suggest that you create a discussion instead of commenting on an old issue.

MapStruct has a way to pass the target type using `@TargetType` to object factories. Have a look at the [Object factories](https://mapstruct.org/documentation/stable/reference/html/#object-factories) in our docs for more information
