### ISSUE TITLE
Found a small mistake in the comments on the source code.

### ISSUE THREAD

**Issue by hnamikaw** [mapstruct/mapstruct#2464]
https://github.com/mapstruct/mapstruct/blob/70ea65f7aa5518cac236c277bf040b058907f713/processor/src/main/java/org/mapstruct/ap/internal/processor/MapperRenderingProcessor.java#L19
The class name is now the interface name.
I think it should be `{@link MapperRenderingProcessor}`, not `{@link ModelElementProcessor}`.

```
/**
 * A {@link ModelElementProcessor} which creates a Java source file representing
 * the given {@link Mapper} object, unless the given mapper type is erroneous.
 *
 * @author Gunnar Morling
 */
public class MapperRenderingProcessor implements ModelElementProcessor<Mapper, Mapper> {
```
↓
```
/**
 * A {@link MapperRenderingProcessor} which creates a Java source file representing
 * the given {@link Mapper} object, unless the given mapper type is erroneous.
 *
 * @author Gunnar Morling
 */
public class MapperRenderingProcessor implements ModelElementProcessor<Mapper, Mapper> {
```

The other Processor had the same mistake.
https://github.com/mapstruct/mapstruct/tree/master/processor/src/main/java/org/mapstruct/ap/internal/processor

Do you want me to fix it and make a pull request?

**Comment by filiphr** [comment]
The current Javadoc is correct. Those classes are implementations of `ModelElementProcessor`. That's why the interface is mentioned in the Javadoc.
