### ISSUE TITLE
When i add qualifiedByName option, compile fail... 

### ISSUE THREAD

**Issue by Clapmin** [mapstruct/mapstruct#2470]
Version
spring-boot 2.3.11.RELEASE
mapstruct:1.4.1.Final
mapstruct-processor:1.4.1.Final

```java
@Mapper
public interface NaviRequestDtoMapper {
    NaviRequestDtoMapper MAPPER = Mappers.getMapper(NaviRequestDtoMapper.class);

    @Mapping(source = "requestDto.location.transId", target = "transactionId")
    @Mapping(source = "requestDto.location.localDateTime", target = "departureTime")
    NaviResult toNaviResultForStart(NaviRequestDto requestDto);

    @Named("stringToLocalDateTime")
    default LocalDateTime stringToLocalDateTime(NaviRequestDto requestDto) {
        return LocalDateTime.now();
    }
}
```

when i compile upper code, it generate ~impl code well.

But after i add option "qualifiedByName", it fails to compile the code with msg 
`The type of parameter "requestDto" has no property named "location.transId".NaviResult toNaviResultForStart(NaviRequestDto requestDto);`

```java
@Mapper
public interface NaviRequestDtoMapper {
    NaviRequestDtoMapper MAPPER = Mappers.getMapper(NaviRequestDtoMapper.class);

    @Mapping(source = "requestDto.location.transId", target = "transactionId")
    @Mapping(source = "requestDto.location.localDateTime", target = "departureTime", qualifiedByName = "stringToLocalDateTime")
    NaviResult toNaviResultForStart(NaviRequestDto requestDto);

    @Named("stringToLocalDateTime")
    default LocalDateTime stringToLocalDateTime(NaviRequestDto requestDto) {
        return LocalDateTime.now();
    }
}
```

This code's compile only succes when "qualifiedByName" option is deleted.
I don't know the cause. Any solution??? 😂

```java
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class NaviRequestDto {
    @NotNull
    private NaviRequestType requestType;
    @NotNull
    private LocationDto location;
}

@Getter
@Setter
@NoArgsConstructor
public class LocationDto {
    private String transId;
    private String dateTime;
    private LocalDateTime localDateTime;
    private int totalDistance;
    private int remainDistance;
    private String startName;
    private String goalName;
    private double lat;
    private double lng;

  @Builder
    public LocationDto(String transId, String dateTime, int totalDistance, int remainDistance, String startName, String goalName, double lat, double lng) {
        this.transId = transId;
        this.dateTime = dateTime;
        this.totalDistance = totalDistance;
        this.remainDistance = remainDistance;
        this.startName = startName;
        this.goalName = goalName;
        this.lat = lat;
        this.lng = lng;
    }
}
```

**Comment by filiphr** [comment]
What happens when you delombok? Is it working? Have you tried with 1.4.2.Final?

The error you are getting

>The type of parameter "requestDto" has no property named "location.transId".NaviResult toNaviResultForStart(NaviRequestDto requestDto);

is a bit weird.

However, what you are trying to do will not work. Your qualified method uses `NaviRequestDto` as a source. However, your `@Mapping` uses `requestDto.location.localDateTime` as a source.

The method is also weird since it doesn't use the parameter. Perhaps you need to use an `expression` here?

**Comment by filiphr** [comment]
I tried your example (without Lombok) and I get the following error for 1.4.1.Final and 1.4.2.Final:

>Qualifier error. No method found annotated with @Named#value: [ stringToLocalDateTime ]. See https://mapstruct.org/faq/#qualifier for more info.

Which is what I would expect.

**Comment by MadeInChina** [comment]
It's got build error when using 1.4.2 but working under 1.3.x version
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project timesheet: Compilation failure: Compilation failure: 
[ERROR] /DtoMapper.java:[30,5] Qualifier error. No method found annotated with @Named#value: [ longToCountry ]. See https://mapstruct.org/faq/#qualifier for more info.
[ERROR] DtoMapper.java:[30,5] Can't map property "Long country" to "Country country". Consider to declare/implement a mapping method: "Country map(Long value)".
[ERROR] -> [Help 1]
`
`
@Mapper(componentModel = "spring",
    uses = {
        CountryRepository.class,
        ClientRepository.class,
        EmployeeRepository.class,
        CategoryRepository.class,
        ProjectRepository.class,
        EmployeeRepository.class,
        ProjectMemberRepository.class
    })
public interface DtoMapper {


  @Mapping(source = "country", target = "country", qualifiedByName = "longToCountry")
  Client clientInputDtoToClient(ClientInputDto clientInputDto);


  @Named("longToCountry")
  default Country map(Long id, @Context CountryRepository countryRepository) {
    return countryRepository
        .findById(id)
        .orElseThrow(
            () -> new NotFoundException("Country with id '" + id + "' is not found"));
  }

}`

**Comment by MadeInChina** [comment]
generated source code in 1.3.1 below, as you see it's correct @filiphr 

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-06-11T08:30:36+0800",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 11.0.9 (Oracle Corporation)"
)
@Component
public class DtoMapperImpl implements DtoMapper {

    @Autowired
    private CountryRepository countryRepository;

    @Override
    public Client clientInputDtoToClient(ClientInputDto clientInputDto) {
        if ( clientInputDto == null ) {
            return null;
        }

        ClientBuilder client = Client.builder();

        client.country( countryRepository.getOne( clientInputDto.getCountry() ) );
        client.id( clientInputDto.getId() );
        client.name( clientInputDto.getName() );
        client.address( clientInputDto.getAddress() );
        client.city( clientInputDto.getCity() );
        client.zipCode( clientInputDto.getZipCode() );

        return client.build();
    }
}
```

**Comment by MadeInChina** [comment]
And followed solved the problem
[chapter-5-data-type-conversions.asciidoc](https://github.com/mapstruct/mapstruct/blob/master/documentation/src/main/asciidoc/chapter-5-data-type-conversions.asciidoc)
```
public abstract CarDto toCar(Car car, @Context Locale translationLocale);

protected OwnerManualDto translateOwnerManual(OwnerManual ownerManual, @Context Locale locale) {
    // manually implemented logic to translate the OwnerManual with the given Locale
}
```

**Comment by filiphr** [comment]
@MadeInChina the generated code is not correct.

It uses

```
client.country( countryRepository.getOne( clientInputDto.getCountry() ) );
```

It does not use the qualified method like you have defined in your `@Mapping`. If you remove the `@Mapping` everything will work correctly.


---------------
@Clapmin I am going to close this since in my opinion it is a configuration error. Please reopen or comment if you think that there is something that MapStruct can do.
