### ISSUE TITLE
Compound DTO support

### ISSUE THREAD

**Issue by cdalexndr** [mapstruct/mapstruct#2474]
- [ ] Is this an issue (and hence not a question)? 

I have a jpa entity `JPAProduct` that has some lazy fetched relationships.
I use a DTO `BaseProduct` that contains all eager fetched properties.
For each lazy fetched properties I use an interface, ex:
```
interface ProductWithImages {
    List<Image> getImages();
    void setImages(List<Image> images);
}

interface ProductWithProperties {
    List<Property> getProperties
    void setPropertiesList<Property> properties);
}
```
This allows me to create custom DTOs like:
```
class ProductWithImagesAndProperties extends BaseProduct implements ProductWithImages, ProductWithProperties { ...
```

How can I map a dynamic DTO implementing some interfaces?
`public abstract <T extends BaseProduct> T dynamicMap(JPAProduct product, Supplier<T> dtoCtr);`

I'm looking for something like:

1. define mapping for each component (BaseProduct, ProductWithImages , ProductWithProperties)
2. apply all these mappings on the same result object (aggregation)

Mapper methods must return concrete classes, so I cannot define separate mappers for my DTO components that are interfaces.

**Comment by cdalexndr** [comment]
I think a possible solution would be to make `@InheritConfiguration` repeatable so that the component mappers can be applied, but currently the mapper function return type must be a concrete class, so this is not possible.

**Comment by cdalexndr** [comment]
Possible solution reflexion:

```
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget BaseProduct product );
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithImages product );
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithProperties product );

<T extends BaseProduct> T mapProduct( JPAProduct product, Supplier<T> dtoSupplier ) {
        T dto = dtoSupplier.get();
        updateProduct( product, dto ); //base
        for (Class<?> interf : dto.getClass().getInterfaces()) {
            try {
                Method method = this.getClass().getDeclaredMethod( "updateProduct", JPAProduct.class, interf );
                method.invoke( this, product, dto );
            } catch (NoSuchMethodException ignore) {
            } catch (InvocationTargetException | IllegalAccessException e) {
                throw new IllegalStateException( String.format( "Cannot map %s", interf ), e );
            }
        }
        return dto;
    }
```

Is there a better solution?

**Comment by filiphr** [comment]
I think that you can define combination of mappings using [Mapping Composition](https://mapstruct.org/documentation/stable/reference/html/#mapping-composition).

Apart from using a reflection like that you can also use instance of checks.

e.g.

```
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget BaseProduct product );
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithImages product );
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithProperties product );

    <T extends BaseProduct> T mapProduct( JPAProduct product, Supplier<T> dtoSupplier ) {
        T dto = dtoSupplier.get();
        updateProduct( product, dto ); //base
        if (dto instanceof ProductWithImages) {
            updateProduct( product, (ProductWithImages) dto);
        }

        if (dto instanceof ProductWithProperties) {
            updateProduct( product, (ProductWithProperties) dto);
        }
        return dto;
    }
```

If you have many things like this what you could do is to create your own annotation processor which will generate a MapStruct `@Mapper` with the instanceof checks already present. Annotation Processors allow you to generate classes / interfaces that can be consumed by another annotation processors. There are multiple rounds in the annotation processor and it will continue running the rounds until all processors have nothing to generate.

e.g.

You will write

```
@MyCustomMapper
public interface ProductMapper {

    <T extends BaseProduct> T mapProduct( JPAProduct product, Supplier<T> dtoSupplier );
}
```

Then based on this you can generate 

```
@Mapper
public abstract class ProductMapStructMapper implements ProductMapper {

    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget BaseProduct product );
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithImages product );
    abstract void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithProperties product );

    @Override
    public <T extends BaseProduct> T mapProduct( JPAProduct product, Supplier<T> dtoSupplier ) {
        T dto = dtoSupplier.get();
        updateProduct( product, dto ); //base
        if (dto instanceof ProductWithImages) {
            updateProduct( product, (ProductWithImages) dto);
        }

        if (dto instanceof ProductWithProperties) {
            updateProduct( product, (ProductWithProperties) dto);
        }
        return dto;
    }

}
```

**Comment by filiphr** [comment]
That was one potential solution building on top of your initial example with update mappings. Keep in mind that update mappings generate different code compared to normal direct mappings.

Another approach would be to have multiple `mapProduct` methods that will map into the explicit types you have:

e.g.

```
@Mapper
public abstract ProductMapper {

    protected abstract ProductWithImagesAndProperties toProductWithImages(JPAProduct product);

    protected abstract ProductOnlyWithImages toProductOnlyWithImages(JPAProduct product);

    public abstract <T extends BaseProduct> T dynamicMap(JPAProduct product, Class<T> dtoClass) {
        if (dtoClass.equals(ProductWithImagesAndProperties.class) {
            return toProductWithImages(product);
        } else if (dtoClass.equals(ProductOnlyWithImage.class) {
            return toProductOnlyWithImages(product);
        } else {
            throw UnsupportedOperationException("Not supported to map to " + dtoClass);
        }
    }

}
```

This of course is more limited since it can only map to implementation classes known during compile time. The previous approach with update mappings allows you to create a combination of things in other dependencies as well.

**Comment by filiphr** [comment]
I am going to close this now since I don't think that there is something that MapStruct can do here. I think that any solution would be quite specific to a project you have.
