### ISSUE TITLE
variable is already defined in method

### ISSUE THREAD

**Issue by cdalexndr** [mapstruct/mapstruct#2478]
- [x] Is this an issue (and hence not a question)? 

Mapping:
`    abstract JPAProduct productFromDto( Product dto, @Context Language language, @Context Shop shop );`

generates:
```
  JPAProduct productFromDto(Product dto, Language language, Shop shop) {
        ...
        jPAProduct.setShop( shopToJPAShop( dto.getShop(), language, shop ) );
```

where the generated `shopToJPAShop` method has duplicate variable name:
`protected JPAShop shopToJPAShop(Shop shop, Language language, Shop shop) {`

Compile error:
` error: variable shop is already defined in method shopToJPAShop(Shop,Language,Shop)`

MapStruct version: 1.4.2.Final

**Comment by cdalexndr** [comment]
Workaround, add explicit mapping method:
`abstract JPAShop fromShop( Shop shop );`
then this method will be used instead of the invalid generated one.

**Comment by filiphr** [comment]
Good catch @cdalexndr. There is a PR for fixing the problem.

Apart from adding an explicit method a workaround will be to change the name of the `@Context` parameter.

e.g

```
abstract JPAProduct productFromDto( Product dto, @Context Language language, @Context Shop contextShop );
```
