### ISSUE TITLE
Update mapping: collection setter not used

### ISSUE THREAD

**Issue by cdalexndr** [mapstruct/mapstruct#2479]
- [x] Is this an issue (and hence not a question)? 

DTO:
```
public interface ProductWithOffers {
    void setOffers( Set<Offer> offers );
    Set<Offer> getOffers();
}
```
Mapping:
`void updateProduct( JPAProduct jpaProduct, @MappingTarget ProductWithOffers product );`

Generated code:
```
        @Override
        void updateProduct(JPAProduct jpaProduct, ProductWithOffers product) {
        ...
        if ( product.getOffers() != null ) {
            Collection<Offer> collection = jpaProduct.getOffers();
            if ( collection != null ) {
                product.getOffers().clear();
                product.getOffers().addAll( collection );
            }
            else {
                product.setOffers( null );
            }
        }
```
The `product.getOffers()` method could return an immutable collection or use a defensive copy so that the returned collection changes doesn't update actual DTO collection.
The setter should be used.

**Comment by filiphr** [comment]
Have you checked the [CollectionMappingStrategy#TARGET_IMMUTABLE](https://mapstruct.org/documentation/stable/api/org/mapstruct/CollectionMappingStrategy.html#TARGET_IMMUTABLE)?

If you do that then MapStruct will use the setter instead. 

You can do this on the `@Mapper` or `@MappingConfig` annotation. Depending on the scope you want for this to be applied.

**Comment by cdalexndr** [comment]
What is the reason this is not the default value?

To be on the safe side of things, I think the setter should be used by default if it is found.
Updating the collection by default using the getter is not safe (defensive copy, immutable collections, etc...).

**Comment by filiphr** [comment]
>What is the reason this is not the default value?

There are numerous reasons why it is not the default:

1. This option was added in a later release. If we changed it, it might have caused backwards incompatibility
2. JPA, sometimes in JPA collections are tracked and in order to sever the connection between a Parent and a Child you need to clear the collection.
