### ISSUE TITLE
[suggestion] Add optional reporting if ignored source properties do not exist

### ISSUE THREAD

**Issue by incaseoftrouble** [mapstruct/mapstruct#2481]
For `unmappedSourcePolicy = ReportingPolicy.WARN` or above, one can use `@BeanMapping(ignoreUnmappedSourceProperties = {...})` to declare source properties which are omitted intentionally. However, an equally simple dual option is missing. I'd suggest having a `ignoredSourcePolicy` configuration which warns / fails if an unknown source property is missing. This is useful for keeping this list "in sync" with reality, especially helpful after refractoring.

I am aware that one could achieve through `ignoreByDefault = true`, but then you'd have to write all mappings explicitly.

Sure, compared to a required missing target property, an ignored missing source property is not really dramatic, but it helps with debugging and keeping code clean. Its definitely a low-priority suggestion.

**Comment by filiphr** [comment]
I am not sure that I understand you completely @incaseoftrouble.

You want to have a warning / error if a source property used in `BeanMapping#ignoreUnmappedSourceProperties` does not exist? i.e. you made a typo?

If that is the case then I would say that we don't need any other option, we should do this out of the box automatically. I think that this is a relatively easy enhancement and anyone from the community can jump in to help with this. Perhaps you would be interested in providing this? We would need to change [this](https://github.com/mapstruct/mapstruct/blob/08016d9ef24a4fb59347953f1f0cba9bcecca810/processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java#L253) line and add a check that the property is indeed in the `unprocessedSourceProperties` and if it isn't to have an error or a warning.

**Comment by incaseoftrouble** [comment]
Done :-) I hope I got it right, since its a new feature I am not entirely sure how to test it. I basically copied what `unmappedSourcesPolicy` is doing, but I might have missed something.

**Comment by filiphr** [comment]
Done in PR #2485, thanks @incaseoftrouble
