### ISSUE TITLE
Some fields lost due to the @Mapping.

### ISSUE THREAD

**Issue by Manjiz** [mapstruct/mapstruct#2488]
- [x] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

```java
class Target {
  Long id;
  FieldObj fieldObj;
}
class FieldObj {
  Long parentId;
  FieldConfig config;
}

class Source {
  Long id;
  FieldObj2 fieldObj;
}
class FieldObj2 {
  FieldConfig config;
}
```

And my mappers:

```java
Target convert(Source dto);

// impl

// Target fieldObj setConfig
```

```java
@Mappings({
  @Mapping(target = "fieldObj.parentId", source = "id")
})
Target convert(Source dto);

// impl

// Target fieldObj setParentId
// But there is no setConfig
```

```java
@Mappings({
  @Mapping(target = "fieldObj.parentId", source = "id"),
  @Mapping(target = "fieldObj.config", source = "fieldObj.config")
})
Target convert(Source dto);

// impl

// Both setParentId and setConfig
```

Must I specified @Mapping for all fields in object field?

**Comment by Manjiz** [comment]
Caused by `@Mapping(target = "fieldObj.parentId", source = "id")`.

**Comment by filiphr** [comment]
Nested target properties are tricky, once you start defining some, and especially if there is an asymmetry MapStruct will only applied the defined mappings.

What you should do is to explicitly map the `fieldObj` to the source.

e.g.

```
@Mapping(target = "fieldObj.parentId", source = "id")
@Mapping(target = "fieldObj", source = "fieldObj")
Target convert(Source dto);
```
