### ISSUE TITLE
Map DTOs implementing Iterable

### ISSUE THREAD

**Issue by cdalexndr** [mapstruct/mapstruct#2493]
- [x] Is this an issue (and hence not a question)? 

I'm mapping a jpa entity to a DTO that implements `Iterable` for convenience and library compatibility (iterate in thymeleaf view).
```
@Mapping(target = "parts", source = "myEntity.pathFromRoot")
Breadcrumbs mapBreadcrumbs( JPAEntity myEntity )
```

where `Breadcrumbs implements Iterable<BreadcrumbPart>`.
This throws error:
` Can't generate mapping method from non-iterable type to iterable type.`
Without implementing iterable, the generated mapping is correct.

From [documentation](https://mapstruct.org/documentation/stable/reference/html/#mapping-collections):
` It is not allowed to declare mapping methods with an iterable source  and a non-iterable target or the other way around. An error will be  raised when detecting this situation.`

A method to ignore **iterable** code generation should be provided.

**Comment by filiphr** [comment]
I think that your use case is covered by #607, which will be released as part of 1.5.

Would be great if you can try out the SNAPSHOT version. 

Let us know if it doesn't work so we can reopen this.

**Comment by cdalexndr** [comment]
> Would be great if you can try out the SNAPSHOT version.

Is there a public snapshot build somewhere, or do I have to build it?

**Comment by filiphr** [comment]
You don't have to build it, we push every snapshot to [Sonatype Snapshots Repository](https://s01.oss.sonatype.org/content/repositories/snapshots/).

You can also use [JitPack](https://jitpack.io/#mapstruct/mapstruct/)
