### ISSUE TITLE
LocalDateTime to XmlGregorianCalendar losses time zone information

### ISSUE THREAD

**Issue by kavalagios** [mapstruct/mapstruct#2498]
Similar to:

https://github.com/mapstruct/mapstruct/issues/1523

the same happens for `XMLGregorianCalendar`. After conversion the timezone information is not set.

**Comment by kavalagios** [comment]
Workaround: Create the following interface and extend it to your mappers using LocalDateTime to XmlGregorianCalendar conversion.

`@Mapper
public interface LocalDateMapper {

    default XMLGregorianCalendar localDateTimeToXmlGregorianCalendar(LocalDateTime localDateTime) {
        XMLGregorianCalendar xmlGregorianCalendar = null;
        try {
            xmlGregorianCalendar = DatatypeFactory.newInstance().newXMLGregorianCalendar(GregorianCalendar.from(localDateTime.atZone(ZoneId.systemDefault())));
        } catch (DatatypeConfigurationException e) {
            e.printStackTrace();
        }

        return xmlGregorianCalendar;
    }
}`

**Comment by filiphr** [comment]
The difference between this and #1523 is the fact that #1523 was for `ZonedDateTime` (which has a zone). However, `LocalDateTime` does not have information for the zone. The fact that `XMLGregorianCalendar` supports undefined time zone information means that everything is mapped correctly.

Your workaround is a solution that should be used if you want to convert from `LocalDateTime` to `XMLGregorianCalendar`  and use a certain time zone
