### ISSUE TITLE
DeepClone generates cloning method for Enums

### ISSUE THREAD

**Issue by MalteJoe** [mapstruct/mapstruct#2505]
- [x] Is this an issue (and hence not a question)? 

I am using the `mappingControl = DeepClone.class` in order to clone objects, change some fields and to persist them seperately.

While it works perfectly fine, I've noticed the generated code for some enum fields looks like this:

```java
protected Status statusToStatus(Status status) {
    if ( status == null ) {
        return null;
    }

    Status status1;

    switch ( status ) {
        case TODO: status1 = Status.TODO;
        break;
        case IN_PROGRESS: status1 = Status.IN_PROGRESS;
        break;
        case DONE: status1 = Status.DONE;
        break;
        default: throw new IllegalArgumentException( "Unexpected enum constant: " + status );
    }

    return status1;
}
```

It is not wrong and I understand that mapstruct is forced to generate a method. However, converting an enum of the same type  will never fail and using the Enum directly shouldn't be an issue.

I know I can override the mappingControl for specific properties, but the enum in my example get's used in many places down the object tree, which I don't want to specify fully.

I'd like to see one of these two solutions:
* Even with `mappingControl = DeepClone.class`, enums of the same type are mapped directly, so the user does not need to specify a direct mapping for each enum field. This is also somewhat in line with the documentation for `org.mapstruct.control.MappingControl.Use#DIRECT` which states that direct mapping is used for all types from the `java` package, which should be extended to enums as well.
* Specify `mappingControl` for a type only. Something like this in the `@Mapper`-annotated Interface:
    ```java
    @Mapping(mappingControl = NoComplexMapping.class)
    Status statusToStatus(Status status);
    ```

For now, I use a mapping method which simply returns it's parameter for all Enum types, but it still feels like an unnecessary method call:

```java
default <E extends Enum<E>> E keepEnum(E enum) {
    return enum;
}
```

**Comment by sjaakd** [comment]
@MalteJoe .. You are right.. It does not make any sense to 'deep' clone an enum type. I guess we did not consider / test this scenario yet.

**Comment by sjaakd** [comment]
Issue is resolved and close. Please give it a shot.
