### ISSUE TITLE
Deprecation warnings if mapper class or mapping method is deprecated

### ISSUE THREAD

**Issue by mjustin** [mapstruct/mapstruct#2521]
I have a mapping in my application that is only used to support a deprecated program element which is intended to be removed in the next major release of the application, but which needs to remain in the minor releases up until that point.  As I do not want the mapper to be used outside the context of the deprecated functionality, and so that I remember to remove it when removing the deprecated code, I have the mapping method marked as `@Deprecated`.

However, the generated mapping code produces a deprecation warning when compiled with deprecation warnings enabled.  The reason for this is that the concrete class that overrides the method is not marked as `@Deprecated` (or `@SuppressWarnings("deprecation")`), so it is an instance of a non-deprecated element overriding a deprecated one.

It would be nice if no such warning were emitted.  It seems the most appropriate thing to do would be to apply the `@Deprecation` annotation to the generated code, since if the mapping interface is `@Deprecated`, this indicates that the developer would want the overriding element to also be deprecated.

This behavior occurs whether just the method or the whole class is deprecated.

Depending on how it is implemented, #1574 might allow for this, since it's a matter of applying the correct annotations.

### Common code

```java
public class Source {
    private String value;
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }
}
```

```java
public class Target {
    private String value;
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }
}
```

**build.gradle**

```groovy
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'
    implementation 'org.mapstruct:mapstruct:1.4.2.Final'
}

compileJava {
    options.deprecation = true
}
```

### Example 1: Deprecated method

```java
@Mapper
public interface DeprecatedMappingMethod {
    @Deprecated
    Target map(Source source);
}
```

**Compiler output:**
```
/path/to/com/example/DeprecatedMappingMethodImpl.java:13: warning: [deprecation] map(Source) in DeprecatedMappingMethod has been deprecated
    public Target map(Source source) {
```

**Generated:**

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-07-18T21:03:26-0500",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.1.1.jar, environment: Java 16.0.1 (AdoptOpenJDK)"
)
public class DeprecatedMappingMethodImpl implements DeprecatedMappingMethod {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        target.setValue( source.getValue() );

        return target;
    }
}
```

### Example 2: Deprecated class

```java
@Deprecated
@Mapper
public interface DeprecatedMapper {
    Target map(Source source);
}
```

**Compiler output:**
```
/path/to/com/example/DeprecatedMapperImpl.java:10: warning: [deprecation] DeprecatedMapper in com.example.github has been deprecated
public class DeprecatedMapperImpl implements DeprecatedMapper {
```

**Generated:**

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-07-18T21:03:26-0500",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.1.1.jar, environment: Java 16.0.1 (AdoptOpenJDK)"
)
public class DeprecatedMapperImpl implements DeprecatedMapper {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        target.setValue( source.getValue() );

        return target;
    }
}
```

**Comment by jearton** [comment]
+1
