### ISSUE TITLE
How to solve ClassNotFoundException: Cannot find implementation for xxx?

### ISSUE THREAD

**Issue by stevenlii** [mapstruct/mapstruct#2527]
Mapstruct、Lombok、Maven 和 Eclipse is my environment. 
But after I read https://github.com/mapstruct/mapstruct/issues/1159
https://github.com/projectlombok/lombok/issues/1359
https://github.com/mapstruct/mapstruct/issues/929
https://github.com/mapstruct/mapstruct/issues/742
...
I still cannot find a way to solve the problem...

**Comment by Zegveld** [comment]
do you have the m2e-apt plugin installed, and configured?
`Window --> Preferences --> Maven --> Annotation Processing` enable here the `Automatically configure JDT APT` setting.
This radio button was what I needed to do to get it working. If I remember correctly.

**Comment by stevenlii** [comment]
> do you have the m2e-apt plugin installed, and configured?
> `Window --> Preferences --> Maven --> Annotation Processing` enable here the `Automatically configure JDT APT` setting.
> This radio button was what I needed to do to get it working. If I remember correctly.
> 
> Edit:
> My symptom was: Eclipse didn't do annotation processing for mapstruct, but maven commands did.
> If maven builds also do not do the annotation processing then you might have missed something in the maven configuration.
thanks for reply~

I installed m2e-apt and configured the plugin like this:
![image](https://user-images.githubusercontent.com/8954758/127088923-306f2440-b757-4c29-8e5b-48a34ccdebf6.png)

But still get a error: 
![image](https://user-images.githubusercontent.com/8954758/127088849-6fe8d637-cb6c-49d5-8881-fa67f28cac37.png)
Plus: 
Eclipse version:2021-06. ( lasted version)
lombok version:1.18.20 ( lasted version)
m2e-apt:1.5.3 ( lasted version)

**Comment by stevenlii** [comment]
Thank you again. It worked.
I remove the plugin configuration in pom.xml which is misunderstood by [here](https://stackoverflow.com/questions/49910607/java-lang-classnotfoundexception-cannot-find-implementation-for)
I share this experience at my blog, hope to help  help others someday in the future. 
https://www.cnblogs.com/stevenlii/p/14955040.html
