### ISSUE TITLE
Issue with unmappedSourcePolicy and implicit source mapping

### ISSUE THREAD

**Issue by mjustin** [mapstruct/mapstruct#2537]
I have a mapper in which the source properties consists of just a subset of the target properties.  I'm mapping those properties, but leaving everything else unchanged.  I'm using `@BeanMapping(ignoreByDefault = true)` to ensure and make explicit that I'm only mapping a small subset of properties over.  I discovered that I can specify just the `target` property in a `@Mapping` annotation to opt a field in to this mapping, when the source property name is the same as the target's:

```java
@Mapper
interface MyMapper {
    @BeanMapping(ignoreByDefault = true)
    @Mapping(target = "renamedTarget", source = "renamedSource")
    @Mapping(target = "property") // source = "property" isn't needed
    void copyProperties(Source source, @MappingTarget Target target);
}
```

I would like to specify the unmapped source policy to fail if I don't map all source properties.  This way I'll be notified at build time if any properties get added to the source that I forget to map.  Using `@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)` works, but only if I explicitly specify the source property (`@Mapping(target = "property", source = "property")`).  If I don't, I get a build error:

```
Unmapped source property: "property".
```

Given that the source is actually mapped by MapStruct in this scenario, I would expect this to compile without error.

## Minimal example:

```java
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR) // Works without the unmappedSourcePolicy
public interface UnmappedSourcePolicyWithImplicitSourceMapper {
    @Mapping(target = "property") // Works if I add source = "property"
    Target map(Source source);
}

public static class Source {
    private String property;

    public String getProperty() { return property; }
    public void setProperty(String property) { this.property = property; }
}

public static class Target {
    private String property;

    public String getProperty() { return property; }
    public void setProperty(String property) { this.property = property; }
}
```

**Comment by Zegveld** [comment]
To complicate things: there are more options then just source, for example besides source you can also use a default value, or an expression. So the solution to fix this unnecessary explicit mentioning of the source will need to take these into account.

I see 2 ways to solve this issue:
1. If there are no source settings on the Mapping annotation then set source to be equal to target.
2. Always explicitly require a source value. (where a source value includes the other types besides source like default)

Both have advantages and disadvantages, but the 2nd option will result in backwards incompatibility.
So I'll be making a fix using the 1st option.

**Comment by Zegveld** [comment]
Turned out there was a 3rd option: all that was needed was to remove the implicit source from the unprocessedSourceProperties.

Is not the first time that this happens to me, I figure out where to put a fix for it. Then find out it isn't the correct location for the fix, because tests are failing. Using those failing tests I could find out what the correct location is for this fix. :smile_cat:

**Comment by mjustin** [comment]
Looks like you were able to just copy/paste my example, so woot.

**Comment by filiphr** [comment]
Thanks a lot for the detailed example @mjustin and thanks a lot @Zegveld for providing the PR.

>Looks like you were able to just copy/paste my example for the actual test within the project, so woot.

Such examples are the best @mjustin, for me usually it is 80% of the time to find out the minimal reproducable test case for the fix.
