### ISSUE TITLE
@AfterMapping Called twice

### ISSUE THREAD

**Issue by esfomeado** [mapstruct/mapstruct#2540]
I have the following mapper code:

```
@Mapper( componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE )
public abstract class PairToReadModelMapper
{
    public abstract ReadModel map( @Context User user, Pair pair, long key );

    public abstract ReadModel map( @Context User user, Pair pair);

    @AfterMapping
    protected void afterMap( @Context User user, @MappingTarget ReadModel readModel)
    {
        afterMap( user, readModel, null );
    }

    @AfterMapping
    protected void afterMap( @Context User user, @MappingTarget ReadModel readModel, Long key )
    {
        // ...
    }
}
```

The idea is to remove the need to call the mapper with a key and if the key isn't passed it should call the afterMap() function with the key as null.

It works fine for the second mapper but the first one will call two times the afterMap().
One without the key and another with the key.

Any idea of how to avoid this?

Thanks

**Comment by Zegveld** [comment]
You can use qualifiers to influence which AfterMapping method is called for which map method.

Documentation for AfterMapping, the qualifiers are mentioned after example 92.: https://mapstruct.org/documentation/dev/reference/html/#customizing-mappings-with-before-and-after
Qualifier explanation: https://mapstruct.org/documentation/dev/reference/html/#selection-based-on-qualifiers

**Comment by filiphr** [comment]
Thanks for pointing this out @Zegveld
