### ISSUE TITLE
Boolean property getter preference

### ISSUE THREAD

**Issue by HawkSK** [mapstruct/mapstruct#2551]
Mapstruct seems to prefer `getX` over `isX` getter with boolean properties when both methods are present. As shown in [the image of specification](https://github.com/mapstruct/mapstruct/issues/1943#issuecomment-552369312), the isX should be preferred.

With my code:

```java
class Entity {
    private Long locked;

    public Long getLocked() { return locked; }

    public boolean isLocked() { return locked != null && locked != 0; }

    public void setLocked(Long locked) { this.locked= locked; }
}


class Dto {
    private boolean locked;

    public void setLocked(boolean locked) { this.locked = locked; }

    public boolean getLocked() { return locked; }
}

interface Mapper {
    @Mapping(target = "locked", source = "locked")
    Dto map(Entity entity);
}
```

I get the following error:
```
java: Can't map property "Long locked" to "boolean locked". Consider to declare/implement a mapping method: "boolean map(Long value)".
```

**Comment by filiphr** [comment]
This has been like this for a while. It was done in https://github.com/mapstruct/mapstruct/commit/4ff0676c61a739f5ab8878872965c65ae8f24029, I am not sure what the implication will be if change this now, it would be breaking change, since code that worked might stop working. What do you think @sjaakd?

For the time being you could resolve this by providing a custom method between `Long` and `boolean`.

**Comment by sjaakd** [comment]
> This has been like this for a while. It was done in [4ff0676](https://github.com/mapstruct/mapstruct/commit/4ff0676c61a739f5ab8878872965c65ae8f24029), I am not sure what the implication will be if change this now, it would be breaking change, since code that worked might stop working. What do you think @sjaakd?

Well, let's established there that `Locked` is no bean property. It is a method to expose the `Long locked`. The property accessors are the provided getter `getLocked ` and setter `setLocked `. 

Agreed with @filiphr .. this is far too risky to change and next to that: I don't see a reason. You can fix this in other words. Provide a mapping method that maps your `Long` to a boolean and it will work as well.  Something similar like this:

```java
class Entity {
    private Long locked;

    public Long getLocked() { return locked; }

   //  public boolean isLocked() { return locked != null && locked != 0; } if you're in control on the Entity

    public void setLocked(Long locked) { this.locked= locked; }
}


class Dto {
    private boolean locked;

    public void setLocked(boolean locked) { this.locked = locked; }

    public boolean getLocked() { return locked; }
}

interface Mapper {
    @Mapping(target = "locked", source = "locked")
    Dto map(Entity entity);

    default boolean mapLock(Long locked){
        return locked != null && locked != 0;
    }


}
```

Will continue to close this issue.
