### ISSUE TITLE
New mapping feature not support property paths

### ISSUE THREAD

**Issue by jonsalvas** [mapstruct/mapstruct#2553]
First of all: thanks for the great job you are doing with this library, it helps us to save a lot of boilerplate code. I was really happy that you finally released the feature to map maps to beans: https://mapstruct.org/documentation/dev/reference/html/#mapping-map-to-bean 
As we use a lot of maps in our project it will be very helpful.

However, I was not really able to make it work in our project so I tried to build a minimal example based on one of your test cases (MapToBeanFromMultipleSource) in the PR. There I noticed that, if the map is a field of a bean the property path in the source parameter is not resolved correctly. Minimized example code:

```
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.Map;

@Mapper
public interface MapToBeanFromMultipleSources {
    @Mapping(target = "string", source = "bean.strings.string")
    Target toTarget(Source bean);

    class Source {
        private Map<String, String> strings;

        public Map<String, String> getStrings() {
            return strings;
        }

        public void setStrings(Map<String, String> strings) {
            this.strings = strings;
        }

    }

    class Target {

        private String string;


        public String getString() {
            return string;
        }

        public void setString(String string) {
            this.string = string;
        }

    }
}
```

I am receiving: "The type of parameter "bean" has no property named "strings.string". Am I missing something, or is this currently not supported?

**Comment by filiphr** [comment]
Thanks for reporting this @jonsalvas.

This is slightly related to #2549. Seems like we no longer allow using the single source parameter name in `Mapping#source` when the parameter is `Map<String, ???>`.

Which means that something like 

```
@Mapping(target = "string", source = "strings.string")
```

should work. However, it doesn't. We will look into this so it works transparently for defined nested mappings. If we add a defined mapping to [`MapToBeanFromMapAndNestedMap`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanFromMapAndNestedMap.java) then it won't work.

We will fix this
