### ISSUE TITLE
There is no way to configure default unmappedSourcePolicy

### ISSUE THREAD

**Issue by remal** [mapstruct/mapstruct#2555]
You can configure default `unmappedTargetPolicy` via annotation processor arguments: `-Amapstruct.unmappedTargetPolicy=ERROR`.

However, as I can see, it is not possible to configure `unmappedSourcePolicy` in the same way (by adding `-Amapstruct.unmappedSourcePolicy=ERROR` argument).

Could you please add this functionality?

**Comment by filiphr** [comment]
You are right, @remal. That `mapstruct.unmappedSourcePolicy` argument is missing.

Are you or someone else from the community interested in providing the functionality for this?
