### ISSUE TITLE
BeanMapping / ignoreByDefault interaction with unmappedSourcePolicy

### ISSUE THREAD

**Issue by incaseoftrouble** [mapstruct/mapstruct#2560]
A rather simple issue:

If I specify `@BeanMapping(ignoreByDefault = true)` and `unmappedSourcePolicy != ReportingPolicy.IGNORE`, non-mapped source parameters still cause an error. Arguably, this might be the correct behaviour, but I think it is not:

`ignoreByDefault` basically means "I will do everything manually". In my understanding, reporting policies are there to warn you about things the automatic matching is doing. In particular, if you have an `unmappedTargetPolicy` + an unmapped target property with `ignoreByDefault = true`, there are no errors (as, essentially, this throws an `ignore = true` on every target property). In the current state, this is asymmetric for the unmapped sources case, as `@BeanMapping.ignoreUnmappedSourceProperties` practically is the equivalent of `@Mapping(ignore = true)`.

Proposal: `ignoreByDefault` also disables complaints about unmapped source properties :-)

This should be quite easy to implement, if you agree I can submit a PR.

**Comment by filiphr** [comment]
You are right @incaseoftrouble, using `@BeanMapping(ignoreByDefault = true)` should be treated as `ReportingPolicy.IGNORE`.

>This should be quite easy to implement, if you agree I can submit a PR.

Yes please submit a PR. It would be very appreciated.

**Comment by filiphr** [comment]
Thanks for the quick PR @incaseoftrouble
