### ISSUE TITLE
Add support for Jakarta Dependency Injection API

### ISSUE THREAD

**Issue by jmongard** [mapstruct/mapstruct#2567]
- [x] Is this an issue (and hence not a question)? 

Hi,

I think it would be great if Mapstruct would support the [Jakarta dependency inject annotations](https://jakarta.ee/specifications/dependency-injection/2.0/):

* jakarta.inject.Inject
* jakarta.inject.Singleton
* jakarta.inject.Named

This would would make generated mappers compatible with Jakarta EE 9, Micronaut 3, etc.  

Could this be as simple as copying the Jsr330 component model with replaced annotation names?

**Comment by filiphr** [comment]
Good point @jmongard. What happens right now when you choose jsr300 and you only have the jakarta ones?

>Could this be as simple as copying the Jsr330 component model with replaced annotation names?

It is even simpler I would say. Instead of copying everything we should adapt the `Jsr330ComponentProcessor` to use the ones from the jakarta namespace if the javax ones are missing. This would mean if the user has only jakarta everything will work as expected.

Would you be interested in adding this functionality @jmongard?

**Comment by jmongard** [comment]
@filiphr 
> What happens right now when you choose jsr300 and you only have the jakarta ones?

I get a compiler error: Couldn't find type javax.inject.Singleton. Are you missing a dependency on your classpath?

>It is even simpler I would say. Instead of copying everything we should adapt the Jsr330ComponentProcessor to use the ones from the jakarta namespace if the javax ones are missing. This would mean if the user has only jakarta everything will work as expected.

Just some thoughts. 
- Can you rely on always having `javax.inject.Inject` or `jakarta.inject.Inject` in the annotation builder class path while running the annotation processor or is it dependent on the build system (Maven, Gradle, command line, ...)?
- I guess JSR330 implies using the javax.inject namespace. Would that confuse more if Mapstruct generated jakarta.inject annotations?
- Would not creating a new value for component model (e.g. `jakarta`) lead to more reproducible builds?
- Could there be a scenario were both annotations is on the class path?
- People switching to JakartaEE would expect they have to do some work and I suspect they would not mind also switching the component model.  

> Would you be interested in adding this functionality

I tried to implement support for Jakarta inject and that was easy. How ever test are using Spring to test the generated classes and Spring does not support the jakarta inject annotations. I have no clue how to configure spring to support them so I failed to create a test following the pattern of the other tests.

**Comment by Draluy** [comment]
I'm using micronaut 3 and would love support for this also.
