### ISSUE TITLE
Can't map property "JAXBElement<String>" to "String"

### ISSUE THREAD

**Issue by nickaden** [mapstruct/mapstruct#2578]
When I try map JAXBElement<String> to String value, it fails with error:
**"Can't map property "JAXBElement\<String\> currencyCode" to "String currencyCode". Consider to declare/implement a mapping method: "String map(JAXBElement\<String\> value)".**

Source type code:
```java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrencyAmountType", propOrder = {
        "amount",
        "currencyCode",
        "billingCurrencyCode"
})
public class CurrencyAmountType implements Cloneable, CopyTo2
{

    @XmlElement(name = "Amount", required = true, nillable = true)
    protected BigDecimal amount;
    @XmlElementRef(name = "CurrencyCode", namespace = "v3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currencyCode;
    @XmlElement(name = "BillingCurrencyCode")
    protected String billingCurrencyCode;


    public BigDecimal getAmount() {
        return amount;
    }


    public void setAmount(BigDecimal value) {
        this.amount = value;
    }


    public JAXBElement<String> getCurrencyCode() {
        return currencyCode;
    }


    public void setCurrencyCode(JAXBElement<String> value) {
        this.currencyCode = value;
    }


    public String getBillingCurrencyCode() {
        return billingCurrencyCode;
    }


    public void setBillingCurrencyCode(String value) {
        this.billingCurrencyCode = value;
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE2;
        return copyTo(null, target, strategy);
    }

})
```

Target class:
```java
@Data
@AllArgsConstructor
public class Amount {
    private BigDecimal value;
    private String currencyCode;
}
```

**Comment by nickaden** [comment]
Using Mapstruct 1.4.2Final

**Comment by incaseoftrouble** [comment]
What about

```java
@Mapping(source = "getBillingCurrencyCode", target = "currencyCode")
public abstract Amount map(CurrencyAmountType amount);
```
or simply declare
```java
public String map(CurrencyAmountType amount) {
  return amount.getBillingCurrencyCode();
}
```

mapstruct is about mapping from beans to beans, the accessor for the string is already there.

**Comment by nickaden** [comment]
Regarding docs, it should implicitliy convert JAXBElement<T> to T: https://mapstruct.org/documentation/stable/reference/html/#implicit-type-conversions

**Comment by incaseoftrouble** [comment]
Ah, sorry, I misunderstood you :)

Can you try to create a minimal example? I guess that the `Fare` mapping as well as all `@Xml...` annotations could be pruned.

One idea: This shouldn't change anything, but what happens if you don't use Lombok for `Amount` (i.e. make it bean instead). Maybe this is some weird interplay with constructor-based mapping?

**Comment by prasanth08** [comment]
Use this annotation @Mapper(uses = ObjectFactory.class) on the interface.

**Comment by dkellenb** [comment]
I stumbled on a similar problem when migrating from Sun to Jakarta. (Can't map property `String to JAXBElement<String>`)  => You need to wait for Release 1.6.0.

**Comment by matthenry87** [comment]
Hello @filiphr! 

A large part of the community is actively switching to Spring Boot 3, and thus jakarta. Any idea when 1.6.0 will be released? This is quite the blocker for our projects in which we're generating POJOs from a WSDL and pointing MapStruct at the generated ObjectFactory.

We've confirmed that it is indeed working with the current snapshot.

Thanks!

**Comment by filiphr** [comment]
I've tried this with 1.5 and javax `JAXBElement` and it works correctly. 

The support for jakarta `JAXBElement` is part of #2730 and will be part of 1.6.

**Comment by matthenry87** [comment]
@filiphr Do we have a rough timeline on when 1.6 is planned for release?

**Comment by filiphr** [comment]
I've reopened #2730 and we'll release it in 1.5.5
