### ISSUE TITLE
Mapper fails to initialize object when constructor contains jackson annotations and is located in different module

### ISSUE THREAD

**Issue by Niffler** [mapstruct/mapstruct#2584]
I'm experiencing an issue where a mapstruct-generated mapper fails to initialize the target object from a different module.
I suspect this issue is caused by the @JsonProperty annotation of the target class' constructor arguments.

The complete code of the following example is contained in [this repository](https://github.com/Niffler/mapstruct-jackson-test).

The target class, which is located in a different module than the mapper interface:
```Java
package org.example.client;

import ...

public final class Target {
    private final String test;
    private final String name;

    @JsonCreator
    public Target(@JsonProperty("test") String test, @JsonProperty("name") String name) {
        this.test = test;
        this.name = name;
    }
    public String getTest() {
        return this.test;
    }
    public String getName() {
        return name;
    }
}
```
The source class, which is the same as the target class without the jackson annotations:
```Java
package org.example.core;

public final class Source {
    private final String test;
    private final String name;

    public Source(String test, String name) {
        this.test = test;
        this.name = name;
    }

    public String getTest() {
        return this.test;
    }

    public String getName() {
        return name;
    }
}
```

The mapper interface, which is located in a different module than the target class:
```Java
package org.example.core;

import ...

@Mapper
public interface SourceTargetMapper {

    SourceTargetMapper MAPPER = Mappers.getMapper(SourceTargetMapper.class);

    Target toTarget(Source s);
}
```

The generated mapper implementation:
```Java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-09-15T20:35:56+0200",
    comments = "version: 1.5.0.Beta1, compiler: javac, environment: Java 1.8.0_282 (AdoptOpenJDK)"
)
public class SourceTargetMapperImpl implements SourceTargetMapper {

    @Override
    public Target toTarget(Source s) {
        if ( s == null ) {
            return null;
        }

        String arg0 = null;
        String arg1 = null;

        Target target = new Target( arg0, arg1 );

        return target;
    }
}
```
As we can see, the mapper initializes the target object with null instead of the field values of the source object.

If the target class is moved to the same module as the mapper interface, the mapper is generated correctly.
Likewise, if the @JsonProperty annotations are removed form the traget class' constructor arguments, the mapper is also generated correctly.

**Comment by skv4733** [comment]
Hi I am facing same issue.  Do you have any updates? May be any  workaround.

**Comment by Zegveld** [comment]
I've checked out the example repository and ran `mvn clean compile` with several java versions.
Here are the results of how the code for the Mapper looks like.
Java 17: :heavy_check_mark: 
Java 11: :heavy_check_mark: 
Java 8: :x: 

As work-around I'd suggest use java 11 or 17 for compiling. I did not alter anything from the example repository, so the classes are still be generated for java 8.

**Comment by filiphr** [comment]
This can also be fixed on Java 8 by making sure that the `parameters` flag is set to true for the compilation is set to true. Then the javac compiler is not going to remove the parameters name from the compile byte code (which is what MapStruct is reading when checking the constructor). You can see how to configure this [here](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#parameters)
