### ISSUE TITLE
属性映射为null

### ISSUE THREAD

**Issue by Strong-bb** [mapstruct/mapstruct#2585]
我发现在 Spring boot 2.5.4版本下 结合lombok 对应的属性映射会为null 而一旦切换成2.3.0 就能够成功映射  希望能解决这个问题

I found that under Spring boot 2.5.4 version, the attribute mapping corresponding to lombok will be null, and once it is switched to 2.3.0, it can be mapped successfully. I hope to solve this problem.

**Comment by sjaakd** [comment]
Sorry.. but can you provide an example.. 

There have been many problems related to lombok and mapstruct in the past. Please read through the issues if there's one that covers your question.

Will continue to close this issue.
