### ISSUE TITLE
Ignore matching mapper for simple assignments

### ISSUE THREAD

**Issue by csisy** [mapstruct/mapstruct#2586]
Given an entity that we wish to update and a simple data class (~DTO) with a member whose type is the same as the entity's type.

```
class MyEntity {
  // ...
  private MyEntity linkedEntity;
  // getter, setter...
}

class MyData {
  // ...
  public MyEntity linkedEntity;
}
```

The mapper is configured to produce an error if a source property is not mapped. This is really convenient to catch typos, for example.

```
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
interface UpdateMapper {
  void update(MyData source, @MappingTarget MyEntity target);

  // ...
  void update(MyEntity source, @MappingTarget MyEntity target);
}
```

And because another MyEntity -> MyEntity mapping exists, the generated mapping tries to use it and generates a similar code to this:

```
class UpdateMapperImpl {
  void update(MyData source, @MappingTarget MyEntity target) {
    // ...
    if (source.linkedEntity != null) {
      if (target.getLinkedEntity() == null) {
        target.setLinkedEntity( new MyEntity() );
      }
      update( source.linkedEntity, target.getLinkedEntity() );
    }
  }
}
```

What I could do is to use an expression in the former update mapper, something like this:

```
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
interface UpdateMapper {
  @Mapping(target = "linkedEntity", expression = "java(source.linkedEntity)")
  void update(MyData source, @MappingTarget MyEntity target);

  // ...
  void update(MyEntity source, @MappingTarget MyEntity target);
}
```

This would simply pass the field to the corresponding setter. The problem is that since the mapper is marked to report unmapped source as error, this does not even compile.

There should be a way to either:

- mark a `@Mapping` to ignore matching mapper functions, or
- have a separate annotation, like `@SimpleMapping` to achieve this, or
- consider the expressions when determining used/unused source/target parameters

**Comment by csisy** [comment]
Found a workaround, but still would be nice if a solution would be part of the MapStruct itself.

```
@Mapper
interface MyMapper {
  @Mapping(target = "linkedEntity", source = "source", qualifiedByName = "assign")
  void update(MyData source, @MappingTarget MyEntity target);

  @Named("assign")
  default <T> T assign(T source) {
    return source;
  }
}
```

**Comment by filiphr** [comment]
If you do not want a mapping to be considered by MapStruct you can easily do that by using `@Named`.

e.g. in your case you can do

```
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
interface UpdateMapper {

  void update(MyData source, @MappingTarget MyEntity target);

  // ...
  @Named("update")
  void update(MyEntity source, @MappingTarget MyEntity target);
}
```

When you have something like this then MapStruct will perform the assignment and not use your method.
