### ISSUE TITLE
Detecting 'javax.annotation.processing.Generated' in modular Java does not seem to work

### ISSUE THREAD

**Issue by liangjihua** [mapstruct/mapstruct#2629]
- [x] Is this an issue (and hence not a question)? 

In modular Java, the code generated by mapstruct uses `javax.annotation.processing.Generated`, but the source module does not require module `java.compiler`. Because of this problem, the generated code cannot be compiled.

I found the following description in the documentation, I am not sure how `mapstruct` decides whether to use `javax.annotation.processing.Generated` :

> In Java 9 java.annotation.processing.Generated was added (part of the java.compiler module), if this annotation is available then it will be used.

Is there an alternative of `@Generated` in modular Java?

 JDK version: 11
mapstruct version: 1.4.2.Final
building tool version: gradle 7.2

**Comment by filiphr** [comment]
Thanks for raising this issue @liangjihua. 

The logic where we decide whether to use the `@Generated` is located in 

https://github.com/mapstruct/mapstruct/blob/e32fc8c283085da5080044c9a41b1dd1e71198ac/processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java#L121-L125

Basically, we check through [`Elements#getTypeElement(CharSequence)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.compiler/javax/lang/model/util/Elements.html#getTypeElement(java.lang.CharSequence)) to get the requested `TypeElement`. 

I personally am not that familiar with the Module system, reading a bit on the Javadocs perhaps we need to use [`Elements#getTypeElement(ModuleElement, CharSequence)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.compiler/javax/lang/model/util/Elements.html#getTypeElement(javax.lang.model.element.ModuleElement,java.lang.CharSequence)) and pass the current mapper module element.

Can you please by any chance provide a small example that we can then integrated in our integration tests to validate that this functionality works as expected?

**Comment by liangjihua** [comment]
I was attempting to reproduce this issue, then I found it's caused by `lombok`, if I don't use `lombok`, everything works well.
`lombok` requires `java.compiler`, I think this is the reason why `@Generated` is available, that proves your guess @filiphr.

**Comment by liangjihua** [comment]
Should search `@Generated` in a specific module, not all modules.

**Comment by filiphr** [comment]
Can you still provide the minimum example with Lombok. The type availability needs to be within the source module. Perhaps we can improve something here

**Comment by liangjihua** [comment]
https://github.com/liangjihua/mapstruct-reproduce
Here it is. Just compile it.

**Comment by filiphr** [comment]
Thanks a lot for the project @liangjihua.

I managed to isolate the problem and it is as I expected. We are using `Elements#getTypeElement` incorrectly in a modular application. 

We need to see how to solve this problem. The APIs we need to use are not there in Java 8, so we need to use some reflection, Multi Release Jars or do it somehow else.

**Comment by filiphr** [comment]
I've managed to find a solution for this problem. There is an open PR once we merge that we are going to properly use the `ModuleElement` when there is one.
