### ISSUE TITLE
@Context  annotation can't be used with parameter of type Map<> in case it is reference as a source

### ISSUE THREAD

**Issue by Vkamnev** [mapstruct/mapstruct#2631]
- [X] Is this an issue (Rather a BUG)

mapstruct version: 1.5.0.Beta1

This code won't compile (same issue in version 1.4, but there maps to bean is not supported oficcialy):
```
public abstract class RecordInvolvedPartyDetailsIndividualRequestMapper {

    public static RecordInvolvedPartyDetailsIndividualRequestMapper INSTANCE = Mappers.getMapper(RecordInvolvedPartyDetailsIndividualRequestMapper.class);

    @Mapping(target = "cdmBusinessObjectIdentification.businessObjectType", source = "flowVars.businessObjectType") 
    @Mapping(target = "customerContactPreference", source = "travelNotification.contactPreferences")
    public abstract RecordInvolvedPartyDetailsIndividualRequest toRecordInvolvedPartyDetailsIndividualRequest
            (TravelNotification travelNotification, @Context Map<String, String> flowVars);

    protected CustomerContactPreference contactPreferencesToCustomerContactPreference(ContactPreferencesDTO contactPreferences, @Context Map<String, String> flowVars) {
        return ContactPreferenceMapper.INSTANCE.fromContactPreferencesDTO(contactPreferences, flowVars);
    }
}
```
This code doesn't compile due to error :
_[29,65] No property named "flowVars.businessObjectType" exists in source parameter(s). Did you mean "contactPreferences"?_

So, basically by adding @Context annotation it doesn't treat the flowVars as a map

 I need to pass a context to underlying mapper, as well as to use some of the content of the context map on a level above. This works if i will replace the 
```
source = "flowVars.businessObjectType"
```
with
```
expression = "java(flowVars.get(\"businessObjectType\"))"
```
for example, and the context map is being passed to underlying mapper, and underlying mapper works just fine. But this is not what i need (this is a 4.x way of interacting with a map)

**Comment by filiphr** [comment]
This works as designed. Parameters which are marked with `@Context` are not treated as source parameters and thus cannot be used in `source`.

If you remove `@Context` then it will work as expected. However, `contactPreferencesToCustomerContactPreference` will not work then.

**Comment by filiphr** [comment]
You could add a helper method to achieve what you are looking for.

e.g.

```
public abstract class RecordInvolvedPartyDetailsIndividualRequestMapper {

    public static RecordInvolvedPartyDetailsIndividualRequestMapper INSTANCE = Mappers.getMapper(RecordInvolvedPartyDetailsIndividualRequestMapper.class);

    public RecordInvolvedPartyDetailsIndividualRequest toRecordInvolvedPartyDetailsIndividualRequest
            (TravelNotification travelNotification, @Context Map<String, String> flowVars) {
        return toRecordInvolvedPartyDetailsIndividualRequest(travelNotification, flowVars, flowVars);
    }

    @Mapping(target = "cdmBusinessObjectIdentification.businessObjectType", source = "flowVars.businessObjectType") 
    @Mapping(target = "customerContactPreference", source = "travelNotification.contactPreferences")
    protected abstract RecordInvolvedPartyDetailsIndividualRequest toRecordInvolvedPartyDetailsIndividualRequest
            (TravelNotification travelNotification, Map<String, String> flowVars, @Context Map<String, String> flowVarsContext);

    protected CustomerContactPreference contactPreferencesToCustomerContactPreference(ContactPreferencesDTO contactPreferences, @Context Map<String, String> flowVars) {
        return ContactPreferenceMapper.INSTANCE.fromContactPreferencesDTO(contactPreferences, flowVars);
    }
}
```

**Comment by Vkamnev** [comment]
Hi @filiphr , can you please reconsider this behavior? The below arguments "why":
1. I think it normal to pass the Context as deep as it needs to be based, as well as use it on a high level. mapstruct allows usage of multiple sources, so i don't understand why one of the sources used can't be "shared"
2. It is kinda similar to "collecting parameter" pattern, just reversed
3. Our use case - we migrating some huge amount of legacy applications, which were using custom "mapper tool", so we need to automate this migration, in other words to be able to generate the mapping templates (or java classes), and having this @Context annotation with map consistent on each level is crucial for us.
4. Tool like spring integration/mulesoft uses concept of a "flow" and it has "flowVars" (in case of mule), which basically is the execution context, and can be a bucket you "throw everyhting", this actually our case - we need to access the context on every level
5. The exception thrown in my case doesn't seem to be " explicit forbid usage of the context as a source", it was rather random, i assume if i use bean instead of a map, it would work with a context.
6. On the next level, i have the same parameter (flowVars) marked as @Context and yet it works (i'm using it as "one of a sources" for ContactPreferenceMapper generation)

So, if it possible to enable support of a @Context as source

**Comment by filiphr** [comment]
@Vkamnev I completely understand why you need to do what you are doing. However, your request is actually falling in another category. You want for MapStruct to support picking up mapping methods with multiple sources, i.e. similar to how we do for Constructors, which is basically https://github.com/mapstruct/mapstruct/issues/1315.

Currently you are basically using one functionality to go around certain limitations we have.

In addition to that, something that could make your request slightly easier is a combination of `@Context` and https://github.com/mapstruct/mapstruct/issues/2559, i.e. we would allow to explicitly mark that a certain method should be treated as a source parameter.
