### ISSUE TITLE
Couldn't find type javax.inject.Singleton. Are you missing a dependency on your classpath?

### ISSUE THREAD

**Issue by macabrus** [mapstruct/mapstruct#2644]
Hello, this is my first issue on github 🎉

I am using jsr330 component model for injection into micronaut beans. However, there build fails because of javax dependency. I don't know if it's related to Micronaut migrating to Jakarta API so I added javax maven dependency:

```
<dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
      <optional>true</optional>
</dependency>
```
And it still failed to compile, saying that dependency is missing which doesn't make sense to me.
I tried with `scope: compile` and `scope: provided` but none worked.

Here is mapper definition:

```
@Mapper(componentModel = "jsr330")
public interface UserMapper {

    @Mappings({
        @Mapping(
            source = "password",
            target = "passwordHash"
        )
    })
    User dtoToEntity(CreateUserDto dto);

}
```

I don't believe it is micronaut issue since it doesn't fail for plain @Mapper annotation instead of @Mapper(componentModel...) Although I believe it's irrelevant for this issue, I'll include micronaut controller just in case. Here is where I'd like to inject the bean:

```
@Controller("/user")
@Secured(SecurityRule.IS_ANONYMOUS)
public class UserController {

    private UserService userService;
    private UserMapper mapper;

    @Inject
    public UserController(UserService userService, UserMapper mapper) {
        this.userService = userService;
        this.mapper = mapper;
    }

    @Get
    public Collection<User> getAll() {
        return userService.getAll();
    }

    @Post("/new")
    public HttpResponse<User> createUser(@Valid @Body CreateUserDto dto) {
        var newUser = mapper.dtoToEntity(dto);
        userService.add(newUser);
        return HttpResponse.ok(null);
    }
}
```

Also, I have read that I had to add compiler flags for default component model but even that didn't work.
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <release>15</release>
          <!-- Uncomment to enable incremental compilation -->
<!--           <useIncrementalCompilation>true</useIncrementalCompilation>-->
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.22</version>
            </path>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>1.4.2.Final</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-inject-java</artifactId>
              <version>3.1.1</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-http-validation</artifactId>
              <version>${micronaut.version}</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <compilerArg>
              -Amapstruct.defaultComponentModel=jsr330
            </compilerArg>
            <arg>-Amicronaut.processing.group=com.bc</arg>
            <arg>-Amicronaut.processing.module=micronaut-starter</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```

Configuration:
Java - 15
Build tool - Maven
Micronaut - 3.1.1
Mapstruct - 1.4.2.Final
Platform - MacOS X

EDIT: Upon examining other issues, I thought this might be related to #2567 

Any help greatly appreciated!

- [x] Is this an issue (and hence not a question)? 
Ans: I don't know whether it's a real issue.

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by filiphr** [comment]
Hey @macabrus,

> Hello, this is my first issue on github 🎉

Congrats on your first issue 🥳 .

To go back to your problem.
It is confusing to me why you would have this problem when you add

```xml
<dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
      <optional>true</optional>
</dependency>
```

I am not a Micronaut user and I am not sure how exactly it works with javax / jakarta. However, indeed #2567 is something that would bring support for Jakarta.

Can you please provide a minimal example with Micronaut so we can have a look at it?

**Comment by macabrus** [comment]
Sure, here is the [minimum repo](https://github.com/macabrus/mapstruct-jsr330-micronaut-issue).
To compile and run: `mvn mn:run`
You can see that processor fails to generate jsr330 compliant beans even with javax.* on CP, so micronaut doesn't pick them up when it compiles but it still runs, injecting null instead of UserMapperImpl into UserController.

**Comment by filiphr** [comment]
I realized why your example is not working is because the `javax.inject.Singleton` is located in

```xml
<dependency>
    <groupId>javax.inject</groupId>
    <artifactId>javax.inject</artifactId>
    <version>1</version>
</dependency>
```

and not in 

```xml
<dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
      <optional>true</optional>
</dependency>
```

Once I added the `javax.inject` dependency then everything is working fine.

I am going to close this issue now and you can follow #2567 for when we add proper support.
