### ISSUE TITLE
manytomany @Named. Return contains a unexpected attribute

### ISSUE THREAD

**Issue by ustcck** [mapstruct/mapstruct#2651]
`relationship ManyToMany {
	Job{task(title)} to Task{job}
}`

`@Entity
@Table(name = "job")
public class Job implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "job_title")
    private String jobTitle;

    @Column(name = "min_salary")
    private Long minSalary;

    @Column(name = "max_salary")
    private Long maxSalary;

    @ManyToMany
    @JoinTable(name = "rel_job__task", joinColumns = @JoinColumn(name = "job_id"), inverseJoinColumns = @JoinColumn(name = "task_id"))
    @JsonIgnoreProperties(value = { "jobs" }, allowSetters = true)
    private Set<Task> tasks = new HashSet<>();
}`

`@Entity
@Table(name = "task")
public class Task implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "title")
    private String title;

    @Column(name = "description")
    private String description;

    @ManyToMany(mappedBy = "tasks")
    @JsonIgnoreProperties(value = { "tasks" }, allowSetters = true)
    private Set<Job> jobs = new HashSet<>();
}`

`public class JobDTO implements Serializable {

    private Long id;

    private String jobTitle;

    private Long minSalary;

    private Long maxSalary;

    private Set<TaskDTO> tasks = new HashSet<>();
}`

`public class TaskDTO implements Serializable {

    private Long id;

    private String title;

    private String description;
}`

> @Mapper(componentModel = "spring", uses = { TaskMapper.class, EmployeeMapper.class })
public interface JobMapper extends EntityMapper<JobDTO, Job> {
    @Mapping(target = "tasks", source = "tasks", qualifiedByName = "titleSet")
    @Mapping(target = "employee", source = "employee", qualifiedByName = "id")
    JobDTO toDto(Job s);
}

> @Mapper(componentModel = "spring", uses = {})
public interface TaskMapper extends EntityMapper<TaskDTO, Task> {
    @Named("titleSet")
    @BeanMapping(ignoreByDefault = true)
    @Mapping(target = "id", source = "id")
    @Mapping(target = "title", source = "title")
    Set<TaskDTO> toDtoTitleSet(Set<Task> task);
}

**When using `jobRepository.findOneWithEagerRelationships(id).map(jobMapper::toDto)`, I got a result that contains a unexpected "description" attribute
`{
  "id": 1,
  "jobTitle": "Dynamic Operations Associate",
  "minSalary": 36593,
  "maxSalary": 95887,
  "tasks": [
    {
      "id": 1,
      "title": "withdrawal Avon rich",
      "description": "payment matrices payment"
    }
  ]
}`**

TaskMapperImpl:
`@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-11-10T16:03:51+0800",
    comments = "version: 1.4.2.Final, compiler: javac, environment: Java 11.0.12 (Eclipse Foundation)"
)
@Component
public class TaskMapperImpl implements TaskMapper {

    @Override
    public Task toEntity(TaskDTO dto) {
        if ( dto == null ) {
            return null;
        }

        Task task = new Task();

        task.setId( dto.getId() );
        task.setTitle( dto.getTitle() );
        task.setDescription( dto.getDescription() );

        return task;
    }

    @Override
    public TaskDTO toDto(Task entity) {
        if ( entity == null ) {
            return null;
        }

        TaskDTO taskDTO = new TaskDTO();

        taskDTO.setId( entity.getId() );
        taskDTO.setTitle( entity.getTitle() );
        taskDTO.setDescription( entity.getDescription() );

        return taskDTO;
    }

    @Override
    public List<Task> toEntity(List<TaskDTO> dtoList) {
        if ( dtoList == null ) {
            return null;
        }

        List<Task> list = new ArrayList<Task>( dtoList.size() );
        for ( TaskDTO taskDTO : dtoList ) {
            list.add( toEntity( taskDTO ) );
        }

        return list;
    }

    @Override
    public List<TaskDTO> toDto(List<Task> entityList) {
        if ( entityList == null ) {
            return null;
        }

        List<TaskDTO> list = new ArrayList<TaskDTO>( entityList.size() );
        for ( Task task : entityList ) {
            list.add( toDto( task ) );
        }

        return list;
    }

    @Override
    public void partialUpdate(Task entity, TaskDTO dto) {
        if ( dto == null ) {
            return;
        }

        if ( dto.getId() != null ) {
            entity.setId( dto.getId() );
        }
        if ( dto.getTitle() != null ) {
            entity.setTitle( dto.getTitle() );
        }
        if ( dto.getDescription() != null ) {
            entity.setDescription( dto.getDescription() );
        }
    }

    @Override
    public Set<TaskDTO> toDtoTitleSet(Set<Task> task) {
        if ( task == null ) {
            return null;
        }

        Set<TaskDTO> set = new HashSet<TaskDTO>( Math.max( (int) ( task.size() / .75f ) + 1, 16 ) );
        for ( Task task1 : task ) {
            set.add( toDto( task1 ) );
        }

        return set;
    }
}
`

**Comment by Zegveld** [comment]
I believe this works as expected. You have supplied a method in your base interface `EntityMapper` which does the `Task` to `TaskDto` and the other way around. Mapstruct notices this method and uses it.
The annotations on the collection mapping will not be used then. 
What you might want to do is override the method in the base interface like this:
```
@Mapper(componentModel = "spring")
public interface TaskMapper extends EntityMapper<TaskDTO, Task> {
@Named("titleSet")
Set toDtoTitleSet(Set task);

@BeanMapping(ignoreByDefault = true)
@mapping(target = "id", source = "id")
@mapping(target = "title", source = "title")
@Override
TaskDTO toDto(Task entity);
}
```

If for a reason you want different behavior for the titles only vs the everything mapping, perhaps putting these in different classes would be better. For example:

```
@Mapper(componentModel = "spring")
public interface TaskMapper extends EntityMapper<TaskDTO, Task> {
}

@Mapper(componentModel = "spring")
public interface TaskMapperTitlesOnly extends EntityMapper<TaskDTO, Task> {
@Named("titleSet")
Set toDtoTitleSet(Set task);

@BeanMapping(ignoreByDefault = true)
@mapping(target = "id", source = "id")
@mapping(target = "title", source = "title")
@Override
TaskDTO toDto(Task entity);

@BeanMapping(ignoreByDefault = true)
@mapping(target = "id", source = "id")
@mapping(target = "title", source = "title")
@Override
Task toEntity(TaskDTO dto);
}
```
I myself am not that familiar with combining iterator mappings with qualifiers, but that might also be a solution.

Hope the above helps.

Come to think of it, this might be an enhancement to not use available mapping methods if explicit mapping annotations are present on an `IterableMapping` or `MapMapping`.

**Comment by ustcck** [comment]
I see, thanks for your reply.
