### ISSUE TITLE
how mapstruct  process @Mapping when first character is uppercase?

### ISSUE THREAD

**Issue by liudaoqiangtj** [mapstruct/mapstruct#2652]
mapstruct 是如何映射首字母大写的对象属性呢？
比如：
@Data
public class FirstUpperDTO {
     private String CellPopple;
}

@Data
public class FirstUpperVO{
   private String cellPopple;
}
我以为CellPopple的mapping应该是这样的：
@Mapper
public Interface CellPoppleMapper{
    @Mapping(source= "cell.CellPople", target = "cellPopple")
    FirstUpperVO transform(CellPopple cell);
}
然后编译报错 “has no property named CellPopple ”
经过多次猜测尝试验证发现，如下书写是编译通过的，且在generated-source目录生成了java文件
@Mapping(source= "cell.cellPople", target = "cellPopple")
就是要将CellPopple改为cellPopple。
想知道mapstruct为什么这么处理？（我知道javabean的规范不允许首字母大写的）

**Comment by filiphr** [comment]
This is explained in our documentation @liudaoqiangtj. It is in [this](https://mapstruct.org/documentation/stable/reference/html/#basic-mappings) section.

>The property name as defined in the [JavaBeans specification](http://www.oracle.com/technetwork/java/javase/documentation/spec-136004.html) must be specified in the `@Mapping` annotation, e.g. `seatCount` for a property with the accessor methods `getSeatCount()` and `setSeatCount()`.

In a nutshell the name of the private fields have no influence on MapStruct.
