### ISSUE TITLE
Mapstruct cannot generate @Autowired

### ISSUE THREAD

**Issue by fromsilence520** [mapstruct/mapstruct#2658]
![image](https://user-images.githubusercontent.com/12153595/142401950-74899219-ae76-475d-a649-3127b0607b0f.png)
![image](https://user-images.githubusercontent.com/12153595/142401966-537d4bee-d640-4faf-8d3a-89e21f520778.png)

**Comment by filiphr** [comment]
This works a designed. If the mappers from `Mapper#uses` are not used by MapStruct then we are not going to generate a field for them.
