### ISSUE TITLE
@Condition not working when the source in the Mapping is the source parameter

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#2666]

**Comment by HemalathaGowdar** [comment]
I have been using @condition , unable to see the methods annotated with @condition. Could you please help me

**Comment by filiphr** [comment]
@HemalathaGowdar you also opened #2688 and commented in another issue. There is really no need to do all those things. You need to be patient and wait for a reply on your issue. I've left a comment in #2688, you need to be way more clearer
