### ISSUE TITLE
Feature request for method override strategies

### ISSUE THREAD

**Issue by PegasusMKD** [mapstruct/mapstruct#2670]
As discussed in the thread, I was advised that I should create a feature request for this.
Stackoverflow thread: https://stackoverflow.com/questions/69952030/can-i-extend-mapstruct-methods/70044235#70044235

This would be really useful for me as a developer of libraries. I'd like to use MapStruct internally in the library, and then let the user "add on" any other mappings they might want. You can see it in more detail in the thread.

Another way that might be useful to have it implemented is maybe adding another annotation for merge, for example:

```java
@Mapper(componentModel = "spring", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE, methodOverrideStrategy = OverrideStrategy.MERGE)
public abstract class RealAccountMapper extends AccountMapper {

    @Override
    @MergeMapping(qualifiedByName="dynamicAccounts")
    @Mapping(target = "username", ignore = true)
    public abstract AccountDto toAccountDtoDefault(Account entity, @Context List<PropertyNode> propertyNodes);
}
```

Where with the `methodOverrideStrategy` we'd indicate that we plan on merging methods, and using the `@MergeMapping()` we'd indicate which mapping method we'd like to merge with. This would make it so that the MapStruct users aren't forced to use the same name while doing the overrides.

I'm open to a discussion, or any more info if needed.

**Comment by Zegveld** [comment]
Would `@InheritConfiguration` work in this case? 
see also https://mapstruct.org/documentation/dev/reference/html/#mapping-configuration-inheritance

It sounds like functionality similar to what that one does, although you would normally use it within the same module. But looking at the documentation of it, and how your class is defined it might do the trick.
You could even combine it with the method name (required if there are multiple candidates to inherit from) `@InheritConfiguration( name = "methodName" )`.

**Comment by PegasusMKD** [comment]
`@InheritConfiguration` works perfect for my use case. Thank you, I've never stumbled upon it until now even while reading documentation!
