### ISSUE TITLE
Spring Dependency Injection prevents using Mappers.getMapper()

### ISSUE THREAD

**Issue by ChrTall** [mapstruct/mapstruct#2681]
I have a Mapper that has the following Annotation:
`@Mapper(componentModel = "spring", uses = {NamedChartVariableMapper.class, ColoredChartVariableMapper.class})`

When I remove "componentModel = 'spring' " I can get the mapper and its required SubMappers(NamedChartVariableMapper) in my Unit Tests via: 
`Mappers.getMapper(SimpleMapper.class);`

If "componentModel = 'spring' " is present in the Annotation, I can get the mapper via Mappers.getMapper(), but when using it, I get a Null Pointer Exception, because NamedChartVariableMapper and ColoredChartVariableMapper are both null.
Is there a way to resolve this issue? The Unit Tests are run in the CI and I don´t want to annotate each Mapper Test with @SpringBootTest because of the overhead.

**Comment by filiphr** [comment]
`Mappers` is a basic way of getting the mappers when using the default component model. It is not meant to be used in combination with other component models such as `spring`. I would suggest that you use Spring to create an instance of you mapper or you use constructor injection and instantiate the mapper on your own.

**Comment by ChrTall** [comment]
@filiphr Thank you that worked.
