### ISSUE TITLE
`@DecoratedWith` does not work with incremental compilation in Gradle 7.3

### ISSUE THREAD

**Issue by laech** [mapstruct/mapstruct#2682]
Demo project for this issue: https://github.com/laech/mapstruct-spring-gradle-incremental-issue

If you checkout the demo project, it contains a mapper and a decorator:

```java
@Mapper(componentModel = "spring")
@DecoratedWith(PersonMapperDecorator.class)
interface PersonMapper {
  PersonDto personToPersonDto(Person person);
}
```

```java
abstract class PersonMapperDecorator implements PersonMapper {

  @Autowired
  @Qualifier("delegate")
  private PersonMapper delegate;

  @Override
  public PersonDto personToPersonDto(Person person) {
    PersonDto dto = delegate.personToPersonDto(person);
    dto.name += "!!";
    return dto;
  }
}
```

After initial compilation via `./gradlew compileJava` and inspecting the generated sources under `build/generated/sources/annotationProcessor/java/main/com/example/demo` we should have a correctly generated mapper and its decorator:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-08T14:16:55+1300",
    comments = "version: 1.5.0.Beta1, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.3.1.jar, environment: Java 17 (Private Build)"
)
@Component
@Primary
class PersonMapperImpl extends PersonMapperDecorator {
}
```

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-08T14:02:40+1300",
    comments = "version: 1.5.0.Beta1, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.3.1.jar, environment: Java 17 (Private Build)"
)
@Component
@Qualifier("delegate")
class PersonMapperImpl_ implements PersonMapper {

    @Override
    public PersonDto personToPersonDto(Person person) {
        if ( person == null ) {
            return null;
        }
        PersonDto personDto = new PersonDto();
        personDto.name = person.name;
        return personDto;
    }
}
```

Now make a change in `PersonMapperDecorator.java`, such as adding a random comment, then compile again with `./gradlew compileJava` and the generated classes become:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-08T14:14:11+1300",
    comments = "version: 1.5.0.Beta1, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.3.1.jar, environment: Java 17 (Private Build)"
)
@Component
class PersonMapperImpl implements PersonMapper {

    @Override
    public PersonDto personToPersonDto(Person person) {
        if ( person == null ) {
            return null;
        }
        PersonDto personDto = new PersonDto();
        personDto.name = person.name;
        return personDto;
    }
}
```

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-08T14:10:35+1300",
    comments = "version: 1.5.0.Beta1, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.3.1.jar, environment: Java 17 (Private Build)"
)
@Component
@Qualifier("delegate")
class PersonMapperImpl_ implements PersonMapper {

    @Override
    public PersonDto personToPersonDto(Person person) {
        if ( person == null ) {
            return null;
        }
        PersonDto personDto = new PersonDto();
        personDto.name = person.name;
        return personDto;
    }
}
```

The problem is the new `PersonMapperImpl` now contains the wrong code. A workaround is to rebuild the whole project, which is problematic for large projects.

**Update:**

This issue is reproducible on Gradle 7.3, but not on Gradle 7.2.

**Comment by filiphr** [comment]
Thanks a lot for your example project @laech. I did some analysis and I added it to https://github.com/gradle/gradle/issues/19366. This is indeed a regression in Gradle and I am not sure whether we can do much. The only thing we could do is to make `@DecoratedWith` have byte code retention, but that doesn't make a lot of point from our point of view, since the annotation is not needed there.

I will keep this issue open in order to track the Gradle issue.

**Comment by filiphr** [comment]
Seems like there was a change in Gradle and incremental processing only works properly when the annotation processor uses `CLASS` or `RUNTIME` retention annotations. 

`@DecoratedWith` is the only annotation that is `SOURCE` retention for MapStruct. Therefore, we are going to use this issue to change this in the upcoming release in order to be able to work properly with Gradle
