### ISSUE TITLE
Access to the target property name 

### ISSUE THREAD

**Issue by HemalathaGowdar** [mapstruct/mapstruct#2688]
Expose target property to method arguments

**Comment by filiphr** [comment]
Can you please provide an example?

**Comment by HemalathaGowdar** [comment]
@Mapper(config = MapperBConfig.class , uses = EValueMapper.class)
@Component 
public abstract  class AttribMapper {
@Mapping(Source = "indicator" , target= "ïndicator")
public abstract TargetAttributes TargetAttributesMapper( Source Attributes @Mapping TargetAttributes );

@condition
public boolean conditioncheck(String value)
{
if(contains in map attribute check) // basically am trying to map to the target attribute if that attribute is required by consumer 
return true
else return false
}

This method should get invoke for all attributes mapping.
I also tried Conditionexpression to check whether this attribute in teh consumer list to map or not . This also not coming in the generated impl class

Could you please suggest here.

**Comment by Zegveld** [comment]
If I understand correctly what you want is something like I've got a `Map<String, Object>` named `source` and another `Map<String, Object>` named `target` and I only want to map the entries from `source` for which there is already an entry present in `target`?
Trying to do this using conditions with Iterables or Maps is not supported yet, see #1610 for more information.

However writing the mapping yourself might not be that much additional code, and mapstruct can still use it in the mappingchain like this:
```
@Mapper
public abstract class ConditionalMapMapper {
    static class Item {
        Map<String, String> value;
       // getters and setters
    }

    static class ItemDto {
        Map<String, String> value;
       // getters and setters
    }

    abstract Item map(ItemDto dto, @MappingTarget Item item);

    void map(Map<String, String> source, @MappingTarget Map<String, String> target) {
        for ( Entry<String, String> entry : source.entrySet() ) {
            if ( target.containsKey( entry.getKey() ) ) {
                target.put( entry.getKey(), entry.getValue() );
            }
        }
    }
}
```

The map method with the source and target map will be used in the implementation to map from/to a map.

```
public class ConditionalMapMapperImpl extends ConditionalMapMapper {

    @Override
    Item map(ItemDto dto, Item item) {
        if ( dto == null ) {
            return null;
        }

        if ( dto.getValue() != null ) {
            if ( item.getValue() == null ) {
                item.setValue( new LinkedHashMap<String, String>() );
            }
            map( dto.getValue(), item.getValue() );
        }
        else {
            item.setValue( null );
        }

        return item;
    }
}
```

Hope this helps.

**Comment by HemalathaGowdar** [comment]
No , I am looking something if Target attribute name is present in my attribute list(list which has selected target attribute name for each diff scenario ) to map then only i should map else I should skip mapping.

**Comment by Zegveld** [comment]
So something like:

```java
@Mapper
public abstract class ConditionalMapMapper {
    static class Item {
        Map<String, String> value;
       // getters and setters
    }

    static class ItemDto {
        Map<String, String> value;
       // getters and setters
    }

    abstract Item map(ItemDto dto, @MappingTarget Item item, @Context List<String> attributeList);

    void map(Map<String, String> source, @MappingTarget Map<String, String> target, @Context List<String> attributeList) {
        for ( Entry<String, String> entry : source.entrySet() ) {
            if ( attributeList.contains( entry.getKey() ) ) {
                target.put( entry.getKey(), entry.getValue() );
            }
        }
    }
}
```

The map method with the source and target map will be used in the implementation to map from/to a map.

```java
public class ConditionalMapMapperImpl extends ConditionalMapMapper {

    @Override
    Item map(ItemDto dto, Item item, List<String> attributeList) {
        if ( dto == null ) {
            return null;
        }

        if ( dto.getValue() != null ) {
            if ( item.getValue() == null ) {
                item.setValue( new LinkedHashMap<String, String>() );
            }
            map( dto.getValue(), item.getValue(), attributeList );
        }
        else {
            item.setValue( null );
        }

        return item;
    }
}
```

Am I getting closer or still misunderstanding you?

**Comment by HemalathaGowdar** [comment]
Sorry for the delay .

This is what we are looking.

package mapstruct;

@Mapper(uses = TesterMapper.PresenceUtill.class)
public interface TesterMapper {
	
	TesterMapper inst = Mappers.getMapper(TesterMapper.class);
	
	@Mapping(source ="name" , target ="name"  )
	@Mapping(source ="secName" , target ="sName" , conditionExpression = "java(variablePresenceCheck(\"sName\"))" )
	@Mapping(source ="isHuman" , target ="isHuman" )
	 MapsStructTarget  mapstrucMapper (MapStructSource src);
	
	
	 class PresenceUtill {

		@Condition
		public boolean checkmethod(String str , String source)
		{
			if (null != str)
			{
				System.out.println(str);
				System.out.println(source);
			
				return true;
			}
			return false;
		}
		
		@Condition
		public boolean checkmethod(Boolean str)
		{
			if (null != str)
			{
				return true;
			}
			return false;
		}

	}
	
	
	  default boolean variablePresenceCheck(String str) { 
		  
		  if (I will check this variable name is present in my attrib list  ) { return true;
		  }
	  return false; }
	 

}
 Using conditionExpression I can achieve this , by passing the name of the variable explicitly in conditionExpression.
Do we have something in @condition annotation too - I need the name of the target variable on each mappings. so that I can evaluate whether I need to set this variable or skip

**Comment by Zegveld** [comment]
@filiphr , I don't believe there is an annotation to reference the property name yet, is there?
So this would be a feature request to implement a `method argument annotation` much like how `@TargetType` works for passing the class, perhaps something like `@TargetProperty`.

**Comment by HemalathaGowdar** [comment]
Thanks for the information . We can use conditional expression when we have diff names. But when we have the same names  for the entire classes , in that case we are not using @Mapping annotations.

Could you please suggest  for this scenario ? can we achieve this by overriding any of the existing methods for now

**Comment by filiphr** [comment]
You are right @Zegveld there is no annotation that would allow access to the target property name. Supporting `@TargetProperty` for a string method argument is something that we could add.

I will rename this issue.

@HemalathaGowdar you can still use `@Mapping` even if the source and target names are identical.

e.g.
```
@Mapping(target = "id", conditionExpression = "java(...)")
```

**Comment by HemalathaGowdar** [comment]
Yes , we can . But the problem is we have so many files with lot of attributes . That new annotation to support in @condition methods . If you could help me with this new feature timelines . Ours is enhancement project ,we can wait for this feature. This would help us.

**Comment by filiphr** [comment]
>If you could help me with this new feature timelines 

Unfortunately we can't provide timelines, since all of us are working on this on a part time voluntary basis and we try to focus on the most requested features for new releases. In case you are interested in seeing this feature sooner you can always provide a PR that we can review and integrate.

**Comment by BabkenSahakyan** [comment]
This is exactly the problem I'm facing now. In my case for a given class I've a list of non editable properties which is configurable and may change at runtime and this `@Condition` methods seems the only appropriate place to do this checking. With a support of `@MappingTarget` and `@TargetProperty` problem will be nicely solved.

Thank you all.

**Comment by HemalathaGowdar** [comment]
When am giving conditional Expression , the NULL check is getting replaced by conditional expression method. I need NULL check to irrespective of conditionalExpression. Could u please suggest

**Comment by filiphr** [comment]
@HemalathaGowdar please do not use this issue to ask questions about unrelated things. The documentation for this is in the [Conditional Mapping](https://mapstruct.org/documentation/dev/reference/html/#conditional-mapping) section of our documentation. If something is not clear please open a discussion, ask on StackOverflow or out Gitter Room.

**Comment by filiphr** [comment]
Thanks for your work on this @ivlcic. This has been integrated into main.

**Comment by FlorianCassayre** [comment]
This seems to correspond to what our project is needing. Is there a planned date for the release of `1.6.0` (even a release candidate)?

**Comment by filiphr** [comment]
@FlorianCassayre we have some other issues that we would like to tackle before we release a first beta release for 1.6. I hope that I can speed this up

**Comment by FlorianCassayre** [comment]
Thanks for the reply, I understand; we will follow that closely and will be looking forward to that beta release.

**Comment by filiphr** [comment]
@ivlcic it is going slower that I would like. Unfortunately I do not have ample of time, so trying to find the time to wrap things up and do an initial release
