### ISSUE TITLE
@Condition docs out of sync

### ISSUE THREAD

**Issue by Desislav-Petrov** [mapstruct/mapstruct#2689]
Hi,

Looks like we have an issue in the 1.5 beta docs: https://mapstruct.org/documentation/dev/reference/html/#selection-based-on-qualifiers

In the bit that says 'Example 83. Custom mapping method declaring checked exception', there seems to be no try-catch ?

**Comment by filiphr** [comment]
There is a try-catch in "Example 84". I don't understand where the out of sync is

**Comment by Desislav-Petrov** [comment]
Hi,

You have the following:

**Example 81. try-catch block in generated implementation** however there is no try-catch as a part of the code snippet below.

**Comment by Zegveld** [comment]
`Example 81. try-catch block in generated implementation` should be `Example 81. Custom condition check in generated implementation`.
I'll create a PR for this to fix it.

**Comment by filiphr** [comment]
Good catch @Zegveld. Thanks for reporting this @Desislav-Petrov. It has been integrated into the main branch and will be in the next release
