### ISSUE TITLE
Mapping from map data type to Java object

### ISSUE THREAD

**Issue by flychao88** [mapstruct/mapstruct#2691]
hank you very much for your answer

I tried to use the test version of mapstruct1.5 beta, but now there is a problem. Although the new test version supports the transformation of map - > bean, it does not support nesting. For example, I add a map data in the map. How should I do this? Thank you very much.

**Comment by filiphr** [comment]
You'll need to be more precise about the problem with some examples. We do support nesting as well. I would suggest using StackOverflow or the [Discussions](https://github.com/mapstruct/mapstruct/discussions) for asking questions
