### ISSUE TITLE
SubclassMapping fails with abstract class

### ISSUE THREAD

**Issue by pennal** [mapstruct/mapstruct#2695]
I am currently testing release 1.5.0.beta2, and more specifically the `@SubclassMapping` annotation and I am running into a few issues. 

This is my structure:
```java
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Table(name = "PlatformUser") // Postgres does not like the `user` keyword
// WARNING: This may not be needed! I am in the middle of a rewrite, so this may need to be removed
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = PersonalUser.class, name = "USER"),
        @JsonSubTypes.Type(value = CompanyUser.class, name = "COMPANY"),
})
public abstract class User extends BaseModel {
    private String email;
    // Other fields omitted for brevity
}

public class PersonalUser extends User {
    private String firstName;
    private String lastName;
    // Other fields
}

public class CompanyUser extends User {
    private String company;
    private String url;
    // Other fields
}
```

And here are the DTOs:

```java
@Data
@Builder
@NoArgsConstructor
public abstract class UserDTO {
    private Integer id;
    private String email;
}

@EqualsAndHashCode(callSuper = true)
@Data
@Builder
public class PersonalUserDTO extends UserDTO {
    private String firstName;
    private String lastName;
}

@EqualsAndHashCode(callSuper = true)
@Data
@Builder
public class CompanyUserDTO extends UserDTO {
    private String company;
    private String url;
}
```

And I have defined the following mappings:
```java
@Mapper(componentModel = "spring", subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION)
public interface CompanyUsersMapper {
    CompanyUsersMapper INSTANCE = Mappers.getMapper(CompanyUsersMapper.class);

    CompanyUserDTO toCompanyUserDTO(CompanyUser companyUser);
    CompanyUser toCompanyUser(CompanyUserDTO companyUserDTO);
}


@Mapper(componentModel = "spring", subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION)
public interface PersonalUsersMapper {
    PersonalUsersMapper INSTANCE = Mappers.getMapper(PersonalUsersMapper.class);

    PersonalUser toPersonalUser(PersonalUserDTO personalUserDTO);
    PersonalUserDTO toPersonalUserDTO(PersonalUser personalUser);
}

@Mapper(componentModel = "spring", subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION)
public interface UsersMapper {
    UsersMapper INSTANCE = Mappers.getMapper(UsersMapper.class);

    @SubclassMapping( source = CompanyUserDTO.class, target = CompanyUser.class )
    @SubclassMapping( source = PersonalUserDTO.class, target = PersonalUser.class )
    User toUser(UserDTO userDTO);

    @InheritConfiguration(name = "toUser")
    UserDTO toUserDTO(User user);
}
```

Now, according to the documentation found [here](https://mapstruct.org/documentation/dev/reference/html/#sub-class-mappings), as long as you set the `subclassExhaustiveStrategy` parameter you should be able to return an abstract type form the mapper:

```
In the case that the Fruit is an abstract class or an interface, you would get a compile error.

To allow mappings for abstract classes or interfaces you need to set the subclassExhaustiveStrategy to RUNTIME_EXCEPTION, you can do this at the @MapperConfig, @Mapper or @BeanMapping annotations
```

Unfortunately, it fails with the following error:

```
[ERROR] <redacted>/api/users/UsersMapper.java:[15,10] The return type User is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
```

I have tried removing it from the two subclass' mappers, but no difference. The error is always the same, and either I am not sure if I set everything correctly

cc @Zegveld taking the liberty to tag you since from what I understood you created this

**Comment by Zegveld** [comment]
Hello @pennal,

You are using `@InheritConfiguration` while what you need is the inverse.
```
    @InheritConfiguration(name = "toUser")
    UserDTO toUserDTO(User user);
```

To be honest I have not tested this with `@InheritInverseConfiguration`, so I am curious to see if this works correctly.

**Comment by Zegveld** [comment]
Ok took a closer look, the subclassmappings are currently not inheritable. 
This is because if they would be inherited then you would end up with an infinite loop situation.

But for reverse inheritence we probably should allow it.

This should currently result in an error on the mapping method annotated with `@InheritInverseConfiguration`.
But if I read it correctly you get the error on the method with the `@SubclassMapping` annotations, is that correct?

**Comment by pennal** [comment]
So I tested your suggestion, and I also removed/disabled the builders for all the DTOs and the mappers. So the user mapper looks like this:

```java
@Mapper(componentModel = "spring", subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION, builder = @Builder(disableBuilder = true))
public interface UsersMapper {
    UsersMapper INSTANCE = Mappers.getMapper(UsersMapper.class);

    @SubclassMapping( source = CompanyUserDTO.class, target = CompanyUser.class )
    @SubclassMapping( source = PersonalUserDTO.class, target = PersonalUser.class )
    User toUser(UserDTO userDTO);

    @InheritInverseConfiguration(name = "toUser")
    UserDTO toUserDTO(User user);
}
```
I am now able to generate the mappers for the subclasses without any issues, and the generated code looks perfect. Unfortunately the main problem still persists, it is still complaining that `User` is an interface/abstract.

And yes, you are right, this happens on the method annotated with `@SubclassMapping`. 

Curiously enough, if I remove the subclass annotation the message is still the same. It seems like that annotation is not changing anything in the way the code is generated. Don't know if this helps. Let me know if I can help in any way

**Comment by Zegveld** [comment]
Hmmm can you check that you've also updated the plugin version of the annotation processor?

**Comment by pennal** [comment]
Kinda lost tbh...I am running the 1.5.0.beta2 release through jitpack:

```
<dependency>
    <groupId>com.github.mapstruct</groupId>
    <artifactId>mapstruct</artifactId>
    <version>1.5.0.Beta2</version>
</dependency>
```

How can I check it?

**Comment by pennal** [comment]
In the generated sources it looks like version 1.4.2 is being used:

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-21T17:19:12+0100",
    comments = "version: 1.4.2.Final, compiler: javac, environment: Java 12.0.2 (Oracle Corporation)"
)
```

Any way to double check or force to use the 1.5.0 version?

**Comment by Zegveld** [comment]
That looks like a maven dependency, there should also be one at the maven-compiler-plugin.
looks something like this:
```
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>1.5.0.Beta2</version>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
```

**Comment by pennal** [comment]
Good catch! That did it, thank you so much for your help. Upgrading the annotation processor to the correct version generated the correct code, and I can use it now without issues.

One note though: using `@InheritInverseConfiguration` still resulted in an error, I had to explicitly write the submappings manually. As we previously discussed it would be useful to be able to inherit them, either through the standard annotation or with an ad-hoc one.

Thanks again

**Comment by Zegveld** [comment]
Moved that request to a separate issue, because this one is mostly filled with fixing the version of the annotation processor.

Closing this issue as the main problem has been solved, and the secondary problem is moved to a separate issue.
