### ISSUE TITLE
Allow @InheritInverseConfiguration with @SubclassMappings

### ISSUE THREAD

**Issue by Zegveld** [mapstruct/mapstruct#2696]
using `@InheritInverseConfiguration` results in an error, I had to explicitly write the `@SubclassMapping`s manually. It would be useful to be able to inherit them, either through the standard annotation or with an ad-hoc one.

_Originally posted by @pennal in https://github.com/mapstruct/mapstruct/issues/2695#issuecomment-998924888_

**Comment by filiphr** [comment]
@Zegveld do you think that we should do this in 1.5.0?

**Comment by Zegveld** [comment]
Think that should be manageable. I'll probably have a PR up today for this ;)

**Comment by Zegveld** [comment]
Just noticed that there is a catch:
```
@SubclassMapping( source = SubA.class, target = ParentZ.class )
@SubclassMapping( source = SubB.class, target = ParentZ.class )
```
The above annotations cannot be inverted, because you would end up with:
```
@SubclassMapping( source = ParentZ.class, target = SubA.class )
@SubclassMapping( source = ParentZ.class, target = SubB.class )
```
which basically means that the same source should end up with 2 different targets. There is an exception for this when you write it down as subclass mappings, but this same exception should also take place with `@InheritInverseConfiguration`.

Will add that as well inside this issue.

**Comment by Zegveld** [comment]
Just noticed that there is only a warning for it.
Adding a compiler error for it so that you cannot use the same source class twice for `@subclassMapping`'s.
