### ISSUE TITLE
Provide OSGi-enabled JARs

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#27]
Only really makes sense for the annotation JAR (someone could want to use the `Mappers` factory at runtime).

**Comment by diamondarts** [comment]
Hi Gunnar,

an OSGi-enabled manifest would help. Then I could use the `mapstruct-x.x.x.jar` as a plugin within a local update site and reference it from my projects.

B.

**Comment by gunnarmorling** [comment]
Hi, yes, the manifest would be good to have. Would you like to send a pull request for this? Regarding the buddy header, I'd rather have a solution which works with plain OSGi. Maybe we should add another `getMapper()` method which accepts a class-loader, too? There is also an issue for supporting BluePrint / OSGi services as a component model, which would be my preferred solution in the long run.

**Comment by jvz** [comment]
I'm using MapStruct in OSGi, and using bnd to wrap the JAR worked fine, so just adding the MANIFEST.MF metadata should be enough. You can use it like so:

```xml
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <configuration>
          <instructions>
            <Export-Package>*</Export-Package>
          </instructions>
        </configuration>
      </plugin>
```

You can also slim down the package exports if desired, but I'm not sure if you can without further testing. Exporting everything works as a simple method of doing so even if it's not very OSGi-y.

**Comment by agudian** [comment]
> Exporting everything works as a simple method of doing so even if it's not very OSGi-y.

Good thing is that our API modules are the only stuff you need on the runtime classpath and hence in the bundle, and everything there is supposed to be exported... :)

**Comment by agudian** [comment]
Added OSGi metadata to mapstruct.jar and mapstruct-jdk8.jar.
