### ISSUE TITLE
Expression applied to wrong target

### ISSUE THREAD

**Issue by rbleuse** [mapstruct/mapstruct#2700]
- [x] Is this an issue (and hence not a question)? 

Hello, there's an issue when applying an expression to a target, it's applied to a wrong target attribute.

```kotlin
data class ServiceDto(
    val id: Long,
    val otherId: Long
)

data class Service(
    val id: Long?,
    val otherId: Long
)

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, componentModel = "spring")
abstract class ServiceMapper {

    abstract fun serviceDtoToService(service: ServiceDto): Service

    @Mapping(target = "id", expression = "java(validateId(service.getId()))")
    abstract fun serviceToServiceDto(service: Service): ServiceDto

    fun validateId(id: Long?): Long {
        return id ?: throw InvalidDataException("Service ID cannot be null")
    }
}
```

The generated implementation is :

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-24T11:04:12+0900",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from kotlin-annotation-processing-gradle-1.6.10.jar, environment: Java 17.0.1 (Azul Systems, Inc.)"
)
@Component
public class ServiceMapperImpl extends ServiceMapper {

    @Override
    public Service serviceDtoToService(ServiceDto service) {
        if ( service == null ) {
            return null;
        }

        Long id = null;
        long otherId = 0L;

        id = validateId( service.getId() );
        otherId = validateId( service.getOtherId() ); // <== shouldn't be validated

        Service service1 = new Service( id, otherId );

        return service1;
    }

    @Override
    public ServiceDto serviceToServiceDto(Service service) {
        if ( service == null ) {
            return null;
        }

        long otherId = 0L;

        otherId = validateId( service.getOtherId() ); // <== shouldn't be validated

        long id = validateId(service.getId());

        ServiceDto serviceDto = new ServiceDto( id, otherId );

        return serviceDto;
    }
}
```

I believe `otherId` shouldn't be validated, it's not defined at all in `serviceDtoToService` and it's not the targeted attribute in `serviceToServiceDto`

**Comment by Zegveld** [comment]
It works as expected because of the following:
You have manually defined a mapping from `Long` to `Long` namely the method `validateId`, it will use this mapping for all `Long` to `Long` conversions.

What you can do to have mapstruct use the method as you want is for example the following:
```
    @Mapping( target = "id", qualifiedByName = "validateId" )
    abstract fun serviceToServiceDto(service: Service): ServiceDto

    @Named( "validateId" )
    fun validateId(id: Long?): Long {
        return id ?: throw InvalidDataException("Service ID cannot be null")
    }
```

Hope this helps in getting it working for you.

**Comment by filiphr** [comment]
Closing this, since @Zegveld has explained why this is happening.

**Comment by rbleuse** [comment]
Thank you @Zegveld that's indeed working.
It's a bit confusing that applying an expression still produces a mapping in that case. But qualifiedByName did the trick.

**Comment by filiphr** [comment]
@rbleuse the reason why it is applied is not the expression. The reason why it is applied is because you have provided a mapping from `Long` to `Long` and MapStruct will always use user defined methods with highest priority. As @Zegveld said in order for uer defined methods to not be explicitly used you need to annotate them with `@Named`
