### ISSUE TITLE
ignore mapping for global

### ISSUE THREAD

**Issue by tonycody** [mapstruct/mapstruct#2711]
![image](https://user-images.githubusercontent.com/6773121/147525607-0b3f07d9-3e79-4b4d-b99f-ea3a6b52ec3b.png)

You don't want any of the attributes in the parent class to participate in mapping. Any mapping does not maping.

Provide such support, otherwise @mapping must be specified on every mapping(ignore = true)

In collaborative development, it is easy to forget to set properties that need to be ignored when using subclasses of different parent classes to write different Mappers. Therefore, it is necessary to provide the ability to mark an attribute as mapping globally ignored

**Comment by Zegveld** [comment]
From the options below I believe that the first option `Example 80` contains an example of what you are looking for. 
If it is something else you want, can you then give us an example of how you would configure this in code?

The following options are available for this behavior:

1. what you could do is defining a shared mapper configuration and reference this in your mappers. [See here for more information.](https://mapstruct.org/documentation/stable/reference/html/#shared-configurations)

2. use `@InheritConfiguration`. [See also chapter 11 of the reference guide.](https://mapstruct.org/documentation/stable/reference/html/#mapping-configuration-inheritance)

3. Create custom annotation with your base mappings on it.
For example
```
@Retention( CLASS )
@Target( METHOD )
@Mapping( target = "code", ignore = true)
public @interface BaseResponseMapping {

}
```
then you can apply that to your methods.

**Comment by tonycody** [comment]
您的来信我已收到，我会尽快回复您！！！

    ------------------------------------------------------

**Comment by tonycody** [comment]
It's too complicated and not very flexible.

**Comment by Zegveld** [comment]
Do you have an idea/example of how a less complicated and/or more flexible solution would look like?

**Comment by filiphr** [comment]
Closing this due to lack of response. @Zegveld  already gave options how this can be achieved. If something more needs to be done a custom `AccessorNamingStrategy` can always be implemented.
