### ISSUE TITLE
[Bug] Mapstruct attempts to autogenerate already implemented method

### ISSUE THREAD

**Issue by nbrugger-tgm** [mapstruct/mapstruct#2712]
- [x] Is this an issue (and hence not a question)?

With the following class structure:

![img](https://www.plantuml.com/plantuml/png/LOyn3eCm34NtdC8ZbSe544A8lLiku0Q3eeOOEMuNojqRO4b7-xslR_T9KVIz1EEZaape20PCzC1r9Mbj1vi1sF2PLD3f3YCVoCUviZ09BtSBoZTeuCD-_5UT42fL1xIPkC2HSeh5ppvYkFQxCIvWIZ0mlwxMix98doYBnLtVkYxy1jfZwanFSSo__000)

A problem arises : **`java: Can't generate mapping method with no input arguments.`**

Which is kind of counterintuitive since `create()` was already implemented manually, so mapstruct should ignore it.
The issue originates from the fact that the base method is abstract and mapstruct doesn't understand that it is already implemented in `BookMapper`. 

If I change `BaseMapper#create()` from:
```java
T create();
```
to:
```java
default T create(){
    return null;
}
```
It works fine.

The concerns using this as workaround is
1. The subclasses are not forced to implement `create()`
2. Mapstruct "shouldn't" attempt autogeneration in the first place

**Comment by Zegveld** [comment]
Which of those classes contain the `@Mapper` annotation?

In your example it should only be on the abstract class `BookMapper`, and not on the interface `BaseMapper`.

**Comment by nbrugger-tgm** [comment]
Sorry forgot to add the Information. `BookMapper` is annotated with `@Mapper`

**Comment by Zegveld** [comment]
I'm having trouble with reproducing this scenario.
With both `1.4.2.Final` and `1.5.0.Beta2` this does not occur for me.

I've used the following classes:
BaseMapper:
```
public interface BaseMapper<T, S> {

    T map(S s);

    T createTarget();

    S createSource();
}
```
BookMapper:
```
import org.mapstruct.Mapper;

@Mapper
public abstract class BookMapper implements BaseMapper<BookDto, Book> {

    @Override
    public Book createSource() {
        return new Book();
    }

    @Override
    public BookDto createTarget() {
        return new BookDto();
    }
}

class Book {
    String title;
    // getter & setter
}

class BookDto {
    String title;
    // getter & setter
}
```
Result BookMapperImpl:
```
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-30T23:52:52+0100",
    comments = "version: 1.4.2.Final, compiler: Eclipse JDT (IDE) 1.4.50.v20210914-1429, environment: Java 17.0.1 (Azul Systems, Inc.)"
)
public class BookMapperImpl extends BookMapper {

    @Override
    public BookDto map(Book arg0) {
        if ( arg0 == null ) {
            return null;
        }

        BookDto bookDto = createTarget();

        bookDto.setTitle( arg0.getTitle() );

        return bookDto;
    }
}
```

Can you provide me with a reproduction scenario where it does cause an issue?

**Comment by nbrugger-tgm** [comment]
Hi thanks for your effort, I will try to reproduce it in a little standalone repo. Will probably be done in 2 workdays

**Comment by nbrugger-tgm** [comment]
Hi, I am sorry, but I cannot (reliably) reproduce the issue. It occurs sporadically, but it seems to originate from the build system or caches. Mapstruct itself seems not to be the source of the problem but with the environment. After deleting the maven local caches etc it worked

**Comment by filiphr** [comment]
Thanks for letting us know @nbrugger-tgm. I would suggest updating to the latest maven-compiler-plugin (in case you aren't using it already), maybe that will help
