### ISSUE TITLE
Clarify documentation about builders and lifecycle `@AfterMapping` / `@BeforeMapping` methods

### ISSUE THREAD

**Issue by andye2004** [mapstruct/mapstruct#2719]
This is a heads-up for people using Lombok `@Builder` annotation, IT IS NOT a MapStruct issue so please feel free to close immediately, it will at least then be visible to others via a search.

There was an undocumented change (or at the very least a change that is not clearly explained) In lombok version 1.18.22 which caused us issues in an older project when the Springboot version was bumped to 2.6.2 as it included Lombok at 1.18.22. In effect this change has made visible `@Builder` (and possibly/probably other annotations?) to other annotation processors when these annotations were not previously visible.

What does this (possibly) mean for MapStruct users given that MapStruct now has visibility of the `@Builder` annotation?

If you are using `@AfterMapping` in any mapper to map a Lombok class annotated with `@Builder` AND you are NOT passing the builder (as opposed to the mapping target) into the after mapping method, you're after mapping code will no longer be processed.

For reference, the Lombok PR that included this change is [#2718](https://github.com/projectlombok/lombok/pull/2718) and confirmation of the changed behaviour is given in this issue [#3083](https://github.com/projectlombok/lombok/issues/3083).

Discussion around MapStruct and using builders as arguments to after mapping methods can be found at MapStruct issue #1862 

Hopefully this can help others avoid a day of frustration like we just endured in trying to track this down.

**Comment by Zegveld** [comment]
Think we can add some documentation to `3.8. Using builders` about the way builders interact with `@AfterMapping` and `@BeforeMapping`. What do you think, @filiphr and @sjaakd ?

**Comment by filiphr** [comment]
We already have something in the [12.2. Mapping customization with before-mapping and after-mapping methods](https://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after) section of the documentation about this.

In the end of that section there is an important section saying:

>when using a builder, the `@AfterMapping` annotated method must have the builder as `@MappingTarget` annotated parameter so that the method is able to modify the object going to be build. The `build` method is called when the `@AfterMapping` annotated method scope finishes. MapStruct will not call the `@AfterMapping` annotated method if the real target is used as `@MappingTarget` annotated parameter.

However, if you think that this is not enough feel free to add a PR that clarifies this.

**Comment by AnakinPt** [comment]
I just hit my head into a wall for many hours with this problem. I have the entity created having Lombok and had my abstract class with @Context and had the @AfterMapping and the @MappingTarget with the entity. I did not understood why the @AfterMapping wasn't being called just because MapStruct found a Builder. The documentation, even being there, that's a strange behaviour why we need to add the builder to the mapping target becasue we only refer the concrete object.
For now, I solved my problem by adding the builder attribute to the @Mapper annotation to ignore builders.

**Comment by savinov** [comment]
Another case with issue:

### given
- mapstruct 1.4.2.Final
- POJO with default value for field

### when
lombok 1.18.20

### then
@Mapper uses POJOs constructor -> field gets declared default value from POJO class

### when
- lombok 1.18.22

### then
@Mapper uses POJOs builder -> field doesn't get declared default value from POJO class but JVM default value (0, false or null)
