### ISSUE TITLE
Custom EnumTransformationStrategy is not loaded 

### ISSUE THREAD

**Issue by emw7** [mapstruct/mapstruct#2739]
Configuration mapstruct 1.4.2.Final + lombok 1.18.22 + java 8

Created a custom enum transformation strategy
```
public class LowerHypenEnumTransformationStrategy implements EnumTransformationStrategy {

  @Override
  public String getStrategyName() {
    return "lowerhypen";
  }

  @Override
  public String transform(String value, String configuration) {
    return (value == null) ? value : value.toLowerCase(Locale.ROOT).replace('_', '-');
  }

}
```

Registered in `META-INF/services/org.mapstruct.ap.spi.EnumTransformationStrategy`:
`<omitted>.util.dto.mapstruct.LowerHypenEnumTransformationStrategy`

If I load with ServicesLoader:
```
    ServiceLoader<EnumTransformationStrategy> services =
        ServiceLoader.load(EnumTransformationStrategy.class);
```
I can see it:
`<omitted>.util.dto.mapstruct.LowerHypenEnumTransformationStrategy=<omitted>.util.dto.mapstruct.LowerHypenEnumTransformationStrategy@2d3ed950
`

But if in mapper method is annotated with:
```
  @EnumMapping(nameTransformationStrategy = "lowerhypen")
  public StateResponse map(final StateResult stateResult);
```
compilation rises following error:
`Mapper.java:[78,3] There is no registered EnumTransformationStrategy for 'lowerhypen'. Registered strategies are: prefix, stripPrefix, stripSuffix, suffix.`

**Comment by Zegveld** [comment]
Did you place the EnumTransformationStrategy in a separate jar and added it to the annotation processor classpath?

> To use a custom SPI implementation, it must be located in a separate JAR file together with the file META-INF/services/org.mapstruct.ap.spi.EnumTransformationStrategy with the fully qualified name of your custom implementation as content (e.g. org.mapstruct.example.CustomEnumTransformationStrategy). This JAR file needs to be added to the annotation processor classpath (i.e. add it next to the place where you added the mapstruct-processor jar).

We need to place this documentation at a more generic location, instead of repeating it at the end of only the first 2 chapters of [using SPI](https://mapstruct.org/documentation/stable/reference/html/#using-spi)

**Comment by emw7** [comment]
Thank you @Zegveld, I missed to add external jar in the path. I solved adding
```
    <path>
        <groupId>com.acme</groupId>
        <artifactId>commons</artifactId>
        <version>${com.acme.commons.version}</version>
    </path>
```
to `<annotationProcessorPaths/>` in the `pom.xml`:
```
<annotationProcessorPaths>
    <path>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
    </path>
    <path>
        <groupId>com.acme</groupId>
        <artifactId>commons</artifactId>
        <version>${com.acme.commons.version}</version>
    </path>
    <path>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct-processor</artifactId>
        <version>${org.mapstruct.version}</version>
    </path>
</annotationProcessorPaths>
```

But right now my strategy is not used, maybe I misunderstood the transformation strategy scope: I'm trying to convert enum constant to string
```
@Value
public class StateResponse {
    private String state;
}

@Value
public class StateResult {

    public static enum State {
        ENABLED, NOT_ENABLED;
    }

    private State state;
}
```

But after mapping StateResult to StateResponde I obtain either 
```
{
    "state": "ENABLED"
}
```
or
```
{
    "state": "NOT_ENABLED"
}
```
while I would like to get either
```
{
    "state": "enabled"
}
```
or
```
{
    "state": "not-enabled"
}
```

There is some issue or enum tranformation strategy are not used for enum to string mapping?

**Comment by Zegveld** [comment]
I ran into the same issue when I tried to use it myself. But when I ran `mvn compile` it did use the designated enum transformation strategy, while the eclipse IDE couldn't find it.
Finally figured out what was missing:
![Screenshot from 2022-02-02 19-10-11](https://user-images.githubusercontent.com/41897697/152212582-e3047160-ed17-43cd-9e33-23ea9749feef.png)
It wasn't listed in the factory path, after adding it there it worked.

Strategies are not used unless specified. I ended up with the following test case:
```
@Mapper
public interface EnumMapper {

    @EnumMapping( nameTransformationStrategy = "lowerhypen", configuration = "requires something inside" )
    String from(Test test);
}

enum Test {
    VALUE_1, VALUE_2
}
```
which resulted in
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-02-02T19:09:10+0100",
    comments = "version: 1.4.2.Final, compiler: Eclipse JDT (IDE) 1.4.50.v20210914-1429, environment: Java 17.0.1 (Azul Systems, Inc.)"
)
public class EnumMapperImpl implements EnumMapper {

    @Override
    public String from(Test test) {
        if ( test == null ) {
            return null;
        }

        String string;

        switch ( test ) {
            case VALUE_1: string = "value-1";
            break;
            case VALUE_2: string = "value-2";
            break;
            default: throw new IllegalArgumentException( "Unexpected enum constant: " + test );
        }

        return string;
    }
}
```

**Comment by Zegveld** [comment]
@emw7, did you succeed in getting it to work?
