### ISSUE TITLE
BeanCurrentlyInCreationException with Spring Boot 2.6 and Circular References

### ISSUE THREAD

**Issue by AnWeber** [mapstruct/mapstruct#2741]
After upgrading to Spring Boot 2.6.3, a BeanCurrentlyInCreationException may occur. This is triggered when two mappers reference each other and thus form a circle

```
@Mapper( componentModel = "spring",  uses = { FooMapper.class })
public interface BarMapper {
    Bar toBo(BarDto dto);
    BarDto toDto(Bar obj) ;
}
```
```
@Mapper( componentModel = "spring",  uses = { BarMapper.class })
public interface ForMapper {
    Foo toBo(FooDto dto);
    FooDto toDto(Foo obj) ;
}
```
Circle detection is a change from [Spring Boot 2.6 (Release Notes)](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#circular-references-prohibited-by-default). Currently there is also a possibility to work around the problem by setting `spring.main.allow-circular-references=true`. 

A better way would be to work around the problem using [@Lazy Annotation](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Lazy.html). Is it possible to extend the SpringComponentProcessor to enable [@Lazy](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Lazy.html) autowire support?

[example.zip](https://github.com/mapstruct/mapstruct/files/7994987/test.zip)

**Comment by filiphr** [comment]
There is a reason why the Spring team decided to not allow circular references by default. I don't think that it is the job of MapStruct to circumvent those issues and allow people using `@Lazy`. If you really need to use circular references you can always use an abstract class and do the injection on your own and add `@Lazy` to the injected mapper.

I am going to close this since we don't want to add support for `@Lazy` currently.

**Comment by AnWeber** [comment]
What are the reasons against using `@Lazy`. Can you possibly give me further documentation. I would like to understand the disadvantages of `@Lazy` in this case.

**Comment by filiphr** [comment]
Form the `@Lazy` javadoc

>Please note that such a lazy-resolution proxy will always be injected; if the target dependency does not exist, you will only be able to find out through an exception on invocation. As a consequence, such an injection point results in unintuitive behavior for optional dependencies

I know that for MapStruct there are no optional dependencies, but if anything is incorrectly configured, e.g. your injected mapper is not annotated with the correct component model then you will only see this when you invoke the mapping. If `@Lazy` is not used then the application will not boot up. This leads to problems that make it difficult to figure our why something isn't working. I've had my fair share of problems when using `@Lazy`. 

Using `@Lazy` means an additional performance impact as now every single invocation needs to go through an additional proxy, perhaps this is negligible, but it is there.

I saw that you did some repo that is adding a `SpringLazyComponentModelProcessor`, doing it on your own is always OK. You can also add your own component model e.g. `springLazy` and decide on your own that you want to use lazy injection for your fields.

**Comment by AnWeber** [comment]
@filiphr thanks for the additional explanation. I am familiar with the problem of lazy initialization. Would it make sense that the SpringLazyComponentProcessor becomes part of Mapstruct. Otherwise I would just publish it as a standalone jar on Maven Central?

**Comment by mshima** [comment]
What about a SETTER value at InjectionStrategy

Setter is the recommended approach for circular injections.
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-dependency-resolution

**Comment by valh1996** [comment]
Could someone give a concrete good workaround please?

**Comment by AnWeber** [comment]
https://github.com/AnWeber/mapstruct-springlazy describes my workaround.

**Comment by valh1996** [comment]
> https://github.com/AnWeber/mapstruct-springlazy describes my workaround.

Thanks but i got this error: `[WARNING] Missing POM for com.github.anweber:mapstruct-springlazy:jar:1.0.0`

Here is my configuration:

```
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<configuration>
				<source>${java.version}</source>
				<target>${java.version}</target>
				<annotationProcessorPaths>
					<path>
						<groupId>org.mapstruct</groupId>
						<artifactId>mapstruct-processor</artifactId>
						<version>${org.mapstruct.version}</version>
					</path>
					<path>
						<groupId>com.github.anweber</groupId>
						<artifactId>mapstruct-springlazy</artifactId>
						<version>1.0.0</version>
					</path>
					<path>
						<groupId>org.projectlombok</groupId>
						<artifactId>lombok</artifactId>
						<version>${org.projectlombok.version}</version>
					</path>
					<path>
						<groupId>org.projectlombok</groupId>
						<artifactId>lombok-mapstruct-binding</artifactId>
						<version>${lombok-mapstruct-binding.version}</version>
					</path>
					<dependency>
						<groupId>org.hibernate</groupId>
						<artifactId>hibernate-jpamodelgen</artifactId>
						<version>${hibernate-jpamodelgen.version}</version>
					</dependency>
				</annotationProcessorPaths>
			</configuration>
		</plugin>
	</plugins>
</build>
```

**Comment by AnWeber** [comment]
I had a typo. I was expecting to be able to publish to Maven Central using `com.github.anweber`. But I had to change it to `io.github.anweber`. I adjusted the README and tried it once with Gradle.
