### ISSUE TITLE
Record polymorphism is not supported

### ISSUE THREAD

**Issue by CyberpunkPerson** [mapstruct/mapstruct#2742]
Hi MapStruct team!

Faced with issue during record composition.

```
public interface SomeInterface {
    Something something();
}
```

```
record SomeThing(Something something) implements SomeInterface {
}
```

```
  @Mapping(target = "another", source = "something")
  SomethingAnother toSomethingAnother(SomeInterface someInterface);
```

Leads to  - _The type of parameter_ `SomeInterface` _has no property named_ `something`.

Best regards,
Andrew

**Comment by Zegveld** [comment]
Indeed there is no property `something` on the `interface`, there is a method `something`.
a property called `something` would be accessed with `getSomething` according to the JavaBean-spec to which is referred in the documentation.
`record`'s have their own spec, but an `interface` follows the JavaBean-spec.

>The property name as defined in the [JavaBeans specification](http://www.oracle.com/technetwork/java/javase/documentation/spec-136004.html) must be specified in the @Mapping annotation, e.g. seatCount for a property with the accessor methods getSeatCount() and setSeatCount().

If you want to use different Accessor methods then you would need to use a different `AccessorNamingStrategy`. [See here for more information about custom `AccessorNamingStrategy`'s.](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy)

A solution without changing the `AccessorNamingStrategy` would be to use the following interface:
```
public interface SomeInterface {
    Something something();
    default Something getSomething(){
        return something();
    }
}
```

**Comment by CyberpunkPerson** [comment]
Hi @Zegveld 

Thanks for the answer.
My mistake I forgot about following of JavaBean-spec on interface level.

Best regards,
Andrew
