### ISSUE TITLE
Ignored unknown source property error, but property exist.

### ISSUE THREAD

**Issue by Trafo** [mapstruct/mapstruct#2743]
From my perspective, I found a bug, because of the inconsistent behaving of ```ignoreUnmappedSourceProperties```.

I defined these classes:
```
data class Inside(val value : String)
data class InsideDto(val value : String)
data class Problem(val problem : String)
data class ProblemDto(val problem : String)
data class Outside(val inside : Inside, val problem : Problem)
data class OutsideDto(val insideDto : InsideDto, val problem : ProblemDto)
```

Inside of a Mapper which has this Config:
```
@MapperConfig(
    componentModel = "spring",
    unmappedSourcePolicy = ReportingPolicy.ERROR,
    unmappedTargetPolicy = ReportingPolicy.ERROR
)
```

I declared:
```
@Mapper(config = MapstructConfig::class)
interface Converter {
    @BeanMapping(ignoreUnmappedSourceProperties = ["inside"])
    fun test(
        outside: Outside,
        insideDto: InsideDto
    ): OutsideDto
}
```

this throws the following error:
```error: Ignored unknown source property: "inside". public abstract [placeholder].OutsideDto test(@org.jetbrains.annotations.NotNull```

I found a workaround. I just have to add an extra mapper declaration inside of my Converter for the Problem mapping:
```
fun solution(problem: Problem) : ProblemDto
```

In this case, everything works. For me, this looks like a bug, because it is not consistent behaviour.

**Comment by Zegveld** [comment]
Could you test what it says if you would use `outside.inside` instead of `inside` in the `ignoreUnmappedSourceProperties`?
Because you have 2 sources I believe that you need to also specify the source in which the property resides.
[See also the explanation about mapping with several source parameters.](https://mapstruct.org/documentation/dev/reference/html/#mappings-with-several-source-parameters)

**Comment by filiphr** [comment]
I don't think that we support nested properties in `ignoreUnmappedSourceProperties`, this is part of #2562. The rest what @Zegveld stands.

**Comment by tiger-seo** [comment]
I have the same problem as @olivierboudet; it looks like BeanMapping is propagating `ignoreUnmappedSourceProperties` down to nested properties if they don't have an explicit mapping method

**Comment by trinimon** [comment]
I can confirm the issue from @olivierboudet as well. Version `1.4.2.Final` worked well for me (Dropwizard application with Lombok 1.18.24, Gradle). After upgrading it to `1.5.2.Final` I was facing the same error messages.

**Comment by WeihmannTNG** [comment]
After Upgrade from 1.4.2.FINAL to 1.5.2.FINAL, I have the same problem. For the sake of completeness, here is a minimal example:
The source dto:
`
@Getter
@Setter
public class SrcDto {
  private int number;
  private SrcField field;
}
`
Its field:
`
@Getter
@Setter
public class SrcField {
	private int x;
}
`

The target dto:
`
@Getter
@Setter
public class TargetDto {
  private int number;
  private TargetField field;
}
`

Its field:
`
@Getter
@Setter
public class TargetField {
	private int x;
}
`

The mapper:
`
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR, unmappedTargetPolicy = ReportingPolicy.ERROR)
public abstract class TheMapper {
	@Mapping(target = "number", ignore = true)
	@BeanMapping(ignoreUnmappedSourceProperties = { "number" })
	abstract TargetDto map(final SrcDto backendDto);
}
`

**Comment by filiphr** [comment]
Thanks for @olivierboudet and @WeihmannTNG for your examples. You are both right. We shouldn't inherit the bean mappings onto the forged methods. We've created PR #3005 that should fix this

**Comment by foal** [comment]
Is it really fixed in 1.5.3 (@filiphr)? I have updated to 1.5.3 and see multiple errors "Ignored unknown source property" on remove I see "Unmapped source properties" with same names....

**Comment by foal** [comment]
I see this error after update to 1.5.3 fot the nested properties

**Comment by WeihmannTNG** [comment]
> I see this error after update to 1.5.3 fot the nested properties

It may make sense to open a new issue together with a minimal example.
