### ISSUE TITLE
[1.5.0.Beta2] `conditionExpression` sets target value to `null` instead of ignoring it

### ISSUE THREAD

**Issue by zeroinformatique** [mapstruct/mapstruct#2757]
I need to set the target value conditionally.

```java
@Mapping(target = "address", conditionExpression = "java(!Address.equalsFullAddress(form.getAddress(),contact.getAddress()))")
void map(Form form, @MappingTarget Contact contact);
```

The documentation states that it will generates a `if` for the setter, which is what I need. But the code is actually this:

```java
if (!Address.equalsFullAddress(form.getAddress(),contact.getAddress()))
  contact.setAddress(form.getAddress());
else
  contact.setAddress(null);
```

Since this is a `@MappingTarget`, the idea was to never set the `address` field if the expression was false; but it still sets it to `null`.

The code generated should be:

```java
if (!Address.equalsFullAddress(form.getAddress(),contact.getAddress()))
  contact.setAddress(form.getAddress());
```

**Comment by Zegveld** [comment]
The condition expression replaces the null check. Set the nullValuePropertyMappingStrategy to IGNORE, [see here for more information.](https://mapstruct.org/documentation/dev/reference/html/#mapping-result-for-null-properties)

**Comment by zeroinformatique** [comment]
I still want `null` values to be set to null, tho. I just want the mapping to be disabled if the condition is false.

**Comment by Zegveld** [comment]
Here is a full explanation of what I mentioned earlier:

Normally with an update mapper you get the following code generated for fields:
```
if ( source.getField() != null ) {
    target.setField( source.getField() );
} else {
    target.setField( null );
}
```

With a condition it will turn into this:

```
if ( conditionCheck( source.getField() ) ) {
    target.setField( source.getField() );
} else {
    target.setField( null );
}
```

With the nullValuePropertyMappingStrategy set to IGNORE and no condition you get this:

```
if ( source.getField() != null ) {
    target.setField( source.getField() );
}
```

With the nullValuePropertyMappingStrategy set to IGNORE and a condition you get this:

```
if ( conditionCheck( source.getField() ) ) {
    target.setField( source.getField() );
}
```

So if in this case your `conditionCheck( source.getField() )` is true, but `source.getField()` returns null, the `target.setField( source.getField() )` is called with null.

**Comment by zeroinformatique** [comment]
Thanks for your detailed answer.
That make sense, I understand the code logic now.

I still have the feeling something's off functionally; not technically, since obviously your trick works.

The solution is probably to update the documentation  for `conditionExpression` to reflect all this.

**Comment by Zegveld** [comment]
The documentation is not updated yet with the 1.5.0.Beta2, but with the next release there is already additional documentation about combining the update mapper with conditions. [See this merged PR for more information.](https://github.com/mapstruct/mapstruct/pull/2740/files)

**Comment by Zegveld** [comment]
Closing this issue.
The javadoc will stay the same, but the reference html documentation will have it covered. Due to the fact that for normal mappings vs update mappings the behavior mentioned here is different.
