### ISSUE TITLE
MapStruct does not work properly with Lombok @Data or @Getters and @Setter annotation

### ISSUE THREAD

**Issue by briandee** [mapstruct/mapstruct#2767]
mapstruct in combination with Lombok, is unable to correctly resolve mappings specified as property fields only, when correctly annotated with Lombok annotations @Data or more verbosely using @Setter and @Getter only.  Except getters and setter are also provided  to the source and target classes. the @Mapping annotation will not work.

This can be reproduced using Lombok version specified in the example gradle snippet, but also same problem exists in mapstruct **1.4.2.Final**. The code I produced works because of the getters and setters added to the Source and Target classes. However, if the setters and getters are removed, the code no longer works. The error is that the field pValue does not exist in the Source object

ext {
    **mapstructVersion = "1.5.0.Beta2"
    lombokVersion = "1.18.20"
    lombokMapstructBindingVersion = "0.2.0"**
}

**sourceCompatibility = JavaVersion.VERSION_1_8**

dependencies {
    implementation "org.mapstruct:mapstruct:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}"
    testImplementation 'junit:junit:4.13.1'

    /*
        this example uses lombok directly over the annotationProcessor,
        the io.freefair.lombok plugin works as well.
        The freefair-lombok plugin is used in the example mapstruct-on-gradle-testcp-with-lombok
     */
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}", "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"
}

Here is an example taken directly from the mapstruct examples project mapstruct-lombok with one minor addition. Here is the mapper code:

          import org.mapstruct.Mapper;
          import org.mapstruct.Mapping;
          import org.mapstruct.factory.Mappers;
          
          import com.mycompany.dto.Source;
          import com.mycompany.entities.Target;
          
          @Mapper
          public interface SourceTargetMapper {
          
              SourceTargetMapper MAPPER = Mappers.getMapper( SourceTargetMapper.class );
          
              @Mapping( source = "test", target = "testing" )
              @Mapping( source = "pValueSet", target = "pValue" )
              Target toTarget( Source s );
          }

Here is the code for the Source class :
                import lombok.Data;
                
                @Data
                public class Source {
                
                    private String test;
                    private Boolean pValueSet;
                
                
                    public Boolean getpValueSet() {
                        return pValueSet;
                    }
                
                    public void setpValueSet(Boolean pValueSet) {
                        this.pValueSet = pValueSet;
                    }
                
                }
Here is the code for the Target class:

                /*
                 * Copyright MapStruct Authors.
                 *
                 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
                 */
                package com.mycompany.entities;
                import lombok.Data;
                
                @Data
                public class Target {
                
                    private Long testing;
                    private Boolean pValue;
                
                    public Boolean getpValue() {
                        return pValue;
                    }
                
                    public void setpValue(Boolean pValue) {
                        this.pValue = pValue;
                    }
                }

Finally here is the test code:

                          package com.mycompany.mapper;
                          
                          import static org.junit.Assert.assertEquals;
                          
                          import org.junit.Test;
                          
                          import com.mycompany.dto.Source;
                          import com.mycompany.entities.Target;
                          
                          public class SourceTargetMapperTest {
                          
                              @Test
                              public void testMapping() {
                                  Source s = new Source();
                                  s.setTest( "5" );
                                  s.setpValueSet(true);
                          
                                  Target t = SourceTargetMapper.MAPPER.toTarget( s );
                                  assertEquals( 5, (long) t.getTesting() );
                                  assertEquals( true, (Boolean) t.getpValue());
                                  System.out.println("Passed!");
                              }
                          }

**Comment by briandee** [comment]
Not an issue. Capitalizing the first letter fixes it without providing setter and getter

**Comment by abishai53** [comment]
Capitalize the first letter of what?

**Comment by filiphr** [comment]
The first letter of the field @abishai53 e.g. `PValue` instead of `pValue`

**Comment by abishai53** [comment]
@filiphr capitalize them in the class or in the mapping annotation. I ask because I don't normally use the annotation since my field names match.

**Comment by filiphr** [comment]
I think in the `@Mapping`, but try both

**Comment by MohsenRezaeii** [comment]
I have answered the question here: https://stackoverflow.com/questions/66170469/java-no-implementation-was-created-for-productmapper-due-to-having-a-problem-in/79457037#79457037
