### ISSUE TITLE
support custom global mapping value defaults

### ISSUE THREAD

**Issue by grexe** [mapstruct/mapstruct#2770]
I am using MapStruct to map some input data from a schema we don't control to our domain model.
Now insteaf of cleanly sending us `null` values for non-existing fields, the source system sometimes (!) sends a custom string, e.g. `#NODATA#`.

I would like to intercept mapping to *always* map this value to e.g. `null` so we can cleanly validate our domain model later, so for *ever* field (of a specific type), I want to define e.g. an interface default method like:
```
@DefaultMapping
default String convertInput(String input) {
    if (input.equals("#NODATA#") {
        return null;
    }
    return input;
}
```

I only found this, but it only controls null checking:
https://mapstruct.org/documentation/stable/reference/html/#checking-source-property-for-null-arguments

I would need a similar mechanism that can be customized to translate custom values to null.

Using latest MapStruct 1.4.2.Final with Java and Maven in a spring-boot project.

**Comment by Zegveld** [comment]
With mapstruct `1.5.0` currently at `1.5.0.Beta2` you can use `@Condition` annotation. If there would have been a null-check then this will replace it, otherwise it will be checked before attempting to set the value.

Hope this will work for your situation.

Example:
```
@Condition
default boolean shouldMap( String input ) {
    return input != null && !input.equals( "#NODATA#" );
}
```

property mapping code will now be something like:
```
if ( shouldMap( source.getSomeField() ) {
    target.setSomeField( source.getSomeField() );
}
```
instead of
```
target.setSomeField( source.getSomeField() );
```
if the property would have been a `String`.

**Comment by grexe** [comment]
thanks for the quick reply @Zegveld - this would indeed cover my specific use case, but since it's only a boolean conditional check without allowing you to return a String, it would not allow for a generic solution where you could establish a specific default mapping behavior, e.g. always map '#NODADA#' to an empty String or "n/a", to stay with my original example.

Would this be something for 1.5.x?

**Comment by Zegveld** [comment]
Now that I think of it, you can always create a String to String mapping method for that.
```
default String map(String input) {
    return input != null && !input.equals( "#NODATA#" ) ? input : "n/a"
}
```

**Comment by grexe** [comment]
You're totally right! I forgot MapStruct's reflection magic auto-detects suitable methods for mapping fields it encounters!
Thanks a lot, will try that tomorrow... Would clean up my code a lot...

**Comment by filiphr** [comment]
What @Zegveld proposed will make all string to string mappings go through your new method. In case you only want to do that for some mappings you can qualify it.

e.g.
```
@Mapping(target = "someField", qualifiedByName = "noDataString")
Target map(Source source);

@Named("noDataString")
default String map(String input) {
    return input != null && !input.equals( "#NODATA#" ) ? input : "n/a"
}
```

Closing this since it has been answered.
