### ISSUE TITLE
MapStruct stopped generating field assigment code

### ISSUE THREAD

**Issue by ViRGiL175** [mapstruct/mapstruct#2772]
Hello. I have an issues with generated code. 

Firstly, thank you for this library. 
It seems very convenient and elegantly simple, so I decied to add it to my Spring Boot project.

First period of time it works perfectly, so I started adding Mapping interfaces for different models etc.
But after some time my tests breaks. I started investigation.

I noticed that sometimes, after project building, Mapper implementations generating without any field assigments.

<details><summary>It looks like this:</summary>
<p>

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-02-27T23:24:30+0400",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.4.jar, environment: Java 17.0.2 (Oracle Corporation)"
)
@Component
public class ChatMapperImpl implements ChatMapper {

    @Override
    public ChatDto toDto(Chat entity) {
        if ( entity == null ) {
            return null;
        }

        ChatDto chatDto = new ChatDto();

        return chatDto;
    }

    @Override
    public Chat toEntity(ChatDto dto) {
        if ( dto == null ) {
            return null;
        }

        Chat chat = new Chat();

        return chat;
    }
}
```

</p>
</details>

I updated Gradle to 7.4, read more reference docs, added Lombok mapper, tested 1.5.0 beta of MapStruct, updates Spring Boot to 2.6.4, cleaning IDEA caches.
Nothing helps. And finally even for simplest models there are no fields assigment code generated.

<details><summary>I enabled verbose logging for MapStruct, but it not indicates any warnings:</summary>
<p>

```
23:47:31: Executing ':classes :testClasses'...


> Task :compileJava
Note: MapStruct: Using accessor naming strategy: org.mapstruct.ap.spi.DefaultAccessorNamingStrategy
Note: MapStruct: Using builder provider: org.mapstruct.ap.spi.DefaultBuilderProvider
Note: MapStruct: Using enum naming strategy: org.mapstruct.ap.spi.DefaultEnumMappingStrategy
Note:  MapStruct: processing: ru.virgil.server.domain.message.MessageMapper.
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.message.MessageDto toDto(ru.virgil.server.domain.message.Message entity).
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.message.Message toEntity(ru.virgil.server.domain.message.MessageDto dto).
Note:  MapStruct: processing: ru.virgil.server.domain.chat.ChatMerger.
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.chat.Chat merge(@MappingTarget ru.virgil.server.domain.chat.Chat serverEntity, ru.virgil.server.domain.chat.Chat deltaEntity).
Note:  MapStruct: processing: ru.virgil.server.domain.user.PrivateUserDetailsMapper.
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.user.PrivateUserDetailsDto toDto(ru.virgil.server.domain.user.PrivateUserDetails entity).
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.user.PrivateUserDetails toEntity(ru.virgil.server.domain.user.PrivateUserDetailsDto dto).
Note:  MapStruct: processing: ru.virgil.server.domain.hint.HintMapper.
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.hint.HintDto toDto(ru.virgil.server.domain.hint.Hint entity).
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.hint.Hint toEntity(ru.virgil.server.domain.hint.HintDto dto).
Note:  MapStruct: processing: ru.virgil.server.domain.chat.ChatMapper.
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.chat.ChatDto toDto(ru.virgil.server.domain.chat.Chat entity).
Note: - MapStruct: creating bean mapping method implementation for ru.virgil.server.domain.chat.Chat toEntity(ru.virgil.server.domain.chat.ChatDto dto).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :processResources UP-TO-DATE
> Task :classes
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

BUILD SUCCESSFUL in 4s
3 actionable tasks: 2 executed, 1 up-to-date
23:47:36: Execution finished ':classes :testClasses'.

```

</p>
</details>

In short, server have Spring Boot with security, web, jpa, conf processor, actuator and thymeleaf starter packs, Tika, Lombok, Firebase Admin, Google Truth for assertions and postgres.

<details><summary>My models in short:</summary>
<p>

```
@Mapper
interface TestMapper {

    TestDto toDto(Test entity);

    Test toEntity(TestDto dto);

}

@Data
@MappedSuperclass
class BaseEntity {

    @GeneratedValue
    @Id
    private UUID uuid;

}

@Entity
@EqualsAndHashCode(callSuper = true)
@Data
@NoArgsConstructor
public class Test extends BaseEntity {

    private int testInt;
    private String testString;

}

@Data
@NoArgsConstructor
class TestDto {

    private int testInt;
    private String testString;

}

```

</p>
</details>

My compiler args:
```
compileJava {
    options.compilerArgs += [
            '-Amapstruct.defaultComponentModel=spring',
            '-Amapstruct.verbose=true',
    ]
}
```

And now I'm fully stuck with this behaviour. 
All I can say that before assigment stopped generating I experimented with `nullValueMappingStrategy` and other null functions.

**Comment by ViRGiL175** [comment]
There is generated code for my "models in short":

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-02-28T00:15:39+0400",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.4.jar, environment: Java 17.0.2 (Oracle Corporation)"
)
@Component
class TestMapperImpl implements TestMapper {

    @Override
    public TestDto toDto(Test entity) {
        if ( entity == null ) {
            return null;
        }

        TestDto testDto = new TestDto();

        return testDto;
    }

    @Override
    public Test toEntity(TestDto dto) {
        if ( dto == null ) {
            return null;
        }

        Test test = new Test();

        return test;
    }
}

```

**Comment by Zegveld** [comment]
What do the `Test`, `TestDto` and `TestMapper` class look like?

**Comment by filiphr** [comment]
@ViRGiL175 I see that you are using Lombok, have you added the `lombok-mapstruct-binding` as explained in our [FAQ](https://mapstruct.org/faq/#Can-I-use-MapStruct-together-with-Project-Lombok) and our [lombok example](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok)?

**Comment by ViRGiL175** [comment]
> @ViRGiL175 I see that you are using Lombok, have you added the `lombok-mapstruct-binding` as explained in our [FAQ](https://mapstruct.org/faq/#Can-I-use-MapStruct-together-with-Project-Lombok) and our [lombok example](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok)?

Yes, sorry, I was sleepy yesterday, and misnamed `lombok-mapstruct-binding` "Lombok mapper". I tried version 0.1.0, 0.2.0, no effect. @filiphr 

```
    implementation "org.mapstruct:mapstruct:1.4.2.Final"
    annotationProcessor "org.mapstruct:mapstruct-processor:1.4.2.Final"
    implementation "org.projectlombok:lombok-mapstruct-binding:0.2.0"
```

> What do the `Test`, `TestDto` and `TestMapper` classes look like?

```
@Mapper
interface TestMapper {

    TestDto toDto(Test entity);

    Test toEntity(TestDto dto);

}

@Data
@MappedSuperclass
class BaseEntity {

    @GeneratedValue
    @Id
    private UUID uuid;

}

@Entity
@EqualsAndHashCode(callSuper = true)
@Data
@NoArgsConstructor
public class Test extends BaseEntity {

    private int testInt;
    private String testString;

}

@Data
@NoArgsConstructor
class TestDto {

    private int testInt;
    private String testString;

}
```

In my first message huge code blocks is hidden in collapsing blocks for convenience. @Zegveld

**Comment by ViRGiL175** [comment]
> the lombok-mapstruct-binding should be `annotationProcessor` instead of `implementation` I think:
> 
> ```
>     annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'
>     annotationProcessor 'org.projectlombok:lombok:1.18.20'
>     annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
> ```

Yes )

<img width="603" alt="image" src="https://user-images.githubusercontent.com/11541555/155946899-c9fac5a5-ff48-4a0d-babe-81408c738385.png">

You are my hero, looks like it generating code again. 

It is those little things falling out of your attention after uncountable attempts of fixing all back. First period time it even worked without `mapstruct-processor`, i'm just didn't know about it when firstly trying Map Struct.

I will try to integrate library to my server further, but I think problem is resolved for now, thank you all.

**Comment by himbo22** [comment]
> the lombok-mapstruct-binding should be `annotationProcessor` instead of `implementation` I think:
> 
> ```
>     annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'
>     annotationProcessor 'org.projectlombok:lombok:1.18.20'
>     annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
> ```

thank you <3 <3
