### ISSUE TITLE
Hibernate lazy loading aware mapping

### ISSUE THREAD

**Issue by reitzmichnicht** [mapstruct/mapstruct#2776]
I think a common problem when using mapstruct for mapping entities to DTOs is that it might produce lazy loading of relations. So in case of different entity fetch graphs you would need different mapping methods that explicitly ignore the lazy loaded stuff and only map the eager loaded properties.
Luckily Hibernate allows to determine on its generated proxy entities if a property is eager or lazy loaded. So the idea is to extend mapstruct with a strategy to only map eager loaded properties by default.

I would be happy to contribute this, the question is where is the best place to extend this behaviour. To be honest the mapstruct architecture doesn't look very extendable for such use cases to provide custom mapping strategies.

Kind regards,
Michael

**Comment by gunnarmorling** [comment]
Might be doable by providing a custom [ModelElementProcessor](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/ModelElementProcessor.java) which removes any lazy properties from the mapper model? Though @filiphr may know of a more specific extension point tailored for that use case.

**Comment by filiphr** [comment]
I think that this can easily be achieved with the new `@Condition` support that we have. I really didn't want to advertise this possibility for hibernate lazy loaded stuff but here we go.

With the new [Conditional Mapping](https://mapstruct.org/documentation/dev/reference/html/#conditional-mapping) you can write your own conditional method for checking whether a collection needs to be mapped.

e.g.

```
@Mapper(uses = HibernateCollectionUtils.class)
public interface MyMapper {

    Target map(Source source);

}


pubic class HibernateCollectionUtils {

    @Condition
    public static <T> boolean isCollectionAvailable(Collection<T> collection) {
        if (collection == null) {
            return false;
        }

        // Write the hibernate logic for checking if a collection is loaded or not
    }

}
```

This would be done during runtime. If you are looking to explicitly ignore certain things, by not even generating this code then currently writing a custom `ModelElementProcessor` like @gunnarmorling proposed is one way. Alternative way would be to implement a custom `AccessorNamingStrategy` that would return a different `MethodType` when calling `AccessorNamingStrategy#getMethodType` in case the method is for a lazy loaded property. Implementing the `AccessorNamingStrategy` would mean that from the point of view of MapStruct the lazy property doesn't even exist in the source type.

**Comment by reitzmichnicht** [comment]
This filtering is fine during runtime, so this looks great. Thanks for pointing into the right direction, will try this out and post an example here.

**Comment by Aytackydln** [comment]
```
public class LazyMappingConfig {

    @Condition
    public static <T> boolean isLazyCollectionAvailable(Collection<T> collection) {
        if (collection == null) {
            return false;
        }

        return Hibernate.isInitialized(collection);
    }
}
```

This is what I did, but mapper tries to pass 'collection' with getter. So this still tries to lazily initialize:
```
if ( LazyMappingConfig.isLazyCollectionAvailable( entity.getSubscriptions() ) ) {
    topic.setSubscriptions( subscriptionEntityListToSubscriptionList( entity.getSubscriptions() ) );
}
```

Hibernate.isInitialized(..); method must be called on field, but since it is private it has to be passed with reflection or mapper *could* use hasXYZ method but that doesn't work on collections.

**Comment by Aytackydln** [comment]
Other possible solution is giving Condition methods a Function, then we can decide to use or not based on Exception thrown

**Comment by Aytackydln** [comment]
So, presence methods work in 1.5.0.Beta2. I will be using that for my project for now.

**Comment by filiphr** [comment]
I was not aware that `Hibernate.isInitialized(...)` must be called on a field. I thought that the initialization happens when you try to iterate or access something in the collection. 

The other alternative that I indeed forgot to mention and you figured it out on your own is the presence check methods `hasXYZ`. 

Closing this now. Please let us know if you think that there is something that we should do about this @Aytackydln

**Comment by Aytackydln** [comment]
After reading your comment I realized by default collections are initialized when they are iterated etc. but in my project I was using Hibernate enhancer which makes the initialization at getter method.

After removing hibernate enhancer now `@Condition` methods work too and I don't have to add checker methods on every entity

**Comment by filiphr** [comment]
Thanks for checking again @Aytackydln. Not needing to have a presence check for every collection in every entity certainly makes it simpler
