### ISSUE TITLE
No property named "xxx" exists in source parameter(s),Did you mean "null"?

### ISSUE THREAD

**Issue by adminSxs** [mapstruct/mapstruct#2782]
**Mastruct Version**:  1.4.2.Final
**Java Version**: 1.8

Example:
```java
@Setter
@Getter
public class Test1{
  private String name;
}
@Setter
@Getter
public class Test2{
 private String username;
}

@Mapper
public interface TestMapper{

  @Mapping(source="name",target="username")
  Test2 parseFrom(Test1 test1);
}

```
when `mvn compile`  occur:
No property named "name" exists in source parameter(s). Did you mean "null"?

in Mapstruct (1.3.0.Final) compile success

**Comment by adminSxs** [comment]
maybe is incompatible lombok(1.18.20), when I remove @Setter  @Getter annotation and write Set/Get method，compile will pass

**Comment by Zegveld** [comment]
what is the maven configuration that you have for the annotation processors?

**Comment by filiphr** [comment]
MapStruct is compatible with Lombok 1.18.20. Have a look at https://mapstruct.org/faq/#Can-I-use-MapStruct-together-with-Project-Lombok for what you are missing. Most likely it is the lombok-mapstruct-binding dependency.

**Comment by filiphr** [comment]
@MaxiCarrillo no you do not need to order the dependencies. You have to make sure that the `lombok-mapstruct-binding` is available. Please read the link from my last comment

**Comment by JasonWeng9** [comment]
@filiphr Hi Fillip, I do use  Lombok 1.18.16 and mapstruct 1.5.3. And @MaxiCarrillo 's workaround works for me. Any reason for that?  Sure, adding lombok-mapstruct-binding works as well.

**Comment by filiphr** [comment]
@JasonWeng9 you need to add the `lombok-mapstruct-binding` to the `annotationProcessorPaths` as well. You do not need to add the `mapstruct-processor` to your dependencies.

You can also see this in our examples

https://github.com/mapstruct/mapstruct-examples/blob/b7041df719da3b9e9c5f6304dcac9d9d7e7938a8/mapstruct-lombok/pom.xml#L75-L91
