### ISSUE TITLE
DefaultAccessorNamingStrategy not found in mapstruct dependency

### ISSUE THREAD

**Issue by Mixermachine** [mapstruct/mapstruct#2787]
- [X] Is this an issue (and hence not a question)? 

Hy Mapstruct team
I'm using lombok with @Builder(setterPrefix = "with") and wanted to use Mapstruct to map my models and dtos.
I already learned that I need to use a custom DefaultAccessorNamingStrategy here (https://stackoverflow.com/questions/67273711/mapstruct-is-unable-to-use-lomboks-builder-with-custom-setterprefix).
When I try to implement a DefaultAccessorNamingStrategy I can not seem to find the interface in 
```
<dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct</artifactId>
        <version>${org.mapstruct.version}</version>
</dependency>
```

The path org.mapstruct.ap... is simply not there.
Am I doing something wrong? Or is this maybe an issue?

**Comment by filiphr** [comment]
Closing this issue since @Zegveld has addressed the problem. Thanks @Zegveld

**Comment by Mixermachine** [comment]
@Zegveld thanks for your answer :)
