### ISSUE TITLE
Improving error messages for auto generated mappings

### ISSUE THREAD

**Issue by afwlehmann** [mapstruct/mapstruct#2788]
- [x] Is this an issue (and hence not a question)? 

The documentation of `Mapper#disableSubMappingMethodsGeneration` states that if one had to use it, the case should be reported, and here we go.

In our case we had a deeply nested hierarchy of types. For each of those types, a corresponding DTOs exists in another package, but these DTOs do not necessarily contain all of the fields of the source types. When working with the default setting of `disableSubMappingMethodsGeneration == false`, the error messages contain only the raw names of the unmapped source fields, but do not yield the information to which type each of the unmapped fields belongs. Hence turning off auto generation made it a lot easier to find the corresponding culprits. Maybe the error messages could be improved to something like `Unmapped source property: typeA.typeB.foo`.

**Comment by filiphr** [comment]
Thanks for raising this issue @afwlehmann. Do you have an example that would show this problem, I think it would be easier for us to work on a fix and provide a better error message for that.

**Comment by filiphr** [comment]
I forgot to ask, how does the error look like now?

**Comment by Zegveld** [comment]
![image](https://github.com/mapstruct/mapstruct/assets/41897697/a9e2f2c3-d3c2-4a67-8c04-92cec903cb6c)
perhaps changing the `unmapped source property` error to be like the `unmapped target property` error would suffice.

**Comment by Zegveld** [comment]
I've got a situation where I need this fixed, because that would make life so much easier.
I hope that I'll be able to put out a PR somewhere this or next week.
