### ISSUE TITLE
No import is added to generated class when using '@BeforeMapping' on a 'used' mapper

### ISSUE THREAD

**Issue by prgood** [mapstruct/mapstruct#2807]
If we use a "baseMapper" class that the only method called is a "@BeforeMapping", than a implementation class is generated without the proper import. This issue was tested at versions: "1.4.2.final" and "1.5.0.RC1"

If we use any of regular(no "BeforeMapping") methods from baseMapper the important is added to the generated class.

```
public class BaseMapper {
    private BaseMapper() {   }

    public static String mapUuidToString(UUID uuid) {
        return uuid == null ? null : uuid.toString();
    }

    @BeforeMapping
    public static <T, D> List<D> handleNullLists(Iterable<T> source) {
        return source == null ? new ArrayList() : null;
    }
}
```

The code below generates a no working implementation class, since a import to `BaseMapper` is missing:
```
@Mapper(componentModel = "spring", uses = {BaseMapper.class})
public interface NoWorkingSample {

    List<String> map(List<Integer> list);
}
```

The code below generates a working implementation class, since we are also using the `mapUuidToString` method from the `BaseMapper`:
```
@Mapper(componentModel = "spring", uses = {BaseMapper.class})
public interface WorkingSample {

    List<String> map(List<UUID> list);
}
```

- [X] Is this an issue (and hence not a question)?

**Comment by Zegveld** [comment]
Thank you for the bug report.
After looking into this I noticed it only surfaces when also using the "spring" `componentModel`.
PR is on the way to get this fixed.

**Comment by prgood** [comment]
Thanks for quick reponse. You guys are amazing! :-)

I did notice that "spring" componentModel was required to trigger this, thanks for the analysis.
