### ISSUE TITLE
Reassign the value to source in the @BeforeMapping method

### ISSUE THREAD

**Issue by CaliInn-Li** [mapstruct/mapstruct#2817]
I am writing a Mapper transferring Bo to Entity. However the source BoList need to be pre-processed before Mapping to ensure that no Bo in the BoList have a null attribute. 
```java
@Mapper
public interface MyMapper{
  Logger LOGGER = LoggerFactory.getLogger(myMapper.class);
  
  MyEntity bo2Entity(MyBo bo);
  
  List<MyEntity> boList2EntityList(List<MyBo> boList);
  
  //not working, only show my purpose
  @BeforeMapping
  default List<MyBo> processBoList(@MappingTarget List<MyEntity> myEntityList, List<MyBo> boList)){
    List<MyBo> newBoList = new ArrayList<>(boList.size());
    for (bo : boList) {
      if(bo.getParam1 == null || bo.getParam2 == null){
        LOGGER.warn("find null attribute in {}", bo.getName());
        continue;
      }
      newBoList.add(bo);
    }
    return newBoList;
  }
}
```
What I want the implementation class generated by mapstruct is like:
```java
public class MyMapperImpl implements MyMapper{
  @Override
  List<MyEntity> boList2EntityList(List<MyBo> boList){
    if( boList == null ) {
      return null;
    }
    
    List<MyEntity> list = new ArrayList<>(boList.size());
    
    //note: doesn't make sence, only show my purpose
    boList = processBoList(list, boList));
    
    //......
  }
}
```
I wish mapstruct could give a way to reassign the value to source before Mapping.

**Comment by Zegveld** [comment]
how about using an `@Condition`?

For example:
```
@Condition
boolean mappingAllowed(MyBo mybo){
    if (bo.getParam1 == null || bo.getParam2 == null) {
        LOGGER.warn("find null attribute in {}", bo.getName());
        return false;
    }
    return true;
}
```

**Comment by CaliInn-Li** [comment]
> how about using an `@Condition`?
> 
> For example:
> 
> ```
> @Condition
> boolean mappingAllowed(MyBo bo){
>     if (bo == null) {
>         return false;
>     }
>     if (bo.getParam1 == null || bo.getParam2 == null) {
>         LOGGER.warn("find null attribute in {}", bo.getName());
>         return false;
>     }
>     return true;
> }
> ```

Thanks! That helps me a lot. I didn't find it cause I hadn't upgraded mapstruct to the latest RC version. If you don't mind, I will ask a question on stackoverflow and link to this issue.
