### ISSUE TITLE
When using Lombok and Qualifiers, compilation fails

### ISSUE THREAD

**Issue by ajs139** [mapstruct/mapstruct#2818]
To reproduce, clone https://github.com/ajs139/intellij-mapstruct-lombok. When the test is first run in IntelliJ, everything is OK. If any modifications are made to MessageMapper, then the tests will fail until the project is rebuilt with the following compilation error:

```
Qualifier error. No method found annotated with: [ @JsonToObject ]. See https://mapstruct.org/faq/#qualifier for more info
Can't map property "String json" to "Object data". Consider to declare/implement a mapping method: "Object map(String value)"
Qualifier error. No method found annotated with: [ @ObjectToJson ]. See https://mapstruct.org/faq/#qualifier for more info
Can't map property "Object data" to "String json". Consider to declare/implement a mapping method: "String map(Object value)"
```

Initially I thought this looked like an IntelliJ problem, however they pointed in me in your direction. Any help would be appreciated.

**Comment by Zegveld** [comment]
What happens when you set the retention policy to `class` instead of `source`?

**Comment by ajs139** [comment]
Works perfectly. That's awesome, thanks so much!
