### ISSUE TITLE
How to use mapstruct to map field from outside a collection to inside a collection

### ISSUE THREAD

**Issue by FJiayang** [mapstruct/mapstruct#2823]
My Environment
java: 17.0.1
mapstruct: 1.4.2.Final

Here is my example

```java
@Data
public class Example {

	private Long outsideId;

	private List<Inside> insides;
}

@Data
public class Inside {

	private Long insideId;

	private String name;
}
```

```java
@Data
public class ExampleReq {

	private Long outSideId;

	private List<InsideReq> insides;
}

@Data
public class InsideReq {

	private String name;
}
```

I want the value of the insideId of all elements in the collection to be the outsideId,

My current configuration is as follows

```java
public interface ExampleAssembler {

	@Mapping(target = "insides.insideId",source = "outsideId")
	Example of(ExampleReq req);
}
```

But it reports an error

```
java: The return type List<Inside> is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
```

How should I configure it?

**Comment by Zegveld** [comment]
The problem is that the property `insides` is a list, therefor using nested properties the next properties are those of `List` and not of `Inside` contained in the `List`.

I think the best way to do this is with an `@AfterMapping` where you set the value manually.

For example the following:
```
@AfterMapping
void configureIds( @MappingTarget Example target ) {
    target.getInsides().forEach( inside -> inside.setInsideId( target.getOutsideId() ) );
}
```
