### ISSUE TITLE
Setting `defaultValue`/`defaultExpression` not honoured for top-level parameters

### ISSUE THREAD

**Issue by konradekk** [mapstruct/mapstruct#2829]
Version: 1.4.2.Final

I’m using MapStruct mapper as a bean creator (I’m injecting some data through CDI too). While there’s no real problem if I use `Boolean` as a parameter it’s impossible to use `boolean` instead. To work around that I need to create my own implementation (protected method in abstract class) with `boolean` parameter calling the one with `Boolean`.

Single `Boolean` parameter is also problematic for me (this is the reason why I use proxy described above) as it yields `null` for `null` argument. All my problems would disappear if I could assign default value for `Boolean` field (for me: `false`) but this apparently is not reflected in generated implementation. Tried some settings but none worked—glad to hear how to achieve that if possible.

I believe above is not really possible so that would be my issue I’d like to file here:
> Single (non-primitive) parameter enforcing `null` → `null` mapping

I think I’m not really interested in default constructor mapping as I want to inject my own values in the mapper (not the constructor) as indicated in the first paragraph.

That’s usability/alignment issue only as simple workaround exists and works.

**Comment by filiphr** [comment]
Can you perhaps show an example that is depicting this problem. I am having troubles understanding the problem from the issue.

**Comment by konradekk** [comment]
I now think I should have started from the example! 😅

I’ve changed my approach slightly from that time but what I was trying to achieve was something along those lines:
```java
@Mapping(target = "flag", source = "flag", defaultValue = "false")
public abstract Model toModel(DTO dto, Boolean flag);
```
where `Model` contains `boolean flag;` to have `false` passed as a `flag` if one passed `null` in `toModel` second parameter.

As far as I remember I was forced to have
```java
@Mapping(target = "flag", source = "flag")
protected abstract Model toModelMapping(DTO dto, boolean flag);
```
that was called in separate method, e.g.
```java
public Model toModel(DTO dto, Boolean flag) {
    return toModelMapping(dto, flag);
}
```

All in all: I wanted to map `null` to one of the boolean values (`false` in my case) instead of `null` in `Boolean` type mapping. I thought it’d be possible to indicate it with e.g. `defaultValue` but I failed.

I still feel that I’ve conveyed my issue in not of the best forms but hope it’s little bit more understandable now…! 😅

Feel free to ping for more details! (excuses for delay!)

**Comment by filiphr** [comment]
>I now think I should have started from the example! 😅

An example is always easier to understand 😄.

Lokoing at your example I think that you were affected by #2023.

In 1.5 I tried the following:

```java
class Model {

    private boolean flag;
    private String id;
}
```

and a mapper:

```java
@Mapper
public interface TestMapper {

    @Mapping( target = "flag", defaultValue = "false")
    Model map(DTO dto, Boolean flag);
}
```

This would generate something like:

```java
    @Override
    public Model map(DTO dto, Boolean flag) {
        //...

        if ( flag != null ) {
            model.setFlag( flag );
        }
        else {
            model.setFlag( false );
        }

        //...
    }
```

Is this what you are expecting?

**Comment by konradekk** [comment]
Yup; exactly that was needed/expected! If this behaviour is available in newer version then consider that issue closed! 🙇‍♂️

**Comment by filiphr** [comment]
Great. I'll close the issue since this works as expected from 1.5. Thanks for the examples @konradekk

**Comment by konradekk** [comment]
Thanks to you too for your assistance! 🎩

**Comment by minbelapps** [comment]
![image](https://user-images.githubusercontent.com/17129475/210074971-00994915-d8be-4f4b-b6b8-f9da0577d74b.png)
