### ISSUE TITLE
Lazy Proxy Feature Proposal

### ISSUE THREAD

**Issue by rmanibus** [mapstruct/mapstruct#2830]
When using a backend that can be lazily  initialized, mapstruct completely destroy those features for now.

The idea of this feature is to provide a new flag in the Mapping annotation:
```
@Mapping(lazy = "true")
```
When setting this flag, the call to the mapper would provide a proxy of the lazy field which hold a reference of the mapping function.
The mapping function will only be called if the actual method is called.

**Comment by filiphr** [comment]
Can you please be more precise of what `@Mapping(lazy = true)` should generate. I fail to understand how mapstruct is destroying lazy initialization? MapStruct calls methods for mappings, and you can implement whatever you want behind those methods, even some lazy initialization.

**Comment by rmanibus** [comment]
Yes, 
this should generate a mapping method that return a javassist proxy object of the target bean. 

When a method is called on this proxy, this should call the actual mapping function (which would be embedded in the proxy, as well as the source objects).

I think It's more or less that way that lazy loading is implemented in modern ORMs.

**Comment by luxbe** [comment]
@rmanibus I am having the same problem currently - did you manage to find a workaround?

**Comment by thunderhook** [comment]
> @rmanibus I am having the same problem currently - did you manage to find a workaround?

What is your problem scenario? Is it about mapping from lazy loaded JPA entities?

Without context it is difficult to provide a workaround.

**Comment by rmanibus** [comment]
I ended up not using lazy loading basically

**Comment by luxbe** [comment]
> > @rmanibus I am having the same problem currently - did you manage to find a workaround?
> 
> What is your problem scenario? Is it about mapping from lazy loaded JPA entities?
> 
> Without context it is difficult to provide a workaround.

The problem I'm having is that when mapping lazy loaded JPA entities with a lot of other lazy loaded connected entities, mapstruct has to load all of them in order to perform the mapping. This is a quite expensive operation and takes quite long due to the network overhead.

The problem with this approach is, in case I only need a few fields, mapstruct still loads everything and resolves the lazy loading proxies. I would expect mapstruct to only load the connected entities when required (when calling a getter method), instead of loading everything eagerly.

**Comment by filiphr** [comment]
@luxbe MapStruct generates mapping code, it has no knowledge of JPA. How do you expect this to work? Can you perhaps provide some example with what isn't working properly and how you would do this manually without MapStruct, if we have that, then perhaps we can do something about it.

**Comment by luxbe** [comment]
Hi @filiphr,

sorry for the delayed response - I was on vacation!
I threw together a simple example with the following classes:

```java
@Getter
@Setter
public class AddressV1 {
    private String streetName;
    private String cityName;
}

@Getter
@Setter
public class AddressV2 {
    private String street;
    private String city;
    private String zipCode;
}

@Getter
@Setter
public class PersonV1 {
    private String fullName;
    private AddressV1 address;
}

@Getter
@Setter
public class PersonV2 {
    private String name;
    private AddressV2 addressV2;
}
```

If I now specify a `PersonMapper` interface:

```java
@Mapper(uses = {
    AddressMapper.class
})
public interface PersonMapper {
    PersonMapper INSTANCE = Mappers.getMapper( PersonMapper.class );

    @Mapping(source = "name", target = "fullName")
    PersonV1 toV1(PersonV2 person);
}
```

Mapstruct would generate a `PersonMapperImpl` class with the following mapping implementation:

```java
@Override
public PersonV1 toV1(PersonV2 person) {
    if ( person == null ) {
        return null;
    }
  
    PersonV1 personV1 = new PersonV1();
    personV1.setAddress( addressMapper.toV1( person.getAddressV2() ) );
    personV1.setFullName( person.getName() );
  
    return personV1;
}
```

The problem with this implementation - as stated above - is that everything is loaded right away. In this case it's only an address, but in case of deeply nested and lazy loaded data from a database, everything has to be loaded before the mapping can take place. In my case, there are thousands of connected entities, which I only need to access a small part of.

# Proposed Solution

My proposed solution would be for Mapstruct to generate a "Proxy" class to delay the mapping until it is actually needed:

```java

public class PersonV1_toV1_MapstructProxy extends PersonV1 {
    private final AddressMapper addressMapper = AddressMapper.INSTANCE;

    private final PersonV2 person;
    private PersonV1 value;

    public PersonV1_toV1_MapstructProxy(PersonV2 person) {
        this.person = person;
    }

    @Override
    public String getFullName() {
        PersonV1 loaded = triggerLazyLoading();
        return loaded.getFullName();
    }

    @Override
    public void setFullName(String fullName) {
        PersonV1 loaded = triggerLazyLoading();
        loaded.setFullName( fullName );
    }
    
    // Setters and Getters for address omitted 
       
    private PersonV1 triggerLazyLoading() {
        if ( value != null ) {
            return value;
        }

        value = new PersonV1();

        value.setFullName( person.getName() );
        value.setAddress( addressMapper.toV1( person.getAddressV2() ) );

        return value;
    }
}


@Mapping(source = "name", target = "fullName")
public PersonV1 toV1(PersonV2 person) {
    if ( person == null ) {
        return null;
    }

    return new PersonV1_toV1_MapstructProxy( person );
}
```

This way, the mapping would be delayed until a getter` or setter on the Proxy class is called. Of course there are some restrictions - for example this approach is only possible with getters and setters and a bit more code is generated. For this reason, this should obviously be opt-in as well.

What do you think of an approach like this?

**Comment by filiphr** [comment]
Thanks for the example @luxbe.

I'm afraid that the example is completely outside of what MapStruct is trying to provide. We do not want to generate proxies like this.

If you need something like this, then you'll need to do something on your own.

What you could use is to control what you want to map using the `@Condition` from MapStruct.

Closing this as we do not want to offer something like this.
