### ISSUE TITLE
Missing 'gem' module / component

### ISSUE THREAD

**Issue by frank-a-otc** [mapstruct/mapstruct#2836]
Hey I'm trying to compile,  looks like the below files and more  are missing. How do I resolve that? 

- org.mapstruct.ap.internal.gem.BuilderGem;
- org.mapstruct.ap.internal.gem.DecoratedWithGem;
- org.mapstruct.ap.internal.gem.InheritConfigurationGem;
- org.mapstruct.ap.internal.gem.InheritInverseConfigurationGem;
- org.mapstruct.ap.internal.gem.MapperGem;

Thanks

**Comment by filiphr** [comment]
How are you trying to compile @frank-a-otc? Those classes are generated classes and everything should work fine when using Maven or IntelliJ. Most likely there is no problem with Eclipse, but I don't use Eclipse, so can't say much.
