### ISSUE TITLE
How can i set property value only when the target property is null?

### ISSUE THREAD

**Issue by jnchen** [mapstruct/mapstruct#2841]
I search for the documentation but do not find a solution. maybe provider a condition or failover in beforeMapping. besides NullValueStrategy unsupport on Method Level is so bad ....

**Comment by filiphr** [comment]
Please use our [DIscussions](https://github.com/mapstruct/mapstruct/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) for asking questions.

When asking a question, please provide an example from what you have tried and show us an example of what you want to achieve so we can help you better.
