### ISSUE TITLE
Can not inverse mapping of nested fields when using mapping methods

### ISSUE THREAD

**Issue by Kirito114** [mapstruct/mapstruct#2842]
Hello everyone !

I am currently facing a problem while trying to reverse map nested properties and I hope someone can help me out on this one.

My DTO and model look something along those lines:

```java
public class DTO {
    String field1
    NestedDto field2
    NestedDto field3
    NestedDto field4
    NestedDto field 5
}

public class NestedDto {
    String field1
    String field2
    String field3
}

public class Entity {
    String field1
    String field2_1
    String field2_2
    String field2_3
    String field3_1
    String field3_2
    // And so on
}
```

So as you can see I have to map groups of fields in the flat Entity to multiple nested objects in the DTO. Since the fields in the nested DTO and the Entity do not have the same names, there is no way for MapStruct to know what to mpa, so it makes sense that I have to define that with @Mapping annotations explicitely. And because there are a lot of mapping annotations to add to be able to map all the flat fields to the nested ones I decided not to put everything on one single mapping method  in the mapper like the following:

```java
// A lot of @Mappings
Dto mapDtoToEntity(Entity entity);
```

But to use mapping methods instead, so I did something like this:

```java
public interface MyMapper {

    @Mapping(target = "field2", source = "source", qualifiedByName = "mapMethod1")
    @Mapping(target = "field3", source = "source", qualifiedByName = "mapMethod2")
    @Mapping(target = "field4", source = "source", qualifiedByName = "mapMethod3")
    @Mapping(target = "field5", source = "source", qualifiedByName = "mapMethod4")
    Dto mapDtoToEntity(Entity source);

    @Named("mapMethod1")
    @Mapping(target = "field1", source = "field2_1")
    @Mapping(target = "field2", source = "field2_2")
    @Mapping(target = "field3", source = "field2_3")
    NestedDto mapfield2ToNestedField2(Entity entity);

    // And the same thing for the other mapping methods
}
```

My question now is how do I do the inverse mapping from Dto to Entity (nested to flat) ? Because if I try _@InheritInverseConfiguration_ MapStruct tells me that the **source** field does not exist in the Entity, which seems to indicate that MapStruct does know that in the original mapping from Entity to Dto it needs to call the mapping methods but when trying to inverse the mapping it just inverts the given mapping which of course does not make sense since the "source" does not denote an existing field. It seems like MapStruct should know how to do the inverse operation since it would just have to inverse the @Mapping annotations on the mapping methods

**Comment by filiphr** [comment]
Doing `@InheritInverseConfiguration` is literally reversing what you have in `@Mapping`, i.e. changing `source` and `target`. We do not do a lot of complex things here.

In order to achieve what you are looking for you will need to do like you have shown in your example.

Closing this, since we can't do much about this now.
