### ISSUE TITLE
[BUG] Integer/Long/... to String conversion changes null to "null"

### ISSUE THREAD

**Issue by vincentvliegen** [mapstruct/mapstruct#2846]
The [WrapperToStringConversion.getToExpression()](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/conversion/WrapperToStringConversion.java#L48) method uses String.valueOf(). This is ideal for displaying values, not for conversion; [null will become "null"](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#valueOf(java.lang.Object)). 
If you map from e.g. an Integer property to a String property, this behaviour is as expected, except for null values.

This could be easily remedied by adding a null check.

**Comment by filiphr** [comment]
I understand your point @vincentvliegen. This has been like this for a really long time, which means changing it might be a backwards incompatible change. Will discuss it with the team.

Was it working as expected at some time perhaps?

**Comment by filiphr** [comment]
@vincentvliegen can you please have a look at #2862. I have added a test case and mapping `null` Integer to `String` correctly maps to `null` (not a null string). Can you perhaps provide your example?
