### ISSUE TITLE
[bug] @AfterMapping method is not called when using @Builder in the target onject

### ISSUE THREAD

**Issue by farhaanfsk** [mapstruct/mapstruct#2848]
Hi,

I recently came across a issue the @AfterMapping method is never called when the @MappingTarget object has a Lombok @Builder annotation in it.

once i removed the @Builder the and generated code the after mapping method was called.

Example: 

**Customer.class**
```
@Builder
@Getter
@Setter
public class Customer {
  private String email;
}
```

**CustomerResource.class**
```
@Builder
@Getter
@Setter
public class CustomerResource {
  private String email;
}
```

**Mapper classs:**

```
@Mapper
public interface CustomerMapper {

  public CustomerResource toCustomerResource(Customer customer);

  @AfterMapping
  default void setMailFormat(@MappingTarget CustomerResource resource) {
    String mail = resource.getEmail();
    resource.setEmail(mail + "@mail.com");
  }
}
```

**Generated mapper implementation:**
```

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-05-16T13:39:18+0530",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.1.jar, environment: Java 1.8.0_201 (Oracle Corporation)"
)
public class CustomerMapperImpl implements CustomerMapper {

    @Override
    public CustomerResource toCustomerResource(Customer customer) {
        if ( customer == null ) {
            return null;
        }

        CustomerResourceBuilder customerResource = CustomerResource.builder();

        customerResource.email( customer.getEmail() );

        return customerResource.build();
    }
}
```

**Mapper implementation post @Builder annotation is removed from Target object CustomerResource** 

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-05-16T13:44:54+0530",
    comments = "version: 1.4.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.1.jar, environment: Java 1.8.0_201 (Oracle Corporation)"
)
public class CustomerMapperImpl implements CustomerMapper {

    @Override
    public CustomerResource toCustomerResource(Customer customer) {
        if ( customer == null ) {
            return null;
        }

        CustomerResource customerResource = new CustomerResource();

        customerResource.setEmail( customer.getEmail() );

        setMailFormat( customerResource );

        return customerResource;
    }
}
```

if you observer in the above ### setMailFormat( customerResource ); which is the after mapping class is called.

**EXPECTED**
the after mapping method should called even if the target object has a builder in it.

Version:
mapstruct -> 1.4.2.Final
lombok -> latest
Java -> 1.8

**Comment by Zegveld** [comment]
When using builders the after mapping method should also use the builder for the target type and not the target type itself.
In your case this would be `CustomerResourceBuilder` instead of `CustomerResource`.

[This is documented behavior: (quote is from the end of the linked chapter)](https://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after)

>Important: when using a builder, the @AfterMapping annotated method must have the builder as @MappingTarget annotated parameter so that the method is able to modify the object going to be build. The build method is called when the @AfterMapping annotated method scope finishes. MapStruct will not call the @AfterMapping annotated method if the real target is used as @MappingTarget annotated parameter.

With 1.5 the documentation of the builder area is also updated to point to this note.
