### ISSUE TITLE
Error in the readme ( what is mapstract paragraph ) 

### ISSUE THREAD

**Issue by Momellouky** [mapstruct/mapstruct#2851]
To create a mapping between two types, declare a mapper class like this:
```
@Mapper
public interface CarMapper {

    CarMapper INSTANCE = Mappers.getMapper( CarMapper.class );

    @Mapping(target = "seatCount", source = "numberOfSeats")
    CarDto carToCarDto(Car car);
}
```

I guess it should be "declare a mapper interface like this: "

**Comment by filiphr** [comment]
You are right @Momellouky. I've created PR #2860 to fix this typo. Thanks for reporting it
