### ISSUE TITLE
How to merge two source objects into target object

### ISSUE THREAD

**Issue by xbsummer** [mapstruct/mapstruct#2855]
```
user A:     {"name": "aaa",  "age": 13, "sex": "male"}
user B:     {"name": "aaa",  "age": 18, "sex": null}

return:    {"name": "aaa",  "age": 18, "sex": "male"}
```
I want to implement as follows:
```
@Mapping(target = "sex", expression="java(B.getSex() == null ? A.getSex() : B.getSex())")
@Mapping(target = "name", expression="java(B.getName() == null ? A.getName(): B.getName())")
@Mapping(target = "age", expression="java(B.getAget() == null ? A.getAget(): B.getAget())")
User merge(User A, User B);
```
there are many fields, Is there a simpler way to implement it?

**Comment by Zegveld** [comment]
If you don't mind that the `user A` object gets updated you could annotate `User A` parameter with `@MappingTarget`. [This way you use an update mapping as described here](https://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances).

**Comment by Zegveld** [comment]
forgot to mention that you also need to use `NullValuePropertyMappingStrategy.IGNORE`

> By specifying nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE on @Mapping, @BeanMapping, @Mapper or @MapperConfig, the mapping result will be equal to the original value of the @MappingTarget annotated target.

[Described here in the Reference Guide](https://mapstruct.org/documentation/stable/reference/html/#mapping-result-for-null-properties)
