### ISSUE TITLE
Combining AnnotateWith with componentModels

### ISSUE THREAD

**Issue by Zegveld** [mapstruct/mapstruct#2875]
When you currently specify a component model specific annotation, while also referring to that component model will generate invalid code.

For example:
```
@Mapper( componentModel = "spring" )
@AnnotateWith( value = Component.class, elements = @Element( strings = "bean name" ) )
public interface MySpringMapper {
```
will generate:
```
@Component
@Component( "bean name" )
public class MySpringMapperImpl implements MySpringMapper {
```
The `@Component` annotation is not repeatable so the java compiler will give an error about this.

The idea is to have support for these situations and in this case skip the generation of the `@Component` annotation without value.

**Comment by AlexElin** [comment]
@Zegveld , where does `@AnnotateWith` come from?
I don't see such annotation in the Mapstruct's 1.5 [javadoc](https://mapstruct.org/documentation/1.5/api/)

**Comment by Zegveld** [comment]
> @Zegveld , where does `@AnnotateWith` come from? I don't see such annotation in the Mapstruct's 1.5 [javadoc](https://mapstruct.org/documentation/1.5/api/)

it is new in the upcoming 1.6

**Comment by filiphr** [comment]
@Zegveld are you sure about this? I see that we have closed #1427 and we actually added support for this in https://github.com/mapstruct/mapstruct/commit/90a487ac0641c39ebec6680567cc97eaede49365 and we have https://github.com/mapstruct/mapstruct/blob/bc5a8771217365b32782f160f132d1dd2a1c4fa1/processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/annotateWith/SpringAnnotateWithMapperTest.java#L37 which tests this

**Comment by Zegveld** [comment]
Closing as duplicate.

and yes I am certain that we do not have a release with the annotatewith annotation. Since I don’t see it listed on the docs page in chapter 3 yet. The 1.6 milestone also lists it as being in this release.

**Comment by filiphr** [comment]
@Zegveld, sorry I didn't quote properly. When I was asking whether you are certain about this I meant the original issue, not whether it is released 😀.
