### ISSUE TITLE
Generated code does not include enclosing class when referring to nested class

### ISSUE THREAD

**Issue by mkjensen** [mapstruct/mapstruct#2880]
MapStruct recently switched to only generating imports for top level classes (#1386). This seems to have caused some bugs that have been fixed (#2704, #2797). However, there are more bugs as captured by this issue.

Here's a small project that shows the bugs in MapStruct 1.5.1.Final and also shows that the bugs do not exist in MapStruct 1.4.2.Final: https://github.com/mkjensen/mapstruct-nested-class-bug/tree/main

Maybe there are more, I'm not sure. Although it results in generated code that is harder to read, maybe it's worth considering to use fully qualified names when referring to classes.

**Comment by mkjensen** [comment]
I have added a test for this issue to https://github.com/mkjensen/mapstruct/tree/issue-2880 (https://github.com/mapstruct/mapstruct/commit/71b250d44a9b012453bd09cccb6df60302310a6a).

It seems like the issue is that `org.mapstruct.ap.internal.model.common.Type#nameWithTopLevelTypeName` requires a `TypeElement` to generate a name but `org.mapstruct.ap.internal.model.common.TypeFactory#getType(javax.lang.model.type.TypeMirror, boolean)` does not supply one for arrays when creating a `org.mapstruct.ap.internal.model.common.Type`.

As this is my first endeavor into the MapStruct code, I'm not sure I will come up with a reasonable fix any time soon.

**Comment by spencercjh** [comment]
same issue.

**Comment by filiphr** [comment]
Thanks a lot for creating the test case @mkjensen. We are going to look into this asap as it is blocking people.

Perhaps we will even add a mechanism to back out of the nested types approach. In order to have a workaround for the problem.

**Comment by filiphr** [comment]
@mkjensen thanks for the test case, it helped located the problem. The fix is in PR #2888

**Comment by AbelPelser** [comment]
This issue is still present for nested enums
