### ISSUE TITLE
Generated null checks for source parameters changed from 1.4.2 to 1.5.1 

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#2881]
### Discussed in https://github.com/mapstruct/mapstruct/discussions/2877

The change is in the null checks of the source parameters.

<div type='discussions-op-text'>

<sup>Originally posted by **otbe** June  7, 2022</sup>

Imagine we have a `Mapper` interface with a mapping method defined like this
```java
@Mapper
interface GeneratedMapper {
  MyPojo map(
      OrganisationId organisation,
      UserId user,
      AuthenticationMethodsReferences amr,
      ZonedDateTime timestamp);
}

```

In the old 1.4.2 version of mapstruct this would generate the following code assuming we have a builder in `MyPojo`
```java
@Override
public MyPojo map(AuthenticationMethodsReferences amr, UserId user, OrganisationId organisation, ZonedDateTime timestamp) {
    if ( amr == null && user == null && organisation == null && timestamp == null ) {
        return null;
    }

    MyPojo.Builder myPojo = MyPojo.builder();

    if ( amr != null ) {
        myPojo.amr( map( amr ) );
    }
    if ( user != null ) {
        myPojo.user( mapUserId( user ) );
    }
    if ( organisation != null ) {
        myPojo.organisation( map( organisation ) );
    }
    if ( timestamp != null ) {
        myPojo.timestamp( timestamp );
    }

    return myPojo.build();
}
```

However version 1.5.0 (and 1.5.1) generate something like this
```java
@Override
public MyPojo map(OrganisationId organisation, UserId user, AuthenticationMethodsReferences amr, ZonedDateTime timestamp) {
    if ( organisation == null && user == null && amr == null && timestamp == null ) {
        return null;
    }

    MyPojo.Builder myPojo = MyPojo.builder();

    myPojo.organisation( map( organisation ) );
    myPojo.user( mapUserId( user ) );
    myPojo.amr( map( amr ) );
    myPojo.timestamp( timestamp );

    return myPojo.build();
}
```

The biggest problem for our use case is now that we have defaults in the builder class (these Pojos are generated by some external 3rd party tool). Without the additional null checks the methods like `timestamp` will always be called with null which leads to undesired side effects.

I scanned through the changelog and all new (and old) null related mapping settings but cant really relate my issue to something from the 1.5.0 release. 

So my question would be: is there a way to bring back the old null check behaviour or is there some reasoning behind this that I dont see right now?

Thank you very much :)</div>

**Comment by marcuspflanz** [comment]
Just noticed the same in our codebase.
Looks like the setting **nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE** helps.

Still: Not sure whether or not this change in behavior is intended. At least didn't find something related in the release notes.

**Comment by filiphr** [comment]
The commit that broke this is https://github.com/mapstruct/mapstruct/commit/84c3bda5a23e48956ad5de4955792ef0a278638e

**Comment by filiphr** [comment]
I did some more analysis on this one. And it is a tricky one. Before it worked by accident and it wasn't consistent to how single source parameter mappings work.

The change in the generated source code is there only due to the fact that we have never done null checks on bean property methods, when a direct assignment is possible. That's why we have the `NullValueCheckStrategy`.

If we take the example from the post and turn it into:

```java

class Wrapper {
    OrganisationId organisation;
    UserId user;
    AuthenticationMethodsReferences amr;
    ZonedDateTime timestamp;
}

@Mapper
interface GeneratedMapper {
  MyPojo map(Wrapper wrapper);
}
```


Then the generated code will look like:

```java
@Override
public MyPojo map(Wrapper wrapper) {
    if ( wrapper == null ) {
        return null;
    }

    MyPojo.Builder myPojo = MyPojo.builder();

    myPojo.amr( map( wrapper.getAmr() ) );
    myPojo.user( mapUserId( wrapper.getUser() ) );
    myPojo.organisation( map( wrapper.getOrganisation() ) );
    myPojo.timestamp( wrapper.getTimestamp() );

    return myPojo.build();
}
```

The code above is also generated in 1.4.

Therefore, if we take the fact that a multi source method behaved differently to a single source method, in my opinion the fact that it changed is actually OK, because a bug was fixed with #2274 and #2023. It was a bug not a feature before.

In order to have a null check the `NullValueCheckStrategy.ALWAYS` needs to be set.

@marcuspflanz regarding

>Looks like the setting `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE` helps.

I am not sure why that would have an influence, because that is only applied for update methods, and not for normal mappings.

We can add a note in the release notes about this behaviour, but I am not sure that it would make sense to fix it, considering that it is not consistent in the way single source parameter mapping works.

What do you think @sjaakd / @Zegveld?

**Comment by nfalco79** [comment]
Hi @filiphr I have an issue due to the missing generation of null check.
This is the simplified situation (1.5.2)

```
public class EventDTO {
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date createdOn;
    ...
}

@MapperConfig(//
        componentModel = "spring",
        collectionMappingStrategy = CollectionMappingStrategy.SETTER_PREFERRED, //
        builder = @Builder(disableBuilder = true), //
        injectionStrategy = InjectionStrategy.CONSTRUCTOR,
        unmappedTargetPolicy = ReportingPolicy.WARN)
public interface EventMapper {

    @Mapping(source = "creationTimestamp", target = "createdOn", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
    EventDTO toEvent(Map<String, String> evtSubject);
}
```
generated code is
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-09-07T11:41:50+0200",
    comments = "version: 1.5.2.Final, compiler: Eclipse JDT (IDE) 1.4.50.v20210914-1429, environment: Java 11.0.16 (Ubuntu)"
)
@Component
public class EventMapperImpl implements EventMapper {

    @Override
    public EventDTO toEvent(Map<String, String> evtSubject) {
        if ( evtSubject == null ) {
            return null;
        }

        EventDTO eventDTO = new EventDTO();

        try {
            if ( evtSubject.containsKey( "creationTimestamp" ) ) {
                eventDTO.setCreatedOn( new SimpleDateFormat().parse( evtSubject.get( "creationTimestamp" ) ) );
            }
        }
        catch ( ParseException e ) {
            throw new RuntimeException( e );
        }
        ...
}
```
if creationTimestamp is null a NPE is raised by the EventMapperImpl.toEvent method (when call parse with null value).
Using nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS on specific attribute mapper I expect it perform a null check before use the value but was not the case.
The same code is generated also if I annotate
`@Mapping(source = "creationTimestamp", target = "createdOn", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_NULL)`

No way because to make it work without wrote a manual custom mapping

**Comment by filiphr** [comment]
@nfalco79, your problem is not related to what is described in the issue. The problem you are facing is the fact that your map might contain null values. However, MapStruct uses only the `containsKey` when mapping from a map. I would suggest that you raise a different issue or a discussion for this use case
