### ISSUE TITLE
Mapstruct picks incorrect mapping method even if source and target are explicitly specified

### ISSUE THREAD

**Issue by SergJeepee** [mapstruct/mapstruct#2887]
Hi!

I'm using mapstruct 1.4.2.Final. The same issue as well observed in the latest 1.5.1.Final.

Source class:
```java
@Table(name = "data_packages")
public class DataPackage {
    @Id
    @GeneratedValue
    private Long id;
}
```
Target class:
```java
public class DataPackageDto   {
    @JsonProperty("id")
    private Long id;
    @JsonProperty("projectsCount")
    private Long projectsCount;
}
```

Mapper:
```java
@Mapper(componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        uses = {ProjectService.class})
public interface DataPackageMapper {

    @Mapping(target = "projectsCount", expression="java(projectService.getProjectsCountByDataPackage(dataPackage.getId()))")
    DataPackageDto toDto(DataPackage dataPackage);
}
```

Generated code:
```java
@Override
public DataPackageDto toDto(DataPackage dataPackage) {
    if ( dataPackage == null ) {
        return null;
    }

    DataPackageDto dataPackageDto = new DataPackageDto();

    dataPackageDto.setId( projectService.getProjectsCountByDataPackage( dataPackage.getId() ) ); //<--- wrong mapping
    dataPackageDto.setProjectsCount( projectService.getProjectsCountByDataPackage(dataPackage.getId()) );

    return dataPackageDto;
}
```

When both source and target objects have fields with the same name (id) and type (Long), the mapper prefers to use a method from injected bean instead. I'm aware that mapper tries to find mapping method with applicable arguments and return types but  I wonder why it's not taking direct mapping:

`dataPackageDto.setId( dataPackage.getId() );`

Explicitly adding source/target fields won't help either:
`@Mapping(source = "id", target = "id")`

The workaround is mapping with java expression or @ Named / qualifiedByName custom mapping method but it really got me wondering why it doesn't prioritise mapping from direct accessors.

Anyway thank you for your work :)

**Comment by evicplus** [comment]
I hava met the same issue, I use 'qualifiedByName' on the specify filed to do mapping

**Comment by filiphr** [comment]
The reason why MapStruct is not taking a direct mapping is due to the fact that there is a manual mapping in the `ProjectService` that can be used. As soon as there is something defined by a user MapStruct will back off.

The best solution for this is to use `@Named` on the `getProjectsCountByDataPackage` and then the mapper to look like

```java
@Mapper(componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        uses = {ProjectService.class})
public interface DataPackageMapper {

    @Mapping(target = "projectsCount", source = "id", qualifiedByName = "projectCountsByDataPackage")
    DataPackageDto toDto(DataPackage dataPackage);
}
```
