### ISSUE TITLE
When mapping into a read-only collection, a NULL check of the source collection is missing

### ISSUE THREAD

**Issue by vgigerich** [mapstruct/mapstruct#289]
I created a mapping into a collection which is only accessible by its getter.
The generated mapper does a NULL check on the target read-only collection, but I would have expected a NULL check on the source collection too.

Generated code looks like this:
```
if ( target.getTagetCollection() != null ) {
    target.getTargetCollection().addAll( toSourceType( source.getSourceCollection() ) );
}
```
Expected something like:
```
if ( target.getTagetCollection() != null  && source.getSourceCollection != null ) {
    target.getTargetCollection().addAll( toSourceType( source.getSourceCollection() ) );
}
```

**Comment by sjaakd** [comment]
Or.. you add: `@Mapper(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)`

**Comment by sjaakd** [comment]
merged
