### ISSUE TITLE
Missing import of nested class

### ISSUE THREAD

**Issue by ludekz** [mapstruct/mapstruct#2897]
I have classes with imports of nested class. _UtilClass.FactoryClass_ in example below. 
This worked in 1.4.2.. After upgrade to 1,5 generated code lacks import declared in annotation property 

```
@Mapper(imports = UtilClass.FactoryClass.class)
public interface ExampleMapper {

  @Mapping(target = "firstName", expression = "java(FactoryClass.doSomething( source ))")
  Person map(Source source);
}
```

**Comment by filiphr** [comment]
In 1.5 we did a change in the imports to only import top level classes. Which means that when you do `UtilClass.FactoryClass.class` only `UtilClass.class` will be imported.

If you do `java(UtilClass.FactoryClass.doSomething( source ))` it should work.

In hindsight, maybe we were trying to be too smart with this change
