### ISSUE TITLE
Fix @TargetType solution to also take parameterized result types

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#291]
Hi,

I studied the `@TargetType` annotation. The current generated implementation creates compilation errors for the following custom mapper

```java
     public <T extends JAXBElement>  T convertToJAXBElement(@TargetType Class<T> clazz, SomeValueDto value) {
         // some logic
         return null;
     }
```
The following code is generated:

```java
public class ExMapperImpl implements ExMapper {

    private final HWMapper hWMapper = new HWMapper();

    @Override
    public JBType map(SampleDto dto)  {
        if ( dto == null ) {
            return null;
        }

        JBType jBType = new JBType();
        jBType.setVoidableSample( hWMapper.convertToJAXBElement( dto.getVoidableSample() , javax.xml.bind.JAXBElement<com.mycompany.sample.jaxb.SampleType>.class ) );

        return jBType;
    }
}
```

Which gives the following error:
`/com/mycompany/sample/ExMapperImpl.java:[24,157] <identifier> expected`

**Comment by sjaakd** [comment]
@agudian any chance that you can distill a cherry-pick out of this one?

**Comment by agudian** [comment]
Yes, at lest for the simple cases. I wanted to clear up the raw=ext.raw stuff anyway. That last example with ```U.class``` is a different caliber, though.

**Comment by agudian** [comment]
The fix for the simple case already made it into the code.

**Comment by sjaakd** [comment]
Shall we open a new issue for this, or keep this one open?

**Comment by agudian** [comment]
I'll create a new one for the other issue and close this one after I've done that (will do it later).

**Comment by agudian** [comment]
created follow up issue. closing this one.
