### ISSUE TITLE
Conversion of BigDecimal to primitive double wrong with 1.5.2

### ISSUE THREAD

**Issue by urswiss** [mapstruct/mapstruct#2913]
After migrating from 1.4.2 to 1.5.2 a test failed. The result from BigDecimal to double is not the same anymore. Please have a look. Thanks.

https://github.com/urswiss/mapstruct-bigdecimal-to-double

**Comment by filiphr** [comment]
Thanks for the analysis @Zegveld. This is most definitely related to #2840 and #1216. We'll need to figure out what actually broke this behaviour.

I think that we need to fix this inconsistency, because mapping from `BigDecimal` to `double` shouldn't use `BigDecimal` to `long`.

**Comment by filiphr** [comment]
After doing some analysis on this one and #2849 it seems like the work we did in #2320 broke this. I still need to analyse why this happened. This was not supposed to happen when we did that PR. What do you think @sjaakd? It feels like the fact that the return type can be assigned to the expected type is causing the problem.

**Comment by saw303** [comment]
@filiphr that's amazing news! Thank you
