### ISSUE TITLE
Presence checker ignored in 1.5.2

### ISSUE THREAD

**Issue by vitorcezli** [mapstruct/mapstruct#2914]
After migrating from 1.4.2 to 1.5.2, the MapStruct presence checker stopped working. On version 1.4.2, MapStruct wouldn't update a field `X` if the source object's `hasX()` function returned **false**. On version 1.5.2, if `hasX()` is **false**, the field `X` is updated to **null**.

The sample code below shows this problem:

```java
public class TestMapper {

    public static class ObjectUpdateDTO {
        private final String field;

        public ObjectUpdateDTO(String newField) {
            this.field = newField;
        }

        public String getField() {
            return field;
        }

        public Boolean hasField() {
            return false;
        }
    }

    public static class ObjectDTO {
        private String field = "field";

        public String getField() {
            return field;
        }

        public void setField(final String newField) {
            this.field = newField;
        }
    }

    @Mapper
    public interface ObjectMapper {
        ObjectDTO update(@MappingTarget ObjectDTO objectDTO, ObjectUpdateDTO objectUpdateDTO);
    }

    public static void main(String[] args) {
        String field = "field";
        ObjectDTO objectBeforeMapping = new ObjectDTO();
        objectBeforeMapping.setField(field);

        String newField = "newField";
        ObjectUpdateDTO objectUpdateDTO = new ObjectUpdateDTO(newField);

        ObjectMapper mapper = Mappers.getMapper(ObjectMapper.class);
        ObjectDTO objectAfterMapping = mapper.update(objectBeforeMapping, objectUpdateDTO);

        System.out.printf("Null: %b", null == objectAfterMapping.getField());
    }
}
```

Version 1.4.2 wouldn't update `field`, because `ObjectUpdateDTO::hasField` returned **false**. So the output would be `Null: false`. On version 1.5.2, `field` is updated to **null**, and the output is `Null: true`.

**Comment by vitorcezli** [comment]
Here is the code generated on 1.5.2:

```java
public class TestMapper$ObjectMapperImpl implements TestMapper.ObjectMapper {

    @Override
    public TestMapper.ObjectDTO update(TestMapper.ObjectDTO objectDTO, TestMapper.ObjectUpdateDTO objectUpdateDTO) {
        if ( objectUpdateDTO == null ) {
            return objectDTO;
        }

        if ( objectUpdateDTO.hasField() ) {
            objectDTO.setField( objectUpdateDTO.getField() );
        }
        else {
            objectDTO.setField( null );
        }

        return objectDTO;
    }
}
```

And here is the code on 1.4.2:

```java
@Component
public class TestMapper$ObjectMapperImpl implements ObjectMapper {

    @Override
    public ObjectDTO update(ObjectDTO objectDTO, ObjectUpdateDTO objectUpdateDTO) {
        if ( objectUpdateDTO == null ) {
            return null;
        }

        if ( objectUpdateDTO.hasField() ) {
            objectDTO.setField( objectUpdateDTO.getField() );
        }

        return objectDTO;
    }
}

```

**Comment by filiphr** [comment]
To be honest, I am not sure why the generated code in 1.4 doesn't have the `else` check. It is actually a bug that fact that the `else` branch is missing in 1.4. We have `Mapper#nullValuePropertyMappingStrategy` and `BeanMapping#nullValuePropertyMappingStrategy` which has a default value of `NullValuePropertyMappingStrategy.SET_TO_NULL`, which means that if the source is not present the target has to be set to `null`.

This should work on 1.4 as well. In order to achieve what you are looking for you will need to use `@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)`

**Comment by vitorcezli** [comment]
Hi @filiphr, thanks for your response. But I have another question related to this issue. In my application, I used the presence check to indicate if I should update a field `X` despite whether this field is *null* or defined on source. For example, consider these situations:

1. `source.X` is not null is `hasX == true` -> `target.X` is updated;
2. `source.X` is not null is `hasX == false` -> `target.X` is not modified;
3. `source.X` is null is `hasX == true` -> `target.X` is updated to null;
4. `source.X` is null is `hasX == false` -> `target.X` is not modified.

In version 1.4.2 these situations were possible due to the buggy absence of the `else` branch. Using `@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)` as you suggested, the third situation will fail if I am not wrong.

So my question is if there is a solution on version 1.5.2 that is valid for all these situations.
