### ISSUE TITLE
Ability to disable @Generated annotations in generated sources

### ISSUE THREAD

**Issue by mspronk** [mapstruct/mapstruct#2918]
I've run into the situation where I think it would be valuable to suppress the `@Generated` annotations that are added to generated sources.

The specific use case is: I want to ensure that code coverage also takes into account the coverage of the implementations of the MapStruct mappers. Unfortunately Jacoco will ignore sources annotated with `@Generated`, and MapStruct can not be configured to omit these annotations.

I would like to implement a flag that allows the `@Generated` annotations to be suppressed for generated sources. (Using a similar mechanism that is currently already in place to suppress the timestamps inside of this annotation (`suppressGeneratorTimestamp`).

The property I would propose could be titled `suppressGeneratedAnnotation` (boolean)

I don't see the downside to adding this option and allowing this suppression. But I'd be interested to hear if there are any counter arguments, or better suggestions to accomplish my use case.

Thanks,
Martijn

**Comment by filiphr** [comment]
@mspronk this issues goes in direct contradiction to #1574. People there are complaining that Jacoco is not ignoring the generated sources. As far as I know both `javax.annotation.Generated` and `javax.annotation.processing.Generated` have a source retention policy. This means that they are not visible in the bytecode and the runtime reflection API.

Having a flag that would disable the annotation is OK, but I wanted to clear out misunderstandings with the code coverage.

**Comment by mspronk** [comment]
Thanks @filiphr for point out that discussion. I'm going to take a more in-depth look at this to make sure I'm not just making the assumption it's ignoring the generated classes because of the annotation.

**Comment by filiphr** [comment]
Have a look at https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/. Seems like Sonarqube automatically ignores files defined in `.gitignore` and the `target` or `build` folder is most definitely there.
