### ISSUE TITLE
Upgrade from 1.4.1 to 1.5.2 broke primitive to wrapper classes mapping 

### ISSUE THREAD

**Issue by danjee** [mapstruct/mapstruct#2921]
We had a mapper that mapped `Integer` to `int` properties from an internal model to a dto (method1). In the same mapper we had a method that mapped from Integer to Short(method2). This method was used in an expression on a different mapping method(method3). After upgrading to 1.5.2 that method Integer->Short (method2) is now used instead of generating a proper Integer to int mapping like it did in 1.4.2(for method1). 
This is bad for values that uses more than 16 bits and very dangerous as it can pass a lot of tests.
Is there an annotation that can be put on a method to restrict it to be used only on expressions and not be picked up by mapstruct just by types?
Thanks

**Comment by Zegveld** [comment]
related to: #2840 and #1216

**Comment by filiphr** [comment]
This is not the first issue we are seeing with the more strict lookups. We should investigate what actually broke this and fix it in a new 1.5 release

**Comment by filiphr** [comment]
I am happy to announce that we have managed to find the root cause for this problem and we have a pending fix in #3032
