### ISSUE TITLE
Make a qualifiedBy that will accept a method reference

### ISSUE THREAD

**Issue by almogtavor** [mapstruct/mapstruct#2926]
I’d like to be able to achieve the `qualifiedByName` behavior but not use strings for referencing my functions. Is there any possibility of enabling the option of passing the method’s actual reference instead of its string-based name?

I'd like to achieve the following behavior:
```java
@Mapper
public interface MovieMapper {

     @Mapping( target = "title", qualifiedBy = this.uppercase)
     GermanRelease toGerman( OriginalRelease movies );

     public String uppercase(String title) {
           return title.upper();
     }
}
```

Instead of:
```java
@Mapper
public interface MovieMapper {

     @Mapping( target = "title", qualifiedByName = "uppercase")
     GermanRelease toGerman( OriginalRelease movies );

     @Named("uppercase")
     public String uppercase(String title) {
           return title.upper();
     }
}
```

I think that the other available option of:
```java
@Mapper( uses = Titles.class )
public interface MovieMapper {
     GermanRelease toGerman( OriginalRelease movies );
}
```
is nice but that does not exactly work well when mapping functions get reused. The annotation-based workaround doesn't feel natural either.

**Comment by Zegveld** [comment]
java does not support this. 
See this stackoverflow question: https://stackoverflow.com/questions/44291122/how-do-i-pass-a-method-to-an-annotation-using-java-8 
Also according to the spec this is not possible: https://docs.oracle.com/javase/specs/jls/se18/html/jls-9.html#jls-9.6.1

**Comment by filiphr** [comment]
As @Zegveld pointed out. Java does not allow passing method references to annotations. The annotation elements must be constant values.

To be honest I fail to understand why the annotation based approach doesn't work for you.

Using `@Named` and `qualifiedByName` works perfectly well. If you need auto completions, I would suggest raising a change request in the [MapStruct IntelliJ plugin](https://github.com/mapstruct/mapstruct-idea).

Using the annotation passed approach might work for you and you will have auto completion automatically.

In your example it will look like:

```java
@Mapper
public interface MovieMapper {

     @Mapping( target = "title", qualifiedBy = UpperCase.class)
     GermanRelease toGerman( OriginalRelease movies );

     @UpperCase
     public String uppercase(String title) {
           return title.upper();
     }
}

@Qualifier
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.CLASS)
public @interface UpperCase {
}
```

Closing this since there is nothing more that MapStruct can do about this.

**Comment by almogtavor** [comment]
@filiphr I think this can be improved by implementing what I've suggest but receiving a `Function<?, ?>` instead of a method. The feature I wanted for this issue was the IDE "Go To Definition", and by receiving a class of `Function<?, ?>` we achieve exactly that.

Also I think it's better than the `Mapper(uses=MyClassOfFunctions.class)` since it's much more readable and clear.

**Comment by almogtavor** [comment]
@filiphr I'll raise it for the plugin solution, but that's not ideal since I'd like to have this also for users who don't have the plugin. And I don't exactly understand - Isn't an annotation accept a `Class`, hence it'll accept a `Class` that is an `instanceof Function`?

**Comment by filiphr** [comment]
@almogtavor I am not sure what you don't understand. Did you read the [JLS Spec 9.6.1](https://docs.oracle.com/javase/specs/jls/se18/html/jls-9.html#jls-9.6.1)? A class is `String.class` what you are looking for is a method reference, which is an object. This is java language limitation

**Comment by almogtavor** [comment]
@filiphr I see. Another question if I may. What do you think about giving up on the `@Named("myFunc")` annotation, and instead just rely on the method's real name? e.g. if the func name is `myFunc`, just take it as the reference. I know that this can be complicated for multiclasses support, but even if one would be able to only reference methods from the current interface, it'll add lots of value to the readiness of the code.

**Comment by filiphr** [comment]
>What do you think about giving up on the `@Named("myFunc")` annotation, and instead just rely on the method's real name?

We cannot just give up on that, because it will be a breaking change. However, we could expand it a bit and allow using `@Named` (without the value) and assume the value is the name of the function. This can lead to people mistakenly forgetting to add a name, but I do not think it is that big of a deal. 

Feel free to open an issue for this and provide a PR if this is something that you would like to see.

**Comment by almogtavor** [comment]
@filiphr what about no `@Named` annotation at all? Can't we just provide support for searching the name from the `qualifiedByName`?

**Comment by filiphr** [comment]
That won't work. If a method is available for using then MapStruct will always use that to map between those types. `@Named` should be used when you want a method to be used in a specific explicit case.

e.g.

```
@Mapper 
public interface MyMapper {

    Customer map(CustomerDto source);

    default String uppercase(String value) {
        return value != null ? value.toUpperCase();
    }
}
```

The mapper above will used the `uppercase` method for mapping all strings.

```
@Mapper 
public interface MyMapper {

    @Mapping(target = "firstName", qualifiedByName = "uppercase")
    Customer map(CustomerDto source);

    @Named("uppercase")
    default String uppercase(String value) {
        return value != null ? value.toUpperCase();
    }
}
```

The mapper above will use the `uppercase` method for mapping only the `firstName` the rest of the properties will use the default mapping.
