### ISSUE TITLE
Enable referencing targets and sources by fields references instead of String

### ISSUE THREAD

**Issue by almogtavor** [mapstruct/mapstruct#2927]
I’d like to be able to pass a getter/setter reference to `@Mapping` instead of strings. The thing is that with Strings we can use IDE features like "Go To Declaration".
I'd like to use Mapstruct this way:
```java
@Mapper
public interface MovieMapper {

     @Mapping( target = my.example.setTitle(), source= their.demo.getTitle())
     GermanRelease toGerman( OriginalRelease movies );
}
```

Instead of:
```java
@Mapper
public interface MovieMapper {

     @Mapping( target = "title", source= "title")
     GermanRelease toGerman( OriginalRelease movies );
}
```

In many cases, we won't even need to specify the group, but even when specifying the group for every field, I'm sure lots of people will be glad to use Mapstruct this way.

**Comment by Zegveld** [comment]
java does not support this. 
See this stackoverflow question: https://stackoverflow.com/questions/44291122/how-do-i-pass-a-method-to-an-annotation-using-java-8 
Also according to the spec this is not possible: https://docs.oracle.com/javase/specs/jls/se18/html/jls-9.html#jls-9.6.1

**Comment by filiphr** [comment]
If you want to use IDE features like "Go To Declaration" then I suggest using the [MapStruct IntelliJ Plugin](https://plugins.jetbrains.com/plugin/10036-mapstruct-support) or the [MapStruct Eclipse Plugin](https://marketplace.eclipse.org/content/mapstruct-eclipse-plugin)

**Comment by almogtavor** [comment]
@filiphr didn't know about this. That's awesome (I suggest pointing features of the plugin on relevant places in the docs so more people will get to know it).

**Comment by filiphr** [comment]
That is a good idea @almogtavor. We've created #2928 to check this out.
