### ISSUE TITLE
Improve documentation for `BeanMapping#ignoreByDefault`

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#2929]
According to #2044 it seems like a google search for "mapstruct ignore all field except one" does not return results from the documentation.

We should improve the docs.

**Comment by metin-durmaz** [comment]
This annotation does not work as expected, and all fields are mapped unless we use ignore=true. (Version 1.5.5.Final)

**Comment by thunderhook** [comment]
> This annotation does not work as expected, and all fields are mapped unless we use ignore=true. (Version 1.5.5.Final)

Hi @metin-durmaz. 

Please create a new issue instead of reviving an old one.
Please try `1.6.0.Beta1` or even `1.6.0.Beta2`, there have been some changes that may have solved your problem.

If it still exists, please provide a minimally reproducible example.

Thanks in advance!
