### ISSUE TITLE
lombok @Builder with property addXYZ performs no mapping

### ISSUE THREAD

**Issue by typekpb** [mapstruct/mapstruct#2940]
Combination of lombok's `@Builder` property with property named `add...` results in lack of mapping using generated Mapper.

Input:
```
import lombok.Builder;
import lombok.Data;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Data
@Builder
public class Foo {

    private String addXYZ;

    @Mapper
    public interface FooMapper {
        FooMapper INSTANCE = Mappers.getMapper(FooMapper.class);

        Foo map(Foo source);
    }

}
```

Actual mapper:
```
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-07-23T22:50:40+0200",
    comments = "version: 1.5.2.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.2.jar, environment: Java 11.0.15 (Amazon.com Inc.)"
)
public class Foo$FooMapperImpl implements Foo.FooMapper {

    @Override
    public Foo map(Foo source) {
        if ( source == null ) {
            return null;
        }

        Foo.FooBuilder foo = Foo.builder();

        return foo.build();
    }
}
```
Expected mapper:

* property `addXYZ` should be copied in mapper implementation

**Comment by filiphr** [comment]
MapStruct has the concept of `adders` for collections. A method that looks looks like `addXYZ` is treated as an adder for the property `XYZ`.

Have a look at https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-895572151 and https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-898872064.

Closing this issue now, with the same comment as in #2533. If someone has an idea for how this can be solved please let us know

**Comment by mmcLine** [comment]
> MapStruct 有`adders`集合的概念。看起来像的方法`addXYZ`被视为属性的加法器`XYZ`。
> 
> 看看[#2533（评论）](https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-895572151)和[#2533（评论）](https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-898872064)。
> 
> [现在关闭这个问题，使用与#2533](https://github.com/mapstruct/mapstruct/issues/2533)中相同的评论。如果有人知道如何解决这个问题，请告诉我们

Whether it can be based on filed name equal addXYZ ？
