### ISSUE TITLE
Support for Jakarta @ApplicationScoped is missing

### ISSUE THREAD

**Issue by jvissers** [mapstruct/mapstruct#2950]
https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#bean_defining_annotations defines a bunch of bean defining annotations. 

Prior to Jakarta, 'cdi' component model on a mapper resulted in an @ApplicationScoped implementation class, which could get properly resolved.

However, with Jakarta CDI spec 3.0, @ApplicationScoped no longer 'sits' in javax. but in jakarta. The result of this is that mapstruct cannot be used in such an arrangement.

**Comment by sjaakd** [comment]
Hmm. That's ugly. I guess there's a reason for this.

@filip i guess we can detect which package @ApplicationScope resides
automatically / early and pass that along?



Op di 2 aug. 2022 00:16 schreef Jan Vissers ***@***.***>:

**Comment by filiphr** [comment]
Thanks for raising this @jvissers. We only adapted the `jsr330` component model to be able to work with Jakarta. We didn't look into the CDI implementation.

We need to provide one new implementation of the [`CdiComponentProcessor`](https://github.com/mapstruct/mapstruct/blob/main/processor/src/main/java/org/mapstruct/ap/internal/processor/CdiComponentProcessor.java). e.g. add `cdiJakarta` as a component model. And also adapt the current implementation to use the `jakarta` namespace if the classes from the javax namespace are not there. In a same way as it is done in the [`Jsr330ComponentProcessor`](https://github.com/mapstruct/mapstruct/blob/main/processor/src/main/java/org/mapstruct/ap/internal/processor/Jsr330ComponentProcessor.java).

@jvissers would you be interested in providing this functionality?

**Comment by jvissers** [comment]
@filiphr - I resolved the issue locally by adding a component processor, and that works. So, yeah - I'm happy to share that with the community.

**Comment by jvissers** [comment]
For my project - here is what I did:

- created a sub-module for this
- added this class, dependency on `mapstruct-processor`

```
public class CustomCDIComponentProcessor extends AnnotationBasedComponentModelProcessor {

  @Override
  protected String getComponentModelIdentifier() {
    return "jakarta-cdi";
  }

  @Override
  protected List<Annotation> getTypeAnnotations(Mapper mapper) {
    return Collections.singletonList(
        new Annotation(getTypeFactory().getType("jakarta.enterprise.context.ApplicationScoped")));
  }

  @Override
  protected List<Annotation> getMapperReferenceAnnotations() {
    return List.of(new Annotation(getTypeFactory().getType("jakarta.inject.Inject")));
  }

  @Override
  protected boolean requiresGenerationOfDecoratorClass() {
    return false;
  }

  @Override
  protected boolean additionalPublicEmptyConstructor() {
    return true;
  }
}
```

- Add this class to META-INF/services/org.mapstruct.ap.internal.processor.ModelElementProcessor
- create a JAR from it

In the projects that needed to consume this:

- changed compiler section to:

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <!-- We can enable this to see what is missing -->
                        <!-- But for now disable Mapstruct unmapped fields -->
                        <compilerArg>
                            -Amapstruct.unmappedTargetPolicy=IGNORE
                        </compilerArg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${version.lombok}</version>
                        </path>
                        <path>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>${version.lib.hibernate}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${version.mapstruct}</version>
                        </path>
                        <path>
                            <groupId>foo.project</groupId>
                            <artifactId>foo-mapstruct-extensions</artifactId>
                            <version>${version.foo-mapstruct-extensions}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
```
- added the following dependency to my project, in order for Intellij to also apply annotation processing correctly

```
<dependencies>
          <dependency>
            <!-- So that Intellij picks up our extension for annotation processing -->
            <groupId>foo.project</groupId>
            <artifactId>foo-mapstruct-extensions</artifactId>
            <version>${version.foo-mapstruct-extensionst}</version>
            <optional>true</optional>
        </dependency>
</dependencies>
```

- changed @Mapper annotation to use model = `jakarta-cdi`

**Comment by edeandrea** [comment]
Hi @filiphr any idea when this might make it into a Mapstruct release? It is a blocker for anyone who wants to use Mapstruct in an EE9 environment and is also using a CDI-based runtime.

See https://github.com/mapstruct/mapstruct/pull/2970#issuecomment-1442311526
