### ISSUE TITLE
Issue with Lombok's FieldNameConstants for Target

### ISSUE THREAD

**Issue by TechnicalRhino** [mapstruct/mapstruct#2951]
- [x] Is this an issue (and hence not a question)? 

In mappers getting this error when using it with Lombok's FieldNameConstants for Mapping Target.

```Target property "<error>" must not be mapped more than once.```

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by filiphr** [comment]
This is a known limitation. Please check the MapStruct interop in the documentation for the `FieldNameConstants` https://projectlombok.org/features/experimental/FieldNameConstants.

If you want to know more have a look at https://github.com/projectlombok/lombok/issues/2991 and https://github.com/mapstruct/mapstruct/issues/2609.

**Comment by genglongsir** [comment]
我目前使用的依赖是
mapstruct-processor:1.5.2.final
mapstruct:1.5.2.final
lombok:1.18.24

maven编译插件的配置是
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapstruct.version}</version>
						</path>
						<path>						
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>${lombok.mapstruct.binding.version}</version>
						</path>
					</annotationProcessorPaths>
当我在映射接口中使用
@Mapping(target = Entity.Fields.entityProperty, source = "dtoProperty")
时，有如下报错信息
no property named "error" 
解决方式是： 将maven编译插件的配置调整一下
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapstruct.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>						
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>${lombok.mapstruct.binding.version}</version>
						</path>
					</annotationProcessorPaths>
如果在映射接口中需要使用多个 @Mapping，那么还需要用@Mappings把多个@Mapping包起来

**Comment by r6hk** [comment]
> 我目前使用的依赖是 mapstruct-processor:1.5.2.final mapstruct:1.5.2.final lombok:1.18.24
> 
> maven编译插件的配置是
> 
> ![Image](https://github.com/user-attachments/assets/a78bd705-facc-4628-933c-8deb7bc80e13)
> 
> 当我在映射接口中使用 [@mapping](https://github.com/mapping)(target = Entity.Fields.entityProperty, source = "dtoProperty") 时，有如下报错信息 no property named "error" 解决方式是： 将maven编译插件的配置调整一下
> 
> ![Image](https://github.com/user-attachments/assets/0eda40f1-7d4c-4388-a7cc-35bc71a0d4a1)
> 
> 如果在映射接口中需要使用多个 [@mapping](https://github.com/mapping)，那么还需要用[@mappings](https://github.com/mappings)把多个[@mapping](https://github.com/mapping)包起来

谢谢老哥解决了这个困扰了我一上午的问题
