### ISSUE TITLE
Feature request, additional global defaults

### ISSUE THREAD

**Issue by andye2004** [mapstruct/mapstruct#2953]
I was wondering if there was a reason that the null value mapping strategies were not added to the Options class in order to override the built-in defaults? If there is no reason preventing this from being done I was hoping it could be added as feature moving forward?

I'm specifically interested in the`nullValueIterableMappingStrategy` and `nullValueMapMappingStrategy` as accepted best practice in this instance is to return empty collections and maps as opposed to null values. Basically I want to set this policy globally instead of via the currently available options.

Cheers, Andy.

**Comment by filiphr** [comment]
We've been reluctant to expose a lot of properties through the `Options` as previously it hasn't worked smoothly in IDEs.

However, if there is a request from the community about a specific property being added to the options I think that we would be willing to accept it. Would you be interested in providing a PR that will add the different properties @andye2004?

**Comment by andye2004** [comment]
Hi @filiphr, I don't mind taking a stab at this, before I do though, I'm wondering if you would want the feature to be overridable at the `MappingConfig` and `Mapper` levels, similar to the `mapstruct.unmappedTargetPolicy`, or system wide, similar to the `mapstruct.disableBuilders`

**Comment by filiphr** [comment]
>I don't mind taking a stab at this, before I do though, I'm wondering if you would want the feature to be overridable at the MappingConfig and Mapper levels, similar to the mapstruct.unmappedTargetPolicy, or system wide, similar to the mapstruct.disableBuilders

You are going to add options that already exist in `MappingConfig` and `Mapper`, right? If you add your changes to `DefaultOptions` then everything would be overridable in a consistent manner (adding some tests for it though is always good 😉)

>Oh, and to your comment re smooth operation in IDEs, does this relate to the plugins that highlight things like unmapped properties etc?

This relates to IDEs not picking up the compiler arguments that have been defined in Maven or Gradle configuration and thus leading to generating mappers that are not the same as generated from the command line. It doesn't relate to the Plugins that we provide

**Comment by filiphr** [comment]
I've had some time and I worked on this during a Hackergarten  event in Zurich

**Comment by filiphr** [comment]
I've reopened this. We'll close it once the PR gets merged
