### ISSUE TITLE
(Partent -> Child -> Child) not able to model with JpaContext MapStruct

### ISSUE THREAD

**Issue by asicode24** [mapstruct/mapstruct#2956]
With JpaContext Class logic, We are not able to model the Parent->child1->child2 relation. Mapstruct generated implemented class logic works only if both child1 and child2 are the children of the Parent

**Comment by filiphr** [comment]
I do not understand the issue. MapStruct does not have any concept about JPA. I would suggest asking a question on [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) or our [Discussions](https://github.com/mapstruct/mapstruct/discussions)

**Comment by asicode24** [comment]
Hi Filip,

Here is an example, i am refering to in your github repo.

https://github.com/mapstruct/mapstruct-examples/blob/main/mapstruct-jpa-child-parent/src/main/java/org/mapstruct/jpa/JpaContext.java

Best Regards,
Asif

**Comment by filiphr** [comment]
This was answered in https://github.com/mapstruct/mapstruct/discussions/2978#discussioncomment-3441902
