### ISSUE TITLE
-Amapstruct.unmappedTargetPolicy=ERROR ignoring only one doesn't work when there are multiple fields

### ISSUE THREAD

**Issue by 847689421** [mapstruct/mapstruct#2964]
Please ask.
I configured `-Amapstruct.unmappedTargetPolicy=ERROR` in pom.xml. `com.shop.dto.ShopDetailWithEcommerceInfoDto.EcommerceInfoDto` has three fields that are not in ShopDetailEcommerceInfoDo. I only ignored one fields in the `convertFrom`method, and there are two other fields that I did not ignore, but I did not receive an error message when I compiled the code, and the compilation passed. Is there something wrong with my usage?
```java
@Mapper
public interface ShopDetailWithEcommerceInfoDtoStructMapper {

    @Mapping(target = "shopId", source = "shopDetail.shopId")
    @Mapping(target = "createTime", source = "shopDetail.createTime")
    @Mapping(target = "updateTime", source = "shopDetail.updateTime")
    @Mapping(target = "ecommerceInfo", source = "ecommerceInfoDo")
    @Mapping(target = "ecommerceInfo.openingBankBranchAreaName", ignore = true)
    ShopDetailWithEcommerceInfoDto convertFrom(ShopDetail shopDetail, ShopDetailEcommerceInfoDo ecommerceInfoDo);
}
```

**Comment by chenzijia12300** [comment]
I think this is probably because mapstruct does not warn or report errors for unmatched fields in the target object's nested property objects.
If you need to warn or report errors for unmatched properties in the nested object, you may need to manually declare the methods of the nested object


Maybe something like this
`
ecommerceInfo map(ShopDetailEcommerceInfoDo ecommerceInfoDo)
`

**Comment by filiphr** [comment]
When using nested target mappings and defining custom mappings then MapStruct is not going to use the defined `unmappedTargetPolicy` for that mapping.

I would suggest that you create an intermediate default method for this:

e.g.

```java
@Mapper
public interface ShopDetailWithEcommerceInfoDtoStructMapper {

    @Mapping(target = "shopId", source = "shopDetail.shopId")
    @Mapping(target = "createTime", source = "shopDetail.createTime")
    @Mapping(target = "updateTime", source = "shopDetail.updateTime")
    @Mapping(target = "ecommerceInfo", source = "ecommerceInfoDo")
    ShopDetailWithEcommerceInfoDto convertFrom(ShopDetail shopDetail, ShopDetailEcommerceInfoDo ecommerceInfoDo);

    @Mapping(target = "openingBankBranchAreaName", ignore = true)
    EcommerseInfoDto convetFrom(ShopDetailEcommerceInfoDo ecommerceInfoDo);
}
```
