### ISSUE TITLE
Two typo questions？

### ISSUE THREAD

**Issue by Qomolang** [mapstruct/mapstruct#2974]
the first question
 in 2.4 "any processor options can be passed using an options element", but there is no "options element" in Maven, is it "compilerArgs"？

And the second question
in 10.10 the second note, a pair of bracket is missed. it should be
"Some types of mappings (collections, maps), in which MapStruct is instructed to use a getter or adder as target accessor (see CollectionMappingStrategy)"
rather than
"Some types of mappings (collections, maps), in which MapStruct is instructed to use a getter or adder as target accessor see CollectionMappingStrategy"

**Comment by filiphr** [comment]
Thanks for raising this @Qomolang. I moved it to the MapStruct core project since the documentation is maintained here.

You are right on both questions:

1. Yes it should be `compilerArgs`
2. Yes it needs to be wrapped in brackets.

I've already pushed fix for this
