### ISSUE TITLE
When the same object is copied, the properties are not copied

### ISSUE THREAD

**Issue by yzhsss** [mapstruct/mapstruct#2981]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/20329077/185832854-c013a326-6eee-42fb-b894-e3d2847084b9.png">

<img width="825" alt="image" src="https://user-images.githubusercontent.com/20329077/185832733-9c007779-c26c-4f45-bca3-877ea072b7f1.png">
When the same object is copied, the properties are not copied

**Comment by filiphr** [comment]
I see that you already asked a question in a discussion #2980. Please do not cross post.
