### ISSUE TITLE
Support for defining Javadoc in the generated mapper implementation

### ISSUE THREAD

**Issue by lehphyro** [mapstruct/mapstruct#2987]
Javadoc validation checks generated code by default and generates warnings for missing tags on generated code.
It could be resolved by copying javadoc into the generated code because simply ignoring generated code causes other issues such as missing types.

**Comment by Zegveld** [comment]
Javadoc is inherited.
A method that does not have any javadoc but is overridden has the same javadoc as the super method.

Which javadoc validation tool are you using that it doesn't pick that up, or are there requirements which result in that you must restate the javadoc when overriding a method?

for example:
```
interface A {
  /**
   * my javadoc
   * @param myParam some text
   */
   void myMethod(String myParam);
}

class B implements A {
    @Override
    void myMethod(String myParam) {
        // does something.
    }
}
```

The javadoc of `B.myMethod(String myParam)` is the same as described in the interface `A`:
```
  /**
   * my javadoc
   * @param myParam some text
   */
```

However generation of javadoc for the implementation class itself might be needed.
Can you give code examples with what exactly of the generated code receives the warnings.

**Comment by lehphyro** [comment]
I'm attaching a test project.
[javadoc-test.zip](https://github.com/mapstruct/mapstruct/files/9426418/javadoc-test.zip)

**Comment by Zegveld** [comment]
Thanks for adding the example.

```
[WARNING] Generating *****\javadoc-test\target\apidocs\com\test\TestMapperImpl.html...
[WARNING] *****\javadoc-test\target\generated-sources\annotations\com\test\TestMapperImpl.java:10: warning: no comment
[WARNING] public class TestMapperImpl implements TestMapper {
[WARNING] ^
```

It seems that it is the javadoc on the implementation class that is the issue, and not on the methods.
It doesn't always make sense to copy this from the source `interface`/`abstract class`. 
Perhaps a default generation of something like this would suffice:
```
/**
 * Implementation of {@link TestMapper}
 */
```

wdyt @filiphr , @lehphyro ?

**Comment by lehphyro** [comment]
Sure, works for me.

**Comment by filiphr** [comment]
Currently we aren't generating any comments in the. The proposed javadoc sounds a bit obsolete, it brings no value to the generated code.

@lehphyro why can't you configure your javadoc generation to ignore missing comments?

**Comment by lehphyro** [comment]
Because that would ignore actual violations, the only way I found to ignore MapStruct generated code is to put generated code in a separate package and configure javadoc to ignore that package but it's not nice to put generated mappers in a different package.

**Comment by filiphr** [comment]
Starting from the next MapStruct version you are going to be able to annotate the generated code with whatever you want. In addition to that, starting from Java 18 you can sue `@SuppressWarnings("doclint")` to ignore doc lint errors (See https://docs.oracle.com/en/java/javase/18/docs/specs/man/javadoc.html#suppressing-messages).

All of this means that you can do something like:

```java
@Mapper
@AnnotateWith(
        value = SuppressWarnings.class,
        elements = {
                @AnnotateWith.Element(strings = "doclint:missing")
        }
)
public interface TestMapper {
}
```

which will generate 

```java
@SuppressWarnings(value = "doclint:missing")
public class TestMapperImpl implements TestMapper {
}
```

and you will no longer have warnings.

-----

Having said all of that and having thought about this a bit more. What would be something that we can consider is to add an additional option to the `@Mapper` that would allow you to define the implementation javadoc. e.g.

```java
@Mapper(implementationJavadoc = "Implementation of {@link TestMapper}")
public interface TestMapper {
}
```

which will generate 

```java
/**
 * Implementation of {@link TestMapper}
 */
public class TestMapperImpl implements TestMapper {
}
```

This however, is something that the MapStruct team is not going to focus on, since we have some other more important things we would like to work on and bring to 1.6. If you @lehphyro or someone else is interested they can provide a PR with this contribution.

**Comment by jccampanero** [comment]
@filiphr I am aware you mentioned it is not a priority, but can I try helping you with this issue or with any other one?

My only concern has to do with the following: how should the provided javadoc string be sanitized in some way in order to prevent errors in the class generation process or even potential security issues?

**Comment by filiphr** [comment]
>@filiphr I am aware you mentioned it is not a priority, but can I try helping you with this issue or with any other one?

You are more than welcome to work on any issue you think you'd like to tackle. Another alternative issue would also be https://github.com/mapstruct/mapstruct/issues/1427, which shouldn't be too difficult.

In any case, if you prefer to work on this one then go ahead.

>My only concern has to do with the following: how should the provided javadoc string be sanitized in order to prevent errors in the class generation process or even potential security issues?

I don't think that we need provide anything special for sanitization. Perhaps we can have a `@Javadoc` annotation and offer the following things:

```java
@Javadoc(
    value = "This is the description",
    authors = { "author1", "author2" },
    deprecated = "Use {@link OtherMapper} instead",
    since = "0.1"
)
```

this can then generate something like:

```java
/**
* This is the description
* 
* @author author1
* @author author2
* 
* @deprecated Use {@link OtherMapper} instead
* @since 0.1
*/
```

We are basically going to pass whatever is defined in the javadoc. In the future we could extend the `@Javadoc` with additional options if people request it.

Apart from what I wrote someone could also write this using Text blocks

```java
@Javadoc(
    """
    This is the description
                   
    @author author1
    @author author2
                   
    @deprecated Use {@link OtherMapper} instead
    @since 0.1
    """
)
```

or plain old strings

```java
@Javadoc("This is the description\n"
                   + "\n"
                   + "@author author1\n"
                   + "@author author2\n"
                   + "\n"
                   + "@deprecated Use {@link OtherMapper} instead\n"
                   + "@since 0.1\n")
```

**Comment by jccampanero** [comment]
Thank you very much for your words @filiphr. 

 I will try to do my best to tackle both issues if you consider it appropriate.

Regarding this one, I agree with you, and using a custom annotation is probably a superior and more extensible solution. I will start working on this from that point of view. I hope I don't bother you too much with my doubts.

Thank you very much again.

**Comment by filiphr** [comment]
>I will try to do my best to tackle both issues if you consider it appropriate.

For sure, feel free to work on both. I've assigned this one to you

**Comment by jccampanero** [comment]
@filiphr Just an update: I've been working on the issue and I think the work is well under way. Please, sorry for the delay, these couple of weeks I have been very busy at work and had very little sparse time even at night.

**Comment by jccampanero** [comment]
It's been hard times for me, but despite that, I can only say sorry for the time in providing a solution to the problem.

I provided an initial implementation of the suggested functionally and created a related PR.

Please, don't hesitate to contact me if additional work should be done.

**Comment by filiphr** [comment]
>It's been hard times for me, but despite that, I can only say sorry for the time in providing a solution to the problem.

@jccampanero there is really not a reason to say sorry for taking your time working on an open source project. As you can see we are also not the fastest in reviewing. We are all doing this in our free times and because we enjoy it. So take as much time as you want, the project won't go anywhere 😉
