### ISSUE TITLE
Adhere to Java specifications - Overriding default methods in interface via decorator

### ISSUE THREAD

**Issue by barkeldiho** [mapstruct/mapstruct#2988]
In Java it is possible to override default methods in interfaces. This mechanism seems not to be picked up by MapStruct when it comes to overriding methods in decorator implementations. The following code leads to a missing method in the generated mapper implementation.

Mapper interface:
````java
@MapperConfig(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.WARN, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
@DecoratedWith(MyDecorator.class)
public interface MyMapper {
    default Object2 toObject(final Object1 object1) {
        return null;
    }
}
````
and a Decorator as follows:

````java
@Component
public abstract class MyDecorator implements MyMapper {
    @Override
    public Object2 toObject(final Object1 object1) {
       ...
    }
}
````

Result is a missing implementation for `toObject()`. This is in MapStruct 1.5.2.

**Why is this important?** I am having troubles to use MapStruct for a direct conversion of a self-made DTO to an object from a dependency. I am getting an ambigeous constructor error but can circumvent it by using a default implementation. Since I now have to use a spring bean during the process the implementation needed to be moved to a decorator.

Best, Thomas

**Comment by filiphr** [comment]
>In Java it is possible to override default methods in interfaces.

Yes we are aware that in Java it is possible to override default methods. However, MapStruct by design only generates mappings for abstract methods. Have a look at [Adding custom methods to mappers](https://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods).

>Why is this important? I am having troubles to use MapStruct for a direct conversion of a self-made DTO to an object from a dependency. I am getting an ambigeous constructor error but can circumvent it by using a default implementation

Why do you need to use a decorator for this? Why not just implement the logic you need yoursefl?

e.g.

```
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.WARN, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public abstract MyMapper {

    // You can inject other things in this class

    public Object2 toObject(final Object1 object1) {
        // Do your own logic here
        return null;
    }
}
```
