### ISSUE TITLE
Multi source data conversion error

### ISSUE THREAD

**Issue by liuxiansheng990710** [mapstruct/mapstruct#2997]
> problem code
```java
@Mapper(uses = {CommonsStructConvert.class}, typeConversionPolicy = ReportingPolicy.WARN)
public interface StudentStructConvert {

    StudentStructConvert INSTANCE = Mappers.getMapper(StudentStructConvert .class);
    
    List<StudentDTO> listConvert(List<StudentDTO> sourceDtoOne, List<StudentDTO> sourceDtoTwo)
}
```
> error message
```java
The return type List<StudentDTO> is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
```
> resolvent
  - @ObjectFactory
    - It will be repeatedly called, resulting in an error
    ```java
    @Override
    public List<RPCOrderStatisticsDTO> mergeTargetConvert(List<RPCOrderStatisticsDTO> sourceDtoOne, List<RPCOrderStatisticsDTO> sourceDtoTwo) {
        if ( sourceDtoOne == null && sourceDtoTwo == null ) {
            return null;
        }

        List<RPCOrderStatisticsDTO> list = mergeTargetConvert( sourceDtoOne, sourceDtoTwo );

        return list;
    }
    ```
 @filiphr Is there any solution

**Comment by filiphr** [comment]
@liuxiansheng990710 please do not use the issue tracker to ask questions. If you have a question please use either [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) or [Discussions](https://github.com/mapstruct/mapstruct/discussions).

To answer your questions. when using multiple source parameters the mapping method is treated as a bean mapping method and thus you get the error you have.
