### ISSUE TITLE
Missing import when mapping nested enums

### ISSUE THREAD

**Issue by emat84** [mapstruct/mapstruct#3004]
Even after the recent fixes that went in 1.5.2, I can still reproduce a missing import when mapping an inner Enum to a String.

1.4.2.Final works

1.5.1.Final and 1.5.2.Final don't work

the generated code looks like:

`targetInstance.targetField( Enum.valueOf( Clazz.InnerEnum.class, sourceInstance.getSourceField() ) );`

and will result in `package Clazz does not exist`

**Comment by filiphr** [comment]
I believe that this has already been fixed on main. This looks like a duplicate of #2945. Therefore, I am going to close this one.
