### ISSUE TITLE
@BeforeMapping method invocation is not generated when mapping a child collection using a qualified mapping method

### ISSUE THREAD

**Issue by Blockost** [mapstruct/mapstruct#3006]
- [x] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

As the issue title suggests ☝️ 

I set up a little test case so that you can verify it very easily: https://github.com/Blockost/mapstruct-beforemapping-test-case

All you need to do is clone the repo, download maven dependencies and build the project. It uses mapstruct `v1.5.1.Final` because, for some reasons, maven does not seem to find `v1.5.2.Final` on Maven Central from my side 🤷 

Once done, you should see this:

```java

protected Set<ChildClassDTO> childClassEntitySetToChildClassDTOSet(Set<ChildClassEntity> set) {
        Set<ChildClassDTO> target = childClassMapper.beforeMapping( set );
        if ( target != null ) {
            return target;
        }

        if ( set == null ) {
            return null;
        }

        Set<ChildClassDTO> set1 = new LinkedHashSet<ChildClassDTO>( Math.max( (int) ( set.size() / .75f ) + 1, 16 ) );
        for ( ChildClassEntity childClassEntity : set ) {
            set1.add( childClassMapper.toDTOWithoutQualifier( childClassEntity ) );
        }

        return set1;
    }

    protected Set<ChildClassDTO> childClassEntitySetToChildClassDTOSet1(Set<ChildClassEntity> set) {
       ///////////////////////////////////////////// 
       // Method invocation is missing here //
      /////////////////////////////////////////////
        if ( set == null ) {
            return null;
        }

        Set<ChildClassDTO> set1 = new LinkedHashSet<ChildClassDTO>( Math.max( (int) ( set.size() / .75f ) + 1, 16 ) );
        for ( ChildClassEntity childClassEntity : set ) {
            set1.add( childClassMapper.toDTOWithQualifier( childClassEntity ) );
        }

        return set1;
    }

```

Any help would be appreciated. If this is qualified as a bug with no workaround, I'm willing to take some time and fix it with a PR if I receive a little help/guidance from you guys 🙏

**Comment by Zegveld** [comment]
the reason is that it is searching for an `@BeforeMapping` that is `qualifiedByName = "qualifier"`.
That one cannot be found, and therefor it doesn't use a beforeMapping.

You can add a method that just passes it on to the actual before method for example:
```
    @Named("qualifier")
    @BeforeMapping
    default Set<ChildClassDTO> beforeMappingQualified(java.util.Collection<ChildClassEntity> collection) {
        return beforeMapping(collection);
    }
```

hope this helps.

**Comment by Blockost** [comment]
Hi @Zegveld, yes it totally helps ! It seems to be the way to do it 💪 

I guess I was confused by [the docs](https://mapstruct.org/documentation/stable/api/org/mapstruct/BeforeMapping.html) which states:

> All before-mapping methods that can be applied to a mapping method will be used

but still, qualifiers need to match.

Thanks for your help !
