### ISSUE TITLE
Mappings are not generated as part of intelliJ build

### ISSUE THREAD

**Issue by peterlitvak** [mapstruct/mapstruct#3014]
IntelliJ: IU-222.3739.54
MapStrict is added as a project dependency as:
```
<dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>1.3.1.Final</version>
            <optional>true</optional>
        </dependency>
```

And configured as a single annotation processor in IntelliJ.

Upon on "Rebuild Project" the empty directory is generated for the mappers.

**Comment by filiphr** [comment]
We haven't had problems with IntelliJ for a while. I would suggest updating MapStruct and checking if everything works as expected. There have some issues in our older versions that have been fixed for a while
