### ISSUE TITLE
SubclassMapping doesn't generate mapping methods

### ISSUE THREAD

**Issue by bilak** [mapstruct/mapstruct#3018]
- [ x] Is this an issue (and hence not a question)? 

Sorry for [crossposting](https://stackoverflow.com/questions/73648381/deepclone-of-same-class-with-subclassmapping) but I just want to reference this issue somewhere in code.

So is it really necessary to include mapping methods for all mentioned subclasses even when we have them in `SubclassMapping` annotation? I initially thought that this is the issue of `DeepClone` but it seems like it's problem of `SubclassMapping` and probably the same type in input/output (source/target) of the method.

**Comment by Zegveld** [comment]
did you try the `@Mapper(mappingControl = DeepClone.class)` as described here: https://mapstruct.org/documentation/stable/api/org/mapstruct/control/MappingControl.html

By default mapstruct will do as few mapping actions as possible.

**Comment by bilak** [comment]
yep, tried that also.

I wasn't looking into mapstruct implementation. Is it somehow possible at compile time get all descendants of given parent class? I mean if we have abstract class or interface, are we able to get all implementations and add them dynamically if we know they are of the same type. So basically doing deepclone of the same class?

**Comment by Zegveld** [comment]
This is not possible because the only classes that we are notified of are the ones that are in the current build. So any class outside this build is only spotted because something is referencing it.

Perhaps for `sealed` classes this would be doable, because then the class references to those classes.

**Comment by bilak** [comment]
> This is not possible because the only classes that we are notified of are the ones that are in the current build. So any class outside this build is only spotted because something is referencing it.

Does this mean that if we have everything on classspath in the build, that we could potentially get all those classes? I mean is there some extension point how to do this?
