### ISSUE TITLE
Globally ignore an attribute all DTOs inherit from a base class

### ISSUE THREAD

**Issue by camproto** [mapstruct/mapstruct#3021]
Is this an  question

I have a base class Nachricht from where several dozens DTOs inherit. For all are mappers with mapstruct defined. All with special mapping configurations. To not forget to configure a property within these mappings I use for all the mapping strategy  mapstruct.unmappedTargetPolicy=ERROR.

Now I have the need to introduce on the base class several convenience getter and setter methods. 

All these individual mapping definitions now need the enhancement to ignore these convenience getter and setter methods. This is copying the same @Mapping(ignore=true) over and over again. 

Is there a more clever way of doing it? 

Actually miss the possibility to centrally configure such ignoreance of an attribute in a mapstruct config and just inherit the mapstruct config with this global attribute ignorance into all mapper classes.

**Comment by Zegveld** [comment]
This is available by creating your own annotation which contains all these `@Mapping` annotations.
[See the documentation for more information.](https://mapstruct.org/documentation/stable/reference/html/#mapping-composition)

**Comment by filiphr** [comment]
Closing since it has been explained how this can be achieved
