### ISSUE TITLE
nullValueCheckStrategy does not work when using expression

### ISSUE THREAD

**Issue by nettadhp** [mapstruct/mapstruct#3034]
### Expected behavior

```java
@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface CarMapper {

 @Mapping(target = "manufacturer", expression = "java(from(car))")
  CarDto carToCarDto(Car car);
}
```
should generate something like

```java
public class CarMapperImpl implements CarMapper {
@Override
public CarDto carToCarDto(Car car) {
   ...
   String manufacturer = from(car);
   if (manufacturer != null)   
   carDto.setManufacturer(from(car));
   ...
 }
}
```

Ie expect to honor `nullValueCheckStrategy` by checking that the result of `from(car)` is not null before setting it.

### Actual behavior

```java
public class CarMapperImpl implements CarMapper {
@Override
public CarDto carToCarDto(Car car) {
  ...
   carDto.setManufacturer(from(car));
}
}
```
There is no null check before setting the manufacturer. 

*Our set method checks for null and throws an NPE when it gets a null value.

### Steps to reproduce the problem

See above description to reproduce

### MapStruct Version

1.5.2.Final

**Comment by filiphr** [comment]
This works as designed. When using `Mapping#expression` none of the other things are applied. In `expression` you can put any java code, there is no way in knowing what we should do a null check for.

I would suggest that you either do it yourself or if you want to rely on MapStruct then I would suggest using `Mapping#source` and using the source parameter.

e.g.

```java
@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface CarMapper {

  @Mapping(target = "manufacturer", source = "car")
  CarDto carToCarDto(Car car);
}
```

**Comment by nettadhp** [comment]
@filiphr not sure I understand why this is as designed. Mapstruct still calls the setter method, it just sets it with the value returned from the expression right? So if the value the expression returns is null, and you have those null check annotations, then the value should not be set. The source would only solve it if the mapping is simple but it's not. There's a calculation that is happening inside the expression and source wouldn't suffice for this. Unless there is some other way which I don't understand.

**Comment by filiphr** [comment]
@nettadhp MapStruct does  a null check on the source value and not on the created value. 

>There's a calculation that is happening inside the expression and source wouldn't suffice for this

I am not sure what you mean by this. Expression is only a shortcut, but you can almost always achieve the same thing with a custom method and / or using a qualifier. In my previous reply there is an example for how you can achieve your example without using `expression`.

**Comment by nettadhp** [comment]
I guess my example wasn't clear enough. Let's say the from method looks like this (and keep in mind this is a super dumb contrived example because my real code is just super complicated and also private for the company I work for, so I hope this will illustrate the problem).
```java
public String manufacturer(Car car) {
   if (car.getYear() > 2020 && "Dodge".equals(car.getManufacturer())) {
         return "New Dodge";
    } else if ("Dodge".equals(car.getManufacturer())) {
       return "Old Dodge";
    } else {
       return car.getManufacturer();  //This value can be null
    }
}
```

Now given the above where that method can return null, how can I prevent carDto from calling `carDto.setManufacturer` when the value is `null`?

**Comment by filiphr** [comment]
Currently we do not have so granular checks. However, what you can do is to use your own custom condition:

```
@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface CarMapper {

    @Mapping(target = "manufacturer", source = "car", conditionQualifiedByName = "hasManufacturer")
    CarDto carToCarDto(Car car);

    @Condition
    @Named("hasManufacturer")
    default boolean hasManufacturer(Car car) {
        return car != null && car.getManufacturer() != null;
    }

    default String manufacturer(Car car) {
        if (car.getYear() > 2020 && "Dodge".equals(car.getManufacturer())) {
            return "New Dodge";
        } else if ("Dodge".equals(car.getManufacturer())) {
            return "Old Dodge";
        } else {
            return car.getManufacturer();  //This value can be null
        }
    }
}

**Comment by nettadhp** [comment]
Nice! I will try that out! However, to me this feels like a workaround. I'm not sure I understand why the logic today doesn't  always check for null before calling the set method when `nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS` is provided? What does it matter how the value is generated, whether via expression, custom method, or 1-1 mapping?

**Comment by filiphr** [comment]
If you read the javadoc of `NullValueCheckStrategy` it talks about dealing with `null` _source_ values. Apart from that this strategy is used for presence checking as well, not just `null` values. e.g. you might have a boolean method that checks if a property has been modified, even with a value of `null` and you might want to set the target to `null` based on that. e.g. in PATCH requests.

**Comment by nettadhp** [comment]
I get it. I just wish there was a way to add the null check to the value returned by an expression before the setter is called. The option you provided is a nice when the logic is fairly simple. But when it's not, it might not be that useful.

**Comment by filiphr** [comment]
>The option you provided is a nice when the logic is fairly simple. But when it's not, it might not be that useful.

I do understand what you mean and it can be a problematic thing. However, currently MapStruct is not designed to work in the way you are expecting. If you want feel free to raise a change request and if there are multiple people that need such a feature they can voice their opinion and we could look into it for a future release.

**Comment by nettadhp** [comment]
Thanks for your feedback!
