### ISSUE TITLE
Would it be possible to add  ElementType.ANNOTATION_TYPE as a target for @ValueMapping?

### ISSUE THREAD

**Issue by heipl-paul** [mapstruct/mapstruct#3037]
### Use case

I write a bunch of mappers for gRPC which suggests `UNSPECIFIED` as a default value for integration with languages that offer the possibility of enum members that were not predefined, and auto-generates `UNRECOGNIZED` (at least in java, it does).

I always want to map both of these with

```java
@ValueMapping(source = "UNSPECIFIED", target = MappingConstants.THROW_EXCEPTION)
@ValueMapping(source = "UNRECOGNIZED", target = MappingConstants.THROW_EXCEPTION)
```

Which, okay, isn't that big of a deal. But since I've been doing a lot of gRPC mappings, I've become accustomed to Mapping Composition. And instead of having a dozen mappings that are all ignoring various gRPC artifact fields, I extract them in their own specific annotation. 

```java
@Retention(RetentionPolicy.CLASS)
@Mapping(target = "mergeFrom", ignore = true)
@Mapping(target = "clearField", ignore = true)
@Mapping(target = "clearOneof", ignore = true)
@Mapping(target = "unknownFields", ignore = true)
@Mapping(target = "mergeUnknownFields", ignore = true)
@Mapping(target = "allFields", ignore = true)
public @interface IgnoreGrpcOnlyFields {
}
```

And then the following for a specific gRpc (proto) class:

```java
@IgnoreGrpcOnlyFields
@Mapping(target = "cityBytes", ignore = true)
@Mapping(target = "provinceBytes", ignore = true)
@Mapping(target = "zipCodeBytes", ignore = true)
// etc ...
public @interface IgnoreAddressGrpcOnlyFields {
}
```

I assume and hope that adding Mapping Composition to \@ValueMapping wouldn't represent a big technical challenge. And right now, the lack of this feature feels inconsistent. 

### Sample code

In the off case that I'm not clear enough, sample code of what I want to do:

```java
@ValueMapping(source = "UNSPECIFIED", target = MappingConstants.THROW_EXCEPTION)
@ValueMapping(source = "UNRECOGNIZED", target = MappingConstants.THROW_EXCEPTION)
public @interface IgnoreGrpcEnumFields {
}
```

```java
@IgnoreGrpcEnumFields
TargetEnum toEntity(SourceGrpcEnum source);
```
### Generated Code

Self evident, it would not change generated code, this only relates to reading the annotation metadata.

### Possible workarounds

Simply adding the individual annotations to each and every GRPC enum.

### MapStruct Version

1.5.2

**Comment by chenzijia12300** [comment]
This looks interesting, can I try to implement it? 😊

**Comment by heipl-paul** [comment]
Thank you for the tip @filiphr, I've not encountered the protobuf spi before, it looks helpful.

Regarding the pull request, I can give it a try, I'll have to look over the code, I'm not familiar with it in the least, I've only ever been an end user. But I'll look into it, how hard can it be? 😅

**Comment by filiphr** [comment]
@heipl-paul seems like @chenzijia12300 already did some work on this issue. @chenzijia12300 in the future, I would suggest waiting a bit before implementing something in order to avoid multiple people working on it.

@heipl-paul it isn't that hard, especially not for this functionality. Anyways, I hope you'll be able to contribute at a different time.

**Comment by chenzijia12300** [comment]
@filiphr I am sorry for my behavior, I will close this pr first, if @heipl-paul doesn't have time to implement it, I will try again
(￣▽￣)"

**Comment by filiphr** [comment]
@chenzijia12300 everything is good. I only wanted to let other people work on things as well. No need to close the PR, you've already implement the logic. Have a look at my review in it. 

If @heipl-paul wants to work on something, we can find something else :)

**Comment by heipl-paul** [comment]
@filiphr Absolutely! Still need a bit of time to familiarise myself with the code, but yeah. This is one of my favorite tools, it would be an honour to help.

**Comment by chenzijia12300** [comment]
@heipl-paul I'm sorry for my rash intervention (⊙﹏⊙)

**Comment by heipl-paul** [comment]
@chenzijia12300 No worries, I can look over your PR and have that as a starting point :P
