### ISSUE TITLE
Setters generation order

### ISSUE THREAD

**Issue by filipeamaral** [mapstruct/mapstruct#304]
# Issue
Generated setters inside conversion method are ordered taking into account the setters order inside target bean source class.
This is a handicap if you have dependencies between target class' attributes when converting beans, e.g.:

* Bean classes A and B: *
```java
public class A {

    private String name;
   
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name= name;
    }
}

public class B {

	private String aName;
	private String name;

	public String getaName() {
		return aName;
	}

	public void setaName(String aName) {
		this.aName = aName;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
```
Code snippet of generated convertion method:
```java
    public B convertAtoB(A source)  {
        if ( source == null ) {
            return null;
        }

        B b = new B();
        b.setaName( applicationConverter.convertName(b.getName()) );
        b.setName( applicationConverter.generateName(source.getName()) );

        return b;
    }
```
As so, there is no way to define that setName must be invoked prior to setaName invocation.
This is useful if there's a dependency between both fields, i.e. what was setted in attribute name, target.getName(), is feeded into setaName for some business logic reason.

# Mapper example
*IMapper:*
```java
@Mapper(uses = ApplicationConverter.class)
public interface IMapper {

	@Mappings({
			@Mapping(target = "name", expression ="java(applicationConverter.generateName(source.getName()))"),
			@Mapping(target = "aName", expression ="java(applicationConverter.convertName(b.getName()))") })
	B convertAtoB(A source);
}
```
*Generated Mapper:*
```java
public class IMapperImpl implements IMapper {

    @Inject
    private ApplicationConverter applicationConverter;

    @Override
    public B convertAtoB(A source)  {
        if ( source == null ) {
            return null;
        }

        B b = new B();
        b.setaName( applicationConverter.convertName(b.getName()) );
        b.setName( applicationConverter.generateName(source.getName()) );

        return b;
    }

}
```
*Application Converter:*
```java
public class ApplicationConverter {
	private static Random random = new Random();

	public String generateName(String sourceName) {
		int ramdomIndex = random.nextInt(sourceName.length());

		return sourceName.substring(ramdomIndex);
	}

	public String convertName(String sourceName) {
		return sourceName.toUpperCase();
	}
}
```
**Note that, in this case, the above snippet applicationConverter.generateName() is not idempotent, i.e. two successive calls with same parameter don't generate the same output.
Another main reason is that, even if applicationConverter.generateName() is idempotent, takes an overhead time that undermines the overall conversion processing time.**

# Solution Proposal
I suggest to implement some kind of dependency feature/member within @Mapping's scope.

* Proposal A
Add *order* member, of int type, to @Mapping.
Lower order numbers come first, higher or absent order numbers come last.
This should support a relaxed numbering mechanism to avoid lower order numbers absence, i.e. if it's only defined an attribute with order number 2, and none with 1, then 2 is the lowest order number (first setter to generate).
This proposal gives more responsibility to the mapper developer but, for complex dependencies, the developer must know how to solve them (see proposal B).

* Proposal B
Add *dependencies* member, of String[ ] type, to @Mapping.
Each @Mapping defines dependencies of target class' attribute to other target class' attributes, e.g.:
@Mapping(source = "name", target = "aName", dependencies = {"name"})
This proposal gives less responsibility to the mapper developer, since the attribute's dependencies are solved by the generator. This is relevant for more complex dependencies, e.g. an attribute that depends on two attributes, and one of those two depends on another one, and so on (engaging this with proposal A would be quite complex). There should be also a validation for dependency cycles, e.g. A depends on B depends on C depends on A.

**Comment by sjaakd** [comment]
@agudian does the above PR solve this issue?

**Comment by agudian** [comment]
Not really, it just stabilizes the ordering that we currently have (by target accessor source order, whenever it is possible for the underlying compiler implementation to determine).

**Comment by sjaakd** [comment]
> Not really, it just stabilizes the ordering that we currently have (by target accessor source order, whenever it is possible for the underlying compiler implementation to determine).

Ah.. its a first step. That's good. I see now.

**Comment by gunnarmorling** [comment]
Right, to solve the issue at hand, a mechanism for explicit user-defined ordering is needed.

Both of @filipeamaral's proposals are sound. I'd go for the `order()` approach, it seems sufficient and easier to implement. Also a user cannot accidentally configure circular dependencies as with the alternative approach. I'll give it a shot.

**Comment by agudian** [comment]
PR was merged to master. Thanks, Gunnar!
