### ISSUE TITLE
Cannot use only BeanMapping#mappingControl 

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#3040]
### Expected behavior

It should be possible to only use `BeanMapping#mappingControl`

### Actual behavior

There is a compile error

### Steps to reproduce the problem

Use `@BeanMapping#mappingControl` on a method

### MapStruct Version

1.5.2

**Comment by filiphr** [comment]
This is an easier good issue that can be implemented by someone from the community. If someone is interested to work on this issue please comment here so that we can assign it to you.

**Comment by chenzijia12300** [comment]
@filiphr Hello, I would like to try

**Comment by filiphr** [comment]
Yes sure @chenzijia12300, go for it
