### ISSUE TITLE
Map<String, ?> to bean - compilation error when value type is generic/object

### ISSUE THREAD

**Issue by lowcasz** [mapstruct/mapstruct#3059]
### Expected behavior

Bean should be created from any map with mixed value types.

### Actual behavior

Bean can be created when all values have the same types only.
When I try pass Map<String, ?> as argument, then values are not casted from Object in generated code and that error is thown:
java: incompatible types: java.lang.Object cannot be converted to _**ExpectedPojoType**_

### Steps to reproduce the problem

Create POJO with mixed types fields, and Map<String, ?> witch contains field name as key, and value as expected pojo value

### MapStruct Version

Mapstruct 1.5.2.FINAL

**Comment by Zegveld** [comment]
I would say that this is expected behaviour. The user needs to specify what to do with the incoming values, for example:
```
    default String convertToString(Object obj) {
        return obj.toString();
    }

    default Integer convertToInt(Object obj) {
        if (obj instanceof Integer){
            return (Integer) obj;
        }
        return -1;
    }
```

If you want to indiscriminately cast from Object to a class then you can add a method which does this, for example:
```
    default <T> T cast(Object obj) {
        return (T) obj;
    }
```

Mapstruct takes the safe route and gives this compile error.

**Comment by lowcasz** [comment]
Why it can't be casted by default when there is not more safety method?
But thank you for work around. ;)
