### ISSUE TITLE
disableBuilder via Application Properties

### ISSUE THREAD

**Issue by FireRedDev** [mapstruct/mapstruct#3061]
### Use case

I use Mapstruct and Lombok @Builder. This causes me Issues with @AfterMapping

@AfterMapping
public void mapIdsToEntities(StorageDto storageDto, @MappingTarget Storage storage) {
would need to be turned into the following using @Builder:

@AfterMapping
public void mapIdsToEntities(StorageDto storageDto, @MappingTarget StorageBuilder storage) {

I need Builders for Tests and not for Mapstruct, so i would like to be able to do the following:
@Mapper(componentModel = "spring", builder = @Builder(disableBuilder = true))
disableBuilder for the entire Spring Application, so other devs in my team dont stumble into the same error.

**Comment by Zegveld** [comment]
this already exists, see [configuration options in the reference guide](https://mapstruct.org/documentation/stable/reference/html/#configuration-options) for all the compiler arguments and how to use them. Below I've listed the one for disabling builders from there.

<html>
<body>


mapstruct. disableBuilders | If set to true, then MapStruct will not use builder patterns when doing the mapping. This is equivalent to doing @Mapper( builder = @Builder( disableBuilder = true ) ) for all of your mappers. | false
-- | -- | --



</body>
</html>

If I misunderstood what you wanted, feel free to reopen this issue.
