### ISSUE TITLE
Can you please make null check for source instance optional?

### ISSUE THREAD

**Issue by aleks-programmer** [mapstruct/mapstruct#3079]
### Use case

Now null check for source instance is not optional. So I generate the mapper and see the code like the following:

```
if ( source == null ) {
    return null;
}
```

But I would like to control that behavior. Now I use Kotlin and we have non-null type but generator generates non-null check.
Could you please check?

### MapStruct Version

1.5.3.Final

**Comment by filiphr** [comment]
The functionality requested in this issue should be resolved by #1243 with explicit support for the `NotNull` and `Nullable` annotations. I believe that Kotlin code is correctly annotated with those annotations and MapStruct can use that to ignore not needed checks. Therefore, I am closing this one in favour of #1243
