### ISSUE TITLE
MapStruct Property has no write accessor in MetaData for target name

### ISSUE THREAD

**Issue by Sam-Si** [mapstruct/mapstruct#3088]
### Expected behavior

The mapping should be done successfully.

### Actual behavior

The following error.
`MapStruct Property has no write accessor in MetaData for target name`

### Steps to reproduce the problem

I have a FlatDTO that needs to be mapped to a nested Response containing InfoData and MetaData
The code for the response is generated by OpenAPI. So the below definitions can't be changed.
```kt
package org.mapstruct.example.kotlin.openapi

import com.fasterxml.jackson.annotation.JsonProperty
import javax.validation.Valid

data class Response(

    @field:Valid @field:JsonProperty("infoData", required = true) val infoData: InfoData,

    @field:Valid @field:JsonProperty("metaData", required = true) val metaData: MetaData
)


data class InfoData(

    @field:JsonProperty("id", required = true) val id: kotlin.String,

    )


data class MetaData(
    @field:JsonProperty("firstProperty") val firstProperty: String? = null,
)

```

I have defined FlatDTO as follows.

```kt
package org.mapstruct.example.kotlin.models

data class FlatDTO(
    var id: String? = null,
    var firstProperty: String,
)
```
Here is my mapper class which maps FlatDTO to Response

```kt
package org.mapstruct.example.kotlin.mapper

import org.mapstruct.Mapper
import org.mapstruct.Mapping
import org.mapstruct.Mappings
import org.mapstruct.example.kotlin.models.FlatDTO
import org.mapstruct.example.kotlin.openapi.Response

@Mapper
interface DataMapper {

    @Mappings(
        Mapping(target = "infoData.id", source = "id"),
        Mapping(target = "metaData.firstProperty", source = "firstProperty")
    )
    fun flatToResponse(flatDTO: FlatDTO): Response
}
```
When I try to build the code using `mvn clean install` I get the following error.

```
error: Property "firstProperty" has no write accessor in MetaData for target name "metaData.firstProperty".
[ERROR]     @org.mapstruct.Mappings(value = {@org.mapstruct.Mapping(target = "infoData.id", source = "id"), @org.mapstruct.Mapping(target = "metaData.firstProperty", source = "firstProperty")})
```

I understand that this message is trying to say that there is no setter function for `firstProperty` because it's defined as `val` but that code cannot be edited. I can write my own custom mapper that works just fine.

I wanted to understand if there is a way to use MapStruct in this scenario.

### MapStruct Version

1.5.3.Final

**Comment by Sam-Si** [comment]
[mapstruct-kotlin.zip](https://github.com/mapstruct/mapstruct/files/10090484/mapstruct-kotlin.zip)
Attaching the project for faster debugging.

**Comment by filiphr** [comment]
@Sam-Si thanks a lot for your example. Can you please have a look at #2281, I think that your problem is identical to the one there.

**Comment by Sam-Si** [comment]
Hi, @filiphr I went through the entire discussion multiple times and couldn't figure out the link between the two.
What changes do I need to do in the code above for it to work? That would be really helpful.
Thanks

**Comment by darshan92kumar** [comment]
Hi, can we have anyone look at this issue ?

**Comment by filiphr** [comment]
@Sam-Si have a look at https://github.com/mapstruct/mapstruct/issues/2281#issuecomment-1010617436 and https://github.com/mapstruct/mapstruct/issues/2281#issuecomment-1064034838 that five workarounds for how this can be resolve.

I am going to close this one in favour of #2281 and #2378

**Comment by khanusova90** [comment]
@filiphr That does not help as generated classes cannot be changed.

**Comment by filiphr** [comment]
In that case you'll have to do some manual mapping. We'll tackle this as part of the larger kotlin support that I want to look into once 1.6 is out

**Comment by Skyggedans** [comment]
Why does MapStruct require a setter for property, if it uses a data class constructor in mapper implementation and source properties in place of its parameters?

**Comment by filiphr** [comment]
@Skyggedans I don't understand your comment. 

If you've read the other issues I've linked here you'll see that when Kotlin data classes are used not everything is properly discovered and we need to do some work on that
