### ISSUE TITLE
java: Can't generate mapping method from iterable type to non-iterable type, with @MappingTarget and a List.

### ISSUE THREAD

**Issue by Philb37** [mapstruct/mapstruct#3093]
Hi,

I'm having an issue with this sample of code. I can't tell if it's me doing something wrong, a feature missing or a bug. I'm using MapStruct version 1.4.1.Final, but I've tried with the 1.5.3.Final and it doesn't seem to work either.

    public class A {
        
        String nameA;
        
        List<C> namesC;
    }

    public class B {
        
        String nameB;
        
        List<D> namesD;
    }

    public class C {
        
        String nameC;
    }

    public class D {
        
        String nameD;
    }

    @Mapper(componentModel="spring")
    public interface CDMapper {

        @Mapping(target="nameC", source="nameD")
        C DtoC(D d);
        
        List<C> DstoCs(List<D> ds);
    }

    @Mapper(uses = {CDMapper.class})
    public interface ABMapper {

        @Mapping(target="nameA", source="nameB")
        A BtoA(B b);
        
        @Mapping(target="namesC", source="ds")
        void fillList(@MappingTarget A a, List<D> ds);
    }

When I try to use the @MappingTarget annotation in the void fillList method I get the error mentioned in the title.

If I remove the @MappingTarget and change the void return type to A return type it works fine, there is also no issue if this isn't a List (replace the List in A and B and make them only C and D).

Without the @MappingTarget the generated code will clone the A object parameters into a new A, which is what I wanted to avoid :

    @Override
    public A fillList(A a, List<D> ds) {
        if ( a == null && ds == null ) {
            return null;
        }

        A a1 = new A();

        if ( a != null ) {
            a1.setC( a.getC() );
            a1.setNameA( a.getNameA() );
        }
        if ( ds != null ) {
            a1.setNamesC( cDMapper.DstoCs( ds ) );
        }

        return a1;
    }

Why doesn't it generate a code similar to the one bellow with the @MappingTarget annotation but throws a compile error ?

    @Override
    public void fillList(A a, List<D> ds) {
        if ( ds == null ) {
            return;
        }

        a.setNamesC( cDMapper.DstoCs( ds ) );
    }

I know there is workarounds but I'm wondering if this is normal behavior ?

**Comment by filiphr** [comment]
Looking a bit more into this it seems like this is a missing feature. We did https://github.com/mapstruct/mapstruct/issues/607, but that was only for non java iterable types.
However, I think that the right solution for this would be done through #2559.

**Comment by filiphr** [comment]
I am indeed going to close this one in favour of #2559
