### ISSUE TITLE
defaultExpression cannot be used without the source in MapStruct 1.5.0 or higher versions

### ISSUE THREAD

**Issue by manishchauhan2090** [mapstruct/mapstruct#3096]
### Expected behavior

We should be able to use defaultExpression in the Mapping without requiring to specify source but that is not the case it seems.
I am using mapstruct version 1.5.0 and even tried with higher mapstruct versions but still got the same error.

@Mapping(target = "oasDate", defaultExpression = "java(LocalDate.now())")

This should have been compiled without any issue.

### Actual behavior

This issue was supposed to be fixed in the mapstruct version 1.4.0.Final but was reintroduced in the latest versions.

https://github.com/mapstruct/mapstruct/issues/1966

### Steps to reproduce the problem

Same as mentioned above.

### MapStruct Version

1.5.0.Final

**Comment by DavidRomao** [comment]
Just as a note, the same happens with the defaultValue

**Comment by filiphr** [comment]
The reason why it doesn't compile is because `java.time.LocalDate` is not imported. The functionality works as it should.

If I do:

```java
@Mapping(target = "oasDate", defaultExpression = "java(java.time.LocalDate.now())")
```

or I add `LocalDate` in `Mapper#imports`

e.g.

```java
@Mapper(imports = LocalDate.class)
```

then everything compiles as it should. The some is for `defaultValue`.

Closing this as works as designed.
