### ISSUE TITLE
Compilation Failure for @AfterMapping annotated Method in conjunction with ObjectFactory

### ISSUE THREAD

**Issue by LambertK123** [mapstruct/mapstruct#3097]
### Actual behavior

My maven build crashes with a compilation failure and the following error message: "@AfterMapping can only be applied to an implemented method". During debugging i was able to trace it back to the usage of an entity factory for the instantiation of mapped classes.

### Steps to reproduce the problem

[MapstructCodeExample.zip](https://github.com/mapstruct/mapstruct/files/10139483/MapstructCodeExample.zip)

### MapStruct Version

1.5.0.RC - 1.5.3.Final

**Comment by filiphr** [comment]
I am surprised that this even managed to produce that error.

I see that you have

```
@Mapper(uses = KlassenMapper.class)
@MapperConfig(uses = KlasseMapperFactory.class)
public abstract class KlassenMapper {

    //...
}
```

this means that you mapper is both a mapper and a mapper config. 

If I clean that up then it works properly.

I would close this issue as works as designed.
