### ISSUE TITLE
Document <THROW_EXCEPTION> in the reference guide

### ISSUE THREAD

**Issue by mjustin** [mapstruct/mapstruct#3112]
### Expected behavior

[`MappingConstants.THROW_EXCEPTION`](https://mapstruct.org/documentation/stable/api/org/mapstruct/MappingConstants.html#THROW_EXCEPTION) (`"<THROW_EXCEPTION>"`) allows throwing an exception for particular value mappings.  For instance:

```java
        @ValueMapping(target = "APPLE", source = "Apple")
        @ValueMapping(target = "BANANA", source = "Banana")
        @ValueMapping(target = MappingConstants.THROW_EXCEPTION, source = MappingConstants.ANY_UNMAPPED)
        Fruit mapFruit(String fruit);
```

However, this constant is not referenced in the [MapStruct reference guide](https://mapstruct.org/documentation/stable/reference/html).

### Actual behavior

I would expect to see this explained in the reference guide.  In my particular use case, I didn't see any references in the [Mapping enum to enum types](https://mapstruct.org/documentation/stable/reference/html/#_mapping_enum_to_enum_types) section.

### Steps to reproduce the problem

Open the [reference guide](https://mapstruct.org/documentation/stable/reference/html).  Notice that there are no references to either `<THROW_EXCEPTION>` or `MappingConstants.THROW_EXCEPTION`.

### MapStruct Version

MapStruct 1.5.3

**Comment by filiphr** [comment]
Valid point @mjustin. We need to add this to the docs.

Is there someone from the community that would be interested in working on this?

**Comment by jccampanero** [comment]
I will work on this if you don't mind @filiphr.

**Comment by mjustin** [comment]
Looks like there are two lists in the updated documentation where `THROW_EXCEPTION` is used where `<THROW_EXCEPTION>` would be more consistent with the other examples.

Specifically, \#5 in both the following lists look like they should be `<THROW_EXCEPTION>`:

> ### 8.2. Mapping enum-to-String or String-to-enum
> 
> MapStruct supports enum to a String mapping along the same lines as is described in [enum-to-enum types](#_mapping_enum_to_enum_types). There are similarities and differences:
> 
> **enum to `String`**
> 
> 1.  Similarity: All not explicit defined mappings will result in each source enum constant value being mapped a `String` value with the same constant value.
> 2.  Similarity: `<ANY_UNMAPPED`\> stops after handling defined mapping and proceeds to the switch/default clause value.
> 3.  Difference: `<ANY_REMAINING>` will result in an error. It acts on the premise that there is name similarity between enum constants in source and target which does not make sense for a String type.
> 4.  Difference: Given 1. and 3. there will never be unmapped values.
> 5.  Similarity: `THROW_EXCEPTION` can be used for throwing an exception for particular enum values.
> 
> **`String` to enum**
> 
> 1.  Similarity: All not explicit defined mappings will result in the target enum constant mapped from the `String` value when that matches the target enum constant name.
> 2.  Similarity: `<ANY_UNMAPPED`\> stops after handling defined mapping and proceeds to the switch/default clause value.
> 3.  Similarity: `<ANY_REMAINING>` will create a mapping for each target enum constant and proceed to the switch/default clause value.
> 4.  Difference: A switch/default value needs to be provided to have a determined outcome (enum has a limited set of values, `String` has unlimited options). Failing to specify `<ANY_REMAINING>` or `<ANY_UNMAPPED`\> will result in a warning.
> 5.  Similarity: `THROW_EXCEPTION` can be used for throwing an exception for any arbitrary `String` value.

**Comment by jccampanero** [comment]
Thank you very much @mjustin, my bad.

I fixed the docs and provided a new pull request to fix the mentioned issues in the documentation.
