### ISSUE TITLE
Use Java HashSet and HashMap new factory method with known capacity when on Java 19

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#3113]
### Use case

Instead of calculating the capacity in the generated code we should instead use

* [`HashSet.newHashSet(int)`](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/HashSet.html#newHashSet(int))
* [`HashMap.newHashMap(int)`](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/HashMap.html#newHashMap(int))

This should be done only when the Source level is >= 19.

**Comment by jccampanero** [comment]
@filiphr Could I work on the issue? I think it should be related to `IterableCreation`, does it? Please, could you elaborate your idea?

Could I help you with any other issues? I tried finding new ones labeled as `good first issue`, but there are only four issues labeled as such, this one, one already in progress, and two more, with seem to be under discussion. Could I help you with anything else?

Thank you very much!!

**Comment by filiphr** [comment]
>@filiphr Could I work on the issue? I think it should be related to IterableCreation, does it? Please, could you elaborate your idea?

Of course you can @jccampanero. The location is indeed related to `IterableCreation`. We will somehow need to pass `org.mapstruct.ap.internal.version.VersionInformation` to the `IterableCreation` and then check there what the right approach would be.

>Could I help you with any other issues? I tried finding new ones labeled as `good first issue`, but there are only four issues labeled as such, this one, one already in progress, and two more, with seem to be under discussion. Could I help you with anything else?

We are trying to work on some of the issues in the 1.6 milestone in order to release something. If you find something in those, feel free to comment on them. Otherwise, if you find any issue that sounds interesting to you and you'd like to work on it, then please let us know.

**Comment by Obolrom** [comment]
@filiphr I tried to resolve this issue and faced the problem. I cannot access the `iterable.size` in the generated code when `resultType.implementationType` is null [in here](https://github.com/mapstruct/mapstruct/blob/main/processor/src/main/resources/org/mapstruct/ap/internal/model/IterableCreation.ftl)
Furthermore, to use static methods
[HashSet.newHashSet(int)](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/HashSet.html#newHashSet(int))
[HashMap.newHashMap(int)](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/HashMap.html#newHashMap(int))
[LinkedHashSet.newLinkedHashSet(int)](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/LinkedHashSet.html#newLinkedHashSet(int))
we should use if/switch statements to generate proper code.

If you have a more elegant idea of how to resolve it, please share it and I will try implement it

**Comment by Obolrom** [comment]
@filiphr Could you please conduct a review?
It seems we should add tests for separated testing of the generated code for JDK 19+

**Comment by jccampanero** [comment]
Sorry @filiphr, I am truly sorry, mate. Many things have changed in my life, and I'm afraid I haven't had the opportunity to contribute to this or any other open source project for quite some time. I sincerely apologize for that.

Thank you very much for submitting your PR, @Obolrom. It is very similar to the code I started to implement when Filip assigned the issue to me.

@Obolrom, may I perform the code review? @filiphr, do you agree with that?

**Comment by filiphr** [comment]
No need to apologise @jccampanero. Life gets in the way, we are all doing this in our free time when we have it.

I don't mind you going through the PR and doing a review @jccampanero. If you have the time, feel free to do it
