### ISSUE TITLE
Support qualifier for SubclassMapping annotated methods

### ISSUE THREAD

**Issue by EvaristeGalois11** [mapstruct/mapstruct#3119]
### Use case

I want to specify which method the subclass mapping should use. For example sometimes i want to use a more complete method that maps all the fields of a subclass and sometimes i want to use a method that just map some fields. This is currently not possible because the qualifiers specified in the BeanMapping annotations is ignored.

These are my mappers:

```java
@Mapper(uses = Dummy1Mapper.class)
public interface DummyMapper {
    @SubclassMapping(source = Dummy1.class, target = Dummy1Dto.class)
    BaseDummyDto toDto(BaseDummy baseDummy);

    @BeanMapping(qualifiedByName = "light")
    @SubclassMapping(source = Dummy1.class, target = Dummy1Dto.class)
    BaseDummyDto toDtoLight(BaseDummy baseDummy);
}

@Mapper
public interface Dummy1Mapper {
    Dummy1Dto toDto(Dummy1 dummy1);

    @Named("light")
    @Mapping(target = "descriptions", ignore = true)
    Dummy1Dto toDtoLight(Dummy1 dummy1);
}
```

### Generated Code

These are the generated mappers, as you can see Dummy1Mapper#toDtoLight is never called:

```java
public class DummyMapperImpl implements DummyMapper {

    private final Dummy1Mapper dummy1Mapper = Mappers.getMapper( Dummy1Mapper.class );

    @Override
    public BaseDummyDto toDto(BaseDummy baseDummy) {
        if ( baseDummy == null ) {
            return null;
        }

        if (baseDummy instanceof Dummy1) {
            return dummy1Mapper.toDto( (Dummy1) baseDummy );
        }
        else {
            BaseDummyDto baseDummyDto = new BaseDummyDto();

            baseDummyDto.setId( baseDummy.getId() );

            return baseDummyDto;
        }
    }

    @Override
    public BaseDummyDto toDtoLight(BaseDummy baseDummy) {
        if ( baseDummy == null ) {
            return null;
        }

        if (baseDummy instanceof Dummy1) {
            return dummy1Mapper.toDto( (Dummy1) baseDummy );
        }
        else {
            BaseDummyDto baseDummyDto = new BaseDummyDto();

            baseDummyDto.setId( baseDummy.getId() );

            return baseDummyDto;
        }
    }
}

public class Dummy1MapperImpl implements Dummy1Mapper {

    @Override
    public Dummy1Dto toDto(Dummy1 dummy1) {
        if ( dummy1 == null ) {
            return null;
        }

        Dummy1Dto dummy1Dto = new Dummy1Dto();

        dummy1Dto.setId( dummy1.getId() );
        List<String> list = dummy1.getDescriptions();
        if ( list != null ) {
            dummy1Dto.setDescriptions( new ArrayList<String>( list ) );
        }

        return dummy1Dto;
    }

    @Override
    public Dummy1Dto toDtoLight(Dummy1 dummy1) {
        if ( dummy1 == null ) {
            return null;
        }

        Dummy1Dto dummy1Dto = new Dummy1Dto();

        dummy1Dto.setId( dummy1.getId() );

        return dummy1Dto;
    }
}
```

### Possible workarounds

The only workaround is to write BaseMapper#toDtoLight by hand.

### MapStruct Version

MapStruct 1.5.3

**Comment by Zegveld** [comment]
I would suggest that we would make the use of qualifiers within the `SubclassMapping` annotation possible in the same way as it works for `@Mapping`.

That way the following would become possible:
```
    @BeanMapping( /* qualifier definition */ )
    @SubclassMapping(source = Dummy1.class, target = Dummy1Dto.class, qualifiedByName = "light") // using name, do not inherit.
    @SubclassMapping(source = Dummy2.class, target = Dummy2Dto.class, qualifiedBy = LightQualifier.class ) // using annotation class, do not inherit.
    @SubclassMapping(source = Dummy3.class, target = Dummy3Dto.class ) // do not inherit.
    BaseDummyDto toDtoLight(BaseDummy baseDummy);
```

The `@BeanMapping` annotation's `qualifiedBy` is not meant for inheriting as can be read in the javadoc:

> A qualifier can be specified to aid the selection process of a suitable factory method or filtering applicable @BeforeMapping / @AfterMapping methods. This is useful in case multiple factory method (hand written of internal) qualify and result in an 'Ambiguous factory methods' error. 
>
> A qualifier is a custom annotation and can be placed on either a hand written mapper class or a method.

If we look at the `@Mapping` annotation we find the following:

> A qualifier can be specified to aid the selection process of a suitable mapper. This is useful in case multiple mapping methods (hand written or generated) qualify and thus would result in an 'Ambiguous mapping methods found' error. A qualifier is a custom annotation and can be placed on a hand written mapper class or a method. 
>
> Note that defaultValue() usage will also be converted using this qualifier.

**Comment by EvaristeGalois11** [comment]
> A qualifier can be specified to aid the selection process of a suitable factory method

Yes you're right, i'm using the wrong tool for the job. In my shallow reading of that part of the documentation i interpreted the subclass mapping as a kind of factory method process, but now i see why it was wrong.

I'll try to provide another PR with what you're saying. Thanks and happy holidays!

**Comment by Zegveld** [comment]
> > A qualifier can be specified to aid the selection process of a suitable factory method
> 
> Yes you're right, i'm using the wrong tool for the job. In my shallow reading of that part of the documentation i interpreted the subclass mapping as a kind of factory method process, but now i see why it was wrong.
> 
> I'll try to provide another PR with what you're saying. Thanks and happy holidays!

Looking forward to the new PR, and enjoy the holidays :)
