### ISSUE TITLE
Support `@InheritConfiguration` for `@SubclassMapping` in methods with identical signature

### ISSUE THREAD

**Issue by EvaristeGalois11** [mapstruct/mapstruct#3125]
### Expected behavior

Working on #3120 i realized that @SubclassMapping wasn't been inherited.

So in a mapper like this i was expecting that TestMapper#mapAnother will inherit all the annotations and basically behave the same way as TestMapper#map:

```
@Mapper
public interface TestMapper {
    TestMapper INSTANCE = Mappers.getMapper( TestMapper.class );

    @SubclassMapping(source = CarDto.class, target = Car.class)
    @SubclassMapping(source = BikeDto.class, target = Bike.class)
    @Mapping(source = "maker", target = "vehicleManufacturingCompany")
    Vehicle map(VehicleDto vehicle);

    @InheritConfiguration
    Vehicle mapAnother(VehicleDto vehicleDto);
}
```

### Actual behavior

But mapstruct generate this, correctly inheriting the mapping annotation but leaving out the subclass related stuff:

```
public class TestMapperImpl implements TestMapper {

    @Override
    public Vehicle map(VehicleDto vehicle) {
        if ( vehicle == null ) {
            return null;
        }

        if (vehicle instanceof CarDto ) {
            return  carDtoToCar( (CarDto) vehicle );
        }
        else if (vehicle instanceof BikeDto ) {
            return  bikeDtoToBike( (BikeDto) vehicle );
        }
        else {
            Vehicle vehicle1 = new Vehicle();

            vehicle1.setVehicleManufacturingCompany( vehicle.getMaker() );
            vehicle1.setName( vehicle.getName() );

            return vehicle1;
        }
    }

    @Override
    public Vehicle mapAnother(VehicleDto vehicleDto) {
        if ( vehicleDto == null ) {
            return null;
        }

        Vehicle vehicle = new Vehicle();

        vehicle.setVehicleManufacturingCompany( vehicleDto.getMaker() );
        vehicle.setName( vehicleDto.getName() );

        return vehicle;
    }

    protected Car carDtoToCar(CarDto carDto) {
        if ( carDto == null ) {
            return null;
        }

        Car car = new Car();

        car.setVehicleManufacturingCompany( carDto.getMaker() );
        car.setName( carDto.getName() );
        car.setManual( carDto.isManual() );

        return car;
    }

    protected Bike bikeDtoToBike(BikeDto bikeDto) {
        if ( bikeDto == null ) {
            return null;
        }

        Bike bike = new Bike();

        bike.setVehicleManufacturingCompany( bikeDto.getMaker() );
        bike.setName( bikeDto.getName() );
        bike.setNumberOfGears( bikeDto.getNumberOfGears() );

        return bike;
    }
}
```

### Steps to reproduce the problem

What the expected behavior says.

### MapStruct Version

MapStruct 1.5.3

**Comment by Zegveld** [comment]
I can at least explain why it was disabled:
The same inheritance structure is also used for inheriting options to methods forged from other methods, for example the `SubclassMapping` annotation would be inherited by the `carDtoToCar` method which then causes it to spawn another `carDtoToCar` method, and it will continue doing this until it runs into a `StackOverflowError`. Easiest fix at that time was disabling the inheritance feature for `SubclassMapping` annotations.

I'll try to create a PR that enables this for when the `@InheritConfiguration` is present.

**Comment by EvaristeGalois11** [comment]
Thank you for your insight, i did in fact slip into the stack overlow you're mentioning when i tried tinkering a bit with the inheritance process. I think that especially if qualifiers will be added to the `SubclassMapping` annotation an inheritance and override mechanism similar to the `Mapping` annotation could be valuable to have.

I haven't worked much on this problem so i can't provide a PR myself, but one of the solution i thought implementing was propagating a `SubclassMapping` annotation iff the receiving method had at least the same type of the parent method in regard of source and target. This should break the cyclic dependency, but it's just a theory that i haven't found the time to test i'm afraid and if you say you want to tackle the problem i'm more than happy to leave an expert works their magic lol.

**Comment by Zegveld** [comment]
There is an annotation passed into the method already. That one should be `null` in case of method inheritance, and in case of `@InheritConfiguration` or `@InheritInverseConfiguration` filled with that annotation. So I was thinking about using that to determine if the inheritance should be applied.

**Comment by Zegveld** [comment]
Just looked at the test-case that had the stack-overflow, and it is the exact same situation as you have but then where inheritance is not wanted.

```
    @SubclassMapping( source = SourceSubclass.class, target = Target.class )
    /* some mappings */
    Target mapSuperclass(Source source);

    @InheritConfiguration( name = "mapSuperclass" )
    /* override mappings to fill in additional fields */
    Target mapSubclass(SourceSubclass source);
```

Currently I'm thinking of introducing an option on the `@InheritConfiguration` annotation where you can turn off the `SubclassMapping` annotation inheritance. Something like: `@InheritConfiguration( name = "mapSuperclass", subclassInheritanceStrategy = DO_NOT_INHERIT )`

**Comment by EvaristeGalois11** [comment]
Yep that's exactly the test i ran into and where i thought of some kind of cyclic detection or protection to avoid it, but the more practical approach of just trusting the user to enable or disable it could be better. 

My only worry is that even if the user enable the subclass mapping in a case similar to the test case is it the right thing to just break completely without some kind of warning or clear error? Because if no we still need some kind of detection to warn the user to disable it. And if a detection is put in place, maybe the `subclassMappingInheritanceStrategy` parameter could more simply just suppress the warning because the inheritance is already skipped by the detection process.

On the other hand this warning could just be stating very clearly in the documentation that enabling the inheritance of subclass mapping could lead to trouble and to disable it in case of problems.

**Comment by Zegveld** [comment]
I think I have a solution, which is to only allow `SubclassMapping`s to be inherited when the `return type` and `parameters` of both methods are identical. In case of sub/super class these are not identical, and in case of your situation these are identical.
