### ISSUE TITLE
Breaking change: Mapping from Map to Bean

### ISSUE THREAD

**Issue by kirbylink** [mapstruct/mapstruct#3144]
### Expected behavior

When target and source object contains maps (Map<String, ?>)  with same name, then the new function "Mapping from Map to Bean" should not be used

Following Object is used with MapStruct 1.4.2.Final:
```java
@Getter
@Builder(setterPrefix = "with")
public class DispatchServiceRequest {
	private final String topic;
	private final String text;
	private final Map<String, Object> attachments;
	private final Date timestamp;
	private final UUID messageId;
	private final DispatcherService dispatcherService;
	private final Delay delay;
}
```
The corresponding Mapper that worked out of the box with MapStruct 1.4.2.Final:
```java
@Mapper(componentModel = "spring")
public interface DispatchServiceRequestMapper {
	@Mapping(target = "messageId", ignore = true)
	DispatchServiceRequest mapToDispatchServiceRequest(String topic, String text, Map<String, Object> attachments, Date timestamp, DispatcherService dispatcherService, Delay delay);
}
```

### Actual behavior

With version 1.5.x.Final i get the following errors:

> Multiple markers at this line
	- Can't map property "Object topic" to "String topic". Consider to declare/implement a mapping method: "String map(Object value)".
	- Can't map property "Object attachments" to "Map<String,Object> attachments". Consider to declare/implement a mapping method: "Map<String,Object> map(Object value)".
	- Can't map property "Object text" to "String text". Consider to declare/implement a mapping method: "String map(Object value)".
	- Can't map property "Object timestamp" to "Date timestamp". Consider to declare/implement a mapping method: "Date map(Object value)".
	- Can't map property "Object delay" to "Delay delay". Consider to declare/implement a mapping method: "Delay map(Object value)".
	- Can't map property "Object dispatcherService" to "Dispatcher.DispatcherService dispatcherService". Consider to declare/implement a mapping method: "Dispatcher.DispatcherService map(Object value)".

It seems, that the new Feature [3.10. Mapping Map to Bean](https://mapstruct.org/documentation/stable/reference/html/#mapping-map-to-bean) breaks the old behaviour.
When i remove the parameter `Map<String, Object> attachments` from the mapper method, it will compile.
When i add for each parameter a mapping like
```java
@Mapper(componentModel = "spring")
public interface DispatchServiceRequestMapper {
	@Mapping(target = "messageId", source = "")
	@Mapping(target = "text", source = "text")
	@Mapping(target = "delay", source = "delay")
	@Mapping(target = "topic", source = "topic")
	@Mapping(target = "timestamp", source = "timestamp")
	@Mapping(target = "attachments", source = "attachments")
	@Mapping(target = "dispatcherService", source = "dispatcherService")
	DispatchServiceRequest mapToDispatchServiceRequest(String topic, String text, Map<String, Object> attachments, Date timestamp, DispatcherService dispatcherService, Delay delay);
}
```
then it also works but in my opinion this is some extra boilerplate which was not necessary before.

### Steps to reproduce the problem

code examples: see above

### MapStruct Version

MapStruct 1.5.3.Final

**Comment by ericmartineau** [comment]
I have this same problem.  IMO pulling values from `Map` is a dangerous feature to have turned on by default, and should be opt-in.  But even so, Map keys should not be used when there's already a parameter that provides the key concretely.

**Comment by filiphr** [comment]
This is a valid point @kirbylink. We should see what we can do and perhaps not treat `Map<String, ?>` as a mapping from Map to Bean when using multiple sources in a mapping.

**Comment by coopstah13** [comment]
suggested solution would work for us as well - i can't imagine that most people with a map source in addition to other sources would ever mean to map the way it works now, perhaps you could add an additional annotation if that is the desire like `@BeanMapping Map<String, Object> fromThisMap`

**Comment by filiphr** [comment]
I agree with you @coopstah13. I would take your proposal as part of #2559.

There are 2 different fixes as part of this issue I think. Basically `Map<String, ?>` should not be treated for implicit mapping in the following situations:

* Single source parameter with the source parameter explicitly being used in the `@Mapping`
e.g.
```java
@Mapper
public interface MyMapper {

    @Mapping(target = "myMap", source = "sourceMap")
    Target map(Map<String, Object> sourceMap);
}
```

* Multi source parameters
e.g.
```java
@Mapper
public interface MyMapper {

    Target map(Source source, Map<String, Object> sourceMap);
}
```

However, for multi source parameters something like:

```java
@Mapper
public interface MyMapper {

    @Mapping(target = "testValue", source = "sourceMap.testValue")
    Target map(Source source, Map<String, Object> sourceMap);
}
```

should still work properly.

**Comment by jase52476** [comment]
Hi, so how do we create a mapper to achieve the functionality in 1.5.5.Final?

I am trying to upgrade form 1.5.5.Final -> 1.6.3, and I had a mapper that was like this:

@Mappings( {
@Mapping( source ="fieldInObject", target="myField1" )
})
Object mapMyObject ( String fieldInObject, Map<String, String> otherFieldsInObject )

It would map the string "fieldInObject" to the appropriate field in the return Object, and then it would generate that would proceed to check my map "otherFieldsInObject" and set the matching fields.

But now, with 1.6.3, it ignores my map, and I cannot follow what was done here or how to get the old functionality.

I was able to create a single-parameter mapper and it works fine.  The use case here is that I have two different sources of data that I'm merging into my result object, so I want to pass them both and have the resulting object contain data from both sources.

**Comment by filiphr** [comment]
There isn't a way to bring the behavior from 1.5 at the moment. See #3697 for more information. The way I would like to tackle this is by doing something like #3793, with that one you should have more power in how this map source parameter should be treated.
