### ISSUE TITLE
Mapstruct try to map method from record

### ISSUE THREAD

**Issue by clemstoquart** [mapstruct/mapstruct#3146]
### Expected behavior

Hi,

Let's say we have the following class:
```java
public class User {
    private String name;
    // getter, setter,...
}
```

And we want to map it to the following record:
```java
public record UserDto(String name) {
    public String prettyPrint() {
        System.out.println("Amazing user: " + name);
    }
} 
```

The following mapper should work:
```java
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserMapper {
    UserDto map(User user);
}
```

### Actual behavior

But it doesn't. 

Mapstruct reports an unmapped target property: `prettyPrint` which is wrong.

I think it should be safe to ignore methods for `record` while setters can't exist in a record.

What do you think ?

### Steps to reproduce the problem

Any record with a method should trigger this issue.

### MapStruct Version

1.5.3.Final

**Comment by csisy** [comment]
There is an addittional but related problem with records.

```
public record DTO(List<String> values) {}

@Mapper
public interface DTOMapper {
    @Mapping(target = "values", source = "...")
    DTO toDTO(...);
}
```

We specified how to map the collection, however mapstruct tries to find a setter/adder/getter method for the collection. And for that it removes the first 3 characters from the corresponding collection name.

This results in the following warning/error (depending on the unmapped target setting): "Unmapped target property: ues" - which is "values" without the first 3 characters.

**Comment by filiphr** [comment]
@clemstoquart are you sure that you provided the right example. I tried with:

```java
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserMapper {

    UserDto map(User user);

    class User {

        private String name;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    record UserDto(String name) {

        public String prettyPrint() {
            return "Amazing user " + name();
        }
    }

}

```

and it generates the right code.

@csisy I would suggest that you create a dedicated issue for a different problem.

**Comment by sbluemel** [comment]
I have a very similiar reproducer with Mapstruct Version 1.6.3:

```java
import java.time.LocalDate;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface RangeMapper {

  @Mapping(target = "validFrom", source = "rangeContainer.a")
  @Mapping(target = "validTo", source = "rangeContainer.b")
  RangeRecord toRange(RangeContainer rangeContainer);

  record RangeRecord(LocalDate validFrom, LocalDate validTo) {

    public RangeRecord restrictTo(RangeRecord other) {
      return null;
    }
  }

  class RangeContainer {
    private LocalDate a;
    private LocalDate b;

    public LocalDate getA() {
      return a;
    }

    public void setA(LocalDate a) {
      this.a = a;
    }

    public LocalDate getB() {
      return b;
    }

    public void setB(LocalDate b) {
      this.b = b;
    }
  }

}
```

On compile I get the error `Unmapped target property: "restrictTo".`.

**Comment by filiphr** [comment]
Thanks for the reproducal @sbluemel. That is indeed a bug, we should not treat methods in records as potential fluent setters. Perhaps, we should not even look at additional setters in record components and only use the record components for the mapping. I created #3886 with your exampl
