### ISSUE TITLE
Pass a reference to parent object as parameter in method annotated with @AfterMapping

### ISSUE THREAD

**Issue by andreevmipt** [mapstruct/mapstruct#3149]
### Use case

I would like to set parent/child relationship for composed objects with 
`@Context` and `@AfterMapping` annotations 
Something like
```java
@AfterMapping
public void establishRelation( @ParentTarget Object parent, @MappingTarget IChild child) {
child.setParent(parent);
}
```
and possibly keeping track of inverse relation relation

**Comment by filiphr** [comment]
Have you seen the [mapstruct-jpa-child-parent](https://github.com/mapstruct/mapstruct-examples/tree/main/mapstruct-jpa-child-parent) example? I believe that this is possible to be achieved using what is there in MapStruct already. Therefore, I am going to close this issue. If you think that the example is not sufficient, then please let us know and we can reopen this issue and discuss it further.
