### ISSUE TITLE
How to exclude a source property from mapping

### ISSUE THREAD

**Issue by Fairyon** [mapstruct/mapstruct#3150]
### Use case

I have a generic mapping class that has a source with a field that should be ignored and a generic target that does not always have that field.
I need to ignore that field by source, but that seems not possible.

My code:
```
public interface RoleMapper<Role> { 
  Role mapRoleDtoToRole(RoleDto roleDto);
}

@Data class RoleDto { 
  private String id; 
  private Collection<PermissionDto> permissions;
}

@Data public class Role1{
  private String id;
  private Set<Permission> permissions;
}

@Data public class Role2{
  private String id;
  private String somethingElse;
}
```

Now I need to ignore the mapping of the permissions field.
`@mapping(target="permissions", ignore=true)` throws a compilation error: Unknown property "permissions" in result type Role2.

Does anyone have any ideas on how to accomplish this?

### Generated Code

```
   @Override
    public Role1 mapRoleDtoToRole(RoleDto roleDto) {
        if ( roleDto == null ) {
            return null;
        }

        Role1 role1 = new Role1();

        role1.setId( roleDto.getId() );

        return role1;
    }
```
for both Role1 and Role2

### Possible workarounds

I solved the problem by inhereting the RoleMapper and ignoring the target in the classes where it is needed, but it would be great if there is a cleaner solution. Like `@mapping(source="permissions", ignore=true)`

### MapStruct Version

MapStruct 1.5.2.Final

**Comment by filiphr** [comment]
I've already answered this in https://github.com/mapstruct/mapstruct/issues/1718#issuecomment-1493372076.
