### ISSUE TITLE
`@BeanMapping(ignoreByDefault = true)` does not work for constructor properties

### ISSUE THREAD

**Issue by alexlambrides** [mapstruct/mapstruct#3158]
### Expected behavior

Utilizing the `@BeanMapping(ignoreByDefault = true)` on a mapping where the target is a Java 14 Record, all fields should be ignored except the ones that are explicitly defined through `@Mapping`.

### Actual behavior

`@BeanMapping(ignoreByDefault = true)` does nothing, all fields are still mapped.

### Steps to reproduce the problem

Add a very basic setup to mimic the `carToCarDto` example, making the CarDto a Java 14 record:
```java
public record CarDto(int id, String make) {}
```

```java
public class Car {
    private int id;
    private String make;
    // getters & setters...
}
```
And with a mapper like so:
```java
@Mapper
public interface CarMapper {
    @BeanMapping(ignoreByDefault = true)
    @Mapping(source = "id", target = "id")
    CarDto carToCarDto(Car car);
}
```

The generated mapper does not ignore the `make` field as seen:
```java
@Override
public CarDto carToCarDto(Car car) {
    if ( car == null ) {
        return null;
    }

    int id = 0;
    String make = null;

    id = car.getId();
    make = car.getMake();

    CarDto carDto = new CarDto( id, make );

    return carDto;
}
```

A workaround for now is to explicitly ignore all the fields you do not want mapped, which behaves correctly (eg. `@Mapping(target = "make", ignore = true)`. However, with a large amount of fields this becomes very difficult to manage.

### MapStruct Version

Mapstruct 1.5.3

**Comment by filiphr** [comment]
I did some investigation on this and the problem is not just with records. The `BeanMapping#ignoreByDefault` is not honoured for any of the constructor properties.

**Comment by alexlambrides** [comment]
@filiphr thanks for the fix 🙌 , I tested your branch locally and everything works as expected!

**Comment by filiphr** [comment]
Thanks for testing this @alexlambrides. We'll merge it soon to main
