### ISSUE TITLE
Allow Mappers.getMapper to understand dependant mappers

### ISSUE THREAD

**Issue by radarsh** [mapstruct/mapstruct#3162]
### Use case

I have a mapper that _uses_ another mapper by making use of the `uses` annotation parameter as follows:

```java
@Mapper(
    componentModel = "spring", 
    injectionStrategy = InjectionStrategy.CONSTRUCTOR,
    uses = HelperMapper.class)
public interface MyMapper {
```
Now this is all fine in the main code and even tests that use `@SpringBootTest`. But not every test needs to be written as a Spring test as this is an overkill and it also comes with added complexities.

However, if we try to use `Mappers.getMapper(MyMapper.class)` in a unit test, this leads to an exception because there is no default constructor generated. I can make the error go away by using a FIELD injection strategy but it still wouldn't fix the root cause which is the factory's inability to resolve dependencies.

```java
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.example.mapper.MyMapperImpl.<init>()
          at org.mapstruct.factory.Mappers.getMapper(Mappers.java:61)
```

So what I propose is to add an overloaded `getMapper` method to `Mappers` class that accepts the dependencies that need resolution. Signature might look like this:

```java
public static <T> T getMapper(Class<T> clazz, Class<?>... dependencies) {
```

The usage will be something like:

```java
Mappers.getMapper(MyMapper.class, HelperMapper.class);
```

I have already achieved something like this in my project and if you agree with the proposal, I will raise a pull request.

### MapStruct Version

1.5.3

**Comment by lbenedetto** [comment]
Yes, this would be appreciated. I'm working around this issue by just instantiating the generated classes myself
```java
new MyMapperImpl(new HelperMapperImpl())
```

**Comment by Zegveld** [comment]
How would you suggest to handle the situation where your dependency mapper also depends on a mapper itself?

Perhaps better would be to have a signature like:
```java
public static <T> T getMapper(Class<T> clazz, Object... dependencies) {...}
```

Then the usage would be something like:
```java
Mappers.getMapper(MyMapper.class, Mappers.getMapper(HelperMapper.class));
```
Or perhaps
```java
Mappers.getMapper(MyMapper.class, helperMapperVariable);
```

And you could continue that chain for as much as needed.

The downside is that there is nothing to prevent you from passing in the wrong arguments. Unlike the situation where you would just instantiate the generated classes themselves at the tests.

**Comment by lbenedetto** [comment]
But why should we have to pass in the list of dependencies when we've already specified them in the `@Mapper` annotation?

**Comment by radarsh** [comment]
> How would you suggest to handle the situation where your dependency mapper also depends on a mapper itself?

Good point. It would be nice if we can identify the dependencies by introspecting mapper class somehow. Then we can eliminate the need to pass the dependencies completely and everything can be handled behind the scenes without changing/overloading the signatures.

> But why should we have to pass in the list of dependencies when we've already specified them in the @Mapper annotation?
> `MyMapperImpl` could have an auto-generated constructor...

Indeed that would be nice but that involves deeper understanding of MapStruct framework which I unfortunately don't have the resources for. Perhaps one of the core members of MapStruct can advise here.

**Comment by filiphr** [comment]
The reason why we do not want to support dependencies in `Mapper#getMapper` has been the fact that `@Mapper` has a class retention. This means that we cannot get it during runtime.

In addition to that we do not want to be a dependency injection framework. What you define in `Mapper#uses` is not only mappers. You can define your own custom mappers (which are not annotated with `@Mapper` themselves).

Therefore, the only possible alternative for you when using the spring component model with the constructor injection is to manually instantiate the mappers as @lbenedetto said in https://github.com/mapstruct/mapstruct/issues/3162#issuecomment-1434814935.


----

What you can do if you want is to create your own annotation processor that is going to create some factory methods to create what you need. However, I would suggest that you use the Spring ApplicationContext to create the mappers for you. You can manually create a context only with the classes you want (and that is really fast).
