### ISSUE TITLE
MapStruct no longer handles generic mapping methods (in conjunction with immutables) after upgrading from 1.4.x to version 1.5.x

### ISSUE THREAD

**Issue by ntinnemeier** [mapstruct/mapstruct#3163]
### Expected behavior

Given the following source and target models (immutable code generated by the immutables framework):
```java
@Value.Immutable
public interface ASource {
    ImmutableBSource getB();
}

@Value.Immutable
public interface ATarget {
    Optional<ImmutableBTarget> getB();
}

@Value.Immutable
public interface BSource {
    String getS();
}

@Value.Immutable
public interface BTarget {
    String getS();
}
```

and the following mapper definition:
```java
public interface Mapper {
    ImmutableATarget map(ImmutableASource value);

    ImmutableBTarget map(ImmutableBSource value);

    default <T> Optional<T> wrapAsOptional(T value) {
        return Optional.ofNullable(value);
    }
}
```

MapStruct 1.4.2 generated a correct mapper that uses the ``wrapOptional`` method for wrapping the ``b`` field in an optional after having converted it:
```java
immutableATarget.b( wrapAsOptional( map( value.getB() ) ) );
```

### Actual behavior

After upgrading to 1.5.3, MapStruct fails to generate a mapper and bails out with the following error message:
```java
Can't map property "ImmutableBSource b" to "Optional<? extends com.bol.generics.ImmutableBTarget> b". Consider to declare/implement a mapping method: "Optional<? extends com.bol.generics.ImmutableBTarget> map(ImmutableBSource value)".
```

I expect it to generate a mapping method similar to the one generated by version 1.4.x.

### Steps to reproduce the problem

See https://github.com/ntinnemeier/mapstruct-1.5-upgrade-bugs/tree/main/generics-with-immutables for a full example.
Switch between version 1.4.x and 1.5.x to see the difference in behaviour.

I couldn't reproduce this behaviour with vanilla Java domain objects. That is to say, domain objects that are not generated by the immutables framework. I haven't checked what happens when the domain classes are generated by Lombok.

### MapStruct Version

MapStruct 1.5.3

**Comment by filiphr** [comment]
Thanks for reporting this @ntinnemeier. This sounds really similar to #2663. However, it seems like the fix for that one (PR #3007) is not fixing this one. We'll look into it.

**Comment by stef-corilus** [comment]
It still doesn't work as in the 1.4.2.Final version. I have the same method to wrap an optional as mentioned in the original post.

However, when I upgrade to 1.6.0, I get the error:

`Can't map property "DateTimeType onsetDate" to "Optional<? extends be.careconnect.nurse.domain.api.datatype.DateTimeType> onsetDate". Consider to declare/implement a mapping method: "Optional<? extends be.careconnect.nurse.domain.api.datatype.DateTimeType> map(DateTimeType value)"`

**Comment by filiphr** [comment]
@stef-corilus the original issue does not have wildcard with extends. Can you please create a new issue and provide an example that is creating the problem you are facing
