### ISSUE TITLE
Array to List mapping with adder fails

### ISSUE THREAD

**Issue by eroznik** [mapstruct/mapstruct#3165]
### Expected behavior

I would expect that given 
```java
public class User {
    private String id;
    private String email;
    private Permission[] permissions;
    // more code omitted for brevity
}
```
I'd be able to get a mapper to map the Java POJO to
```
message UserDTO {
    string id = 1;
    string email = 2;
    repeated PermissionDTO permissions = 3;
// more code omitted for brevity
}
```
Which  would map the `permission` array to the proto `permissionsList` through the adder pattern.

### Actual behavior

The auto-code generation fails because the generated code tries to directly add the whole array instead of iterating over it, map each value on its own and add it to the list.

### Steps to reproduce the problem

I modified the public Protobuff example so it fails
https://github.com/eroznik/mapstruct-examples/commit/f4c3a4eae7a678b8ba83820bdee4532f6d02b622

The pushed code is using the latest snapshot, mostly because I was using the latest snapshot version while testing it out locally. Keep in mind that the linked commit won't build.

### MapStruct Version

All versions that I tested.

**Comment by filiphr** [comment]
Thanks for reporting this @eroznik and thanks for the PR. I've added some comments to the PR (we need some tests before merging it).

I also changed the title, since the problem is not linked to protobuf, but it is generally linked that arrays cannot be mapped to collection / iterable using an adder method.

**Comment by eroznik** [comment]
Thanks for the review. I'll be adding tests for sure, now that it's confirmed the changes make sense.
