### ISSUE TITLE
Convert multiple beans into a map

### ISSUE THREAD

**Issue by shanrenxj** [mapstruct/mapstruct#3179]
### Use case

Hi filiphr, I find that you will understand many issues of bean to map as map to bean. What we need is bean to map, bean to map, bean to map, not map to bean

### Generated Code

Object a；
Object b;
Map m;
a -> m;
b -> m;
That m contains attributes of a and b

**Comment by filiphr** [comment]
I am not sure that I understand your request @shanrenxj. If you are looking for mapping a Bean into a Map then I would suggest that you follow #2504. If you meant something else, then please provide some examples and clarify what you need. Once you do that we can reopen the issue.
