### ISSUE TITLE
how to map a class field to a list

### ISSUE THREAD

**Issue by santy-ramirez** [mapstruct/mapstruct#3188]
### Use case

I'm wanting to implement mapping a dto object field to a list of an object; that is to say:
I want to send from a client

 { 
username:"string", 
password:"string",
 email:"String" ,
authority:"Log"
}
and map authority map to a list to be able to save in the database with the relationship of many to many

### Possible workarounds

try to fix it as below but not sure.

![qualifer](https://user-images.githubusercontent.com/66737901/223739418-a47bfab8-8f89-4dc8-acd8-c28b03e3e31e.png)
![mapper](https://user-images.githubusercontent.com/66737901/223739428-70bd04b0-d847-4bf7-9c0e-27e22f33484e.png)
![implement](https://user-images.githubusercontent.com/66737901/223739430-ae3a190c-4e6c-4d58-9c66-74787f667777.png)
![dto](https://user-images.githubusercontent.com/66737901/223739433-1b98a021-a15a-49f8-9c45-f564f4aede14.png)
![dao](https://user-images.githubusercontent.com/66737901/223739438-a1b12139-bbe0-45be-bad2-55d9d6224d73.png)

link del repo:
https://github.com/santy-ramirez/TestSpringSecurity

**Comment by filiphr** [comment]
From what I can see in your [`UserMapper`](https://github.com/santy-ramirez/TestSpringSecurity/blob/main/src/main/java/com/example/appTestSpringSecurity/mapper/UserMapper.java) everything is mapped. Can you please let us know what exactly isn't working? 

In the meantime I am going to close the issue, once we have more information we can reopen it
