### ISSUE TITLE
update entity and dto field type not refresh impl，error .NoSuchMethodError

### ISSUE THREAD

**Issue by linG5821** [mapstruct/mapstruct#3196]
### Expected behavior

Can refresh the implementation

### Actual behavior

throw java.lang.NoSuchMethodError

### Steps to reproduce the problem

1. I have tow class Apple and AppleDTO，Their fields are identical，It is normal for me to compile and convert. 
2. Without clearing the last compilation result(dot execute mvn clean), When I change the type of 'color' field in both, String->Integer, recompile.
3. Use mapper again for conversion，throw java.lang.NoSuchMethodError: 
4. lombok has been updated getter and setter，but  mapperImpl throw NoSuchMethodError

tips: When my entity, dto, and mapper are in the same package, they may succeed, but they cannot be refreshed when I put different packages separately

### MapStruct Version

lombok 1.8.26, mapstruct 1.5.3.Final, lombok-mapstruct-binding 0.2.0

**Comment by linG5821** [comment]
I had to do manually  `mvn clean compile`, to make it normal, I expect him to be automatic

**Comment by filiphr** [comment]
MapStruct is an annotation processor. If the mapper classes are not run through the annotation processor when something changes that this is some kind of a bug in the IDE that you are using. I would suggest that you raise this with the IDE. 

I have no problems with IntelliJ and as far as I know people using Eclipse have no issues as well.
