### ISSUE TITLE
Support for implicit conversion between java.time.LocalDate and java.time.LocalDateTime

### ISSUE THREAD

**Issue by belkin1667** [mapstruct/mapstruct#3199]
### Expected behavior

Either `LocalDateTime map(LocalDate date)` results in compilation error or mapping results in `date == null ? null : LocalDateTime.of(date, LocalTime.MIN)`

### Actual behavior

`LocalDateTime map(LocalDate date)` maps any `date` to `null`

The problem seems to be related to incorrect mapping sequence: `LocalDate` to `XMLGregorianCalendar` and `XMLGregorianCalendar` to `LocalDateTime`. Separately those mappings are correct, but combined are not:
Generated mapper contains the following line:
```java
LocalDateTime localDateTime = xmlGregorianCalendarToLocalDateTime( localDateToXmlGregorianCalendar( date ) ); 
```

Generated method `xmlGregorianCalendarToLocalDateTime(..)` returns `null` if hours, minutes or seconds are equal to `DatatypeConstants.FIELD_UNDEFINED`, which they are cause `localDateToXmlGregorianCalendar(..)` calls `javax.xml.datatype.DatatypeFactory::newXMLGregorianCalendarDate` which sets hours, minuts, seconds and milliseconds as `FIELD_UNDEFINED`

Methods I'm talking about for reference:
```java
        private static LocalDateTime xmlGregorianCalendarToLocalDateTime( XMLGregorianCalendar xcal ) {
            if ( xcal == null ) {
                return null;
            }

            if ( xcal.getYear() != DatatypeConstants.FIELD_UNDEFINED
                && xcal.getMonth() != DatatypeConstants.FIELD_UNDEFINED
                && xcal.getDay() != DatatypeConstants.FIELD_UNDEFINED
                && xcal.getHour() != DatatypeConstants.FIELD_UNDEFINED
                && xcal.getMinute() != DatatypeConstants.FIELD_UNDEFINED
            ) { //some mapping }
            return null;
        }
```

```java
private XMLGregorianCalendar localDateToXmlGregorianCalendar( LocalDate localDate ) {
            if ( localDate == null ) {
                return null;
            }

            return datatypeFactory.newXMLGregorianCalendarDate(
                localDate.getYear(),
                localDate.getMonthValue(),
                localDate.getDayOfMonth(),
                DatatypeConstants.FIELD_UNDEFINED );
        }
```

```java
    public XMLGregorianCalendar newXMLGregorianCalendarDate(
            final int year,
            final int month,
            final int day,
            final int timezone) {

            return newXMLGregorianCalendar(
                    year,
                    month,
                    day,
                    DatatypeConstants.FIELD_UNDEFINED, // hour
                    DatatypeConstants.FIELD_UNDEFINED, // minute
                    DatatypeConstants.FIELD_UNDEFINED, // second
                    DatatypeConstants.FIELD_UNDEFINED, // millisecond
                    timezone);
            }
```

### Steps to reproduce the problem

Define Mapper:
```java
@Mapper
public interface IssueBelkinmikeMapper {

    IssueBelkinmikeMapper INSTANCE = Mappers.getMapper( IssueBelkinmikeMapper.class );

    LocalDateTime map(LocalDate date);
}
```

Define Test:
```java
@WithClasses({
    IssueBelkinmikeMapper.class
})
@IssueKey("belkinmike")
class IssueBelkinmikeMapperTest {

    @ProcessorTest
    void throwsException() {
        LocalDate source = LocalDate.of(2022, 2, 2);
        LocalDateTime target = IssueBelkinmikeMapper.INSTANCE.map(source);
        assertThat(target).isNotNull();
    }
}
```

Test should pass or fail at mapper generation stage, but it is not

IMHO: It should fail at generating such mapping, cause I met this problem mapping dtos:

I had this classes
```java
class EntityDto {
    LocalDate dateFrom;
}
class Entity {
    LocalDate dateFrom;
}

interface MyMapper {
    EntityDto map(Entity e);
}
```

then dto field's type changed to LocalDateTime: 

```java
class EntityDto {
    LocalDateTime dateFrom;
}
class Entity {
    LocalDate dateFrom;
}

interface MyMapper {
    EntityDto map(Entity e);
}
```

And I would expect mapping to fail and attract my attention to it, but it did not

### MapStruct Version

main branch (commit id=a7ba12676d237957be0753076f436d7974c9f7f4)

**Comment by belkin1667** [comment]
Workaround is using `@Mapper( mappingControl = NoComplexMapping.class )`, however I do not consider current default behaviour is correct to be default

**Comment by belkin1667** [comment]
Found this comment regarding wrong matches using 2 step mappings:

https://github.com/mapstruct/mapstruct/blob/237543c47cb1827189e8c8d81b5b5b9c2eabadf1/processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java#L183

**Comment by belkin1667** [comment]
I believe MapStruct (regarding to 2 step mappings) operates assuming that if methods signatures match, then there is a correct mapping, however it is not always true and depends on implementation of found methods, as we can see. Therefore I suggest introducing some mechanics to exclude some known incorrect mappings

Would appreciate some help on ideas how to better implement this idea as I'm new to MapStruct source code

**Comment by filiphr** [comment]
MapStruct actually does not have an out of the box support for mapping between `LocalDate` and `LocalDateTime`. This works by accident via the 2-step mappings.

I would rename this issue to support implicit mapping between `LocalDate` and `LocalDateTime`. The mapping should be in the following manner:

* `LocalDate` -> `LocalDateTime`: `date.atStartOfDay()`
* `LocalDateTime` -> `LocalDate`: `date.toLocalDate()`

The `JavaZonedDateTimeToDateConversion` can be used as an example.

This is a good issue for someone from the community that is interested in contributing to MapStruct. Please let us know if you would like to work on this. @belkin1667 you have the priority in case you are interested in adding this functionality.

----

A workaround for this would be to define your own custom mapping for `LocalDate` -> `LocalDateTime`

e.g.

```java
public class CustomLocalDateTimeMapper {

    public LocalDateTime toLocalDateTime(LocalDate localDate) {
        return localDate != null ? localDate.atStartOfDay() : null;
    }
    
    public LocalDate toLocalDate(LocalDateTime localDateTime) {
        return localDateTime != null ? localDateTime.toLocalDate() : null;
    }

}
```

and then put `CustomLocalDateTimeMapper` in `Mapper#uses`
