### ISSUE TITLE
Chain some mappers

### ISSUE THREAD

**Issue by BrunoMacherel-eaton** [mapstruct/mapstruct#3201]
### Use case

I have 3 classes : A, B and C
and some mappers : 
 * A -> B
 * B -> C
It could be nice to create a third mapper (A -> C) that use the first two.

```java
@Mapper
public abstract class TestMapper {

    public abstract B toB(A a);
    public abstract C toC(B b);

    public abstract C toC(A a); // Chain existing mapper methods ?
/*
    // Expected implementation
    public C toC(A a) {
        C c = toC(toB(a));
        additionalStuff(a, c);
        return c;
    }
*/

    @AfterMapping
    protected void additionalStuff(A a, @MappingTarget B b) {
        // some mapping logic
    }

    @AfterMapping
    protected void additionalStuff(A a, @MappingTarget C c) {
        // some mapping logic
    }
}
```

I first ask on stackoverflow if it is possible to to so (but it seems not) : https://stackoverflow.com/questions/75742150/is-it-possible-to-chain-mappers-using-mapstruct

**Comment by Zegveld** [comment]
I do not think that this will be something that Mapstruct will support easily.

The reason why I believe this is as follows:

1. There is the possibility that `A to B` will lose information that is still present when going from `A to C`. This is the reason why you do not always want to chain mappers this way.
2. This can be done trivially by a developer without using an unimplemented method:
```
public C toC(A a) {
  return toC(toB(a));
}
```
3. if you have a mapper that wants to go from `A` to `C` and you supply the methods `B toB(A a)` and `C toC(B b)` mapstruct will use these.
```
class Source {
  private A obj; //getters and setters omitted but present
}
class Target {
  private C obj; //getters and setters omitted but present
}
@Mapper

interface MyMapper {
  Target map(Source source);
}
```
The generated implementation will be the equivalent of:
```
  target.setObj( toC( toB( target.getObj() ) ) );
```
The maximum supported amount of methods for chaining is 2.

But these are just my thoughts about it.

**Comment by Zegveld** [comment]
I just took a look at your stackoverflow question, and I think what you are looking for is something completely different.

You basically want to map A to B, then B to C then update the result with remain information from A. With is doable with still a single method that you implement yourself, while you let MapStruct handle all the mapping information.
```
@Mapper
public abstract class TestMapper {

    // mappings A to B
    public abstract B toB(A a); // calls additionalStuffB method

    // mappings B to C
    public abstract C toC(B b);

    // additional mappings A to C
    abstract C updateCwithA(@MappingTarget C c, A a); // calls additionalStuffC method

    public C toC(A a) {
      return updateCwithA( toC( toB( a ) ), a);
    }

    @AfterMapping
    protected void additionalStuffB(A a, @MappingTarget B b) {
        // some mapping logic
    }

    @AfterMapping
    protected void additionalStuffC(A a, @MappingTarget C c) {
        // some mapping logic
    }
}
```

**Comment by BrunoMacherel-eaton** [comment]
> 1. There is the possibility that `A to B` will lose information that is still present when going from `A to C`. This is the reason why you do not always want to chain mappers this way.

That's why I want to have an additional "AfterMapping" method that will add the missing informations (but not reimplementing the whole mapping).

> 2. This can be done trivially by a developer without using an unimplemented method:
> 
> ```
> public C toC(A a) {
>   return toC(toB(a));
> }
> ```

I know that's trivial and that's what I did but I prefer let mapstruct do this for me.

> 3. if you have a mapper that wants to go from `A` to `C` and you supply the methods `B toB(A a)` and `C toC(B b)` mapstruct will use these.
>
> ... 
> The generated implementation will be the equivalent of:
> 
> ```
>   target.setObj( toC( toB( target.getObj() ) ) );
> ```

This is not what I ask for.

**Comment by filiphr** [comment]
This to me looks like an edge case and MapStruct is there to solve some of the problems. If you need to customize something it is really trivial to do it.

In your example doing what you expect is easier than MapStruct doing the chaining.

e.g.

```java
    public C toC(A a) {
        C c = toC(toB(a));
        additionalStuff(a, c);
        return c;
    }
```

If we start doing the chaining there can be non trivial complexity due to the fact that there might be multiple paths to reach from `A` to `C`
