### ISSUE TITLE
Improve line location report for invalid qualifier for SubclassMapping

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#3202]
In PR #3120 we added support for `qualifiedBy` and `qualifiedByName`. Our generic logic seems like it is putting the error line location on the method element itself. We should instead use the `@SubclassMapping` element for reporting the error.

This issue is a good issue to get started with MapStruct. If the original creator of the PR @EvaristeGalois11 is not interested in adding this, then I would invite someone from the community to give it a go.

**Comment by EvaristeGalois11** [comment]
Yep no problem, i'll give it a try! :rocket:
