### ISSUE TITLE
One2Many and Many2One

### ISSUE THREAD

**Issue by TimmyME** [mapstruct/mapstruct#3206]
### Use case

I would like Mapstruct to autogenerate code for one2many and many2one scenarios.
It can be controlled by a annotation on class level or be the default logic.

### Generated Code

**Examples classes:**
```java
class FromMany {
    String[] fieldOne;
    List<String> fieldTwo;
}

class ToOne {
    String fieldOne;
    String fieldOne;
}
```

Example how mapstruct can generate the code(and somthing similar for arrays):

```java
    protected List<String> mapOne2Many(String value) {
        if (value != null) {
            return Collections.singletonList(value);
        }
        return null;
    }

     protected String mapMany2One(List<String> value) {
          if (CollectionUtils.isNotEmpty(value)) {
            return value.get(0);
        }
        return null;
    }
```

### Possible workarounds

Today I add these many2one and one2many manually.

### MapStruct Version

1.5.3.Final

**Comment by filiphr** [comment]
Please use the [GitHub Discussions](https://github.com/mapstruct/mapstruct/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) for asking questions.

We currently do not have such a mechanism. You would need to write it by hand.

What you can try is to use generics.

e.g.

```java
    protected <T> List<T> mapOne2Many(T value) {
        if (value != null) {
            return Collections.singletonList(value);
        }
        return null;
    }

     protected <T> T mapMany2One(List<T> value) {
          if (CollectionUtils.isNotEmpty(value)) {
            return value.get(0);
        }
        return null;
    }
```
