### ISSUE TITLE
How do I prohibit the use of automatic mapping capabilities? I expect that if the relationship between fields is not explicitly specified, an error will occur during compilation

### ISSUE THREAD

**Issue by mgjun** [mapstruct/mapstruct#3215]
### Expected behavior
```java
public class Person {
    private String name;
    private int age;

    // getter, setter
}

public class PersonDto {
    private String name;
    private int age;

    // getter, setter
}

@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface PersonMapper {

    // if name field not use @Mapping, except failed when compile
    @Mapping(source = "age", target = "age")
    PersonDto to(Person person);
}
```
### Actual behavior

currenty it will automatic mapping "name" fields.
I want to use the Mapstruct compilation check, its a good ability. but automatic mapping is not what I want.

### Steps to reproduce the problem
```java
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface PersonMapper {

    // if name field not use @Mapping, except failed when compile
    @Mapping(source = "age", target = "age")
    PersonDto to(Person person);
}
```
### MapStruct Version

MapStruct 1.4.1.Final

**Comment by filiphr** [comment]
Please use our [GitHub Discussions](https://github.com/mapstruct/mapstruct/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) for asking questions.

I would suggest you to look into `@MappingControl`. With that you can control what kind of Mapping you want to do, i.e. you can disable implicit conversions.
