### ISSUE TITLE
Java 5 Language Level Support

### ISSUE THREAD

**Issue by ujaehnic** [mapstruct/mapstruct#322]
Please consider to respect compliance to java language level 5. In particular now it is not possible to generate Mapper with restriction to java language level 5 since ``mapstruct`` generates the ``@Override`` annotation to the generated mapping methods. There is a workaround using abstract classes instead of interfaces for ``Mapper`` declaration, but it would be more convenient having a configuration option to specify java language level and prevent from generating ``@Override`` annotion in case java language level is less than 6.

**Comment by gunnarmorling** [comment]
Hi @ujaehnic, how is it going with this one? Do you still have plans to send a pull request for it?

**Comment by gunnarmorling** [comment]
Hi @ujaehnic, are you still interested in this? If not I'd close this one as "Won't fix" as Java 5 really is ancient by now.

**Comment by gunnarmorling** [comment]
Going to close this one as we discussed, @ujaehnic.
