### ISSUE TITLE
Add functionality for mapping map

### ISSUE THREAD

**Issue by onacit** [mapstruct/mapstruct#3232]
### Use case

This is not the case of `java.util.Map`.

Say we have the following classes for mapping entities and dtos.

```java
class ClassRoomEntity {
    String name;
}

class ClassRoomType {
    String name;
}
```

MapStruct does such a beautiful job for mapping those classes.

And the technique using semicolon(`;`) for filtering selection is really helping me.

```
/classRooms;name=a;name=b/{subpath}/{subpath}
```

Which, internally through JPA static metamodel, generates an SQL looks like this.

```
SELECT *
FROM class_room
WHERE
    name = 'a'
    AND name = 'b'
```

Now let us see following DTO.

```java
class ClassInfoType {

    private ClassRoomType classRoom; // < maps from a ClassRoomEntity

    private SomeOtherType someOther; // <- maps from a SomeOtherEntity

    private String anotherProperty;
}
```

We know that MapStruct can also have the capability for mapping these kind of mapping.

And the controller's path expression will look like this.

```
/classInfos;classRoom.name=a;classRoom.name=b;someOther.age=15/{subResource}
```

Now it'll be much handy when I access the mapping info, in runtime, which may give information like this.

* `classRoom.name` is mapping to/from `ClassRoomEntity`'s `name` property.
* `someOther.age` is mapping to/from `SomeOtherEntity`'s `age` property.

Now the feature being requested by this issue is the **mapping information** of a *Mapper* and that's why I call it a *mapping map*.

I hope my poor English make you understand what I want.

Thanks.

**Comment by filiphr** [comment]
@onacit I am not sure that I understand what you would like MapStruct to do in this case. We do have `@Condition` and in 1.6 we have `@TargetPropertyName` that you can combine with a `@Context` annotation to decide if a property needs to be mapped or not.
