### ISSUE TITLE
dependsOn not working with expressions

### ISSUE THREAD

**Issue by AlexSala07** [mapstruct/mapstruct#3234]
### Expected behavior

Following mapping:
```java
    @Mapping(target = "date", expression = "java(computeDate(contactEntity, dto))")
    @Mapping(target = "mail", dependsOn = "date")
    public abstract ContactEntity updateContactEntity(@MappingTarget ContactEntity contactEntity, ContactUpdateDto dto);
```
should generate following code:
```java
        contactEntity.setDate( computeDate(contactEntity, dto) );
        contactEntity.setMail( dto.getMail() );
```

### Actual behavior

Following mapping:
```java
    @Mapping(target = "date", expression = "java(computeDate(contactEntity, dto))")
    @Mapping(target = "mail", dependsOn = "date")
    public abstract ContactEntity updateContactEntity(@MappingTarget ContactEntity contactEntity, ContactUpdateDto dto);
```
currently generates following code:
```java
        contactEntity.setMail( dto.getMail() );
        contactEntity.setDate( computeDate(contactEntity, dto) );
```

Basically ignoring the order given by the `dependsOn` property.

### Steps to reproduce the problem

Using the mapping provided in the "Actual behavior" should be enough to reproduce this issue.
Similar issue that should have been fixed but with constants instead of expressions: #619

### MapStruct Version

MapStruct 1.5.2.Final

**Comment by filiphr** [comment]
This is indeed similar to #619 (or even the same as #619). I am going to close this in favour of that one, since they would need the same fix.
