### ISSUE TITLE
Add quarkus 3 support

### ISSUE THREAD

**Issue by yuhaibohotmail** [mapstruct/mapstruct#3235]
### Use case

Establish a version that fully supports Jakarta - EE 10 to support quarkus3 and spring boot 3

### MapStruct Version

Mapstruct 1.5.2

**Comment by filiphr** [comment]
Closing this as a duplicate of #2950. We also have #2567 (which is in 1.5 already).

If none of those issues are matching what you need can you please clarify what is missing in MapStruct?
