### ISSUE TITLE
jakarta-cdi component model not in docs?

### ISSUE THREAD

**Issue by edeandrea** [mapstruct/mapstruct#3236]
### Expected behavior

Offshoot from #2950 - I don't see the `jakarta-cdi` model mentioned in https://mapstruct.org/documentation/stable/reference/html/#configuration-options ? Shouldn't it be listed in the `mapstruct.defaultComponentModel` section of the table?

### Steps to reproduce the problem

Look at https://mapstruct.org/documentation/stable/reference/html/#configuration-options and notice that `jakarta-cdi` is not there in the documentation.

### MapStruct Version

1.5.4

**Comment by filiphr** [comment]
Thanks @edeandrea. Will add this to the docs
