### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by wirekang** [mapstruct/mapstruct#3255]
### Use case

I have an mapper written in kotlin.

```kotlin

@Mapper(
    unmappedSourcePolicy = ReportingPolicy.ERROR,
    unmappedTargetPolicy = ReportingPolicy.ERROR,
)
abstract class FooMapper {
    @Mappings(...)
    abstract fun map(src: Foo): Bar
}
```

When there is mapping error due to changes of `Foo` or `Bar`, the error message is:

```

> Task :core:kaptKotlin
/home/the/path/to/project/core/build/tmp/kapt3/stubs/main/foo/bar/foo/bar/FooMapper.java:142: error: Unmapped source property: "baz".
    public abstract com.onout.foo.bar.dto.Bar map(@org.jetbrains.annotations.NotNull
                                               ^
```

This error message has problems.

1. Not enough information
2. Poor readablility

The source of both error is generated java mapper.

Even though the error shows which line has a problem, the line is not a human written, but is generated java mapper which has poor readablility (because it is not born to be read). And the generated java method takes several lines, so I can't figure out the arguments it takes by error message which shows single line.

For now, when there are errors my routine is:

1. Checkout which line in generated java mapper has problem.
2. Open the generated java file and identify the method. (very painful)
3. Go back to kotlin mapper and identify the method.
4. Fix.

The generated java mapper looks like:

```
package com.foo.bar.baz;

import java.lang.System;

@org.mapstruct.Mapper(config = com.foo.bar.baz.BaseMapperConfig.class)
@kotlin.Metadata(mv = {1, 8, 0}, k = 1, d1 = {"veryveryveryveryveryveryveryvery long something"})
public abstract class ShopMapper {
    
    public FooMapper() {
        super();
    }
    
    @org.jetbrains.annotations.NotNull
    public abstract com.foo.bar.baz.dto.Bar map(@org.jetbrains.annotations.NotNull
    com.foo.bar.baz Foo);

    @org.jetbrains.annotations.NotNull
    public abstract com.foo.bar.baz.dto.Bar map(@org.jetbrains.annotations.NotNull
    com.foo.bar.baz Foo);
```

### Generated Code

-

### Possible workarounds

It would be very helpul if the error message contains the summary of the method.

As-is:
```

/home/the/path/to/project/core/build/tmp/kapt3/stubs/main/foo/bar/foo/bar/FooMapper.java:142: error: Unmapped source property: "baz".
    public abstract com.onout.foo.bar.dto.Bar map(@org.jetbrains.annotations.NotNull
                                               ^
```

## 1
```

/home/the/path/to/project/core/build/tmp/kapt3/stubs/main/foo/bar/foo/bar/FooMapper.java:142: error: Unmapped source property: "baz".
    parameters: com.foo.bar.Foo, @Context java.lang.String,
    returns: com.foo.bar.dto.Bar

    public abstract com.onout.foo.bar.dto.Bar map(@org.jetbrains.annotations.NotNull
                                               ^
```

## 2
```

/home/the/path/to/project/core/build/tmp/kapt3/stubs/main/foo/bar/foo/bar/FooMapper.java:142: error: Unmapped source property: "baz".
    parameters: com.foo.bar.Foo, @Context java.lang.String, @MappingTarget com.foo.bar.dto.Bar
    returns: void

    public abstract com.onout.foo.bar.dto.Bar map(@org.jetbrains.annotations.NotNull
                                               ^
```

This have a huge impact on productivity because our project is rely on mapstruct a lot.

### MapStruct Version

1.5.3-final

**Comment by filiphr** [comment]
@wirekang the location of the error messages you are seeing comes from KAPT from Kotlin. MapStruct reports the element (method) on which the error happened.  From MapStruct you only have "Unmapped source property: "baz"". It seems like KAPT is not displaying the error message nicely.

I think that it would be best if we can review this as part of #2522. @wirekang are you OK with us closing this in favour of #2522?

**Comment by wirekang** [comment]
Please rescue us from painful labor.
