### ISSUE TITLE
MapStruct mapping fields in DTO flaky with Spring Boot 3

### ISSUE THREAD

**Issue by ShubamVirdi** [mapstruct/mapstruct#3256]
### Expected behavior

MapStruct should always map add DTO classes and subclasses

### Actual behavior

MapStruct is sometimes mapping the classes and subclasses and sometimes not. The Mapper Impl file is sometimes having empty object creation definitions and when we rerun the project by changing anything in mapper interface it maps all values.
but this happens again and again.

MapStruct Version: 1.5.4.Final
Spring Boot Version: 3.0.6

### Steps to reproduce the problem

@Mapper(unmappedTargetPolicy = ReportingPolicy.WARN)
public interface CustomerProfileMapper {

    CustomerProfileMapper INSTANCE = Mappers.getMapper(CustomerProfileMapper.class);

    CustomerProfile toCustomerProfile(CustomerProfileDTO customerProfileDTO);

    CustomerProfileAddress toCustomerProfileAddress(CustomerProfileAddressDTO customerProfileAddressDTO);

    CustomerProfileConnection toCustomerProfileConnection(CustomerProfileConnectionDTO customerProfileConnectionDTO);

    CustomerProfileConsent toCustomerProfileConsent(CustomerProfileConsentDTO customerProfileConsent);

    CustomerProfileAdditionalAttributes toCustomerProfileAdditionalAttributes(CustomerProfileAdditionalAttributesDTO customerProfileAdditionalAttributes);
}

### MapStruct Version

1.5.4.Final

**Comment by filiphr** [comment]
An update to Spring Boot 3 cannot have an impact on MapStruct, because MapStruct is an annotation processor that is not linked to Spring Boot at all.

It might be some kind of a bug in IntelliJ / Eclipse or your IDE of your choice. I would suggest looking into that.

**Comment by MattWiersma** [comment]
To any who come across this in the future. I had this same issue and the solution was based around the annotation processor ordering in my build script. Specifically Lombok.

You must have the Lombok annotation processor before the MapStruct annotation processor in the build file or else MapStruct won't know about the generated getters/setters and builders.
