### ISSUE TITLE
Unknown property "xxxx" in result type xxxx. Did you mean "null"?

### ISSUE THREAD

**Issue by liuyuan-1024** [mapstruct/mapstruct#3268]
### Steps to reproduce the problem

[springboot-init.zip](https://github.com/mapstruct/mapstruct/files/11427444/springboot-init.zip)

When I run maven complie,  IDEA will report an error

The error is as follows

Unknown property "languageName" in result type RepositoryVO. Did you mean "null"?

### MapStruct Version

MapStruct 1.5.5.Final

**Comment by shuaixiaomi** [comment]
hi , how you solved this problem?
