### ISSUE TITLE
实现类生成错误

### ISSUE THREAD

**Issue by isomd** [mapstruct/mapstruct#3279]
### Expected behavior

实现类可以实时生成
![image](https://github.com/mapstruct/mapstruct/assets/102352438/df15bf54-fb62-4a4e-a8fd-c1402af2d91b)
![image](https://github.com/mapstruct/mapstruct/assets/102352438/145f1278-0d90-4df9-a3ab-9d3da14b3153)

### Actual behavior

package com.xc.mapper;

import com.xc.entity.dos.UserInfo;
import com.xc.entity.vos.params.RegisterParams;
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-05-16T09:41:17+0800",
    comments = "version: 1.5.3.Final, compiler: javac, environment: Java 17.0.6 (Amazon.com Inc.)"
)
public class UserCopyMapperImpl implements UserCopyMapper {

    @Override
    public UserInfo copy(RegisterParams registerParams) {
        if ( registerParams == null ) {
            return null;
        }

        UserInfo userInfo = new UserInfo();

        return userInfo;
    }
}

### Steps to reproduce the problem

我写了一个copy接口后，开始可以正常使用，但是在我添加了一个接口后删除就出现了原本的接口无法实现copy功能

### MapStruct Version

mapstruct1.5.3

**Comment by filiphr** [comment]
@isomd I am not sure that I understand what the problem is. Can you please explain in English and to show us what you expect to happen?

The fact that there are no getters / setters invoked might be due to the fact that you are using Lombok, but not the Lombok MapStruct binding dependency.

**Comment by isomd** [comment]
@filiphr Sorry, I explain again in English. At first, I'm using the mapstruct as usual, but I find a bug. When I typed a wrong the mapstruct interface and deleted it, I found a bug where the correct interface didn't do what it was supposed to do. I saw the codes which were generated by the mapstruct. The implementation class of the UserCopyMapper interface is the image above. As you can see, it does not have a normal generate assignment statement. So, I uploaded
 the bug. I apologize for the lack of clarity.

**Comment by filiphr** [comment]
@isomd the problem in the image you generated is the fact that it is empty (no getters / setters are invoked)? Are you using Lombok? How does your `UserInfo` and `RegisterParams` look like?

**Comment by isomd** [comment]
@filiphr Yes, I know what I should do. Thank you very much.
