### ISSUE TITLE
imp code is generated, but no values are assigned

### ISSUE THREAD

**Issue by PerkinsLi** [mapstruct/mapstruct#3282]
### Expected behavior

I want mapstruct compile-time error if mapstruct can't assign values

### Actual behavior

```
@Getter
@Setter
public class User implements Serializable {

    private String name;

    private Integer age;
}

@Getter
@Setter
public class User1 implements Serializable {

    private String name;

    private Integer age;

}

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-05-22T16:12:22+0800",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 1.8.0_191 (Oracle Corporation)"
)
public class UserMapperImpl implements UserMapper {

    @Override
    public User1 toUser1(User source) {
        if ( source == null ) {
            return null;
        }

        User1 user1 = new User1();

        return user1;
    }
}

```

now  I add lombok-mapstruct-binding annotationProcessorPaths solve the problem,  but  I want find how much problem code already generated before I solve the problem. 

 Is there a configuration? If there is no set, get method, the compilation times error

### Steps to reproduce the problem

use lombok and mapstruct all ,  
lombok version 1.18.16
mapstruct version 1.4.1.Final

### MapStruct Version

1.4.1.Final

**Comment by filiphr** [comment]
There is no configuration for this. We do have #1140, which is meant to output a warning if no property has been mapped.

Closing this in favour of #1140
