### ISSUE TITLE
Use method as mapping source

### ISSUE THREAD

**Issue by simcar** [mapstruct/mapstruct#3290]
### Use case

I read the documentation, and as i noticed there is no way to map a method as mapping source. As example, consider the following code:

```java
public class Foo {
   private Integer id;

   public String bar() {
      return "Id: " + String.valueOf(this.id);
   }
}

public class FooDto {
   public Integer id;
   public String bar;
}
```
A possible solution is to define a method with @AfterMapping annotation, like this:

```java
@Mapper
public interface FooMapper {

   FooDto toFooDto(Foo foo);

   @AfterMapping
   default void mapBar(Foo foo, @MappingTarget FooDto dto) {
      dto.bar = foo.bar();
   }

}
```

### Generated Code

A cleaner solution might be to annotate the mapping method as follows:

```java
@Mapping(target="bar", sourceMethod="bar")
FooDto toFooDto(Foo foo);
```

Do you think it might be a good idea? If yes, I could submit a pull request with the feature implementation.

**Comment by filiphr** [comment]
This can be already achieved by a custom `AccessorNamingStrategy`.  See #3286 and #3211 for more information.

Adding something like `sourceMethod` to `@Mapping` is not something that I would like to do. 

Other ways, apart of a custom `AccessorNamingStrategy` would be to us an expression
