### ISSUE TITLE
@ApplicationScoped not generated, if configured in Eclipse IDE

### ISSUE THREAD

**Issue by mheydem** [mapstruct/mapstruct#3294]
### Expected behavior

If the annotation processing for mapstruct is configured with mapstruct.defaultComponentModel=jakarta-cdi in Eclipse IDE (2022-09), the generated mappers shall have the annotation jakarta.enterprise.context.ApplicationScoped.

### Actual behavior

If the annotation processing for mapstruct is configured with mapstruct.defaultComponentModel=jakarta-cdi in Eclipse IDE, the generated mappers DO NOT have the annotation jakarta.enterprise.context.ApplicationScoped.

### Steps to reproduce the problem

Interestingly the mappers are correctly generated when using maven configuration:
```
<build>
    	<plugins>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<configuration>
			<source>17</source>
			<target>17</target>
			<annotationProcessorPaths>
				<path>
					<groupId>org.mapstruct</groupId>
					<artifactId>mapstruct-processor</artifactId>
					<version>1.5.5.Final</version>
				</path>
			</annotationProcessorPaths>
			<generatedSourcesDirectory>
				${project.basedir}/src-gen
			</generatedSourcesDirectory>
			<showWarnings>true</showWarnings>
			<compilerArgs>
				<arg>
					-Amapstruct.destdir=src-gen
				</arg>
				<arg>
					-Amapstruct.defaultComponentModel=jakarta-cdi
				</arg>
				<arg>
					-Amapstruct.suppressGeneratorTimestamp=true
				</arg>
				<arg>
					-Amapstruct.suppressGeneratorVersionInfoComment=true
				</arg>
				<arg>
					-Amapstruct.verbose=true
				</arg>
			</compilerArgs>
		</configuration>
	</plugin>
</plugins>
</build>
```

### MapStruct Version

1.5.5.Final

**Comment by Zegveld** [comment]
The configuration seems to work for me with `2022.06`.
can you check if the Processor options are there in the Project Properties as seen below?
![image](https://github.com/mapstruct/mapstruct/assets/41897697/da5461b9-ef7d-4e4d-b40d-78eec9f8c946)

**Comment by mheydem** [comment]
Thank you for the quick response.
It is an operating error on my side.
I forgot to update the referenced mapstruct version in Factory Path.
It was still pointing to 1.5.2.Final which does not implement the defaultComponentModel=jacarta-cdi.
After pointing to 1.5.5.Final it works correctly.
Sorry for the inconvenience.
