### ISSUE TITLE
Support for multiple fields in source 

### ISSUE THREAD

**Issue by ollio** [mapstruct/mapstruct#3295]
Hi,

It would be nice to be able to specify multiple fields in the source attributes that are then mapped into a list.

```java
@Mapping(target = "counters", source = "processedArea,machineDuration", qualifiedByName = "mapCounters")
Usage map(Machine machine);

@Named("mapCounters")
default List<CounterValue> mapCounters(Counter ... counter) {
    return MappingUtils.list(counter);
}

```

In this case 'Usage' has a list of counters: 

```java
@Data
class Usage {
   private List<Counter> counters;
}
```

These source fields are mapped with several another @Mapping definition into a Counter. For e.g.:

```java
default Counter map(SquareMeter value) {
    return notNull(value, CounterTotalArea::of);
}

```

With the support of multiple sources it will become really flexible and easy to enhance. 

Thanks, Olli

**Comment by filiphr** [comment]
Hey @ollio we've already had a request for this and we've rejected this. Have a look at https://github.com/mapstruct/mapstruct/issues/2104#issuecomment-643601662 for our reasoning. 

What you can actually do is:

```java
@Mapper
public interface CounterMapper {

    @Mapping(target = "counters", source = "machine")
    Usage map(Machine machine);

    default List<CounterValue> mapCounters(Machine machine) {
        return MappingUtils.list(map(machine.getProcessedArea()), map(machine.getMachineDuration()));
    }

    default Counter map(SquareMeter value) {
        return notNull(value, CounterTotalArea::of);
    }


}
```
