### ISSUE TITLE
FR: Work with lazy scalar property of hibernate3+

### ISSUE THREAD

**Issue by babyfish-ct** [mapstruct/mapstruct#3313]
### Use case

**Problem**

In this article: https://medium.com/cloud-workers/mapstruct-and-hibernate-jpa-lazy-loading-1c1c6f416e, the author uses the `Condition` of mapstruct to handle the lazy loading problem of Hibernate.

The lazy loading problem discussed in this article is the classic feature of Hibernate2+, for many-to-one association, it is a uninitialized proxy object; for one-to-many/many-to-many association, it is special uninitialized collection implementation provided by hibernate. Although the proxy or collection is uninitialized, developer can safely get it and then use `Hibernate.isInitialized(obj)` to check whether it is initialized.

However, since Hibernate3, another new lazy loading mechanism is provided. Not only the association properties, but also the scalar properties can be lazy. please view the link https://stackoverflow.com/questions/19610085/using-lazy-for-properties-in-hibernate, this feature is designed for lob scalar properties.

Unfortunately, for this uninitialized scalar properties, exception will be immediately raised when the getter is called, the developer must use [Hibernate.isPropertyInitialized(obj, propertyName)](https://docs.jboss.org/hibernate/orm/6.0/javadocs/org/hibernate/Hibernate.html#isPropertyInitialized(java.lang.Object,java.lang.String)) to check it before access it.

So the solution in this article cannot work with lazy scalar property in Hibernate3+.

**Expected behavior**

Support a new annotation `@PropertyCondition`, it can be used like this

```java
@PropertyCondition
public boolean isAccessible(MyData data, String propertyName) {
    return Hibernate.isPropertyInitialized(data, propertyName);
}
```

**Comment by filiphr** [comment]
@babyfish-ct I don't think that a new condition will be needed. I think that this would be possible using the new `@TargetPropertyName` from https://github.com/mapstruct/mapstruct/issues/2688. Do you think that you can try this out from main @babyfish-ct?

**Comment by babyfish-ct** [comment]
I'm developing a new ORM, a `GraphQL` style. Its query works like GraphQL, so it can query data structure with any shape.

That means all ORM entities must dynamic types, each property *(either association or scalar)* can be specified or unspecified

`Unspecified != Null`
-    Not specified means unknown, user do not want to fetch it
-    Null means known but no data, use has fetched it.

For unspecified property:

-   Exception will be raised when it is accessed by code directly, like Hibernate3+ *(In fact, the dynamism of entity objects in this ORM is the result of extending the pre-error lazy property exception of Hibernate 3+ to any property of any object)*
-  Property will be ignored when it serialized to JSON.

Although this ORM is not finished, but now it have some users, they use condition expression on every type and every property when they want to convert dynamic object to static pojo, like #2688, this is very hard.

Today, I provided users with a workaround to help them mitigate this issue even though mapstruct does not support this feature. So, the sense of urgency is not as high as it was a few days ago. However, is it possible for mapstruct to support this feature in the future, which would be much more elegant than the current workaround?

**Comment by filiphr** [comment]
I am not sure that I understand @babyfish-ct. 

What is the problem in using

```java
@Condition
public boolean isAccessible(MyData data, @TargetPropertyName String propertyName) {
    return Hibernate.isPropertyInitialized(data, propertyName);
}

```

instead of: 

```java
@PropertyCondition
public boolean isAccessible(MyData data, String propertyName) {
    return Hibernate.isPropertyInitialized(data, propertyName);
}

```

Keep in mind that the `@TargetPropertyName` is not yet released, so only available in 1.6.0-SNAPSHOT and on main.

**Comment by babyfish-ct** [comment]
OK, I understand. same requirement.

Super cool, now everything property can be dynamic, handle data structure of **ANY** shape

**Comment by babyfish-ct** [comment]
Suggestion: @TargetPropertyName -> @PropertyName

Reason: @TargetPropertyName may make use think it is property name of target object, actual, it is property name of source object, not target object

**Comment by filiphr** [comment]
You might be right @babyfish-ct. I've opened https://github.com/mapstruct/mapstruct/issues/3323 to look into this before we do the 1.6 release
