### ISSUE TITLE
Add `@SourcePropertyName` to handle a property name of the source object

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#3323]
A suggestion from https://github.com/mapstruct/mapstruct/issues/3313#issuecomment-1627449047

**Comment by filiphr** [comment]
We might actually need a new `@SourcePropertyName` to have the source property. Currently all our tests use implicit mapping, and in this case the source and target property names are identical.

**Comment by filiphr** [comment]
Discussed with the team we are going to add `@SourcePropertyName` that would pass the name of the source property and `@TargetPropertyName` that would pass the target property name

**Comment by aboqasem** [comment]
Hello @filiphr & @babyfish-ct, I do not see where's the confusion in the name. It's indeed getting the `target`'s property name as the name says. I added a test case that proves that: https://github.com/aboqasem/mapstruct/commit/76e7067ebe51e9bce2db07b73a84953b17305a28.

Am I missing something?

**Comment by thunderhook** [comment]
@aboqasem I looked at the tests and the code and yes, indeed. The `@TargetPropertyName` handles the `target`s property name. So there will be an additional `@SourcePropertyName` annotation which handles the `source`s property name. I will rename this ticket to avoid any further confusion.

**Comment by thunderhook** [comment]
What I would do in your case: Take a look at the [commit](https://github.com/filiphr/mapstruct/commit/8fa286fe4ce790cc2a65adff55c813bc9717437a) where the `@TargetPropertyName` was introduced to see out how it works. I think the code for the `@SourcePropertyName` will be very similar.

Yes, the `.ftl` files are [Apache FreeMarker](https://freemarker.apache.org/index.html) java templates which are used for the code generation of mappers (and all of their belongings). The `org.mapstruct.ap.internal.processor.MapperCreationProcessor` is the main processor that handles the creation of a mapper class.

Another hint: When you run a test, e.g. the `TargetPropertyNameTest`, you can have a look at the generated sources and mappers that are generated and compiled in: `...\mapstruct\processor\target\compilation-tests\org.mapstruct.ap.test.conditional.targetpropertyname.TargetPropertyNameTest`.

If it is okay with @filiphr (I don't know if he's currently working on this issue) you are welcome to contribute!

**Comment by aboqasem** [comment]
Thanks a lot, @thunderhook!

Let me try to check the `good-first-issue`s first, since there's 5 of them at the moment.

**Comment by filiphr** [comment]
@aboqasem thanks for your work on this. This is one of the last issues I'd like to have in before releasing a Beta 1 from 1.6. Have far are you with your work on this?

**Comment by aboqasem** [comment]
> Have far are you with your work on this?

I only [added a few tests](https://github.com/mapstruct/mapstruct/compare/main...aboqasem:mapstruct:feat/%233323-property-names) and stopped to see `good-first-issue`s to better understand how the code works. I still do not quite get how things are working and I am not sure how to debug yet.

If you find the test cases useful you may just copy [the patch](https://github.com/mapstruct/mapstruct/compare/main...aboqasem:mapstruct:feat/%233323-property-names.patch) and continue working on it.

Thanks for understanding!

**Comment by filiphr** [comment]
That makes sense @markostijak. That you are asking might be more in the direction of #2559.  

However, I would suggest to create a new issue for this, let's keep this issue only for `@SourcePropertyName`. Implementation wise it is really different
