### ISSUE TITLE
provide support for source = "."

### ISSUE THREAD

**Issue by nalmeida84** [mapstruct/mapstruct#3333]
### Use case

Need to map several fields from DTO to compose object.
IngenicoPaymentResponse has an internal IngenicoPaymentResponseItem that needs to be matched with the provided DTO.

```
  @Mapping(target` = "ingenicoPaymentResponseItem", source = ".")
  @Mapping(target` = "ingenicoPaymentResponseItem.comPlus", source = "comPlus", qualifiedByName = "comPlusListToString")
  IngenicoPaymentResponse asIngenicoPaymentResponse(IngenicoPaymentDTO src);
```

It was not working as expected, only "comPlus" field was matched.
MapStruct currently has support to target="." but not for source="."

### MapStruct Version

1.5.5-Final

**Comment by filiphr** [comment]
@nalmeida84 you can already do this by referencing the parameter name in `source`

e.g.

```java
  @Mapping(target` = "ingenicoPaymentResponseItem", source = "src")
  @Mapping(target` = "ingenicoPaymentResponseItem.comPlus", source = "comPlus", qualifiedByName = "comPlusListToString")
  IngenicoPaymentResponse asIngenicoPaymentResponse(IngenicoPaymentDTO src);
```
