### ISSUE TITLE
Constructor binding for immutable target class with annotated constructor doesn't work

### ISSUE THREAD

**Issue by Choi-Sung-Hoon** [mapstruct/mapstruct#3350]
### Expected behavior

Proper mapping logic exists in mapper implementation.

### Actual behavior

Same Issue as https://github.com/mapstruct/mapstruct/issues/2584

#### Environment
* JDK 8
* Gradle 6.9.1
* 1.4.2.Final, 1.5.5.Final

mapper implementation has missing property mapping when `injectionStrategy = InjectionStrategy.CONSTRUCTOR` and constructor of target class is annotated with `@JsonCreator`.

the problematic target class is like below

```java
@Getter // lombok annotation
public class Response {
    private final String name;

    @JsonCreator
    public Response(@JsonProperty("name") String name) {
        this.name = name
    }
}
```

The target class is immutable and has no setter.

When implemented mapper code is generated, the `name` property is not set. (which means it's `null`)

It works well if I put `@Setter` annotation on the class or `@ConstructorProperties` on the constructor.

### Steps to reproduce the problem

1. create immutable target class
2. use constructor binding with the all-args constructor annotated with `@JsonCreator`

### MapStruct Version

1.4.2, 1.5.5

**Comment by Choi-Sung-Hoon** [comment]
I think I found the cause.

This happens when the constructor of target class is annotated with `@JsonCreator`.

When I use `@ConstructorProperties` on the constructor in the target class, it's resolved.

**Comment by filiphr** [comment]
@Choi-Sung-Hoon if this is the same as #2584, why are you creating a new issue? Have a look at https://github.com/mapstruct/mapstruct/issues/2584#issuecomment-1676260419 to see why it isn't working. For Gradle it is the same problem, when using Java 8, you have to make sure that you are passing the `--parameters` flag to the java compiler. This is explained in [here](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing) in the Gradle docs
