### ISSUE TITLE
Is ’build‘ a keyword?An entity containing a build field must report an error.Delete everything OK

### ISSUE THREAD

**Issue by zxuanhong** [mapstruct/mapstruct#3358]
### Expected behavior
```
 private String build;
```
An entity that contains a build field wants the entity to be converted normally

### Actual behavior

<img width="1342" alt="image" src="https://github.com/mapstruct/mapstruct/assets/62740686/5f99c2c3-fe13-49e5-acbe-d794efb7c790">

### Steps to reproduce the problem

1. An entity containing a build field must report an error.Delete everything OK
<img width="553" alt="image" src="https://github.com/mapstruct/mapstruct/assets/62740686/b23ed2a4-5aa2-4ba0-92dd-2cb3e93af027">
<img width="1377" alt="image" src="https://github.com/mapstruct/mapstruct/assets/62740686/5e21938e-3023-42f1-bf64-78d637324b24">

### MapStruct Version

1.5.5

**Comment by Zegveld** [comment]
The things highlighted in your images are related to Lombok not MapStruct.
Looks the same as this issue: https://github.com/projectlombok/lombok/issues/3230
