### ISSUE TITLE
MapStruct fails to use Lombok builder for custom methods

### ISSUE THREAD

**Issue by heipl-paul** [mapstruct/mapstruct#3363]
### Expected behavior

I expect MapStruct to not care at all that I defined the following method:

```java
@Getter
@Introspected
@Builder(builderMethodName = "") // I tried without builderMethodName = "", same issue.
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PROTECTED)
public class InsuranceApplication {

    // ...

    public static InsuranceApplicationBuilder builder() {
        return new InsuranceApplicationBuilderImpl();
    }

    private static class InsuranceApplicationBuilderImpl extends InsuranceApplicationBuilder {
        public InsuranceApplication build() {
            var application = super.build();
            CommonValidator.validate(application);
            return application;
        }
    }
}
```

In my mind, this is the exact same contract that Lombok declares: 

- I have a builder method.
- It returns a type named [MyClassName]Builder. It should not matter that the real type is actually [...]Impl.
- The builder has the default `build()` method as far as the contract is concerned.

The fact that mapstruct refuses to use the builder is ... odd. I don't feel like I'm doing something wrong. I don't feel like I should write a new Builder SPI for the same exact contract that would be there had I done nothing custom. 

My only recourse as thing stand is to build objects in a factory, use default builder, and move validation in factory. This is not unsurmountable. But again. I changed nothing in the contract. Why would this not work?

### Actual behavior

Generated code with error message:  
  

```
InsuranceApplication insuranceApplication = new InsuranceApplication();
                                                ^
required: no arguments
found:    no arguments
reason: InsuranceApplication() has protected access in InsuranceApplication
```

If I remove the custom build method. Even though it is the same exact contract, then it uses the builder instead and no longer tries to access the `
@NoArgsConstructor(access = AccessLevel.PROTECTED)`

### Steps to reproduce the problem

```java
@MapperConfig(
        componentModel = ComponentModel.JSR330,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR,
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        nullValueIterableMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT,
        collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED,
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG
)
public interface DefaultMappingConfig {
}

@Getter
@Introspected
@Builder(builderMethodName = "")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PROTECTED)
public class InsuranceApplication {

    UUID id;

    public static InsuranceApplicationBuilder builder() {
        return new InsuranceApplicationBuilderImpl();
    }

    private static class InsuranceApplicationBuilderImpl extends InsuranceApplicationBuilder {
        public InsuranceApplication build() {
            var application = super.build();
            CommonValidator.validate(application);
            return application;
        }
    }
}

@Data
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@MappedEntity("insurance_application")
public class InsuranceApplicationEntity {

    String id;

}

@Mapper(config = DefaultMappingConfig.class)
public interface UuuIdMapper {
    default UUID toUuuId(String id) {
        return Optional.ofNullable(id).map(UUID::fromString).orElse(null);
    }
}

@Mapper(
        config = DefaultMappingConfig.class,
        uses = {
                UuuIdMapper.class
        }
)
public interface InsuranceEntityMapper {
    InsuranceApplication toDomain(InsuranceApplicationEntity entity);
}
```

Gradle:

```
ext {
    // ...
    jakartaAnnotationApiVersion = '1.3.5'
    jakartaInjectApiVersion = '2.0.1'
    javaxAnnotationVersion = '1.3.2'
    commonsLang3Version = '3.12.0'
    lombokVersion = '1.18.22'
    jacksonVersion = '2.13.2'
    mapstructVersion = '1.5.2.Final'
    reactorCoreVersion = '3.4.18'
    snakeYamlVersion = '2.0'
    javafakerVersion = '1.0.2'
    jakartaPersistenceApiVersion = '3.1.0'
    reactiveGrpcVersion = '0.0.7'
    wireMockVersion = '2.27.2'
    googleCloudVersion = '26.15.0'
}

// lombok
annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
compileOnly "org.projectlombok:lombok:${lombokVersion}"
testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

// mapstruct
annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
implementation "org.mapstruct:mapstruct:${mapstructVersion}"

// micronaut
annotationProcessor("io.micronaut.data:micronaut-data-processor")
annotationProcessor("io.micronaut:micronaut-http-validation")
implementation("io.micronaut.reactor:micronaut-reactor")
implementation("io.micronaut:micronaut-jackson-databind")
implementation("io.micronaut:micronaut-runtime")
implementation("jakarta.annotation:jakarta.annotation-api")
implementation("io.micronaut:micronaut-validation")
runtimeOnly("ch.qos.logback:logback-classic")
implementation("io.micronaut.reactor:micronaut-reactor-http-client")
implementation('io.micronaut:micronaut-validation')
implementation("io.micronaut.security:micronaut-security-jwt")
```

### MapStruct Version

1.5.2.Final

**Comment by JavaPantry** [comment]
Similar Issue - Incorrect Mapping Behavior with Lombok Builder and CycleAvoidingMappingContext

**Description:** I'm encountering an issue related to incorrect mapping behavior when using MapStruct in conjunction with Lombok's builder pattern and the `CycleAvoidingMappingContext`. This issue leads to unintended instances being created during the mapping process, resulting in incorrect relationships between entities.

**Hint** - If Entities and Dto have circular references mapper implementation inserts references to builder into CycleAvoidingMappingContext instead of reference to entity or dto. 

This issue caused an exception when attempting to save an entity to the database using Hibernate-based Spring JPA. The exception message is as follows:

javaCopy code

`org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.springcloud.sbsuite.orders.domain.OrderLine.orderHeader -> com.springcloud.sbsuite.orders.domain.OrderHeader`

**Comment by thunderhook** [comment]
@JavaPantry Is it possible that you posted under the wrong ticket? Your problem seems to be related to 3060 or 2721 which has a possible workaround in the comment https://github.com/mapstruct/mapstruct/issues/2721#issuecomment-1299990934

**Comment by thunderhook** [comment]
@heipl-paul I was able to reproduce your problem. This is due to a breaking change in lombok 1.18.16 which needs an additional annotation processor. See: https://mapstruct.org/documentation/stable/reference/html/#lombok

I never did this in gradle, but it seems like this is the needed part: https://stackoverflow.com/a/72334665
Let me know if it works for you.

**Comment by heipl-paul** [comment]
@thunderhook Yep, that fixes everything. Wasn't aware of the change. Thanks for the help ;)
