### ISSUE TITLE
primitive mapping parameters cause code generation that doesn't compile

### ISSUE THREAD

**Issue by NikolayMetchev** [mapstruct/mapstruct#3375]
### Expected behavior

Generate a valid mapper implementation

### Actual behavior

Generates code that doesn't compile

### Steps to reproduce the problem

If you try and generate a Mapper from the kotlin code below you will generate java code that doesn't compile. It will have the following in its implementation:

```
        if (  ) {
            return;
        }
```
There is a workaround if you uncomment `nullValueMappingStrategy` line.

```
package com.mapstructbug

import org.mapstruct.Mapper
import org.mapstruct.MappingTarget

@Mapper(
// uncomment the line below to work around this bug.
//    nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT,
)
abstract class MapstructBug {

    abstract fun mapToTarget(
        a: Long,
        b: Int,
        @MappingTarget target: Target,
    )
}

data class Target(
    var a: Long,
    var b: Int,
)
```

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
This is the same as #3317 and has been fixed on main. It will be part of 1.6
