### ISSUE TITLE
Support Iterable interface as an input

### ISSUE THREAD

**Issue by SergeS** [mapstruct/mapstruct#3376]
### Use case

We are using records with collections defined as `Iterable<T>` , and it would be handy to somehow make mapstruct able to convert from `Iterable<T>` to any other Iterable type. For example.

```java
record B (
  String value;
) {}

record A (
  Iterable<B> listOfB
) {}

class C {
  List<String> listOfB
}

@Mapper
interface Mapper {
  C mapAtoC(A input);

  default String mapBToSting(B in) {
    return in.value();
  }
}

```

### Generated Code

```java

interface MapperImpl {
  public C mapAtoC(A input) {
    ....

    C c = new C();
    
    List<String> listOfB = StreamSupport.stream(labels.spliterator(), false).map(this::mapBToSting).toList();
    c.setListOfB(listOfB);

    ....
  }
}


```

### Possible workarounds

Currently I need to create such functions manually

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
This is a valid request. We might need to change the `map` part a bit, but apart from that I don't see why not add such a functionality. I'll leave this is a future enhancement so we can decide how to add it after 1.6. However, if you are interested in contributing, we are more than happy to look at a PR.

**Comment by kooixh** [comment]
I've taken a stab at this, really appreciate if anyone can review my PR
