### ISSUE TITLE
Generated code does not compile for nested none static classes instatiation

### ISSUE THREAD

**Issue by DominikSarnowskiSapiens** [mapstruct/mapstruct#3393]
### Expected behavior

For simple structure like this:
`public class Outer {
    public class Inner {
     } 
}`

Instantiation of object of the Inner class should look like below:
new Outer().new Inner()

### Actual behavior

In 1.5.5.Final it generates the below code which is not compiling:

`new Outer.Inner()`

which leads to java error:

**java: an enclosing instance that contains Outer.Inner is required.**

### Steps to reproduce the problem

@Mapper(componentModel = "spring")
public interface OuterMapper {
    Outer.Inner map(Source source);
}

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
@DominikSarnowskiSapiens and why don't you make the `Inner` class `static`? I am not sure that `Outer.Inner` should even be exposed like that

**Comment by DominikSarnowskiSapiens** [comment]
@filiphr ...because it is in the library I use and do not have much control over how it was implemented, but I need to map objects like this and I would be happy to use MapStruct for it :)

**Comment by thunderhook** [comment]
@DominikSarnowskiSapiens Never seen this notation before. I don't know why this library decided to use "non-static nested classes" (inner classes) (see [Java Tutorials](https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html)). They may have a good reason (although I doubt it 😅).

At first glance, this is not a simple fix and might need a proper rework of how MapStruct handles instantiation.

As a workaround, you can provide an object factory for classes like this. I hope this is no show-stopper for you:

```java
@Mapper(uses = OuterInnerFactory.class)
interface Issue3393Mapper {

    @Mapping(target = "name", source = "name")
    Outer.Inner map(Source source);

}

class OuterInnerFactory {

    public Outer.Inner createOuterInner() {
        return new Outer().new Inner();
    }

}

class Source {

    public String name;

}

class Outer {

    class Inner {

        public String name;

    }
}
```

**Comment by DominikSarnowskiSapiens** [comment]
Hello @thunderhook thank you for the suggestion. I hope they have a good reason for this :D
Definitelly it is not stopper for me as I already use the suggested @ObjectFactory.
The only thing in this solution is that the more inner classes I will get in the lib the more factories I need to create what causes neverending circle of changes.

I understand the change is not required much so I need to live with it :)
