### ISSUE TITLE
Why only the parameters of the parent class are mapped?

### ISSUE THREAD

**Issue by Code-WangShuai** [mapstruct/mapstruct#3394]
### Use case

The result is only the parameters of the parent class
```
public class BaseEntityDO implements Serializable {
    private Long id;
    private Long tenantId;
    private Long version;
    private Long createdBy;
    private Long createdTime;
    private Long updatedBy;
    private Long updatedTime;
    private Boolean deletedFlag;
    private Long deletedBy;
    private Long deletedTime;
}

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class RoleDO extends BaseEntityDO {
    private String groupKey;
    private String name;
    private String intro;
    private Boolean status;

}

@Data
public class BaseModel {
    private Long id;
    private Long tenantId;
    private Long version;
    private Long createdBy;
    private Long createdTime;
    private Long updatedBy;
    private Long updatedTime;
    private Boolean deletedFlag;
    private Long deletedBy;
    private Long deletedTime;
}



@Data
@AllArgsConstructor
@NoArgsConstructor
public class RoleModel extends BaseModel {
    private String groupKey;
    private String name;
    private String intro;
    private Boolean status;
}
```

### Generated Code
```
@Mapper(componentModel = SPRING, unmappedSourcePolicy = ReportingPolicy.IGNORE)
public interface RoleDomainConverter <RoleModel, RoleDO> {

     RoleDO toDo(RoleModel model) ;
}
```
What do I do if I want the values in "roleModel" and "RoleDO"?

### MapStruct Version

1.5.5

**Comment by thunderhook** [comment]
I am not exactly sure what you're trying to achieve.

> The result is only the parameters of the parent class

Well no, the mapper generated the mappings for id, groupKey, name, intro and status as well:

```java
//...
roleModel.setId( roleDO.getId() );
roleModel.setGroupKey( roleDO.getGroupKey() );
roleModel.setName( roleDO.getName() );
roleModel.setIntro( roleDO.getIntro() );
roleModel.setStatus( roleDO.getStatus() );

```

> What do I do if I want the values in "roleModel" and "RoleDO"?

What do you mean by that? RoleModel is the mapping target and RoleDO is the source.

Maybe it will be more clear when you also post the code that you want MapStruct generate.
Please also post the code instead of screenshots. It makes it easier to quote them and to copy them to create a reproducal.
Thanks.

**Comment by Code-WangShuai** [comment]
I released the code,The problem is When I call "toModel", none of these are actually generated
```
roleModel.setGroupKey( roleDO.getGroupKey() );
roleModel.setName( roleDO.getName() );
roleModel.setIntro( roleDO.getIntro() );
roleModel.setStatus( roleDO.getStatus() );
```
![image](https://github.com/mapstruct/mapstruct/assets/49975230/82be54ac-067c-4f54-8a71-948987ebd1df)

这是他生成的代码
![image](https://github.com/mapstruct/mapstruct/assets/49975230/a5c9fa9d-39bc-4ff5-ac53-6136921b989f)

**Comment by thunderhook** [comment]
I see, the original screenshot you posted was the code you expected from MapStruct. And not what what it actually generated. I will have a look in the evening. Thanks!

**Comment by filiphr** [comment]
@Code-WangShuai are you using the `lombok-mapstruct-binding` dependency?

**Comment by Code-WangShuai** [comment]
> @Code-WangShuai are you using the `lombok-mapstruct-binding` dependency?

No, I didn't use it

**Comment by thunderhook** [comment]
> > @Code-WangShuai are you using the `lombok-mapstruct-binding` dependency?
> 
> No, I didn't use it

Could you fix it by adding the dependency?

**Comment by Code-WangShuai** [comment]
It's amazing. I added it and it was fine. Thank you so much!

**Comment by thunderhook** [comment]
Perfect, glad to hear!
