### ISSUE TITLE
Error building abstract class if ObjectFactory return a builder

### ISSUE THREAD

**Issue by rmanibus** [mapstruct/mapstruct#3395]
### Expected behavior

This is working well if:
- `Resource` class is concrete 
- `Resource` class is abstract and the ObjectFactory return a `Resource` instance.

However if the ObjectFactory return a builder and Resource is abstract, this is failing

```
@SuperBuilder()
public abstract class Resource implements Owned {

}

@Mapper()
public interface ResourceMapper {

    Resource toModel(ResourceEntity entity);

    @ObjectFactory
    default ResourceBuilder<?, ?> resourceFactory(ResourceEntity entity) {
        return CDI.current()
                .select(ResourceFactory.class, new ForType.ForTypeQualifier(entity.getType()))
                .get()
                .newInstance();
    }
}    
```

### Actual behavior

```
error: The return type Resource is an abstract class or interface. Provide a non abstract / non interface result type or a factory method.
    Resource toModel(ResourceEntity entity, @Context MappingContext mappingContext);
```

### Steps to reproduce the problem

mapstruct on gradle and java 20

### MapStruct Version

Mapstruct 1.5.2

**Comment by filiphr** [comment]
@rmanibus this works as designed. If there is no way for MapStruct to determine that `ResourceBuilder` is a builder for `Resource` then we won't be using the `@ObjectFactory`. The rules for determining a builder are in the [Using builders](https://mapstruct.org/documentation/stable/reference/html/#mapping-with-builders) section of our documentation.

If you have different rules you'll need to provide your own `BuilderProvider`
