### ISSUE TITLE
MapStruct-Examples Java 17 Incompatibility.   NoClassDefFoundError & Could not initialize class.

### ISSUE THREAD

**Issue by 8bllgrl** [mapstruct/mapstruct#3396]
### Expected Behavior:

I expected the tests to pass on java 17. If you could point me to a location in documentation or other official information that states explicitly where the acceptable versions of MapStruct are let me know. It could be an oversight on my part.
### Problem Description:

The GitHub project example from https://github.com/mapstruct/mapstruct-examples is not functioning as expected in Java 17, *although,* it works properly in Java 11.

My main concern is about compatibility or deprecated features in MapStruct that might not allow it to work in the version needed for my project.

### Actual Behavior:

Tests failed when running the project in java 17.0.1.

### Additional Info:

- My project requires java 17.0.7 for the entire project.
- Question❔: Does MapStruct involve any features in relation to Reflection that would have been deprecated in Java 17? If you could answer this that would be wonderful.

### Environment Details:

- **IntelliJ IDEA Version:** 2023.1.1 (Community Edition)
- **Operating System:** Windows 11 (Issue also reproduced on Windows 10)
- **JAVA_HOME Path:** `C:\\Program Files\\Amazon Corretto\\jdk17.0.7_7`
- **Mapstruct Version:** 1.5.5.Final

### Steps to Reproduce the Problem:

1. Clone the example projects from GitHub:
    - Repository: https://github.com/mapstruct/mapstruct-examples
    - Subproject: https://github.com/mapstruct/mapstruct-examples/tree/main/mapstruct-on-gradle
2. Open the subproject in IntelliJ.
3. Navigate to `File → Project Structure → Project → SDK` and switch to `Eclipse Temurin version 11.0.19`.
    - Apply the changes.
4. Build the Gradle project.
5. Run `ConversionTest.java`.
6. ✅ Tests pass successfully (JDK 11).
7. Switch JDK version to `java version 17.0.7` in IntelliJ.
    - Apply the changes.
8. Run the tests again.
9. ⛔ Tests fail with the following error messages:
    
    ```java
    Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache [in thread "Daemon worker"]
    
    Could not create an instance of type ijmapper_6nopapf8sgnh49endlsi3z36c.
    > Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
    
    ```
    

### MapStruct Version:

MapStruct 1.5.5.Final

**Comment by filiphr** [comment]
@8bllgrl those examples are not a reference for whether MapStruct runs on Java 17 or not.

You can see the CI on main (https://github.com/mapstruct/mapstruct/actions/workflows/main.yml?query=branch%3Amain) and you'll see that everything runs on Java 17 without any issues.

The error you are seeing in the example is due to the fact that the Gradle version in that example does not support Java 17. However, if you are using a Gradle version that supports Java 17 there won't be any issues.

Cheers,
Filip

**Comment by 8bllgrl** [comment]
@filiphr 
Ah. Good to know it works for Java 17, and it's helpful to know that the error was due to the Gradle version. I will change the gradle version. I will open up new issues if anything else arises.

Thanks, Filip!

**Comment by 8bllgrl** [comment]
@filiphr 
Successfully changed the gradle version and it fixed this issue. 
Thank you 🙂

**Comment by filiphr** [comment]
That's good to hear @8bllgrl. Your issue also lead us to go through our examples and upgrade our test pipelines to run with the relevant Java versions. The gradle example now runs with Java 17 out-of-the-box. See https://github.com/mapstruct/mapstruct-examples/pull/146 for more info
