### ISSUE TITLE
Slow mapping of large sets

### ISSUE THREAD

**Issue by reisi007** [mapstruct/mapstruct#3399]
### Expected behavior

 Set<|Single|> set1 = new LinkedHashSet<|Single|>( Math.max( (int) ( set.size() / .75f ) + 1, 16 ) );

### Actual behavior

 Set<|Single|> set1 = new LinkedHashSet<|Single|>();

### Steps to reproduce the problem

```
  <compilerArgs>
   <arg>
       -Amapstruct.suppressGeneratorTimestamp=true
   </arg>
   <arg>
     -Amapstruct.suppressGeneratorVersionInfoComment=true
  </arg>
  <arg>
   -Amapstruct.verbose=true
 </arg>
 <arg>
 -Amapstruct.unmappedTargetPolicy=ERROR
 </arg>
 <arg>
  -Amapstruct.defaultComponentModel=spring
  </arg>
</compilerArgs>
```

It seems to us that having no constructor parameter is much faster for larger sets coming from Hibernate Hibernate

Also help me: If I have a Set of size 100, the generated set is of size 76.... If I have a 1:1 mapping it is too small, so it might be best sticking to the default algorithm....

I feel like mapstruct does not allow for customizing the generated code templates, or did I miss something?

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
@reisi007 have you done some measurements?

>Also help me: If I have a Set of size 100, the generated set is of size 76.... If I have a 1:1 mapping it is too small, so it might be best sticking to the default algorithm....

The calculation that we are doing is `Math.max( (int) ( set.size() / .75f ) + 1, 16 )` so if you have a set of size it will be `Math.max( (int) ( 100 / .75f ) + 1, 16 )` which is `Math.max(134, 16)` so the set size will be 134 elements. This computation is similar to what Java is doing with the new factory methods for `HashMap` and `HashSet`. From Java 21 there is:

* `LinkedHashSet#newLinkedHashSet`
* `LinkedHashMap#newLinkedHashMap`

and they are using `(int) Math.ceil(numMappings / 0.75d)`

**Comment by reisi007** [comment]
Goddamit, my collegues didn't spot my mistake. I admit to not knowing math and that / 0,75 is not *,75

I have done some mesurements, sadly no benchmarks with jProfiler.... Difference was 4 secs to 2 secs for the convertion method of the set. That was quite reproduceable +-500ms.

I was doing these test under Java 17. As the performance of size was affecting the calculation very harshly (Hibernate PersistentSet - was using a local DB).

I do understand that this is a edge case - if there is a way to add a generation template to test stuff like this out I would very much like to do so.....

However, extracting this complex mapping is not possible for me so I could not do a micro benchmark.

If you think this is only a problem with out code - pls feel free to close this issue

**Comment by reisi007** [comment]
Thank you for the hint. Will close this issue as it seems to be out problem and i got a workaround.

I did not know about ObjectFactory! Thank you so much!
