### ISSUE TITLE
Difference between kotlin and java mapper

### ISSUE THREAD

**Issue by zivkovic** [mapstruct/mapstruct#3407]
### Expected behavior
Expected behaviour is for kotlin code to generate the mapper successfully.

### Actual behavior

In kotlin, error occurs:
```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.10:kapt (kapt) on project a: Compilation failure: Compilation failure: 
[ERROR] C:\git\...\Mapper.java:7: error: Can't generate mapping method with primitive return type.
[ERROR]     public abstract long testMe(@org.jetbrains.annotations.NotNull
```

In java, everything works.

### Steps to reproduce the problem

The issue here is that in java, the mapper is generated successfully, but in kotlin it fails with error 'Can't generate mapping method with primitive return type.'. Why does this fail at all? If its valid in java, surely it should be valid in kotlin as well. Am I doing something wrong here? I'm confused.

Kotlin code:
```
fun testMe(a: String): Long {
    return 1L
}
```

Java code:
```
default long testMe(String a) {
    return 1L;
}
```

To reproduce the problem, copy the above kotlin code, use it in a project and try to compile it.

Mapper configuration:
```
@MapperConfig(
    componentModel = "cdi",
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    unmappedTargetPolicy = ReportingPolicy.ERROR
)
```

I encountered this problem in a project using Quarkus 3.4.2, using kotlin 1.9.10 and mapStruct 1.5.5.Final. Any info would be welcome.

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
This is a big in Kotlin. See #1577. Kotlin does not generate a default method for

```kotlin
fun testMe(a: String): Long {
    return 1L
}
```

Therefore to achieve the same as in Java you'll need to do

```kotlin
@JvmDefault
fun testMe(a: String): Long {
    return 1L
}
```
