### ISSUE TITLE
The option mapstruct.defaultComponentModel is not being recognized

### ISSUE THREAD

**Issue by NadChel** [mapstruct/mapstruct#3409]
### Expected behavior

I don't expect to get this warning when specifying `-Amapstruct.defaultComponentModel=spring`
```
java: The following options were not recognized by any processor: '[mapstruct.defaultComponentModel]'
```

### Actual behavior

I have this configuration in my `pom.xml` file:
```xml
    <properties>
        <java.version>11</java.version>
        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
<!-- more pom code -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <dependency>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </dependency>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>2.6.6</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>
                            -Amapstruct.defaultComponentModel=spring
                        </arg>
                    </compilerArgs>
                </configuration>
            </plugin>
```
I believe my configuration follows the [Mapstruct documentation][1]

Is there something I omitted?

[This issue][2] doesn't appear to be helpful

  [1]: https://mapstruct.org/documentation/stable/reference/html/
  [2]: https://github.com/mapstruct/mapstruct/issues/1256

### Steps to reproduce the problem

1. Create a Maven project
2. Mimic my pom.xml
3. Build the project

### MapStruct Version

1.4.2.Final

**Comment by foaw** [comment]
The annotation processor is just that, and the library itself with the actual annotations still has to be on the classpath. Are you adding MapStruct in the dependencies section?

```xml
<dependencies>
    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
    </dependency>
    <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct</artifactId>
        <version>${org.mapstruct.version}</version>
    </dependency>
</dependencies>
```

Note that `lombok-mapstruct-binding` is just a processor. [All it does](https://github.com/projectlombok/lombok/blob/master/src/bindings/mapstruct/lombok/mapstruct/NotifierHider.java) is notify MapStruct of changes to the AST when it modifies it. Without this processor, your code may occasionally run into compilation errors.

---

By the way, you can also reuse the `java.version` property in the configuration of the compiler plugin.

**Comment by filiphr** [comment]
@NadChel can you please share more of the output from Maven or share an example project that we can look into? As @foaw mentioned the warning does not come from MapStruct, it comes from Java itself when none of the processors on the annotation procesor path consume the defined properties. There can be various reasons why the MapStruct processor won't be invoked.

**Comment by YaraslauBarysenka** [comment]
I faces the same issue as well. Please take a look.

**Comment by thunderhook** [comment]
@YaraslauBarysenka could you please provide more output from maven or share an example project? As it is now, we have a hard time looking at it without a reproducer.

**Comment by aldise** [comment]
I noticed that I get that warning when there are no `@Mapper` annotated classes in the project.

For example, IntelliJ IDEA re-compiles the classes selectively by need and time to time I get that warning there, but never when I'm using maven via command line (like `mvn clean compile`).

Example project - https://github.com/aldise/mapstruct-example

**Comment by filiphr** [comment]
>I noticed that I get that warning when there are no `@Mapper` annotated classes in the project.

If there are no `@Mapper` classes (i.e. no MapStruct is used), why is then the `mapstruct-processor` as a dependency.

Regarding the IntelliJ usage. I would try using the recommended approach from MapStruct with the use of of [`annotationProcessorPaths`](https://mapstruct.org/documentation/1.5/reference/html/#_apache_maven) instead of providing it as a regular dependency.

I'm going to close this issue as this is a regular output from the java compiler itself and there is nothing that we can do about it.

**Comment by thunderhook** [comment]
Hi @zappee !

Would you please be so kind to provide a GitHub project that we can check out to reproduce the issue?

Thanks!

**Comment by thunderhook** [comment]
Thanks for the reproducer!

This is the way how maven works with so-called [core plugins](https://maven.apache.org/ref/3.6.3/maven-core/plugins.html) like the `maven-compiler-plugin`. If you define something in the `<pluginManagement>` block in your parent, it will be used in every submodule. If this were a third-party plugin, you would have to explicitly define it in the submodules pom.xml (as you did in `remal-gombi-kafka-consumer`), but the maven-compiler-plugin will do this even if you do not define it explicitly.

So in your case you could:
* ignore the warning
* move the compilerArg to the submodule that needs it
* work with maven profiles

**Comment by zappee** [comment]
Thanks for correcting me. 
I switched to using the suggested 2nd solution (`move the compilerArg to the submodule that needs it`) and the WARN message disappeared.
