### ISSUE TITLE
Means of disabling signature comparison with @InheritConfiguration

### ISSUE THREAD

**Issue by foaw** [mapstruct/mapstruct#3412]
### Use case

There can be innumerable reasons **not** to compare signatures when filtering out for candidates. Consider the cases:

- Where the user has no control over the definition(s) of the result or input type(s),
- Where types are passed, where it makes no sense to introduce a type hierarchy, and
- There is additional information that is required by the downstream or inheriting method, so the number of parameters will have to differ. Often I'd work around this by instead forming a single "context" type out of all parameters, which brings us back to the previous point.

Although these are only what I could recall off the top of my head, even they already cover a good portion of the usages. This is why I think a means of disabling signature comparison should be introduced.

### Possible workarounds

My current approach to the problem is as follows:

- The parent, or inherited method is extracted into its own mapper, which is marked as `@MapperConfig`.
- The parameter type is changed to `j.l.Object`, as is result's; if there are multiple parameters, we then pack them into a single type, which will be the single parameter.
- Specify the newly-minted `@MapperConfig` in the child, or inheriting method's `@Mapper#config`.

What I propose is that `@InheritConfiguration` has a new method, say, `ignoreSignature`. If set to `true`, `canInheritFrom`'s last two checks should not be evaluated and have no effect on dropping a method from the candidates. Although rough, this is a very powerful tool.

https://github.com/mapstruct/mapstruct/blob/a8df94cc2049099dce5f42ead520965da563e9b0/processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java#L680-L686
https://github.com/mapstruct/mapstruct/blob/8fa286fe4ce790cc2a65adff55c813bc9717437a/processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java#L360-L368

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
> Often I'd work around this by instead forming a single "context" type out of all parameters, which brings us back to the previous point.

Have you looked into [Mapping Composition](https://mapstruct.org/documentation/stable/reference/html/#mapping-composition)? I think this is more the right direction for you.

I don't see how adding `ignoreSignature` would help here, it kinda feels the same like the mapping composition

**Comment by foaw** [comment]
And it probably is the same. The ultimate proposal was to have annotation carriers for inheritance that would never be compiled, and mapping composition gives just that.
