### ISSUE TITLE
Using `Mapping#expression` and `Mapping#conditionaQualifiedBy(Name)` should lead to compile error

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#3413]
### Expected behavior

Using a combination for `Mapping#expression` and `Mapping#conditionQualifiedBy(Name)` should lead to compile error

### Actual behavior

There is no compile error and the `Mapping#conditionQualifiedBy(Name)` is simple ignored

### Steps to reproduce the problem

```
@Mapper
public interface MyMapper {
    @Mapping(target = "value", expression = "java(source.getValue())", conditionQualifiedByName = "condition")
    Target map(Source source);
}
```

This is related to #3405

### MapStruct Version

1.5.5

**Comment by the-mgi** [comment]
hello, i'd like to take on this issue

**potential fix**: mapstruct/processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions#isConsistent need another if branch, for this, and a new error message defined in Message.java, and a test would be required.

**Comment by thunderhook** [comment]
Hello @the-mgi,

sounds good. I have assigned you the issue.

Have fun! :)
