### ISSUE TITLE
NPE after accessing record field with generic interface in eclipse environment

### ISSUE THREAD

**Issue by cart-before-horse** [mapstruct/mapstruct#3418]
### Expected behavior

annotation processor process annotations without crashes

Its most likely eclipse jdt issue, but in case someone stumble on this like me
i submitted an issue there https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1497
i wonder if its worth trying to work around this quirk

### Actual behavior

Exception

<details>
<summary>stacktrace</summary>

> Internal error in the mapping processor: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.Element.getKind()" because "element" is null  
>  at org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:91)     
>  at org.mapstruct.ap.internal.util.AbstractTypeUtilsDecorator.asMemberOf(AbstractTypeUtilsDecorator.java:129)   
>  at org.mapstruct.ap.internal.util.Filters.getWithinContext(Filters.java:142)   
>  at org.mapstruct.ap.internal.util.Filters.getReturnType(Filters.java:114)  
>  at org.mapstruct.ap.internal.util.Filters.recordAccessorsIn(Filters.java:102)  
>  at org.mapstruct.ap.internal.model.common.Type.getPropertyReadAccessors(Type.java:674)     
>  at org.mapstruct.ap.internal.model.common.Type.getAlternativeTargetAccessors(Type.java:1006)   
>  at org.mapstruct.ap.internal.model.common.Type.getPropertyWriteAccessors(Type.java:756)    
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:226)     
>  at org.mapstruct.ap.internal.model.AbstractBaseBuilder.createForgedAssignment(AbstractBaseBuilder.java:98)     
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapping(PropertyMapping.java:824)   
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapping(PropertyMapping.java:788)   
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forge(PropertyMapping.java:319)  
>  at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:326)     
>  at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:169)  
>  at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:145)  
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:256)  
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1418)    
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1382)    
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:294)     
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:418)     
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:181)     
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:135)   
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:82)    
>  at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)    
>  at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)   
>  at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)  
>  at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)    
>  at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)    
>  at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)  
>  at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)   
>  at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)   
>  at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953)    
>  at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)   
>  at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)   
>  at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:406)   
>  at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:371)     
>  at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:338)   
>  at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:190)    
>  at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:147)   
>  at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:290)     
>  at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:213)   
>  at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)     
>  at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)     
>  at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)  
>  at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)     
>  at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)  
>  at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)    
>  at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)    
>  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) 

<details>

### Steps to reproduce the problem

example repo https://github.com/cart-before-horse/eclipse-jdt-issue-demo

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
@cart-before-horse I see that the Eclipse issue has been fixed already and that it will be part of the 4.30 M3 release. Considering that there is already a fix in Eclipse, I do not think that we need to do anything to workaround this bug.

**Comment by filiphr** [comment]
Btw, I forgot to say, thanks a lot for creating the Eclipse JDT issue and providing the fix there
