### ISSUE TITLE
Incorrect Mapping Method Being Generated

### ISSUE THREAD

**Issue by joelwilson005** [mapstruct/mapstruct#3434]
### Expected behavior

```
  todoList.setCompleted( todoListPartial.isCompleted() );
        if ( todoListPartial.isCompleted != null ) {
            todoList.isCompleted( todoListPartial.isCompleted());
        }
```

### Actual behavior

```
  todoList.setCompleted( todoListPartial.isCompleted() );
        if ( todoListPartial.getDueDate() != null ) {
            todoList.setCompleted(todoList
        }
```

MapStruct is trying to map two completely separate fields. 

### Steps to reproduce the problem

  <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.5.5.Final</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

### MapStruct Version

1.5.5.Final

**Comment by thunderhook** [comment]
@joelwilson005 Please add the code of the models you're mapping and the code of the mapper so that we can try to reproduce it.

**Comment by joelwilson005** [comment]
Here's the code for the models: 
`// TodoList.java

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TodoList {
    @Id
    @GeneratedValue
    private Long id;

    private String title;

    private String description;

    private Timestamp dueDate;

    private boolean completed;



    @CreationTimestamp
    @Column(updatable = false)
    private Timestamp createdAt;

    private Timestamp updatedAt;

    @ManyToOne
    private UserEntity userEntity;

    @OneToMany(cascade = CascadeType.REMOVE)
    private List<Action> actionList = new ArrayList<>();

}
`

`// UpdateTodoListDto.java
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UpdateTodoListDto extends CreateTodoListDto {

    @NotNull
    private Long id;

    private boolean completed;

    private Timestamp dueDate;
}
`

`
// CreateTodoList.java
@Data
@AllArgsConstructor
@NoArgsConstructor
public class CreateTodoListDto {

    @NotBlank
    private String title;

    private String description;

    private Timestamp dueDate;
}
`

Here's the mapping interface:

`
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface TodoListMapper {

    void mapCreateTodoListDtoToTodoList(CreateTodoListDto createTodoListDto, @MappingTarget TodoList todoList);

    void mapTodoListToTodoListResponseDto(TodoList todoList, @MappingTarget TodoListResponseDto todoListResponseDt);

    void mapUpdateTodoListDtoToTodoList(UpdateTodoListDto updateTodoListDto, @MappingTarget TodoList todoList);

    void mapTodoListPartialTodoList(TodoList todoListPartial, @MappingTarget TodoList todoList);
}

`

**Comment by joelwilson005** [comment]
My bad.  The generated code is actually correct.
