### ISSUE TITLE
Mapping a nullable field to a non-nullable field in kotlin leads to a nullpointerexception at runtime

### ISSUE THREAD

**Issue by mvanderblom** [mapstruct/mapstruct#3436]
### Expected behavior

I would expect mapstruct to log an error since there is no valid way to do the mapping in case of a null value.

### Actual behavior

Mapstruct throws a nullpointer at runtime

### Steps to reproduce the problem

```kotlin
data class Source(val id: Long, val name: String?)
data class Target(val id: Long, val name: String)

@Mapper
interface SourceToTargetMapper {
  fun map(source: Source): Target
}

val source = Source(id = 1, name = null)
mapper.map(source) // // java.lang.NullPointerException: Parameter specified as non-null is null: method dev.vanderblom.mapstruct.kotlinnullabillitydemo.Target.<init>, parameter name
````

https://github.com/mvanderblom/mapstruct-kotlin-nullabillity-demo

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
MapStruct does not have support for `NonNull` / `Nullable` annotations yet. Please have a look at #1243 to follow this.
