### ISSUE TITLE
Slow compilation speed

### ISSUE THREAD

**Issue by zhb-github** [mapstruct/mapstruct#3441]
### Use case

After adding mapStruct, the project compilation took more than 5 minutes, compared to 2 minutes before

### MapStruct Version

1.5.5final

**Comment by filiphr** [comment]
@zhb-github we need a bit more information that this. See #3435 for how to submit a performance problem. We need at least some kind of sampling done so we can look into it.

**Comment by filiphr** [comment]
Closing this due to lack of information. If more information is provided we can reopen it.
