### ISSUE TITLE
Mapstruct does not follow proper custom implementation with Kotlin

### ISSUE THREAD

**Issue by stepanenkomaks** [mapstruct/mapstruct#3447]
### Expected behavior

Here is mapper from my interface with my custom logic: 

```
fun mapFile(file: ResourceFileEntity): String {
        return file.resourceUrl
    }
```

### Actual behavior

Here is what I see in the generated implementation 

```
@Override
    public String mapFile(ResourceFileEntity file) {
        if ( file == null ) {
            return null;
        }

        String string = new String();

        return string;
    }

```
So it always returns just empty string instead of `file.resourceUrl `

### Steps to reproduce the problem

comments = "version: 1.5.5.Final, compiler: javac, environment: Java 17.0.2 (Eclipse Adoptium)"

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
This is a Kotlin issue not a MapStruct one. See #3407 and #1577. The Java byte code generated by Kotlin for

```kotlin
fun mapFile(file: ResourceFileEntity): String {
    return file.resourceUrl
}
```

does not contain the `default` modifier. Therefore, MapStruct thinks that is ia an abstract method and will try to implement it.

You should instead annotate your method with `@JvmDefault
```kotlin
@JvmDefault
fun mapFile(file: ResourceFileEntity): String {
    return file.resourceUrl
}
```
