### ISSUE TITLE
@MappingTarget without null check leading to NullPointerException

### ISSUE THREAD

**Issue by gabrikid** [mapstruct/mapstruct#3449]
### Expected behavior

In "[updating existing bean instances](https://mapstruct.org/documentation/dev/reference/html/#updating-bean-instances)", generated code should include a null check against the argument annotated with @MappingTarget to avoid NullPointerException.

### Actual behavior

Generated code only includes a null check against the first argument (source), leading to NullPointerException.

### Abstract method:

```java
    void mergeDtoToEntity(AuthorRequestDto authorRequestDto, @MappingTarget AuthorEntity authorEntity);
``` 

### Generated code:

```java
    @Override
    public void mergeDtoToEntity(AuthorRequestDto authorRequestDto, AuthorEntity authorEntity) {
        if ( authorRequestDto == null ) {
            return;
        }

        authorEntity.setName( authorRequestDto.name() );
        authorEntity.setEmail( authorRequestDto.email() );
    }
``` 

### Proposal:

```java
        if ( authorRequestDto == null || authorEntity == null ) {
            return;
        }
``` 

### MapStruct Version

1.6.0.Beta1

**Comment by filiphr** [comment]
This works as designed. Check the Javadoc of [`@MappingTarget`](https://mapstruct.org/documentation/stable/api/org/mapstruct/MappingTarget.html)

It says:

>**NOTE**: The parameter passed as a mapping target **must** not be null.

Therefore, I am closing this issue.
