### ISSUE TITLE
Nested mappings do not work correctly with Lombok Builder

### ISSUE THREAD

**Issue by jakub-jaskowiec** [mapstruct/mapstruct#3468]
### Expected behavior

The failing scenario is based on mapstruct-nested-bean-mappings from the mapstruct-examples repo and it has been demonstrated in the following PR: https://github.com/mapstruct/mapstruct-examples/pull/147
 
Failing scenario: Add a parameter to the mapper and use it in the nested mapping:
1. The "map" method receives an additional parameter which should be mapped as "approval"
```
     @Mapping(target = "quality.report.organisation.approval", source = "approvalParam")
    FishTankDto map(FishTank source, String approvalParam);
```
2. Add Lombok Builder annotation to FishTankDto and other nested subclasses

Expectation: The example compiles and generates the mappings

### Actual behavior

Compile error:
`java: No read accessor found for property "quality" in target type.`

Note:
The example works when no Lombok annotations are used

### Steps to reproduce the problem

Compile the following PR:
https://github.com/mapstruct/mapstruct-examples/pull/147

### MapStruct Version

1.6.0.Beta1, 1.5.5.Final

**Comment by thunderhook** [comment]
Hi @jakub-jaskowiec!

Thanks for the report. This is a known issue, therefore I'm closing this in favour of #2941 where this is ideally getting resolved.

For the explanation of the issue itself (and current workarounds) see the comments in the following issue:
* https://github.com/mapstruct/mapstruct/issues/3353#issuecomment-1698267950
