### ISSUE TITLE
Allow factories to return a dynamically created class

### ISSUE THREAD

**Issue by xenoterracide** [mapstruct/mapstruct#3472]
### Use case

So I've seen the documentation on using factories. I'm trying to use Byte Buddy to create a subclass.

```java
var clazz =
  new ByteBuddy()
    .subclass(entityClass)
    .defineField(
            MODIFICATIONS_FIELD, GroupModifications.class, Opcodes.ACC_PUBLIC)
    .method(ElementMatchers.isSetter())
    .intercept(MethodDelegation.to(GroupChangeTrackingProxy.class))
    .make()
    .load(GroupProxyFactory.class.getClassLoader())
    .getLoaded();
```

What I'd like to be able to do is return this class for a constructor that should otherwise match the constructors given on the real class.

Part of the problem here is that some of the fields on this class are final and need to be created with the constructor.

There are 2 constructors, one with 3 args, and one no arg. Unfortunately this is openapi generated code so I also don't really control that class either... Although I could strip that no arg constructor out of the subclass ;) .

### Generated Code

I'm doing something like this... I'm using spring utils and vavr to avoid checked exceptions, you probably don't want to generate with those instead using the raw reflection api. currently this isn't going to work as written. I'd want the generated code to rethrow a checked exception as a runtime exception.

```java
    private static <T> T createInstanceOf(Class<? extends T> clazz) {
        var ctors = Stream.of(clazz.getDeclaredConstructors());
        var found =
                ctors.filter(ctor -> ctor.getParameterCount() > 0)
                        .findFirst()
                        .map(
                                ctor ->
                                        Try.of(() -> ctor.newInstance())
                                                .getOrElseThrow(ex -> new RuntimeException(ex)));

        @SuppressWarnings("unchecked")
        var res = (T) found.orElseThrow();
        return res;
    }
```

### Possible workarounds

I'm trying to think about how I could get those constructor parameters. Most likely I can't use mapstruct to instantiate this. I'll have to write something more custom for each class that needs this.

### MapStruct Version

1.5.5

**Comment by filiphr** [comment]
@xenoterracide can you please clarify a bit how MapStruct fits in this examples? What do you want to achieve with MapStruct here?

**Comment by xenoterracide** [comment]
I want to use it similar to https://mapstruct.org/documentation/stable/reference/html/#mapping-with-constructors

**Comment by xenoterracide** [comment]
I might be able to do this in the mean time https://mapstruct.org/documentation/stable/reference/html/#passing-target-type I'm finding the example a bit confusing though... maybe another bug, but I'd show an example where you just pass `CarDto` and then show how you could simplify it. I was trying to figure out what `Reference` was.

**Comment by filiphr** [comment]
@xenoterracide from what I could understand from #3476 you are looking for a way to create the return type, i.e. use an `ObjectFactory`. In the documentation you shared for passing target type you are looking at something that is for mapping the properties. the `resolve` and `toReference` methods are actually methods that are going to map from `Reference` to `T` and from `BaseEntity` to `Reference`.

If you look at the generated code it has:

```java
car.setOwner( referenceMapper.resolve( carDto.getOwner(), Owner.class ) );
```

The `carToCarDto` in that example will look like:

```java
carDto.setOwner( referenceMapper.toReference( car.getOwner() ) );
```
Should we close this issue now?

**Comment by xenoterracide** [comment]
I left this open because I was kind of hoping that maybe you'd still be interested in 

> Maybe an API like DTO copy( ENTITY, Class<DTO> )

it'd at least have reduced some of my code...

**Comment by filiphr** [comment]
>it'd at least have reduced some of my code... If not, you can close.

I am not sure that I am following. As I understood you in #3476 you would like to use `DTO copy( ENTITY, Class )` an on object factory, right? So if you annotate the method with `@ObjectFactory` then it would be used, right?

**Comment by xenoterracide** [comment]
no, that would be this ticket. You wouldn't need an `@ObjectFactory` with what I was proposing here. `@ObjectFactory` is an alternative solution to this.

... you know what. I'm gonna close this and make a second cleaner ticket. Even I'm getting confused as to which is which. Then we can decide whether to close that with an undesirable behavior...

Currently I think there's a feature request and a doc bug.
