### ISSUE TITLE
Use @Builder And @Data，the @ObjectFactory Invalid

### ISSUE THREAD

**Issue by partick33** [mapstruct/mapstruct#3478]
### Actual behavior

I use @Builder And @Data in an entity，the field not final，when i use add the @Builder, the @ObjectFactory Invalid，the generate Code will use the Builde，not use no args construct 

### Steps to reproduce the problem

I use @Builder And @Data in an entity，the field not final，when i use add the @Builder, the @ObjectFactory Invalid，the generate Code will use the Builde，not use no args construct 

### MapStruct Version

1.5.2.Final

**Comment by thunderhook** [comment]
Do you use the `lombok-mapstruct-binding` annotation processor? See: https://mapstruct.org/documentation/stable/reference/html/#lombok

If the problem is still the case with it, please provide a simple example.
