### ISSUE TITLE
customPageA convert to customPageB cause StackOverflowError

### ISSUE THREAD

**Issue by resp-200** [mapstruct/mapstruct#3479]
### Actual behavior

I'm trying to convert a custom Page into another custom Page， and I got a stackOverFlowError at compile time

this is errorMsg : 

![image](https://github.com/mapstruct/mapstruct/assets/108868195/57fcfa55-8400-4b7c-9614-108e3e08458b)

### Steps to reproduce the problem

Here are my examples：

### MobileDTO
````java
package com.example.demo.test;

import lombok.Data;

import java.io.Serializable;

@Data
public class MobileDTO implements Serializable {
    private Integer value;
}

````
### ServerDTO
````java
package com.example.demo.test;

import lombok.Data;

import java.io.Serializable;

@Data
public class ServerDTO implements Serializable {
    private Integer value;
}

````
### MobilePage
````java
package com.example.demo.test;

import lombok.Data;

import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;

@Data
public class MobilePage<T>  implements Serializable {

    private List<T> list;

    private Integer total;

    private Integer pageNum;

    private Integer pageSize;


    public MobilePage(){
        list = new LinkedList<>();
        total = 0;
    }


    public MobilePage(List<T> list, Integer total) {
        this.list = list;
        this.total = total;
    }

    public MobilePage(List<T> list, Integer total, Integer pageNum, Integer pageSize) {
        this.list = list;
        this.total = total;
        this.pageNum = pageNum;
        this.pageSize = pageSize;
    }
}

````
### ServerPage
````java
package com.example.demo.test;

import lombok.Data;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Data
public class ServerPage<T> implements Serializable {

    private List<T> list;

    private Integer total;

    private Integer pageNum;

    private Integer pageSize;

    public static ServerPage defaultPage() {
        ServerPage page = new ServerPage();
        page.setList(new ArrayList());
        page.setTotal(0);

        return page;
    }
}

````
### Converter
````java
package com.example.demo.test;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface MyMap {
    MyMap INSTANCE = Mappers.getMapper(MyMap.class);

    MobilePage<MobileDTO> convert2MobileStockInfoDTOPage(ServerPage<ServerDTO> data);
}

````

There is no recursion in my code, why is this happening?

### MapStruct Version

1.3.0.Final

**Comment by KelseySking** [comment]
Yes, I also encountered this problem, which confused me

**Comment by Liweiqi163** [comment]
me too

**Comment by thunderhook** [comment]
Would you be so kind to upgrade MapStruct to the latest version (e.g. 1.5.5.Final) and try again? There have been issues with 1.3.0 which have been fixed with 1.3.1, e.g. #1751

@KelseySking & @Liweiqi163 what versions do you use?

**Comment by thunderhook** [comment]
I have just tried your sample code on 1.5.5.Final and it works fine. Please upgrade your mapstruct version. If the problem persists, I'll reopen the issue.

**Comment by resp-200** [comment]
thinks for your help , I will test it soon

**Comment by KelseySking** [comment]
Thank you for your answer. I have upgraded the version and resolved this issue

**Comment by resp-200** [comment]
I read all discussion about "StackOverflowError" ，but there have quite a few changes between 1.3.0Final ~ 1.5.5Final， I'm more interested in how to solve it in the end.

**Comment by thunderhook** [comment]
You can try to upgrade to 1.3.1, maybe it's already fixed there. I'm not sure if you can fix this on your side without upgrading it.

**Comment by filiphr** [comment]
@resp-200 we do not have support for older versions. If something is working on the latest GA version (1.5.5.Final at this time) then you can either upgrade to that one or figure it out on your own.

**Comment by resp-200** [comment]
I upgrade to 1.3.1 Final , and then I had sloved this problem . Thanks again for your help.
