### ISSUE TITLE
Use a custom Generated annotation

### ISSUE THREAD

**Issue by sanmibuh** [mapstruct/mapstruct#3484]
### Use case

javax.annotation.processing.Generated annotation has a source Retention policy.

So pitest cannot see this annotation on the bytecode, and it could find mutants.
Please check https://github.com/hcoles/pitest/issues/347

### Generated Code

Create a Custom @Generated with CLASS retention and use this annotation instead of the javax ones.

### MapStruct Version

1.5.5

**Comment by thunderhook** [comment]
Starting with MapStruct 1.6.0.Beta1 you can pass annotations to generated code. Have a look at the examples here:

* https://mapstruct.org/news/2023-11-04-mapstruct-1_6_0_Beta1-is-out/#passing-annotations-to-generate-code
* https://mapstruct.org/documentation/dev/reference/html/#adding-annotations

**Comment by filiphr** [comment]
@sanmibuh for mutation testing I would also argue that you shouldn't ignore code generated by MapStruct and you should instead write tests for it

**Comment by sanmibuh** [comment]
@filiphr why test the mappers itself? 
I test the functionality, not the code.

Mappers are tested indirecty when you test a functionality that uses it.

The problem with pitest is that the generated mappers code has a lot of paths and in your use case you haven't. For example nullsafe check on attributes that cannot be null in the code.

**Comment by sanmibuh** [comment]
For example, in this package:
<img width="809" alt="image" src="https://github.com/mapstruct/mapstruct/assets/15193703/e007ed8f-5883-4d02-a7e0-fe932e79abb7">
As you can see EventsRepository (My secondary adapter) has full coverage without any mutants. Im testing only this class functionality with the diferent use case it has.
But I have mutants in the mapper because there are som atribute tha cannot be null but the mapper add paths to be nullsafe.

Make a test for the mapper for a not existing real case It is an effort without return.

If in the future I remove mapstruct in this case and I code the mapping myself (or any other refactor) the test is not changed and assures my code.
I

**Comment by filiphr** [comment]
>Mappers are tested indirecty when you test a functionality that uses it.

That's what I meant actually. Not have something like `MyMapperTest`, but have some tests that are covering the functionality.

>The problem with pitest is when the generated mappers code has a lot of paths and in your use case you haven't. For example nullsafe check on attributes that cannot be null in the code.

for the nullsafe check I would suggest checking #1243. It is a large feature that we want to add nullability and MapStruct respecting that.

For other paths (not related to null checks) it might be a bit related to how you define mappings.

>Make a test for the mapper for a not existing real case It is an effort without return.

I 100% agree with you about this. There is no point in testing the use cases that you do not have. The ideal scenario with #1243 would be if MapStruct can be smart enough not to generate code that you do not need. 

With the new `@AnnotateWith` you can already add annotations to ignore them, but in your place I would leave it and live with the lower coverage. However, I know that sometimes there are strict rules about being above a certain threshold.

**Comment by sanmibuh** [comment]
Yes, the problem is the threshold. For coverage, we don't have any problem because we do no need 100%. But we dont want any mutants.

So it makes sense excluding for pitest (nowadays we are excluding by Name, excluding all *MapperImpl)
But we are not excluding them on the unit test
