### ISSUE TITLE
Allow instantiating with class/constructor

### ISSUE THREAD

**Issue by xenoterracide** [mapstruct/mapstruct#3486]
### Use case

The context was, I was creating a dynamic proxy, and the constructor needed to be called has multiple arguments. Writing the reflection to instantiate the constructor is kind of annoying. Proposed APIs

```java
Dto copy( Entity e, Class<Dto> clazz ); // magically figure it out the same way we can figure out how to use multiple arg constructors now.
Dto copy( Entity e, Constructor<Dto> ctor );
```

Instead of calling `new Dto()` mapstruct would instead use reflection to create a newInstance, but otherwise call the constructor as it would if it were using `new`.

There's a chain of previous context in #3472 and #3476 but it's confusing so isolating this request.

### Generated Code

this definitely isn't final code as it uses vavr, and instead of deterministically knowing which constructor to use, is using a very poor heuristic.

```java
        var ctors = Stream.of(clazz.getDeclaredConstructors());
        var found =
                ctors.filter(ctor -> ctor.getParameterCount() > 0)
                        .findFirst()
                        .map(
                                ctor ->
                                        Try.of(() -> ctor.newInstance())
                                                .getOrElseThrow(ex -> new RuntimeException(ex)));

        @SuppressWarnings("unchecked")
        var res = (T) found.orElseThrow();
    }
```

### Possible workarounds

`@ObjectFactory`

### MapStruct Version

1.5.5

**Comment by filiphr** [comment]
Why is it a problem to use `@ObjectFactory` for this.

```java
@Mapper
public interface MyMapper {

    Dto copy(Entity e);

    @ObjectFactory
    static <T extends Dto> T instantiate(Entity source, @TargetType Class<T> targetDto) {
        // Write custom logic to determine what to create
    }
}
```

------ 
I think that it would also be easier if you provide some minimal example with some code. Like how would you write this type of mapping by hand (without MapStruct).

**Comment by xenoterracide** [comment]
because I'm lazy and I don't want to write a bunch of try/catch code, the more work I can have mapstruct do for me the better ;) .

**Comment by filiphr** [comment]
I still don't understand what you are looking for MapStruct to generate for you. Would really appreciate if you can create an MCVE (Minimal Complete Verifiable Example) that we can see how you would write such a thing by hand and then we can go on from there to see what MapStruct can do for you.

**Comment by xenoterracide** [comment]
I want it to generate a calls to `ctor.newInstance()` (which is convoluted and depends on a few things)

**Comment by filiphr** [comment]
So you are going to have custom logic that would find the `Constructor` and then pass it on the mapping method?

and then for 

```java
Dto copy( Entity e, Constructor<Dto> ctor );
```

you would expect something like:

```java
public Dto copy( Entity e, Constructor<Dto> ctor ) {

    Dto dto = ctor.newInstance();

    // mapping from entity to dto

    return dto;
}
```

**Comment by xenoterracide** [comment]
yes! but if it's got more than one parameter... you'd have to figure that out, probably in the same way you do here https://mapstruct.org/documentation/stable/reference/html/#mapping-with-constructors . If it's a class, obviously you'd have to look for the right constructor instead of just being handed one first, but that's just looping over them.

Initially, I wasn't sure how I'd add `@Default` but come to think of it, I always new which constructor, so I could easily have added that to magic proxy constructor.

**Comment by xenoterracide** [comment]
I figured that's where we'd end up, but at least we got to the point where you understood what I was suggesting. That's not intended to be a criticism of you, btw.

**Comment by filiphr** [comment]
>I figured that's where we'd end up, but at least we got to the point where you understood what I was suggesting

Well I was having troubles understanding because we already have the `@ObjectFactory` and I already proposed that few times, but seems like you don't want to use `@ObjectFactory`

**Comment by xenoterracide** [comment]
at the initial time of writing I didn't understand/know about it. It's not the feature I was proposing either, so I tried making the issue less distracted by the original context. Reflection code is often "samey" and full of boilerplate so it seem's like a worthwhile feature to make it simpler.
