### ISSUE TITLE
Merge target with source presence checking set target property to default instance with null source property

### ISSUE THREAD

**Issue by cristian-aimi** [mapstruct/mapstruct#3491]
### Expected behavior

using the source presence check (hasXyz) I could receive a property as valued, for example hasXyz=true, but then find it valued at NULL, this to indicate that it must be cleaned, in this case I would expect to set the target with NULL

``` java
if ( proto.hasResStatus() ) {
    if (proto.getResStatus() == null) {
        h5s.setResStatus(null);
    } else {
        if ( h5s.getResStatus() == null ) {
            h5s.setResStatus( new ResStatus() );
        }
        resStatusInputProtoMapper.toH5s( proto.getResStatus(), h5s.getResStatus() );
    }
}
```

### Actual behavior

instead mapstruct ignores this case and always tries to set the target object by creating a new instance as target if not present

``` java
if ( proto.hasResStatus() ) {  
    if ( h5s.getResStatus() == null ) {
        h5s.setResStatus( new ResStatus() );
    }
    resStatusInputProtoMapper.toH5s( proto.getResStatus(), h5s.getResStatus() );
}
```

### Steps to reproduce the problem

``` java
@Mapper(
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
    uses = {
        ResStatusInputProtoMapper.class
    }
)
public interface ReservationInputProtoMapper  {

    Reservation toH5s(ReservationInputProto proto, @MappingTarget Reservation h5s);
}
```
### MapStruct Version

1.5.5.Final

**Comment by cristian-aimi** [comment]
```
public interface ResStatusInputProtoMapper {

ResStatus toH5s(ResStatusInputProto proto, @MappingTarget ResStatus h5s);
}
```

**Comment by thunderhook** [comment]
Hi,

I'm not sure I'm following. Shouldn't a source presence check avoid passing a `null` value?
Do you have a use case for a presence check that is "valid" where the underlying value is `null`?

Of course you could argue that it's possible to write **any** code in the source presence check method, such as:
```java
public boolean hasResStatus() {
  return true; // i don't care, always return true, haha!
  // or maybe: return true if another possibly related field is set
}
```

But this feels like abusing the system for maybe another use case or workaround.
So please provide more details on this, I'm happy to help,

**Comment by cristian-aimi** [comment]
Hi,

I confirm, I was making improper use of the presence check, sorry and thanks
