### ISSUE TITLE
Java 8 compiling error

### ISSUE THREAD

**Issue by eix128** [mapstruct/mapstruct#3496]
### Expected behavior

mvn install cmd should success 
because your readme tells us java 8 support...

### Actual behavior

mvn install 
failed:

[INFO]
[INFO] --- enforcer:3.4.1:enforce (enforce-mapstruct-rules) @ mapstruct-processor ---
[INFO] Rule 1: org.apache.maven.enforcer.rules.dependency.DependencyConvergence passed
[INFO] Rule 2: org.apache.maven.enforcer.rules.RequirePluginVersions passed
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for MapStruct Aggregator 1.6.0-SNAPSHOT:
[INFO]
[INFO] MapStruct Parent ................................... SUCCESS [ 26.216 s]
[INFO] MapStruct Build Configuration ...................... SUCCESS [  4.486 s]
[INFO] MapStruct Core ..................................... SUCCESS [ 25.159 s]
[INFO] MapStruct Core JDK 8 ............................... SUCCESS [  0.317 s]
[INFO] MapStruct Processor ................................ FAILURE [ 10.338 s]
[INFO] MapStruct Integration Test ......................... SKIPPED
[INFO] MapStruct Documentation ............................ SKIPPED
[INFO] MapStruct Distribution ............................. SKIPPED
[INFO] MapStruct Aggregator ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2023-12-30T21:47:20+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (enforce-mapstruct-rules) on project mapstruct-processor:
[ERROR] Rule 0: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
[ERROR] Detected JDK version 1.8.0-391 (JAVA_HOME=C:\Tools\Java\jdk-1.8\jre) is not in the allowed range [11,).
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :mapstruct-processor

### Steps to reproduce the problem

[ERROR] Rule 0: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
[ERROR] Detected JDK version 1.8.0-391 (JAVA_HOME=C:\Tools\Java\jdk-1.8\jre) is not in the allowed range [11,).

Java 8 391 Windows x64

### MapStruct Version

1.6.0-SNAPSHOT

**Comment by thunderhook** [comment]
Using MapStruct in your projects needs at least Java 8. Building the MapStruct source needs at least Java 11, see: https://github.com/mapstruct/mapstruct#building-from-source
