### ISSUE TITLE
I can't transfer Bean to Map<String,Object>

### ISSUE THREAD

**Issue by raysonTao** [mapstruct/mapstruct#3502]
### Expected behavior

i hope that MapStruct can privide a example or response How can i implement Bean to Map<String,Object> meanwhile point out the map key is `@Mapping's target`
```java
@Mapper
public interface SimulateConverter {

    SimulateConverter INSTANCE = Mappers.getMapper(SimulateConverter.class);

    @Mapping(target = "id", source = "id", ignore = true)
    @Mapping(target = "activeTime", source = "activeTime", ignore = true)
    @Mapping(target = "deviceId", source = "deviceId", ignore = true)
    @Mapping(target = "MinCellTemp", source = "minCellTemp")
    @Mapping(target = "MaxCellTempPosition", source = "maxCellTempPosition")
    @Mapping(target = "MinCellVolt", source = "minCellVolt")
    @Mapping(target = "MinCellTempPosition", source = "minCellTempPosition")
    @Mapping(target = "MaxCellVolt", source = "maxCellVolt")
    @Mapping(target = "MaxCellVoltPosition", source = "maxCellVoltPosition")
    @Mapping(target = "MinCellVoltPosition", source = "minCellVoltPosition")
    @Mapping(target = "MaxCellTemp", source = "maxCellTemp")
    Map<String, Object> pack2map(PackEntitiy packEntitiy);
}
```
Wrong compile remind: `The return type Map<String,Object> is an abstract class or interface`
if i change Map to  HashMap ;  `Unknown property "id" in result type HashMap<String,Object>. Did you mean "empty"?` 

### Actual behavior

Wrong compile remind: `The return type Map<String,Object> is an abstract class or interface`
if i change Map to  HashMap ;  `Unknown property "id" in result type HashMap<String,Object>. Did you mean "empty"?` 

### Steps to reproduce the problem

just use provided my code;

### MapStruct Version

1.5.5 final

**Comment by thunderhook** [comment]
Hi @raysonTao!

Thanks for bringing this up. Mapping a bean to a `Map<String, Object>` is not currently supported.
There is an issue for that. I will close this one in favour of this one:
* #2504
