### ISSUE TITLE
False warning for @Mapper

### ISSUE THREAD

**Issue by eix128** [mapstruct/mapstruct#3510]
### Expected behavior

I have Entity

```java
package com.manage.jpa;

import com.manage.jpa.auth.UserEntity;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@EntityListeners(AuditingEntityListener.class)
@MappedSuperclass
public abstract class GenericEntity extends BaseEntity {

    @LastModifiedDate
    @Column(columnDefinition = "timestamp default '2020-04-10 20:47:05.967394'")
    protected LocalDateTime lastModifiedDate;

    @CreatedDate
    @Column(columnDefinition = "timestamp default '2020-04-10 20:47:05.967394'", updatable = false)
    protected LocalDateTime createdDate;


    @CreatedBy
    protected Integer createSicil;

    @LastModifiedBy
    protected Integer modifierSicil;


    @Basic(fetch = FetchType.EAGER)
    @Column(name = "isEnabled", unique = false, nullable = false)
    protected boolean enabled;
}
```

The columns on entity auto generated by spring boot.

One class extends that mappedsuperclass

```java
@Entity
@Getter
@Setter
public class ItemTypeEntity extends GenericEntity {

    private String itemType;

    @ManyToOne
    private ItemCategoryEntity itemCategory;

    @Override
    public DTOObject<?,?> toDTOObject() {
        return null;
    }
}
```

and

```java
package com.manage.jpa;

import com.manage.model.DTOObject;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Getter
@Setter
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @Column(name = "idValue", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "native")
    @GenericGenerator(name = "native", strategy = "native")
    protected Long idValue;



    public abstract DTOObject<?,?> toDTOObject();
}
```

my base entity for all...

my DTO Object:

```java
package com.manage.service.admin.category.dto;

import com.manage.jpa.inventory.ItemCategoryEntity;
import com.manage.model.DTOObject;
import com.manage.service.admin.category.CategoryMapper;
import lombok.Data;
import lombok.EqualsAndHashCode;

@EqualsAndHashCode(callSuper = true)
@Data
public class ItemCategoryDTO extends DTOObject<ItemCategoryEntity,String> {

    private String kategori;
    private Integer kategoriId;

    @Override
    public ItemCategoryEntity toJPA() {
        return CategoryMapper.INSTANCE.toEntity(this );
    }

    @Override
    public String getUpdateValue() {
        return null;
    }
}
```

```java
package com.manage.service.admin.category;

import com.manage.jpa.inventory.ItemCategoryEntity;
import com.manage.service.admin.category.dto.ItemCategoryDTO;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper(componentModel = "spring")
public interface CategoryMapper {
    public CategoryMapper INSTANCE = Mappers.getMapper(CategoryMapper.class);

    @Mapping(source = "categoryName", target = "kategori")
    @Mapping(source = "idValue", target = "kategoriId")
    @Mapping(source = "idValue", target = "key")
    public ItemCategoryDTO toDto(ItemCategoryEntity categoryEntity);

    @InheritInverseConfiguration
    @Mapping(source = "key", target = "idValue")
    public ItemCategoryEntity toEntity(ItemCategoryDTO itemCategoryDTO);


    public List<ItemCategoryDTO> toAllDTOS(List<ItemCategoryEntity> authors);
}
```

### Actual behavior

/media/xxxx/yyyy/Files/Works/DeepAssets/src/main/java/com/manage/service/admin/category/CategoryMapper.java:23: warning: Unmapped target properties: "lastModifiedDate, createdDate, createSicil, modifierSicil, enabled".
    public ItemCategoryEntity toEntity(ItemCategoryDTO itemCategoryDTO);
                              ^
1 warning

Well i know i can ignore the field by 
```java
@Mapper(componentModel = "spring",unmappedTargetPolicy = ReportingPolicy.IGNORE)
```
But these fields are not ignored.
They are auto generated annotated strings.
lastModifiedDate, createdDate, createSicil etc..

They are annotated and auto generated by spring boot.
@CreatedBy

I think your warning should check them auto generated fields at runtime or not....

### Steps to reproduce the problem

```java
package com.manage.service.admin.category;

import com.manage.jpa.inventory.ItemCategoryEntity;
import com.manage.service.admin.category.dto.ItemCategoryDTO;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper(componentModel = "spring")
public interface CategoryMapper {
    public CategoryMapper INSTANCE = Mappers.getMapper(CategoryMapper.class);

    @Mapping(source = "categoryName", target = "kategori")
    @Mapping(source = "idValue", target = "kategoriId")
    @Mapping(source = "idValue", target = "key")
    public ItemCategoryDTO toDto(ItemCategoryEntity categoryEntity);

    @InheritInverseConfiguration
    @Mapping(source = "key", target = "idValue")
    public ItemCategoryEntity toEntity(ItemCategoryDTO itemCategoryDTO);


    public List<ItemCategoryDTO> toAllDTOS(List<ItemCategoryEntity> authors);
}
```

### MapStruct Version

1.5.5.Final

**Comment by thunderhook** [comment]
Hi @eix128 

MapStruct has no knowledge how and what properties are getting generated by some other framework. This could be some magic from spring boot, but possibly due to other frameworks, even a self-written annotation processor handling custom annotations.

MapStruct is looking at properties that can be modified (set) by looking at the setters (or possibly a builder method when using the builder pattern).

In your example the `GenericEntity` has a `@Setter` annotation above the class. Therefore every field is mutable and can be modified by MapStruct (or even yourself).

```java
@Getter
@Setter // <--
@EntityListeners(AuditingEntityListener.class)
@MappedSuperclass
public abstract class GenericEntity extends BaseEntity {

    @LastModifiedDate
    @Column(columnDefinition = "timestamp default '2020-04-10 20:47:05.967394'")
    protected LocalDateTime lastModifiedDate;

    @CreatedDate
    @Column(columnDefinition = "timestamp default '2020-04-10 20:47:05.967394'", updatable = false)
    protected LocalDateTime createdDate;

    @CreatedBy
    protected Integer createSicil;

    @LastModifiedBy
    protected Integer modifierSicil;

    @Basic(fetch = FetchType.EAGER)
    @Column(name = "isEnabled", unique = false, nullable = false)
    protected boolean enabled;
}
```

Therefore I would suggest to remove the mutability of the fields that you don't want to be modified afterwards by removing the setter (which is generally good practice).

If this is not possible (because it is not your own code, but it seems it is) you can:

1. ignore them at the mapping method

```java
    @Mapping(target = "lastModifiedDate", ignore =true)
    @Mapping(target = "createdDate", ignore =true)
    // ...
    @Mapping(source = "categoryName", target = "kategori")
    @Mapping(source = "idValue", target = "kategoriId")
    @Mapping(source = "idValue", target = "key")
    public ItemCategoryDTO toDto(ItemCategoryEntity categoryEntity);
```

Or provide a MapperConfig with a prototype mapping where those fields are ignored. You can find an example in the reference documentation, see: [`Example 92. Mapper configuration class with prototype methods`](https://mapstruct.org/documentation/stable/reference/html/#shared-configurations)

**Comment by eix128** [comment]
@thunderhook 
But there could be some annotation you can add to notify MapStruct like

@MapStructIgnore
@CreatedBy

So you just check 'your own' struct.
That can be easy for you...

**Comment by thunderhook** [comment]
@eix128 Using annotations to ignore certain setters was decided against in #1152 (4 years ago). However, this may be getting more attention now, see https://github.com/mapstruct/mapstruct/issues/3222#issuecomment-1518670392 (maybe leave a 👍 there)

With the current release, it is possible to write a custom accessor naming strategy that checks if a method is annotated with a given annotation. However, this is quite cumbersome as it needs to be built as a separate Maven dependency. See https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy for more information.

But specifically in your example, is there any particular reason to expose the setters of these fields? IMHO the setters should just not be there. Even if MapStruct currently supported an annotation to ignore the setter, would you rather use it and provide more code/annotations and bloat your models?

To be clear, I'm not trying to badmouth the code, I'm just trying to figure out if there's a meaningful use case behind it.
