### ISSUE TITLE
Improve tests to show that Lombok `@SuperBuilder` is supported

### ISSUE THREAD

**Issue by thunderhook** [mapstruct/mapstruct#3524]
It is currently not clear if Lombok `@SuperBuilder` is supported by MapStruct (see https://github.com/mapstruct/mapstruct-idea/issues/159#issuecomment-1826883528). It may work by accident.

We're using it extensively in our company code. So it is critical for us to know if we should disable our builders or maybe even need to redesign our domain objects.

Therefore I want to provide a set of integration tests to show that it works.

If it has been proven, we can look at the following tickets:
* https://github.com/mapstruct/mapstruct-idea/issues/159#issue-1990285833
* respectively this PR: https://github.com/mapstruct/mapstruct-idea/pull/161

@filiphr Does that sound okay to you?

**Comment by filiphr** [comment]
Lombok `@SuperBuilder` is a bit special and I am a bit reluctant to say that we officially support it. Perhaps some of this has been covered by #3492. 

If we can have simple tests (without Lombok) that displays that this works, then I am fine, but going further and we officially support `@SuperBuilder` I am not sure that it is a good idea. I am also fine in providing an improved fluent builder support, but it really depends on the level of changes that we need to do to support this.

**Comment by thunderhook** [comment]
I understand your reluctance. Officially supporting it would also mean providing ongoing support, even if the feature changes on Lombok's end.

I will provide some tests with delomboked `@SuperBuilder` code with different scenarios, e.g:
* abstract or non-abstract parent classes
* None, one or more interfaces between
* annotated with SuperBuilder without inheritance

I may come up with some edge cases as I write the tests. 
As soon as I realise that a certain scenario does not work, I can then open a new issue.

I hope to get some tests done next week 🤞

**Comment by filiphr** [comment]
That sounds great @thunderhook. Having delomboked `@SuperBuilder` is something that I am OK with. That way we can actually see how the code looks like and we can more easily work on fixes if needed.
