### ISSUE TITLE
Access to Source Property Name in Conditional Methods

### ISSUE THREAD

**Issue by Inso4** [mapstruct/mapstruct#3541]
### Use case

On the release notes for 1.6.0.Beta1 at [maptstruct.org](https://mapstruct.org/news/2023-11-04-mapstruct-1_6_0_Beta1-is-out/) it mentions "Access to target / source property names in conditional and mapping methods", however on [2688](https://github.com/mapstruct/mapstruct/issues/2688) support was only added for Target Property name. 

I actually have a use case for providing source property name as well. Consider this example: 

```
public class Employee {
    private String employeeName;

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
}

public class EmployeeDTO {
    private String name;
    private Set<String> initializedProperties = new HashSet<>();

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.initializedProperties.add("name");
        this.name = name;
    }

    public boolean hasProperty(String property) {
        if(initializedProperties.contains(property)) {
            return true;
        }
        return false;
    }
}

public class DTOPresenceChecker {
    @Condition
    public static boolean hasProperty(EmployeeDTO dto, @SourcePropertyName String propertyName) {
        return dto.hasProperty(propertyName);
    }
}

@Mapper(uses = DTOPresenceChecker.class)
public interface EmployeeMapper {

    @Mapping(source = "name", target = "employeeName")
    Employee map(EmployeeDTO employeeDTO);
}
```

### Generated Code

For the use case above i'd like mapstruct to generate code like below
```
// GENERATED CODE
public class EmployeeMapperImpl implements EmployeeMapper {

    @Override
    public Employee map(EmployeeDTO employeeDTO) {
        // ...
        if ( DTOPresenceChecker.hasProperty( employeeDTO, "name" ) ) {
            employee.setEmployeeName( employeeDTO.getName() );
        }
        // ...
    }

    // ...
}
```

### Possible workarounds

I can maintain a static mapping of mismatched source and target properties to lookup by target, but the above would be a useful feature for me. 

### MapStruct Version

1.6.0.Beta1

**Comment by thunderhook** [comment]
Hi @Inso4 

Thanks for bringing this up.
Yes, sorry about that. It wasn't communicated well in the release notes. I think what was meant was that the 1.6.0.Final release will have these features.

Access to the source property name is already implemented and will be part of 1.6.0.Beta2, see:
* #3323
