### ISSUE TITLE
MapStruct: custom mapping function is applied to all fields

### ISSUE THREAD

**Issue by Govardhan451** [mapstruct/mapstruct#3548]
### Expected behavior

target.setA(modify(a));
target.setB(modify(b));

### Actual behavior

target.setA(String.valueOf(a));
target.setB(modify(b));

### Steps to reproduce the problem

Source class:

                    class Source {
                        private int a;
                        private int b;
                        // getters etc...
                    }
Target class:

                    class Target {
                        private String a;
                        private String b;
                        // getters etc...
                    }
Mapper:

      @Mapping(source="a", target="a") // should not be necessary, but to make it more explicit
      @Mapping(target="b", expression = "java(modify(b))")
      public abstract Target sourceToTarget(Source source);
      
      String modify(int value) {
          return "prefix_" + value;
      }

### MapStruct Version

1.5.5.Final

**Comment by thunderhook** [comment]
Hi @Govardhan451 

I think you may have accidentally swapped the expected and actual code parts.

The following code shows that the modify method is used for `a` and `b`:

```java
@Mapper
abstract class _3548Mapper {

    @Mapping(source="a", target="a") // should not be necessary, but to make it more explicit
    @Mapping(target="b", expression = "java(modify(b))")
    public abstract Target sourceToTarget(Source source);

    String modify(int value) {
        return "prefix_" + value;
    }

}

class Source {
    public int a;
    public int b;
}

class Target {
    public String a;
    public String b;
}
// GENERATED CODE

class _3548MapperImpl extends _3548Mapper {

    @Override
    public Target sourceToTarget(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        target.a = modify( source.a );

        target.b = modify(b);

        return target;
    }
}
```

If you define a method with a given source and target type, MapStruct will use it **whenever it can be used**. In your case `int -> String`.

To avoid this, you can use the `@Named("someName")` annotation above your method. MapStruct will only use named methods, when they're explicitly defined with `@Mapping(..., qualifiedByName = "someName")`.

```java
    @Named("someName")
    String modify(int value) {
        return "prefix_" + value;
    }
```
