### ISSUE TITLE
No actual mapping code, when inherited from another interface

### ISSUE THREAD

**Issue by ARManakhov** [mapstruct/mapstruct#3549]
### Expected behavior

Actually when i have `@Mapping` annotation on one of the methods, it generates just fine 
```java
    @Override
    public Source toEntity(SourceDto entity) {
        if ( entity == null ) {
            return null;
        }

        Source source = new Source();

        source.setName( entity.getName() );
        source.setBaseUrl( entity.getBaseUrl() );
        source.setLocalPath( entity.getLocalPath() );
        source.setExtractorChains( extractorChainDtoSetToExtractorChainSet( entity.getExtractorChains() ) );
        Map<String, String> map = entity.getHeaders();
        if ( map != null ) {
            source.setHeaders( new LinkedHashMap<String, String>( map ) );
        }

        return source;
    }
 ```

### Actual behavior

But without any annotations on methods, it generate this code
```java
    @Override
    public Source toEntity(SourceDto entity) {
        if ( entity == null ) {
            return null;
        }

        Source source = new Source();

        return source;
    }
```

### Steps to reproduce the problem

I made repo with example https://github.com/ARManakhov/mapstruct_bug
in short in my project i have two classes to map (not included all fields here, it has some additional lists, but you can view in my repo, but actualy no changes when i remove that additional fields):

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Source {
    private Long id;
    private String name;
    private String baseUrl;
    private String localPath;
}
```
```java
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SourceDto {
    private String name;
    private String baseUrl;
    private String localPath;
}
```

Interface for mappers
```java
public interface Mapper<D, E> {
    D toDto(E entity);

    E toEntity(D entity);

    List<D> toDto(List<E> entity);

    List<E> toEntity(List<D> dto);
}

```

And my mapper class for Source and SourceDto
```java
@org.mapstruct.Mapper
public interface SourceMapper extends Mapper<SourceDto, Source> {
    SourceDto toDto(Source entity);

    Source toEntity(SourceDto entity);

    List<SourceDto> toDto(List<Source> entity);

    List<Source> toEntity(List<SourceDto> dto);
}
```

### MapStruct Version

1.5.5.Final

**Comment by chenzijia12300** [comment]
Hi,I don't think this is a BUG. 
It happens because you didn't add `annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0" ` in build.gradle.
Using Lombok 1.18.16 and later requires an additional annotation handler to be declared.
You can take a look at this https://mapstruct.org/documentation/dev/reference/html/#_set_up

**Comment by filiphr** [comment]
Thanks for the pointer @chenzijia12300. Closing this since it was answered. @ARManakhov if you already had the `lombok-mapstruct-binding` dependency, then please let us know and we'll reopen it.

**Comment by ARManakhov** [comment]
yes, i have `lombok-mapstruct-binding` dependency

**Comment by ARManakhov** [comment]
oh, i'm sorry. As @chenzijia12300 pointed out, i forgot to add it
