### ISSUE TITLE
Ignore mapping of fields from super classes and interfaces

### ISSUE THREAD

**Issue by zyberzebra** [mapstruct/mapstruct#3551]
### Description:
Currently, when using MapStruct to map between two classes, it is not possible to ignore mapping of fields that are inherited from a super class or implemented from an interface.
### Problem:

I would have to use 
```java
@Mapping(target = "propertyToIgnore1",ignore = true)
@Mapping(target = "propertyToIgnore2",ignore = true)
@Mapping(target = "propertyToIgnore....",ignore = true)
``` 
for every target and if i update the Interface or Superclass i would have to back to all my mappers and add that ignore field.

### Example
  
![image](https://github.com/mapstruct/mapstruct/assets/73640367/d502331f-2c2a-4974-af0c-0e25d935a230)

```java
public interface BookMapper {

    BookDTO bookToBookDTO(Book book);

    @ObjectFactory
    default BookDTO bookDTOToBookFactory(Book book){
        BookDTO bookDTO = new BookDTO();
        bookDTO.setPrice(calculatePriceSpecificForUser());
        return bookDTO;
    }

}
``` 
The generated Code will Override the Price.
```java
public class BookMapperImpl implements BookMapper {

    @Override
    public BookDTO bookToBookDTO(Book book) {
        if ( book == null ) {
            return null;
        }

        BookDTO bookDTO = bookDTOToBookFactory( book );

        bookDTO.setAuthor( book.getAuthor() );
        bookDTO.setTitle( book.getTitle() );
        bookDTO.setPublisher( book.getPublisher() );
        bookDTO.setPrice( (long) book.getPrice() );

        return bookDTO;
    }
}
``` 
### Proposed Solution:
`@Mapping(ignore = AbstractProduct.class)`

### Usage
```java
    @Mapping(ignore = AbstractProduct.class)
    BookDTO bookToBookDTO(Book book);
``` 
Resulting in: 
```java
public class BookMapperImpl implements BookMapper {

    @Override
    public BookDTO bookToBookDTO(Book book) {
        if ( book == null ) {
            return null;
        }

        BookDTO bookDTO = bookDTOToBookFactory( book );

        bookDTO.setAuthor( book.getAuthor() );
        bookDTO.setTitle( book.getTitle() );
        bookDTO.setPublisher( book.getPublisher() );

        return bookDTO;
    }
}
``` 

### Possible workarounds

```java
    @Mapping(target = "price",ignore = true)
    @Mapping......
    BookDTO bookToBookDTO(Book book);
``` 

### MapStruct Version

MapStruct 1.5.5.Final

**Comment by filiphr** [comment]
This is trickier then it looks like. The way that MapStruct works if by looking at getters / setters. So what if you override one of the getters in in `Book`. Should that property be ignored or not?

Closest that is possible for this might be `@BeanMapping(ignoreByDefault = true)`. However, you would need to define explicitly which fields you want to map when using this.

**Comment by zyberzebra** [comment]
> So what if you override one of the getters in in `Book`. Should that property be ignored or not?
I would expect, no mapping. 

> Closest that is possible for this might be @BeanMapping(ignoreByDefault = true). 
Yes, that would work as a workaround but becomes a non-viable solution in bigger projects I guess.

If you have an Idea how it could be done with one of the SPI Processors I could try implementing it testing it with something custom.

**Comment by filiphr** [comment]
>I would expect, no mapping.

That's one crucial problem. The way MapStruct works is by using getters / setters to determine if something is a property, it has no way of knowing whether the property is defined in the `AbstractBook` or `Book`.

> If you have an Idea how it could be done with one of the SPI Processors I could try implementing it testing it with something custom.

You can extend the `DefaultAccessorNamingStrategy` and override the `getMethodType`. There you have access to the `ExecutableElement` and you can check what the parent of that method is. Is it an interface, is it an abstract class and so on. The only thing is that you don't have access to the target mappings at this point.

The way we are getting methods is by using our  `ElementUtils#getAllEnclosedExecutableElements`, in theory we could pass a boolean flag indicating whether we should fetch from the parents or not.

**Comment by Zegveld** [comment]
Considering the example, wouldn't it be better to use an `@AfterMapping` in that situation?
That way you can override the default value with the calculated value.

Concerning the main issue that you would want to address:
Wouldn't the [shared configuration feature](https://mapstruct.org/documentation/stable/reference/html/#shared-configurations) help a lot in preventing the following problem:
> I would have to use
> ....
> for every target and if i update the Interface or Superclass i would have to back to all my mappers and add that ignore field.

Adjusted example from documentation:
```java
@MapperConfig(
    mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG
)
public interface CentralConfig {

    // Not intended to be generated, but to carry inheritable mapping annotations:
    @Mapping(target = "prop1", ignore = true)
    @Mapping(target = "prop2", ignore = true)
    AbstractProduct anyDtoToEntity(BaseDto dto);
}
```

```
@Mapper( config = CentralConfig.class )
public interface SourceTargetMapper {

    @Mapping(target = "numberOfSeats", source = "seatCount")
    // additionally inherited from CentralConfig, because Book extends AbstractProduct and BookDto extends BaseDto:
    // @Mapping(target = "prop1", ignore = true)
    // @Mapping(target = "prop2", ignore = true)
    Book toCar(BookDto car)
}
```

You might need to introduce a marker interface for the dto objects to make use of this, but you can then do a generic definition which is inherited through the config.

And when you have changes to that class, you only have to go to 1 location to update it instead of every.

This might not be a complete solution for your issue, but could help make it a lot more manageable.

**Comment by zyberzebra** [comment]
Great Solution!
![image](https://github.com/mapstruct/mapstruct/assets/73640367/4d29b6c1-a183-47ee-a751-159ef351a640)

```java
@Mapper( config = CentralConfig.class )
public interface BookMapper {

  BookDTO bookToBookDTO(Book book);

  @ObjectFactory
  default BookDTO bookDTOToBookFactory(Book book){
    BookDTO bookDTO = new BookDTO();
    bookDTO.setPrice(calculatePriceSpecificForUser());
    return bookDTO;
  }

  default double calculatePriceSpecificForUser(){
    return (double) 4.99; // imagine some crazy logic
  }
}
``` 
```java
@MapperConfig(
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG
)
public interface CentralConfig {
    
    @Mapping(target = "price", ignore = true)
    ProductDTO anyEntityToDTO(AbstractProduct entity);
}
``` 
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-03-16T08:15:38+0100",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 21.0.2 (Azul Systems, Inc.)"
)
public class BookMapperImpl implements BookMapper {

    @Override
    public BookDTO bookToBookDTO(Book book) {
        if ( book == null ) {
            return null;
        }

        BookDTO bookDTO = bookDTOToBookFactory( book );

        bookDTO.setTitle( book.getTitle() );
        bookDTO.setInventoryID( book.getInventoryID() );

        return bookDTO;
    }
}
```

**Comment by zyberzebra** [comment]
Could I somehow set the Custom Mapper config at module level?
That would basically solve my problem.

Mapper( config = CentralConfig.class )
