### ISSUE TITLE
Unexpected code generation behavior when modifying properties of classes

### ISSUE THREAD

**Issue by minhnhathoang** [mapstruct/mapstruct#3555]
### Expected behavior

```java
@Component
public class UserConvertorImpl implements UserConvertor {

    @Override
    public User toEntity(UserDO arg0) {
        if ( arg0 == null ) {
            return null;
        }

        UserBuilder user = User.builder();

        if ( arg0.getId() != null ) {
            user.id( arg0.getId() );
        }

        return user.build();
    }
```
### Actual behavior

```java
@Component
public class UserConvertorImpl implements UserConvertor {
    @Override
    public User toEntity(UserDO arg0) {
        if ( arg0 == null ) {
            return null;
        }

        UserBuilder user = User.builder();

        return user.build();
    }
}
```

### Steps to reproduce the problem

Here is my code:

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@SuperBuilder
@ToString
@TableName("m_user")
public class UserDO {
    @TableId("id")
    private String id;
}

@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
@Data
@Entity
public class User {
    private String id;
}

public interface EntityConvertor<Entity, DO> {
    Entity toEntity(DO dataObject);
}

@Mapper(
    componentModel = "spring",
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface UserConvertor extends EntityConvertor<User, UserDO> {
}
```

When I modify properties within DTO classes, the automatically generated code loses all null check if statements (nullValueCheckStrategy = always) and value assignments.

After the unexpected code appears, I executed mvn clean install but there was no change.

I have tried:
Clearing cache (Invalidate Caches in IntelliJ) and restarting IDE -> Unexpected behavior.
Deleting the /target directory -> mvn clean install -> Unexpected behavior.
Modifying the UserConvertor interface (adding comment, space, or code) -> Expected behavior.

I am using IntelliJ IDEA 2022.3.3 Ultimate Edition and have tried with Java 11 and 17.

### MapStruct Version

1.5.5.Final, 1.4.1.Final

**Comment by thunderhook** [comment]
Hi @minhnhathoang!

Do you use the `lombok-mapstruct-binding` plugin as stated in the [docs](https://mapstruct.org/documentation/stable/reference/html/#lombok)?

**Comment by minhnhathoang** [comment]
> Hi @minhnhathoang!
> 
> Do you use the `lombok-mapstruct-binding` plugin as stated in the [docs](https://mapstruct.org/documentation/stable/reference/html/#lombok)?

I followed your suggestion and incorporated the lombok-mapstruct-binding plugin into my project. After doing so, the code generation issue I was experiencing was resolved.

Thank you for providing me with the information above.
