### ISSUE TITLE
Mapstruct with quarkus ignores ReportingPolicy.WARN

### ISSUE THREAD

**Issue by bkalas** [mapstruct/mapstruct#3557]
### Expected behavior

I cloned example https://github.com/mapstruct/mapstruct-examples/tree/main/mapstruct-quarkus
I added one property to PersonDTO
and added unmappedTargetPolicy = ReportingPolicy.WARN) to QUakusMapperConfig.
I expected waringing to be printed out druing build.
Here you can find the source code:
[mapstruct-quarkus-bug.zip](https://github.com/mapstruct/mapstruct/files/14651529/mapstruct-quarkus-bug.zip)

### Actual behavior

No warnings during build

### Steps to reproduce the problem

uzip the attached project.  [mapstruct-quarkus-bug.zip](https://github.com/mapstruct/mapstruct/files/14651529/mapstruct-quarkus-bug.zip)
mvn clean package

### MapStruct Version

1.6.0.Beta1

**Comment by filiphr** [comment]
This is not a problem of MapStruct. If you set `maven.compiler.showWarnings=true` and / or upgrade to a newer version of the maven-compiler-plugin e.g. 3.13.0 or 3.12.1. The default for the warnings was changed from `false` to `true` in 3.11 (https://issues.apache.org/jira/browse/MCOMPILER-457).

**Comment by bkalas** [comment]
ah true, simply update to 3.13.0 was enough. Thanks
