### ISSUE TITLE
Trigger FileNotFoundException When I delete the interface

### ISSUE THREAD

**Issue by Yangqi0338** [mapstruct/mapstruct#3559]
### Expected behavior

Springboot Service can run

### Actual behavior

Springboot Service build is success but can‘t run，FileNotFoundException error will be reported

### Steps to reproduce the problem
![image](https://github.com/mapstruct/mapstruct/assets/25914993/b22d00a0-6180-4707-9924-4f4134d786f3)

After compilation, an implementation class will be generated under the corresponding interface's package with the same name。
![image](https://github.com/mapstruct/mapstruct/assets/25914993/a8269d6d-bd7b-4b8a-81ba-e7a52fb9a726)

generated-resources are also generated。
![image](https://github.com/mapstruct/mapstruct/assets/25914993/770d3512-4f20-4390-840d-cb33ba6add51)

now，I'm delete the source interface，this compiled class was not deleted together。
![image](https://github.com/mapstruct/mapstruct/assets/25914993/0e5d3d1a-2647-4db3-97b1-01e0f37adbf9)

then run the springboot service，will tell me：FileNotFoundException。
This situation will be alleviated after I delete the target package。
Similarly, switching the git branch (This is the main reason, which can cause colleagues who do not know how to use MapStruct to start the service and report errors)

### MapStruct Version

MapStruct 1.5.5.Final， MapStruct 1.6.0.Beta1

**Comment by Yangqi0338** [comment]
Perhaps this is a compatibility issue with Springboot，I‘m using the springboot version is 1.5.10.RELAASE。very older

**Comment by filiphr** [comment]
MapStruct is an annotation processor, this error has nothing to do with Spring Boot. The IDE that you are using should be able to detect that the implementation was created by a class that no longer exists and remove it. Therefore, I am going to close this
