### ISSUE TITLE
Allow use of conditions on `@SubclassMapping`

### ISSUE THREAD

**Issue by gigena-git** [mapstruct/mapstruct#3572]
### Use case

I'd be good that `@SubclassMapping` could allow both `conditionQualifiedBy` and `conditionQualifiedByName`. The conditions would have to accept the assigned subclass:

```java
@Mapper
public interface ParentMapper  {

  @Override
  @SubclassMapping(source = ChildOne.class, target = Target.class, conditionQualifiedBy = ConditionOne.class)
  @SubclassMapping(source = ChildTwo.class, target = Target.class, conditionQualifiedBy = ConditionTwo.class)
  @SubclassMapping(source = ChildThree.class, target = Target.class, conditionQualifiedBy = ConditionThree.class)
  Target map(Parent parent);

  Target mapOne(ChildOne childOne);

  Target mapTwo(ChildTwo childTwo);

  Target mapThree(ChildThree childThree);

  @ConditionOne
  default boolean testOne(ChildOne childOne) {
    // Check something
  }

  @ConditionTwoe
  default boolean testTwo(ChildTwo childTwo) {
    // Check something
  }

  @ConditionThree
  default boolean testThree(ChildThree childThree) {
    // Check something
  }
}
```
The mappings can come from other mappers using `qualifiedBy` or `qualifiedByName`.

### Generated Code

The end result should be something like this:

```java
@Override
public Target map(Parent parent) {
    if ( parent == null ) {
        return null;
    }

    if (parent instanceof ChildOne && testOne((ChildOne) parent)) {
        return mapOne( (ChildOne) parent );
    }
    else if (parent instanceof ChildTwo && testTwo((ChildTwo) parent)) {
        return mapTwo( (ChildTwo) parent );
    }
    else if (parent instanceof ChildThree && testThree((ChildThree) parent)) {
        return mapThree( (ChildThree) parent );
    }
    else {
        throw new IllegalArgumentException("Not all subclasses are supported for this mapping. Missing for " + parent.getClass());
    }
}
```

And if the Java version is 17 or higher, do this:
```java
@Override
public Target map(Parent parent) {
    if ( parent == null ) {
        return null;
    }

    if (parent instanceof ChildOne childOne && testOne( childOne)) {
        return mapOne( childOne );
    }
    else if (parent instanceof ChildTwo childTwo && testTwo( childTwo ) {
        return mapTwo( childTwo );
    }
    else if (parent instanceof ChildThree childThree && testThree( childThree ) {
        return mapThree( childThree );
    }
    else {
        throw new IllegalArgumentException("Not all subclasses are supported for this mapping. Missing for " + parent.getClass());
    }
}
```

### Possible workarounds

Currently the mapper I'm using in production looks like this:

```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)  // There are configs that retrieve mapperOne and mapperTwo
public class MapperService implements Function<Source, Target> {

  @Override
  public Target apply(@NonNull Source source) {
    if (source instanceof SourceChildOne) {
      if (((SourceChildOne) source).getProperty().equals("Value")) {
        return mapperOne.map((SourceChildOne) source); // This returns TargetChildOne
      } else {
        throw new IllegalArgumentException("Wrong class: " + source.getClass());
      }
    } else if (source instanceof SourceChildTwo) {
      if (((SourceChildTwo) source).getOtherPriority().equals("Another Value")) {
        return mapperTwo.map((SourceChildTwo) source); // This returns TargetChildTwo
      } else {
        throw new IllegalArgumentException("Wrong class: " + source.getClass());
      }
    } else if...{
      // The are several cases like this, maintaining this code will get harder
      //if Source and Target get new subclasses.
    } else {
      throw new IllegalArgumentException("Wrong class: " + source.getClass());
    }
  }
}
```
The mapper is used by other `@Service` classes to convert from `Source` to `Target` without having to worry about what subclass of `Source` is being sent, and what subclass of `Target` is being received.

The improvement I'm working on right now leverages `@SubclassMapping`, that has already solved how to determine the right `Source` and `Target` subclasses.
```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public class MapperService implements Function<Source, Target> {

  @Override
  @SubclassMapping(source = SourceChildOne.class, target = TargetChildOne.class)
  @SubclassMapping(source = SourceChildTwo.class, target = TargetChildTwo.class)
  // More mappings here.
  Target apply(Parent parent);
}
```
which generates this code:
```java
@Component
public class MapperServiceImpl implements MapperService {
    @Override
    public Target apply(Source source) {
        if ( source == null ) {
            return null;
        }

        if (source instanceof SourceChildOne) {
            return mapperOne.map( (SourceChildOne) source );
        }
        else if (source instanceof SourceChildTwo) {
            return mapperTwo.map( (SourceChildTwo) source );
        }
        // More else ifs here.
        else {
          throw new IllegalArgumentException("Not all subclasses are supported for this mapping. Missing for " + parent.getClass());
        }
    }
}
```
This looks a lot like what I want, but I still cannot add the extra checks programmatically. The approach I suggest in the "Use Case" section would solve the issue.

Other approaches I've thought of, but didn't work were:

- Subclassing `Source` even more so that each condition is represent by a new subclass of `Source`. However by doing this I would be introducing knowledge of `Target` into the service that is emitting the subclass of `Source`.
- Not using the `MapperService` at all and use each of the mappers directly. However by doing this I would need to create a reference to each mapper in the object that gets `Source` from the emitting service and that then sends `Target` to the receiving service. With that many mappers, this solution adds a lot of extra code - precisely defeating the purpose using Mapstruct. 

### MapStruct Version

1.6.0.Beta1

**Comment by filiphr** [comment]
I think that this would be tricky to achieve. I would suggest using the workaround you shared would work without an issue. You can even do something like what the expected generated code looks like.

```java
@Mapper
public abstract class ParentMapper  {

  @Override
  public Target map(Parent parent) {
    if ( parent == null ) {
        return null;
    }

    if (parent instanceof ChildOne childOne && testOne( childOne)) {
        return mapOne( childOne );
    }
    else if (parent instanceof ChildTwo childTwo && testTwo( childTwo ) {
        return mapTwo( childTwo );
    }
    else if (parent instanceof ChildThree childThree && testThree( childThree ) {
        return mapThree( childThree );
    }
    else {
        throw new IllegalArgumentException("Not all subclasses are supported for this mapping. Missing for " + parent.getClass());
    }
  }

  protected abstract Target mapOne(ChildOne childOne);

  protected abstract Target mapTwo(ChildTwo childTwo);

  protected abstract Target mapThree(ChildThree childThree);

  protected boolean testOne(ChildOne childOne) {
    // Check something
  }

  protected boolean testTwo(ChildTwo childTwo) {
    // Check something
  }

  protected boolean testThree(ChildThree childThree) {
    // Check something
  }
}
```

Using this approach you can still use `ParentMapper` in other mappers and the public method would be picked up to map all instances of `Parent` to `Target`

You are saying that maintaining your code would get harder. However, you'll still need to provide additional `@SubclassMapping` for this to work properly when you add new classes, right?

**Comment by gigena-git** [comment]
Ok. In the end we decided to go with finer subclassing, being careful not to leak client info into the server side.

So, the best option would be to:

1. Use vanilla Mapstruct to create individual mappers between each of the concrete subclasses (i.e `SourceASubclassOne` to `TargetBSubclassThree`). The `componentModel` will be `default`.
2. Use Mapstruct Spring Extensions to define the mapper/converter that contains the mapper between the parent (abstract) classes (i.e `SourceA` to `TargetB`). This would be the mapper that would contain the `@SubclassMapping` annotation. It would also contain an `uses` clause with only the mappers that relate to the subclasses in question.
3. Get rid of the root mapper class (and its massive `uses` clause) and just use `ConversionServiceAdapter`. This makes sense, as it's component model is `spring`.

**Comment by filiphr** [comment]
Thanks for the explanation @gigena-git. I'll go ahead and close this issue for now. In case there is more interest from the community about this, we can go ahead and reopen it and see if there is something that we can do
