### ISSUE TITLE
Specified mapper is ignored

### ISSUE THREAD

**Issue by twallmey** [mapstruct/mapstruct#3573]
### Expected behavior

I've created an mapping (@Mapper) that references other mappers (uses = xy, ...). Unfortunately these referenced mappers are ignored and the generated code doese not use them. Instead an individual mapping is genereated.

The following mapping is defined:
```java
@Mapper(uses = {
        SymptomMapperV1V2.class,
        FaultcodeMapperV1V2.class,
        SkillLevelMapperV1V2.class,
        SolutionMapperV1V2.class,
        ApplianceTypeMapperV1V2.class,
        ApplianceFeatureMapperV1V2.class
})
public interface ApplianceToProductV1V2Mapper {
    @Mapping(source = "applianceType", target = "productType")
    public ProductV2 convert(ApplianceV1 applianceV1);

    @Mapping(source = "productType", target = "applianceType")
    public ApplianceV1 inverseConvert(ProductV2 productV2);
}
```
Although these mappers are explicitely named they are completely ignored. If you take a look at the conversion between attributes ApplianceTypeV1 and ApplianceTypeV2 you can see that a custom mapping was generated instead of using the dedicated mapper:

```java
protected ApplianceTypeV2 applianceTypeV1ToApplianceTypeV2(ApplianceTypeV1 applianceTypeV1) {
        if ( applianceTypeV1 == null ) {
            return null;
        }
        ApplianceTypeV2 applianceTypeV2 = new ApplianceTypeV2();

        applianceTypeV2.setType( applianceTypeV1.getType() );
        applianceTypeV2.setId( applianceTypeV1.getId() );
        applianceTypeV2.setFaultcodes( faultcodeV1CollectionToFaultcodeV2Collection( applianceTypeV1.getFaultcodes() ) );
        applianceTypeV2.setApplianceFeatures( applianceFeatureV1CollectionToApplianceFeatureV2Collection( applianceTypeV1.getApplianceFeatures() ) );
        applianceTypeV2.setCompatibilities( applianceTypeCompatibilityV1CollectionToApplianceTypeCompatibilityV2Collection( applianceTypeV1.getCompatibilities() ) );
        applianceTypeV2.setProductgroups( productGroupV1CollectionToProductGroupV2Collection( applianceTypeV1.getProductgroups() ) );
        applianceTypeV2.setSymptoms( symptomV1CollectionToSymptomV2Collection( applianceTypeV1.getSymptoms() ) );
        applianceTypeV2.setSolutions( solutionV1CollectionToSolutionV2Collection( applianceTypeV1.getSolutions() ) );
        Collection<Long> collection6 = applianceTypeV1.getMaterialnumbers();
        if ( collection6 != null ) {
            applianceTypeV2.setMaterialnumbers( new ArrayList<Long>( collection6 ) );
        }
        applianceTypeV2.setLabel( applianceTypeV1.getLabel() );
        applianceTypeV2.setModificationDate( applianceTypeV1.getModificationDate() );
        applianceTypeV2.setComment( applianceTypeV1.getComment() );
        applianceTypeV2.setDescription( applianceTypeV1.getDescription() );
        Set<URI> set = applianceTypeV1.getInferredTypes();
        if ( set != null ) {
            applianceTypeV2.setInferredTypes( new LinkedHashSet<URI>( set ) );
        }

        return applianceTypeV2;
    }
```

Can you tell me what's wrong? What do I have to do in order to make Mapstruct consider the dedicated mappers?

### Actual behavior

Mapstruct should use the dedicated/named mappers instead of generation a default mapping for selected attributes.

### Steps to reproduce the problem

```java
@MapperConfig(
        componentModel = "spring"
)
public interface MapstructConfig {
}
```

### MapStruct Version

1.5.5.Final

**Comment by thunderhook** [comment]
Hi @twallmey!

Please provide the code of `ApplianceTypeMapperV1V2`, `ProductV2` and `ApplianceV1`. It's hard to tell without that code.

Thanks in advance.

**Comment by twallmey** [comment]
Hi @thunderhook !
Thanks a lot for your response. I've attachted the requested code. Pls. let me know if need further information - the code is just a short extract of the complete mapping definitions that are defined...

[code-extract.zip](https://github.com/mapstruct/mapstruct/files/15033421/code-extract.zip)

**Comment by thunderhook** [comment]
@twallmey 
I have had a look at it. I can't reproduce the problem with just those 4 files (I have to create too many stubs that don't lead to the problem you describe), but I think I've seen what might be a problem.

Your main mapping method does not use the `@Context` variable...
```java
public ProductV2 convert(ApplianceV1 applianceV1);
```

...while the mapper you are using has it in its method signature:
```java
@Mapping(source = "applianceType", target = "productType")
public ProductV2 convert(ApplianceV1 applianceV1, @Context CycleAvoidingMappingContext context);
```

MapStruct is looking for the exact same signature because it needs to call this method with this context parameter. 

Could you try adding it to your main mapping method like this and see if it works?
```java
public ProductV2 convert(ApplianceV1 applianceV1, @Context CycleAvoidingMappingContext context);
```

Otherwise, please provide a short minimal reproducal that we can have a look at.
Thanks in advance.

**Comment by twallmey** [comment]
Thanks a lot for your hint! This was indeed the problem - everything works as expected now.
