### ISSUE TITLE
Nested Mappings suddenly stop with return null

### ISSUE THREAD

**Issue by Zegveld** [mapstruct/mapstruct#3575]
### Situation description
I'm using mapstruct to handle conversions from an older version of a datastructure to a newer version.
Example of changes that happen for me:
Old data structure:
```
A
- AA
- AB
  - ABA
    - ABAA
      - ABAAA
    - ABAB
    - ABAC
  - ABB
    - ABBA
    - ABBB
- AC
```
New data structure:
```
A
- AA
  - ABAA
    - ABAAA
  - ABBB
- AB
  - ABA
    - ABAB
  - ABB
    - ABBA
- AC
  - ABAC
```

### Expected behavior

Now I've defined a single mapping tree to handle all the movements:
```
@Mapping(source = "AB.ABA.ABAA", target = "AA.ABAA")
@Mapping(source = "AB.ABA.ABAC", target = "AC.ABAC")
old.package.A mapA(new.package.A source);
```

Expected is that mapstruct continues with mapping of the code. In 1.5.5 this was also the case.
```
void abaaToAbaa(new.package.ABAA source, old.package.ABAA mappingTarget) {
  if (source == null) {
    return;
  }
  mappingTarget.setABAAA(source.getABAAA());
}
```

### Actual behavior

This results in the following code being generated:
```
void abaaToAbaa(new.package.ABAA source, old.package.ABAA mappingTarget) {
  if (source == null) {
    return;
  }
}
```

### Steps to reproduce the problem

To be added once reproduced in mapstruct code base itself.

### MapStruct Version

Mapstruct 1.6.0.Beta1

**Comment by Zegveld** [comment]
Running into problem that I'm not able to get it reproduceable within the mapstruct code-base IT's. Think I'll go debug the workings in the private codebase to figure out why it goes wrong, and then use this knowledge to create a reproduction scenario.

**Comment by Zegveld** [comment]
After some more analysis, the cause was a `ignoreByDefault=true` which was present on the top level bean mapping. This caused all the forged methods from that mapping to inherit it.

Closing this issue as invalid, but we might need to discuss how we want `ignoreByDefault` to behave....

**Comment by alantanlc** [comment]
@Zegveld I am facing a similar issue where the nested object fields are not being mapped. Possible to reopen this issue?

### Expected Behaviour

@Mapping(source = "src.name", target = "name")
B aToB(A src);

```
B aToB(A src) {
  if (src == null) {
    return;
  }
  
  B tarB = new B();
  tarB.setName( src.getName() );

  return tarB;
}
```

### Actual Behaviour

```
B aToB(A src) {
  if (src == null) {
    return;
  }
  
  B tarB = new B();
  // missing tarB.setName( src.getName() );

  return tarB;
}
```

**Comment by thunderhook** [comment]
@alantanlc Could you please provide a reproducible example? I tried to create one with your snippet, but wasn't able to reproduce this.

A simple code that runs in a single java file would be nice, like this (which is not working right now):

```java
@Mapper
interface Issue3575Mapper {

    @Mapping(source = "a.b.c.d1", target = "name")
    D2 aToD2(A a);

}

class A {
    public B b;
}

class B {
    public C c;
}

class C {
    public D1 d1;
}

class D1 {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

class D2 {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

This currently fails with `Can't map property "D1 a.b.c.d1" to "String name". Consider to declare/implement a mapping method: "String map(D1 value)".`

**Comment by Zegveld** [comment]
> @Zegveld I am facing a similar issue on 1.6.0.Beta1 where the deeply nested object fields are not being mapped. Possible to reopen this issue?

Not reopening this issue, see #3577 for the discussion about behaviour of ignoreByDefault combined with (nested) mappings.
See also [the release notes of 1.6.0.Beta1](https://github.com/mapstruct/mapstruct/releases/tag/1.6.0.Beta1).
