### ISSUE TITLE
When @InheritConfiguration and qualifiedByName are used at the same time, it will be invalid when the field names are inconsistent.

### ISSUE THREAD

**Issue by rofemen** [mapstruct/mapstruct#3584]
### Expected behavior

Under normal circumstances, this targetWillBeIgnore field will be assigned normally
It will only be invalid when @InheritConfiguratio is used together with qualifiedByName and the field names of source and target are different. It will be effective when the name of target is willBeIgnore.

Code snippets have been provided below.

### Steps to reproduce the problem

    @Data
    static public class RestSiteDto{
        long willBeIgnore;
    }
    @Data
    static public class SiteDto{
        long targetWillBeIgnore;
        String tenantId;
        String qualifiedField;
    }
    @MapperConfig
    public interface RestConfig {
        @Mapping(target = "tenantId", source = "tenantId")
        @Mapping(target = "targetWillBeIgnore", source = "source.willBeIgnore")
        SiteDto convert(RestSiteDto source, String tenantId);
    }

    @Mapper(config = RestConfig.class)
    public interface RestSiteMapper {
        @InheritConfiguration
        @Mapping(target = "qualifiedField", source = "source", qualifiedByName = "defaultQualifiedField")
        SiteDto convert(RestSiteDto source, String tenantId);

        @Named("defaultQualifiedField")
        default public String defaultQualifiedField(RestSiteDto source){
            //do something
            return "";
        }
    }

·------------------------The following is the code generated after compilation-------------------------------------------

//targetWillBeIgnore This field will be ignored

    public SiteDto convert(RestSiteDto source, String tenantId) {
        if ( source == null && tenantId == null ) {
            return null;
        }

        SiteDto siteDto = new OrderExternalConverter.SiteDto();

        siteDto.setQualifiedField( defaultQualifiedField( source ) );
        siteDto.setTenantId( tenantId );

        return siteDto;
    }

### MapStruct Version

org.mapstruct:mapstruct:1.5.2.Final

**Comment by zyberzebra** [comment]
I recreated your example.
It works on the latest main branch/version.
https://github.com/zyberzebra/mapstruct/commit/70652c868245436895131dbde50d8132f9179622

**Comment by filiphr** [comment]
Thanks for trying this out @zyberzebra. @rofemen this is actually the same as #3361, which has been fixed in 1.6.0.Beta1. Can you please try with that version?

-----
@zyberzebra just FYI, you can always look into `target/compilation-tests/<test FQN>/...` to see the code that MapStruct generated. This looks like:

```java
public class RestSiteMapperImpl implements RestSiteMapper {

    @Override
    public SiteDto convert(RestSiteDto source, String tenantId) {
        if ( source == null && tenantId == null ) {
            return null;
        }

        SiteDto siteDto = new SiteDto();

        if ( source != null ) {
            siteDto.setQualifiedField( defaultQualifiedField( source ) );
            siteDto.setTargetWillBeIgnore( source.getWillBeIgnore() );
        }
        siteDto.setTenantId( tenantId );

        return siteDto;
    }
}
```

**Comment by zyberzebra** [comment]
> you can always look into target/compilation-tests/<test FQN>/... to see the code that MapStruct generated.

You got a trick that IntelliJ picks it up as implementation, for easier navigation?

**Comment by filiphr** [comment]
>You got a trick that IntelliJ picks it up as implementation, for easier navigation?

Not really, there are a lot of tests and we also generate twice the same, once for Eclipse and once for javac. Perhaps there is a way, but I haven't tried it

**Comment by thunderhook** [comment]
What i do: It's not perfect, but definitely better than my first approach in using the windows file explorer:
* `Project View > Three Dots > Tree Appearance > Show Excluded Files`
* Then you see the `target` directories inside IntelliJ and can faster navigate to the compiled code

When you want to debug inside a generated Mapping code you can (it's quite cumbersome) by marking **one** specific directory as Test Sources Root (adding it to the main directory `compilation-tests` does not work because the implementations are generated twice (and therefore lead to duplicate class compile errors):
![grafik](https://github.com/mapstruct/mapstruct/assets/8238759/75a8cafe-ad70-4fd5-9748-49179a241fc3)

**Comment by zyberzebra** [comment]
Thanks for sharing your workflow! :)

> does not work because the implementations are generated twice

Could we possibly switch the "double" generation off somehow? when experimenting

**Comment by thunderhook** [comment]
> Could we possibly switch the "double" generation off somehow? when experimenting

You could comment out the following line, that should do the trick:
https://github.com/mapstruct/mapstruct/blob/5bbd1a78ea67442cf8024fdcef7c9dff4356408d/processor/src/test/java/org/mapstruct/ap/testutil/ProcessorTest.java#L48

**Comment by zyberzebra** [comment]
> You could comment out one of the following lines, that should do the trick:
![image](https://github.com/mapstruct/mapstruct/assets/73640367/68a4ec56-6e18-47fb-9ef5-b429546c1d1d)
Works great! Thanks :)
