### ISSUE TITLE
@BeanMapping(ignoreByDefault = true) Implicit mapping error

### ISSUE THREAD

**Issue by baojunz** [mapstruct/mapstruct#3603]
### Expected behavior

Hello, I encountered the following issues while using BeanMapping.

At first, my version was 1.5.5. Final

When multiple objects are nested in my source class, the target also nested multiple objects. After using @ BeanMapping (ignoreByDefault=true), the explicit field processing did not follow my expectations.

I have reviewed historical issues and based on https://github.com/mapstruct/mapstruct/issues/3577

So I upgraded the version to 1.6.0.Beta1, which is great. Solved my problem. But then I encountered other problems, which I think may have been caused by new issues during the bug fixing process. The specific issues are as follows:

I created two different mapping methods in my mapping, with the first method labeled @ BeanMapping (ignoreByDefault=true) for explicit mapping. In the second method, I want to use mapstruct's own implicit mapping. But when I looked at the compiled file, I found that. The mapping method was not generated as scheduled. This requires me to manually redo it.

### Steps to reproduce the problem

<img width="1444" alt="image" src="https://github.com/mapstruct/mapstruct/assets/48702961/4f2af1d1-7f69-48c6-af34-39230b5150b6">

![image](https://github.com/mapstruct/mapstruct/assets/48702961/73579191-50d8-408d-a86a-242923214277)

<img width="1204" alt="image" src="https://github.com/mapstruct/mapstruct/assets/48702961/f2959dd9-e188-4b6c-a139-9046b30c3a65">

### MapStruct Version

1.6.0.Beta1

**Comment by baojunz** [comment]
When I switched to 1.6.0.Beta2, it still didn't solve my problem. I feel that the @ BeanMapping (ignoreByDefault=true) annotation is effective globally, not for the annotated mapping method

**Comment by thunderhook** [comment]
Hi @baojunz 

would you be so kind and provide a simple reproducer in a single Java file in text form? Typing the code from a screenshot is no fun.

Thanks in advance!

**Comment by filiphr** [comment]
This might be similar to #3591.
