### ISSUE TITLE
Reduce configuration code for after method

### ISSUE THREAD

**Issue by bmaehr** [mapstruct/mapstruct#3606]
### Use case

Would it be possible to support this syntax for after method:

```java
public abstract BookDto fromEntity(Bookentity);

@AfterMapping(mappedTargets = ["property1", "property2", "property3"])
protected void fromEntityCustom(final Book entity, @MappingTarget final BookDto dto) {
   ...
}
```

to reduce the code

### Possible workarounds

```java
@Mapping(target = "property1", ignore = true)
@Mapping(target = "property2", ignore = true)
@Mapping(target = "property3", ignore = true)
public abstract BookDto fromEntity(Book entity);

@AfterMapping
protected void fromEntityCustom(final Book entity, @MappingTarget final BookDto dto) {
  ...
}
```

### MapStruct Version

1.5.5

**Comment by thunderhook** [comment]
We also used `@AfterMapping` a lot in our codebase to do some custom mapping. However, `@AfterMapping` was not really designed for this.

What I would suggest is using custom, qualified mapping methods like this:

```java
@Mapping(target = "property1", source = "property1", qualifiedByName = "mapEntityProperty1")
public abstract void updateEntity(BookDto dto, @MappingTarget Book entity);

@Named("mapEntityProperty1")
protected String mapEntityProperty1(final String property1) {
    return Util.calculate(property1);
}
```

**Comment by bmaehr** [comment]
Yes, that is an other option but what is not working there is this: #3607

**Comment by filiphr** [comment]
I'm going to close this as this is not something that `@AfterMapping` was meant for. You can provide custom mapping methods using qualifiers, or you can do something like what is proposed in #3539 once that is in.

@thunderhook you can reduce your `@Mapping` to `@Mapping(target = "property1", qualifiedByName = "mapEntityProperty1")`. When source and target are identical, the source can be skipped
