### ISSUE TITLE
Support update-style method for qualifyByName

### ISSUE THREAD

**Issue by bmaehr** [mapstruct/mapstruct#3607]
### Use case

It would be nice to suppert this syntax
```java
@Mapping(target = "property1", qualifiedByName = "updateEntityProperty1") 
public abstract void updateEntity(BookDto dto, @MappingTarget Book entity);

protected void updateEntityProperty1(final BookDto dto, @MappingTarget final Book entity) {
    if (resource.getProperty1() != null) {
        entity.setProperty1(Util.calculate(resource.getProperty1()));
    }
}
```

### Possible workarounds

```java
@Mapping(target = "property1", ignore = true)
public abstract void updateEntity(BookDto dto, @MappingTarget Book entity);

@AfterMapping
protected void updateEntityCustom(final BookDto dto, @MappingTarget final Book entity) {
    if (resource.getProperty1() != null) {
        entity.setProperty1(Util.calculate(resource.getProperty1()));
    }
}
```

### MapStruct Version

1.5.5

**Comment by charles-alves** [comment]
Hi @bmaehr, you should try something like this

```java
@Mapping(target = "property1", qualifiedByName = "updateEntityProperty1") 
public abstract void updateEntity(BookDto dto, @MappingTarget Book entity);

@Named(updateEntityProperty1)
protected String updateEntityProperty1(final BookDto dto, @MappingTarget final Book entity) {
    if (resource.getProperty1() != null) {
        return Util.calculate(resource.getProperty1())
    }
    return null;
}
```

**Comment by bmaehr** [comment]
> Hi @bmaehr, you should try something like this
> 
> ```java
> @Mapping(target = "property1", qualifiedByName = "updateEntityProperty1") 
> public abstract void updateEntity(BookDto dto, @MappingTarget Book entity);
> 
> @Named("updateEntityProperty1")
> protected String updateEntityProperty1(final BookDto dto, @MappingTarget final Book entity) {
>     if (resource.getProperty1() != null) {
>         return Util.calculate(resource.getProperty1())
>     }
>     return null;
> }
> ```

That was my suggestion (and additionally make the Named optional) but it is currently not possible.

**Comment by filiphr** [comment]
@bmaehr I'm not sure what you are trying to achieve.

If I do:

```java
@Mapper
public interface BookMapper {

    @Mapping(target = "property1", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE, qualifiedByName = "updateEntityProperty1")
    void update(BookDto dto, @MappingTarget Book book);

    @Named("updateEntityProperty1")
    default String customProperty1(String property1) {
        return property1;
    }
}
```

Then in my generated code I would have:

```java
        if ( dto.getProperty1() != null ) {
            book.setProperty1( customProperty1( dto.getProperty1() ) );
        }
```

I think that the syntax you are using for the update is incorrect. With the `qualifiedByName` you need to provide a method that is going to perform the mapping from one to another property. And then for the source null check you need to use `NullValuePropertyMappingStrategy`. You can use this strategy on `@Mapping`, `@BeanMapping`, `@Mapper` and `@MapperConfig`.

Closing this, since this is already possible
