### ISSUE TITLE
Compiler argument mapstruct.defaultComponentModel seems to break Spring Batch's Bean detection

### ISSUE THREAD

**Issue by Sax388** [mapstruct/mapstruct#3608]
### Expected behavior

I expected the gradle configuration
```gradle
dependencies {
  implementation "org.mapstruct:mapstruct:1.5.5.Final"
  implementation "org.projectlombok:lombok:1.18.32"
  annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"
  annotationProcessor "org.mapstruct:mapstruct-processor:1.5.5.Final"
  annotationProcessor 'org.projectlombok:lombok:1.18.32'
}

compileJava {
  options.compilerArgs = [
          '-Amapstruct.defaultComponentModel=spring'
  ]
}
```
to set `componentModel = "spring"` in all my `@Mapper` annotations.

### Actual behavior

Instead I've got errors like this
```java
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException:
No qualifying bean of type 'org.springframework.batch.core.Job' available:
expected single matching bean but found 5:
```

### Steps to reproduce the problem

I've got a Spring Batch configuration with multiple jobs. Without the compiler argument everything works but with it the Spring Bean detection for Spring Batch seems to go haywire.

I even had left the `@Mapper(componentModel = "spring")` in my annotations.

### MapStruct Version

1.5.5

**Comment by Sax388** [comment]
I also mentioned this issue on the Spring Batch discussion board: https://github.com/spring-projects/spring-batch/discussions/4596.

**Comment by filiphr** [comment]
The only possible explanation why this could happen is if you have somewhere `@Mapper(uses = Job.class)`. 

Please provide a minimal reproducible repository if you want us to look into this.

**Comment by Sax388** [comment]
Unfortunately I currently don't have the time to provide one. I removed the compiler flag and added the component model in the annotations and everything worked fine. I'm going to close this issue in favor of more relevant ones coming up.
