### ISSUE TITLE
@SubclassMapping not working with @BeanMapping.ignoreUnmappedSourceProperties

### ISSUE THREAD

**Issue by pemu69** [mapstruct/mapstruct#3609]
### Expected behavior

`@BeanMapping.ignoreUnmappedSourceProperties` should not be ignored.

### Actual behavior

I want to use `@SubclassMapping` and `@BeanMapping.ignoreUnmappedSourceProperties` on the same mapping method. The `@BeanMapping.ignoreUnmappedSourceProperties` seems to be ignored. If I remove the  `@SubclassMapping` annotations the error (Unmapped source property: "id") disappears.

### Steps to reproduce the problem

```java
class Vehicle {
    public int price;
}

class Car extends Vehicle {
    public int seats;
}

class Truck extends Vehicle {
    public int capacity;
}

class VehicleDto {
    public int id;
    public int price;
}

class CarDto extends VehicleDto {
    public int seats;
}

class TruckDto extends VehicleDto {
    public int capacity;
}

@MapperConfig(
    unmappedSourcePolicy = ReportingPolicy.ERROR,
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION
)
class Config {
}
@Mapper(config = Config.class)
public abstract class VehicleMapper {

    @SubclassMapping(source = CarDto.class, target = Car.class)
    @SubclassMapping(source = TruckDto.class, target = Truck.class)
    @BeanMapping(ignoreUnmappedSourceProperties = { "id" })
    public abstract Vehicle toVehicle(VehicleDto vehicle);

    @InheritInverseConfiguration
    @Mapping(target = "id", ignore = true)
    public abstract VehicleDto toVehicleDto(Vehicle vehicle);
}

```

### MapStruct Version

1.5.5

**Comment by filiphr** [comment]
Have you tried with 1.6.0.Beta2?

**Comment by pemu69** [comment]
I tried with 1.6.0.Beta2 and the same error occurs, the error message is now more verbose: Unmapped source property: "id". Mapping from SubclassMapping for ch.postfinance.dlam.mapstruct.CarDto "CarDto carDto" to "Car car"

**Comment by Obolrom** [comment]
@filiphr I can try to solve this issue

**Comment by filiphr** [comment]
Yes sure @Obolrom. I'll assign it to you. If you have some questions, feel free to reach out.
