### ISSUE TITLE
Mapstruct doesn't follow JavaBean naming convention

### ISSUE THREAD

**Issue by holomekc** [mapstruct/mapstruct#3610]
### Expected behavior

I am aware that this issue was raised already:
#3230
#3408

But currently Mapstruct does not follow the naming conventions. The expected behavior would be:
Explanation: https://stackoverflow.com/questions/2948083/naming-convention-for-getters-setters-in-java
Spec snippet:
> ... However to support the occasional use of all
upper-case names, we check if the first two characters of the name are both upper case and if
so leave it alone.

```java
public class Shape {
  private String xValue;


  public void setxValue(final String xValue) {
     this.xValue = xValue;
  }

  public String getxValue() {
    return this.xValue;
  }
}
```

Expectation is that mapstruct recognizes the getter and setter properly.

### Actual behavior

At the moment this creates issues with other libraries, which follow this naming convention. E.g. Swagger (OpenApi) generation:
swagger-api/swagger-codegen/issues/445

or Jackson, where our models need to follow the guideline to prevent duplicate properties:
fasterxml/jackson-databind/issues/653

Our generated (OpenApi) entities and our own entities follow the convention, but we need to define additional mappings like this, which should not be necessary:

```java
@Mapping(target = "setxValue", source = "xValue")
```

Edit: Small addition. Sometimes it is a bit strange. If the target is a java record with a param called xValue and a source class with a getter getxValue(), then it works fine and no additional mapping annotation is necessary.

### Steps to reproduce the problem

-

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment]
I'm not sure that I am fully following where the issue is.

From the explanation I can see that we are following the Java Bean spec for the source. It would be extremely strange to me why we wouldn't do the same for the target. Is `Shape` the class you have for the mapping or your class looks different?

Is it possible that you have a builder for the target?

**Comment by filiphr** [comment]
You can see our logic for this in
 https://github.com/mapstruct/mapstruct/blob/main/processor%2Fsrc%2Fmain%2Fjava%2Forg%2Fmapstruct%2Fap%2Fspi%2FDefaultAccessorNamingStrategy.java#L171-L191

When using a fluent setter (i.e. a builder) we are not following the Bean spec fully.

e.g.

`Builder settlementDate(...)` vs `Builder setSettlementDate(...)`. In those both cases the property name is `settlementDate`. If we followed the bean spec, then the first property name would be `tlementDate` which would be incorrect.

Therefore if your setter look like `Builder setxValue(...)` the property name would be `setxValue`

**Comment by holomekc** [comment]
Hi @filiphr ,

thx for the incredible quick answer. Sorry I should have provided a better example:

Source:
```java
public record InternalShape(String xValue, String somethingElse) {}
```

Target:
```java
public class Shape {
  private xValue;
  private somethingElse;

  public Shape setxValue(final String xValue) {
    this.xValue = xValue;
  }

  public String getxValue() {
    return this.xValue;
  }

  public Shape setSomethingElse(final String somethingElse) {
    this.somethingElse = somethingElse;
  }

  public String getSomethingElse() {
    return this.somethingElse;
  }
}
```

Mapper:
```java
@Mapper
public interface SomeMapper {
  
  @Mapping(target = "setxValue", source = "xValue")
  Shape toExternal(final InternalShape shape);
}
```

So mapstruct recognizes the setter for setSomethingElse, but does not recognize the setter for setxValue. Therefore, we need to define target = "setxValue". 

Regarding what you wrote the reason is the builder pattern we use? I did not check the code yet. I will do that later. But only for properties with a single lowercase char at the beginning. My brain was confused at the beginning, because for setSomethingElse it is working fine and for setxValue it is not. 

Does this mean if the setter signature would be: ```public void setxValue(final String xValue)``` it would work without an additional annotation?

Thx again
Br,
Chris

**Comment by filiphr** [comment]
Thanks for the classes.

Your setter goes in the fluent setter / builder setter and that's why we don't recognize it.

>Does this mean if the setter signature would be: `public void setxValue(final String xValue)` it would work without an additional annotation?

It would indeed work. In that case we follow the Bean spec fully.

**Comment by holomekc** [comment]
Hmm. I think it is generated code, which I cannot really change.

Is there a reason why the spec is not fully supported in this case?

**Comment by filiphr** [comment]
I don't think that the method is according to the Bean spec as well. I think the bean spec requires the setters to have a return type void. 

From section 8.3.1

>By default, we use design patterns to locate properties by looking for methods of the form: 
>
> public <PropertyType> get<PropertyName>(); 
>public void set<PropertyName>(<PropertyType> a);

We have special logic for fluent setters in order to be able to support builder setters.

e.g.

`Builder settlementDate(...)` vs `Builder setSettlementDate(...)`. In those both cases the property name is `settlementDate`. If we followed the bean spec, then the first property name would be `tlementDate` which would be incorrect.

I don't think that this is something that we can change

**Comment by holomekc** [comment]
Hi @filiphr 
I see. Thank you for all the information. We will check what we can do on our end.
