### ISSUE TITLE
Not mapping field with start at "add"

### ISSUE THREAD

**Issue by vyatich** [mapstruct/mapstruct#3625]
### Expected behavior

all fields mapping correctly

### Actual behavior

I use mapstruct (version 1.5.3.Final) with spring, and create implementation by spring like this
`@Mapper(componentModel = "spring")`

my dependecies
`implementation("org.mapstruct:mapstruct:1.5.3.Final")`
`implementation("org.mapstruct:mapstruct-processor:1.5.3.Final")`

My Dto and DtoObject object have field 
`private String addInfo;`
and builder genrated by lombok version 1.18.32

but when I use method

`Dto toDto(DtoObject object)`

implementation created without mapping this field

If i directly use method annotation
`@Mappint(source = "addInfo", target = "addInfo")`
I get exception on compile time with a message about the absence of a method in the builder on target class
I saw generated decompiled class and it have builder method

### Steps to reproduce the problem

just create 2 object with filed addInfo and try to mapping there

### MapStruct Version

1.5.3.Final

**Comment by thunderhook** [comment]
Hi @vyatich 

Thanks for reaching out to us.

This is a known issue when using the builder pattern in combination with a field starting with `add`.

Have a look at
* https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-895572151
* https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-898872064.

Closing this issue now. If someone has an idea for how this can be solved please let us know.

As a workaround you can either:
* disable the builder for the mapper via `@Mapper(builder = @Builder(disableBuilder = true))`
* extend the builder and add a `setAddInfo(...)` method
* ignore the field and use a decorator mapping as proposed in https://github.com/mapstruct/mapstruct/issues/2533#issuecomment-1787349075
