### ISSUE TITLE
Add locale parameter for numberFormat

### ISSUE THREAD

**Issue by Slava96** [mapstruct/mapstruct#3628]
### Use case

When mapping from BigDecimal / double to String type (maybe like a number with 2 digits after separator), then it choose separator with honor to default program locale.
So, the results is incosistent. On my computer i have a locale with "ru/RU" and it choose ',' as separator, but on remote tests with locale "en/US" it chooses '.'

### Generated Code

Add a locale parameter with conjuction to numberFormat

### Possible workarounds

Workaround - have a separate util method with manually created DecimalFormat.

### MapStruct Version

MapStruct 1.5.5.Final

**Comment by filiphr** [comment]
This is a valid request @Slava96. We are busy with other issues, if you are interested in something like this I would suggest raising a PR for it.

**Comment by Obolrom** [comment]
@Slava96 @filiphr 
I have implemented the additional logic for a locale parameter.
If the param is not specified then the default locale will be used.

e.g. `@Mapping( target = "bigDecimal1", numberFormat = "#0.#E0", locale = "en/US" )`

Feel free to conduct a code review #3693
