### ISSUE TITLE
Support for completing the conversion in the constructor

### ISSUE THREAD

**Issue by codeleep** [mapstruct/mapstruct#3633]
For example I am using springboot related framework. I would create an Aform. 
  1. When passing to the Service, it needs to be inserted into the database and it needs to be converted to AEntiy. 
  2. When the front end queries, I will convert AEntiy to AVo.
It is certainly achievable using mapstruct current approach. But I want to have a whole new way of doing this without creating a Mapper interface.

Below I will describe my idea：

Suppose I have the following three java beans

```java

/**
** AForm
**/
public class AForm {
    private String name;
    private Long age;
}

/**
** AEntiy
**/
public class AEntiy {
    private String name;
    private Long age;
}

/**
** AVo
**/
public class AEntiy {
    private String name;
    private Long age;
}
```

I hope they can want to change between the conversion. Then I manually add the corresponding pair constructor

```java
/**
** AForm
**/
public class AForm {
    private String name;
    private Long age;
  
    public AForm(AEntiy aEntiy) {
        if (aEntiy == null) {
            return;
        }
        this.setName(aEntiy.getName());
        this.setAge(aEntiy.getAge());
    }
  
    public AForm(AVo aVo) {
        if (aVo == null) {
            return;
        }
        this.setName(aVo.getName());
        this.setAge(aVo.getAge());
    }
}

/**
** AEntiy
**/
public class AEntiy {
    private String name;
    private Long age;
  
   public AEntiy(AForm aForm) {
        if (aForm == null) {
            return;
        }
        this.setName(aForm.getName());
        this.setAge(aForm.getAge());
    }
  
    public AEntiy(AVo aVo) {
        if (aVo == null) {
            return;
        }
        this.setName(aVo.getName());
        this.setAge(aVo.getAge());
    }
}

/**
** AVo
**/
public class AVo {
    private String name;
    private Long age;
  
    public AVo(AForm aForm) {
        if (aForm == null) {
            return;
        }
        this.setName(aForm.getName());
        this.setAge(aForm.getAge());
    }
  
    public AVo(AEntiy aEntiy) {
        if (aEntiy == null) {
            return;
        }
        this.setName(aEntiy.getName());
        this.setAge(aEntiy.getAge());
    }
}
```

As you can see, when I create different constructors, I can use the new keyword to create corresponding data. But if I write this code manually it makes it very clunky.

Therefore, I hope that the corresponding annotation can be added and the corresponding code can be automatically generated. Such:

```java
/**
** AForm
**/
@BeanMappingConstructor({ AEntiy.class , AVo.class})
public class AForm {
    private String name;
    private Long age;
}

/**
** AEntiy
**/
@BeanMappingConstructor({ AForm.class , AVo.class})
public class AEntiy {
    private String name;
    private Long age;
}

/**
** AVo
**/
@BeanMappingConstructor({ AEntiy.class , AForm.class})
public class AVo {
    private String name;
    private Long age;
}
```

Of course, I just provided an idea to simplify the conversion. As for more details, I haven't considered them yet.

**Comment by filiphr** [comment]
I'm not sure that this is something that we are interested in doing. You can create your own annotation processor that is going to create MapStruct mappers and then the MapStruct annotation processor is going to generate the mapping code.

If for some reason you are actually looking for MapStruct to generate the constructors, then this is something that is not supported by the Annotation Processor API, that's something in the realm of Lombok and using internal non supported APIs from the java compiler
