### ISSUE TITLE
Remove the deprecation note of mapping an enum via `@Mapping` in Javadoc and the reference guide

### ISSUE THREAD

**Issue by thunderhook** [mapstruct/mapstruct#3638]
In march 2016 the enum mapping via `@Mapping` was deprecated, see https://github.com/sjaakd/mapstruct/commit/42d428d35fb17ca6898abca083007486dc30d48a. I found no follow-up issue to remove it.

This issue is about removing the capability and the hint inside of javadoc and the reference guide (see Section 8.1)

**Comment by filiphr** [comment]
Are you sure that this is not already done? Have you tried using it?

If you try to use then there is a compile error. We did something in https://github.com/mapstruct/mapstruct/commit/7bee12138da5f601364987d053e4fd3eeb43cbcd

**Comment by thunderhook** [comment]
I actually didn't try it. I will do that later. If it is already removed, then I will change the issue to just clean up the Javadoc and reference guide.

**Comment by filiphr** [comment]
Cleaning up the Javadoc and reference guide sounds goo do me. Perhaps we can even do it for the final 1.6

**Comment by thunderhook** [comment]
Yes, it was already removed in the commit you mentioned. I cleaned up the deprecation marks.
