### ISSUE TITLE
Not using builder lombok by default 

### ISSUE THREAD

**Issue by ateixivi14** [mapstruct/mapstruct#3646]
### Expected behavior

Mapstruct should use by default Lombok Builder, but instead is using constructor
I have this dependencies 
```
	implementation("org.mapstruct:mapstruct:1.5.5.Final}")
	annotationProcessor("org.mapstruct:mapstruct-processor:1.5.5.Final")
	compileOnly("org.projectlombok:lombok")
	annotationProcessor("org.projectlombok:lombok") 
```
I tried some diferent things as adding 
1. ```configurations {
	compileOnly {
		extendsFrom(configurations.annotationProcessor.get())
	}}```
2.` tasks.compileJava {
	options.compilerArgs.add("-Amapstruct.disableBuilders=false")
}`
3. `@Mapper(componentModel = "spring", builder = @Builder(disableBuilder = false))`

but still happens.
Is something missing? I have another project with exact same configuration and uses builder
```@Override
    public Vehicle vehicleEntityToVehicleModel(VehicleEntity vehicleEntity) {
        if ( vehicleEntity == null ) {
            return null;
        }

        Vehicle.VehicleBuilder vehicle = Vehicle.builder();
        ...
}`

### Actual behavior

```
    @Override
    public Vehicle vehicleEntityToVehicleModel(VehicleEntity vehicleEntity) {
        if ( vehicleEntity == null ) {
            return null;
        }

        Vehicle vehicle = new Vehicle();

        return vehicle;
    }
```

### Steps to reproduce the problem

 The error I'm having: error: constructor VehicleEntity in class VehicleEntity cannot be applied to given types;
        VehicleEntity vehicleEntity = new VehicleEntity();
`./gradlew clean build`

### MapStruct Version

1.5.5.Final

**Comment by thunderhook** [comment]
Have a look at the [gradle section of the reference guide](https://mapstruct.org/documentation/stable/reference/html/#_set_up). You're missing the `lombok-mapstruct-binding` dependency.
