### ISSUE TITLE
Map Java Map to Protobuf map Problem

### ISSUE THREAD

**Issue by Cestbo** [mapstruct/mapstruct#3647]
### Use case

hello，as follows, universalItemInfo's ext_info is Protobuf map，i want to convert a map object to a protobuf map object，but the generated code ‘universalItemInfo.getExtInfoMap().putAll( map )’ don‘t work，it causes UnsupportedOperationException. Can generate `universalItemInfo.putAllExtInfo()`  for the protobuf map?
`map<string, string> ext_info = 11;`

```
if ( universalItemInfo.getExtInfoMap() != null ) {
            Map<String, String> map = itemSelectInfo.getExtInfo();
            if ( map != null ) {
                universalItemInfo.getExtInfoMap().putAll( map );
            }
        }
```

### Generated Code

universalItemInfo.putAllExtInfo()

**Comment by moryxsw** [comment]
you can see this: https://github.com/mapstruct/mapstruct/issues/1655

**Comment by filiphr** [comment]
Thanks @y9domains. Closing this issues as everything has been explained in #1655. @Cestbo if something is not clear please let us know.
