### ISSUE TITLE
Mapping from class with non-JavaBean style getters

### ISSUE THREAD

**Issue by scottmore** [mapstruct/mapstruct#365]
Original discussion on mapstruct-users: 
https://groups.google.com/forum/#!topic/mapstruct-users/bURGk6CS4fk

There are cases where I need to map from Java classes that don't follow the getFoo() method JavaBeans naming convention, instead consistently lobbing off the "get" part.  For example, I need to automatically map from the following class to a class with matching "setName(String)" setter without having to define mappings explicitly (i.e via configuration annotation or similar).

```
public class SourceClass {

    private String name;

    public SourceClass() {
    }

    public String name() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

One idea is to introduce an interface to map from getter method to property name, then have an optional argument on the configure annotation to specify a class implementing that interface.  The mapper could map method names in source class to property names (JavaBeans: getName -> name, My example: name -> name).  Hopefully that would play nice with the @Mapper annotations and allows for a very similar SetterTransform to map from property name to any bizarre setter method convention in the target class.

something like this:

    public interface GetterTransform {
       
        /**
         * Transform method receives all method names in source class of
         * no-argument, non-void return type methods and returns property
         * name or null if method is not to be mapped
         *
         * @param methodName Name of potential getter method in source class
         * @return Expected property name in target class or null to skip
         */
        public String transform(String methodName);
    }

A JavaBeans-compliant class transform would look something like this:
   
    public class JavaBeansTransform implements GetterTransform {

        public String transform(String methodName) {
            if (!methodName.startsWith("get") || methodName.length() <= 3) {
                return null;
            }
           
            // Lob off get and lowercase next character
            return String.format("%s%s",
                    methodName.substring(3, 4).toLowerCase(),
                    methodName.substring(4));
        }
    }

   
For classes like the SourceClass example above the transform would look like this:

    public class CustomTransform implements GetterTransform {
       
        public String transform(String methodName) {
            return methodName;
        }
    }

Gunnar Morling's reply:

>One minor issue I see with the proposal of
```
    @Mapper(propertyNamer=MyTransformer.class)
```
>is that it requires a class which actually only would be needed for the generation (MyTransformer) to be visible to the application; javac has a separation of the compilation classpath and the "processor path" which contains the classes required by annotation processing. Not sure whether it's really a problem; One could work around it by e.g. specifying the FQN instead (we have a set of processor options already).

**Comment by chschu** [comment]
Ok, so I won't add a new attribute to ```@Mapper```. That makes sense, because we would need one for each and every customization point that might be added in the future.

Some kind of priority will be required then, because the default implementation will always be on the AP's class path.

Giving the implementation access to the currently processed mapper (e.g. via the TypeMirror for the mapper interface) make sense, but only if there is a way to delegate to the next/default implementation in case the current implementation does not handle a case. It feels like chaining could be a good idea here.

I'll give it a try.

**Comment by gunnarmorling** [comment]
+1 for making this configurable on a global level, e.g. via the service loader mechanism. I'd expect one project to apply the same property style throughout its code base.

> Some kind of priority will be required then, because the default implementation will always be on the AP's class path.

I would just raise an error in case more than one implementation is present. Our own default implementation wouldn't need to be retrieved via the service loader, so the service loader would only be used to discover custom implementations.

> Giving the implementation access to the currently processed mapper (e.g. via the TypeMirror for the mapper interface) make sense

Is this really needed? Wouldn't just the method name suffice as suggested originally? I'd like to avoid exposure of TypeMirror et al. as they can be quite awkward to work with.

> It feels like chaining could be a good idea here

Interesting; Would one really make use of this? E.g. fall back to another property style? Would be nice to see some actual use case for this. I'm not strictly against it, just wondering.

> I'll give it a try.

Cool; Many thanks for working on this, @chschu!

**Comment by chschu** [comment]
The delegation+priority thing only makes sense if the implementation has access to the current mapper type. The implementation could then check if it is responsible (like Andreas put it: check for annotation ```@NeedsMyAwesomeNamingStrategy```), and either return something itself, or delegate to the next implementation.

The "single custom implementation" approach is a lot easier to implement, because it doesn't affect any existing method signatures.

@agudian Flexibility vs. simplicity. What do you think?

**Comment by agudian** [comment]
> @agudian Flexibility vs. simplicity. What do you think?

Both would be great! :wink: But when in doubt, we should choose the simplest approach that fits the current requirements. So I would try to avoid delegation and priorities, and keep the interface simple. Preferrably with only one method.

Wouldn't it be possible to just return ```null``` in case the custom implementation likes to abstain?

We could also think about handing in a sort of ```MappingContext``` object that can hold additional information about the mapper being mapped. It would be an interface with maybe some getters for useful information and perhaps methods like ```isMethodAnnotatedWith(Class<A extends Annotation>)``` and ```isMapperAnnotatedWith(..)```. 
We would hand in an implementation (not part of the public API) of that interface, able to answer all these questions. I'm sure in time we might find out what other information might be useful and then we can just extend that interface without having to change the callback method signature itself.

WDYT?

**Comment by gunnarmorling** [comment]
@chschu How is it going with this issue? Anything I can help with? As @agudian has been saying, let's go for the most simplest thing getting the job done. Let's fight complexity from the beginning :)

**Comment by chschu** [comment]
Sorry, been quite busy recently. Commit ef124bd is as simple as it gets, but doesn't provide much flexibility. As long as the naming conventions are consistent within a project (or within an AP execution) this should suffice.

Regarding @agudian 's proposals:

Returning ```null``` to delegate to the default implementation seems a bit "magic" to me, and it requires an additional wrapper implementation that handles the ```null``` case. I'd prefer a more explicit approach, e.g. "injecting" the default implementation using a designated method of the ```AccessorNamingStrategy```.

The ```MappingContext``` seems like a good idea. What would be the best way to pass it around, so it is available when the ```AccessorNamingStrategy``` is invoked?

**Comment by chschu** [comment]
An integration test would be nice here, but that means that we need to run `mvn install` during the integration tests. The SPI implementation needs to be build in a separate artifact, which is then specified as a dependency of the AP plugin.

**Comment by agudian** [comment]
Just merged your fix. Great team effort! :grinning:

**Comment by gunnarmorling** [comment]
Yes, absolutely. Great to see this one in!

**Comment by metalpalo** [comment]
Hi
is possible to use different AccessorNamingStrategy only for one method in mapper?

thanks
