### ISSUE TITLE
Inverse Inheritance Strategy not working for ignored mappings only with target

### ISSUE THREAD

**Issue by zyberzebra** [mapstruct/mapstruct#3652]
### Expected behavior

Inverse Configuration is autmatically generated.

### Actual behavior

`@Mappings` have to be defined twice

### Setup
```java
@Mapper(config = FooBarConfig.class)
public interface FooBarMapper {

    Bar toBar(Foo foo);

    Foo toFoo(Bar bar);

}
@Data
class Foo { int secret; }
@Data
class Bar { int secret; }

@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG)
interface FooBarConfig {

    @Mapping(target = "secret", ignore = true)
    Bar toBar(Foo foo);

    @InheritInverseConfiguration(name = "toBar")
    Foo toFoo(Bar bar);
}
``` 

### Generated

```java
public class FooBarMapperImpl implements FooBarMapper {

    @Override
    public Bar toBar(Foo foo) {
        if ( foo == null ) {
            return null;
        }

        Bar bar = new Bar();

        return bar;
    }

    @Override
    public Foo toFoo(Bar bar) {
        if ( bar == null ) {
            return null;
        }

        Foo foo = new Foo();

        foo.setSecret( bar.getSecret() );

        return foo;
    }
}
``` 
### Only way to get it working
```java
@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG)
interface FooBarConfig {
    @Mapping(target = "secret", ignore = true)
    Bar toBar(Foo foo);
    @Mapping(target = "secret", ignore = true)
    Foo toFoo(Bar bar);
}
``` 

### MapStruct Version

1.5.5

**Comment by filiphr** [comment]
Thanks @zyberzebra, this indeed looks like a bug.

Does it work if you use:

```java
@Mapping(target = "secret", source = "target", ignore = true)
```1

**Comment by Hypnagokali** [comment]
Hi @zyberzebra, @filiphr

Is anyone already working on this issue?

I had a look at it and found the method `MappingOptions#canInverse`:
```java
public boolean canInverse() {
        return constant == null && javaExpression == null && !( isIgnored && sourceName == null );
}
```
Ignore mappings without a sourceName are excluded from the inverse configuration, but I don't know what the reason might be.

However, it does not seem to be problem to simply omit the last condition:
```java
public boolean canInverse() {
        return constant == null && javaExpression == null;
}
```
After this change the inverse configuration works for ignore mappings without source and all tests are green. Other (non-ignore) mappings without a sourceName have already worked before.

If no one can think of a reason for this condition, I could provide a pull request with a test.

**Comment by filiphr** [comment]
Good catch @Hypnagokali. Not sure why we have that condition. If no tests fail, then perhaps we can remove it, but not sure. We'll need to have a test case where the target does not exist in the source and use inverse.

Feel free to provide a PR, we'll look into it once you do

**Comment by StefanLobbenmeierObjego** [comment]
Funnily enough our code actually relied on this behaviour that this ignore only goes one way - we had a snippet roughly like this:

```java
    @Mapping(target = "creationDate", ignore = true) // NOTE: Handled by JPA.
    Entity toEntity(Model model);    

	@InheritInverseConfiguration
    Model toModel(Entity entity);
```

We added creationDate to the model as well and the mapping from jpa to model was working with 1.6.0 and broke with 1.6.2.

It is however easy to restore previous behaviour / override the new default like this:

```java
    @Mapping(target = "creationDate", ignore = true) // NOTE: Handled by JPA.
    Entity toEntity(Model model);    

	@InheritInverseConfiguration
    @Mapping(target = "creationDate", source = "creationDate") // Allow reading from Entity
    Model toModel(Entity entity);
```

(just to be clear - I prefer the new default to the previous one, just sharing in case other people run into this)

Relevant xkcd: https://xkcd.com/1172/

**Comment by DerKanzler** [comment]
Yeah, that's definitely a breaking change. 😞
We heavily relied on that "feature".

Any chance to revert it back?
I have to ask because otherwise we will have to add the explicit mapping like @StefanLobbenmeierObjego mentioned.

**Comment by filiphr** [comment]
Thanks for sharing this @StefanLobbenmeierObjego. I've added the information to the release notes.

@DerKanzler I think that the xkcd (https://xkcd.com/1172/) that @StefanLobbenmeierObjego shared here matches this perfectly. The fact that the ignore was only being inherited when using `@InheritConfiguration`, but not when using `@InheritInverseConfiguration` is a bit misleading and not something that is really expected I would say. I think adding the explicit mapping is the right approach for this.
