### ISSUE TITLE
@Mapping(defaulExpression=) does not work for classes with Collections which elements have a custom mapping function (with lombok builders)

### ISSUE THREAD

**Issue by kurellajunior** [mapstruct/mapstruct#3653]
### Expected behavior

Given:
- a class with lombok @Builder generated Builder as target class with @Builder.Default on an attribute that is initialized with an empty listwith a type, that needs transformation itself
- Source object with this attribute set to null
- `@Mapping(target:"attribute", defaultExpression:"java(new java.util.ArrayList<>())"`

Expected
Code that in either way respects the default List if the source attribute is `null`

### Actual behavior

the sub mapping returns null instead of default value.

### Steps to reproduce the problem

- ItemMapper.java
```java
import lombok.*;
import org.mapstruct.*;
import java.util.ArrayList;
import java.util.List;

@Data
class Itemclass {
    int one;
    String other = "text";
}

@Data
class Source {
    List<Itemclass> items1;
    List<Itemclass> items2;
}


@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class TargetItem {
    int two;
    String specific;
}

@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class Target {
    @lombok.Builder.Default
    List<TargetItem> items1 = new ArrayList<>();
    @lombok.Builder.Default
    List<TargetItem> items2 = new ArrayList<>();
}

@Mapper(
        unmappedSourcePolicy = ReportingPolicy.ERROR,
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        typeConversionPolicy = ReportingPolicy.ERROR,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR
)

public abstract class ItemMapper {

    @Mapping(target = "specific", source = "other")
    @Mapping(target = "two", source = "one")
    public abstract TargetItem mapItem(Itemclass item);

    @Mapping(target = "items1", defaultExpression = "java(List.of())")
    @Mapping(target = "items2", defaultExpression = "java(List.of())")
    public abstract Target mapItems(Source source);
}
```
- ItemMapperImpl.java
```java

import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-08-06T10:32:16+0200",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 21.0.4 (Ubuntu)"
)
public class ItemMapperImpl extends ItemMapper {

    @Override
    public TargetItem mapItem(Itemclass item) {
        if ( item == null ) {
            return null;
        }

        TargetItem.TargetItemBuilder targetItem = TargetItem.builder();

        targetItem.specific( item.getOther() );
        targetItem.two( item.getOne() );

        return targetItem.build();
    }

    @Override
    public Target mapItems(Source source) {
        if ( source == null ) {
            return null;
        }

        Target.TargetBuilder target = Target.builder();

        target.items1( itemclassListToTargetItemList( source.getItems1() ) );
        target.items2( itemclassListToTargetItemList( source.getItems2() ) );

        return target.build();
    }

    protected List<TargetItem> itemclassListToTargetItemList(List<Itemclass> list) {
        if ( list == null ) {
            return null;
        }

        List<TargetItem> list1 = new ArrayList<TargetItem>( list.size() );
        for ( Itemclass itemclass : list ) {
            list1.add( mapItem( itemclass ) );
        }

        return list1;
    }
}
```
### MapStruct Version

```xml
    <properties>
      <lombok.version>1.18.32</lombok.version>
      <org.mapstruct.version>1.5.5.Final</org.mapstruct.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by zyberzebra** [comment]
I can't reproduce the Error on my machine.
![image](https://github.com/user-attachments/assets/826fe64a-1253-43ef-83d4-4d115e46309a)
### The generated Mapper:
```java
public class ItemMapperImpl extends ItemMapper {

    @Override
    public Target mapItems(Source source) {
        if ( source == null ) {
            return null;
        }
        Target.TargetBuilder target = Target.builder();
        return target.build();
    }
}
``` 
### The lombok Builder
```java
private static List<String> $default$items() {
        return new ArrayList<>();
    }

public Target build() {
            List<String> items$value = this.items$value;
            if (!this.items$set) {
                items$value = Target.$default$items();
            }
            return new Target(items$value);
        }
```

**Comment by kurellajunior** [comment]
@zyberzebra, you are ignoring the `items` attribute. This of course works. I do want to take the items-attribute from source to target if not null.
I forgot to set the apporpriate line in my example above, will add:
```java
    @Mapping(target = "items", defaultExpression = "java(List.of())")
```

**Comment by kurellajunior** [comment]
@thunderhook, indeed, this configuration was not set (but everything worked still) But even with this setting, the generated mapstruct classes do not contain any sign of `java.util.List.of()` Which I would expect to be somewhere there…

My complete configuration:
```xml
    <properties>
      <lombok.version>1.18.32</lombok.version>
      <org.mapstruct.version>1.5.5.Final</org.mapstruct.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by Srimathi-S** [comment]
@kurellajunior I tried replicating your issue,

 Without doing it the way @zyberzebra did that is without the below code
` @Mapping(target = "items", ignore = true)`
I was getting an exception saying  
`Unmapped target property: "items"`

and with your code line 
`@Mapping(target = "items", defaultExpression = "java(List.of())")`
I am getting below exception
`The type of parameter "source" has no property named "items". Please define the source property explicitly.`

I think you need a getter for the source items to be copied to the target item. If you change the code to the following by adding getters:


```
@Getter
class Source {
    List<String> items;
}
```

or by making items public

```
class Source {
  public List<String> items;
}
```
you will get your expected behaviour.

**Comment by zyberzebra** [comment]
@kurellajunior @Srimathi-S 
Isn't that what you are expecting?
### Generated Mapper
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-08-05T21:36:53+0200",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 21.0.2 (Azul Systems, Inc.)"
)
public class ItemMapperImpl extends ItemMapper {

    @Override
    public Target mapItems(Source source) {
        if ( source == null ) {
            return null;
        }

        Target.TargetBuilder target = Target.builder();

        List<String> list = source.getItems();
        if ( list != null ) {
            target.items( new ArrayList<String>( list ) );
        }
        else {
            target.items( List.of() );
        }

        return target.build();
    }
}

``` 
### Reproduce
```java
@Data
class Source {
    List<String> items;
}
@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class Target {
    @lombok.Builder.Default
    List<String> items = new ArrayList<>();
}
@Mapper(
        unmappedSourcePolicy = ReportingPolicy.ERROR,
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        typeConversionPolicy = ReportingPolicy.ERROR,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR
)
public abstract class ItemMapper {
    @Mapping(target = "items", defaultExpression = "java(List.of())")
    public abstract Target mapItems(Source source);
}
```

**Comment by Srimathi-S** [comment]
@zyberzebra I am not facing this issue. I was checking with @kurellajunior to see what his expectations are as with getters the issue seems to be sorted. Also not sure how something is getting generated without any exception in the first place without data or getter annotation. So asked him to share his implementation

**Comment by kurellajunior** [comment]
@zyberzebra This is exactly, what I would expect, however, my generated code does not contain this if-switch. It might have to do with the fact, that the type of the list has its own mapper function autogenerated. I will try to recreate the effect in isolated form (the code above was written free-hand)

> ```java
> @Generated(
>     value = "org.mapstruct.ap.MappingProcessor",
>     date = "2024-08-05T21:36:53+0200",
>     comments = "version: 1.5.5.Final, compiler: javac, environment: Java 21.0.2 (Azul Systems, Inc.)"
> )
> public class ItemMapperImpl extends ItemMapper {
> 
>     @Override
>     public Target mapItems(Source source) {
>         if ( source == null ) {
>             return null;
>         }
> 
>         Target.TargetBuilder target = Target.builder();
> 
>         List<String> list = source.getItems();
>         if ( list != null ) {
>             target.items( new ArrayList<String>( list ) );
>         }
>         else {
>             target.items( List.of() );
>         }
> 
>         return target.build();
>     }
> }
> ```

**Comment by kurellajunior** [comment]
I finally got a minimal working example thanks to your input (will also update original post for clarity)
### ItemMapper.java
```java
import lombok.*;
import org.mapstruct.*;
import java.util.ArrayList;
import java.util.List;

@Data
class Itemclass {
    int one;
    String other = "text";
}

@Data
class Source {
    List<Itemclass> items1;
    List<Itemclass> items2;
}


@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class TargetItem {
    int two;
    String specific;
}

@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class Target {
    @lombok.Builder.Default
    List<TargetItem> items1 = new ArrayList<>();
    @lombok.Builder.Default
    List<TargetItem> items2 = new ArrayList<>();
}

@Mapper(
        unmappedSourcePolicy = ReportingPolicy.ERROR,
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        typeConversionPolicy = ReportingPolicy.ERROR,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR
)

public abstract class ItemMapper {

    @Mapping(target = "specific", source = "other")
    @Mapping(target = "two", source = "one")
    public abstract TargetItem mapItem(Itemclass item);

    @Mapping(target = "items1", defaultExpression = "java(List.of())")
    @Mapping(target = "items2", defaultExpression = "java(List.of())")
    public abstract Target mapItems(Source source);
}
```

### ItemMapperImpl.java
```java

import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-08-06T10:32:16+0200",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 21.0.4 (Ubuntu)"
)
public class ItemMapperImpl extends ItemMapper {

    @Override
    public TargetItem mapItem(Itemclass item) {
        if ( item == null ) {
            return null;
        }

        TargetItem.TargetItemBuilder targetItem = TargetItem.builder();

        targetItem.specific( item.getOther() );
        targetItem.two( item.getOne() );

        return targetItem.build();
    }

    @Override
    public Target mapItems(Source source) {
        if ( source == null ) {
            return null;
        }

        Target.TargetBuilder target = Target.builder();

        target.items1( itemclassListToTargetItemList( source.getItems1() ) );
        target.items2( itemclassListToTargetItemList( source.getItems2() ) );

        return target.build();
    }

    protected List<TargetItem> itemclassListToTargetItemList(List<Itemclass> list) {
        if ( list == null ) {
            return null;
        }

        List<TargetItem> list1 = new ArrayList<TargetItem>( list.size() );
        for ( Itemclass itemclass : list ) {
            list1.add( mapItem( itemclass ) );
        }

        return list1;
    }
}
```

As you can see, the inner generated method `itemclassListToTargetItemList` does not respect the expression value but simply returns `null` instead of `List.of()`

**Comment by Srimathi-S** [comment]
@kurellajunior add nullValueCheckStrategy and set it to always. Use the below `ItemMapper`

```
public abstract class ItemMapper {

    @Mapping(target = "specific", source = "other")
    @Mapping(target = "two", source = "one")
    public abstract TargetItem mapItem(Itemclass item);

    @Mapping(target = "items1", defaultExpression = "java(List.of())", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
    @Mapping(target = "items2", defaultExpression = "java(List.of())", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
    public abstract Target mapItems(Source source);
}
```

Generated Implementation

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-08-06T22:04:53+0530",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 17.0.12 (Homebrew)"
)
public class ItemMapperImpl extends ItemMapper {

    @Override
    public TargetItem mapItem(Itemclass item) {
        if ( item == null ) {
            return null;
        }

        TargetItem.TargetItemBuilder targetItem = TargetItem.builder();

        targetItem.specific( item.getOther() );
        targetItem.two( item.getOne() );

        return targetItem.build();
    }

    @Override
    public Target mapItems(Source source) {
        if ( source == null ) {
            return null;
        }

        Target.TargetBuilder target = Target.builder();

        List<TargetItem> list = itemclassListToTargetItemList( source.getItems1() );
        if ( list != null ) {
            target.items1( list );
        }
        else {
            target.items1( List.of() );
        }
        List<TargetItem> list1 = itemclassListToTargetItemList( source.getItems2() );
        if ( list1 != null ) {
            target.items2( list1 );
        }
        else {
            target.items2( List.of() );
        }

        return target.build();
    }

    protected List<TargetItem> itemclassListToTargetItemList(List<Itemclass> list) {
        if ( list == null ) {
            return null;
        }

        List<TargetItem> list1 = new ArrayList<TargetItem>( list.size() );
        for ( Itemclass itemclass : list ) {
            list1.add( mapItem( itemclass ) );
        }

        return list1;
    }
}
```
By default it doesn't perform null check inside method unless there is implicit conversion which was why your default values didn't work. Hope this helps

**Comment by kurellajunior** [comment]
Cool, that works.
Still not really intuitive that the default from the builder is overwritten. If the names would not be different you would still need to define the function to set the null check strategy.

I would rather expect, that only for non-null values the builder functions are called to ensure the default-handling of the Lombok-Builder.

Now, the default needs to be defined in two places. In our Project with literally over 100 classes, all in bigger nested structures several level deep, this means overhead on each mapping interface (10 in total). If one updates the default behaviour they have to check all mappers and update them across the several modules… As I said unintuitive and error-prone.

Thanks for the help!

**Comment by zyberzebra** [comment]
@kurellajunior I agree with you, that  the explicit NullValueCheckStrategy should not be needed here.
The docs are also suggesting that it would work without.
`A defaultExpression String based on which the specified target property is to be set if and only if the specified source property is null.`

**Comment by filiphr** [comment]
>I would rather expect, that only for non-null values the builder functions are called to ensure the default-handling of the Lombok-Builder.


I'm not following that statement @kurellajunior. If you want to make sure that the setter / builder setter is invoked with non null values then the `NullValueCheckStrategy.ALWAYS` should be used. Otherwise, the defaults of MapStruct kick in, and the default is that no null check should be done in this case.

How is all of this linked with the `defaultExpression`? Sorry, there were a lot of comments and I'm not sure that I fully understand the issue.

**Comment by kurellajunior** [comment]
@filiphr : boiled down to two different points:

1. The whole mapping fails to respect lombok’s default strategies. So you would nee to always implement the defaults in two places which is really errorprone. This problem is visible here:
```java
import lombok.*;
import org.mapstruct.*;

import java.util.ArrayList;
import java.util.List;

@Data
class SimpleSourceItem {
    String text = "text";
}

@Data
class SimpleSource {
    List<SimpleSourceItem> items1;
    List<SimpleSourceItem> items2;
}


@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class SimpleTargetItem {
    String text;
}

@lombok.Builder
@NoArgsConstructor
@AllArgsConstructor
class SimpleTarget {
    @lombok.Builder.Default
    List<SimpleTargetItem> items1 = new ArrayList<>();
}

@Mapper()
public abstract class SimpleItemMapper {
    public abstract SimpleTarget mapItems(SimpleSource source);
}
```
I claim, that this should just work:
```java
new SimpleItemMapperImpl().mapItems(new SimpleSource()).items1 != null;
```
 Mapstruct really should call the respective builder function only if the value is not null thus let the user take control at the model definition level. I would rather explicitly set the Nullcheck to false to deactivate the default by lombok.


2. the term `defaultExpression` and its description implies, that if the incoming value is `null` this expression is used. Instead, if the incoming type is a list of a complex type that has its own mapping function generated, some inner magic which documentaiton was not obvious to me, ignored the default expression which need to be overwritten with `NullValueCheckStrategy`.

**Comment by filiphr** [comment]
1.  The way `null` source properties are explained in our documentation https://mapstruct.org/documentation/stable/reference/html/#checking-source-property-for-null-arguments. By default the `nullValueCheckStrategy` that we are using os `NullValueCheckStrategy.ON_IMPLICIT_CONVERSION`. From the docs you can see the following situations where we generate a null check

>* direct setting of source value to target value when target is primitive and source is not.
>* applying type conversion and then:
>    * calling the setter on the target.
>    * calling another type conversion and subsequently calling the setter on the target.
>    * calling a mapping method and subsequently calling the setter on the target.

So in order to achieve what you are looking for you need to use `@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)`

This will generate 

```java
        List<SimpleTargetItem> list = simpleSourceItemListToSimpleTargetItemList( source.getItems1() );
        if ( list != null ) {
            simpleTarget.setItems1( list );
        }
```

2. OK, I think that I understand now. I thought you wanted MapStruct not to do `simpleTarget.setItems1( simpleSourceItemListToSimpleTargetItemList( source.getItems1() ) );`. Lombok has nothing to do with what you are asking for.  You are right here, we need to always use the `defaultExpression`, which we do for non collections. We'll look into it. You can circumvent it (i.e. keep the defaults that are in the builder itself by using the `NullValueCheckStrategy.ALWAYS`)

>I would rather expect, that only for non-null values the builder functions are called to ensure the default-handling of the Lombok-Builder.

This was confusing me, it was implying that you want to use the defaults that are defined in the builder. I guess when you say builder you mean `@Mapping` and not the actual builder for the target class?

**Comment by filiphr** [comment]
I just tried out the shared example with 1.6.0 and it works as expected, without the use of `nullValueCheckStrategy`. @kurellajunior can you please check with 1.6.0 as well?

**Comment by kurellajunior** [comment]
@filiphr: yes indeed, the "defaulExpression" in now honored in 1.6.0. I still disagree with the other point, but will open another issue for this.
