### ISSUE TITLE
Mapping of object graphs leads to `NullPointerException`

### ISSUE THREAD

**Issue by Earlpride** [mapstruct/mapstruct#3657]
### Expected behavior

**I expected the code to run without any issues and the objects to be correctly mapped from their source type to the target type.**

I am using Mapstruct to map DTOs to entities and vice versa. Some of my DTO/entity classes contain associations to other DTO/entity classes, creating a self-referential object graph
(example based on my provided code: `blackDto1` -> `whiteDto1`. Any reference chain that requires _the same mapper to be invoked twice_ should lead to the issue I am describing).

### Actual behavior

**The mappings fail because the mappers throw a `NullPointerException`.**

When mappers are invoked to map objects with these ~cyclic~ references, they end up causing `NullPointerException`s.
Specifically, the first mapper to be invoked a second time will throw a `NullPointerException`.

# Stack Trace
```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "net.gray.connect.mapper.test.mapstruct.mapper.IBlackMapper.toEntity(net.gray.connect.mapper.test.mapstruct.dto.BlackDto)" because "this.iBlackMapper" is null
at net.gray.connect.mapper.test.mapstruct.mapper.IWhiteMapperImpl.toEntity(IWhiteMapperImpl.java:24)
at net.gray.connect.mapper.test.mapstruct.mapper.IBlackMapperImpl.toEntity(IBlackMapperImpl.java:24)
at net.gray.connect.mapper.test.mapstruct._MainTest.main(BlackWhite.java:37)
```

### Steps to reproduce the problem

1. Run the code in [this repository](https://github.com/Earlpride/BlackWhiteMapping).

# My Environment
* JDK: Eclipse Temurin `21.0.4`
* Build tool: Gradle
* Mapstruct: `1.6.0RC1` (problem was also observed in `1.5.5.Final`)

## My Mapstruct configuration
```java
compileJava {
	//Configuration options: https://mapstruct.org/documentation/1.6/reference/html/#configuration-options
	options.compilerArgs += [
	        '-Amapstruct.defaultComponentModel=default',
		'-Amapstruct.defaultInjectionStrategy=constructor',
		'-Amapstruct.disableBuilders=false',
		'-Amapstruct.suppressGeneratorTimestamp=false',
		'-Amapstruct.suppressGeneratorVersionInfoComment=false',
		'-Amapstruct.unmappedSourcePolicy=WARN',
		'-Amapstruct.unmappedTargetPolicy=WARN',
		'-Amapstruct.verbose=true'
    ]
}
```

### MapStruct Version

1.6.0RC1

**Comment by Obolrom** [comment]
@filiphr , can I try to fix this issue?

**Comment by filiphr** [comment]
I'm not sure that you can fix this @Obolrom. We do not support cyclic mappers when using the default component model. If cyclic dependency is needed between mappers then one of the other component models should be used.

**Comment by Earlpride** [comment]
> I'm not sure that you can fix this @Obolrom. We do not support cyclic mappers when using the default component model. If cyclic dependency is needed between mappers then one of the other component models should be used.

Sorry, after looking up the definition for the term "cyclic", I have realized that what I am describing is not cyclic behavior. 

The problem arises with the following reference chain: `blackDto1` -> `whiteDto1`, as described in the issue.

**Comment by filiphr** [comment]
@Earlpride you do have a cycle between the mappers.

In your repo you have 

```java
@Mapper(uses = IBlackMapper.class)
public interface IWhiteMapper {
	IWhiteMapper INSTANCE = Mappers.getMapper(IWhiteMapper.class);
	
	WhiteEntity toEntity(WhiteDto dto);
	
	WhiteDto toDto(WhiteEntity entity);
}
```

and

```java
@Mapper(uses = IWhiteMapper.class)
public interface IBlackMapper {
	IBlackMapper INSTANCE = Mappers.getMapper(IBlackMapper.class);
	
	BlackEntity toEntity(BlackDto dto);
	
	BlackDto toDto(BlackEntity entity);
}
```

The reason why it is `null` is because we did with #2277 which leads to the generated mappers to use `MyMapper.INSTANCE` instead of doing `Mappers.getMapper` when using the default implementation.

If you rename the `public static field` to something else. There will be a loop trying to create an instance of the mappers.

The problem is not in the mapping of object graphs, the problem is that you are using cyclic dependency between the mappers.

If you put all the mapping methods in one mapper or you use a different way to create an instance of your mapper. you won't have this issue.
