### ISSUE TITLE
POJO fields with Capital Letter "L" not getting mapped in the Impl class - Mapstruct 1.3

### ISSUE THREAD

**Issue by kc-karan** [mapstruct/mapstruct#3688]
### Expected behavior

```
public class PartnerDetails {
    private Long glCode;
    private String businessCategory;
    private String merchantCategoryCode;
}
```

```
 protected com.adapter.types.PartnerDetails partnerDetailsToPartnerDetails(PartnerDetails partnerDetails) {
        if ( partnerDetails == null ) {
            return null;
        }

        PartnerDetailsBuilder partnerDetails1 = com.adapter.types.PartnerDetails.builder();

        partnerDetails1.glCode( partnerDetails.getGlCode() );
        partnerDetails1.businessCategory( partnerDetails.getBusinessCategory() );
        partnerDetails1.merchantCategoryCode( partnerDetails.getMerchantCategoryCode() );

        return partnerDetails1.build();
    }

```

### Actual behavior

```
public class PartnerDetails {
    private Long gLCode;
    private String businessCategory;
    private String merchantCategoryCode;
}
```

Implementation File Generated - 

```
protected com.adapter.types.PartnerDetails partnerDetailsToPartnerDetails(PartnerDetails partnerDetails) {
        if ( partnerDetails == null ) {
            return null;
        }

        PartnerDetailsBuilder partnerDetails1 = com.adapter.types.PartnerDetails.builder();

        partnerDetails1.businessCategory( partnerDetails.getBusinessCategory() );
        partnerDetails1.merchantCategoryCode( partnerDetails.getMerchantCategoryCode() );

        return partnerDetails1.build();
    }
```

### Steps to reproduce the problem

In any of the fields just use the capital letter L while naming a variable/field.

### MapStruct Version

Mapstruct 1.3

**Comment by Obolrom** [comment]
@kc-karan, have you tried the latest stable version of [mapstruct 1.6.0](https://github.com/mapstruct/mapstruct/releases/tag/1.6.0) ?

**Comment by filiphr** [comment]
@kc-karan this works as designed following the Java Bean spec.

The Spec defines that for a property with a second latter being upper case it's getter should have be `get<propertyName>` without upper casing the property name.

so in your case your property is `gLCode` which means that your getter should be `getgLCode`, the setter should be `setgLCode` or `gLCode`.

**Comment by kc-karan** [comment]
I'm using a builder pattern over my POJO, which doesn't let setters be defined for keeping POJO's immutable. Here is the complete POJO with Lombok annotations defined - 

```
@Value
@Builder
public class PartnerDetails {
    private String businessCategory;
    private Long merchantCategoryCode;
    private Long gMCode;
}
```

**Comment by filiphr** [comment]
If you are using the builder pattern then the builder setter should be the same name as the property. However, the getter has to satisfy the conditions I mentioned. If it doesn't, you'll need to adjust the `@Mapping`
