### ISSUE TITLE
Add "verbose" processor option to print out details if required

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#37]

**Comment by sjaakd** [comment]
see also #177 for more ideas.

**Comment by agudian** [comment]
At some point we talked about where to add that output, but I can't find it anymore.

I see two options:
* as comments in the generated java file, e.g. with a special handling of the templates (the template writer could check if such info is attached to the model and apply a special comment-template before)
* in a separate file to be placed somewhere (but where?)

**Comment by sjaakd** [comment]
solved by PR..

**Comment by filiphr** [comment]
Just for traceability. The PR that solved this is https://github.com/mapstruct/mapstruct/pull/1741
