### ISSUE TITLE
Compatibility with magic bean

### ISSUE THREAD

**Issue by bowbahdoe** [mapstruct/mapstruct#3710]
### Use case

I maintain this library https://github.com/bowbahdoe/magic-bean and I would like for there to be some way to have mapstruct know ahead of time that getters and setters will be generated in the same sense as for lombok.

If it could work as-is today that is cool - but I could use some pointers on how to do that if so.

**Comment by filiphr** [comment]
@bowbahdoe have you tried using MapStruct and your Magic Bean library?

Reading your review and based on the generated Bean Ops classes everything should work out-of-the-box.

**Comment by bowbahdoe** [comment]
I have and it has not worked. I can set up a reproducer, but I think the issue is that magic bean's processor doesn't necessarily run before mapstruct?

**Comment by filiphr** [comment]
>I have and it has not worked. I can set up a reproducer, but I think the issue is that magic bean's processor doesn't necessarily run before mapstruct?

Having an example project that we can look into will indeed help to understand why it isn't working. The fact that Magic Bean is another annotation processor means that ordering shouldn't matter. If MapStruct runs first, then the classes will not be resolved and MapStruct will postpone the generation for the next round.

The reason though why it might not work is due to the fact that Magic Bean is claiming all annotations as processed 

https://github.com/bowbahdoe/magic-bean/blob/680aec22106966c165052e8b433416575d3e1cd0/src/main/java/dev/mccue/magicbean/processor/AnnotationProcessor.java#L362C9-L362C21

If you return `true` there it means that all the annotations that were passed in the process method are claimed by your processor. So if MapStruct runs first (it will postpone to the next round), then Magic Bean comes in and says I've claimed all annotations, and then in the next round there will be no annotations to process and this MapStruct will not be invoked again

**Comment by bowbahdoe** [comment]
https://github.com/bowbahdoe/mapstruct-magicbean-repro

**Comment by bowbahdoe** [comment]
> If you return true there it means that all the annotations that were passed in the process method are claimed by your processor. So if MapStruct runs first (it will postpone to the next round), then Magic Bean comes in and says I've claimed all annotations, and then in the next round there will be no annotations to process and this MapStruct will not be invoked again

Play a bit with the repro, but say this is the issue. Are you saying i should always return false or is there some other scheme?

**Comment by filiphr** [comment]
Check what happens if you do `return false`.

In any case, what I would do is to also just copy the code that is generated by your processor and see if it works as if it was written by a user.

**Comment by bowbahdoe** [comment]
I will check that shortly. In the meantime i updated the reproducer to have `javac @compile_after_gen`. It does work if it was all written by a user.

**Comment by bowbahdoe** [comment]
Just changing to `return false` nets me some new errors

<img width="443" alt="image" src="https://github.com/user-attachments/assets/84642b43-683f-439e-a015-c7b16c03da0e">

**Comment by bowbahdoe** [comment]
Changing to `return false` does not fix the issue

**Comment by filiphr** [comment]
The fact that it does work as if it has been written by a user implies to me that something might be off in the magic bean processor.

I'll try to have a look at it tomorrow

**Comment by filiphr** [comment]
@bowbahdoe I think that this might be linked to some bug or limitation in the java compiler. 

The error I am getting when I do `javac @compile` with the `@Mapper` uncommented is

```java
gen/AppleBeanOps.java:4: error: incompatible types: AppleBeanOps cannot be converted to Apple
        return (switch (this) { case Apple __ -> __; });
                                     ^
1 error
```

When I add

```
-XprintProcessorInfo
-XprintRounds
```

then we can see

```
Round 1:
        input files: {Apple, AppleDTO, AppleMapper}
        annotations: [dev.mccue.magicbean.MagicBean, org.mapstruct.Mapper]
        last round: false
Processor org.mapstruct.ap.MappingProcessor matches [org.mapstruct/org.mapstruct.Mapper] and returns false.
Processor dev.mccue.magicbean.processor.AnnotationProcessor matches [dev.mccue.magicbean/dev.mccue.magicbean.MagicBean] and returns false.
Round 2:
        input files: {AppleBeanOps}
        annotations: []
        last round: false
Processor org.mapstruct.ap.MappingProcessor matches [] and returns false.
Processor dev.mccue.magicbean.processor.AnnotationProcessor matches [] and returns false.
Round 3:
        input files: {AppleMapperImpl}
        annotations: [javax.annotation.processing.Generated, java.lang.Override]
        last round: false
Processor org.mapstruct.ap.MappingProcessor matches [] and returns false.
Processor dev.mccue.magicbean.processor.AnnotationProcessor matches [] and returns false.
Round 4:
        input files: {}
        annotations: []
        last round: true
gen/AppleBeanOps.java:4: error: incompatible types: AppleBeanOps cannot be converted to Apple
        return (switch (this) { case Apple __ -> __; });
                                     ^
1 error
```

and if I commented out the `@Mapper` then we can see

```
Round 1:
        input files: {Apple, AppleDTO, AppleMapper}
        annotations: [dev.mccue.magicbean.MagicBean]
        last round: false
Processor dev.mccue.magicbean.processor.AnnotationProcessor matches [dev.mccue.magicbean/dev.mccue.magicbean.MagicBean] and returns false.
Round 2:
        input files: {AppleBeanOps}
        annotations: []
        last round: false
Processor dev.mccue.magicbean.processor.AnnotationProcessor matches [] and returns false.
Round 3:
        input files: {}
        annotations: []
        last round: true
```

Unfortunately, my expertise with something on this low level of the java compiler is a bit limited. In additional to that, from what I can see the compile error is in the class that gets generated by Magic Bean. I do not believe that this has anything to do with MapStruct.

I'll close the issue, but we can keep discussing it

**Comment by bowbahdoe** [comment]
Well this sounds like it might be worth reporting to the compiler team.

**Comment by filiphr** [comment]
>Well this sounds like it might be worth reporting to the compiler team.

If you can do that that would be great. Feel free to share the issue here, I would be interested to understand why it isn't working as expected
