### ISSUE TITLE
MapStruct does not pass the parent source object to mapping methods of nested entity if the desired parent source object is used in an expression

### ISSUE THREAD

**Issue by elizavetaMenshikova** [mapstruct/mapstruct#3743]
### Expected behavior

No compilation error

### Actual behavior

I am trying to create an OrderLogisticsDto object from an OrderLogisticsFlowDto object. OrderLogisticsFlowDto contains a nested Operator class. 
![OrderLogisticsDto](https://github.com/user-attachments/assets/f88a1871-64c3-431f-9e96-547954aff63c) 

The Operator class contains a nested OperatorInfo. 
![Operator](https://github.com/user-attachments/assets/03346045-a8ba-4132-906e-e4a8871cc5ad)

OperatorInfo contains 3 fields: vdaId, fullName, phone.
![OperatorInfo](https://github.com/user-attachments/assets/4a42ae2d-ebb8-4b2d-a684-98a7752b1cb8)

vdaId and phone are initialized using the "source = "dto. ..." construct, and fullName uses an expression with the parent object as a parameter:

![OrderLogisticsDtoMapper](https://github.com/user-attachments/assets/a5b4c0f2-8e6e-4c47-9dbb-d3b987b825df)

I get a compile error:
![compilation error](https://github.com/user-attachments/assets/9321efb0-1130-44ad-9b47-594659b512f5)

Because the maptruct generates the following code and does not pass orderLogisticsFlowDto to the signature of the operationLogToOperatorInfo and employeeDtoToOperatorInfo methods.

![OrderLogisticsDtoMapperImpl_2](https://github.com/user-attachments/assets/e847ca0c-1564-4992-b606-5a8ba6d72e57)

But if I comment out the lines where the "source = "dto ..." construct is used, 
![OrderLogisticsDtoMapper_commented](https://github.com/user-attachments/assets/0e1f1eba-684d-4405-9838-c1dfb3a24346)

then compilation is successful because the orderLogisticsFlowDto parameter is passed to the signature of the mapping method of the nested OperatorInfo object.
![OrderLogisticsDtoMapperImpl_commented](https://github.com/user-attachments/assets/769bfafa-ce63-4a49-b71c-096ce61c81a7)

### Steps to reproduce the problem

To reproduce the error, you can run the Main class in the project using the [link](https://github.com/elizavetaMenshikova/mapstruct-bug-test).

I reproduced the error on versions 1.5.2.Final, 1.6.2. 

To compile the program, you need to comment out the lines 
`
            @Mapping(target = "operator.operatorInfo.vdaId", source = "dto.operationLog.userId"),
            @Mapping(target = "operator.operatorInfo.phone", source = "dto.employeeDto.login"),
`
in the OrderLogisticsDtoMapper class.

### MapStruct Version

1.5.2.Final, 1.6.2

**Comment by filiphr** [comment]
This is not a bug, and it works by design. When you use expression you are entirely on your own. You are depending on some internal of how MapStruct generates the code.

The example you have provided would be better implemented if your mapper looks like:

```java
@Mapper
public interface OrderLogisticsDtoMapper {

    String SPACE_SEPARATOR = " ";

    @Mappings({
            @Mapping(target = "operator.operatorInfo.vdaId", source = "dto.operationLog.userId"),
            @Mapping(target = "operator.operatorInfo.phone", source = "dto.employeeDto.login"),
            @Mapping(target = "operator.operatorInfo.fullName", source = "dto.employeeDto"),
    })
    OrderLogisticsDto map(OrderLogisticsFlowDto dto);

    default String getFullName(EmployeeDto employeeDto) {
        return (employeeDto.getSurname() + SPACE_SEPARATOR + employeeDto.getName() + SPACE_SEPARATOR + employeeDto.getPatronymic()).trim();
    }
}
```

Basically do not use `expression`, but use `source`
