### ISSUE TITLE
Redundant if condition in Java record mapping with RETURN_DEFAULT strategy

### ISSUE THREAD

**Issue by primavistalab** [mapstruct/mapstruct#3747]
### Expected behavior

The generated code should avoid unnecessary empty `if ` blocks. It should generate something like these:

```java
    @Override
    public ApiCategoryRecord mapRecord(Category category) {
        Long id = null;
        String title = null;
        if ( category != null ) {
            id = category.getId();
            title = category.getTitle();
        }

        ApiCategoryRecord apiCategoryRecord = new ApiCategoryRecord( id, title );

        return apiCategoryRecord;
    }
```

OR

```java
    @Override
    public ApiCategoryRecord mapRecord(Category category) {
        if ( category != null ) {
            return new ApiCategoryRecord( category.getId(), category.getTitle() );
        }
        else {
            return new ApiCategoryRecord( null, null );
        }
    }
```

### Actual behavior

MapStruct generates an empty and unnecessary `if` block after constructing the record:

```java
    @Override
    public ApiCategoryRecord mapRecord(Category category) {
        Long id = null;
        String title = null;
        if ( category != null ) {
            id = category.getId();
            title = category.getTitle();
        }
        ApiCategoryRecord apiCategoryRecord = new ApiCategoryRecord( id, title );
        if ( category != null ) {
        }
        return apiCategoryRecord;
    }
```

Literally this is not a bug but a minor inefficiency in the generated code.
It does not affect functionality, removing the redundant if condition would improve code clarity and doesn’t suggest anything went wrong during generation.

### Steps to reproduce the problem

Use the following setup

```java
public class Category {
    private Long id;
    private String title;
    public Long getId() { return id; }
    public String getTitle() { return title; }
}

public record ApiCategoryRecord(Long id, String title) {}

@Mapper(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public interface ICategoryMapper {
    ApiCategoryRecord mapRecord(Category category);
}
```

### MapStruct Version

1.6.2

**Comment by primavistalab** [comment]
`version: 1.6.2, compiler: javac, environment: Java 21.0.5 (BellSoft)`

**Comment by filiphr** [comment]
Thanks for reporting this @primavistalab.

>Literally this is not a bug but a minor inefficiency in the generated code.
It does not affect functionality, removing the redundant if condition would improve code clarity and doesn’t suggest anything went wrong during generation.

We strive to generate code as it has been written by a human. The fact that we generate

```java
if ( category != null ) {
}
```

is a bug for us.

The fix should be relatively easy. We'll look into it
