### ISSUE TITLE
Add section to README.md comparing mapstruct with  Java Records

### ISSUE THREAD

**Issue by earizon** [mapstruct/mapstruct#3751]
### Use case

Java Beans was designed with the first versions of Java around 1996. It looks to me that Java newcomers that have randomly read about Java development and Java Beans will randomly ignore the existence of the "alternative" Java Records. Also, beans are so "pervasive" in Java literature that there is a traction to continue using them by pure "inertia". A brief comparative in README.md can help clarify concepts. Both of them generate static safe code. Records are simpler to use and promote safe immutable data (data "dominates" over behavior), while Beans help in more complex scenarios for which the internal data structures and states will evolve over time (behavior "dominates" over data).
 As of 2024-10 I guess the best approach is to use records for "simple data code". Fall back to MapStruct when Records just fall short.
  Said otherwise, try to avoid people using Beans when Records "just work".

### Generated Code

N/A

### Possible workarounds

N/A.

**Comment by filiphr** [comment]
That's a good point @earizon. I'll try to work a bit on the wording.

MapStruct in the end is for data mapping. Whether your data is done with beans, DTOs, builders, records does not make difference to MapStruct.


>Records are simpler to use and promote safe immutable data (data "dominates" over behavior),

Here I am also a bit vary as the data is immutable if the passed objects are immutable. 

e.g.

```java
record Customer(String name, List<Address> addresses)
```

The example above is not immutable as `List` on its own is mutable.

**Comment by filiphr** [comment]
@earizon does https://github.com/mapstruct/mapstruct/pull/3762 make sense to you?

**Comment by earizon** [comment]
> @earizon does #3762 make sense to you?


Yes it does! I owe you a coffee!
