### ISSUE TITLE
EnumMapping to support String-to-Enum conversion #2

### ISSUE THREAD

**Issue by RichMacDonald** [mapstruct/mapstruct#3763]
### Use case

This feature was originally requested at https://github.com/mapstruct/mapstruct/issues/3430.

String to Enum mapping supports PREFIX_TRANSFORMATION and STRIP_PREFIX_TRANSFORMATION but not the other cases. In the test case `CheeseEnumToStringPrefixMapper`, consider the following:

` @EnumMapping(nameTransformationStrategy = MappingConstants.CASE_TRANSFORMATION, configuration = "upper")`
` @EnumMapping(nameTransformationStrategy = MappingConstants.CASE_TRANSFORMATION, configuration = "lower")`
` @EnumMapping(nameTransformationStrategy = MappingConstants.CASE_TRANSFORMATION, configuration = "capital")`

...etc ...

The only one I personally care about is "upper", since I only deal with enums that are named using the uppercase convention. 

I have added a comment to the original feature request at https://github.com/mapstruct/mapstruct/issues/3430#issuecomment-2467212889.

Here is my particular desired case.

````java
@EnumMapping(nameTransformationStrategy = MappingConstants.CASE_TRANSFORMATION, configuration="upper")
@ValueMapping(target = "TRUE", source = "Y")
@ValueMapping(target = "TRUE", source = "YES")
@ValueMapping(target = "FALSE", source = "NO")
@ValueMapping(target = "FALSE", source = "N")
@ValueMapping(target = "INDETERMINATE", source = MappingConstants.ANY_UNMAPPED) //Or throw an Exception because we have an unknown type?
@ValueMapping(target = "INDETERMINATE", source = MappingConstants.NULL)
ThreeWayBooleanCode threeWayBooleanCode(String boolString);

public enum ThreeWayBooleanCode {

	TRUE(true),
	FALSE(false),
	INDETERMINATE(null);

	public final Boolean booleanValue;

	ThreeWayBooleanCode(Boolean booleanValue) {
		this.booleanValue = booleanValue;
	}
}
````

Since I control this enum, I am going to implement my solution with an explicit method:

````java
default ThreeWayBooleanCode threeWayBooleanCode(String boolString) {
	return ThreeWayBooleanCode.matchString(boolString);
}
public static ThreeWayBooleanCode matchString(String boolString) {
	if (boolString == null) {
		return ThreeWayBooleanCode.INDETERMINATE;
	}
	boolString = boolString.toUpperCase();
	if (boolString.contains("Y")) {
		return ThreeWayBooleanCode.TRUE;
	}
	if (boolString.contains("N")) {
		return ThreeWayBooleanCode.FALSE;
	}
	return ThreeWayBooleanCode.INDETERMINATE;
}
````

But still, a useful feature to add to Mapstruct, IMHO.

Keep up the good work.

**Comment by filiphr** [comment]
I think that misconception is what `upper` and `lower` do. They are not there to do some changes and transformations on the passed value. They are rather how should we transform the enum for the matching.

So for what you are asking you would actually need to use `lower`. Then we would use `true` and `false` (as string) in the switch statement and map to the enum.

**Comment by RichMacDonald** [comment]
You're right about the misconception. I am probably not the only one who made this mistake. Reading a manual with assumptions, rather than reading the text exactly. I just "assumed it would apply to the passed value", so I never noticed that everything in the manual refers to transforming the enum value.

A "case-insensitive" comparison would solve a lot of cases but you can't use that in a switch statement.

In my above example with ThreeWayBooleanCode, the explicit hand-written java method is cleanest. For something with a lot more enums, converting everything to upper or lower case works better.

Should there be another annotation for explicitly manipulating the passed value? It isn't strictly needed because the user can do the transformation before calling the mapping. But it is awkward because you wind up changing the value of the input object, which you probably don't want to do (or cannot do).

````java
String myEnumStr1 = source.getMyEnumStr();
if (myEnumStr1 != null){
   source.setMyEnumStr(myEnumStr1.toUpperCase();
}
//... do the above for all enum matches
MyMapper.INSTANCE.convert(source, @Target target);
// ... now we need to set those input values back to the original.
  source.setMyEnumStr(myEnumStr1 ); //might not be possible
````

Not as nice as converting the passed value within the generated method.

Could try and write an intermediate method in the Mapping which does the case conversion, but then you'd have two methods with the same (Stirng, MyEnum) signature.

How hard would it be to allow `@EnumMapping(nameTransformationStrategy = MappingConstants.CASE_TRANSFORMATION, configuration="caseInsensitive")` and then implement that by converting both the enums and the passed value to uppercase?

**Comment by filiphr** [comment]
>How hard would it be to allow `@EnumMapping(nameTransformationStrategy = MappingConstants.CASE_TRANSFORMATION, configuration="caseInsensitive")`

I don't think that something like this would be too hard. However, this would only be applicable for String-to-Enum and maybe it can work for Enum-to-Enum (as this we compare on our side to do the mapping). Although I wouldn't put this too high on our list of priorities as a custom method is trivial to write.

e.g.

```java
@Mapper
public interface EnumMapper {

    // The @Named is here just to make sure that there is a single out-of-the-box method for String to CheeseType
    @Named("stringToEnum") 
    CheeseType map(String value);

    default CheeseType mapCaseInsensitive(String value) {
        return value != null ? map(value.toUpperCase(Locale.ROOT) : map(null);
    }

}
```

As for your `ThreeWayBooleanCode` the cleanest is indeed a hand-written method, but mostly due to the fact that you want to map `Y`, `N`, `YES`, `NO`. So writing the handwritten method is cleaner and having bunch of `@ValueMapping`(s).

**Comment by RichMacDonald** [comment]
I hadn't thought about two methods to handle case-insensitive. Your solution is a good one. Thanks.
