### ISSUE TITLE
Mappings with Generics & Primitives fail

### ISSUE THREAD

**Issue by xmaniac** [mapstruct/mapstruct#3770]
### Expected behavior

Let's have an interface:
```java
interface GenericMapper<A, B, C, D> {
    A mapA(B b);
    C mapC(D d);
}
``` 
And have an implementation using MapStruct:
```java
@Mapper
abstract class Mapper implements GenericMapper <Long, Long, String, String>{}
``` 
We would hope to MapStruct to be able to create an implementation.

### Actual behavior

Mapstruct generates an invalid method for the string mapping
```java
    @Override
    public String mapC(String arg0) {
        if ( arg0 == null ) {
            return null;
        }

        String string = new String();

        return string;
    }
``` 
And fails to generate a method body for the Long one with
```java
- Ambiguous constructors found for creating java.lang.Long: Long(long), Long(java.lang.String). Either declare parameterless constructor or annotate the default constructor with an annotation named @Default. Occured at 'VM mapEntityToModelVersion(VE 
arg0)' in 'EntityToModelMapper'.
``` 
Is the only way to solve this issue is to actually implement the methods by hand?

### Steps to reproduce the problem

No configuration beyond the defaults

### MapStruct Version

Mapstruct 1.6.2

**Comment by filiphr** [comment]
What would you expect MapStruct to generate here?

This has nothing to do with generic an primitives, but rather with the fact that we do not support mapping from `Long` to Long` or `String` to `String`.

Something like

```java
@Mapper
interface MyMapper {
    Long mapLong(Long b);
    
    String mapString(String d);
}
```
is also not going to work.
