### ISSUE TITLE
Cannot use FieldNameConstants

### ISSUE THREAD

**Issue by small-thanks** [mapstruct/mapstruct#3774]
### Expected behavior

<img width="991" alt="image" src="https://github.com/user-attachments/assets/88654e98-746d-4c20-aecc-c90694a9caae">

### Actual behavior

Unknown property "<error>" in result type SupplierOrgDTO. Did you mean "code"?
    @Mapping(source = OCSupplierOrg.PARENT + "." + OCBase.OC_ID, target = SupplierOrgDTO.Fields.PARENT_OC_ID)
                                                                                               ^

### Steps to reproduce the problem

add @Mapping(source = OCSupplierOrg.PARENT + "." + OCBase.OC_ID, target = SupplierOrgDTO.Fields.PARENT_OC_ID) and exec gradle clean build 

### MapStruct Version

1.6.3

**Comment by filiphr** [comment]
This is not a MapStruct problem. See #2951. If you read Lombok's https://projectlombok.org/features/experimental/FieldNameConstants you'll see what you need to do to make the `FieldNameConstants` work with MapStruct.
