### ISSUE TITLE
NoSuchMethod Error when injection strategy is CONSTRUCTOR and there's a use of others mappers at the code

### ISSUE THREAD

**Issue by RafaelRfs** [mapstruct/mapstruct#3781]
### Expected behavior

Hi guys, how are you?

Thanks by awesome working that you are doing,

i'm here to report a bug that i've got   :  

when i'm trying to use the class Mappers.getMappers(SomeMapperClass.class)

with the component model = "spring"

and the injectionStrategy = InjectionStrategy.CONSTRUCTOR is configured, 
with  uses = {
        OtherMapper.class
}

CODE:
```
@Mapper(componentModel = "spring", uses = {
        TechnologiesMapper.class
},injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface ProjectsMapper {

    Project mapToProject(ProjectsDomain projectsDomain);

}
```

there's a bug that says "no such method error", i think i'ts because the others  or whether you create more than one construtor at the class generated, it can solve because of the use of the reflection ...

Reading the PRs i see that AlexELin created a fix ...

### Actual behavior

Error no suchMethodException

### Steps to reproduce the problem

In the unit tests

```
package com.site.rfs.blog.dataproviders.mappers;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mapstruct.factory.Mappers;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.*;
@ExtendWith(SpringExtension.class)
class ProjectsMapperTest {

    private ProjectsMapper projectsMapper;

    @BeforeEach
    public void setUp(){
        this.projectsMapper = Mappers.getMapper(ProjectsMapper.class);
    }

    @Test
    public void test(){
        assertNotNull(this.projectsMapper);
    }

}

```

It throws a error:

java.lang.RuntimeException: java.lang.NoSuchMethodException: 

Debugging the code it' happen when calling the line 49 of the method doGetMapper:

Constructor<T> constructor = implementation.getDeclaredConstructor() at the 

When i change the injection strategy, it's change the behavior and i'ts work:

InjectionStrategy.SETTER
or
InjectionStrategy.FIELD(default);

Please accept the fix of AlexELin, it'll help everyone

https://github.com/mapstruct/mapstruct/pull/3736

### MapStruct Version

1.6.3

**Comment by RafaelRfs** [comment]
I've done a little workaround not defining the component model as a spring and I'm creating beans on my spring context that references the mappers, then it can create the beans on the memory and I can use the whole spring's context

**Comment by RafaelRfs** [comment]
Beans config:

```
@Configuration
public class MapperConfig{
      

 @Bean
   public MyMapper getMyMapper(){
     return Mappers.getMappet(MyMapper.class);

}
}
```
And the Mapper class:

```
@Mapper(uses = { OtherMapper.class}, injectionStrategy = InjectionSrategy.CONSTRUCTOR)
public interface MyMapper{

   public AnyDto  mapTo( Any domain );


}


When I do like this I can use the mapper on the spring and the tests units, detail that the dependencies inside when I use the Mappers.getMapper the dependencies inside is created inside the unit tests and the whole mapper works as well, in the spring I'll have to do reflection because of the auto wired dependencies...

**Comment by filiphr** [comment]
@RafaelRfs I've replied to your comment in https://github.com/mapstruct/mapstruct/pull/3736#issuecomment-2509672086. What you are proposing as a workaround is just a hack, and I would strongly advise against doing that.

You can always instantiate the mapper impl class in your own code if you want to do it in tests.
