### ISSUE TITLE
Mapstruct not able to generate mapping when java record

### ISSUE THREAD

**Issue by kunalvarpe** [mapstruct/mapstruct#3790]
### Expected behavior

mapping function should your builder on record type object and fill the mapping properties.

### Actual behavior

It is only generating the builder without setting property mapping and return empty build object.

### Steps to reproduce the problem

Here is the details mapstruct config used.

CarEntity.java
```java
@Table("cars") // spring data jdbc
@Builder // lombok builder
public class CarEntity {
   private Integer id;
   private String name;
   // other properties ....
}
```
Car.java
```java
@Builder // lombok builder
public record Car(Integer id, String name) {}
```
CarEntityMapper.java
```java
@Component
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface CarEntityMapper {

    CarEntity toEntity(Car car);

    Car fromEntity(CarEntity carEntity);
}
```
Generated implementation by mapstruct
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-12-14T21:20:37+0530",
    comments = "version: 1.6.3, compiler: IncrementalProcessingEnvironment from gradle-language-java-8.11.1.jar, environment: Java 21.0.3 (Oracle Corporation)"
)
@Component
public class CarEntityMapperImpl implements CarEntityMapper {

    @Override
    public CarEntity toEntity(Car Car) {
        if ( Car == null ) {
            return null;
        }

        CarEntity.CarEntityBuilder CarEntity = CarEntity.builder();

        if ( Car.id() != null ) {
            CarEntity.id( Car.id() );
        }
        if ( Car.name() != null ) {
            CarEntity.name( Car.name() );
        }
        if ( Car.category() != null ) {
            CarEntity.category( Car.category() );
        }
        if ( Car.amount() != null ) {
            CarEntity.amount( Car.amount() );
        }
        if ( Car.currency() != null ) {
            CarEntity.currency( Car.currency() );
        }
        if ( Car.userId() != null ) {
            CarEntity.userId( Car.userId() );
        }
        if ( Car.createdAt() != null ) {
            CarEntity.createdAt( Car.createdAt() );
        }
        if ( Car.updatedAt() != null ) {
            CarEntity.updatedAt( Car.updatedAt() );
        }

        return CarEntity.build();
    }

    @Override
    public Car fromEntity(CarEntity CarEntity) {
        if ( CarEntity == null ) {
            return null;
        }

        Car.CarBuilder Car = Car.builder();

        return Car.build();
    }
}
```

If you see the `fromEntity` is not correctly implemented as it involve java record Car with lombok `@Builder`. 
If we remove `Builder` annotation then also it generate the `fromEntity` implementation like below which is incomplete.

```java
@Override
    public Car fromEntity(CarEntity CarEntity) {
        if ( CarEntity == null ) {
            return null;
        }
        Integer id = null;
        String name = null;

        Car car = new Car(id, name);

        return car;
    }
```

Project library versions: 
Spring Boot: 3.3.6
Mapstruct: 1.6.3
Lombok: 1.18.36
lombok-mapstruct-binding: 0.2.0

### MapStruct Version

MapStruct 1.6.3

**Comment by thunderhook** [comment]
Hi @kunalvarpe 

Do you use the `lombok-mapstruct-binding` as a dependency in the plugin as described in the [reference guide section of lombok](https://mapstruct.org/documentation/stable/reference/html/#lombok)?

We use records with builders in our projects and it is just working fine.

**Comment by kunalvarpe** [comment]
Sorry issue is resolved now. Just to let other know issue is with Entity class where I just put `@Builder` annotation, lombok expect `@Data` annotation as well. Which is ideally correct as entity should generate getters and setters. Closing this issue as this is as expected.

**Comment by thunderhook** [comment]
Oh, I see. It was due to the missing getters of the `CarEntity`.
Be aware that using `@Data` can cause other problems due to the automatic generation of `toString()`.
You might consider only setting `@Getter` and if you need it to be mutable also adding `@Setter`.

For more information see: https://medium.com/@devchaghtai/understanding-and-resolving-lombok-data-pitfalls-in-jpa-hibernate-entities-ebc76000da18
