### ISSUE TITLE
Ambiguous factory methods.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#385]
When an `ObjectFactory`, e.g. one generated by JAXB contains 2 methods:

```java

public A createA() {
...
}

public B createB() {
...
}
```
And:

```java
public class A extends B {
}
```

MapStruct generates an Ambiguous factory method. MapStruct should be smart enough to select the 'tightest' match based on return type.

**Comment by gunnarmorling** [comment]
Resolved by introducing new `@BeanMapping` method. I'll leave it open for as a reminder that the doc update still is pending.

**Comment by sjaakd** [comment]
Documentation handled. Solution merged.
