### ISSUE TITLE
Target properties should support nesting (as in #65) too.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#389]
See example below, by @ascuderetti

```java
CarDto
{
   Long idColor;
   BigDecimal price;
}

CarEntity
{
  ColorEntity color;
  BigDecimal price;
}

ColorEntity
{
  Long id;
  String valule;
}
```

(ps. Entity is the object mapping the db ER schema usually managed by a framework like Hibernate, Dto is the object mapping client requirements)

In a READ context Entity is the "source" and Dto the "target", we will have this mapping:

```java
source="color.id" target="idColor"
source="price" target="price"
```
...and your choice is ok.

In a WRITE context (Dto is the "source" and Entity is the "target"), we should have this mapping:

```java
source="idColor" target="color.id"
source="price" target="price"
```
...in this context the nesting on the target side is useful...!

A typical write context case is, for example, when a user inserts a new car. He selects a color from a select.

The http data will be mapped on the CarDto and the CarDto on the Entity with a code like this:

```java
CarEntity car = new CarEntity();

ColorEntity color = new ColorEntity();
color.setId(dto.getIdColor());
//...
//...
car.setColor(color);
//....
```
In this way a framework like Hibernate, with the right configuration, will process the object color with the id setted, nested in the CarEntity, like a foreign key of CarTable to ColorTable.

In my software project this is a common pattern.

---------

Also `@InheritInverseConfiguration` should reverse the nested source properties.

---------

Solution direction & further information: see #65.

**Comment by gunnarmorling** [comment]
@sjaakd, @ascuderetti: I still think it is a good idea that each mapping method only deals with one object on the target side. How would we e.g. deal with the unreported target properties warning if a method could also be in charge of populating sub-properties in the graph? Also the selection of specific factory methods for the sub-nodes wouldn't work.

The given example could be implemented like so, using a manually written mapper class:

    @Mapper(uses=ColorMapper.class)
    public interface CarMapper {

        // generated implementation looks like this:
        // carEntity.setColor( colorMapper.getObjectById( dto.getIdColor(), ColorEntity.class ) )
        @Mapping(target="color", source="idColor")
        CarEntity carDtoToCarEntity(CarDto dto);
    }

    public class ColorMapper {
        <T> T getObjectById(long id, @TargetType Class<T> entityType) {
            // could get it from the database or cache or just return entityType.newInstance( id );
        }
    }

Alternatively, a simple expression could be used:

        @Mapping(target="color", expression="java(new ColorEntity(dto.getIdColor())")
        CarEntity carDtoToCarEntity(CarDto dto);

This seems sufficient to me. So IMO we should avoid the issues of supporting nested properties on the target side, unless a more compelling use case comes up which cannot be addressed with the existing mechanisms.

**Comment by sjaakd** [comment]
* There are more means to do this (see discussion at end of issue #65 before we opened this one). The point is: why use MapStruct? To answer that for myself: because it does stuff for you (generating boring  methods). So I guess you can do this by hand, that's an option we always have. 

* WRT to unmapped target properties, we could consider *one* nested property in a target as a mapped target property (and see the remainder as responsibility for the user) 

* The factory argument is a good argument. But we I don't see why we could not add that in a later phase.

But:

* We did see a clear use case for the `@InheritReverseConfiguration`  (actually right from the star, but then implicit). Why does that argument not apply to nested source properties?

* To elaborate on the last argument: perhaps we should limit the use case to exactly that: `@InheritReverseConfiguration`. Then you avoid potentially complex mixed scenarios (source and targets nested).

**Comment by sjaakd** [comment]
@gunnarmorling , today I had several occurrences of what just what I described above. I have some nested source mappings from an entity to a DTO.  I wanted to create reverse mappings, but that's not possible in an automatic fashion. My comment dd 15 jan would solve that and overcome most of your objections. WDYT?

**Comment by sjaakd** [comment]
Ok.. I thought a bit about this one. Initially I thought that perhaps I could forge the new update methods. But they should be forged incurring. That will not work. That's why I went for a more plain approach.

Consider the following example:

```java
public class PlayerDto {

    private String name;
    private ShirtDto shirt;
...
```

```java
public class ShirtDto {

    private int number;
    private String color;
    private SponsorDto sponsor;
...
```

```java
public class SponsorDto {

   private String name;
   private String address;
...
```

```java
public class PlayerEntity {

    private String name;
    private int number;
    private String shirtColor;
    private String sponsor;
...
```
mapper:

```java
@Mapper
public interface ExampleMapper {

    @Mappings ({
        @Mapping( target = "name", source = "name"),
        @Mapping( target = "number", source = "shirt.number" ),
        @Mapping( target = "shirtColor", source = "shirt.color" ),
        @Mapping( target = "sponsor", source = "shirt.sponsor.name" )
    })
    PlayerEntity mapToEntity( PlayerDto player );

    @InheritInverseConfiguration
    PlayerDto mapToDto( PlayerEntity player );

}
```

I would expect the following code to be generated for ` PlayerDto mapToDto( PlayerEntity player );` :

```java
    @Override
    public PlayerDto mapToDto(PlayerEntity player) {
        if ( player == null ) {
            return null;
        }

        PlayerDto playerDto = new PlayerDto();

        ShirtDto shirtDto = new ShirtDto(); // factory method if available
        playerDto.setShirt( shirtDto );
        shirtDto.setColor( player.getShirtColor() );
        shirtDto.setNumber( player.getNumber() );
        SponsorDto sponsorDto = new SponsorDto(); // factory method if available
        sponsorDto.setName( player.getSponsor() );
        shirtDto.setSponsor( sponsorDto );

        playerDto.setName( player.getName() );

        return playerDto;
    }
```
All target properties are mapped on `PlayerDto` level, so we do not raise an 'unmapped-target-property' error. WDYT?

**Comment by deepu105** [comment]
@sjaakd its bit confusing so will 1.0.0.Final support nested target as well?

I currently have this use case and I expected mapstruct to support it but then realized it doesnt work Im new to mapstruct and dont know how to do it in mapstruct

So I have the below JAXB generated class and I want a to populate this from a flat Flight  entity before dispatching a webservice

I was trying the below befor realizing it doesnt work
```
@Mapper(componentModel = "spring", uses = {})
public interface FlightInfoRequestMapper {

    @Mappings({
        @Mapping(source = "date", target = "generalFlightInfo.flightDate.departureDate"),
        @Mapping(source = "origin", target = "generalFlightInfo.boardPointDetails.trueLocnID"),
        @Mapping(source = "number", target = "generalFlightInfo.flightID.flightNumber"),
        @Mapping(source = "carrier", target = "generalFlightInfo.companyDetails.marketingCompany")
    })
    GetFlightInfoReq flightToFlightInfoRequest(Flight flight);

}
```
```

public class GetFlightInfoReq {

    @XmlElement(required = true)
    protected GetFlightInfoReq.GeneralFlightInfo generalFlightInfo;


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flightDate",
        "boardPointDetails",
        "offPointDetails",
        "companyDetails",
        "flightID",
        "flightTypeDetails",
        "marriageDetails"
    })
    public static class GeneralFlightInfo {

        protected GetFlightInfoReq.GeneralFlightInfo.FlightDate flightDate;
        protected GetFlightInfoReq.GeneralFlightInfo.BoardPointDetails boardPointDetails;
        protected GetFlightInfoReq.GeneralFlightInfo.OffPointDetails offPointDetails;
        protected GetFlightInfoReq.GeneralFlightInfo.CompanyDetails companyDetails;
        protected GetFlightInfoReq.GeneralFlightInfo.FlightID flightID;
        protected GetFlightInfoReq.GeneralFlightInfo.FlightTypeDetails flightTypeDetails;

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trueLocnID"
        })
        public static class BoardPointDetails {

            protected String trueLocnID;

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "marketingCompany",
            "operatingCompany"
        })
        public static class CompanyDetails {

            @XmlElement(required = true)
            protected String marketingCompany;
            protected String operatingCompany;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "departureDate",
            "departureTime",
            "arrivalDate",
            "arrivalTime",
            "dateVariation"
        })
        public static class FlightDate {

            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar departureDate;
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar departureTime;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar arrivalDate;
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar arrivalTime;
            protected String dateVariation;
			
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "flightNumber",
            "operationalSuffix"
        })
        public static class FlightID {

            @XmlElement(required = true)
            protected String flightNumber;
            protected String operationalSuffix;

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "flightIndicator"
        })
        public static class FlightTypeDetails {

            protected List<String> flightIndicator;

        }

    }

}

```

**Comment by sjaakd** [comment]
@deepu105 . The current status of the discussion:
1. Its not going to be part of 1.0 (most likely).
2. Nesting of target properties is not going to be allowed directly.
3. However, the idea is to support reverse mapping of nested source properties. The status quo is that we consider lack of such functionality as a bug. But its tricky and time consuming to implements.

Now some remarks. The functionality you desire is possible nowadays. However, you need to specify in your binding that JAXB generates getters and setters. 

Your mapper would then look like this:

```java
package mapstruct.ex;

import mapstruct.ex.GetFlightInfoReq.GeneralFlightInfo;
import mapstruct.ex.GetFlightInfoReq.GeneralFlightInfo.BoardPointDetails;
import mapstruct.ex.GetFlightInfoReq.GeneralFlightInfo.CompanyDetails;
import mapstruct.ex.GetFlightInfoReq.GeneralFlightInfo.FlightDate;
import mapstruct.ex.GetFlightInfoReq.GeneralFlightInfo.FlightID;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

@Mapper()
public interface FlightInfoRequestMapper {

    @Mapping(target = "generalFlightInfo", source = "flight")
    GetFlightInfoReq flightToFlightInfoRequest(Flight flight);


    @Mappings({
        @Mapping(target = "flightDate", source = "flight" ),
        @Mapping(target = "boardPointDetails", source = "flight"),
        @Mapping(target = "flightID", source = "flight"),
        @Mapping(target = "companyDetails", source = "flight" ),
        @Mapping(target = "flightTypeDetails", ignore = true )
    })
    GeneralFlightInfo flightToGeneralFlightInfo(Flight flight);


    @Mapping(target = "trueLocnID", source = "origin")
    BoardPointDetails flightToBoardPointDetails(Flight flight);


    @Mappings({
        @Mapping(target = "departureDate", source = "date"),
        @Mapping(target = "departureTime", ignore = true) ,
        @Mapping(target = "arrivalDate", ignore = true) ,
        @Mapping(target = "arrivalTime", ignore = true) ,
        @Mapping(target = "dateVariation", ignore = true)
    })
    FlightDate flightToFlightDate(Flight flight);

    @Mappings({
        @Mapping(target = "flightNumber", source = "number"),
        @Mapping(target = "operationalSuffix", ignore = true)
    })
    FlightID flightToFlightID(Flight flight);

    @Mappings({
        @Mapping(target = "marketingCompany", source = "carrier"),
        @Mapping(target = "operatingCompany", ignore = true)
    })
    CompanyDetails flightToCompanyDetails(Flight flight);


}

```
A little bit more verbose than your solution. But it works. It makes use of the fact that MapStruct can also map the parameter itself (flight). 

In a later version you might want to define this as a nested source property method and then reverse it.

**Comment by deepu105** [comment]
@sjaakd thanks a lot mate.
I didn't know it was possible this way, may ne you guys add some similar examples in the docs

Also my personal opinion is that the above illustrated way is too much code for complicated structures which i could write using a plain java mapping function with less code. So for me these kind of complicated mapping and writing custom expression etc defeats the purpose of using mapstruct, coz if i have to write things thia was i would be more comfortable doing it in plain java. Hope mapstruct supports nesting both ways in future. A great project btw

**Comment by gunnarmorling** [comment]
Hi @deepu105, many thanks for your input! We aim at a solution for this use case for 1.1.

> may be you guys should add some similar examples in the docs

Yes, that's on our to-do list. Any help in form of pull requests is welcome :)

> coz if i have to write things this way , i would be more comfortable doing it in plain java.

Understood, and that's what you should be doing by all means if you feel a "manual" mapping is better suited in some cases. You may either just implement it by hand from scratch, or you customize a generated mapping method via [decorators](http://mapstruct.org/documentation/#section-decorators) or the new [lifecycle hooks](http://mapstruct.org/documentation/#section-before-after) introduced in CR1.

**Comment by deepu105** [comment]
Thanks @gunnarmorling I'll take a look at lifecycle hooks and decorators, I really liked the precompile approach of mapstruct compared to reflection based solutions. I guess if mapstruct really can improve in terms of more JAXB support etc, it could be a boon to people who write complex webservices and stuff, coz seldom I have seen a JAXB class directly being used in a project, we always write a transformation layer and mapstruct seems really useful in the complex response to flat entity mapping now, I guess the flat entity to request ill do it by hand for now

**Comment by lehcim** [comment]
Hello. Just using MapStruct since yesterday, trying to port some Dozer code, because you know, xml ...
For now, I'm using the 'expression' to build nested dtos, but this feature would be greatly appreciated.
(reverse mapping of nested source properties is OK for me).

**Comment by lehcim** [comment]
Mmh.... about the "reverse mapping of nested source properties" method, I'm not sure it would work in every use case : It's OK if one side is nested and the other is flat, but what if each side is half-flat / half-nested ?

How  can we map Example to ExampleDto in this example:

```java
FooDto {
    String x
    String y
}

ExampleDto {
    String barA
    String barB
    FooDto f
}

Bar {
    String a
    String b
}

Example {
    Bar bar ;
    String fooX
    String fooY
}
```

(yes I know, the model is ugly but sometimes you don't have a choice)

**Comment by sjaakd** [comment]
> yes I know, the model is ugly but sometimes you don't have a choice

Right.. Especially when your target - and or source DTO's are generated :smile:. Anyway, thanks for the comment. I am working on a solution for the reverse mapping for some months now, on-and-off. Way back we decided to treat that as a bug (you can't reverse map nested source properties yet). The work is not progressing that fast.

When that is in place, the 'full' scenario in the form of the mixed scenario is than in reach as well, but that's more a feature issue. So do we see additional problems when introducing such a feature. I've encountered some small ones so far.. So lets take it step by step.

**Comment by suportevectorx** [comment]
Guys, seriously, this "limitation" should be on bold red letters on the first page of the website... it took me a couple ( of very frustrating ) hours until i found this thread to understand *why* my mappings ( into nested target objects ) were not working.

**Comment by gunnarmorling** [comment]
Sorry to hear that; Generally the reference documentation is comprehensive, so if something is not listed as supported there, you should assume it to be not supported.

While we are working on this, we may create a more descriptive error message when using dot paths for target property names; Maybe you'd be willing to help out with a patch for this, @suportevectorx?

**Comment by sjaakd** [comment]
@gunnarmorling .. Ok  I promised this in the telco we had last week. Imagine our test cases for nested source properties.

Here's the mapper..

```java
package org.mapstruct.ap.test.nestedsourceproperties;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import org.mapstruct.ap.test.nestedsourceproperties._target.ChartEntry;
import org.mapstruct.ap.test.nestedsourceproperties.source.Artist;
import org.mapstruct.ap.test.nestedsourceproperties.source.Label;
import org.mapstruct.ap.test.nestedsourceproperties.source.Song;
import org.mapstruct.ap.test.nestedsourceproperties.source.Studio;
import org.mapstruct.factory.Mappers;

/**
 * @author Sjaak Derksen
 */
@Mapper
public abstract class ArtistToChartEntry {

    public static ArtistToChartEntry MAPPER = Mappers.getMapper( ArtistToChartEntry.class );


    @Mappings({
        @Mapping(target = "chartName", ignore = true),
        @Mapping(target = "songTitle", source = "title"),
        @Mapping(target = "artistName", source = "artist.name"),
        @Mapping(target = "recordedAt", source = "artist.label.studio.name"),
        @Mapping(target = "city", source = "artist.label.studio.city"),
        @Mapping(target = "position", ignore = true)
    })
    abstract ChartEntry map(Song song);


    Song map(ChartEntry chartEntry) {

        if ( chartEntry == null ) {
            return null;
        }

        Song song = new Song();
        Artist artist = new Artist();
        Label label = new Label(); // we now dig into each node of the graph, create objects when needed
        Studio studio = new Studio(); // of course, in an update method, we would check if a node already exists
        studio.setName( chartEntry.getArtistName() ); // ok, we're at a leaf now, so set leaf attributes
        studio.setCity( chartEntry.getCity() ); // leaf
        label.setStudio( studio ); // go up again
        label.setName( chartEntry.getRecordedAt() ); // there's also a leaf
        label.setStudio( studio ); // go up again
        song.setArtist( artist ); // go up again

        return song;

    }


//    @InheritInverseConfiguration
//    Song map(ChartEntry song);

}
```

Now.. I implemented the mapping myself as abstract method (deviated a bit here from the original test case to show this). The comment indicates what I'm trying to do. 

I've some moths ago progressed to the point that I can detect whether a node is shared, so that I don't create an object twice. I just need to implement the code generation part.

The commented out methods indicate what it should be. Of course we should remember to think about update methods and all other kind of forms. We can only allow getters and adders at the deepest level I assume. 

So WDYT?

**Comment by sjaakd** [comment]
Perhaps I should publish my current work in a PR (so just to get an early feedback). Although its far from finished. WYDT?

**Comment by lehcim** [comment]
Yes please ! I'll take a look if you publish it.

**Comment by sjaakd** [comment]
fixed..

**Comment by dermoritz** [comment]
What is the state here? Is there a current solution? 1.1.0 is released isn't it?

**Comment by sjaakd** [comment]
It works in 1.10. However not flawless. Checkout #1011.

**Comment by dermoritz** [comment]
thanks! it is working fin for me. and also thanks for "@Named" support!

**Comment by sjaakd** [comment]
> thanks for this hint. it is working fine for me. and also thanks for "@Named" support!

No problem!

**Comment by mohamnag** [comment]
can this be done into collections? 
lets say I have this:
```java
class Target {
    List<TargetItem> items;
    // ... setter, getter
}

class TargetItem {
    String sourceId;
}

class Source {
    String id;
    // ... setter, getter
}
```

and following mapper:

```java 
interface Mapper {
    @Mapping(source = "id", target = "items[].sourceId")
    Target map(Source source);
}
```

this is a very useful mapping feature when data de-normalization is needed on API

**Comment by sjaakd** [comment]
@mnreddy7 .. that's strange.. the [unit test](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/nestedtargetproperties/ChartEntryToArtist.java) is working..  could it be that you do something wrong.?

**Comment by mnreddy7** [comment]
Even though it is not throwing any error, It is not generating code for nested mapping for target. It works for source though

**Comment by filiphr** [comment]
@mohamnag there is another issue for that request. I just don't remember the number and I am on my phone now.

@mnreddy7 when both are nested we generate symmetrical mappings. And as @sjaakd said the tests for it are passing. Please provide us with a failing example so we can have a look at it. If you do that please open a new issue.
