### ISSUE TITLE
nested source generating invalid code

### ISSUE THREAD

**Issue by hestwood** [mapstruct/mapstruct#400]
//Mapper
        PersonMapper INSTANCE = Mappers.getMapper(PersonMapper.class);
	@Mappings({@Mapping(source="child.id",target="name")}
	)
	abstract People personToPeople(Person person);

    //Generated code
    private String personChildId(Person person) {

        String string = null;
        if ( person != null ) {
            Person child = person.public hestwood.mapstruct.Person getChild() ;
            if ( child != null ) {
                String id = child.public java.lang.String getId() ;
                if ( id != null ) {
                    string = id;
                }
            }
        }
        return string;
    }

**Comment by agudian** [comment]
Fixed.
