### ISSUE TITLE
NestedProperty: Primitives do not work

### ISSUE THREAD

**Issue by shasait** [mapstruct/mapstruct#407]
Mapstruct produces the following code for the adapted integration test:

    private int sourceForNestedIntValue(Source source) {

        if ( source == null ) {
            return null;   <<< what to return here? 0 or some customizable value?
        }
        SomeIntType forNestedInt = source.getForNestedInt();
        if ( forNestedInt == null ) {
            return null;   <<< what to return here? 0 or some customizable value?
        }
        int value = forNestedInt.getValue();
        if ( value == null ) {   <<< null check must be skipped
            return null;
        }
        return value;
    }

**Comment by shasait** [comment]
I will work on a fix (PR)...

**Comment by agudian** [comment]
@shasait: Merged your PR. Thanks alot! :+1:
