### ISSUE TITLE
Static methods calls should not use a mapper instance

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#410]
See #405. Static methods currently use an instance of a mapper, but call the methods on the class.... which leads to problems for utility type of helpers which have typically a private constructor (e.g. due to check style, PMD or other demands).

So: 
1. MapStruct should call static methods on the class
2. If there's no reason to instantiate a mapper, e.g. no instance methods are called, the mapper should not be instantiated as private member of the mapper under construction.

**Comment by gunnarmorling** [comment]
Interesting, never crossed my mind but you are right.

**Comment by sjaakd** [comment]
Done..
