### ISSUE TITLE
qualified method is not used in mapping collections

### ISSUE THREAD

**Issue by natash** [mapstruct/mapstruct#417]
I have noticed interesting befaviour that I don't know if it is intended or not. I will try to explain it with example:

    //first mapper
    @Mappings({ @Mapping(source = "game.players", target = "players", qualifiedBy = QualifyPlayerMapper.class) })
    TargetGame mapGame(Game game);
   
    //second mapper
    @Mappings({ @Mapping(source = "player.street", target = "addressStreet")})
    TargetPlayer mapPlayer(Player player);
       
    //some mapping method that I wanna use and it is qualiffied
    @QualifyPlayerMapper
    TargetPlayer mapPlayerMyWay(Player player);
   
    so in the generated class, in the playerCollectionToPlayerCollection method, is used  mapPlayer.
    In my opinion it should use the second method - mapPlayerMyWay
   
   
    Regards,
    Natalia

**Comment by sjaakd** [comment]
@natash, can you include your definition of @QualifyPlayerMapper as well?

**Comment by natash** [comment]
@Qualifier
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.SOURCE)
public @interface QualifyPlayerMapper

**Comment by sjaakd** [comment]
@natash , can you add a mapping (and see if it works):

```java
IterableMapping(qualifiedBy = QualifyPlayerMapper.class)
List<TargetPlayer> mapTargetPlayer(List<Player> Player);
```

Assumption: MapStruct does not delegate the `Qualifier` to the generated interable method. By making it explicit, you can add the qualifiedBy at the right level.

You can remove the complete `@Mappers` annotation from `TargetGame mapGame(Game game)`, since matching should take place on name (players==players).

**Comment by gunnarmorling** [comment]
That's an interesting case; @sjaakd, I assume that when `@Mapping#qualifiedBy()` is given for a collection-typed property, that value is used to select the matching collection mapping method, right? 

Now in the case where the iterable mapping method is generated as a private helper method, should we apply the given qualifier to select the right element mapping method (I think that's what is suggested here).

I feel we should not so not to change the semantics of `qualifiedBy()` depending on whether the collection method is generated or not). As you say, one can achieve the required behavior by explicitly declaring the collection mapping method. This seems the more consistent appraoch to me, i.e. leave it as is. WDYT?

**Comment by sjaakd** [comment]
> I feel we should not so not to change the semantics of qualifiedBy() depending on whether the collection method is generated or not). As you say, one can achieve the required behavior by explicitly declaring the collection mapping method. This seems the more consistent appraoch to me, i.e. leave it as is. WDYT?

I agree with you on this one. 

However, if we decide to tackle this, then we also need to look at the other  (e.g. dateFormat). 

Anyway, whatever we decide, we should document it :smile:

Lets first await if the proposed solution works for @natash .

**Comment by natash** [comment]
Hi, again, 

I did this : 
//second mapper
@Mappings({ @Mapping(source = "player.street", target = "addressStreet")})
TargetPlayer mapPlayer(Player player);

//some mapping method that I wanna use and it is qualiffied
@QualifyPlayerMapper
TargetPlayer mapPlayerMyWay(Player player);

@IterableMapping(qualifiedBy = QualifyPlayerMapper.class, dateFormat = "")
Collection<ProducerRating.Player> mapPlayerCollection(Collection<Player> collection);

I see, that you know the problem with IterableMapping - that it wants dateFormat  in all of it cases. 

So, in this case mapPlayerMyWay is implemented in Impl class, as well as in the decorator. 
I think that it actually calls the generated method.

**Comment by sjaakd** [comment]
@natash. No, I did not realize that `dateFormat` was mandatory. I think we have to make it optional with the introduction of `qualifiedBy`. We should provide run-time-processor-check to see if one of them `dateFormat` or `qualifiedBy` is specified and make `dataFormat` optional.

@gunnarmorling, WDYT?

**Comment by gunnarmorling** [comment]
> I think we have to make it optional

Yes, absolutely, that makes sense. Same for MapMapping I guess.

**Comment by sjaakd** [comment]
Both `@IterableMapping#qualifiedBy` can be defined independently from `@IterableMapping#dateFormat` . That should enable the use case above.
