### ISSUE TITLE
Add Compiler-Info to generated java files

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#424]
As supplement for #390:

I would then suggest that for now we just append the comment introduced there with some info on the compiler:

Introduced with PR #422:
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-01-21T19:49:29+0100",
    comment="Implementation-Version: 1.0.0-Beta3"
)
```
Proposed here:
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-01-21T19:49:29+0100",
    comment="Implementation-Version: 1.0.0-Beta3 with JavacProcessingEnvironment from tools.jar on Java 1.8.0_25 (Oracle Corporation)"
)
```
That is the simple name of the ProcessingEnvironment implementation, the simple file name of the library that class was loaded from, and the system properties java.version and java.vendor. So that tells us pretty much what we need to know: APT from Oracle JDK 1.8.0_25 was used.

If the Eclipse JDT compiler is used via Maven, the output looks like this:
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-01-21T19:49:29+0100",
    comment="Implementation-Version: 1.0.0-Beta3 with BatchProcessingEnvImpl from org.eclipse.jdt.compiler.apt-1.1.0.v20140509-1235.jar on Java 1.8.0_25 (Oracle Corporation)"
)
```
... Which also contains all the info we need: Eclipse JDT with version given in the jar file was used on an Oracle Java 1.8.0_25. Don't know yet how it looks with the Built-In Eclipse JDT, but that should be similar.

And on JDK 9 (with the new modular build image):
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-01-21T19:49:29+0100",
    comment="Implementation-Version: 1.0.0-Beta3 with JavacProcessingEnvironment from jdk.compiler on Java 1.9.0-ea (Oracle Corporation)"
)
```

@sjaakd, @gunnarmorling: WDYT? Should we perhaps strip the term "Implementation-Version:"?

**Comment by agudian** [comment]
Oh and I would introduce a processor option to suppress the complete comment-attribute (default: with comment).

**Comment by agudian** [comment]
Tried it out with Eclipse and the direct project-level APT:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-01-22T21:12:58+0100",
    comments = "1.0.0-SNAPSHOT with IdeBuildProcessingEnvImpl from org.eclipse.jdt.apt.pluggable.core_1.0.400.v20131113-0353 on Java 1.8.0_25 (Oracle Corporation)"
)
```
(witin Eclipse, the ProcessingEnvironment implementation is loaded and available with a ```bundleresource:``` classpath URL that says pretty much nothing - but it sure has a nicely filled Manifest :smile:, from which I took the info above)

So, to sum it up: I can cover simple jars, OSGI-bundles and JDK 9 JRE modules. 

Remains the question: is the string too long now? The examples above do not try to guess or derive any information (e.g. if the package starts with com.sun., print only "javac ${java.version}" or something like that) - I'd like to avoid that, as it could easily break with new versions or slightly other vendor implementations. That's why the comment contains all those pieces of information from which we should always be able ourself to determine the actual environment.

WDYT?

**Comment by sjaakd** [comment]
> WDYT?

Agreed. However, I do think you can probably do some enters..

BTW: good work!

**Comment by gunnarmorling** [comment]
The actual change is done; Leaving the issue open as a reminder for the doc update. Thx!

**Comment by gunnarmorling** [comment]
@agudian, could you send a PR for the doc update? Thx!

**Comment by agudian** [comment]
Didn't forget it, but had no time for yet either.

**Comment by agudian** [comment]
Doc added to beta4-branch.

**Comment by gunnarmorling** [comment]
Thanks!
