### ISSUE TITLE
Make sure dateFormat(), source(), target() etc. are not empty

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#451]
An error should be raised in case the annotation attributes accepting Strings are set to an empty string.

**Comment by gunnarmorling** [comment]
Should be doable now with the new improved default value handling.

**Comment by sjaakd** [comment]
@gunnarmorling : is this fixed? Most of the mappings have checks on completeness..

**Comment by filiphr** [comment]
It's quite an old issue, so I would say it is fine 😄
