### ISSUE TITLE
Investigate test failures when building MapStruct with JDK 1.9 EA

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#453]
- org.mapstruct.ap.test.reverse.InheritInverseConfigurationTest
- org.mapstruct.ap.test.template.InheritConfigurationTest
- org.mapstruct.ap.test.selection.qualifier.QualifierTest
- org.mapstruct.ap.test.severalsources.SeveralSourceParametersTest

**Comment by sjaakd** [comment]
This has been solved AFAIK.
