### ISSUE TITLE
Processor-Classpath and Compile-Classpath must not be mixed

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#454]
While trying out the current code with a more elaborate "example" project, I came accross different issues.

First of which: the processor classpath can not be considered being the same as the compile-classpath. In NativeTypes#isTypeAvailable(String), we try to load classes from NativeTypes.class.getClassloader(). If you run Eclipse with JDK 8, but have a project using JDK 6, then the java.time.* types are present in the processor classpath, but not in the application - leading to an exception later on during processing.

I already have an idea what we could do to spot that in the integration tests properly. PR will follow tomorrow or so.

**Comment by gunnarmorling** [comment]
Interesting. It's quite an obvious bug, but conditions for it are quite rare I guess (you need either Java 8 or Joda in the processor environment but not in the project under test). Good catch!

**Comment by gunnarmorling** [comment]
Done.
