### ISSUE TITLE
Formatting in generated code needs some cleanup

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#456]
Before we ship Beta4, we should try to clean up some formatting issues that crept in.

For example, in this file created by AbstractClassTest, there are a lot of unnecessary line breaks that we should try to get rid of again:

```java
package org.mapstruct.ap.test.abstractclass;

import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-02-10T22:56:30+0100",
    comments = "version: , compiler: javac, environment: Java 1.8.0_25 (Oracle Corporation)"
)
public class SourceTargetMapperImpl extends SourceTargetMapper {

    private final ReferencedMapper referencedMapper = new ReferencedMapper();



    @Override
    public Target sourceToTarget(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();


        target.setBirthday( calendarToString( source.getBirthday() ) );
        target.setNotAttractingEqualsMethod( referencedMapper.objectToBoolean( source.getNotAttractingEqualsMethod() ) );
        target.setId( source.getId() );
        target.setSize( (long) source.getSize()
        );
        target.setManuallyConverted( referencedMapper.holderToInt( source.getManuallyConverted() ) );



        return target;
    }

    @Override
    public Target sourceToTargetFromBaseMapperInterface(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();


        target.setBirthday( calendarToString( source.getBirthday() ) );
        target.setNotAttractingEqualsMethod( referencedMapper.objectToBoolean( source.getNotAttractingEqualsMethod() ) );
        target.setId( source.getId() );
        target.setSize( (long) source.getSize()
        );
        target.setManuallyConverted( referencedMapper.holderToInt( source.getManuallyConverted() ) );



        return target;
    }

}
```

**Comment by sjaakd** [comment]
:+1: Good points.. I did fix some of them already (and possibly introduced some more). But somehow they keep popping up when you try to make readable free marker lines e.g. (if - then - else) stuff.

**Comment by gunnarmorling** [comment]
Yes, +1 for fixing this.

Instead of addressing it within the templates, we may add logic to `IndentationCorrectingWriter` which reduces several subsequent new lines to a single one.

**Comment by agudian** [comment]
Noooo, didn't see you self-assigning this one. I'll push a PR with a proposed fix anyway, so you can see if you come up with a better approach...

Just needed 15 minutes of doing something meaningful before I shut off... the other inherit-from-base-config stuff needs more concentration than I have right now... :wink:

**Comment by agudian** [comment]
@gunnarmorling, perhaps you have a good idea on how to unit-test the code formatting... perhaps using checkstyle (omitting line length restrictions)?

**Comment by gunnarmorling** [comment]
> Noooo, didn't see you self-assigning this one. I'll push a PR with a proposed fix anyway, so you can see if you come up with a better approach...

No problem, thanks for taking over :) I'll check it out right now.

> perhaps you have a good idea on how to unit-test the code formatting

I wouldn't bother to check this sort of thing automatically. A "manual" check of the formatting every now and then is sufficient IMO.

**Comment by agudian** [comment]
Thinking about it, I guess my fix doesn't work on mac os. You'll see, I guess ;-). Feel free to fix my fix if you want to play with it. A nice puzzle solvable within 15 min... :wink:

**Comment by gunnarmorling** [comment]
It actually works (in case you assume "\r" is a line break on OS X, that's how it used to be, but it's not the case anymore). I'm wondering though why it works on Windows :) After a "\r" it seems not write to be in AFTER_LINEBREAK on Windows (guess it should be something like IN_LINEBREAK?). I planned to look a bit closer at the class in general, I'm not exactly happy with its current shape.

**Comment by gunnarmorling** [comment]
I've got something locally now which should work in all cases. It also uses now the line breaks of the system which runs MapStruct (previously we would have used the line breaks from the template, i.e. those from the system which compiled MapStruct).

I'll polish a bit and send a PR. Took me a bit longer than 15 min though :)

**Comment by agudian** [comment]
> Took me a bit longer than 15 min though :)

Perhaps we're getting rusty on our old days... :wink:

**Comment by gunnarmorling** [comment]
@agudian Just sent PR #462. Could you check it out and give it a try on Windows? I think the overall design of the writer is much better now, easily extensible if needed.

**Comment by gunnarmorling** [comment]
Done.

**Comment by rslakra** [comment]
I think, the following code:
` if ( source == null ) {`

should be formatted as:
` if (source == null) {`

or there should be some property to manage it as every project as different code style and checker.

**Comment by filiphr** [comment]
@rslakra what you are saying is a subjective thing. In the MapStruct code base we are formatting with spaces in the `if`. We have #877, but that's low on the list of priorities in the moment

**Comment by rslakra** [comment]
@filiphr I agree that's why I suggested that there should be some property to support broader audiences.
