### ISSUE TITLE
Eclipse APT Incremental: generation does not work in some cases

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#460]
I have tested around with using MapStruct in Eclipse during the incremental compilation. Although the clean build always works, the incremental generation sometimes leads to errors in the generator (e.g. unable to map from a to b...), as if the "used" mappers defined in the mapper-config interface were not present.

So I stared a debug session with my big original workspace and found some funny behaviour:

At some places we transform a TypeMirror to a TypeElement using ```(TypeElement) ( (DeclaredType) mirror ).asElement()```. That also works fine in Eclipse. But if you then call ```#getEnclosedElements()``` on that TypeElement, you could end up with an empty list. The reason is that in some cases the TypeElement may be backed in Eclipse by an UnresolvedTypeBinding instead of a SourceTypeBinding or a BinaryTypeBinding. And funny enough, Eclipse does not try to resolve the binding upon usage.

We have two options, I'd say:
1. we check every point where we use  ```(TypeElement) ( (DeclaredType) mirror ).asElement()``` and instead do: ```elementUtils.getTypeElement( ( (TypeElement) ( (DeclaredType) usedMapper ).asElement() ).getQualifiedName().toString() )``` (might have an impact on the performance, though)
2. we fix that in Eclipse... and wait for the fix to be applied... and wait for the release to come...

Any suggestions?

**Comment by gunnarmorling** [comment]
I would say if it can be fixed properly in Eclipse that should be the way to go. Of course we could do 1. as a work-around for the time being. We might extract a helper for this which falls back to `elementUtils#getTypeElement()...` if we don't find any enclosed methods the other way.

**Comment by agudian** [comment]
> We might extract a helper for this which falls back to elementUtils#getTypeElement()... if we don't find any enclosed methods the other way.

Good idea, did that. :+1: 

For the Eclipse patch, I'll try to do that at some point.

**Comment by gunnarmorling** [comment]
@agudian, I guess that one can be closed, right?

**Comment by agudian** [comment]
Right. Forgot that. :+1:
