### ISSUE TITLE
Miss Locale import for default conversion String to org.joda.time.LocalDate

### ISSUE THREAD

**Issue by AydenSekey** [mapstruct/mapstruct#465]
The mapping : `@Mapping(source="aStringDateField", target="aLocalDateField")`
Generate code : `setALocalDateField(DateTimeFormat.forPattern(DateTimeFormat.patternForStyle( "L-", `**Locale**`.getDefault() )).parseLocalDate( source.getAStringDateField() ) );`

But miss `import java.util.Locale;` in generated source file.

**Comment by gunnarmorling** [comment]
Hi, thanks for the report. Going to fix it asap. As a work around, you can add `Locale` explicitly via `@Mapper#imports()`.

**Comment by agudian** [comment]
Fix is merged.
