### ISSUE TITLE
Nested mappings - incorrect working

### ISSUE THREAD

**Issue by iflauik** [mapstruct/mapstruct#466]
Hello, 
I have a next case:
  @Mappings({
        @Mapping(target = "country", source = "departure.city.country"),
        @Mapping(target = "location", source = "departure.city.location"),
        @Mapping(target = "postCode", source = "departure.city.postCode"),
        @Mapping(target = "district", source = "departure.city.district")  
    })
    AddressDTO mapAddress(DepartureAddress departure);
With this mappings everything works fine and  next code will be genereted:
     
...
   Address city = departureAddress.getCity();
            if ( city != null ) {
                String district = city.getDistrict();
                if ( district != null ) {
                    string = district;
                 }
             }
         }
         return string;
...

 but I have a such case also:

 @Mapping(target = "district", source = "departure.city.city")

and for this case will be generated:

          Address city = departureAddress.getCity();
            if ( city != null ) {
             String city = city.getDistrict(); 
                if ( city != null ) {
                    string = city ;
                }
            }
        }
        return string;

As you understand it is dosent work.

**Comment by agudian** [comment]
Hi @iflauik, thanks for letting us know! :+1: 

Fortunately, it has already been fixed - #373. 
We'll release the next version pretty soon-ish and it will contain the fix.

If you don't want to wait, you can use the latest snapshot version.
