### ISSUE TITLE
Mapping Object Graphs with Cycles

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#469]
Currently, we have no support of handling cycles within mapping methods. That can be a problem if, for example, both source and target object structures contain bidirectional associations between parent and children. Generic frameworks detect and handle such cycles by maintaining identity-maps. 

We -stubled upon- fell over that in production when suddenly some servers went blank, as it turned out due to stack-overflow-errors. We handled other potential cases with some manual mapping code, but that one spot was overlooked (and the unit tests didn't cover the exact situation). And it wasn't even an obvious spot, as it required two mapping steps to find the starting point of the cycle again.

I think there are two things we could do here:
1. Report-Only: issue warnings or errors if we detect potential cycles. Such an analysis could be performed by an additional processor that checks the model after the MapperCreationProcessor. Question is: what would a user do after spotting this thing.
2. Support handling of cycles: we could maintain an identity-map of source->target instances and return the already mapped instance at the start of the mapping method. Question here is: where would that map be located? In a ThreadLocal? But then this has to be cleared at some point. Might get messy. Or we create a new type MappingContext in package org.mapstruct (would become a runtime-dep if used) and if a mapping method has that thing in its signature, then it is used. Users would pass in a new instance of the context when they want to start their mapping with their root object, e.g. with a static `MappingContext.create()`.

Any thoughts?

**Comment by simpuls** [comment]
Hello,
do you found a solution for the problem?
I have the same problem with a bidirectional relation between to entity objects.
My current workaround is to map this to entity objects "plain" - without the bidirectional relation and after the plain mapping connecting them by reference.

Looking forward for a better solution.

**Comment by almothafar** [comment]
+1

**Comment by agudian** [comment]
Until we get this resolved properly, let's document a possible workaround:

# Workaround

I'll borrow the example from #507:

```java
public class TreeNode {
    private TreeNode parent;
    private List<TreeNode> children;
    // other properties and getters/setters
}

public class TreeNodeDto {
    private TreeNodeDto parent;
    private List<TreeNodeDto> children;
    // other properties and getters/setters
}
```

The `parent` properties could be of other types, the possible cycle could also span over a longer chain of properties, but it doesn't matter for the example.

To avoid the stack-overflow error, we do two things:
* Ignore the back-reference to `parent` in `TreeNodeDto`.
* Add an `@AfterMapping` method to manually set the `parent` property in all children.

```java
@Mapper
public abstract DemoMapper {
    @Mapping( target = "parent", ignore = true )
    public abstract Target toTarget(Source source);

    @AfterMapping
    protected void addBackReference(@MappingTarget TreeNodeDto target) {
        for (TreeNodeDto child : target.getChildren() ) {
            child.setParent( target );
        }
    }
}
```

**Comment by sjaakd** [comment]
@agudian ; shall we add this to examples?

**Comment by stryd3r** [comment]
Any news about this problem?

**Comment by pascalgn** [comment]
Yes. Hi. Sorry, there were some larger pauses between my commits because I had to think of a good solution.

The first idea was to add a configuration parameter `mappingStrategy = IdentityMap`. (those are commits `3519c7c` and `feade77`, both of which I ended up discarding). However, that would have introduced runtime dependencies to MapStruct, which I would like to avoid.

After some thought, I found a simple solution, without any need for big changes in the API: It is the second solution proposed by @agudian in the initial comment, using an `IdentityHashMap` in a `ThreadLocal`, but without runtime dependencies.

The only thing I changed is this: When annotating methods with `@BeforeMapping`, the return parameter of this method is now checked -- if it matches the currently mapped object and is not null, this parameter is returned in the mapping method.

This allows us to write the following code:
  
    @BeforeMapping
    public static Object getInstance(Object source) {
        return ALREADY_MAPPED.get( source );
    }

    @BeforeMapping
    public static void setInstance(Object source, @MappingTarget Object target) {
        ALREADY_MAPPED.put( source, target );
    }

Referencing the class with these methods with `@Mapper`'s `using` parameter, the following code will be generated:

    @Override
    public NodeDTO nodeToNodeDTO(Node node) {
        NodeDTO target = (NodeDTO) NodeMapperContext.getInstance( node );
        if ( target != null ) {
            return target;
        }

        if ( node == null ) {
            return null;
        }

        NodeDTO nodeDto = new NodeDTO();

        ModelMapperContext.setMapping( node, nodeDto );

        return nodeDto;
    }

**The actual change and the code for the context is a bit more complex**, due to the usage of `ThreadLocal` and the need for cleanup, but this shows the general idea. For details, please check `Issue469Test.java` and `NodeMapperContext.java`.

Two more things:

1. **I have not yet modified the documentation.** The idea was to first see what other people think of my implementation before writing the docs.
2. Due to the need to call static callback methods, I also fixed #739 with my commit.

The build seems to be clean and I think all unit tests still run. I will add the pull request to this thread in a minute and I'm happily waiting for any feedback or suggestions from you!

**Comment by pascalgn** [comment]
The pull request is #911

**Comment by pascalgn** [comment]
I have commented on this issue in #911. If you find the time, please let me know if you have any more comments/suggestions!

**Comment by AntwaneB** [comment]
Hello,

Is there any updated regarding when (if?) this is going to be merged to the main repository?

Thanks :)

**Comment by fluxish** [comment]
I also would appreciate an update ;)

**Comment by agudian** [comment]
I've added a comment in #911: we'll get to it, and I do acknowledge that this should be high on our priority list.

**Comment by zt1983811** [comment]
Hi @agudian  could you give an ETA on when this feature can be release? we have a project now waiting for this solution. Thanks

**Comment by agudian** [comment]
> Hi @agudian could you give an ETA on when this feature can be released? we have a project now waiting for this solution. Thanks

I can't give an ETA, but I've just reviewed the PR. If all goes well, we should be able to merge it to master soon and you can use a custom build before we release the first 1.2 beta or candidate release.

**Comment by zt1983811** [comment]
Perfect thank you @agudian

**Comment by agudian** [comment]
Closing this, as it's now possible to do with #911 being merged. Thanks again to @pascalgn for this great patch!

**Comment by zt1983811** [comment]
@agudian Great news on this, do we have nightly build or beta release somewhere ?

**Comment by agudian** [comment]
Snapshots from master are published to the repository https://oss.sonatype.org/content/repositories/snapshots/ (as 1.2.0-SNAPSHOT)

**Comment by zt1983811** [comment]
@agudian I just tried the snapshot version, it seems I still get StackOverflowError on the mapper, Do you need to do something special when I have many to many relationship that is cycle ?

**Comment by filiphr** [comment]
@zt1983811 It doesn't work out of the box. Have a look at the [CallbacksWithReturnValuesTest](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/CallbacksWithReturnValuesTest.java), more specifically the [NodeMapperWithContext](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NodeMapperWithContext.java). 

Soon we will create an example in our mapstruct/mapstruct-examples that people can use.

**Comment by zt1983811** [comment]
@filiphr Thank you, I will take a look of it and wait for the example/

**Comment by zt1983811** [comment]
@filiphr I checked your pull request in example  mapstruct, and it works. Really appreciate for this fix. However, my concerting is why we need to create CycleAvoidanceMapper.java class in all the packages? If I make this in a common package it will not work. Also could you make it generic like annotation I can just use it? 

Thanks

**Comment by filiphr** [comment]
@zt1983811 How do you mean you need to create the `CycleAvoidanceMapper` in all the packages? Or you mean that you need to add it to the `uses` attribute of the `@Mapper`? The `CycleAvoidanceMapper` is already generic and you can use it with any mapper.

@gunnarmorling, @agudian, @sjaakd What is your opinion about:
>Also could you make it generic like annotation I can just use it?

**Comment by zt1983811** [comment]
@filiphr From the [pull request in example](https://github.com/mapstruct/mapstruct-examples/pull/13/commits/057945bb75b4b2d56875d2078539c5240e64f049#diff-3fc3e0b9076ceda462750e3f45e92b88) I found you manually create a class called CycleAvoidanceMapper.java. My question is why this is necessary?  If not where is the generic  CycleAvoidanceMapper class? I try to search in repo but do not find [any.](https://github.com/mapstruct/mapstruct/search?utf8=%E2%9C%93&q=CycleAvoidanceMapper) .

**Comment by filiphr** [comment]
@zt1983811 as I said earlier the support for cycle avoidance is not out of the box and it comes indirectly with the merge of #911. Currently to avoid cycle one has to create their own class like the `CycleAvoidanceMapper` and add it to the `uses` attribute of your mapper. This way people can implement their own logic and their own way of avoiding cycles. The PR for the examples (which is not yet officially merged) is one way of doing it and it is an example which is used in our tests to make sure that the new feature added in #911 by @pascalgn works.

**Comment by zt1983811** [comment]
@filiphr Ah ok now I understand this is not the final version. I will wait for it then. Thanks

**Comment by filiphr** [comment]
@zt1983811 just to clarify, it will be part of the examples (meaning that you will have to create the class yourself and use it where you need to)

**Comment by zt1983811** [comment]
@filiphr  Perfect thanks for the detail explanation and care :+1: -)

**Comment by eapereira** [comment]
This solution work fine with OneToOne relationship, but how would be with OneToMany, where inside the list we have a class with one property being the parent target?

**Comment by chris922** [comment]
@eapereira New comments for closed tickets are often not noticed, questions like this could better be asked on StackOverflow using the tag `mapstruct`.

In case this is not already the solution you are referring to please take a look at this example: https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-mapping-with-cycles 
This example also includes mapping of lists having cycles when I got it correctly.
