### ISSUE TITLE
Allow to specify target package for generated mapper implementation

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#472]

**Comment by 0x3333** [comment]
I was going to report and found this issue.

My use case is:

Implementations goes to a sub package called "impl".

Ex.:

com.mycompany.project.some.MyMapper
com.mycompany.project.some.impl.MyMapperImpl

Thanks.

**Comment by gunnarmorling** [comment]
Thanks for your feedback! Out of interest, which component model are you using? CDI, Spring? Or are you working with the `Mappers` class provided by MapStruct?

**Comment by 0x3333** [comment]
Hi! I'm using Guice as DI, and a custom made framework tied to Guice ecosystem. That's why we have "namespace" like the one I said. The Mapper is from MapStruct itself. Great tool by the way.

**Comment by gunnarmorling** [comment]
Ok, I see.

I was asking because I'm wondering how we could make this work when the `Mappers` factory is used (which you do not use AFAIU). This factory currently simply appends "Impl" to the name of the requested mapper interface, this would not work when this implementation class lives in another package. 

@sjaakd, you suggested to generate the "binding" from mapper interfaces to implementations so that the factory can use it. But where would such binding class live? I think it only can be in the mapper package itself (otherwise we'd just move the problem by one level). Or do you have another idea?

I'm still a bit reluctant to actually access that information from the annotations themselves at runtime, as that'd mean we'd need to re-implement the logic in the factory class (which would be no problem when only taking the `@Mapper` class into account, but I think we should also make the implementation package configurable via `@MapperConfig`). But maybe it's not such a big deal after all? WDYT?

**Comment by gunnarmorling** [comment]
> Great tool by the way.

Thanks, glad to hear it's helpful to you :)

**Comment by 0x3333** [comment]
In my case I bind the Interface with the generated mapper statically.

My two cents is that u can generate a Binding class, e.g. my.company.mapper.MyMapper$Binding.
The class should live in the same package the mapper interface(@Mapper). The generated Mapper(Impl) can live in another alien package. The $Binding class can be used as a provider, in DI context and by the Mappers too.

**Comment by agudian** [comment]
I would find it odd to habe a class in the package of the mapper interface that references the .impl package - in many projects, there are code analysis rules that restrict such references or the resulting package cycles. 
How about we create files in Meta-inf for SPI-style retrieval in case of the default component model?

**Comment by gunnarmorling** [comment]
> How about we create files in Meta-inf for SPI-style retrieval in case of the default component model?

Ah, yes. That might do the trick indeed. I'll give that a try.

**Comment by agudian** [comment]
Fixed. Thanks, @ggtools!
