### ISSUE TITLE
Replace @NullValueMapping with equivalent member in @BeanMapping

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#474]
Hey @sjaakd, now that we have the `@BeanMapping` annotation, IMO it'd be more regular to have a member there `nullValueMappingStrategy()` instead of a dedicated annotation. WDYT?

**Comment by agudian** [comment]
I thought about the same thing when I was about to restructure the docs today... ```@NullValueMapping``` didn't really fit in with the rest that we have now.

**Comment by sjaakd** [comment]
> Hey @sjaakd, now that we have the @BeanMapping annotation, IMO it'd be more regular to have a member there nullValueMappingStrategy() instead of a dedicated annotation. WDYT?

Good point!

**Comment by gunnarmorling** [comment]
Cool. Anyone up for it :)

**Comment by sjaakd** [comment]
I can take it.. But not tonight anymore.. Just finished PR471 ..

**Comment by sjaakd** [comment]
I've removed `@NullValueMapping` and moved it to `@BeanMapping`, `@MapMapping` `@IterableMapping`. That works. However, I spotted that @agudian  has done some nice refactoring and moved `@MapMapping` `@IterableMapping` into `MappingOptions`. 

I believe we should do the same for `@BeanMapping` and perhaps also for `@EnumMapping`. WDYT?

Next I need to adapt the error messages a bit.

More tomorrow.

**Comment by gunnarmorling** [comment]
> I believe we should do the same for @BeanMapping and perhaps also for @EnumMapping

Sounds reasonable to me. `MappingOptions` seems to represent all annotations potentially given on mapping methods.

**Comment by agudian** [comment]
Right, that was the plan. Seems like I only did half of the job ;-)

**Comment by sjaakd** [comment]
> Right, that was the plan. Seems like I only did half of the job ;-)

No problem..  You can help out with reviewing :+1:  :smile:

**Comment by agudian** [comment]
Sjaak's PR is merged, and I've just pushed the doc-update.

**Comment by gunnarmorling** [comment]
> Sjaak's PR is merged, and I've just pushed the doc-update.

Cool, many thanks, you two!

Could you also add a short notice to the migration notest: https://github.com/mapstruct/mapstruct/wiki/Migration-notes

**Comment by agudian** [comment]
> Could you also add a short notice to the migration notest: https://github.com/mapstruct/mapstruct/wiki/Migration-notes

done.
