### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by pardom** [mapstruct/mapstruct#481]
Currently there are class dependencies (Java 8 Dates and JAXB) that cause ClassNotFound exceptions in the annotation processor when compiling for Android. Are there plans to support the Android build environment?

**Comment by gunnarmorling** [comment]
Hi, we haven't specifically thought about this yet, but it should be doable.

Actually it should work already without the Java 8 date types (these should only be accessed if actually present, so MapStruct can be used on Java 6/7), so this may be a bug. Assuming we fix that, it should be possible to do similar for the JAXB classes.

Do you have stracktraces which show where the CNFEs exactly happen?

**Comment by pardom** [comment]
I created an example project exhibiting the behavior I'm seeing: https://github.com/pardom/MapStructTest

When I build using `./gradlew clean assembleBeta --debug` I see this output:
```
09:46:50.125 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
09:46:50.811 [ERROR] [system.err] error: Couldn't find type java.time.ZonedDateTime. Are you missing a dependency on your classpath?
09:46:50.854 [ERROR] [system.err] 1 error
```

**Comment by agudian** [comment]
That particular error was fixed already. Could you try using our latest snapshot version?

**Comment by pardom** [comment]
I just updated to the snapshot and tried again.

`./gradlew clean assembleDebug --debug --refresh-dependencies`

Produces:
```
10:32:37.704 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
10:32:38.192 [ERROR] [system.err] error: Couldn't find type java.time.ZonedDateTime. Are you missing a dependency on your classpath?
10:32:38.233 [ERROR] [system.err] 1 error
```

**Comment by agudian** [comment]
Thanks for your feedback - I saw just now that the snapshot we have on deployed is too old and did not yet contain the fix that I was thinking about. I'm deploying the current state of our master branch right now, so it would be great if you could try again (I don't have an Android SDK installed).

**Comment by pardom** [comment]
Cool, that took care of the `ZonedDateTime` CNFE. Now it's just JAXB:
```
14:11:36.706 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
14:11:37.367 [ERROR] [system.err] error: Couldn't find type javax.xml.bind.JAXBElement. Are you missing a dependency on your classpath?
14:11:37.406 [ERROR] [system.err] 1 error
```

**Comment by gunnarmorling** [comment]
Ok, that's kind of what I've expected. Should be possible to do the same handling for the built-in JAXB conversions.

**Comment by pardom** [comment]
Great! Is this something small that I can PR?

**Comment by gunnarmorling** [comment]
Yes, your help is more than welcome! It should be fairly simple.

Check out [BuiltInMappingMethods](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/model/source/builtin/BuiltInMappingMethods.java) which is where the built-in JAXB-related methods should be excluded. We do another exclusion for Java 8 classes there already.

You can find general information regarding the development of MapStruct [here](http://mapstruct.org/contributing/).

**Comment by pardom** [comment]
Ah, I didn't know that method was actually working. I wasn't working against the snapshot though, so that explains it.

**Comment by pardom** [comment]
I'm having problems building in IntelliJ (cross-module references). I'll keep trying, but you'll probably be faster at this. :confused:

**Comment by gunnarmorling** [comment]
I don't use IntelliJ myself, but did you see these tips [here](http://mapstruct.org/contributing/#section-06)?

**Comment by pardom** [comment]
Yes, but I'm having different build issues.

**Comment by pardom** [comment]
In addition to the above fix, Android requires a dependency for the `@Generated` annotation. With the updated snapshot and the additional dependency, this project now works: https://github.com/pardom/MapStructTest

**Comment by RomanMinenok** [comment]
Guys, why you don't update this page http://mapstruct.org/news/2013/07/08/using-mapstruct-with-gradle.html? Compare build.gradle in the sample project by @pardom and this page? I almost dropped any remote idea of using your lib after seeing the page and it turned out that it can be used in pretty standard and straightforward way with Gradle.

**Comment by agudian** [comment]
Apart from updating the bolg post (you find it in the repo mapstruct/mapstruct.org), the main documentation in this repository (published as reference docs) could also use that example. And so does the readme.md here.

Would you consider opening a pull request?

(This may sound lame or bitchy (or both), but I mean it in a purely positive manner - any help is appreciated).

**Comment by RomanMinenok** [comment]
I see. Not sure about updating web site, but I can add Android specific demo (basically adapting the one from @pardom) here guys if you wish https://github.com/mapstruct/mapstruct-examples

I just wanted to point out that looks like that article is very outdated and brings harm to the project since Gradle integration can be actually done in a very simple and clean way currently. I would delete basically all of it and just add a link to Gradle example repo, but you guys would be the best judges about how you should do that. 

Also that particular repo with examples is hard to discover, there is only a link buried deeply on the web site. So maybe you are right we could add a link to example repo to the main project README (let me know, I can make a PR for that).

**Comment by RomanMinenok** [comment]
Guys, if anyone is interested - I actually could not make MapStruct work on Android. In the sample provided by @pardom the core feature is missing which is multiple `@Mapping` annotations on a method name. It refuses to work as Android  as it is compatible only with Java 8. No workarounds that I tried to apply to the issue actually helped also.

**Comment by pardom** [comment]
@RomanMinenok Since you cannot use multiple `@Mapping` annotations with Android, you'll have to use the [`@Mappings`](http://mapstruct.org/documentation/1.0/api/index.html) annotation.

For example:

```java
@Mapper
public interface CarMapper {
 
    @Mappings({
        @Mapping(source = "numberOfSeats", target = "seatCount"),
        @Mapping(source = "manufacturingDate", target = "manufacturingYear")
    })
    CarDto carToCarDto(Car car);
 
    PersonDto personToPersonDto(Person person);
}
```

**Comment by RomanMinenok** [comment]
Thanks @pardom, it helped! Probably having a working Gradle example for Android would be a good idea too.
