### ISSUE TITLE
Deploy SNAPSHOT upon every build in our CI

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#491]
We should have the latest snapshot available in the oss.sonatype.org repo, to make it easier for users to try out the latest stuff or to retest a bugfix.

**Comment by gunnarmorling** [comment]
@agudian, great idea. I had opened the same issue at the same time :) Do you think you could look into this? If you need any further permissions on CloudBees for this, just let me know. Ideally, we'd have a custom account/key only used for this purpose.

**Comment by agudian** [comment]
Done. For now, the artifacts are deployed with my credentials.

**Comment by gunnarmorling** [comment]
Cool, many thanks!
