### ISSUE TITLE
Use qualifiers to resolve ambiguous mappings

### ISSUE THREAD

**Issue by dilipkrish** [mapstruct/mapstruct#497]
When a mapping provides a qualifier to be used to resolve a mapping method, the annotation processor
should attempt to resolve it using the provided qualifier

Granted that there is a work around using expressions. But I'd rather have an option where we use expression as a last resort.

**Comment by dilipkrish** [comment]
Created a PR to demonstrate this issue #496

**Comment by dilipkrish** [comment]
Figured out what the problem was. Details in the PR #496

**Comment by sjaakd** [comment]
@dilipkrish good to hear you solved it. Been there myself as well :smile:. BTW: do you know beta4 is out.. ?

**Comment by dilipkrish** [comment]
Just curious, what is the reason for the slow release cadence, esply from beta to release? We're using mapstruct in [springfox](http://springfox.io) and its looks fairly stable to me.

**Comment by gunnarmorling** [comment]
Good question :) It's mainly a question of resourcing; E.g. personally I
could recently dedicate far less time to the project than I had wished.

I also consider it fairly stable, we don't have planned for any large
changes for the Final. So using the Beta shouldn't make you feel too
uncomfortable :) We are mainly fixing bugs and polishing out some remaining
glitches at this point.

There will be an RC soon (next weeks), and the Final should be out after
that rather quickly, assuming no more blockers pop up.
