### ISSUE TITLE
Emit warnings for precision loss

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#5]
This follows up on #1; If built-in conversion causes a possible precision loss (e.g. from `long` to `int`), a warning or error should be created. If the concerned attribute is mapped via `@Mapping` the marker should be at the annotation, otherwise at the mapping method(s).

It might be a good idea to make it configurable either globally and or via an attribute in `@Mapper` whether the error kind should be `WARNING` or `ERROR`.

**Comment by GuiSim** [comment]
Any progress on this feature? I think it would be a great addition to MapStruct.

**Comment by agudian** [comment]
No one worked on this, yet. Would you maybe like to give it a try?

**Comment by gunnarmorling** [comment]
As @agudian is saying, any help with this would be welcome. I'd be very glad to see it in :) We can give directions to get started if needed.

**Comment by GuiSim** [comment]
Thanks for the proposition. We're still unsure if we're going to go ahead with MapStruct but if we do, I'd love to contribute back to the project as I think we'll need this feature.

I'll update if we choose MapStruct!

**Comment by gunnarmorling** [comment]
Sure; if you have any questions during your decision process, let us know, we'll be glad to help as good as we can.

**Comment by gunnarmorling** [comment]
Hey @GuiSim, curious which route you did end up following? If you didn't go for MapStruct in the end, do you mind me asking what spoke against it? Always eager to learn from people's thinking so we can improve the stuff. Thanks!

**Comment by GuiSim** [comment]
We didn't go with any mapping technology for now.. we're still writing what we call "translators" to convert from one type to another.

It's still a tedious process but we're slowly removing intermediary objects. We realize that this increases coupling but we feel like the pros outweigh the cons.

**Comment by sjaakd** [comment]
i'll pick this one up. I think we have to have a strategy as well (just like for unmapped target properties):
* fail 
* warn

**Comment by sjaakd** [comment]
There are actually 2 interesting things, which are not the same.
1. narrowing. In general, loss of precision (the stuff after the dot when converting from float to int) or loss of range (trying to fit a int in a short).
2. widening.. In general not a problem , but could lead to precision loss. In case of integer or long to float conversion, or long to double. 

I think we need to distinguish these cases.
So:
- ReportingPolicy conversionNarrowingPolicy;
- ReportingPolicy conversionPrecisionLossPolicy;

**Comment by sjaakd** [comment]
the term JDK uses is "possibly lossy conversion from t1 to t2" ..

**Comment by sjaakd** [comment]
Done..
