### ISSUE TITLE
qualified method do not qualify if they are private to the mapper.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#502]
I've used qualifiers on private methods in an abstract mapper. Doesn't seem to work.

**Comment by agudian** [comment]
> I've used qualifiers on private methods in an abstract mapper. Doesn't seem to work.

That's not supposed to work. If the methods are private, then the generated code can't reference them. Or are they actually picked up and you get a compile error?

**Comment by gunnarmorling** [comment]
If a mapper is an abstract class (rather than an interface), I think it
should be able to make use of private (element etc.) mapping methods, no?

**Comment by gunnarmorling** [comment]
Hum, no, they'd have to be protected / package-private at least. It's too
late I guess ;)

2015-04-12 23:39 GMT+02:00 Gunnar Morling <gunnar.morling@googlemail.com>:

> If a mapper is an abstract class (rather than an interface), I think it
> should be able to make use of private (element etc.) mapping methods, no?
>

**Comment by sjaakd** [comment]
Made the same thinking error as Gunnar! I'll close this one!
