### ISSUE TITLE
Convert collection to dto

### ISSUE THREAD

**Issue by bosofelipe** [mapstruct/mapstruct#506]
It is possible to convert list to dto ?

simple example 

@Mapping(source = "state.name", target = "state[0].name")

**Comment by sjaakd** [comment]
Hi @bosofelipe ,  you mean something like [this](https://github.com/mapstruct/mapstruct-examples/tree/master/maptruct-iterable-to-non-iterable)?

**Comment by bosofelipe** [comment]
@sjaakd Collection to POJO 

exemple 
class UserDTO with attributes name and age

List<AnyUser> anyUser()  and AnyUser with fullName and years

It is possible to convert list to dto ?

anyUser[0].fullName to UserDTO.name  ?

**Comment by sjaakd** [comment]
So, what you need to do is define a mapping method from `UserDTO` to `AnyUser` like this:

```java
@Mapper( uses = { CustomMapper.class, IterableNonInterableUtil.class } )
public interface UserMapper {

 @Mapping( target = "userDto", source = "anyUser",  qualifiedBy = FirstElement.class ),
DtoContainingUserDTO map(ObjectContainingAnyUser in);

@Mappings( {
    @Mapping( target = "name", source = "fullName" ),
    @Mapping( target = "age", source = "years" )
})
UserDTO map(AnyUser user);
}
```

Your `CustomMapper` contains handwritten methods to convert `fullName` to `name` and `years` to `age`.

**Comment by celinoaraujo** [comment]
Perfect, list to dto.

And dto to list?

Example:

@Mapping(source = "state.name", target = "state[0].name")

**Comment by bosofelipe** [comment]
@sjaakd And dto to list? like up exemple

**Comment by sjaakd** [comment]
Well, you can write a custom method, just as I did for the qualifier example. Something along the lines of:

```java
@AsList
public <T> List<T> asList( T in ) {
    List<T> result = new ArrayList<T>();
    if ( in!=null ) {
       result.add(in);
   }
   return result;
}
```

You can use the qualifier approach as well (`@AsList`), so that only `Mapping(source="aaa", target="bbb", qualiedBy=AsList.class)` qualifies. Just copy the example.

**Comment by sjaakd** [comment]
Can this be closed?
