### ISSUE TITLE
infinite loop to map 2 class that are related with many to many.

### ISSUE THREAD

**Issue by boussoufiane** [mapstruct/mapstruct#507]
Hi  , 

If there are two classes that are linked by a relationship many to many one falls into a infinite loop.
For example, a user has several roles and a role has multiple users.
the method mapUser call MapRoles wich call MapRole wich call MapUser wich call mapUser and so on .... .
 can you please help me with a  bypass .

regards .

**Comment by boussoufiane** [comment]
My class : 
@Mapper
public interface EntityToDtoMapper {
	
	EntityToDtoMapper INSTANCE = Mappers.getMapper( EntityToDtoMapper.class );
	
	Role mapRole(RoleEntity role);
	
	User mapUser(UserEntity user);
	
    List<User> mapUsers(List<UserEntity> users);
	
	List<Role> mapRoles(List<RoleEntity> roles);


}

**Comment by sjaakd** [comment]
Hi @boussoufiane , I believe @agudian  reported this in #469. Is this what you mean?

**Comment by agudian** [comment]
Closing it, as it's a duplicate.
