### ISSUE TITLE
Occasionally empty generated .java file in multithreaded build

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#508]
Following up #504, which threw an NPE, I now have some empty .java files flying around. Seems like a flush is missing somewhere...? I'm investigating...

**Comment by agudian** [comment]
Damn, I didn't find anything, yet. An additional flush() in IndentationCorrectingWriter.close() after currentState.onExit(..) didn't change anything, either.

@gunnarmorling: any idea what that could be?

**Comment by gunnarmorling** [comment]
@agudian, do you have a specific mapper definition which triggers that
error?

**Comment by agudian** [comment]
Nope, but it seems like if it happens for one maven module, then it happens for all the mappers there.

We are building with JDK 1.8.0_25 with -T4 and the annotation processors (MapStruct and Hibernate Metamodel Gen) are picked up from the classpath by javac (via maven-compiler-plugin).

Just tried several builds locally with -T8, but it always worked as expected.

**Comment by agudian** [comment]
Tomorrow I'll rewrite the poms to perform the processing with the processor plugin, separated from the acutal compilation. Let's see if that changes anything...

**Comment by gunnarmorling** [comment]
You could try and remote-debug your Maven process, maybe modifying the
IndentationCorrectingWriter class so you can add a break point if an empty
file gets written. Will probably require some fiddling...

**Comment by agudian** [comment]
That was my plan as well, but I can't reproduce it deterministically. I tried it locally several times without any luck, and I can't do it remotely on the jenkins build node...

**Comment by agudian** [comment]
Using the processor-plugin didn't change anything.

What I can see is that if I end up with an empty file, the write(..) method in IndentationCorrectingWriter is never called and the encapsulating BufferedWriter is empty as well. That could hint to a threading-issue with freemarker or the way we use it. Didn't find it yet, though.

**Comment by agudian** [comment]
What I found out today: freemarker's template cache returned an "empty" template, i.e. a Template instance that contains an empty rootNode, as if the input stream was empty.
By default, the cache checkes every five seconds if the template source may have changed. For us it doesn't change, but that's something that the cache seems to recognize - shouldn't be a problem. But the default cache storage uses weak references, allowing cache entries to be GC'ed. I've reconfigured the cache to not do any checks for modifications and to use a cache storage that uses hard references (i.e. once cached, an entry is not discarded).
That didn't help too much though. Each module that is compiled uses its own classloader (naturally) and thus all the static instances we have are NOT shared between the compiler threads for different modules in the same JVM - e.g. the freemarker Configuration (and thus the caches) are not subject to multithreaded access.
Plus, if one module contains empty mapper files, then ALL the generated sources are affected - which would mean that the initial loading of the template somehow failed.
In one instance of the problem, I was in the debugger and saw the emtpy template, and still was able to read the template file from the class loader correctly. So I added a check to just before the template is processed:

```java
            BufferedWriter writer = new BufferedWriter( new IndentationCorrectingWriter( sourceFile.openWriter() ) );

            Map<Class<?>, Object> values = new HashMap<Class<?>, Object>();
            values.put( Configuration.class, CONFIGURATION );

            Template rootTmpl = CONFIGURATION.getTemplate( "org.mapstruct.ap.model.GeneratedType.ftl" );
            if ( rootTmpl.toString().isEmpty() ) {
                System.out.println( Thread.currentThread().getName()
                    + " [debug] unable to read root template. clearing cache." );
                CONFIGURATION.clearTemplateCache();
            }

            model.write( new DefaultModelElementWriterContext( values ), writer );
```
I saw that debug message one or two times and the resulting mapper files were ok in that case. I'm having trouble recreating the issue ever since (including hitting this workaround).

**Comment by sjaakd** [comment]
> I saw that debug message one or two times and the resulting mapper files were ok in that case

Hmm. That's strange.. Are you checking the right thing then? E.g. are the templates populated at a later moment than your forced debug?

**Comment by gunnarmorling** [comment]
Have you tried the `NullCacheStorage`? This effectively disables caching AFAIU. This may help to find out whether the problem is related to caching of templates or their retrieval from the source files.

**Comment by agudian** [comment]
> Hmm. That's strange.. Are you checking the right thing then? E.g. are the templates populated at a later moment than your forced debug?

Yes, I'm checking the right thing - I loaded the Template and "usually" it is populated, but on these rare occasions it remained empty.

> Have you tried the NullCacheStorage? This effectively disables caching AFAIU. This may help to find out whether the problem is related to caching of templates or their retrieval from the source files.

Using NullCacheStorage and my own implementation of a TemplateLoader (which manually creates the "jar:"-URL, opens the input stream, slurps in the content and returns a reader for that content), I came accross the following exception:

```
Caused by: java.io.IOException: Stream closed
        at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:121)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.mapstruct.ap.writer.ModelWriter$LocalClasspathLoader.getReader(ModelWriter.java:161)
```

That means: while reading from the freshly obtained input stream, "something" closed the stream (or the JarFile). It could be that such an exception is somewhere swallowed within Freemarker, resulting in the empty template - although I didn't find such a spot, yet.

I now deactivated the caching of the JarFile on the URLConnection, let's see how that works out.

**Comment by agudian** [comment]
> I now deactivated the caching of the JarFile on the URLConnection, let's see how that works out.

That seems to do it: four days and more than 42 builds without an accident. I'll prepare a clean PR for that in the next days.

**Comment by gunnarmorling** [comment]
Done. Thanks for investigating and fixing this, @agudian!
