### ISSUE TITLE
AUTO_INHERIT_FROM_CONFIG does not combine with @InheritInverseConfiguration

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#511]
Sorry guys, I don't remember what we agreed here. I can check myself as well this weekend. However, the following: 

The above use case (subject) does not combine. When I add the  `@InheritInverseConfiguration`  MapStruct takes the properties from the inverse configuration as expected, but 'forgets' the base mappings in the `MapperConfig` entirely. 

I would either expect some kind of warning, or even better, that MapStruct 'stacks' the mappings defined in `MapperConfig` with the ones pointed out by `@InheritInverseConfiguration` (the last one prioritised). 

WDYT?

**Comment by agudian** [comment]
The current behaviour intended by the implementation is to inherit all config from the reverse method, wheras the config of the reverse method may very well have been enriched by the prototype form the mapper config.

Otherwise you would need to allow ```@InheritInverseConfiguration``` to be combined with ```@InheritConfiguration``` on the same method (as the auto-inheritance should always be reflectable with manually applying ```@InheritConfiguration```, IMHO - otherwise you could be in trouble if suddenly you need to resolve ambiguities).

**Comment by sjaakd** [comment]
I remember now.. thanks :smile:

> The current behaviour intended by the implementation is to inherit all config from the reverse method, wheras the config of the reverse method may very well have been enriched by the prototype form the mapper config.

 That works on the assumption that the reverse method has the same properties as the forward method. In my case, the reverse method maps to a result that derives from a generated JAXBType, with a forest of attributes I'd like to ignore in the mapping. The DTO from which I map does not have these attributes (exactly because of the fact that they have no meaning to my business).. 


> Otherwise you would need to allow @InheritInverseConfiguration to be combined with @InheritConfiguration on the same method (as the auto-inheritance should always be reflectable with manually applying @InheritConfiguration, IMHO - otherwise you could be in trouble if suddenly you need to resolve ambiguities).

Is there any way we could distinguish between a prototype `@InheritConfiguration` and the regular `@InheritConfiguration`? Another option would be to merge the `@aaaConfiguration` in the way they are specified (and if omitted, assume they are first). So last overides first. WDYT?

**Comment by sjaakd** [comment]
not relevant anymore..
