### ISSUE TITLE
Duplicated class MapperImpl

### ISSUE THREAD

**Issue by jmayday** [mapstruct/mapstruct#514]
I'm struggling with maven/mapstruct and "duplicate class ...MapperImpl" error. 
In general maven can't build my project with 'mvn clean install' but actually mapper implementation is generated. Problem is that is generated twice:
	
	- target\generated-sources\annotations\com\mycompany\myproj\mappers\MyMapperImpl.java
	
	- target\generated-sources\com\mycompany\myproj\mappers\MyMapperImpl.java

I tried to follow 'get started'; I put these two dependencies to dependencyManagement:
	
	<dependency>
		<groupId>org.mapstruct</groupId>
		<artifactId>mapstruct</artifactId>
		<version>${org.mapstruct.version}</version>
	</dependency>

	 <dependency>
		<groupId>org.mapstruct</groupId>
		<artifactId>mapstruct-processor</artifactId>
		<version>${org.mapstruct.version}</version>
		<scope>provided</scope>
	</dependency>

and build section looks like this:

	
	<build>
		<plugins>
			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
				<version>2.2.3</version>
				<configuration>
					<defaultOutputDirectory>
						${project.build.directory}/generated-sources
					</defaultOutputDirectory>
					<processors>
						<processor>org.mapstruct.ap.MappingProcessor</processor>
					</processors>
				</configuration>
				<executions>
					<execution>
						<id>process</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>process</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.mapstruct</groupId>
						<artifactId>mapstruct-processor</artifactId>
						<version>${org.mapstruct.version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

I tried with mapstruct 1.0.0.Beta3 and 1.0.0.Beta4

**Comment by cardamo** [comment]
If mapping processor specified in the maven-processor-plugin configuration there is no need in mapstruct-processor dependency.

**Comment by jmayday** [comment]
@cardamo Thank you for quick response. Removing mapstruct-processor did help.
