### ISSUE TITLE
Adder source object does not have NPE check

### ISSUE THREAD

**Issue by paul999** [mapstruct/mapstruct#516]
Generated code: getDocuments() returns null.
```java
        if ( dossier != null ) {
            blkWbbDossierEntity.setPre1987Bln( fromBoolean( dossier.getPollutionStartedBefore1987() ) );
            blkWbbDossierEntity.setIdAuthority( dossier.getDossierIdLocalAuthority() );
            for ( DocumentDto blkWbbDocument : dossier.getDocuments() ) {
                blkWbbDossierEntity.addBlkWbbDocument( toEntity( blkWbbDocument ) );
            }
```

**Comment by gunnarmorling** [comment]
Hi @paul999, could you also provide the involved type definitions (`Dossier`, `DossierEntity`)  and the mapper interface you declared? Thx!

**Comment by sjaakd** [comment]
@gunnarmorling : I'll provide fix + reproducer.. I know this guy: @paul999  :smile:

**Comment by agudian** [comment]
Checked and pushed Sjaaks fix to master. Thanks @paul999 for reporting and @sjaakd for fixing it! :+1:

**Comment by gunnarmorling** [comment]
Cool, thanks, guys!
