### ISSUE TITLE
Update collection in target bean

### ISSUE THREAD

**Issue by nocquidant** [mapstruct/mapstruct#522]
Thanks a lot for this nice library!

I have the following use-cases:

1. get dto from entities 
2. create entities from dto
3. **update entities from dto**

In some cases, my mapping between dto and entiy is 1-1 (no "flat" dto) and i have a OneToMany relationship for my entities.

I read from the doc (from 3.5 section):
" Collection- or map-typed properties of the target bean to be updated will be cleared and then populated with the values from the corresponding source collection or map." 

For a Car entity with passengers (Person), my mapper looks like this: https://gist.github.com/nocquidant/eefd659dba7384d72c6d

What would be the "best practice" here (my updateCarFromDto method is C/P from the generated mapper, except for 1 line)?

P.S. It would be nice to be able to use a method like (instead of clear/populated):
```
public void updatePersonListFromDto(List<PersonDto> dtos,  @MappingTarget List<Person> entities)
```

Thanks,
//nick

**Comment by sjaakd** [comment]
Hi Nick, would this be the same functionality as is proposed in #487 . You see, I planned to do selection of update methods in steps (its quite large in its entirety. I'll continue discussing there so that we have all info available whenever I get around to do this.

**Comment by nocquidant** [comment]
Thanks for pointing me out #487.
Regards

**Comment by sjaakd** [comment]
Sure. No problem. I added some more ideas around that one in the mean time.
