### ISSUE TITLE
Behavior for null collections / maps in Map/Iterable mapping methods

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#528]
In update methods (@MappingTarget), if you include an null source collection / map, the code currently does not touch the target collection (no clear). 

We should discuss if that's correct and write it down as a general approach somewhere.

**Comment by sjaakd** [comment]
need to add a reproducer otherwise close

**Comment by thunderhook** [comment]
I think this is covered with #1830 now. I'll close this issue.
