### ISSUE TITLE
NullValueMappingStrategy.RETURN_DEFAULT generates invalid code for arrays

### ISSUE THREAD

**Issue by DCstewieG** [mapstruct/mapstruct#534]
My mapper:

    @Mapper
    public interface MyMapper
    {
        MyObjectB[] map(MyObjectA[] array);
    }

Generated code:

    @Override
    public MyObjectB[] map(MyObjectA[] array) {
        if ( array == null ) {
            return new MyObjectB[];
        }
    
        ...
    }

 Should be:

    return new MyObjectB[0];

**Comment by agudian** [comment]
Fixed. Thanks for the report, @DCstewieG!
