### ISSUE TITLE
Wildcard generics do not work together with @TargetType

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#542]
I noticed that the generated code when using extends bounds (such as in #527) will cause problems with the `@TargetType` annotation (determining which super type should be returned).

**Comment by gunnarmorling** [comment]
Could you add an example for this situation? Do you think we should fix it in 1.0? If it affects corner cases only, we also could do it in a bugfix release 1.0.1 in order to get the Final out.

**Comment by sjaakd** [comment]
```java
@Mapper
public interface Converter {

    void map(Source source, @MappingTarget Target target);

    default void map(List<? extends Converter.SourceApple> sources, List<Converter.TargetApple> targets) {
        // some logic calling mapping method below..
    }

    void map( SourceApple source, @MappingTarget TargetApple targetApple);

    public static class Source {

        private List<? extends SourceApple> apples;

        public List<? extends SourceApple> getApples() {
            return apples;
        }

        public void setApples(List<? extends SourceApple> apples) {
            this.apples = apples;
        }
    }

    public static class Target {

        private List<TargetApple> apples;

        public List<TargetApple> getApples() {
            return apples;
        }

        public void setApples(List<TargetApple> apples) {
            this.apples = apples;
        }
    }

    public static class SourceApple {

    }

    public static class TargetApple {

    }
}
```
gives an error: `org.junit.ComparisonFailure: [Compilation failed. Diagnostics: [DiagnosticDescriptor: ERROR Converter.java:11 Can't map Collection element "org.mapstruct.ap.test.bugs._527.Converter.SourceApple apples" to "org.mapstruct.ap.test.bugs._527.Converter.TargetApple apples". Consider to declare/implement a mapping method: "org.mapstruct.ap.test.bugs._527.Converter.TargetApple map(org.mapstruct.ap.test.bugs._527.Converter.SourceApple value)".]] 
`

**Comment by sjaakd** [comment]
I cannot reproduce this problem.. Above code is not valid (@MappingTarget forgotten).. So'll continue to close this issue.
