### ISSUE TITLE
Superflous imports for Map and List

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#544]
run: org.mapstruct.ap.test.collection.CollectionMappingTest

**Comment by sjaakd** [comment]
I think I fixed this one a zillion times :smile: (all in different spots). Perhaps @agudian  can come up with a nice UT to test for superfluous imports :bulb: . Something along the lines of running an IDE import optimizer on the generated code and check if it changed.

**Comment by agudian** [comment]
Could be that I introduced this one with my latest missing-import fix. I checked a couple of other tests but didn't see this one. 

Anyway. I thought about running checkstyle on the generated code some time ago. This would be a great application for this. I'll try that... :-)

**Comment by agudian** [comment]
I just took a closer look and it's there quite a while now...

**Comment by sjaakd** [comment]
> Could be that I introduced this one with my latest missing-import fix. I checked a couple of other tests but didn't see this one.

Could be that I introduced that myself somehow :smile: .. Anyway, preventing such introduction of problems is a valuable addition to our test harnas.

**Comment by agudian** [comment]
Yeah, I thought so, too. If you have an idea how to solve this in a nice way, feel free to grab my PR with the test extension and add that fix there :-)

**Comment by sjaakd** [comment]
Always first blame somebody else.. :smiling_imp: I'll have a shot at it..

**Comment by sjaakd** [comment]
merged & fixed.
