### ISSUE TITLE
Add customization for generated class names/bean names

### ISSUE THREAD

**Issue by ggtools** [mapstruct/mapstruct#556]
When using the Spring component model, the generated classes are annotated with `@Component`. With this default configuration Spring will use the class name as the *bean* name. While this ok most of the time it might lead to name collisions if your mapper has a very common name such as `ParameterMapper`

The solution could be either to make the implementation prefix customizable or have a way to add a qualifier to the `@Component` annotation

**Comment by gunnarmorling** [comment]
Thanks for the report! You are the second one to bring up this request :)

Would it work for you if we made this customizable through `@Mapper`/ `@MapperConfig`?

    @Mapper(implSuffix="MySuffix")?
    public class MyMapper { ... }

**Comment by ggtools** [comment]
Yes that'll be perfect.

**Comment by gunnarmorling** [comment]
Cool, would you maybe be interested in preparing a pull request for this? We've scheduled the RC1 for next week, I won't be able to do it myself by then, not sure about the others :) It should be a good one to get into the code base, just follow up how other `@Mapper(Config)` properties are handled and pass the file name to the template writer.

**Comment by ggtools** [comment]
I'll try to find some time to prepare a PR so it can be included in the next release.

**Comment by gunnarmorling** [comment]
Awesome, you rock, @ggtools!

**Comment by ggtools** [comment]
Still try to work on this although time is a rare resource

**Comment by gunnarmorling** [comment]
Cool, thanks for the update, @ggtools. We've moved the CR1 to next week now. If it's not in there, it's no big deal as we can do follow-up releases very soon just as needed.

**Comment by gunnarmorling** [comment]
I am moving this to 1.1 for now; But if have a PR for this some time soon, we can do a CR2 including that feature.

**Comment by agudian** [comment]
Fixed. Thanks, @ggtools!

**Comment by Hamzaaton** [comment]
Hi @gunnarmorling, the "Impl" suffix worked (and still works) fine.  
I am trying to obfuscate my code source, so all the class names are modified to (a, b, c, d..), and I get a conflict for the Mappers and other Components. 
Is it possible to add an option that allows to generated Component to hava a name with which we can call with the Qualifier annotation?

**Comment by Z-100** [comment]
I don't know if I'm the only one, but for me the `implementationName = "Something"` only worked while using it in the parentheses after @Mapper. @MapperConfig didn't work.

**Comment by filiphr** [comment]
@Z-100 this issue was closed 6 years ago. If something is not working then please create a new issue.
