### ISSUE TITLE
Make error message more descriptive if no private collection mapping can (implicitly) be generated

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#558]
Currently it states:

> No implementation can be generated for this method. Found no method nor implicit conversion for mapping source element type into target element type.

But it should mention the affected source/target property.

**Comment by sjaakd** [comment]
duplicate of #512

**Comment by gunnarmorling** [comment]
Ah, cool. Wasn't aware of the original one. Thanks for spotting it and fixing #512 :)
