### ISSUE TITLE
There is no version anymore in the generated @Generated annotation.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#563]

**Comment by agudian** [comment]
What? Where? How? Really?

I just ran `VersionInfoTest#includesCommentAndTimestamp` and it worked...

**Comment by sjaakd** [comment]
Hmm.. for me it doesn't :smile: 
```java
package org.mapstruct.ap.test.versioninfo;

import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-05-29T23:34:44+0200",
    comments = "version: , compiler: javac, environment: Java 1.8.0_05 (Oracle Corporation)"
)
public class SimpleMapperImpl implements SimpleMapper {

    @Override
    public Object toObject(Object object) {
        if ( object == null ) {
            return null;
        }

        Object object_ = new Object();

        return object_;
    }

}
```

**Comment by agudian** [comment]
Try building with maven before you execute the test again... or check the integration tests. Or what do you do? I just tried different stuff again, always found the version right there...

**Comment by sjaakd** [comment]
I just ran: `VersionInfoTest#includesCommentAndTimestamp`, as focussed test method.. Of course..  my mistake.. No Maven in there...
