### ISSUE TITLE
MapStruct.org: Documentation-Nav Panel grows too long

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#569]
I just noticed that our navigation panel on the right is getting too long. On smaller screens (or smaller browser windows), the "Contents" list is cropped.
We might need to think about some restructuring of the site, eg. to add chapters with sections. In the nav-bar, only the current chapter would need to be expanded to reveal the underlying sections... Or something like that...

Any ideas?

**Comment by gunnarmorling** [comment]
+1 For revisiting the docs in general and their structuring. I also noticed that the top-level structuring of the docs grew too long. It should not be more like 8 chapters or so. We also might hight the ToC an smaller screens.

I also would like to convert that to AsciiDoc, which will give us easier editing, a generated ToC etc. Probably we should upgrade to the latest awestruct as a first step. Btw. let's have issues related to the web-site in the mapstruct/mapstruct.org repo. There is one issue for the Eclipse update site already.

**Comment by gunnarmorling** [comment]
A menu with sub-items such as http://getbootstrap.com/css/ would be great. I believe this needs Bootstrap 3 though which will require us to update the site first (I tried quickly and the layout is broken as many CSS classes where renamed from Bootstrap 2 to 3...).

**Comment by gunnarmorling** [comment]
@agudian Do you know whether there is a way to move an issue to another project? This one should better live under the mapstruct.org repo (in fact I create a duplicate of this just the other day).

**Comment by agudian** [comment]
Not that I know of, now. But then let's just close this one here.
