### ISSUE TITLE
Error using ObjectFactory with componentModel = "spring"

### ISSUE THREAD

**Issue by deepu105** [mapstruct/mapstruct#573]
When `@Mapper(componentModel = "spring", uses = {ObjectFactory.class}` is used on a JAXB classes the generated code assumes that `ObjectFactory` is availeble for DI and generates below in the Impl class. In my case the `ObjectFactory` is in a Jar and is not declared as a spring component/bean.

```
@Autowired
private ObjectFactory objectFactory;
```

Is this the intended behaviour or a bug

**Comment by gunnarmorling** [comment]
This is "working as designed". All the dependencies of a mapper are obtained through the configured component model. So you need to configure a Spring bean for `ObjectMapper`, e.g. through a `@Bean` annotated method of a configuration class.

**Comment by deepu105** [comment]
OK thanks for the clarification
