### ISSUE TITLE
Missing resolution of generic type-vars of property accessors

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#574]
I have came across a bean class structure with a generic abstract superclass:

```java
public abstract class AbstractIdHoldingTo<ID> {
    private ID id;
    public ID getId() {..}
    public void setId(ID id) {..}
}
public abstract class AbstractTo extends AbstractIdHoldingTo<Long> {
}
public class TargetTo extends AbstractTo {
}
```

When mapping from/to TargetTo, MapStruct doesn't get that the property type of `id` is `Long`.

**Comment by agudian** [comment]
The good thing is that we have everything in place already (the trick in `TypeFactory.getMethodType()` that uses `asMemberOf(..)`), which made the fix fairly simple.

Pull-Request follows right away.

**Comment by gunnarmorling** [comment]
Done.
