### ISSUE TITLE
Assignability-check for @MappingTarget in before-/after-mapping methods is wrong

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#576]
I stared at those lines of code so many times, and yet, it doesn't work as I wanted it to. For example:

```java
public abstract class BaseDto {..}
public abstract class CarDto extends BaseDto {..}

@Mapper
public abstract class CarMapper {
   public abstract CarDto toCarDto(Car entity);

   @AfterMapping
   public void registerMapping(@MappingTarget BaseDto anyBaseDto) {
       ...
   }
}
```

I would expect that for the mapping to `CarDto`, the invocation of the callback `registerMapping` is generated, as the result type `CarDto` is assignable to the `@MappingTarget` parameter. But that currently only works if the `@MappingTarget` parameter is `java.lang.Object` (as in the unit-tests), or if it is the same type as the mapping result type.

**Comment by gunnarmorling** [comment]
> I would expect that for the mapping to CarDto, the invocation of the callback registerMapping is generated

+1, that'd be my expectation as well.

**Comment by gunnarmorling** [comment]
Done.
