### ISSUE TITLE
No null check when converting from XMLGregorianCalendar to LocalDate

### ISSUE THREAD

**Issue by CyNoSureDev** [mapstruct/mapstruct#580]
The generated mapping for mapping from XMLGregorianCalendar fields to LocalDate fail if the from field contains a null value.

Snippets (generated code):
```java
 obj.setDeliveryDate(LocalDate.parse(xmlGregorianCalendarToString(xmlGregorianCalendar, null))
```
```java
if (date != null) {
    dto.setDeliveryDate(stringToXmlGregorianCalendar(DateTimeFormatter.ISO_LOCAL_DATE.format(date), null));
}
```

**Comment by agudian** [comment]
Yep, that's not cool. There should be a null-check on `xmlGregorianCalendar` in the first snippet, just as it is generated for the second one.

Thanks for the report!

**Comment by gunnarmorling** [comment]
Done.
