### ISSUE TITLE
Cannot create a method where the returned object is a String 

### ISSUE THREAD

**Issue by zamrokk** [mapstruct/mapstruct#584]
Hi ,
i try to create a map function like this (used by more complex other mapping functions) :  

@Mapping(source="dto.field1")
String dtoToString(Dto dto);

Actually, a "target" is required if i use the "source". Same issue using "expression", a "target" is needed.

How can i make it ?

**Comment by gunnarmorling** [comment]
MapStruct generally operates on Java beans, i.e. it expects properties on the source and target objects. For your case I'd just make the mapper an abstract class and implement the method from hand (code generation would give you no advantage really):

    String dtoToString(Dto dto) {
        return dto.getField1();
    }

That method can then be used by other (generated) methods for mapping a DTO property into a string property. Instead of declaring this manually written method on an abstract mapper itself you also can declare it on another class and import it through `@Mapper#uses()`.

**Comment by zamrokk** [comment]
The original requirement is coming from cascade calls in fact, ordered as below :

@Mapping(source="entitySet",target="stringList")
Object1 mapTo(Object2 o2);

List<String> dtoToStringList(Set<Entity> entitySet);

@Mapping(source="code")
String dtoToString(Entity e);


Maybe is more clear like this

i just wanted to ask the most simple question first

**Comment by gunnarmorling** [comment]
`Object1 mapTo(Object2 o2);` and `List<String> dtoToStringList(Set<Entity> entitySet);` should be fine to be generated once you have your manual DTO-to-String method in place.

**Comment by zamrokk** [comment]
ok thank you :+1: 

This confirms well the case

**Comment by anatoliy-balakirev** [comment]
It's really pity that Mapstruct does not support that. In case when there are a lot of classes like that and they are nullable - creating that code manually introduces some boilerplate, which would be great to avoid.

**Comment by anatoliy-balakirev** [comment]
@gunnarmorling as [there is](https://github.com/mapstruct/mapstruct/issues/1355) now an implicit mapping between `String` and `java.util.Currency`, plus, with addition of records to the Java language, there are now potentially many "wrapper" classes around the `String`, does it make sense to review this and extend Mapstruct to support that type of conversion explicitly?

**Comment by filiphr** [comment]
@anatoliy-balakirev I think that it might be worthwhile to look into support some kind of value type mapping. Can you please create a separate issue for this?
