### ISSUE TITLE
why "expression" on @Mapping is not calling other map functions ?

### ISSUE THREAD

**Issue by zamrokk** [mapstruct/mapstruct#585]
For a mapping of a field, I want to select on the source object the first element of the list.
As an Xpath style-like using the "/bookstore/book[1]" , i try to  recreate this in mapstruct

    @Mapping(expression  = "java(gedDocumentEntity.getGedDocumentAttenteEntities().iterator().next())", target = "gedDocumentAttenteDto")
    DocumentGedViewDto maptTo(GedDocumentEntity gedDocumentEntity );

    DocumentAttenteGedDto entityToDto(GedDocumentAttenteEntity entity);

The code is compiling as expected but i got an error on the implementation as below 

    incompatible types: fr.convergence.modele.parametrage.GedDocumentAttenteEntity cannot be converted to fr.convergence.ged.attente.dto.DocumentAttenteGedDto

I conclude that the second map function is not called in cascade because i have this on the generated code : 

            documentGedViewDto.setGedDocumentAttenteDto( gedDocumentEntity.getGedDocumentAttenteEntities().iterator().next() );

**Comment by zamrokk** [comment]
i answer myself adding the function "entityToDto" directly on "expression" like this : 

    expression  = "java(entityToDto(gedDocumentEntity.getGedDocumentAttenteEntities().iterator().next()))"

it looks to work as a workaround  :+1:

**Comment by gunnarmorling** [comment]
As you found out already, the given expression is passes "as is" to the target setter. No further conversions are applied (MapStruct doesn't analyze the expression, so there is no way of knowing the type of the expression outcome). I am going to close this one, as this really "works as designed".

**Comment by atomcat1978** [comment]
@gunnarmorling Couldn't ResultType be used here to define the returning type. This way MapStruct could do an automatic mapping.

**Comment by filiphr** [comment]
@atomcat1978 it cannot, currently MapStruct takes the given expression "as is" without any checks. 

What you can do is to have some generic util mapping method that will return you the first element of a list. Have a look at the `mapstruct-iterable-to-non-iterable` example from the [mapstruct-examples](https://github.com/mapstruct/mapstruct-examples). Currently MapStruct will pick up the mapping correctly if the helper method is not generic, but in theory it should pick it up
