### ISSUE TITLE
Empty constant String result in unmapped target property

### ISSUE THREAD

**Issue by paul999** [mapstruct/mapstruct#588]
```
public interface CodeSpaceConstants {
    String CS_CONSTRUCTION_STANDARD = "";
    String CS_WELLHEAD_PROTECTOR = "";
}
```

```
    @Mappings( {
        @Mapping( target = "codeSpace", constant = CodeSpaceConstants.CS_CONSTRUCTION_STANDARD )
    })
    abstract ConstructionStandardType toConstructionStandardType( String value );
```
Results in
Unmapped target property "Codespace"

while expected
Mapped to empty String.

**Comment by gunnarmorling** [comment]
Hum, that's a tough one. Because we cannot really distinguish constant from not being given at all vs. being given with the empty string. Same for expression() and source(), the empty string is the default value for all of these. One solution would be to come up with a "magic value" representing null as the default value. But it would have to be something which is not a legal, constant, expression or source name.

**Comment by agudian** [comment]
I think that's not possible at all, as we treat the `constant` expression for Strings as literals - and there is no invalid String literal that we could use as "default" in the annotation definition.

As a workaround, this is possible:
```java
    String EXPR_EMTPY_STRING = "java( \"\" )";

    @Mapping( target = "codeSpace", expression = EXPR_EMPTY_STRING) 
    ConstructionStandardType toConstructionStandardType( String value );
```

**Comment by gunnarmorling** [comment]
If we use something which is not a legal Java identifier - such as `%NULL%` - it should be alright. No one would ever want to use that as an actual value for `constant`, `expression` or `source`.

**Comment by agudian** [comment]
Once #618 is fixed, we should be able to solve this quite nicely.

**Comment by gunnarmorling** [comment]
Done. Turns out the JSR 269 API allows to distinguish the case where the value explicitly set to the default value of the attribute from the case where no value is given and thus the default applies. Thus setting `constant=""` can be supported now.
