### ISSUE TITLE
@DecoratedWith with componentModel=spring not working

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#592]
No class implementing/extending the decorator is generated.

The spring integration test should be extended to verify that the solution is working correctly. The test should include two decorated mappers to check that two different mappers with the same qualifier are supported by spring the way we imagine it to work.

See also #568 - the javadoc / documentation needs an upate and perhaps the created integration-test can serve as a base for the code-examples.

**Comment by gunnarmorling** [comment]
There is a test for this: https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/main/java/org/mapstruct/itest/spring?

**Comment by agudian** [comment]
But you could leave out the `@DecoratedWith` and it would still (almost) work. What's missing is that if you have a mapper with more than one method and you decorator doesn't decorate all of the methods (and thus is abstract), then we don't generate an implementation (extending the decorator class) that just delegates to the plain mapper. I always thought that was the point of `@DecoratedWith`.

Or is the current behaviour what you expected and the thing I'm calling a bug here is just a missing improvement?

**Comment by gunnarmorling** [comment]
> then we don't generate an implementation (extending the decorator class) that just delegates to the plain mapper.

Hum, that'd be a bug indeed. I am surprised though that this is the case.

**Comment by agudian** [comment]
I've started up fixing it and will try to do the same for jsr330 (where we have the same problem).

**Comment by reylibutan** [comment]
Is there a fix for this now? I have an abstract Decorator and it is never injected.

**Comment by agudian** [comment]
The fix is waiting in pull-request #599 - it still needs some review, especially on the jsr330 part, and some javadoc enhancements. But if you like, you can grab it from there and give it a try - should work smoothly for spring.

**Comment by gunnarmorling** [comment]
Thanks, @agudian! Sorry btw. for being so slow in reviewing the pending PRs
:/ I have been quite busy with other things recently, but I hope to come
back to those PRs soon. It's about time to cut a CR2 release with these
fixes (and maybe some others).

**Comment by agudian** [comment]
Fixed for Spring and JSR 330.
