### ISSUE TITLE
@Mapper(componentModel = "spring") not working

### ISSUE THREAD

**Issue by reylibutan** [mapstruct/mapstruct#593]
I have a mapper defined like this

```java
@Mapper(componentModel = "spring")
public interface UserMapper {
    //code here
}
```

I am getting it like this

```java
@Autowired
private UserMapper userMapper;
```

But I get this exception
`No qualifying bean of type`

I don't know if this should work as is or do I need to do some more config somewhere?
I also tried, adding

```xml
<option>
    <mapstruct.defaultComponentModel>spring</mapstruct.defaultComponentModel>
</option>
```

**Comment by gunnarmorling** [comment]
Have you made the Spring container aware of the user mapper bean? To do so, either enable component scanning or explicitly register the bean in the application context. You can check out [this test](https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/test/java/org/mapstruct/itest/spring) for an example using Spring's programmatic configuration.

**Comment by gunnarmorling** [comment]
Have you made the Spring container aware of the user mapper bean? To do so, either enable component scanning or explicitly register the bean in the application context. You can check out [this test](https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/test/java/org/mapstruct/itest/spring) for an example using Spring's programmatic configuration.

**Comment by gunnarmorling** [comment]
Have you made the Spring container aware of the user mapper bean? To do so, either enable component scanning or explicitly register the bean in the application context. You can check out [this test](https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/test/java/org/mapstruct/itest/spring) for an example using Spring's programmatic configuration.

**Comment by gunnarmorling** [comment]
Have you made the Spring container aware of the user mapper bean? To do so, either enable component scanning or explicitly register the bean in the application context. You can check out [this test](https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/test/java/org/mapstruct/itest/spring) for an example using Spring's programmatic configuration.

**Comment by gunnarmorling** [comment]
Have you made the Spring container aware of the user mapper bean? To do so, either enable component scanning or explicitly register the bean in the application context. You can check out [this test](https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/test/java/org/mapstruct/itest/spring) for an example using Spring's programmatic configuration.

**Comment by gunnarmorling** [comment]
Have you made the Spring container aware of the user mapper bean? To do so, either enable component scanning or explicitly register the bean in the application context. You can check out [this test](https://github.com/mapstruct/mapstruct/tree/master/integrationtest/src/test/resources/springTest/src/test/java/org/mapstruct/itest/spring) for an example using Spring's programmatic configuration.

**Comment by reylibutan** [comment]
Hi, I believe component scanning is enabled since I am getting all other beans correctly. (@Services, @Repository etc). Am I supposed to register the interface or the generated impl?

**Comment by reylibutan** [comment]
Another thing overlooked on my end. I did not re-generated mapper imeplementations after adding so it was still using the previously generated implementations.

To others who are experiencing this, just make sure to regenerate mapper implementations after putting `componentModel`.

```java
@Mapper(componentModel = "spring")
```

**Comment by PFStruct** [comment]
I am having the same issue. Can you please clarify what was done to resolve?
