### ISSUE TITLE
Test on properties in method with @mappingtarget

### ISSUE THREAD

**Issue by bbonnin** [mapstruct/mapstruct#596]
Hello,

Suppose I have :
```java
@Mapper(componentModel="default")
public interface PersonMapper {
 
    PersonMapper INSTANCE = Mappers.getMapper( PersonMapper.class );
     
    void mapCarToCarDto(Car from, @MappingTarget CarDto into);
    
    void mapPerson(Person from, @MappingTarget PersonDto into);
}
```
where a car is a property of a person.

The generated `PersonMapperImpl` is :
```java
public class PersonMapperImpl implements PersonMapper {

    @Override
    public void mapCarToCarDto(Car from, CarDto into) {
        if ( from == null ) {
            return;
        }

        into.setSeatCount( from.getNumberOfSeats() );
        into.setModel( from.getModel() );

    }

    @Override
    public void mapPerson(Person from, PersonDto into) {
        if ( from == null ) {
            return;
        }

        into.setName( from.getName() );
        if ( into.getCar() == null ) {
            into.setCar( new CarDto() );
        }
        mapCarToCarDto( from.getCar() , into.getCar() );
    }
}
```
My problem is in the `mapPerson` method, if the `from` person has no car, the `into` person will get one ! I think the test should be something like that :
```
    if ( from.getCar() != null && into.getCar() == null ) {
            into.setCar( new CarDto() );
    }
    mapCarToCarDto( from.getCar() , into.getCar() );
```
Thanks

**Comment by gunnarmorling** [comment]
Hum @sjaakd, I agree, this seems not the right behavior. WDYT?

**Comment by gunnarmorling** [comment]
Hum @sjaakd, I agree, this seems not the right behavior. WDYT?

**Comment by gunnarmorling** [comment]
Hum @sjaakd, I agree, this seems not the right behavior. WDYT?

**Comment by sjaakd** [comment]
@gunnarmorling : I think you closed this one accidentally, right? 

In general: The intention is that the target object graph should follow the source object graph. So, missing objects should be created. I reckon that the proposed addition is correct.

Note: that also means that a pre-existing target property will be set to null when null in the source.

**Comment by gunnarmorling** [comment]
> @gunnarmorling : I think you closed this one accidentally, right?

Oops, yes. Re-opened it.

> So, missing objects should be created. [...] a pre-existing target property will be set to null when null in the source.

+1 That's the way it should be. So it should look like that altogether:

    if ( from.getCar() != null ) {
        if ( into.getCar() == null ) {
            into.setCar( new CarDto() );
        }
        mapCarToCarDto( from.getCar() , into.getCar() );
    }
    else {
        if ( into.getCar() != null ) {
            into.setCar( null );
        }
    }

**Comment by agudian** [comment]
Does it make any sense to call mapCarToCarDto if into.getCar() is null? The state of 'into' can't be changed there.

**Comment by gunnarmorling** [comment]
if `into.getCar()` is null, it will be populated with a new instance prior to the `mapCarToCarDto()` call.

**Comment by sjaakd** [comment]
I think that the provided code snippet achieves the same (in condensed form), right?:
```java
    if ( from.getCar() != null && into.getCar() == null ) {
            into.setCar( new CarDto() );
    }
    mapCarToCarDto( from.getCar() , into.getCar() );
```
I guess we agree that target should follow the source. Also in case the source is null ('just another value as far as I'm concerned').  So in the provided snippet, the `mapCarToCarDto` is responsible for populating the target with null. If its generated I believe it does (see generated code at start of this issue). For HW mapping methods the same applies as for 'create' methods.

BTW: We should have the same logic to prevent NPE's in case of conversions or a conversion prior to calling the `mapCarToCarDto` and follow the same reasoning for the issue that @agudian suggested for #580. And... we should put it somewhere in our design documentation (I've got a feeling this discussion will raise its head more often :smile: ).

**Comment by gunnarmorling** [comment]
> So in the provided snippet, the mapCarToCarDto is responsible for populating the target with null.

How would that work? `mapCarToCarDto()` does not have access to the owning person, right? So it cannot set the person's car to null in this case.

**Comment by sjaakd** [comment]
> How would that work? mapCarToCarDto() does not have access to the owning person, right? So it cannot set the person's car to null in this case.

hmmmmm... you might have a point there :+1:

**Comment by gunnarmorling** [comment]
Done.
