### ISSUE TITLE
Automatically create (private) mapping methods to map nested properties

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#60]

**Comment by agudian** [comment]
What I meant here were forged methods for bean properties.

**Comment by gunnarmorling** [comment]
@agudian Is there actually anything left to be done here? we already create forged methods for mapping nesting props, right? If that's not what you have in mind, could you add an example?

**Comment by agudian** [comment]
Example:
```java
class Car {
    private SteeringWheel steeringWheel;
    private List<Seat> seats;
...
}
// classes CarDto, SteeringWheel, SteeringWheelDto, Seat, SeatDto look equally dull and don't contain any property name differences
```

In my Mapper, I'd like to just write:
```java
@Mapper
interface CarMapper {
  CarDto toCarDto( Car car );
  Car toCar( CarDto dto );
}
```

Right now, we report errors on unmappable target properties, and suggest to declare mapping methods for SteeringWheel <-> SteeringWheelDto and Seat <-> SeatDto. 
The idea was to create  forged methods for those cases as well, so that I'd only have to declare them myself if I need to fine-tune the mapping or want to publicly expose those methods in my mapper interface.

We can't do that, yet, can we?

**Comment by sjaakd** [comment]
> We can't do that, yet, can we?

Nope.. But I would really like such a feature. Especially  in combination with #168 and #292 :smile:

**Comment by sjaakd** [comment]
@navpil thanks for the great work!
