### ISSUE TITLE
Feature Request: Possibility to provide default value

### ISSUE THREAD

**Issue by luxmeter** [mapstruct/mapstruct#600]
Hi guys,

First of all, I appreciate your work and I'm happy that MapStruct exists. Keep it up!

To my request:
I've encountered a situation where I want to define a default value in case the source attribute is null.
Something like that:
```
@Mapper(target="countryCode", source="country.code", default="DE")
```

I solved my problem through a workaround:
```
@Mapper(target="countryCode", expression="java((source.getCountry() != null) ? source.getCountry().getCode() : \"DE\";)")
```

Would be awesome if this code snippet could be generated automatically.

Thank you!

**Comment by sjaakd** [comment]
Hi @luxmeter .. We have a `@NullMappingStrategy`. Please checkout [here](http://mapstruct.org/documentation/#section-14). Perhaps this can be extended with a 'constant' parameter somehow. That 'constant' parameter would work in line with our current constant @gunnarmorling WDYT?

Best regards,
Sjaak

**Comment by luxmeter** [comment]
Am I right that the Strategy is applied to all cases where a null is encountered? I just want to specify default values for specific attributes.

Best regards

**Comment by sjaakd** [comment]
> Am I right that the Strategy is applied to all cases where a null is encountered? I just want to specify default values for specific attributes.

That's indeed right.

**Comment by gunnarmorling** [comment]
`NullValueMappingStrategy` applies to mapping methods themselves, but not single properties. Somehow re-using may lead to confusions IMO. Having a new attribute `@Mapping#defaultValue()` seems nicer to me.

**Comment by luxmeter** [comment]
Hi,

I decided to contribute and try to add the feature by myself. @agudian gave me already a little introduction. Let's see how far I come. I will inform you about my progress but will take some time...

BR

**Comment by gunnarmorling** [comment]
@luxmeter Thanks for giving this a try! Just let us know in case you hit any road blocks. So how would the behaviour around `defaultValue()` exactly be? I'd say it'd be ignored when using either `constant()` or `expression()` and only be used as default when accessing a source property (either implicitly or by `source()` being given, right?

**Comment by luxmeter** [comment]
@gunnarmorling Hi, that's also what I would say. Will try to implement it today. Let's see how far I come.

**Comment by luxmeter** [comment]
@gunnarmorling @agudian I have already a problem. I added the defaultValue property to the Mapping interface but it seems that neither the default value is read nor the user defined value set in the Mapping annotation in my mapper. The MappingPrism just returns null for the value. Could you take a look and tell me what I forgot? https://github.com/mapstruct/mapstruct/compare/master...luxmeter:issue-600

**Comment by luxmeter** [comment]
Ok.. you can forget my last post. Apparently, it was a generation / refreshing problem in my IDE. But I have another problem now. The defaultValue property of the mapping annotation is now available in the datamodel (PropertyMapping) but I can't figure out how can I access it in the FTL templates, e.g. in the SetterWrapper template. Any hints?

**Comment by luxmeter** [comment]
@gunnarmorling @agudian 
Soooooooooooooooooooooooooooooo.. I'm done but I'm not sure if it is implemented as you would expect (I'm also not so happy about it). A quick overview:
* Added a `defaultValue` property for the Mapping annotation (also for java8)
* If the `defaultValue` is set and the source type is not a primitive, the defaultValueAssignment is built
  - This is done by using the `ConstantMappingBuilder`. I bet that this is a overkill but I wasn't sure what I need really to build the assignment
* Adapted the BeanMappingMethod.ftl, PropertyMapping.ftl, NullCheckWrapper.ftl and SetterWrapper.ftl to render the assignment in case the defaultValueAssignment is available

Im excited to hear from you.

BR

**Comment by agudian** [comment]
Awesome, @luxmeter! Just create a pull-request of the current state and we can discuss it there properly.
I'm having some hardware-difficulties while migrating my dev-environment to another machine, so I can't try out your stuff just yet - I might need some more days or so.
What I already saw is how you enhanced the templates. Do I read that correctly that you don't do the null-check on the source property, but the outcome of a potential property mappping? 
Could you enhance your test case to cover the different scenarios for direct assignments, mappings with a property mapping method and property-mappings that use update-methods.

**Comment by luxmeter** [comment]
Hi,

> Do I read that correctly that you don't do the null-check on the source property, but the outcome of a potential property mappping?

Where do you see that? The assignment is done in the NullCheckWrapper.ftl and SetterWrapper.ftl. I add my defaulValueAssignment in the first case if the source propert is null. In the latter, I add the defaultValueAssignment if the `<@_assignment/>` is null. As far as I understood, this is the the source property. However, I check in the SetterWrapper.ftl if the source property is null after it has been already assigned to the target property because I was too lazy for complicated checks..

I added the additional tests and made a pull request.

**Comment by luxmeter** [comment]
Ups.. forgot the test for direct assignment but I don't know what do you mean. I thought it is not possible to assign directly a value (without using setter/getter).

**Comment by agudian** [comment]
The code by @luxmeter is merged, but I guess we should also add a doc-update. I can handle that, I need to document some other stuff as well anyway.
