### ISSUE TITLE
Add processor option to suppress warnings

### ISSUE THREAD

**Issue by aklemp** [mapstruct/mapstruct#601]
Hi,

I just evaluated this project and it seems very nice, slim and efficient compared to a lot of other tools/approaches I used in the past. However, I propose an additional parameter for the annotation processor. Something like "mapstruct.suppressWarnings" that will add

``` java
@SuppressWarnings("all")
```

to the generated mapper classes. The motivation is the usage in an IDE where all source folders have the same warning configuration and for example missing javadoc leads to warnings.

Kind regards,
  aklemp

**Comment by gunnarmorling** [comment]
Hi, couldn't you just disable these warnings for specific source folders such as _taget/generated-sources_? I am a bit reluctant to add such option as it will mask "real" errors (generally we go to great length to avoid warnings in the generated code in the first place). Also is "all" supported in a portable manner (i.e. in Eclipse/ejc and javac)?

**Comment by aklemp** [comment]
Hi,

unfortunetely, there is no way that I know of to configure these settings permanently per source folder (in Eclipse) without being overwritten on update project from Maven. Hidden "real" errors will not be a problem because they are no warnings. Instead of true/false for the parameter you could also take a comma separated list of warnings to ignore, so everyone can hide the ones, they are not interested in. There can also be warnings in generated code by lots of other tools (especially metrics tools). Usually these warnings don't make any sense in generated code. Being an optional parameter it would not hide any warnings if you don't want to.

Kind regards,
  aklemp

**Comment by agudian** [comment]
Just out of curiosity: what kind of warnings do you get for the generated code? Missing javadoc for the class or for any generated private methods?

**Comment by aklemp** [comment]
Hi,

yes, currently it is missing javadoc on classes and (CDI) injected nested mappers. But it is only a simple test project yet without any further metrics tools.

Kind regards,
  aklemp

**Comment by Sarev0k** [comment]
I have a similar issue.  I'm using a `@Mapping` expression, and my generated code is causing warnings in Findbugs, because of the null checks the generated code is doing and the fact that my custom expression could be dereferencing null.

I'd love to be able to annotate my Mapper interface in such a way where I could get `@SuppressFBWarnings` applied to the generated class.

**Comment by gunnarmorling** [comment]
@Sarev0k Can you share some of the generated code which causes the warning? Not sure whether it's of the usage of custom expressions but I'd rather avoid such warning on null dereferencing instead of suppressing it.

**Comment by Sarev0k** [comment]
Whoops, better late than never I guess.

Here's the source files I used to reproduce this:
```java
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public class Foo {
    @Nonnull
    public List<String> getBazs() {
        return new ArrayList<>();
    }

    public void setBazs(final List<String> bazs) {
    }
}
```

```java
import java.util.ArrayList;
import java.util.List;

public class Bar {
    public List<String> getBazs() {
        return new ArrayList<>();
    }

    public void setBazs(final List<String> bazs) {
    }
}
```

```java
import org.mapstruct.Mapper;

@Mapper
public interface FooMapper {
    Bar map(final Foo foo);
}
```

Generated output:
```java
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-05-23T17:51:35-0700",
    comments = "version: 1.2.0.Final, compiler: javac, environment: Java 1.8.0_171 (Oracle Corporation)"
)
public class FooMapperImpl implements FooMapper {

    @Override
    public Bar map(Foo foo) {
        if ( foo == null ) {
            return null;
        }

        Bar bar = new Bar();

        List<String> list = foo.getBazs();
        if ( list != null ) {
            bar.setBazs( new ArrayList<String>( list ) );
        }
        else {
            bar.setBazs( null );
        }

        return bar;
    }
}
```

Findbugs Error:
```
Bug type RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE (click for details)
In class FooMapperImpl
In method FooMapperImpl.map(Foo)
Value loaded from list
Return value of Foo.getBazs()
Redundant null check at FooMapperImpl.java:[line 22]
```

**Comment by filiphr** [comment]
Thanks @Sarev0k. Anytime is good.

Btw for this particular use case I think that https://github.com/mapstruct/mapstruct/issues/1243 would be a good fit

**Comment by ndvdh** [comment]
@filiphr Is there a timeline when this would be addressed? Thanks !

**Comment by Guchman** [comment]
USBR_UNNECESSARY_STORE_BEFORE_RETURN

**Comment by Zialus** [comment]
Hi @Sarev0k, how are you currently getting around this?

**Comment by filiphr** [comment]
From 1.6.0.Beta1 this can be fixed using `@AnnotateWith`.

e.g.

```java
@AnnotateWith(value = SuppressWarnings.class, elements = @AnnotateWith.Element(strings = "all"))
```

This can be put on the mapper or on the methods individually. In `strings` you can use whichever warning you want to suppress.
