### ISSUE TITLE
Java 8 - Cant use static method on interface with decorators.

### ISSUE THREAD

**Issue by martin0esteves** [mapstruct/mapstruct#603]
When adding a static method to an interface (java 8) for using in an expression the decorator created will try to override it and calling it using the mapper interface instance given to the decorator.

It tries to build a decorator instance that overrides mapA() and calls it using the delegate inside that method, which gives the following two errores while compiling:

- "error: method does not override or implement a method from a supertype"
- "error: illegal static interface method call" <--- Cant call interface static method using instances

Instead, I belive it should ignore the static method.

Code example that fails:

    @Mapper
    @DecoratedWith(IMapperDecorator.class)
    public interface IMapper {
        IMapper INSTANCE = Mappers.getMapper(IMapper.class);
      
        @Mapping(target = "atributeA", expression = "java( IMapper.mapA() )" )
        AtributeAClass mapToAtributeAClass(ClassWithA classWithA);
    
        static String mapA() { return null; }
    }

**Comment by gunnarmorling** [comment]
Hi @martin0esteves, thanks for the report. I am not surprised, we didn't not really take static (interface) methods into the consideration. Would you be interested in providing a fix maybe?

**Comment by martin0esteves** [comment]
Hello Gunnar, thank you for the offer. I would like to implment this fix but I´m short of time at the moment. Anyways, I do not discart coming back to implement it sometime.

**Comment by bedla** [comment]
Consider PR at https://github.com/mapstruct/mapstruct/pull/617 . Thx, Ivos

**Comment by agudian** [comment]
Merged the fix by @bedla.
