### ISSUE TITLE
Is there to Turn off Default Mapping

### ISSUE THREAD

**Issue by pjkant** [mapstruct/mapstruct#608]
Is there a way to turn off the default mapping.
Meaning when the field names are the same in the source and destination.
I am running into a date conversion issue.. 
I have an explicit mapper for that field defined it still generates the default mapping causing a Date parse exception..
Any ideas...

thanks.

**Comment by agudian** [comment]
Hmm, actually, if there is an explicit method defined for a mapping (to be generated or manually implemented), then that method should be used for the mapping - even if the source and target types already match.
Can you give us a code snippet of your source and target properties, your mapper and the explicit mapping method that you have?

**Comment by gunnarmorling** [comment]
@pjkant I'm going to close this one, as it's impossible to analyze without an actual example. As Andreas is saying, it should work. Feel free to re-open if you can provide a testcase demonstrating the issue. Thanks!

**Comment by pjkant** [comment]
thanks for looking into it..
it was a user error.. so sorry to bother u guys

thanks.
