### ISSUE TITLE
Testing generated

### ISSUE THREAD

**Issue by johnament** [mapstruct/mapstruct#609]
Hey, so we're looking at mapstruct and seems to fit everything we need except for testing aspects.  It seems like the key things missing are ways to verify that the annotations include a proper set of attributes and that's nothing missing.

Two ideas that popped up are 
- Make the mapping/mappings annotations runtime available so that tests can verify them.
- Leverage the generated sources rule in our tests to verify that the right output is what is expected.

As well as
- Other ideas as proposed here

So what do you think? Is making this available at runtime feasible?

**Comment by gunnarmorling** [comment]
Hi John, I am not sure I get 100% what you are after. You could test the generated mapper implementations and their behaviour. In other words, you could invoke a mapper method for a given input and assert the state of the resulting object. This should make sure the code generator is configured in the way you would like to have it.

> Make the mapping/mappings annotations runtime available so that tests can verify them.

Could you provide an example how that would look like / be used? At the moment, there is no runtime component provided by MapStruct (apart from the `Mappers` factory when working with the default component model). Do you have some API in mind? Or just changing the retention level of the annotation types?

> Other ideas as proposed here

Proposed where? Is there maybe a link missing?

**Comment by johnament** [comment]
Hi Gunnar, thanks for the response.  One of the ideas we're throwing around is to change the retention policy to runtime instead of class.  This way in a test we can inspect that the configuration includes all proper configuration settings.  We're also interested in seeing what recommendations you have for testing, for example do this to test out that a mapper includes all proper fields based on some control list provided.

**Comment by sjaakd** [comment]
Hi! What we do is create one test source object graph. Then make sure you have forward and reverse implemented. Feed the test source object to the mapper and apply reverse mapping on the result. Then use a handy tool called unitils to compare this with the original source object graph. Unitils has a handy 'assertReflectionEquals' to do that trick. Of course you can permute the source object to get a bigger coverage in additional test cases. As test framework Unitils used plain old Junit.

**Comment by johnament** [comment]
I was trying to go for something simpler.  To me, testing the mapper is fine, but realistically since its generated code should be outside the scope to test.  We wanted to do things like make sure if a new field were added to a POJO it were mapped appropriately, and not ignored.

**Comment by sjaakd** [comment]
Okay! In my case there are multiple mapping methods that could map a source to target property. Although MapStruct behaves in a logical way when selecting a mapping method, I'd still like to make sure that what I expect indeed happens. Hence I test the generated code as well

**Comment by gunnarmorling** [comment]
> change the retention policy to runtime instead of class. This way in a test we can inspect that the configuration includes all proper configuration settings.

The problem I see is that not all properties are necessarily configured by an annotation (no need if they can be mapped by default). Also just inspecting the annotations would basically assert your interpretation of the behaviour but it would not assert that the resulting mapper really does what you *meant* it to do.

As @sjaakd says I think you are indeed best off by writing a test for the generated mapper.

> make sure if a new field were added to a POJO it were mapped appropriately, and not ignored.

There is `Mapping#unmappedTargetPolicy()` for this in case new fields are added on the target side of a mapping (as an unpopulated field in the target of a projection indicates an over-sight). Depending on the setting, you'd get a compile error or warning then. Adding new properties on the source side I don't consider as problematic (e.g. a DTO usually represents just a view/projection of source data, it does not necessarily contain all the source properties).

But we could think about adding `unmappedSourcePolicy()` if that'd help you. I think there is even an issue for this already. Maybe you'd be interested in helping out with this feature?

**Comment by agudian** [comment]
Or do you want to assert that no unmapped target properties are simply ignored by some developers? Or that the mappers are not configured with unmappedTargetPolicy=IGNORE? For both things, you could also add custom rules in chrckstyle or sonarqube...
Perhaps you can give us an example of what you want to verify?

**Comment by johnament** [comment]
Actually i think `unmappedTargetPolicy` is what I'm looking for, short term.  `unmappedSourcePolicy` would also be good, since then we can control it from a programmatic standpoint.  Personally, I don't want to have to test the mapper (still consider it not my code) but it makes sense for now.

I guess I'll submit a ticket for the `unmappedSourcePolicy` option?

**Comment by gunnarmorling** [comment]
> I guess I'll submit a ticket for the unmappedSourcePolicy option?

+1, thanks!
