### ISSUE TITLE
Add `Mapping#unmappedSourcePolicy` to control failures to map newly added fields.

### ISSUE THREAD

**Issue by johnament** [mapstruct/mapstruct#610]
Adding this so that unmapped fields can optionally fail a build if no mapping present for the attribute.

**Comment by gunnarmorling** [comment]
Yes, this has been asked for before. In case you are interested in helping out with that one, let us know :)

**Comment by velo** [comment]
Anyone doing this? I think I will give it a shot!

**Comment by gunnarmorling** [comment]
@velo I am not aware of anyone working on this, so if like to give it a try, that's awesome! Let me know if you hit any roadblocks and I'll be glad to help.

**Comment by spoerri** [comment]
@velo did you make any progress? We'd like to use this too...

**Comment by velo** [comment]
I end up not needing it... only unmappedTargetPolicy was enough for me

**Comment by gunnarmorling** [comment]
Hey @spoerri maybe you'd like to give this a shot?

**Comment by spoerri** [comment]
No time for near future... and i'd probably go for https://github.com/mapstruct/mapstruct/issues/621 first.

**Comment by filiphr** [comment]
This has been integrated with #1282. Thanks @spoerri for the PR. I have opened #1317 to follow the ignoring.
