### ISSUE TITLE
Nested Mapper Interface not supported

### ISSUE THREAD

**Issue by Highbrainer** [mapstruct/mapstruct#611]
Hi, 

If the mapper interface (or abstract class) is nested into another class/interface, mapstruct won't work. 

For example, consider the following simple class:

``` java
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

public class ClassWithNestedMapper {
    @Mapper
    public interface MyMapper {
        MyMapper INSTANCE = Mappers.getMapper(MyMapper.class);
    }

    public static void main(String[] args) {
        System.out.println(MyMapper.INSTANCE);
    }
}
```

A call to the main method will fail :

``` java
java.lang.ClassNotFoundException: ClassWithNestedMapper$MyMapperImpl
    at org.mapstruct.factory.Mappers.getMapper(Mappers.java:82)
    at mapper.SecondClassWithNestedMapper$MyMapper.<clinit>(SecondClassWithNestedMapper.java:9)
    ... 1 more
Caused by: java.lang.ClassNotFoundException: ClassWithNestedMapper$MyMapperImpl
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.mapstruct.factory.Mappers.getMapper(Mappers.java:77)
    ... 2 more
```

because the `getMapper(...)` method tries to load class

``` java
clazz.getName() + IMPLEMENTATION_SUFFIX 
```

which resolves to `ClassWithNestedMapper$MyMapperImpl`

Though the fact is that the implementation class is generated as a standalone file - not nested into ClassWithNestedMapper obviously.

IMHO, the bug is on the generation side. Because two different classes in the same package may have nested interfaces with the same name. And I don't talk about interfaces nested into interfaces...
So I guess the solution will have to change the naming convention for the generated implementation and/or dispatch implementations into sub-packages according to the mapper nest hierarchie.

Example 2 : `ClassWithNestedMapper$MyMapper` and `AnotherClassWithNestedMapper$MyMapper` will collide in generating `MyMapperImpl.java` in the same directory.

``` java
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

public class AnotherClassWithNestedMapper {
    @Mapper
    interface MyMapper {
        MyMapper INSTANCE = Mappers.getMapper(MyMapper.class);
    }

    public static void main(String[] args) {
        System.out.println(MyMapper.INSTANCE);
    }
}

```

**Side note**
By the way, the generated mapper implementation does not compile anyway : it declares that it implements `MyMapper` instead of `ClassWithNestedMapper.MyMapper` ...!

I thank you in advance for your time and kind feedback. I think I can give a hand and draft a solution if that's needed.

Cheers!

**Comment by gunnarmorling** [comment]
Hey @Highbrainer, sorry for that super-late reply; I somehow missed this one when you filed it and only noticed it just now.

If you still are interested in helping out with this, that'd be much appreciated.

> So I guess the solution will have to change the naming convention for the generated implementation and/or dispatch implementations into sub-packages

Could just the outer and inner name be concatenated? I.e. the generated type would have the name `AnotherClassWithNestedMapper_MyMapper` here? Also the `Mappers` factory class would have to be adapted.

> By the way, the generated mapper implementation does not compile anyway...

At least that's working now, the required import is added to the generated file :)

**Comment by Tillerino** [comment]
I'll give this a go.
