### ISSUE TITLE
How to map existing target object?

### ISSUE THREAD

**Issue by reylibutan** [mapstruct/mapstruct#613]
Basically what I want to do is the following:
I have the following classes:
How do I map ClassB and its member variable ClassB2 to the same object ClassA?

```java
class ClassA {
    String f1;
    String f2;
    String f3;
}

class ClassB {
    String f1;
    ClassB2 b2;
}

class ClassB2 {
    String f2;
    String f3;
}

**Comment by psalchow** [comment]
One way to achieve this is to annotate your mapping from ClassB to ClassA as follows:

    @Mapping(target = "f2", source = "b.b2.f2"),
    @Mapping(target = "f3", source = "b.b2.f3")

If you do not like to annotate the path to your attributes exlicitly you can define the two mappers (from ClassB to ClassA and ClassB2 to ClassA). If you decorate one of the mapping you can call the other mapping within it.

**Comment by gunnarmorling** [comment]
@reylibutan Glad to see your question answered. Thanks, @psalchow!

Btw. the [MapStruct users group](https://groups.google.com/forum/?hl=en#!forum/mapstruct-users) is a better place for asking questions on MapStruct usage, this tracker here should be used for actual issues only (bug reports, feature requests etc.). Thanks!

**Comment by reylibutan** [comment]
Oh I didn't know about that group! That would be very helpful! Bookmarked.
