### ISSUE TITLE
compilation problem if a @Mapper interface use a @Mapper abstract class

### ISSUE THREAD

**Issue by zamrokk** [mapstruct/mapstruct#614]
Hi all,

i just realized that this combination doesnt work : 

@Mapper(uses = { GedMapper.class })
public interface DepotActesMapper ...
... somewhere using implicitely a map function from abstract class below 

@Mapper
public abstract class GedMapper ...
... here a map function that will be used

i got compilation problems. I suppose the interface is compile before the abstract class or something else because the error is that the interface cannot see the mapping function on the abstract class 

Coul you bring more information about it ?

Thanks

**Comment by agudian** [comment]
What's the visibility of the method in the abstract class? Could give us a more elaborate example? Because it should actually work :wink:

**Comment by zamrokk** [comment]
you are right , i switched from an interface to an abstract class. When i changed to abstract i forgot to change the visibility of the method to public. As the 2 classes below are not in the same package, compilation had failed.

Good intuition !   ;-)
