### ISSUE TITLE
Conflict between Apache CXF and mapstruct

### ISSUE THREAD

**Issue by Code-Herder** [mapstruct/mapstruct#615]
Hello,

It seems there is a conflict between Apache CXF and mapstruct. When I have both plugins in my pom the Apache CXF code generation plugin will generate the code alright but it seems it's not ready for mapstruct to pick it up and do the code generation ( that's my rough guess of what's happening ).

In maven, with -X the crash happens inside org.bsc.maven:maven-processor-plugin:2.2.4 and the compile errors I get beforehand are the compiler not finding the classes generated by Apache CXF.

A "fix" to this issue is:
1. Remove the mapstruct plugin from the pom.
2. Compile once to generate the code and have the classes compiled.
3. Re add mapstruct and watch it do it's thing correctly now.

**Comment by Code-Herder** [comment]
Erm, I read a bit more and it seems this is completely my fault. You can't expect two code generator to live in the same pom like this when one depends on the other.

**Comment by agudian** [comment]
> You can't expect two code generator to live in the same pom like this when one depends on the other.

Well, actually, you can. The CXF-plugin runs in the maven-lifecycle phase "source-generation", which is the same as the maven-processor-plugin runs in by default. If you have two plugins that run in the same lifecycle-phase, the order of the declarations in `<build><plugins>..</plugins></build>` is used as execution order for the plugins. So if you want to make sure CXF runs before maven-processor-plugin, you have to declare them in that order.

But you're right, that's not a mapstruct issue.

**Comment by gunnarmorling** [comment]
+1 to what @agudian says. Maybe we can add an example to our _mapstruct-examples_ project? The combination of the two seems not too uncommon.

**Comment by Code-Herder** [comment]
Well, my CXF code is generated correctly, but my mapstruct mappers use the resulting classes from CXF code generator. From what I understood of the callstack it simply wasn't finding the objects to do it's job.

Sorry, I'm still new to maven but it looks to me as if this is what is happening.

**Comment by ja1979** [comment]
Hi... I had a similar issue using **maven-processor-plugin** and **cxf plugin**. When they are used individually they work well but when used at the same time **maven-processor-plugin** fails with message "[ERROR] error on execute: error during compilation"

I found a solution changing the behavior of **maven-processor-plugin**. I set **true* to the parameter **addCompileSourceRoots**. In this way it include source code generate from **CXF**.

I my case it work smoothly. Hope it helps!

**Comment by ja1979** [comment]
What I suggested previously works OK when no generated code exist (after a clean), but I got a error compiling code when generated code already exist so I removed that parameter and set a new one:

`<additionalSourceDirectories>${project.build.directory}/generated/cxf</additionalSourceDirectories>`

...in the **maven-processor-plugin** section of the pom.xml.
