### ISSUE TITLE
Better way to distinguish between defined and undefined annotation values

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#618]
Currently we use the default value "default" for annotation attributes if we want to be able to check if a value was explicitly specified or not.
That's because the hickory-prisms don't allow us to check if an attribute was specified or not, but just returns the default in case it wasn't defined. The APT API can be used to get that information, though.

I see two possibilities:
1. We fork hickory and extend the generated source to have methods like `componentModelDefined():boolean` in addition to `componentModel():String`.
2. We create our own wrapper and a simple metamodel so we can still access the attributes in a generic and still type-safe way (with unit-tests that check that the metamodel fits the state of the annotations).

Option 2 might be the easiest, I guess.

Once we have that in place, we can go through our annotations and add the real "default" values that are also documented in the javadoc.

**Comment by gunnarmorling** [comment]
Ah, that's a very interesting proposal. I assumed one cannot distinguish the two cases (because that's how it is with reflection), but being able to do it with an AP is great news.

Regarding the two options, are you sure the original Hickory project is dead? Or maybe they accept a patch with that feature and do a release? Otherwise I'd go for the wrapper approach, forking and maintaining another project may be too much of a burden I fear. WDYT?

**Comment by agudian** [comment]
The original hickory project at java.net didn't have commits in eight years and the fork that we use hasn't been touched for five years or so (hasn't even been migrated to git, yet - unlike most other stuff in jolira).

So I'd prefer the wrapper as well, for the same reasons - although coding-wise, the change to the hickory-generator would be doable in almost no-time at all... damn...

**Comment by agudian** [comment]
While I was checking on how to implement it, I found that the currently generated prisms already have everything in place:

```
if ( mappingPrism.values.constant() != null ) { // check in .values, if the attribute is specified or not
    String specifiedConstant = mappingPrism.constant();
}
```

I'll rework our code and defaults to leverage this.

**Comment by gunnarmorling** [comment]
Ah, very cool!

**Comment by gunnarmorling** [comment]
Done.
