### ISSUE TITLE
Support for concat multiple fields or append a constant to exists value

### ISSUE THREAD

**Issue by mozinrat** [mapstruct/mapstruct#624]
@Mappings({
            @Mapping(target = "searchKey", source = "traceId +'END'")
    })
    Dto entityTodto(ResultEntity entity);

 @Mappings({
            @Mapping(target = "searchKey", source = "traceId +'-'+keyIndex")
    })
    Dto entityTodto(ResultEntity entity);

Also it would be great if we can append value
@Mappings({
            @Mapping(target = "searchKey", appendSource = "childId") 
              ==> searchKey = searchKey+child.getChildId()
    })
    Dto entityTodto(ChildResultEntity child);

**Comment by gunnarmorling** [comment]
`@Mapping#expression()` should be a solution for these cases, e.g.

    @Mapping(target = "searchKey", expression = "java(source.getTraceId() + \"END\")")
    Dto entityTodto(ResultEntity entity);

We plan to support a real expression language instead of Java in order to allow for more concise expressions, but that's some rough ideas at this time.

**Comment by filiphr** [comment]
As this could be solved via `@Mapping#expression()` I am going to close this. If you want to follow the discussion for a real expression language instead of Java then see https://github.com/mapstruct/mapstruct/issues/244
