### ISSUE TITLE
@MappingTarget & "Ambiguous mapping methods found for factorizing"

### ISSUE THREAD

**Issue by jdevreese** [mapstruct/mapstruct#625]
```Java
public class ObjectFactory
{
    public static MyClass createImpl1()
    {
        return ...;
    }

    public static MyClass createImpl2()
    {
        return ...;
    }
}
```

```Java
@Mapper(uses=ObjectFactory.class)
public interface MyMapper
{
    ...
    void map(TheirClass a, @MappingTarget MyClass m);
    ...
}
```

```
Ambiguous mapping methods found for factorizing MyMapper.MyClass: MyMapper.MyClass ObjectFactory.createImpl1(), MyMapper.MyClass ObjectFactory.createImpl2().
```

The error makes sense if the mapping method was something like "*MyClass map(TheirClass a);*", because in that case a new instance of *MyClass* needs to be created in the generated method.
But I'm using *@MappingTarget*, which means I'm providing an implementation of the target. I shouldn't get an error about not knowing which factory method to use.

**Comment by agudian** [comment]
Right, that shouldn't happen. And we should also rephrase the error message (for those cases where it is actually required) to something like "Ambiguous factory methods found for creating XX:...", as "factorizing" doesn't seem to be the right wording here.

**Comment by agudian** [comment]
Fixed.
