### ISSUE TITLE
Generated source formatting: unnecessary blank lines

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#626]
The generated code looks a bit cluttered again. Example:

```java
public class OrganizationMapperImpl implements OrganizationMapper {

    private final DepartmentEntityFactory departmentEntityFactory = new DepartmentEntityFactory();

    @Override
    public void toOrganizationEntity(OrganizationDto dto, OrganizationEntity entity) {
       ...
    }

    @Override
    public void toNumber(Integer number, OrganizationTypeNrEntity entity) {
        if ( number == null ) {
            return;
        }


        entity.setNumber( number );

    }

}
```

Perhaps we can smart-up our smart IndentationCorrectingWriter to swallow double newlines, emtpy lines before closing brackets and emtpy lines after opening brackets?

**Comment by gunnarmorling** [comment]
> swallow double newlines

Hum, I thought that'd happen already :(

> emtpy lines before closing brackets

Seems like a good idea.

> emtpy lines after opening brackets

Do you think so? E.g. the emptly line after "implements OrganizationMapper {" seems alright to me.

**Comment by agudian** [comment]
> > swallow double newlines
> Hum, I thought that'd happen already :(

Looking at the code, you're right. Seems a windows-only problem with the switch from IN_LINE_BRAKE to AFTER_LINE_BREAK... I'll investigate.

> > emtpy lines after opening brackets
> 
> Do you think so? E.g. the emptly line after "implements OrganizationMapper {" seems alright to me.

Yea, it's alright at that point - just wanted to be on the safe side for method-bodies / block statements. But we don't have a "problem" there right now.

**Comment by agudian** [comment]
> Looking at the code, you're right. Seems a windows-only problem with the switch from IN_LINE_BRAKE to AFTER_LINE_BREAK... I'll investigate.

Ah, it's actually the transition from AFTER_LINE_BREAK to IN_LINE_BREAK...

**Comment by gunnarmorling** [comment]
Done.
