### ISSUE TITLE
It cannot read inherited fields in 1.0.0-Beta3, it can with 1.0.0-Beta2

### ISSUE THREAD

**Issue by albertonavarro** [mapstruct/mapstruct#629]
It looks like a regression to me, let me share this code with you:

https://github.com/albertonavarro/cabotrafalgar-recordserver/blob/master/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateRecordMapper.java

This class works file with the olde 1.0.0-SNAPSHOT (using maven) and 1.0.0-Beta2, but not really with Beta3 or RC1.

Is this an expected behavior?

Gradle config:

description = 'RecordServer-persistence-couchdb'
dependencies {
    compile group: 'org.ektorp', name: 'org.ektorp', version:'1.4.2'
    compile group: 'org.ektorp', name: 'org.ektorp.spring', version:'1.4.2'
    compile project(':persistence-api')
    testCompile group: 'org.testng', name: 'testng', version:'6.8.8'
}
test.useTestNG()

ext {
    generatedMapperSourcesDir = "${buildDir}/generated-src/mapstruct/main"
}

task wrapper(type: Wrapper) {
    gradleVersion = '1.6'
}

configurations {
    mapstruct
}

dependencies {
    compile( 'org.mapstruct:mapstruct:1.0.0-SNAPSHOT' )

    testCompile( 'org.testng:testng:6.3.1' )
    testCompile ( 'org.easytesting:fest-assert:1.4' )

    mapstruct( 'org.mapstruct:mapstruct-processor:1.0.0-SNAPSHOT' )
}

sourceSets.main {
    ext.originalJavaSrcDirs = java.srcDirs
    java.srcDir "${generatedMapperSourcesDir}"
}

task generateMainMapperClasses(type: JavaCompile) {
    //class output dir, required by JavaCompile
    ext.aptDumpDir = file( "${buildDir}/tmp/apt/mapstruct" )
    destinationDir = aptDumpDir

    classpath = compileJava.classpath + configurations.mapstruct
    source = sourceSets.main.originalJavaSrcDirs
    ext.sourceDestDir = file ( "$generatedMapperSourcesDir" )

    options.define(
            compilerArgs: [
                    "-nowarn",
                    "-proc:only",
                    "-encoding", "UTF-8",
                    "-processor", "org.mapstruct.ap.MappingProcessor",
                    "-s", sourceDestDir.absolutePath,
                    "-source", sourceCompatibility,
                    "-target", sourceCompatibility,
            ]
    );

    inputs.dir source
    outputs.dir generatedMapperSourcesDir;
    doFirst {
        sourceDestDir.mkdirs()
    }
    doLast {
        aptDumpDir.delete()
    }
}

compileJava.dependsOn generateMainMapperClasses
compileJava.options.define(compilerArgs: ["-proc:none", "-encoding", "UTF-8"])
compileTestJava.options.define(compilerArgs: ["-proc:none", "-encoding", "UTF-8"])

Output:
:persistence-api:jar UP-TO-DATE
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateRecordMapper.java:32: error: No property named "id" exists in source parameter(s).
        @Mapping(target = "id", source = "id")
        ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateRecordMapper.java:23: error: Unknown property "new" in return type.
            @Mapping(target = "new", ignore = true)})
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateRecordMapper.java:22: error: Unknown property "revisions" in return type.
            @Mapping(target = "revisions", ignore = true),
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateRecordMapper.java:21: error: Unknown property "attachment" in return type.
            @Mapping(target = "attachment", ignore = true),
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateInfoMapper.java:38: error: No property named "id" exists in source parameter(s).
        @Mapping(target = "id", source = "id")
        ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateInfoMapper.java:23: error: Unknown property "new" in return type.
            @Mapping(target = "new", ignore = true)})
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateInfoMapper.java:22: error: Unknown property "revisions" in return type.
            @Mapping(target = "revisions", ignore = true),
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateInfoMapper.java:21: error: Unknown property "attachment" in return type.
            @Mapping(target = "attachment", ignore = true),
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateInfoMapper.java:27: error: Unknown property "attachment" in return type.
            @Mapping(target = "attachment", ignore = true),
            ^
/home/alberto/code/cabotrafalgar-recordserver/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CandidateInfoMapper.java:28: error: Unknown property "new" in return type.
            @Mapping(target = "new", ignore = true)})
            ^

**Comment by agudian** [comment]
How exactly does the target type look like?

**Comment by gunnarmorling** [comment]
Hey @albertonavarro, could you provide simple source/target types exposing the issue? E.g. you could for the repo and create a test case based on the inheritance tests [here](https://github.com/mapstruct/mapstruct/tree/master/processor/src/test/java/org/mapstruct/ap/test/inheritance). Thanks!

**Comment by albertonavarro** [comment]
The former question is something I can answer right now, the latter will take some more time.

The target is
CDBCandidateRecord.java
https://github.com/albertonavarro/cabotrafalgar-recordserver/blob/master/persistence-couchdb/src/main/java/com/navid/trafalgar/recordserver/persistence/couchbase/CDBCandidateRecord.java
extends
http://grepcode.com/file/repo1.maven.org/maven2/org.ektorp/org.ektorp/1.1.1/org/ektorp/support/CouchDbDocument.java

On the other end, the source is
https://github.com/albertonavarro/cabotrafalgar-recordserver/blob/master/persistence-api/src/main/java/com/navid/trafalgar/recordserver/persistence/CandidateRecord.java
that extends
https://github.com/albertonavarro/cabotrafalgar-recordserver/blob/master/persistence-api/src/main/java/com/navid/trafalgar/recordserver/persistence/CandidateInfo.java

I hope this can help before creating the example myself (I don't have much time)

**Comment by agudian** [comment]
@albertonavarro - Thanks, that's enough info. Everything is ok on the side of MapStruct. We just added some error outputs for faulty annotations:

Let's checkt the errors in CandidateRecordMapper together (I checked http://grepcode.com/file/repo1.maven.org/maven2/org.ektorp/org.ektorp/1.4.2/org/ektorp/support/CouchDbDocument.java, which seems to be the version you used according to your gradle snippet above):
`CandidateRecordMapper.java:32: error: No property named "id" exists in source parameter(s).
@Mapping(target = "id", source = "id")`
for method:
```
    @Mappings({
        @Mapping(target = "id", source = "id")
    })
    List<CandidateRecord> fromDto(List<CDBCandidateRecord> dto);
```
As the type `List` does not have a property "id", this annotation doesn't make sense here. Just remove it. The element-mappings are defined by the element-mapping method (`CandidateRecord fromDto(CDBCandidateRecord dto);` - as you are probably aware, you don't have to provide the `@Mapping` annotation if source and target property are named the same, so you can remove the annotation there as well).

`CandidateRecordMapper.java:23: error: Unknown property "new" in return type.
@Mapping(target = "new", ignore = true)`
The setter for `new` has the default-visibility and thus isn't visible in your code. Just remove the annotation.

`CandidateRecordMapper.java:22: error: Unknown property "revisions" in return type.
@Mapping(target = "revisions", ignore = true)`
The property is called `revision` and not `revisions`.

`CandidateRecordMapper.java:21: error: Unknown property "attachment" in return type.
@Mapping(target = "attachment", ignore = true)`
The property is called `attachments` and not `attachment`. 

I didn't check the errors on CandidateInfoMapper now, but it looks to me like it's basically the same stuff.

I'm closing this issue as not-a-bug. If you're on Eclipse, you can try out our MapStruct Eclipse plugin that gives some code-completion on source/target property names: https://github.com/mapstruct/mapstruct-eclipse

Anyway, thanks for raising your suspicion. It's appreciated! :+1:

**Comment by albertonavarro** [comment]
Thanks a lot for your help, regarding "id", I added it because somehow it wasn't working before, maybe a bug you have fixed since I started using this library.

I'll retry tonight, thanks a lot.

**Comment by albertonavarro** [comment]
All working, thanks
