### ISSUE TITLE
Add a configuration option to ignore all fields that don't have a matching mapper

### ISSUE THREAD

**Issue by sdeitmer** [mapstruct/mapstruct#630]
Not sure if this is already possible, but we would love to have a feature that allowed us to ignore fields that can't be mapped. 
We are using mapstruct to map complex entity graphs and want to fill in some fields (basically everything that is not a simple type) from outside of the mapper, depending on context. So, it would be helpful if the mapper could be configured to just ignore all fields that don't have a matching mapping method, instead of requiring a @Mapping(... ignore=true) annotation for each field in question.

**Comment by sjaakd** [comment]
Hi @sdeitmer 

Is [unmappedTargetPolicy](http://mapstruct.org/documentation/) what you're after? I often use it in 'warn' mode during development and when ready I switch to 'error'. For me this is a completeness check.

Also its good to know that there's an Eclipse plugin that generates the 'ignore=true'  by default for all parameters. 

Does that answer your question?

**Comment by gunnarmorling** [comment]
I am going to close this one as "Won't fix" as _unmappedTargetPolicy_ should address this. Feel free to re-open if you think something else should be done. Thanks!
