### ISSUE TITLE
NullPointerException when using generics in mapper interface

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#631]
From [SO](http://stackoverflow.com/questions/32096886/mapstruct-mapping-of-generics):

    @Mapper
    public interface MyMapper<X extends Base_1, Y extends Base_2>{
        public X mapBase_2ToBase_1(Y obj);
    }

This causes the following NPE:

    java.lang.NullPointerException
    at org.mapstruct.ap.util.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:90)
    at org.mapstruct.ap.util.Executables.getAllEnclosedExecutableElements(Executables.java:189)
    at org.mapstruct.ap.model.common.Type.getAllExecutables(Type.java:395)
    at org.mapstruct.ap.model.common.Type.getSetters(Type.java:464)
    at org.mapstruct.ap.model.common.Type.getPropertyWriteAccessors(Type.java:353)
    at org.mapstruct.ap.model.BeanMappingMethod$Builder.souceMethod(BeanMappingMethod.java:93)
    at org.mapstruct.ap.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:345)
    at org.mapstruct.ap.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)
    at org.mapstruct.ap.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114)
    at org.mapstruct.ap.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)
    at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:193)
    at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:173)
    at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:154)

**Comment by sjaakd** [comment]
Hmmm. I added logic some while ago not to allow parameterized types like this. I reckon this one should have been flagged already with a warning in the `MethodRetrievalProcessor`

**Comment by sjaakd** [comment]
Ah.. `org.mapstruct.ap.test.collection.wildcard.IterableTypeVarBoundMapperOnMapper` does take the case into consideration were a parameterized type is being used. However the more simple case of using a type-var directly is not covered.

**Comment by sjaakd** [comment]
@gunnarmorling , I'll have a more thorough look. I'll guess if we want to support this, we'll have to act on the type bound iso the type itself (which besides being a type var, can also be an upper / lower bound of a wild card type. The generated code will look something like this:

```java
package org.mapstruct.ap.test.bugs._631;

import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-08-23T22:58:51+0200",
    comments = "version: , compiler: javac, environment: Java 1.8.0_05 (Oracle Corporation)"
)
public class SourceTargetMapperImpl implements SourceTargetMapper  {

    @Override
    public Base_1 mapBase_2ToBase_1(Base_2 obj) {
        if ( obj == null ) {
            return null;
        }

        Base_1 x = new Base_1();

        return x;
    }
}
```

WDYT?

**Comment by gunnarmorling** [comment]
A clear error is raised in this situation now.

**Comment by EggIt** [comment]
Hi was this bug resolved please?
I have a similar mapper but i am stuck at maven compilation... i get the following error : 
```
Can't generate mapping method for a generic type variable source.
	E dtoToEntity(D dto);
	  ^
```

This is my mapper :
```
@Mapper(componentModel="spring")
public interface ReferentielMapper<D extends ReferentielDTO, E extends Referentiel> {
	ReferentielMapper<?, ?> INSTANCE = Mappers.getMapper(ReferentielMapper.class);
	E dtoToEntity(D dto);
	D entityToDto(E entity);
}
```

Any help please?
i am using v.1.1.0.CR2

**Comment by filiphr** [comment]
@EggIt This bug was resolved and you are getting a correct error message. The bug was that there was an NPE and not a nice error message.

Currently mapstruct cannot generate a mapping method for a generic variable.

Why do you need to use such generic mapping?

**Comment by EggIt** [comment]
Thanks for your response.

Well, i have many entities inheriting common fields from base class Referentiel, and few of them introduce new fields. (say : ChildA, ChildB etc...)

So, i created a generic service to operate CRUD functionalities for all these entities :
```
public interface ReferentielService<T extends ReferentielDTO> {
   T save(T dto);
   T findOne(Long id);
   List<T> findAll();
}
```
and then i thought of a generic mapper as well in the abstract service :
```
public abstract class ReferentielServiceSupport<T extends ReferentielDTO, E extends Referentiel> implements ReferentielService<T> {
	@Inject
	private ReferentielMapper<T, E> mapper;

// methods implementation goes here
}
```
And finally declare my concrete services :
```
@Named
public class ChildAServiceSupport extends ReferentielServiceSupport<ChildADTO, ChildA> {}
```
and
```
@Named
public class ChildBServiceSupport extends ReferentielServiceSupport<ChildBDTO, ChildB> {}
```

So basically, as i specified base classes in ReferentielMapper, i expected the generated ReferentielMapperImpl to map common fields between Referentiel and ReferentielDTO.
This way, if generic mapping was supported, most of my ChildXServiceSupport services won't need to override base implementations.

**Comment by filiphr** [comment]
@EggIt You would need to do the same thing you are doing for your services for the mappers.

You need the base interface **without** the `@Mapper` annotation so MapStruct won't pick it up and won't generate an implementation for it.

```
public interface ReferentielMapper<D extends ReferentielDTO, E extends Referentiel> {
    E dtoToEntity(D dto);
    D entityToDto(E entity);
}
```

And then

```
@Mapper(componentModel="spring")
public interface ChildAReferentielMapper<ChildADTO, ChildAReferentiel> { }
```

```
@Mapper(componentModel="spring")
public interface ChildBReferentielMapper<ChildBDTO, ChildBReferentiel> { }
```

This way you will be able to inject the base mapper in your services.

If you want to customize specifics, you can try making the `ReferentielMapper` a `@MapperConfig` and then use that config in the children interfaces and override the methods so you can provide mappings and add `@InheritConfiguration` to them, you will need to override both methods and add `@InheritInverseConfiguration` to the second one.

**Comment by EggIt** [comment]
Excellent! Thanks for the tip.
Will keep note of the specifics suggestions as i am sure i will need them sooner or later.
