### ISSUE TITLE
Generics method does not match

### ISSUE THREAD

**Issue by bedla** [mapstruct/mapstruct#634]
Hi,
I found that when you have mapper defined as 
```java
@Mapper
public interface SourceTargetMapper {
    Bar mapFooToBar(Foo foo);
    List<Bar> mapFooListToBarList(List<Foo> fooList);
//    TargetBar mapSourceToTarget(SourceFoo source);
    Target<Bar> mapSourceToTarget(Source<Foo> source);
}
```
And source and target classes as
```java
public class Source<T> {
    private final List<T> items;
    public Source(List<T> items) { this.items = items; }
    public List<T> getContent() { return items; }
}
public class Target<T> {
    private List<T> content;
    public List<T> getContent() { return content; }
    public void setContent(List<T> content) { this.content = content; }
}
```
Matching algorithm is not working in this case because of `getContent()` from Source returns unspecified type `List<T>` and not `List<Foo>`. I found it while investigating issue #607 .
When I specify parameter on on Source/Target class it works as expected (see commented line on mapper).
```java
public class SourceFoo extends Source<Foo> {
    public SourceFoo(List<Foo> items) { super( items ); }
}
public class TargetBar extends Target<Bar>{ }
```
From source code it lookls like it is more deeper in javax.lang.model.* implementation / I guess.

Ivos

**Comment by sjaakd** [comment]
@bedla : have you checkout out the `org.mapstruct.ap.test.selection.generics.GenericTypeMapper` and associated tests?

**Comment by antslava** [comment]
Any update on this issue?

**Comment by gunnarmorling** [comment]
Hey @antslava, we didn't yet get to fixing this. If you need it quickly, you might consider to send in a PR for fixing it?

**Comment by gunnarmorling** [comment]
Ok, I think I got an angle on this. Will send a PR hopefully shortly. Essentially, we are using (Type)Element in several places where we actually should use DeclaredType instead which conveys the information about the type parameter.

**Comment by antslava** [comment]
@gunnarmorling, Thanks for your help.

**Comment by gunnarmorling** [comment]
Hey @antslava, I just sent in PR https://github.com/mapstruct/mapstruct/pull/738. Maybe you could build MapStruct from that branch (just run "mvn clean install") and see whether it fixes the issue for you, too?

**Comment by antslava** [comment]
Hi @gunnarmorling, thanks. I will try it today and write you about results.

**Comment by antslava** [comment]
Hi @gunnarmorling , your PR works. Thanks for your help.

**Comment by gunnarmorling** [comment]
@antslava Cool, glad to hear. Thanks for testing and your feedback!

**Comment by gunnarmorling** [comment]
Done.
