### ISSUE TITLE
mapstruct creates new entity even if the source is empty

### ISSUE THREAD

**Issue by shane-chen** [mapstruct/mapstruct#635]
mapstruct creates new entity even if the source is empty this causes strange problems in some cases.

example:

if ( target.getMainReference() == null ) {
   target.setMainReference( new Reference() );
}
toReference( source.getMainReference() , target.getMainReference() );

should be something like:
if ( target.getMainReference() == null && source.getMainReference() != null) {
    target.setMainReference( new Reference() );
    toReference( source.getMainReference() , target.getMainReference() );
}

**Comment by agudian** [comment]
Please try again with MapStruct version 1.0.0.CR2, which should fix that.

**Comment by agudian** [comment]
Btw, Hi Shengyao :smile:!

**Comment by agudian** [comment]
#596 is the the issue that I think describes the same thing and has been fixed for 1.0.0.CR2.

**Comment by agudian** [comment]
Closing this, hoping that the issue is fixed for @shane-chen with 1.0.0.CR2.
