### ISSUE TITLE
Allow NullValueMappingStrategy to be configured for forged collection mapping methods.

### ISSUE THREAD

**Issue by samwright** [mapstruct/mapstruct#640]
Currently if there is a mapper for converting `A -> B`, and elsewhere there is a mapping that requires `List<A> -> List<B>`, MapStruct generates a private method for it without any extra declarations required in the interface. This is a very cool feature.

However, this method is configured to return `null` if the source `List<A>` field is `null`, regardless of the `@Mapper#nullValueMappingStrategy`. I would like to be able to configure these generated mapping methods to `RETURN_DEFAULT` (e.g. an empty list) when the source `List<A>` field is `null`.

Because I need this behaviour, I have to declare the iterable mapping methods in the mapper interface and use `@IterableMapping#nullValueMappingStrategy`, e.g.

```java
@IterableMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
List<B> aToBList(List<A> aList);
```

This doesn't really add value to the interface, and is required for each iterable return type I need (i.e. is bad for all the reasons that the forged methods are good).

Could this be added as a configuration to `@Mapping`? E.g. `@Mapping#forgedNullValueMappingStrategy`.

Alternatively, if `@Mapping#defaulValue` could take a special string to represent an empty collection/map (e.g. an empty string) then I could get the behaviour I need.

I'm happy to help implementing this, though I'm unfamiliar with the code-base and would need some pointers.

Thanks for the awesome tool!

**Comment by sjaakd** [comment]
@samwright : did you know you could also define the `NullValueMappingStrategy` on the `Mapper` and `MapperConfig`. These form a hierarchical structure, were `MapperConfig` is at the top, which can be overridden by `Mapper` which, in its turn, can be overridden by individual mapping methods.

I've to checkout how they work on forged methods thought. But you can group methods requiring a strategy together in a used mapper and put it on the `Mapper`.

**Comment by gunnarmorling** [comment]
Right, `nullValueMappingStrategy()` given via `@Mapper`/`@MapperConfig` should be applied to forged methods, too. If it doesn't, I'd consider that a bug.

**Comment by samwright** [comment]
@gunnarmorling I expected that to happen, but as this example shows the forged methods always follow the `RETURN_NULL` strategy, regardless of the `@Mapper#nullValueMappingStrategy`:

```java
@Mapper(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public abstract class PersonMapper
{
    public PersonDto toDto(Person person) {
        return new PersonDto();
    }

    public abstract PeopleDto toDto(People people);

    public class Person {}
    public class PersonDto {}
    public class People {
        private List<People> people;

        public List<People> getPeople() {
            return people;
        }

        public void setPeople(List<People> people) {
            this.people = people;
        }
    }
    public class PeopleDto {
        private List<PeopleDto> people;

        public List<PeopleDto> getPeople() {
            return people;
        }

        public void setPeople(List<PeopleDto> people) {
            this.people = people;
        }
    }
}
```
... generates ...
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2015-09-13T13:51:12+0100",
    comments = "version: 1.0.0.CR2, compiler: javac, environment: Java 1.8.0_60 (Oracle Corporation)"
)
public class PersonMapperImpl extends PersonMapper {

    @Override
    public PeopleDto toDto(People people) {

        PeopleDto peopleDto = new PeopleDto();

        if ( people != null ) {
            peopleDto.setPeople( peopleListToPeopleDtoList( people.getPeople() ) );
        }

        return peopleDto;
    }

    protected List<PeopleDto> peopleListToPeopleDtoList(List<People> list) {
        if ( list == null ) {
            return null;
        }

        List<PeopleDto> list_ = new ArrayList<PeopleDto>();
        for ( People people : list ) {
            list_.add( toDto( people ) );
        }

        return list_;
    }
}
```
For my use case, I'd like all `@BeanMapping` mappings to `RETURN_NULL` (since the nullity of the bean field inside another bean has significance) and all `@IterableMapping` and `@MapMapping` mappings to `RETURN_DEFAULT` (since IMHO all such fields should never be null, as they already have a built-in concept of emptiness). 

If the `@Mapping#nullValueMappingStrategy()` is honoured by forged methods then I'll use that to set `RETURN_DEFAULT`, and will have to apply `RETURN_NULL` to all bean mappings. Not a big deal, but if lots of people wanted this behaviour it may be worth having separate null mapping strategies for beans and iterables/maps, e.g. `@Mapping#iterableNullValueMappingStrategy`, `@Mapping#beanNullValueMappingStrategy`. But then that adds more options and complexity.

An extra feature that would help my use case is if there was a null value mapping strategy that would only set the target property if the source value is not null, e.g. `MAP_IF_NOT_NULL`.

**Comment by sjaakd** [comment]
@samwright, @gunnarmorling : I think that we handle this as two separate items..

1. A bug (for not handling the `NullValueMappingStrategy` correctly.

2. A feature request for implementing `NullValueMappingStrategy` at the forged methods by means of mapper configuration of the calling method.

The latter one, is not that easy when you come to think of it.. Forged methods are now reused. So if you create the possibility to have two forged variants (with different `NullValueMappingStrategy` ).. Anyway.. I reckon the latter (when going to be implemented is for after 1.0), whilst the first can possibly make it to 1.0

**Comment by samwright** [comment]
1. @sjaakd agreed. Getting the forged methods to use NullValueMappingStrategy would fix this issue (and I'd be very thankful/impressed if this can make it to 1.0)

2. If a mapper that defines `Person -> PersonDto` has the `@Mapper#forgedNullStrategy` or `@Mapper#iterableNullStrategy` or w/e, then wouldn't that just create one forged method (e.g. with `RETURN_DEFAULT`) that all other mappings would use? Why would you then need an equivalent `RETURN_NULL`-style method? Perhaps that discussion should probably take place in a new ticket.

**Comment by sjaakd** [comment]
Wrt. 1, I'll have a shot at it.. I made the original forged method implementation, but I cannot remember why I left this out.

**Comment by sjaakd** [comment]
Wrt. 2. I think we first have to agree whether we want such functionality. 

If so, I would like to argue that we define the complet `@IterableMapping` and `@MapMapping` as members of `@Mapping`. Just like this:

```java
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.METHOD)
public @interface Mapping {

    ...

    IterableMapping generatedIterableMappings();
    MapMapping generatedMapMapping();

}

```
At least, if that's possible. (BTW: I would prefer not to use the term `forged` to the outside)

**Comment by samwright** [comment]
@sjaakd I like that approach, but I think it might make the `@Mapping` method annotations quite verbose, e.g.:

```java
@Mapping(source = "peopleList", target = "peopleDtoList", generatedIterableMapping = @IterableMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT))
public abstract PeopleDto toDto(People people);
```
which wouldn't fit on one line, so would look messy with multiple `@Mapping` annotations. I'd rather apply that at the class level using (`@Mapper`):

```java
@Mapper(uses = { StringIdMapper.class, TimeMapper.class, AnnotationMapper.class },
                 generatedIterableMapping = @IterableMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT))
public abstract class MessageMapper {
    ...
}

```
So `@Mapper` would look like:

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface Mapper {
    ...

    IterableMapping generatedIterableMappings();
    MapMapping generatedMapMapping();

}
```
Or perhaps both `@Mapping` and `@Mapper` could support this configuration, with the method annotation taking priority.

**Comment by sjaakd** [comment]
Well,  `nullValueMappingStrategy` on `Mapper` level applies all mappings (iterable, bean, and map). #645 also applies that to generated mappings iterable - and map mappings. So, its consistent, and point 1. is covered.

The second one (2.) proposes to have a mechanism on mapping level to override this behavior for generated map and iterable mapping, in a similar way that is already in place for defined methods by means of `@IterableMapping` and `@MapMapping`. There are more parameters you can specify on `@IterableMapping` and `@MapMapping`. The proposal automatically takes these parameters into consideration and always will honor the same contract as `@IterableMapping` and `@MapMapping`, so in essence we don't have to think about that and we do have a simpeler interface story to tell. .

**Comment by samwright** [comment]
Good point, I hadn't thought about that. You are right that your approach is more consistent and preferable.

Perhaps I can get my desired behaviour from prototype methods in a `@MapperConfig`-annotated interface instead (I haven't had a chance to play with it yet, but perhaps setting `@BeanProperty(nullStrategy = RETURN_NULL)` on an `Object -> Object` prototype method would do it)

Otherwise I'm happy with setting everything to `RETURN_DEFAULT` and then I'll annotate the beans that should be `null` with `RETURN_NULL`, which has the benefit of making it more obvious what's going on.

Thank you for your efforts!

**Comment by gunnarmorling** [comment]
The PR for solution 1) has been merged.

@sjaakd, could you open up a follow-up issue for the other line of discussion? I think being able to configure different null value mapping strategies for bean and collection mapping methods through `@Mapper`/`@MapperConfig` would make sense.

I don't think there is a need for `@Mapping#generatedIterableMappings()` and the like, just explicitly create and configure the iterable method and it will be invoked by the bean mapping method as needed. It's a bit more to write but it uses the existing concepts and I don't think it's worth making `@Mapping` more complex.
