### ISSUE TITLE
Build should ignore unavailable JDKs if toolchains.xml is present

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#642]
If there is a _~/.m2/toolchains.xml_ file which contains some additional JDKs (e.g. Java 6) but not all possible values from `ProcessorSuite` (e.g. not JDK 6 and 9), the integration tests will fail with an exception complaining about the missing entries:

    Caused by: org.apache.maven.plugin.MojoFailureException: Cannot find matching toolchain definitions for the following toolchain types:
jdk [ vendor='oracle'  version='[1.6,1.7)' ]

Can we somehow make it that this does not fail the build? Personally I'd be willing to test against JDK 7 and 8 but not against 6 (hard to get in on Mac any longer) and 9 (had trouble with that because it was used by default for some applications, e.g. Eclipse).

**Comment by agudian** [comment]
In the meantime, you can install JDK 6 for Mac from here: https://support.apple.com/kb/DL1572

The JDK 9 test is only enabled when the system property `processorIntegrationTest.canUseJdk9` is set to `true`.

But I agree it would be cool if the test runner could detect what's actually available in the toolchains.xml file.
