### ISSUE TITLE
Feature request: forge enum mapping methods.

### ISSUE THREAD

**Issue by samwright** [mapstruct/mapstruct#643]
If a mapping requires the conversion between two enums that are completely equivalent, MapStruct could create a private mapping method to perform this (much like how iterable conversion methods can be forged).

This would obviate the need to declare `EnumA -> EnumB` and `EnumB -> EnumA` abstract methods, making the abstract class/interface cleaner.

**Comment by gunnarmorling** [comment]
I don't think that's worth the effort really. Two identical enums should be very rare (why wouldn't you just use one to begin with in such case). And if there are differences, a dedicated method is needed to hold the configuration. I'm going to close as "Won't fix" therefore, thanks for bringing up the idea nevertheless.
