### ISSUE TITLE
Find alternative way to handle asMemberOf when using Eclipse 

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#644]
The following error occurs in integration test (Java8) when `fooFromId and `barFromId ` in:
```java
package org.mapstruct.ap.test.bugs._636;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import org.mapstruct.factory.Mappers;

@Mapper
public interface SourceTargetMapper extends SourceTargetBaseMapper {
    SourceTargetMapper INSTANCE = Mappers.getMapper( SourceTargetMapper.class );

    @Mappings({
        @Mapping(source = "idFoo", target = "foo"),
        @Mapping(source = "idBar", target = "bar")
    })
    Target mapSourceToTarget(Source source);

    default Foo fooFromId(long id) {
        return new Foo(id);
    }

    static Bar barFromId(String id) {
        return new Bar(id);
    }

}
```
are brought to the (intended) base class:

```java
package org.mapstruct.ap.test.bugs._636;

import org.mapstruct.Mapper;

@Mapper
public interface SourceTargetBaseMapper {

    // TODO.. move default and static interface method here when problem in eclipse processor is fixed.

}
```

```
ERROR] /Users/sjaak/Development/java/NetBeansProjects/mapstruct/mapstruct1/integrationtest/target/tmp/org.mapstruct.itest.tests.Java8Test/eclipse_jdt_java_8/src/main/java/org/mapstruct/ap/test/bugs/_636/SourceTargetMapper.java:[27] 
public interface SourceTargetMapper extends SourceTargetBaseMapper {
^^^^^^^^^^^^^^^^^^
Internal error in the mapping processor: java.lang.IllegalArgumentException: element is not valid for the containing declared type at org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:89) at org.mapstruct.ap.internal.model.common.TypeFactory.getMethodType(TypeFactory.java:264) at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.getMethod(MethodRetrievalProcessor.java:182) at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetr
```

Ergo, it seems that the eclipse compiler plugin cannot handle the Java8 constructs `default` and `static method` in an `interface` base class.

**Comment by gunnarmorling** [comment]
@sjaakd, @agudian: This seems to be the Eclipse bug we are bitten by: [#382590](https://bugs.eclipse.org/bugs/show_bug.cgi?id=382590). I seems to be fixed in the latest milestone; I'll give it a try tomorrow, failed to build JDT myself so far.

**Comment by agudian** [comment]
cool, this kind of looks like what I was trying as well. Although there is no handling of interfaces, which I think could be missing there.

**Comment by gunnarmorling** [comment]
So `GenericsTest` passes with JDT as of 4.6 Milestone 3. That's some good news :)

**Comment by gunnarmorling** [comment]
> Although there is no handling of interfaces, which I think could be missing there.

Ah, yes. That seems still incorrect indeed. They would have to follow-up super-interfaces as well. E.g. `InheritedMappingMethodTest` is suffering from that.

I will file a bug in the Eclipse tracker. As there has some movement around this recently I think we have quite good chances to get this fixed as well soon-ish. Maybe I'll try and propose a fix, too.

**Comment by gunnarmorling** [comment]
I've filed bug [#481555](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481555) for this.

**Comment by gunnarmorling** [comment]
Done.
