### ISSUE TITLE
Updating a null property doesnt work correctly when using @QualifiedBy when the source property is null

### ISSUE THREAD

**Issue by PierrickPuimeanChieze** [mapstruct/mapstruct#648]
Mapper Code : 
```java
@Mapper
public abstract class MandateMessageMapper {
    @Mapping(target="convertedProperty", qualifiedBy = TargetPropertyConverter.class)
    public abstract Target updateTarget(Source source, @MappingTarget Target);
    
    @TargetPropertyConverter
    public String convert(Object sourceProperty) {
        return sourceProperty;
    }
}
```
Mapper Implementation code
```java
public abstract class MandateMessageMapperImpl {
    public Target updateTarget(Source source, @MappingTarget Target) {
        target.setConvertedproperty(convert(source.getConvertedProperty());
    }
}
```
Should be :         
```java
public abstract class MandateMessageMapperImpl {
    public Target updateTarget(Source source, @MappingTarget Target) {
        if (source.getConvertedProperty() != null) {
            target.setConvertedproperty(convert(source.getConvertedProperty());
        }
    }
}
```

**Comment by agudian** [comment]
Hi Pierrick,

Thanks for the report! Is it the null-check that you are missing? If so, then that is how we intended it. Calling other property-mapping methods is done without null-checks, so that the implementor of that property-mapping method can decide what to do with that null value (e.g. return a specific default or something).

**Comment by agudian** [comment]
Ah, forget what I wrote. The null-check on 'source' is missing.
The null-check on 'source.getX()' would still not be required, though.

**Comment by PierrickPuimeanChieze** [comment]
I understand but sometimes, the null-check seems to be done. For exemple, when mapping a date, their is a null check which is done.
Additionally, it would be very useful for an update method. For exemple, in my case, the target property must be left intact if the source property is at null, and I don't have any control on this behavior.

Is an option a possibility ? There is some suggestion on this suggestion that I find quite interesting : https://github.com/mapstruct/mapstruct/issues/369

**Comment by PierrickPuimeanChieze** [comment]
By the way this a duplicate of the issue #649. I am closing this one, as the other is a lot more clear.
