### ISSUE TITLE
Update property in MappingTarget only if source property is not null

### ISSUE THREAD

**Issue by cbornet** [mapstruct/mapstruct#649]
I would like to update target attributes only if the source ones are not null (to implement some kind of partial update). Is there a way to do that ? If not, could it be implemented, for instance as an option of MappingTarget ?
What I get

``` java
 @Override
 public void updateFooFromDto(FooDto fooDto, Foo foo) {
        if ( fooDto== null ) {
            return;
        }

        site.setBar( fooDto.getBar() );
        site.setBaz( fooDto.getBaz() );
}
```

What I would like to generate:

``` java
 @Override
 public void updateFooFromNonNullAttributesOfDto(FooDto fooDto, Foo foo) {
        if ( fooDto== null ) {
            return;
        }
        if ( fooDto.getBar() != null ) {
            site.setBar( fooDto.getBar() );
        }
         if ( fooDto.getBaz() != null ) {
            site.setBar( fooDto.getBaz() );
        }
}
```

**Comment by gunnarmorling** [comment]
Actually your suggested code is what you should get if `bar` and `baz` on the source side are nullable types. Are you working with primitive types there by any chance?

**Comment by cbornet** [comment]
They are primitive's wrapper types such as Integer, String, Boolean, ...

**Comment by agudian** [comment]
That's not supported, yet. A similar question was asked on the mailing-list today and also in the past already.
So it seems there is a need for this feature. :)

What we need is some idea on how a user would configure this.

**Comment by PierrickPuimeanChieze** [comment]
There was some suggestions on the issue #369

For my part, I think that a new Null strategy (named for example IGNORE) would be the best.

**Comment by matt-blanchette** [comment]
+1

**Comment by matt-blanchette** [comment]
Agreed that a new NullValueMappingStrategy like IGNORE would work better for me as well.

The discussion in #369 mentions changing @Mapping, which could work,
but this involves adding @Mapping for those automatically mapped by name.

**Comment by rsharifu** [comment]
I completely agree. I'm going to jump in and use this library in my project when IGNORE is released.

**Comment by jannikweichert** [comment]
I'd highly appreciate a solution for this as well. A new NullValueMappingStrategy seems to be promising approach

**Comment by bhdrk** [comment]
+1

**Comment by sjaakd** [comment]
I added an [example](https://github.com/sjaakd/mapstruct-examples) PR. Please have a look at the current MapStruct behavior. I'm not sure I understand what is actually desired in this issue.

**Comment by bhdrk** [comment]
@sjaakd, the idea is very simple. There is a requirement for an extra parameter on @MappingTarget annotation. e.g. `acceptNullValues`  is very suitable. 

The default behavior is:

``` java
 @Override
 public void updateFooFromDto(FooDto fooDto, Foo foo) {
        if ( fooDto== null ) {
            return;
        }

        site.setBar( fooDto.getBar() );
        site.setBaz( fooDto.getBaz() );
}
```

if I add the `acceptNullValues` property 

``` java
public interface MyMapper {
    void updateFooFromDto(FooDto fooDto, @MappingTarget(acceptNullValues=true) Foo foo) 
}
```

Then expected generated code:

``` java 
@Override
 public void updateFooFromNonNullAttributesOfDto(FooDto fooDto, Foo foo) {
        if ( fooDto== null ) {
            return;
        }
        if ( fooDto.getBar() != null ) {
            site.setBar( fooDto.getBar() );
        }
         if ( fooDto.getBaz() != null ) {
            site.setBar( fooDto.getBaz() );
        }
}
```

Why we need that? Beacuse that is a must for REST Services on update (PUT) service calls if we just update a few field of an entity. I will try to explain with an example.

This is my service request.

**Request body:**
``` json
{
   "project_name": "new test project"
}
```
and my service method:

```java
@RequestMapping(value = "/projects/{projectNameOrId}", method = PUT)
@ResponseBody
public ProjectDTO update(@AuthenticationPrincipal User user,
                             @PathVariable Long projectNameOrId,
                             @RequestBody ProjectDTO dto) throws IOException {

        Project project = projectService.findByNameOrId(user.getCompany(), projectNameOrId);

        /**
         * at this line, all fields of my project entity will be null. 
         * Because mapper set all fields. But the request just contains project name field.
         */ 
        myMapper.dtoToProject(dto, project); 
        
        .....
}
```

Sorry for long comment and my bad english ;)

**Comment by sjaakd** [comment]
@bhdrk 

This is my example:

```java
@Mapper
public interface SourceTargetMapper {

    SourceTargetMapper MAPPER = Mappers.getMapper( SourceTargetMapper.class );

    @Mappings( {
        @Mapping( target = "numberOfStomachs", source = "numberOfStomachs" )
    } )
    MammalEntity toTarget( MammalDto source, Long numberOfStomachs, @MappingTarget MammalEntity target );
}
```

This is the generated code (MapStruct, 1.0.0Final)

```java
public class SourceTargetMapperImpl implements SourceTargetMapper {

    @Override
    public MammalEntity toTarget(MammalDto source, Long numberOfStomachs, MammalEntity target) {
        if ( source == null && numberOfStomachs == null ) {
            return null;
        }

        if ( source != null ) {
            if ( source.getNumberOfLegs() != null ) {
                target.setNumberOfLegs( source.getNumberOfLegs().longValue() );
            }
        }
        if ( numberOfStomachs != null ) {
            target.setNumberOfStomachs( numberOfStomachs );
        }

        return target;
    }
}
```

Looks what you need right? And not what's generated by your processor. So, are you on the same version?

**Comment by sjaakd** [comment]
See https://github.com/mapstruct/mapstruct-examples

**Comment by sjaakd** [comment]
@bhdrk .. Sorry. I see now.. You need a check on the target.

**Comment by bhdrk** [comment]
@sjaakd

My Entity:

```java
public class User {

    private String username;

    private String email;
}
```

My DTO:

```java
public class UserDTO {

    private String username;

    private String email;
}
```

Mapper:

```java
@Mapper
public interface UserMapper {

    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    void dto2Entity(UserDTO dto, @MappingTarget User entity);
}

```

Generated Code:

```java
public class UserMapperImpl implements UserMapper {
    @Override
    public void dto2Entity(UserDTO dto, User entity) {
        if ( dto == null ) {
            return;
        }

        entity.setUsername( dto.getUsername() );
        entity.setEmail( dto.getEmail() );
    }
}
```

I want that If I add something like that:

```java
void dto2Entity(UserDTO dto, @MappingTarget(acceptNullValues=false) User entity);
````

Expected Generated Code:

```java
public class UserMapperImpl implements UserMapper {

    @Override
    public void dto2Entity(UserDTO dto, User entity) {
        if ( dto == null ) {
            return;
        }

        if (dto.getUsername() != null)
            entity.setUsername( dto.getUsername() );

        if (dto.getEmail() != null)
            entity.setEmail( dto.getEmail() );
    }
}
```

I hope, it is clear now.

**Comment by gunnarmorling** [comment]
Check out the pending PR #720, this should give you exactly what you want. The idea there is that you can define (globally, per mapper, per mapping method, per mapped property) if/how the presence of source properties should be checked. There'd be a setting for always mandating a null check:

    @Mapper(sourceValuePresenceCheckStrategy=IS_NULL)
    interface UserMapper {
        void dto2Entity(UserDTO dto, @MappingTarget User entity);
    }

This would result in the generated mapper being generated the way you describe it.

**Comment by sjaakd** [comment]
@bhdrk I see your point. My example generates a null check because of type conversion. Hence the confusion. @gunnarmorling thanks

**Comment by bhdrk** [comment]
thank you @gunnarmorling. that's what I am looking for :+1:

**Comment by Mendred** [comment]
+1 for this feature.

**Comment by Walker555** [comment]
+1 for this feature.

**Comment by bfg** [comment]
i'd appreciate this feature too.

**Comment by getAkashJain** [comment]
+1 for this feature.

**Comment by nachii** [comment]
+1 for this feature!

**Comment by remmeier** [comment]
relates to https://github.com/mapstruct/mapstruct/issues/674 and https://github.com/mapstruct/mapstruct/issues/369 as well. 

it would further be great to support:

`
@Override
 public void updateFooFromNonNullAttributesOfDto(FooDto fooDto, Foo foo) {
        if ( fooDto== null ) {
            return;
        }
        if ( fooDto.isLoaded("bar") ) {
            site.setBar( fooDto.getBar() );
        }
         if ( fooDto.isLoaded("bar")l ) {
            site.setBar( fooDto.getBaz() );
        }
}
`

to differentiate between "being null" and just not being loaded. Instead of fooDto.isLoaded one might consider some other been providing loading information, such as 

` if ( loadingStrategy.isLoaded(fooDto, "bar")l ) {
    site.setBar( fooDto.getBaz() );
 }`

Example use case: for jpa to dto mapping I usually do not want to map lazy Hibernate proxies that still need to be loaded (ruins the performance). Instead everything loaded with fetch/entiy graphs should be mapped to dtos.

**Comment by fluxish** [comment]
+1 for this feature

**Comment by sjaakd** [comment]
@fluxish , @bhdrk , @Mendred, @Walker555, @bfg , @getAkashJain , @nachii .. I think this issue is resolved with the following mapper (using the example of @bhdrk ):

```java
@Mapper( nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS )
public interface UserMapper {

    UserMapper INSTANCE = Mappers.getMapper( UserMapper.class );


    void dto2Entity(UserDTO dto, @MappingTarget User entity);
}
```

which generates the desired:

```java
public class UserMapperImpl implements UserMapper {

    @Override
    public void dto2Entity(UserDTO dto, User entity) {

        if ( dto == null ) {
            return;
        }

        if ( dto.getUsername() != null ) {
            entity.setUsername( dto.getUsername() );
        }

        if ( dto.getEmail() != null ) {
            entity.setEmail( dto.getEmail() );
        }
    }
}
```

-----
@remmeier , @fluxish .. I think that your problem is resolved by the introduction of the customizable `hasXYZ` methods. See example: https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-spi-accessor-naming.

-----
So, I want to continue and close this issue later this week if this works for you. If this does not work for you, let us know. Note: you can always write a new issue if this does not work for you.

**Comment by bhdrk** [comment]
@sjaakd I tested that. But there is a bug for collection field types such as `java.util.Set`. My generated code below. There is no null check for dto.getPermissions()  field.

```java
public class ModelMapperImpl implements ModelMapper {

    @Override

    public Permission map(PermissionDTO dto) {

        if ( dto == null ) {

            return null;
        }

        Permission permission = new Permission();

        if ( dto.getId() != null ) {

            permission.setId( dto.getId() );
        }

        if ( dto.getDisplayName() != null ) {

            permission.setDisplayName( dto.getDisplayName() );
        }

        return permission;
    }

    @Override

    public void map(RoleDTO dto, Role entity) {

        if ( dto == null ) {

            return;
        }

        if ( dto.getId() != null ) {

            entity.setId( dto.getId() );
        }

        if ( dto.getDisplayName() != null ) {

            entity.setDisplayName( dto.getDisplayName() );
        }

        // Expected null check for Collection fields
        
        // if (dto.getPermissions() != null) { <<--- This line is missing in generated code. it should be added.
        
        if ( entity.getPermissions() != null ) {

            Set<Permission> set = permissionDTOSetToPermissionSet( dto.getPermissions() );

            if ( set != null ) {

                entity.getPermissions().clear();

                entity.getPermissions().addAll( set );
            }

            else {

                entity.setPermissions( null );
            }
        }

        else {

            Set<Permission> set = permissionDTOSetToPermissionSet( dto.getPermissions() );

            if ( set != null ) {

                entity.setPermissions( set );
            }
        }
        
        // } end of expected null check
    }

    protected Set<Permission> permissionDTOSetToPermissionSet(Set<PermissionDTO> set) {

        if ( set == null ) {

            return null;
        }

        Set<Permission> set_ = new HashSet<Permission>();

        for ( PermissionDTO permissionDTO : set ) {

            set_.add( map( permissionDTO ) );
        }

        return set_;
    }
}

```

**Comment by sjaakd** [comment]
@bhdrk but there is a null check, right.. Its the combination of:
```java
            Set<Permission> set = permissionDTOSetToPermissionSet( dto.getPermissions() );
            if ( set != null ) {
                entity.getPermissions().clear();
                entity.getPermissions().addAll( set );
            }
```
And the call to the generated method..

```java
  protected Set<Permission> permissionDTOSetToPermissionSet(Set<PermissionDTO> set) {

        if ( set == null ) {
            return null;
        }
```
So it should work in your case. Or am I missing something?

We can discuss surrounding all the property related code with a null check if-and-only-if the 
`@Mapper( nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS )` in case of collection mapping. But that would be a different topic.

**Comment by fluxish** [comment]
I'm sorry, it's exactly what I want, thanks

**Comment by sjaakd** [comment]
> Is there a way to avoid to generate the first if?

That would be difficult right now. We need to have a check on the target property to avoid NPE's. In the future, there might be a way to hook in your own templates.. I believe we have an issue for that.

**Comment by bhdrk** [comment]
@sjaakd  you are missing `else` block. There is a `entity.setPermissions( null )`. Therefore target object property will be null due to source object. 

```java
if ( set != null ) {

    entity.getPermissions().clear();

    entity.getPermissions().addAll( set );
}

else {

    entity.setPermissions( null ); // <--- devil line
}

```

The solution seems simple. Just should be a null check before collection setter like other fields.

```java
//-----------------------------------------------------------------------------------

   if (dto.getPermissions() != null) {   // <<< --- Required null check line 

//-----------------------------------------------------------------------------------

        if ( entity.getPermissions() != null ) {

            Set<Permission> set = permissionDTOSetToPermissionSet( dto.getPermissions() );

            if ( set != null ) {

                entity.getPermissions().clear();

                entity.getPermissions().addAll( set );
            }

            else {

                entity.setPermissions( null );
            }
        }

        else {

            Set<Permission> set = permissionDTOSetToPermissionSet( dto.getPermissions() );

            if ( set != null ) {

                entity.setPermissions( set );
            }
        }

//-----------------------------------------------------------------------------------

   } // end of expected null check 
```

**Comment by sjaakd** [comment]
ahh.. now I get your point. What happens here is that the mapping method generates the method `permissionDTOSetToPermissionSet`.. This is a so called `create method`. Can you try to implement an `update mapping` method with the following signature `permissionDTOSetToPermissionSet( Set<PermissionDTO> set, @MappingTarget Set<Permission>)`.

This can be done by using abstract class `ModelMapper` in stead of an interface `ModelMapper` or by referring to an used mapper implementing such method.

Reasoning behind this: a generated update method will call an update method itself if available. This is not the case. Unfortunately, automatically generating such update method is not in place (check out #487, #489) and difficult.

**Comment by sjaakd** [comment]
if you want an example.. Check out our unit test on update [method selection](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/ExternalSelectionTest.java) and its generated code how `ExternalHandWrittenMapper` is called.

**Comment by sjaakd** [comment]
@bhdrk: I thought a bit more about it. The above should work for you in the current situation. But I also think you have a point. I wrote: #954 to tackle this specific scenario.

**Comment by bhdrk** [comment]
Thank you @sjaakd, finally I understand my wrong :) After adding a update method `void map(Set<PermissionDTO> dtos, @MappingTarget Set<Permission> entities);` the mapper works as expected. 

```java
@Mapper(
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS
)
public interface ModelMapper {

    BasicEntity map(Permission entity);

    Permission map(PermissionDTO dto);

    void map(Set<PermissionDTO> dtos, @MappingTarget Set<Permission> entities);

    void map(RoleDTO dto, @MappingTarget Role entity);
} 
```

the generated code of related methods is below.

```java
    public void map(RoleDTO dto, Role entity) {

        if ( dto == null ) {

            return;
        }

        if ( dto.getId() != null ) {

            entity.setId( dto.getId() );
        }

        if ( dto.getDisplayName() != null ) {

            entity.setDisplayName( dto.getDisplayName() );
        }

        if ( entity.getPermissions() == null ) {

            entity.setPermissions( new HashSet<Permission>() );
        }

        map( dto.getPermissions(), entity.getPermissions() );
    }

   public void map(Set<PermissionDTO> dtos, Set<Permission> entities) {

        if ( dtos == null ) {

            return;
        }

        entities.clear();

        for ( PermissionsDTO permissionsDTO : dtos ) {

            entities.add( map( permissionsDTO ) );
        }
    }

```

But I still think that a null check should be also added for collection fields. Because the developers can forget to add the update methods of collection fields and also this is an extra effort when  DTOs contains multiple collection fields.

**Comment by sjaakd** [comment]
@bhdrk Thanks for your feedback.

> But I still think that a null check should be also added for collection fields. Because the developers can forget to add the update methods of collection fields and also this is an extra effort when DTOs contains multiple collection fields.

I agree hence I wrote #954 to cover this (see my reasoning there). But, we also have to take into consideration that a user actually might want to have `null` when source property is `null`.  There's a PR pending. I hope I can convince the others to take it still in. 

I'll continue to close this one..

**Comment by gerardbosch** [comment]
As this discussion got very long, if someone is looking how to only update non-null fields, it can be achieved using:

```java
@BeanMapping(nullValuePropertyMappingStrategy =  NullValuePropertyMappingStrategy.IGNORE)
```

in the mapping method, together with the `@MappingTarget` in the mapper target argument.

This way, only defined (non-null) properties in the source will mutate the target. Hope it helps!
