### ISSUE TITLE
defaultValue will not be set

### ISSUE THREAD

**Issue by Mendred** [mapstruct/mapstruct#650]
Hello,

I try to set a defaultValue if a field is null in my Mapping.
The class is generated by mapStruct, but there is no null check and no defaultValue either. 

I'm using 1.0.0RC2 without java8.

```java
@Mappings({@Mapping(target = "startJahr", source = "jahr", defaultValue = "2015")})
    TarifTO mappeTarifInTarifTO(Tarif tarif);
```

```java
@Override
    public TarifTO mappeTarifInTarifTO(Tarif tarif) {
        if ( tarif == null ) {
            return null;
        }

        TarifTO tarifTO = new TarifTO();

        tarifTO.setStartJahr( tarif.getJahr() );
        tarifTO.setSparte( tarif.getSparte() );

        return tarifTO;
    }
```

Have I done something wrong?

**Comment by gunnarmorling** [comment]
No, your usage looks right. Could you try for a property where source and target name don't differ? Maybe we are accidentally not applying the default value in the case where they differ. @sjaakd, any idea?

**Comment by gunnarmorling** [comment]
@mendred, what is the type of `jahr` on the source side? Is is a primitive type by any chance (`int` as opposed to `Integer`)? If so, that'd explain why there is no null check generated.

**Comment by sjaakd** [comment]
@gunnarmorling good point.. @Mendred , if this is not the case could you provide a complete example?

**Comment by Mendred** [comment]
Omg. My fault. Im using primitives. Thank you

**Comment by gunnarmorling** [comment]
> @gunnarmorling good point..

Yes, but to be fair, some clever bird gave me that hint ;)

> Omg. My fault. Im using primitives. Thank you

Cool, closing it then. Glad to hear all works :)
