### ISSUE TITLE
IllegalArgumentException in MappingProcessor when using Prototyping in shared conf

### ISSUE THREAD

**Issue by Mendred** [mapstruct/mapstruct#651]
Hello,

first of all thank you for your help yesterday.
I'm actually learning how to use MapStruct and I tried to use prototyping like you do in your example:

```java
@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG)
public interface CentralConfigWithPrototyping {

    @Mapping(source = "basePrimaryKey", target = "toKey")
    BaseTO mappeBaseInBaseTO(BaseEntity baseEntity);
}
```

The basePrimaryKey and toKey are Integers (Wrapper) with generated getters and setters.
Tthe TarifTO inherits BaseTO and Tarif inherits BaseEntity
```java
@Mapper(config = CentralConfigWithPrototyping.class)
public interface ConfigMapperWithPrototyping {
    TarifTO mappeTarifInTarifTO(Tarif tarif);
}
```

Eclipse shows the following error message:

![2015-10-02 10_05_48-](https://cloud.githubusercontent.com/assets/14924849/10241943/58f1a0c8-68ed-11e5-89cd-7a643b288a4a.png)

**Comment by sjaakd** [comment]
hi @Mendred,

This is a known issue of the Eclipse compiler. See #644. I've been trying to find a work around for this one. Alternatively: does it build with Maven?

I'll close this issue.
