### ISSUE TITLE
hard to make it work in android studio and gradle system.

### ISSUE THREAD

**Issue by zbobyuan** [mapstruct/mapstruct#652]
mspstruct is awesome, but it's a little hard to config in gradle system. http://mapstruct.org/news/2013/07/08/using-mapstruct-with-gradle.html

Do you have a plan to improve it?
Some code generation tools like dagger2 are very easy to use in gradle system, just add a line to build.gradle:
compile 'com.google.dagger:dagger:2.0.1'

**Comment by agudian** [comment]
You should be able to do just the same with MapStruct: 
* add ..:mapstruct:.. as 'compile' dependency (in case you use a component model other than 'default', you can also use 'provided').
* add ..:mapstruct-processor:.. as 'provided' dependency.

That should do it just the same as the dagger-compiler. I didn't try, though. :wink: 

Would you give it a try? Perhaps you could send a pull-request for an additional example in our mapstruct/mapstruct-examples repository?

**Comment by gunnarmorling** [comment]
There actually is a PR for simplifying the Gradle example already, it just slipped my mind to merge it: https://github.com/mapstruct/mapstruct-examples/pull/4. Would that be good enough, @zbobyuan?

@agudian I will merge the PR this weekend, just need to put the latest Gradle wrapper there, the one provided seemed not to be the current one IIRC.

**Comment by gunnarmorling** [comment]
Ok, I've merged that PR for the examples project. The - greatly simplified - build.gradle file is here: https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-on-gradle/build.gradle

@zbobyuan Can you check that out and let us know whether that's what you are after.

@agudian, @sjaakd I guess we could write another blog post describing that much simpler set-up :)

**Comment by zbobyuan** [comment]
Great, thanks!
