### ISSUE TITLE
mapping collections/arrays with multiple input collections/arrays

### ISSUE THREAD

**Issue by SoSayethSimon** [mapstruct/mapstruct#653]
Hello,

I want to map two Arrays (both with the same size) into a Bean-List. The normal mapping between the two Elements and a single Bean works.

The standard Array-to-Collection Mapping though doesn't work this way and generates just a method making a nullcheck and creating an empty List. This is probably the case, because the processor can't know the length of the given Arrays and the mapping would be ambiguous, right?

However it would be quite possible to create a definite mapping in my case, since both Arrays always share their size. Maybe it's possible to create a standard implementation, which checks the size of both arrays and maps them into the Bean-Collection in case of an identical size? The same could of course also be applied in Collection-to-Collection and Array-to-Array mapping.

Right now i'm using 1.0.0.CR2 and can't find a similar implementation, so i would like to know your opinion on this :)

Some example sources below:

Bean:
```Java
public class FooBean {
	
	private String attributeOne;
	
	private DateTime attributeTwo;
	
	public String getAttributeOne(){
		return attributeOne;
	}
	
	public String setAttributeOne(String attributeOne){
		this.attributeOne = attributeOne;
	}
	
	public DateTime getAttributeTwo(){
		return attributeTwo;
	}
	
	public DateTime setAttributeTwo(DateTime attributeTwo){
		this.attributeTwo = attributeTwo;
	}
	
}
```

Interface:
```Java
@Mapper
public interface FooInterface {

	public FooBean mapElementsToBean(String attributeOne, DateTime attributeTwo);
	
	public List<FooBean> mapElementArraysToBeanList(String[] attributeOnes, DateTime[] attributeTwos);
	
}
```

Generates roughly this Implementation:
```Java
public class FooInterfaceImpl implements FooInterface {

	@Override
	public FooBean mapElementsToBean(String attributeOne, DateTime attributeTwo){
		if (attributeOne == null || attributeTwo == null){
			return null;
		}
		
		FooBean FooBean = new FooBean();
		
		FooBean.setAttributeOne(attributeOne);
		FooBean.setAttributeTwo(attributeTwo);
		
		return FooBean;
	}

	@Override
	public List<FooBean> mapElementArraysToBeanList(String[] attributeOnes, DateTime[] attributeTwos){
		if (attributeOnes == null || attributeTwo == null){
			return null;
		}
		
		List<FooBean> list = new ArrayList<FooBean>();
		
		return list;
	}
}
```

But could generate this implementation of mapElementArraysToBeanList:
```Java
	@Override
	public List<FooBean> mapElementArraysToBeanList(String[] attributeOnes, DateTime[] attributeTwos){
		if (attributeOnes == null || attributeTwo == null){
			return null;
		}
		
		List<FooBean> list = new ArrayList<FooBean>();
		
		if (attributeOnes.length == attributeTwo.length) {
			for(int i = 0; i < attributeOnes.length; i++) {
				list.add(mapElementsToBean(attributeOnes[i], attributeTwo[i]));
			}
		}
		
		return list;
	}
```

**Comment by sjaakd** [comment]
MapStruct is in essence a bean mapping framework. So, when mapping A to B the essence is that the properties of A are mapped to B.

Some history:

In the evolution of MapStruct we first considered that A could also be mapped from B1 and B2.  In case of conflicts (e.g. B1 and B2 both share a property attributeOne), you need to specify which one you want to take by means of an `@Mapping` annotation.

When implementing  nested source properties (so source B.attributeOne.sub1) , we found a need that you need to specify the argument-name as well, in case of mapping  multiple sources (B1, B2). So in your first mapper example: `attributeOne`. We -at that point- included the option to map non bean objects as source objects (as fall back option).

-----
What's not implemented is selection of mapping methods that have 2 (or more source arguments B1, B2) in a bean mapping. This problem category on its own and already poses a lot  of problems. So, in your `generated code` the calling of `mapElementsToBean(attributeOnes[i], attributeTwo[i])` from `public List<FooBean> mapElementArraysToBeanList(String[] attributeOnes, DateTime[] attributeTwos)` . 

-----

However, you can already realize your use case. You need to implement a hand written method. You can do this by creating an abstract class as mapper:

```java
@Mapper
public abstract class FooInterface {

    public  abstract FooBean mapElementsToBean(String attributeOne, DateTime attributeTwo);

    public List<FooBean> mapElementArraysToBeanList(String[] attributeOnes, DateTime[] attributeTwos){
        if (attributeOnes == null || attributeTwo == null){
            return null;
        }

        List<FooBean> list = new ArrayList<FooBean>();

        if (attributeOnes.length == attributeTwo.length) {
            for(int i = 0; i < attributeOnes.length; i++) {
                list.add(mapElementsToBean(attributeOnes[i], attributeTwo[i]));
            }
        }

        return list;
    }
}
 ```

So assuming this method is an exception, you can make use MapStruct using many of the methods you declare abstract. The stuff MapStruct can't do, you can do that yourself by implementing the method yourself.

**Comment by SoSayethSimon** [comment]
Thank you for the fast answer! I implemented the method you described for my use case, and it works perfectly. The issue can therefore be closed :)

Still, i'm curious about the selection of mapping methods with 2 or more arguments. Is that implementation something to look forward to in future releases? Or did you dismiss it, in order to keep the complexity at bay?

**Comment by sjaakd** [comment]
> Or did you dismiss it, in order to keep the complexity at bay?

That's indeed the current status quo.  Perhaps you can open an issue (feature request) on specifically the selection of methods with more than one source arguments. If there's more interest in this feature we can discuss it further. 

Thanks for your feedback.
