### ISSUE TITLE
"No implementation type" Error Despite @BeanMapping(resultType=...) Being Set to Type with Default Constructor

### ISSUE THREAD

**Issue by mbach979** [mapstruct/mapstruct#657]
MapStruct fails in the following case with a "No implementation type is registered for return type" error despite the @BeanMapping(resultType=...) being specified with a class that has an accessible default constructor.

```
interface i1
{
    public String getId();
    public void setId(String id);
}

class i1impl implements i1
{
    private String id;

    public i1impl()
    {
    }

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }
}

class dto
{
    private String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }
}

@Mapper
public interface i1dtoMapper
{
    @BeanMapping(resultType=i1impl.class)
    public i1 dto2i1(dto src);
}
```

Looking at the code it seems that the BeanMappingMethod.build() has code to handle this by setting resultType on the resulting instance, but the validation of the method in MapperCreationProcessor.getMappingMethods() only checks for whether the BeanMappingMethod has a factoryMethod, and not whether the resultType is a concrete class.   

Hacking in an additional condition to look at the result type of the BeanMappingMethod and therefore not throwing the error seems to fix the problem.  The generated mapper correctly instantiates the @BeanMapping(resultType=..) specified class using the default constructor.

**Comment by agudian** [comment]
Looks like you already have some insight here. Would you be willing to turn this into a pull-request including tests and possibly updates to the Javadoc of the annotation?

**Comment by gunnarmorling** [comment]
So far, `@Mapping#resultType()` was only intended as means of narrowing down several matching factory methods. I don't see a problem with using it for the purpose you describe, so if you send in a PR I'd happily apply it.

Of course there is always the work-around of specifying the more specific (implementation) type in the mapping method definition, so it's not a blocker.

**Comment by domdorn** [comment]
any updates here? 
I'm trying to do mapping to a interface and specify the implementation class somehow, but I'm unable 

code looks like this:

    @BeanMapping(resultType = ModifiableOpeningTime.class)
    OpeningTime mapOpeningTime(otherpackage.model.OpeningTime value);

ModifiableOpeningTime is a normal POJO, OpeningTime is a interface

thx

**Comment by agudian** [comment]
@domdorn That shouldn't be too hard to do, but sending in a PR would speed things up... :)
In the meantime, you'd have to use factory-methods (http://mapstruct.org/documentation/1.1/reference/html/index.html#object-factories)

**Comment by filiphr** [comment]
This has been resolve in #998. @mbach979, @domdorn you can have a look at the 1.2.0-SNAPSHOT and let us know if your problems are resolved 😄
