### ISSUE TITLE
Remove "mapping method of iterable to non-iterable type"-error if iterable param is used as targettype-field-source

### ISSUE THREAD

**Issue by gbrehmer** [mapstruct/mapstruct#661]
example: 

```java
class EntityA {
  String propA;
  String propB;
  List<EntityB> items;
}

class ResultDtoA {
  String propA;
  String propB;

  ResultDtoB dtoB;
}

class ResultDtoB {
  List<EntityB> items;
}

@Mapping(source = "items", target = "dtoB")
ResultDto mapAtoDtoA(EntityA a)

@Mapping(source = "items", target = "items") // not necessary
ResultDtoB mapBtoDtoB(List<EntityB> items)
```

Use case: Existence of EntityA doesn't mean, that an instance of ResultDtoB should be present, too. Only if the list of EntityB's is not empty (or not null if easier), an instance of ResultDtoB should be generated. First generated mapping method is optional because my current use case needs custom mapping methods before starting with mapping of list of EntityBs.

Workaround w/o first generated mapper method is to add an additional parameter to the second method. e.g.:
```java
@Mapping(source = "items", target = "items") // not necessary
ResultDtoB mapBtoDtoB(Void workaround, List<EntityB> items)
```

**Comment by agudian** [comment]
What your trying to achive here (at least in the example) looks like another use case for #389 (nested target properties), so you would then write:

```java
@Mapping(source = "items", target = "dtoB.items")
ResultDtoA mapAtoDtoA(EntityA a)
```

Whether or not an instance of `ResultDtoB` would be created there (as you propose to configure with #662) is something that needs to be solved for the nested target property feature as well.

(I'm not saying we should or shouldn't do this, I'm just trying to get this into context with the other open feature-issues)

**Comment by gbrehmer** [comment]
yes, thanks, I didn't recognize #389 before. then this request could be closed, especially because the last mapping method from my entire example is not necessary anymore.
