### ISSUE TITLE
Use JDK and Eclipse compiler in AnnotationProcessorTestRunner

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#667]
The recurring problems that we have with subtle and not-so-subtle differences in the APT API implementation in JDK and in the Eclipse compiler show that our integration tests don't cover enough cases.

So I propose to just use our processor tests, which contain all sorts of edge cases and specific feature tests, and run the processor not only with the JDK compiler, but also with the Eclipse compiler. Kind of like the JUnit Parameterized runner, all test methods would be executed with the JDK variant _and_ the JDT variant.

**Comment by gunnarmorling** [comment]
Done.
