### ISSUE TITLE
Add support for hasX methods to check if a source property X should be set

### ISSUE THREAD

**Issue by spoerri** [mapstruct/mapstruct#669]
Please support mapping to and from instances of message classes generated by Google Protocol Buffers (version 2).

In addition to simple getters for primitive fields, these classes have methods that indicate whether the field is set on the message at all.

If the field is not set of the source object (protobuff), we should refrain from setting it on the destination object.

E.g. protobuf generated code:
public double getPrice();
public boolean hasPrice();

And on a separate builder object, just:
public void setPrice(double price);

We should generate:
if (carMessage.hasPrice()) {
 car.setPrice(carMessage.getPrice());
}

And:
if (car.hasPrice()) {
 carMessage.setPrice(car.getPrice());
}

**Comment by matt-blanchette** [comment]
A similar use case is the Guava/JDK8 Optional types, with isPresent() boolean check before calling setter (and an extra .get() call for the value).

**Comment by agudian** [comment]
Hi @spoerri,

interesting idea! Adding support for `hasX()` methods is certainly something that we can do.

Calling that "support for protocol buffers" might be a bit too far fetched, though. Looking at the Docs, it seems that they suggest using builder classes for the instance creation, and that might just be a whole different story - although we already support stuff like `addX(X x)` for collections, so mapping into builder instances would probably work.

Anyway, let's do this step by step. Would it be OK for you if we changed the title of this issue to something like "Add support for hasX methods to check if a source property X should be set"?

You'd then probably hit the same problem that the feature request #649 addresses.

**Comment by agudian** [comment]
> A similar use case is the Guava/JDK8 Optional types, with isPresent() boolean check before calling setter (and an extra .get() call for the value).

I'd see `Optional` as a slightly different case (because of the get() and the creation semantics), but one that we definitely should support. I'm creating a new issue for that.

**Comment by gunnarmorling** [comment]
@agudian, did you ever create that issue for `Optional`?

**Comment by sjaakd** [comment]
fixed and implemented by means of SPI and annotation

**Comment by Spaum145** [comment]
Is this hasX method still supported? Can't make it work in 1.2.0.Final.

**Comment by filiphr** [comment]
@Spaum145 yes this should still be supported. As this is quite an old issue can you please create a new issue with your problem. Maybe a reproducal case would be ideal, as we have tests for this and it works

**Comment by Spaum145** [comment]
@filiphr thanks for attention. I've managed to use this feature with help of nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS in Mapper annotation.
