### ISSUE TITLE
Unclear error logging

### ISSUE THREAD

**Issue by bademux** [mapstruct/mapstruct#671]
Hello,
Unuseful error message is shown when  
```java 
@Mapper() class TestConverter extends Converter{} 
```
The error message mention parent Converter class, while the problem is in TestConverter (annotated with Mapper).
Debugging is really unpleasant if you have multiple Converters (Mappers) extending the same base class.

[ERROR]  <path>/Converter.java:[13,23] Can't map property "com.example.Test test" to "com.example.DtoTest test". Consider to declare/implement a mapping method: "com.example.DtoTest map(com.example.Test value)".

**Comment by agudian** [comment]
Hi @bademux, thanks for the report! We already have an issue that goes into the same direction: #598.

So I'm closing this as a duplicate. If you feel that this is something else, please reopen - if you feel that the other issue lacks some information, then please comment there.

Thanks!
