### ISSUE TITLE
Rename interfacePackage in ServiceEntry and GeneratedType

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#673]
As Sjaak noticed in a review on `ServicesEntry`:

> just out of curiosity: shouldn't getInterfacePackage() not be renamed to getMapperPackage()?
> ... as it doesn't necessarily correspond to the package name of an `interface`, if the type annotated with `@Mapper` is an `abstract class`.

And I said:

> Right. We could rename it, but to be constent it should be renamed in `GeneratedType` and thus in `Mapper` and `Decorator` as well. And then it would be a bit more difficult to differentiate between "mapper implementation" and "mapper" and "decorator"... perhaps something like "superTypePackage"? Sounds a bit bulky...

**Comment by gunnarmorling** [comment]
This affects just internal implementation types, right?

**Comment by agudian** [comment]
Right, there is no inpact for users.

**Comment by thunderhook** [comment]
The mentioned methods do not exist anymore, so I'll close this issue.
