### ISSUE TITLE
Strange exception in logs "ClassNotFoundException: org.mapstruct.Mapper"

### ISSUE THREAD

**Issue by bademux** [mapstruct/mapstruct#675]
Hello,
I have strange exceptions in logs while starting tomcat8 for all my autogenerated Mappers. 
What it can be?
Thanks.

```java
2015-10-28 18:18:02,050 [main] DEBUG o.s.c.a.ClassPathBeanDefinitionScanner - Identified candidate component class: URL [jar:file:/<path>/mapper/target/mapper-1.0.jar!/com/example/converter/MyMapperImpl.class]
2015-10-28 18:18:02,051 [main] DEBUG o.s.c.t.c.AnnotationAttributesReadingVisitor - Failed to class-load type while reading annotation metadata. This is a non-fatal error, but certain annotation metadata may be unavailable.
java.lang.ClassNotFoundException: org.mapstruct.Mapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_65]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_65]
	at org.springframework.core.type.classreading.RecursiveAnnotationAttributesVisitor.visitEnd(RecursiveAnnotationAttributesVisitor.java:47) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
...
```

**Comment by agudian** [comment]
Apperently, if you use Spring, then the dependency org.mapstruct:mapstruct (or the -jdk8 variant, if you use that) needs to be on the classpath / in your war. So using the 'provided' scope won't work.

**Comment by bademux** [comment]
Why this happen?
I need only code-generation ability of the library Mappers#getMapper(Class) isn't used (spring component model actually in use).

**Comment by agudian** [comment]
During the Spring component scan, Spring expects all class annotations to be on the classpath (apparently). Instead of ignoring missing annotations, the folks at Spring seem to have decided to treat that as an error :-/

**Comment by bademux** [comment]
So maybe it is worth to externalize annotations as separate lib org.mapstruct:annotation?
For most of users it will be transparent change, and the new lib can be used as public API while annotation processing tool - as impl.
Summarizing pure annotation lib can used in the same manner as hibernate-jpa-2.0-api.
I can put the annotation lib into on classpath, making spring happy.
IMHO, it is the last moment (before final) to do this 
Anyway thanks for support.

**Comment by agudian** [comment]
That's already how it is: the annotations are in org.mapstruct:mapstruct (or org.mapstruct:mapstruct-jdk8) and the processor is in its own jar, in org.mapstruct:mapstruct-processor.

**Comment by bademux** [comment]
I was thinking about light artifact with annotations and interfaces only, the one can be included into war to make spring and compiler happy.

**Comment by agudian** [comment]
Besides that Mappers class and the annotations, there is nothing else in the mapstruct.jar (or mapstruct-jdk8.jar). It comprises the user-code API.
What would you add or remove there?

**Comment by bademux** [comment]
Jar with one annotation looks creepy, but copy-pasting Mapper class, or bytecode manipulation is not "buy and go" solution...
As for me I prefer light artifact from mapstruct. And the worst solution will be leave application with exceptions in logs.

**Comment by agudian** [comment]
Sorry, but I think I don't understand. The mapstruct.jar is exactly what you need to add to your classpath in order to satisfy Spring's wish for seeing the annotations. Because it won't stop with one annotation. Depending on what you do with it, Spring also checks annotations on methods or method parameter. And there you are, you need those annotations on the classpath.
I don't see how having the Mappers class (the only thing that's not an annotation in that jar) could be troublesome - as it is part of the API when mapstruct is used with the default component model.
What am I missing?

**Comment by bademux** [comment]
Ah, sorry for my stupidity. mapstruct-jdk8-X.X.X.jar ( mapstruct-X.X.X.jar) is light enough for my needs.
Thanks again.
Issue can be closed.

**Comment by gunnarmorling** [comment]
Ok, cool. @agudian, should we add this as an entry to a new FAQ section on the web-site? I imagine it's a more common issue for Spring users. WDYT?

**Comment by kvneswar** [comment]
Issue has been resolved by adding the following dependencies:

compile group: 'org.mapstruct', name: 'mapstruct-processor', version: '1.0.0.Final'
compile group: 'org.mapstruct', name: 'mapstruct', version: '1.0.0.Final'

**Comment by rajneekanth** [comment]
@kvneswar , after adding these dependencies, i am getting this error. 
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper

**Comment by filiphr** [comment]
@rajneekanth the class that is missing is a class from Jackson and not from MapStruct. MapStruct has no dependencies towards Jackson. Make sure your setup is correct. Have a look at the [mapstruct-examples](https://github.com/mapstruct/mapstruct-examples) and the documentation on our [website](http://mapstruct.org/) to correctly set everything up.

**Comment by rajneekanth** [comment]
ok, i corrected it and now i am getting another error related to JNDI. 

by any chance you have encountered this error? any helping hand will be highly appreciable. Thank you.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Cannot convert value [com.lloydstsb.luis.jndi.JNDIContext@1fbc2bf {}] from source type [JNDIContext] to target type [String]

**Comment by filiphr** [comment]
@rajneekanth this has nothing to do with MapStruct. I would suggest you to search for this on Google or Stackoverflow in order to solve your problem
