### ISSUE TITLE
Create a Gitter room for the project

### ISSUE THREAD

**Issue by anaumidis** [mapstruct/mapstruct#676]
It will be nice to create a gitter room for mapstruct.

**Comment by gunnarmorling** [comment]
Hi, there is a room already: https://gitter.im/mapstruct

There has been noch much activity there really, but I should get notified in case someone posts something, so feel free to give it a try. I'll close this issue "out of date". Thanks!

**Comment by anaumidis** [comment]
There is no room... Just organization's profile...

Consider creating a room for the repository...

**Comment by gunnarmorling** [comment]
Hi, have you been logged into Gitter when testing it? The room is there for sure (we'used it a while ago and I still see the logs from back then), but I suppose you must be logged in.

**Comment by gunnarmorling** [comment]
Had another look; The original room was for org members only; I've created another public room now: https://gitter.im/mapstruct/mapstruct-users. Let me know in case you have trouble accessing it. Thanks!
