### ISSUE TITLE
Support for Sync and Clone

### ISSUE THREAD

**Issue by nagkumar** [mapstruct/mapstruct#68]
Hi,

Would it be possible to have sync and clone method support so that, when I am converting DTO to DAO, I can say all the DTO instance data is synced with an existing instance of DAO object..

Regards,
Raja Nagendra Kumar
C.T.O
www.tejasoft.com

**Comment by sjaakd** [comment]
@nagkumar , @gunnarmorling : I think this is basically there with the `@MappingTarget` and going to be enhanced with #160. I'll mark it as duplicate (#160 contains more information). WDYT?

**Comment by agudian** [comment]
Closing as duplicate of #160... :smile: Let's reopen it in case we missed something that @nagkumar had in mind additionally.
