### ISSUE TITLE
Inconsistent timezone conversion between new- and old-style date-time objects

### ISSUE THREAD

**Issue by Zetten** [mapstruct/mapstruct#681]
The following simplified test case (I think) shows that the symmetry of the mapping function will fail for conversions between Date and LocalDateTime when the system timezone is not equivalent to UTC:
```
public class A {
    private java.util.Date date;
}

public class B {
    private java.time.LocalDateTime date;
}

@Mapper
public interface ABMapper {
        B aToB(A obj);
        A bToA(B obj);
}

@Test
public void test() {
    ABMapper mapper = Mappers.getMapper(ABMapper.class);
    A a = new A();
    a.setDate(new Date());
    assertEquals(a, mapper.bToA(mapper.aToB(a)));
}
```

The issue seems to be in [JavaLocalDateTimeToDateConversion](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateTimeToDateConversion.java) where the mapping in one direction uses an offset from UTC of zero (i.e. `ZoneOffset.UTC`) and in the other direction uses an offset based on the local system timezone (`ZoneId.systemDefault()`).

Maybe I've misunderstood something, but it's caused a test error in my project so I'm curious to know if this is intended behaviour :)

I realise that the two types are not _directly_ translatable thanks to the intricacies of zone offsets, but would it be possible to restore symmetry to the mapping by making the timezone configurable? E.g. I can create a custom mapping that just flattens the Date-derived Instant into UTC, which is not perfect but at least fits my needs right now:
```
    public LocalDateTime toJava8(Date date)
    {
        return date == null ?
            null :
            LocalDateTime.ofInstant(date.toInstant(), ZoneId.ofOffset("", ZoneOffset.UTC));
    }
```

**Comment by gunnarmorling** [comment]
Hi @Zetten, thanks for this report! Agreed, the conversion should be symmetric. I will change the `Date` to `LocalDateTime` conversion so it uses UTC, too.

**Comment by agudian** [comment]
Fix is merged.

**Comment by Zetten** [comment]
Looks good, thanks very much!
