### ISSUE TITLE
Incompatibility between Joda 2.3 and JDK 1.8.0_60 leads to test failures

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#684]
I had already fixed that once with commit feb5e2f13b0eea3027000cc7f03d6b63690505c5, not knowing by then that this was a known compatibility issue between Joda versions before 2.9 and JDK 1.8.0_60 (and above).
I'd like to revert my previous fix in favour of just updating the Joda version that we use during the tests.

**Comment by gunnarmorling** [comment]
PR Merged; Thanks, @agudian!
