### ISSUE TITLE
Generic property type is not determined correctly if an @Mapping is given

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#687]
If you have a generic source property accessor 'T getItem()' and configure an '@Mapping(source="item", ...)', then the generic type is not resolved for the accessor method within the declared source type.

Can be reproduced with the test case I added to the asMemberOf PR. The fix is also alredy included there as a separate commit (which will get a new commit message).

**Comment by gunnarmorling** [comment]
Done.
