### ISSUE TITLE
Overridden methods are not correctly filtered out in some interface-constellations

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#688]
The GenericsHierarchyTest added in the asMemberOf PR contains class hierarchies with classes that implement multiple interfaces, with the interfaces declaring the 'same' methods but with shadowing signatures.
The current algorithm in Executables doesn't support that case and assumes that method specializations only occur within one linear type hierarchy (and not between sibling interfaces that are both implemented by one class).
As a consequence, the test fails - at least when uses with the JDK compiler.
The PR already contains a fix in Executables for this.

**Comment by gunnarmorling** [comment]
Done.
