### ISSUE TITLE
Rename test classes/methods used in GenericsHierarchyTest

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#693]

**Comment by gunnarmorling** [comment]
@agudian Assigned it to you, hope that's alright ;)

**Comment by agudian** [comment]
I was hoping you'd take this one - I still have no great idea for those names... :grin:

**Comment by gunnarmorling** [comment]
Ok, I'll send a PR for it.

**Comment by gunnarmorling** [comment]
Done.
