### ISSUE TITLE
@Mapping enum to default doesn't add import for enum

### ISSUE THREAD

**Issue by kevinmic** [mapstruct/mapstruct#698]
I am trying to map an enum to a default value like this

@Mapping(target = "type", defaultValue = "A")

The target enum is in a different package than the mapper.  When the mapper generates I get a compile error in the generated class saying "cannot find symbol".  I went and looked at the generated code and it all looks correct except there is no import statement for the defaulted enum.

I can get around it if I add a mapping for the enum to itself like below, but I would rather not.

public ObjType toType(ObjType type);

Note, I am using version 1.0.0.CR2 of mapstruct.

**Comment by agudian** [comment]
Indeed, that's a bug - fortunately it's easy to fix. :wink:
