### ISSUE TITLE
Do not use Enum.valueOf in EnumStringConversion, at least not for constants

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#700]
`EnumStringConversion` currently uses `Enum.valueOf` to convert from a String to an enum.

When mapping to an enum using `@Mapping#constant()` or `@Mapping#defaultValue()`, we shouldn't use that, but instead use the enum instance directly - and, most importantly, raise a proper error message in case the provided value is not the name of an enum instance of the required type. Currently, you'd get an IllegalArgumentException at runtime if you have a typo in there.

**Comment by gunnarmorling** [comment]
Filing bugs on release day, how dare you ;-)

**Comment by agudian** [comment]
That's why I labled it an "enhancement"... :wink:

**Comment by sjaakd** [comment]
going to close this one. Fixed by PR. @agudian thanks for reviewing
