### ISSUE TITLE
Misleading hint

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#703]
I'm currently implementing  a larger example (complete use case).  I think this yields some nice discussion material when ready :smile:

First: the following hint is misleading..

MapStruct:

org/mapstruct/example/mapper/reusable/GeoToolkitMapper.java:[46,69] Can't map property "javax.xml.bind.JAXBElement<? extends net.opengis.gml.v_3_2_1.AbstractSurfaceType> abstractSurface" to "org.geotoolkit.gml.xml.v321.AbstractSurfaceType abstractSurface". Consider to declare/implement a mapping method: "org.geotoolkit.gml.xml.v321.AbstractSurfaceType map(javax.xml.bind.JAXBElement<? extends net.opengis.gml.v_3_2_1.AbstractSurfaceType> value)”.

However, implementing this method does not solve the problem.

**Comment by jrevillard** [comment]
Hi @sjaakd,

I'm facing the same issue, what's the correct way of solving it then ?

Best,
Jerome

**Comment by jrevillard** [comment]
Well, I basically implemented them manually for the moment.

**Comment by sjaakd** [comment]
> I'm facing the same issue, what's the correct way of solving it then ?

@jrevillard Thanks for your comment. We need to revisit wildcards and generic types. Hopefully we don't need the error message anymore by then.

**Comment by sjaakd** [comment]
Just tried this one.. It seems to work now...
