### ISSUE TITLE
"product_id" style assign to  "productId"

### ISSUE THREAD

**Issue by wangtengchao** [mapstruct/mapstruct#705]
Is there anyway to convert "product_id" style to "productId" style , not hard coding? 
I only know this function below:
@Mapping(target = "productId",source = "product_id"),

Thank you !

**Comment by gunnarmorling** [comment]
You might be able to do this with the SPI for property accessor discovery (see this [blog post](http://mapstruct.org/news/2015/06/11/mapstruct-1_0_0_CR1-has-landed.html) for some details). This would allow you to have a getter named `getXyz_Id()` be considered as accessor for a property named `xyzId`.

Would be interested in how that goes, so any feedback is welcome. I am going to close this issue, as it's more a question than a feature/bug report. Please use the mapstruct-users group preferably for asking questions. Thanks!
