### ISSUE TITLE
can't mapping the source to target error always occurred 

### ISSUE THREAD

**Issue by ahmadw** [mapstruct/mapstruct#715]
Hi,
 
I am new in mapstruct and I am using spring as DI I follow up your documentation regarding DI containers I tried to map my entity to dto  as below :

@Mapper(componentModel = "spring")
public interface CustomerMapper {
    @Mapping(source = "registered",target = "activeProfile")
    CustomerDto customerToCustomerDto(Customer customer);
}

when i run mvn install i get this error : 
java:27: error: No property named "registered" exists in source parameter(s).
    @Mapping(source = "registered",target = "activeProfile")

my entity using lombok and I am sure there is registered field 

please help

**Comment by ahmadw** [comment]
the problem was from lombok in the entity once I removed it and created setters/getters all goes well

**Comment by gunnarmorling** [comment]
Hi, yes, it's a known issue that Lombok doesn't play well together with other annotation processors that require to see the entire state of Lombok-modified classes. See #510 for some details.

**Comment by leonardomartins92** [comment]
You can add lombok to mapping's plugin path 
`	<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.8.1</version>
			<configuration>
					<source>1.8</source> 
					<target>1.8</target> 
					<annotationProcessorPaths>
					       <path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
						
			</annotationProcessorPaths>
		</configuration>
	</plugin>`

**Comment by leonardomartins92** [comment]
You can add lombok to mapping's plugin path:
                                                `<path>
 							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
 							<version>${lombok.version}</version>
 						</path>`
