### ISSUE TITLE
can't be used with spring data

### ISSUE THREAD

**Issue by xiaomige** [mapstruct/mapstruct#719]
this is my pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.jeremy</groupId>
  <artifactId>mapstruct-project</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
	<parent>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-parent</artifactId>
	    <version>1.3.1.RELEASE</version>
	</parent>
	<dependencies>
	    <dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-web</artifactId>
	    </dependency>
	    
	    <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		
		<dependency> 
			<groupId>org.springframework.boot</groupId> 
			<artifactId>spring-boot-starter-data-jpa</artifactId> 
		</dependency> 
		
		<dependency>
	      <groupId>mysql</groupId>
	      <artifactId>mysql-connector-java</artifactId>
	    </dependency>
		
	    <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20141113</version>
		</dependency>
	    
	      
	    <dependency>
	        <groupId>org.mapstruct</groupId>
	        <artifactId>mapstruct-jdk8</artifactId>
	        <version>${org.mapstruct.version}</version>
	    </dependency>
	    
	    
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>bootstrap</artifactId>
			<version>3.3.4</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>jquery</artifactId>
			<version>2.1.4</version>
		</dependency>
	</dependencies>

 	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
		<org.mapstruct.version>1.0.0.Final</org.mapstruct.version>
    </properties>

    <build>
        <plugins>
        
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
             
            <plugin>
	            <groupId>org.bsc.maven</groupId>
	            <artifactId>maven-processor-plugin</artifactId>
	            <version>2.2.4</version>
	            <configuration>
	                <defaultOutputDirectory>
	                    ${project.build.directory}/generated-sources
	                </defaultOutputDirectory>
	                <processors>
	                    <processor>org.mapstruct.ap.MappingProcessor</processor>
	                </processors>
	            </configuration>
	            <executions>
	                <execution>
	                    <id>process</id>
	                    <phase>generate-sources</phase>
	                    <goals>
	                        <goal>process</goal>
	                    </goals>
	                </execution>
	            </executions>
	            <dependencies>
	                <dependency>
	                    <groupId>org.mapstruct</groupId>
	                    <artifactId>mapstruct-processor</artifactId>
	                    <version>${org.mapstruct.version}</version>
	                </dependency>

	            </dependencies>
	        </plugin>

        </plugins>
    </build>
    
</project>

**Comment by gunnarmorling** [comment]
What exactly is the problem? We need some more context here, otherwise it's impossible to provide you any help: What behavior do you expect, what is happening instead? Is there any error or exception?

**Comment by xiaomige** [comment]
thanks very much! It works when it to re-create new project to test, wonderful!
