### ISSUE TITLE
NPE during annotation processing with generics and nested properties

### ISSUE THREAD

**Issue by tmonney** [mapstruct/mapstruct#722]
As discussed at https://groups.google.com/d/msg/mapstruct-users/ok2OJMnbHdI/iJQeEUgvDAAJ, MapStruct fails to process the following mapper:
```java
@Mapper
public interface GenericsMapper {

    // This mapping fails with a NPE during annotation processing
    @Mapping(target = "data", source = "contents.data")
    Target mapGeneric(Source<Contents> source);

    // This mapping is fine
    @Mapping(target = "data", source = "contents.data")
    Target mapSpecialized(ContentsSource source);
}

public class Target {
    private String data;

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}

public class Source<C> {
    private C contents;

    public C getContents() {
        return contents;
    }

    public void setContents(C contents) {
        this.contents = contents;
    }
}

public class Contents {
    private String data;

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}

public class ContentsSource extends Source<Contents> {
}
```

Reproducer project is available at https://github.com/tmonney/mapstruct-generics-issue.

Thanks for looking into this!

**Comment by antslava** [comment]
Hi All, any update on this issue?

**Comment by gunnarmorling** [comment]
Hey @antslava, we didn't get yet to this. Maybe you'd be interested in helping out and send in a fix?

**Comment by gunnarmorling** [comment]
Hey @tmonney, @antslava, could you test the latest MapStruct master and see whether the issue remains? Just clone the repo, run `mvn clean install` and use "1.0.1-SNAPSHOT" as dependency version in your project.

We fixed some related bugs and this should be no issue anymore (compiling the types given in this issue succeeds for me). Thanks!

**Comment by tmonney** [comment]
Hi @gunnarmorling,

I just checked with latest snapshot and indeed it seems to work OK, both in my reproducer test case and in our "real" code.

Do you have any idea when we can expect a release with this fix?

Thanks a bunch!

**Comment by gunnarmorling** [comment]
Nice, thanks for reporting back! Going to close this then.

> Do you have any idea when we can expect a release with this fix?

We've planned to do the 1.1 Beta1 release next week or latest the week after that.

**Comment by tmonney** [comment]
OK, great!

**Comment by antslava** [comment]
Hi @gunnarmorling , it's work. Thanks for your help.
