### ISSUE TITLE
Validate value given for date format is valid

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#725]

**Comment by filiphr** [comment]
Isn't this already solved with the [DateFormatValidatorFactory](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/common/DateFormatValidatorFactory.java)? Or this issue is here to show the `@Mapping` annotation that has the error?

**Comment by gunnarmorling** [comment]
@filiphr the idea is to check whether the value given for `@Mapping#dateFormat()` et al. is valid. Re-reading the comment on that attribute I'm wondering whether it's still correct. Is it really `SimpleDateFormat` syntax when we are mapping to the Java 8 time types? This may need some updating, too.

**Comment by filiphr** [comment]
@gunnarmorling that is what that class is used for. You just need to dig a bit deeper to see that the strings passed to it are actually coming from `@Mapping`. The only downside is that we don't mark the line where that is happening. 

>Is it really SimpleDateFormat syntax when we are mapping to the Java 8 time types?

No it isn't. We do this validation:
* `SimpleDateFormat` - for `java.util.Date` source or target, and for `XMLGregorianCalendar` source or target
* Java `DateTimeFormatter` - for Java 8 time types
* Joda `DateTimeFormatter` - for Joda time types

**Comment by gunnarmorling** [comment]
Would be nice to flag the `dateFormat()` annotation element itself in case a wrong value is given.
