### ISSUE TITLE
Mapping Set<Long> to int throws NPE

### ISSUE THREAD

**Issue by greuelpirat** [mapstruct/mapstruct#729]
When the source class has an Attribute `Set<Long> attr1` and the target class has the same attributename with a simple type like `int attr1`, a NullPointerException will be thrown at 

`org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.hasCompatibleCopyConstructor(MappingResolverImpl.java:547)`

    sourceType = {org.mapstruct.ap.internal.model.common.Type@3381} "java.util.Set<java.lang.Long>"
    targetType = {org.mapstruct.ap.internal.model.common.Type@3382} "int"

**Comment by gunnarmorling** [comment]
How comes you are closing it again? The mapping isn't supported (seems not really sensible to map a set into a single int value), but this shouldn't trigger an NPE but rather a meaningful error.

**Comment by greuelpirat** [comment]
I could solved this with a workaround by adding the following mapping-method:

    default Integer sizeOfCollection(Collection<?> collection) {
        return collection == null ? 0 : collection.size();
    }

Sorry, I was a little confused, I will reopen it again.

**Comment by gunnarmorling** [comment]
Yes, that makes sense. Maybe you'd like to help out and send in a PR for having MapStruct raise a more meaningful error in this case?

**Comment by greuelpirat** [comment]
I will look for it. may take some time.

**Comment by gunnarmorling** [comment]
Cool; Looking forward to your contribution. Just let me know if you need any help.

**Comment by gunnarmorling** [comment]
Done.
