### ISSUE TITLE
Make use of constructor arguments when instantiating mapping targets

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#73]
Some thoughts:
- Need a way to select the constructor to use if there are several ones
- Properties not covered by the chosen constructor should be populated by setters
- Optionally, the mechanism should take parameterized factory methods into account

**Comment by pardom** [comment]
I would also like to see this, specifically for immutable objects. Any update?

**Comment by gunnarmorling** [comment]
No update really, but it's one of the remaining things which I think should be done for 1.0. Would you be interested in giving this a try?

**Comment by pardom** [comment]
I might be. Can you point me in the right direction?

**Comment by gunnarmorling** [comment]
Some helpful docs to get started are:

* the JavaDocs of [MappingProcessor](https://mapstruct.ci.cloudbees.com/job/mapstruct-javadoc/javadoc/index.html?org/mapstruct/ap/MappingProcessor.html) which describe the overall architecture
* the JavaDocs of [org.mapstruct.ap.model](https://mapstruct.ci.cloudbees.com/job/mapstruct-javadoc/javadoc/index.html?org/mapstruct/ap/model/package-summary.html) and [org.mapstruct.ap.processor](https://mapstruct.ci.cloudbees.com/job/mapstruct-javadoc/javadoc/index.html?org/mapstruct/ap/processor/package-summary.html)

For this issue, you'd probably have to adapt `PropertyMapping` (describs the "link" between a source and target property, so this would somehow have to express that a property is propagated by a constructor argument rather than a setter call) and `BeanMappingMethod` (describes one mapping method between two bean types, so this would have to express which constructor of the target type to invoke).

Hope this helps for a start, let me know in case you run into any road blocks. Thanks!

**Comment by pardom** [comment]
Hmm, not sure I have the time to spend on this right now, so I can't promise I'll get it done. This feature would satisfy my immutability requirement though, so kudos to whoever does it. :+1:

**Comment by mozinrat** [comment]
I would love to use this feature if its there, can anyone point me about whats being done.

**Comment by gunnarmorling** [comment]
@mozinrat no one found the time to implement it yet unfortunately. If you are interested and would like to help out with building it, let me know and I will help you to get running with Hacking on MapStruct.

**Comment by mozinrat** [comment]
@gunnarmorling whats the plan for this, lets connect on some platform email etc and discuss the possibility. I can give it a week or so but its hard for me to give any more time. Forking the repo meanwhile...:)

**Comment by gunnarmorling** [comment]
@mozinrat It should be doable in a week :)

You can send a mail to [mapstruct-users](https://groups.google.com/forum/?hl=en#!forum/mapstruct-users) to get a discussion started on the feature and its implementation. To get started, you can checkout the information given [here](http://mapstruct.org/contributing/#section-02) and the technical documentation hints given in the section after that.

I think the main issue to decide is how to select the constructor to be chosen in case there are several ones, e.g. a default (no-args) constructor and one or two constructors with arguments.

**Comment by pjean** [comment]
:+1: I would like to be able to use immutable object.
I think you should take a look at the Jackson project which uses the constructor and some annotations for serialization and deserialization. It should be quite similar to map the target.
This [issue](https://github.com/FasterXML/jackson-databind/issues/399) is a good start for investigation.

**Comment by gunnarmorling** [comment]
@pjean, yes, support for this is very high on my wish list. It's basically a question of resources, so if someone from the community stepped up to give this a shot, this would be awesome. Maybe you'd be interested?

**Comment by pjean** [comment]
Need to go deep into mapstruct code. I will take a look if I find enough time and will keep you in touch.

**Comment by afdia** [comment]
There is an alternative solution to the "which constructor to use" problem: Provider-Methods, which are used by Guice and Dagger (DI frameworks) when they should create classes without an `@Inject` annotation (I guess CDI uses the same concept but it's called Producers).

Instead of annotating a constructor, you would write a provider method. e.g.:
```
class Car {
	int doors;
	Color color;
	public Car(int doors, Color color) {
		this.doors = doors;
		this.color = color;
	}
}
```
The provider method could be located in the mapper class and would look like
```
@Provides
public Car createCar(int doors, Color color) {
	return new Car(doors, color);
}
```

This approach introduces some overhead (because the user has to map the method parameters to the appropriate constructor field), but is much more flexible and non invasive to the class which should be mapped.

This could be an advantage when classes should not or cannot be modified (e.g. generated classes) and would also enable alternative ways to create a class (e.g. calling a static creator method)

The disadvantage is that MapStruct can only verify the correctness of the provider method arguments, but not the correctness of the `method argument -> constructor argument` mapping.

I guess the best solution would be letting the user choose between both ways (80% of the time the annotation would be sufficient, but otherwise the more flexible approach would be nice to have)

Just some food for thought :)

**Comment by hyungsul** [comment]
I am currently investigating this issue. In my project, I modeled DTOs as immutable and have the same problem with this issue. Because I have a long list of parameters in DTOs, it is inefficient to list all the constructor parameters in the mapping annotation. 

For me, it is good enough to have a boolean flag like "immutable" so that all the values are mapped via a constructor instead of setters without listing all the constructor parameters in the annotation.

**Comment by gunnarmorling** [comment]
@afdia Thanks for your input! We already have "factory methods", but they don't they take arguments either. But we could enhance those, making them just like producer methods in CDI. Qualifiers could be used to resolve ambiguities.

In the end I'd like to see support for both: parameterized constructors and parameterized factory/producer methods.

**Comment by gunnarmorling** [comment]
@hyungsul, agreed some means of simplified configuration would be great, so to select between e.g. the default constructor and a single parameterized one.

**Comment by cliedeman** [comment]
I have started work on this here https://github.com/mapstruct/mapstruct/pull/847

**Comment by sjaakd** [comment]
👍 i'll take a look as soon as I'm back .

**Comment by mattiasoamz** [comment]
Would you consider adding support for Guava immutable collections as well? Not sure if it should be handled as part of this issue - it does relate to support immutable beans but from an implementation perspective it's a different thing.

**Comment by filiphr** [comment]
@mattiasoamz This can possibly done via some conversions. Can you perhaps create a new issue for this and maybe specify how would you use them (the use case)? I have not used the Guava immutable collections, and an example bean with them would be much appreciated 😄

**Comment by mattiasoamz** [comment]
@filiphr I'm sorry for my late response - the holidays got in between. I have created #1025.

**Comment by hakamairi** [comment]
Hi,
I'm currently working with a lot of immutable classes and this could be the mapping solution.
What's the progress on the issue?

The initial approach is a bit similar to @JsonCreator @JsonProperty of com.fasterxml.jackson.

**Comment by jelmew** [comment]
Hi. Is any progress made on this issue for using allargsconstructors instead of the all args constructor? Is someone working on this?

**Comment by filiphr** [comment]
@jelmew as far as I know no one is working on this one. If you want feel free to take it and try it out. There is already an old PR #847 in case you want to have a look there as well. That code probably needs to be rebased on the latest master, as there are probably quite a few changes

**Comment by wjbuys** [comment]
Could a similar approach to [Jackson's JDK8 `ParameterNames` module](https://github.com/FasterXML/jackson-modules-java8/tree/master/parameter-names) be used here? That works pretty nicely for constructing annotation-less POJOs through their constructors.

**Comment by filiphr** [comment]
@wjbuys thanks for the link. Actually MapStruct can read the constructor parameter names even on Java 6. MapStruct is an Annotation Processor and runs during the compilation phase, so we are using the `javax.lang.model` and the names are already present.

**Comment by wjbuys** [comment]
Ah, of course, that makes sense. Thanks for the clarification.

**Comment by gunnarmorling** [comment]
@filiphr, in terms of the old PR, is it realistic that it can be rebased to
current master without rewriting large parts? It may be better to close it
and start from scratch. I feel really bad about the fact we never applied
it, but at this point it seems we should be looking forward.

**Comment by mohamnag** [comment]
I think I'm a bit too late to the party, however I wanted to ask why you think the `@ConstructorProperties` can not be reused? If by type you mean the constructor's parameter type, then it should be available by reflection from method signature right?

The thing is that there are other tools outside generating and using this like lombok for generation and jackson for desalinization. This means if it can be reused, it will just fall into place even for existing libs.

**Comment by almothafar** [comment]
@gunnarmorling I was thinking about a solution for this like:

```
public class Order {
    private final long id;
    private final String name;

    public Order(@MapperConstructor long id, @MapperConstructor String name) { ... }
 }
```

Or as what @mohamnag suggested:

```
@Mapper(config = CentralConfig.class)
public interface OrderMapper {
    public static OrderMapper INSTANCE = Mappers.getMapper(OrderMapper.class);

    @ConstructorProperties(source = "name", target = "name")
    Order map(OrderDTO orderVO);

    @InheritInverseConfiguration
    OrderDTO map(Order order);
}
```

**Comment by ade90036** [comment]
Any update on this? 

Feature requrst opened since 2013 and no concrete solution as yet. 

I'm on the same boat as others. Need to work with immutable objects. Hence mapping via constructor is a must.

Regards

**Comment by ade90036** [comment]
Hi, thanks for the prompt reply.

 I have guess that. :grinning:

The constructor approach nicely fits in with other libraries such as lombok and Jackson. 

Would you be so kind to point me to PR or Issue number to see if this is something that would work in my scenario? 

I'm currently using mapstruct with lombok for standard bean / bean mapping but for entity beans (database) objects where IDs are immutable I'm using custom converter.

Regards

**Comment by sjaakd** [comment]
There's an old PR pending. We had much internal discussion on that one. The problem is that you need to relate constructor arguments with source accessors. Remember: they can have the same type, so you must have a (compile safe) mechanism to point which arg goes where...

Lombok supports a builder pattern by the way.. Not sure about Jackson though.

**Comment by eximius313** [comment]
I see that version `1.3.0` of Mapstruct focuses on immutable objects - wich is great.
Unfortunately, currently only builders are supported. 
I think that utilizing all-argument constructors (or the ones created by Lombok's @AllArgsConstructors) is vital for Immutables.

**Comment by piteron** [comment]
It would be great to have such a constructor parameters injection support. Imagine this working with Kotlin's immutable data classes.

**Comment by hamzayoussef** [comment]
Domain Driven Design users really need this feature.

**Comment by ahulyk** [comment]
any info on support Kotlin data classes?

**Comment by dsgoers** [comment]
My team had this problem because there is a field that can only be set in the constructor; no setter.  Here is what I did:
```
public abstract class Mapper {
    abstract Target toTarget(Source source, @MappingTarget Target target);

    public final Target toTarget(final Source source) {
        return toTarget(source, new Target(source.someGetter()));
    }
}
```

**Comment by marceloverdijk** [comment]
Besides using constructor arguments for mapping Kotlin [Data](https://github.com/mapstruct/mapstruct/issues/1672) classes, this will also get some interest from Java developers as with Java `Record`s coming in JDK14 as part of [JEP 359](https://openjdk.java.net/jeps/359).

**Comment by filiphr** [comment]
After almost 7 years we have finally added support for using constructors when instantiating mapping targets. 

This would be part of our next 1.4 release. I hope to have a beta as soon as possible.

**Comment by sjaakd** [comment]
Hey Filip.. Congrats!

**Comment by filiphr** [comment]
Forgot to add. This supports mapping into Java 14 records and Kotlin data classes

**Comment by ahulyk** [comment]
Cool :) Thanks!!!

**Comment by jacekgajek** [comment]
How to make a partial update while using constructor instantiation? Let's say I have a User entity and UserDto object and want to update just "name" and not "login" and "passHash". I don't want to make them mutable. Ideally I would like to set " nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE", pass a source object A: User, an existing (not updated) object B:UserDto and mapper would returned an object C:UserDto which would be like B updated with non-null properties in A.

**Comment by filiphr** [comment]
@jacekgajek there is really no need to cross post question across different places. I see that you already created [this](https://stackoverflow.com/questions/65290782/how-to-make-a-partial-update-while-using-constructor-instantiation-with-mapstruc) StackOverflow question

**Comment by jacekgajek** [comment]
Yeah sorry. I realized that this is not a good place to ask so I've created a question on StackOverflow although I forgot to delete the post here. Doing it now.
