### ISSUE TITLE
Generated code for Custom Mapper with Static method doesn't have import

### ISSUE THREAD

**Issue by Gautham** [mapstruct/mapstruct#730]
Example :
```
package a.x;
@Mapper(componentModel = "spring", uses = MyCustomMapper.class)
class MyMapper {

}
```
```
package a.y;
class MyMapper {
    public static String convert(MyClass X) {
    }
}
```

The generated java file does not contain an import for MyCustomMapper. So, if the class is not in the same package, compilation fails.

Converting to non-static method causes the import to be included.

(Sidenote : This is an awesome library and extremely useful). Thanks

**Comment by agudian** [comment]
Good catch, thanks for the report! We'll take care of it in time for the next release... :-)

**Comment by gunnarmorling** [comment]
Hey @Gautham, I tried to reproduce the issue, but it works as intended for me. I've pushed a test to my fork: https://github.com/mapstruct/mapstruct/commit/a2ec001ce6337f3da9382766d155e3a35c48e393.

Could you take a look at that one and check how it possibly is different from your set-up?

What version of MapStruct have you been using?

**Comment by Gautham** [comment]
The test you wrote matches my scenario correctly. I was using Beta 4, I think. I guess this was resolved in a newer issue. Sorry for the trouble then lol
