### ISSUE TITLE
ZonedDateTime to XMLGregorianCalendar

### ISSUE THREAD

**Issue by JanuszProgramowania** [mapstruct/mapstruct#746]
When I try to map a property type ZonedDateTime to property with type XMLGregorianCalendar in generated mapper implementation occurs compilation error.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project myProject: Compilation failure
[ERROR] /C:/Development/Projects/myProject/target/generated-sources/com/atg/ws/dto/CustomerOrderHeaderMapperImpl.java:[308,51] cannot find symbol
[ERROR] symbol:   variable TimeZone
[ERROR] location: class com.atg.ws.dto.CustomerOrderHeaderMapperImpl`

This is caused by missing import in generated file.
`import java.util.TimeZone;`

This TimeZone class is used is the following generated function:
```
    private Calendar zonedDateTimeToCalendar(ZonedDateTime dateTime) {
        if ( dateTime == null ) {
            return null;
        }
        Calendar instance = Calendar.getInstance( TimeZone.getTimeZone( dateTime.getZone() ) );
        instance.setTimeInMillis( dateTime.toInstant().toEpochMilli() );
        return instance;
    }
```

This looks like a bug to me

**Comment by agudian** [comment]
Yupp, it's a bug. Thanks for reporting! 

I'll create a fix in a pull-request right away...

**Comment by agudian** [comment]
pull-request merged.
