### ISSUE TITLE
Convert reference documentation to AsciiDoc

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#754]
Hey @sjaakd and @agudian, I spent some time and started to convert the reference documentation into the AsciiDoc format. This gives us many advantages:

* Simpler mark-up, no more mixture of HAML and Markdown
* Proper, automated numbering :)
* Scrollable menu, nothing cut off anymore on smaller screens
* Can be rendered to HTML and PDF
* We can include the reference guide to the distribution bundle

Please find the very first rough result attached. That's the PDF (GitHub doesn't allow to attach the HTML, which looks a bit nicer :/):

[index.pdf](https://github.com/mapstruct/mapstruct/files/129086/index.pdf)

I still need to do several changes, such as fixing references but you already get a good impression. The gitbook stuff looks nice to, but for now I prefer to have the docs in the project itself so we can include it into the dist as mentioned above.

Note that I just aim for the conversion with this as a first step. Subsequently we also should re-structure the guide to make it more logical, but I'll leave that as separate step.

Let me know what you think.

**Comment by agudian** [comment]
Very nice! :+1:
I'll try to find some time tonight to look into it in more detail.

**Comment by sjaakd** [comment]
Indeed. Very clear I was able to read it in the supermarket on my mobile while pushing the cart and doing shopping :smile: I'll look into it a bit further later this weekend. 

Ps I did see the url/references were not converted.

**Comment by sjaakd** [comment]
> Ps I did see the url/references were not converted.

I meant the local references, like: `[Implicit type conversions](#section-datatype-conversion-01))`

**Comment by gunnarmorling** [comment]
I've pushed my work-in-progress to https://github.com/gunnarmorling/mapstruct/tree/754, so if you like you can also build it yourself (mvn clean install -pl documentation) and take a look at the HTML under target/generated-docs.

Have fun shopping for now, @sjaakd :-)

**Comment by gunnarmorling** [comment]
Done :)
