### ISSUE TITLE
Decorator class generator can not handle void/update methods

### ISSUE THREAD

**Issue by gbrehmer** [mapstruct/mapstruct#765]
In the decorator not overridden void methods are producing compile errors in the generated decorator part. Default wrapper code generated return statement:

`public void updateMethod(Dto dto, Entity entity) {
  return delegate.updateMethod(dto, entity);
}`

Workaround is to override those methods in the decorator and to simply call the delegate.

**Comment by sjaakd** [comment]
Ai.. This is an issue.

**Comment by gunnarmorling** [comment]
Done.
