### ISSUE TITLE
Qualified String Mapper sometimes used for general String mapping

### ISSUE THREAD

**Issue by gbrehmer** [mapstruct/mapstruct#770]
I did not have a testcase to reproduce this error yet.

Sometimes a String-To-String mapping method with special Qualifier will be selected for all String-to-String mapping cases, where Qualifier is not set.

A clean project eclipse build fixes the problems. In addition these problems never occur during command line build process (or builds on jenkins).

My Environment: MacOS, Java 1.8.0_31, JHipster 2.27.0 (mapstruct 1.0.0), STS 3.5.2 / eclipse 4.5.1, gradle, Gradle eclipse Plugin & self configured APT settings on project level.

**Comment by agudian** [comment]
Does your qualifier annotation have retention=CLASS defined? If not, it would explain what you observe.

**Comment by gbrehmer** [comment]
I'm using retention=Source like in the official documentation.

```@Qualifier
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.SOURCE)
public @interface Password {

}

**Comment by gunnarmorling** [comment]
Ok, could you use CLASS then and let us know whether this resolves the
issue for you?

Depending on the state of (partial) compilations in Eclipse, SOURCE-level
annotations cannot be read. We should update the docs to recommend CLASS by
default.

**Comment by gunnarmorling** [comment]
Going to close this, as Andreas has fixed the examples/docs to use retention `CLASS`. Feel free to re-open if the issue remains also if you are using `CLASS`, too.

**Comment by gbrehmer** [comment]
Yes, thanks, changing retention to `CLASS` works as expected

**Comment by gunnarmorling** [comment]
Cool, glad to hear and thanks for reporting back!
