### ISSUE TITLE
Allow @Mapping(source=) to be the source of the current method.

### ISSUE THREAD

**Issue by kevinmic** [mapstruct/mapstruct#773]
Given objects that look like this 

``` java
public class Song {
   String songTitle;
   Artist artist;
}

public class Artist {
    String artistName;
}

public class SongFlattened {
    String songTitle;
    String artistName;
}
```

I would like to be able to easily map back and forth between them.  I can easily map from the nested object to the flattened by doing this

``` java
@Mapping(source="artist.artistName", target="artistName")
public SongFlattened toFlat(SongNested nested);
```

Doing the reverse mapping is much more painful, one way would be to do this using an abstract class and manually wiring everything ...

``` java
public abstract Song toSong(SongFlattened flat);

public abstract Artist toArtist(SongFlattened flat);

public Song toNested(SongFlattened flat) {
   Song song = toSong(flat);
   if (song != null) {
      songNested.setArtist(toArtist(flat));
   }

}
```

Or another way using expressions

``` java
@Mapping(target="artist", expression("java(toArtist(flat))")
public abstract Song toSong(SongFlattened flat);
public abstract Artist toArtist(SongFlattened flat);
```

This way is cleaner than the abstract class but it could be much cleaner.

I would like an easier way to say that the source of the given mapping is the same as the source passed into the current method.

``` java
@Mapping(reuseSource=true, target="artist")
public abstract Song toSong(SongFlattened flat);
public abstract Artist toArtist(SongFlattened flat);
```

**Comment by agudian** [comment]
I came accross the same problem in a real-life application as well and it would be cool if we'd allow that. I'm not so sure about how that might look, though. Your proposal is one way of doing it, but we should gather some more ideas.
One alternative could be that we just select the `toArtist` method implicitly and pass the source object, as it fits the required signature (given that `SongFlattened` does not have a property named `artist`).

**Comment by maposchmi** [comment]
Might it a proper Solution to split it to 2 mappers:

```
@Mapper
interface ArtistMapper
{
  Artist toArtist(SongFlattened flat);
}
```

```
@Mapper(uses=ArtistMapper.class)
interface SongMapper
{
  @Mapping(source="artist.artistName", target="artistName")
  SongFlattened toFlat(SongNested nested);

  Song toSong(SongFlattened flat);
}
```

**Comment by sjaakd** [comment]
@maposchmi , have you looked at #389 ?

**Comment by kevinmic** [comment]
@maposchmi, currently nesting the mappers doesnt solve the problem.  As a solution I don't think it makes sense to force a developer to do it that way to achieve the desired result.  Mapstruct should be able to do it whether specified in one or multiple mappers.

**Comment by kevinmic** [comment]
Honestly I was simply cleaning up my old issues.  I have been using @InheritInverseConfiguration and it seems to be meeting most of my needs.

**Comment by pdemanget** [comment]
I have this sort of need and I don't use@InheritInverseConfiguration, I just wonder if the root reference is possible, if there's a workaround. I will just use and AfterMapping and a second mapping for that, but I find it overkill.
