### ISSUE TITLE
Add support for java.util.Optional's (and com.google.common.base.Optional) in return values on mapping methods. 

### ISSUE THREAD

**Issue by ugrave** [mapstruct/mapstruct#774]
For example the a mapper definition like the following code:
`Optional<DataDto> map(Data source);`

Mapstruct should generate a mapper like this:
```
public Optional<DataDto> map(Data source) {
	if (source == null) {
		return Optional.empty();
	}

	DataDto target = new DataDto();

	return Optional.of(target);
}
```

**Comment by gunnarmorling** [comment]
Good idea; Propably it'd make sense to support it in inline conversions, too.

**Comment by agudian** [comment]
Not only a good idea, it's an *awesome* idea... I bet some smartass has written that down already... #674... :grin: 
Still, thanks Ulrich! Better twice than not at all. Would you be interested in helping with the implementation?

(closing this as duplicate)
