### ISSUE TITLE
Set initial capacity for new collection element in collection mapping

### ISSUE THREAD

**Issue by ugrave** [mapstruct/mapstruct#777]
In collection mappings the new created target collection shout be initialize with a capacity of the source collection. For collections with many elements a lot of re-sizing is done.

Example
Mapper:
`List<DataDto> map(List<Data> source);`
Generated Mapper:

```
List<DataDto> list = new ArrayList<DataDto>( source.size() /* + growCapacity */ );
 for ( Data data : source ) {
   list.add( map( data ) );
}
```

Maybe its also a good point to have an optionn to make the result list larger then the source list(see growCapacity attribute)
This could be made configurable (for example with the IterableMapping annotation).

**Comment by agudian** [comment]
I'm not sure if that growCapacity thing is something we should add as an option, but properly initializing the with the expected size for certain implementations (`ArrayList`, `HashSet`, `HashMap`) would surely make sense.
For the growCapacity, I could imagine that we allow factory methods to have the source size being passed as argument, so users could implement what they need there.

You already know what's coming next: if you find the time, we'd gladly apply a patch of yours... :+1:

**Comment by gunnarmorling** [comment]
+1 for specifying the right size (though it's not super-easy for sets/maps). Regarding a parameter for grow capacity, I side with @agudian: It seems a bit too specific.

Any help for using the correct size is very welcome!

**Comment by filiphr** [comment]
The initial capacity constructor is used where needed. I will close this issue. I think that the part about the `growCapacity` can go in a new issue. 

Just to clarify for `Map`(s) and `Set`(s) we use: `Math.max((int) (c.size()/.75f) + 1, 16)`, something similar to what Guava does and what the Java Collections use when creating a new `HashMap` / `HashSet` from a collection
