### ISSUE TITLE
Mapping only parent class properties if I target parent property in @Mapping annotation 

### ISSUE THREAD

**Issue by almothafar** [mapstruct/mapstruct#791]
I have issue with mapping Class have parent and I used one of attributes of parent in `target` and `source`: 

```
@Mapper
public interface UserMapper {
    public static UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    @Mappings({
            @Mapping(source = "id", target = "id"),
    })
    User map(UserDTO userDTO);
    UserDTO map(User user);
}
```

Classes: 

BaseModel: 
@MappedSuperclass
public abstract class BaseModel extends Model {

    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Integer id;

    @Column
    @CreatedTimestamp
    public Timestamp createdDate;

    @Column
    @UpdatedTimestamp
    public Timestamp updatedDate;

    @Column
    @Version
    private long version = 0;

    @Column
    public boolean isActive = true;

    public BaseModel() {
    }
}

User:
```
@Entity
@EntityConcurrencyMode(ConcurrencyMode.NONE)
@Table(name = "USERS")
public class User extends BaseModel {

    @Column(name = "full_name", nullable = false)
    public String fullName;

    @Column(nullable = false)
    public String email;

    public User() {
    }
}
```

BaseDTO:

```
public abstract class BaseDTO {

    public String id;
    public boolean isActive=true;

}

```
UserDTO: 
```
public class UserDTO extends BaseDTO {

    public String fullName;
    public String email;

}
```

So simply the generated UserMapperImpl will be like this : 
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2016-03-23T15:25:54+0200",
    comments = "version: 1.1.0.Beta1, compiler: javac, environment: Java 1.8.0_66 (Oracle Corporation)"
)
public class UserMapperImpl implements UserMapper {

    @Override
    public User map(UserDTO userDTO) {
        if ( userDTO == null ) {
            return null;
        }

        User user = new User();

        if ( userDTO.getId() != null ) {
            user.setId( Integer.parseInt( userDTO.getId() ) );
        }
        user.setIsActive( userDTO.getIsActive() );

        return user;
    }

    @Override
    public UserDTO map(User user) {
        if ( user == null ) {
            return null;
        }

        UserDTO userDTO = new UserDTO();

        if ( user.getId() != null ) {
            userDTO.setId( String.valueOf( user.getId() ) );
        }
        userDTO.setIsActive( user.getIsActive() );

        return userDTO;
    }
}
```

And its skip the attributes of Child class that I map.

I'm using Playframework 2.5 and added the following code to build.sbt:

```
libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  filters,
  "mysql" % "mysql-connector-java" % "5.1.38",
  "de.svenkubiak" % "jBCrypt" % "0.4",
  "org.mapstruct" % "mapstruct-jdk8" % "1.1.0.Beta1",
  "org.mapstruct" % "mapstruct-processor" % "1.1.0.Beta1",
  "commons-io" % "commons-io" % "2.4"
)
```

I think its an issue with **incorrect** error:

```
[error] D:\Sources\HiddenApp\app\mappers\UserMapper.java:20: No property named "fullName" exists in source parameter(s).
[error]             @Mapping(source = "fullName", target = "fullName"),
[error] (compile:compileIncremental) javac returned nonzero exit code
```

But both property is exists, to workaround this, I change it to one of parent property like `id`, wait processor to make new Imp file, then return to `fullName`.

**Comment by almothafar** [comment]
I think the issue was that I was not use setter and getter, play framework standards that to use without setter and getter and the framework itself generate them, otherwise will not touch the class and will not generate those.

I just added the setters and getters and this issue gone.

Not sure, keep this as an issue for simple classes without setters and getter or its not issue at all?

**Comment by agudian** [comment]
The same explanation as in #790 applies here... :)

Closing it as duplicate as well. Thanks anyways!
