### ISSUE TITLE
Why nesting is not supported on target attribute mapping

### ISSUE THREAD

**Issue by mkrishna4u** [mapstruct/mapstruct#792]
I was trying to use mapstruct in many of the software applications but always stuck with the limitation of target nesting. It is a very good framework, i think it can beat any other framework like dozer etc.. So we should support target attribute nesting as soon as possible. 

The design that i am thinking is:
> 1. It can only be applicable when there is a single source and single target object. Also annotate this method as @BidirectionalNestingEnabled. So during the code generation we can check that mapping method should contain only one argument for @BidirectionalNestingEnabled method and generate the code accordingly.
2. @InheritInverseConfiguration method should also be annotated with @BidirectionalNestingEnabled to make sure user has provided the right configuration for direct and inverse mapping.

Probably this might help. if you need more information and help, please get back to me.

**Comment by sjaakd** [comment]
Hi @mkrishna4u, I've been working on and off on this issue. I'll continue soon on this one. There's an issue for this already: #389. So I'll mark this one as duplicate and close it.

**Comment by gunnarmorling** [comment]
Hey @mkrishna4u, thanks for this report; As Sjaak is saying, there is an issue for it already, so let's continue the discussion over there. In one of the comments, I've described some challenges around target-side nesting, any input from you on these is highly appreciated. Thanks!
