### ISSUE TITLE
EnumNaming

### ISSUE THREAD

**Issue by maposchmi** [mapstruct/mapstruct#796]
We had to map a lot of Beans to Jaxb-Objects, both containing enums.
Jaxb converts an underscore to 3 underscores:
Enum.class:
FOO_BAR
JaxbEnum.class
FOO___BAR

We didnt want to map all that enum-constants manually.

**Comment by maposchmi** [comment]
So we introduced an EnumNamingStrategy similar to AccessorNamingStrategy to EnumMappingMethod.
Its not perfect, but it works für us.

[mapstruct-1.0.1-modified.zip](https://github.com/mapstruct/mapstruct/files/206232/mapstruct-1.0.1-modified.zip)

**Comment by sjaakd** [comment]
@maposchmi: you are aware that `Mapping` of enums (EnumMappingMethod) is deprecated? Its replaced by `@ValueMapping`..

**Comment by maposchmi** [comment]
We used 1.0.0.Final and i guess that there it is not deprecated.
On the quick i didnt find docu about @ValueMapping

**Comment by DanielDressler** [comment]
So is a solution for this being considered? While newer, ValueMappingMethod still simply matches by exact names and needs to be configured with exact source/target pairs.

Support for JaxB-generated enums could be built-in. I'd probably prefer a "dumber" approach of just ignoring a few typical delimiters and maybe even case when matching enum constants by name. (Which project has a lot of enums containing both A_BC and aB_C?)

More generally, an SPI like the suggested one would help. It could be improved by providing a normalization of names for both the source and target values. The exact name match would then happen on these normalized sets of names. The custom normalization could just strip delimiters, or a prefix, or whatever a project needs.

Even more generally, if #798 results in a very generic name-mapping SPI, that might also work for enum-values.

**Comment by filiphr** [comment]
Recently we added new `EnumNamingStrategy` and `EnumTransformationStrategy` that would enable the use case in the issue.

There are is no out of the box support for replacing 3 underscores with one. However, it is possible to register a custom `EnumTransformationStrategy` that would be able to do that.
