### ISSUE TITLE
Use classloader of given mapper type in Mappers#getMappers()

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#801]
We should use these classloaders in the given order:

* The CL of the given class object (in 99% of cases that's the right one)
* As a fallback, the TCCL
* As a fallback, MapStruct's own CL

**Comment by jvz** [comment]
Using the CL of the provided class would certainly make more sense than the TCCL. I just came across this bug in an OSGi environment where my mapper is in one bundle (and ClassLoader) but used by another bundle (via Camel's type converters). This causes a sort of ClassLoader race condition based on which bundle causes the initialization of the mapper.

**Comment by gunnarmorling** [comment]
Fixed in master. Thanks for your feedback, @jvz!

**Comment by jvz** [comment]
FWIW, what I ended up doing as a workaround for 1.0.0 was this:

```java
public class MapperFactory {

	private static final String IMPLEMENTATION_SUFFIX = "Impl";

	/**
	 * Returns an instance of the given mapper type.
	 *
	 * @param clazz The type of the mapper to return.
	 * @param <T>   The type of the mapper to create.
	 * @return An instance of the given mapper type.
	 */
	public static <T> T getMapper(final Class<T> clazz) {
		try {
			return clazz.getClassLoader().loadClass(clazz.getName() + IMPLEMENTATION_SUFFIX).asSubclass(clazz).newInstance();
		} catch (final ClassNotFoundException | InstantiationException | IllegalAccessException e) {
			throw new RuntimeException(e);
		}
	}

	private MapperFactory() {
	}
}
```
