### ISSUE TITLE
Google AutoValue support

### ISSUE THREAD

**Issue by natros** [mapstruct/mapstruct#802]
AutoValue is used to create immutable objects using an annotation processor. It would be nice if mapstruct would support this mapping.

[AutoValue](https://github.com/google/auto/blob/master/value/userguide/index.md)
[AutoValue with Builders](https://github.com/google/auto/blob/master/value/userguide/builders.md)

**Comment by gunnarmorling** [comment]
Hey, any thoughts on how this support should look like? Is it "just" support for builders? Or anything else? I like the idea (there is an issue for builder-style support somewhere already), but the details are still a bit vague to me.

**Comment by natros** [comment]
With jackson I can do this:

```java
@AutoValue
@JsonDeserialize(builder = AutoValue_User.Builder.class)
public abstract class User {
    @JsonProperty
    public abstract Integer userId();

    @JsonProperty
    public abstract String login();

    @JsonProperty
    public abstract String name();

    public static Builder builder() {
        return new AutoValue_User.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        @JsonProperty
        public abstract Builder userId(Integer userId);

        @JsonProperty
        public abstract Builder login(String login);

        @JsonProperty
        public abstract Builder name(String name);

        public abstract User build();
    }
}

        User user1 = User.builder().userId(1).login("fsousa").name("Filipe Sousa").build();
        System.out.println("user1 = " + user1);

        ObjectMapper objectMapper = new ObjectMapper();
        String s = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(user1);
        System.out.println("s = " + s);

        User user2 = objectMapper.readValue(s, User.class);
        System.out.println("user2 = " + user2);
```

In this example jackson is able to serialize and deserialize based on the builder. 
Maybe something like this should be possible to use.

```java
@Mapper
public interface UserMapper {
    @MapstructBuilder(builder = AutoValue_User.Builder.class)
    UserDto toUserDto(User user);
}
```

**Comment by gunnarmorling** [comment]
The [Immutables](https://immutables.github.io/) project would be another interesting case in the same category as AutoValue it seems.

**Comment by natros** [comment]
And there is also https://github.com/google/FreeBuilder from google.

**Comment by smartytime** [comment]
I submitted a PR that would support this use case, as well as lombok @Builder

https://github.com/mapstruct/mapstruct/pull/1229

**Comment by rmannibucau** [comment]
+1 to support it, @AutoValue generation is particular enough to not make it easy to bridge with a custom strategy (in particular the final fields handling)

**Comment by maciekpapiez** [comment]
:+1:

**Comment by ugrave** [comment]
Support for the Builders generated by [Lombok](https://projectlombok.org/features/Builder) would also be nice.

**Comment by filiphr** [comment]
With #1373 support for builders has been added to master. We are going to release 1.3.0 Beta so you can give it a shot soon.
