### ISSUE TITLE
Date -> XMLGregorianCalendar generated mapper is not customizable

### ISSUE THREAD

**Issue by jlzi** [mapstruct/mapstruct#804]
Consider I want to map Date field to XMLGregorianCalendar one. MapStruct generates such mapper for me.
The problem is that the generated mapper always includes not only year, month and day of month to the result, but also time and timezone. You can see it if you run the main method of the attached [sample project](https://github.com/mapstruct/mapstruct/files/222604/mapstruct-date-calendar-mapping.zip):
```
From generated date mapper: 1990-11-20T00:00:00.000+02:00
From custom date mapper: 1990-11-20
```
For now looks like the only possibility to have the result which contains only year, month and day of month is to write custom date mapper and do not forget to add it to `uses` everywhere.

Maybe it is worth to make the Date -> XMLGregorianCalendar mapping configurable as well?

**Comment by agudian** [comment]
Let's close this as won't-fix. My take would be that doing it with a hand-written method is the way to go in such cases, as it's usually more expressive and better maintainable than a specific and possibly more convulated configuration via annotations.
Is that alright with you, @jlzi?
