### ISSUE TITLE
Javadoc of ValueMapping is garbled in the released source-jars.

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#805]
It contains stuff like:
```
 * Mapping result:
 * â•”â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•¦â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•—
 * â•‘ OrderType           â•‘ ExternalOrderType          â•‘
```

I guess it's an encoding issue in either the files or in the configuration of the source-plugin. The generated and published javadocs are fine, but Eclipse shows me the docs based on the content of the source-jars. So we need to fix that before the next release.

**Comment by sjaakd** [comment]
Eclipse is a tool of the devil.. :smile:. Use Netbeans
