### ISSUE TITLE
@Mapping in boolean property like isXXX

### ISSUE THREAD

**Issue by riyvitxgt** [mapstruct/mapstruct#806]
if the property is boolean, and It's name like isSaled, the target should be saled, not isSaled, like bellow
@Mapping(target = "saled",expression  = "java(null !=entity.getIsSale()  && 1== entity.getIsSale())")
because the setter for isSaled is  setSaled, not setIsSaled, is there any way to fixed this problem?

**Comment by gunnarmorling** [comment]
Hi, I would have expected that it already behaves as you describe. Could
you provide the exact definitions of the source and target properties,
please?

**Comment by agudian** [comment]
I don't fully get what your actual and expected results are, but MapStruct only checks the getXyz/setXyz/isXyz methods and derives the property name 'xyz' from that (following the Java Bean spec, taking the special handling of boolean and Boolean into account). We don't look how the underlying class attribute is called.

Perhaps you can provide an example of how your methods in the target class look like?

**Comment by riyvitxgt** [comment]
```
public class Goods {
  private Double price;
  private Integer isSaled;
  getter/setter;
}
public class GoodsModel {
  private Double price;
  private boolean isSaled;
  getter/setter;
}
@Mapper(componentModel = "spring", uses = {})
public interface GoodsMapper {
  GoodsModel entityToModel(Goods entity);

  Goods modelToEntity(GoodsModel model);

  void updateEntityFromModel(GoodsModel model, @MappingTarget Goods entity);
}
```
I want to when the goods.isSaled == 1 ,the goodsModel.isSaled = true;
the code will not mapper goods.isSaled to goodsModel.isSaled;
so I add Mapping in GoodsMapper
```
@Mapper(componentModel = "spring", uses = {})
public interface GoodsMapper {
  @Mappings({
    @Mapping(target = "isSaled",expression  = "java(null !=entity.getIsSaled()  && 1== entity.getIsSaled())")
  })
  GoodsModel entityToModel(Goods entity);

  Goods modelToEntity(GoodsModel model);

  void updateEntityFromModel(GoodsModel model, @MappingTarget Goods entity);
}
```
there will be an error: Unknown property "isSaled" in return type.
if the @Mapping like this ,It can be work
`@Mapping(target = "saled",expression  = "java(null !=entity.getIsSaled()  && 1== entity.getIsSaled())")`
Why the target is saled but not isSaled?
Sorry, english is poor, It's may be hard to understand ^-^

**Comment by agudian** [comment]
Could you also add to the example how your getter/setter for isSealed in GoodsModel look like?

**Comment by riyvitxgt** [comment]
`public class Goods {
  private Double price;
  private Integer isSaled;

  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public Integer getIsSaled() {
    return isSaled;
  }

  public void setIsSaled(Integer isSaled) {
    this.isSaled = isSaled;
  }
}

public class GoodsModel {
  private Double price;
  private boolean isSaled;

  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public boolean isSaled() {
    return isSaled;
  }

  public void setSaled(boolean saled) {
    isSaled = saled;
  }
}
`

**Comment by agudian** [comment]
Alright, your accessor methods in `GoodsModel` are called `isSaled` and `setSaled`. As per Java Bean Specification, the name of the *property* is "saled".
That's totally independent of how the methods are implemented - if they store it in an attribute or in a `HashMap` or write it to a file :wink:.
Hope that helps.
I'm closing this issue as not-a-bug, as there is nothing that we would change here.
