### ISSUE TITLE
Mapping composition

### ISSUE THREAD

**Issue by ebelanger** [mapstruct/mapstruct#807]
It would be great if MapStruct could support mapping composition by defining a new annotation.  It could work similar to how [Hibernate Validator](http://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html/ch06.html#section-constraint-composition) constraint composition does.  This would allow reuse of mapping configurations by duck-typing instead of inheritance, which is useful when you do not have total control over the entities.

**Comment by gunnarmorling** [comment]
Hey Eric, could you provide an example of how such mapping composition
would look like and how it would be used? I'm aware of Bean Validation
constraint composition, but I'd like to know how you envision such
composition to apply to MapStruct.

**Comment by ebelanger** [comment]
`
@Mapping(target = "id", ignore = true)
@Mapping(target = "deleted", ignore = true)
@Mapping(target = "account", ignore = true)
@Mapping(target = "options", ignore = true)
@Mapping(target = "promotions", ignore = true)
public abstract Plan update(PlanView view, @MappingTarget Plan plan);

@Mapping(target = "id", ignore = true)
@Mapping(target = "deleted", ignore = true)
@Mapping(target = "account", ignore = true)
@Mapping(target = "pricings", ignore = true)
@Mapping(target = "promotions", ignore = true)
public abstract Option update(OptionView optionView, @MappingTarget Option option);
`

In this scenario, Plan and Option do not share an interface explicitly but we can clearly see one is defined implicitely.  What I would like to do in this case is:

`
@Mapping(target = "id", ignore = true)
@Mapping(target = "deleted", ignore = true)
@Mapping(target = "account", ignore = true)
@Target(METHOD)
@Retention(RUNTIME)
@Documented
public @interface EntityMapping { }

@EntityMapping
@Mapping(target = "options", ignore = true)
@Mapping(target = "promotions", ignore = true)
public abstract Plan update(PlanView view, @MappingTarget Plan plan);

@EntityMapping
@Mapping(target = "pricings", ignore = true)
@Mapping(target = "promotions", ignore = true)
public abstract Option update(OptionView optionView, @MappingTarget Option option);
`

And that would pretty much be it.  It is pretty much the same as defining mappings for a base class, but for when you do not have one.

**Comment by sjaakd** [comment]
👍 . I like the idea. Should also not be too difficult to realize.

**Comment by ebelanger** [comment]
Great.  I will prepare a PR soon then :)

**Comment by agudian** [comment]
I think we should first check how that is in line with our other config facilities, such as MappingConfig and the config-inheritance settings.
Adding just another dimension might just be an easy thing now, but could convolute our way of supplying mapping configs.
I could imagine that we can extend the current options and for example extend how and which mapping configs from MappingConfig types are applied automatically or explicitly. Perhaps we can add an InheritConfiguration option to inherit configs from a different type (e.g. tell MapStruct to treat Option and Plan similarly)... Or something else.

What do you think, could we discuss some different ways before starting with an implementation?

**Comment by ebelanger** [comment]
I do not mind discussing other possible concepts, but what I do like about my proposed solution is that it doesn't modify the cores of MapStruct.  It is simple annotation inheritance to remove duplication in cases where beans share property names but no common interface.  In my case, it is because we are mapping with generated classes derived from some JSON data structure.

I am not sure how expending the MappingConfig would support this though.  MappingConfig seems to work based on inheritance. which is not possible in some cases like I mentionned.

Modifying InheritConfiguration could work in some cases, but would probably require tweaking when some properties are present in the inherited configuration but not in the target.

The closest thing I can think of if I would write this by hand and did not want to duplicate code is to create an common interface and implement some decorators that would delegate to the actual properties.  Then I could map the common properties by decorating the bean, applying the mappings and continue with the undecorated bean.  But in my opinion, the added complexity would not worth it.

**Comment by spoerri** [comment]
Is the alternative to fix `@InheritConfiguration(name =` so that it works no matter the source and target types?

To be as fully general, InheritConfiguration would also have to support java @Repeatable...

> some properties are present in the inherited configuration but not in the target.

Imho this is an orthogonal consideration, and current mapstruct style would be to require organizing either the composition annotations or the prototype methods in such a way that configured properties are always mapped.

**Comment by sjaakd** [comment]
Implemented by #1979
