### ISSUE TITLE
Customized Factories

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#81]
Hi,

I'm working with JAXB a lot. I'd like to add some kind of (customizable) external factory mechanism to MapStruct. Possibly in the similar way as now is done for the mappers themselves. 

MapStruct could then generate a FactoryImpl 'underneath' the Factory interface. The user could tweak what kind of Factory (e.g. JAXB) is generated. Also the user could customize the behavior by making his own implementation.

In JAXB I'm facing the problem of many namespaces (coming form OGC), so many factories which have XSD specifications created with the ' garden of eden' principle (in essence duplicating the amount of factory methods for JAXB Objects). This is further complicated by the fact that I need to compile with 'generateElementProperties' is set to true in order to create element wrappers (JAXBElement). In other words, constructing objects is more tricky than for normal (simple) JAXB generated objects. I would like the solution immediately to cover this tricky case as well. MapStruct would fill a nice gap that is (in my knowledge) not yet occupied by other frameworks.

Any first Ideas? 

I'll try to get more solid on this soon.

Best regards,
Sjaak

**Comment by jairyp90** [comment]
@Mapper(uses = {AdditionalMonetaryUtil.class,SignatureUtil.class,
		AccountingSupplierPartyUtil.class,AccountingCustomerPartyUtil.class,
		InvoiceLineUtil.class,LegalMonetaryTotalUtil.class})
public interface FacturaMapper {
	
	FacturaMapper INSTANCE = Mappers.getMapper(FacturaMapper.class);
	
	@Mappings({		
		@Mapping(target = "ublExtensions.ublExtension",source = "additionalMonetaryTotal", qualifiedBy = InvoiceAdditionalMonetaryTotal.class),
		@Mapping(target = "ublVersionID.value", source="head.UBLVersionID"),
		@Mapping(target = "customizationID.value", source="head.customizationID"),
		@Mapping(target = "id.value",source="head.id"),
		@Mapping(target = "issueDate.value" ,source="head.issueDate",dateFormat = "yyyy-MM-dd"),
		@Mapping(target = "invoiceTypeCode.value",source = "head.invoiceTypeCode"),
		@Mapping(target = "documentCurrencyCode.value",source = "head.documentCurrencyCode"),
		@Mapping(target = "signature", source = "signature", qualifiedBy = InvoiceSignature.class),
		@Mapping(target = "accountingSupplierParty", source = "accountingSupplierParty",qualifiedBy =InvoiceAccountingSupplierParty.class ),
		@Mapping(target = "accountingCustomerParty",source = "accountingCustomerParty",qualifiedBy =InvoiceAccountingCustomerParty.class),
		@Mapping(target = "legalMonetaryTotal",source="legalMonetaryTotal",qualifiedBy = InvoiceLegalMonetaryTotal.class),
		@Mapping(target = "invoiceLine",source = "lines",qualifiedBy = InvoiceInvoiceLine.class),
		@Mapping(target = "despatchDocumentReference" ,ignore = true ),
		@Mapping(target = "contractDocumentReference", ignore = true),
		@Mapping(target = "additionalDocumentReference", ignore = true),
		@Mapping(target = "paymentTerms",ignore = true),
		@Mapping(target = "prepaidPayment",ignore = true),
		@Mapping(target = "allowanceCharge",ignore = true),
		@Mapping(target = "taxTotal",ignore = true)

	})
	InvoiceType DocumentEBToInvoice(DocumentEB factura);
}


it is correct to use it to map a JAXB class?

**Comment by filiphr** [comment]
@jairyp90 I don't quite understand what you want to ask?

Yes you can use MapStruct to map JAXB classes

**Comment by gunnarmorling** [comment]
@jairyp90, please don't use issues resolved for a long time for usage
questions. It's better suited in the user forum:
https://groups.google.com/forum/#!forum/mapstruct-users
