### ISSUE TITLE
Ignore common field by field-based or config-base ignore config

### ISSUE THREAD

**Issue by wenerme** [mapstruct/mapstruct#814]
``` java
class BaseEntity {
@MapperIgnore
@Version
Long version;
@MapperIgnore
@CreateTime
Date createTime;
@MapperIgnore
@UpdateTime
Date updateTime;
}
class Person extends BaseEntity{
String  name;
Integer age;
}
class Cat extends BaseEntity {
Color color;
}


interface PersonMapper {
// With MapperIgnore do not have to repeat ignore version,createTime,updateTime
Person map(PersonDTO s);
// With MapperIgnore do not have to repeat ignore version,createTime,updateTime
Person merge(PersonDTO s,@MappingTarget Person e);
}
```

There is no `BaseDTO` that I can do

``` java
interface BaseMpper{
<T extends BaseEntity, D extends BaseDTO> T mapBase(D s); // Maybe just use Object is ok
}

interface PersonMapper {
@InheritConfiguration(name = "mapBase")
Person map(PersonDTO s);
}
```

Also a `BaseDTO` is a bad idea, because it looks like 

``` java
class BaseDTO{
// Nothing here
}
```

**Comment by wenerme** [comment]
We got almost 100 entity now, every mapper I have to do this, that's very inconvenience.

**Comment by wenerme** [comment]
Currently we define  these field in each entity not `BaseEntity` yet.

Common field like this
```
Date createTime;
Date updateTime;
// For soft delete
int deleted = 0;
User createBy;
User updateBy;
```

In real code

![image](https://cloud.githubusercontent.com/assets/1777211/16103257/66ea5ada-33a9-11e6-92c5-4acb371e887e.png)
![image](https://cloud.githubusercontent.com/assets/1777211/16103261/7b5b488a-33a9-11e6-85de-a2aa0dcae169.png)

**Comment by agudian** [comment]
To solve that kind of problem, we created the _prototype methods_ in shared mapper configurations: http://mapstruct.org/documentation/1.1/reference/html/index.html#shared-configurations

Check the example with mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG and use Object as parameter type in the prototype method. However, note that when this config is applied to entity-to-entity mapping methods, those fields will be ignored there as well. I suggest adding a base-dto type in your application, as this would make it a bit more explicit- your call.


Please let us know if that works for you.

**Comment by wenerme** [comment]
My currently work around is remove the setter of these field in BaseEntity, only have to handle one or two filed in mapper. 

```
@MappedSuperclass
@QueryExclude
@Where(clause = "is_del = 0")
@EntityListeners(AuditingEntityListener.class)
public class MajorEntity extends AbstractEntity<Long> {

    @CreatedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @LastModifiedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time")
    private Date updateTime;

    @Column(name = "is_del", nullable = false)
    private Integer deleted = 0;

    @Version
    @Column(name = "version")
    private Integer version = 0;

    public Date getCreateTime() {
        return createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public MajorEntity setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    public Integer getVersion() {
        return version;
    }
}
```

Now I only need to ignore deleted.

`AUTO_INHERIT_FROM_CONFIG ` is kind of wild, I don't want to this cause invisible problem.

**Comment by sjaakd** [comment]
@wenerme , @agudian : I think that something similar is proposed in: #807. Is this a duplicate?

**Comment by wenerme** [comment]
Yes, #807 can solve this problem too with different approach but better idea.

**Comment by filiphr** [comment]
Closing this since #807 has been added in 1.4. If we need to do something else for this one we can reopen it
