### ISSUE TITLE
Decorator and void-methods error: "Void methods cannot return a value"

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct#816]
I've got a problem when using a decorator and declaring a void method in my mapping interface, see the following example:
```java
	@Mapper
	@DecoratedWith(TestMapper.AbstractTestMapper.class)
	public interface TestMapper {
		public static class TestEntity {
		}
	
		public static class TestDto {
		}
	
		public TestDto map(TestEntity entity);
	
		public void map(TestEntity entity, @MappingTarget TestDto target);
	
		public static abstract class AbstractTestMapper implements TestMapper {
			@Autowired
			@Qualifier("delegate")
			private TestMapper delegate;
	
			// without this method the generated class has an error:
			// Void methods cannot return a value
			@Override
			public void map(TestEntity entity, TestDto target) {
				delegate.map(entity, target);
			}
		}
	}
```
Without the `map`-method inside my decorator the generated java file contains a compile error: "Void methods cannot return a value".

The generated code looks like this here:
```java
    @Override
	public void map(TestEntity entity, TestDto target) {
    	return delegate.map(entity, target);
    }
```

The workaround is to add appropriate void methods to the mapper, like I did in the example above.

Same problem exists when the mapping interface is an abstract class.

EDIT: Problem exists in 1.0.0.Final and 1.1.0.Beta1

Thanks in advance and best regards,
Christian

**Comment by agudian** [comment]
Just noticed that it's a duplicate to #765. So I'm closing this. 

Still, thanks for the report, @chris922! We'll make sure that we get this fixed soon.
