### ISSUE TITLE
Mapstruct at runtime?

### ISSUE THREAD

**Issue by shankyty** [mapstruct/mapstruct#817]
Is there a way to use mapstruct in runtime to generate mapper and load those in class-loader?
I have have requirement to generate mapper from config which is in database from which I am able to generate pojo but now I need to generate mapper from newly constructed pojo and existing pojo in class loader?

**Comment by agudian** [comment]
Although it is not something we would encourage you to do, there is always the possibility to invoke the Java compiler with MapStruct as annotation processor at runtime and then load the generated and compiled classes. Our tests do it that way. You can find some of the tidbits here:

https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/testutil/runner/JdkCompilingStatement.java

Closing the issue, as I don't see that we would have to implement something, as it's covered by Java standard API already :). Feel free to comment, though.
