### ISSUE TITLE
Feature request: null strategy for bean field.

### ISSUE THREAD

**Issue by wenerme** [mapstruct/mapstruct#822]
```java
class A{String a;}
interface AMapper{
A map(A a);
@BeanMapping(nullFieldStrategy=IGNORE)
A patch(A a);
}

class AMapperImpl{
public A patch(A a){
 if(a == null)return null;
A target = new A()
if(a.getA() != null){
target.setA(a.getA());
}
// If a.getA() is null should be ignore
}
}
```

This very useful to handler HTTP `PATCH` method for JPA.

Currently I have to do some dirty stuff

* Patch DTO to Entity
  * Convert Entity to DTO
  * Use [jodd-bean](http://jodd.org/doc/beanutil.html#beancopy) copy PATCH DTO to entity's DTO which support ignoreNull
  * merge the final DTO to Entity

This is fine if entity have no collection field, but if the entity have collection, this will clear all collection and add them again.Which will delete and insert a lot stuff.

**Comment by agudian** [comment]
Closing it as a duplicate to #649. The feature might actually be right around the corner... :)
