### ISSUE TITLE
Mappers cannot auto-generated within eclipse NEON

### ISSUE THREAD

**Issue by shane-chen** [mapstruct/mapstruct#828]
Hi all,

we are using mapstruct 1.0.0.Final in our project. After upgrading the eclipse IDE to NEON and importing eclipse projects, some mappers cannot be auto-generated. Following is the error and a screenshot in the IDE:

```
Multiple markers at this line
	- Internal error in the mapping processor: java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/compiler/apt/model/ElementImpl at 
	 org.mapstruct.ap.internal.util.workarounds.EclipseAsMemberOfWorkaround.asMemberOf(EclipseAsMemberOfWorkaround.java:60) at 
	 org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.asMemberOf(SpecificCompilerWorkarounds.java:137) at 
	 org.mapstruct.ap.internal.util.workarounds.TypesDecorator.asMemberOf(TypesDecorator.java:148) at 
	 org.mapstruct.ap.internal.model.common.TypeFactory.getMethodType(TypeFactory.java:261) at 
	 org.mapstruct.ap.internal.model.common.TypeFactory.getParameters(TypeFactory.java:277) at 
	 org.mapstruct.ap.internal.model.common.TypeFactory.getSingleParameter(TypeFactory.java:273) at org.mapstruct.ap.internal.model.PropertyMapping
	 $PropertyMappingBuilder.getTargetType(PropertyMapping.java:502) at org.mapstruct.ap.internal.model.PropertyMapping
	 $PropertyMappingBuilder.build(PropertyMapping.java:166) at org.mapstruct.ap.internal.model.BeanMappingMethod
	 $Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:433) at org.mapstruct.ap.internal.model.BeanMappingMethod
	 $Builder.build(BeanMappingMethod.java:128) at 
	 org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:361) at 
	 org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143) at 
	 org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114) at 
	 org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73) at 
	 org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:223) at 
	 org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:203) at 
	 org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:169) at 
	 org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139) at 
	 org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121) at 
	 org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159) at 
	 org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135) at 
	 org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:915) at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437) at 
	 org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417) at 
	 org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:368) at 
	 org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179) at 
	 org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305) at 
	 org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61) at 
	 org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256) at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175) at 
	 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
	 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:
	 246) at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
	 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
	 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:
	 383) at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:
	 235) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: java.lang.ClassNotFoundException: 
	 org.eclipse.jdt.internal.compiler.apt.model.ElementImpl at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at 
	 java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 42 more
	- Convert the abstract class "HaulageReferenceDefaultMapper" into an interface.
```

![image](https://cloud.githubusercontent.com/assets/10446357/16611016/3638503e-435f-11e6-9e59-bd69c9459c49.png)

I also tried the version 1.1.0-Beta1. Unfortunately, there are even more errors within eclipse NEON.

Is the issue to do with eclipse java compiler? 
Can someone advice me, how to fix the issue. Thanks.

Shengyao

**Comment by gunnarmorling** [comment]
Seems our work-arounds for addressing some bugs within the Eclipse APT implementation fail due to changes of some internal types as of Neon. I cannot think of any work-around really, apart from staying on the previous Eclipse version.

@agudian maybe you can take a look? Seems your field of expertise really :) Would be nice to have this in the upcoming Beta so people can use MapStruct with the latest Eclipse.

**Comment by agudian** [comment]
Yes, that smells like an issue with the Eclipse compiler. We'll look into it asap.

**Comment by increChong** [comment]
I have the same problem

**Comment by filiphr** [comment]
@increChong please make sure that you are using the latest version of MapStruct and if you are still experiencing issues, open a new issue. This one has been fixed for over an year in the `1.1.0.Beta2` release

**Comment by increChong** [comment]
@filiphr  my version of MapStruct is `1.2.0.CR1`,but I can't solve the`Internal error in the mapping processor: java.lang.NoClassDefFoundError......`

**Comment by increChong** [comment]
`Internal error in the mapping processor: java.lang.NoClassDefFoundError: java/time/LocalDate  	at org.mapstruct.ap.internal.model.source.builtin.XmlGregorianCalendarToLocalDate.<init>(XmlGregorianCalendarToLocalDate.java:43)  	at org.mapstruct.ap.internal.model.source.builtin.BuiltInMappingMethods.<init>(BuiltInMappingMethods.java:55)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.<init>(MappingResolverImpl.java:102)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:102)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:80)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)  	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)  	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:818)  	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:330)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:135)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)  	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)  	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)  	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)  	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)  	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)  	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)  	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)  `

**Comment by filiphr** [comment]
@increChong, can you please open a new issue with the full stacktrace that you are having and write all the details so we can reproduce the error that you are experiencing. This issue is closed for over a year.

**Comment by filiphr** [comment]
Looking at your stacktrace the your issue is not even related to this one...

**Comment by increChong** [comment]
@filiphr 
![tim 20171213144425](https://user-images.githubusercontent.com/25929286/33925738-3ccb0f36-e016-11e7-9bbd-a7e78104f00c.png)

**Comment by filiphr** [comment]
@increChong as I wrote earlier your issue is not related to this closed issue. Please open a new issue with your problems and best would be if you can create a project that can have your issue reproduce. Otherwise, we can't really help you out.
