### ISSUE TITLE
MapStruct needs a Logo...

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#83]
I propose we collect some ideas and then choose one of them here.

Btw, Maven currently looks for a fresh new logo, and someone there posted the idea to pitch in some money and use http://www.48hourslogo.com/ - which I think might be a real alternative if we don't come up with anything fancy on our own... :)

**Comment by sjaakd** [comment]
Just for idea forming..

![mapstruct](https://cloud.githubusercontent.com/assets/6173283/5988007/68548546-a94c-11e4-8b69-626e094a6cd9.png)

**Comment by gunnarmorling** [comment]
Hi @sjaakd, many thanks! I like the idea with the lines, that's symbolizes nicely what MapStruct is about. I'd try to put the text right to the logo. What program/format did you use, maybe I could play a bit with it as well if you pass me the source.

**Comment by sjaakd** [comment]
Shure! That was the idea. I used Inkscape. I'll share the source later (when I'm home). It svg so you can edit in other tools as well. 
 
Personally I don't like the color yet. 

Verstuurd vanaf mijn iPhone

**Comment by sjaakd** [comment]
> Hi @sjaakd, many thanks! I like the idea with the lines, that's symbolizes nicely what MapStruct is about.

:smile: Nice to hear. I played with the idea already for quite some time.. but didn't have the time to make a start on it..

**Comment by sjaakd** [comment]
![mapstructlogo2](https://cloud.githubusercontent.com/assets/6173283/5989932/bf58eeb6-a999-11e4-9590-3f26e75437e5.png)

**Comment by sjaakd** [comment]
A bit more balanced, centered and soberder.

**Comment by sjaakd** [comment]
![mapstructlogo3](https://cloud.githubusercontent.com/assets/6173283/5989956/e6428cd4-a99a-11e4-9c9b-adb990bea68e.png)

**Comment by sjaakd** [comment]
Ok. after some color advice (from my wife :smile: ). .

**Comment by sjaakd** [comment]
Gents: WDYT?

**Comment by agudian** [comment]
Sjaak, I think it's a good concept... :+1: 

I think it needs some more finishing touch - the font, the color of the text, spacing of the lines - stuff like that. (at my company, we have some Powerpoint macros - and one of them creates a "Sticker" which is basically the short text with slim bars above and below - just like this one here - so I'm perhaps a bit biased towards not liking that particular detail because of that :wink:)

**Comment by sjaakd** [comment]
@agudian. Please feel free to adapt. Perhaps we could store the source somewhere on GitHub. Any ideas (I've got one later version in SVG format)..

**Comment by agudian** [comment]
The new logo went online already, so we can close this one :+1:
