### ISSUE TITLE
Add SPI explanation / example somewhere

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#832]
Speaks for itself

**Comment by gunnarmorling** [comment]
@sjaakd did you ever end up writing up something around the SPI?

**Comment by sjaakd** [comment]
Nope.. its on my TODO list.. Will take a look later.. Shouldn't be that big issue.

**Comment by gunnarmorling** [comment]
Ok, cool, thanks, Sjaak!
