### ISSUE TITLE
'Unknown property' error raised for ignored targets with no setter

### ISSUE THREAD

**Issue by bpiper** [mapstruct/mapstruct#833]
If I have a Mapping that specifies a target property as ignored, and there is no setter for that property in the target class, I am getting an `Unknown property "myPropertyName" in return type` error raised.  This is not what I would expect if I have indicated that the property is to be ignored.

In `BeanMappingMethod.handleDefinedSourceMappings`, it is attempting to resolve the `targetWriteAccessor` for a mapping even though the mapping might be ignored.  The `targetWriteAccessor` is not actually used at all if the `mapping.isIgnored()` condition further down evaluates to true, hence there doesn't seem to be a legitimate reason for resolving the target accessor on an ignored mapping.

The workaround for this is of course to define a setter for the ignored property (but have it throw an exception, because I don't want anything actually calling it).  This isn't ideal though, as it could invite other things to use the setter instead of modifying the field via reflection.

**Comment by agudian** [comment]
I'd say what you describe is not a problem but it is how it's supposed to work.
Read-only properties shouldn't need to be explicitly ignored anyway. If you get a warning for an unmapped property but that property is read-only, then my feeling is that there lies the bug instead. Do you get such a warning if you don't mention that property in the annotations?

**Comment by bpiper** [comment]
Yes, you're quite right... I hadn't realised that target properties with no mutator would be implicitly ignored.  I'd lumped a couple of read-only properties in with a couple of writeable properties that I also wanted to ignore and assumed that Mapstruct would complain if I didn't... but turns out it doesn't.  

Arguably it would still be worth printing a more useful warning or error if someone adds an ignore mapping for a read-only property (e.g. "Target mapping for 'myProperty' with ignore = true is unnecessary as the property is read-only"), rather than implying that they need to add a mutator for that property... but I'm otherwise happy to close this.

**Comment by sjaakd** [comment]
> Arguably it would still be worth printing a more useful warning or error if someone adds an ignore mapping for a read-only property

Good suggestion. Although, I reckon its a more broader case in which you specify a `@Mapping` that has no write accessor but does have a read accessor.

**Comment by agudian** [comment]
Sjaak added a better message for this case, closing it. 
@bpiper thanks for the report!
