### ISSUE TITLE
MapStruct clash with Sonar code quality warning

### ISSUE THREAD

**Issue by mirabilos** [mapstruct/mapstruct#835]
@Mapper
    public interface CarMapper {
    
        CarMapper INSTANCE = Mappers.getMapper( CarMapper.class );

This yields a Sonar warning “Move constants to a class or enum.” with the rationale “Constants should not be defined in interfaces” (squid:S1214).

What is the “correct” way to work around this? Also, can this please be documented in, say, http://mapstruct.org/documentation/1.0/reference/html/index.html#mappers-factory example 10?

Thanks in advance!

**Comment by mirabilos** [comment]
FWIW, just adding `//NOSONAR` to the INSTANCE line isn’t enough, unfortunately

**Comment by sjaakd** [comment]
@mirabilos , nothing forbids you from taking an abstract class as base for an `@Mapper`. Also, you can place the ` CarMapper INSTANCE = Mappers.getMapper( CarMapper.class );` in a class as public static final.

Sonar is there to help you to stick to good practices and conventions. However, it does not proclaim to have the ultimate truth :smile:.

**Comment by mirabilos** [comment]
Thanks, this indeed helped. It was a bit tricky to figure it out, but here’s what I did in the end:

    -public interface CommentMapper {
    +public abstract class CommentMapper {

… and…

    -    CommentMapper INSTANCE = Mappers.getMapper(CommentMapper.class); //NOSONAR
    +    public static final CommentMapper INSTANCE = Mappers.getMapper(CommentMapper.class);

… and put `public abstract ` in front of all methods:

-    Comment map(CommentDto dto);
+    public abstract Comment map(CommentDto dto);

It seems to work so far, and Sonar most certainly stopped complaining, too.

**Comment by sjaakd** [comment]
Nice to hear. Thanks for your feedback .

**Comment by AntonioJoaoAzevedo** [comment]
For completeness this also keeps sonar happy and is better than changing it to an abstract class:

```
@Mapper
public interface CarMapper {  //NOSONAR

    CarMapper INSTANCE = Mappers.getMapper( CarMapper.class );

```

**Comment by mirabilos** [comment]
AntonioJoaoAzevedo dixit:

>For completeness this also keeps sonar happy and is better

No because that disables *all* Sonar warnings for that line.

**Comment by AntonioJoaoAzevedo** [comment]
Correct but still preferable in my opinion to changing the code to make sonar happy.

The reader can choose but in my case with Java 8 the abstract class introduced squid:S1610 “Abstract classes without fields should be converted to interfaces” and to silent it I would have to add NOSONAR to that same line as my team accepts no open Sonar issues.

**Comment by tompaz3** [comment]
Actually, in Java 8+, I ended up adding private class with static method in the interface to keep both Sonar and MapStruct relatively happy.

```java
@Mapper
public interface CarMapper {
    static CarMapper getInstance() {
        return CarMapperInstance.CAR_MAPPER_INSTANCE;
    }
    
    Car map(CarDto dto);
    
    final class CarMapperInstance {
        private static final CarMapper CAR_MAPPER_INSTANCE = Mappers.getMapper(CarMapper.class);
        private CarMapperInstance() { }
    }
}
```

Isn't too pretty, but in my opinion, still better than an abstract class.

While AntonioJoaoAzeve's code is more concise, `//NOSONAR` is regarded as a "code smell" in our team (especially on class/interface/enum level).

**Comment by a3aanwisse** [comment]
Why not suppress the specific sonar warning using:

`@SuppressWarnings("squid:S1214")`

This only suppresses the specific warning

**Comment by polarlights** [comment]
We can also config the **sonar.exclusions** property of  [sonar-project.properties](https://docs.sonarqube.org/latest/analysis/analysis-parameters/).
There is no any complex and buggy code in our mapper file, then we may just exclude it.

**Comment by mirabilos** [comment]
@polarlights there’s some code in them as soon as you add methods, which you’d want checked.

**Comment by polarlights** [comment]
@mirabilos mapstruct helps us mapping between class. In our team, we just add mapping annotation when necessary; and we seldom define any custom methods in it.  So we don't have the concern.

Maybe in some scenarios we have to add some methods, I think we could extract these method into another class and call another method instead.

I don't like to add annotation of `@SuppressWarnings` in every mapper by hand personally.  We don't need to add any intrusion code about sonar, just adding a configuration may cover almost 80+% our scenarios.:smiley:

**Comment by pragmaticway** [comment]
I like `public abstract class` approach. Much cleaner when it comes to Sonar Qube

**Comment by yatindraTechment** [comment]
> Thanks, this indeed helped. It was a bit tricky to figure it out, but here’s what I did in the end:
> 
> ```
> -public interface CommentMapper {
> +public abstract class CommentMapper {
> ```
> 
> … and…
> 
> ```
> -    CommentMapper INSTANCE = Mappers.getMapper(CommentMapper.class); //NOSONAR
> +    public static final CommentMapper INSTANCE = Mappers.getMapper(CommentMapper.class);
> ```
> 
> … and put `public abstract` in front of all methods:
> 
> ```
> -    Comment map(CommentDto dto);
> +    public abstract Comment map(CommentDto dto);
> ```
> 
> It seems to work so far, and Sonar most certainly stopped complaining, too.

thanks for update

**Comment by filiphr** [comment]
The funny thing is that according to [SONARJAVA-3477](https://jira.sonarsource.com/browse/SONARJAVA-3477) and starting from Sonarqube 6.8 this error should not be reported by Sonar for interfaces with other members.
