### ISSUE TITLE
Overriding nested target properties

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#839]
Overriding nested target properties works. But produces duplicate code.

**Comment by gunnarmorling** [comment]
@sjaakd is this still an issue? Could you ellobrate a bit on what you mean by "duplicate code"?

**Comment by sjaakd** [comment]
@sjaakd is this still an issue? Could you ellobrate a bit on what you mean by "duplicate code"?

Ouch. I most likely made an issue during my work which I was meant to detail further in the evening.. Which I forgot. I have no idea.. Will proceed to close.
