### ISSUE TITLE
How to map from Enum to value and vice versa?

### ISSUE THREAD

**Issue by vitaliy-zinchenko** [mapstruct/mapstruct#840]
**I have Entity:**
```
public class Bean {
    private TestEnum testEnum;

    public TestEnum getTestEnum() {
        return testEnum;
    }

    public Bean setTestEnum(TestEnum testEnum) {
        this.testEnum = testEnum;
        return this;
    }
}

```
**And Dto:**
```
public class BeanDto {
    private String value;

    public String getValue() {
        return value;
    }

    public BeanDto setValue(String value) {
        this.value = value;
        return this;
    }
}

```
**And Enum:**
```
public enum TestEnum {
    TEST("t");

    private final String value;

    TestEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

}
```

**So, I have object like this:**
```
Bean bean = new Bean();
bean.setTestEnum(TestEnum.TEST);
```

I want Mapper to convert this Entity to Dto and I want the field BeanDto.value to be populated with "t".
Is it possible to do it? If yes, how can I do this?

I don't want to use this approach https://iamhug.gitbooks.io/mapstruct/content/7mapping_enum_types.html because in this case I need to write a lot of code.

**Comment by agudian** [comment]
The way to go is implementing manual mapping methods and make them available in the mapper (as `protected` methods in an abstract mapper class, in a seperate class referenced in `@Mapper( uses = .. )` or as Java 8 default methods in the interface):
```
protected String testEnumToString(TestEnum e) {
    return e.getValue();
}
protected TestEnum toTestEnum(String value) {
    for (TestEnum e : TestEnum.values()) {
        if ( e.getValue().equals( value ) ) {
            return e;
        }
    }
    throw new IllegalArgumentException(...); // or whatever you want
}
```

I'm gonna close this issue, as it's more a question.
