### ISSUE TITLE
Missing import in generated mapping class

### ISSUE THREAD

**Issue by darrenreimer** [mapstruct/mapstruct#849]
I have an issue similar to #844, but in my case the import was being included correctly in the generated mapper class for MapStruct versions up until 1.0.0.Final and is broken in versions 1.1.0.Beta1 and 1.1.0.Beta2.  My actual mapping is quite complicated, but I was able to get this down to a simple scenario so it should be easy to reproduce.
Source class:
```
public class Source {
  private List<Serializable> sourceList;

  public List<Serializable> getSourceList() {
    return sourceList;
  }

  public void setSourceList(List<Serializable> sourceList) {
    this.sourceList = sourceList;
  }
}

```
Target class:

```
public class Target {
  private List<Serializable> targetList;

  public List<Serializable> getTargetList() {
    if (targetList == null) {
      targetList = new ArrayList<Serializable>();
    }
    return targetList;
  }

  // Setter method must be missing to reproduce issue.
//  public void setTargetList(List<Serializable> targetList) {
//    this.targetList = targetList;
//  }
}
```

Mapping class:
```
@Mapper
public abstract class TestMapper {

  @Mapping(source = "sourceList", target = "targetList")
  public abstract Target mapSourceToTarget(Source source);
  
  // Without this workaround method the import java.io.Serializable will be missing from the TestMapperImpl.
  //public abstract List<Serializable> missingSerializableImportWorkaround(List<Serializable> serializable);
}
```

With any 1.1.0 version I have tried the 'import java.io.Serializable' will be missing from the generated TestMapperImpl class, resulting in a compile time error.  This was not an issue for any 1.0.0 versions I have used.  In my case I cannot modify the actual target class so adding a setter method is not an option.  As mentioned in the code, as a workaround a dummy method can be added to the TestMapper which will cause the import to be included in TestMapperImpl.

**Comment by gunnarmorling** [comment]
Hi, thanks for the report. Would you be interested in providing a bugfix for this one? Thanks!

**Comment by darrenreimer** [comment]
Possibly.  Though this fix may benefit from someone who is aware of relevant code changes made between versions 1.0.0.Final and 1.1.0.Beta1.

**Comment by gunnarmorling** [comment]
It may have been me, but I don't remember details :) Generally, required imports are aggregated along the model object tree. So the starting point would be to find the element referring to that type the import is missing for, i.e. here the return type of the mapping method or the parameter type. Then the `Type` instance representing `Type<Serialiazable>` should return `Serializable`, too, via `getImports()`.

**Comment by sjaakd** [comment]
Should be fixed.

@agudian : thanks for reviewing.
@darrenreimer : can you test the latest 1.1.0.SNAPSHOT? I'll close the issue in the meantime

**Comment by darrenreimer** [comment]
Yes, I'll test it out and let you know.

**Comment by darrenreimer** [comment]
Verified this has been fixed in 1.1.0-SNAPSHOT.

**Comment by sjaakd** [comment]
Thanks!

**Comment by myatmin** [comment]
Is this issue being recurrent on 1.4.0 beta versions?
Tested with all 3 beta versions and only workaround could add the required import.

**Comment by sjaakd** [comment]
@myatmin the concept of beta's is to flush out problems.. I optimised the built-in methods, so it could be that I missed out on certain stuff. Could you provide a minimal reproducer and raise a new issue?

**Comment by filiphr** [comment]
@myatmin this is an old issue that has been fixed long time ago. If you are having issues please open a new issue with an example of what isn't working

**Comment by myatmin** [comment]
@sjaakd @filiphr I submitted the issue #2170 with example.
