### ISSUE TITLE
CheckStyle rules should discover missing whitespace in if-blocks, method invocations etc.

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#85]

**Comment by gunnarmorling** [comment]
@agudian Ah, that may be the issue you already have the fix for :)

**Comment by agudian** [comment]
Indeed! Thanks for digging this out! :+1:

**Comment by gunnarmorling** [comment]
Hey @agudian, do you still have that patch somewhere? Would be great to have it, e.g. one of the other PRs does some formatting differently.

**Comment by agudian** [comment]
Fixed with #701.

**Comment by gunnarmorling** [comment]
Ah yes; That other PR was branched off before the fix for #701. Thanks :)
