### ISSUE TITLE
Add built-in conversion from java.util.LocalDate to java.util.Date

### ISSUE THREAD

**Issue by pjlarson** [mapstruct/mapstruct#852]
There is no mapper for java.util.LocalDate to java.util.Date

Granted there are a lot of combinations of things you're attempting to cover.

Since I need this and stubbornly refuse to stop using mapstruct since I already have it in my POM, I will attempt to submit a pull request.

**Comment by sjaakd** [comment]
Ok.. Are you aware its always possible to define a hand-written method to do this for you?

**Comment by gunnarmorling** [comment]
> Since I need this and stubbornly refuse to stop using mapstruct since

That's some stubbornness I like :) A PR is surely welcome, the existing
built-in conversions around dates should provide some guidance. Thanks a
lot!

**Comment by pjlarson** [comment]
@sjaakd I am aware and have done just that. But it feels a bit strange that all the combinations similar to mine are covered in the built-ins, but this particular one is not. Potentially I will have mapstruct in many many projects, and it would be great if I could have java.time.LocalDate<->java.util.Date built in rather than have to manage my own library and manual mappings.

**Comment by sjaakd** [comment]
In that case, by all means: please provide a PR. Thanks!

**Comment by gunnarmorling** [comment]
+1 Looking forward to this contribution :)

**Comment by gunnarmorling** [comment]
@pjlarson Any update on this? Would be nice to have it for the 1.1 CR which we've planned soon-ish.

**Comment by pjlarson** [comment]
Hi Gunnar. Unfortunately when I put in the fix it broke a test related to a
gregoriancalendarxml test. I left for vacation so not looking at it. Can
you mark it for the following release and I'll do a pull request when I get
back. I will need help understanding what broke.

**Comment by sjaakd** [comment]
Hi Peter, do you want one of us to take a look and fix it? It's up for CR1 next week.

**Comment by pjlarson** [comment]
It's on my home PC and I don't have access to it while on vacation. If only
I had pushed to my fork before I left...

I have someone at home who's not a software person. I'll see if I can talk
them through git over the phone. Stay tuned...

**Comment by pjlarson** [comment]
Hi guys, so sorry for the delay. I created a pull request. There is a test failing for an unrelated conversion. I could not figure it out on my own.

**Comment by gunnarmorling** [comment]
Going to look into the test failure right now.

**Comment by gunnarmorling** [comment]
@sjaakd So this change is triggering a different path in the 2-step conversion resolution. Source is of type `XMLGregorianCalendar`, target is of `LocalDate`.

Before the conversion was

     XMLGregorianCalendar -> String -> LocalDate

Whereas now it's 

     XMLGregorianCalendar -> Date -> LocalDate

Simplest would be to add an explicit conversion for `XMLGregorianCalendar` to `LocalDate`. WDYT? Your idea of disable two-step conversions for specific cases is growing on me I think.

**Comment by sjaakd** [comment]
> Your idea of disable two-step conversions for specific cases is growing on me I think.

Nice to hear.. :smile:. The idea is to order 2 step conversions by their middle type. So if you've to three types available:
1. String
2. Date
3. SomeOther type.

The order of preference should be 3. first, then 2. then 1. Then you still keep the current stuff working. Or more generic "something special", "something from java.util", " something from java.lang" possibly emitting a warning on the latter two.

**Comment by gunnarmorling** [comment]
PR is merged.

**Comment by sjaakd** [comment]
> Simplest would be to add an explicit conversion for XMLGregorianCalendar to LocalDate. WDYT? Your idea of disable two-step conversions for specific cases is growing on me I think.

This is of course always preferable.
