### ISSUE TITLE
Support non-generic specializations of Iterables and Maps

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#853]
Properly support types like `StringList extends ArrayList<String>` or `LongToDateMap implements Map<Long, Date>`. Currently using such types for properties results in exceptions during the mapper generation.

(#845 fixes this).

**Comment by gunnarmorling** [comment]
@agudian Would you agree if we moved this to 1.1.1 or 1.2? I agree it should be supported but it seems like quite some corner case so I wouldn't mind deferring it (esp. since it hasn't been reported by a user).

**Comment by agudian** [comment]
Merged 👍
