### ISSUE TITLE
Use assertj instead of fest

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#860]
While working on my last pull request I noticed that fest asserts are used for testing the framework. 

Would you be interested in replacing the fest asserts with [assertj](https://github.com/joel-costigliola/assertj)? Assertj is actually a fork of fest and is actively developed as opposed to fest. There  is also a [migration guide](http://joel-costigliola.github.io/assertj/assertj-core-migrating-from-fest.html) about migration from fest assert.

**Comment by gunnarmorling** [comment]
So far I didn't perceive any shortcoming due to the lack of development in FEST Assert.

Agreed though that using an actively maintained lib would be nice. Would you like to give it a go? That'd be great, I cannot judge though how much work it'd be (we are still on FEST 1.4).

Thanks for the idea and any help!

**Comment by filiphr** [comment]
I will try to do the migration assertj. I had a quick look and it seems that there aren't a lot of special usages of FEST Assert so it shouldn't be too complicated.

@gunnarmorling I have one question, which version should I use:
* AssertJ 1.x requires Java 6 or higher
* AssertJ 2.x requires Java 7 or higher (use the org.assertj.core.api.Java6Assertions entry point on Android)
* AssertJ 3.x requires Java 8 or higher (use the org.assertj.core.api.Java6Assertions entry point on Android)

2.x and 3.x have the same features (3.x having java 8 specifics).

I am asking because, I've seen java 8 in the tests, but in the pom I think the maven-compiler is configured for java 6.

**Comment by filiphr** [comment]
@gunnarmorling It was much easier than I thought so I provided a pull request for the switch. If you are interested you can review it.

**Comment by gunnarmorling** [comment]
Awesome, thanks a lot! Regarding the version, we use Java 8 for building but work with source level 1.6 for source and target (apart from the mapstruct-jdk8 module). Not sure where this leaves us exactly in terms of the AssertJ version, but it seems your PR works successfully using AssertJ 3.x?

**Comment by filiphr** [comment]
Yes the PR is working with AssertJ 3.x. If you are OK I'll leave this version, as in any case there are java 8 classes in the tests

**Comment by agudian** [comment]
Your PR is merged. Thanks a lot, @filiphr!

**Comment by filiphr** [comment]
Great. We can close the issue now.
