### ISSUE TITLE
Track progress of https://bugs.eclipse.org/bugs/show_bug.cgi?id=481555

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#861]

**Comment by filiphr** [comment]
@gunnarmorling the eclipse bug seems to be resolved. Do we need to do something on our side?

**Comment by gunnarmorling** [comment]
The bug supposedly is fixed in Eclipse 4.7, which was released last week. So while we should be able to remove the workaround in `SpecificCompilerWorkarounds.asMemberOf()` eventually with that, we should wait a bit more until 4.7 is more widely in use. Moving this one to 1.3, so to verify and remove the workaround eventually.

**Comment by eximius313** [comment]
Its status is ```VERIFIED FIXED```

**Comment by sjaakd** [comment]
Resolved. Also included a more definite version of compiler-work-arounds (with a delegator). Removed all the resolved issues.
