### ISSUE TITLE
Specifying componentModel="default" in mapper has no effect if defaultComponentModel is configured

### ISSUE THREAD

**Issue by pavelbely** [mapstruct/mapstruct#880]
My assumption is that configuring defaultComponentModel literally overrides default component model.

So if I configure defaultComponentModel:
```xml
<options>
  <mapstruct.defaultComponentModel>spring</mapstruct.defaultComponentModel>
</options>
```

And then when I try to specify default as a component model for my mapper:
```java
@Mapper(componentModel = "default", uses=SomeOtherMapper.class)
public interface MyMapper {
```
it has no effect and the mapper is created as Spring bean and **SomeOtherMapper** is autowired in it instead of get using `Mappers.get(SomeOtherMapper.class)`.

I'm getting this in MapStruct 1.0.0.Final and 1.1.0.Beta2.

**Comment by agudian** [comment]
Um, right. I wonder if we did that on purpose.

**Comment by agudian** [comment]
I'm labelling it at as a bug, as it doesn't really make sense... :smirk:

**Comment by agudian** [comment]
Found another spot: `MapperConfig#unmappedTargetPolicy` is ignored if there was a value specified as processor option.

**Comment by gunnarmorling** [comment]
These processor options became quite obsolete when we added config inheritance via `@MapperConfig`. I wished we had removed these options then. I think we should deprecate them now. WDYT?

**Comment by agudian** [comment]
We had that discussion before, I think :). I'm still in favor of keeping them, as it removes a possible pitfall for large projects with many devs. And I guess I had some other equally weak arguments back then.
I think it doesn't hurt having the options and if it is usefull for some users, why not.

**Comment by agudian** [comment]
Fix merged to master. Thanks @sjaakd for the reviews!
