### ISSUE TITLE
NullPointerException in implicit type conversions

### ISSUE THREAD

**Issue by stoerr** [mapstruct/mapstruct#891]
When upgrading from MapStruct 1.1.0.Beta2 to 1.1.0.CR1 we suddenly got some NullPointerExceptions when MapStruct tries to convert an Integer to a Long. If you try to map the following, you get code that will throw an NPE in the .longValue() call when nested.getPropInt is null. This might be related to issue #843 . The correct way would probably be to save the result of srcNestedPropInt( src ) in a local variable and check it for being null, or to introduce a method that does such conversions in a nullsafe way.

    @Mapper
    public interface BuggyMapper {

        class Src {
            public SrcNested getNested() {
                return new SrcNested();
            }
        }

        class SrcNested {
            public Integer getPropInt() {
                return null;
            }
        }

        class Dest {
            public void setPropLong(Long l) {
            }
        }

        @Mapping(source = "nested.propInt", target = "propLong")
        Dest convert(Src src);
    }

generates the following buggy code:

    public class BuggyMapperImpl implements BuggyMapper {

        @Override
        public Dest convert(Src src) {
            if (src == null) {
                return null;
            }

            Dest dest = new Dest();

            dest.setPropLong(srcNestedPropInt(src).longValue());

            return dest;
        }

        private Integer srcNestedPropInt(Src src) {

            if (src == null) {
                return null;
            }
            SrcNested nested = src.getNested();
            if (nested == null) {
                return null;
            }
            Integer propInt = nested.getPropInt();
            if (propInt == null) {
                return null;
            }
            return propInt;
        }
    }

**Comment by sjaakd** [comment]
Merged & solved.. @stoerr thanks for reporting.
