### ISSUE TITLE
String.valueOf called for int to int mapping

### ISSUE THREAD

**Issue by piercena** [mapstruct/mapstruct#892]
We have a source and target bean. Both has a parameter of type int on them. In the mapper impl that is generated using "mvn clean compile" the generated code is target.setType(String.valueOf(int)); even though both the source and target has an int type. In the target bean though there are two methods that set the same parameter on the target, one that takes in an int and one that takes in a string. The 1.0.0Final documentation says that String.valueOf(int) is only called implicitly when the source is of type int and the target is of type String. We believe this is a bug. Our current work around was to rename the method that took in the type String parameter and this fixed the issue.

**Comment by sjaakd** [comment]
@piercena could you provide a reproducer?

**Comment by piercena** [comment]
Since this was added for the 1.1.0.Final milestone does that mean this was found or do you still need the reproducer? I apologize for not providing that and completely forgetting to look back at this since I posted the issue.

**Comment by gunnarmorling** [comment]
Yes, please do provide a reproducer. That will help very much. Thanks!

**Comment by gunnarmorling** [comment]
Done.
