### ISSUE TITLE
Fix integration-test execution with jigsawed JDK 9 in toolchain

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#900]
With the Jigsaw-enabled JDK 9 builds, we need to add `-addmods java.annotations.common` to the compiler args, as otherwise some of the annotations we add to the classes won't be available (e.g. `@Generated`).
We might also consider detecting if the annotation is available in the classpath and leave it out / comment it out in the generated classes to make it easier for our users.

**Comment by sjaakd** [comment]
oops. wrong reference.. sorry

**Comment by gunnarmorling** [comment]
Done.
