### ISSUE TITLE
Generate an interface from a bean for compile time safety

### ISSUE THREAD

**Issue by agentgt** [mapstruct/mapstruct#902]
This might be outside of the scope of the library but is there a way for MapStruct to generate a filling contract for a bean?

That is I want to something like the following:

http://stackoverflow.com/questions/39600413/annotation-processor-to-create-interfaces-for-bean-construction

Basically I want to be able to do something like:

```java
@MaybeSomeAnnotationToTriggerCodeGen
public MyBean {
    private String id; //getter and setter omitted
    private String name; //getter and setter omitted
}

//generated
public interface MyBeanFillContract {
    public String getId();
    public String getName();
}

//generated static method somewhere
public static void fill(MyBean b, MyBeanFillContract c) {
    b.setId(c.getId());
    b.setName(c.getName());
}
```

It feels like MapStruct is the closest I have seen. If it is missing from the library and you think it is in scope I could probably implement this and submit a pull request?

**Comment by gunnarmorling** [comment]
Hi, there is no such functionality like this in MapStruct right now. It's not really in the scope of this tool, but have you looked into [Immutables](https://immutables.github.io/) or Google's AutoValue? They may be more what you are after.

**Comment by agentgt** [comment]
Yes I have sort of thought about that but it would require an interface first approach (ie interface->POJO).

We would have to convert our code base to having loads of abstract classes or interfaces (depending on the library).

**Comment by gunnarmorling** [comment]
I'm going to close this as "Won't fix" as it's not something which I think we'll add in the foreseeable future. Nevertheless thanks for getting in touch and bringing up the idea.
