### ISSUE TITLE
mapping does not work when parameter name is 'values' 

### ISSUE THREAD

**Issue by zivry** [mapstruct/mapstruct#909]
A really non descriptive error is thrown, and I looked for the reason of problem for hours. 
apparently the name of the parameter cannot be 'values', I sill fail to understand why. 
The exception: 

/workarea/zivry/workspace/NBODataService/service/src/main/java/com/intel/swiss/microservices/nbodataservice/controllers/JobDtoMapper.java:24: error: Internal error in the mapping processor: java.lang.RuntimeException: org.mapstruct.ap.shaded.freemarker.template.TemplateModelException: Getting the number of items or enumerating the items is not supported on this method+sequence (wrapper: f.e.bded.freemarker.ext.beans.SimpleMethodModel) value.  (Hint 1: Maybe you wanted to call this method first and then do something with its return value. Hint 2: Getting items by intex possibly works, hence it's a "+sequence".)    ----  FTL stack trace ("~" means nesting-related):         - Failed at: #list propertyMappingsByParameter[sou...  [in template "org/mapstruct/ap/internal/model/BeanMappingMethod.ftl" at line 64, column 9]  ----         at org.mapstruct.ap.internal.writer.ModelWriter.writeModel(ModelWriter.java:93)         at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:70)      at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:52)     at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:42)       at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:37)       at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:223)         at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:203)        at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:169)         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)         at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)   at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)         at com.sun.tools.javac.main.Main.compile(Main.java:523)         at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)         at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)       at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)       at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)       at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)       at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)     at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)     at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)          at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)       at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)       at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)       at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)     at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)   at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)      at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)   at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)          at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)      at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)        at org.gradle.internal.Factories$1.create(Factories.java:22)    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)      at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)       at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)   at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)       at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)          at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)          at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)          at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)          at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)          at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)   at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)          at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)     at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)     at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)      at org.gradle.launcher.Main.doAction(Main.java:33)      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)     at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)   at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)         at org.gradle.launcher.GradleMain.main(GradleMain.java:23)  Caused by: org.mapstruct.ap.shaded.freemarker.template.TemplateModelException: Getting the number of items or enumerating the items is not supported on this method+sequence (wrapper: f.e.bded.freemarker.ext.beans.SimpleMethodModel) value.  (Hint 1: Maybe you wanted to call this method first and then do something with its return value. Hint 2: Getting items by intex possibly works, hence it's a "+sequence".)    ----  FTL stack trace ("~" means nesting-related):    - Failed at: #list propertyMappingsByParameter[sou...  [in template "org/mapstruct/ap/internal/model/BeanMappingMethod.ftl" at line 64, column 9]  ----         at org.mapstruct.ap.shaded.freemarker.ext.beans.SimpleMethodModel.size(SimpleMethodModel.java:93)       at org.mapstruct.ap.shaded.freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:152)        at org.mapstruct.ap.shaded.freemarker.core.Environment.visitIteratorBlock(Environment.java:501)         at org.mapstruct.ap.shaded.freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)          at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.MixedContent.accept(MixedContent.java:57)    at org.mapstruct.ap.shaded.freemarker.core.Environment.visitByHiddingParent(Environment.java:278)       at org.mapstruct.ap.shaded.freemarker.core.IfBlock.accept(IfBlock.java:48)      at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.MixedContent.accept(MixedContent.java:57)    at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.Environment.process(Environment.java:235)    at org.mapstruct.ap.shaded.freemarker.template.Template.process(Template.java:262)      at org.mapstruct.ap.internal.writer.FreeMarkerModelElementWriter.write(FreeMarkerModelElementWriter.java:48)    at org.mapstruct.ap.internal.model.common.ModelElement.write(ModelElement.java:38)      at org.mapstruct.ap.internal.writer.ModelIncludeDirective.execute(ModelIncludeDirective.java:61)        at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:333)      at org.mapstruct.ap.shaded.freemarker.core.UnifiedCall.accept(UnifiedCall.java:100)     at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.MixedContent.accept(MixedContent.java:57)    at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:145)        at org.mapstruct.ap.shaded.freemarker.core.Environment.visitIteratorBlock(Environment.java:501)         at org.mapstruct.ap.shaded.freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)          at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.MixedContent.accept(MixedContent.java:57)    at org.mapstruct.ap.shaded.freemarker.core.Environment.visit(Environment.java:257)      at org.mapstruct.ap.shaded.freemarker.core.Environment.process(Environment.java:235)    at org.mapstruct.ap.shaded.freemarker.template.Template.process(Template.java:262)      at org.mapstruct.ap.internal.writer.FreeMarkerModelElementWriter.write(FreeMarkerModelElementWriter.java:48)    at org.mapstruct.ap.internal.model.common.ModelElement.write(ModelElement.java:38)      at org.mapstruct.ap.internal.writer.ModelWriter.writeModel(ModelWriter.java:84)         ... 99 more  
public interface JobDtoMapper { //NOSONAR
       ^
warning: Unclosed files for the types '[com.intel.swiss.microservices.nbodataservice.controllers.JobDtoMapperImpl]'; these types will not undergo annotation processing

**Comment by agudian** [comment]
Well, that looks strange indeed. What version of MapStruct do you use? What compiler?

I just tried a simple mapper of beans that contain a `values` property, but it worked as expected. Could you share a simplified example?

**Comment by agudian** [comment]
Ahh... If the source argument is called `values`, I get the same error:

```
   SomeTarget toTarget(SomeSource values);
```

**Comment by agudian** [comment]
That's a bug in freemarker - strange thing. I'll prepare a PR with a workround...

**Comment by zivry** [comment]
Thanks! I am using 1.0.0.Final by the way.

**Comment by agudian** [comment]
If you have the chance, could you build the PR above and check if it solves the problem for you? Just to make sure I didn't miss anything.

**Comment by zivry** [comment]
Sorry, for some reason build fails for me. I don't understand if it is a local environment problem

**Comment by gunnarmorling** [comment]
@zivry What kind of build error do you get?

**Comment by gunnarmorling** [comment]
Merged the fix.
