### ISSUE TITLE
Make conversion look-ups more flexible

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#91]
Implicit conversions are currently looked up only using exact matches of source and target type. Thus the following method can not be generated atm., also if there was a generic `ObjectToStringConversion`:

```
Set<String> numberSetToStringSet(Set<? extends Number> numbers);
```

Here, the conversion look-up should take an `ObjectToStringConversion` into account.

**Comment by sjaakd** [comment]
Let me see.. Don't know if I understand you correctly. In our current code:

```java
@Mapper
public interface MyMapper {

    MyMapper INSTANCE = Mappers.getMapper( MyMapper.class );

    Target convert(Source source);

    public default String toString(Object o) {
        return o != null ? o.toString() : null;
    }


    class Source{
        public List<Number> s;
    }

    class Target{
        public List<String> s;
    }
}

```

generates

```java

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-10-10T19:18:43+0200",
    comments = "version: , compiler: javac, environment: Java 1.8.0_181 (Oracle Corporation)"
)
public class MyMapperImpl implements MyMapper {

    @Override
    public Target convert(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        target.s = numberListToStringList( source.s );

        return target;
    }

    protected List<String> numberListToStringList(List<Number> list) {
        if ( list == null ) {
            return null;
        }

        List<String> list1 = new ArrayList<String>( list.size() );
        for ( Number number : list ) {
            list1.add( toString( number ) );
        }

        return list1;
    }
}

```

Not sure whether we want the conversion from object to string as one of the default conversions.  We noticed (especially in 2 step mapping methods) strange behaviours. We'll probably get a lot of unintended mappings. Better leave it to the user to define such method explicitly such as in the example above

**Comment by gunnarmorling** [comment]
Ok, let's close it then. I could see how someone might want to have the generic method be invoked, but as you say, it's not too much effort to add the right method matching the specific types.
