### ISSUE TITLE
broken link on documentation page

### ISSUE THREAD

**Issue by zora-borys** [mapstruct/mapstruct#925]
please update or delete broken link on documentation page
step to reproduce:

- go to this link: 
http://mapstruct.org/documentation/

- click link with text below:
Layered applications with Mapstruct; Using MapStruct for object mappings in multi-layered applications

link points to:
http://software-reengineered.com/layered-an-application-with-mapstruct/ - does not exists

**Comment by agudian** [comment]
Thanks for the info! I didn't find the article anymore, so I've removed the link.
