### ISSUE TITLE
Implementation class not found exception in eclipse

### ISSUE THREAD

**Issue by yhjhoo** [mapstruct/mapstruct#929]
I am getting 

"Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for"

in eclipse IDE, with version 1.0.0.Final and 1.1.0.CR1 . 

Refer to the sample code here https://github.com/yhjhoo/mapStructTest.git

Just found out, it's also not working in inteliji

**Comment by agudian** [comment]
Did you check the info-box below the example pom in the documentation at http://mapstruct.org/documentation/1.1/reference/html/index.html#setup ?
It describes the necessary stuff you need in Eclipse.

For IntelliJ, you need to setup the annotation processing manually. There's this issue open that could fix that and perhaps you'd like to vote for it: https://youtrack.jetbrains.com/issue/IDEA-150621

(I'm closing this issue as it's more a question regarding the IDE config. Feel free to comment nonetheless or reopen if you see an actual issue.)

**Comment by nghiaht** [comment]
Things are all right after reviewing [http://mapstruct.org/](url).
I noticed that the annotation `@Mapper` is missing above the interface.

Update the annotation, and perform a gradle clean task (IntelliJ IDEA), then run again, the exception no longer exists.
