### ISSUE TITLE
Wrong type for nested properties

### ISSUE THREAD

**Issue by oliversaggau** [mapstruct/mapstruct#931]
When I try to map a nested property from source (long) to the target (Long) and the source or the nested object is null, the target gets the value 0L instead of null. I think the type of generated method in the impl is wrong. Instead of using the type of the target (Long) which actually is nullable, MapStruct uses the type of the source property (long) for the generated method.

I attached a simple model and a unit-test which covers this issue:
[src.zip](https://github.com/mapstruct/mapstruct/files/535922/src.zip)

**Comment by sjaakd** [comment]
@oliversaggau thanks.. I'll have a look.

**Comment by sjaakd** [comment]
Hmm. seems you are right.. 

1. The generated method (forged method) is correct. It's intention is just to get the content of the nested property.

2. Type conversion (in this case boxing) is used to map this to the `id` with type `Long`. Which is in essence also correct.

In short.. I need to think about this a bit more. For instance you might imagine a check in the calling generated method on the presence of `nested`. However, how would you handle a `nested.nestedX.id` with `nestedX` being `null`? Would you map `null` on any of the intermediate nesting levels also to null?

**Comment by oliversaggau** [comment]
I think think the forged method is absolutly correct at the moment to return `0L` (so basically the default value) for any intermediate nesting level being `null`. I would definitly expect exactly that. But rather then mapping the default value of the source property I would expect the target having the default value of the target property.

So basically I would just change the forged method to have a result type that matches the target property instead of the source property. The type conversion (in this case boxing) would then just occur in the last return statement of the forged method (where the actual value is returned). Any intermediate nesting levels being `null` should still return the default value of the result type of the forged method. Just like it is at the moment, only with the result type being slightly different.

**Comment by gunnarmorling** [comment]
PR merged to master.

**Comment by sjaakd** [comment]
I was thinking of a generalized approach. If the target type extends Object and the source type is primitive, use the wrapped type as return type of the forged method instead of its corresponding primitive type. WDYT?

Verstuurd vanaf mijn iPhone
