### ISSUE TITLE
Mapper should be able to ignore one attribute from nested List 

### ISSUE THREAD

**Issue by zt1983811** [mapstruct/mapstruct#933]
Mapper should be able to ingore one attribute from nested List object, For example:

```
Class country{
     String id;

     String name;

     @JsonIgnoreProperties("country")
     List<City> cities;
}`

Class City{
     String id;

     String name;

     @JsonIgnoreProperties("cites")
     Country country;
}
```

In the mapper I should be able to ignore target cites.country and country.cites to avoid hibernate many to one infinite recursion. 

```
interface CountryMapper {

    @Mapping(target="cites.country", ignore=true)
    ContryDto toDto(Country country)
}

interface CityMapper {

    @Mapping(target="country.cities", ignore=true)
    CityDto toDto(City city)
}

```

I am currently get follow errors : 
java.lang.StackOverflowError\n\tat org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)\n\tat com.toms.api.mapper.DepartureCityMapperImpl.hibernateToDomain(DepartureCityMapperImpl.java:97)\n\tat com.toms.api.mapper.CountryMapperImpl.hibernateToDomain(CountryMapperImpl.java:58)\n\tat com.toms.api.mapper.DepartureCityMapperImpl.hibernateToDomain(DepartureCityMapperImpl.java:62)\n\tat com.toms.api.mapper.DepartureCityMapperImpl.hibernateToDomain(DepartureCityMapperImpl.java:99)\n\tat com.toms.api.mapper.CountryMapperImpl.hibernateToDomain(CountryMapperImpl.java:58)\n\tat com.toms.api.mapper.DepartureCityMapperImpl.hibernateToDomain(DepartureCityMapperImpl.java:62)\n\tat com.toms.api.mapper.DepartureCityMapperImpl.hibernateToDomain(DepartureCityMapperImpl.java:99)\n\tat com.toms.api.mapper.CountryMapperImpl.hibernateToDomain(CountryMapperImpl.jav

**Comment by filiphr** [comment]
@zt1983811 There is a way to do what you are looking for. You can achieve it with the `@Qualifier`. You can use `@Named` and `qualifiedByName`, or you can use your own custom `@CountryWithoutCities` qualifier with `qualifiedBy`

```java
interface CountryMapper {

    @Mapping( target = "cities", qualifiedByName = "noCountry")
    CountryDto toDto(Country country);

    @CountryWithoutCities
    @Mapping( target = "cities", ignore = true)
    CountryDto toDtoWithoutCities(Country country);
}

interface CityMapper {

    @Named( "noCountry" )
    @Mapping( target = "country", ignore = true)
    CityDto toDtoWithoutCountry(City city);

    @Mapping( target = "country", qualifiedBy= CountryWithoutCities.class)
    CityDto toDto(City city);
}
```

Yes you will need 2 more methods if you want to do the reverse. Is this solving your problem?

**Comment by sjaakd** [comment]
@zt1983811 : is there still an issue? If not, I'll proceed to close this one this week.

**Comment by zt1983811** [comment]
No it is get resloved
