### ISSUE TITLE
Classes declared with 'uses' not being autowired

### ISSUE THREAD

**Issue by brettanomyces** [mapstruct/mapstruct#938]
Classes declared with 'uses' will only be autowired if one of their methods is used as a source->target mapping, so if their only use is in an expression they will not get autowired

http://stackoverflow.com/q/38807415/1427295

**Comment by nowakprojects** [comment]
I have this siutation in many cases. When we should expect this enhancement to be implemented?

**Comment by filiphr** [comment]
Currently this is not high on our priorities. However, we would gladly accept a PR for this enhancement, if you are willing to contribute.

**Comment by chris922** [comment]
What do you think is the best way for this?

The easiest way would probably be to just include all mapper references by default in the generated mapper, but imho this is not the best option..  I guess there are reasons why it will be checked which mapper references will be used and only those will be included.

Checking the expressions if such a reference will be used would probably the best, but also most complex, way. As far as I got it the expressions are just inserted as raw values and they will not be evaluated.

**Comment by sjaakd** [comment]
This can be solved now, by means of `@Context` and a handwritten method.

```java
@Mapper(componentModel="spring")
public interface MyMapper { 

   @Mapping(target="x",ignore = true)
   // other mappings
   Target map( Source source, @Context MyService service);

    @AfterMapping
   default void map( @MappingTarget Target.X target, Source.ID source, @Context MyService service) {
        target.set( service.findById( source.getId() ) );
   }
 }
```

I think this is by far preferable over the proposed solution (expressions are intended to fill in stuff that MapStruct can't do). Also: relying on a generated field name is probably not the safest thing to do with future extensions in mind.

Therefore I would propose to close this issue.

**Comment by yelhouti** [comment]
@sjaakd thsi doesn't solve the problem as now, if you want to call `map` you need to pass the context as a parameter, clearly not very handy...

**Comment by yelhouti** [comment]
@filiphr I will gladly add a PR for this if I know what you guys expect, one choice could be:
if a method contains `@context` (ex: `MyService` in the first map method below) and the same service is present in `uses`, have the method superchaged using the Autowired/injected `this.MyService`
the resulting implementation would look like
```
Target map( Source source, MyService myService) {...}

Target map( Source source) {
    return map(source, this.myService)
}
```
We can di the same for the afterMapping method but I don't know if it would be usefull.

**Comment by filiphr** [comment]
@yelhouti you know that you can make the mapper an `abstract` class and autowire what you need in that

**Comment by mschielmann** [comment]
Depending on the context, but I guess some may find this useful:
```
@Mapping(target = "somethingMappedInAutowiredMapper", source = ".")
```
As mentioned, `autowire` works only for target / source mapping, and in my concrete scenario this helped. You can use the whole mapped object as a source using `source="."`.

**Comment by sachinPramodya** [comment]
When using below abstract class got this error `java.lang.NullPointerException: null
	at com.presto.salesApp.modules.inventory_new.stock_mapping.mappers.StockMappingMapperRepo.getStockItem(StockMappingMapperRepo.java:43) ~[classes/:na]
`
any help will be appreciated 

@Mapper(componentModel = "spring")
public abstract class StockMappingMapperRepo {

    @Autowired
    private StockItemRepository stockItemRepository;

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mappings({
            @Mapping(target = "id", source = "id"),
            @Mapping(target = "primaryLocationId", source = "primaryLocationId"),
            @Mapping(target = "productId", source = "productId"),
            @Mapping(target = "stockItemId", source = "stockItemId",qualifiedByName = "getStockItem"),
            @Mapping(target = "outputMultiplier", source = "outputMultiplier"),
            @Mapping(target = "version", source = "version"),
            @Mapping(target = "created", ignore = true),
            @Mapping(target = "updated", ignore = true)
    })
   public abstract StockMapping convertFromResponseToModel(
            StockMappingPatchRequest stockMappingPatchRequest,
            @MappingTarget StockMapping stockMapping
    );

    @Named(value = "getStockItem")
    public StockItem getStockItem(UUID stockItem) {
        return stockItemRepository.findById(stockItem).get();
    }
}

**Comment by fascynacja** [comment]
is there any new solution for this issue?
