### ISSUE TITLE
Weird variable names generated for Issue289Test

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#941]
For some reason some private variables do have three underscores at the end of the name.

**Comment by filiphr** [comment]
A suggestion from @sjaakd in PR #979:

>I was thinking, reading the code.. I see a lot of variable names like string, string_, string__, etc.. Perhaps we should start to use number suffixes.. So string_001, string_002 when we generate save variable names..

My suggestion and @agudian is to not use the underscore and the leading zeros, basically having: `string1, string2`.

Code snippet from @agudian for improving the naming (be more smart when naming the private variables:
```java
// should be named 'children'
        List<NodeDTO> list = nodeListToNodeDTOList( node.getChildren() ); 
        if ( list != null ) {
            nodeDTO.setChildren( list );
        }
// should be named 'attributes'
        List<AttributeDTO> list_ = attributeListToAttributeDTOList( node.getAttributes() );
        if ( list_ != null ) {
            nodeDTO.setAttributes( list_ );
        }
```

In `NodeMapperWithContextImpl`:

```java
protected AttributeDTO attributeToAttributeDTO(Attribute attribute) {
        AttributeDTO target = NodeMapperContext.getInstance( attribute, AttributeDTO.class );
        if ( target != null ) {
            return target;
        }

        if ( attribute == null ) {
            return null;
        }

        AttributeDTO attributeDTO_ = new AttributeDTO();

        NodeMapperContext.setInstance( attribute, attributeDTO_ );

        attributeDTO_.setNode( nodeToNodeDTO( attribute.getNode() ) );
        attributeDTO_.setName( attribute.getName() );
        attributeDTO_.setValue( attribute.getValue() );

        NodeMapperContext.cleanup();

        return attributeDTO_;
    }
```
And the `attributeDTO` is not conflicting.

**Comment by sjaakd** [comment]
Not necessarily with the underscore before the number
Idea here is to make it a bit more easy parseable. You simply look for the last occurrence of an _.. If there is not, you add it followed by a sequence number 1. If there is, you try to parse the number behind it. If no success, you still add _, assuming there was an _ initially. If success, you take the number and increase it & replace the number.

**Comment by agudian** [comment]
```java
    public static String getSaveVariableName(String name, Collection<String> existingVariableNames) {
        name = decapitalize( sanitizeIdentifierName( name ) );

        Set<String> conflictingNames = new HashSet<String>( KEYWORDS );
        conflictingNames.addAll( existingVariableNames );

        int c = 1;
        String seperator = Character.isDigit( name.charAt( name.length() - 1 ) ) ? "_" : "";
        while ( conflictingNames.contains( name + seperator + c ) ) {
            c++;
        }

        return name + seperator + c;
    }
```

😁

**Comment by filiphr** [comment]
I like your implementation @agudian, basically if the name ends with a digit we add an underscore and then the sequence number, otherwise we just add the sequence number.

**Comment by sjaakd** [comment]
:). We should probably add the name to the set once we checked it was not in the set of existingVariableNames.. 

And.. What if the variable already contained a number.. E.g. `MyType123`?

**Comment by filiphr** [comment]
> We should probably add the name to the set once we checked it was not in the set of existingVariableNames

Earlier when I was checking something, this is exactly what I wanted to check, which class should be responsible for adding the new variable name to the `existingVariableNames`. I am not sure how that is done now, but I like the idea of @sjaakd.

**Comment by sjaakd** [comment]
I missed this as well previously, leading to duplicate variables.
