### ISSUE TITLE
Documentation: default methods

### ISSUE THREAD

**Issue by dgruntz** [mapstruct/mapstruct#945]
I just read the (newest) documentation and there you describe in chapter "3.2. Generating mappers from abstract classes" that abstract classes can be used to add specific mappings from one type to another for those cases which can't be generated by MapStruct. 

However, I have not read in the documentation (but it seems to be possible) that such methods could also be provided as default methods to the mapper interface. The example provided in chapter 3.2 would then look as follows:

    @Mapper
    public interface CarMapper {

        @Mappings({...})
        CarDto carToCarDto(Car car);

        default PersonDto personToPersonDto(Person person) {
            //hand-written mapping logic
        }
    }

**Comment by gunnarmorling** [comment]
Hi, did you try to use a default method? It may work indeed (never tried it
myself). If it does, would you mind sending an update for the reference
guide? Thanks!

**Comment by dgruntz** [comment]
Yes I tried it and I was surprised that it worked. But I also found an example on [mapstruct-users](https://groups.google.com/forum/?fromgroups#!searchin/mapstruct-users/default%7Csort:relevance/mapstruct-users/PqB-g1SBTPg/cgeaNU-4CgAJ) and therefore I assumed that this is a known feature.

I could add a section or extend an existing section, but it was not clear to me whether it should be part of Section 3.2 (Generating mappers from abstract classes) or whether a new section should be written or whether it should be added at the end of Section 3.1. 

If I hear no objection, then I will add a remark to chapter 3.2, as an interface with default methods is comparable to an abstract class.

**Comment by gunnarmorling** [comment]
Adding a note and short example to 3.2 seems good. Maybe we also could
rename that section, I don't have a good idea right now, though.

**Comment by dgruntz** [comment]
Just added https://github.com/mapstruct/mapstruct/pull/947. I leave it up to you to close this issue.

**Comment by gunnarmorling** [comment]
Merged all your doc PRs, @dgruntz. Thanks a lot! I've changed the commit messages to refer to this issue and added one more commit to clarify that default methods may only be used on Java 8.

**Comment by dgruntz** [comment]
ok fine, and thanks for this nice project.
