### ISSUE TITLE
Missing Type import for Map<k,v> when providing custom mapper

### ISSUE THREAD

**Issue by simontrudeau** [mapstruct/mapstruct#955]
When declaring a mapper like so using MapStruct version 1.1.0.CR2:

Mapper:
```java
@Mapper(uses = {personMapper.class})
public interface CarMapper {
	SuperCar mapCar(Car source, @MappingTarget SuperCar destination);
}
```

Custom Mapper
```java
@Component
public class EslUserCustomFieldMapMergeMapper {

public Map<String,Person> merge(Map<String,Person> source, @MappingTarget Map<String,Person> destination){
		source.entrySet().forEach(entry -> destination.put(entry.getKey(), entry.getValue()));
		return destination;
	}
}
```

Car containing a Map of Person
```java
public class Car {
    private Map<String, Person> persons = new HashMap<String, Person>();
...
}
```

The generate code is missing import for type `Person`. The generate code (`CarMapperImpl.java`) contains the following and is missing *import* for the type `Person`, thus it doesn't compile:
```java
...
if ( destination.getPersons() == null ) {
            destination.setPersons( new HashMap<String, Person>() );
        }
carMapper.merge( source.getPersons(), destination.getPersons() );
...
```

Is it possible to add a hint or something so that the generator knows to add the import for the type `Person`?

**Comment by filiphr** [comment]
If you add `@Mapper( imports = Person.class )`, mapstruct will add the import to mapper class and it will work.

**Comment by simontrudeau** [comment]
It works, thank you.

**Comment by sjaakd** [comment]
But.. is still an issue :smile:

**Comment by sjaakd** [comment]
Fixed.

**Comment by gunnarmorling** [comment]
@sjaakd, @agudian, shouldn't this be assigned to the 1.1.0.Final release?

**Comment by gunnarmorling** [comment]
Assigned that milestone. When closing an issue please make always sure a milestone is assigned. Thanks! Same for #954.

**Comment by sjaakd** [comment]
> Assigned that milestone. When closing an issue please make always sure a milestone is assigned. Thanks! Same for #954.

Ok.. Forgot.

**Comment by gunnarmorling** [comment]
No problem. Just was wondering whether there was any intention behind it :)
