### ISSUE TITLE
Add support to Java 8 Streams

### ISSUE THREAD

**Issue by svpace** [mapstruct/mapstruct#962]
Add support for stream attributes. Allowing mappings like:
``
class From {
    public Stream<Foo> getFoos() {...}
}
``
to
``
class To {
    public void setBars(Stream<Bar> bars)  {...}
}
``
or even
``
class To {
    public void setBars(Set<Bar> bars)  {...}
}
``
by applying the proper Collector

**Comment by agudian** [comment]
Hmm, interesting! It would probably make sense to generate the fluent kind of mapping with method references, such as `to.setBars( from.getFoos().map( this::toBar ) );`...
The Stream to Collection conversion could be done by adding appropriate built-in Conversions (again, for in-line usage).
Especially that last part shouldn't be too hard to get started with (in the code it's somehow similar to our numeric conversions). Would you care to try it and prepare a PR?

**Comment by filiphr** [comment]
Support for this was added in #964
