### ISSUE TITLE
Documentation incorrectly refers to NullValueMappingStrategy in chapter 9.5

### ISSUE THREAD

**Issue by ruszki** [mapstruct/mapstruct#965]
In the documentation the chapter named "Controlling checking result for 'null' properties in bean mapping" contains incorrect references. The text refers to _NullValueMappingStrategy.ON_IMPLICIT_CONVERSION_ and _NullValueMappingStrategy.ALWAYS_. These should be _NullValueCheckStrategy.CONVERSION_  and _NullValueCheckStrategy.ALWAYS_, respectively.

Later in the same chapter there is a paragraph about @_Mapper#nullValueMappingStrategy_ and @_MappingConfig#nullValueMappingStrategy_. These should be @_Mapper#nullValueCheckStrategy_ and @_MapperConfig#nullValueCheckStrategy_, respectively.

**Comment by filiphr** [comment]
Thanks for reporting the incorrect reference @ruszki. We have fixed it
