### ISSUE TITLE
Detect strange enters and spaces in generated code such as prior to #968

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#970]
See generated code due to `SetterWrapperForColllectionsAndMaps` prior to #968. Is it possible that Checkstyle detects such generated code formatting problems??

**Comment by sjaakd** [comment]
@filiphr : I guess that this is solved by the fixtures?

**Comment by filiphr** [comment]
Yes with #1028 we can easily add any fixture and have a fixed test for them.

I will close this one
