### ISSUE TITLE
How to nest mappers with multiple parameters

### ISSUE THREAD

**Issue by twentylemon** [mapstruct/mapstruct#974]
I have some mappers like the following, converting a legacy time to a new type. The conversion requires some additional metadata.

```java
@Mapper(uses = NestedMapper.class)
public interface SomeTypeMapper {
    @Mapping/* copy fields from legacy */
    @Mapping(target = "nestedList", source = "legacy.nestedList")
    SomeType convert(Legacy legacy, Metadata metadata);
}

@Mapper
public interface NestedMapper {
    @Mapping/* convert using nestedLegacy and metadata */
    NestedType convert(NestedLegacy nestedLegacy, Metadata metadata);
}
```

I get a compile time error, in reference to SomeTypeMapper.convert
 No implementation can be generated for this method. Found no method nor implicit conversion for mapping source element type into target element type.

I expected the metadata from SomeTypeMapper::convert would be passed to NestedMapper::convert -- is it possible to have this behaviour?

**Comment by sjaakd** [comment]
That's not how it works. Both `legacy` and `metadata` are considered source from which to construct the target `SomeType`. See chapter 3.3 of our reference guide (several source parameters).

IIUC It seems that what you want is to pass along state / config information in `Metadata` right? That has been discussed in the past. Not sure whether we have an issue for that.

**Comment by twentylemon** [comment]
Thanks for the quick response. Yes, I wanted to pass along the `metadata` to the other mapper.

Your answer makes sense -- `metadata` isn't actually needed to create `SomeType`, it is only needed for `NestedType`. Perhaps the best solution here is to write `SomeTypeMapper::convert` manually in an abstract class.

**Comment by sjaakd** [comment]
No problem.. I'll open up a new issue to pass state information somehow. We've discussed this earlier and I expected an issue for that. See  #975. I'll proceed to close this one.
