### ISSUE TITLE
Open a way to pass state information to subsequent mappings

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#975]
E.g. by a parameter and (new) annotation like: `@PassAsState` or something like that.

**Comment by agudian** [comment]
How about `@MappingContext`? That's what we pondered with in the issue and PR regarding the handling of cycles in graph structures. Then that would require finishing up PR #911 (handling return values from before/after mapping methods) and allowing this state object to be passed in property mapping methods and those before/after methods.

**Comment by sjaakd** [comment]
`@MappingContext` is perhaps a bit confusing. Its sole purpose is to let (generated)mapping coe ignore it and just happily pass it along. Perhaps.... `@ContextParameter`

Just a thought we should make it an annotation to use directly or which can act as a marker to stick to other annotations.

So:

`A map(B param1, @ContextParameter1 C param2, @ContextParameter2 D param3)` that could call  method which signature: `A1 map(B1 param1, @ContextParameter1 C param2, @ContextParameter2 D param3)` this way:

```java
A map(B param1, @ContextParameter1 C param2, @ContextParameter2 D param3) {

   A a = new A();
   a.set1( map( param1, param2, param3 )  );
   ..
   return a;

}

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.CLASS)
@ContextParameter
public @interface ContextParameter1 {
}

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.CLASS)
@ContextParameter
public @interface ContextParameter2 {
}

```

WDYT?

**Comment by agudian** [comment]
A meta-annotation might just be a bit over-engineered here, IMHO. Using just one annotation should do the trick as well and keeps the mappers readable.
I guess we should take some time to come up with a good name, as obviously you found `@MappingContext` confusing and I think the *Parameter* in `@ContextParameter` is a bit stating the obvious (like annotating a constructor with `@Constructor` 😜).

**Comment by sjaakd** [comment]
> A meta-annotation might just be a bit over-engineered here, IMHO

That might be true :). However, I propose to have an initial annotation which might double as meta annotation in the future. The only thing needed, for now, would be specifying the proper `@Target`.. 

As for the name.. We could decide it to keep it as simple as `@Context`..

**Comment by agudian** [comment]
I'm gonna start working on this.

And how cool what it be if we would check the annotated type for methods with `@BeforeMapping` / `@AfterMapping` / `@ObjectFactory` annotations on it and support calling them on the given state/context instance? We could then provide a self-contained type that handles cycles in graphs. We could even add it to the mapstruct core, e.g. as `CyclicGraphContext` class, so users would only have to add that parameter to their mapper method(s) and pass in a fresh instance for each mapping invocation.

**Comment by sjaakd** [comment]
😄👍👍👍👍 I think they naturally belong together and should be available as such! Great initiative!!

Verstuurd vanaf mijn iPhone

**Comment by agudian** [comment]
Hum, it's more complicated than I thought - I'll have to refactor our various spots of method matching/selection and the rendering of MethodReference first to allow for such context parameters to be passed along... so it's going to take some time.

**Comment by gunnarmorling** [comment]
Initial PR is merged. Remaining to-dos:

- [ ] Doc update
- [ ] ability to pick factory methods and @BeforeMapping/@AfterMapping methods directly from @Context parameter types (as per @agudian's comment on the initial PR)
- [ ] Clarify why context parameter types must be unique

**Comment by agudian** [comment]
> Clarify why context parameter types must be unique

The reason behind it is that in the method selection the possible parameter assignments are permutated by their type assignability - for `@MappingTarget` and `@TargetType` there can be only one, for source params (the not annotated params) and the `@Context` params we only have the assignability - if that yields muliple permutations for the same method, we currently just select the first one. Perhaps we can do some more stuff there (the old code for the before/after methods also tried to match the parameter names in those cases, but I'm not so sure if we should really still do that and I didn't migrate that part in the refactoring. Should we put that back in?
As for the context params, we could use the meta-annotations Sjaak suggested above and have them being unque.

**Comment by agudian** [comment]
Alright, it's on master now.
