### ISSUE TITLE
Please use @Stateless and not @Singleton in mapstruct

### ISSUE THREAD

**Issue by GeroldSchierholz** [mapstruct/mapstruct#977]
In my oppinion mapstruct should use @Stateless annotation in favour of @Singleton because it should be safe to have more instances of mapper beans created as long as they are stateless.

Additionally and more important:
Concurrent access to @Singleton beans could cause "Concurrent Access Timeout Exceptions":

http://stackoverflow.com/a/25890389
https://docs.oracle.com/cd/E19798-01/821-1841/gipsz/index.html

If there are other reasons for your decision I would love to discuss them here.

Best Regards

Gerold

**Comment by agudian** [comment]
You can check #664, which suggested the use of `@Singleton`. Can you foresee the implications of using `@Stateless` in different jsr330-based DI implementations?
Perhaps we should add the possibility to add another or alternate annotation after all, as was proposed in the issue.

**Comment by gunnarmorling** [comment]
Do you mean `javax.ejb.Stateless`? If so, I'm no big fan of adding any dependency to EJB, I'd like to stick us to pure JSR 330 / CDI. Are you experiencing any actual issue here?

**Comment by gunnarmorling** [comment]
Hey @GeroldSchierholz any further thoughts on this? Relying on EJB is a no-no for me, so I'm inclined to close this one as "Won't fix".

**Comment by gunnarmorling** [comment]
I'm going to close this. Relying on EJB doesn't seem like the best idea.
