### ISSUE TITLE
Rephrase documentation around lifecycle methods

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#983]
See #911 

* Remove experimental character.
* Explain the three groups.
* Explain that one cannot rely on the ordering in a group.

"The methods are split up into three groups: first the before-mapping methods without mapping-target param, then the before-mapping methods with mapping-target params, and finally the after-mapping methods. In that order, and that's part of the API contract.
But if you need to rely on the order within one of those groups (e.g. two after-mapping methods), then that's the code smell I was referring to in that section. The order is kept stable in the generation, but you might get different results with different compilers when the used mapper is part of another module. But we might want to rephrase it (in a separate PR) if that wasn't clear.".

**Comment by agudian** [comment]
Thanks for creating the issue, Sjaak! I'll take care of it 🙂

**Comment by filiphr** [comment]
We also need to update the JavaDoc of the `AfterMapping` and `BeforeMapping` annotations. Currently there is this sentence:

>Only methods with return type {@code void} may be annotated with this annotation.

**Comment by agudian** [comment]
This on is done... :)
