### ISSUE TITLE
Nested Iterable to Non-Iterable mapping?

### ISSUE THREAD

**Issue by lincetto** [mapstruct/mapstruct#985]
Hi,
I found this example about Iterable to Non-Iterable mapping using Qualifier :

[https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-iterable-to-non-iterable](url)

But how to make this mapping able to map nested properties (using dot annotation)?

E.g. mapping the field xyz of first element of a collection in the source object to a plain field on the target object?

The example define a Qualifier

```
@Qualifier  
@Target(ElementType.METHOD)  
@Retention(RetentionPolicy.SOURCE)  
public @interface FirstElement {
}
```

then  define a Custom Mapper

```
public class MapperUtils {
    @FirstElement
    public <T> T first(List<T> in) {
        if (in != null && !in.isEmpty()) {
            return in.get(0);
        }
        else {
            return null;
        }
    }
}
```

and, finally, the mapping is defined as 

`	@Mapping(target = "emailaddress", source = "emails", qualifiedBy = FirstElement.class )
`

But if I would like to extract from the first element of emails collection a specific field, like I would have done with code `emails.get(0).getEmailAddress`?

**Comment by sjaakd** [comment]
@lincetto .. did you close this on purpose? Or is the issue resolved?

**Comment by lincetto** [comment]
@sjaakd, no, I didn't resolve it yet. But it is more an help request than an issue so I decided to open a question on StackOverflow. But if you can help me or point me to the solution I'll appreciate.

**Comment by sjaakd** [comment]
Hey @lincetto.. you might also want to try our [user group](https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users). Just refer to your stack-overflow issue and one of us will have a look.
