### ISSUE TITLE
Add option to generate Apache Camel's @Converter annotation into mappers and methods

### ISSUE THREAD

**Issue by Chessray** [mapstruct/mapstruct#990]
I'm working on a project where we're using both Apache Camel and Mapstruct with CDI.

Camel offers a @Converter annotation as described [here](https://camel.apache.org/type-converter.html). In order to use a generated Mapstruct-Mapper as @Converter, I have to write a "gluing class" looking somewhat like this:

    package sample.conversion;
    import org.apache.camel.Converter;
    import javax.inject.Inject;
    @Converter
    public class TypeConverter {
        @Inject
        private Mapper mapper;
        @Converter
        public TargetType toTarget(SourceType input) {
            return mapper.toTarget(input);
        }
    }

If instead the generated mapper class and and the `toTarget` method already had the @Converter annotation, I could drop this class altogether.

**Comment by filiphr** [comment]
@Chessray I haven't used Apache Camel. However, by looking at the link you send to us, more specifically **Add type converter classes at runtime**. You should be able to make it work without the "glue" class by implementing `TypeConverters` and adding the `@Converter` annotation in the not implemented method.

Will this work for you? 

We need to discuss if we want to provide a way for the user to be able to customize the annotations that we add to the mapper during `cdi` or `spring`. However, I think that MapStruct adding this annotation is not something we want to do.

**Comment by gunnarmorling** [comment]
@Chessray Could you also put the `@Converter` annotation to the mapper interface itself?

**Comment by Chessray** [comment]
I tried the following

- annotation on interface
- annotation on interface and method
- annotation on interface and method + interface extending TypeConverters
- the above + injecting Instance<TypeConverters> into my customised CamelContext and adding it to the context's TypeRegistry.

None of these worked. I think the last one failed, because the camel-cdi component changes the way that @Converters are looked up.

Anyway, so far it's looking like I'll have to stick my workaround, but it would definitely work if the generated class had the annotations.

I accept that the Camel requirement may be very specific, but in the end all I want to do is add custom annotations to the generated class and methods. Doesn't that sound like something that could be useful in other contexts as well?

**Comment by filiphr** [comment]
@Chessray I think that you should be adding the `@Converter` annotation on the interface. Again this is just by looking at their examples.

I think that you should have something like:

```java
@Mapper
public interface MyMapper extends TypeConverters {
 
    @Converter
    TargetType map(SourceType source);
}
```

```java
MyMapper mapper = ... //I think that the mapper here should be the injected one
context.getTypeConverterRegistry().addTypeConverters(mapper);
```

>I accept that the Camel requirement may be very specific, but in the end all I want to do is add custom annotations to the generated class and methods. 

Adding a custom annotation to the method works if you add the annotation in the interface/abstract method (in theory). I know for a fact that if you use `@Transactional` from spring in the interface, but not in the Implementation it will work.

>Doesn't that sound like something that could be useful in other contexts as well?

We need to discuss about the ability to add a custom annotation to the generated mapper, via some processor option or something similar. @gunnarmorling, @agudian, @sjaakd WDYT?

**Comment by gunnarmorling** [comment]
It's not the first time that the request for adding some specific annotations comes up. Supporting that somehow would be nice.

You already can do it today by adding your own `ModelElementProcessor` and hook it up via the service loader mechanism (see how the internal processors are doing it, e.g. you can take the ones for CDI or Spring support as a template and adjust them as per your needs). Use a priority which puts them rather towards the end of the processor chain. Then add your JAR with that implementation to the processor path so that MapStruct can pick it up.

 The only caveat is that this isn't a supported (public) SPI for the time being, but the risk is low as your custom processor class with be just a few lines.

**Comment by sjaakd** [comment]
> We need to discuss about the ability to add a custom annotation to the generated mapper, via some processor option or something similar. @gunnarmorling, @agudian, @sjaakd WDYT?

What are you thinking? Adding an (optional) annotation property to `@Mapper` or `@BeanMapping`, e.g.: `Class<? extends Annotation>[]includeAnnotation() default { };`? The immediate drawback I see is that you can't include any properties in that includedAnnotation if that's required.

**Comment by gunnarmorling** [comment]
Yes, lacking support for annotation attributes would be unfortunate. I could see an option that simply copies all non-MapStruct annotations from the interface to the generated implementation.

That said, @Chessray, did you declare your mapper as an abstract class instead of an interface and annotate it? This may do the trick to let the annotations be considered by CDI.

**Comment by filiphr** [comment]
>What are you thinking?

I was thinking more in the direction that someone can define it via the `ProcessorOptions` and add that as an annotation, maybe a custom `AnnotationBasedComponentModelProcessor` that will add this custom annotation to all the processors. However, your idea with the optional annotation property to `@Mapper` or the other mappings is interesting option. Yes there is a drawback that you cannot include any properties. However, they can create their custom annotations with the required properties.

**Comment by Chessray** [comment]
@gunnarmorling Just tried the abstract class - same result. :-(

**Comment by filiphr** [comment]
This could be related to #1574

**Comment by Chessray** [comment]
Hadn't seen that one yet. I'll close this request so we can use #1574 as single point of truth.
