### ISSUE TITLE
Split reference guide source into an adoc file per chapter

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#991]

**Comment by gunnarmorling** [comment]
Also re-format it to use one sentence (or line of thought for longer sentences) per line.

**Comment by Captain1653** [comment]
Maybe we steel need it. But I little didn't understand   about reformat. I have found two long lines: Chapter 10.6 and Chapter 12.2.  @gunnarmorling Is it what do you mean?
