### ISSUE TITLE
Add a switch to turn off auto-mappings

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#993]
Follows up on #60.

**Comment by gunnarmorling** [comment]
Assigned this to 1.2 as discussed during this week's hangout.

**Comment by gunnarmorling** [comment]
- [ ] Add the switch (processor option? on the mapper level?)
- [ ] Doc update

**Comment by filiphr** [comment]
Just as a note the fix for #1011 relies on the automapping to create mapping for nested target properties. We need to make sure that the switch is only applied to the correct place

**Comment by gunnarmorling** [comment]
Hey @filiphr, is this option somewhere described in the docs? I cannot seem to find any mention of it (only the SPI).

**Comment by filiphr** [comment]
@gunnarmorling not in the docs, but it is in the Javadoc [`Mapper#disableSubMappingMethodsGeneration`](http://mapstruct.org/documentation/dev/api/org/mapstruct/Mapper.html#disableSubMappingMethodsGeneration--)

**Comment by gunnarmorling** [comment]
Ok, thanks for clarifying, @filphr. I've filed https://github.com/mapstruct/mapstruct/issues/1219 for adding it to the ref guide, too.
