### ISSUE TITLE
FQN's in the generated code for arrays.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#999]
Check out generated code for unit test: `org.mapstruct.ap.test.array.ScienceMapperImpl`

**Comment by filiphr** [comment]
@sjaakd Have a look at the PR. Maybe, for the future we need to add tests that will evaluate the generated mappers (we will have to go through them and decide if they make sense first). That way we can be sure that the generated code is as someone will write it 😄

**Comment by filiphr** [comment]
Fixed via #1000
